### ISSUE TITLE
Modification: verify.glif.io - bump automatic datacap size

### ISSUE THREAD

**Issue by andrewxhill** [filecoin-project/notary-governance#100]
## Issue Description

Right now, the automatic verification for clients (via https://verify.glif.io/) provides 8GiB of datacap. Offering clients a fast track to something closer to a full sector's worth of data would be idea. This would allow projects like [Textile's Hub](https://textile.io) to give users quick instructions to start storing their data without any application fuss or needing to learn much more about verification. 

I'm not familiar with the risk level (re. network gaming) that comes with this bump, which would take the glif maintainers to weigh in. 

## Impact

- Allow most if not all small projects and experimental projects to fully test Filecoin deal making with real data. 
- Allow many critical, smaller, datasets to be added by their owners (e.g. gov portals).
- Allow sufficient DataCap for many projects to use until such time that new DataCaps can be extended to the same address. 

## Proposed Solution(s)

- Ensure glif maintainers would be open to bumping the limit. 
- Determine the right size for the bump. 32GiB seems reasonable
- See if any additional metrics could be included (e.g. age of github account), but I sense this stuff has been explored if not rejected already. 
- Add a modification to their original notary proposal that indicates the change. 
- Get started.

**Comment by andrewxhill** [comment]
just a note.

at 32GiB automatic datacap. it would take 32 fake accounts to generate a TiB of bad deals. or 32,768 fake github accounts to generate a PiB of bad deals.

**Comment by andrewxhill** [comment]
@Schwartz10 i'm interested in pushing this proposal forward but there are a couple of todos/unknowns. some context, i'm pushing this change purely from a fil+ usability standpoint, I haven't put a lot of thought into the impacts of this change on gaming etc. outstanding questions.

1. would you be open to making the change on your end?
2. if so, what do you think are the downsides of such a change?
3. are there any additional mitigation strategies we could take for those?
4. what is your executive assessment of the pro/con of such a change?
5. how does the datacap extension on same address FIP play into this? does it make it a moot point?

for 3, some ideas could include a tiered datacap based on github account age, etc.

**Comment by Schwartz10** [comment]
@andrewxhill thanks for tagging me! 

If bumping the datacap per grant is something that benefits the community, we are certainly open to raising the amount. The change would be very easy for us to make. Of course, it places a bit more pressure on our security setup, but I'm fairly confident at this point in our security. These are the rules:

- The verifier grants [amount] of datacap to requesters 1 time every 30 days
- The verifier makes sure the GitHub account of the user is >180 days old
- The verifier has a failsafe mechanism in case of any hacks - it has an internal (configurable) "counter" that is currently set to 50 allocations. If someone were to hack the faucet, the most allocations they could get is up to the counter. We could lower this to something like 10 until we feel comfortable raising it again.
- The verifier is capable of blocking certain FIL addresses if they try to game the system
- The verifier alerts us when people try to game the system, we can shut it off right away if something fishy is up

One thing to consider - we have been flagged by the GitHub security team in the past - the space race faucet drew a lot of attention and thousands of fake GitHub accounts were created. We cannot let that happen again or we will be shut off from GitHub's API. Therefore, we want to make sure that the datacap amount is not _too_ big as to incentivize fake account creation. I.e. - it should be easier for someone to request datacap from somewhere else than it is to try and game the Glif verifier system. 

Other than that, I think any downsides are more on the crypto-econ side - how does providing more datacap to the FIL economy effect all other things? These are questions my team and I do not have much visibility or expertise in yet, so would have to defer to someone more knowledgeable.

**Comment by andrewxhill** [comment]
thanks jonathan. re. the 180d limit. what about the idea of adding a tiered datacap? 8Gib for 180d and 32Gib for 720d or something well ahead of the age of glif? i'm imagining an uptick in fake requests once we are 180ish days past the launch of glif :D. for that, you might even consider making the 180d limit dynamic (e.g. days since mainnet).

cc @jnthnvctr re. `Other than that, I think any downsides are more on the crypto-econ side - how does providing more datacap to the FIL economy effect all other things? These are questions my team and I do not have much visibility or expertise in yet, so would have to defer to someone more knowledgeable.` i'd love your thoughts too.

**Comment by Schwartz10** [comment]
>  i'm imagining an uptick in fake requests once we are 180ish days past the launch of glif :D

Ha, right...

I think what you're proposing sounds reasonable. Although we do have some tentative plans right now to make a more robust verification system that reduces reliance on Github and could pave way for some more flexibility in granting datacap like you're talking about. 

A user would basically configure a decentralized identity with verifiable credentials (including GitHub, Twitter...etc). The more verified credentials a user has, the more data cap they could get. Of course, we'd still have to check the credentials they provide meet some minimum baseline rules. This way we can get a better "full picture" sense of who a user is. Surprisingly enough, a decent amount of folks don't even have GitHub! So this seems like it could provide greater accessibility to those diverse audience groups.

**Comment by dkkapur** [comment]
In line with the original proposal and the conversations in the past notary governance calls, I'd like to propose that we proceed with at least the suggested change of bumping up the automated verifier at verify.glif.io to 32GiB. Thanks @andrewxhill for proposing. @Schwartz10 if there are any risks with this, please do share.

**Comment by andrewxhill** [comment]
So the latest thinking is:

1. Go. We should make this change @Schwartz10 
2. Ideally, just add an amendment to your initial notary application indicating the change.
3. I was thinking, in that amendment, maybe we should plan on an initial testing phase (e.g. 1, 2, or 3 months) with a planned review to see what level of manipulation (if any) we see after the change? I'm not sure how feasible this is.

**Comment by Schwartz10** [comment]
Sure I can add a comment on the initial notary application later today.

Re your point 3 @andrewxhill - one thing we could do is bring down the "throttle" we have to 10 - so that scripted attacks can't possibly get more than 320 GiB (10 allocations). Even so, we've battled against many scripting attacks with this backend during the space race (its the same logic as the faucet).

The only thing here is the fake github account creation, but in a few months we'll be well prepared to get off GitHub if we need to. We have another identity solution in the works.

**Comment by Schwartz10** [comment]
@andrewxhill @dkkapur this change has been pushed to prod. We can close this issue.
