### ISSUE TITLE
v5 Notary Allocator Application: PiKNiK

### ISSUE THREAD

**Issue by jamerduhgamer** [filecoin-project/notary-governance#1007]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): PiKNiK FIL+
2. Organization Name: PiKNiK
3. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1knvu3opxqmavyh73hmu3z53q2skxxdp6zwqjnzy
4. Country of Operation (Where your organization is legally based): United States
5. Region of Operation (What region will you serve?): North America primarily but open to all regions
6. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Manual
7. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 50 PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
Hi @jamerduhgamer 
Wanted to let you know this application has been received. Also verifying you have completed and submitted the Airtable form with your detailed Allocator plan - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by Filplus-govteam** [comment]
Providing the information shared in Application for Public Review/Comment.

Basic Info

**1. Pathway Name:**
PiKNiK FIL+

**2. Organization:**
PiKNiK

**3. Allocator's On-chain addresss:**
f1knvu3opxqmavyh73hmu3z53q2skxxdp6zwqjnzy

**4. Country of Operation:**
United States

**5. Region(s) of operation:**
North America,Europe,Africa ,Asia minus GCR,Greater China,Oceania,Japan,South America

**6. Type of allocator: What is your overall diligence process? Automated (programmatic), Market-based, or Manual (human-in-the-loop at some phase). Initial allocations to these pathways will be capped.**
Manual

**7. Amount of DataCap Requested for allocator for 12 months:**
50 PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?**
No. We will continue following what we have done in the past and use the same due diligence process as previous notary rounds.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack. Additionally, I will adhere to all local & regional laws & regulations that may relate to my role as a business partner, organization, notary, or other operating entity.  You can read the Filecoin Code of Conduct here: https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md**
Acknowledgment: Acknowledge

**Comment by Filplus-govteam** [comment]
Client Diligence

**10. Who are your target clients?**
Individuals learning about Filecoin,Small-scale developers or data owners,Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.**
PiKNiK will do its due diligence in checking which SPs that the client plans on sending the DataCap. Ideally they are a notable contributing member in the Filecoin ecosystem or have some other reputational sound background.
Client Diligence Process
	•	Check if the client has any miner actors and if they do, use blockchain explorers like filfox.info and the Starboard reputation system to see if they are knowledgeable about Lotus deal making and sealing.
	•	Check the client's social media, LinkedIn, and Filecoin Slack involvement for their reputability.
	•	Check if the client has participated in any community events.
Other methods to evaluate legitimacy includes the domain of the email the Github user communicates from, the website domain age, searching the originality of texts, and reviewing the dataset sample with respect to the claimed size and dataset description.

**12. Please specify how many questions you'll ask, and provide a brief overview of the questions.**
Several questions depending on the client reputation and dataset. Could be less questions for more reputable clients and more questions for new unknown entities.
	•	What SPs are you working with?
	•	Where are those SPs located?
	•	How are you preparing the data to be stored?
	•	Do you have any public websites or social media?

**13. Will you use a 3rd-party "Know your client" (KYC) service?**
No

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral)**
Any client can apply

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?**
By using the spreadsheet that has been used for previous rounds to track how much datacap is going to a client.

**Comment by Filplus-govteam** [comment]
Data Diligence

**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmitting, or accessing of data.**
Acknowledgement: Acknowledge

**17. What type(s) of data would be applicable for your pathway?**
Public Open Dataset (Research/Non-Profit),Public Open Commercial/Enterprise,Private Commercial/Enterprise,Private Non-Profit/Social Impact

**18. How will you verify a client's data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?**
We will check the client's publicly available websites, social media or other information to see if it makes sense for the client to have provenance over the claim data. If anything is suspicious, we will meet with the client in a meeting to confirm. We will not use a 3rd-party KYB service.

**19. How will you ensure the data meets local & regional legal requirements?**
By requiring a list of SPs and regions of operation for those SPs

**20. What types of data preparation will you support or require?**
We can provide data prep services and sharding but will not have any requirements for the client in regards to data prep.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?**
If we are the data preparers then there will be no issues with this. If we are not doing the data prep then we will require the data preparing entity to send us some samples of commands and logs used to prep the data and some sample files if needed.

**Comment by Filplus-govteam** [comment]
Data Distribution

**22. How many replicas will you require to meet programmatic requirements for distribution?**
2+

**23. What geographic or regional distribution will you require?**
2 or more physical locations. 2 or more separate geopolitical regions. We will not exclude any geopolitical regions besides the regions that is illegal for a United States entity to work with.

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?**
2+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?**
Yes unless the client explains a situation where they will not be having equal percentage distribution. No we will not as we experienced firsthand how difficult it is to stick to a

**26. What tooling will you use to verify client deal-making distribution?**
CID checker bot works great so I hope that will continue to be available

**27. How will clients meet SP distribution requirements?**
Yes if we are managing the data distribution.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?**
No, SPs should be located where they say they are storing the data geographically.

**Comment by Filplus-govteam** [comment]
Datacap Allocation Strategy

**29. Will you use standardized DataCap allocations to clients?**
No, client specific

**30. Allocation Tranche Schedule to clients:**
First: 25% of requested datacap Second: 25% of requested datacap Third: 25% of requested datacap Fourth: 25% of requested datacap Max per client overall: Client and dataset specific

**31. Will you use programmatic or software based allocations?**
No, manually calculated & determined

**32. What tooling will you use to construct messages and send allocations to clients?**
The filplus.fil.org website works great and hope that will continue to be available.

**33. Describe the process for granting additional DataCap to previously verified clients.**
The current subsequent allocation bot works great and hope it will continue to be available. The only issue with subsequent allocations were the notaries response time and not the bot.

**Comment by Filplus-govteam** [comment]
Tools and Bookkeeping

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • dispute discussion & resolution • community updates & comms**
• client discoverability & applications - spreadsheet tracking and meetings • due diligence & investigation - publicly available information and meetings • bookkeeping - spreadsheet • on-chain message construction - current filplus.fil.org website • client deal-making behavior - current CID checker bot • tracking overall allocator health - current CID checker bot • dispute discussion & resolution - GitHub notary governance repo • community updates & comms - Slack and GitHub

**35. Will you use open-source tooling from the Fil+ team?**
GitHub repo and Slack for community updates and communications with the client. Google spreadsheet for tracking, recording and history bookkeeping purposes. The various bots and automations built into the filecoin-plus-large-datasets GitHub repo.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?**
GitHub and our internal and external spreadsheets.
External - https://docs.google.com/spreadsheets/d/1ZgzkpAx5uQsdcVEk11W2NvDkyKKwo4YGEnyzKzaeMWE/edit#gid=2048864629

**Comment by Filplus-govteam** [comment]
Risk Mitigation, Auditing, Compliance

**37. Describe your proposed compliance check mechanisms for your own clients.**
We will track the datacap distribution using the CID checker bot. As long as the client has good communication of any blockers or issues, we will be understanding of their demographic choices and time metrics. Trust evaluations are done at the start and checked between datacap tranche allocations.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.**
Disputes will be handled by communicating with the client and SPs. If needed, we will open an issue on the notary governance GitHub repo.

**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.**
If needed we will announce updates via GitHub issues in the notary governance repo.

**40. How long will you allow the community to provide feedback before implementing changes?**
We are always open to community feedback and will implement changes if the feedback makes logical sense to our team.
We can continue use the notary governance GitHub repo to engage with the community and monitor the feedback there.

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?**
We use a multisig that has multiple signers with a threshold >2. Only these signers will have administrative and signatory rights after approval to sign has reached a consensus and approved.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?**
We will not be deploying smart contracts.

**Comment by Filplus-govteam** [comment]
Monetization

**43. Outline your monetization models for the services you provide as a notary allocator pathway.**
We will assist clients with finding connecting them with partners to obtain collateral for staking but will not provide that ourselves.
Application review, data prep, data distribution are all part of our Filecoin service and we will discuss that with the client and will not be sharing any specific price points for our end-to-end services.
Auditing is part of the FIL+ ecosystem and will continue to be done at no cost.

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.**
We are a Delware LLC and have Infrastructure and Filecoin services.

**45. Where will accounting for fees be maintained?**
We will not share any information on staking and burning or monetization of our services unless needed for a specific situation.

**Comment by Filplus-govteam** [comment]
Past Experience, Affiliations, Reputation

**46. If you've received DataCap allocation privileges before, please link to prior notary applications.**
[filecoin-project/notary-governance#438](https://github.com/filecoin-project/notary-governance/issues/438), filecoin-project/notary-governance#776

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.**
We are an SP and have connected with a lot of SPs through hosting ESPA.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?**
We should have a steady stream of small to medium sized clients (1 - 5 PiBs) and we expect a few large clients throughout the year (5+ PiBs). We have existing clients and an onboarding funnel

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2v3zv6qw2w4gslejsqmetpmelcupdnecsktdcxcq
#### Datacap Allocated
> 5PiB
