### ISSUE TITLE
Discussion Points for Governance Call - **March 16 2300UTC**

### ISSUE THREAD

**Issue by KwrayPL** [filecoin-project/notary-governance#101]
Our next Governance will take place on **March 16 2300UTC**.

To ensure we are covering the most pressing topics and questions, opening this issue early to collect your input on anything that should be added to the agenda. Please add items into the comments below to ensure they are included on the next call.

Zoom details:
https://protocol.zoom.us/j/93414028246
Passcode: 554538

Community Calendar 
https://calendar.google.com/calendar/u/1?cid=Y19rMWdrZm9vbTE3ZzBqOGM2YmFtNnVmNDNqMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t

**Comment by jnthnvctr** [comment]
https://github.com/filecoin-project/notary-governance/issues/94

**Comment by NSC-FIL** [comment]
https://github.com/filecoin-project/lotus/discussions/5781

**Comment by dkkapur** [comment]
#98

**Comment by andrewxhill** [comment]
I'd propose to remove all notaries who have all of these properties: 

1. Planned to accept applications via plus.fil.org
2. Have not granted a single datacap to a client.
3. Have an average response time to plus.fil.org applications of greater than 14 days.

It sets a higher bar for new notaries to onboard quickly.

**Comment by andrewxhill** [comment]
that's an arbitrary number, i'm not set on 14days being the duration, but some clear criteria.

**Comment by andrewxhill** [comment]
https://github.com/filecoin-project/notary-governance/issues/104

**Comment by Fatman13** [comment]
Will the recording be uploaded to YouTube?

**Comment by dkkapur** [comment]
@Fatman13 Yes!

**Comment by dkkapur** [comment]
Youtube recording for this session: https://www.youtube.com/watch?v=sjct8dcKAaY&list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx
