### ISSUE TITLE
V5 Notary Allocator Application: Pluskit

### ISSUE THREAD

**Issue by PluskitOfficial** [filecoin-project/notary-governance#1016]
1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): Pluskit
2. Organization Name: Pluskit
3. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
4. Country of Operation (Where your organization is legally based): HK, GCN
5. Region of Operation (What region will you serve?): GCN/Asia minus GCN
6. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Manual
7. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 200 PiB

**Comment by Kevin-FF-USA** [comment]
Hi @PluskitOfficial 

Wanted to let you know this application has been received. Also verifying you have submitted the Airtable form with your detailed Allocator plan - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by Filplus-govteam** [comment]
Providing the information shared in Application for Public Review/Comment.

Basic Info

**1. Pathway Name:**
Pluskit

**2. Organization:**
Wellhealth International Limited.

**3. Allocator's On-chain addresss:**
f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka

**4. Country of Operation:**
HK, GCN

**5. Region(s) of operation:**
Asia minus GCR,Greater China

**6. Type of allocator: What is your overall diligence process? Automated (programmatic), Market-based, or Manual (human-in-the-loop at some phase). Initial allocations to these pathways will be capped.**
Manual

**7. Amount of DataCap Requested for allocator for 12 months:**
200PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?**
We will manually make a plan for the distribution pathway and distinguish the subjects who have applied and those who have not applied, so as to avoid duplication of work as much as possible to improve work efficiency. In addition, we have known a large number of data and industry tools to assist us in better distribution.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack. Additionally, I will adhere to all local & regional laws & regulations that may relate to my role as a business partner, organization, notary, or other operating entity. You can read the Filecoin Code of Conduct here: https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md**
Acknowledgment: Acknowledge

**Comment by Filplus-govteam** [comment]
Client Diligence 

**10. Who are your target clients?**
Individuals learning about Filecoin,Small-scale developers or data owners,Enterprise Data Clients,Other (specified above)

**11. Describe in as much detail as possible how you will perform due diligence on clients.**
We prepare to do as follows:
	•	First of all, we will designate specialized personnel and develop standardized audit procedures and fixed working hours.
	•	Upon receipt of the application, we will ask clients to answer fixed questions, and vet the authenticity of the clients' identity, the amount of the clients' real data, the openness of the data, and the storage plan of the clients' data (such as how many nodes exist, how many copies will be stored, and which areas will be stored) according to the key questions.
	•	In addition to the information answered by clients, we will also take the initiative to search the relevant information of the client online to verify the real situation of the clients. Specifically: a.Subject Authenticity We will ask clients to send the subject certification documents by email, and ask the clients to send the verification email to us by official email address. If needed, we'll post the application on slack to get more community members to verify the subject's authenticity. b. Real Data Volume We will ask the clients to explain the data form and corresponding quantity ratio, and also ask them to show a screenshot of the current data volume. c. Storage Plan We will force clients to specify storage locations and nodes prior to actual allocation.
	•	At present, we are also planning to develop a new automated tool, which can realize the input of the client's business name and output of a comprehensive authenticity assessment score. It will help us judge the enterprise authenticity and improve work efficiency.
	•	This is our current overall approval process: https://github.com/PluskitOfficial/Pluskit/blob/main/image.png

**12. Please specify how many questions you'll ask, and provide a brief overview of the questions.**
We plan to ask the following questions:
 A. Are you an individual or a business/organization? If an individual, please specify the name, date of birth, and nationality; if a company/organization, please specify the company name, registration time, and registration area. At the same time, please provide the corresponding supporting documents (individuals provide ID cards, enterprises/organizations provide licenses, which can be sent by E-mail).   B. What is your industry? What data will be stored? How much do you plan to store? Can the data be made public (if not, are we allowed to conduct random checks at any time?) 
C .Please share information and relevant supporting documents or links that illustrate your industry status. 4.Did you get any honors? Please provide relevant supporting documents or links. 5.Please provide your social media account and indicate the number of followers. 6.Please describe the duration of your involvement in your industry and give a brief description of your industry. 7.Please specify the storage location, miner ID and storage proportion of your data to be stored. We require any data to be stored on the same node no more than 30% of the same batch of DataCap acquisitions. 8.If you get a DataCap, do you agree to send the storage record back here within 15 days of storage? 9.Did you get a DataCap? If yes, please attach all application links and inform the current remaining amount. We have made a form to record user information.The form is as follows. https://github.com/PluskitOfficial/Pluskit/blob/main/Clients%20Onboarding%20Records.xlsx

**13. Will you use a 3rd-party "Know your client" (KYC) service?**
We recognize and will use official tools such as Toggle, uqudo, linkdin, twitter, facebook and medium to verify clients. That includes the certification and operation of the business, the employment history of the individual, and checking updates through website, social media and portal website to determine whether the business is still functioning.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral)**
No. We will open applications to users in all fields.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?**
We will clarify the client's usage speed in advance and ask the client to remind us when he has completed 50% of datacap allocated. We will check how much the client has used before each datacap request, and maintain at least once a week to verify the client's datacap usage, and provide guidance and help.

**Comment by Filplus-govteam** [comment]
Data Diligence

**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmitting, or accessing of data.**
Acknowledgement: Acknowledge

**17. What type(s) of data would be applicable for your pathway?**
Public Open Dataset (Research/Non-Profit),Private Commercial/Enterprise,Public Open Commercial/Enterprise,Private Non-Profit/Social Impact

**18. How will you verify a client's data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?**
We will verify their ownership by verifying the authenticity of the client's subject and the correspondence between the data and the client. The general process is as follows. 1.Check the authenticity of the subject: We will use 3rd-party KYB toolings to check the authenticity of the enterprise. 2.Judge the correspondence between the data and the client: We will require clients to provide informations aboout their business and data to judge the correspondence. 3.Require commitment: We'll requires them to commit to the ownership and storage rights of the data. 4.Punishment mechanism: Once the above information is found false, it will be given a period of time or permanent punishment that is not allowed to apply, depending on the situation. And we will take back their unused DataCa. When doing KYB, we'll generally use the following three tools/services: 1.For global enterprise information query. WikiGlobal：www.wikiglobal.com x315：https://www.x315.cn/searchworld 2.For some countries's information query. ①China -National enterprise credit information Publicity system: http://gsxt.saic.gov.cn/ -Aiqicha: https://aiqicha.baidu.com/ -Tianyancha: https://www.tianyancha.com/ -Hong Kong companies registry comprehensive consulting system: http://www.icris.cr.gov.hk/csci/ -Department of Commerce, Ministry of Economic Affairs, Website: http://gcis.nat.gov.tw/ ②USA -Wysk B2B Hub：http://www.wysk.com/index/ -（Delaware）State of Delaware：https://delecorp.delaware.gov/ -Secretary of States Business Entity Search ③Singapore -ACRA Website：https://www.acra.gov.sg/home/ ④UK -BVI Financial services Commission：http://www.bvifsc.vg/en-gb/regulatedentities.aspx -GOV.UK：https://www.gov.uk/ ⑤Australia -Australia Bussiness Register：http://abr.business.gov.au/ ⑥India -Ministry of corporate Affairs：http://www.mca.gov.in/ ⑦Germany -Firmenwissen：http://www.firmenwissen.de/index.html 3. Other comprehensive information query. -linkdin：https://www.linkedin.com/ -Twitter：https://twitter.com/ -facebook：www.facebook.com -medium：https://medium.com/

**19. How will you ensure the data meets local & regional legal requirements?**
First of all, we have mastered the basic data related laws due to longtime working as Notary. We will do the following things to ensure the data meets legal requirements. Ask for commitment.We'll ask clients to make commitment to state their data has met the local legal requirements. Make punishment rules. Once the date is found not meet the requirement, we will not accept their application for a certain time and all the unused DataCap will be taken back. We will also disclose it in the community.

**20. What types of data preparation will you support or require?**
We will ask clients to package the data into categories and give a brief description for each package. We support various preparation methods, such as Singularity, Lotus and so on.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?**
We'll start by telling clients on Github and Slack that they can't make sector-size subse. We will randomly check the stored data. 2 pieces of data are sampled for each PiB of data to confirm whether the data is abused.

**Comment by Filplus-govteam** [comment]
Data Distribution

**22. How many replicas will you require to meet programmatic requirements for distribution?**
3+

**23. What geographic or regional distribution will you require?**
Each batch of data requires at least 3 different provinces or countries. We will not require (or exclude) certain geopolitical regions.

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?**
4+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?**
We will require each client that each batch of their data to be stored at least 4 SPs, with no more than 30% of the quantity stored on each SP. At the application stage, we'll ask for a public description of the plan on Github and document it by using a form. Before the subsequent application, we will check whether the actual distribution ratio is roughly in line with their plan.

**26. What tooling will you use to verify client deal-making distribution?**
We will use the existing CID checker bot and datacapstats.io to assist us in verification. At the same time, we will use the browsers to make further confirmation. Filfox:https://filfox.info/en/deal Glif:https://explorer.glif.io/ Filscan:https://filscan.io/tipset/dsn/ FilecoinPLUS:https://datacapstats.io/clients Filecoin tools:https://filecoin.tools/ Filedrive:https://filplus.info/

**27. How will clients meet SP distribution requirements?**
We will ask clients to clarify the SP plan and specific distribution on Github in advance, and use tools such as Bot to check whether the number of SPs meets the requirement of at least 4 SP after storage.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?**
We do not support VPNs. We will ask clients to provide the address proof of the selected SPs, and at the same time through the software, such as Filecoin Green, Filstats.io, to query the address. In addition, if a client is reported to be using a VPN, we will reject his/HER subsequent applications.

**Comment by Filplus-govteam** [comment]
Datacap Allocation Strategy

**29. Will you use standardized DataCap allocations to clients?**
No, client specific

**30. Allocation Tranche Schedule to clients:**
For general applications, we will allocate their required amount on a certain ratio basis. But no more than our maximum. • First: 20% of their required amount, but not more than 10TiB. • Second: 40% of their required amount, but not more than 20TiB. • Third: 70% of their required amount, but not more than 40TiB. • Fourth: 100% of their required amount, but not more than 100TiB. • Max per client overall: 100 for individule and 500 for enterprise. For LDN, we do not set a cap, as long as the client's storage is in line with community requirements.

**31. Will you use programmatic or software based allocations?**
Yes, standardized and software based

**32. What tooling will you use to construct messages and send allocations to clients?**
https://plus.fil.org/

**33. Describe the process for granting additional DataCap to previously verified clients.**
We will use certain criteria for subsequent allocation. The specific process are as follows: 1. We will define the threshold for reapplication, that is, the amount of remaining datacap/the amount of datacap used in the last week < 0.5, and check whether the client's datacap allocated by us does not exceed 20% of our own total datacap. If these two conditions are met, the client can apply again. We will carry out the following investigation. If not, we will not continue to check and allocate. 2. Based on the results of SA bot, https://datacapstats.io/, etc. We will check the actual usage of the datacap obtained before. The application will be rejected if the following circumstances occur. a. At least 3 different provinces or countries do not exist b. Do not stored on at least four SPs c. The datacap storage of single SP storage exceed 30% d. The stored data does not support retrieval e. The stored data retrieved by sampling is not valid data 3. If there is no problem in the above two steps, we will conduct the next allocation according to the standard.

**Comment by Filplus-govteam** [comment]
Tools and Bookkeeping

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • dispute discussion & resolution • community updates & comms**
• client discoverability & applications We will publish our contact information on Pluskit's official website, Slack, Github. And we usually receive application requests from clients through Slack, Github and email, and guide clients in the application process. • due diligence & investigation -KYC/KYB Baidu encyclopedia, Qichacha, Tianyancha, Wikiglobal, regional government websites, portal information, etc -Socail media Official website, Wechat public account, Weibo, Linkdin, Twitter, Facebook, Medium, etc -Website Whois、Tencent cloud, etc. • bookkeeping We will record through online tools such as Google Docs, Graphite Docs, github, and offline Docs. • on-chain message construction Filecoin tools:https://filecoin.tools/ FilecoinPLUS:https://datacapstats.io/clients Glif:https://explorer.glif.io/ Filedrive:https://filplus.info/ Filfox:https://filfox.info/en/deal Filscan: https://filscan.io/tipset/dsn/ • client deal-making behavior Filecoin tools:https://filecoin.tools/ FilecoinPLUS:https://datacapstats.io/clients Glif:https://explorer.glif.io/ Filedrive:https://filplus.info/ Filfox:https://filfox.info/en/deal Filscan: https://filscan.io/tipset/dsn/ • tracking overall allocator health datacapstats.io, SA bot, etc. • dispute discussion & resolution Github、Email、Zoom、Slack • community updates & comms Github、Email、Slack

**35. Will you use open-source tooling from the Fil+ team?**
Yes. API integration tools https://documenter.getpostman.com/view/131998/Tzsim4NU#98fe18ca-b15a-4753-986f-91882fd87a12 Notary allocation inquiry a.https://datacapstats.io/notaries b.https://filplus.info/ Data retrieval ratio https://retrievalbot-dashboard.vercel.app/. SP Dispersed location query SA Bot. Query the SP allocation https://datacapstats.io/clients/X/breakdown. Datacap usage records a.https://filecoin.tools/ b.https://datacapstats.io/clients

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?**
All allocation decisions will be recorded in form and kept/updated both on Google&Shimo. and locally. The information will be publicly available on Github. Other private clients' information, such as the size of the client's assets, data composition, etc., will not be publicly available on Ggithub, but will be stored in emails and local files. In the event of dispute, or as required by PL, non-public disclosure will be made in the form of mail with the permission of the client.

**Comment by Filplus-govteam** [comment]
Risk Mitigation, Auditing, Compliance

**37. Describe your proposed compliance check mechanisms for your own clients.**
	•	Tracking and auditing DataCap distribution of allocated datacap For regular applications, We will pre-formulate the main scoring standards and the corresponding DataCap allocation standards, and publish them on Github for all community members to consult and strictly follow the standards. In addition, we will record the allocation results of all allocation results, including regular applications, LDN, E-Fil, etc.), in a timely manner and publish them to be monitored by the whole community on Github.
	•	The clients' downstream usage of datacap We will implement clear downstream usage standards for clients and require them to commit to compliance and disclosure of usage. Before re-allocation, we will check the actual usage, and continue to allocate according to the standard if it meets the requirements. If it does not meet the requirements, it will be given 2 reminders and warnings, and if the client still violates the rules, the application will no longer be assigned, and it will be notified in slack. There is a maximum of 2 consecutive opportunities for client violations.
	•	Client compliance standards We would ask that clients to meet enterprise compliance, data compliance, SP compliance, storage compliance. Corporate compliance:
	•	The enterprise should be legally existing.
	•	Possess of the right to legally store data. Data compliance:
	•	The data type and content must meet the requirements of the registration location
	•	Data is allowed to be publicly/privately stored on the Filecoin, whether it is own data or third-party data. SP compliance:
	•	Number of SPS and allocation ratio
	•	Location of the SP and IP address area
	•	Support retrieval Storage compliance:
	•	No abuse
	•	Support retrieval
	•	The stored data is valid Before datacap allocation, we will ask the client to clarify the above information, the total amount of datacap requested, and the estimated weekly datacap usage. All these must meet our requirements. At the same time,we will ask clients to publish their usage on Github every 2 weeks. After datacap allocation, w will check every 2 weeks whether the client has feedbacks on the issue of their application, whether datacap usage meets our requirements, and whether it is used in the way promised in advance.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.**
First of all, we will avoid disputes as much as possible by setting clear standards and following up datacap usage throughout the process. In the event of dispute with the client, we will:.Make an initial response on Github within 3 working days. Then, we will find out the situation and explain it on Github within 2 working days. We will disclose non-private information related to the client in view of the dispute. If information is private, we will contact PL and send the information to PL via email and request PL to publish the verification results on Github. For the part related to the dispute that we am not clear about, we will communicate with the client and ask them to explain on Github and provide relevant evidence. 3. If there are omissions in the dispute, we will explain on Github and apologize. If necessary, we will ask PL assistance to remove the client's DataCap. In the event of a dispute against me, we will:
	•	Make an initial response on Github within 3 working days. Then, we will find out the situation and explain it on Github within 2 working days.
	•	Actively submit evidence related to the dispute on Github. If it involves private information, we will contact PL and send the information to PL by email, requesting PL to publish the verification results on Github.
	•	We promise there will be no private deals that violate community norms if we am elected as allcator.

**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.**
We will update some information and tools within community norms, but not too often, no more than twice a year. When it comes to updates, we will explain the update point on Github and Slack. In the meantime, we will notify PL and existing clients via Github, Slack and email.

**40. How long will you allow the community to provide feedback before implementing changes?**
Before changing, we will publicly state the proposed update point and estimated effective time on github and slack. We will ask community members to respond within 1 month. In the case of inadequacies, we will reconfirm and publish. If no objection received from PL and community members within 1 month, the corresponding update point will automatically take effect.

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?**
We will use ledger to manage our on-chain wallet addresses and keep the ledger in a place where only we can get it and sign applications with the Ledger. And, we will use ledger to operate on a specific network. If we use multiple signatures, we will activate legder first and connect on the computer. Then, we will log in to plus.fil.org and select the corresponding issue for approval.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?**
No, we won't use smart contracts at this stage. Further consideration will be given in the future based on the development situation and the specification of the rules of Filecoin Plus.

**Comment by Filplus-govteam** [comment]
Monetization

**43. Outline your monetization models for the services you provide as a notary allocator pathway.**
In the present stage, we think it is the initial stage of profit exploration, so allocator should not set up too many charges. We plan to start experimenting with charging for value-added services. Usually we will review clients' applications within 5 working days and complete the feedback. If urgent feedback is required, we will charge the urgent fee and complete it within 2 working days after receipt of the account. It is estimated 10 FIL/ time.

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.**
The name of organization: Wellhealth International Limited. The legal entity: Bo Shen Location: suite 603,6/f laws comm plaza 788 cheung sha wan road,kowloon,hong kong Registration date: Aug.18.2017 Wellhealth International Limited. is currently actively exploring the Filecoin and support the further development and operation of Pluskit.

**45. Where will accounting for fees be maintained?**
If expense accounting is involved, we will use a special address for unified income and expenditure. Income and expenditure are presented on the chain. We will use offline forms to record and make them available to the public when necessary. This address is not clear at the moment and will be clear before Jan. 20.

**Comment by Filplus-govteam** [comment]
Past Experience, Affiliations, Reputation

**46. If you've received DataCap allocation privileges before, please link to prior notary applications.**
The GitHub URL of our previous notary applications: [filecoin-project/notary-governance#448](https://github.com/filecoin-project/notary-governance/issues/448) [filecoin-project/notary-governance#694](https://github.com/filecoin-project/notary-governance/issues/694)

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.**
As an independent team, we joined Filecoin as developers and started to develop a statistical tool, pluskit.io, to make it easier for the community to query DataCap distribution data more efficiently. Pluskit team was founded in June 2021, and the product was officially launched in October 2021. In December 2021, Pluskit team was invited to participate in the Notary Governance Call to present a project showcase, which won a large number of likes from community members; In January 2022, Pluskit received Next Step Microgrant; In February 2022, Pluskit was included in the Filecoin Community Roadmap. In March 2022, Pluskit was elected as Notary in the 3rd round of Notary Elections. During the tenure, we actively performed the duties as a notary: a. Attended almost every Governance calls. b. Timely process applications. We received four general applications with an average processing time of 1 day and we dealt LDN for more than 60 times. c. Actively participate in community discussions and express our own views, such as E-Fil+, project Beacon, issue of the third round of notary signing etc. d. Join E-Fli+ group and attend the meetings. In addition, in 2021 and 2022 we are notary of Filecoin Plus and deeply involved in the notary work.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?**
We will initially assess the actual demand of clients according to their industry, business type and data type. As for the client's pathway usage, we will require it to be publicly posted on Github, and further confirm the actual usage of the allocated datacap through query tools (such as https://filecoin.tools/, https://filplus.info/, etc.). Because I've approved a number of applications as a notary, we have some existing public clients. W usually get clients' applications through Email, Github and Slack

**Comment by Kevin-FF-USA** [comment]
Hi @Filplus-govteam,
Wanted to let you know this application has been received. Once you complete and submit the include Airtable (form) information - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by PluskitOfficial** [comment]
Hi, @Kevin-FF-USA @kevzak 
        In the materials of allocator application we have submitted before, some information is missing and the meaning of the question is misunderstood. We add the following information:
8. We have developed a tool collection browser so that we can allocate datacap to clients according to clear projects, and allocation decisions have sufficient data support.
Efficiency: The collection of many third-party websites and tools makes users can view community tools, notary distribution information, etc., without scattered access, and efficiency of gaining information increased by more than 50%.
User engagement: Different types of information are summarized, and users with different needs are further brought together on the platform to enhance users' engagement.
10. We will choose enterprise clients, because the amount of personal data and small developers' data is relatively limited, while enterprise clients have more sufficient data, and they have real storage needs to participate in storing on the Filecoin network.
14. We will open the application to users in all fields. When we receive the applications, we will clarify the application steps, community regulations, our allocation strategy, and attach our contact information (email, Slack, etc.) on the issue of the application. When clients have any questions, we will answer and explain at once.
17. We support the application from the industries of value to human beings, including but not limited to technology industry, entertainment industry, education industry, medical industry, etc.
Minimum amount of public open datasets (research/non-profit): a single dataset of 100T
Minimum amount of private business/enterprise: a single dataset of 10T
Minimum amount of public open commercial/enterprise: a single dataset of 10T
19. Most of the applications we have processed are from Asia and North America. In Asia, we already have a team of legal advisers. In North America, we plan to hire a legal team as well. For these two regions that we are more familiar with. For other regions, we will also get legal professional advice after receiving the application by actively seeking community help and finding local legal part-time staff.
Checking steps:
-We will check the client's previous storage history on the internet and github to see if there is any violation.
-Our legal consultant will conduct a manual inspection of the data sampling.
-We will use data filtering software for spot checks.
22.8 +
27. We will inform SP related channels in the question-and-answer phase, guiding the client to find SP through the Github/Slack/FilecoinGreen/datacapstats.io, etc. If clients have questions about the relevant channel, we will give detailed explanations and guidance on a one-to-one basis.
29. Yes, we will make a unified standard in advance, and allocate datacap according to the corresponding standard, and limit the maximum acquisition of a client.
[https://gi](https://github.com/PluskitOfficial/Pluskit/blob/main/Scoring%20Sheet%20For%20Allocating.xlsx)[t](https://github.com/PluskitOfficial/Pluskit/blob/main/Scoring%20Sheet%20For%20Allocating.xlsx)[hub.c](https://github.com/PluskitOfficial/Pluskit/blob/main/Scoring%20Sheet%20For%20Allocating.xlsx)[o](https://github.com/PluskitOfficial/Pluskit/blob/main/Scoring%20Sheet%20For%20Allocating.xlsx)[m/Plu](https://github.com/PluskitOfficial/Pluskit/blob/main/Scoring%20Sheet%20For%20Allocating.xlsx)[s](https://github.com/PluskitOfficial/Pluskit/blob/main/Scoring%20Sheet%20For%20Allocating.xlsx)[ki](https://github.com/PluskitOfficial/Pluskit/blob/main/Scoring%20Sheet%20For%20Allocating.xlsx)[t](https://github.com/PluskitOfficial/Pluskit/blob/main/Scoring%20Sheet%20For%20Allocating.xlsx)[Official/Pluski](https://github.com/PluskitOfficial/Pluskit/blob/main/Scoring%20Sheet%20For%20Allocating.xlsx)[t](https://github.com/PluskitOfficial/Pluskit/blob/main/Scoring%20Sheet%20For%20Allocating.xlsx)[/blob/main/Scoring%20S](https://github.com/PluskitOfficial/Pluskit/blob/main/Scoring%20Sheet%20For%20Allocating.xlsx)[he](https://github.com/PluskitOfficial/Pluskit/blob/main/Scoring%20Sheet%20For%20Allocating.xlsx)[et%20F](https://github.com/PluskitOfficial/Pluskit/blob/main/Scoring%20Sheet%20For%20Allocating.xlsx)[or](https://github.com/PluskitOfficial/Pluskit/blob/main/Scoring%20Sheet%20For%20Allocating.xlsx)[%20Allocating.xlsx](https://github.com/PluskitOfficial/Pluskit/blob/main/Scoring%20Sheet%20For%20Allocating.xlsx)
30. For the client's first application, no reputation has been established, so we will allocate a small amount of datacap, and gradually establish reputation through continuous application, and then allocate more datacap.
31. We will use plus.fil.org and Ledger for allocation.
35. In the process of using the tool, we will timely feedback the problems and optimization suggestions related to the tool to the community.
38. We will use tools to record arguments
Meeting records: Slack group, Zoom
Process records: Github repository, Google documentation
39. We will specify the process of the tool and the details of the rule changes in the announcement.
45. f1d5fwu3ux7bkbfbf7zqs62wgliq7bhelv6g4nuby
48.
-Our parent company has developed in the health industry for nearly 7 years and has accumulated dozens of industry partners. Based on our customers' current situation, we will communicate with companies with large datasets and guide them to use Filecoin for data storage.
-We often participate in web3.0 related conferences, in which we will contact other industry entities, we will take the initiative to explain FilecoinPlus to them, and invite them to participate in Filecoin Plus.

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2p4lym5klogvenjp45zbux77kmbuniizzs22j7za
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2p4lym5klogvenjp45zbux77kmbuniizzs22j7za
#### Datacap Allocated
> 2.5PiB

**Comment by galen-mcandrew** [comment]
Looks like these are two duplicate proposals for the same amount. txID 715 and 716.

716 has the second approval (bafy2bzacecgmncelwa5qt3wiogwkb4uwzfwlio3xxbmz77ugrfnlz7bprdxhc) so we will ask RKH to remove pending transaction 715 (bafy2bzacecqzrrx7bx7txtrqkl5pryeo5t3l5dstddm6zpgkqwlwvmadyvdwy)
