### ISSUE TITLE
v5 Notary Allocator Application: Waterdrop Lab

### ISSUE THREAD

**Issue by amiclan666** [filecoin-project/notary-governance#1017]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): Waterdrop Lab
3. Organization Name:  SSDMINER CLOUD INTELLIGENT
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain):  f157xffs5vqgzfvcdwhqo7bna2cqadhxchq52mvbi
5. Country of Operation (Where your organization is legally based):  Hong Kong, China
6. Region of Operation (What region will you serve?):  Greater China
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase):  Automated/programmatic 
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB):  120PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
@amiclan666 
Wanted to let you know this application has been received. After you complete and submit the Airtable form with your detailed Allocator plan - the public answers will be posted in a thread below. If you have any questions - please let me know.

**Comment by galen-mcandrew** [comment]
## Datacap Request for Allocator
#### Address
> f2ddjxnv4bvvl6br7nuuthgk6cx5ad53jnqefszka
#### Datacap Allocated
> 5PiB
