### ISSUE TITLE
Discussion: Mistaken datacap granted by Glif notary service.

### ISSUE THREAD

**Issue by Schwartz10** [filecoin-project/notary-governance#102]
## Issue Description
After the recent mandatory Lotus API Upgrade to version `1.5.0`, our team made a mistake in the process QAing the Glif verifier (notary service). We accidentally granted 8GB of datacap to `f1y6py4yuc2jwukmeivurhrwzffqpmqgmdboggdfy` on mainnet. [Transaction](https://filfox.info/en/message/bafy2bzaceamlva6e7cq7irchkgs6ztqqycpoo6l7jgtaqenucxdo4fbtjakuu).

We expected this call to error after mistakenly assuming this verified client had remaining datacap bytes on it (and the Glif verifier should throw a helpful error message in that case). Since the verified client actually had 0 bytes of data cap left, the transaction went through and succeeded.

We of course do not choose to test in prod! Due to the time urgency, we did not have a great way to test this aspect of the Glif verifier on a dev network like Calibration net or a local network. We did our best to test all other aspects in safer ways, but when eventually we had to move our testing to mainnet and the mistake was made.

## Impact
Fortunately, 8GB of datacap is not too much, however, the owner of `f1y6py4yuc2jwukmeivurhrwzffqpmqgmdboggdfy` may be confused or worry about the integrity of the notary system.

## Proposed Solution(s)
Not entirely sure yet, just wanted to escalate this and make the issue public. We do have access to an email address on this account, we could try to email them and point them to this issue as an explanation of the mistake.

In the future we would:
a. Have a better understanding of when breaking changes will be introduced to the API that require mandatory API upgrades (this is likely our fault, we just need to know where to look). This will give us a wider window to upgrade
b. When mandatory upgrades are introduced, provide some testnet to test notary flows on so that we don’t have to test in prod

The combination of the two - having to move fast to deploy the fix and not having another place to test besides mainnet - is what put us in the situation that likely increased the chances of a screw up like this.

Please let me know if there is any additional course of action we should take to escalate this issue and deal with it appropriately. Sorry for the mistake!

**Comment by dkkapur** [comment]
@Schwartz10 - this was mentioned in the last couple of notary governance calls, and also looks like no-one really flagged any additional issues with this. Thanks for being transparent and sharing this information along with next steps. At this point - unless you have additional next steps you would like to clarify or raise, I propose that you share what actions you took and close the issue.

**Comment by Schwartz10** [comment]
Hey @dkkapur - in terms of the steps we took - we filed this issue, and we learned more about what to/not to do in QA - glad to hear nothing was flagged!
