### ISSUE TITLE
Discussion: Criteria for removing inactive notaries

### ISSUE THREAD

**Issue by andrewxhill** [filecoin-project/notary-governance#103]
Issue to discussion a more automatic way to remove inactive Notaries.

We need to strive for a fast, simple onboarding process for new clients. I'd propose to remove all new notaries who have all of these properties:

1. Planned to accept applications via plus.fil.org
2. Have not granted a single datacap to a client.
3. Have an average response time to plus.fil.org applications of greater than 14 days (or some agreed upon duration).

It sets a higher bar for new notaries to onboard quickly.

i'm not set on 14days being the duration, but some clear criteria.

we could also have a simple path for notaries to extend that duration (e.g. if they hit technical issues or other that keep them from onboarding). perhaps also we can have a simple way for a notary to temporarily hide their information from the application form while not able to respond.

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/issues/112

**Comment by andrewxhill** [comment]
Conclusion from last gov call. Don't do this right away. Implement some more automated feedback and tools to move pipelines forward (including warnings to notaries). If we see a growth in the problem, we can reopen and design something then.
