### ISSUE TITLE
Modification: Notary Applications - Add anticipated response time and throughput

### ISSUE THREAD

**Issue by andrewxhill** [filecoin-project/notary-governance#104]
In notary applications, it would be good to ask applicants to commit to two parameters up front:

1. Their proposed response time to new clients. This will be a KPI that we can hold them to in the future of their tenure. 
2. Their high watermark for application throughput. If a notary is getting too many applications, that's a good thing and we should work to find those clients other notaries, not penalize the notary for slowing down.

We can also filter applicants that have two low of either number to ensure all clients have a good onboarding experience.

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/issues/112

**Comment by dkkapur** [comment]
@andrewxhill - proposing that we continue this conversation on above mentioned PR to confirm the language around introducing this guidance. Based on this, closing out the issue for now. Can re-open as needed. Thanks!
