### ISSUE TITLE
Modification: Notary allocation address change - fixing Blotocol Japan's DataCap allocation address

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/notary-governance#106]
## Issue Description
Based on the initial application in https://github.com/filecoin-project/notary-governance/issues/56, the address granted DataCap is not usable for @MasaakiNawatani until tooling exists to support multisigs. In the meanwhile, it is recommend that we rotate the Notary's address to `f1fh53sdaie3yi25qxwcqxpt5h4naex5ibdaffibi`.

## Impact
@MasaakiNawatani is unable to grant DataCap to clients until this is resolved.

## Proposed Solution(s)
1. Set DataCap allocation of `f3rnnecpx2n5cxs5fsjrnqq32r3hacubkt45mnbywvcaskgwpfuzixdmydpcdmujwqwoe6l2oi4tzyj2zakjsq` to 0TiB.
2. Set DataCap allocation of `f1fh53sdaie3yi25qxwcqxpt5h4naex5ibdaffibi` to 10TiB.

## Related Issues
Original application: https://github.com/filecoin-project/notary-governance/issues/56

**Comment by dkkapur** [comment]
@MasaakiNawatani can you confirm that the addresses listed under the "Proposed Solution" are correct?

**Comment by MasaakiNawatani** [comment]
Hi Deep, thank you for helping out. 

The correct address should be:  f1fh53sdaie3yi25qxwcqxpt5h4naex5ibdaffibi

So yes, that is correct.

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f3rnnecpx2n5cxs5fsjrnqq32r3hacubkt45mnbywvcaskgwpfuzixdmydpcdmujwqwoe6l2oi4tzyj2zakjsq
#### Datacap Allocated
> 0TiB

**Comment by MasaakiNawatani** [comment]
> ## Request Approved
> #### Address
> > f3rnnecpx2n5cxs5fsjrnqq32r3hacubkt45mnbywvcaskgwpfuzixdmydpcdmujwqwoe6l2oi4tzyj2zakjsq
> 
> #### Datacap Allocated
> > 0TiB

Hi Deep, I checked my ledger and datacap allocation is still not showing on my correct address. Do I need to do anything on my end? Thanks.

**Comment by dkkapur** [comment]
@MasaakiNawatani - at the moment no, we're waiting to ensure this message is being processed and then signed-on by Root Key Holders before proceeding with the next step.

**Comment by MasaakiNawatani** [comment]
> @MasaakiNawatani - at the moment no, we're waiting to ensure this message is being processed and then signed-on by Root Key Holders before proceeding with the next step.

Got it. Hope it can be done sooner than later. Thank you, Deep.

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/issues/113 was opened to track the corrected allocation
