### ISSUE TITLE
Modification: Notary allocation change - fixing MathWallet's DataCap allocation

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/notary-governance#107]
## Issue Description
The DataCap allocation for MathWallet Notary does not seem to have gone through during the first round of Notary allocations.

## Impact
MathWallet Notary is unable to grant DataCap to Clients.

## Proposed Solution(s)
1. Confirm that DataCap was not allocated to the wrong address by the FIL+ tooling
2. Allocated 10TiB of DataCap to Notary address `f1snwd4w4y2fjwadkftcitcsnoerprlkrphn6kily` 

## Related Issues
Original application: https://github.com/filecoin-project/notary-governance/issues/26

**Comment by jnthnvctr** [comment]
## Request Approved
#### Address 
> f1snwd4w4y2fjwadkftcitcsnoerprlkrphn6kily
#### Datacap Allocated
> 10TiB

**Comment by rayshitou** [comment]
Strangely, our total DataCap is still zero in this website -https://filplus.info  . And "no such verifier" again when i verify client. @jnthnvctr

**Comment by rayshitou** [comment]
Hi @dkkapur 
I can see the DataCap on filplus.info now, but it still zero on plus.fil.org. And prompts "no such verifier" also when i verify client.

**Comment by dkkapur** [comment]
@rayshitou - initial analysis shows that you have may received DataCap at this address in the past as a client? DataCap is currently not designed to be added more than once to an address, and once an address has been given the status of a verified-client (which would have happened when you initially got DataCap) it cannot become a Notary (aka "verifier" on-chain). Can you help me confirm if this address received DataCap as a client in the past or if this is something else?

**Comment by rayshitou** [comment]
@dkkapur - Yea.  It seems got 8GB DataCap at https://verify.glif.io/

**Comment by rayshitou** [comment]
Hi @dkkapur, could you please help to change to this address - f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja

**Comment by dkkapur** [comment]
Yes - trying this again!

**Comment by dkkapur** [comment]
Pursuing this here: https://github.com/filecoin-project/notary-governance/issues/114
