### ISSUE TITLE
Modification: filecoin-project/filecoin-plus-client-onboarding - add an auto-close bot

### ISSUE THREAD

**Issue by andrewxhill** [filecoin-project/notary-governance#109]
## Issue Description

As we try to improve the performance of notaries, we should also try to help them by removing stale issues and non-responsive applicants. Having issues sit open for more than a few days sets a bad precedent.

## Impact

- Add more pressure to clients to move quickly with their applications. 
- Remove stale applications proactively.
- Allow the repo issues to be a better representation of current needs (not outdated ones).

## Proposed Solution(s)

We should add an auto close bot to the https://github.com/filecoin-project/filecoin-plus-client-onboarding repo. We discussed on two previous governance calls that ~10days sounded like the right number to test out at first.

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/issues/112

**Comment by dkkapur** [comment]
Quick note - this was raised in the notary governance call this past week and there generally was consensus to pursue this, at the very least, as an experiment. 

We're investigating integrating this functionality into the current filecoin_plus_bot, and will use a generic issue closing bot as a backup plan. Will keep this issue updated.

**Comment by dkkapur** [comment]
Bot was implemented and has been useful! Closing out this issue as part of routine cleanup.
