### ISSUE TITLE
Potential abuse by notaries - asking for Governance and community review

### ISSUE THREAD

**Issue by kevzak** [filecoin-project/notary-governance#1101]
## Issue Description
In reviewing https://datacapstats.io/large-datasets?limit=25, it was noticed several instances in the past few days/weeks of specific notaries signing off on 2PiB allocations of DataCap with no client name or address. Specifically:
Smart Dong
Bobbi Choi
Joy Lee
Tokencan

## Impact
Potential clear sign of abuse of power

## Proposed Solution(s)
Immediate removal from multisig and potential removal of DataCap

**Comment by kevzak** [comment]
FYI @galen-mcandrew @Kevin-FF-USA

**Comment by galen-mcandrew** [comment]
Addresses:
TAKI Chain: f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
Bobby Choii: f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
Tokencan: f1txboxiscdm4f3okffyjmbilmwjtbisrbee72j6q
NFTStar: f1c36q3bpodeddiers557j6e2mafw3oglitx56vty

**Comment by kevzak** [comment]
More found:
<img width="862" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/102751751/66a1618f-05c1-4259-93d9-c99254fce260">

**Comment by kevzak** [comment]
<img width="831" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/102751751/19f668b5-2945-4e96-9163-cba9665ff8c7">

**Comment by kevzak** [comment]
<img width="834" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/102751751/40c829d9-894b-480c-9d7a-683e7f58cd89">

**Comment by kevzak** [comment]
<img width="822" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/102751751/1f3444a2-b6b7-4c4e-aaff-bb6e22a1f9de">

**Comment by kevzak** [comment]
Pangod
Aifabot
Ewesion
RawTech Ventures
Protocan
Meibuy Cloud

**Comment by MegaFil** [comment]
Looks like the fil+ rules are not being strictly enforced anymore, more than half of the notaries are breaking the rules now. Where is RG?

**Comment by Chris00618** [comment]
Almost all SPs think fil+ is a joke. Why do these people continue?

Solana's snapshot project is all about fake data stored into filecoin, and too many notaries are abusive on this case. We think the fil+ team should be laid off a long time ago.
![image](https://github.com/filecoin-project/notary-governance/assets/105741726/c8c46c48-bb49-40b9-a8ab-f9c45163b469)


https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/923

![image](https://github.com/filecoin-project/notary-governance/assets/105741726/93b0f534-12fd-42a9-815a-83acef84ebae)
![image](https://github.com/filecoin-project/notary-governance/assets/105741726/01c7b887-3547-48d7-b475-9bfa3e1e7e21)

**Comment by kenzz45** [comment]
"DC allocation involves subjective human decisions, opening the door to favoritism and discrimination, driving miners away to chains with normal consensus algorithms."

**Comment by TrueBlood1** [comment]
Also more found:

![a](https://github.com/filecoin-project/notary-governance/assets/126061227/17e31fe0-05ca-4662-b642-4a2db077ce76)

Laura: f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
STCloud: f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci

**Comment by TrueBlood1** [comment]
![b](https://github.com/filecoin-project/notary-governance/assets/126061227/78bde3e2-8469-4b85-bd37-23a84c523b30)

**Addresses**

Antalpha: f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
SXX Future: f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq

**Comment by TrueBlood1** [comment]
![c](https://github.com/filecoin-project/notary-governance/assets/126061227/75ff00dc-06c9-4d56-a8aa-229e3421bef8)

**Addresses**
FILWallet: f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
LendMi: f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da

**Comment by TrueBlood1** [comment]
![d](https://github.com/filecoin-project/notary-governance/assets/126061227/7ea0922f-753f-405b-9c58-03207c9df95d)
![e](https://github.com/filecoin-project/notary-governance/assets/126061227/bb0ff97e-733a-4576-984c-a192af0a96aa)

**Addresses**
DeFil: f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
IPFS.CN: f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a

**Comment by TrueBlood1** [comment]
![f](https://github.com/filecoin-project/notary-governance/assets/126061227/4f1c7bce-7ed9-454d-9917-426523378aca)
![g](https://github.com/filecoin-project/notary-governance/assets/126061227/676b6ef1-a30d-427c-b7a4-ea5017c62f02)

**Addresses**
NFTSTAR: f1c36q3bpodeddiers557j6e2mafw3oglitx56vty
YuanHe Tech (Firefly): f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa

**Comment by TrueBlood1** [comment]
With so many similar phenomena, the rules of Fil+ need to be clarified again.

**Comment by galen-mcandrew** [comment]
This issue is in regards to signatures that do not have supporting client or GitHub diligence issues. Specifically, we are seeing "first" allocations for large tranches that do not have client application records. We are scoping this GitHub issue to that specific dispute type, so other claims or disputes are off topic for this thread. If there are other disputes, we would like to track those in specific forums.

We are working with the root key holders to remove the signers flagged above for large allocations with no supporting diligence.

**Comment by kevzak** [comment]
> notaries signing off on 2PiB allocations of DataCap with no client name or address

@MegaFil as I stated initially, the flag in this proposal is regarding a specific group of notaries signing off with **_no client name or address_** on the first allocation at 2PiBs.

Your examples highlighted are all applications with client names, addresses, github links, and a variety of different signers on different allocation amounts and allocation stages. Not sure the correlation.

**Comment by kevzak** [comment]
> With so many similar phenomena, the rules of Fil+ need to be clarified again.

@TrueBlood1  What rules are you asking to be clarified? Perhaps I can help. 

The general Fil+ guidelines haven't changed and have always been listed here: (https://github.com/filecoin-project/filecoin-plus-large-datasets?tab=readme-ov-file#current-scope)

This proposal is to address a very specific example of notaries signing without client address or name. It is not related to the Fil+ guidelines.

**Comment by kevzak** [comment]
> ![c](https://private-user-images.githubusercontent.com/126061227/306964336-75ff00dc-06c9-4d56-a8aa-229e3421bef8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjkxMzAsIm5iZiI6MTcwODYyODgzMCwicGF0aCI6Ii8xMjYwNjEyMjcvMzA2OTY0MzM2LTc1ZmYwMGRjLTA2YzktNGQ1Ni1hOGFhLTIyOWUzNDIxYmVmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQxOTA3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTc0ZWVkNzJkNDhiMjk0NzNmZDFiZjdlMDI4ODE0MTc3ZGE5ZGViZDk0YWE2ZGI1YWFkNWMwNDBiOTgwZmNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rFnZBUscSqzgCSAnEoQR7QIuvLL3kRsPPjz-0fKU4bU)
> 
> **Addresses** FILWallet: f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq LendMi: f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da

This signature was for application # 975 which exists. No issue here

**Comment by kevzak** [comment]
> eneral Fil+ guidelines haven't changed and have always be

@TrueBlood1 thanks for flagging these but all of your examples do have client addresses listed so we can track the application. Sometimes a client name might not be listed on this view in datacapstats.io, but you should be able to search for the application in LDN github repo using the client address. Let me know if that helps.

**Comment by TrueBlood1** [comment]
More found:

![a](https://github.com/filecoin-project/notary-governance/assets/126061227/05fc9dd6-73af-4f72-abfa-b2fa3ff7afcf)

**Addresses**
Fei Yan - Kernelogic: f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
Genesis: f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri

**Comment by TrueBlood1** [comment]
![c](https://github.com/filecoin-project/notary-governance/assets/126061227/aa5ee7d0-791c-4556-bd8e-ee7089d3195d)

**Addresses**
Fei Yan - Kernelogic: f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
New Web Group: f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq

**Comment by TrueBlood1** [comment]
![d](https://github.com/filecoin-project/notary-governance/assets/126061227/a9a19b17-731d-4345-bacb-7fb9682e334e)

**Addresses**
Tim Guo: f1yslbnnqzrjlyuxsmyxfbqcc7xthcavgpripjevi
New Huo Pool: f16karfxq7lxdy7izqrzrk75jf3not34k6sg6zvcy

**Comment by TrueBlood1** [comment]
![e](https://github.com/filecoin-project/notary-governance/assets/126061227/a785232b-7f0e-4ac5-9fd0-14fe980cc62c)

**Addresses**
Genesis: f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
FogMeta: f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq

**Comment by TrueBlood1** [comment]
![f](https://github.com/filecoin-project/notary-governance/assets/126061227/9bef9ae6-a069-45e8-bf99-cadae3f87a2f)

**Addresses**
FILWallet: f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
ORIGIN Storage: f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga

**Comment by kevzak** [comment]
> More found:
> 
> ![a](https://private-user-images.githubusercontent.com/126061227/307295799-05fc9dd6-73af-4f72-abfa-b2fa3ff7afcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTU2NjUsIm5iZiI6MTcwODY5NTM2NSwicGF0aCI6Ii8xMjYwNjEyMjcvMzA3Mjk1Nzk5LTA1ZmM5ZGQ2LTczYWYtNGY3Mi1hYmZhLWIyZmEzZmY3YWZjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMzM2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDFmZmM3YTc0NmE0ZTM0NWVlNTc3ZWZkNmY3YzgyNzUzMmZjNDgzZTNmZGM5MWNmYjBmMWU4N2YxMzFjOTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ETEEjMURcvFibcNk0o5MyWePi0hzQztVGZeeRA6S4Pc)
> 
> **Addresses** Fei Yan - Kernelogic: f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa Genesis: f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri

That's weird, even though showing unknown I found this one: https://github.com/filecoin-project/notary-governance/issues/1101#issuecomment-1961105048

**Comment by kevzak** [comment]
> ![b](https://private-user-images.githubusercontent.com/126061227/307296737-13d7d3cb-1048-4a7c-8dd4-de4a5daa665b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTU2NjUsIm5iZiI6MTcwODY5NTM2NSwicGF0aCI6Ii8xMjYwNjEyMjcvMzA3Mjk2NzM3LTEzZDdkM2NiLTEwNDgtNGE3Yy04ZGQ0LWRlNGE1ZGFhNjY1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMzM2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMWM0NDE2NGEyMmQyMTZiM2E1YjM4ZTQ4ZTQ0NjY1MmU2ODZmNTcwMjZmNWEyNGIwYzdmZjMzM2RhMzVhMDYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kB_N2RI6Bw1rYQskmNyx1l1ve07s9MXpDZISlQw0og4)
> 
> **Addresses** DEFIL: f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea NDLABS: f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+f02519046

**Comment by kevzak** [comment]
> ![c](https://private-user-images.githubusercontent.com/126061227/307297222-aa5ee7d0-791c-4556-bd8e-ee7089d3195d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTU2NjUsIm5iZiI6MTcwODY5NTM2NSwicGF0aCI6Ii8xMjYwNjEyMjcvMzA3Mjk3MjIyLWFhNWVlN2QwLTc5MWMtNDU1Ni1iZDhlLWVlNzA4OWQzMTk1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMzM2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDBjOTg5ZDM4NDYzYzY5ZWE2YmZhOTc0ODIyYzg0NTgwOGE5NTkzNjIyMTc4YjU2NjAyNzMwYWQ4M2MxMjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HJ4m-iiQLLqNTfjN6wD02vZ-ApQO73cSwDSWADdaFXE)
> 
> **Addresses** Fei Yan - Kernelogic: f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa New Web Group: f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+f02223359

**Comment by kevzak** [comment]
The two that do not exist are 
5619
Addresses used
FILWallet: f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
ORIGIN Storage: f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga

5993
Addresses used
Tim Guo: f1yslbnnqzrjlyuxsmyxfbqcc7xthcavgpripjevi
New Huo Pool: f16karfxq7lxdy7izqrzrk75jf3not34k6sg6zvcy

cc @galen-mcandrew 
thanks @TrueBlood1

**Comment by Chris00618** [comment]
> > More found:
> > ![a](https://private-user-images.githubusercontent.com/126061227/307295799-05fc9dd6-73af-4f72-abfa-b2fa3ff7afcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTU2NjUsIm5iZiI6MTcwODY5NTM2NSwicGF0aCI6Ii8xMjYwNjEyMjcvMzA3Mjk1Nzk5LTA1ZmM5ZGQ2LTczYWYtNGY3Mi1hYmZhLWIyZmEzZmY3YWZjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMzM2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDFmZmM3YTc0NmE0ZTM0NWVlNTc3ZWZkNmY3YzgyNzUzMmZjNDgzZTNmZGM5MWNmYjBmMWU4N2YxMzFjOTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ETEEjMURcvFibcNk0o5MyWePi0hzQztVGZeeRA6S4Pc)
> > **Addresses** Fei Yan - Kernelogic: f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa Genesis: f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
> 
> That's weird, even though showing unknown I found this one using f address: [#1101 (comment)](https://github.com/filecoin-project/notary-governance/issues/1101#issuecomment-1961105048)

That's because you're not familiar enough with the github platform, which often automatically deletes records and account information. 

You should be focusing on records that clearly store junk data (like solana snapshots, etc), this time you're mistaken about what the point is again.  @kevzak
