### ISSUE TITLE
v5 Notary Allocator Application: FIDL Removal Notary #1

### ISSUE THREAD

**Issue by willscott** [filecoin-project/notary-governance#1105]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name: FIDL Removal Notary Number 1
3. Organization Name: FIDL
4. On-chain address for Allocator: f1v7bulqmf3llgq5g7mvjiuiqmrsznirwqxr3fq7q
5. Country of Operation (Where your organization is legally based): USA
6. Region of Operation (What region will you serve?):  Global
7. Type of Allocator, diligence process: Automated
9. DataCap requested for allocator for 12 months of activity: 32Gib

Reference: https://github.com/filecoin-project/Allocator-Governance/issues/2

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1v7bulqmf3llgq5g7mvjiuiqmrsznirwqxr3fq7q
#### Datacap Allocated
> 32 GiB

**Comment by galen-mcandrew** [comment]
@willscott these accounts are not yet initialized on-chain. They will need to receive some FIL and/or send a message to have a "create time" before they can receive DataCap.

**Comment by willscott** [comment]
Address is now funded on chain

**Comment by willscott** [comment]
This is complete 🙇
