### ISSUE TITLE
Governance will take place on March 30 1500UTC.

### ISSUE THREAD

**Issue by KwrayPL** [filecoin-project/notary-governance#111]
Our next Governance will take place on March 30 1500UTC.

To ensure we are covering the most pressing topics and questions, opening this issue collect your input on anything that should be added to the agenda. 

Please add items into the comments below to ensure they are included on the next call.

Zoom details:
https://protocol.zoom.us/j/93414028246
Passcode: 554538

Community Calendar
https://calendar.google.com/calendar/u/1?cid=Y19rMWdrZm9vbTE3ZzBqOGM2YmFtNnVmNDNqMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/issues/94

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/issues/105 @NSC-FIL we should discuss this tomorrow

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/issues/100

**Comment by dkkapur** [comment]
https://youtu.be/BOLZ_iyVVaI YouTube recording for this call
