### ISSUE TITLE
Governance to take place on April 13 at 2300UTC.

### ISSUE THREAD

**Issue by KwrayPL** [filecoin-project/notary-governance#112]
Our next Governance will take place on April 13 at 2300UTC.

To ensure we are covering the most pressing topics and questions, opening this issue collect your input on anything that should be added to the agenda.

Please add items into the comments below to ensure they are included on the next call.

Zoom details:
https://protocol.zoom.us/j/93414028246
Passcode: 554538

Community Calendar
https://calendar.google.com/calendar/u/1?cid=Y19rMWdrZm9vbTE3ZzBqOGM2YmFtNnVmNDNqMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/issues/94

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/issues/114

**Comment by dkkapur** [comment]
#103, #104, #105, #109

**Comment by KwrayPL** [comment]
Link to Deck: https://docs.google.com/presentation/d/1cqoSD5-G-5nSR5v8OjADGGo9XprdK3OpnO9yIbIwIfw/edit#slide=id.g9e888c97ec_0_321

**Comment by KwrayPL** [comment]
Link to video:   2021.04.13   

https://protocol.zoom.us/rec/share/esTR37GrUwCGP_LJo0HrGWxQzjcTn37qPU57I52FlgddVTOS08CuaOrxlXVnt4uB.a3vbdWTkI19i1kZu 

Passcode: skd&SY92

**Comment by KwrayPL** [comment]
Link to Public Youtube Video: https://www.youtube.com/watch?v=BIvFtwCeOjU&list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx&index=5
