### ISSUE TITLE
Modification: Notary allocation address change - fixing Blotocol Japan's DataCap allocation address (2)

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/notary-governance#113]
In line with https://github.com/filecoin-project/notary-governance/issues/106 - 

Using this issue to track step 2 of the fix:
> Set DataCap allocation of f1fh53sdaie3yi25qxwcqxpt5h4naex5ibdaffibi to 10TiB.

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1fh53sdaie3yi25qxwcqxpt5h4naex5ibdaffibi
#### Datacap Allocated
> 10TiB

**Comment by MasaakiNawatani** [comment]
Hi @dkkapur, 

I just checked this now, I still don't see the 10 TiB allocated to my address. Please see attached screenshot. 
![image](https://user-images.githubusercontent.com/75875000/113407441-e130e480-93df-11eb-83c4-5c2351eeabb5.png)

**Comment by dkkapur** [comment]
@MasaakiNawatani - need RKHs to sign the latest message to get it on chain. This is the last step to get the DataCap allocated correctly. Thanks!

**Comment by dkkapur** [comment]
@MasaakiNawatani - you should be good to go!
