### ISSUE TITLE
Modification: Notary allocation change - fixing MathWallet's DataCap allocation (2)

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/notary-governance#114]
## Issue Description
The DataCap allocation for MathWallet Notary did not work since the address requested to be notarized had received DataCap in the past. 

## Impact
Despite the attempt to grant DataCap to MathWaller Notary address in #107, MathWallet Notary is still unable to allocate DataCap to Clients.

## Proposed Solution(s)
Allocate 10TiB of DataCap to Notary address `f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja`

## Related Issues
#107

**Comment by dkkapur** [comment]
@rayshitou can you confirm that this address is correct and has not received any DataCap in the past?

**Comment by rayshitou** [comment]
@dkkapur  yes, it's correct and not received any DataCap in the past.

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### Datacap Allocated
> 10TiB

**Comment by dkkapur** [comment]
@rayshitou - RKHs reported back that they cannot sign this transaction since the address is not initialized on chain. Easiest way to do this is to send it a small amount of FIL to get it correctly initialized. Can you do this?

**Comment by rayshitou** [comment]
@dkkapur - I have sent a little FIL to this address. https://filfox.info/en/message/bafy2bzaceb32xbp464ou6dyu2mcxx47d7sglrydc3ljwjkgazr7f3tqtmwnry

**Comment by dkkapur** [comment]
@rayshitou can you confirm that this is good to go?

**Comment by rayshitou** [comment]
Yea, I can see DataCap at http://plus.fil.org/ now, I will give a feedback when the allocation to client is successful. 
The previously reviewed client canceled their application.

**Comment by dkkapur** [comment]
@rayshitou sounds good. Thanks! Will close this out for now and we can open another issue if additional steps are required.
