### ISSUE TITLE
Governance to take place on April 27 at 1500UTC.

### ISSUE THREAD

**Issue by KwrayPL** [filecoin-project/notary-governance#115]
Our next Governance will take place on April 27 at 1500UTC.

To ensure we are covering the most pressing topics and questions, opening this issue collect your input on anything that should be added to the agenda.

Please add items into the comments below to ensure they are included on the next call.

Zoom details:
https://protocol.zoom.us/j/93414028246
Passcode: 554538

Community Calendar
https://calendar.google.com/calendar/u/1?cid=Y19rMWdrZm9vbTE3ZzBqOGM2YmFtNnVmNDNqMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t

**Comment by dkkapur** [comment]
Confirming ready for next steps: #109

**Comment by dkkapur** [comment]
#104 - https://github.com/filecoin-project/notary-governance/pull/116

**Comment by dkkapur** [comment]
#94 - confirm next steps

**Comment by dkkapur** [comment]
For notary elections: #118, #117, and additional related issues

**Comment by dkkapur** [comment]
#98 for open discussion

**Comment by dkkapur** [comment]
Recording up here: https://www.youtube.com/watch?v=-XKZAPbvKUg
