### ISSUE TITLE
Modification: Notary selection process - selecting notaries based on number per region or DataCap required per region

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/notary-governance#117]
## Issue Description
In the Governance Call on 2021-04-13, it was raised that having a target number of Notaries per region may not be the most effective form of ensuring good DataCap coverage for clients. We may instead want to discuss the alternative of meeting DataCap projections per region. 

## Impact
In the previous election cycle, EU ran out of available DataCap a lot sooner than the other regions. Though this was circumstantial, and Notaries from other regions were able to cover - it does raise the flag that Notary DataCap grants for allocations may need to be better aligned with demand in the individual region.

## Proposed Solution(s)
TBD

**Comment by dkkapur** [comment]
In the initial round of Notary elections, < 2 PiB of DataCap was distributed, of which ~75 applications were granted in the [Client Onboarding repo](https://github.com/filecoin-project/filecoin-plus-client-onboarding). From these, here are some rough notes (please excuse me for errors in this manual tracking of the data):

| Region | Number of applications | DataCap allocated (in TiB) |
| ----- | -- | -- |
| Africa | 0 | 0 |
| Europe | 16 | 75.1 |
| Greater China Region | 38 | 270.36 |
| North America | 16 | 77.2 | 
| Oceania | 0 | 0 |
| Asia - GCN | 4 | 8.12 |
| South America | 0 | 0 |

Based on this - of the ~430.8 TiB across 74 applications: 
| Region |  % of applications | % of DataCap allocated |
| ----- | -- | -- |
| Europe | 22% | 17% |
| Greater China Region | 51% | 63% |
| North America | 22% | 18% | 
| Asia - GCN | 5% | 2% |

However - please note that this is not necessarily a great indicator of demand for DataCap since it only reflects the applications that were accepted rather than the total requests that were made. Additionally - we saw clients apply to notaries in other regions as well, which in many cases yielded a successful allocation. 

From the first round of notary grants (1,954 TiB): 
| Region |  DataCap granted to notaries (in TiB) | % of DataCap granted |
| ----- | -- | -- |
| Europe | 210 | 11% |
| Greater China Region | 1,324 | 67.5% |
| North America | 400 | 20.5% |
| Asia - GCN | 20 | 1% |

There's roughly about 1.4 PiB of DataCap still remaining. If we were to increase the circulating DataCap supply substantively, we should consider granting at least the amount that was granted before = >2 PiB. (Please note that #94 is also in active development and there should be a path here for large datasets to be served in the next few weeks.)

If we target total DataCap created (granted/allocated/in deals) = 5 PiB: 

| Region |  Target % total DataCap granted | Target DataCap (in TiB) | Current remaining DataCap | Allocated in this round of elections |
| ----- | -- | -- | -- | -- | -- |
| Europe | 20% | 1024 | 8.52 | ~1016 TiB |
| Greater China Region | 40% | 2048 | 999 | ~1049 TiB |
| North America | 20% | 1024 | 234 | ~790 TiB |
| Asia - GCN | 10% | 512 | 8 | ~504 TiB |
| Africa | 0-10% | < 512 TiB | 0 | < 512 TiB | 
| Oceania | 0-10% | < 512 TiB | 0 | < 512 TiB | 
| South America | 0-10% | < 512 TiB | 0 | < 512 TiB | 

Variance for applications across regions is high - 31 unique applications were filed for the last election, of which 14 were selected with an attempt to get 3 notaries in each region. If we see a lot of new notaries coming in, this could mean ~5-10 notaries in regions like Greater China, EU, NA. The Fil+ ecosystem is still relatively young, and time-to-datacap is high, having more notaries will generally improve maturing the program as well as delivering value through Filecoin faster. 

Based on this, proposing that we do the following: 

* Increase target notary count per region to 5 for EU, NA, GCR (SA, Asia-GCN, Oceania, South America stay at 3)
* Set max notary count for any region at 7
* Select number of notaries per region based on meeting target notary count, and if that does not bring the region past the expected allocation DataCap from this round (last column in the table below), add notaries till we reach 7.

**Comment by KodaRobotDog** [comment]
I totally agree with this new strategy.

**Comment by dkkapur** [comment]
Closing this out for now, will revisit for next election cycle.
