### ISSUE TITLE
Second round of Notary elections

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/notary-governance#118]
**Update: Elections are open! Current window to submit an application is from May 11 - May 25**

Proposing that we open up applications for the next round of Notary elections. 

Tentative timeline for this could be:
- Applications open: May 3 - May 17
- Application scoring and additional follow-up: May 18 - May 24
- Initial set of new Notaries announced at Governance call on May 25

Alternatively, we could wait for Fil+ day to kick of the Notary application process:
- Applications open: May 13 - May 28
- Scoring and follow-up: May 28 - June 7
- Initial set of new Notaries announced at Governance call on Jun 8

We should close on the following set of issues before proceeding: 
#78, #86, #74, #117

**Comment by dkkapur** [comment]
Note: as discussed in prior Governance calls, Notaries with existing allocations that are not seeking additional DataCap grants to allocate need not re-apply.

**Comment by KodaRobotDog** [comment]
I'd prefer the latter:

Applications open: May 13 - May 28
Scoring and follow-up: May 28 - June 7
Initial set of new Notaries announced at Governance call on Jun 8

**Comment by flyworker** [comment]
Have we decided when to start?
Thanks.

**Comment by dkkapur** [comment]
@flyworker - yes! Updated the original issue description. Applications are open till May 25

**Comment by dkkapur** [comment]
The following list of notaries is currently proposed to be elected: 

| Region | Notary | Application | Unrounded score | Notes |
| --- | --- | --- | --- | --- |
| Asia-GCN | 12ships Foundation | https://github.com/filecoin-project/notary-governance/issues/180 | 1.9 | |
| Asia-GCN | MathWallet | https://github.com/filecoin-project/notary-governance/issues/123 | 1.8 | |
| Asia-GCN | Masaaki Nawatani | https://github.com/filecoin-project/notary-governance/issues/131 | 1.7 | |
| Europe | Filecoin Foundation | https://github.com/filecoin-project/notary-governance/issues/187 | 3.2 | Pending region confirmation |
| Europe | Julien NOEL / Twinquasar | https://github.com/filecoin-project/notary-governance/issues/136 | 1.7 | |
| Europe | Nicklas Reiersen / TechHedge | https://github.com/filecoin-project/notary-governance/issues/186 | 1.2 | |
| Europe | Speedium | https://github.com/filecoin-project/notary-governance/issues/122 | 1.2 | |
| GCR | Fenbushi Capital | https://github.com/filecoin-project/notary-governance/issues/138 | 3.4 | |
| GCR | 1475 - Simon686 | https://github.com/filecoin-project/notary-governance/issues/172 | 3.2 | Pending fixes to application and confirmation of bookkeeping plan |
| GCR | IPFSFORCE - Steven Li | https://github.com/filecoin-project/notary-governance/issues/158 | 2.7 | Pending clarification of potential dispute / missing allocation |
| GCR | IPFSMain - Neo Ge | https://github.com/filecoin-project/notary-governance/issues/168 | 2.6 | |
| GCR | IPFSUnion - Steve Song | https://github.com/filecoin-project/notary-governance/issues/135 | 2.4 | |
| GCR | ByteBase | https://github.com/filecoin-project/notary-governance/issues/169 | 2.4 | |
| GCR | Wise R&D Center - waynewyang | https://github.com/filecoin-project/notary-governance/issues/178 | 2.4 | |
| NA | XnMatrix | https://github.com/filecoin-project/notary-governance/issues/150 | 2.6 | |
| NA | Performive | https://github.com/filecoin-project/notary-governance/issues/132 | 2.1 | Pending response on potential dispute / missing audit information |
| NA | Koda Inc. | https://github.com/filecoin-project/notary-governance/issues/153 | 1.7 | |
| NA | Filswan NBFS | https://github.com/filecoin-project/notary-governance/issues/157 | 1.4 | |
| NA | SECUREXPERTS Inc. | https://github.com/filecoin-project/notary-governance/issues/164 | 0.9 | |
| Oceania | Holon Innovations | https://github.com/filecoin-project/notary-governance/issues/130 | 2.2 | |

**Comment by dkkapur** [comment]
Updated per latest discussions:

The following list of notaries is currently proposed to be elected: 

| Region | Notary | Application | Unrounded score | Notes |
| --- | --- | --- | --- | --- |
| Asia-GCN | 12ships Foundation | https://github.com/filecoin-project/notary-governance/issues/180 | 1.9 | |
| Asia-GCN | MathWallet | https://github.com/filecoin-project/notary-governance/issues/123 | 1.8 | |
| Asia-GCN | Masaaki Nawatani | https://github.com/filecoin-project/notary-governance/issues/131 | 1.7 | |
| Europe | Filecoin Foundation | https://github.com/filecoin-project/notary-governance/issues/187 | 3.2 | |
| Europe | Julien NOEL / Twinquasar | https://github.com/filecoin-project/notary-governance/issues/136 | 1.7 | |
| Europe | Nicklas Reiersen / TechHedge | https://github.com/filecoin-project/notary-governance/issues/186 | 1.2 | |
| Europe | Speedium | https://github.com/filecoin-project/notary-governance/issues/122 | 1.2 | |
| GCR | Fenbushi Capital | https://github.com/filecoin-project/notary-governance/issues/138 | 3.4 | |
| GCR | 1475 - Simon686 | https://github.com/filecoin-project/notary-governance/issues/172 | 3.2 | Pending fixes to application |
| GCR | IPFSFORCE - Steven Li | https://github.com/filecoin-project/notary-governance/issues/158 | 2.7 | |
| GCR | IPFSMain - Neo Ge | https://github.com/filecoin-project/notary-governance/issues/168 | 2.6 | |
| GCR | IPFSUnion - Steve Song | https://github.com/filecoin-project/notary-governance/issues/135 | 2.4 | |
| GCR | ByteBase | https://github.com/filecoin-project/notary-governance/issues/169 | 2.4 | Pending response on "duration" over which sustained contributions were made to the ecosystem |
| GCR | Wise R&D Center - waynewyang | https://github.com/filecoin-project/notary-governance/issues/178 | 2.4 | |
| GCR | Binghe Distributed Storage Lab | https://github.com/filecoin-project/notary-governance/issues/149 | 2.4 | |
| NA | XnMatrix | https://github.com/filecoin-project/notary-governance/issues/150 | 2.6 | |
| NA | Performive | https://github.com/filecoin-project/notary-governance/issues/132 | 2.1 | Pending response on potential dispute / missing audit information |
| NA | Koda Inc. | https://github.com/filecoin-project/notary-governance/issues/153 | 1.7 | |
| NA | Filswan NBFS | https://github.com/filecoin-project/notary-governance/issues/157 | 1.4 | |
| NA | SECUREXPERTS Inc. | https://github.com/filecoin-project/notary-governance/issues/164 | 0.9 | |
| Oceania | Holon Innovations | https://github.com/filecoin-project/notary-governance/issues/130 | 2.2 | |

**Comment by dkkapur** [comment]
The following list of notaries is currently proposed to be elected to the RKH: 

| Region | Notary | Application link | DataCap grant | Address on chain |
| --- | --- | --- | --- | --- |
| Asia-GCN | 12ships Foundation | https://github.com/filecoin-project/notary-governance/issues/180 | 100TiB | f1inc6lx4oosssdf5n7rkt45rtwzlip7ohott7vha |
| Asia-GCN | MathWallet | https://github.com/filecoin-project/notary-governance/issues/123 | 100TiB | f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja |
| Asia-GCN | Masaaki Nawatani | https://github.com/filecoin-project/notary-governance/issues/131 | 100TiB | f1fh53sdaie3yi25qxwcqxpt5h4naex5ibdaffibi |
| Europe | Filecoin Foundation | https://github.com/filecoin-project/notary-governance/issues/187 | 1PiB | _awaiting acceptance of notary status_ |
| Europe | Julien NOEL / Twinquasar | https://github.com/filecoin-project/notary-governance/issues/136 | 100TiB | f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii |
| Europe | Nicklas Reiersen / TechHedge | https://github.com/filecoin-project/notary-governance/issues/186 | 10TiB | f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq |
| Europe | Speedium | https://github.com/filecoin-project/notary-governance/issues/122 | 10TiB | f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa |
| GCR | Fenbushi Capital | https://github.com/filecoin-project/notary-governance/issues/138 | 1PiB | f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq |
| GCR | 1475 - Simon686 | https://github.com/filecoin-project/notary-governance/issues/172 | 1PiB | f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a |
| GCR | IPFSFORCE - Steven Li | https://github.com/filecoin-project/notary-governance/issues/158 | 1PiB | f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna |
| GCR | IPFSMain - Neo Ge | https://github.com/filecoin-project/notary-governance/issues/168 | 1PiB | f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa |
| GCR | IPFSUnion - Steve Song | https://github.com/filecoin-project/notary-governance/issues/135 | 100TiB | f1enfilmuyphmnqexjt33zfbk56c25mo2lplgbpxa |
| GCR | ByteBase | https://github.com/filecoin-project/notary-governance/issues/169 | 100TiB | _waiting for address_ |
| GCR | Wise R&D Center - waynewyang | https://github.com/filecoin-project/notary-governance/issues/178 | 100TiB | _awaiting acceptance of notary status_ |
| GCR | Binghe Distributed Storage Lab | https://github.com/filecoin-project/notary-governance/issues/149 | 100TiB | f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi |
| NA | XnMatrix | https://github.com/filecoin-project/notary-governance/issues/150 | 1PiB | f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a |
| NA | Performive | https://github.com/filecoin-project/notary-governance/issues/132 | 100TiB | f13vzzb65gr7pjmb2vsfq666epq6lhdbanc4vfopq |
| NA | Koda Inc. | https://github.com/filecoin-project/notary-governance/issues/153 | 100TiB | f1jyalts5uhtmp5sbbssse23toshvsqbbtjgukm5a |
| NA | Filswan NBFS | https://github.com/filecoin-project/notary-governance/issues/157 | 10TiB | f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy |
| NA | SECUREXPERTS Inc. | https://github.com/filecoin-project/notary-governance/issues/164 | 10TiB | f1bjdcjxha3ldcstw5zmvkyu3r2p5x2bsm745kgsi |
| Oceania | Holon Innovations | https://github.com/filecoin-project/notary-governance/issues/130 | 100TiB | _awaiting address_ |

**Comment by oldtimeroad** [comment]
When will the third round of notary elections start?
Thanks
