### ISSUE TITLE
Notary Application: Anwen Web3 Lab

### ISSUE THREAD

**Issue by askender** [filecoin-project/notary-governance#12]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Anwen Web3 Lab
- (Optional) Affiliated Organization: 
- Website / Social Media:  @askender on the Filecoin Slack
- On-chain Address(es) to be Notarized: f1iugbjhypzyhhi6ymc6vnab5uj7re5y56km52rky
- Region of Operation: Greater China
- Use case(s) to be supported: User Content (Personal Storage, User Generated Media)
- DataCap Requested: 100TB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
- As an individual, I joined Filecoin Community from 2019 November because I like IPFS and Web3, and I also join in all test phrase as a storage miner.
- Running miner :  f07998 f019362
- Actively participating on slack (more than 1k messages) and 10+ github issues
- Participating to HackFS/ SR1 / SR2 Orbital burn / Slingshot 1 (project Anwen-Web3-Content-Community) / program
- Github handles: askender
- Got Filecoin Slingshot Communtiy Call-out Award, https://anwen.cc
- I build a team of 2 menber now. And we’ve been applied for Filecoin Frontier Accelerator
- Start create a company focus on web3 content ecology
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
- locked as collateral, vesting over time: 753.1666+151.3000=904.4666 FIL
- Space Race Award currently available: 196 FIL
Evidence:
- https://calibration.filfox.io/zh/address/t07998
- https://calibration.filfox.io/zh/address/t019362
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- Actively participating and helping the Filecoin miner community (more than 1k messages on slack)
- Participating to HackFS/ SR1 / SR2 Orbital burn / Slingshot 1 (project Anwen-Web3-Content-Community) / program
- report bugs and other issues: https://github.com/filecoin-project/lotus/issues/created_by/askender
- Make pull-request:  https://github.com/filecoin-project/rust-fil-proofs/pull/1253#pullrequestreview-463834037
- https://github.com/filecoin-project/lotus/pulls/askender strange, my unmerged PR is disappeared (magik6k told me he wrote a better version).
- Filecoin Slingshot community call-out award winner.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
bugs may make miners waste Filecoin or time:
- https://github.com/textileio/powergate/issues/653#issuecomment-727733577
- https://github.com/filecoin-project/lotus/issues/4843
- https://github.com/filecoin-project/lotus/issues/3096 got fixed
- https://github.com/filecoin-project/lotus/issues/4118 got fixed
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
As a NLP researcher
- I published several papers accepted by some top academic conferences.   
- Core member of the champion team in 2018 Conference on Machine Translation (WMT18)

As a startup:
I have been preparing for fulltime-startup and running a content website since 2012.
I have been quitted my job in Alibaba Damo Academy as a NLP algorithm engineer and start focus on Web3 ecology. I am praparing for creating a company（will register soon）in China, with 2 full-time member(including me), to support content ecology, Web3 and IPFS/Filecoin.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
google scholar : https://scholar.google.com/citations?user=tzIrta0AAAAJ&hl=zh-CN
site : https://anwen.cc
linkedin : https://www.linkedin.com/in/askender-li-27059265/
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Please answer here.
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
User Content (Personal Storage, User Generated Media) & Web 3.0 / Decentralized Applications

We are keep build decentralized content platform/community which rewards content(such as articles/videos/datasets/links) creators and sharers with Filecoin. And We help store and spread valuable content in IPFS/Filecoin to avoid 404.
I like to create a more decentralized web and world. I think I can also help make Filecoin more decentralized.
I like the idea of Creative-Commons and RSS, and I am trying to make the content ecology more open.
I am writing the next generation RSS 3.0 protocol which will also include incentive mechanism for creators.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
Our strategy for the our Phrase 1: 
- Data should be licenced under Creative Commons and offer the IPFS links
- People make pull-requests to allocate the DataCap requested
- Reputation of organization is also considered
- Community contribution of organization is also considered
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
I will write a python script to parse the github-repo-pull-requests.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
I will be the only one accessing the key and the server.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
Only Creative Commons articles/videos are welcome for the phrase 1, and all data is publicly accessible.
Ask them for evidence on how they allocate the DataCap before unlocking the rest of the dataCap. 
The principles:
   - help to make the data more useful to others
   - make the content more diversity
   - prevent abusement
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
Is the dataset/articles/videos licensed under Creative Commons?
Will you offer the list of those data licensed under Creative Commons?
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
We will check all the datacid to ensure Clients are properly allocating their DataCap.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Yes, I plan on keeping records of our allocation decisions via a github repo.
We are open to any audit requests.

```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we conduct our allocation decisions in public using Github repo and IPFS.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None
```

**Comment by dkkapur** [comment]
@askender - thanks for your application to be a Notary, please see the scored rubric here: 
https://docs.google.com/spreadsheets/d/19AUBDzHDoqe6gvkb44XL5vPjLVDzOtm8Oy6L4Fb02xU/edit?usp=sharing

A few points: 
- You mentioned in your application that you are planning to register the company; if there are any updates on this, please do share since that will impact row 11 on the rubric (score should increase from 0 -> 1, especially since you already have a website which has been recognized)
- Your process for handling applications seems to be via GitHub. Please share additional details on how you plan on doing this (which repo,  what steps clients need to take to apply for DataCap, etc.). If you plan on using the same application/repo as the Filecoin Foundation is using for their allocations instead, that is fine as well (this will be scored as a 3 on the rubric). 
- For checking that DataCap allocation is being spent appropriately, you mention that you would like to verify the CIDs - are you planning on building a tool for automating this? If so - would you also consider Open Sourcing this tool? 

Also, please note that there is a proposed rubric change what would require us to rescore applications (#36)

**Comment by askender** [comment]
Yes. I have registered a company recently named Wuhan Qingyunyao Network Technology Company. 
  https://www.tianyancha.com/company/4045734592  

I plan on using the same application/repo as the Filecoin Foundation is using for their allocations instead.

> For checking that DataCap allocation is being spent appropriately, you mention that you would like to verify the CIDs - are you planning on building a tool for automating this? If so - would you also consider Open Sourcing this tool?
Yes, I will build and open-source this tool.

**Comment by jnthnvctr** [comment]
Hi @askender - we've taken a pass at scoring your application: https://docs.google.com/spreadsheets/d/1FsRK-vNXOMmc5gdFaRNQYVPjVjdCKhd654l9R9HYCsM/edit?usp=sharing

Eligibility score: 2
Unrounded score: 1.7

**Comment by jnthnvctr** [comment]
Apologies, sorry I think you were the victim of me trying to bulk edit the status label!

Thank you for submitting - hope you're able to join the governance call later today!

**Comment by dkkapur** [comment]
@askender - just wanted to let you know that Notary applications are currently open again until May 25. In case you'd be interested in applying again, please create a new Issue of type "Notary Application" and fill in the form (it is completely reasonable to reuse material from your prior application).
