### ISSUE TITLE
 Governance call to take place on May 11 at 1600 UTC

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/notary-governance#120]
Our next Governance will take place during [Filecoin Plus Day](https://filecoinfoundation.medium.com/join-us-for-filecoin-plus-day-a06b9c4acf85) around 1600 UTC time.

To ensure we are covering the most pressing topics and questions, opening this issue collect your input on anything that should be added to the agenda.

Please add items into the comments below to ensure they are included on the next call.

Zoom details:
https://protocol.zoom.us/j/93414028246
Passcode: 554538

Community Calendar
https://calendar.google.com/calendar/u/1?cid=Y19rMWdrZm9vbTE3ZzBqOGM2YmFtNnVmNDNqMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t

**Comment by dkkapur** [comment]
#117, #118

**Comment by dkkapur** [comment]
#119 - @LandsatFile20 if you are able to join the call and would like to discuss further!

**Comment by dkkapur** [comment]
#94

**Comment by bashenanan** [comment]
verygood？

**Comment by dkkapur** [comment]
Governance call recording is available on YouTube [here](https://www.youtube.com/watch?v=msGELmevm-8&list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx&index=7)
