### ISSUE TITLE
Speedium

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/notary-governance#122]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Wijnand Schouten
- Affiliated Organization: Speedium
- Website / Social Media: www.speedium.network
- On-chain Address to be Notarized: f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
- Region of Operation: Europe
- Use case(s) to be supported: Personal user storage, scientific datasets, video & music.
- DataCap Requested: 250 TB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
As an individual, I have worked as a crypto miner and programmer / developer for over 4 years. 
I’ve been a part of the Filecoin community since 2020 and founded Speedium in 2019 together with Hidde.
I am also one of the MinerX community members who are helping to make Filecoin better and grow.

As an organization, Speedium is a leading Usenet Service Provider. We have made many steps in onboarding data to the filecoin network and have worked with many notaries ( Phillip , Neowebg3, and AndrewHill ). Speedium is aiming to bring our populair cache to the filecoin network, decentralising the Usenet space and improving the enduser experience.

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
6000 FIL ( See f01240 )
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We are an active MinerX member, helping to onboard members and improve and strengthen the Filecoin network. We have made substantial input on github improving dealmaking and reporting bugs. As a usenet organization, Speedium has been engaged with blockchain technology since day one. We are extremely interested in all sorts of decentralized storage and have been experimenting with multiple blockchain storage projects since 2019. Since the launch of Filecoin we have been participating in Testnet, Spacerace 1, Spacerace 2 and Mainnet. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
In 2019, Hidde and I (aka "Hidde / Wijnand Schouten") introduced Blockchain storage on our website Speedium.network, actively promoting the possibility that it can be done. With this believe we started to be involved in the Filecoin community and have been engaging parties to join us to invest. 

Since the beginning of testnet we have filed multiple bug reports on Git under my handle cryptowhizzard.
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Speedium ( https://speedium.network ) is the first Blockchain Usenet Platform. We operate our own fully independent backbone ( IPV4/IPV6 ) and Usenet storage.
Currently we are connected with 30 Gb/s with multiple exchanges like Speed-IX / NL-IX proving extreme low latency and high speed transfers throughout Europe.
To find more statistics on how we are connected, see peedingdb.com/net/23120. 
We are currently providing our peering partners with a combined Usenet feed of +/- 140 TB daily and we are fully storing this for over a month in our spool arrays.
We are a Dutch usenet provider and we are operating with three board members, fully operational since 2019.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Speedium ( https://speedium.network ) is the first Blockchain Usenet Platform. We operate our own fully independent backbone ( IPV4/IPV6 ) and Usenet storage.
Currently we are connected with 30 Gb/s with multiple exchanges like Speed-IX / NL-IX proving extreme low latency and high speed transfers throughout Europe.
To find more statistics on how we are connected, see peedingdb.com/net/23120. 
We are currently providing our peering partners with a combined Usenet feed of +/- 140 TB daily and we are fully storing this for over a month in our spool arrays.
We are a Dutch usenet provider and we are operating with three board members, fully operational since 2019.


```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Organisation: Speedium
Website: https://speedium.network
founded in 2019 
headquartered in Oudkarspel
Number of employees: 4
Discord: https://discord.gg/2hxXZBS
Telegram: https://t.me/speedium
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We plan to support multiple use cases; the percentage will be determined by my knowledge and usage expectation, 
which may vary depending on the variable circumstances of each scenario and different regions. 
- 35% - user content (personal user storage)
- 25% - scientific datasets (AI training, geological data, autonomous driving) 
- 40% - media & entertainment (video & music)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
Similar to Philip and NeowebG3 strategy, We plan on setting up thresholds with varying degrees of trust. 
These guidelines can serve as a tool of assessment and further add a level of consistency across the board. 
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
We will do a duedilligence procedure and intent to only onboard registred company's who are audited.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
On a ledger / hardware wallet.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
We intend to work on principles of limited thrust and we only onboard requests where agreements are made to who the verified data will be send with the respective ratios. Below is the proposed procedure of Due Diligence. We need 3 types of information for review depending on the volume of clients required Due Diligence:
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information; 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name;
 - date of birth; 
 - street address (P.O. box number is not acceptable); 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle) 
2. What is your use case for the DataCap being requested? 
3. What is the Filecoin address you would like me to allocate the DataCap? 
4. How much DataCap would you like to request? 
For organizational clients: 
5. What is the name, nature, registration country, time since inception, and named officers of your organization? Please link to relevant websites. 
6. In which region do you intend to use the DataCap? If you intend to use the DataCap in multiple regions, please specify. 
7. How many miners do you plan on allocating a DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
8. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
*9. Have you previously received DataCap? If so, please share some details on how you spent the previous allocated DataCap in terms of question number 6, 7 & 8. 
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Prospective clients are encouraged to allocate the DataCap to more than 3 to 5 different miners, 
which not only increases storage redundancy but also helps maintain decentralization and reduce the possibility of potential misuse. The more miners clients allocate, the more DataCap clients are likely to get. 
Notaries will be able to ask the client about their intentions through question# 7 for the first allocation, 
and further verify this through question# 9 during the next allocation. 
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Yes, all allocation decisions will be guided by the rubric publicly on Github. So are all communications. 
Since all interactions are intended to occur publically, most of the allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly in the Github repo first. 
If convincing justifications can’t be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions. 
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be conducted in the Github repository. 

```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
no
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
-
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
No
```

**Comment by dkkapur** [comment]
Hi @cryptowhizzard - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1a4PihfKrG9Z3ow-33a2H4Gl9Vi_2_tDzYPvjZwKpnUo/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.2.

**Comment by cryptowhizzard** [comment]
Hello @dkkapur 

Thanks for taking time to score our application.

Line 10: 
We have handed out multiple times the issue that miners could be DOS'd by sending (retrieval) deals from client to miner causing the miner to jam and skip W-Post. I have also tracked tickets on Github with DirkMC @ git and offered temporary solutions ( With timeout settings ).

Line 11:
With Speedium as onboarding client we are actively working on onboarding our populair Usenet Cache data on the filecoin network. We will be working during the summer / as soon as there is a stable datacap stream on plugins for SABNZB so (Speedium's) endusers can download this cache data directly from the filecoin network greatly improving their enduser's experience. So I guess this should be L2 indeed.

Line 12:
We can utilize our Twitter and Facebook and E-mail lists of Speedium and notify our user base that we are actively engaged in filecoin. So we confirm that we can share more about Filecoin Plus on our Twitter and Facebook account. These accounts have approximately 1400 users.

Line 22:
For each application we will ask where the datacap will be stored (The specified miners) and we will put this in an agreement public available on Github. We will only accept verified miners to store data on so we can actively monitor the selfdealing ratio and also make sure that the probability of data being available in later stages is high. We will be actively monitoring each allocation with the tools f.e. build by Ribasushi to check if all deals are made according to the predefined agreement and send to the miners agreed upon. Changes upon this agreement can be made (in case of a miner going out of business) but this has to be communicated @ GitHub together with the replacement miner (if any) so we can agree upon this.

**Comment by dkkapur** [comment]
@cryptowhizzard thanks for sharing your comments, addressing them here:
- Line 10: These are counted towards in Line 9; Line 10 is specific to security vulnerabilities that were reported through the Filecoin Security Program / Bug bounty program
- Line 11: Post the work that you do this summer - I think if your presence in the Usenet community is substantial, then agree that moving forward, this should be at L2. However at this point in time, it seems like L1 is still correct. 
- Line 12: Twitter account (https://twitter.com/speedium_netwrk) shows less than 500 followers, hopefully I'm looking at the right one. For this criteria to be at L1/L2, each account individually needs to be at > 500.
- Line 22: What you describe above is great for due diligence and ensuring compliance - this is why you have scored at a 5 for Line 23. What we are looking for in this criteria is that you have a clear rubric/allocation methodology that you will follow for clients that is published so they are also able to understand how to get DataCap from you. You cited using something like what a few other notaries have, but without specifying if its exactly the same or how it will differ, I cannot score you at 3 or higher for this. 

The final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 1.2

Here is the link to the updated rubric:
https://docs.google.com/spreadsheets/d/1a4PihfKrG9Z3ow-33a2H4Gl9Vi_2_tDzYPvjZwKpnUo/edit?usp=sharing

**Comment by cryptowhizzard** [comment]
Hello deep. I am going to order a new ledger today for a brand new address to be notarized on chain on advice of Julien. I will update my ticket as soon as i have received it with a new address.

**Comment by dkkapur** [comment]
@cryptowhizzard - based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of: 100 TiB. In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm that the region of operation for client applications you will focus on is [Europe]

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

> * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

> * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

> * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

5. (when your Ledger arrives) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Datacap Allocated
> 10TiB

**Comment by dkkapur** [comment]
This went through correctly
