### ISSUE TITLE
Notary Application: MathWallet

### ISSUE THREAD

**Issue by rayshitou** [filecoin-project/notary-governance#123]
# Notary Application
## Core Information
- Name: MathWallet
- Affiliated Organization: MathWallet
- Website / Social Media: mathwallet.org
- On-chain Address to be Notarized: f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
- Region of Operation: Asia-GCN
- Use case(s) to be supported: general, blockchain data, web3 dapp
- DataCap Requested: 100TB

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
MathWallet's main contribution and work in Filecoin Ecoystem includes:
* Has supported Filecoin since Testnet, and is one of the earliest wallets to support Filecoin testnet. See: http://blog.mathwallet.org/?p=1637
* Developed Filecoin App wallet. See: https://mathwallet.org/filecoin-wallet/
* Developed Filecoin custodial wallet system and Swap system.
* Runs two open Filecoin sync nodes for community use.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
N/A
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
* There are currently over 7,000 Filecoin wallets in MathWallet, with a cumulative total of over 15,000 transfers.
* We have collected and sorted various Filecoin eco-applications through our MathDAppStore for users to find and use. See: https://mathdapp.store/?blockchain=filecoin
* We provide a relevant API of Filecoin wallet, which helps DAPP developers to aggregate relevant functions. See: http://doc.mathwallet.org/en/filecoin  for developers' integration function
* We have written various Filecoin wallet operation tutorials to spread relevant knowledge to the community
For English, see: http://blog.mathwallet.org/?tag=filecoin
For Chinese, see: http://blog.mathwallet.xyz/?tag=filecoin
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
N/A
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
* MATH is a multi-chain and cross-chain blockchain assets hub whose products include:
MathWallet (supports 50+ blockchains including BTC, ETH, Filecoin etc and 1.2M users); MATH VPoS Pool, MathDAppStore, MathStaking, MathCustody, MathNFT, MathChain, MathHub, MathDEX, MathID, MathPay, and others.
Our investors includes Fenbushi Capital, Alameda Research, FundamentalLabs, Multicoin Capital.
* Registered country: Singapore
* Organization Size: 30 people
* Date of establishment: November 2017
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://mathwallet.org
https://twitter.com/mathwallet
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Official Website: https://mathwallet.org

News:
* MathWallet Raises $7.8 Million From Alameda Research and Multicoin
https://www.financemagnates.com/cryptocurrency/news/mathwallet-raises-7-8-million-from-alameda-research-and-multicoin/
* Fenbushi Capital Roundtable Series 3: MathWallet COO Eric talks about the role of Wallet in Filecoin ecosystem:
https://mp.weixin.qq.com/s/pdHYXpEDViSgjaVYXsCp2w
* The development history of wallets in China:
https://www.theblockbeats.com/news/19632
* MathWallet and Hurun Report reached strategic cooperation:
http://news.iresearch.cn/yx/2019/01/282439.shtml

Social Media:
MathNews https://news.mathwallet.xyz
MathBlog (CN) http://blog.mathwallet.xyz
MathBlog (EN) http://blog.mathwallet.org
Twitter https://twitter.com/Mathwallet
Weibo https://weibo.com/2803855662/
Medium https://medium.com/@mathwallet
Bilibili https://space.bilibili.com/526464306
Youtube https://youtube.com/c/MathWallet
Bishijie https://i.bishijie.com/home/math/dynamic
Bihu https://bihu.com/people/397093
Jinse https://www.jinse.com/member/88928
Tuoluocaijing https://www.tuoluocaijing.cn/columns/author311997/
Chainnews https://www.chainnews.com/u/748716797548.htm
Huoxing24 https://www.huoxing24.com/userCenter/360b0e7fc498439f8ade74568f96c393
Odaily https://www.odaily.com/user/2147493170
Xueqiu https://xueqiu.com/u/5676556297
Ccvalue https://www.ccvalue.cn/column/%E9%BA%A6%E5%AD%90%E9%92%B1%E5%8C%85
Jianshu https://www.jianshu.com/u/e0bab1403fe8
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We will support a variety of use cases to ensure diversity. Based on the multi-chain and cross-chain nature of MathWallet, we will focus on use cases for blockchain data storage, particularly in IPLD related application scenarios.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
In making the plan, we will consider the following factors:
* Reputation of the organization
* Scale of allocation
* Frequency allocation
* Safety Precautions
* Transparency of customers
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Our allocation priorities are:
(1)	public datasets that are easy to maintain;
(2)	Blockchain data;
(3)	Web3 data.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The key allocated to the DataCap is protected on the multi-signature hardware wallet.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
* For due diligence on public datasets, we will look for strong evidence that they have a good maintenance foundation and a high reputation in their field.
* For due diligence on blockchain data, we will investigate the authenticity and feasibility of their requirements based on our experience in the development of multi-chain wallets.
* For due diligence on Web3 data, we will use our experience in operating DappStore to investigate the DApp team, product planning and implementation.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
We will review the request according to the list of questions linked below:
https://github.com/filecoin-project/notary-governance/blob/main/notaries/templates/sample-client-application.md
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
We will ask Client to seperate DataCap to different entity.
We will review the Client status and if Client is not improperly over-allocating DataCap to a single entity, we will reject the Client's applicaiton during the next allocation.
We will publicize all requests and assignments which are subject to community’s supervision.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
All allocation decisions will be in the following Github repository, and all questions will be traceable:
(https://github.com/mathwallet/filecoin-notaries-onboarding) 
We will have focal point to answer any questions through email and telegram group.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will happen in public, at the following repository:
(https://github.com/mathwallet/filecoin-notaries-onboarding)
We will have focal point to answer any questions through email and telegram group.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes, [here](https://github.com/filecoin-project/notary-governance/issues/26)
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
10TB
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None
```

**Comment by dkkapur** [comment]
Previous applications:
- https://github.com/filecoin-project/notary-governance/issues/26

Allocation track record from last round:
- 10 TiB allocated in past round, 3 client applications in repo, 3 verified clients in dashboard currently
- list of client applications approved: https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues?q=is%3Aissue+is%3Aclosed+label%3Astate%3AGranted+sort%3Aupdated-desc+assignee%3Arayshitou

Client applications and usage of datacap: 
![image](https://user-images.githubusercontent.com/2343218/120597301-b8d26000-c3f9-11eb-9024-f3cdb13d65fb.png)

DataCap received by miner IDs:
(at this point, none of the clients have used their DataCap based on the data present here: https://filplus.d.interplanetary.one/notaries/f0689911)

**Comment by dkkapur** [comment]
Hi @rayshitou - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1baQQNZ_tNa18b6w4yxYMy3OFXP-SFNaVEOe_L3oapog/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.8.

**Comment by rayshitou** [comment]
Thank you, @dkkapur
About Individual Reputation, we have over 100,000 Twitter followers (https://twitter.com/MathWallet) and over 10,000 Telegram followers (https://t.me/mathwallet).
And bookkeeping plan, we post the allocation decisions on GitHub(https://github.com/mathwallet/filecoin-notaries-onboarding).

**Comment by dkkapur** [comment]
@rayshitou - thanks for sharing this. Based on this, the following adjustments were made: 
- Individual Reputation: 1 -> 2; assuming you can affirm that you are able to use these accounts to share info about your engagement in Filecoin, Fil+, etc. (which I believe you had confirmed in the past application)
- Bookkeeping plan: 2 -> 3, based on the link you provided.

The final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 1.8

Here is the link to the updated rubric: https://docs.google.com/spreadsheets/d/1baQQNZ_tNa18b6w4yxYMy3OFXP-SFNaVEOe_L3oapog/edit?usp=sharing

**Comment by dkkapur** [comment]
@rayshitou - as shared in the last Governance call, based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of: 100 TiB. In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm the region of operation for client applications you will focus on is [Asia minus GCN]

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

> * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

> * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

> * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**Comment by rayshitou** [comment]
@dkkapur thank you very much!


> 1. Please confirm the region of operation for client applications you will focus on is [Asia minus GCN]

       ACK.

> 2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.
> 
> > * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

           ACK.

> 
> > * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

           ACK.

> 
> > * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

           ACK.

> 
> > * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

           ACK.

> 
> > * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.
> 

           ACK.

> > * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

           ACK.

> 
> 3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

       We do not have any affiliations with any mining operations. We will disclose all client addresses if/when we get any in the future.

> 4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

      ACK.

> 5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

      ACK.

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### Datacap Allocated
> 100TiB

**Comment by dkkapur** [comment]
This went through correctly
