### ISSUE TITLE
Notary Application: Diancun 

### ISSUE THREAD

**Issue by DC-Byteark** [filecoin-project/notary-governance#124]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name:David
- Affiliated Organization: Diancun Tech
- Website / Social Media:https://diancun.net
- On-chain Address to be Notarized:f1r5idduxae7ecopashldq7ptfyj2zzskm2rojtva
- Region of Operation: Greater China
- Use case(s) to be supported: Web 3.0, User Content, Scientific Data, Media & Entertainment, Other
- DataCap Requested:100 TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Early 2018, I founded Diancun Tech, aim to become a comprehensive edge-clouding computing infrastructure service provider. 
In the meantime, IPFS, as a leading distributed storage solution, catches my eye. 
As a member of IPFS community, I am actively following the progress of IPFS, participating in and holding many offline and online activities. 
In 2020, Diancun Tech joined Filecoin Devnet, made a huge contribution to launch Filecoin Mainnet. 
In the Slingshot competition, Diancun Tech won first place in Phase 1 with the dragonfly project.

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
The total adjusted power is 104 PiB,The total available amount is about 10,729 Fil, The total initial pledge amount is about 1,155,300 Fil,The total locked rewards amount is about 519,563 Fil.
Here are some of my miner IDs, and we can sign messages with the private keys:
- f0134867 
- f086204 
- f0145060 
- f082730 
- f029585 
- f01155 
- f014699 
- f010202 
- f014686 
- f010038 
- f0130639
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
we've partitcipated proof parameters generating: https://github.com/filecoin-project/phase2-attestations/blob/master/b288702/README.md

Our team members' github handles: yaohcn, strahe, hexcola,wangyancun,Derek-zd

Ask & Discuss issues:
- https://github.com/filecoin-project/lotus/issues/1917
- https://github.com/filecoin-project/lotus/pull/4653
- https://github.com/filecoin-project/lotus/issues?q=is%3Aissue+author%3Ayaohcn

PRs
- feat(gpu): add support for NVIDIA RTX A6000.    https://github.com/filecoin-project/bellperson/pull/181
- fix health report.    https://github.com/filecoin-project/lotus/pull/6011
- fix storage reservations.     https://github.com/filecoin-project/lotus/pull/5926
- fix drop sector.     https://github.com/filecoin-project/lotus/pull/5622
- correct log in maybeUseAddress.    https://github.com/filecoin-project/lotus/pull/5359
- make addpiece configurable.     https://github.com/filecoin-project/lotus/pull/3107
- add space check in StorageFindSector.    https://github.com/filecoin-project/lotus/pull/2976
- feat: specific ipfs gateway.    https://github.com/filecoin-project/lotus/pull/514
- async connect to bootstrappers .    https://github.com/filecoin-project/lotus/pull/4785/commits
- allow paramfetch to use a specific ipfs gateway.    https://github.com/filecoin-project/rust-fil-proofs/pull/702

- https://github.com/filecoin-project/lotus/pull/1586
- https://github.com/filecoin-project/lotus/pull/3105
- https://github.com/filecoin-project/lotus/pull/3027
- https://github.com/filecoin-project/lotus/pull/4984
- https://github.com/filecoin-project/lotus/issues/6125
- https://github.com/filecoin-project/lotus/issues/5264
- https://github.com/filecoin-project/lotus/issues/5157
- https://github.com/filecoin-project/lotus/pull/5158

We helped to answer questions on the Slack channel.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
None.
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Diancun Tech is a private limited liability company, founded on August 22nd, 2018. 
It is registration in China. Right now, we have around 104 employees.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Official Website: https://www.diancun.net
WeChat Official Account: 点存科技（ipfsdiancun）
Weibo: 杭州点存科技有限公司
Tiktok China: 点存科技
https://www.zhihu.com/org/dian-cun-ke-ji
https://www.huoxing24.com/userCenter/c8b5a2ebf17e49448040649c50f43338
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://mp.weixin.qq.com/s/FCuBjunNlBYHpSoi701_Pg
http://cio.chinabyte.com/255/725706255.shtml
https://mp.weixin.qq.com/s/XlJumxLLFw9Ki-Wj_0iVaA
https://mp.weixin.qq.com/s/Dp-1Czt_dHGwLdq2xud1gA
https://server.51cto.com/Datacenter-656800.htm
https://mp.weixin.qq.com/s/rq9XNDIzUHHq9J7JRUc-LQ
http://m.cciapcb.com.cn/article/item-1757.html#10006-weixin-1-52626-6b3bffd01fdde4900130bc5a2751b6d1
http://news.iresearch.cn/yx/2019/04/289410.shtml
http://d.youth.cn/newtech/201906/t20190604_11973084.htm
http://www.cntechw.com/html/news/20190626/4689397506004028946.shtml
https://finance.qq.com/a/20190426/009847.htm
https://www.sohu.com/a/308843059_120011750?sec=wd&spm=smpc.author.fd-d.1.1555590300549IV05EoA
http://news.iresearch.cn/yx/2019/04/288108.shtml
http://www.chinaz.com/news/mt/2019/0410/1007599.shtml
http://news.iresearch.cn/yx/2019/04/289410.shtml
https://finance.qq.com/a/20190426/009847.htm
https://finance.qq.com/a/20190422/008095.htm
https://www.sohu.com/a/324234281_120035092
https://www.sohu.com/a/323577986_120035092
https://www.sohu.com/a/325526239_120035092
https://www.jianshu.com/p/951f566640ef
https://www.toutiao.com/i6682620104116535812/
https://www.toutiao.com/i6680060184225645060/
https://www.toutiao.com/i6677844785199317512/
https://www.toutiao.com/i6677471462711886349/
https://www.toutiao.com/i6681545933324288519/
https://www.jianshu.com/p/249b05c5c80e
https://baijiahao.baidu.com/s?id=1672445813680298407&wfr=spider&for=pc
https://www.btc126.com/view/103256.html
https://www.bilibili.com/video/av370896681/
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
N/A.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
In order to prevent clients from maliciously using DataCap, we plan to establish a credit mechanism and cooperate with offline investigations and discussions to screen clients. 
The credit score depends on the following categories: registered capital, establishment time, the continuity of the amount of stored data, and the authenticity of the stored data. 
There will be a threshold for the credit score, and clients below the threshold will be banned. 
The higher the credit score, the more DataCaps can be allocated.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
All processes will be published to Github, including the results of discussions.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
As the legal person of the company, the person in charge of the organization, will personally participate in it to ensure the safety of DataCap.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
Similarly, the use of DataCap by each client is continuously monitored through the credit mechanism. 
Clients below the threshold will be banned.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
Based on credit mechanism, the following question might be asked:
1. What is the purpose of applying for DataCap? Can you provide relevant supporting materials?
2. How much DataCap do you need?
3. How would you distribute the DataCap you applied for?
4. Basic information of individuals or organizations.
5. etc.. 
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Base on the credit score of the client.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
All processes will be published on Github repository.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, it will be public.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
N/A.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
N/A. 
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
N/A.
```

**Comment by dkkapur** [comment]
Hi @waynewyang - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1xYT_a9vH3Juj-f1iSzDQNDbpnyFNPhpVyDQudKgQsMI/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.0.

**Comment by DC-Byteark** [comment]
hi @dkkapur  -this is our additional details:
1.Could you specify when exactly you got involved with the Filecoin Devnet? 
	
	In 2019.2.15, Diancun Tech joined Filecoin Devnet
	https://m.weibo.cn/6851772816/4340022461202684 
	
2.Would you mind confirming the # of followers you have on the platforms you reference? Thank you!

	We have 3437 followers on Weibo  // https://weibo.com/u/6851772816
	We have 2218 followers on douyin // https://v.douyin.com/eHHMPDf/
	We have 8683 followers on huoxing // https://mp.huoxing24.com/main
	
3.Nothing specified in app 

	We will support various use cases to ensure diversity, such as medical gene data, Web 3.0, User Content, Scientific Data, Media & Entertainment, Other.
	
4.Can you specific how exactly your credit scoring mechanism will work and how it is calculated? 

	Please refer to diancun.allocation.table.xlsx document for details of allocation policy.
	
5.Would be great to get more specificity around what type of information exactly you're going to collect and how you're going to store it etc. - thanks
	
	5.1.Can you introduce yourself or your organization and  contact information ?(Github, Twitter, Linkedin handle, Wechat, etc.)
	5.2.If you represent an organization,Please introduce the name of the organization, place of registration, registered capital, time of establishment and your position
	5.3.Please provide the company website that can be accessed
	5.4.In which region(s) do you intend to use the DataCap?
	5.5.What type of data is stored and how long?	
	5.6.Whether there is a specified miner or how many miniers are assigned to store data?
	5.7.Would you like to provide the allocation strategy and allocation of datacap
	5.8.Is the data you store legal
	5.9.Is your data publicly retrievable on filecoin

	
6. Will the allocation decisions be made and tracked in https://github.com/filecoin-project/filecoin-plus-client-onboarding or in a separate GitHub repo?
	yes. all allocation decisions be made and tracked in https://github.com/filecoin-project/filecoin-plus-client-onboarding
	
	
[diancun.allocation.table.xlsx](https://github.com/filecoin-project/notary-governance/files/6607900/diancun.allocation.table.xlsx)

**Comment by dkkapur** [comment]
@DC-Byteark - thank you so much for addressing all these points! The rubric scoring has been updated to reflect this:
- Time commitment: 1/2 -> 3, accounts for the 2+ years in testnet
- Allocation strategy: 1 -> 5
- Client Due Diligence: 1 -> 3

The final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 1.7

Link to updated rubric:
https://docs.google.com/spreadsheets/d/1xYT_a9vH3Juj-f1iSzDQNDbpnyFNPhpVyDQudKgQsMI/edit?usp=sharing
