### ISSUE TITLE
Notary Application: Fatman13

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/notary-governance#125]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information

- Name: Fatman13
- Affiliated Organization: Guazi Dynamic
- Website / Social Media: @fatman13 on Slack and Github
- On-chain Address to be Notarized: f3wvmap64wokgkvavberi2l3o7li5egvym526kdgk3bmnmto5qbcq7jin3wpbkiifoa26caxreois237d66nrq
- Region of Operation: Greater China and Asia-GCN
- Use case(s) to be supported: Professional Services, Developer Tools, Web 3.0, Web 2.0, User Content, Scientific Data
- DataCap Requested: 10TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment

Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

```
Github handle: @fatman13 
Slack handle: @fatman13
Twitter handle: @fatman13
Miner ID: f02731
Closely following filecoin project since 2017 and started full-time participation in 2020. Have been contributing to the network through mining, community discussions, governance and promotion of filecoin in general.
```

### Stake Exposure

Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

```
As of May 14th, 2021 total token at stake is about ~200k. (most are staked in miner id f02731)
```

### In-protocol Reputation

Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

```
- Partner @ guazi.io oversee deployment and operatoins of our mining node
- Active member of filecoin Slack channel with 1100+ messages
- Contibute to governace like FIPs https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md
- Volunteer of ProtoSchool
- Wehcat public account (瓜子动力) for filecoin news, insigts, eco-system and etc
- Participation in events like https://mp.weixin.qq.com/s/sD6kTsuYZhilUdcwzcXGHg for promotion of filecoin
```

### In-protocol Security

Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 

```
Nothing notable yet...
```

### External Reputation

Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

```
We are a company of ~10 people founded in Sep 2020, who are based in China. We offer turnkey mining solution to clients in east Asia.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

```
Website: guazi.io
Wehcat public account: 瓜子动力
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

```
https://mp.weixin.qq.com/s/sD6kTsuYZhilUdcwzcXGHg
https://www.tuoniaox.com/news/p-469057.html
http://www.btb8.com/fil/2010/97772.html
https://www.jiemian.com/article/5196371.html
https://www.jinse.com/news/blockchain/800936.html
https://page.om.qq.com/page/OiP1FgLD5z1rasQf9EWQwWcw0
```

### Use Case Diversity

(Optional) Any additional information you'd like to share about the use case(s) you plan to support?

```
Professional Services, Developer Tools, Web 3.0, Web 2.0, User Content, Scientific Data
```

# Allocation Plan

### Allocation Strategy

How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.

```
We will reference heavily on the guidelines by 1st gen notaries and adapt if not copy most of their model to our own. For example, strategy mentioned in https://github.com/filecoin-project/notary-governance/issues/14#issue-747912777 will be our reference point. Additionally, we are planning on much faster response instead of dragging the process into months of waiting.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 

```
The range we are thinking right now will be from [10 * automatic verificatoin amount] to [100 * automatic verification amount], where a single entiry could be allocated maximum of [100 * automatic verification amount] per month (same cool down period as automatic verificaion). 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
No one but myself will be allocating datacap.
```

### Client Due Diligence

How will you vet your Client to ensure they are spending that DataCap responsibly?

```
We will reference the guidelines by 1st gen notaries and adapt their model to our own. Again we will most likely adopt strategy described in https://github.com/filecoin-project/notary-governance/issues/14#issue-747912777.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 

```
1. Can you introduce yourself? Where can I find you online? Examples include Github, Twitter, LinkedIn, WeChat, etc., and more than one is encouraged.
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. How many miners do you plan on allocating the DataCap? Please specify if you have a specific miner(s) you would like to allocate the DataCap.
6. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing? If so, how will you plan to report it?
7. Will your organization be responsible for allocating the full DataCap? Examples where this might not be the case, include app builders where the application end-users may have access to storage backed by the DataCap. Please read our full proposal for details on this approach. Unfortunately, our proposed multisig enabled DataCap provider is not ready today, but when it is, we will provider further documentation.
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?

```
Through https://filplus.info/#/, blockchain explorer and user reports, we shall find out if a single entity is being over-allocated.
```

### Bookkeeping Plan

Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?

```
Yes, through Github. 
All levels of specificity of genuine audit requests will be responded in a timely manner. 
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 

```
Github only.
```

### Past allocation 

Have you previously received DataCap to allocate before? If so, please link to any previous applications.

```
No
```

Cumulatively, how much DataCap have you previously successfully allocated? 

```
n/a
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 

```
n/a
```

**Comment by dkkapur** [comment]
Hi @Fatman13  - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1xhi4IIyAKc-H0uc9UVQQZliYRDO7Gh3WieOpjFtbESU/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.6.

**Comment by Fatman13** [comment]
Hello, @dkkapur, thanks for the reply! And yes, will only be using https://github.com/filecoin-project/filecoin-plus-client-onboarding.

**Comment by dkkapur** [comment]
@Fatman13 thank you for confirming! The final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 1.6

Link to rubric: 
https://docs.google.com/spreadsheets/d/1xhi4IIyAKc-H0uc9UVQQZliYRDO7Gh3WieOpjFtbESU/edit?usp=sharing
