### ISSUE TITLE
Proposal: Shift next Notary Governance call (Nov 24th 5pm) to Nov 25th 12am UTC

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/notary-governance#13]
As of now, we have our next Notary Governance call scheduled for **Nov 24th 5pm UTC**. This issue proposes shifting that slot back to **Nov 25th 12am UTC** (Nov 24th 7pm EST) to accommodate our global community.

As a suggested agenda, I propose we discuss: 
- Feedback for open applications
- Review any open PRs
- Review any discussion on open issues 

Note, as mentioned before the window for applications will remain open until we come closer to the end of the Beta. 

Please submit feedback or additional agenda topics as comments below.

**Comment by jnthnvctr** [comment]
Given the previous community feedback, and the lack of further discussion on this issue - I will confirm moving this back just for this week.

**Comment by dkkapur** [comment]
Notes from the call today: https://docs.google.com/document/d/1gLMtS7OcII0KDaoVNCuP9ymOXpofVvsiK1CssfUbFFk/edit?usp=sharing

**Comment by jnthnvctr** [comment]
Topic: Notary Governance
Start Time : Nov 24, 2020 03:52 PM

Meeting Recording:
https://protocol.zoom.us/rec/share/BNbrPGmr-lYIlamUAs7SjkNttKYJ5KjF_6RCl5LasEHoWZKvPP7MzlJi0JD5iG75.rkZVD9SiBdLfvuG6

Access Passcode: &p#5D4ej
