### ISSUE TITLE
Holon Innovations Notary Application

### ISSUE THREAD

**Issue by MegTei** [filecoin-project/notary-governance#130]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Holon Innovations
- Affiliated Organization: Holon Global Investments PTY Ltd
- Website / Social Media: https://holon.investments/
- On-chain Address to be Notarized:
- Region of Operation: Oceania
- Use case(s) to be supported: https://docs.google.com/document/d/1_Z-fe-e5zOXdpvlumYsTdI1Lr7l1GF8bmpw59tXAxxA/edit#heading=h.2b63d2ru17hx 
(/notaries/templates/README.md#definitions)]
- DataCap Requested: 100 TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
1) In 2017 Heath Behncke Holon co-founder participated in the Filecoin SAFT
2) Holon Global is among a small number of funds that have an investment philosophy open to digital assets in Australia and Latin America and is working to make access to Web3.0 opportunities open to everyone.
3) Holon Innovations (part of the Holon Global group) has committed $5mUSD infrastructure to set up our own mining operation
4) Have commenced an awareness campaign to build both knowledge of IPFS and Filecoin and the community in Oceania
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Prefer not to state
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Holons' founder Heath Behncke was an early advocate and investor in FIL, having analysed the problems of web2.0 and discovering the potential of decentralised storage models and the Filecoin proposition. Filecoin is now an investment focus for Holon with the following underway:
1) Investment of 25 PT in Filecoin mining infrastructure in 2021
2) Holon Innovations is currently setting up the Holon FIL Wholesale Fund with custody partner Anchorage. This is a fund dedicated to investing in growing Holon's FIL mining operation, with target funding amount of $90m USD.  Planned launch mid 2021.
3) Planning to add FIL to its managed funds in 2022 and listing on a local exchange as an ETF.
4) Commenced a thought leadership campaign targeting the tertiary education sector in Oceania to build awareness and the Filecoin community with the student and academia community - a 'grass-roots' tactic to excite Grads and inform educators of disruptive technologies. This involves sponsoring education/ masterclasses, presentations/ webinars and sharing resources.
5) Advocacy campaign - following the first phase of the awareness campaign Holon Innovations will run hackathons and accelerators late 2021-2022
Fundamentally, the Holon team see the potential and believe in the value Filecoins decentralised storage can offer the world and are working to help make it a success. Our own mission is to look after the wealth of our clients, to ensure they benefit from disruption, not suffer.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
N/A 
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Holon Global Investments was founded in 2018 at a time when it was clear digital assets will become an investment class and that everyone should have access to investing in them. 
Our mission is to be the 'next generation Fund Manager' with an evolutionary philosophy. Having worked in wealth management for decades, this experienced team came together over a desire to solve the issues investors face around declining returns and access to investing in digital assets which offer yield potential. Holon Global Investments (HGI) has 3 entities:
1) Holon Global Investments - delivering a range of investment funds, diversified across digital assets
2) Holon Innovations - builds tacit know-how through getting involved in Web3.0 and decentralised projects, the first is a Filecoin mining operation starting in Sydney AUS and expanding across Oceania
3) Holon Principal Investments & VC - The first strategic investment in Avanti bank (https://holon.investments/why-we-invested-in-avanti-the-future-of-banking/) is part of creating a safe legal structure for digital assets and in the future the VC arm with fund accelerators and other Web 3.0 ventures 
The Holon Photon Fund (the Fund) launched July 2019 was designed to capture large scale opportunities in public markets by investing in the leaders, enablers and beneficiaries of transformative innovation of today, tomorrow and the future. With the goal to deliver total returns that are 10% p.a. in excess of those of the broader equity market across a five-to-seven-year investment timeframe, this has been achieved to date.
With Wealth creation now taking place through innovation and disruptive new business models our investors in Australia, Europe and Latin America are investing in the Photon Fund because they can access unique investments they can't get anywhere else such as Chinese stocks, Roku, Microstrategy, Coinbase etc. 
We are currently designing a range of digital asset funds, which will provide investors with a huge opportunity to profit from disruption to launch in 2021. The first will be a FIL Fund, open to wholesale investors to invest in Filecoin Infrastructure, (mid 2021). For every FIL invested, investors will earn ROI of 1.6 over a 5 year term, the Filecoin network, benefiting from expansion in Oceania. ```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Holon Global Founders: Heath Behncke www.linkedin.com/in/heath-behncke-a164971a/  
Luke Behncke www.linkedin.com/in/luke-behncke-3a945723/ 
MD of Holon Innovations: Jonathan Hooker www.linkedin.com/in/jonathan-hooker-syd/ 
Website: www.holon.investments 1300 subscribers
Linkedin: Holon Global Investments 450 followers 
Livewire: Holon Global Investments 2000-3000 views per story 
Twitter: @GlobalHolon
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Holons relevant and recent press profile includes:

Fund Manager profile - The Australian Financial Review http://www.afr.com/markets/equity-markets/it-s-not-just-about-value-or-growth-for-holon-s-behncke-20210408-p57hfq?btis
Web 3.0 interview - The Eureka report https://www.eurekareport.com.au/investment-news/investing-in-the-internet-of-value/149674
Web3.0 in diversified portfolios - Livewire https://www.livewiremarkets.com/wires/why-web-3-0-is-a-threat-and-opportunity-for-portfolios
Holon investment in Avanti Bank https://www.finextra.com/pressarticle/86821/avanti-comples-37-million-series-a-funding-ahead-of-launch-of-digital-asset-bank
Commentator on digital assets - Coinbase - Sydney Morning Herald https://www.smh.com.au/technology/watershed-moment-as-coinbase-ipo-widens-crypto-investor-pool-20210414-p57j45.html
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We see generating the market across 2 dimensions in Oceania:

Targeting the tertiary education sector to build advocacy. 
1.1 Generating awareness with grads who are at the beginning of their careers will serve to build community and inspire working in the ecosystem. This "grass-roots" tactic will build advocacy amongst students - the future entrepreneurs. 
1.2 Generating awareness with academics who develop the curriculum program to connect research with commercial opportunity through Filecoin. Activities will include:
- A series of masterclasses partnering with Universities such as RMIT, UNSW, Macquarie
- An ARC Linkage grant together with ANU and Macquarie that dedicates PHD students to work on aspects of real world IPFS problems as well as commercialisation
- Hackathons and accelerators
Storing and securing the world's most important data. Target sectors/ audience includes: 
2.1 The tertiary education sector are target Beta clients, leading important research projects, tolerance for Beta calibre and open to 2-way feedback. Together with PHD students who are aligned with solving decentralised and web3.0 problems (NFP) 
2.2 Media/ CDNs 
2.3 Indigenous art (NFP) 
2.4 Legal sector 
2.5 Government/ public records (NFP) 
2.6 Environment & sustainability (NFP) 
2.7 Explore Northern hemisphere 'data mirror' use cases. That is, data which is stored on the other side of the world that needs to be available in Southern hemisphere
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
The mission of our DataCap strategy is to build network effect. Our role as a Notary and how we will generate the market are strategically aligned. Oceania is lagging the Northern Hemisphere's awareness and adoption of decentralized protocols and solutions, our use case diversity will target the most ideal clients/ data who will become advocates. The end to end customer journey from ‘acquire to ‘retire’ and all service in between will be managed in the following way 
(1) Prequalification. This first stage will educate, vet and collaborate with clients on their data storage ‘problems to solve’. Highly qualified/ committed clients with a data storage strategy and execution plan will be encouraged to apply 
(2) Application. The process will require a number of artefacts and once submitted Holon Notary Ops will triage for completeness before processing 
(3) Due Diligence. All requisite checks for company, team and legitimacy. 
(4) DataCap sizing & scoring. The clients data strategy and execution plan will indicate storage size together with a scorecard the applicant will be rated against criteria. The allocation of DataCap will be approved on the following basis: 
4.1 Region is Oceania, 50-50 across commercial/ business and Not-for-profit (NFPs) projects. 
4.2 A scorecard with ‘weighted criteria’ will produce an approval rating which will include:
- Reputation of business
- Storage request and growth rate
- Low retrieval rates
- Security considerations/ sensitivity of data
- Ability to become a Filecoin ambassador/ advocate The scorecard can be found at 02.2 DataCap sizing & scoring page 10 https://docs.google.com/document/d/1_Z-fe-e5zOXdpvlumYsTdI1Lr7l1GF8bmpw59tXAxxA/edit# 
(5) KYC & Onboarding. Following an approved rating and tranche forecast we will onboard the new client in a frictionless and positive process 
(6) Beta phase. The new client will be monitored closely under a probation, ‘Beta’ phase. Each client will be vetted regularly against their decentralised data storage strategy and execution plan to ensure the allocated DataCap is being spent exclusively as approved. 
(7) Other ‘in-life’ processes, maintenance, changes and client close are also supported by Holon Notary Ops Our service level mission is to provide the most positive CX possible in every circumstance so that clients not only recontract but become our salesforce.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
The processes Holon Notary Ops will support include: 
(1) Pre-qualification of client, including review of the clients data storage strategy and execution plan, together with https://github.com/filecoin-project/notary-governance/blob/main/notaries/templates/sample-client-application.md 
(2) Triage and client due diligence to vet the applicant 
(3) Scorecard process to derive a client tier (from ineligible to platinum client) 
(4) The rating will be reviewed after the 6 month beta phase (probation) period and ongoing, annually 
(5) The DataCap allocation will be determined from the scorecard with guidelines around 25% will be allocated over the first 3-6 months, then tranched evenly over the term of the contract 
(6) During the probation term (first 6 months) Holon Notary Ops monitoring will be more rigorous and aligned with the client tier and the weighted criteria (associated to their data volume, reputation, sensitivity of data). At the end of the probation term the client scorecard and rating will be reviewed The full set of client lifecycle processes can be found here https://docs.google.com/document/d/1_Z-fe-e5zOXdpvlumYsTdI1Lr7l1GF8bmpw59tXAxxA/edit#
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The address that will be allocated DataCap will have its keys be secured with custody partner Anchorage
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
Following onboarding of the client and allocation of their first tranche, clients will be monitored and vetted regularly against their decentralised data storage strategy and execution plan to ensure the allocated DataCap is being spent exclusively as approved. Additionally during this ‘probation’ term Holon Notary Ops will ask the Client to provide some or all of the following: 
(1) A consolidated Content Identifier (“CID”) list for verified deals that includes deal CID and miner ID (showing how the allocated DataCap has been used); 
(2) A description of the data being stored and how the data has been processed; 
(3) Instructions on data retrieval. 
(4) Random-sample inspections by Holon Notary Ops on the verified deals sent out by the Client on chain will be checked against the deal CID and retrieval from miners to verify the data authenticity. Filecoin public monitoring and auditing will be in play also 
(5) “In-life” client questionnaire

Where are you storing your data in a single geography or many?
What key features are you using (e.g. Fast Retrieval) with your storage deals?
How are you securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
Describe how you have spread your data across miners
Are you storing data that abides by local regulations and in compliance with the recipient miner’s terms of service?
Are there any disputes open against you from your previous DataCap allocations? Or any violations to date
We are likely to use an automated tool such as https://www.fil.deals/
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
Many clients in Oceania will also only be discovering how they will use a decentralised storage model. Holon will prequalify target clients for Filecoin community and advocacy ‘fit’. A pre-application activity will work with ideal clients and assist them with sizing, storage and retrieval requirements. We will use the existing client questionnaire https://github.com/filecoin-project/notary-governance/blob/main/notaries/templates/sample-client-application.md as well as across the following key areas: 
(1) Filecoin awareness - demonstrates understanding of:
- Filecoin economics
- stage of Filecoin network development
- storage and miner dynamics
- awareness of risks
Part or the decentralized storage community 
(2) Expectation management
Work through with the client short & long term expectations including
Organisational readiness - definition of an execution plan to transform from centralised to decentralized - a project plan mapping resources and budget and change management 
(3) DataCap allocation and subsidization strategy - how the client will continuously identify and work with reliable storage and miners with or without additional DataCap
For "in-life" or active clients, before providing additional tranches, Holon Notary Ops will check every day via a monitoring dashboard (such as the one used by current Notaries https://filplus.d.interplanetary.one/ ) for any client violations.

Holon will provide the client with 2 templates to assist them to define the strategy and plan.

A decentralised data storage strategy
The organisations execution plan The depth and detail the application goes to will be a strong indicator of the quality of client and their commitment
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
We will source tooling that is capable of tracking, monitoring and alerting Holon Notary Ops. We also require clients to make public their deal transactions with miners.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
All allocation decisions will conform to standards using the repo https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues

We will store all the work records of clients, their artefacts and allocation decisions.
1.The allocation guidelines and other supporting rules will be publicly available following approval. 
2. The client record/ data, application, correspondence and decision reports will be kept for at least 3 years. 
3. Audits to be conducted by professional lawyers or accountants appointed through Filecoin community governance procedure. Auditors will have access to all relevant files ensuring confidentiality and that certain data may be withheld without permission of the Client authority.

We will manage any conflict of interest between Holon Global Investments and Holon Innovations mining venture through a firewall. Holon Global Investments(HGI) is a highly regulated (ASIC) financial institution which requires us to establish our own Responsibility Entity to ensure full compliance and transparency of activity, this extends to Holon Innovations mining venture and entirely HGI are commercially separate. We will ensure the integrity of Holon Innovations mining venture and the separate role of Holon Notary Ops using the precedent set by other Notaries who are also miners via client proxies. That is, where a client in Oceania wants to use Holon miners the request will be routed via another Notary for both transparency and avoidance of any conflict.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will conform to standards using the repo https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues, made public for transparency in this phase. In future some clients and their storage needs may be complex or sensitive and records may be then maintained on Holon Database
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
N/A
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
N/A
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
N/A
```

**Comment by dkkapur** [comment]
Hi @MegTei - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/16IN59IYE7KdBduYmHKsa2kixM89XJ7X_rNu_XLZWrp4/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.9.

**Comment by dkkapur** [comment]
Hi @MegTei - thanks for sharing your comments in the rubric. I have responded to them there. Adjustments were also made to your rubric based on the info you provided. 

The final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 2.2

Here is the link to the updated rubric:
https://docs.google.com/spreadsheets/d/16IN59IYE7KdBduYmHKsa2kixM89XJ7X_rNu_XLZWrp4/edit?usp=sharing

**Comment by dkkapur** [comment]
@MegTei - based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of 100 TiB. In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm that the region of operation for client applications you will focus on is [Oceania]

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

> * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

> * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

> * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**Comment by MegTei** [comment]
HI @dkkapur Find responses below:
1. Yes, Oceania
2. Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship
- We agree and will abide by these principles
Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.
- We agree and will abide by these principles
Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.
- We agree and will abide by these principles
No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.
- We agree and will abide by these principles
Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.
- We agree and will abide by these principles
Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.
- We agree and will abide by these principles
3. The miner https://filscan.io/tipset/address-detail?address=f0410941
4. Yes.
5. We will use a Leadner Nano S. Deep, We need someone to walk us through the process of signing using the Fil+ registry app. Or is there a video?
Also is there any onboarding process for new notaries?

**Comment by dkkapur** [comment]
@MegTei - Ledger Nano S should work great! Most opt for X but pretty sure the functionality should transfer without an issue. We are working on getting some onboarding materials published and looking into pairing new notaries with existing ones as well to help with this process. 

For immediate next steps: 
- https://docs.filecoin.io/get-started/lotus/ledger/ - start with this, and complete the "Set up your Ledger device" steps
- the easiest path is to then hop into Glif - https://wallet.glif.io/ and "Login via Ledger Device"
- this should then show your address on the Filecoin mainnet for your Ledger, which we can then grant the notary status and DataCap to

**Comment by dkkapur** [comment]
Address shared via Slack: f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i

**Comment by MegTei** [comment]
Hi Deep, good to go. Meg

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Datacap Allocated
> 100TiB

**Comment by dkkapur** [comment]
This grant seems to have gone through correctly and should not be in Error status. Fixing this now!
