### ISSUE TITLE
Notary Application: Masaaki Nawatani of Blotocol Japan

### ISSUE THREAD

**Issue by MasaakiNawatani** [filecoin-project/notary-governance#131]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: **Masaaki Nawatani**
- Affiliated Organization: Blotocol Japan Ltd.
- Website / Social Media: https://blotocol.com
- On-chain Address to be Notarized: **f1fh53sdaie3yi25qxwcqxpt5h4naex5ibdaffibi**
- Region of Operation: [Asia-GCN]
- Use case(s) to be supported: _Web 3.0 / Decentralized Applications_ and _Web 2.0 Applications_
- DataCap Requested: **100 TiB**

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
I am committed to push meaningful distributed storage to as many verifiable clients as possible. As an existing Notary, 
I have spent a fair amount of time out of my day to help the cause. I have a perfect attendance in all 
of the Notary Governance Calls and have actively communicated with the Notary Community via Slack. 
My Github handle is _MasaakiNawatani_, My Slack handle is Masaaki Nawatani.

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
I prefer not to disclose. 
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As one of only two existing Notaries assigned to the Asia-GCN region, I have spent a considerable amount of time 
helping the cause. I have made good working relations with Deep Kapur, Jonathan Victor and fellow notaries 
Philipp Barnhardt and Julien Noel. Despite having technical issues with my data allocation, as soon as it was fixed, 
I immediately went into action, crafted a working strategy in conducting due diligence and in the process, 
was able to allocate datacap to three (3) clients in my assigned region in just a short span of time. 
I am looking forward to contributing more if re-elected. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
Being part of the pioneer group of Notaries elected, there were many obstacles and technical challenges that we all faced. 
I have been very open about having multisig and address rotation be given a second look by the Keyko team - which eventually resolved my allocation issue, but more importantly opened opportunities for discussion to improve the way datacap allocations are done. 
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Blotocol Japan Ltd. is a duly registered software engineering company with offices in Japan and The Philippines. 
We have built blockchain applications and crypto projects since 2017 and have been shifting our focus 
on Web 3.0 technology. I have a team of Software Engineers currently working remotely in different parts of Asia. 
We can handle English, Japanese and Chinese projects and we are very familiar with specific 
business situations including Japan, Philippine, China, Korea, Singapore, Malaysia and so on. 
We deeply understand the nature of the businesses of clients in our region and we are sure that 
we can make correct and fair decisions in allocating DataCap in this region.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://blotocol.com
Officers on Slack: @blotocol, @obbie-one
LinkedIn: https://www.linkedin.com/in/masaaki-nawatani/

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
None at this time. 
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We plan to support the majority of use cases that we consider to be our expertise. We are currently
supporting Web 2.0 and Web 3.0 Dapps projects over the past year and will be looking into supporting 
user content and organizations that are supporting the PWD (person-with-disability) community. 
In line with this, we are also looking into supporting organizations that are doing scientific research 
to further improve people's quality of life through sustainable solutions. 
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
I plan to allocate DataCap to clients who will be able to provide verifiable information about their organization 
and have their data storage plan made available to the public and their end-users. Same as what the majority of my fellow Notaries did, I will be setting up thresholds with varying degrees of trust to promote consistency across the board. 

```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
I plan to allocate DataCap to duly registered and end-user transparent Clients by performing due diligence. 
The same method that I used in my first stint as Notary. If a client requires a large amount of DataCap and 
his business is worth being allocated, I will first allocate 5Tb and advise the client to start small 
then allocate conservatively - to further understand if the client really needs additional DataCap or not.

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
By using a Ledger Wallet, which is only accessible by me. 
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
The vetting process to ensure Clients are/will spend DataCap responsibly will comprise of the following required elements: 

1. Company / Organization Proof of Existence
 - Company documents such as Business Registration, License to Operate and other government issued documents 
to validate their business rights and existence.
 
2. Stakeholders
 - Acquire the core information of all authorized signatory’s that will act on behalf of the application entity. 
Which may include a signed authorization letter from the Board of Directors or CFO/CTO/CEO. 
In the event that there are multiple shareholders, a comprehensive core information for each actor will be 
required along with a photo of their government issued ID and a selfie while holding the document. 

3.Checking related reputations
-We will check not only his Website but also SNS such as Twitter, Facebook, Instagram and so on. 
We will also check local news sites and company database via Chamber of Commerce in which his 
company registered with. 

```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```

1. Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization, the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide that as well.
2. Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 
4. Do you intend to store your data in a single geography or many?
5. Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?
6. How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
7. Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?
8. For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?
9. Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?
10. Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.
11. Are there any disputes open against you from your previous DataCap allocations?
12. Have you ever previously violated: Your own attested allocation / audit plan? Or Been found to be in violation of the Principles of Filecoin Plus?
13. What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
14. Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
15. Do you plan on conducting your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
16. Have you previously received DataCap to allocate before? If so, please link to any previous applications.
17. Cumulatively, how much DataCap have you previously successfully allocated? 
18. Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
19. Do you have any links or documentation that shows your transparency to your data storage plans with your end-users? If none, can you provide within the next 7 days?


```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
To promote a completely decentralized system of storage, as well as strengthen redundancy - ultimately minimizing the possibility of ‘gaming’ the system, I will clearly communicate the importance of storing with multiple miners (3-5 is recommended).  Also, I will be more conservative, even though I I think his business plan is worth being allocated DataCap, I will allocate less than 5Tb first and ask him to apply again in the future (or with another Notary) if its not enough. When the client applies again, then I will conduct due diligence, check his business and ask more questions.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
During my stint as Notary - I have kept records of all allocation decisions made. These decisions are 
based on the rubric of Filecoin Plus and are available publicly. For any audit requests, it must be raised 
as a public issue on Github and follow the process agreed upon during Notary governance calls. 
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be made publicly available on Github. This includes the entire vetting process 
in the interest of transparency and fairness. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
I received 10 TiB. See this issue for reference. 
https://github.com/filecoin-project/notary-governance/issues/113

```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
9.2 TB
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None.
```

**Comment by dkkapur** [comment]
Previous applications:
- https://github.com/filecoin-project/notary-governance/issues/56

Allocation track record from last round:
- ~9.1 TiB allocated in past round, 3 client applications in repo, 3 verified clients in dashboard currently
- list of client applications approved: https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues?q=is%3Aissue+is%3Aclosed+label%3Astate%3AGranted+sort%3Aupdated-desc+assignee%3AMasaakiNawatani

Client applications and usage of datacap: 
![image](https://user-images.githubusercontent.com/2343218/120598765-86c1fd80-c3fb-11eb-82a9-585203bb15b8.png)


DataCap received by miner IDs:
(at this point, none of the clients have used their DataCap based on the data present here: https://filplus.d.interplanetary.one/notaries/f0399944)

**Comment by dkkapur** [comment]
Hi @MasaakiNawatani - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1WpshXOcE0mAU7t6C6TrGokLCOHjJVNDgojI4rVuP6Hw/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.7.

**Comment by MasaakiNawatani** [comment]
Hi Deep, hope you're doing well. Thanks for your review and consideration. 

**Just to elaborate further on our allocation strategy:** 
If a client requested more than 1TB, I will first allocate maximum of 1TB, then validate real usage of the said Data cap. If the client used more than 80% of the allocation, and returned to apply for more datacap, I will check confirm how deals were made and request hard evidence of real usage - in as little time as possible to improve the processing time between requests and grants. If it makes sense, then I will proceed in allocating additional datacap.

**Comment by dkkapur** [comment]
@MasaakiNawatani - thanks for sharing this! However - your allocation strategy above cites:
> I will be setting up thresholds with varying degrees of trust to promote consistency across the board. 
 
 The info you provide here is helpful in the context of vetting a client and their actions on the network, but does not specifically shed more light on the thresholds/scoring you plan to do for clients. Additionally, your application originally cites 5 TiB, but here you cite 1 TiB. I think both are reasonable numbers, but I do think you should pick one to be consistent. 

The final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 1.7

Here is the link to the updated rubric:
https://docs.google.com/spreadsheets/d/1WpshXOcE0mAU7t6C6TrGokLCOHjJVNDgojI4rVuP6Hw/edit?usp=sharing

**Comment by dkkapur** [comment]
@MasaakiNawatani - as shared in the last Governance call, based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of: 99 TiB (qualified for 100 TiB, currently have < 1 TiB unallocated DataCap). In order to confirm your participation in the Fil+ ecosystem:

1. Please confirm the region of operation for client applications you will focus on is [Asia minus GCN]

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additonal services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

> * Commitment to effeciently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

> * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially recieve requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

> * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**Comment by MasaakiNawatani** [comment]
Hi @dkkapur , we are honored to fulfill another round of Notary duties for Filecoin Plus. Thank you for considering us. 

1. The region that we will be focusing on is **ASIA minus GCN**
2. Upfront Disclosures: 

_Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship
- **I accept and agree.**

Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.
- **I accept and agree.**

Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.
- **I accept and agree.**


No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.
- **I accept and agree.**

Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.
- **I accept and agree.**

Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input._
- **I accept and agree.**

3. I am not affiliated or have any bias with any active miners or clients in the community. 

4. I will abide by the allocation / client due diligence plan that I laid out above.
5. I have 900 MB of datacap from round 1, therefore I will use a new address for round 2:

The address that should receive DataCap allocation is - - - **f1nno2h7vh5h22kynap2ca7ywxwvxpbl2yclfbguq**

Please confirm if I understood the instructions for number 5. Thank you.

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1fh53sdaie3yi25qxwcqxpt5h4naex5ibdaffibi
#### Datacap Allocated
> 100TiB

**Comment by dkkapur** [comment]
This went through correctly
