### ISSUE TITLE
Notary Application: IPFSUnion - Steve Song

### ISSUE THREAD

**Issue by IPFSUnion** [filecoin-project/notary-governance#135]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Steve Song
- Affiliated Organization: IPFSUnion
- Website / Social Media: https://ipfsunion.cn
- On-chain Address(es) to be Notarized: [f1enfilmuyphmnqexjt33zfbk56c25mo2lplgbpxa, f1egzdymosrohqcx2hwrbhppi3yvzgxpvnpzrij6a]
- Region of Operation: [Greater China]
- Use case(s) to be supported: [Web 3.0 / Decentralized Applications, Web 2.0 Applications, User Content, Scientific Data, Media & Entertainment, Other]
- DataCap Requested: 100T

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
As an individual, I founded a boutique private equity fund focusing on TMT industry with other three partners in 2016. After that, I screened more than 300 companies and completed more than 20 deals including 8 blockchain projects majored in exchange, public chain and Defi. At the end of 2016, I saw great value and potential of IPFS protocol from hundreds of blockchain projects and believed it to be the only project that could be implemented in business scenarios since the appearance of blockchain technology. After careful study of the Filecoin white paper, I participated in the Filecoin ICO in 2017. Thereafter, I have kept a very close attention to this project during 2018 and finally decided to work with some partners to create a company specialized in Filecoin project named IPFSUnion. 

As an organization, IPFSUnion was founded in 2019 with an aim to build a more secured, efficient and liberated Web of 3.0 and the company has quickly become a major player in the Filecoin field. In addition, our official website is https://www.ipfsunion.cn and our github handle named IPFSUnion, so is Slack. 

Based on Web 3.0 protocol and powerful hardware, IPFSUnion is one of the firsts to build an integrated and comprehensive distributed storage ecosystem which covers the full spectrum of IDC, hardware servers and specially designed chips implemented IaaS layer, AI Operation & Maintenance and Virtual OS supported PaaS layer, and a multi-application supported SaaS layer:

    1. At IaaS layer, we are in superior position of high-performance hardware R&D and manufacture. Our IronMiner series distributed storage server promises to deliver a concept of “Ultimate Cost Performance and Service Experience”, enabling individual and enterprise users to enjoy one-stop service of cluster deployment. In the meanwhile, IPFSUnion has invested heavily in specially designed chips and independently developed FPGA & ASIC DSN-dedicated chips to boost hardware performance, lower production, operation & maintenance costs. Furthermore, in cooperation with the government, we are building the largest IPFS IDC in China and have established partnership with nearly 200 IDC around the world(https://filecoin.io/blog/posts/ipfsunion-has-announced-an-investment-to-build-a-large-industrial-park-focused-on-filecoin-mining/).

    2. At PaaS layer, we not only manage to significantly optimize algorithm that elevates efficiency in data sealing and storage, but also independently develop an AI Operation & Maintenance interface called “Eagles”, which enables 7*24 real-time monitoring on the entire network and hardware operation status with additional capacities of Auto-Deployment, Log Analysis, Fault Self-Recovery, etc.

    3. At SaaS layer, IPFSUnion has independently developed by far the most widely used bilingual DSN blockchain explorer “Filscout” (www.filscout.io). In addition, we are to initiate the enterprise-oriented Cloud Service “IPFSUnion Cloud”.

On the miner side, currently IPFSUnion has 11 official miners who can be found by account address “f1egzdymosrohqcx2hwrbhppi3yvzgxpvnpzrij6a” and “f1enfilmuyphmnqexjt33zfbk56c25mo2lplgbpxa”, and the total power has reached 289PiB. We have also been nominated as the member of Filecoin Foundation’s miner group by Juan Benet.

On the developer side, IPFSUnion has built very close relationship with the official development teams and has submitted a great number of bug reports plus other improvement proposals. IPFSUnion has successfully won rewards in every previous round of Slingshot competition and developed “IPFSFound” project (https://filecoin.in/) which is one of the first applications that help valid data access to Filecoin network. 

In addition, IPFSUnion has so many official accounts on major social platforms. Wechat official account is one of our most major publicity platforms where own tens of thousands of followers. we have 42227 followers in the account named “IPFS星际联盟” and 14880 followers in the account “IPFSUnion星际联盟”. Moreover, our Weibo(Chinese twitter) account "“IPFS星际联盟FILE” also has 12137 followers. The specific evidence is summarized here(https://docs.google.com/document/d/1G3_PK3_e4p3OcjSxtBB1zSd8mUEXa7b7rwnYNNVqWEI/edit?usp=sharing).  

Last but not least, IPFSUnion strives to push the entire Filecoin and IPFS ecosystem forward. On one hand, we organize open courses and industry forums every week. On the other hand, we have also built strong relationship with local governments and industry giants to apply the IPFS and Filecoin technologies. We believe that the future of Filecoin is unlimited.

```
### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
The total FIL at stake is about 5.15MM with the following 22 Miner IDs till June 7th, 2021. The details are as follows:  
```
   |  Account  |  Balance/FIL  |  Account  |  Balance/FIL  |  Account  |  Balance/FIL  |  Total/FIL  |
   |  ----  | ----  |  ----  | ---- | ---- | ---- | ---- |
   |f023530|523602.6827|f0131822|799742.9101|f0133957|157111.0943|*Total*  5158025.2356|
   |f01231|243510.9256|f0133505|704427.6922|f0673920|116432.5742|*Available*  342223.2764|
   |f016398|171901.2379|f0152337|400141.7251|f066102|119423.3651|*Pledge*  3504401.8010|
   |f021479|212415.0616|f0429122|328035.1566|f053229|121668.4926|*Locked*  1311400.1582|
   |f070932|144442.7453|f0463030|374819.2574|f0508328|52709.9593|
   |f0680529|234582.8618|f0133501|147427.0513|f0407733|60631.7286|
   |f089173|14696.5067|f0449196|23935.1222|f0155212|171943.3869|
   |f0154944|34423.6974|

<br/>

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As a member of Filecoin community, I have dedicated all my working time in promoting the ecological development of Filecoin industry with the company since 2019.

1. I was really honored to join the Fil+ Day on 11th May this year to share some projects and visions of IPFSUnion(https://www.youtube.com/watch?v=DGGF5siwaK4).

2. Last year, when we held the biggest distributed storage summit in China, I invited Juan Benet to give us a speech to share his views of the decentralized future of Web 3.0 with thousands of Chinese users (https://twitter.com/IPFSUnion_CN/status/1394593033866387457).

3. I joined the Filecoin liftoff week at the Miner Spotlight in October 2020(https://www.youtube.com/watch?v=TUCbVzWux9Q).

4. I actively took part in every notary governance call to discuss proposals for better improvements of Filecoin Plus and tried my best to help peers who have problems on Slack channels.

As a world’s leading decentralized storage solution provider, IPFSUnion has been actively participating and organizing various events to promote Filecoin ecosystem，and has achieved significant results.

1. Starting from August 2019，IPFSUnion has been pushing a large number of articles about the latest developments in Filecoin on major social platforms weekly including WeChat official account, Twitter, Zhihu, Jianshu etc.，and has led thousands of people to get into Filecoin storage (i.e. https://twitter.com/IPFSUnion_CN, https://www.zhihu.com/org/ipfsxing-ji-lian-meng-7/posts).

2. We not only attended many blockchain/IPFS or Filecoin related conferences or Panel discussions, like Can Conferences in 2019, both Global Mining Forum and Filecoin Mining Community Call held by the Filecoin Foundation in May of 2020, but also held many national-wide distributed storage summits in order to promote the Filecoin project to more new-comers (https://www.163.com/tech/article/FOTD8DC000099A7M.html).

3. A high-profile participant in every round of Slingshot competition. Our competition project “IPFSFound” is expected to win awards again in the latest round of Slingshot.

4. Filscout(https://filecoin.in/) is an excellent Filecoin network explorer developed by The IPFSUnion team which really realizes the complete transparency of on-chain data. Moreover, we have been updating and optimizing it and adding many new features such as orphan block stats, real time gas used and miner gas cost search etc. 

5. We developed tools like Mining machine investment income calculator (http://fil8.top/invest/) and Pool statistics tool(http://fil8.top/invest/) which have been included here(https://github.com/filecoin-project/community-china) to help users better understand the filecoin ecosystem.  

6. In April 2021, together with Chinese local government, we have initiated the construction of one of the biggest storage data centers in China. The total investment of this data center will be 1.3 billion USD (https://filecoin.io/blog/posts/ipfsunion-has-announced-an-investment-to-build-a-large-industrial-park-focused-on-filecoin-mining/).

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
As the member of Filecoin Security Group, IPFSUnion has submitted a number of official bug reports plus other improvement proposals. The details are as follows:

1. Leo Zhang is one of core developers from IPFSUnion. Firstly, Leo participated in the Filecoin Security Research Fellowship and submitted some issues which can be seen in https://security.filecoin.io/bug-bounty/. Secondly, he discussed more than 6 bug reports via Email with alex@protocal.ai. Finally, he also submitted issues #2277, #3019, #2247 etc. in https://github.com/filecoin-project/lotus/issues, and an issue about filecoin-docs in https://github.com/filecoin-project/filecoin-docs/issues/562. Most of them have been adopted and merged.

2. Our CTO Maobisheng has submitted many bugs since Sep 2019, such as #400, #424, #474, #1285 etc. in https://github.com/filecoin-project/lotus/issues.
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
IPFSUnion is a reputable decentralized storage solution provider based in Shanghai, China. The company was founded in June 2019, then rapidly developed into a leader in the field of IPFS network.

Currently, we have about 150 employees, many of whom come from Microsoft, Alibaba, SAP, Huawei, Giant Network, AMD, Inventec and other well-known enterprises. Our team has been deeply engaged in the field of cloud storage and Internet for more than ten years and has built strategic partnership with major cloud service providers such as Alibaba Cloud and telecom operators globally.

Recently, IPFSUnion has obtained nearly US$20 million of investment from the Industrial Fund of Fuzhou High-tech Zone in Jiangxi Province and a strategic investment from Fenbushi Capital. We will work harder to promote the development of Filecoin ecosystem and lead the upstream and downstream evolution of the distributed storage industry.

In addition, IPFSUnion has established a complete sales channel globally, providing thousands of users with the most cost-efficient products and software services. In China, there are more than 500 agents and distributors. Apart from the headquarter in Shanghai, we have another 23 Operation Centers in different locations, covering all Tier-1 cities and mostTier-2/3 cities in China.

Although we are based in China, but we always harbor an international vision. IPFSUnion has formed strategic cooperation with over 100 distributors overseas and has sold servers through these channels to foreign markets including North America, Europe and Southeast Asia. The company has more than 200 IDC resources in cooperation and 5 independent IDC in use. We are also planning to establish a R&D center in Los Angeles in the very near future.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Official website：https://www.ipfsunion.cn
Self-developed blockchain explorer：https://www.filscout.com
WeChat Official Account: IPFS星际联盟; IPFSUnion星际联盟
Twitter: https://twitter.com/ipfsunion_cn
Github：https://github.com/IPFSUnion 
Zhihu：https://zhuanlan.zhihu.com/p/173753718
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
IPFSUnion has a wide range media exposure globally. Here are some report examples in top medias.
* https://filecoin.io/blog/posts/ipfsunion-has-announced-an-investment-to-build-a-large-industrial-park-focused-on-filecoin-mining/
* https://www.coindesk.com/china-filecoin-mining-facility
* https://dmex.medium.com/dmex-joined-forces-with-ipfsunion-for-an-ama-the-future-of-fil-mining-and-the-technical-roadmap-of-3b23b2b3ab1
* https://elastos.info/elastos-credit-oracles-land-first-major-use-case-in-fuzhou-with-ipfs-union/
* https://in.finance.yahoo.com/news/global-blockchain-eco-conference-ipfsunion-093157060.html
* https://zhuanlan.zhihu.com/p/367945768
* https://apnews.com/press-release/newswire/technology-business-greater-china-corporate-news-shanghai-50f7cc6f457bf631fd1d823e80d30f69
* https://finance.yahoo.com/news/2020-shanghai-global-ipfs-decentralized-160000175.html
* https://tech.163.com/20/1014/13/FOTD8DC000099A7M.html
* https://finance.sina.com.cn/tech/2020-10-14/doc-iiznctkc5542661.shtml
* http://tech.ifeng.com//c//80XKHf5zHmL

For more information, please search more on Baidu & Google.

```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
IPFSUnion has an application-oriented strategy which focuses on how to push IPFS and Filecoin into massive commercial use in long-term basis. Therefore, we would like to support wide range of use cases. In addition, we are building strong relationships with various entities which have solid data resources such as: cloud service providers (i.e., Alibaba Could, Qiniu Cloud, UCloud, Kingsoft Could etc.), internet giant with huge data storage need, third-party institutions in different industries (i.e., universities, research institutions, public service organizations etc.). The allocation for the aforementioned types of use cases will be relative even to avoid potential bias.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
Base on some allocation rubrics shared by Andrew Hill at Fil+ Day, we have further standardized our allocation strategy in detail.  
The most important thing about DataCap allocation is to ensure that client utilizes DataCap to store real data. so I firstly specify some rules to figure out the true identity of the applicant.
* Browse their official website to get a general understanding of the company or the individual. 
* Query the company's registration information from government related websites to make sure the information he submitted is truth.
* Ask some questions to know about the applicant's position/organization/plan/use case etc. 
* Then We will classify applicants based on their industry reputation and scale etc. All applicants will be divided into eight categories to determine the amount of datacap they will get. The following Rubric will be the primary guideline I use when evaluating a client and determining their DataCap allocation.   
You can see it: https://docs.google.com/spreadsheets/d/1dD8aI3lsZGRp5rUWiULeRaPwFc7Z2z8tkzpdnTY-tyo/edit?usp=sharing
These scoring guidelines can serve as a tool of assessment and further to add a level of consistency across the board. 

```

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
There are not many internal processes because the whole application process should be open and transparent, and I don’t want to affect my credibility as a notary due to certain private procedures. There are only several necessary internal processes Currently.
1. Some brief communications via e-mail to make sure the e-mail address is authentic and valid.
2. For some companies involved in confidentiality that can’t answer some details in public, I will have some communications in my private repository. In the event of a dispute, I will share repository with officials immediately.
The target and amount about my allocation can be found in the scoring guidelines. As to the distribution rate, it depends on the number of clients applying to me. If there are a large number of high-quality organizations applying to me, I won’t be stingy with the DataCap in my hands. Currently, I plan to allocate 8TB DataCap per week.
In addition, I will try to simplify my process to enable applicants interested in DataCap to use it as soon as possible. For customers who apply for a large amount of DataCap, I will review them more carefully.

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
On the one hand, we will have some private keys that are stored in the hard wallet. on the other hand, we will set a multiple authentication mechanism (including check identity, review source of data and arrange for supervisor approval) to secure every step of DataCap allocation.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
There will be three stages in verification process to ensure the DataCap is used properly. Moreover, the greater the amount of DataCap requested, the more restricted the client scrutiny will be. The details are as follows:
```
   |  Stage  |  New Client/small DataCap request  |  Repeat Client/large DataCap request  |  
   |  ----  | ----  |  ----  | 
   |Before the allocation|1.  Ask for some details about his organization and use plan<br> 2.  Verify the submitted information<br> 3.  Score them according to our score sheet|1.  Learn about his DataCap usage<br>2.  Collect details <sup>[1]</sup> about his organization and use plan.<br>3.  Detailed review of related information<br>4.  Score them according to our score sheet<br>|
   |During the allocation|1.  2-day waiting period for possible adjustments or disagreements<br>2.  Allocate a small amount of DataCap (less than 5TB) for trial<br>|1.  At least a 7-day waiting period for due diligence, usage review, possible adjustments or disagreements.<br>2.  A DataCap allocation agreement will be signed to clarify the rights & responsibilities of each party.<br>3.  Allocate DataCap carefully after scoring|
   |After the allocation|1.  Provide help and guidance for DataCap users<br>2.  Communicate with customers on a regular basis to know his DataCap usage and leave him a good impression on Filecoin|1.  Conduct routine verification to ensure the DataCap is used properly<br>2.  Introduce a feedback mechanism to sync DataCap usage list and to optimize suggestion<br>3.  If the applicant commits any violation, we will take actions to stop further allocation or even take punishment actions <sup>[2]</sup>. |
   ```
   [1] Details include but not limited to these:
        1. Entity Information
        - Formation documents - this includes certificates of registration/incorporation/information.
        - government-issued identification number for the entity
        2. Authorized Signatory Information
        - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence including written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or the company operation agreement, if necessary).
        - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID.
        3. Beneficial Owners
        - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or something similar to verify the ownership, and also the following information for each of them:
        - legal name;
        - date of birth;
        - street address (P.O. box number is not acceptable);
        - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence;
        - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual.
        4. A file list which contains the size and datacid of each stored file.
 
   [2] Punishment actions may include disqualify the applicant certification, public its wrong actions in the community, stop further allocation forever, fine the FIL pledged by the client etc. In the extreme scenario, legal option will also be taken based on the aforementioned DataCap allocation agreement.

   ```
<br>

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
individual and organization
    1.	What's your name? What's your duty in your company? Please introduce yourself and your team briefly, and show me some your social media accounts such as GitHub, email address, WeChat official account etc.
    2.	For your organization, Please describe its time since inception, registration country，scale, named officers, project, industry reputation etc.
track record
    1.	How did you know about Filecoin? Please describe your understanding of Filecoin storage.
    2.	Please describe any of your honor and disputes in the field of Filecoin.
    3.	Regarding your data you intend to store, What’s the original source of those data, and do you have any proof of ownership or authorization?
    4. Has your organization obtained DataCap before? if so, please answer the following sub-questions.
        * Please share all links and recording of your application before.
        * How about your DataCap usage? Is there any remaining? Is there any information on the deals you've created and miners you've used with your previously allocated?
use plan
    1.	Please describe your plan to use DataCap as detailed as possible? (including use case, amount, timespan, geography, miner, partner etc.)
    2.	Do you plan to record your allocation decisions and execution details in public? 
    3.	How do you plan to protect the DataCap you have obtained to make sure that it is used to its best advantage?
In addition, I may further ask some questions to give an accurate score to the applicant.

```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Firstly, from the questions about use plan and further investigation, I can know some details about his allocation plans. When scoring applicants according to the above sheet, the more geographical distribution, use cases and miners assign, the higher score he will get and the more datacap clients are likely to get.  
Next, we will keep tracking clients’ information such as the DataCap distribution records, related miner addresses and storage providers, to ensure that they are consistent with their words and deeds.
Finally, a reward and punishment mechanism will be established. If someone over-allocating datacap to a single entity, I will refuse further allocation and issue a warning which will be public to the Filecoin community. On the contrary, reputable client have the opportunity to obtain more datacap.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
1. All allocation decisions will happen in public in the following[repository](https://github.com/filecoin-project/filecoin-plus-client-onboarding). Since all interactions are intended to occur publicly, most of the allocation decisions should be self-explanatory.
2. I will build a profile of every client who obtained DataCap from me in a public place, and the profile is like this: (https://docs.google.com/spreadsheets/d/1ZqDpBoWux6FP8n3fMITSyZhcln2OtrJGuL9E2IecBfw/edit?usp=sharing)
3. If there are any complaints about notary, a dispute resolution application can be filed to the Notary Governance after 14 days since its original challenge data. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
In public only. All allocation decisions will happen in the following [repository]( https://github.com/filecoin-project/filecoin-plus-client-onboarding )
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None
```

**Comment by dkkapur** [comment]
Hi @IPFSUnion  - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1o1KjzpsvB9bIoKv6VgATHEW7oQ0_Pq-Vwe4yQh_-QK8/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 2.1.

**Comment by IPFSUnion** [comment]
Hi @dkkapur ,Thanks for your detailed scoring. Based on the latest scored rubric, I made the following adjustments:
1. Individual Reputation： In fact, we have 2+ social accounts with more than 10000 followers, such as WeChat official account named "IPFS星际联盟“ has 42227 followers and "IPFSUnion星际联盟” has 14880 followers, Weibo account ”IPFS星际联盟FILE“ has 12137 followers. The evidences are summarized here(https://docs.google.com/document/d/1G3_PK3_e4p3OcjSxtBB1zSd8mUEXa7b7rwnYNNVqWEI/edit?usp=sharing).  
2. Stake Exposure： I re-counted the number of our tokens at stake, and found it has exceeded 5MM which you can check in the specific accounts.
3. In-protocal Security:  I have added some more details, hoping to get a higher score.

**Comment by dkkapur** [comment]
@IPFSUnion - thanks for sharing!
- Individual Reputation: updated to a 3 assuming you can affirm that posting about Filecoin, Fil+, etc., is possible to these accounts? 
- Stake Exposure: thanks, agreed; adjusted to a 4
- In-protocol Security: Based on Leo's contributions, this should be an L3; score adjusted to 3

The final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 2.4

Link to rubric: 
https://docs.google.com/spreadsheets/d/1o1KjzpsvB9bIoKv6VgATHEW7oQ0_Pq-Vwe4yQh_-QK8/edit?usp=sharing

**Comment by dkkapur** [comment]
@IPFSUnion - based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of 100 TiB. In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm that the region of operation for client applications you will focus on is [Greater China Region]

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

> * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

> * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

> * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**Comment by IPFSUnion** [comment]
1. Please confirm that the region of operation for client applications you will focus on is [Greater China Region]  
***Confirmed, [Greater China Region]***

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.  

    * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship  
    ***Confirmed***

    * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.  
    ***Confirmed*** 

    * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.  
    ***Confirmed*** 

    * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.  
    ***Confirmed***

    * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.  
    ***Confirmed***

    * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.  
    ***Confirmed***

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  
***f023530	/ f0131822 / f0133957 / f01231 / f0133505 / f0673920 / f016398	/ f0152337 / f066102 / f021479 / f0429122 / f053229 / f070932 / f0463030 / f0508328 / f0680529 / f0133501 / f0407733 / f089173 / f0449196 / f0155212 / f0154944***				

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  
***Confirmed***

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.
***f1enfilmuyphmnqexjt33zfbk56c25mo2lplgbpxa***

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1enfilmuyphmnqexjt33zfbk56c25mo2lplgbpxa
#### Datacap Allocated
> 100TiB

**Comment by dkkapur** [comment]
This went through correctly
