### ISSUE TITLE
Notary application : Julien NOEL / Twinquasar

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/notary-governance#136]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Julien NOEL
- Affiliated Organization: Twinquasar
- Website / Social Media: http://twinquasar.io / Slack :  Julien NOEL - Twin Quasar (s0nik42) 
- On-chain Address(es) to be Notarized: f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
- Region of Operation: I operate and I’m physically based in France / Europe
- Use case(s) to be supported: Any
- DataCap Requested: 100 TiB or any allocation that can be granted to my profile.

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
I’m the founder of Twin Quasar a Filecoin ecosystem mining and software development fully engaged with  Filecoin for many years. We invest money and all our time to support and help the Filecoin ecosystem.  We will do as much as we can for Filecoin to succeed.
Personally, I've been using  IPFS for years, I joined filecoin community 15months ago.
- Running miner : f010479
- Actively participating and Helping on slack(more than 20k messages)
- Granted twice for Lotus-farcaster
- Presenting for miner show and tell : https://www.youtube.com/watch?v=1JtQnhvxlVg
- Presenting for Celebration week : https://www.youtube.com/watch?v=cyer6_gSv78
- Participating to SR1 / SR2 Orbital burn / Slingshot 1/2.2/2.3 (project dCompute) / Apollo program
- Participating to Dorahack Hackathon
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
3000 Fil 
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- Proud and active MinerX member
- Actively participating and Helping the Filecoin miner community (thousands of messages on slack)
- Developing Farcaster an opensource software for the miner community
- Current Notary for EU. Participating to weekly calls and actively helping to scructure the Fil+ program.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
I identified a security bug on the faucet during SR2 not publicly disclose. Please liaise with @Why if you need more information.
- Developing a new service to protect the network against illegal content. 
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
I spent 17 years working for Tech companies with an expertise in Datacenters, Operating Systems, network and secuirty. My last position was Head of a Business Unit for a fortune 100 company.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
linkedin : https://www.linkedin.com/in/julien42/
Website : http://twinquasar.io
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Please answer here.
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
I’m looking to help and support filecoin growth. After working closely with the Notary during the first wave of notaries to define process to on-board large client, I would like to work on onboarding such client. 
In // I'm interesting to small project of the ecosystem like Lighthouse or MooseDar 
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
My apporach is similar to What I did until now  : 

Defining thresholds with varying degrees of trust.
Higher the request, Higher the scrutiny

Several factors will be considered when making allocation decisions: 
Reputation of organization
Scale of allocation over a certain period of time
Security considerations
Transparency of Client
Client engagement to respect guidelines :
	- Process
	- Delegation
	- Contractual terms. 
	- etc…
Sucess of a Probation period for new client (described below)
Public or Private Data
```

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
I run an internal tool to verify how the datacap has been spent.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
I'm using a Ledger
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
- Asking for commitment and transparency from the client
- Phasing : 
 - Approbation phase : 1tiB / 2TiB
 - Verify the process is understood from the client and correctly apply
 - Allocate More + Audit iteration (5TiB max)
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
 - Yourself , e.g. include links to social media / news mentions etc
 - Your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
 - Type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. 
 - public data vs private data etc
 - Your relationship with the data, especially with regard to copyright
 - How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
 - Have you already ask datacap to another notary that have been accepted or rejected.
 - Do you run a storage miner ?
 - How much data are you considering storing to your own miner ?
 - Please describe the nature of the relationship with this miner especially if you've got any interests in storing these miners ?
 - Will you agree to share here all the CIDs related to the datacap ?
 - Did you already have datacap from another notary ?
 - Adress confirmation
 
If the data is private, I ask much more information and authorization from the client to audit the data unencrypted. 
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
I ask the client to publish all the deals to the github repo. Then I go through all deals, verify they are correct, and calculate the % of allocation per miners
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
For transparency purpose, I plan to provide all the allocation decisions in public via a github repo. I will also agree to align the process the other notaries and the community; keeping in mind the processes we put in place have to be efficient. 
I will answer to any audits requests. 
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
For transparency purpose, I provide all the allocation decisions in public via a github repo. I will also agree to align the process the other notaries and the community. 
Private allocation will need more tooling and tracking that are not here yet. Depending on the volume of such requests I may consider accepting private requests.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes 10TiB : https://github.com/filecoin-project/notary-governance/issues/5
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
8TiB
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
No
```

**Comment by julien** [comment]
wrong @julien on GitHub though

**Comment by dkkapur** [comment]
Previous applications:
- https://github.com/filecoin-project/notary-governance/issues/5

Allocation track record from last round:
- 7 TiB allocated in past round, 4 client applications in repo, 4 verified clients in dashboard currently
- list of client applications approved: https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues?q=is%3Aissue+is%3Aclosed+label%3Astate%3AGranted+assignee%3As0nik42

Client applications and usage of datacap: 
![image](https://user-images.githubusercontent.com/2343218/120593742-c46f5800-c3f4-11eb-96c5-89ca744dc24b.png)

DataCap received by miner IDs:
| Notary Name | Miner ID | DataCap received in GiB | % of Notary's DataCap Grant |
|-------------|----------|-------------------------|-----------------------------|
| JulienNOEL  | f010446  | 256.000084              | 3.13%                       |
| JulienNOEL  | f01240   | 224.0000735             | 2.73%                       |
| JulienNOEL  | f02576   | 336.0001102             | 4.10%                       |
| JulienNOEL  | f023467  | 240.0000787             | 2.93%                       |
| JulienNOEL  | f01234   | 992.0003254             | 12.11%                      |

**Comment by dkkapur** [comment]
Hi @s0nik42 - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1tgvPPt7dSGaHBp7vcP_Z-7E77dKAyZR6ikYwEULtHxU/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial score is: 1.7.

**Comment by s0nik42** [comment]
Hi @dkkapur 

Line 11 : I think Farcaster position us to L2 instead of L1
Line14 : Can you explain a little bit more how it works ?

Line 22 : 
1/ 20% : Are the data : public /Private , verifiable, etc...
2/ 40% : data size based on number of clients / type of files / Existing proof of evidence of the data size (Online data / Invoice / etc...) 
3/ 20% : Evaluation of the usefulness of using IPFS/ Filecoin as a storage layer, etc...
4/ 10% : Data distribution : Geographic / Number of miners, etc... 
5/ 10% : Track record : Does the client is familiar with the Fil+ rules, successfully pass the probation period, etc... 

Line 23: 
We think we need agility here as the number of request in EU is not massive. We rather go for a case by case process than an industrial process like what our friends in other regions may need. BUT ! we're happy to comply with a Grid approach like how Fenbushi introduce to us if it's how the notary community wants to go. Please keep in mind that compared to large notaries we will never give more than 5TiB at a time. Which is a high risk  mitigation.    

Line 24 : 
We clearly states in our application that we will need more tooling for private request : `For transparency purpose, I provide all the allocation decisions in public via a github repo. I will also agree to align the process the other notaries and the community. 
Private allocation will need more tooling and tracking that are not here yet. Depending on the volume of such requests I may consider accepting private requests.
`
As of now, I never received any private  request and the notary community didn't confirm we should go done this road.

 The bookeeping we're doing via github is detailled enough for auditing : 
- We ask for the autorisation to audit the data before providing the allocation
- We engage our client to publish the CIDs in the slingshot format for all deals related to the datacap
- We check CIDs are published before allocating new datacap, and we verified the CIDs against the https://filecoin.tools/ API. (example : https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/136)

I think we should get a L3 or L4 here.  


Line 26: I think we should get L2 here

**Comment by dkkapur** [comment]
@s0nik42 thanks for sharing your comments. Addressing feedback here: 
- Line 11: Farcaster is still Filecoin specific. L2 here would apply in case your work also impacted adjacent communities like IPFS, other protocols / Web3 projects, etc. 
- Line 14: This is primarily to promote applications that are coming in for regions with minimal Fil+ presence. In your case, this ends up not really making a difference in the rubric, since you're weighed only against other Notary applications from EU, which already has existing notaries (3), hence the score of L2.
- Line 22: IMO this is a step in the right direction, but still counts as minimal specificity compared to many other applications.
- Line 23: Makes sense. Having a grid that you comply with and publish ahead of time would bump you up. This is already scored at 3.
- Line 24: Moved this to a 3 based on your bullets shared. Agree that private requests are not a priority at the moment and do not represent the primary usage of DataCap / Fil+. However, Bookkeeping plans that have scored beyond a 3 typically included the use of specific and dedicated tooling to help notaries flag client behavior that does not comply with their expectations. This applies to all clients, regardless of whether or not the allocation request was public or private. 
- Line 26: you are already at L2 here

The final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 1.7

Here is the link to the updated rubric: https://docs.google.com/spreadsheets/d/1nwkK6ooJDTau4sIeih21gjxPzyinNv7873KlujMq-Zg/edit?usp=sharing

**Comment by dkkapur** [comment]
@s0nik42 - based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of 98 TiB. In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm that the region of operation for client applications you will focus on is [Europe]

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

> * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

> * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

> * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**Comment by s0nik42** [comment]
> On 24 Jun 2021, at 11:43, Deep Kapur ***@***.***> wrote:
> 
> 
> @s0nik42 <https://github.com/s0nik42> - based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of 98 TiB. In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:
> 
> Please confirm that the region of operation for client applications you will focus on is [Europe]
> 
> 
EU
> 
> Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.
> 
> Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

f010479

> Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

Agreed
> Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

Agreed
> No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

Agreed

> Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

Agreed
> Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.
 Agreed
> Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt
> 
> 
f010479
> 
> Please affirm that you will abide by the allocation / client due diligence plan you laid out above.
> 
> 

I will

> 
> (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.
> 
> 

f1cenccszpgjssybrtoepkaagpysivg3zrifnesya

**Comment by dkkapur** [comment]
@s0nik42 - I was wrong about not being able to use the same address again as Notary. I mentioned this in Slack last week but want to check with you before next steps; would you rather proceed with reusing `f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii` or receive the second allocation at `f1cenccszpgjssybrtoepkaagpysivg3zrifnesya`? I recommend reusing the prior address to minimize management overhead between DataCap allocations.

**Comment by s0nik42** [comment]
@dkkapur yes reusing my previous address is my preference : f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### Datacap Allocated
> 100TiB

**Comment by dkkapur** [comment]
This went through correctly
