### ISSUE TITLE
Notary Application: IPFSForce - Steven Li

### ISSUE THREAD

**Issue by steven004** [filecoin-project/notary-governance#14]
# Notary Application
***Note: Please only submit PRs for proposed edits to this form. To apply as a Notary, please file an [issue](https://github.com/filecoin-project/notary-governance/issues/new?assignees=&labels=request&template=notary-application.md&title=).***

To apply as a notary, please fill out the following form. 

## Core Information
- Name: `Steven Li`
- (Optional) Affiliated Organization: `IPFS Force` 
- Website / Social Media: `@Steven on Filecoin Project Slack, @Steven004_Li on Twitter`
- On-chain Address(es) to be Notarized: `f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna`
- Region of Operation: `Greater China`
- Use case(s) to be supported: `User Content, Scientific Data, Media & Entertainment`
- DataCap Requested: `100TiB`

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

```
As an individual, I has been deeply cultivating distributed storage for over 10 years in multinational and startup companies.

I was the head of Cisco (China) Cloud Object Storage and the core developer of China's first-generation security routers. With my knowledge and experience in networking, security and storage, I fell perfectly align with Filecoin's vision as a DSN infrastructure for humanity information storage.

As an advocate and practitioner of distributed storage and Web 3.0, I started focusing on IPFS study and development since 2017. Early 2018, I joined in Filecoin Community and work as Co-Founder & CTO of IPFS Force. Since then, all of my working time is on IPFS and Filecoin ecosystem buildup.

At present, I am committed to the design and ecological construction of key modules such as Filecoin's consensus algorithm, proof of replication, economic model and mining cluster architecture.
```
More information:
- GitHub handles: steven004
- IPFS Force Miner ID: f02438, f02425, f02731, f020604, f02726, f03266, f03287, f02610, f02721
- Slack: @Steven
- Participating to DevNet/ TestNet/ HackFS/ SR1/ SR2/ Slingshot 1(as reviewer)/Filecoin Community activities as one of top testers and miners
- Stewardship of Filecoin Implementation: Venus(go-fliecoin)

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Total stake: 1.09MM FIL with Miner ID f02438, f02425, f02731, f020604, f02726, f03266, f03287, f02610, f02721 as collateral(viewed on Nov. 20th, 2020)
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

```
As an Individual, I have been working as an IPFS/Filecoin ecosystem advocate and builder:
- Weekly IPFS/Filecoin/Web3 technical or marketing articles (over 100 articles published)
- Speaker of IPFS/Filecoin/Web3 conferences
- Organizer and lecture of Protocol School Shanghai Chapter
- Contributor of Filecoin protocol and code development via issues/PRs commitments

As the technical lead and co-founder of IPFS-Force community, led and helped the team: 
- Established and lead IPFS/Filecoin activities in China: Force Open Day(#148 on Nov. 17th 2020), Protocol School Shanghai & Chengdu, EOS & IPFS HackFS
- Published IPFS/Filecoin related reports and articles: whitepaper translation, 1-67 Filecoin Weekly Report, 1-108 IPFS Weekly Report, IPFS/Filecoin Ecological Report, SpaceRace Report, Filecoin Mining Guidelines (1-3 series), 100 Questions about IPFS/Filecoin and other reports and articles wrote by IPFS-Force researchers and analyzers

Recently Filecoin Community activities
- Filecoin Open Day, Oct. 26th 2020
- Filecoin Core Devs Biweekly #5, https://www.youtube.com/watch?v=jCJFhhR0gW8&t=2495s
- How We Won Space Race, Oct. 21th 2020, https://www.youtube.com/watch?v=1QVa48Eela8
- Filecoin Protocol Implementation: What's next?, Oct. 21th 2020, https://www.youtube.com/watch?v=JmvQ0F1qtYQ
- Filecoin Chain Explorers, Oct. 21th 2020, https://www.youtube.com/watch?v=f2sk2WqrIjs
- Space Race Miner Show & Tell, Spe. 4th 2020, https://www.youtube.com/watch?v=pHi85ZNs3AY
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
Security is the first priority and the most important factor of a chain. I, as the key engineer of the China's first generation of secure router, paid a lot of attention on security of the system, and contributed to Filecoin via publicly submitted issues, or privately discussion due to the sensibility of some security issue.

Some of the issues submitted related to security: 
- 
- https://github.com/filecoin-project/specs/issues/559
- https://github.com/filecoin-project/venus/issues/3308 
- https://github.com/filecoin-project/venus/issues/3349
- https://github.com/filecoin-project/venus/issues/3523

There are some discussion in slack private channel or via email too, e.g. 
- Nondeterministic signature of round winner calculation
- Owner change proposal from security prospective
- determiistic winner of big miners, to drive the winning algorithm change
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
IPFS Force started in May 2017 is a non-profit decentralization storage and web3 community, based in Shanghai, China.

IPFS Force community is sponsered by Shanghai Kunyao Network S&T Co., Ltd. since Kunyao was set up in July 2018 as a company. 

IPFS Force regularly conduct meetups and events, and support the industry to develop application, Filecoin mining, and provide services.

Currently, IPFS Force has near 100 core members, and hundreds of thousands of participants of hosted events via on-site or on-line events.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: ipfser.org
Twitter: https://twitter.com/force_ipfs
Weibo: https://weibo.com/p/1006066336693097/home?from=page_100606&mod=TAB#place
WeChat Oifficial Account: IPFS原力区

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.8btc.com/media/634903
https://www.jinse.com/lives/200205.html
https://36kr.com/newsflashes/973370131575041
https://36kr.com/newsflashes/669046320289795
https://news.huoxing24.com/flash/20200825220511648353.html
https://news.huoxing24.com/flash/20200706192231201068.html
https://news.huoxing24.com/flash/20200706191320331822.html
https://www.jinse.com/lives/200205.html
https://www.jinse.com/lives/175039.html

```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Scientific Data(AI training, geological data, autonomous driving) 
Media & Entertainment(video & music)
User Content(personal user storage)

```

# Allocation Plan Template
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.

> The purpose of allocating the DataCap is to make sure clients use these DataCap in the right way.
>
> For new clients, there will be offline investigation and discussion regarding who they are, what they will use filecoin as a storage to save, and how to do it, based on that, I would have the first judgement to qualify or not as verified clients.
> 
> For qualified clients, my allocation strategy emphasizes historical reputation and also the plan for new-required data investigation.
We plan to allocate DataCap with small incremental amount(<10%) and build a reputation mechanism.
> Each allocation will be considered as an assessment of clients reputations with score accumulation and corresponding trust degree.
For example, if a client applies for DataCaps, provides valid data and spends these DataCap responsibly, his reputation credit will increase. With higher credit, Clients can apply for more DataCaps in the future.
> We are also willing to use Filecoin Plus Registry to make all allocation in public.

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap? 

> Referring to the Filecoin Plus Client Rubric & Allocation Draft, I edited a draft of credit and scoring mechanism of clients and communities or individuals behind, with the limitation of minimum 1GB and maximum 100TB DataCap. See the details from:  https://drive.google.com/file/d/1Zy7TLZN1dEqYNWubgMUdnog_c885-1KB/view?usp=sharing
>
> At this moment, I think it’s good time to attract more external data providers to come into the Filecoin Network, become verified clients and store useful data. For this reason, my audit mechanism will evaluate the value of data as well. Clients with high-value data can have priority of allocation and larger amount of DataCap. The initial rules are list in the table: https://drive.google.com/file/d/13w0H3DMrKMeXFP4x1COFWx03Ohhhk0Ap/view?usp=sharing. 
Basically, the more value the data can bring to the network, the more can be be granted. 
> 
> Besides, there will also be a 10% incremental allocation strategy. For example, if clients(applied DataCap from me) provide valid data without improperly over-allocating as they promised, and all of checked data are qualified, when the next time they apply for DataCap allocation from me, their allocation could have maximum 10% increase.

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

> The offline wallet had been developed and verified for the accounts associated with the Datacap allocation.
And, multisig wallet is to be used when there are more clients coming in.

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 

In the early stage, all clients has to go through a strict process to be qualified. Firstly, I need to collect information including:  
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information; 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name;
 - date of birth; 
 - street address (P.O. box number is not acceptable); 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

 With these provide, an interview and data source checking process need to go through. After that, an agreement should be signed for the next step - gradually allocate datacap and let the client gather more credit. 

```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
1. Introduction of yourself/ your organization(with links)
2. Use case
3. Location
4. Max DataCap Allocation
5. Filecoin address
6. Miners you intend to allocate DataCap with allocation proportion
7. Specific requirement of miners and storage service
8. For-profit or not

```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Periodical inspection and audit of DataCap usage
Use incentive mechanism: encourage clients to report unfair allocation
We will also develop a tool to randomly check all the clients' verified deals to make sure they are following the protocol.
 
Once our team complete the development of audit tool, we are happy to make it open sourcing and provide technical specifications or architecture docs, so other notaries can use it. This toll will require clients to post deal transaction in public, and Filecoin Community can audit data and storage deals once again.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Yes, all allocation decisions will be guided by the rubric publicly on Github.  
Since all interactions are intended to occur publically, most of the allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly, e.g. the Github repo.
If convincing justifications can’t be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions. 

```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
In pubblic(tentatively on GitHub) in order to be supervised by Filecoin Community
 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None

```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None

```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None

```

**Comment by jnthnvctr** [comment]
Hi @steven004  - we have a draft of your scoring here - please see Column H for some comments!

https://docs.google.com/spreadsheets/d/1l95mDpn8v2rF9s_G-SfgHKmKl0np_tUR8A09V69AxRY/edit?usp=sharing

Would you be able to review and address? Specifically I want to call your attention to: 
Row 21: To ask if you could provide a little bit of clarity on your 10% cap proposal (and how you intend to increase the allocations). Additionally, if you'd like to see an example of what a higher detail application might look like - there is a good example [here](https://docs.google.com/spreadsheets/d/1zQ3FXJmmBMmynDIdRjYTYp-K95Dp95ypVoBfRhABPC0/edit?usp=sharing). 

Row 22: To ask if you'd be interested in open sourcing the tooling you'll be using! 

Row 23: To call out that the current Filecoin Plus Registry currently integrates only with a Ledger for signing. You can still accept requests from the Registry (and iterate in the public repo), but if you intend to use other tooling to process the allocation you will likely need to do that out of band (and we can coordinate with your team how we can give you API write access to publish your actions in the Repo). 

Please note this scoring might be affected by the proposed rubric update here: https://github.com/filecoin-project/notary-governance/pull/36

**Comment by steven004** [comment]
@jnthnvctr ，would you please grant me the access to https://docs.google.com/spreadsheets/d/1l95mDpn8v2rF9s_G-SfgHKmKl0np_tUR8A09V69AxRY/edit?usp=sharing. 

Without the access, I can just reply the questions below based on my understanding at this moment. 

> Row 21: To ask if you could provide a little bit of clarity on your 10% cap proposal (and how you intend to increase the allocations). Additionally, if you'd like to see an example of what a higher detail application might look like - there is a good example [here](https://docs.google.com/spreadsheets/d/1zQ3FXJmmBMmynDIdRjYTYp-K95Dp95ypVoBfRhABPC0/edit?usp=sharing).
> 
Did not see Row 21 for the 10% cap proposal. But if you mean my 10% incremental allocation strategy. I mean that I would regularly check the clients' verified data (all data, or randomly picked data). While if all of checked data are qualified, the client's next data cap could have maximum 10% increase. 


> Row 22: To ask if you'd be interested in open sourcing the tooling you'll be using!
> 
Yes, no problem. 


> Row 23: To call out that the current Filecoin Plus Registry currently integrates only with a Ledger for signing. You can still accept requests from the Registry (and iterate in the public repo), but if you intend to use other tooling to process the allocation you will likely need to do that out of band (and we can coordinate with your team how we can give you API write access to publish your actions in the Repo).
I would think there is no difference between signing with a Ledger or with an air-gap signing software. And in the early stage, it is also fine to do it out of band. Please point me to the integration document or implementation, so that we can move on to nail down the solution.

**Comment by steven004** [comment]
@jnthnvctr 
To address your questions, I updated [the application](https://github.com/filecoin-project/notary-governance/issues/14#issue-747912777) to include more information, including the detailed scoring system, mainly focus on the **Allocationn Strategy** and the **Client Due Diligence**.

**Comment by jnthnvctr** [comment]
Hi @steven004  based on your updated submission - we have scored your applicatoin here: https://docs.google.com/spreadsheets/u/1/d/1tfwRJvoWo8UNN7OKoE_2H6hZX8urfOkCaOsxe5H6vBM/edit?usp=sharing

Eligibility score: 2
Unrounded score: 2.2

**Comment by jnthnvctr** [comment]
Hi @steven004 - as mentioned on the governance call yesterday, your team was in the top of your region for being a prospective Notary! Prior to confirming your role as a Notary, there are a few items that need to be affirmed: 

1. Please acknowledge the region of operation in which you tend to primarily focus: [GCN]

2. Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.

* **Upfront Disclosures**: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship. 

* **Promoting Client Best Practices**: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found [here](https://github.com/filecoin-project/notary-governance/issues/9).

* **No Self Dealing**: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

* **Operating in good faith**: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

3. Please list any addresses you are affiliated with below - stating the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt. 

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above. 

5. (If ready) - Please confirm the address that should receive DataCap.

**Comment by jnthnvctr** [comment]
Additionally, if you plan on being listed in the Filecoin Plus Registry - please confirm what information you'd like to have displayed below. Please note that public requests currently write to a public repository (and we can work with you to configure the requests as needed). 

"name": "Your Name",
"use_case": [
    "List",
    "of",
    "Use Cases"
],
"location": "EUR",
"github_user": "notaryc",
(optional) "website": "google.com",
(optional) "max_datacap_allocation": "100 GB", // To indicate to clients what size allocations you might support. 
(optional) "private_request": "false",                       // set as true if you plan on supporting private requests. 
(optional) "email": "youremail@a.com",                 // only needed if you are supporting private requests
"info": ""                                                                            // You can use this to share information with Clients about your allocation strategy / reqs

**Comment by steven004** [comment]
> Hi @steven004 - as mentioned on the governance call yesterday, your team was in the top of your region for being a prospective Notary! Prior to confirming your role as a Notary, there are a few items that need to be affirmed:
> 
> 1. Please acknowledge the region of operation in which you tend to primarily focus: [GCN]

Yes, we are in GCN. 

> 2. Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.

> * **Upfront Disclosures**: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship.

ACK
    
> * **Promoting Client Best Practices**: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found [here](https://github.com/filecoin-project/notary-governance/issues/9).

ACK

> * **No Self Dealing**: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

ACK

> * **Operating in good faith**: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

ACK

> 3. Please list any addresses you are affiliated with below - stating the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

- All ForcePool miners and their related owner / worker / controller addresses; The owner/worker/controller addresses might change for security or other reasons, but the miner ID will keep the same. 
- ForcePool miner list: f02438, f02425, f02731, f020604, f02726, f03266, f03287, f02610, f02721
- All the miners are managed by IPFS-Force and owned by investors

> 4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

ACK

> 5. (If ready) - Please confirm the address that should receive DataCap.

`f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna `, as listed in the application

**Comment by jnthnvctr** [comment]
Thank you for all the above! If in the future you have relevant IDs to disclose, please add them to this issue (and state the relevant affiliation information).

To confirm also - the public location for your decisions will be the same repo as the Filecoin Foundation? If somewhere different, please just share a link to where you intend those decisions to be processed. 

Regarding the integration with the dashboard, I will connect you on Slack with the relevant team. Note, you do not need to use the same app as the Filecoin Foundation for signing - and if you're signing out of band you can still make use of the Registry for listing (and iterate in the public Github repo for decisioning).

**Comment by steven004** [comment]
> Thank you for all the above! If in the future you have relevant IDs to disclose, please add them to this issue (and state the relevant affiliation information).

Sure.


> To confirm also - the public location for your decisions will be the same repo as the Filecoin Foundation? If somewhere different, please just share a link to where you intend those decisions to be processed.

I will start with the same repo as the Filecoin Foundation, at the same time, we are developing tools for this. I will share it once it is workable.

> 
> Regarding the integration with the dashboard, I will connect you on Slack with the relevant team. Note, you do not need to use the same app as the Filecoin Foundation for signing - and if you're signing out of band you can still make use of the Registry for listing (and iterate in the public Github repo for decisioning).

Really appreciate!

**Comment by dkkapur** [comment]
@steven004 - just want to double check, would you like to be listed in the public Filecoin Plus Registry as a Notary? If so, could you please fill this out (or confirm that you don't want this) and we can move forward with the final step of confirmation?

```
"name": "Your Name",
"use_case": [
"List",
"of",
"Use Cases"
],
"location": "GCN",
"github_user": "steven004",
(optional) "website": "google.com",
(optional) "max_datacap_allocation": "100 GB", // To indicate to clients what size allocations you might support.
(optional) "private_request": "false", // set as true if you plan on supporting private requests.
(optional) "email": "youremail@a.com", // only needed if you are supporting private requests
"info": "" // You can use this to share information with Clients about your allocation strategy / reqs
```

**Comment by steven004** [comment]
@dkkapur , I would like to be listed in the public Filecoin Plus Registry as a Notary before new tools developed and published. Information to display: 
```
"name": "Steven Li",
"use_case": [
"Open datasets that serve as a foundation for humanities most important information",
"data affiliated with strategic growth initiatives of the Filecoin project",
"data from centralized cloud storage clients looking to switch to Filecoin network"
"Personal public data for copyright/property authentication"
],
"location": "GCN",
"github_user": "steven004",
"info": " " 
```

Please let me know if anything more required. Thanks.

**Comment by jnthnvctr** [comment]
## Request Approved
#### Address 
> f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna
#### Datacap Allocated
> 100TiB
