### ISSUE TITLE
Notary Application-Matrix Storage

### ISSUE THREAD

**Issue by MatrixStorage** [filecoin-project/notary-governance#141]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name:Matrix Storage
- Affiliated Organization: Hainan Anmai Cloud Network Technology Co., Ltd. 
- Website / Social Media:
Website of Matrix Storage：https://storage.anmaicloud.com/ 
GitHub：https://github.com/MatrixStorage
Slack：https://filecoinproject.slack.com/archives/D020S5V5JF3
Website of Hainan Anmai Cloud Network Technology Co., Ltd. ：https://anmaicloud.com/
- On-chain Address to be Notarized:f1rgwkydqsbbadhvdhfjfxcy5ohra2nj2atxe2a4y
- Region of Operation: Greater China
- Use case(s) to be supported:General，prefer cases on IPFS ecological applications, not limited to Web3.0 or Dapp, and big data service.
- DataCap Requested:1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Nature of Matrix Storage:
Matrix Storage is a decentralized storage service platform of Web3.0, which is independently developed by Hainan Anmai Cloud Network Technology Co., Ltd. We have officially launched and provided service in mainland China on April 21, 2021.
Anmai Cloud is a global decentralized cloud computing provider with one-stop service.It provides distributed cloud computing resources, products and services to users, including IPFS computers, IPFS infrastructure solutions, cloud GPU computing services, distributed storage toolsets, enterprise-class distributed PAAS services, etc.
GitHub:https://github.com/MatrixStorage
Node: It has established cooperation with Athena Pool, possessing of computing power ranks the first all over the word with about 70 nodes.
https://explorer.atpool.com/zh-CN/athena

Major Projects:
At the present stage, the most important mission of Matrix Storage is to provide customers with fast, stable and reliable decentralized Storage services based on IPFS and Filecoin network. We have established data storage cooperation with many domestic enterprises with stored data reaching 23 TiB, which is uploading. With the large-scale promoting of Matrix Storage within the next year, we expect that there will be more than 1PiB effective data stored through Matrix Storage.
http://prnews.techweb.com.cn/qiyenews/archives/209018.html
https://www.fromgeek.com/daily/1044-402139.html
http://www.cctime.com/html/2021-5-21/1573219.htm
https://smart.huanqiu.com/article/43Bp6EpDa8z
https://mp.weixin.qq.com/s/m2NmJaS1NlGlSFrpp8nhtA
https://tech.ifeng.com/c/86OX6f46sUm

Cooperation projects：
1.Cooperative Enterprise
-We have Launched IPFS co-branded gene testing tool, for consumer through cooperating with 23Mofang, which is the largest consumer gene testing product in China. There are more than 2PiB of genetic test data from more than 10 thousand users, which will be stored on the chain through Matrix Storage. At the same time, 23Mofang will cooperate with academic institutions to study "Health Guideline for Young People", "Discovery, Prevention and Treatment of Common Diseases", "Ethnic Tracing", "Various Relationship between Obesity and Physical Index", etc.. And all these research results will be decentralized stored through Matrix Storage.
Website of 23Mofang:https://www.23mofang.com
-We have provided decentralized storage services to Codoon Health, from comprehensive health industry, and safeguard the storage of their health data.
Website of Codoon Health:https://www.codoonhealth.com
-We have provided decentralized storage of legal material evidence for Zhongjing Tianping, the subordinate enterprises of State Information Center (China Economic Network). In combination with blockchain technology, the copyright of users' electronic data is guaranteed by means of electronic signature, timestamp, distributed cloud storage, hash verification, etc., which realize the safe archiving and backtracking of the stored data.
Website of Zhongjing Tianping:https://www.bjzjtp.com
-We provide storage services for Digital Media Industry Base. The Data to be stored is related to Tibetan, Qiang and Yi culture and can be downloaded and used by film and television lovers, production institutions. Digital Media Industry Base, founded on January 05, 2005, is one of the four national digital media technology industrialization bases, distributed and constructed by the Ministry of Science and Technology in China.
Website of Digital Media Industry Base:http://www.cd-szmt.com
2.Cloud Service Provider
-We have established strategic cooperation with domestic centralized storage service providers Huaqi Cloud, China's leading cloud media service provider, and Qiniu Cloud, a well-known cloud platform service (PaaS) provider in China. It reduces the storage cost of massive audio and video files caused by the radio and television media industry, and expands more service scenarios. We plan to launch decentralized storage products within this year to provide storage services for their customers' archived data. Currently, technology docking is under way.
Website of Huaqi Cloud：http://www.chinamcloud.com
Website of Qiniu Cloud：https://www.qiniu.com
Related Link：https://baijiahao.baidu.com/s?id=1700195421766703794&wfr=spider&for=pc
3.Cooperation on Ecological Applications
-At present,  Matrix Storage has provided storage support for APP used in judicial collection, and this product will provide service for judicial industry personnel to collect evidence.

Major contributions:
In March 2021, Matrix Storage participated in the 2021 Global Computing Power Summit, named "Peak Computing Power", which was guided by Ya 'an Bureau of Economic Information, hosted by Anmai Cloud and China Software Industry Association, and co-organized by Shutian Information and Ya 'an Digital Economy. Matrix Storage was invited to introduce the product at the conference. This summit makes industry participants have a knowledge of decentralized storage services based on IPFS and Filecoin networks.
The organizing committee communicated with outstanding enterprises and government  to seek development in accordance with the policy. During the conference, dozens of leading enterprises in storage and computing industry, including AMD, Nvidia, Qiniu Cloud, Seagate, etc., had in-depth exchanges on the new paradigm of digital economy around the theme of distributed storage and blockchain. The top miners gathered to open discuss about the new trend of the power industry, current technology and industry hot spots. Investment and research institutions joined hands with industrial capital to explore the future of distributed storage industry, systematically grasping the trend and opportunities brought by industrial upgrading in the new infrastructure era, and talked about the industrial hot spots.
A strong lineup of enterprises and guests from the whole industrial chain of distributed storage participated in this summit, including AMD, Dell, Inspur, Sugon, H3C Technologies, Huawei, Lenovo, Digital China, DapuStor, Seagate, Western Digital, IBM, Qiniu Cloud, and dozens of other companies.
Related reports：
http://www.yaan.gov.cn/gongkai/show/20210330151012-33060-00-000.html
https://www.jinse.com/news/blockchain/1018910.html

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
`Matrix Storage serves as a platform, which do not directly participate in mining so as to have no nodes. We hold a little FIL for product testing.`

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Although the Matrix Storage project was officially launched in April 2021, early technology research based on IPFS and Filecoin networks began as early as July 2019, which is also organization registration time (link：https://aiqicha.baidu.com/company_detail_25374366564015?rq=es&pd=ee&from=ps). Therefore, after the mainnet was launched, a special project team was quickly set up to do product research and development, complete products were presented in a short period of time, and market customers were accumulated in the early stage. Matrix Storage product system based on IPFS and Filecoin network is built. The system consists of an enterprise-class storage platform, a storage tool set and a C-terminal application.
1.Production Line of Matrix Storage Business-oriented Platform
Functions implemented in this version 1.0.0:
-Upload/archive of files
Files are uploaded to the IPFS network as warm data, and archived to the Filecoin network maintained by miners as cold data.
-Extraction/download of files
The archived files need to be extracted from miners'  distributed network to the IPFS network/matrix storage centralized server for download service.
-Access control of files
Files storage can be divided into public or private storage. The publicly stored files will reside in the public IPFS network and can be accessed from any public IPFS network.The files in private storage can only be accessed through the IPFS network built by Matrix Storage.
Functions implemented in this version 1.0.1:
-List Multipart Uploads added in API
Users can choose the data size while uploading and synthesize a complete file to form a CID after completely uploading, which improve upload success rate.
-Multiple uploading of the same file. 
Multiple uploading of the same file is supported for users. 
-Filecoin address import function
Import existing Filecoin address into matrix storage systems to make full use of existing FIL is supported for users.
-The single uploading file jumped from 512MB to 64GB on Web.
Meet the needs of using the web console to transfer large file
2.Core function of Matrix storage -IPFS cloud disk
-Upload/download of image V1.0.0
Upload the phone photo and download it from the IPFS network
-Preview/Share of image V1.0.0
Images are previewed via IPFS gateway and shared in WeChat applet/Moments via CID .
-Import of third-party partner data V1.1.0
Third party partners (23 Mongfang mentioned above)  is supported to upload specific data to customer's specific IPFS cloud disk and download.
3.Matrix Storage provides open API interface; visual debugging and online command-line tools, helping users to upload data files easily. Application SDK provides JAVA, Python, C and other multi-language SDK, so that users with development ability can directly complete the secondary development, effectively improving efficiency and performance.
4.We are developing NFT middleware, which is the first Web3.0 oriented middleware product of Matrix Storage. NFT developers can easily access IPFS/ Filecoin network through EasyNFT middleware.
In addition, we have also posted a project profile about Matrix Storage on the Slack channel to let more industry participants know more about our service.
https://www.kejixun.com/article/210521/527318.shtml
https://tech.sina.com.cn/roll/2021-05-21/doc-ikmxzfmm3845980.shtml
http://news.ikanchai.com/2021/0521/422452.shtml
http://www.citnews.com.cn/news/202105/128329.html
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
[BUG] GenerateUnsealedCID,more than 32 GB file,return Piece is large then sector #6292https://github.com/filecoin-project/lotus/issues/6292
Matrix Storage is developing tools to provide notaries with a trading display of clients and miners' nodes. At the same time, miners and clients can post/bid on the trading market online. Making all transactions fair and transparent, so as to achieve trade compliance from the source.
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Matrix Storage provides an intermediate bridge between data storage needs and data storage providers by providing easy-to-use PaaS services, OpenAPI services, and a storage toolset suite. On the one hand, it connects with customers who have data storage requirements. on the other hand, it connects with stable and reliable storage service providers, and forms an ecological closed loop of decentralized storage network from data production, data verification to data storage. It builds a collection and distribution service platform for verifiable data storage, and provides one-stop distributed data storage solutions for large-volume and multi-type data-intensive industries, such as the customers mentioned above.
As a bridge established for connecting the underlying technology with real business needs, Matrix Storage has established cooperative relationships with core people in the upstream and downstream industries.
Miners: 
We have established a cooperative relationship with Athena Pool, the top in the industry, and provided more stable storage nodes for storage users, which ensure the stability and reliability of the storage cluster and achieve the effective balance between the performance and cost. There will be more high-quality and stable nodes joining Matrix Storage  in the future, and provide users with more storage options and storage space.
https://www.donews.com/news/detail/4/3151551.html
http://news.yesky.com/hotnews/211/725744711.shtml
http://www.itbear.com.cn/html/2021-05/405335.html
Clients: 
Matrix Storage is implemented in the fields of radio, television and video, big data of genes, big data of health, judicial storage and AI agents, as mentioned above.
At present, we are pushing forward to try more cooperation with traditional storage service providers. We are also looking for more enterprise users who have real data storage needs to provide them with more secure, more reliablemore convenient , and  less costly storage products.
Links：
http://finance.sina.com.cn/tech/2021-01-15/doc-ikftpnnx7560619.shtml
https://baijiahao.baidu.com/s?id=1700195812822277472&wfr=spider&for=pc
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Matrix Storage's team was established in October 2020 and possess of independent research and development, promotion and operation personnel. At present, there are more than 20 research and development personnel and more than 10 promotion/operation personnel. The average working experience of R&D personnel is more than 5 years.
Website：https://storage.anmaicloud.com/
https://github.com/lucifercd Mr.Lu participated in the issuance and promotion of cryptocurrency
https://github.com/kiba-zhao
https://github.com/lei286394973
https://github.com/back0893
https://filecoinproject.slack.com/archives/CR98WERRN/p1620384716043500

Anmai Matrix Storage promotes the large-scale application of distributed Storage technology
https://smart.huanqiu.com/article/43Bp6EpDa8z
https://mp.weixin.qq.com/s/w7pWomuxN-CMVUM2BfDCGw
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Anmai cloud has become the first member of the "Hainan on Chain" Ecological Alliance https://www.anmaicloud.com/am/midea/article/detail?
Hainan Anmai Cloud Network obtained the "Value-added Telecom Business License of the People's Republic of China" https://www.anmaicloud.com/am/midea/article/detail?Id=45&Lang=zh_CN&typeName=%E5%B8%82%E5%9C%BA%E5%8A%A8%E6%80%81
Promote the application of distributed storage and computing on Software Defined Storage Summit 2021
  https://anmaicloud.com/am/midea/article/detail?Id=64&Lang=zh_CN&typeName=%E5%B8%82%E5%9C%BA%E5%8A%A8%E6%80%81
2020FAT“Top 100 in Blockchain Fintech” https://anmaicloud.com/am/midea/article/detail?Id=42&Lang=zh_CN&typeName=%E5%B8%82%E5%9C%BA%E5%8A%A8%E6%80%81
Council member of China Chamber of International Commerce https://anmaicloud.com/am/midea/article/detail?Id=40&Lang=zh_CN&typeName=%E5%B8%82%E5%9C%BA%E5%8A%A8%E6%80%81
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Matrix Storage provides decentralized storage services based on IPFS for users from all industries. As long as the data and business are in compliance with laws and regulations, we do not make too many requirements in terms of type. In addition, we believe that big data can benefit mankind, so we encourage more enterprises to store public data that can be retrieved.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
We calculated the level of applicants through scoring, and set maximum amount  for each level in first allocation, so that we could fully follow up the usage of applicants;
All individuals and businesses are encouraged to get involved in the IPFS business, but we prefer organizations in order to build the IPFS ecosystem more quickly.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
We judge the qualification on a scale of 1 to 4 (round), and our scoring mechanism is as follows:
```
![image](https://user-images.githubusercontent.com/82867405/119134947-5d56b880-ba70-11eb-90cc-8ac5612a4c7b.png)

```
1.The entire application and allocation process will be transparent and open;
2.Strictly review the information provided by users, including but not limited to some written evidence;
3.Establish online communication audit mechanism and offline investigation audit as far as possible;
4.Score will be given after reviewing the information provided by clients;
-We will confirm the previous DataCap usage when clients submit next application.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The private keys will be stored in the hard wallet
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
According to the business & technology planning submitted by the applicant, we will conduct a sample survey on the applicant's business in effectiveness, continuity and usage after DataCap have been granted:
1.Communicate with organization, contact person online/offline from time to time;
2.Submit the information to prove the business is in operation;
3.Extract and view data samples;
4.Query the usage of DataCap.
If the applicant is found that they use DataCap irresponsibly or exchange benefits existing, the applicant shall immediately disclose this information to the authorities and cooperate in the verification. If it is true, the applicant shall be disqualified from the allocation. The processing result and the true situation shall be published to the community.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
1.Why did your company choose IPFS industry and decentralized storage?
2.Can you give more details about duration, nature, scale of your company?
3.What industry does the company mainly serve/how many people are served?
4.Can you present future business or technology plans?
5.Can you explain in detail about data type, and copyright ownership? And how much data will your company store? 
6.Does your company need to call for stored data, and if so, how often it happens?
7.How many miners do you want to choose for storing the data? How much DataCap will be allocated to each miner?
8.Will you publicly record allocation decisions?Which platform will you use?
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
During the review phase, we will ask questions about the allocation, the allocation preference of the applicant, and encourage collaboration with several miners. After the allocation, we will track the user's DataCap usage and business development to ensure that the allocation plan provided by the applicant is real. If you have any questions or other questions, we will keep abreast of the situation.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
We will record our allocation decisions.
At the early stage, we will record in the form of Excel, which includes issue number, applicants, current state, DataCap requirements, application date, website/social media, nodes and proportions; Filecoin address, GitHub account, result; result time, DataCap allocation, and remarks. At the same time, we plan to record it through Matrix Storage system.
```
![image](https://user-images.githubusercontent.com/82867405/119292124-57d0bc80-bc82-11eb-9134-0e468e5c7e27.png)

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be public
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```no```

Cumulatively, how much DataCap have you previously successfully allocated? 
```no```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```no```

**Comment by dkkapur** [comment]
Hi @MatrixStorage  - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/13g4jTJDJz1DYKMGu-W2wG_w5HgjR9TT4L8VDlNgmgC0/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.4.

**Comment by MatrixStorage** [comment]
Hi, Deep. Thanks for your initial score.
I would like to add more information about some categories.

**1.Time Commitment** 
Anmai Cloud,  affiliated Organization of Matrix Storage, worked in the distributed storage industry as early as 2019. Matrix Storage officially started the project construction and technical pre-research. At present, Matrix Storage have been working in the IPFS/Filecoin for 2 years.

**2.Stake Exposure**
In order to make business progress smoothly, Anmai Cloud assigned the miner ID, f0135467 (more than 1.44mm FIL with the Miner), to Matrix Storage to support the daily consumption and operation of the project

**3.In-protocol Reputation**
Over the past 2 years, We have established data storage cooperation with many domestic enterprises with stored data reaching 23 TiB, which is uploading. With the large-scale promoting of Matrix Storage within the next year, we expect that there will be more than 1PiB effective data stored through Matrix Storage.  Industry leading enterprise, such as 23Mofang, the largest consumer gene testing product in China, Zhongjing Tianping, the subordinate enterprises of State Information Center (China Economic Network), Digital Media Industry Base, one of the four national digital media technology industrialization bases,  Huaqi Cloud and Qiniu Cloud, China's leading cloud media service provider, have became our cooperative parters.
https://baijiahao.baidu.com/s?id=1700195421766703794&wfr=spider&for=pc
At the same time, we set up WeChat groups. These WeChat groups have linked storage users and storage resource providers. Users can release their demands and storage resource providers can accept storage requirements. We will also regularly publish updates of industry and product to the WeChat group, expanding the reach of the matrix storage and IPFS/Filecoin.

**4.Individual Reputation**
We have 11, 138 fans on the Wechat official accounts, and we are willing to post information about IPFS/Filecoin on our account.
Related Link：https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MjM5MTYzMDQ4NA==&scene=124#wechat_redirect 
![image](https://user-images.githubusercontent.com/82867405/121025562-ddeb1800-c7d7-11eb-9565-b735a9658721.png)
Awards:
2019
October：
Council member of China Chamber of International Commerce 
December:
Anmai cloud has become the first member of the "Hainan on Chain" Ecological Alliance 
2020
Augest
2020FAT“Top 100 in Blockchain Fintech”
September:
Anmai Cloud was selected by 36Kr as "Top 20 of New Infrastructure Start-up Enterprises with the Most Growth" in the "New Infrastructure Start-up List"

**5.Concreteness of Allocation Plan**

***Client Due Diligence**
How will you vet your Client to ensure they are spending that DataCap responsibly?
In the application process, We will confirm with the client whether there are cooperative miners. If there are, we will ask them to clarify the location of the miners,  miners' ID, the proportion of distribution and the reason for selecting the miners;
If not, we will actively guide them on how to find miners (e.g. Slack, Matrix Storage, Miner reputation system, etc.);
After allocation, we will require the customer to timely publish the trasaction information, including the location of the miners,  miners' ID, the proportion of distribution, etc.
We will follow up every week. If no abnormality is found, we will gradually expand the allocation;
If there is any abnormality, we will remind you in time. If the client does not cooperate, we will terminate the subsequent allocation and confirm with the official whether the previous allocation can be recovered from the technical level.
What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
We will continue to clarify and track customer allocation during the application review stage, allocation, and after allocation. See Q1 strategy for details.

***Bookkeeping Plan**
We will record in the form of table (https://docs.google.com/spreadsheets/d/1o0QzgKRB7sdQFKWkViTpkLjlkuoyxFq0lGg_7EjotOE/edit?usp=sharing), including Issue Number; Applicants; Current State; DataCap Requirements; Application Date; Website/Social Media; Nodes and Proportions; Filecoin Address; GitHub Account; Result; Result Time; DataCap Allocation; Remarks.
At the same time, We will store deal reputation information and basic client information in a distributed and irreversible manner, including but not limited to datacap allocation decisions;
The user handle the registration, login, edit the basic information, submits the datacap request and other actions through Matrix Storage. All information are recorded by the matching system.
![image (1)](https://user-images.githubusercontent.com/82867405/121025620-ee02f780-c7d7-11eb-8fa7-f40cd23ebd6d.png)

- All allocations will be updated and published on the GitHub issue to follow up on DataCap allocations and related informations of allocation.
- All allocation information is recorded on GitHub, table, and Matrix Storage. The information is open and transparent. If there is any abnormality, we will update it on the GitHub issue simultaneously.

**Comment by dkkapur** [comment]
@MatrixStorage thanks for sharing all this info. Here are some responses/comments:
- Time Commitment: left this at a 0 still, since we don't have documentation of Matrix Storage specifically as an organization having directly contributed to the ecosystem as its own entity. However - this was also partially because the scoring for this section is just a Max() operator on this row and the Stake Exposure
- Stake Exposure: assuming you can confirm that you own the private keys to this miner (please call this out immediately if you do not), this has been bumped up to a 3
- Reputation: largely stayed the same, since Matrix Storage as its own entity is newly formed, and only 1 account was shown with > 500 followers
- Client Due Diligence, Bookkeeping Plan: both increased to 5

The final scores for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 2.1

Here is the link to the updated rubric:
https://docs.google.com/spreadsheets/d/13g4jTJDJz1DYKMGu-W2wG_w5HgjR9TT4L8VDlNgmgC0/edit?usp=sharing

**Comment by MatrixStorageTech** [comment]
Matrix Storage have provided substantially adopted services / products, such as online Storage, offline Storage, OpenAPI and EasyNFT middleware.
Matrix Storage Platform is provided for storage resource providers, notaries and clients to store data, transact, and DataCap apply.
EASYNFT is a platform for connecting IPFS dirtributed storage network. NFT developers can easily access the IPFS network through the middleware. Giving a new use experience for NFT storage users. Users can permanently store data in a easy and safe way through simple code interaction.
But we only got 1 point on the Organization Reputation.
Please review this item.
Thanks.

**Comment by MatrixStorageTech** [comment]
Matrix Storage have provided substantially adopted services / products, such as online Storage, offline Storage, OpenAPI and EasyNFT middleware.
Matrix Storage Platform is provided for storage resource providers, notaries and clients to store data, transact, and DataCap apply.
EASYNFT is a platform for connecting IPFS dirtributed storage network. NFT developers can easily access the IPFS network through the middleware. Giving a new use experience for NFT storage users. Users can permanently store data in a easy and safe way through simple code interaction.
But we only got 1 point on the Organization Reputation.
Please review this item.
Thanks.
