### ISSUE TITLE
Notary Application：Arsyun

### ISSUE THREAD

**Issue by AbelLaker** [filecoin-project/notary-governance#145]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name:arsyun
- Affiliated Organization: arsyun
- Website / Social Media: https://www.arsyun.com/
- On-chain Address to be Notarized:f3shqqcmeiypdmpxskvog4hktpwi3mnavk2mzzyvrp4un4ryg2ytqtvyxgahi4xhhvfbmjozaddjennakszvvq
- Region of Operation:Greater China
- Use case(s) to be supported:  [General,Web 3.0 / Decentralized Applications, Web 2.0 Applications, User Content, Scientific Data, Media & Entertainment, Other]
- DataCap Requested:100T

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
1. In 2017, Arsyun launched the "IPFS Plan", dedicated to the practical application of IPFS technology in the commercial field.
2. In 2018 and 2019, Arsyun became the only Chinese company to be invited to participate in the IPFS Global Developers Conference for two consecutive sessions.
3. In the first quarter of 2020, Arsyun became the first node on the Filecoin testnet to reach 1PB of computing power, and it was also the only 2PB-level node in the first phase of the testnet.
4. Arsyun actively participate in various filecoin projects and provide filecoin technical services to many companies
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
f02520 340,887.5803 
f02303 407,621.5656 
etc.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Arsyun was working as an IPFS/Filecoin ecosystem advocate and builder:
- Speaker of IPFS/Filecoin/Web3 conferences
- Contributor of Filecoin protocol and code development via issues/PRs commitments
- I have been invited to attend the IPFS camp in berlin and Barcelona. 

Recently Filecoin Community activities
- joined the IPFS Camp on June 27-30, 2019, in Barcelona: https://youtu.be/kc_dxO-V8YM
- ranked at the top of the SR1 leaderboard, https://spacerace.filecoin.io/` 
- How We Won Space Race, Oct. 21th 2020, https://www.youtube.com/watch?v=1QVa48Eela8
- Filecoin Protocol Implementation: What's next?, Oct. 21th 2020, https://www.youtube.com/watch?v=JmvQ0F1qtYQ
- Space Race Miner Show， Spe. 4th 2020, https://www.youtube.com/watch?v=pHi85ZNs3AY
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
Security is the first priority and the most important factor of a chain.

Some of the issues submitted related to security: 
- https://github.com/filecoin-project/lotus/pull/467
- https://github.com/filecoin-project/lotus/pull/4985
- https://github.com/filecoin-project/lotus/pull/2186
- https://github.com/filecoin-project/lotus/pull/2007
- https://github.com/filecoin-project/lotus/pull/1847
- https://github.com/filecoin-project/lotus/pull/1836
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
- Nature of Arsyun: Aming to be the world's leading blockchain distributed cloud storage service provider.
- country of registration: China
- size of the organization: 60+
- time since inception: 2017
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
ARS Location: Shenzhen, China
ARS Website: https://www.arsyun.com
ARS Twitter: https://twitter.com/pServer11 
WeChat Oifficial Account: 先河系统 
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.8btc.com/article/618502
https://www.8btc.com/article/638910
https://www.chainnews.com/articles/253822877827.htm
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Multiple use cases will be supported. The percentage will be determined by my knowledge and usage expectation, 
which may vary depending on the variable circumstances of each scenario and different regions. 
- 30% - user content (personal user storage)
- 30% - scientific datasets (AI training, geological data, autonomous driving) 
- 40% - media & entertainment (video & music)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
First of all, we should allocate the DataCap to the right Clients. and make sure they use the DataCap in a right way.
For qualified Clients, Their historical reputation will be a important fator which has much weights to get the DataCap.
For new Clients, I will consider their data qulity and growability in future. I will do my best to help them make success.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Currently, There are less internal process, mainly for key decisions, such as high requested DataCap(over 20%) or over-allocating DataCap to a single entity.
Most process will be in public and under the supervise of Filecoin Community.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hardware wallet will be used to store the keys associated with the DataCap allocation address. 

```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. ` 
Below is the proposed procedure of Due Diligence. We need 3 types of information for review by myself or our compliance team depending on the volume of clients required Due Diligence:
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information; 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name;
 - date of birth; 
 - street address (P.O. box number is not acceptable); 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
1. Please introduce yourself?  (Github, Twitter, Linkedin handle) 
2. What is your use case? 
3. How much DataCap would you like to request? 
4. Your filecoin address 
5. In which region do you intend to use the DataCap? 
6. How many miners do you plan on allocating a DataCap?
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
- Single clients are encouraged to allocate the DataCap to more than 5 different miners.
- Periodical inspection and audit of DataCap usage.

```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Yes, all allocation decisions will be guided by the rubric publicly on Github.
Since all interactions are intended to occur publically, most of the allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly in the Github repo first. 
If convincing justifications can’t be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions. 
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be conducted in the Github repository.

```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None.
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None.
```

**Comment by dkkapur** [comment]
Hi @AbelLaker  - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1aqgAd1QSPcuI6smssCnP4z_7V84rCRU0Nee0_iPcZYU/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.7.

**Comment by AbelLaker** [comment]
@dkkapur The supplementary information is as follows：

**1. Great to see lots of contributions to lotus, but this specific to security vulnerabilities reported for Filecoin**
    We are improving the wallet security proposal before, and we have confirmed the submission before.

**2. Twitter account is suspended**
   This is fine：https://twitter.com/pServer11  

**3. Can you describe in further detail the different factors you would like to consider and how you'd weigh them in your decision making process?**
   3.1 Prequalification
   Preliminary KYC review of the qualifications of users who need storage, and preliminary screening of users with real needs. The first stage is the registered user stage. The required review materials are given different weights based on the different materials submitted by different users, and the authenticity and magnitude of the corresponding materials.
   3.2 Requirements and content pre-review
   After the pre-qualification is passed, users are required to submit corresponding requirements and related content materials. The requirements and content storage must meet the laws and regulations of the corresponding regions. According to needs and content, users are given corresponding weights.
   3.3 Apply
   We will give users different initial allocation quotas for Datacap based on the above information, and users will submit formal applications according to the corresponding quotas.
   3.4 Due diligence
   Perform all necessary checks on companies, groups, and legality.
   3.5 Datacap size and score
   The size of Datacap is based on the completeness and legitimacy of the user's information; the practicality and innovation of the requirements; the richness and difference of the content; it also includes the user's historical goodwill value and the honesty in the use process. .
We give and adjust different allocation quotas for users based on ratings.
   3.6 Sampling inspection
   We will track the true usage of users, and sample the content of users’ data; if there is any violation of the rules, we will punish them and announce it to all notaries.
   3.7 Public display
  We will show all the approved applications publicly and accept the supervision of the whole network.
  
 **4. Contingent on further details on "Periodical inspection and audit of DataCap usage" and how this will be carried out?**
  4.1 First, after the DataCap distribution, we need to disclose the user's Filecoin address so that we can monitor it closely. In addition, we will pay close attention to all storage orders (especially verified transactions) of such users and related storage providers.
  4.2 We will establish a user reputation scoring mechanism to score customers. Among them, the more diversified the DataCap granted by the customer, the higher the score the customer will get. Customers who deploy less than 30% of DataCap to any storage provider can get extra points, while deploying ≥70% of DataCap to any storage miner within a period of time will be deducted points.
  4.3 Penalties-If the user's score on storage provider diversification is too low, a warning will be issued and all other notaries will be notified of the above-mentioned "excessive centralized distribution". Further penalties may be taken, such as canceling the remaining DataCap, in response to any users who continue to ignore our warnings.
  4.4 Audit-External and internal audits will be conducted throughout the data deployment process. Encourage community members to participate as external auditors to expose any user's excessive attention to Datacap allocation.
  
 **5 Will the allocation decisions be made and tracked in https://github.com/filecoin-project/filecoin-plus-client-onboarding or in a separate GitHub repo?** 
We only use https://github.com/filecoin-project/filecoin-plus-client-onboarding

**Comment by dkkapur** [comment]
@AbelLaker - thanks for sharing this additional info!
- The security contributions are measured specifically for those that are submitted through the Filecoin Security Program (i.e., Bug Bounty)
- Twitter account linked does not have > 500 Followers, score for this left at 0
- Allocation Plan: score increased from 1 to a 3 based on shared info
- Thanks for additional details/confirmation on Due Diligence and Bookkeeping!

Based on this, the final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 1.7

Link to rubric: 
https://docs.google.com/spreadsheets/d/1aqgAd1QSPcuI6smssCnP4z_7V84rCRU0Nee0_iPcZYU/edit?usp=sharing

**Comment by AbelLaker** [comment]
@dkkapur Hi,Our fan of WeChat official account is >500, as shown in the figure.
![Uploading 1.png…]()

**Comment by AbelLaker** [comment]
@dkkapur Hi,Our fan of WeChat official account is >500, as shown in the figure.
![Uploading 1.png…]()

**Comment by AbelLaker** [comment]
![1](https://user-images.githubusercontent.com/40750116/122322885-c854bb80-cf58-11eb-8948-70e80daf8b41.png)
