### ISSUE TITLE
Notary Application-Extend Labs

### ISSUE THREAD

**Issue by longmans** [filecoin-project/notary-governance#148]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
```
Name:Extend Labs
Affiliated Organization: Guangzhou CloudBridge Technology Co., Ltd.
Website / Social Media:
Website of Extend Labs Product: http://www.afilpool.finance/
Website of Guangzhou CloudBridge Technology Co., Ltd.: http://cloudbridge.pro/
On-chain Address to be Notarized: f1noqy7jwlk46xujxbq2pxsdizqsaq4vh43fb37na
Region of Operation: Greater China
Use case(s) to be supported: General, prefer cases on IPFS ecological applications, 
not limited to Infrastructure or Dapp(DEFI), and big data service.
DataCap Requested: 500TB
```

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Nature of Extend Labs:

Extend Labs focuses on web3.0 infrastructure, with special attention to valid data verification, 
and puts forward a PoQ proposal(As described below). Hope to provide efficient and stable distributed 
storage services for enterprises and individuals in the future.

FIP Proposal: A proposal of Proof-of-Quality
https://github.com/filecoin-project/FIPs/issues/101


Major Projects:

http://www.afilpool.finance/en

http://bzzscan.com/

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Extend Labs is a laboratory whose products include AI algorithm research, decentralized DEFI, etc. 
It does not have a large number of pledged coins, and there is no capital risk. 

```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
None
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
None 
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
http://www.afilpool.finance/en

http://bzzscan.com/

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
None
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.jinse.com/lives/249653.html

https://news.huoxing24.com/flash/20210520223638295936.html
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Extend Labs is committed to the infrastructure construction of web3.0. 
Team members come from NetEase and Alibaba. Many PhDs from higher education institutions participate. 
We bring AI algorithms and privacy calculations to Filecoin's real data verification field and other ecological work.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
We calculated the level of applicants through AI algorithms for the user reputation. At the beginning we will 
label and train effective models, and then make predictions based on the models.

```
![image](https://user-images.githubusercontent.com/932025/119269629-3a243880-bc2b-11eb-9f86-3896135497cc.png)

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Not clear yet
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The private keys will be stored in the hard wallet.

```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
We will check the validity of user uploads and adjust the user’s credibility based on the results.

```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
Directly use the customer's sample data for analysis.

```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Use spot check mechanism
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
We will retain all of our allocation decisions, which should be subject to fair and open oversight.

We take every request for auditing/reviewing very seriously and reject unreasonable complaints. 
We will submit the review materials within 1 working days after the request is initiated

```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be public on-chain
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
No
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
No
```

**Comment by dkkapur** [comment]
Hi @longmans  - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/19RGMSACyscBUD0TyjGPZQ7exQnn8aqhsPpDYKT72ass/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.0.

**Comment by dkkapur** [comment]
@longmans, the final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 1
- Unrounded score: 1.0

Link to rubric: 
https://docs.google.com/spreadsheets/d/19RGMSACyscBUD0TyjGPZQ7exQnn8aqhsPpDYKT72ass/edit?usp=sharing
