### ISSUE TITLE
Notary Application-Binghe Distributed Storage Lab

### ISSUE THREAD

**Issue by MRJAVAZHAO** [filecoin-project/notary-governance#149]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Binghe Distributed Storage Lab
- Affiliated Organization: None
- Website / Social Media: @ Binghe Lab on Slack
- On-chain Address to be Notarized: f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
- Region of Operation: Greater China
- Use case(s) to be supported: General
- DataCap Requested: 1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Binghe Distributed Storage Lab (hereinafter referred to as Binghe Lab) is a world-leading decentralized IPFS distributed storage technology research institution, dedicated to outputting professional knowledge, the latest technology public evaluation, cutting-edge distributed storage information and the best distributed storage solutions to the industry.

Since 2014, the core members of Binghe Lab team have begun to contact the IPFS/Filecoin project. In June 2020, the R&D members began to study the underlying technology. In July 2020, Binghe Distributed Storage Lab was formally established.

The research results of Binghe Lab are widely used in products such as Athena distributed storage systems, customized customer service solutions, Athena explorer, and FIL calculators. With the technology accumulation of Binghe Lab, Athena Pool continues to develop at a high speed, ranking first in computing power all over the world.

With the technology support of Binghe Lab, Athena Pool also actively participated in the official competition, including Testnet Phase 2, Calibration and SpaceRace, and achieved outstanding results.

- https://baijiahao.baidu.com/s?id=1672344050430213968&wfr=spider&for=pc

- https://www.jinse.com/news/blockchain/759928.html

- https://xw.qq.com/cmsid/20200804A0O5TW00

- https://baijiahao.baidu.com/s?id=1677951450775029762&wfr=spider&for=pc

- https://www.jinse.com/news/blockchain/824672.html

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
As a neutral institution, Binghe Lab does not directly or indirectly participate in mining, so we do not hold tokens. But we plan to launch a ten-million-dollars-level Filecoin eco-fund project in June this year. We might apply for a wallet and obtain tokens after that.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Since 2014, the core members of Binghe Lab team have begun to contact the IPFS/Filecoin project. In June 2020, the R&D members began to study the underlying technology. In July 2020, Binghe Distributed Storage Lab was formally established.

As a promoter of IPFS/Filecoin, Binghe Lab has actively carried out knowledge popularization, organized technology evaluations, outputted various types of analysis reports such as the Fil Index to the industry and held industry events. 

In  March, the 2021 global computing power summit——"Peak Computing Power" , hosted by China Software Industry Association and co-organized Binghe Lab, has attracted nearly 1,000 people to participate in and more than 300,000 people watched the online broadcast.

- http://live.cykjvip.com/live/mk/aggspread/200180684/d0d5f686-87fb-11eb-be34-18ded7a37b78

- https://www.jinse.com/news/blockchain/1018910.html

- https://mp.weixin.qq.com/mp/appmsgalbum__biz=Mzg2NzUzOTMyNg==&action=getalbum&album_id=1649509099643961347#wechat_redirect

- https://mp.weixin.qq.com/s/oOvyeA3dtGZu32nJKYE0YA

- https://mp.weixin.qq.com/mp/homepage__biz=Mzg2NzUzOTMyNg==&hid=18&sn=7f9aef8e821c9e0130acd86b15cd0d99&scene=18

- https://mp.weixin.qq.com/s/-4eVGXr7B4uJupB9F5sjig

At the same time, Binghe Lab is also actively carrying out industry cooperation. Up to now, the Lab has reached cooperation with more than 50 enterprises, including Inventec, Sugon, Super Cloud, Qiniu Cloud, SandStone, Lexun. The scope of cooperation spans over 10 different industries, and  the market value of partners exceeds tens of billions of dollars.

- https://m.8btc.com/article/631797

- https://baijiahao.baidu.com/s?id=1692746699228413907&wfr=spider&for=pc

It is worth mentioning that Binghe Lab will cooperate with Dell to jointly open block chain public courses in domestic universities. The courses are aimed at undergraduates and postgraduates majoring in computer science from well-known domestic universities such as Tsinghua University, Fudan University, and Sichuan University, etc.. The courses will mainly include basic knowledge of blockchain and engineering practice. In this process, the three parties will also work together to study web3.0 related applications, and jointly output research results in the form of projects. The program is expected to start at the end of June.

In addition to jointly offering blockchain courses, Binghe Lab will also jointly develop cloud storage products (similar to backup products) with Dell. The cooperation will be conducted in the form of Dell providing equipment and Binghe providing technology guidance.

In addition, Binghe Lab plans to launch a ten-million-dollars-level Filecoin eco-fund project in June this year to invest in the incubation of Filecoin ecological applications.

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
In April 2021, the Secretary-General of Binghe Lab (@Scarlettzhang on Slack) discussed the solutions with the PL through Slack, emails and online meetings regarding the excessive cost of online order delivery. The Slack Channel is fil-rrmine, and Deep Kapur, jennijuju, Keren etc. are involved in this discussion.

On April 19, 2021, the Filecoin Computing Power Rescue Plan initiated by the Binghe Lab was officially launched. This is the  first public welfare technology consulting service for miners across the network. By consolidating the power of the distributed storage industry chain, it provides free computing power disaster preparedness experience sharing, rescue consulting, security risk control plan sharing, and remote disaster recovery. Such services fully guarantee the security of customer data and digital assets on the Filecoin Mainnet.

- https://news.huoxing24.com/20210419174148082406.html

```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Binghe Lab is a world-leading decentralized IPFS distributed storage technology research institution and established on July 18, 2020. The members of Binghe Lab includes:
1. Academic Institutions: Shanghai Branch of Institution of Computing Technology, University of Electronic Science and Technology of China, Tsinghua PBCSF Blockchain Club, etc.
2. Hardware Manufacturers: Dell China, H3C, etc.
3. Distributed Storage Service Providers: StorSwift, FunGeek, TYun, Storlead, etc.
4. IDC Service Providers: China Netlan, Shangzhonglian, etc.
5. Ecological Application Companies: RRMine, Jack&Me, IQiYi Games, Xunyou, Weiling Technology, etc.
6. Industry Investment Funds: QF Capital, Fenghou Capital, EMP Capital Limited etc.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
1. Social Media
Slack: Binghe Lab
WeChat Official Accounts: 冰河分布式存储实验室
Weibo: 冰河分布式存储实验室
Bilibili: 冰河分布式存储实验室

2. Related Personnel
Secretary-General: Zhang Xiaohang（@Scarlettzhang on Slack&GitHub）
Technology Consultant: Leng Bo (@coder-lb on Slack&GitHub））
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
- ​https://www.chinaz.com/2020/0803/1166086.shtml

- https://www.jinse.com/blockchain/1049551.html

- https://www.jinse.com/news/blockchain/785622.html

- https://www.jinse.com/news/blockchain/768399.html

- https://www.jinse.com/news/blockchain/759928.html
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
In order to better serve community participants, Binghe Lab will not impose strict restrictions on use cases, but as a technology research institution, we prefer to support developer tools, Web 3.0, Web3 DApp, Web 2.0 applications and other technology-related applications.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
What we understand the primary responsibility of a notary is to verify the validity of the client, not of data. Therefore, we will focus on clients' authenticity, influence, allocation decision, etc.

Since there is currently no good way for us to verify privacy/encrypted data, we will pay great attention to the publicity of data.

As a non-profit research institution, in order to serve more clients and maximize the scope of industry coverage, we do not limit the nature of clients.

For more effective verification, we will give priority to accepting applications from clients in Greater China or clients who are not in Greater China but choose Chinese miners.

In order to prevent fraud, our distribution strategy will be "level ladder+ stage ladder" .
Level ladder: The results were divided into 5 levels. The higher the level, the more DataCap 
will be granted.
Stage ladder: We will initially grant a small amount of DataCap. If no abnormal situation 
happens, the allocation amount will be gradually increased.

As a technology research institution, we also attach great importance to the implementation of application ecology. Therefore, we will give additional 5% to 40% of DataCap to applicants who have developed IPFS/Filecoin-related applications or have contributions to IPFS/Filecoin industry.

- https://docs.google.com/spreadsheets/d/1ipVpNMahvpn3NMcwmfO6eVPmHVZ-QejpEEtPVV5XVi0/edit?usp=sharing

```

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Our goal is to reach as many people as possible and help them participate in IPFS/Filecoin. So we will not be too strict when vetting which will be on the basis of ensuring the fairness and effectiveness of verification.

We will restrict the first allocation at 10TiB and the single allocation at 20TiB. Besides, we will set an upper limit of 50TiB for a single clients.

In addition, we will daily monitor the application submission and reply them within 2 working days. We will strictly score according to our rules. The vetting process, allocation decisions and other related application information will be 100% open to the public.

Vetting process:
1. Raise general questions;
2. Review application information, check documents, and ask supplementary questions for unclear answers;
3. Ask for more information and/or documents if necessary;
4. Conduct client due diligence;
5. Make score according to our marking table and put the final score on the issue. If clients have any question about the score, we will verify again till no objections;
6. Confirm the Filecoin address with clients;
7. Perform allocation;
8. Record the allocation decision and publish the distribution on Slack every two weeks (Maybe synchronized with the Notary Goverance Call);
9. Track the  allocation of clients and request them to disclose transaction information in a timely manner.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The private keys will be stored in the hard wallet and will be accessible only by the principal.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
When accepting the application, we will confirm whether they have potential miners. If so, we will ask them to clarify the miner number, allocation proportion and the source of miners; if not, we will recommend channels such as Slack to guide them to find better miners.

After approval, we will require clients to display transaction information, including miner number, allocation proportion and the source of miners, etc., and then follow up weekly on this basis.

 If no abnormality is found, we will gradually expand the allocation amount in the follow-up. If there is any abnormality happens, we will send remind messeage for the first time and put the client on a blacklist for the second time（ application will not be accepted within one year）. Meanwhile, the matter will be synchronized with the PL.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
In order to get more clients involved in the Filecoin network, we're not going to ask too many complicated questions, but focus on questions about the validity of clients. 

Question List:
1. Please provide organization name, business scale, social media accounts&follwers, and business license (could be sent by email);  if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&follwers, and ID card (can be sent by email);
2.When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?
3. Please describe your business data volume, source and later planning? Please describe the
type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.
4. In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.
5. Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.

We may add additional questions and requests based on responses and client due diligence.
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
During the application phase, it is required to clarify the miner ID and other information. 

After the application, it is required to publish transaction information, including miner ID, allocation proportion and the source of miners, etc. 
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Yes, all allocation decisions will be recorded and any necessary information can be provided at any time without violation of community norms and with the consent of the client.

In case of uncertainty, we will communicate and confirm with the PL in time.

Normally, the record information will includes:
1.Application informations that can be disclosed, such as applicant name, applicant profile, allocation plan, transaction information, etc.
2.The scoring table related to the clients
3.Allocation decision, including Messages, addresses, and approved amount.
4.Other necessary information that does not offend the community
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All decisions will be made public.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No, it is the first time for us to apply for becoming a notary. As a technology research institution, we hope to have a new identity to better serve the community and industry.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None
```

**Comment by dkkapur** [comment]
Hi @waynewyang - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1V-UnEN__fWSG3PlbBJYAt9YQKuKPDIcscCJ8NxQWmTg/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.2.

**Comment by MRJAVAZHAO** [comment]
Hi,  @dkkapur , we want to add some information. Please check below.

> Time Commitment

Scarlett Zhang, Secretary-General of Binghe Lab, is an entrepreneur and investor in the blockchain industry. She began to pay close attention to the progress of the IPFS project in 2017 and co-founded the Binghe Lab in July 2020. At the same time, relying on her own influence, Scarlett has promoted more than 50 upstream and downstream enterprises in the industry to reach IPFS special cooperation and jointly released a 5 billion IPFS infrastructure production plan in November 2020 with a number of enterprises. In March 2021, she signed an IPFSEiB-level storage procurement cooperation with Sugon.

> Stake Exposure

As mentioned before, we will launch a ten-million-dollars-level Filecoin ecofund project in June. Now we have started preparations that we have cooperated with Athena Pool in the form of a technology share. Miner ID is f0142720 with about 1.3 million tokens.

> External Reputation

Since establishment in 2020, Binghe Lab has provided technology support to Athena pool to help it become the world’s number one in computing power. At the same time, we continue to output knowledge/science,/information/technology evaluation, organize convenes industry summits and establish industry foundations, which has a profound impact to make more people participate in Filecoin. Binghe Lab has become an important and highly influential organization in the Web3.0 era.

At present, Binghe Lab has reached cooperation with more than 50 companies. The scope of cooperation spans over 10 different industries and the market value of partners exceeds tens of billions of dollars. In addition, the co-organized "Peak Computing Power" global computing power summit has attracted nearly 1,000 people to participate in and more than 300,000 people watched the online broadcast.

Binghe Lab has established omni-channel media accounts, with a total number of follwers exceeding 14,000.
1.Social Media
Slack: Binghe Lab
WeChat Official Accounts: 冰河分布式存储实验室(more than 7,000 followers)
Weibo: 冰河分布式存储实验室
Bilibili: 冰河分布式存储实验室
Mars Finance：冰河分布式存储实验室(more than 4,100 followers)
Zhihu：冰河分布式存储实验室
Baijiahao：冰河分布式存储实验室
Chain Node：冰河分布式存储实验室
Babbitt：冰河分布式存储实验室
2.Wechat Group
We have created 8 WeChat groups to discuss IPFS/Filecoin industry issues. Currently there are about 1,700 community members

Regarding individuals:
1.Secretary-General: Zhang Xiaohang（@Scarlettzhang on Slack&GitHub）
Scarlett Zhang is an entrepreneur and investor in the blockchain industry. She began to pay close attention to the progress of the IPFS project in 2017 and co-founded the Binghe Lab in July 2020. At the same time, relying on her own influence, Scarlett has promoted more than 50 upstream and downstream enterprises in the industry to reach IPFS special cooperation and jointly released a 5 billion IPFS infrastructure production plan in November 2020 with a number of enterprises. In March 2021, she signed an IPFSEiB-level storage procurement cooperation with Sugon.

2.Technology Consultant: Leng Bo (@coder-lb on Slack&GitHub））
As a technology consultant, Leng Bo has providedconsulting services to Binghe Lab for more than half a years.

3.There are several industry consultants of Binghe who have participated in the exploration of the blockchain/cryptocurrency field for a long time, forming a very high personal influence through continuous vocalization on Weibo.
A. @Mikko朱尘（1,540,000 followers in total）
B. @熊越XiongYue（160,000 followers in total）
C. @不胖的胖妮（110,000 followers in total）
D. @万卉Dovey（more than 55,000 follwers）

> Allocation Strategy

Google Docs has been made public and you can check after logging in to your Google account.
https://docs.google.com/spreadsheets/d/1ipVpNMahvpn3NMcwmfO6eVPmHVZ-QejpEEtPVV5XVi0/edit?usp=sharing

> Bookkeeping Plan

We'd like to add another explanation of our bookkeeping plan.
1. Content
We will record the following information (the following information will be fully disclosed on GitHub):
A. Applicantion information
Application date, request amount, applicant's name, associated organization name, business scale, establishment time/date of birth, business license/ID card, social media number and number of associated follwerss, volume of business data, volume of stored data, data type, data format, data source, publicity of data
B. Allocation decision
scored rubric, allocation amount, allocation date, allocation address
C. Allocation record
miner IDs, location, storage proportion
Please check detailed information here:
https://docs.google.com/spreadsheets/d/1prGqLjeQn4zznNDpsouSsdhOcoq4A_LMawxYP84K8o0/edit?usp=sharing
 
2. Recording method
online documents (Google documents) + offline documents (office), offline documents will be uploaded to IPFS every half year.
 
3. Recording process
We will established a notary team. The team members include reviewer, assigner, calibration personnel, and external communication personnel, a total of 4 people.
A. The reviewer will record the application information: after completing the review process, record the key information of the applicant
B. Assigner(person in charge): perform assignment and record
C. Calibration staff: follow up the allocation of clients, record allocation information, and calibrate the rationality of allocation
D. External communication personnel: if there is an audit requirement, the person will be responsible for carefully cooperating with the audit; if part of the information is uncertain, the person will be responsible for communicating with officials and clients
The above information will be recorded in the form of an online document. After completion, the offline document will be exported and saved as an archive.
 
4. Recording principles
A. All public information shall not violate community norms
B. Priority to obtain clients' consent
C. If we are not sure whether it can be disclosed or the client does not agree to disclose non-private information, we will communicate with the official
D. All information will be stored for a long time and stored on the IPFS network.

**Comment by MRJAVAZHAO** [comment]
Hi, @dkkapur 
We have updated few contents and pictures in the last comment.
Any questions, please fell free to let us know.

**Comment by MRJAVAZHAO** [comment]
Dear @dkkapur 

In March this year, Scarlett (Secretary-General of Binghe Lab) won the _Outstanding Ecological Contribution Award_ issued by ProtoSchool. We added this information and pic in the above comment.

For your convenience, we replaced all pictures with links. Kindly check the above comment.

**Comment by dkkapur** [comment]
@MRJAVAZHAO - thank you for providing all these details! Based on this, several adjustments have been made to the rubric: 
- Stake Exposure: 0 -> 3
- Organizational reputation: 1; still at a 1 because it seems like the presence is still very much focused on Filecoin and the Filecoin community, as opposed to extending beyond to other protocols/Web3 Projects
- Individual reputation: 0 -> 2, thanks for the screenshots!
- Allocation Strategy: 3 -> 5
- Bookkeeping Plan: 2 -> 5

The final scores for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 2.1

Here is the link to the updated rubric: 
https://docs.google.com/spreadsheets/d/1V-UnEN__fWSG3PlbBJYAt9YQKuKPDIcscCJ8NxQWmTg/edit?usp=sharing

**Comment by MRJAVAZHAO** [comment]
@dkkapur -Thanks! There are some points that need your re-scoring and confirmation.

>  Organization Reputation

1.In addition to being active in the Filecoin community, Binghe Lab also actively promotes blockchain, Swarm, NFT, DeFi, and other fields of knowledge through WeChat official accounts to expand industry participants' awareness of the entire digital currency field.
https://mp.weixin.qq.com/s/Wf2zxhnx2UbSNgau_189RQ
https://mp.weixin.qq.com/s/IZjOI9-1rI5qbnwi9WLj2g
https://mp.weixin.qq.com/s/9T3m_rgLMXBdf-Zw1pd7_w
https://mp.weixin.qq.com/s/PKjk7GIa8g8PZHy2VOrMuQ
https://mp.weixin.qq.com/s/XnaaAEsUvfb1aMyZBFL3pQ

2.On 2021.4.19, Binghe Lab launched the Filecoin Computing Power Rescue Plan. Although the plan is based on Filecoin rescue, it is aimed at miners of the entire network.
https://news.huoxing24.com/20210419174148082406.html  

3.Athena Explorer, developed by Binghe Lab, provides not only network-wide data query for miners, but also provides industry trend data, Fil calculator tools, node monitoring and other industry-exclusive functional modules, among which, Athena Explorer itself and  Fil calculator tools have been recognized by community-china and also the industry.
https://www.atpool.com/en-US/
https://github.com/filecoin-project/community-china

> Individual Reputation

Our industry consultants’ personal social media accounts have exceeded 100,000. We think this score should be L3. Please confirm again.

**Comment by dkkapur** [comment]
@MRJAVAZHAO - thanks for your additional comments. 

- Organizational reputation: promoting and educating users is great, but this category currently caters to organizations that have built and released projects of substantial adoption in other ecosystems. As such, these are all examples of excellence in the Filecoin ecosystem and/or building a great platform for people to educate themselves, but it does not seem like the current definition of `Reputable entities in Filecoin-adjacent communities with substantially adopted services / products` is met
- Individual reputation: `There are several industry consultants of Binghe` per your previous response, these are accounts of associates / consultants correct? Are they directly involved in Binghe's efforts as a Notary in any way?

**Comment by MRJAVAZHAO** [comment]
@dkkapur Thank for your reply.

> Individual reputation

Yes,  these are Weibo(similar to twitter) accounts of our industry consultants. 
Actually, they often discuss industry issues with Scarlette（Secretary-General of Binghe Lab). At the same time, they express their views on IPFS/Filecoin through their own Weibo account to increase the influence of IPFS/Filecoin in China.

**Comment by MRJAVAZHAO** [comment]
In addition, if Binghe Lab becomes a notary, they will also synchronize this information on their Weibo account and will also continue to promote IPFS/Filecoin in the future.

**Comment by dkkapur** [comment]
@MRJAVAZHAO thanks for confirming that these account are indeed directly operated by your team/consultants and can post about Filecoin/Filecoin Plus in the future. Based on this, the rubric has been adjusted and your score has increased to 2.4.

**Comment by dkkapur** [comment]
@MRJAVAZHAO - based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of 100 TiB. In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm that the region of operation for client applications you will focus on is [Greater China Region]

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

> * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

> * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

> * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**Comment by MRJAVAZHAO** [comment]
@dkkapur It's really an excited news! Thanks a lot!

1.We confirm that we will focus on  [Greater China Region] 

2.We confirme all  items below:

> - Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

Confirmed.

> - Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

Confirmed.

> - Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

Confirmed.

> - No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

Confirmed.

> - Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

Confirmed.

> - Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

Confirmed.

3.As mentioned before, we cooperated with Athena Pool in the form of a technology share. Our Miner ID is f0142720. 

4. f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### Datacap Allocated
> 100TiB

**Comment by dkkapur** [comment]
@MRJAVAZHAO - can you ping me (U0159AVN857) on Slack so I can get the right Slack ID connected in the Fil+ channels? Thanks!

**Comment by dkkapur** [comment]
This grant seems to have gone through correctly and should not be in Error status. Fixing this now!

**Comment by MRJAVAZHAO** [comment]
@dkkapur We updated our DataCap allocation strategy in the following points.

- Scoring Standards for DataCap Allocation

https://docs.google.com/spreadsheets/d/12ItWjuddDPZpFBE84dzNJxBM24AhZHDJcWsu9RY3xG4/edit#gid=0

- DataCap Allocation Records

https://docs.google.com/spreadsheets/d/1G5XO5pyn97bFdB8cOXzp9s1bwXTqyj-CUy4mooP3ijo/edit?usp=sharing

- Question List

1. Please provide organization name, business scale, social media accounts&follwers, and business license (could be sent by email);  if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&follwers, and ID card (can be sent by email);
2. When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?
3. Is there any law risk? What percentage of questions are yours?
4. Please describe your organization, such as established time, the number of employees, users volumn, the number of social media followers.
5. How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.
6. In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.
7. Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.
