### ISSUE TITLE
Notary Application:XnMatrix

### ISSUE THREAD

**Issue by XnMatrixSV** [filecoin-project/notary-governance#150]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: XnMatrix
- Affiliated Organization: XnMatrix
- Website / Social Media:@XnMatrix SV on the Filecoin/Slack
- On-chain Address to be Notarized: f1nneomjjusexfkglvgdpphztfwbmago223jrtawa
- Region of Operation: North America
- Use case(s) to be supported: User Content, Scientific datasets, Media & Entertainment
- DataCap Requested:1 PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
As an organization, XnMatrix Group built quite an extensive relationship with the Filecoin community since 2019. We have sustained some contributions to the overall network. 
As a miner and researcher，we joined the testnet, space race, slingshot, mainnet. 
Here is some GitHub issue we discussed about:
https://github.com/filecoin-project/lotus/issues/3928
https://github.com/filecoin-project/lotus/issues/4861
https://github.com/filecoin-project/lotus/issues/1824
In addition, we are deeply involved in the mining of filecoin. Our miner IDs are f02614, f09652, f010424, f03362, f020928, f039992 and more,  with a total computing power of about 600 PiB.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
So far, we hold total tokens more than 1MM FIL, of which 742 FIL is currently available, 759193 FIL is locked as collateral, and 553035FIL is vesting.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Now XnMatrix is the world's leading IPFS supplier with the leading IPFS mine pool.
XnMatrix can provide customers with one-stop storage services, including storage resource management, storage resource trading, and storage token trading across different block chains.
At the same time, XnMatrix provides decentralized cloud computing services based on the Web 3.0 infrastructure backboned by blockchain technology.
We participated in the AMA online meeting actively.
At the same time, we successfully held the 2020 Distributed Storage Summit in Chengdu. 
We are honored to invite @Keren from the Protocol Lab to give a keynote speech. Please check with @Keren who will be able to substantiate our contributions. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
We participated in the early testing before reset and gave the official feedback.
Leng Bo @coder-lb joined our IPFS business union as technical consultant early. 
We found some serious/critical bugs, such as
https://github.com/filecoin-project/specs-actors/issues/448 : The mining power is permanently dropped but there are no expired faulty sectors
https://github.com/filecoin-project/lotus/issues/1824 : We need to add Deadline for SubmitWindowedPoStParams
https://github.com/filecoin-project/lotus/issues/2204 : Index out of range issue of lotus-storage-miner proving info
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Organization: XnMatrix Silicon Valley Office
Nature:  private company
Registration Country: California,US
Established: Jan, 2021
Size: over 500 employees
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Homepage: https://www.xnmatrixs.com
Twitter: https://twitter.com/superxnmatrix?lang=en
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
XnMatrix is the world’s leading decentralized cloud computing platform, offers fully featured decentralized cloud/network resource services and computing power products to individuals and enterprises, to complement and leapfrog the centralized cloud computing in terms of lower cost, data privacy and security and digital asset liquidity.
We also optimize distributed storage efficiency in terms of hardware, software, algorithms, operation and maintenance, applications, etc. 
We provide integrated storage products and industry solutions for enterprises and industries.
It mainly includes ultra-low-cost computing power covering IPFS, cryptocurrency, AI, edge computing and other fields, as well as services derived from computing power requirements, including cloud computing account management, cloud computing APP SaaS service, cloud computing e-commerce platform PaaS service, cloud computing trading service, etc.
https://finance.yahoo.com/news/2020-distributed-storage-summit-ended-124500305.html
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
- 60% - Media & entertainment (video & music & game)
- 30% - User content (personal user storage，such as file, photo)
- 10% - Scientific datasets (Health data, AI training, Meteorology data) 
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
Here is our allocation process.
```
![1621834931(1)](https://user-images.githubusercontent.com/74889675/119301991-ee5aa900-bc95-11eb-82de-1dcdcf94b441.jpg)
```
1. The DataCap will be mainly allocated to North American customers.
   Other regions Applications will enter the waiting queue.

2. We will classify customers based on their industry reputation and scale. 
   All customers will be divided into four categories:  top team customers, medium team customers, small team customers, and individual. 
   The four categories of customers are allocated 40%, 30%, 20%, and 10% respectively.

3. The client classification rules are as follows:
https://docs.google.com/spreadsheets/d/1LjVLLmV0GxEDZf4eH5hv3m2v00qDzbKlez9g0-t95RY/edit?usp=sharing

4. In the initial stage of specific allocation, we will take out a small part (<10%) of each category for testing, and gradually establish a reputation mechanism (including incentive, punishment, supervision)

5. Each assignment will be used to evaluate the customer's reputation.
   For example, if a customer applies the DataCap which is valid and efficient, its reputation credit will increase.
   With higher credit, the customer can apply more DataCap (maximum increase 200%).

6. Throughout the allocation and use the DataCap, we will establish a corresponding review mechanism.   
   Good customer will benefit, bad customer will be punished. The quality of the customer will be optimized gradually.
```
Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Our internal processes rarely involve allocating DataCap target, amount or rate.
Most of the processes are external, which are open to the public.
The few internal processes, such as the collection of confidential information or the execution of due diligence, will be in private. 
Only when we are unable to verify the truth and legality of the information provided by the customer, the internal processes will be triggered.
In addition, some third-party tools may also be used to collect the information of clients from web.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hardware wallet will be used to store the keys for DataCap address.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
Generally, the higher DataCap is needs, the stricter the customer review. In the early stages, all customers must go through a rigorous process.
For individual customers, the verification of their identity will be verified through two parts, the account age and the account activity, which will prove that customers are valid users and not machines. 
In addition, some open third-party data, such as Linkedin and Twitter official accounts, can also be used to verify online identities.
For organizational customers, we will set up a due diligence team and establish a complete review mechanism to ensure the reasonable allocation and effective use of the DataCap.
The following is the proposed due diligence procedure.
According to the customer level that requires due diligence, we need the following types of information. 
The review requirements for small-scale storage users are relatively simple, and users for large-scale storage will be strictly reviewed.

A. Basic information / Initial verification
Verify content:
1.Whether the customer have used up allocated DataCap
2.Valid client
(1)Active time is more than 6 months of github account or other authoried social platform account, like Twitter, linkedin, Weixin,etc.
(2)Whether to meet the basic requirements?
3.Application Requirements
XnMatrix accepts applicants for DataCap from all entities legally existing within the territory , including but not limited to enterprises, institutions, non-profit organizations, individuals, etc. Application requirements mainly includes three parts,  basic requirements, ban instructions, and annoucements.
Basic Requirements
（1）Abide by the laws and regulations of applicants' area with no bad record due to any violation of laws and regulations.
（2）All actions comply with the Filecoin community specifications and do not directly or indirectly harm the Filecoin network.
（3）The location of the applicant allows/does not restrict the development of distributed storage and related businesses. If there is any requirement about distributed storage and related businesses, the applicant should achieve corresponding required standards. 
（4）The data to be stored should meet the following requirements:
① Clients have the irrefutable proprietary right of the data, such as usage, storage, etc. Data can be from daily business, production, and data obtained and authorized from a third platform.
② The content should be legal, true, valid, and not sensitive.
（5）We discourage that miners or entities associated with miners apply for DataCap, and shall not conduct offline transactions with miners for benefits.
Ban Instructions
（1）It is prohibited for related applicants to apply at the same time.
（2）It is forbidden to upload false or unauthorized data.
（3）DataCap applications and data storage are prohibited for illegal, unethical or malicious purposes, including but not limited to give away, transfer or sell to third parties.
Annoucements
（1）The principle of exhausted Datacap: Before applying, please confirm that you have no available DataCap. The application will not be granted if the Datacap is not exhausted.
（2）The principle of waiting: XnMatrix will give priority to applications from North American clients. Applications from other regions should wait for 7 days. XnMatrix will confirm whether or not to process the application based on the remaining DataCap. If there is still a surplus after 7 days, XnMatrix will initiate the application vetting procedure for these applications.
（3）The principle of updated specifications: XnMatrix will process all applications in accordance with the above specifications. If it is necessary to add or modify the relevant specifications, XnMatrix reserves rights to decide whether to approve the requirements of clients in the process of application with the new regulations.
（4）The principle of response: During the vetting process, XnMatrix can put forward more requirements to clients, and all applicants shall respond within 7 days, otherwise it will be deemed to be automatically withdrawn and XnMatrix will close the issue.
（5）The principle of allocation: For individuals/organizations that meet the above basic requirements, XnMatrix will score and classify according to clients’profile. The detailed allocation plan is in the following part. XnMatrix will allocate 0-10 TiB for the first time, 0-20TiB for the increased application, 0-100TiB for the accumulated application. If there is no sufficient reason, it is recommended to apply for DataCap within the above amount.
（6）All interpretation rights belong to XnMatrix within the law.

B. Basic requirements of DataCap allocation / Second verification
Verify content:
1.Whether the region is same as the notary's region?
2.Information integrity, whether there are the following required items not filled in / selected:
(1)Name, website / social media, filecoin address, DataCap request
(2)Region (where you / company, the client,  based)
(3)An individual or a company
    For an individual: number of social media audiences, past project level, filecoin activities,data type, storage requirements，links to social media/news mentions, etc.
    For company:date of establishment, number of employees, business area, number of registered users, number of social media audiences, storage requirements, the best products or projects, links to social media/news mentions etc.
(4)Whether they are willing to publish the transaction flow on GitHub;
(5)Data source, your relationship with data.
3. Information accuracy
(1) Whether the website / social media is a valid link;
(2) Whether the filecoin address is a valid filecoin address;

C. More information/Final verification
Confirm the DataCap allocation plan with the qualified client. Reclssify if the client add extra questions to verify the client's qualification, and decide allocation scale.
Content:
1. The client's application records from other notaries, whether it is finally passed or rejected. whether it is properly used after allocation, and the reasons for rejection, etc
2. For qualified clients, grant DataCap according to the level. For the allocation plan, whether the client accepts it

After collecting and reviewing the above information, they will learn spend the DataCap reasonably and effectively.
We will make a training plan and release an online test for DataCap and Filecoin. Only clients who pass the test can apply the dataCap.
We will help customers match and recommend more suitable miners. We will provide clients more useful information about miners, such as failure rate, storage cost, safety, reliability, capacity, etc.
We mark the results of using DataCap as the feedback to influence the allocation in future , thereby affecting customer behavior.
The incentive mechanism, punishment mechanism and supervision mechanism will make spending the DataCap responsibly and effectively.

1. incentive mechanism
If a customer applies the DataCap which is valid and efficient, its reputation credit will increase. With higher credit, the customer can apply more DataCap (maximum increase 200%).
We encourage customers to allocate DataCap to more new miners, and each new miner allocation will have additional incentives.

2. punishment mechanism
If a customer is found to be abusing data, it will be punished.The next apply will reduce 50%.
In particular, if the client and the miner cheat together, both of them will be added to the banlist.
Other clients can report unfair allocation.

3.supervision mechanism
As a Notary, we will develop a tool to randomly check verified transactions of all customers to ensure they comply with the agreement.
Also,we will use a series of incentive mechanisms to encourage other clients to report unfair allocation and allow them to monitor and  supervise each other.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
We will ask customers the following questions:
1.Are you representing for yourself or your company？
2.If you are representing for your company, Please give the following informations, duration of etablishment, number of employees, business scope, users volume, number of social media followers, data size to be stored, products or projects, and so on. If you are representing for yourself , please introduce yourself,such as number of social media followers, filecoin activities partipation with links, data size to be stored. Provide links to social media/news mentions.
3.The history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time, etc.
Type, size, and source of the data you will be store on Filecoin,e.g. public data or private data, etc. Is there any sensitive or illegal content?
4.How do you intend to store the data on Filecoin, e.g. redundancy, location/miner preferences, etc
5.Have you already apply for DataCap to another notary, and whether it is accepted or rejected. Is there any reliable DataCap left?
6.Would you like to post real transactions on Github?
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
We will monitor and track the use of DataCap strictly.
Each assignment will be used to evaluate the clients' reputation. 
We encourage customers to allocate DataCap to more new miners, and each new miner allocation will have some incentives.
Also, we will develop a tool to randomly check verified transactions of all customers to ensure they comply with the agreement.
If some problems are found, we will communicate and coordinate promptly. 
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
We will keep every detail record for all allocation decisions on Github, including time, amount, allocated customers, reason for judgment, etc.
Since all interactions are intended to occur publically, most of the allocation decisions should be self-explanatory.
Any challenges raised regarding allocation decisions should be discussed publicly, e.g. the Github repo.
If convincing justifications can’t be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date.
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders to resolve the dispute.
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will happen in the Github repository publicly.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
100TiB received before. Link: https://github.com/filecoin-project/notary-governance/issues/27
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
25TiB
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None
```

**Comment by dkkapur** [comment]
Previous applications:
- https://github.com/filecoin-project/notary-governance/issues/27

Allocation track record from last round:
- 30 TiB allocated in past round, 8 client applications in repo, 8 verified clients in dashboard currently
- list of client applications approved: https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues?q=is%3Aissue+assignee%3AXnMatrixSV+is%3Aclosed+label%3Astate%3AGranted

Client applications and usage of datacap: 
![image](https://user-images.githubusercontent.com/2343218/120254377-8c261900-c23e-11eb-9ad7-1062e49b2eeb.png)

DataCap received by miner IDs:
| Notary Name | Miner ID | DataCap received in GiB | % of Notary's DataCap Grant |
|-------------|----------|-------------------------|-----------------------------|
| XnMatrix    | f01234   | 192.000063              | 0.75%                       |
| XnMatrix    | f09848   | 104.0000341             | 0.41%                       |
| XnMatrix    | f015927  | 72.00002362             | 0.28%                       |
| XnMatrix    | f014409  | 8.000002624             | 0.03%                       |
| XnMatrix    | f01278   | 472.0001548             | 1.84%                       |
| XnMatrix    | f022352  | 472.0001548             | 1.84%                       |
| XnMatrix    | f023467  | 192.000063              | 0.75%                       |
| XnMatrix    | f0157535 | 516.0001692             | 2.02%                       |
| XnMatrix    | f066596  | 32.0000105              | 0.13%                       |
| XnMatrix    | f071624  | 64.00002099             | 0.25%                       |
| XnMatrix    | f010446  | 32.0000105              | 0.13%                       |
| XnMatrix    | f01240   | 1696.000556             | 6.63%                       |
| XnMatrix    | f010479  | 96.00003149             | 0.38%                       |
| XnMatrix    | f061158  | 64.00002099             | 0.25%                       |
| XnMatrix    | f019551  | 32.0000105              | 0.13%                       |
| XnMatrix    | f08403   | 64.00002099             | 0.25%                       |
| XnMatrix    | f02387   | 64.00002099             | 0.25%                       |
| XnMatrix    | f062353  | 224.0000735             | 0.88%                       |
| XnMatrix    | f014768  | 64.00002099             | 0.25%                       |
| XnMatrix    | f023971  | 1160.00038              | 4.53%                       |
| XnMatrix    | f08399   | 8.000002624             | 0.03%                       |
| XnMatrix    | f0221135 | 32.0000105              | 0.13%                       |
| XnMatrix    | f01276   | 256.000084              | 1.00%                       |
| XnMatrix    | f0447183 | 1328.000436             | 5.19%                       |
| XnMatrix    | f019104  | 32.0000105              | 0.13%                       |
| XnMatrix    | f0145874 | 64.00002099             | 0.25%                       |

**Comment by dkkapur** [comment]
Hi @XnMatrixSV  - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1uYFXrK8b2KdV83AsJo5nqrWjyUz6BTxREsAiySidaNQ/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 2.4.

**Comment by XnMatrixSV** [comment]
Hi, @dkkapur 
I have some information to add about your question in the table.
Q1:Twitter for company has > 500 Followers, can you confirm that you can leverage this to tweet about Filecoin and Filecoin Plus (and related events)?
A:we need to add another Twitter account, https://twitter.com/XnMatrixSV
We have 2,390 followers on Twitter, we are willing to post  related events about Filecoin and Filecoin Plus on Twitter.
Q2:All allocation decisions are visible in GitHub and data lines up with what is tracked in Fil+ dashboard. Great to see it!
A:All allocation decisions will happen in the Github repository publicly, [repository](https://github.com/filecoin-project/filecoin-plus-client-onboarding)
In addition, we have created a special repository(https://github.com/XnMatrixSV/Bookkeeping) and We will continue to optimize in the subsequent allocation process.
Thank you.

**Comment by dkkapur** [comment]
@XnMatrixSV - thanks for sharing your responses. Your rubric has been re-scored:
- Individual reputation: increased from 0 to 1, given the above confirmation of being able to use the 2 Twitter accounts
- Bookkeeping plan: increased from 2 to 3, based on shared tooling / dedicated GitHub repo 

The final scores for this election cycle are:
- rounded Final Allocation Amount: 2
- unrounded score: 2.4

Here is the link to the updated rubric: https://docs.google.com/spreadsheets/d/1uYFXrK8b2KdV83AsJo5nqrWjyUz6BTxREsAiySidaNQ/edit?usp=sharing

**Comment by dkkapur** [comment]
@XnMatrixSV in an effort to be more consistent with scoring on bookkeeping, your score is now at a 5 for this category. 

The final scores therefore for this election cycle are:

    Rounded Final Allocation Amount: 3
    Unrounded score: 2.6

Here is the link to the updated rubric: https://docs.google.com/spreadsheets/d/1uYFXrK8b2KdV83AsJo5nqrWjyUz6BTxREsAiySidaNQ/edit?usp=sharing

**Comment by dkkapur** [comment]
@XnMatrixSV - based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of 959 TiB (qualified for 1024 TiB, currently has an allocation of 65 TiB). In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm that the region of operation for client applications you will focus on is [North America]

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

> * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

> * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

> * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**Comment by XnMatrixSV** [comment]
> 1. Please confirm that the region of operation for client applications you will focus on is [North America]
    Confirmed.
> 2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> - Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship
      Confirmed.
> - Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.
      Confirmed.
> - Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.
      Confirmed.
> - No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.
      Confirmed.
> - Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.
      Confirmed.
> - Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.
      Confirmed.
> 3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.
      Our miner IDs are f02614, f09652, f010424, f03362, f020928, f039992. All the miners are managed by XnMatrix and owned by investors.
> 4. Please affirm that you will abide by the allocation / client due dilig ence plan you laid out above.
    We will abide by the allocation / client due dilig ence plan we laid out above.
> 5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.
f1g22n3xpcnied4al2epgtslinc5gpfhj46ivy3nq

**Comment by dkkapur** [comment]
@XnMatrixSV - I was wrong about not being able to use the same address again as Notary. I mentioned this in Slack last week but want to check with you before next steps; would you rather proceed with reusing `f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a` or receive the second allocation at `f1g22n3xpcnied4al2epgtslinc5gpfhj46ivy3nq`?

**Comment by XnMatrixSV** [comment]
I‘d rather proceed with reusing f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a. Thanks, @dkkapur .

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### Datacap Allocated
> 1PiB

**Comment by dkkapur** [comment]
This went through correctly

**Comment by XnMatrixSV** [comment]
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a

Hi we want to change the address to f1nneomjjusexfkglvgdpphztfwbmago223jrtawa

could you tell us the process of updating?

thank you

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
[bafy2bzaceanw75b76mf4kdw2eg4iq3xpa7p3vdvgxscmrp5uihbdk4iyb7kwi](https://filfox.info/en/message/bafy2bzaceanw75b76mf4kdw2eg4iq3xpa7p3vdvgxscmrp5uihbdk4iyb7kwi?t=4)
