### ISSUE TITLE
Notary Application：KaptinLin

### ISSUE THREAD

**Issue by KaptinLin** [filecoin-project/notary-governance#152]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: KaptinLin
- Affiliated Organization: Minerhub
- Website / Social Media: @KaptinLin on Github, @kaptinlin on Filecoin Slack	
- On-chain Address to be Notarized: f2x3qejzy5l2jju6fewcgnkxrvigzhd7zwhv34wdy
- Region of Operation: Greater China
- Use case(s) to be supported: Internet, media and digital city
- DataCap Requested: 500TB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
As an individual,I’ve been a part of the Filecoin community since 2019. I’ve been an active members and closely participate in the Filecoin ecosystem through Filecoin Slack, involving in many conversations dedicated to supporting Filecoin. I want to support Filecoin development and ecosystem as much as I can.
-My Github handle: @KaptinLin
-My miner ID: F0102670

As an organization, Minerhub (https://minerhub.com/) is a leading one-stop mining service provider, committed to Filecoin mining solutions in a cost-effective way. 
-The mining monitor tool we developed Fgas (https://fgas.io/) has been granted by the Filecoin Official as valued ecosystem tool.
-The technical team of the CreativeFileCloud project, which ranks 2 in the Slingshot phase one competition. https://www.bilibili.com/video/av457590471/
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
My miner ID: F0102670 
I have a total of 87,311.8900 FIL at stake, including 12,346.6173 FIL available, 65,271.6286 FIL locked as collateral, 9,732.2192 FIL vesting over time.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
I am actively participating and helping the Filecoin miner community on Slack, presenting in multiple Filecoin talks and panels.
-Participating to /Slingshot /Filecoin Plus/Slingshot phase 2.3 rules/Verified Datacap trade/ Community activities. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```None.```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Minerhub is a private company founded on 2018, in Xiamen, China.
The company is for-profit, and its country of registration is China. At the moment, we have over 100 employees.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Minerhub is a well established mining service company. It aims to optimize the mining algorithm and increase the mining efficiency. Minerhub works with large and medium scale miners from Ethereum and Filecoin. As a mining service company,we highly support the growth of the Filecoin ecosystem, and advocates for Filecoin and the Decentralized Web.
Minerhub website: https://minerhub.com/
Here are some events we attended:
https://www.chainnode.com/event/538531
https://www.chainnode.com/event/548924
https://www.chainnode.com/event/557805
https://www.chainnode.com/post/516892
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Here are some articles introducing our company and projects:
https://www.chainnode.com/event/544703
https://www.chainnode.com/post/567434
http://www.zhiziclub.com/contentDetail?articleId=77324
http://www.zhiziclub.com/contentDetail?articleId=78803
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
I plan to support multiple use cases:
Internet data (including website backup, user personal data, etc.)
Media (including master disk protection of traditional media, low-visit videos of media, regulatory archives, etc.)
Digital city (including aerial surveying and mapping, Internet of Things data collection, video surveillance, etc.)
As we proceed, other use cases will be considered.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
First of all, we do not define threshold of the Datacap allocated to each use case, but will do a risk control based on the 
The 80/20 Rule. For all new applicants (first time application within the entire Filecoin network), the first allocation will not exceed 20% of the total DataCap, and a single new client will be less than 10%, and the remaining 80% of the Datacap is allocated to consecutive customers who have been tested for credibility.
For new clients, we will first conduct offline due diligence. If they conduct the use cases we are familiar with, we will evaluate whether their data is suitable for Filecoin and whether the amount of DataCap applied for is reasonable. If they are in other use cases, we will consult the notaries who are eligible with. And then we will make evaluation and suggestion on the miners that the client plans to cooperate with with reference to the credibility on filrep.io.
When the clients run out of their initial Datacap and try to apply again, no due diligence will be performed. But the usage and allocation of the previous Datacap will be investigated. If the rules of Filecoin Plus and the promise at the time of application are followed, we will allocate new DataCap based on their business increment again.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
First of all, we do not define threshold of the Datacap allocated to each use case, but will do a risk control based on the 
The 80/20 Rule. For all new applicants (first time application within the entire Filecoin network), the first allocation will not exceed 20% of the total DataCap, and a single new client will be less than 10%, and the remaining 80% of the Datacap is allocated to consecutive customers who have been tested for credibility.
For new clients, we will first conduct offline due diligence. If they conduct the use cases we are familiar with, we will evaluate whether their data is suitable for Filecoin and whether the amount of DataCap applied for is reasonable. If they are in other use cases, we will consult the notaries who are eligible with. And then we will make evaluation and suggestion on the miners that the client plans to cooperate with with reference to the credibility on filrep.io.
When the clients run out of their initial Datacap and try to apply again, no due diligence will be performed. But the usage and allocation of the previous Datacap will be investigated. If the rules of Filecoin Plus and the promise at the time of application are followed, we will allocate new DataCap based on their business increment again.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Our DataCap will be kept in a multi-signature address, and at least three organization members need to sign for the transaction to be conducted.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
We think the incumbent notary Fenbushi Capital did a good job in due diligence, and we will use their due diligence template: https://github.com/filecoin-project/filecoin-plus-client-onboarding/tree/main/Fenbushi%20Capital
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
As mentioned, we will adopt similar questions to the question list of Fenbushi Capital:
1.Description of your major business as well as the type and size of the data you plan to store;
2.What do you know about FIlecoin network and what motivates you to choose it for your data storage;
3.What is your past practice on data storage;
4.Why do you apply for DataCap and what makes you think your data storage worth of spending DataCap;
5.Allocation among miners - who are the miners you plan to store the data with and the reasons (including allocation proportion with each miner);
6.Specific requirements for intended miners (e.g. redundancy, location, encryption requirements;
7.Any measures (technical or/and non-technical) to ensure proper allocation of DataCap;
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Some third-party tools, like Filhub can be used to collect the information of DataCap usage.We will use their tools to track DataCap usage information on-chain.
If the client has overallocate their Datacap to one entity, we will impose limitation on their further applications.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
We will track and allocate the clients application in a transparent manner via Github repo/issue. In addition, we will make some internal forms and databases to record more due diligence information to support better retrieval. We will also regularly synchronize these with other notaries and officials.
Due to the due diligence required for the first time application, the required response time will be relatively long, but it will not exceed one month;
For the second time and beyond applications, the response time will be controlled within one week.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We intend to do all the allocation in public channel (tentatively on Github) for transparent purpose and to be supervised by the Filecoin community.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None.
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None.
```

**Comment by dkkapur** [comment]
Hi @KaptinLin  - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1bRMf8624dyiJf30EXB8-0UvMyCbDIDCV2FnPC91NSio/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.4.

**Comment by KaptinLin** [comment]
@dkkapur Thanks for your reply！
Regarding your concerns, 

1.Here is our detailed plan on how clients will be selected or what factors will be weighed more:

https://docs.google.com/spreadsheets/d/1UYfgmVYkk1ys1ZeX_OfAQw7xpbEoxxrycDWkp5dT77w/edit?usp=sharing

2.For the place of allocation decisions be made and tracked，we will update them on :
https://github.com/filecoin-project/filecoin-plus-client-onboarding

**Comment by KaptinLin** [comment]
@dkkapur Thanks for your reply！
Regarding your concerns,

1.Here is our detailed plan on how clients will be selected or what factors
will be weighed more:

https://docs.google.com/spreadsheets/d/1UYfgmVYkk1ys1ZeX_OfAQw7xpbEoxxrycDWkp5dT77w/edit?usp=sharing

2.For the place of allocation decisions be made and tracked，we will update
them on :
https://github.com/filecoin-project/filecoin-plus-client-onboarding

**Comment by dkkapur** [comment]
@KaptinLin - thanks for sharing! Based on this, the score for Allocation Strategy was increased to a 5. The final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 1.6

Link to rubric: 
https://docs.google.com/spreadsheets/d/1bRMf8624dyiJf30EXB8-0UvMyCbDIDCV2FnPC91NSio/edit?usp=sharing
