### ISSUE TITLE
Notary Application:Koda Inc.

### ISSUE THREAD

**Issue by KodaRobotDog** [filecoin-project/notary-governance#153]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name:  Emma Russell
- Affiliated Organization:  Koda Inc.
- Website / Social Media:@KodaRobotDog on the Filecoin/Slack
- On-chain Address to be Notarized:f1fb27mp6xwlfgcm4vhxwdrjx5ldsqtdtzu3vh6ay
- Region of Operation: North America
- Use case(s) to be supported: AI, Intelligence, Big Data
- DataCap Requested:1 PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
My name is Emma Russell, and I am the CEO  of Koda Inc. 
I’ve been actively involved in the Filecoin community for more than one year.  I am the manager for  Koda twitter @KodaRobotDog so I had lots of interaction with IFPS/Filecoin network in the past year.  I personally promote IPFS/Filecoin storage with Maye Musk:
```
<img width="657" alt="97525b93a8d30e77bff619fda1e510b" src="https://user-images.githubusercontent.com/71876834/120419650-6a8b7580-c395-11eb-9ff4-afec11faf854.png">

```
As a Filecoin user case, KODA is the world’s first decentralized Robot dog. 
My Github name:  KodaRobotDog 
My Slack handle:   @KodaRobotDog
Koda’s Twitter has an active interaction with IPFS core teams such as Juan, Collin, and Molly. Koda was featured on IPFS website:
https://docs.ipfs.io/concepts/usage-ideas-examples/
Koda participated Slingshot and won prizes in August 2020:
https://github.com/koda9-inc/slingshot/commit/5be630cc5a7e9bc2b7006d267f6a9941a1b15a80
https://github.com/filecoin-project/slingshot/pull/109/files/5be630cc5a7e9bc2b7006d267f6a9941a1b15a80#diff-7cf22450ffac34e30503fba623487997f5f762f65e0f7bae33fc0fad318da2c1
Above is the link for Koda Robot Dog data collecting SlingShot Phase 1 Competition information  and below is our Rewards:
```
<img width="411" alt="1 (1)" src="https://user-images.githubusercontent.com/71876834/119305189-fbc66200-bc9a-11eb-8cba-7b416729a415.png">

```
Moreover, Koda Robot Dog had great exposures on main stream media and most of those articles also talked about Koda owners have the option to store on Filecoin. In short, we brought many viewers from AI and robots’ community to Filecoin community:
1. Yahoo! Finance, KODA Pre-Launches World's First Futureproof Social Robot Dog: https://finance.yahoo.com/news/koda-pre-launches-worlds-first-123200698.html 
2. Forbes Walmart Ditches Major Robot Contract: So What Does This Mean For The Industry?:https://www.forbes.com/sites/tomtaulli/2020/11/08/walmart-ditches-major-robot-contract-so-what-does-this-mean-for-the-industry/?sh=7120c25c2b52
3. BBC, This robot dog knows how you're feeling:https://www.bbc.co.uk/newsround/amp/55816322
4. Towards Data Science, The Future of AI is Decentralized:https://towardsdatascience.com/the-future-of-ai-is-decentralized-848d4931a29a
Social Media Profiles: 
1. Twitter: https://twitter.com/kodarobotdog?lang=en 
2. Instagram: https://www.instagram.com/kodarobotdog/?hl=en
3. YouTube: https://www.youtube.com/channel/UCmi9nzoQw0ZEEJUwyekkJxA
Expected market coverage: 1,000 dogs are expected to be sold worldwide at $50,000 per dog, covering 1,000 high-end families.
Robodog spokesperson Maya Musk's Twitter will regularly call for using Filecoin storage, and we'll promote Filecoin storage on a regular basis for the long term.

At the same time, Koda Inc will launch Koda Drive, which aims at promoting centralized IPFS storage among young people. Maye Musk called on young people around the world to use IPFS/Filecoin Network storage, which greatly promoting the real usage of  storage market based on Filecoin Network.

https://kodarobotdog.medium.com/100-woman-creators-3551e5325e55
Layouts around the robot dog business based on IPFS/Filecoin:
Koda Robot Dog has a decentralized storage market, that is Koda Drive, similiar to Icloud of Apple. We called on young people all over the world to use Koda Drive and greatly promote the storage market based on Filecoin Network.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
I prefer not to disclose.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
The interaction of IPFS and Koda Robot Dog on Twitter:
（1）Koda Robot Dog liked by IPFSMain.
https://twitter.com/kodarobotdog/status/1364704207773724673?s=21
```

<img width="183" alt="1 (3)" src="https://user-images.githubusercontent.com/71876834/119305438-4fd14680-bc9b-11eb-9522-4773378972fb.png">
<img width="199" alt="1 (4)" src="https://user-images.githubusercontent.com/71876834/119305459-565fbe00-bc9b-11eb-9b01-350a5dfbd367.png">

```
（2）Koda Robot Dog Twitter liked by Juan Benet.
https://twitter.com/kodarobotdog/status/1316523206228865024?s=21
```

<img width="173" alt="1 (5)" src="https://user-images.githubusercontent.com/71876834/119305484-5e1f6280-bc9b-11eb-8378-dee75d25b3e2.png">
<img width="204" alt="1 (6)" src="https://user-images.githubusercontent.com/71876834/119305516-68d9f780-bc9b-11eb-9e81-c9c39dc6ae96.png">

```
（3）Koda Robot Dog interacted with Jesse, Juan Benet, Molly, Colin, IPFSMain, Filecoin.
 https://twitter.com/kodarobotdog/status/1339726416129052672?s=21
```

<img width="186" alt="1 (7)" src="https://user-images.githubusercontent.com/71876834/119305537-70999c00-bc9b-11eb-96f6-825a487666e1.png">

<img width="178" alt="1 (8)" src="https://user-images.githubusercontent.com/71876834/119305544-71cac900-bc9b-11eb-9a6f-7d4aeee56103.png">

<img width="177" alt="1 (9)" src="https://user-images.githubusercontent.com/71876834/119305580-7db68b00-bc9b-11eb-8c26-d3de74e4a56c.png">

<img width="159" alt="1 (10)" src="https://user-images.githubusercontent.com/71876834/119305579-7db68b00-bc9b-11eb-9d78-212b96fba226.png">

```
（4）Koda Robot Dog was mentioned by Molly on Twitter.
https://twitter.com/momack28/status/1296514875972231174?s=21
```

<img width="140" alt="1 (11)" src="https://user-images.githubusercontent.com/71876834/119305586-80b17b80-bc9b-11eb-8df8-c627f6ba3a67.png">

```
（5）Koda Robot Dog was mentioned by IPFSMain on Twitter.
https://twitter.com/ipfs/status/1293186672645947393?s=21
```
<img width="161" alt="1 (12)" src="https://user-images.githubusercontent.com/71876834/119307074-b0618300-bc9d-11eb-8704-49be778c9ac5.png">
<img width="138" alt="1 (13)" src="https://user-images.githubusercontent.com/71876834/119305677-9fb00d80-bc9b-11eb-822e-4e3099038e91.png">

```
（6)Koda Robot Dog's article was forwarded by IPFS Pinbot.
https://twitter.com/kodarobotdog/status/1295806231961993218?s=21
```

<img width="157" alt="1 (14)" src="https://user-images.githubusercontent.com/71876834/119305753-bf473600-bc9b-11eb-8aa2-f44f4c68346b.png">

```
（7）Koda Robot Dog was mentioned by IPFSMain on Twitter, which was liked by IPFS.
https://twitter.com/ipfsmain/status/1364342684463230978?s=21 
```

<img width="128" alt="1 (15)" src="https://user-images.githubusercontent.com/71876834/119305830-d6862380-bc9b-11eb-899f-d2e729cfa608.png">

<img width="136" alt="1 (16)" src="https://user-images.githubusercontent.com/71876834/119305840-d8e87d80-bc9b-11eb-9923-8b930a5ac108.png">

```
（8）Koda RobotDog is followed by all the core team member of IPFS, and IPFSMain always interact with us.
```

<img width="411" alt="1 (17)" src="https://user-images.githubusercontent.com/71876834/119305881-ea318a00-bc9b-11eb-84ce-b171de25ad73.png">

<img width="109" alt="1 (18)" src="https://user-images.githubusercontent.com/71876834/119305923-f9183c80-bc9b-11eb-903c-f94c4e1c7f1c.png">

```
（9）Koda Robot Dog's article was forwarded  by  many tech bloggers, which mostly liked by IPFS official Twitter. 
```

<img width="172" alt="1 (19)" src="https://user-images.githubusercontent.com/71876834/119305922-f9183c80-bc9b-11eb-90d5-fe4dc0ff6491.png">

<img width="193" alt="1 (20)" src="https://user-images.githubusercontent.com/71876834/119305934-fb7a9680-bc9b-11eb-86dc-7d336e78e63c.png">

<img width="184" alt="1 (22)" src="https://user-images.githubusercontent.com/71876834/119305949-03d2d180-bc9c-11eb-8bac-3f61c6bea8fe.png">

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
We haven’t made any Bug suggestion.But during the IPFS/Filecoin testing phase, we've been involved, working with miners in a number of countries.
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Organization: Koda Inc.
Nature:  private company
Registration Country: Delaware, US
Established:May, 2020
Size: over 10 employees
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Homepage: koda9.com
Twitter: https://twitter.com/KodaRobotDog
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Headquartered in Mountain View, California, Koda Inc. is an innovative robotics company harnessing decentralized computing power's advantages. The company's inaugural product is a quadruped robotic dog named KODA, the world's first decentralized AI robotic dog with the option to store data on IPFS.
KODA has won “Red Dot Award: Product Design 2021,” was featured as "Best of CES 2021" by the Wall Street Journal, and was covered by various major news media platforms, including BBC News, Forbes, etc.
As an IPFS (Filecoin) user case, Koda team presented on Filecoin monthly meetup in August 2020. Koda tweets had active interaction with IPFS core teams such as Juan, Collin, Molly.  Koda Robot Dog had great exposures on main stream media and most of those articles also talked about Koda owners have the option to store on Filecoin. Basically, we brought many viewers from AI and robots community to Filecoin community:
Homepage: koda9.com
Twitter: https://twitter.com/KodaRobotDog
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
AI, Intelligence, big data
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
By limiting the maximum allocation that customers can apply for the first time, we are able to control the storage usage of customers within a controllable scope.
Target customers: Considering the small storage demand of individual customers, we only support enterprise users who have their own real data at this stage;Give priority to organizations locate in North America.
The DataCap allocation is determined by scoring, and the score results are 1,2,3, and 4, the first maximum allocation of score corresponds to 2.5TiB, 5TiB, 7.5TiB, 10TiB. Allocation can be increased next time according to the actual usage of customers.
Scoring Rule
```
![1621838437(1)](https://user-images.githubusercontent.com/71876834/119307311-151cdd80-bc9e-11eb-9883-a98e2d1cee6c.jpg)

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Auditing stage
1. Ensure publicity and transparency of the entire application process
2. Investigate customer background online and offline/conduct online interview
3. Strictly examine the authenticity of the information provided by customers
Distribution stage
Score and determine data cap allocations
Tracking after distribution
1. Make a sampling survey of the data that customers need to store to confirm the reality and validity of the data
2. Conduct irregular investigation on customers' subsequent usage, and adapt reward and punishment mechanisms.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
By using a Ledger Wallet, which is only accessible by only the person in charge. 
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
After application for the first time, customers will be randomly checked on their usage and stored data.
If the customer's storage data meets the requirements of reality and validity and the storage demand is greater than Datacap obtained for the first time, the subsequent application can be increased next time according to the actual usage of customers. If the customer's storage data does not meet the requirements or the actual storage demand is less than the first application amount, the customer will be punished and all subsequent requirements will be rejected.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
1. Can you introduce your organization? Where can I find you online? (Github, Twitter, Linkedin handle) 
2. Please give more information about your organization. What are the establishment time, business scope, number of registered users, number of social media followers, and storage usage of your company? e.g. include links to social media/news mentions etc.
3.can you talk more about your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time, etc
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Prospective clients are encouraged to allocate the DataCap to more different miners. The interaction will be required to publish on Github.
which not only increases storage redundancy but also helps maintain decentralization and reduce the possibility of potential misuse. 
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Yes, all allocation decisions will be guided by the rubric publicly on Github. So are all communications. 
Since all interactions are intended to occur publically, most of the allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly in the Github repo first. 
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be conducted in the Github repository. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None
```

**Comment by dkkapur** [comment]
Hi @KodaRobotDog  - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1tE5thhKFSpvowmlRnr0LI3EQH5XM4IxzbjRNTyeBghA/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.2.

**Comment by KodaRobotDog** [comment]
Hello, @dkkapur. I added more information the initially scored rubric. 

Q1:The RobotDog presence does not count towards individual reputation. Do you have other presences, Emma? 
Emma : https://www.linkedin.com/in/emmaucsd/, over 10000 followers.
John Suit(the advising CTO of Koda Inc.) : https://www.linkedin.com/in/john-suit-226b35/, over 1000 followers.
He has been actively involved in the Filecoin community for more than one year, and he presented Koda Robot Dog at the Filecoin monthly virtual meet up in August, 2020. 

Q2:Rubric cites storage demands as 1P and greater; it is most likely that clients are requesting DataCap on the per TiB level. Is the PiB level intentional?  
We have made some adjugements on this point. 

Q3:Details on how client usage of DataCap is tracked and feedback is provided would be useful 
we will ask for the details on how client usage of DataCap and keep records in https://github.com/filecoin-project/filecoin-plus-client-onboarding 

Q4:Will all allocation decisions be made in https://github.com/filecoin-project/filecoin-plus-client-onboarding? 
Yes, we will publish all our decisions on Github.

**Comment by KodaRobotDog** [comment]
Hello Deep,

 I updated my application as Notary on Github. I wonder whether I can get
some score on "Individual Reputation"? I believe I made some noise in the
community and on twitter. I've been in the community since last summer.


Best,


Emma @Koda

**Comment by KodaRobotDog** [comment]
My linkedin has 10,000+ followers where I can post my status as a notary if
approved publicly.

My twitter accounts has 7000+ followers where I can post my status as a
notary if approved publicly. (https://twitter.com/KodaRobotDog)

I think I can fit into L3 BOX about "individual reputation"

**Comment by dkkapur** [comment]
@KodaRobotDog thanks for sharing this info! Made the following updates: 
- Stake exposure: 2, validated that those minerIDs have > 500k FIL at stake
- Individual reputation: 2, each account individually needs 10k+ followers for this to be at a 3
- Allocation strategy: 5
- Client Due Diligence: 3, though this could have also been at a 5 had there been a plan for how you will ensure clients are distributing fairly across miners + a process for checking this for future allocations. A 3 or a 5 here would have yielded the same scoring outcome in this round, so does not make a difference in this case. 

Based on this, the final scores in this election cycle are: 
- Rounded Final Allocation Amount: 2
- Unrounded score: 1.7

Link to rubric: https://docs.google.com/spreadsheets/d/1tE5thhKFSpvowmlRnr0LI3EQH5XM4IxzbjRNTyeBghA/edit?usp=sharing

**Comment by dkkapur** [comment]
@KodaRobotDog - based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of 100 TiB (qualified for 100 TiB based on rubric scoring). In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm that the region of operation for client applications you will focus on is [North America]

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

> * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

> * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

> * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**Comment by KodaRobotDog** [comment]
1. Confirmed.
2. Each of the following items were confirmed.
> - Upfront Disclosures: Confirmed.
> - Promoting Client Best Practices: Confirmed.
> - Commitment to efficiently serving the Network: Confirmed.
> - No Self Dealing: Confirmed.
> - Operating in Good Faith: Confirmed.
> - Community Governance Participation: Confirmed.
3. Miners we run: f082095, f0100033, f095970.
4. We will abide by the allocation / client due diligence plan we laid out above.
5. There are something wrong with the previous address, we will use f1jyalts5uhtmp5sbbssse23toshvsqbbtjgukm5a.

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1jyalts5uhtmp5sbbssse23toshvsqbbtjgukm5a
#### Datacap Allocated
> 100TiB

**Comment by dkkapur** [comment]
This grant seems to have gone through correctly and should not be in Error status. Fixing this now!

**Comment by KodaRobotDog** [comment]
@dkkapur @galen-mcandrew @Kevin-FF-USA 
Hello, friends.
We will add a slack handle,@Blair-Kodadog. 
Please add him in the notary channel.
Thanks.

**Comment by KodaRobotDog** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceack6kfjagljtxoghuy76edb2ktnpcgjyanpnh47dddsslet7e5mm
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceack6kfjagljtxoghuy76edb2ktnpcgjyanpnh47dddsslet7e5mm
