### ISSUE TITLE
Notary Application-IPFSCLOUD

### ISSUE THREAD

**Issue by billysoa** [filecoin-project/notary-governance#155]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
Name: YuLiang Bai
(Optional) Affiliated Organization: IPFS Cloud
Website / Social Media: @YuLiang Bai on the Filecoin Slack
On-chain Address(es) to be Notarized: f2dinnf2h4eeuyz5hf2wogbz2bkvapnks7uash7mq
Region of Operation: Greater China
Use case(s) to be supported: Personal user storage, scientific datasets, video & music.
DataCap Requested: 100TB

###Long Term Network Alignment
**Time Commitment**
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

As an individual, I have worked as a crypto miner for over 4 years. 
I’ve been a part of the Filecoin community since 2018 and founded IPFS Cloud in 2018. 
I am also one of the Slingshot community reviewers who are helping evaluate applicant projects. 
I recently have been nominated to serve in the Filecoin Foundation Mining Working Group. 

As an organization, IPFS Cloud is a leading service provider committed to comprehensive Filecoin mining solutions in a cost-effective way. 
We have built quite an extensive relationship with the Filecoin community since its initial launch back in 2018, 
and as a result, have sustained countless contributions to the overall network. 

We have multiple miners running on the Filecoin network; here are 3 well-known nodes since SR1: f0146393& f048986&f048975.

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
The total FIL at stake is over 149440Fil.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

The total FIL at stake is over 149440Fil.

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
`
As a member of the Filecoin community, we have
- joined the Slack.
- post on Slack : https://slate.host/coco/cid:bafybeifep6h4opewt5gwtiaqmxb4qgbw5lbmv6q4dyxnpjm5cvupedkvem

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

IPFSCloud  is a private company founded on 2018, in Shenzhen, China. 
The company is for-profit, and its country of registration is China. 
At the moment, we have over 40 employees working at the Shenzhen.

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

IPFSCloud: https://web.ipfs1606.com

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

https://slate.host/coco/cid:bafybeifep6h4opewt5gwtiaqmxb4qgbw5lbmv6q4dyxnpjm5cvupedkvem

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?

I plan to support multiple use cases

-30% - user content
- 30% - AI training
- 40% - media (video & music)

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.

```
No one but myself will be allocating datacap.
```
Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
No one but myself will be allocating datacap.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
   A hardware wallet will be used to store the keys associated with the DataCap allocation address securely. 
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
Please answer here.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
Please answer here. 
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Please answer here. 
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Please answer here.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Please answer here. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Please answer here.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
Please answer here. 
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
Please answer here.
```

**Comment by dkkapur** [comment]
Hi @waynewyang - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1x27ob5_bRM13b3OxN8KKw2MkAeveP1FHlV8kt8ptZNc/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.1.

**Comment by dkkapur** [comment]
@billysoa, the final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 1
- Unrounded score: 1.1

Link to rubric: 
https://docs.google.com/spreadsheets/d/1x27ob5_bRM13b3OxN8KKw2MkAeveP1FHlV8kt8ptZNc/edit?usp=sharing
