### ISSUE TITLE
Notary Application -Filswan |NBFS

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/notary-governance#157]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name:  Filswan
- Affiliated Organization: 
Filswan – NBFS Canada

- Website / Social Media:
https://filswan.com
https://www.nbfspool.com
https://t.me/NebulaAICommunity (1000+ users)
wechat group :Nebula AI 区块链， (over 1000 users)

- On-chain Address to be Notarized:
- Region of Operation: [North America, South America, Europe, Africa, Greater China, Asia-GCN, Oceania]
North America 

- Use case(s) to be supported: [Please select from [here](/notaries/templates/README.md#definitions)]
Professional Services 
Web 3.0 / Decentralized Applications     
Web 2.0 Applications     
User Content 
Scientific Data      
Media & Entertainment    
- DataCap Requested: 100 TiB

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Founded at 2017 Nebula AI  is aiming at building a global decentralized computing system cross continent. 
- December 2017, we create a write paper to demonstrate the usage of  IPFS/Filcoin as the storage layer for DAPP.
- https://www.fxempire.com/education/article/nebula-ai-nbai-the-convergence-of-ai-and-blockchain-513273
```
> Decentralized encrypted data storage
> With NBAI no central organization has access to all your data. That is obtained by the combined usage of IPFS, multiple - private keys for access control and data verification which makes sure the data cannot be tampered with. This way you can be sure that your data won’t be misused or even accessed by who shouldn’t have access to it.
```
- 2018 Nebula AI whitepaper about IPFS/Filecoin published on IEEE Access, 29, 2019. Digital Object Identifier 10.1109/ACCESS.2018.2890507

- April 2020  participated testnet of filecoin project, we build the brand NBFS for filecoin project which finally incorporated as a sub-company called NBFS inc, The major business for NBFS is Filecoin mining and decentralized storage service. 

NBFS also builds Filswan project to help the Fil plus, Filecoin deal market, Filswan team has 8 people dedicated the platform over the last year. The platform has sent over 15000 deals and storge over 300 TB data on NBFS miners node.

We participate daily discussion on slack (more than 35k messages)，wechat group( more than 10k messages) and more than 20 GitHub issues

* https://github.com/filecoin-project/lotus/issues/5245
* https://github.com/filecoin-project/lotus/issues/4370
* https://github.com/filecoin-project/lotus/issues/6027
* https://github.com/filecoin-project/lotus/issues/5821
* https://github.com/filecoin-project/lotus/issues/2314
* https://github.com/filecoin-project/slingshot/issues/434
* https://github.com/filecoin-project/neptune/issues/42
* https://github.com/filecoin-project/notary-governance/issues/78
* https://github.com/filecoin-project/lotus/issues/3902
* https://github.com/filecoin-project/lotus/issues/6237

- Jan – May 2021, we were selected as minerX fellow, participated in early stage testing , release testing, deal management, and help improve louts and other ecosystem projects. It took several hours per week to participant all the activities.

Charels Cao, CEO of NBFS, is elected as ambassador of Filecoin, and help all the new comers and community as well as spread all the information and news to different groups on twitter and other platform.

Github handles: https://github.com/filswan
NBFS Canada is the biggest mining node in NA region, has more than 1PB sealed power with over 300 Tb data sealed on the 8 nodes.
Miner ids: f019104, f02401,f01276,f0165400,f0145874,f0157535
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
We have 15000 Fil currently at stake, 15,000 locked as collateral
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

```
- Twice community champion Winner
- Actively participating and helping the Filecoin miner community (more than 13k messages on slack)
- Participating to  SR1 / SR2 Orbital burn / Slingshot 1/2.1/2.2/2.3
- Filecoin MinerX Fellow.
- Filecoin Global Ambassador
- [Filecoin Devgrant: Petabyte-Scale Data Transport Tool ](https://github.com/filecoin-project/devgrants/pull/216/files)
- Filecoin Devgrant application: S3/Filecoin integration
- RETMKT Builders - NBFS Filecoin Swan Platform 
- Weekly Meeting with Protocol Lab
Participated in many activities invited by Filecoin Team
- Lecture on Mining Technology, 4th Sep 2020
- Made a speech in the Slingshot Phase 1: Closing Ceremony, 28th Oct 202
- Invited to “Filecoin as a Decentralized substrate for computing with Juan Benet”, 28th OCT 2020
- 2021 new year community meetup “Introduction of Swan market platform”,
- 2021 April, invited to RETMKT Builders - NBFS Filecoin Swan Platform 
- 2021 May, Fil plus community show case
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
We participated in lots of bug testing as miner X members.
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

```
Nebula AI inc, is registered 2017 in Montreal, Canada.
We have 12 full time employees, 10 of them located in Canada, 2 of them located in China.
- 2018 Nebula AI whitepaper about IPFS/Filecoin published on IEEE Access, 29, 2019. Digital Object Identifier 10.1109/ACCESS.2018.2890507
- The Natural Science and Engineering Research Council of Canada (NSERC) special fund supports research on the direction of video coding.
- The Ministry of Science and Technology of China and the Quebec government cooperate on the edge computing project, with millions of government funding support
- Natural Science Foundation of Canada (NSERC) Blockchain to AI Cloud Computing Research Grant
- Canadian Information Technology and Integrated Systems Mathematical Organization (Mitacs) AI medical identification project grants
- CENGN (Canadian Center of Excellence for Next Generation Networks) Research Support Project
- 2020 World Internet Conference Wuzhen Summit Prize
- Microsoft Entrepreneurship Support Program (BizSpark) Support
- HP Enterprise Supplier Partner
- Dell Enterprise Supplier Partner
- ASUS Enterprise Service Partner
- Amazon Enterprise Partner 
[NVIDIA Canadian Cloud Computing Supplier](https://www.nvidia.com/en-us/about-nvidia/partners/partner-locator)
- AWS Premier Partner  
- AWS Innovation funding
- white paper referance by 
- https://www.igi-global.com/chapter/integrating-blockchain-with-ai/265391
- https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8598784
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

```
https://nbfspool.com
https://twitter.com/nbfscanada
Medium: https://medium.com/nebula-ai 
Facebook https://www.facebook.com/NebulaAI/
YouTube: https://www.youtube.com/channel/UCWltsUAyiser4-_eLLGmpdg
LinkedIn: https://www.linkedin.com/company/nebula-ai
WeChat Official Account: NebulaAI区块链
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.cengn.ca/nebula-ai
https://www.glassdoor.ca/Overview/Working-at-Nebula-AI-EI_IE2198238.11,20.htm
https://www.nserc-crsng.gc.ca/ase-oro/Details-Detailles_eng.asp?id=650691
https://www.chainnews.com/articles/888159767969.htm
https://xwayca.wordpress.com/2018/10/02/nebula-ai-orion
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Scientific Data (AI training, geological data, autonomous driving) 
Media & Entertainment (video & music)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.

| Factors  | Details | Rating Weight |
| :---         |     :---      |          :--- |
| Ecosystem Value | The data should be meaningful for the Filecoin ecosystem. e.g. some data record random or meaningless data will be rejected.| 40% |
| Technology | Client should show they have enough technology to manage the deal transfer and result tracking. Data used in slingshot is not qualified since participants already get the reward from competition.  | 20% |
| Past History | Client past successfully complete the data quota will be a plus, other wise it will be decrease the allocation | 20% |
| Legal | The content upload should have no copywrite issue and qualified the local law and governance. | 20% |
```
The purpose of allocating the DataCap is to make sure clients use these DataCap in a manner fit the ecosystem needs.
For new applied clients, we need background check about his/her information, usually individual will be granted less Datacap than organizations.
We are building an internal tool about the reputation system, clients have a score from 1 to 10, factors be calculated will include but not limited to: contribution to the community, working terms inside the system, community reputation, GitHub activity, past allocation credit history, deal success rate, miner behavior (if they have miners), decentralization of the storage, duplications of the copies, compliance with local regulations, data quality, data cited by users.

With Filswan.com we have built a system shows the clients task sending history, the miners paster deal reputation history, you can check a sample here: https://www.filswan.com/#/miner/f010479

```

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Yes. With all the applications we asked a tracking record from submission – review-approval -deal tracking. The approval needs two sign officers’ approval, and the system tracking record need to be in place. 

Individual DataCap start from 1GB up to maximum 5TB, organizations start from 10GB to maximum 10TB. They can ask for a 10% incremental of next application after used current Datacap, but a cool time of 7 days is mandatory between two allocation requests. 

Client allocation can also be decreased or cancelled if they violated the terms , policy can conduct of Filecoin community.

Client can apply for arbitrage if they believe any process or conclusion in incorrect.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Mutisig wallet will be used for signing the DataCap under C-level member’s control
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 

In the early stage, all clients are required for an onboarding process to be qualified. Firstly, I need to collect information including:  
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information. 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name.
 - street address (P.O. box number is not acceptable). 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence. 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

 With these provide, an interview and data source checking process need to go through. After that, an agreement should be signed for the next step - gradually allocate datacap and let the client gather more credit. 
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
Introduction of yourself/ your organization (with links)
Use case
Location of the client
Max DataCap Allocation
Filecoin sign address
Data copyright and other legal concerns.
Specific requirement of miners and storage service
For-profit or not
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Periodical inspection and audit of DataCap usage

Scan tools for monitoring verified deals with miners, content scanning tools for violation of local law and policies, usage of the data, verified data distribution. https://github.com/nebulaai/trusted-miner
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Yes, I plan on keeping records of our allocation decisions via a GitHub repo. We will also build a open source project for auditing purpose.
- The allocation plan and criteria is public accessible  
- Each approval and allocation is on GitHub
- All the conversation of datacap interview with client is recorded under the awareness with the client and saved in secure place.
- Client submission related documents are securely saved for future auditing.
- Client data quatation usage is online traceable.  All the datacap alocated will be saved in database for future analysis and auditing. 
We are open to any audit requests.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes,both
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
0
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
0
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
No
```

**Comment by dkkapur** [comment]
Edited formatting slightly for readability

**Comment by dkkapur** [comment]
Hi @flyworker  - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/137wiaDvhfB_jM4BQ7zN6hFZ2Qv-zlre6rySpTPoYIsY/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.4.

**Comment by flyworker** [comment]
- Bug tracking does not qualify. Do you have other examples?
No

- Filswan accounts do not qualify as an 'individual' - do you have other examples?
No, we applied as a company so we do not have individual account.

- Using Canada + China (where most of your company appears to be based) to inform your score here
We do not have company in China at the moment.

- Great to see you are building an internal tool about the reputation system; looking forward to learning more! Will this be open sourced?
Yes, it will be open sourced.

**Comment by flyworker** [comment]
Another question, 
In the Organization Reputation part, I noticed lots of organization in China is defined as 

> Reputable entities in Filecoin-adjacent communities with substantially adopted services / products (e.g. Textile, Supranational, Pinata, Infura)

Why filswan has been invited to 10+ Filecoin introduction videos and added to community projects, also part of the data retrieval project, used by minerX memebers , granted devgrant, why it cannot be coincided as _Reputable entities in Filecoin-adjacent communities with substantially adopted service_?

**Comment by dkkapur** [comment]
@flyworker - thanks for sharing your responses!

- Individual reputation typically measures specifically accounts that the Notary has access to and can post about with relation to Filecoin, Fil+, or other activities in the ecosystem. In this case, only your LinkedIn qualifies as > 500 followers. However, even if you were to have Rex post on your behalf, the score on this criteria would still be at a 1, and the section is graded at a Max() so the final output would be unchanged. As a result, I am leaving this at a 0 since it should not impact final scoring in any way.
- Re Filswan - as I understand it, the focus is still very much in the Filecoin community. The criteria specifically grades for presence in adjacent ecosystems, i.e., IPFS, NEAR, other protocols or large Web3 projects. This is why this criteria continues to be at a 1 for you. 
- Additionally, Bookkeeping has been adjusted to a 3. This does not impact your score, but was done in an effort to be more consistent across scoring all applications. When your tooling for Bookkeeping is available/live, then this will be scored at a 5.

The final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 1
- Unrounded score: 1.4

Link to rubric:
https://docs.google.com/spreadsheets/d/137wiaDvhfB_jM4BQ7zN6hFZ2Qv-zlre6rySpTPoYIsY/edit?usp=sharing

**Comment by dkkapur** [comment]
@flyworker - based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of 10 TiB (qualified for 10 TiB based on rubric scoring). In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm that the region of operation for client applications you will focus on is [North America]

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

> * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

> * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

> * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**Comment by dkkapur** [comment]
@flyworker - awaiting your response to the above before proceeding with next steps with the RKH. Thanks!

**Comment by flyworker** [comment]
Sorry for the late reply, please check my answer below:


1.     Please confirm that the region of operation for client applications you will focus on is [North America]
**Yes,  region of operation for client applications I will focus on is [North America]**

2.      Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

- Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship
**Agreed**
-  Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.
**Agreed**
-  Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.
**Agreed**
- No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.
**Agreed**

- Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.
**Agreed**

- Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.
**Agreed**
3.     Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

**f02401,f02387,f019104,f01276,f0157535,f0165400,f0145874,f0447183**

4.     Please affirm that you will abide by the allocation / client due diligence plan you laid out above.
**Agreed**

5.     (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

TBD

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Datacap Allocated
> 10TiB

**Comment by dkkapur** [comment]
This went through correctly
