### ISSUE TITLE
Notary Application: IPFSFORCE-Steven Li

### ISSUE THREAD

**Issue by steven004** [filecoin-project/notary-governance#158]
# Notary Application
***Note: Please only submit PRs for proposed edits to this form. To apply as a Notary, please file an [issue](https://github.com/filecoin-project/notary-governance/issues/new?assignees=&labels=request&template=notary-application.md&title=).***

To apply as a notary, please fill out the following form. 

## Core Information
- Name: `Steven Li`
- (Optional) Affiliated Organization: `IPFS Force` 
- Website / Social Media: `@Steven on Filecoin Project Slack, @Steven004_Li on Twitter`
- On-chain Address(es) to be Notarized: `f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna`
- Region of Operation: `Greater China`
- Use case(s) to be supported: `User Content, Scientific Data, Media & Entertainment`
- DataCap Requested: `500TiB`

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

```
As an individual, I has been deeply cultivating distributed storage for over 10 years in multinational and startup companies.

I was the head of Cisco (China) Cloud Object Storage and the core developer of China's first-generation security routers. With my knowledge and experience in networking, security and storage, I fell perfectly align with Filecoin's vision as a DSN infrastructure for humanity information storage.

As an advocate and practitioner of distributed storage and Web 3.0, I started focusing on IPFS study and development since 2017. Early 2018, I joined in Filecoin Community and work as Co-Founder & CTO of IPFS Force. Since then, all of my working time is on IPFS and Filecoin ecosystem buildup.

At present, I am committed to the design and ecological construction of key modules such as Filecoin's consensus algorithm, proof of replication, economic model and mining cluster architecture.
```
More information:
- GitHub handles: steven004
- IPFS Force Miner ID: f02438, f02425, f02731, f020604, f02726, f03266, f03287, f02610, f02721
- Slack: @Steven
- Participating to DevNet/ TestNet/ HackFS/ SR1/ SR2/ Slingshot 1(as reviewer)/Filecoin Community activities as one of top testers and miners
- Stewardship of Filecoin Implementation: Venus(go-fliecoin)

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Total stake: 5.25MM FIL with Miner ID f02438, f02425, f02731, f020604, f02726, f03266, f03287, f02610, f02721, f0144547, f0218283, f0397561 as collateral(viewed on May 24th, 2021)
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

```
As an Individual, I have been working as an IPFS/Filecoin ecosystem advocate and builder:
- Weekly IPFS/Filecoin/Web3 technical or marketing articles (over 100 articles published)
- Speaker of IPFS/Filecoin/Web3 conferences
- Organizer and lecture of Protocol School Shanghai Chapter
- Contributor of Filecoin protocol and code development via issues/PRs commitments

As the technical lead and co-founder of IPFS-Force community, led and helped the team: 
- Established and lead IPFS/Filecoin activities in China: Force Open Day(#148 on Nov. 17th 2020), Protocol School Shanghai & Chengdu, EOS & IPFS HackFS
- Published IPFS/Filecoin related reports and articles: whitepaper translation, 1-67 Filecoin Weekly Report, 1-108 IPFS Weekly Report, IPFS/Filecoin Ecological Report, SpaceRace Report, Filecoin Mining Guidelines (1-3 series), 100 Questions about IPFS/Filecoin and other reports and articles wrote by IPFS-Force researchers and analyzers

Recently Filecoin Community activities
- Filecoin Open Day, Oct. 26th 2020
- Filecoin Core Devs Biweekly #5, https://www.youtube.com/watch?v=jCJFhhR0gW8&t=2495s
- How We Won Space Race, Oct. 21th 2020, https://www.youtube.com/watch?v=1QVa48Eela8
- Filecoin Protocol Implementation: What's next?, Oct. 21th 2020, https://www.youtube.com/watch?v=JmvQ0F1qtYQ
- Filecoin Chain Explorers, Oct. 21th 2020, https://www.youtube.com/watch?v=f2sk2WqrIjs
- Space Race Miner Show & Tell, Spe. 4th 2020, https://www.youtube.com/watch?v=pHi85ZNs3AY
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
Security is the first priority and the most important factor of a chain. I, as the key engineer of the China's first generation of secure router, paid a lot of attention on security of the system, and contributed to Filecoin via publicly submitted issues, or privately discussion due to the sensibility of some security issue.

Some of the issues submitted related to security: 
- 
- https://github.com/filecoin-project/specs/issues/559
- https://github.com/filecoin-project/venus/issues/3308 
- https://github.com/filecoin-project/venus/issues/3349
- https://github.com/filecoin-project/venus/issues/3523

There are some discussion in slack private channel or via email too, e.g. 
- Nondeterministic signature of round winner calculation
- Owner change proposal from security prospective
- determiistic winner of big miners, to drive the winning algorithm change
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
IPFS Force started in May 2017 is a non-profit decentralization storage and web3 community, based in Shanghai, China.

IPFS Force community is sponsered by Shanghai Kunyao Network S&T Co., Ltd. since Kunyao was set up in July 2018 as a company. 

IPFS Force regularly conduct meetups and events, and support the industry to develop application, Filecoin mining, and provide services.

Currently, IPFS Force has near 100 core members, and hundreds of thousands of participants of hosted events via on-site or on-line events.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: ipfser.org
Twitter: https://twitter.com/force_ipfs
Weibo: https://weibo.com/p/1006066336693097/home?from=page_100606&mod=TAB#place
WeChat Oifficial Account: IPFS原力区

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.8btc.com/media/634903
https://www.jinse.com/lives/200205.html
https://36kr.com/newsflashes/973370131575041
https://36kr.com/newsflashes/669046320289795
https://news.huoxing24.com/flash/20200825220511648353.html
https://news.huoxing24.com/flash/20200706192231201068.html
https://news.huoxing24.com/flash/20200706191320331822.html
https://www.jinse.com/lives/200205.html
https://www.jinse.com/lives/175039.html

```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Scientific Data(AI training, geological data, autonomous driving) 
Media & Entertainment(video & music)
User Content(personal user storage)

```

# Allocation Plan Template
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.

> The purpose of allocating the DataCap is to make sure clients use these DataCap in the right way.
>
> For new clients, there will be offline investigation and discussion regarding who they are, what they will use filecoin as a storage to save, and how to do it, based on that, I would have the first judgement to qualify or not as verified clients.
> 
> For qualified clients, my allocation strategy emphasizes historical reputation and also the plan for new-required data investigation.
We plan to allocate DataCap with small incremental amount(<10%) and build a reputation mechanism.
> Each allocation will be considered as an assessment of clients reputations with score accumulation and corresponding trust degree.
For example, if a client applies for DataCaps, provides valid data and spends these DataCap responsibly, his reputation credit will increase. With higher credit, Clients can apply for more DataCaps in the future.
> We are also willing to use Filecoin Plus Registry to make all allocation in public.

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap? 

> Referring to the Filecoin Plus Client Rubric & Allocation Draft, I edited a draft of credit and scoring mechanism of clients and communities or individuals behind, with the limitation of minimum 1GB and maximum 100TB DataCap. See the details from:  https://drive.google.com/file/d/1Zy7TLZN1dEqYNWubgMUdnog_c885-1KB/view?usp=sharing
>
> At this moment, I think it’s good time to attract more external data providers to come into the Filecoin Network, become verified clients and store useful data. For this reason, my audit mechanism will evaluate the value of data as well. Clients with high-value data can have priority of allocation and larger amount of DataCap. The initial rules are list in the table: https://drive.google.com/file/d/13w0H3DMrKMeXFP4x1COFWx03Ohhhk0Ap/view?usp=sharing. 
Basically, the more value the data can bring to the network, the more can be be granted. 
> 
> Besides, there will also be a 10% incremental allocation strategy. For example, if clients(applied DataCap from me) provide valid data without improperly over-allocating as they promised, and all of checked data are qualified, when the next time they apply for DataCap allocation from me, their allocation could have maximum 10% increase.

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

> The offline wallet had been developed and verified for the accounts associated with the Datacap allocation.
And, multisig wallet is to be used when there are more clients coming in.

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 

In the early stage, all clients has to go through a strict process to be qualified. Firstly, I need to collect information including:  
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information; 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name;
 - date of birth; 
 - street address (P.O. box number is not acceptable); 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

 With these provide, an interview and data source checking process need to go through. After that, an agreement should be signed for the next step - gradually allocate datacap and let the client gather more credit. 

```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
1. Introduction of yourself/ your organization(with links)
2. Use case
3. Location
4. Max DataCap Allocation
5. Filecoin address
6. Miners you intend to allocate DataCap with allocation proportion
7. Specific requirement of miners and storage service
8. For-profit or not

```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Periodical inspection and audit of DataCap usage
Use incentive mechanism: encourage clients to report unfair allocation
We will also develop a tool to randomly check all the clients' verified deals to make sure they are following the protocol.
 
Once our team complete the development of audit tool, we are happy to make it open sourcing and provide technical specifications or architecture docs, so other notaries can use it. This toll will require clients to post deal transaction in public, and Filecoin Community can audit data and storage deals once again.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Yes, all allocation decisions will be guided by the rubric publicly on Github.  
Since all interactions are intended to occur publically, most of the allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly, e.g. the Github repo.
If convincing justifications can’t be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions. 

```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
In pubblic(tentatively on GitHub) in order to be supervised by Filecoin Community
 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
YES
https://github.com/filecoin-project/notary-governance/issues/14

```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
51TiB

```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None

```

**Comment by dkkapur** [comment]
Previous applications:
- https://github.com/filecoin-project/notary-governance/issues/14

Allocation track record from last round:
- ~51 TiB allocated in past round, 13 client applications in repo, 16 verified clients in dashboard currently
- list of client applications approved: https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues?q=is%3Aissue+label%3Astate%3AGranted+is%3Aclosed+assignee%3Asteven004

Client applications and usage of datacap: 
![image](https://user-images.githubusercontent.com/2343218/120254377-8c261900-c23e-11eb-9ad7-1062e49b2eeb.png)

DataCap received by miner IDs:
| Notary Name | Miner ID | DataCap received in GiB | % of Notary's DataCap Grant |
|-------------|----------|-------------------------|-----------------------------|
| IPFSForce   | f01247   | 1.000000328             | 0.00%                       |
| IPFSForce   | f09848   | 912.0002991             | 1.75%                       |
| IPFSForce   | f0142721 | 544.0001784             | 1.04%                       |
| IPFSForce   | f023467  | 801.1252628             | 1.53%                       |
| IPFSForce   | f0406703 | 192.000063              | 0.37%                       |
| IPFSForce   | f0135078 | 320.000105              | 0.61%                       |
| IPFSForce   | f01278   | 96.00003149             | 0.18%                       |
| IPFSForce   | f0134518 | 64.00002099             | 0.12%                       |
| IPFSForce   | f019551  | 1.000000328             | 0.00%                       |
| IPFSForce   | f08399   | 256.000084              | 0.49%                       |
| IPFSForce   | f0442383 | 284.0000932             | 0.54%                       |
| IPFSForce   | f02576   | 480.0001574             | 0.92%                       |
| IPFSForce   | f0134516 | 36.00001181             | 0.07%                       |
| IPFSForce   | f0116445 | 1280.00042              | 2.45%                       |
| IPFSForce   | f0118330 | 1280.00042              | 2.45%                       |
| IPFSForce   | f0406322 | 192.000063              | 0.37%                       |
| IPFSForce   | f0116436 | 1280.00042              | 2.45%                       |
| IPFSForce   | f0149132 | 1175.000385             | 2.25%                       |
| IPFSForce   | f01240   | 208.0000682             | 0.40%                       |
| IPFSForce   | f0142723 | 1248.004316             | 2.39%                       |
| IPFSForce   | f022142  | 160.0000525             | 0.31%                       |
| IPFSForce   | f0118317 | 1280.00042              | 2.45%                       |

**Comment by dkkapur** [comment]
Hi @steven004   - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/15Sl7e5p74cBmftx27U0q7QQYPxUIUHqTLGhgRM0w1qs/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days. Specifically - we need to see the audit trail for the allocations that are not accounted for in the GitHub based client applications. This information is being pulled from here https://filplus.d.interplanetary.one/notaries, which is a recently published dashboard. If there are issues with the data being reported here, please do share as well so we can correct this immediately. Thank you!

Your initial score is: 2.7.

**Comment by steven004** [comment]
Hey @dkkapur , 
> Allocation Strategy - Would appreciate any details on the reputation system for clients that could be built here - will it be public? Can this info be shared with other notaries? How will you calculate client reputation? 

I randomly check clients' data storing in Filecoin network, and evaluate how the datacap is used at the same time. In addition, I really value the clients' tooling for retrieve data from Filecoin network for their users' access. In addition, I am doing  phone interview to research some detailed information from clients, including their usage and perspective of DataCap, their next plan on the FIL+ project, what kind of data they stored with these allocations, and their suggestions of the whole application process, etc.
Non-private and non-sensitive information will be public in the GitHub client onboarding repo, and a reputation record will be built referring to my credit and scoring mechanism of clients. I’ll periodically share these records with other notaries. 

> Bookkeeping Plan - Tooling to be built is referred to - would be great if you could share any details on how you will be checking client usage of data cap (i.e., will you be making retrievals on stored data to check it?)

Filplus.info is a useful tool to check the usage of DataCap and verified deal flow. After call-back, I’ll retrieve stored data to verify whether clients stored data as they mentioned. At the same time, I really value the clients' services for their users, and how the data stored in Filecoin can benefit to others. 

> Past Allocation - Only 13 client applications seem to be in GitHub client onboarding repo. According to your bookkeeping plan, all applications should be tracked in GitHub. Do you have any more information you can share on those allocations? This scoring is contingent on this.

All my granted datacap for applications are from GitHub client onboarding repo. There is no one is from another channel.  Please let me know if you have any question on any allocation. I was cautious and careful on datacap granting, since I really want this will not be abused by storing garbage. Once some clients' credit is built up, or they have better tooling or mature application, there will be faster allocation rate later.

**Comment by dkkapur** [comment]
Audit pass on the applications - only found 1 issue that needs additional explanation (the others are issues in the data tracking, and not your fault):
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/388 shows up on the dashboard. I see the message on chain where you gave this client DataCap: https://filfox.info/en/message/bafy2bzaceaet3twyfr5woxprfzr3i44e3gmj7wvq7ptrmzdaijn3hw7q2266k?block=bafy2bzacedzodxp6ptniymgkpf377evjncmtqib5r24pkfclsobdde3twruys. Do you have any records of who this client is? Additionally, they have spent all their DataCap making deals with a single miner ID: https://filplus.d.interplanetary.one/clients/f0511870.

**Comment by dkkapur** [comment]
The final scores for this election cycle are:
- Rounded Final Allocation Amount: 3
- Unrounded score: 2.7

Link to rubric: 
https://docs.google.com/spreadsheets/d/15Sl7e5p74cBmftx27U0q7QQYPxUIUHqTLGhgRM0w1qs/edit?usp=sharing

However - your scoring confirmation/election is blocked until we can resolve the above mentioned gap in the allocation tracking / auditing.

**Comment by steven004** [comment]
> Audit pass on the applications - only found 1 issue that needs additional explanation (the others are issues in the data tracking, and not your fault).
> 
> [filecoin-project/filecoin-plus-client-onboarding#388](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/388) shows up on the dashboard. I see the message on chain where you gave this client DataCap: https://filfox.info/en/message/bafy2bzaceaet3twyfr5woxprfzr3i44e3gmj7wvq7ptrmzdaijn3hw7q2266k?block=bafy2bzacedzodxp6ptniymgkpf377evjncmtqib5r24pkfclsobdde3twruys.
> 
> https://filplus.info/#/client?client_name=%E6%88%90%E9%83%BD%E5%8D%8E%E6%A0%96%E4%BA%91%E7%A7%91%E6%8A%80%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8
> 
> Do you have any records of who this client is?

This client is 成都华栖云科技有限公司 (see: https://www.chinamcloud.com/) . The application they submitted should be [here](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/388), however, now I just can get 404. I do not know why this happened. I remember there is another application issue was deleted too, and I mentioned that to you @dkkapur . Sorry I do not make a copy of the application issue, and never throught which can be gone. 

I remember this client requested 5TB, and I granted 2TB for a start, and, I am willing to check how the data is used and see if there will be more datacap to be granted next. 

> 
> Additionally, they have spent all their DataCap making deals with a single miner ID: https://filplus.d.interplanetary.one/clients/f0511870.

The client will not gain much credit with this, as per the rules I set. That's also why I grant a small amount of datacap for the first time. 


Please let me know what else I should do or provide.

**Comment by cdhua** [comment]
This is 成都华栖云科技有限公司.
We would like to say that the explorer(https://filplus.d.interplanetary.one/clients/f0511870) have lost some data.
Our address is f16vsdjjjz6zqxmhrdazs6qp33hk6iu4vnbs3o64i. Our DataCap is stored in the two nodes, f0142721 and f0142723.
You can search it in https://www.filscout.com/zh/market/storage and https://filfox.info/en/deal.
Our plan is to store DataCap on 4 or 5 nodes, but it is only stored in two nodes for the policy control of some regions.
I hope you can understand and I'm so sorry for any inconvenience caused.

**Comment by steven004** [comment]
@cdhua, thanks for your capturing this and the clarification.

**Comment by dkkapur** [comment]
@cdhua thanks for providing the info! 
- I will follow up on the data dashboard issue
- Can you help us understand why you deleted your client application from the repo?

Thanks @steven004 - I think you are cleared of any issues for this round

**Comment by dkkapur** [comment]
@steven004 - based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of 500 TiB. In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm that the region of operation for client applications you will focus on is [Greater China Region]

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

> * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

> * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

> * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**Comment by steven004** [comment]
> 1. Please confirm that the region of operation for client applications you will focus on is [Greater China Region]

ACK

> 2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.)
> 
> > * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

ACK

> 
> > * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

ACK. Notaries should also be Filecoin network and ecosystem advocate and supporters.

> 
> > * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

ACK

> 
> > * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

ACK

> 
> > * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

ACK

> 
> > * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

ACK

> 
> 3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

We (IPFSForce) are managing a pool for our customers, and all the addresses under our control, including owner, workers and controllers. These addresses might be changed for security reason time by time, but you can always get all the addresses from the chain via miner ID. The relevant miner IDs are: `f02438, f02425, f02731, f020604, f02726, f03266, f03287, f02610, f02721, f0144547, f0218283, f0397561`.

Other addresses not relevant to above, this can be updated from time to time too. 
`f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna`
`f1x64picxdodkqpbyrsohztkzs6aa5xovjmp6jzma`
`f3wylwd6pclppme4qmbgwled5xpsbgwgqbn2alxa7yahg2gnbfkipsdv6m764xm5coizujmwdmkxeugplmorha`
`f3r47fkdzfmtex5ic3jnwlzc7bkpbj7s4d6limyt4f57t3cuqq5nuvhvwv2cu2a6iga2s64vjqcxjqiezyjooq`

> 4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

ACK 

> 5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

I will update this in this thread, when it's ready, expected within own week.

**Comment by dkkapur** [comment]
@steven004 - going to attempt topping up the same address as before. Let me know if this is not good!

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna
#### Datacap Allocated
> 500TiB

**Comment by steven004** [comment]
@dkkapur ， It's fine to top up the same address. Thanks.

**Comment by dkkapur** [comment]
This went through correctly!

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
[bafy2bzaceaq6dqny3yrbowng5u5uh4ehwybhjbenbbnjtxarslzce24v7sbti](https://filfox.info/en/message/bafy2bzaceaq6dqny3yrbowng5u5uh4ehwybhjbenbbnjtxarslzce24v7sbti?t=4)
