### ISSUE TITLE
Notary Application  ：Firefly 

### ISSUE THREAD

**Issue by Firefly2020-cloud** [filecoin-project/notary-governance#16]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
- Name:Nickole zhu
- (Optional) Affiliated Organization: Firefly 
- Website / Social Media: http://fireflyblock.com
- On-chain Address(es) to be Notarized: f3rmhlmqfaph6czwiqwlg3kfjgejugt5thcviowlmt3l42464q25ptk3znphuuiwrdbyumun3ui7q2gut7v2da
- Region of Operation:  Greater China
- Use case(s) to be supported: [Web 3.0 / Decentralized Applications, Web 2.0 Applications, User Content, Scientific Data, Media & Entertainment, Other]
- DataCap Requested: 50TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Please answer here.As an individual, I have worked as a crypto miner for over 5 years. 
I’ve been a part of the Filecoin community since 2017 and founded Firefly  in 2018. 
As an organization, Firefly is a leading service provider committed to comprehensive Filecoin mining solutions in a cost-effective way. 
We have built quite an extensive relationship with the Filecoin community since its initial launch back in 2017, 
and as a result, have sustained countless contributions to the overall network. 

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Please answer here.SR1——The effective storage reaches 2.8PiB, and the reward is 20,000 FIL
After the main network is online, continue to increase the computing power to the current 3.7 PiB
Contact industry users and actively promote effective data uplink

```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Please answer here.Since joining the community, I have paid close attention to official information, hoping to participate more in various official activities.


```
### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
Please answer here. Please check with @Keren  who will be able to substantiate our contributions. 

```
### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Please answer here.Firefly I is a private company founded on July 5, 2018, in HangZhou, China. 
The company is for-profit, and its country of registration is China. 
At the moment, we have over 100 employees working at the HangZhou and Shenzhen headquarters since its inception 2 years ago. 

```
Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Please answer here.https://twitter.com/fireflyblock1
http://www.fireflyblock.com/
www.fireflypool.com
https://weibo.com/7329627144/profile?
https://baike.baidu.com
https://www.chainnews.com/u/095136341312.htm

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Please answer here.https://news.163.com/20/0403/17/F9A9TMPC00019OH3.html

```
### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Please answer here.I plan to support multiple use cases; the percentage will be determined by my knowledge and usage expectation, 
which may vary depending on the variable circumstances of each scenario and different regions. 
-    60% - user content (personal user storage) 
-   25 % - scientific datasets (AI training, geological data, autonomous driving) 
-    15% - media & entertainment (video & music)

```
# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
Please answer here.The acquired valid data is preferentially used for personal data storage，Use industry resources, contact potential users (enterprises, governments), and broaden the use scenarios of filecoin network

```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Please answer here. This is an ecological environment that we need to guard together, and it needs commitment and common progress

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Please answer here.In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 
For individual clients, online identity will be verified by both account age and account activity perspectives, and this will serve to prove that they are valid users and not bots 
Third-party tools like twitteraudit may also be used to verify online identities. 
For organizational clients, application organizations should be easy to verify through the appearance of their application. 
The developing applications may require further stringent investigation; 
this is to ensure that the application is valid and enclosed with meaningful content, rather than the shell of a malicious client. 
Large public datasets hosted by organizational clients are easy to verify because the data should be unencrypted and accessible to anyone. 

```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
Please answer here.In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 
For individual clients, online identity will be verified by both account age and account activity perspectives, and this will serve to prove that they are valid users and not bots 
Third-party tools like twitteraudit may also be used to verify online identities. 
For organizational clients, application organizations should be easy to verify through the appearance of their application. 
The developing applications may require further stringent investigation; 
this is to ensure that the application is valid and enclosed with meaningful content, rather than the shell of a malicious client. 
Large public datasets hosted by organizational clients are easy to verify because the data should be unencrypted and accessible to anyone. 

```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
Please answer here. 1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle) 
2. What is your use case for the DataCap being requested? 
3. What is the Filecoin address you would like me to allocate the DataCap? 
4. How much DataCap would you like to request? 
For organizational clients: 
5. What is the name, nature, registration country, time since inception, and named officers of your organization? Please link to relevant websites. 
6. In which region do you intend to use the DataCap? If you intend to use the DataCap in multiple regions, please specify. 
7. How many miners do you plan on allocating a DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
8. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 

```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Please answer here. 1) the private key adopts hardware key, which is kept by a special person and a responsibility system is established
2) Increase software implementation and limit the use range of private keys
3) Establish a risk control system to limit the application account number, IP and capacity
4) Monitor datacap application in real time and establish post-event alarm processing
5) conduct self-inspection, and regularly issue data distribution reports
6) Special personnel track the community situation and eliminate illegal use scenarios


```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Please answer here.Yes, all allocation decisions will be guided by the rubric publicly on Github. So are all communications. 
Since all interactions are intended to occur publically, most of the allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly in the Github repo first. 

```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Please answer here. In pubblic(tentatively on GitHub) in order to be supervised by Filecoin Community
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Please answer here.None. 

```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
Please answer here. None. 

```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
Please answer here.None.

**Comment by jnthnvctr** [comment]
Hi @Firefly2020-cloud , we've taken a pass to score your application. See Column H for comments on areas where your application could be improved! https://docs.google.com/spreadsheets/d/13lmNe15WB4cbGeBaFjtpr99oU73_Gc37qvdU-8xAKjw/edit?usp=sharing

Please also be aware that this draft PR includes rubric changes which might affect your score: https://github.com/filecoin-project/notary-governance/pull/36

**Comment by Firefly2020-cloud** [comment]
Please authorize my email access, thank you
zhuyanni0firefly@gmail.com

**Comment by Firefly2020-cloud** [comment]
I have checked the content of the application. How do I synchronize the supplementary information to you?

**Comment by jnthnvctr** [comment]
Please edit the original issue!

**Comment by jnthnvctr** [comment]
Based on the above application, we've provided a score here: https://docs.google.com/spreadsheets/d/1Bybfz2SUBMGDU584n0ttCLUcrnbbDgOiMIdaLwYu_JE/edit?usp=sharing

Eligibility score: 1
Unrounded score: 1.3
