### ISSUE TITLE
Notary Application-TianjiStudio

### ISSUE THREAD

**Issue by IPFS-grandhelmsman** [filecoin-project/notary-governance#165]
# Notary Application-TianjiStudio

To apply as a notary, please fill out the following form.

## Core Information

- Name: Bailey-li
- Affiliated Organization: TianjiStudio
- Website / Social Media: [https://dapponline.io/ ]( https://tjwallet.net)
- On-chain Address to be Notarized: [f3qggpnbf4r5ssj7l2uoimvusvo3nedlsfe7ihhkkeecjwn4e7lxgavxezeills5resomikiljtj53up7nmnaa]
- Region of Operation: [Greater China]
- Use case(s) to be supported: [Web 3.0 / Decentralized Applications, Web 2.0 Applications, User Content, Scientific Data, Media & Entertainment, Other]
- DataCap Requested: 100TiB

*Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!*

### Time Commitment

Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

```
Participated in Trusted Setup Ceremony Phase 1 https://github.com/arielgabizon/perpetualpowersoftau/blob/master/README.md. 

Participate in the first phase of the testnet that started in December 2019, ID: t019125, and the final storage capacity exceeds 1PiB. 

PB-scale Miner Testing,E-mail submitted the relevant test plan,the email was sent to the Filecoin team, and Filecoin team members like @why @keren knew about it https://github.com/filecoin-project/devgrants/blob/master/rfps/rfp-pbscale-miner-testing.md

Selected as a member of Filecoin Security Research Fellowship by Filecoin team,@why is one of the organizers, he can prove it https://security.filecoin.io/

Participated in Trusted Setup Ceremony Phase 2 https://filecoin.io/blog/trusted-setup-complete/

Participate in HackFS, the project is called Filecoin123 https://hack.ethglobal.co/showcase/filecoin123-recBa27E4zfpHRRln

Participated in Space Race, and finally ranked 22nd in the world (name: Five Star-Helmsman&Heiben) Miner ID: t03176 https://spacerace.filecoin.io/

Participated in the slingshot competition, project name: 1. Starry sky in Yunnan 2. Filecoin-Crawl

Participated in Slingshot-Phase 1 Closing Ceremony https://www.youtube.com/watch?v=qheNJZ1DClM&list=PL_0VrY55uV19nu6orLLCaGCGocsjvpiGZ&index=1
```

### Stake Exposure

Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

```
The total FIL at stake is about 570690.8237FIL with the following Miner IDs till May 24th, 2021. The details are as follows:  
```

| Account   | Address Balance(FIL) | Initial Pledge |
| --------- | -------------------- | -------------- |
| f080868   | 140682.4672          | 101650.1874    |
| f0496068  | 14915.787            | 12481.3724     |
| f0218072  | 15870.8469           | 12608.3414     |
| f0761728  | 10860.4093           | 10478.5019     |
| f066302   | 91626.0774           | 62330.5256     |
| f066476   | 10038.6522           | 6551.2595      |
| f0154865  | 12963.6303           | 10492.0567     |
| f0146278  | 20441.1844           | 14383.0638     |
| f065113   | 42815.3162           | 25501.0150     |
| f03176    | 177619.1648          | 113238.4592    |
| f0158276  | 15050.3860           | 11335.0948     |
| f033456   | 4422.8054            | 2574.0987      |
| f033384   | 8567.3034            | 5758.2501      |
| f033399   | 4816.7932            | 3034.3835      |
| Total/FIL | 570690.8237          | 392416.61      |

### In-protocol Reputation

Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow.

```
Participated in Trusted Setup Ceremony Phase 1 https://github.com/arielgabizon/perpetualpowersoftau/blob/master/README.md

Participate in the first phase of the testnet that started in December 2019, ID: t019125, and the final storage capacity exceeds 1PiB

PB-scale Miner Testing,E-mail submitted the relevant test plan,the email was sent to the Filecoin team, and Filecoin team members like @why @keren knew about it https://github.com/filecoin-project/devgrants/blob/master/rfps/rfp-pbscale-miner-testing.md

Selected as a member of Filecoin Security Research Fellowship by Filecoin team,@why is one of the organizers, he can prove it https://security.filecoin.io/

Participated in Trusted Setup Ceremony Phase 2 https://filecoin.io/blog/trusted-setup-complete/

Participate in HackFS, the project is called Filecoin123 https://hack.ethglobal.co/showcase/filecoin123-recBa27E4zfpHRRln

Participated in the slingshot competition, project name: 
1. Starry sky in Yunnan 
2. Filecoin-Crawl

Participated in Slingshot-Phase 1 Closing Ceremony https://www.youtube.com/watch?v=qheNJZ1DClM&list=PL_0VrY55uV19nu6orLLCaGCGocsjvpiGZ&index=1

Participated in Filecoin Devgrants and submitted three application project applications:
1.FileWallet-Tools https://github.com/filecoin-project/devgrants/pull/107
2.Filecoin-file-storage-and-retrieval-utility https://github.com/filecoin-project/devgrants/pull/106
3.Filecoin123-Block-Explorer https://github.com/filecoin-project/devgrants/pull/105

PB-scale Miner Testing,E-mail submitted the relevant test plan,the email was sent to the Filecoin team, and Filecoin team members like @why @keren knew about it https://github.com/filecoin-project/devgrants/blob/master/rfps/rfp-pbscale-miner-testing.md

Participate in HackFS, the project is called Filecoin123 https://hack.ethglobal.co/showcase/filecoin123-recBa27E4zfpHRRln
```

### In-protocol Security

Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side).

```
We have submitted a lot of bugs that can help Filecoin improve its security. Here are some bugs

filecoin-project/rust-fil-proofsa sanity check failed of window post haven't catch.https://github.com/filecoin-project/rust-fil-proofs/issues/1308The ability to read files in parallel is required when window post occurshttps://github.com/filecoin-project/rust-fil-proofs/issues/1281Suggest to add more sector information in case of fault.https://github.com/filecoin-project/rust-fil-proofs/issues/1261

filecoin-project/lotusit's very slow to called `lotus-miner info` when the sectors number is over 10000.https://github.com/filecoin-project/lotus/issues/3913miner attempting to prove commit over 200 sectors in epochhttps://github.com/filecoin-project/lotus/issues/3638Some new deals from storage markets have append to a old sector which one have a invalid deal.https://github.com/filecoin-project/lotus/issues/3594It seems have a dead lock in messagepool when push message.https://github.com/filecoin-project/lotus/issues/3115`lotus state wait-msg` can not wait the `mpool replace` messages.https://github.com/filecoin-project/lotus/issues/2943invalid proof (compute error?): failed to fill whole bufferhttps://github.com/filecoin-fivestar/lotus/issues/71How can i get a rpc error return when define a chan response in rpc call?https://github.com/filecoin-project/go-jsonrpc/issues/14Suggest adding IP output of client to log when JWT Verification failed.https://github.com/filecoin-project/lotus/issues/1870
```

### External Reputation

Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

```
Tianji Data was established in Shenzhen, China, and the team was established in 2018. Since its establishment two years ago, it has been committed to the ecological construction of blockchain. Its products include DappOnline, TJWallet, Filecoin ecological construction, etc, we are the best data service provider and distributed storage solution provider.

DappOnline is the world’s leading blockchain ecological application store. It uses “DApp big data + DApp application + blockchain ecology” as the framework. Information, evaluation, analysis, recommendation, etc. can all be consulted. It is loved by many users all over the world;TJWallet is another product of Tianji Data. It provides a one-stop digital asset management solution with a dual ecological guarantee of “software wallet + hardware wallet”, which fully combines the security of hardware wallets and the ease of use of software wallets. 

Software wallets can manage blockchain assets with one click, and provide BTC, ETH, TRX, Filecoin, ACL, and all ERC20, TRC10, TRC20 and other digital asset transactions and transfers and other fullchain asset management; hardware wallets act as flash drives and Offline storage of the user’s blockchain private key, the full name is offline disconnection operation, the private key will not leave the hardware wallet, the entire transaction verification process is completed in the hardware wallet itself. 

The encrypted currency stored in the wallet remains offline and cannot be hacked.TJWallet is the first digital wallet tool in the 2020 star project IPFS/Filecoin ecosystem that supports F1/F3 full-chain full-function transaction transfer.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

```
https://dapponline.io/
https://tjwallet.net
https://twitter.com/DappOnline
https://twitter.com/TJ_Wallet
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

```
https://dapponline.io/
https://tjwallet.net
https://twitter.com/DappOnline
https://twitter.com/TJ_Wallet
```

### Use Case Diversity

(Optional) Any additional information you'd like to share about the use case(s) you plan to support?

```
I hope to help and support the development of Filecoin. Participating in this Beta is my contribution to defining Filecoin+ roles and additional processes.After the Beta period is over, I will also consider allocating time for this activity. Maybe by then, I will have a better understanding of different cases and get more value from them. Currently, I am happy to support any use case.
```

# Allocation Plan

### Allocation Strategy

How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.

```
After several months of conference calls, I think the plan is feasibleDefine thresholds with different levels of trust.The higher the requirements, the stricter the review:

Several important factors:
Reputation of the applicant organization
Is there any contribution to the Filecoin ecosystem (not necessarily a factor, but it will be a bonus item)
Scale of allocation
Assigned rating
Safety Precautions
Customer transparency

The type of data applied for (the public data set will be given priority)The specific distribution plan can be viewed in the Google shared table：https://docs.google.com/spreadsheets/d/1AsAyaW1mV-eKyaqLWWTIAsaWHf24YNCriinHc-naJrs/edit?usp=sharing
```

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap?

```
Out of the principle of openness and transparency, there will not be too many internal processes.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
Fix the key of the address assigned to DataCap in the hardware wallet.
```

### Client Due Diligence

How will you vet your Client to ensure they are spending that DataCap responsibly?

```
Divided into individuals and organizationspersonal account:

Can use third-party authentication information
Organize customers:
Review organization entity information (registration information, etc.)
Corporate identity
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them?

```
Personal information (Github, Twitter, Linkedin handle)
In which regions do you plan to use DataCap
Can the data set be shared
Provide data set sharing list
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?

```
Periodical inspection and audit of DataCap usage.
```

### Bookkeeping Plan

Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?

```
I intend to keep records of allocation decisions and make these records public in the GitHub repo. I will respond to all review requests.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both?

```
Yes, I will publish these records in the GitHub repo. For the sake of transparency and fairness, I do not intend to send them via email or telegram.
```

### Past allocation

Have you previously received DataCap to allocate before? If so, please link to any previous applications.

```
None
```

Cumulatively, how much DataCap have you previously successfully allocated?

```
None
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations?

```
None
```

**Comment by dkkapur** [comment]
Hi @IPFS-grandhelmsman - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1cXiPFyDZRxeEiU2Dz7kNrn5tzkgOVonlOxfEIIzkbOc/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.7.

**Comment by dkkapur** [comment]
@IPFS-grandhelmsman, the final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 1.7

Link to rubric: 
https://docs.google.com/spreadsheets/d/1cXiPFyDZRxeEiU2Dz7kNrn5tzkgOVonlOxfEIIzkbOc/edit?usp=sharing
