### ISSUE TITLE
 Notary Application - Yunchao group

### ISSUE THREAD

**Issue by thhminer** [filecoin-project/notary-governance#167]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Yunchaogroup
- Affiliated Organization: China (Anhui) Yunchao Gene Technology Group Co., Ltd. 
- Website / Social Media: http://www.tianhehui123.com/, http://161.117.181.10/
- On-chain Address to be Notarized: f2aziaqyrnpwwr33nerwu2qqgbjybhcgd66x2ifla
- Region of Operation: Greater China
- Use case(s) to be supported: General
- DataCap Requested: 1PB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
China (Anhui) Yunchao Gene Technology Group Co., Ltd. is the designated cooperation unit of national large gene center!
It has three major science and technology industrial bases,Main business of Yunchao group:
1. Whole genome sequencing and all kinds of gene detection
2. Research and development of gene technology
3. Stem cell technology research and development and stem cell anti-aging health services
4. Gene big data storage and commercial landing
5. Store Gene data to IPFS

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
The total registered capital is 133 million yuan.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Through continuous investigation and research for three consecutive years, Yunchao group decided to try to use IPFs (filecoin) network to store encrypt big gene data since 2021!
Within five years, Yunchao group plans to store 1 million person time (500g / person time) genomic data, and the total data volume will reach 500 PIB.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
for the security , our focus is data encryption only , we will encrypt data before upload to IPFS.

```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Anhui Yunchao Gene Technology Group Co., Ltd. was established on April 20, 2018. The legal representative is Li Yunming. The business scope of the company includes: technology development, technology promotion, technology transfer, technology consultation and technology service in the field of life science; Health management services; R & D. 

In the future, Yunchao group is expected to lead China and even the world in gene data storage!
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Tianhehui company: http://www.tianhehui123.com/
GTA gene project: http://161.117.181.10/
Yunchao Gene : https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzIzMDY0OTEwOA==&scene=124#wechat_redirect
Yunchao group: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzI0OTUxNDU4MA==&scene=124#wechat_redirect
GTA facebook: https://www.facebook.com/GTA.BlockChain
GTA twitter: https://twitter.com/GTAGlobal1
GTA Reddit: https://www.reddit.com/r/popular/?newUser=true
GTA Medium: https://medium.com/@gtablockchain
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.jinse.com/blockchain/440643.html
http://www.jinziwang.com.cn/portal.php?mod=view&aid=3019

```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
no yet
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
Currently we will reached up to 1PB, would grow up to 500PiB in 5 years.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
as mentioned above
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
For customer review the allocation of DataCap, we have developed an app for our customer to keep track of gene data and filecoin distribution .

```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
None. we provide service directly to our customers.

```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
None. 
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
None.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```

Yes, the records of allocation would be kept and published. When customers have doubts about the transaction and can provide evidence that they are involved in the transaction, we will cooperate with the public distribution plan and subsequent transaction details.

```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```

Yes, the allocation decisions would be public on Github.


```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
629 TiB, will be 1PiB by the end of this month. 
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None.
```

**Comment by dkkapur** [comment]
Hi @thhminer  - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1eM6iImiJqPxjeyA99Ovs8rEgIp_IJaCReLo5mr1rEts/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 0.7.

**Comment by dkkapur** [comment]
@ZHONGblock, the final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 1
- Unrounded score: 0.7

Link to rubric: 
https://docs.google.com/spreadsheets/d/1eM6iImiJqPxjeyA99Ovs8rEgIp_IJaCReLo5mr1rEts/edit?usp=sharing
