### ISSUE TITLE
Notary Application: ByteBase

### ISSUE THREAD

**Issue by swatchliu** [filecoin-project/notary-governance#169]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name:Shanghai ByteBase Information Technology Co., Ltd
- Affiliated Organization: ByteBase
- Website / Social Media:https://www.bytebase.cn/   Wechat:冰塔数科
- On-chain Address to be Notarized:f1cywlxarzudoubnbcawdbitrqkryxoyagxrsliiq
- Region of Operation: Greater China
- Use case(s) to be supported: General
- DataCap Requested:100 TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
GitHub Handle: swatchliu@163.com
Miner ID：F0111007

Mr. Wang Songping, the founder of Shanghai ByteBase Information Technology Co., Ltd., graduated as the electrical engineering major of Shanghai Tongji University. He has nearly 20 years of technology and business management experience in the IT and Internet industries and has a profound understanding of data center, cloud computing, and blockchain ecological construction. Once worked in Huawei, Ctrip, UCloud, and other companies, successively held the positions of technical manager, director, regional general manager, vice president, etc., participated in the incubation and construction of Ctrip B-end business, and was responsible for the preparation of Unicode's overseas business segment and the ecological channel partner department from 0 to 1.
During the construction of cloud storage services, he learned about the IPFS interstellar file system and was optimistic about its future development, because the emergence of IPFS coincided with the Chinese government's efforts to promote the "new infrastructure" (5G, Internet of things, block-chain, cloud computing, big data, referred to as 5IBCD). The "new infrastructure" will inevitably produce massive data. However, the traditional HTTP technology may not be able to adapt to the geometric growth of data, so IPFS is the data storage support of China's "new infrastructure" construction, and is a vent project in the new era, with immeasurable future value. 
In the second half of 2018, I got to know miners from Filecoin through friends' introduction, provided a lot of help on IDC room design and training, and provided IT technical support for several miners in China. During this time, he also gained a detailed understanding of the overall nature of the Filecoin network, which, in addition to mining, can serve as a great storage tool for real-world individuals, studios, or enterprises.

After a year and a half of market research and system infrastructure analysis and research and development, Mr. Wang Songping co-founded ByteBase in 2020 and built the independently developed ByteBase data storage platform. With Filecoin sharing incentive as the driving engine, the platform makes full use of the immutable and data rights confirmation features of the blockchain. Fusion of widely distributed globally decentralized network node resources, and to provide the organization, the copyright backup, maintenance, important subject since the card, mass storage, and many other scenarios and business customers, provide more reliable, more safe and higher cost performance of distributed data storage card services, to further build and energize sustainable development of ecological chain data assets application. Following link for Bytabase grand opening https://t.1yb.co/pkpP 

In addition, Mr. Wang Songping and his friends are also engaged in technology-related we-media content on Douying(TikTok Chinese Version) account and WeChat official account.

Following is a simple introduction of 2 social medias:

Douyin ID：AT88888888AT （Tiktok Chinese Version）  Nickname：Filecoin阿特

Established on 3th, Nov. 2018, this Douyin account sermonizes block-chain, distributed storage filed majorly, and release the short video of market analysis and analysis to update the dynamic information and opinions of the industry. So far, it has gained 12,000 followers.

WeChat Official account：LoT前哨站
Registered on 21st, March 2018, it mainly introduces applications related to the Internet of Things, developer consultation, technology research combining IoT smart device and cloud, and sharing of new things. So far, it has received 24,816 people following this public account.

```

<img width="205" alt="IPFS阿特" src="https://user-images.githubusercontent.com/46444977/119429152-e3108780-bd40-11eb-9597-5b8fd776b833.png">
<img width="205" alt="loT" src="https://user-images.githubusercontent.com/46444977/119429155-e4da4b00-bd40-11eb-9b36-0d6205ec2b25.png">
<img width="402" alt="lotwechat" src="https://user-images.githubusercontent.com/46444977/119429213-fe7b9280-bd40-11eb-9976-7e68365c4778.png">

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

```
So far, we have got 150,000+ Fil with the miner ID: f0111007
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
ByteBase Milestone
•  June 2019, ByteBase set up the project of Filecoin storage
•  April 2020, Mr. Wang songping and other 2 developers set up the company prototype.
•  Nov. 2020, after the 6 months of learning with Filcoin network and IPFS architecture, Bytebase start their storage system form 0.1-0.5 version
•  Dec. 2020 Bytebase officially registered, total 27 employee.
•  March 2021, the beta version 1.0 was launched, and 8 enterprises became the core users and participated in the experience.
•  April 2021, the official version is launched, and nearly 50 companies have partnered with ByteBase to continuously store information about IT, entertainment, healthcare, and the arts into the Filecoin network.

ByteBase Products Introduction:        
ByteBase Privacy Storage Platform: https://www.bytebase.cn  

With Filecoin sharing incentive as the driving engine, the platform makes full use of the tamper-proof and data right confirmation features of blockchain, integrates the decentralized network node resources widely distributed in the world, and serves many application scenarios and commercial customers, such as public trust organizations, copyright maintenance, important backup, subject self-authentication, mass storage, etc.

Users can upload their local disk data to the ByteBase private storage platform and finally chain it to the Filecoin network. The whole process realizes decentralized management, which is in line with the de-centralization characteristics of block-chain. ByteBase private storage platform is an application of Filecoin to achieve commercial implementation in the real world. Solved the Filecoin block-chain storage because there is no application entry and complete encapsulated interface, commercial organizations and the public can not directly call or experience the problem.

ByteBase private storage platform has established more than 2000 IPFS nodes, scattered around the world, and more than 300 enterprises to establish cooperative relations. The platform supports distributed storage of multiple copies of data, which can avoid data unavailability due to component failure. At the same time, the large storage capacity can satisfy the customer to store any type of file. In addition, the platform also provides an API data interface to customers, so that users can easily manage their own data stored on the platform and develop. various types of upper-level business applications.

Product establishment news from Slack Fil-Lobby

In addition, ByteBase has established data storage cooperation with nearly 50 Internet-related companies and joint development of Filecoin related ecological applications (Shanghai Xiaogongyi E-commerce Co., Ltd., Beijing EveVision Network Technology Co., Ltd., Chengdu Xingshuo Technology Co., Ltd., Shanghai Xinshu Information Technology Co., Ltd., etc.).

```

<img width="520" alt="bytebase platform" src="https://user-images.githubusercontent.com/46444977/119429807-30d9bf80-bd42-11eb-9eeb-76635bd7366d.png">
<img width="513" alt="slacknews" src="https://user-images.githubusercontent.com/46444977/119429816-359e7380-bd42-11eb-9ddc-b1b9e2227814.png">

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
NONE.
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```

•  The nature of your organization	：Limited-liability company
•  The country of registration		：China（Mainland）
•  Size of the organization		：Almost 100 employees，Obtained nearly 20 million CNY of investment
•  Time since inception			：Company registration time 2020.12.24


Organization Reputation

Shanghai ByteBase Information Technology Co., Ltd. was registered and established in Shanghai in 2020. ByteBase is a leading platform solution provider based on IPFS and blockchain storage in China.

Currently, there are nearly 100 team members, mainly focusing on system development, mainly from Alibaba, Huawei, Tencent, UCloud and other traditional Cloud service manufacturers.

The representative products of the company are the independently developed ByteBase data storage platform, and the solution of the storage platform driven by Filecoin shared incentive engine. Platform to make full use of the tamper-resistant and data made by characteristic of the block-chain, has the world's widely distributed fusion decentralized network node resources, and to provide the organization, the copyright backup, maintenance, important subject since the card, mass storage, and many other scenarios and business customers, provide more reliable, more safe and higher ratio of distributed data storage card service, Further build and enable a sustainable block-chain data asset application ecosystem.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
ByteBase official website: https://www.bytebase.cn/

WeChat: 冰塔数科

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
CHAINDD
http://english.chaindd.com/3549318.html 

Souhu
https://www.sohu.com/a/463037189_100217347 

Medium
https://arnold-zx.medium.com/standing-on-the-cloud-to-see-the-future-true-elite-global-leads-the-next-digital-era-13a83fd198c9

Baidu
https://mbd.baidu.com/newspage/data/landingshare?preview=1&pageType=1&isBdboxFrom=1&context={"nid"%3A"news_9807413127250964568"%2C"sourceFrom"%3A"bjh"} 

Wechat  
https://mp.weixin.qq.com/s?__biz=Mzg2MjU1OTU5Nw==&mid=2247484644&idx=1&sn=77d5e9953ffddaf5614dda1e5c09f23b&chksm=ce0748e6f970c1f033083431926d866476657a3789c8a1e95ed991639637dda21956918e4c78&token=1825079802&lang=zh_CN#rd

https://mp.weixin.qq.com/s?__biz=Mzg2MjU1OTU5Nw==&mid=2247484677&idx=1&sn=ce76264010236f4e02a21ee07dcbc924&chksm=ce074907f970c01111e9357eb8c66872af25c3f09545266003c4a5d7b5aba75106062f71ac8f&token=1825079802&lang=zh_CN#rd

https://mp.weixin.qq.com/s?__biz=Mzg2MjU1OTU5Nw==&mid=2247484648&idx=1&sn=831fa086d1e431ab30ee8bd776c9e692&chksm=ce0748eaf970c1fc04c67b2f618846850d4629ba01e229d18471944351608658e5dab1ccfa24&token=1825079802&lang=zh_CN#rd 

```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We plan to support all use cases in compliance with law, as the Filecoin Plus is currently in beta, and I want to understand how all use cases affect the network and then make adjustments.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
We have developed a set of scoring criteria for clients to apply to DataCap, which has been uploaded to Google Docs.
https://docs.google.com/spreadsheets/d/1VEdGP0m03d0nrqzqWikOINzOe3wa_WLx-a6Ij73Ydxc/edit?usp=sharing

```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
On our platform, we have developed and integrated the Filecoin DataCap application process in out official website: www.bytebase.cn

We also provide an online form for clients to submit application information.
Link: https://www.wenjuan.com/s/qAVFfuN/#

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hardware wallet will be used to store the keys associated with the DataCap allocation address securely. 
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
In order to ensure the fairness and impartiality of DataCap allocation, we have developed separate online and offline application processes according to the number of DataCap applications and individual users and corporate users.

For individual users:
we will review their Github registration years (minimum of 180 days) to prevent bots from malicious applications. The amount of approval will also be controlled below 0.5TiB.

For corporate users:
We have developed different review methods and requirements depending on the number of their DataCap applications.
If it is less than or equal to 5TiB, we will adopt an online review. The following points will be reviewed.
•  Business license
•  Enterprise power of attorney (CEO signature + seal)
•  All shareholders with more than 25% of the total number of shareholders will be photographed with their ID cards or passports.
•  Sample data submission (0.2% of their total DataCap request)

If the application is larger than 5TiB, we will add offline review (business trip to visit customers or invite them to ByteBase) based on the online survey method. There are:
•  Enterprise Business Type 
•  Data sources
•  Data volume (monthly)
•  Enterprise perceptions of filecoin 
•  Data storage plans

```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
•  Please introduce yourself and your personal information on social media (Official website, WeChat ,LinkedIn ,MaiMai, GitHub).
•  What is your purpose of applying for DataCap?
•  Please provide the address of the wallet you want to apply for DataCap
•  Please provide the number of DataCap you want to apply for.
•  Please provide the name of the organization, nationality, country of registration, time of registration, executive name, relevant website (if you are an institutional user).
•  Please provide the region where you want to use DataCap, if it is more than one region, please note that.
•  How many miners do you plan to distribute DataCap to, and if there are specially designated miners, please note that.
•  Have you ever assigned DataCap before? If so, please provide the details.

```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Applicants are required to distribute DataCap to at least 3 or more miners, which will increase storage redundancy and helps maintain decentralization and reduces the potential for misuse.

We will regularly monitor and record the usage of all DataCap distributed out once a month.
For applicants who are found to have abnormal usage, we will contact them then get to know the situation and record it.

```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
•  All allocation decisions will happen in public in the GitHub - all communications will also take place through the repository and the issue tracking.
•  For the level of allocation of quantity, I decided to divide it into five levels as shown in the table above. The higher level of audit will be more rigorous.
•  In addition to this, each application will be saved in a graphic form and uploaded to the Filecoin network via ByteBase storage platform for permanent archiving.

```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will happen in public in the GitHub- all communications will also take place through the repository and the issue tracking, and also, we will send the E-mail to clients for twice informing to ensure effectiveness.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None.
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None.
```

**Comment by dkkapur** [comment]
Hi @swatchliu - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/11Wsn2gPwUQ3q2_V_Am9gALIEKdtXH4ehjPBtY1pJ1Ig/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 2.2.

**Comment by swatchliu** [comment]
Hi Deep,

Thanks for your advice. Regarding the scoring we would like to update it as below:

**Individual Reputation:**  
1. We will keep post the information regarding the Filecoin ecosystem in both Douyin & WeChat.  

**Bookkeeping Plan:** 
1. Before DataCap approval is issued, it will be released on our official website for two days, any comments can be submitted to us from any miner.
2. We will invite another notary in China, "Fenbushi Capital" to help or monitor us review some large DataCap Applications (more than 50TiB).
3. We will provide the record of our approval of DataCap on our official website and our WeChat official account.

That's all for our updated information.

We are looking to hear from you soon.

Best regards.

Yours swatchliu

**Comment by flyer111** [comment]
Hi @dkkapur , I have some doubts about his Douyin and Wechat account, I find that his Douyin account is to publish filecoin related content starting in 2020 rather than 2018, and all articles from his wechat official account(LoT前哨站) has nothing to do with filecoin or IPFS, so I think it needs to be re-rated here.

**Comment by swatchliu** [comment]
Hi Deep，

I would like to update my bookkeeping plan No.3 with the below link.  http://cloud-test.bytebase.cn/#/dashboard 

Honestly, this is the demo version, we will publish it on our official website once we become the notary.

**Comment by dkkapur** [comment]
@swatchliu - I unfortunately do not have a Douyin account, but it would be great if you could share any screenshots or help clarify the claim around the account being established in 2018 as per @flyer111's comment above. 

Bookkeeping score increased to a 5 based on your intended plan to track applications. 

Your current scores for this round of elections are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 2.4

Link to rubric: 
https://docs.google.com/spreadsheets/d/11Wsn2gPwUQ3q2_V_Am9gALIEKdtXH4ehjPBtY1pJ1Ig/edit?usp=sharing

However - if selected as a notary, this is contingent on your commitment score remaining at a 4 rather than dropping down to a 2.

**Comment by swatchliu** [comment]
Hi Deep,

Thanks for your great support.

**Comment by flyer111** [comment]
Sorry, can you share any filecoin-related content posted with this account before April 2020? I can only see you sharing your wonderful life between 2018-2020 in this account, so I think this is your personal account before, renamed in 2020, this should not belong to the time commitment.  
In addition, ByteBase was established on December 24,2020 which is only half a year to now. It's too young to be a notary in my opinion. @dkkapur

**Comment by ozhtdong** [comment]
1475 attenteded product launch of ByteBase, and met ByteBase's team members, who started to researched IPFS storage from 2018. As far as we know, ByteBase's platform builds a bridge between traditional companies and Filecoin network. Maybe verified data of traditional companies need an access such as ByteBase's platform to Filecoin. @dkkapur

**Comment by swatchliu** [comment]
Hi Flyer111,

Thanks for your attention and ardent advice. I didn’t realize you were so focused on us.

We are ByteBase. We do our hard job on the development of our platform and our programmers fix bugs to make our system run smoother and smarter. You are welcome to visit our company in Shanghai China and we’d show you what we are doing now.

Could you identify yourself instead of hiding behind a new ID that signed in on June 8? 

We’d appreciate it if you share something useful about Filecoin ecosystem instead of commenting here. Or, you’re always free to prove yourself by putting up your own work.

In addition, "flyer111" was registered on June 8 2021 which is only 17 days to now. It's too young to be an adviser in my opinion.

**Comment by Fenbushi-Filecoin** [comment]
In our view, any volunteer’s personal track record, especially his/her contributions to the Filecoin community, should be “inheritable’ and carried forward to the entity that he/she is associated with.

We have witnessed so many folks advocating the adoption of Filecoin since years ago while their businesses were not formalized until much later.  What matters are his/her proven deeds, not the form that things got done.  As such, the contributions that trace back to ByteBase’s pre-incorporation stage are no less valid for all intents and purposes.  It seems unconvincing to downplay or even deny a volunteer’s credits on the mere ground that his/her contributions were made in the name of an individual (as opposed to a formal business company).  

The foregoing principle of retroactivity ought to apply universally to everyone dedicated to the Filecoin ecosystem.  We mean to deliver the clear message to the crypto-space that every person, regardless of being an individual or an entity, is welcome to be part of the Filecoin ecosystem and his/her credits would be recognized on an unbiased basis.

**Comment by dkkapur** [comment]
@Fenbushi-Filecoin @ozhtdong thanks for sharing your opinion here as well! @swatchliu - appreciate you sharing the clips from past years. Based on the general desire to increase DataCap availability and liquidity, I think we should move forward with electing ByteBase in this election cycle.

**Comment by dkkapur** [comment]
@swatchliu - based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of 100 TiB. In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm that the region of operation for client applications you will focus on is [Greater China Region]

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

> * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

> * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

> * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App).

**Comment by swatchliu** [comment]
@dkkapur Appreciate your kindness, Thanks a lot!

1.We confirm that we will focus on [Greater China Region]

2.We confirm all items below:

> - Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

Confirmed.

> - Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

Confirmed.

> - Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

Confirmed.

> - No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

Confirmed.

> - Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

Confirmed.

> - Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

Confirmed.

3.As mentioned before, our Miner ID is F0111007.

4.We will abide by the allocation / client due diligence plan we laid out above.

5.(Not Ready) We are preparing Ledger and we will let you know ASAP.

**Comment by dkkapur** [comment]
@swatchliu - let me know when you receive your Ledger so we can proceed with next steps with the RKH. Thanks!

**Comment by swatchliu** [comment]
> @swatchliu - let me know when you receive your Ledger so we can proceed with next steps with the RKH. Thanks!

Hi Deep, our F1 Address as below:
f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Datacap Allocated
> 100TiB

**Comment by dkkapur** [comment]
This grant seems to have gone through correctly and should not be in Error status. Fixing this now!
