### ISSUE TITLE
Notary Application:ZhongChuangCheng

### ISSUE THREAD

**Issue by ZHONGblock** [filecoin-project/notary-governance#171]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name:ZhongChuangCheng
- Affiliated Organization: ZhongChuangcheng Blockchain (Shenzhen) Co., Ltd
- Website / Social Media:http://zhongblock.com/
- On-chain Address to be Notarized:f3vr7tu2nbqbc2ptoejsfy7njyz2xrujwybiuuk2xjsj6xv7t44k3lhotezvs6kobtpianzwkz6ijeccmtb6sa
- Region of Operation: Greater China
- Use case(s) to be supported: Web3.0, IPFS
- DataCap Requested:100TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
A service-oriented technology company based on blockchain + distributed cloud storage +IDC cloud base, enabling traditional industries.With scientific, rigorous, professional attitude and professional solutions, digitization and token transformation of the enterprise, so that it can achieve "on-chain operation", upgrade to the blockchain economy, so as to achieve the "four modernizations" ------ Industrial digitalization, commercial token, financing deflation, value transcendence.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
We does not have a large number of pledged coins, and there is no capital risk.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
None.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
None. 
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
ZhongChuangCheng Blockchain (Shenzhen) Co., Ltd. was established in 2018, located in Shenzhen, Guangdong Province, and currently has more than 20 employees.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
http://zhongblock.com/..
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://mp.weixin.qq.com/s/StI7dwcLGX-8MKEVLOLkrA.
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
None.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
We will examine the customer's qualification, scale, technical strength, use and other information in detail, and then reasonably allocate the quota according to the standard.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
We will make flexible adjustments according to the actual situation. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will have a dedicated team responsible for data security .
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
We will conduct an initial review against the criteria and spot checks will be made during the process to ensure that the client is using the allocated quota properly.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
We will ask the following questions: 1 Company Profile.The company's history in the IPFS field.Purpose of applying for DataCap.4. Future plans. 
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Regular inspection. 
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
We will keep a detailed record of our allocation process for inspection.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All records will be made public as required. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None. 
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None.
```

**Comment by dkkapur** [comment]
Hi @ZHONGblock  - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1adKM_a5AP2cewERGQf1w739Lu7PEAcitKvT0aear2Pc/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 0.7.

**Comment by dkkapur** [comment]
@ZHONGblock, the final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 1
- Unrounded score: 0.7

Link to rubric: 
https://docs.google.com/spreadsheets/d/1adKM_a5AP2cewERGQf1w739Lu7PEAcitKvT0aear2Pc/edit?usp=sharing
