### ISSUE TITLE
Notary Application：Maitian Yunji (Hangzhou) Technology Co., Ltd

### ISSUE THREAD

**Issue by beyongo** [filecoin-project/notary-governance#174]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name:iKo
- Affiliated Organization: Maitian Yunji (Hangzhou) Technology Co., Ltd
- Website / Social Media:https://www.mtfs.top/#/index
- On-chain Address to be Notarized:f12y74czbkrjizcwwudvrsfdbmgpxarfrpfovpjwq
- Region of Operation: [Greater China]
- Use case(s) to be supported: [Web 3.0 / Decentralized Applications, Web 2.0 Applications, User Content, Scientific Data, Other]
- DataCap Requested:5PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
1. At the beginning of 2017, we founded a team focusing on TMT industry with other four patners to explore potential business opportunities.

2. After that, a couple of partners of our team participated in Filecoin’s public sale on Coinlist in 2017.

3. At the end of 2017,we saw great value and potential of IPFS protocol and believed it to be the most likely project that could be implemented in business scenarios.

4. After careful study of the Filecoin white paper, we finally decided to create a company specialized in Filecoin project named Maitian Yunji (Hangzhou) Technology Co., Ltd. 

5. As an company,we committed to the blockchain technology research .We have build deep cooperation with Peking University, Beijing Jiaotong University to set up technology research centers. Thereafter ,we developed the world's first dedicated chip for distributed storage server named 'Matian Chip' independen
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
The total FIL at stake is about 0.44M with the following 14 Miner IDs till May 24th, 2021. The details are as follows:
```
Account(ID) | Balance(FIL) | Account(ID) | Balance(FIL)
-- | -- | -- | --
f067375 | 45,114.1929 | f02529 | 3,596.7543
f021254 | 24,829.5371 | f03002 | 660.5693
f086442 | 87,209.2748 | f0135414 | 42,683.82
f094764 | 29,438.9551 | f0146220 | 43,788.2551
f065686 | 12,917.4183 | f0232459 | 41,746.9356
f01287 | 39,067.851 | f0117434 | 37,058.192
f02613 | 4,197.5671 | f0130134 | 29,132.9897

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As a member of Filecoin community, we have dedicated lots of time in promoting the ecological development of Filecoin industry since 2019.

1. Last year, we have join the Filecoin Space Race in September 24th, 2020 and finally ranking 33th.

2. In this year, We join the Fil+ Day on 11th May.

3. We joined the Filecoin liftoff week at the Miner Spotlight in October 2020.

4. We actively took part in every notary governance call to discuss proposals for better improvements of Filecoin Plus and tried my best to help peers who have problems on Slack channel.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
NONE
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Maitian is a rapidly developing decentralized storage solution provider based in Chengdu and Hangzhou, China. 

The company was founded in June 2018, as of now, we have about 100 employees, many of whom come from Lenovo, Alibaba, Huawei and other well-known enterprises. 

The company is led by Ni Guangnan, a well-known researcher of the Institute of Computing Technology, Chinese Academy of Sciences, and he also is one of an academician of the Chinese Academy of Engineering.

Bai Xuefeng, a computer doctor graduated from Peking University and an expert on distributed storage based on block chain technology, serves as the cloud technology consultant for Maitian. 

In April 2019, Maitian Yunji (Hangzhou) Technology Co., Ltd. established the China Development Research Institute Distributed Storage Research Center with China Development Research Institute.

On December 16, 2020, Maitian Yunji (Hangzhou) Technology Co., Ltd. signed a cooperation agreement with People's Daily Online and People's Data (National Big Data Disaster PreparedCenter). From then on, Maitian Yunji will undertake the technical service and operation work of the "People's Cloud Network" project.

From 2020 to 2021, together with Chinese local government, we have initiated the construction of one of the biggest storage data centers in China. 

We are committed to becoming the leader and builder of blockchain distributed storage, and promote data centers from centralized Chinese to blockchain distributed, and from static storage to intelligent processing.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Official website：https://www.mtfs.top/#/index
Self-developed distributed memory service：https://pro.mty.wang/index
WeChat：麦田云际
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Maitian has a wide range media exposure globally. Here are some report examples in top medias.

* https://news.huoxing24.com/20200924221855654715.html
* http://nx.people.com.cn/n2/2020/1216/c192493-34478366.html
* http://www.ningling.gov.cn/ywdt/xzf/2020-10-24/8884.html
* http://yn.xinhuanet.com/hot/2020-12/09/c_139575882.htm
* https://www.sohu.com/a/436930873_216434
* https://sghexport.shobserver.com/html/baijiahao/2020/11/26/304040.html
* https://ishare.ifeng.com/c/s/7xLSnnG9jt2
* https://www.cnjxol.com/54/92/202006/t20200614_630826.shtml

For more information, please search more on Baidu & Google.
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Maitian Cloud Network, project orientation is the new infrastructure 5G edge computing data center, is mainly deployed in prefectures and counties to serve the surrounding economy and provide comprehensive cloud computing services, especially the cloud storage services, for the government, enterprises and individual users.

We aim to establish 500 ~ 1000 (the 3000 or so) data center, networking with distributed storage technology, the formation of fragments content addressing, distributed storage of wheat, resources fully Shared cloud network, fundamentally solve the data storage industry weaknesses including security, reliability, speed, cost, management etc, providing more secure, more reliable, faster, lower cost, comprehensive cloud computing storage services.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
The most important thing about DataCap allocation is to ensure that client utilizes DataCap to store real data. so I firstly specify some rules to figure out the true identity of the applicant.
* Browse their official website to get a general understanding of the company or the individual. 
* Query the company's registration information from government related websites to make sure the information he submitted is truth.
* Ask some questions to know about the applicant's position/organization/plan/use case etc. 
* Then We will classify applicants based on their industry reputation and scale etc. All applicants will be divided into eight categories to determine the amount of datacap they will get. The following Rubric will be the primary guideline I use when evaluating a client and determining their DataCap allocation. 
  
You can see it: 

https://docs.google.com/spreadsheets/d/1dD8aI3lsZGRp5rUWiULeRaPwFc7Z2z8tkzpdnTY-tyo/edit?usp=sharing

These scoring guidelines can serve as a tool of assessment and further to add a level of consistency across the board. 
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
The whole application process should be open and transparent, we design the necessary internal processes follows：

1.Each applicant requesting DataCap is required to formally submit a written application (in pre-specified form) and other relevant supporting information to us for our review process to kick off;

2.A preliminary review of the foregoing application will be made by our internal “Notary Taskforce” to pre-qualify the applicant, who must be a serious and well-established business entity or non-profit organization having plausible data storage demands;

3.Each applicant failing the pre-qualification will be requested to provide additional information or be simply denied, as the case may be;

4.For the pre-qualified applicant, our “Notary Taskforce” will conduct a due diligence to scrutinize its legal standing, operations and data concerned; 

5.Based on the due diligence result, a rating will be performed by us for each business entity applicant in accordance with the preceding factors and criteria, following which we will assign a score to that applicant.  Rating for non-profit organization applicants will be dispensed with; and

6.We will resolve, in the form of a written decision, the denial or grant of requested DataCap allocation and (if granted) the amount of DataCap allocated, taking into account the applicant’s score (for business entity only) and data size concerned, and will then implement the same.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will adopt various authentication solution in this verification processsuch， as using multi-signature to control the allocation process. 

On the other hand，we will have some private keys that are stored in the hard wallet. on the other hand, we will set a multiple authentication mechanism (including check identity, review source of data and arrange for supervisor approval) to secure every step of DataCap allocation.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
Similar to the practice of professional investment institutions, There will be three stages in verification process to ensure the DataCap is used properly.The details are as follows:
```

Stage | New Client/small DataCap request | Repeat Client/large DataCap request
-- | -- | --
Before the allocation | 1. Ask for some details about his organization and use plan2. Verify the submitted information3. Score them according to our score sheet | 1. Learn about his DataCap usage2. Collect details&nbsp;[1]&nbsp;about his organization and use plan.3. Detailed review of related information4. Score them according to our score sheet
During the allocation | 1. 2-day waiting period for possible adjustments or disagreements2. Allocate a small amount of DataCap (less than 5TB) for trial | 1. At least a 7-day waiting period for due diligence, usage review, possible adjustments or disagreements.2. A DataCap allocation agreement will be signed to clarify the rights &amp; responsibilities of each party.3. Allocate DataCap carefully after scoring
After the allocation | 1. Provide help and guidance for DataCap users2. Communicate with customers on a regular basis to know his DataCap usage and leave him a good impression on Filecoin | 1. Conduct routine verification to ensure the DataCap is used properly2. Introduce a feedback mechanism to sync DataCap usage list and to optimize suggestion3. If the applicant commits any violation, we will take actions to stop further allocation or even take punishment actions&nbsp;

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
individual and organization：

1.What's your name? What's your duty in your company? Please introduce yourself and your team briefly, and show me some your social media accounts such as GitHub, email address, WeChat official account etc.

2.For your organization, Please describe its time since inception, registration country，scale, named officers, project, industry reputation etc.

track record：

1.How did you know about Filecoin? Please describe your understanding of Filecoin storage.
2.Please describe any of your honor and disputes in the field of Filecoin.
3.Regarding your data you intend to store, What’s the original source of those data, and do you have any proof of ownership or authorization?
4. Has your organization obtained DataCap before? if so, please answer the following sub-questions.

* Please share all links and recording of your application before.
* How about your DataCap usage? Is there any remaining? Is there any information on the deals you've created and miners you've used with your previously allocated?

use plan：

1.Please describe your plan to use DataCap as detailed as possible? (including use case, amount, timespan, geography, miner, partner etc.)
2.Do you plan to record your allocation decisions and execution details in public? 
3.How do you plan to protect the DataCap you have obtained to make sure that it is used to its best advantage?
In addition, I may further ask some questions to give an accurate score to the applicant.
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Firstly, from the questions about use plan and further investigation, I can know some details about his allocation plans. When scoring applicants according to the above sheet, the more geographical distribution, use cases and miners assign, the higher score he will get and the more datacap clients are likely to get.  

Next, we will keep tracking clients’ information such as the DataCap distribution records, related miner addresses and storage providers, to ensure that they are consistent with their words and deeds.

Finally, a reward and punishment mechanism will be established. If someone over-allocating datacap to a single entity, I will refuse further allocation and issue a warning which will be public to the Filecoin community. On the contrary, reputable client have the opportunity to obtain more datacap.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Firstly, from the questions about use plan and further investigation, I can know some details about his allocation plans. When scoring applicants according to the above sheet, the more geographical distribution, use cases and miners assign, the higher score he will get and the more datacap clients are likely to get.  

Next, we will keep tracking clients’ information such as the DataCap distribution records, related miner addresses and storage providers, to ensure that they are consistent with their words and deeds.

Finally, a reward and punishment mechanism will be established. If someone over-allocating datacap to a single entity, I will refuse further allocation and issue a warning which will be public to the Filecoin community. On the contrary, reputable client have the opportunity to obtain more datacap.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
In public only.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
NONE
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
NONE
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
NONE
```

**Comment by dkkapur** [comment]
Hi @beyongo  - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1-wgmuw9IhCBlFMF1_Y7x0EPVbDs1WRDd3vtsOtTKtXc/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.9.

**Comment by beyongo** [comment]
In which year was Maitian Yunji (Hangzhou) Technology Co., Ltd. established?

> Hi @beyongo - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
> https://docs.google.com/spreadsheets/d/1-wgmuw9IhCBlFMF1_Y7x0EPVbDs1WRDd3vtsOtTKtXc/edit?usp=sharing
> 
> Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.
> 
> Your initial unrounded score is: 1.9.

In which year was Maitian Yunji (Hangzhou) Technology Co., Ltd. established?
