### ISSUE TITLE
Notary Application: ABMatrix

### ISSUE THREAD

**Issue by nathanusask** [filecoin-project/notary-governance#175]
# Notary Application

## Core Information
- Name: ABMatrix
- (Optional) Affiliated Organization: ABMatrix
- Website / Social Media: https://www.abmatrix.cn
- On-chain Address(es) to be Notarized: f1pfx2kugqswry7obfu7e77syyxgrq2smdltbzd3i
- Region of Operation: Greater China
- Use case(s) to be supported: Professional Services -- Long-term data storage and log backups
- DataCap Requested: 100TB

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

```
ABMatrix is dedicated to the development of blockchain technologies and applications.
Our long-term businesses include but are not limited to industrial internet, factory devices data storage, factory maintenance log backups, IPFS-Filecoin middleware, zero-knowledge proof products, etc.

Since its inception in 2017, ABMatrix has built its reputation with hard work.
During the past several years, we have obtained:
1. 11 software copyrights;
2. 1 official patent certificate;
3. 2 patent certificates in progress;
4. member of Ningbo Committee of Blockchain Experts;
5. third-place award from the first Substrate Developers Contest in 2019;
6. 1 certificate of eligible BSN developers;
7. 1 certificate from the Ministry of Industry and Information Technology
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

```
We currently have almost 300,000 FIL in total with roughly 13,000 FIL available.
We are able to maintain up to 30PB quality adjusted power as our current quality adjusted power slightly exceeds 22PB.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

```
ABMatrix is currently in the middle of the test phase where we use IPFS as the warm data storage and Filecoin as the cold data storage for factory monitoring data and maintenance logs.
In addition, a manufacturing execution system (MES) platform is under development to boost the productivity of various manufacturers.
By the end of 2021, the MES platform will incorporate blockchain technologies as well as IPFS, Filecoin, and Zero-Knowledge proof to protect and leverage the data.
By mid-2022, over 200 small to middle scale manufacturers are projected to join our network.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g., if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 

```
None. 
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

```
ABMatrix was founded in 2017 and now comprises 40+ developers and researchers with various backgrounds including but not limited to computer science, physics, math, mechanical engineering, electrical engineering, etc.
In ABMatrix, we believe that technology helps to build trust among people.
We aim to unleash the power of blockchain technology to make the world a better place.
Firstly, we aim to help small and middle scale factories and manufacturers to protect their data and to maximize the value of it, at the lowest cost possible.
Second, we aim to end the era of data breach and cloud service monopolization from Big Tech companies.
Finally, we aim to build an ecosystem (a cognitive distributed industrial internet) where everyone is able to get involved.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

```
Founders: Jingzhong Xu, Haozheng Guo
Website: www.abmatrix.cn
WeChat: 加密矩阵
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

```
The following are a few highlights of ABMatrix being an active community contributor:
1. ABMatrix became a member of TOP30 blockchain corporations of 2020 in China (https://mp.weixin.qq.com/s/2uIK3YB4Fv-ezxsQeK-MxA)
2. Subsidiary of ABMatrix became a member of Ningbo Committee of Blockchain Experts (https://mp.weixin.qq.com/s/Pm5D0sTnlFhq5pwcT-hJVg)
3. ABMatrix: recipient of 2020 Technological Innovation of the Year (https://mp.weixin.qq.com/s/zsTgvQ4l818CjSS36-FWwQ)
4. ABMatrix was invited to the Blockchain Cross-Chain and Bridge forum by Web3 (https://mp.weixin.qq.com/s/ccsSIndWCeFh2273E5CxgA)
5. ABMatrix presented BOOL Network demo at Web3.0 training camp (https://mp.weixin.qq.com/s/C_ShtKfm5qIPEAKFtOA94Q)
6. ABMatrix hosted 2020 Ningbo Distributed Storage Conference (https://mp.weixin.qq.com/s/rqpGVhZBqg4KfOommp92CQ)
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?

```
For factories/manufacturers at small or middle scale, cloud services offered by Big Tech companies are highly costly.
In addition, Big Tech companies' legacy IT stacks are open to data breaches, which will then lead to small and middle scale factories' privacy being compromised.
in light of the above-mentioned issues, we plan to support
1. factory monitoring data storage (mostly video data from surveillance cameras);
2. factory devices maintenance log backups;
3. factory production data;
4. privacy-preserving strategies applied to all data.
```

# Allocation Plan Template
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.

```
Based on the fact that our target data sources are mainly from manufacturers and factories, the DataCap will be allocated according to factors such as the factory size, daily data collection size, and the value and quality of the data.
Data quality and value will be assessed by professionals in the corresponding industry.
We assume that the DataCap request is submitted by developers committed to serving a set of manufacturers and that such commitment runs in the form of smart contracts.
In this case, we will ask the developers to submit proofs such as testing results of daily data collection size.
```

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap? 

```
We will ask professionals from the corresponding industries to evaluate whether or not the data amount is reasonably reported by clients (i.e., developers in this case).
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
We will use the cutting-edge multi-signature hardware to ensure that our DataCap won't be abused or misused.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?

```
Since our projected clients are mainly developers, we will ask for their resumes, github activities, and social media profiles. If necessary, we will schedule interviews with them.

```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them?

```
1. Do you intend to store your data in a single geography or many?
2. Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?
3. How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
4. Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?
5. Will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?
6. Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?
7. Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.
8. Are there any disputes open against you from your previous DataCap allocations?
9. Have you ever previously violated:
	a. Your own attested allocation/audit plan?
	b. Been found to be in violation of the Principles of Filecoin Plus?
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?

```
1. We will acquire the Client’s Filecoin address and regularly monitor their storage orders.
2. We will document each activity (good/bad) and take actions accordingly; each activity will be evaluated with specific rubrics and we will score each activity. Meanwhile, we will set thresholds and determine what the next steps we will take should either threshold be hit.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?

```
Yes.

All records will be kept in our private IPFS network in JSON format.
We make sure each JSON file is up-to-date via IPFS name system and each IPNS record is then stored in a secured database.
Each record includes application UID, applicants, application status (Open/Closed), DataCap requested, DataCap approved, application date, nodes and proportions, Filecoin address, GitHub account, decision date, and activities (a list of activities that records the processes of the application).
```

Do you plan on conducting your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 

```
Based on the clients' willingness of whether they want to expose themselves to the public, we will determine if we will announce our allocation decisions publicly or privately.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
No. 
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
No.
```

**Comment by dkkapur** [comment]
Hi @nathanusask - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1GMMkMBHz9RPvj6CHHGRgKNHELBUfmvdoBzpcaj8Ndao/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial score is: 1.5.

**Comment by nathanusask** [comment]
Hi @dkkapur , thanks for thoroughly reviewing our application, and here are our additional answers to your questions:

**Allocation Strategy**: This could be scored up if you can share any additional thinking on verifying clients and finding ways to prove who they are; the current plan covers to some extent by assuming that the smart contracts in place between clients and developers are enough.
```
Regarding the proof of who they are,
we plan to do a private inspection on materials such as the company registrar license
as well as their company/team size that can help us determine their eligibility to acquire datacap. 
Next, we ask the dev team to provide their application prototype to see if there exists any datacap abuse possibility.
The smart contract will require that the developers
and clients stake a certain amount of FIL in case they commit any wrongdoings;
i.e., they will get rewarded
when they continuously deliver
what is expected from them or have their FIL confiscated should they fail the commitment.
```

**Bookkeeping Plan** How will you handle disputes for clients where the data has been requested to be private?
```
We assume that the dispute occurs when the clients fail to use their private keys to decrypt the data
and thus can't verify their data validity.
In this case, we've designed a protocol
wherein we provide an encryption application to the clients
so that they can use the application to encrypt the data
before sending the data to our Filecoin nodes.
Next, if anyone acquires validity proof from us we use our zero-knowledge proof application on the data and send out the proof.

(We kindly ask how the case occurs
when the data requested is private
should we failed to correctly interpret the *dispute*.
However, we believe that we're prepared for all cases in terms of technical solutions.)

Another plan is that we provide a TEE-based solution such as SGX -- a programmable private-preserving platform,
where all the computation logic is designed and verified by authorized institutes.
The security is guarded by SGX so whenever a dispute occurs
we will let the clients authorize us to send the data to the institutes
and further inspections and dispute resolutions go from there.
```

**Comment by dkkapur** [comment]
@nathanusask thanks for sharing the additional info!
- Allocation Strategy: score increased to 3
- Bookkeeping Plan: score increased to a 5 based on given explanation + previous response in application. The case of a private dispute would occur if the community wants to see proof of allocation to a specific client if that client is seen misusing DataCap through various monitoring tools available that track deals being made with DataCap. 

The final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 1.7

Link to rubric: 
https://docs.google.com/spreadsheets/d/1GMMkMBHz9RPvj6CHHGRgKNHELBUfmvdoBzpcaj8Ndao/edit?usp=sharing
