### ISSUE TITLE
BitriseCapital 

### ISSUE THREAD

**Issue by BitriseCapital** [filecoin-project/notary-governance#176]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: BitriseCapital
- Affiliated Organization: BitriseCapital
- Website / Social Media: https://www.bitrisevc.com/sy
- On-chain Address to be Notarized: f17qnnebruqlplgvw5mt6iypq6cvy3xqutqrj2zca
- Region of Operation: Asia-GCN
- Use case(s) to be supported: Web 3.0, IPFS
- DataCap Requested: 1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Bitrise Capital participated in the fundraising of the Filecoin Ecological Special Fund, and also the LP of the Fenbushi capital Filecoin special fund. The overall fund was over-raised, and the final management scale was 300,000 FIL.
Miner ID: f0103665
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Currently available: 114,398.2057 FIL
Evidence:
https://filfox.info/en/address/f0103665
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
None
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
None
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Bitrise Capital (registered in Singapore in 2017) is a venture capital institution focusing on the field of blockchain, and its main investment direction is in the field of digital currency and mining. More than 60 projects have been invested. Bitrise capital's goal is to provide safe and reliable decentralized + financial services, providing asset management, digital asset payment, connecting defi ecology, NFT ecology, polkadot ecology and other hot spots in the industry. Bitrise Capital has a fantastic investment team . With the goal of iterative team cognition, bitrise capital updates its investment logic, has insight into high-quality projects in the market and controls market fluctuations.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://www.bitrisevc.com/sy
Twitter：https://twitter.com/BitriseCapital
WeChat ID: gh_67bd591d0b8e
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.bitrisevc.com/newsinfo/499321.html
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
None
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
The data volume will be used to classify the allocation requirement into five groups, Level 1-Level 5. The higher the data volume requested by clients, the stricter the regulations will be. These clients will be examined based on their reputation, data, diversity and decentralization, allocation tactics, track record, and other factors.
Therefore, we will have a reliable employee to execute the DataCap allocation Beta phase so that clients may understand the entire scoring and operating procedure.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
There isn't too much limit for the target but followings are the targets we prefer:
1.Public development data 2.Slingshot value data 3.Some public sector backups of data
We will make flexible adjustments according to the actual situation.  
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We filled with hardware wallet protection.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
We will get the KYC of our clients to check their background, reputation and stakeholders information.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
The questions we will ask:
1. Could you please introduce your company, principle business, scale of the team and main projects.
2. Please provide the data to be stored on Filecoin, the sources of the data and copyright ownership.
3. How many miners do you want to choose for storing the data? 
4. Can you provide relevant supporting materials for the purpose of DataCap allocation?
5. Will you publicly record allocation decisions?Which platform will you use?
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Firstly, we will establish a customer track record in order to avoid clients from making poor allocation decisions. Second, clients must disclose their allocation history, and if the allocation is not acceptable, I will remind them. If customers continue to ignore it, we will implement a blacklisting mechanism that will limit their future applications.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Yes, we plan on keep the records of the allocation decision, all processes will be published on Github repository.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
I plan to make it public in GitHub repo, and also we will send the E-mail to clients for twice informing to ensure effectiveness.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None
```

**Comment by dkkapur** [comment]
Hi @BitriseCapital - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1Azw8-VccwUToeUK-vVtvYAiyhKv0UzPg07dO2o2BAqI/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.2.

**Comment by dkkapur** [comment]
@BitriseCapital, the final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 1
- Unrounded score: 1.2

Link to rubric: https://docs.google.com/spreadsheets/d/1Azw8-VccwUToeUK-vVtvYAiyhKv0UzPg07dO2o2BAqI/edit?usp=sharing
