### ISSUE TITLE
Notary Application: The9

### ISSUE THREAD

**Issue by serafimey** [filecoin-project/notary-governance#177]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Zhu Hao
- Affiliated Organization:Shanghai The9 Information Technology Co.,Ltd. 
- Website / Social Media:www.th9.com
- On-chain Address to be Notarized:f1bodegkwcdjofy55wli23jidxg2v3wbftrg3itey
- Region of Operation: Greater China
- Use case(s) to be supported: General
- DataCap Requested: 1 PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```

The9 focuses on web3.0 infrastructure, with special attention to valid data verification, 
We will been promoting the filecoin plus project to the outside world, and connecting with the companies to understand their storage intention.

http://bc.the9.com/

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
We prefer not to disclose..
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We established subsidiary in order to let more people understand and support IPFS, To promote IPFS, we established NBTC to invest in some ecology applications based on IPFS to support implementation of those applications. and other applications born for IPFS ecology. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
We haven’t made any Bug suggestion.But during the IPFS/Filecoin testing phase, we've been involved, working with miners in a number of countries.. 
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Organization: Shanghai The9 Information Technology Co.,Ltd. 
Nature:  listed company
Registration Country: China
Established: 1999
Size: over 100 employees
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
http://www.the9.com.
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://weibo.com/the9ncty
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
We will examine the customer's qualification, scale, technical strength, use and other information in detail, and then reasonably allocate the quota according to the standard.

```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Not clear yet. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The private keys will be stored in the hard wallet.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
We will check the validity of user uploads and adjust the user’s credibility based on the results.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
What's your name, your company name? Can you offer the social media/website link of you/ your company?
What kind of data do you what to store and how much?
Which address do you need to be notarized?
Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?
How many miners do you want to store your data to? How much data for each miner?
Will you record your allocation decision in public? Which platform will you use?
What method/tool will you use to insperct miners? Which aspect of miners will you inspect?
Have you ever allocated before? If yes, how did you do when you were questioned?
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
We will ask Client to seperate DataCap to different entity.
We will review the Client status and if Client is not improperly over-allocating DataCap to a single entity, we will reject the Client's applicaiton during the next allocation.
We will publicize all requests and assignments which are subject to community’s supervision.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Yes, all allocation decisions will be guided by the rubric publicly on Github. So are all communications.
We are open to any audit requests.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will happen in public in the following repository - all communications will also take place through the repository and the issue tracking, and also we will send the E-mail to clients for twice informing to ensure effectiveness. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes,https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/240
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
10TiB
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
none.
```

**Comment by dkkapur** [comment]
Hi @serafimey - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1H2D9PvtxKnSG2rFLLgnGUVSA_rX0iXwRENq2RMRF1jY/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial score is: 1.5.

**Comment by dkkapur** [comment]
@serafimey, the final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 1.5

Link to rubric: 
https://docs.google.com/spreadsheets/d/1H2D9PvtxKnSG2rFLLgnGUVSA_rX0iXwRENq2RMRF1jY/edit?usp=sharing
