### ISSUE TITLE
Notary Application: Wusi R&D Center-waynewyang

### ISSUE THREAD

**Issue by waynewyang** [filecoin-project/notary-governance#178]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name:  Wei Yang

- Affiliated Organization:  Shenzhen Wusi R&D Center

- Website / Social Media:  https://github.com/wusirdcenter

- On-chain Address to be Notarized: f1lxlgiariqqfd7fqn7pvjt3azvwzly3eyyztrqmi

- Region of Operation:  [Greater China]

- Use case(s) to be supported:  [VR Applications，Web 3.0 / Decentralized Applications, Web 2.0 Applications, User Content, Scientific Data, Media & Entertainment, Other]

- DataCap Requested: 10T

  
  
  

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Since 2018, I began to pay attention to the ipfs community project, track and participate in community construction and the popularization of technology in Greater China continuously;

In 2018, I did a analysis of the ipfs project and published a series of blog posts to promote the promotion of ipfs technology in Greater China;

In 2019, as soon as the filecoin project was open sourced, I analyzed the source code for the first time and published a series of articles. I am fortunate to be the first filecoin community contributor in Greater China. I participated in numbers of blockchain-related forums and national information industry technology conferences, delivered several keynote speeches on the filecoin project, preached the technology and the vision of filecoin in Greater China, and led our team to build software services and hardware equipment based on filecoin technology;

During 2019-2020, I participate in the filecoin testnet stage, slingshot stage, and mainnet stage. and  I have once led the creation and operation of numbers of large miners;

This year, I will lead our new team to actively participate in the construction of the ipfs and filecoin ecosystem continuously.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

```
N/A
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
From 2018 to 2019, I participated in the ipfs global developer conference for twice;
Since the filecoin project was open sourced, I once submitted a number of PRs and ISSUEs, as follows:
https://github.com/filecoin-project/lotus/pull/406
https://github.com/filecoin-project/lotus/pull/429
https://github.com/filecoin-project/lotus/pull/440
https://github.com/filecoin-project/lotus/pull/443
https://github.com/filecoin-project/lotus/pull/444
https://github.com/filecoin-project/lotus/pull/453
https://github.com/filecoin-project/lotus/pull/454
https://github.com/filecoin-project/lotus/pull/457
https://github.com/filecoin-project/lotus/pull/471
https://github.com/filecoin-project/lotus/pull/1836
https://github.com/filecoin-project/lotus/pull/1838
https://github.com/filecoin-project/lotus/pull/1847
https://github.com/filecoin-project/lotus/pull/1971
https://github.com/filecoin-project/lotus/pull/2169
...
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
I participated in the filecoin bug bounty program and submitted the filecoin security bug as follows:

https://security.filecoin.io/bug-bounty/
The condition of time-offset mining fault : https://github.com/filecoin-project/lotus/pull/1988
ReportConsensusFault does not take effect : https://github.com/filecoin-project/lotus/issues/1981
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Wusi R&D Center is located in Shenzhen China. we are committed to becoming the global leading Web3.0 contributor. Our company focuses on the distributed compute and storage ecology construction and the link between Web3.0 and the real economy. 

Our company's core team is composed by technical backbones who are from well-known companies such as Alibaba, Huawei, and ZTE, and more than 95% of the  employees are R&D personnel.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Github: https://github.com/wusirdcenter
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://github.com/waynewyang

My ipfs related article:
https://github.com/waynewyang/analysis-of-IPFS-in-Chinese

My blog post about filecoin:
https://www.jianshu.com/u/01c1069071c7
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
The current application for datacap is mainly uesed for the filecoin matching system, which is a filecoin ecological application.
including：VR，Web 3.0 / Decentralized Applications, Web 2.0 Applications, User Content, Scientific Data, Media & Entertainment,etc.;
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
We are planning to develop a deal matching system, the basic design ideas as follows: https://github.com/wusirdcenter/filmatchup/blob/master/Readme.md

It collects and integrates information on-chain and off-chain, manages and unveals client and miner information, matches clients and miners to complete deals; on one hand,We want to be more involved in the community；on the other hand ,in the development and testing phase of this system, we hope to apply 10T datacap for testing , verifing, and improving the work mechanism and process of notary.

1. Users are required to provide basic information such as business license and tax number, pass third-party certification, and sign a declaration of legal use of datacap, at the time of registering;

2. We will establish a reputation system for compliance deals:
(1) At the beginning, we will inquire the basic information of the company on 3rd party website, such as www.qcc.com, www.tianyancha.com, and establish the initial value of the reputation index;
(2) If users can use datacap in compliance, their reputation value will increase accordingly;
(3) If users abuse datacap, the reputation value will decrease accordingly;

3. We will adjust the user's datacap size according to a certain strategy when the user's reputation changes；

4. We will consider using technical means to achieve automated or semi-automated spot checks on whether users are legally using datacap

```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Once this system is established, datacap will be automatically allocated according to the user’s reputation information and datacap request, and matching will be processed automatically. The specific allocation and matching strategy will be published on this website. The code of this system software will be open sourced in the filecoin community.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
using a hardware wallet. 

```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
1. The matching system ensures that the client's datacap is used distributely to different storage entities, so that the malicious party has no incentive to illegally use the datacap;

2. All the user's basic information and apply records will be required to be signed with their private key, and these records will be unvealed publicly;

3. Evidence of abusing datacap will also be unvealed publicly;

4. The reputation and punishment mechanism of the deal matching system will ensure that the client will suffer corresponding losses if he does evil;
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
1. Please sign a specific piece of data with your private key, so that we can verify your identity in filecoin;

2. Please fill in the legal person's name, ID card and other basic information, and perform real-name authentication (for example, using Alibaba Cloud’s real-person authentication service)；

3. What is your application scenario?

4. Do you agree to sign a declaration of compliant use of datacap

The above information will be synchronized in [repository](https://github.com/filecoin-project/filecoin-plus-client-onboarding) to keep a complete record

```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
1. All clients' deal data can be tracked in the matching system;

2. The matching system will ensure that datacap will not be over-allocated to the same entity

3. if a client make a datacap deal with storage entities which is not asigned by the matching system, it may be punished according to a specifc rules

4.The reputation module may implement penalties to clients and miners accordig to their behaviors, such as datacap reduction, datacap slashing, and miner matching restriction;

```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
We will design an open source system to store deal reputation information and basic client information in a distributed and irreversible manner, including but not limited to datacap allocation decisions;

The user handle the registration, login, edit the basic information, submits the datacap request and other actions by signing with its private key. All key information are recorded by the matching system. Anyone can obtain these information from the macthing system;

By establishing contacts with credible industry entities, introducing a data source credibility mechanism, and establishing a quantifiable data screening mechanism, the subjective and untrustworthy factors in datacap allocation are reduced as much as possible, so that all datacap allocation records are public and cannot be tampered

```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
in github or filmatch system

On the basis of the previous statement, all information is recorded in the matching system, and the information is public and transparent. Since all participant's information is associated with a specific entity, doing evil will directly reduce its reputation value, so each Participants will not do evil.

The matching will push the key information, such as datacap allocation records、deal records and penality records to [repository](https://github.com/filecoin-project/filecoin-plus-client-onboarding), and provide a website for all parties to view.

```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
N/A
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
N/A
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
N/A
```

**Comment by dkkapur** [comment]
Hi @waynewyang - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1CEj1m1_xRvey0JtXAC09ixcxWIOwT2Gldk66NQb5yWI/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 2.2.

**Comment by waynewyang** [comment]
@dkkapur thanks for your reply.
1 the first issue, How many followers on your blog? Could this serve as an amplification platform for the work you are doing in the Fil+ ecosystem?
 - The current blog is mainly my personal blog, with 100+ followers，This doesn't look like much，We hope to create a better filecoin application-level entrance by fil-match system
 
2  the second issue, https://github.com/wusirdcenter/filmatchup/blob/master/doc/reputation.md
In the reputation system, our initial thoughts hope to incorporate off-chain data to get closer to the actual market. This is only a preliminary outline, I think further thinking is needed.But first, it should include factors such as the success rate of transactions on the chain and the stability of miners.

**Comment by dkkapur** [comment]
@waynewyang - thanks for sharing. Based on this, Allocation Plan was bumped to a 5. 

The final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 2
- Unrounded score: 2.4

Link to rubric: 
https://docs.google.com/spreadsheets/d/1CEj1m1_xRvey0JtXAC09ixcxWIOwT2Gldk66NQb5yWI/edit?usp=sharing

**Comment by dkkapur** [comment]
@waynewyang - based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of 100 TiB. In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm that the region of operation for client applications you will focus on is [Greater China Region]

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

> * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

> * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

> * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**Comment by dkkapur** [comment]
@waynewyang - awaiting your response to the above before proceeding with next steps with the RKH. Thanks!

**Comment by waynewyang** [comment]
> @waynewyang - based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of 100 TiB. In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:
> 
> 1. Please confirm that the region of operation for client applications you will focus on is [Greater China Region]
- ACK
> 2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.
> 
- ACK
> > * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship
> 
- ACK
> > * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.
> 
- ACK
> > * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.
> 
- ACK
> > * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.
> 
- ACK
> > * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.
> 
- ACK
> > * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.
> 
- ACK
> 1. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.
- NA 
> 2. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.
- ACK
> 3. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.
- Ledger address： f1lxlgiariqqfd7fqn7pvjt3azvwzly3eyyztrqmi

and @wjywood is our team member who is response for notary system and issue.

**Comment by dkkapur** [comment]
@waynewyang thanks - for the applications that will come in through GitHub (https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues), do you want those assigned to your GitHub handle or @wjywood?

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1lxlgiariqqfd7fqn7pvjt3azvwzly3eyyztrqmi
#### Datacap Allocated
> 100TiB

**Comment by waynewyang** [comment]
> @waynewyang thanks - for the applications that will come in through GitHub (https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues), do you want those assigned to your GitHub handle or @wjywood?

Hi @dkkapur pls assigned @wjywood ,thank you very much:)

**Comment by wjywood** [comment]
@dkkapur @waynewyang

**Comment by wjywood** [comment]
@dkkapur @waynewyang  I will take over this part of the work, thank you for your continued support.

**Comment by dkkapur** [comment]
@wjywood - please ping me in Filecoin Slack as well so I can add you to the right channels! Thank you :)

**Comment by dkkapur** [comment]
Looks like this address still needs to be initialized on chain to be granted notary status. Pinged you in Slack with additional details!

**Comment by galen-mcandrew** [comment]
@wjywood Did you get the message Deep sent in slack? Were you able to initialize the address (f1lxlgiariqqfd7fqn7pvjt3azvwzly3eyyztrqmi)?

**Comment by wjywood** [comment]
@Galen @Deep Kapur, we have initialized the address(f1lxlgiariqqfd7fqn7pvjt3azvwzly3eyyztrqmi).




https://filfox.info/en/message/bafy2bzacec4pm5duiwnjedg4mo3haftqtmbli6vzoaticmf5xw2yc2ekxcdmg








在 2021年8月19日 ***@***.***> 写道：


@wjywood Did you get the message Deep sent in slack? Were you able to initialize the address (f1lxlgiariqqfd7fqn7pvjt3azvwzly3eyyztrqmi)?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by galen-mcandrew** [comment]
Thanks for clarifying! I'll check what's happening on our side, we may need to re-send the approval messages to the root key holders. I'll get back to you here with an update!

**Comment by wjywood** [comment]
@galen-mcandrew the address(f1lxlgiariqqfd7fqn7pvjt3azvwzly3eyyztrqmi) is still invalid.  is there anything i can do?

**Comment by galen-mcandrew** [comment]
@waynewyang & @wjywood , can we confirm this is cleared and you are able to make DataCap allocations? If so, we'll close this issue

**Comment by wjywood** [comment]
@galen-mcandrew

**Comment by wjywood** [comment]
@galen-mcandrew  it's working now, we greately appreciate your help! https://filfox.info/en/message/bafy2bzacedcr3v3lusq6zpfepy5w47hetqt5shgwj27rs7n5wibgchg4oo54o

**Comment by galen-mcandrew** [comment]
Great! Let us know if you need more assistance! You can also reach us on Slack in the fil-plus and fil-plus-notaries channels.
