### ISSUE TITLE
Modification: Notary Rubric - Refactoring definitions for leveling in "In-protocol reputation"

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/notary-governance#18]
## Issue Description
Currently the leveling for "In-protocol reputation" has a minimum time requirement for L1 of 1 year. Given the stringent conditions for the Industry Reputation section, it is highly likely that a number of qualified notaries will score 0s across the board. For this specific criteria, it seems that the time constraint ends up being the biggest filter - while we have a number of qualified notaries that have made contributions over the last year, many of them have not contributed for OVER 1 year. 

##  Impact
This should have a minimal impact on the overall scoring of a notary and their application, but refactoring the L1 condition of this row will increase the likelihood of applicants getting at least a 1 for the "Industry Reputation" section, instead of a 0. 

## Proposed Solution(s) 
Change the L1 condition for the "In-protocol reputation" section to be defined as greater than 6 months instead of 1 year.

## Related Issues
Other issues affecting Industry Reputation: 
https://github.com/filecoin-project/notary-governance/issues/23#issue-750109815
https://github.com/filecoin-project/notary-governance/issues/24#issue-750120276
https://github.com/filecoin-project/notary-governance/issues/22#issue-750104402

**Comment by s0nik42** [comment]
I think for most of the miner folks, the real engagement is correlated to  the announcement  of spacerace. At that time we started to see an impressive acceleration on the volume of messages on slack, and community contributors really showed up. Miners invested a lot to get the proper hardware. Software developper had to allocate times to upskill their teams.  In all these cases,  individual or companies have to think about ROI (as for time than material) which is most of the time on a few years. 6 months is probably a good Threshold at least for the first batch.

**Comment by jnthnvctr** [comment]
Given this has been open for a week and we see some agreement - I'm going to surface to the slack channel once more, and with no other suggestions draft a PR reflecting this change.
