### ISSUE TITLE
Interstellar Storage

### ISSUE THREAD

**Issue by oceanyiren** [filecoin-project/notary-governance#181]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name:Colin Chen
- Affiliated Organization: Interstellar Storage (Shenzhen) Network Technology Co., Ltd
- Website / Social Media:WeChat Official account: Star Storage Shenzhen
- On-chain Address to be Notarized:f3shhfnkmar43s2lik7vvps6nod5som6nln5zoxehshgbhz6kcy35dzclfq4rgjsugy7cpvkmff5x4bgquexaq
- Region of Operation: Greater China
- Use case(s) to be supported: General
- DataCap Requested:100 TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
I have helped support many outstanding community members.Recently, we have assisted the peers to incubate 17 nodes, which are running stably, and the computing power keeps growing.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
I prefer not to disclose.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
1. Replied some miners' problems from time to time in the community and the community, and solved related difficulties. When I received the thanks from the miners, I was very moved.
2. Advocate people to weaken the ranking and focus on the correct value of Filecoin mining investment -- input/output ratio.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
1. Participated in the early test before RESTET, and gave the official test feedback (declare: the test was to pull branches by myself and merge PR; It's not an official privilege.)
2. Assisted the official in code review and pre-upgrade test of PR twice.
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Interstellar Storage (Shenzhen) Network Technology Co., Ltd. is an innovative technology enterprise with IPFS technology research, storage server sales, hosting operation and maintenance services as a whole. It is an industrial cluster enterprise with distributed storage industry as the main body and data storage and application ecology as two wings. It is a service-oriented enterprise with block chain platform and nodes.
Company was founded in 2019, a few years time, interstellar storage (shenzhen) accumulated several petabytes/day of work force resources and FIL fields of various high quality resources, based on the now service node number + 30, we are not content to just become a little beneficiaries, and challenge to be a contributor to advance, to become FIL whole industry chain industry service providers, We will deeply and thoroughly pursue the value of blockchain, and hold up and achieve bigger and more dreams with the heart of sincere achievement and the attitude of whole-hearted and whole-life.
Country of registration: China
Size: 50 to 100 people in a team
Founded in 2019
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://mp.weixin.qq.com/s/HX9znScsmNhg4OXNz1LPfQ
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
None
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
None at this time. 
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
The advanced strategy is to set thresholds with different levels of trust.
As a standard practice, for relatively small amounts of DataCap(gigabyte scale), the goal is to make the process relatively easy -- higher thresholds require more scrutiny.

In making allocation decisions, the following factors will be taken into account:
Reputation of the organization
Size of allocation
Frequency allocation
Safety precautions
Transparent customers
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Currently, none -- however, our goal is to allocate the limited data sets I have (during this beta) to different customers to achieve early key use cases :(1) a common data set with high trust, clarity, and ease of maintenance; (2) Excellent Slingshot team; (3) Web3 data.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Enables the key for the address assigned to DataCap to be protected on the hardware wallet.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
This may vary depending on the size of the allocation.
For higher levels of allocation, more attention will be paid to the quality of the customer, the amount of attention they intend to spend on Datacap, and the acceptance of the overall principles of the process.
In general, I expect due diligence on public data sets to find strong evidence that they are well maintained and have a high reputation in their field.
The outstanding Slingshot team will be active participants in the Filecoin community and on a high growth/production track.
Web3 data is a key DAPPs with an active and growing user base.
In the process, I'm going to share some basic strategies for clients to consider when making storage transactions.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
The plan is to try to match the requested information to the number of DateCaps requested.
Is it clear how assigned datacaps are handled?
How is the distribution planned?
The reason for this arrangement?
How to give us feedback on the result of processing?
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
In the initial phase of this testing, the process will follow our customer intuition and good intentions, but we plan to invest in build technology to help achieve a robust, secure and practical process.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
All allocation decisions will be made publicly -- and all communications will be made through repositories and issue tracking.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All assignment decisions will occur publicly
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None
```

**Comment by dkkapur** [comment]
Hi @Firefly2020-cloud - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1Gf7uq0u337i_5dOFQYKC_3cTpPyZCXOckUV284P95ck/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial score is: 0.9.

**Comment by dkkapur** [comment]
@oceanyiren, the final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 1
- Unrounded score: 0.9

Link to rubric: 
https://docs.google.com/spreadsheets/d/1Gf7uq0u337i_5dOFQYKC_3cTpPyZCXOckUV284P95ck/edit?usp=sharing
