### ISSUE TITLE
Modification: [ notary-governance/notaries/templates] - [ Update since to last rubric]

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/notary-governance#182]
## Issue Description
The last rubric is modified at December 4th, 2020.
We have some discussion after that. 
Please check the related issue part.

## Related Issues

https://github.com/filecoin-project/notary-governance/issues/74
https://github.com/filecoin-project/notary-governance/issues/78
https://github.com/filecoin-project/notary-governance/issues/25

**Comment by dkkapur** [comment]
@flyworker - please suggest any changes to existing rubric in the coming 2 weeks for the next election cycle if you have any ideas! Thank you!
