### ISSUE TITLE
Tengsheng Technology Co., Ltd

### ISSUE THREAD

**Issue by skm-cike** [filecoin-project/notary-governance#184]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information

- Name:  Lu Hua
- Affiliated Organization:  Tengsheng Technology Co., Ltd
- Website / Social Media:  http://www.tsara-ipfs.com/
- On-chain Address to be Notarized:  f3urflxhfpy3nekk66opsfmb5ae5t42zrdd2anet2z2krdhaliadcxs5aobpucsl3mgeyup6xxgukweiom2z2a
- Region of Operation: Greater China
- Use case(s) to be supported:  User Content，Media & Entertainment
- DataCap Requested: 100TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment

Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

```
We are filecoin storage miners. In the testing stage, we have been following up on filecoin, focusing on slack and optimizing the code. And developed a storage website using filecoin for storage.
```

### Stake Exposure

Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

```
IPFS Force Miner ID: f070730,f0700033,f016563,f054120,f042896,f02421
```

### In-protocol Reputation

Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

```
In the test phase, we release bug information on slack, contribute to the code repair and optimization, and reply to some other questions
```

### In-protocol Security

Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 

```
In the test phase, we release bug information on slack, contribute to the code repair and optimization, and reply to some other questions
```

### External Reputation

Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

```
Name: Tengsheng Technology Co., Ltd
Organizational nature: Private limited liability company (LTD)
Country of Registration: China
Established: September 2017
Sichuan Tengsheng Technology Co., Ltd., established in March 2017, is a network technology company engaged in software development, information system integration services, data processing and storage, server manufacturing and hosting, and Internet data services. It mainly focuses on the application of blockchain, participates in the Internet business, and serves the society with the concept of customer-centered, demand-oriented and service-oriented.

Sichuan Tengsheng science and Technology Co., Ltd. has set off a prairie fire with stars to ignite our ambition, and has a tough heart to shorten the distance between you and me. Adhering to the high-tech as the entity, it provides blockchain application solutions and data storage solutions for many large enterprises, individuals and groups. In the process of realizing the ecological construction of blockchain, it embodies its own value, achieves the maximum win-win cooperation, and has won wide approval from all walks of life.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

```
Please answer here.
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

```
http://www.tsara-ipfs.com/
```

### Use Case Diversity

(Optional) Any additional information you'd like to share about the use case(s) you plan to support?

```
https://www.jinse.com/news/blockchain/762964.html
```

# Allocation Plan

### Allocation Strategy

How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.

```
It is used to provide personal storage service test for users
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 

```
Our own development and release process
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
We will have a dedicated team responsible for data security 
```

### Client Due Diligence

How will you vet your Client to ensure they are spending that DataCap responsibly?

```
We need to investigate and understand clients detailed. Clients need to clarify how the DataCap will be allocated, build a fair mechanism, and store all operation history and information in database for review and tracking.

We are preparing the following questions to vet our client:
- Basic clients information, project information and progress;
- Why they apply the DataCap?
- Client credit rating information;
- Client security evaluation;
- Client DataCap allocation quota;

The above questions will be calculated to obtain a comprehensive score. Clients whose score and credit are lower will not be allocate DataCap.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 

```
1. Customers are required to submit DataCap usage report
2. Regularly review the use of DataCap
3. Establish an online credit system leveraging the audit system. 
4. Clearly define the rules of reward & punishment. Any violation is tracked and would impact the credibility of the client. 
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?

```
We believe that open and transparent distribution rules, and strict and pragmatic execution are important factors to ensure that there will be no over-allocating DataCap to a single entity. All allocation processes will be publish online, and distributions that are too centralized will not be allowed.
 
```

### Bookkeeping Plan

Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?

```
All allocation decisions will be made publicly -- and all communications will be made through repositories and issue tracking.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 

```
Yes
```

### Past allocation 

Have you previously received DataCap to allocate before? If so, please link to any previous applications.

```
NO
```

Cumulatively, how much DataCap have you previously successfully allocated? 

```
NO
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 

```
NO
```

**Comment by dkkapur** [comment]
Hi @skm-cike - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1bTLkqg6rP_-XR9fWI41Ru_UStG6NKr89_5YSVJSsHGo/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial score is: 1.0.

**Comment by dkkapur** [comment]
@skm-cike, the final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 1
- Unrounded score: 1.0

Link to rubric: 
https://docs.google.com/spreadsheets/d/1bTLkqg6rP_-XR9fWI41Ru_UStG6NKr89_5YSVJSsHGo/edit?usp=sharing
