### ISSUE TITLE
Notary application of origin pool

### ISSUE THREAD

**Issue by lamborghiniandy** [filecoin-project/notary-governance#185]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Andy Guo
- Affiliated Organization: Origin Pool
- Website / Social Media: ipfsorigin.com
- On-chain Address to be Notarized:
- f3xbo6oze2rcr3a4wqmypsn3ymfhzmg4dag2sazpr32cniybjdptmsezk4czb6wb2vuzmukftfnuebca7o3s7q
- Region of Operation: [North America, South America, Europe, Africa, Greater China, Asia-GCN, Oceania]
- Greater China
- Use case(s) to be supported: [Please select from [here](/notaries/templates/README.md#definitions)]
- Not limited to IPFS ecology, but also plan to use in the Big data services and CDN use case.  We have the experience of providing p2p cdn services to big internet companies in China like Tik tok, Kuaishou，Kingsoft Cloud, and some other streaming platform.
- DataCap Requested:1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
We started ipfs research in 2018, and came back to catch up with the filecoin again in 2019. We went through all of the testnet. 
Here is some of our thinking about ipfs-cluster in 2018. 
https://canx.me/posts/ipfs-cluster-considered-unnecessary/
We passed all the testnet :
Testnet1|     Testnet2|     Spacerace     |
T017267|     T01030  | T02417,T017273|
Co-developed a decentralized netdisk with Blockcasting Cloud in slingshot. (Slingshot registration ID: 676715867.)
### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Miner ID | Collateral | Currently avaiable| Vesting overtime|
---------- |-----------|---------------------|-------------------|
f02417     | 18529	|          101	        |         10983
F040665	| 201165	|          1957	        |        148705
F062619	| 142443	|          1154	        |        90786
F0112667|   63847	|          1317	        |          45104
F0118799|    1279	|           631	        |          673
F0119146|    1665	|           14	        |          793
F0435971|    83624	|          115	        |         10711
F0764901|    74029	|         10079	        |         2801
F0137594|    47954	|         289	        |        20660
F0396149|     14212 |         4254	        |         4152
F0503010|   184018	|           87	        |         29768
F0154335|    96685	|         103	        |         10551
F0153078|    20931	|           33	        |          6652
F0155049|   385390	|         1785	        |        103668
F0155050|    220033|          2371             |	  63941
-----------|----------|--------------- ------|--------------
### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

We continuously propagate ipfs in Beijing from 2019. Beijing is the most important city in China, but we are the solely one mining company located in Beijing. In the Oct. 2020, while many miners complained about protocol labs, we wrote quite a lot of articles to explain the filecoin economic model and spoke in public place to support PL. We tried to help maintain PL. reputation in China's community in that time, while many miners tried stroke at the beginning of mainnet launch. 
Besides, we co-developed a decentralized net disk in Slingshot( ID: 676715867) with Blockcasting Cloud. (https://github.com/litianc/slingshot/blob/master/participants/BlockcastingCloud.md )

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
In 2018,  some of our codes were merged. For example: 
https://github.com/btfslib/go-libp2p-quic-transport/commit/944de2ea4fec3bbab65d9d36577b7128142b361a
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
We are aiming to become the biggest mining pool of filecoin, despite now the pool cannot cross the public network. We registered in China. The number of our employee is about 60. We started with ipfs from Mar, 2018.   
We earned a good reputation among our clients as well. 
Also, we maintain good relationship with Langchao, one of china's largest cloud storage provider. 
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://www.ipfsorigin.com/
Named officer: 
Andy Guo CEO, ex Node Capital (one of the biggest crypto fund of China)  Director of Investment;
Hover Fang CMO, ex CEO assitant of 21 Vianet ( Nasdaq listed company);
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.btcfans.com/flash/id-42242
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We plan to do something with our ally company to test the storage and retreival on p2p cdn network.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.

In order to allow DataCap to allocate more adequately and to increase the value of the data provided by applicants, we classify applicants, adjust applicant levels, and adjust the DataCap quota ratio in stages.

Applicants are classified into three parts: 70% of the DataCap quota is used for applications by enterprises across the society, 20% for applications by well-known Internet companies, and 10% for data storage by institutions including scientific research institutes and public welfare organizations. Among them, well-known Internet companies and public institutions have separate quotas. Because of the early days of DataCap quotas, the market is immature. We will take the initiative to obtain valuable applicants. Secondly, we have many such applicants who have cooperated. Such applicants can represent China's Internet. At the enterprise level, they have a reputation in China and even the world. We introduce this kind of applicant data into file coin, which will be very helpful for the ecological landing of file coin. At the maturity stage of DataCap quotas, all quotas will be fully market-oriented.

Applicant grade adjustment: The basis of applicant grade adjustment is the value of the applicant's data, but at the same time, referring to the applicant's reputation, the grade weight index is set. The value of data is an important indicator for the adjustment of grade weight. It is evaluated from the data type, data source, frequency of being called, and the speed of data addition. The data type accounts for 25%, the data source accounts for 25%, and the data is called frequency. It accounts for 40%, and the rate of data addition accounts for 10%. The Notary Public Evaluation Committee is responsible for the grade adjustment of applicants and is responsible for the results.

From the beginning of the applicant's application for DataCap quota, we file and track the applicant, including: (i) the legality of the applicant, company documents such as business registration, business license and other government-issued documents to verify their business rights and Existence; (ii) the applicant’s brand and social reputation; (iii) the value of the applicant’s data. In addition, the authenticity of the information provided by the applicant is very important. If any illegal or fraudulent behavior is found, the applicant will be disqualified directly.

Adjust the DataCap quota ratio in stages: The quota is tentatively adjusted in four phases, and the proportions of the four phases are 30%, 30%, 20%, and 20% respectively. The customer quota in the next period will be adjusted according to the customer level of the previous period. Applicants who meet the requirements will get DataCap quota, and those who do not meet the requirements will be disqualified.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap?
```
Uphold the openness and transparency of the application process and maintain the credibility of notaries. The brief internal process is as follows:
1. Email application. The applicant initiates an application to us through official e-mail. The main content is the introduction of the applicant, the introduction of the value of the stored data, the reasons and plans for participating in the application, and other content that can prove the applicant's strength and attitude towards the application. We will start the review process after receiving the email;
2. Pre-audit. Our "Notarization Evaluation Committee" will pre-qualify the above-mentioned application to confirm whether the applicant has business 3. Rating. Applicants will be graded according to the results of the pre-assessment, and DataCap will be granted based on the results of the assessment.
```
How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Third-party identity verification is a good solution, and we also consider setting up multiple identity verification mechanisms; secondly, we can adopt a multi-signature method to ensure the security of the private key.

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
The verification process will be divided into three stages to ensure the efficient use of DataCap.

Before distribution
1. Pre-review of submitted information
2. Clarify the applicant's detailed usage plan
3. Due diligence, about 7 days
4. Applicant's rating and preliminary DataCap allocation opinions are given

During allocation
1. A DataCap distribution agreement will be signed to clarify the rights and responsibilities of both parties.
2. Allocate DataCap based on the applicant's rating

After distribution
1. Use spot checks to verify the authenticity and value of DataCap to ensure the correct use of DataCap
2. Establish DataCap usage tracking mechanism, and optimize DataCap distribution and usage
3. If the applicant has any violations of DataCap distribution, we will take measures to stop further distribution, even
```  

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
We will not ask customers to fill out lengthy questionnaires, but first elicit the customer's layout and thinking about DataCap through a few simple questions, and then propose targeted questions based on the number of DataCaps requested and the answers provided by the customer.
Several opening questions such as:
1. What is the original source of the stored data, and in what format?
2. Has your organization obtained DataCap before? What is the current usage situation?
3. Is it convenient to describe in detail your plan to use DataCap and the transaction information created?

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
We must understand the details of the customer's distribution plan and continue to track the customer's distribution records to DataCap to ensure that their words and deeds are consistent. If you find that the customer has a single storage, and give customers diversified storage suggestions, in fact, we don't have to worry too much about the customer distributing DataCap in violation of regulations, because we adjust the DataCap ratio in four phases.
In reviewing the distribution of DataCap by the client, we can review by the internal notary jury, or encourage community members to participate in external review, and reward fil for community members for their contributions.

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Regardless of customer allocation or internal management, we will keep files. In the future, we will consider uploading the allocation pair record to github to make the allocation and decision-making relatively open and transparent. Of course, in the early days, we did not intend to publicly distribute and file the contents of customers to avoid leaking customer privacy, but accept the review of the filecoin/ipfs governance community or protocol laboratory.

If anyone has any doubts about the notary, they can raise a question to our notary jury or apply to the filecoin/ipfs governance community for our review. We will maintain an open attitude to the questioner's investigation results. If the questioner thinks the circumstances are serious, a hearing can also be initiated.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
The principle of openness and transparency is based on the premise of customer privacy, so we will publicize the general allocation decision in the github repository, but will not disclose the details to reduce the impact on customers. So we will have it publicly and privately.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None.
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None.
```

**Comment by dkkapur** [comment]
Hi @lamborghiniandy  - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1vk0skcqZhJYqR98sMR7HAUd05zy-61kqwGY2-h56Z7A/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.4.

**Comment by dkkapur** [comment]
@lamborghiniandy, the final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 1
- Unrounded score: 1.4

Link to rubric: 
https://docs.google.com/spreadsheets/d/1vk0skcqZhJYqR98sMR7HAUd05zy-61kqwGY2-h56Z7A/edit?usp=sharing
