### ISSUE TITLE
Notary Application : Nicklas Reiersen / TechHedge

### ISSUE THREAD

**Issue by Reiers** [filecoin-project/notary-governance#186]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Nicklas Reiersen
- Affiliated Organization: TechHedge
- Website / Social Media: www.filecoin.no - (under construction) Slack: @reiers
- On-chain Address to be Notarized: f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq _<- Updated_
- Region of Operation: Norway, Europe
- Use case(s) to be supported: any
- DataCap Requested: 50 TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
TechHedge - Not incorporated. TechHedge was initially just a investment group interested in tech, 4 members. 
We found IPFS years ago and been using it frequently ever since. We fell in love and invested in Filecoin under the ICO. 
Now we have converted a house into a DC and are committed to help out in anyway we can. 
- minerID : f022352
- Active member in Community since Nov 2019. 
- Participated in SR1 / SR2 Orbital burn
- Participating in MinerX
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
6000 FIL
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- Proud and active MinerX member
- Actively participating and helping out in the Filecoin Community.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
Added issues on GitHub. 
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
TechHedge - Investments, Marketing, Networking, Data Center, Web Design. 
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website : http://www.filecoin.no
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
-
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Nothing
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
Defining thresholds with varying degrees of trust.
Higher the request, Higher the scrutiny

Several factors will be considered when making allocation decisions: 
Reputation of organization
Scale of allocation over a certain period of time
Security considerations
Transparency of Client
Client engagement to respect guidelines :
	- Process
	- Delegation
	- Contractual terms. 
	- etc…
Sucess of a Probation period for new client (described below)
Public or Private Data
```

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
No. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Separate node with a cold storage wallet - or a ledger. 
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
- Asking for commitment and transparency from the client
- Phasing 
- Approbation phase : 2TiB
- Verify the process is understood from the client and correctly apply
- Allocate More + Audit iteration (5TiB max)
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
 - Yourself , e.g. include links to social media / news mentions etc
 - Your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
 - Type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. 
 - public data vs private data etc
 - Your relationship with the data, especially with regard to copyright
 - How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
 - Have you already ask datacap to another notary that have been accepted or rejected.
 - Do you run a storage miner ?
 - How much data are you considering storing to your own miner ?
 - Please describe the nature of the relationship with this miner especially if you've got any interests in storing these miners ?
 - Will you agree to share here all the CIDs related to the datacap ?
 - Did you already have datacap from another notary ?
 - Address confirmation
 
If the data is private, I ask much more information and authorization from the client to audit the data unencrypted.
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
I ask the client to publish all the deals to the GitHub repo. Then I go through all deals, verify they are correct, and calculate the % of allocation per miners.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
For transparency purpose, I plan to provide all the allocation decisions in public via a GitHub repo. I will also agree to align the process the other notaries and the community; keeping in mind the processes we put in place have to be efficient. 
I will answer to any audits requests. 
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
For transparency purpose, I provide all the allocation decisions in public via a GitHub repo. I will also agree to align the process the other notaries and the community. 
Private allocation will need more tooling and tracking that are not here yet. Depending on the volume of such requests I may consider accepting private requests.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
-
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
No.
```

**Comment by dkkapur** [comment]
Hi @Reiers - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1a6nGXwuqSC8I9P-G9RINXUYL9ORrPsrvZhAzh5EaOY4/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.2.

**Comment by dkkapur** [comment]
@Reiers, can you confirm you will be using https://github.com/filecoin-project/filecoin-plus-client-onboarding or is there a different repo / place to track your client applications?

The final scores therefore for this election cycle will be:
- Rounded Final Allocation Amount: 1
- Unrounded score: 1.2

Here is the link to the updated rubric: https://docs.google.com/spreadsheets/d/1a6nGXwuqSC8I9P-G9RINXUYL9ORrPsrvZhAzh5EaOY4/edit?usp=sharing.

**Comment by Reiers** [comment]
**Confirming** that I will use https://github.com/filecoin-project/filecoin-plus-client-onboarding) for client applications. 
@dkkapur

**Comment by Reiers** [comment]
_I need to change the "On-chain Address to be Notarized", I didn’t know we had to use ledgers._ 

**I will update it tomorrow.**

**Comment by dkkapur** [comment]
@Reiers - based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of: 100 TiB. In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm that the region of operation for client applications you will focus on is [Europe]

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

> * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

> * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

> * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**Comment by Reiers** [comment]
# Accepting and Confirming to be a Fil+ Notary

**1. I confirm the region of operation will be in Norway, Europe.**

**2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.**

> Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship.

**minerID:** f022352
**Owner:** f1rw76pc3bg2obkzgz4zb62nssjq4szwia6vb5vly
**Worker:** f3uwqu37dt23c5kijeacqgqb3unk364fzprl4zcyjfrow53uwwcy2dhyue423pvxa24xsvlphk7a7awvyfchdq
**Commit:** f3uuyrd6sx3rr6l7orum32b635ltiqwofte62baf2n5ox6vbews3omomqezsyiy6qouzxtvis2wtg6z3s3qq6a
**Precommit:** f3uqltfzgoauastv6hltgcjhf7y74jj5vevpy7a2hwsrnv6sxzwkpy3pdjzzgwqd7pv75mn77clwztqx62fqwq
**Post:** f3vst2mrbgn7lxos4sibg74n5itzzyl4kkqp47pgfgcdub7dv5f5l64krzqu5izsckpvzuigzwhk7pnrja4t7a

**_All wallets above are being used in the miner operation._** 

> Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

**- Agreed**

> Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

**- Agreed**

> No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

**- Agreed**

> Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

**- Agreed**

> Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

**- Agreed**

> Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

**minerID: f022352**

> Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

**I confirm and will.** 

> Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**Ledger wallet:** `f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq`

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### Datacap Allocated
> 10TiB
