### ISSUE TITLE
Notary Application : Filecoin Foundation 

### ISSUE THREAD

**Issue by tinkmk** [filecoin-project/notary-governance#187]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Megan Klimen
- Affiliated Organization: Filecoin Foundation
- Website / Social Media: https://fil.org/ 
- On-chain Address to be Notarized:
- Region of Operation:  EU/NA 
- Use case(s) to be supported: Humanities most important open and public data, as well as official Filecoin affiliated growth initiatives such as Slingshot or Discover
- DataCap Requested: 1 PiB

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
I am one of the founders of the Filecoin Foundation. As an organization, the [Filecoin Foundation](https://fil.org/about) is an independent organization dedicated to supporting the growth and long term success of Filecoin.  The Foundation was also the first beta notary for Filecoin Plus, as well as a notary for Europe in the first round of notary selections where @philippbanhardt represented the Filecoin Foundation and distributed 100TiB of Data Cap, 

I have been with the Filecoin Foundation, and a part of the Filecoin ecosystem since July 2020.  
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

```
100 million tokens, per the vesting [schedule](https://coinlist.co/filecoin). 
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
The Filecoin Foundation is an independent organization dedicated to supporting Filecoin, an open source, decentralized storage network designed to preserve humanity’s most important information.The Filecoin Foundation facilitates governance of the Filecoin network, funds critical development projects, supports the growth of the Filecoin ecosystem, and advocates for Filecoin and the Decentralized Web.

As a founder and officer of the Filecoin Foundation I spent the majority of my time working towards the long term sustainable development of the Filecoin community. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
The Filecoin Foundation worked with Protocol Labs to run the security audit for Venus, and provided funding for this audit.  The Foundation has spent the last several months recruiting and hiring a security lead to facilitate the transition of Filecoin's Bug Bounty program to the Foundation.  The Foundation has put in place contracts with other members of the ecosystem to support the development of additional implementations of the Filecoin protocol in order to support the security and smooth functioning of Filecoin as a whole. 
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
The Filecoin Foundation is an independent organization dedicated to supporting Filecoin, an open source, decentralized storage network designed to preserve humanity’s most important information.The Filecoin Foundation facilitates governance of the Filecoin network, funds critical development projects, supports the growth of the Filecoin ecosystem, and advocates for Filecoin and the Decentralized Web.

The Filecoin Foundation was founded in 2018 is registered in the US. 
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://fil.org/ 
https://twitter.com/FilFoundation
https://www.linkedin.com/in/megan-klimen/
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We will exclusively support (1) open data sets (high trust, unambiguous, and easy to maintain), that truly feed into Filecoin's mission of being the foundation for humanities most important information, and (2) support strategic growth initiatives for the Filecoin project as a whole. Across all use cases we expect they foster decentralization across the entire network.

The mission of the Filecoin Foundation is to ensure the long term success of the Filecoin Network. Through our work with members of the Filecoin Ecosystem the foundation has a unique understanding of the reliability of ecosystem partners. The Filecoin Foundation can apply data cap through these trusted relationships to ensure onboarding of useful data to the Filecoin Network.  
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
We are using an application modeled after the one used by https://github.com/filecoin-project/notary-governance/issues/29# 

The allocation requirement is planned to be divided into 5 categories from L1-L5 by the data volume. The larger data volume clients request, the more strict requirements will be. We want to inspect these clients by reputation, data, diversity and decentralization, allocation strategies, track record, etc.

Following table shows the scoring system:
https://docs.google.com/spreadsheets/d/1zZzleFFhuQh__7vsBxfNdJUd874uzBSPffvP1wjrRQ4/edit?usp=sharing

In addition, we plan to share this table with clients and also work with applicants to understand their respective scores. 

Furthermore, we plan to use our knowledge of teams needing data cap through our work with them in programs such as our developer grant program, our ecosystem development  programs such as Starling Labs, to help them understand how to become verified clients and help facilitate their onboarding of useful data to the filecoin network. 

```

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
We would like to facilitate as much useful data getting on to the network as is possible, so we feel like the important criteria is ensuring that we have systems to build trust with a client, which can come from allocating smaller amounts of data cap, rather than targeting a specific data cap. We will always be working to maximize the amount of useful data getting on to the network as long as that data is 1) coming from trusted clients and 2) working towards the long term viability of the Filecoin ecosystem. We hope to use the trusted relationships we have built with other members of the filecoin ecosystem to onboard client data with a high degree of certainty that the data meets these criteria. 

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The address that will be allocated DataCap will have its keys be secured on a hardware wallet.  Notaries acting on behalf of the Filecoin Foundation have been extensively vetted by the foundation. 
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
Clients who apply for DataCap for a project associated with other Foundation services will have the allocated data evaluated in conjunction with their other milestone check ins. 

Clients who apply for DataCap from the general public will have submitted a detailed proposal and have been vetted according to the criteria in the above rubric 

https://docs.google.com/spreadsheets/d/1zZzleFFhuQh__7vsBxfNdJUd874uzBSPffvP1wjrRQ4/edit#gid=0

Clients behavior will be compared to the plan they had submitted and if there are significant deviations, especially with publicly available data, the foundation will investigate.  Long term we expect to utilize tooling that will automate verification of on chain data vs what was proposed in the clients initial application. We also expect the community to flag any broad cases of wrong doing and to work with our dispute management system. Additionally those found to have misallocated data will be strongly discouraged from engaging in other forms of Filecoin Foundation support. 

```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
The plan is to try and keep asks for information matched with the amount of DataCap being requested. Some of the questions, but not all, can be found [here](https://github.com/filecoin-project/notary-governance/blob/main/notaries/templates/sample-client-application.md) or see here for an application during the Filecoin Plus beta: https://github.com/keyko-io/filecoin-clients-onboarding/issues/62. 
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
We plan to invest in building technology that can help manifest a process that is robust, secure and pragmatic. We also expect all clients to make public their deal transactions with miners.

```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
All allocation decisions will happen in public in the following repository - all communications will also take place through the repository and the issue tracking.
For the level of allocation of quantity, I decided to divide it into five levels as shown in the table above. The higher level of audit will be more rigorous.

```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will happen in public in the following [repository](https://github.com/keyko-io/filecoin-notaries-onboarding)
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
@philippbanhardt acted as a representative of the Filecoin Foundation in the following previous application:
https://github.com/filecoin-project/notary-governance/issues/54
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
100 TiB
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
No
```

**Comment by dkkapur** [comment]
Updated formatting for readability

**Comment by dkkapur** [comment]
Previous applications:
* https://github.com/filecoin-project/notary-governance/issues/54
* https://github.com/filecoin-project/notary-governance/issues/4

**Comment by dkkapur** [comment]
Allocation track record from last round:
- 91+ TiB allocated in past round across 18 client applications
- list of client applications approved: https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues?q=is%3Aissue+label%3Astate%3AGranted+assignee%3Aphilippbanhardt+is%3Aclosed
- Client applications and usage of datacap: 
![image](https://user-images.githubusercontent.com/2343218/120025032-ec019300-bfa4-11eb-9b51-dcd4a989e778.png)

DataCap received by miner IDs:
| Notary Name         | Miner ID | DataCap received in GiB | % of Notary's DataCap Grant |
|---------------------|----------|-------------------------|-----------------------------|
| Filecoin Foundation | f019002  | 16.00000525             | 0.02%                       |
| Filecoin Foundation | f053088  | 26.00000853             | 0.03%                       |
| Filecoin Foundation | f060693  | 2.000000656             | 0.00%                       |
| Filecoin Foundation | f02620   | 112.0000367             | 0.11%                       |
| Filecoin Foundation | f087256  | 1.000000328             | 0.00%                       |
| Filecoin Foundation | f02387   | 896.0002939             | 0.88%                       |
| Filecoin Foundation | f022142  | 702.0002303             | 0.69%                       |
| Filecoin Foundation | f080480  | 4.000001312             | 0.00%                       |
| Filecoin Foundation | f015927  | 496.0001627             | 0.48%                       |
| Filecoin Foundation | f062353  | 1604.000526             | 1.57%                       |
| Filecoin Foundation | f03325   | 32.0000105              | 0.03%                       |
| Filecoin Foundation | f0116445 | 1541.000505             | 1.51%                       |
| Filecoin Foundation | f0111007 | 32.0000105              | 0.03%                       |
| Filecoin Foundation | f010505  | 32.0000105              | 0.03%                       |
| Filecoin Foundation | f061959  | 564.000185              | 0.55%                       |
| Filecoin Foundation | f047419  | 656.0002152             | 0.64%                       |
| Filecoin Foundation | f022352  | 2147.000704             | 2.10%                       |
| Filecoin Foundation | f089228  | 2232.000732             | 2.18%                       |
| Filecoin Foundation | f0103665 | 1.000000328             | 0.00%                       |
| Filecoin Foundation | f010479  | 2952.008781             | 2.88%                       |
| Filecoin Foundation | f019362  | 48.00001574             | 0.05%                       |
| Filecoin Foundation | f08240   | 32.25001058             | 0.03%                       |
| Filecoin Foundation | f010088  | 96.00003149             | 0.09%                       |
| Filecoin Foundation | f063869  | 1830.0006               | 1.79%                       |
| Filecoin Foundation | f010446  | 16.00000525             | 0.02%                       |
| Filecoin Foundation | f01278   | 1454.000477             | 1.42%                       |
| Filecoin Foundation | f060072  | 142.0000466             | 0.14%                       |
| Filecoin Foundation | f0161542 | 5056.157908             | 4.94%                       |
| Filecoin Foundation | f01240   | 1104.000362             | 1.08%                       |
| Filecoin Foundation | f02401   | 2080.000682             | 2.03%                       |
| Filecoin Foundation | f0228712 | 1856.000609             | 1.81%                       |
| Filecoin Foundation | f01276   | 1120.015992             | 1.09%                       |
| Filecoin Foundation | f066102  | 496.0001627             | 0.48%                       |
| Filecoin Foundation | f08403   | 672.0002204             | 0.66%                       |
| Filecoin Foundation | f064218  | 1520.000499             | 1.49%                       |
| Filecoin Foundation | f079815  | 3.000000984             | 0.00%                       |
| Filecoin Foundation | f040332  | 32.0000105              | 0.03%                       |
| Filecoin Foundation | f079817  | 98.00003214             | 0.10%                       |
| Filecoin Foundation | f034544  | 1341.00044              | 1.31%                       |
| Filecoin Foundation | f08399   | 224.0000735             | 0.22%                       |
| Filecoin Foundation | f030649  | 33.00001082             | 0.03%                       |
| Filecoin Foundation | f0364957 | 1792.000588             | 1.75%                       |
| Filecoin Foundation | f034545  | 1277.000419             | 1.25%                       |
| Filecoin Foundation | f088125  | 224.0000735             | 0.22%                       |
| Filecoin Foundation | f019104  | 1318.312932             | 1.29%                       |
| Filecoin Foundation | f010617  | 928.0003044             | 0.91%                       |
| Filecoin Foundation | f079285  | 64.00002099             | 0.06%                       |
| Filecoin Foundation | f019399  | 40.00001312             | 0.04%                       |
| Filecoin Foundation | f0157535 | 96.00003149             | 0.09%                       |
| Filecoin Foundation | f0116436 | 1764.000579             | 1.72%                       |
| Filecoin Foundation | f0118317 | 816.0002676             | 0.80%                       |
| Filecoin Foundation | f07998   | 1964.000644             | 1.92%                       |
| Filecoin Foundation | f023977  | 2.000000656             | 0.00%                       |
| Filecoin Foundation | f021961  | 24.00000787             | 0.02%                       |
| Filecoin Foundation | f010491  | 322.5001058             | 0.32%                       |
| Filecoin Foundation | f09848   | 2028.000665             | 1.98%                       |
| Filecoin Foundation | f019551  | 366.00012               | 0.36%                       |
| Filecoin Foundation | f0226324 | 2368.000777             | 2.31%                       |
| Filecoin Foundation | f0118330 | 1671.000548             | 1.63%                       |
| Filecoin Foundation | f03624   | 112.0000367             | 0.11%                       |
| Filecoin Foundation | f0167505 | 2432.000798             | 2.38%                       |
| Filecoin Foundation | f02576   | 1040.000341             | 1.02%                       |
| Filecoin Foundation | f053229  | 1488.000488             | 1.45%                       |
| Filecoin Foundation | f01272   | 2.000000656             | 0.00%                       |
| Filecoin Foundation | f065280  | 14.00000459             | 0.01%                       |
| Filecoin Foundation | f019100  | 40.00001312             | 0.04%                       |
| Filecoin Foundation | f023467  | 2175.000713             | 2.13%                       |

**Comment by dkkapur** [comment]
Hi @tinkmk - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1IUsiBpZ87Vn2SRhkHWfZ2pB6Zou9q5OqcA5GnJOjB5w/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial score is: 3.2.

**Comment by dkkapur** [comment]
@tinkmk, the final scores therefore for this election cycle are:
- Rounded Final Allocation Amount: 3
- Unrounded score: 3.2

Link to rubric: 
https://docs.google.com/spreadsheets/d/1IUsiBpZ87Vn2SRhkHWfZ2pB6Zou9q5OqcA5GnJOjB5w/edit?usp=sharing

We need a final confirmation on region before proceeding. EU/NA?

**Comment by tinkmk** [comment]
Hi @dkkapur, The Filecoin Foundation would like to stay in the EU region, since this is the region where we have done our previous notary work we think that we think we would be more effective in this region than moving to NA, so we can use the expertise we've developed allocating data cap for EU clients in this next round.

**Comment by dkkapur** [comment]
@tinkmk - based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! Per your application and the scored rubric, you will be receiving an allocation of 1 PiB. In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm that the region of operation for client applications you will focus on is [Europe]

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

> * Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> * Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

> * Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> * No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

> * Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

> * Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

6. In the case of the Filecoin Foundation - there is an existing allocation of ~8.5 TiB that was stated to not be allocated in the future. Can you confirm this will remain the case, and we can request the RKHs to remove that previous allocation? If not, you will only receive 1024 - 8.5 = 1015.5 TiB in this cycle.

**Comment by dkkapur** [comment]
@tinkmk - awaiting your response to the above before proceeding with next steps with the RKH. Thanks!

**Comment by tinkmk** [comment]
Please confirm that the region of operation for client applications you will focus on is [Europe]

**Confirming Europe as region of operation**

Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles.

Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.
**I agree to the above**

Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

**I agree to the above statement** 

No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

**I agree to the above statement** 

Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

**I agree to the above statement** 

Community Governance Participation: It is expected that Notaries make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, learnings, and input.

**I agree to the above statement** 

Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

**Agreed**

(If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a**

In the case of the Filecoin Foundation - there is an existing allocation of ~8.5 TiB that was stated to not be allocated in the future. Can you confirm this will remain the case, and we can request the RKHs to remove that previous allocation? If not, you will only receive 1024 - 8.5 = 1015.5 TiB in this cycle.

**I can confirm this is the case**

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### Datacap Allocated
> 1PiB

**Comment by dkkapur** [comment]
This grant seems to have gone through correctly and should not be in Error status. Fixing this now!

**Comment by dkkapur** [comment]
@tinkmk - can you please confirm the correct GitHub account we should be using to assign incoming client applications to the Filecoin Foundation?

**Comment by dannyob** [comment]
Hi @dkkapur -- I'll be managing the Filecoin Foundation datacap request process. My github account is https://github.com/dannyob 

Thanks!
