### ISSUE TITLE
Hi @ipfscn  - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:

### ISSUE THREAD

**Issue by ipfscn** [filecoin-project/notary-governance#192]
Hi @ipfscn  - thanks for submitting your application to be a Notary! The initially scored rubric can be found here:
https://docs.google.com/spreadsheets/d/1apBrsF7rtewIoYYqFRKGDUh-Xy-4taRDuwCAuAimd8I/edit?usp=sharing

Please take a look at the notes (column I) and share any relevant additional details here in comments so we can update your score ideally within the next 2 days.

Your initial unrounded score is: 1.5.

_Originally posted by @dkkapur in https://github.com/filecoin-project/notary-governance/issues/166#issuecomment-855381636_

**Comment by dkkapur** [comment]
@ipfscn - closing this out to track all comments and responses in the original issue instead!
