### ISSUE TITLE
Modification: https://plus.fil.org/ - Allow applying with addressing holding datacap

### ISSUE THREAD

**Issue by andrewxhill** [filecoin-project/notary-governance#205]
## Issue Description

The filecoin address field will block submission if the supplied address already has datacap. This isn't a blocker on the latest network anymore.

<img width="537" alt="Screen Shot 2021-07-07 at 11 14 02 AM (1)" src="https://user-images.githubusercontent.com/370259/125126519-18362680-e0b0-11eb-9fa5-647e90393af6.png">

## Impact

Would allow people to apply for extra datacap on the same address.

## Proposed Solution(s)

Remove blocking functionality in the web form.

**Comment by galen-mcandrew** [comment]
Per @ialberquilla and Keyko team, this was addressed July 7th. Closing as resolved
