### ISSUE TITLE
Notary status - retrying for 12ships Foundation

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/notary-governance#208]
Original application here: https://github.com/filecoin-project/notary-governance/issues/180

Attempt to sign status on chain resulted in ExitCode 16. Looks like this address was used as a verified client and so could not be signed as a verifier/Notary on chain. 

Re-proposing allocation here.

**Comment by dkkapur** [comment]
New address proposed from @IreneYoung

`f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq`

Confirming that this is not showing up on Fil+ dashboards.

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### Datacap Allocated
> 100TiB

**Comment by galen-mcandrew** [comment]
@IreneYoung looks like this message has cleared the root key holders! I'm seeing address f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq listed in the app as an approved notary at this time.
