### ISSUE TITLE
Governance call to take place on Jul 20 at 3pm UTC 

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/notary-governance#209]
Our next Governance will take place on Jul 20 at 3pm UTC / 8am PT.

To ensure we are covering the most pressing topics and questions, opening this issue to collect your input on anything that should be added to the agenda.

Please add items into the comments below to ensure they are included on the next call.

Zoom details:
https://protocol.zoom.us/j/93414028246
Passcode: 554538

Community Calendar
https://calendar.google.com/calendar/u/1?cid=Y19rMWdrZm9vbTE3ZzBqOGM2YmFtNnVmNDNqMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t

**Comment by Broz221** [comment]
@dkkapur It's June 20 or June 22

**Comment by dkkapur** [comment]
@Broz221 this one was Jul 20, sorry about that

**Comment by dkkapur** [comment]
Recording: https://www.youtube.com/watch?v=D-p9EGpWcRs
