### ISSUE TITLE
Notary Application: China PPIAAS Technology Co.,Ltd

### ISSUE THREAD

**Issue by tangkefu** [filecoin-project/notary-governance#216]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: ppiaas
- Affiliated Organization:   ppiaas data
- Website / Social Media:    http://www.ppiaas.com
- On-chain Address to be Notarized:  f2xze7jbv5ukfrphsfp45a3iebyjb4j45adxuw5ja
- Region of Operation: [Greater China]
- Use case(s) to be supported: [Web 3.0 / Decentralized Applications, Web 2.0 Applications, User Content, Scientific Data, Media & Entertainment]
- DataCap Requested: 100T

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```

Our core team founded in 2015,  focus on blockchain technology and fintech.
At the mid of 2020, we saw great value and potential of IPFS protocol and believed it to be the most likely project that could be implemented in business scenarios.
We create a company specialized in Filecoin project named ppiaas data (Shenzhen) Technology Co., Ltd. 
We have 70+ employee now,  and total sealed data is over 50PB.

https://github.com/ppiaas
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
The total FIL at stake is about 0.44M with the following 5 Miner

f0160870:  89,203
f0106363:  124,918
f0124923:  134,364
f068556:    34,943
f0130868:  54,581
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Our team PRs as follow:
https://github.com/filecoin-project/go-jsonrpc/pull/39
https://github.com/filecoin-project/go-jsonrpc/pull/40
https://github.com/filecoin-project/lotus/pull/4918
https://github.com/filecoin-project/lotus/pull/5261
https://github.com/filecoin-project/bellperson/pull/132
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
Na
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
PPIAAS(星宫数据) is located in Shenzhen China. we are committed to becoming the global leading D-IaaS clouding infrastructure provider. 
Our company focuses on the distributed storage ecology construction and the link between D-IaaS and the real application. 

Our company's core team is composed by technical backbones who are from well-known companies such as Huawei, and ZTE.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
http://www.ppiaas.com

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.jinse.com/news/blockchain/928837.html
https://www.zilian8.com/kuaixun/466070.html
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Scientific Data(AI training, geological data) 
VR Data(3d model and material)
User Content(personal user storage)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
The purpose of allocating the DataCap is to make sure clients use these DataCap in the right way.

For new clients, there will be offline investigation and discussion regarding who they are, what they will use filecoin as a storage to save, and how to do it, based on that, I would have the first judgement to qualify or not as verified clients.

For qualified clients, my allocation strategy emphasizes historical reputation and also the plan for new-required data investigation.
We plan to allocate DataCap with small incremental amount(<10%) 
We are also willing to use Filecoin Plus Registry to make all allocation in public.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
The whole application process should be open and transparent, we design the necessary internal processes follows：

1. Each applicant requesting DataCap is required to formally submit a written application (in pre-specified form) and other relevant supporting information to us for our review process to kick off;

2.A preliminary review of the foregoing application will be made by our internal “Notary Taskforce” to pre-qualify the applicant, who must be a serious and well-established business entity or non-profit organization having plausible data storage demands;

3.Each applicant failing the pre-qualification will be requested to provide additional information or be simply denied, as the case may be;

4.For the pre-qualified applicant, our “Notary Taskforce” will conduct a due diligence to scrutinize its legal standing, operations and data concerned; 

5.Based on the due diligence result, a rating will be performed by us for each business entity applicant in accordance with the preceding factors and criteria, following which we will assign a score to that applicant.  Rating for non-profit organization applicants will be dispensed with; and

6.We will resolve, in the form of a written decision, the denial or grant of requested DataCap allocation and (if granted) the amount of DataCap allocated, taking into account the applicant’s score (for business entity only) and data size concerned, and will then implement the same.

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will adopt various authentication solution in this verification process such as using multi-signature to control the allocation process. 

On the other hand，we will have some private keys that are stored in the hard wallet. on the other hand, we will set a multiple authentication mechanism (including check identity, review source of data and arrange for supervisor approval) to secure every step of DataCap allocation.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
We will reference the guidelines by 1st gen notaries and adapt their model to our own. 
Again we will most likely adopt strategy described in https://github.com/filecoin-project/notary-governance/issues/14#issue-747912777.

```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
1. What kind of data do you need to store and how much capacity do you need to store?
2. Can you show a demo data?
3. What kind of storage current you use, how much data was stored, and how much money was spent?
4. In what way will you evaluate the miner to decide whether to use him as your storage?
5. How many miners will you store the data, how to allocate it, and what factors will you consider?
6. Is it possible to make public the distribution records and the specific implementation?
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Periodical inspection and audit of DataCap usage
Use incentive mechanism: encourage clients to report unfair allocation
We will also develop a tool to randomly check all the clients' verified deals to make sure they are following the protocol.
 
Once our team complete the development of audit tool, we are happy to make it open sourcing and provide technical specifications or architecture docs, so other notaries can use it. This toll will require clients to post deal transaction in public, and FileCoin Community can audit data and storage deals once again.

```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Yes, all allocation decisions will be guided by the rubric publicly on Github.  
 Any challenges raised regarding allocation decisions should be discussed publicly, e.g. the Github repo.
If convincing justifications can’t be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions. 


```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
In public(tentatively on GitHub) in order to be supervised by FileCoin Community
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Na
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
Na
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
Na
```

**Comment by galen-mcandrew** [comment]
Hi @tangkefu Thanks for your application! You submitted an application to become a Notary, which may not suit your needs. Notaries act as stewards of the Filecoin Plus program, helping distribute DataCap to external clients. 

It sounds like you are interested in securing an allocation of DataCap for your own company/project, to then be used in sealing deals with storage providers. Is that correct?

If so, please read more about onboarding as a client here: https://github.com/filecoin-project/filecoin-plus-client-onboarding and you can find a notary here: https://plus.fil.org/

Let us know if we have misunderstood your request!

**Comment by tangkefu** [comment]
Hi @galen-mcandrew， We already build  application for some clients to storage  their application data.  Miner or Notary maybe the appropriate role for us,  so what something else we need to provider?
