### ISSUE TITLE
Modification: Notary Rubric - Refactor "External Reputation" and rename to "Organization Reputation"

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/notary-governance#22]
## Issue Description
In the current definition of External Reputation, the emphasis is on organizations that have reputations OUTSIDE of the Filecoin protocol. The original intent was to define reputation in such a way that captured an organization's reach in spheres outside of the protocol. The reasoning was that higher trust could be given to someone who had reputational risk outside of Filecoin - as abusing trust inside the protocol would have severe ramifications elsewhere. 

The current definition falls short, in that it does not provide a substantive definition in such a way that one can easily define the leveling. Further, given the exclusion of reputation inside of the Filecoin protocol makes it difficult to evaluate organizations who may have reputation both inside and outside the protocol based on their activities (e.g. a large scale miner). 

##  Impact
Without clear definitions here, the best choice is to bias towards a smaller DataCap allocation - leading to potentially artificially lower amounts of DataCap being awarded. 

## Proposed Solution(s) 
While a good set of objective definitions have not been defined, the spirit of what this was trying to capture is some sort of sizing of reputational stake for the organization in question. A proposed "gut-feel" leveling is suggested below, but this issue seeks community feedback on whether (1) this is a reasonable "gut-feel" definition, and (2) what better objective measures might be to create these buckets. 

L1 = smaller miners and less known
L2 (prevalence in Filecoin-adjacent communities) = Supranational, Fleek, Pinata, Infura
L3 (people in Web3 space will know about) = Polychain, Consensys
L4 (strong name in Web2 and Web3 but less known publicly) = Ethereum Foundation, Vimeo 
L5 (household names) = Andreseen Horowitz, Netflix 

Further, since the goal is no longer to filter on reputation outside of Filecoin, it is proposed that this criteria be renamed to "Organization Reputation".

## Related Issues
https://github.com/filecoin-project/notary-governance/issues/23#issue-750109815
https://github.com/filecoin-project/notary-governance/issues/24#issue-750120276
https://github.com/filecoin-project/notary-governance/issues/18#issue-750090784

**Comment by s0nik42** [comment]
+1 for small miners. You could also later on, take into accounts the overall contribution to the notary process/governance.

**Comment by jnthnvctr** [comment]
Would people be opposed to the "subjective" definitions, provided in the () above next to the levels - provided, there are anchoring examples?

**Comment by s0nik42** [comment]
I think for now, its clear enough
