### ISSUE TITLE
When will the next Notary applications open?

### ISSUE THREAD

**Issue by JKinGH** [filecoin-project/notary-governance#220]

**Comment by galen-mcandrew** [comment]
Hello! We are not currently running Notary elections, and anticipate having another election cycle in Q4 ’21. We’ll post about it in the #fil-plus channel of the [Filecoin community slack](https://filecoinproject.slack.com/archives/C01DLAPKDGX), and in the [Notary Governance Repo](https://github.com/filecoin-project/notary-governance).

You’re also welcome to join the [Community Governance calls](https://calendar.google.com/calendar/u/1/r?cid=Y19rMWdrZm9vbTE3ZzBqOGM2YmFtNnVmNDNqMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t) and meet other notaries, clients, and community members in the Fil+ ecosystem.
