### ISSUE TITLE
Next Governance Call: Sept 14 3pm UTC AND 11pm UTC

### ISSUE THREAD

**Issue by galen-mcandrew** [filecoin-project/notary-governance#226]
We will again have 2 Notary Governance call times this week, covering the same agenda but supporting more timezone attendance. These will occur at 8am PT // 3pm UTC AND 4pm PT // 11pm UTC, and you are welcome to attend both! These will be recorded, and video links will be posted here.

Agenda topics will include: program metrics and stats, high-level updates from last week's Design Summit including 6-month program goals, demo of new tooling and process for LDN's to support experiment as ratified in issue 217, potentially client presentations, and open discussion.

If you have items to add to the agenda, please comment below!

Zoom meeting details:
https://us02web.zoom.us/j/84281454216?pwd=NzVzT2lmYU5TalN3V2ZSM0R3NFRyUT09

Meeting ID: 842 8145 4216
Passcode: 828593

[Community Calendar](https://calendar.google.com/calendar/u/1?cid=Y19rMWdrZm9vbTE3ZzBqOGM2YmFtNnVmNDNqMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/discussions/227

**Comment by choibs95** [comment]
I will be attending for potential client presentation representing NHN KCP Corp. 
Looking forward to it.

**Comment by galen-mcandrew** [comment]
Link to youtube video here: https://www.youtube.com/watch?v=m4WVrWP-68w

Enjoy!
