### ISSUE TITLE
Modification: Notary Rubric - New criteria for Industry Reputation, "Individual Reputation"

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/notary-governance#24]
## Issue Description
In the current rubric there is no option to provide credit to a notary who is applying as an individual. This unintentionally penalizes prospective notaries who apply as individuals instead of applying as a broader organization. 

##  Impact
Fixing this will mean that qualified individual notaries will not be penalized for not applying as a part of a larger organization. 

## Proposed Solution(s) 
Given that an individual is inherently riskier than an organization - it is proposed we cap this leveling to be in the range of L1-L3. Note this is not mutually exclusive from organizational reputation - and organizations who apply (and specifically the person who files the application) may submit details to be ranked on these criteria. 

For this condition, we propose that the L1 criteria for "In-protocol reputation" be met AND the following criteria: 
- L1: Has access to 2+ social media accounts which individually have audiences > 500 where they will post publicly about their status as a notary if approved
- L2: Has access to 2+ social media accounts which individually have audiences > 1000 where they will post publicly about their status as a notary if approved
- L3: Has access to 2+ accounts on social media accounts which individually have audiences > 10000 about their status as a notary if approved

The reasoning is that by meeting the L1 definition of "In-protocol reputation" it can be guaranteed there is some minimal alignment with Filecoin as a network. By defining different thresholds of reach there can be some accountability from an individual reputation if a notary is to act maliciously. 

## Related Issues
Other issues affecting Industry Reputation:
https://github.com/filecoin-project/notary-governance/issues/24#issue-750120276
https://github.com/filecoin-project/notary-governance/issues/22#issue-750104402
https://github.com/filecoin-project/notary-governance/issues/18#issue-750090784

**Comment by s0nik42** [comment]
We should agree on  key elements to include in the communication, like  a link to a page presenting the Notary / Fil+  / etc...

**Comment by jnthnvctr** [comment]
I agree!

I think the basics that we'd want included: 
1) A statement about being accepted as a Notary (literally just a sentence)
2) A link to explain what a Notary is / Filecoin Plus
3) A link to where they will be accepting incoming requests from clients
