### ISSUE TITLE
Notary Application: MathWallet

### ISSUE THREAD

**Issue by ericfish** [filecoin-project/notary-governance#26]
# Notary Application

## Core Information
* Name: MathWallet
* (Optional) Affiliated Organization: MathWallet
* Website / Social Media:  mathwallet.org
* On-chain Address(es) to be Notarized: f1e2bq5cr3ipfzv4otv3k65em6gupqd7atiiaxbri
* Region of Operation:  Asia
* Use case(s) to be supported: general, blockchain data, web3 dapp
* DataCap Requested: 100TB

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

```
MathWallet's main contribution and work in Filecoin Ecoystem includes:
* Has supported Filecoin since Testnet, and is one of the earliest wallets to support Filecoin testnet. See: http://blog.mathwallet.org/?p=1637
* Developed Filecoin App wallet. See: https://mathwallet.org/filecoin-wallet/
* Developed Filecoin custodial wallet system and Swap system.
* Runs two open Filecoin sync nodes for community use.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

```
N/A
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow.

```
* There are currently over 7,000 Filecoin wallets in MathWallet, with a cumulative total of over 15,000 transfers.
* We have collected and sorted various Filecoin eco-applications through our MathDAppStore for users to find and use. See: https://mathdapp.store/?blockchain=filecoin
* We provide a relevant API of Filecoin wallet, which helps DAPP developers to aggregate relevant functions. See: http://doc.mathwallet.org/en/filecoin  for developers' integration function
* We have written various Filecoin wallet operation tutorials to spread relevant knowledge to the community
For English, see: http://blog.mathwallet.org/?tag=filecoin
For Chinese, see: http://blog.mathwallet.xyz/?tag=filecoin
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side).

```
N/A
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

```
* MATH is a multi-chain and cross-chain blockchain assets hub whose products include:
MathWallet (supports 50+ blockchains including BTC, ETH, Filecoin etc and 1.2M users); MATH VPoS Pool, MathDAppStore, MathStaking, MathCustody, MathNFT, MathChain, MathHub, MathDEX, MathID, MathPay, and others.
Our investors includes Fenbushi Capital, Alameda Research, FundamentalLabs, Multicoin Capital.
* Registered country: Singapore
* Organization Size: 30 people
* Date of establishment: November 2017
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

```
https://mathwallet.org
https://twitter.com/mathwallet
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

```
Official Website: https://mathwallet.org

News:
* MathWallet Raises $7.8 Million From Alameda Research and Multicoin
https://www.financemagnates.com/cryptocurrency/news/mathwallet-raises-7-8-million-from-alameda-research-and-multicoin/
* Fenbushi Capital Roundtable Series 3: MathWallet COO Eric talks about the role of Wallet in Filecoin ecosystem:
https://mp.weixin.qq.com/s/pdHYXpEDViSgjaVYXsCp2w
* The development history of wallets in China:
https://www.theblockbeats.com/news/19632
* MathWallet and Hurun Report reached strategic cooperation:
http://news.iresearch.cn/yx/2019/01/282439.shtml

Social Media:
MathNews https://news.mathwallet.xyz
MathBlog (CN) http://blog.mathwallet.xyz
MathBlog (EN) http://blog.mathwallet.org
Twitter https://twitter.com/Mathwallet
Weibo https://weibo.com/2803855662/
Medium https://medium.com/@mathwallet
Bilibili https://space.bilibili.com/526464306
Youtube https://youtube.com/c/MathWallet
Bishijie https://i.bishijie.com/home/math/dynamic
Bihu https://bihu.com/people/397093
Jinse https://www.jinse.com/member/88928
Tuoluocaijing https://www.tuoluocaijing.cn/columns/author311997/
Chainnews https://www.chainnews.com/u/748716797548.htm
Huoxing24 https://www.huoxing24.com/userCenter/360b0e7fc498439f8ade74568f96c393
Odaily https://www.odaily.com/user/2147493170
Xueqiu https://xueqiu.com/u/5676556297
Ccvalue https://www.ccvalue.cn/column/%E9%BA%A6%E5%AD%90%E9%92%B1%E5%8C%85
Jianshu https://www.jianshu.com/u/e0bab1403fe8
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?

```
We will support a variety of use cases to ensure diversity. Based on the multi-chain and cross-chain nature of MathWallet, we will focus on use cases for blockchain data storage, particularly in IPLD related application scenarios.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.

```
In making the plan, we will consider the following factors:
* Reputation of the organization
* Scale of allocation
* Frequency allocation
* Safety Precautions
* Transparency of customers
```

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap?

```
Our allocation priorities are:
(1)	public datasets that are easy to maintain;
(2)	Blockchain data;
(3)	Web3 data.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
The key allocated to the DataCap is protected on the multi-signature hardware wallet.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?

```
* For due diligence on public datasets, we will look for strong evidence that they have a good maintenance foundation and a high reputation in their field.
* For due diligence on blockchain data, we will investigate the authenticity and feasibility of their requirements based on our experience in the development of multi-chain wallets.
* For due diligence on Web3 data, we will use our experience in operating DappStore to investigate the DApp team, product planning and implementation.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them?

```
We will review the request according to the list of questions linked below:
https://github.com/filecoin-project/notary-governance/blob/main/notaries/templates/sample-client-application.md
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?

```
We will ask Client to seperate DataCap to different entity.
We will review the Client status and if Client is not improperly over-allocating DataCap to a single entity, we will reject the Client's applicaiton during the next allocation.
We will publicize all requests and assignments which are subject to community’s supervision.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?

```
All allocation decisions will be in the following Github repository, and all questions will be traceable:
(https://github.com/mathwallet/filecoin-notaries-onboarding) 
We will have focal point to answer any questions through email and telegram group.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both?

```
All allocation decisions will happen in public, at the following repository:
(https://github.com/mathwallet/filecoin-notaries-onboarding)
We will have focal point to answer any questions through email and telegram group.
```

### Past allocation
Have you previously received DataCap to allocate before? If so, please link to any previous applications.

```
None
```

Cumulatively, how much DataCap have you previously successfully allocated?

```
None
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations?

```
None
```

**Comment by dkkapur** [comment]
@ericfish - thanks for applying to be a Notary! Your initial scored rubric can be found here: 
https://docs.google.com/spreadsheets/d/12hYLDzuMI2i0qm6yK_ThB5TtBAtAJjvLnx3D5cqz6f0/edit?usp=sharing

A few follow-ups:
1. Can you confirm your region of operation? You listed Asia, but currently we are separating this into Greater China Region and Asia-GCN (Asia minus the Greater China Region). Notaries should have 1 region of operation only. 
2. I have added a few comments to the rubric (column H) for the section "Concreteness of Allocation Plan". Would appreciate additional details based on these comments so we can appropriately score your application (scores should increase with more detail provided).

**Comment by jnthnvctr** [comment]
@ericfish - can you confirm your region of operation?

**Comment by jnthnvctr** [comment]
Hi @ericfish  we have a tentative score for you, but requires confirmation of your region of operation: 

https://docs.google.com/spreadsheets/d/1WZzS2AGLTgLlNHUmNUKQEEBLObukVLLAb-zQMINKapw/edit?usp=sharing

Pending your response, the score is: 
Eligibility Score: 1
Unrounded Score: 1.3

**Comment by jnthnvctr** [comment]
Hi @ericfish    - as mentioned on the governance call yesterday, your team was in the top of your region for being a prospective Notary! Prior to confirming your role as a Notary, there are a few items that need to be affirmed: 

1. Please acknowledge the region of operation in which you tend to primarily focus: [Asia-GCN]

2. Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.

* **Upfront Disclosures**: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship. 

* **Promoting Client Best Practices**: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found [here](https://github.com/filecoin-project/notary-governance/issues/9).

* **No Self Dealing**: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

* **Operating in good faith**: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

3. Please list any addresses you are affiliated with below - stating the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt. 

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above. 

5. (If ready) - Please confirm the address that should receive DataCap.

**Comment by jnthnvctr** [comment]
Additionally, if you plan on being listed in the Filecoin Plus Registry - please confirm what information you'd like to have displayed below. Please note that public requests currently write to a public repository (and we can work with you to configure the requests as needed). 

"name": "Your Name",
"use_case": [
    "List",
    "of",
    "Use Cases"
],
"location": "EUR",
"github_user": "notaryc",
(optional) "website": "google.com",
(optional) "max_datacap_allocation": "100 GB", // To indicate to clients what size allocations you might support. 
(optional) "private_request": "false",                       // set as true if you plan on supporting private requests. 
(optional) "email": "youremail@a.com",                 // only needed if you are supporting private requests
"info": ""                                                                            // You can use this to share information with Clients about your allocation strategy / reqs

**Comment by ericfish** [comment]
@jnthnvctr 

1. Primarily focus region: Asia-GCN

> Upfront Disclosures

ACK.

> Promoting Client Best Practices

ACK.

> No Self Dealing

ACK.

> Operating in good faith

ACK.

3. We do not have any affiliations with any mining operations. We will disclose all client addresses if/when we get any in the future.

4. ACK!

5. Address: f1e2bq5cr3ipfzv4otv3k65em6gupqd7atiiaxbri


Filecoin Plus Registry Info:

"name": "MathWallet",

"use_case": [

"general",

"blockchain data",

"web3 dapp"

],

"location": "",

"github_user": "rayshitou",

"website": "mathwallet.org"

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f1e2bq5cr3ipfzv4otv3k65em6gupqd7atiiaxbri
#### Datacap Allocated
> 10TiB

**Comment by jnthnvctr** [comment]
hi @ericfish  - are you on the Filecoin slack by any chance? Would someone from your team be able to message @jnthnvctr  in that slack channel?

**Comment by ericfish** [comment]
@jnthnvctr my colleagure 'stone' will contact you on slack, thanks!

**Comment by jnthnvctr** [comment]
hi @ericfish  per my message in slack can you confirm this address is correct?

**Comment by jnthnvctr** [comment]
hi @ericfish  your colleague @ rayshitou has been in touch - following up with him and will ask him to comment here with the correct address when we have it!

**Comment by rayshitou** [comment]
@jnthnvctr our new address is:  f1snwd4w4y2fjwadkftcitcsnoerprlkrphn6kily

**Comment by jnthnvctr** [comment]
## Request Approved
#### Address 
f1snwd4w4y2fjwadkftcitcsnoerprlkrphn6kily
#### Datacap Allocated
10TiB
