### ISSUE TITLE
Notary Application: XnMatrix

### ISSUE THREAD

**Issue by ann-shin** [filecoin-project/notary-governance#27]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Ann Shin
- (Optional) Affiliated Organization: XnMatrix
- Website / Social Media: @ Dr.Ann Shin on the Filecoin Slack
- On-chain Address(es) to be Notarized: f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
- Region of Operation: North America
- Use case(s) to be supported: User Content, Scientific datasets, Media & Entertainment 
- DataCap Requested: 1 PB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_ 

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
As an individual, I’ve worked to help support a few prominent community members (notably Chainlink, Textile, & SpaceX). 
I’ve been a part of the Filecoin community since 2018. 
As an early preacher of FileCoin/IPFS, I joined XnMatrix Group. 
I am the founding consultant of Glacier Distributed Storage Laboratory and the senior consultant of Renren Mine right now. I take the latest IPFS information and bright future prospects to Chinese community and companies.

Here’s the link to the projects that we’ve invested in: https://ultrafundvc.com/portfolio
Interviewed by U-Channel TV, Blog Talk Radio, Tech Crunch Radio, Nigeria Financial Radio, World Talent Economy Forum...etc.
Spoke on major stages such as Block World, Malta Blockchain Summit 2018, AI Show Biz.... etc.
More recently, I’ve started to educate Filecoin in small groups in the Silicon Valley.

As an organization, XnMatrix Group built quite an extensive relationship with the Filecoin community since 2019.  We have sustained some contributions to the overall network. 
As a miner and researcher，we joined  the testnet, space race, slingshot, mainnet. 
Here is some gitlab issue we discussed about:
https://github.com/filecoin-project/lotus/issues/3928
https://github.com/filecoin-project/lotus/issues/4861
https://github.com/filecoin-project/lotus/issues/1824

In addition, we are deeply involved in the mining of filecoin. Our miner IDs are f02614, f09652, f010424, f03362, f020928, f039992 and more,  with a total computing power of 50 PB.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
So far, we hold total tokens more than 1MM FIL, of which 4,023 FIL is currently available, 843,753 FIL is locked as collateral, and 330,833FIL is vesting.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
I am a high-profile speaker in many blockchain forums in the Silicon Valley. 
I plan to host meetups virtually and offline once a month in future to educate everyone about decentralized storage and FILECOIN. 
Since April 2018, I've already spoken at numerous blockchain conferences (more to come):
10/31 Panelist https://www.eventbrite.com/e/corporate-innovation-global-venture-summit-tickets-48303847107
11/1-2 Jury Panel on startups with President of Malta https:// maltablockchainsummit.com/
12/10 Judge Panelist at Oracle: https://www.meetup.com/California-Software-Professional-Association-CSPA/events/255480942/
1/7/2019 Moderator: https://www.svfundingsummit.com/

And here’s my Linkedin profile: https://www.linkedin.com/in/gazillionaire/

IPFS has witnessed explosive development in 2020.
Now XnMatrix is the world's leading IPFS supplier with the leading IPFS mine pool.
XnMatrix can provide customers with one-stop storage services, including storage resource management, storage resource trading, and storage token trading across different block chains.
At the same time, XnMatrix provides decentralized cloud computing services based on the Web 3.0 infrastructure backboned by blockchain technology.

In the recent time, We participated in the AMA online meeting actively.
At the same time, we successfully held the 2020 Distributed Storage Summit in Chengdu. 
We are honored to invite @Keren from the Protocol Lab to give a keynote speech. Please check with @Keren who will be able to substantiate our contributions. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
We participated in the early testing before reset and gave the official feedback.
Leng Bo @coder-lb joined our IPFS business union as technical consultant early. 
We found some serious/critical bugs, such as
https://github.com/filecoin-project/specs-actors/issues/448 : The mining power is permanently dropped but there are no expired faulty sectors
https://github.com/filecoin-project/lotus/issues/1824 : We need to add Deadline for SubmitWindowedPoStParams
https://github.com/filecoin-project/lotus/issues/2204 : Index out of range issue of lotus-storage-miner proving info
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Organization: XnMatrix
Nature:  private company
Registration Country: HongKong, China
Established:May, 2020
Size: over 300 employees
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Homepage: https://www.xnmatrixs.com
Twitter: https://twitter.com/superxnmatrix?lang=en
WeChat Official Account: XnMatrix
Linkedin: https://www.linkedin.com/company/xnmatrix2020
Medium: https://pr-44637.medium.com/

My linkedin has more than 500+ followers. 
Our wechat official account has more than 1000+ followers. Our twitter has more than 1000+ followers.
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
XnMatrix is the world’s leading decentralized cloud computing platform, offers fully featured decentralized cloud/network resource services and computing power products to individuals and enterprises, to complement and leapfrog the centralized cloud computing in terms of lower cost, data privacy and security and digital asset liquidity.
We also optimize distributed storage efficiency in terms of hardware, software, algorithms, operation and maintenance, applications, etc. 
We provide integrated storage products and industry solutions for enterprises and industries.
It mainly includes ultra-low-cost computing power covering IPFS, cryptocurrency, AI, edge computing and other fields, as well as services derived from computing power requirements, including cloud computing account management, cloud computing APP SaaS service, cloud computing e-commerce platform PaaS service, cloud computing trading service, etc.

https://finance.yahoo.com/news/2020-distributed-storage-summit-ended-124500305.html
https://36kr.com/topics/836219830696069
http://www.cnr.cn/rdzx/cxxhl/zxxx/20201127/t20201127_525344968.shtml
http://www.chinanews.com/business/2020/11-20/9343298.shtml
https://www.businesswire.com/news/home/20200916005395/en/
http://prnews.techweb.com.cn/qiyenews/archives/188809.html
https://www.myzaker.com/article/5f73ee418e9f096d9936e298/
https://apnews.com/press-release/newswire/4190dd75a9d3a4cc6719ba648929b7bc
https://finance.yahoo.com/news/mr-wu-wenjie-chairman-xnmatrix-150000958.html
https://tech.sina.com.cn/roll/2020-09-04/doc-iivhuipp2523374.shtml
https://www.8btc.com/article/624455
https://mp.weixin.qq.com/s/i59KYMuh4nZIzsHslRoYGQ
https://mp.weixin.qq.com/s/n5zhW3DKzKAFxf5wV7ONgg
https://mp.weixin.qq.com/s/oTts2731hZoffHACe4TIOg
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We plan to support those use cases; the percentage depending on the variable circumstances of each scenario, frequency and requirements.
- 60% - Media & entertainment (video & music & game)
- 30% - User content (personal user storage，such as file, photo)
- 10% - Scientific datasets (Health data, AI training, Meteorology data) 
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
1. The DataCap will be mainly allocated to North American customers.
   Other regions Applications will enter the waiting queue.

2. We will classify customers based on their industry reputation and scale. 
   All customers wiil be divided into four categories:  top  team customers, medium team customers, small team customers, and start-up team customers. 
   The four categories of customers are allocated 40%, 30%, 20%, and 10% respectively.

3. The client classification rules are as [follows:](https://docs.google.com/spreadsheets/d/1O3daNeNiUcc1nLuqFPgLLs1MEVzLjB-lr4BKj0Es9rI/edit?usp=sharing)

4. In the initial stage of specific allocation, we will take out a small part (<10%) of each category for testing, and gradually establish a reputation mechanism (including incentive, punishment, supervision)

5. Each assignment will be used to evaluate the customer's reputation.
   For example, if a customer applies the DataCap which is valid and efficient, its reputation credit will increase.
   With higher credit, the customer can apply more DataCap (maximum increase 200%).

6. Throughout the allocation and use the DataCap, we will establish a corresponding review mechanism.   
   Good customer will benefit, bad customer will be punished. The quality of the customer will be optimized gradually.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Our internal processes rarely involve allocating DataCap target, amount or rate.
Most of the processes are external, which are open to the public.
The few internal processes, such as the collection of confidential information or the execution of due diligence, will be in private. 
Only when we are unable to verify the truth and legality of the information provided by the customer, the internal processes will be triggered.
In addition, some third-party tools may also be used to collect the information of clients from web.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hardware wallet will be used to store the keys for DataCap address.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
Generally, the higher DataCap is needs, the stricter the customer review. In the early stages, all customers must go through a rigorous process.
For individual customers, the verification of their identity will be verified through two parts, the account age and the account activity, which will prove that customers are valid users and not machines. 
In addition, some open third-party data, such as Weibo and WeChat official accounts, can also be used to verify online identities.
For organizational customers, we will set up a due diligence team and establish a complete review mechanism to ensure the reasonable allocation and effective use of the DataCap.
The following is the proposed due diligence procedure.
According to the customer level that requires due diligence, we need the following types of information. 
The review requirements for small-scale storage users are relatively simple, and users for large-scale storage will be strictly reviewed.

1. Basic information (small teams, start-up teams)
-Business license;
-Legal person related information, including: ID card, mobile phone number;
-Application with Legal person or agent’s signatures
-Use schedule for DataCap
-Materials or certificates that demonstrate ability and influence

2. Product operation information (top teams, medium teams)
-A list of related products.
-Users age, gender and other info.
-What are the popular product and services.
-Past and projected growth rates.
-Investigate how the product can be improved in the future and have new growth points.
-Research industry trends to understand whether the company's industry is growing or slowing down. Study the profitability of the industry.

After collecting and reviewing the above information, they will learn spend the DataCap reasonably and effectively.
We will make a training plan and release an online test for DataCap and Filecoin. Only clients who pass the test can apply the dataCap.
We will help customers match and recommend more suitable miners. We will provide clients more useful information about miners, such as failure rate, storage cost, safety, reliability, capacity, etc.

We mark the results of using DataCap as the feedback to influence the allocation in furture , thereby affecting customer behavior.
The incentive mechanism, punishment mechanism and supervision mechanism will make spending the DataCap responsibly and effectively.

1. incentive mechanism
If a customer applies the DataCap which is valid and efficient, its reputation credit will increase. With higher credit, the customer can apply more DataCap (maximum increase 200%).
We encourage customers to allocate DataCap to more new miners, and each new miner allocation will have additional incentives.

2. punishment mechanism
If a customer is found to be abusing data, it will be punished.The next apply will reduce 50%.
In particular, if the client and the miner cheat together, both of them will be added to the banlist.
Other clients can report unfair allocation.

3.supervision mechanism
As a Notary, we will develop a tool to randomly check verified transactions of all customers to ensure they comply with the agreement.
Also,we will use a series of incentive mechanisms to encourage other clients to report unfair allocation and allow them to monitor and  supervise each other.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
We will ask customers the following questions:
* What is your main business, the scale and when your organization was established?
* What data should the customer store? Is there any sensitive data or illegal data?
* What is your use case for the DataCap being requested?
* Which miners do you plan on allocating a DataCap? Why choose them?
* Will you continue to apply DataCap in the future?
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
We will monitor and track the use of DataCap strictly.
Each assignment will be used to evaluate the clients' reputation. 
We encourage customers to allocate DataCap to more new miners, and each new miner allocation will have some incentives.
Also, we will develop a tool to randomly check verified transactions of all customers to ensure they comply with the agreement.

If some problems are found, we will communicate and coordinate promptly. 
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
We will keep every detail record for all allocation decisions on Github, including time, amount, allocated customers, reason for judgment, etc.
Since all interactions are intended to occur publically, most of the allocation decisions should be self-explanatory.
Any challenges raised regarding allocation decisions should be discussed publicly, e.g. the Github repo.
If convincing justifications can’t be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date.
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders to resolve the dispute.
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will happen in the Github repository publicly.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None
```

**Comment by jnthnvctr** [comment]
Hi - we've taken a first pass at scoring your application here: https://docs.google.com/spreadsheets/d/1t4EHgP2PsjPJijuMzHd9a7LKZtwFSmP23SiN25ybMLs/edit?usp=sharing

Please take a look at the comments in column H - if you have questions please ask! If you make changes, please edit your original issue to reflect the updates!

Lastly, please be aware that some changes in the rubric may be approved which might affect your scoring https://github.com/filecoin-project/notary-governance/pull/36

**Comment by ann-shin** [comment]
Hi @dkkapur 
Thanks for your scoring. 

Firstly, let me reply your questions:
Row 13:
Xnmatrix group is a global company, our business is located in North America, China, Australia. Our North American subsidiary will focus our business on the North American market. Xnmatrix group will also give priority service to our North American partners. Therefore, we applied for North America first. So that，we changed our allocation strategy which will give priority to applications from North America. Other regions Applications will enter the waiting queue.

Row 21:
Yes, we will make a training plan (some paper materials, online course) and we will release an online test for DataCap and Filecoin. 
Yes, the customer classification will be a public process, and the rules are as follows https://docs.google.com/spreadsheets/d/1O3daNeNiUcc1nLuqFPgLLs1MEVzLjB-lr4BKj0Es9rI/edit?usp=sharing. 
We will help customers match and recommend more suitable miners.  We will provide customers with more useful information about miners, such as failure rate, storage cost, safety, reliability, miner size, etc. We believe that customers will be more inclined to local miners.

Row 22:
Yes, incentive mechanism, punishment mechanism and supervision mechanism will be some good ideas. You can view some details of the Client Due Diligence section.The mechanism will be improved and refined.

Row 23:
Yes, the plan is use the same tooling as the Filecoin foundation. 

I also updated the application to include more information, including time commitment, in-protocol reputation , in-protocol security, the detailed scoring system, mainly focus on the Allocationn Strategy and the Client Due Diligence. 

Please check these parts again.

Thanks!

**Comment by jnthnvctr** [comment]
Hi @ann-shin - we've taken a pass at scoring your application based on your updates: https://docs.google.com/spreadsheets/d/1IAiH1mgplrAdvwGac4IaAq6yuiKjJNmp6q3fRC1cK4k/edit?usp=sharing

Eligibility score: 2
Unrounded score: 1.7

**Comment by jnthnvctr** [comment]
Hi @ann-shin   - as mentioned on the governance call yesterday, your team was in the top of your region for being a prospective Notary! Prior to confirming your role as a Notary, there are a few items that need to be affirmed: 

1. Please acknowledge the region of operation in which you tend to primarily focus: [NA]

2. Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.

* **Upfront Disclosures**: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship. 

* **Promoting Client Best Practices**: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found [here](https://github.com/filecoin-project/notary-governance/issues/9).

* **No Self Dealing**: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

* **Operating in good faith**: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

3. Please list any addresses you are affiliated with below - stating the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt. 

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above. 

5. (If ready) - Please confirm the address that should receive DataCap.

**Comment by jnthnvctr** [comment]
Additionally, if you plan on being listed in the Filecoin Plus Registry - please confirm what information you'd like to have displayed below. Please note that public requests currently write to a public repository (and we can work with you to configure the requests as needed). 

"name": "Your Name",
"use_case": [
    "List",
    "of",
    "Use Cases"
],
"location": "EUR",
"github_user": "notaryc",
(optional) "website": "google.com",
(optional) "max_datacap_allocation": "100 GB", // To indicate to clients what size allocations you might support. 
(optional) "private_request": "false",                       // set as true if you plan on supporting private requests. 
(optional) "email": "youremail@a.com",                 // only needed if you are supporting private requests
"info": ""                                                                            // You can use this to share information with Clients about your allocation strategy / reqs

**Comment by zhaoleistar** [comment]
Hi @jnthnvctr

>1.Please acknowledge the region of operation in which you tend to primarily focus: [NA]

Yes, we are in NA zone.

>2.Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.

Upfront Disclosures: Confirmed
Promoting Client Best Practices: Confirmed
No Self Dealing: Confirmed
Operating in good faith: Confirmed

>3.Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

Atpool miner list: f02614,f03362,f09652,f010424,f020928,f039992,f0104654
The Atpool owner/miners and worker/controller addresses might change for security or other reasons, but the miner ID will keep the same.
All the miners are managed by XnMatrix and owned by investors.
If in the future we have relevant IDs to disclose, we will add them to this issue.

>4.Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

Yes, we will.

>5.Please confirm the address that should receive DataCap.

f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
I will start with the same repo as the Filecoin Foundation.
 
>6.Additionally, if you plan on being listed in the Filecoin Plus Registry - please confirm what information you'd like to have displayed below. 

"name": "Ann Shin/XnMatrix",
"use_case": [
"User Content",
"Scientific Dataset",
"Media"
],
"location": "NA",
"github_user": "ann-shin",
"max_datacap_allocation": "10 TiB",
"private_request": "false"

**Comment by ann-shin** [comment]
Hi @jnthnvctr

>1.Please acknowledge the region of operation in which you tend to primarily focus: [NA]

Yes, we are in NA zone.

>2.Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.

Upfront Disclosures: Confirmed
Promoting Client Best Practices: Confirmed
No Self Dealing: Confirmed
Operating in good faith: Confirmed

>3.Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

Atpool miner list: f02614,f03362,f09652,f010424,f020928,f039992,f0104654
The Atpool owner/miners and worker/controller addresses might change for security or other reasons, but the miner ID will keep the same.
All the miners are managed by XnMatrix and owned by investors.
If in the future we have relevant IDs to disclose, we will add them to this issue.

>4.Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

Yes, we will.

>5.Please confirm the address that should receive DataCap.

f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
I will start with the same repo as the Filecoin Foundation.
 
>6.Additionally, if you plan on being listed in the Filecoin Plus Registry - please confirm what information you'd like to have displayed below. 

"name": "Ann Shin/XnMatrix",
"use_case": [
"User Content",
"Scientific Dataset",
"Media"
],
"location": "NA",
"github_user": "ann-shin",
"max_datacap_allocation": "10 TiB",
"private_request": "false"

**Comment by dkkapur** [comment]
@ann-shin - if you plan on using the same repo as the Filecoin Foundation + want to use the same web app to manage Client applications, your address needs to be backed by a Ledger. Can you confirm that (1) you plan on doing this and your address is backed by a Ledger, (2) update your address with a Ledger-backed address, or (3) confirm that you don't plan on using the same web app tooling? I can then proceed with the final step of confirming you as a Notary. Thanks!

**Comment by jnthnvctr** [comment]
hi @ann-shin   - are you on the Filecoin slack by any chance? I see two ann-shins, would you be able to message me (@jnthnvctr ) there?

**Comment by ann-shin** [comment]
hi @dkkapur  @jnthnvctr,  confirmed that (1) the address  f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a  is backed by a Ledger.   
Thank you.

**Comment by jnthnvctr** [comment]
## Request Approved
#### Address 
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### Datacap Allocated
> 100TiB

**Comment by jnthnvctr** [comment]
hi @ann-shin  per my message in slack can you confirm this address is correct?

**Comment by XnMatrixSV** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceasldfbhnuquh23pj3vpftvbcd2bxp5oene3jgw2iv6ihexpvo5d2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasldfbhnuquh23pj3vpftvbcd2bxp5oene3jgw2iv6ihexpvo5d2
