### ISSUE TITLE
Notary Application: 1475 - Simon686

### ISSUE THREAD

**Issue by ozhtdong** [filecoin-project/notary-governance#29]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Simon686
- (Optional) Affiliated Organization: 1475
- Website / Social Media: 1475ipfs.com/@simon686-1475 on the Filecoin Slack
- On-chain Address(es) to be Notarized: f1a3up2i324yasakyge2gpt4ml3ipsjhk5z7qkxhi
- Region of Operation:  China
- Use case(s) to be supported: General
- DataCap Requested: 1 PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

GitHub handle:https://github.com/ozhtdong
Miner id： f01475

When I worked in UnionPay in 2016, I found IPFS protocol and started paying attention to PL.
At that time, I worked as big data analyst in UnionPay, which is a joint organization of China bank card established by People's Bank of China and with the approval of the State Council.
During the work in 2016, I looked up a large number of documents to seek the solutions of massive data storage security and customer privacy issues. Then IPFS came into my eyes, which can solve the centralization fault and make data storage safer and longer. Not only did I share IPFS with my friends but I also decide to introduce top talent to establish laboratory and start up business together. The laboratory members include mathematical scientist currently ranked 2.3% in the world's largest Kaggle, software and hardware development expert with over 15 years' experience, founding partner of IBC capital, blockchain ecosystem investor with the academic background of Tsinghua University, Peking University, Fudan University, University of Hong Kong and other famous schools and also with employment background of Baidu, Google and other high-tech companies. From then on, I devoted myself to the research of IPFS underlying protocol.
It is known to us all that PL created a decentralized storage network called filecoin in 2017. I had been involved in Filecoin community from the beginning of the establishment and participate with my friends in 2017 ICO of Filecoin.
Subsequently, I participated in the early testing before reset and gave the official feedback. During the DVnet, we found several major bugs, such as 100% block generation, drift attack, chain synchronization attack, etc.; during the testnet, we analyzed the reasons for infinite chain bug and manually targeted elimination of specific nodes bug and provide test-passed fix solution and key log analysis. For the most important implementations such as lotus and go-filecoin, we also contributed to them. （https://mp.weixin.qq.com/s?__biz=MzAwMTQ3NjczNQ==&mid=2247485007&idx=1&sn=34ec7c567dc2ac3d08dcd7d1c72a3526&chksm=9ad8575fadafde496aaceffb9acc02757118d014c3a8240f287a9ecadf23e03bff337b7df751&token=347207485&lang=zh_CN#rd）
We also poured attention to the confusion of some Chinese miners. As a result, we have established several IPFS Chinese ecological WeChat groups, and have responded to some miners' problems from time to time in the official community and WeChat groups to solve relevant difficulties. We also held many online AMA and offline salons to popularize and promote Filecoin. （eg: https://www.jinse.com/news/blockchain/765891.html）
Our contribution to ecology goes beyond that. 1475 block browser was developed for the clear overview of miners' status. 1475 fund was set up to invest in applications that are beneficial to ecology. 1475 cloud was created based on distributed storage. We will never stop on the contribution for IPFS-Filecoin ecology. （https://www.jinse.com/news/blockchain/897934.html）

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

1.3MM FIL at stake. Please kindly find the following worker of some of our miners:
f3vsw24ypdikc22g4kspqvn7ybg3wjp6zmje35wjtjqipittub2fu2bxkxwdxui4v2zzlc5cwij7ms3q5zoyha ,which is just around 30% of our total token.

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

After I devoted myself to underlying protocol in 2016, we established star ecology in order to let more people understand and support IPFS, at which a group of traditional stock investors who are interested in IPFS gathered. To promote IPFS, we established 1475 lab and 1475 ecology fund to invest in some ecology applications based on IPFS to support implementation of those applications. So far, we have 100k+ members (Evidence in: 
https://docs.google.com/document/d/1vyuSvXfxnXpACMSJqkgqxeqmusv4rDJXrrBCtr9A31k/edit) of star ecology. 1475 block, 1475 cloud (yun.1475ipfs.com) and other applications born for IPFS ecology. Meanwhile, we support many development teams of ecology application so that there will be more applications based on IPFS in the future.
With the emergence of more and more enthusiasts, we established several 1475 ecology WeChat Group and used our professional knowledge to answer some miners' questions in community and WeChat Group from time to time. Moreover, we held so many online AMAs, with the highest frequency of 26 AMAs per month. Offline salon activities are held regularly every Friday, and also 2-4 large-scale summits per month are held to share IPFS-Filecoin project. Therefore, we also won many rewards from the community such as the most influential enterprise of IPFS, IPFS technology innovation award, China (industry) most influential international brand, best application pioneer enterprise award of blockchain, blockchain technology breakthrough award, project most worthy of investment award, etc., we also employed as the director of China enterprise network.(Evidence in:
https://docs.google.com/document/d/1vyuSvXfxnXpACMSJqkgqxeqmusv4rDJXrrBCtr9A31k/edit )
Meanwhile, we developed 1475 mining pool system to help the majority of people to participate in the Filecoin project, which supports people to connect their own equipment across networks, models, IDC, regions to 1475 mining pool and aims at building the Filecoin with the members of mining pool. In the course of SR1, we helped the members share the competition rewards which accounts for 1/5 of the global. We still believe and make every effort to the fact that everyone who supports this project can join the big family, even small miners.

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 

I participated in the early testing before reset and gave the official feedback.
During the DVNet: we found several major bugs, such as 100% block generation, drift attack, chain synchronization attack, etc.
During the TestNet: we analyzed the reasons for infinite chain bug and manually targeted elimination of specific nodes bug and provide test-passed fix solution and key log analysis.
Assisted the official to do code review and pre-upgrade test of PR for the second time.
The fastest speed on the list was tested for extreme stress on TestNet2.
Twice chain maintenance, assisted the official to do many upgrades.

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

Personal Reputation
1475 founder, Master's degree of Shanghai Jiaotong University, began to pay attention to and be optimistic about the prospect of IPFS since 2016, dedicated to the ecological contribution of IPFS, founded Shanghai Tianru Network Technology Co., Ltd., blockchain industry researcher.
Created a WeChat social media named 星空生态 in 2017 and now there are 26087 followers. (Evidence in: 
https://docs.google.com/document/d/1vyuSvXfxnXpACMSJqkgqxeqmusv4rDJXrrBCtr9A31k/edit). Also I created many other SOM platforms with many followers and over 1 mm  pageviews.

Organization Reputation
The team 1475 is from Shanghai Tianru Network Technology Co., Ltd, the company is located in Shanghai, China. There are multiple businesses in TR, including high-performance terminal storage equipment selling, stable and secure computer room network system, efficient storage algorithm empowerment,etc. The core members of team 1475 worked for Baidu, Accenture, Google, UnionPay and other internet giants, who are all well-known as big data experts and AI algorithm experts in the industry, as well as hardware experts from Intel with 20 years of experience in the industry.
In June 2020, the 1475 team was formally recognized as a high-tech enterprise by Shanghai Government. It has applied for 28 patents and software copyrights, with multiple certificates such as IDC value-added telecommunications business license and ISP value-added telecommunications business license. Obtained investment from HashKey Capital, Fenbushi Capital, and Yimo Capital.

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

1475 official website: https://1475ipfs.com/
LinkedIn: https://www.linkedin.com/in/%E6%98%8E-%E6%9D%A8-b43239a0/

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

1475 official website: https://1475ipfs.com/
1475 WeChat Official Account：1475IPFS COM
China Enterprise: http://www.zhongqiwang.cn/index.php?s=/zixun/3233.html
Jinse: https://www.jinse.com/news/blockchain/897934.html

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?

I plan to support all use cases in compliance with law, as the Filecoin Plus is currently in beta, and I want to understand how all use cases affect the network and then make adjustments.

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.

Actually, the application of notaries inspires us a lot. So we decided to handle the allocation of DataCap to clients with the same attitude. First of all, the allocation requirement is planned to be divided into 5 categories from L1-L5 by the data volume. The larger data volume clients request, the more strict requirements will be. We want to inspect these clients by reputation, data, diversity and decentralization, allocation strategies, track record, etc. 
Following table shows the scoring system we designed:
https://docs.google.com/spreadsheets/d/15JfJ7im8Zt5U8re_KUASG1dVrhwiHgw0BjiHNaebx2A/edit?usp=sharing
In addition, we plan to show this table in Github, just like the notaries' application and design questions and evidence requested based on those table for clients to fulfill and apply for the DataCap. We will also make public scoring to determine the allocation quantity.
Furthermore, we plan to select one client with excellent industry reputation to run the Beta period of DataCap allocation so that clients can come up with the whole process of scoring and operation.

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 

There isn't too much limit for the target but followings are the targets we prefer:
1.Public development data 2.Slingshot value data 3.Some public sector backups of data
Additionally, I don't want to control a lot over the rate of allocating DataCap, in that it depends on whether there is that much demand or not. If they have too much demand for Filecoin storage, I think the rate and target should not be the most important factor we need to consider. Similarly, the quantity also depends on the customer's demand, and I think the judgment is to identify the reasonable or fake demand. As an example, it is more important for a bank's loan examiner to assess the customer's ability and demand, whether he/she has passed his/her review, how much credit will be given to him/her, and whether he/she will make effective use of this part of the credit line, which is the most important thing.

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

I will do a detailed due diligence on the clients who apply for datacap and the judgement criteria are listed in the table above. I will score clients' situation and determine whether or not to allocate datacap to them and how many according to the score. For me, every client is equal so that everyone can apply for the DataCap and their demands will be approved once they are qualified. If they are not qualified, then they can not get the DataCap but I will give them some suggestions. After all, we still hope that more people can join the filelcoin ecosystem, and hope that the system restrictions or cold rules will not inhibit people's enthusiasm for Filecoin.

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?

I will vet my client according to the allocation table above：
https://docs.google.com/spreadsheets/d/15JfJ7im8Zt5U8re_KUASG1dVrhwiHgw0BjiHNaebx2A/edit?usp=sharing
So I will need their information and evidence of Client Reputation, Data, Diversity and Decentralization, Allocation Strategy and Track Record.
For client reputation, client‘s Business license, screenshoot of search result that client's name in local Enterprise information inquiry website, company website/social meidas link are needed. Besides, if clients have cloud usage, I need the platform name and relevant evidence.
For data, clients need to show me what kind of data they want to store. Also, I will vet the data from time to time during/after allocation.
For diversity and decentralization, I want to know client's allocation plan, especially how many miners to store data, the region and  allocation amount of each miner.
For allocation strategy, client should have detailed method or tool to inspect the miners.
Besides, I will vet clients' performance from time to time, and disqualify the bad allocation. 

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 

1. What's your name, your company name? Can you offer the social media/website link of you/ your company?
2. What kind of data do you what to store and how much?
3. Which address do you need to be notarized?
4. Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?
5. How many miners do you want to store your data to? How much data for each miner?
6. Will you record your allocation decision in public? Which platform will you use?
7. What method/tool will you use to insperct miners? Which aspect of miners will you inspect?
8. Have you ever allocated before? If yes, how did you do when you were questioned?

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?

First of all, I set a track record of clients to prevent clients from making bad allocation such as allocating to only one miner or using bad allocating methods, which will lead to the lower score and lower allocation volume. Secondly, clients need to disclose their allocation record, and I will remind them if the allocation is not reasonable. If clients ignore it, we will also adopt a blacklist mechanism, which will limit their applications in the future.

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?

All allocation decisions will happen in public in the following [repository](https://github.com/keyko-io/filecoin-notaries-onboarding) - all communications will also take place through the repository and the issue tracking. 
For the level of allocation of quantity, I decided to divide it into five levels as shown in the table above. The higher level of audit will be more rigorous.

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 

All allocation decisions will happen in public in the following [repository](https://github.com/keyko-io/filecoin-notaries-onboarding) - all communications will also take place through the repository and the issue tracking, and also we will send the E-mail to clients for twice informing to ensure effectiveness.

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.

None.

Cumulatively, how much DataCap have you previously successfully allocated? 

None.

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 

None.

**Comment by dkkapur** [comment]
@ozhtdong thanks for applying to be a Notary. You can find an initially scored rubric here: https://docs.google.com/spreadsheets/d/1HBgJR5y4zofzasvaFIZQs3XUq4glQSc2ZJ-5GozLbnQ/edit?usp=sharing

Please note that a lot of the scoring under "Industry Reputation" is going to change soon with https://github.com/filecoin-project/notary-governance/pull/36, and this will definitely impact your current score. 

The main follow up I would ask for is in the "Bookkeeping Plan" - if you can refer to the comments (in Column H, row 23) and share additional details, that would help with accurate scoring of your application. 

Thanks and let me know if you have any questions!

**Comment by ozhtdong** [comment]
Hi @dkkapur 
Thanks for your scoring. I have changed my anwser in Client Due Diligence and Bookkeeping Plan. Please check these parts again.
Moreover, I still have two questions on the scoring:
1. Why the score of track record is 0 instead of 1? I found that the track record score of Filecoin foundation and IPFS Force is 1.
2. 1475 have contributed to Filecoin for many years. Why we only get the score of one year? Do we need to offer more information?
I am looking forward to your reply, thanks.

**Comment by ozhtdong** [comment]
@dkkapur Hi. Here is our evidence: https://docs.google.com/document/d/1vi2W__0x-KPD-tytraBugCyYhD2Gaw03moQI70UQP08/edit?usp=sharing
We attend 2017 ICO.

**Comment by jnthnvctr** [comment]
Hi @ozhtdong  based on your submission, we've scored your application here: https://docs.google.com/spreadsheets/d/1qYByMz1cGkWgTavtNWy0liHkbawyVhFRDsWVuEx0j8U/edit?usp=sharing

Eligibility score: 2
Unrounded score: 2.2

**Comment by jnthnvctr** [comment]
Hi @ozhtdong  - as mentioned on the governance call yesterday, your team was in the top of your region for being a prospective Notary! Prior to confirming your role as a Notary, there are a few items that need to be affirmed: 

1. Please acknowledge the region of operation in which you tend to primarily focus: [GCN]

2. Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.

* **Upfront Disclosures**: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship. 

* **Promoting Client Best Practices**: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found [here](https://github.com/filecoin-project/notary-governance/issues/9).

* **No Self Dealing**: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

* **Operating in good faith**: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

3. Please list any addresses you are affiliated with below - stating the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt. 

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above. 

5. (If ready) - Please confirm the address that should receive DataCap.

**Comment by jnthnvctr** [comment]
Additionally, if you plan on being listed in the Filecoin Plus Registry - please confirm what information you'd like to have displayed below. Please note that public requests currently write to a public repository (and we can work with you to configure the requests as needed). 

"name": "Your Name",
"use_case": [
    "List",
    "of",
    "Use Cases"
],
"location": "EUR",
"github_user": "notaryc",
(optional) "website": "google.com",
(optional) "max_datacap_allocation": "100 GB", // To indicate to clients what size allocations you might support. 
(optional) "private_request": "false",                       // set as true if you plan on supporting private requests. 
(optional) "email": "youremail@a.com",                 // only needed if you are supporting private requests
"info": ""                                                                            // You can use this to share information with Clients about your allocation strategy / reqs

**Comment by ozhtdong** [comment]
@jnthnvctr Glad to hear this news. Thanks for your quick messages.
Please kindly refer to the following reply:
1.**Region of operation**: GCN
2.**Upfront Disclosures**: Confirmed
  **Promoting Client Best Practices**：Confirmed
  **No Self Dealing**: Confirmed
  **Operating in good faith**: Confirmed
3.**Miners We Run**: f01475/f014386/f021547/f020618/f020452/f021461/f045756/f089551
4.**Allocation / Client Due Diligence Plan**: Confirmed 
5.**Address**: f1a3up2i324yasakyge2gpt4ml3ipsjhk5z7qkxhi
Please feel free to contact me for any further requirement.

**Comment by dkkapur** [comment]
@ozhtdong - can you also let us know what you'd like displayed on the Filecoin Plus Registry per @jnthnvctr's last message, or confirm that you don't plan to be listed? 

> Additionally, if you plan on being listed in the Filecoin Plus Registry - please confirm what information you'd like to have displayed below. Please note that public requests currently write to a public repository (and we can work with you to configure the requests as needed).

```
"name": "Your Name",
"use_case": [
"List",
"of",
"Use Cases"
],
"location": "GCR",
"github_user": "ozhtdong",
(optional) "website": "google.com",
(optional) "max_datacap_allocation": "100 GB", // To indicate to clients what size allocations you might support.
(optional) "private_request": "false", // set as true if you plan on supporting private requests.
(optional) "email": "youremail@a.com", // only needed if you are supporting private requests
"info": "" // You can use this to share information with Clients about your allocation strategy / reqs
```

**Comment by ozhtdong** [comment]
@dkkapur @jnthnvctr 
Yes, I would like to be listed.
"name": "1475-simon",
"use_case": [General],
"location": "GCN",
"github_user": "ozhtdong",

**Comment by jnthnvctr** [comment]
## Request Approved
#### Address 
> f1a3up2i324yasakyge2gpt4ml3ipsjhk5z7qkxhi
#### Datacap Allocated
> 100TiB

**Comment by ozhtdong** [comment]
Thanks for your approval. Can we allocate datacap now? Which step should we adopt to proceed?

**Comment by jnthnvctr** [comment]
hi @ozhtdong  per my message in slack can you confirm this address is correct?

**Comment by hmffff** [comment]
Thank you, let me check it. @jnthnvctr

**Comment by jnthnvctr** [comment]
Updating per your message in slack with the new address!

## Request Approved
#### Address 
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### Datacap Allocated
> 100TiB
