### ISSUE TITLE
Notary Application:IPFSNEWS

### ISSUE THREAD

**Issue by Dylan933** [filecoin-project/notary-governance#31]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
- Name: IPFSNEWS
- (Optional) Affiliated Organization:  IPFSNEWS（www.ipfsnews.net）
- Website / Social Media:@ Ryan on the Filecoin workspace Slack
- On-chain Address(es) to be Notarized:f15q44xppx5oug7nqqlkvwon2yg32x6mohxanfbhi
- Region of Operation: China

- Use case(s) to be supported: 
-Precious human data in five fields/ including human history/ natural science/ medical data/astronomical imaging and Web3.0 network.

- DataCap Requested:
-100TB or a reasonable estimate based on our team's role in the IPFS ecosystem and the results of our hard work to promote the IPFS ideal.

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Please answer here.
```
IPFSNEWS is an IPFS&Filecoin vertical media platform.As we described in detail in this article, westarted to operate the community and spread IPFS/Filecoin technology in theform of a company in 18. we also held an IPFS technology forum in Shanghai onJanuary 13, 2019. at that time, Steven Li (@ipfsforce) Simon686(@1475IPFS), andLeng Bo（@storswift）have all become Filecoin miners.We are honored to continue tocontribute to IPFS/Filecoin for more than 2 years.(https://www.huodongxing.com/event/2473723064000)

The detailed experience in the encryption industry is as follows:
-In 2013, I came into contact with Bitcoin through the media and embarked on the road of alternating research and exploration of Bitcoin bull and bear.

-In the summer of 2017, I came into contact with IPFS/Filecoin during the ICO boom, and learned about the project dynamics through International Financial Media ，then I shared it among small and medium-sized communities.

-At the beginning of 2018, I started working as a full-time media platform, disseminating information on the blockchain industry, and contacted the first batch of Filecoin mining entrepreneurs in Shanghai,and got in touch with the earliest Filecoin miner in Shanghai, which enabled me to learn more deeply.

-On January 13, 019, we organized an IPFS/Filecoin meetup in Shanghai, the theme activity of "[Broken Bureau]: IPFS Storage Explosion-The Year of Blockchain Break in 2019", the activity line link:https://www.huodongxing.com/event/2473723064000

-On April 21, 2019, we jointly held Filecoin Mining activity in Shanghai, which was the "2019 IPFS/Filecoin Mining and Global Mining Pool Forum" event. Here is part of the photo information link:https://pan.baidu.com/s/1LkIEIHdMVyvalBZVNuGg7Q （View the extract code: IPFS）

-I am honored to be able to accompany the growth of IPFS/Filecoin to this day. We have fully experienced each stage of the Filecoin network including Before DevNet/ DevNet/ TestNet/ HackFS/ SR1/ SR2/ Slingshot 1 and other important events.

Before DevNet：https://www.huodongxing.com/event/2473723064000

DevNet：https://mp.weixin.qq.com/s/waaBJOiw2hGG66FlQOZ-KA

TestNet:
https://mp.weixin.qq.com/s/gVD3KBtVUb_NWuHCl2FLng
https://mp.weixin.qq.com/s/Gq60nZGfOkefXep_uMbscw
https://mp.weixin.qq.com/s/vCJW9NpeezAgDIuvXCUQMg
https://mp.weixin.qq.com/s/5_xQayPbrffAOWFH-5d7dg

SR1：https://mp.weixin.qq.com/s/Hs5urdswpeMUl06kmfl_Lg

Filecoin Dev Grants:https://mp.weixin.qq.com/s/waaBJOiw2hGG66FlQOZ-KA

Slingshot 1:https://mp.weixin.qq.com/s/7Ll6FOv9dw3Ih_h5IGJj_A

-As one of the earliest IPFS ecological vertical communities in China, we have done a systematic sorting of knowledge points. our team  have been promoting the greatness of IPFS/Filecoin protocol and its importance to the future human society in China and the IPFS Chinese community.

-We write and disseminate IPFS/Filecoin information through websites, major Chinese media platforms, and IPFS communities, as well as hold Meetup and IPFS themed summits in major Chinese cities on an ongoing basis. Help many outstanding IPFS community members and community companies (software developers, storage customers, Filecoin miners, university professors, Internet data companies, such as Alibaba/Tencent/Baidu.) understand the IPFS/Filecoin protocol and technical path.

-As the co-founders of the IPFSNEWS media platform of Interstellar Vision, our team will continue to organize IPFS/Filecoin-themed activities to promote the ecological prosperity of the IPFS/Filecoin network.Ecosystem and encourage practitioners to correctly understand IPFS/Filecoin for the region. The importance of blockchain and Web3.0 network infrastructure has led more developers to participate in the construction of the IPFS ecosystem.

-We held China's first IPFS theme summit lasting two days,which theme was "2020 IPFS Ecology and Distributed Storage Industry Summit".Here is some information about it .
(Theme: 2020 IPFS Ecology and Distributed Storage Industry SummitAddress: Hangzhou, ChinaTime: July 3-4, 2020)
https://live.photoplus.cn/live/pc/30688767/#/live
https://mp.weixin.qq.com/s/5O5y6LRCPXRk-OLBrzC49A
Protocol Lab Keren Yin attended the summit and delivered a speech: 
https://v.qq.com/x/page/n3208qo2c8o.html

Github handle: https://github.com/Dylan933

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Please answer here.
```
We have a node involved in mining, and there are 70M FIL quantities in pledge, which are from f045756.

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Please answer here.
```
-Yes, we have done a lot of work，The main work is as follows：
We have been working on the popular science series of activities for introduction to IPFS and the translation of Filecoin Spec (These are only a small part of our work, login to each platform can see more IPFS/Filecoin information)，Including the following:
https://www.ipfsnews.net/detail?articleId=1119，
https://mp.weixin.qq.com/s/43-At6M25cfUq3FruaManw，https://mp.weixin.qq.com/s/5zBialCY6f3G62wwy9iCOg
https://mp.weixin.qq.com/s/Qw7M9V1BrM9YhFY_G8l8pw

We have been committed to the sharing and dissemination of technology; we have done the introduction and application of IPFS technology, related articles and official news of the IPFS community.

IPFS Character Series AMA:
https://mp.weixin.qq.com/s/XdU0XIPN7rC_z24NhUeG8g
https://mp.weixin.qq.com/s/agqx57R2PIahK6wzOErpzQ
https://mp.weixin.qq.com/s/t0QDLmW5VIyvJqoOb3jcow
https://mp.weixin.qq.com/s/wH7q20mHf0nteRkNeca9Fg
https://mp.weixin.qq.com/s/7NkMl8HUPBaV8AoyivmqFA
https://mp.weixin.qq.com/s/3nQSd2lyNg9HVB-Csu4F-w
https://mp.weixin.qq.com/s/zaU3QA_w1gn4hCxh5zj3aw
https://mp.weixin.qq.com/s/XHeaMiphNb0OUAHRdH64Tw
https://mp.weixin.qq.com/s/3pl3csv0yNqEf71_o8hjlw
https://mp.weixin.qq.com/s/tHHdmgDWXSXDNoEt8Wnkog
https://mp.weixin.qq.com/s/qMw-iCzWZ_SYLgAXnckv7A
https://mp.weixin.qq.com/s/EFtOvFCQh2r-jaFF3wDfIw
https://mp.weixin.qq.com/s/rO211HvjLsiqw1y-wKhjXg
https://mp.weixin.qq.com/s/0aODNoVHyf7MINYmhX91WQ
https://mp.weixin.qq.com/s/n0rn2MNcl84jBbaMdchbeQ

《Principles and Practices of IPFS》Original reading podcast program:
https://mp.weixin.qq.com/s/qFYFqEROCGsKT7HUaV0DIA
https://www.ximalaya.com/youshengshu/26657032/205061032
https://www.ximalaya.com/youshengshu/26657032/206774585
https://www.ximalaya.com/youshengshu/26657032/208176468
https://www.ximalaya.com/youshengshu/26657032/209659208
https://www.ximalaya.com/youshengshu/26657032/211351897
https://www.ximalaya.com/youshengshu/26657032/213333024
https://www.ximalaya.com/youshengshu/26657032/215109094
https://www.ximalaya.com/youshengshu/26657032/220096352
https://www.ximalaya.com/youshengshu/26657032/222932308
https://www.ximalaya.com/youshengshu/26657032/224120463
https://www.ximalaya.com/youshengshu/26657032/225989387
https://www.ximalaya.com/youshengshu/26657032/228250276
https://www.ximalaya.com/youshengshu/26657032/229992568
https://www.ximalaya.com/youshengshu/26657032/232258950
https://www.ximalaya.com/youshengshu/26657032/234296583
https://www.ximalaya.com/youshengshu/26657032/239651662
https://www.ximalaya.com/youshengshu/26657032/241264347
https://www.ximalaya.com/youshengshu/26657032/242553768
https://www.ximalaya.com/youshengshu/26657032/257549694

IPFS official dynamic series:
https://mp.weixin.qq.com/s/R60oW0ZZhAFA9g4DrSUj_g
https://mp.weixin.qq.com/s/pMFjncI2lFPHH-m9O-QKOQ
https://mp.weixin.qq.com/s/R_LJrfMZ0WIoc1Iz7Dbqfw
https://mp.weixin.qq.com/s/_75fO1om10jPTKH0DR0s-Q
https://mp.weixin.qq.com/s/MkYionAA6Qh-xBUFSE6ATg
https://mp.weixin.qq.com/s/pMFjncI2lFPHH-m9O-QKOQ
https://mp.weixin.qq.com/s/Qcldtl0oBGBQLLhDkXJB2A
https://mp.weixin.qq.com/s/7Ll6FOv9dw3Ih_h5IGJj_A
https://mp.weixin.qq.com/s/DPSUA8w9eAhqhDNNJW-ItA
https://mp.weixin.qq.com/s/yOw9yPM3fBI5jO9T5KngUQ
https://mp.weixin.qq.com/s/DPSUA8w9eAhqhDNNJW-ItA
https://mp.weixin.qq.com/s/yOw9yPM3fBI5jO9T5KngUQ
https://mp.weixin.qq.com/s/-WZnMM5023cIYwYlm0nkTA
https://mp.weixin.qq.com/s/C8jXtV_9-JunCqkduIlcqA
https://mp.weixin.qq.com/s/3t67it-MAD0Xuv4JeJtlfw

The video of  IPFS /  Filecoin topics discussion:
https://v.qq.com/x/page/l32061k5rcv.html
https://v.qq.com/x/page/u09633nsne4.html
https://v.qq.com/x/page/u09619loygq.html
https://v.qq.com/x/page/t0962afxozi.html
https://v.qq.com/x/page/u09633nsne4.html
https://v.qq.com/x/page/n096308rt86.html
https://v.qq.com/x/page/h0962bjisoy.html
https://v.qq.com/x/page/u09619loygq.html
https://v.qq.com/x/page/f3043lxh8mr.html
https://v.qq.com/x/page/h3005xp0hww.html
https://v.qq.com/x/page/n3005xz9aco.html
https://v.qq.com/x/page/g0901ezh5hn.html
https://v.qq.com/x/page/u09619loygq.html
https://v.qq.com/x/page/t09012u2fe4.html

The practices of IPFS:
https://mp.weixin.qq.com/s/YW7Q8R6FCOW_GTPyokCehw
https://mp.weixin.qq.com/s/a4q5pHc0N4ZEho4bUhnPVA
https://mp.weixin.qq.com/s/jmnzQVO3PFWWCbJ4HHgLUg
https://mp.weixin.qq.com/s/Me6OJ0esSfiOq7A65nc8Tg，
https://mp.weixin.qq.com/s/-z-6csUON6VW--ROJHijkQ
https://mp.weixin.qq.com/s/YW7Q8R6FCOW_GTPyokCehw
https://mp.weixin.qq.com/s/a4q5pHc0N4ZEho4bUhnPVA
https://mp.weixin.qq.com/s/rO211HvjLsiqw1y-wKhjXg

IPFS Community Series:
https://mp.weixin.qq.com/s/gVD3KBtVUb_NWuHCl2FLng
https://mp.weixin.qq.com/s/rmdu4uFPIR8EWqLi61KXVA
https://mp.weixin.qq.com/s/2LIhJjX-3eAPSd_3Z26R9A
https://mp.weixin.qq.com/s/rf0b8w1QbBqRo6aO64kVYQ
https://mp.weixin.qq.com/s/2LIhJjX-3eAPSd_3Z26R9A

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
Please answer here. 
```
-As mentioned above，Our main efforts are to promote and build consensus among the IPFS community in China and to convey the correct understanding of IPFS and Filecoin, and how to participate in them.
We are a media information platform that hasbeen working with the IPFS Chinese community for more than two years.

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Please answer here.
```
-IPFSNEWS was established in June 2018. The company is registered in Shanghai, China and currently has 9 members (including community volunteers).The specific date of establishment can be found in the business system of the Chinese government: http://sh.gsxt.gov.cn/%7B09CADC9261EB7D4092DC1B914337FF0C421E7CAE24780C4E58D2216F33AA95DB1C40347660EA88B5996A577B19DEBC36438DFC22370381774332E412261CE156CC6ACC6ACC7BE147DD41E741E741E77BE741DBD274A03A8D2B8D178D20326AA23BC2D10377BFC80FFC2E49D349FE587B1924086A36FE2C4BFC66C066C066-1607532238799%7D

-IPFSNEWS is a media platform that is perpendicular to the IPFS field. 
We insist on relying on technology and the principle of openness and co-prosperity to provide the fastest, most comprehensive and professional ecological information for IPFS enthusiasts around the world, hoping to provide the IPFS ecology Practitioners provide a platform for correct knowledge and high-value IPFS knowledge information and communication.

-We set up and runThe IPFSNEWS columns inmultiple Chinese media outlets to expand our reach.In particular, officialwechat and Weibo @ipfs star vision have been highly active in the community. Atpresent, the number of subscribers has exceeded 10,000 and is growingcontinuously. (https://weibo.com/u/5691539082)

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Please answer here.
```
IPFSNEWS official website:https://www.ipfsnews.net/
IPFSNEWS official WeChat public account:星际视界IPFSNEWS
Our official Weibo:@IPFS星际视界
Twitter:  @ipfsnews2
Medium: @IPFSNEWS
In the Chainnews column：https://www.chainnews.com/u/909198825155.htm
In the 8bit column ：https://www.8btc.com/author/54498
In the Odaily column：https://www.odaily.com/user/2147491185
In the Jiansh column：https://www.jianshu.com
In the Bihu column ：@IPFSNEWS
In the Jinse column:https://www.jinse.com/
In the Beepcrypto column:https://beepcrypto.com/home?userId=807
In the lofter column :https://ipfsnews.lofter.com/
In the Lichang  column: https://lichang.io/personalCenter
In the Himalayan Podcast column:https://www.ximalaya.com/youshengshu/26657032/
In the Baidu column：https://author.baidu.com/home?from=bjh_article&app_id=1632758744024601
Personal Linkedin：https://www. linkedin.com/in/will-wang-276a45133

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Please answer here.
```
-Online AMA series
We have been focusing on the construction of the IPFS ecosystem.hosting and organizing many on-line/off-line special events around IPFS and Filecoin in China. The following is our large number of articles, pictures and videos about IPFS&Filecoin, as well as case information published on online and offline activities. Including the following:
1、In the 《100 Futures of IPFS and he》 series, we will gather online AMA into the WeChat public account "IPFS100 People" menu, such as online AMA, the selection is as follows:
 https://mp.weixin.qq.com/s/agqx57R2PIahK6wzOErpzQ
https://mp.weixin.qq.com/s/t0QDLmW5VIyvJqoOb3jcow
https://mp.weixin.qq.com/s/wH7q20mHf0nteRkNeca9Fg
https://mp.weixin.qq.com/s/wH7q20mHf0nteRkNeca9Fg
https://mp.weixin.qq.com/s/XHeaMiphNb0OUAHRdH64Tw
https://mp.weixin.qq.com/s/zaU3QA_w1gn4hCxh5zj3aw
https://mp.weixin.qq.com/s/7NkMl8HUPBaV8AoyivmqFA

2、《Please, Filecoin》was held on May 15th, 2020 on the launch day of the Big Miner Testnet. Here is the link to the video playback of the event:https://live.polyv.cn/splash/1617576

-Offline continuous summit:
1、China-Hefei: "Anhui Blockchain Club-IPFS/Filecoin Technology Forum" event on July 24, 2019,here is some detailed introduction:https://mp.weixin.qq.com/s/08VB1Yw61y3mbqifJ43Eag

2、China-Hangzhou: The "IPFS Ecology and Distributed Storage Summit" was organized on July 3, 2020. This summit was also supported and helped by Protocol Labs Colin Evran and Keren Yin. Filecoin Official Blog China on August 24, 2020 Recorded in the community activity section https://filecoin.io/blog/roadmap-update-august-2020/
Keynote speech by Colin Evran《ipfs-filecoin-ecosystem-growth》https://v.qq.com/x/page/w3112wvzn1q.html
Keren Yin shared the theme of "Filecoin's Vision and Ecological Development" at the summit sitehttps://v.qq.com/x/page/n3208qo2c8o.html
Here is the full video playback
https://play.yunxi.tv/livestream/flash?id=e1eecab932304450b9e332502dbbf490#/

3、China-Ningbo: "New Infrastructure, New Opportunities-2020 Supercomputing and Distributed Storage Industry Summit" on August 29, 2020. The introduction of the event is as follows:https://mp.weixin.qq.com/s/OkowIFcjBReCxtr9GmCAQQ
The video ：https://live.polyv.cn/splash/1882999

4、China-Shanghai: On November 27, 2020, during the Shanghai Blockchain International Week, we organized the "IPFS Ecology & Storage Special Session" to focus on exchanges on various explorations of IPFS ecological applications and decentralized storage applications. the link to the activity:https://www.huodongxing.com/event/9564562337000

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Please answer here.
```
-Our use case plan is used to store precious data sets covering humanity, history, natural science, medical data, astronomical images, and Web3.0 networks. Now there is a preliminary estimated distribution as follows:
Humanities&history account for 5%
natural science data accounted for 10%
Medical data account for15%
astronomical image data account for 20%
Web3.0 network data accounted for 50%

***#How to Use Case Diversity#Our plan is like this：《Assign a strategic schedule》https://docs.google.com/spreadsheets/d/1pmtiClZqsQysqvgImIJX1_89Jt-OH6zU/edit#gid=1303001804

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
Please answer here.
```
-In the initial stage, we plan to focus on Internet companies (institutions) customers and help them use the Filecoin network. Focus on participating in the improvement of system rules and process construction.At the same time, our Datacap quota will be divided into different levels (granularity), and develop the management and allocation scheme of the system.
Regarding the distribution of DataCap, we plan to expand with reference to the following elements:
1. Regularly inspect the customer's data storage security management system
2. Investigate the reputation of customers in the industry
3. R&D investment and accumulation in data management
4. Magnitude and dispersion degree of storage devices
5. Growth rate and quality of customers

***Regarding #Allocation Plan#, we have designed a plan of our own:“Filecoin Datacap Application Form” https://docs.google.com/spreadsheets/d/1yIpR2g5F74S0YVdbjkwXypVE5c5T3a5v/edit#gid=842689753

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Please answer here. 
```
-There are plans to add the above content to the internal process ,which is of course a dynamically balanced process based on the actual Filecoin network.This will be a dynamic balancing process. I would also like to hear about the application of actual commercial storage after the launch of the Filecoin mainnet. At present, we are more concerned about data storage in the following areas:
1.Slingshot data in the Filecoin network
2.Important data native to various blockchain main networks (data on blockchain, smart contracts, user DID, etc.)
3.Large-scale cold data in the Internet industry (such as scientific data such as medical imaging, astronomy and geography)

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Please answer here.
```
-The safe and reasonable use of DataCap is the core of notary's work. In terms of security, we initially plan to establish a security team within the organization and implement a multi-layer authorization model at the executive level.
During the test period, I hope that Protocol Labs will establish a platform for notary public information disclosure and supervision, and at the same time launch verification tools, authorized multi-signature platforms and other measures.

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
Please answer here.
```
-First of all, we need to understand the relevant information of the customer.Secondly, we require the customer to clarify the distribution method of DataCap.Form a good trust mechanism with each other again; and finally archive all information for review.We are preparing the following data record sheets for customers to provide reference for Datacap usage review and evaluation.
1. Customer information registration form (customer status, project progress)
2.  Datacap requirement application form (source, quantity, use case, frequency, etc.)
3. Customer Credit Rating Form
4. Customer safety rating table
5. Customer Datacap individual entity allocation plan
6. Formation of report retention and registration

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
Please answer here. 
```
-In the initial testing phase, we plan to set up demand tables (including customer detailed information, demand and data attribute descriptions) for different levels of customers and regularly organize review meetings; review results will be announced through an open platform. Steps:
1. We plan the different qualifications of customers (from the customer information registration form and the Datacap demand application form to classify customers' credit and security levels)
2. Please submit project information and project progress
3. Customers are requested to submit a list of datacap individual entity allocations
4. Customers are requested to submit the Datacap single entity distribution plan
5. Regularly organize review meetings and publicize review results

***Regarding #Allocation Plan#, we have designed a plan of our own:https://docs.google.com/spreadsheets/d/1yIpR2g5F74S0YVdbjkwXypVE5c5T3a5v/edit#gid=340586181
We have prepared the gadget form for the customer to use in the application
-English version of notary Public form   https://www.wenjuan.com/s/UZBZJvfRwf/
-Chinese version of notary Public Form   https://www.wenjuan.com/s/yQRNr28/

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Please answer here. 
```
-I believe that good systems and procedures are still needed to ensure that the work of notaries can be carried out in a fair and transparent environment. Every notary should carry out work in a cautious and pragmatic manner.I will implement the above plan and adopt the common plan of the community to ensure the reasonable distribution of DataCap; I look forward to the technical realization of these plans and processes.
1. Ask the customer to submit the DataCap list of individual entities and allocation plan when auditing the customer
2. In the process of allocation, the list of individual entities assigned to DataCap and the allocation plan should be synchronized timely
3. Supervise customers after the assignment.

***In addition, we add a part of the notary's scoring and management plan: "Notary's score sheet" https://docs.google.com/spreadsheets/d/1yIpR2g5F74S0YVdbjkwXypVE5c5T3a5v/edit#gid=958760372

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Please answer here.
```
-Yes, I fully support the recording of the entire allocation decision, similar to publishing on GitHub or based on the Filecoin blockchain network to ensure transparency and credibility.(https://github.com/Dylan933/notary-governance)

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Please answer here. 
```
-There is no doubt that this is also a must as a Datacap notary.

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Please answer here.
```
None

Cumulatively, how much DataCap have you previously successfully allocated? 
```
Please answer here. 
```
None

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
Please answer here.
```
None

**Comment by dkkapur** [comment]
@Dylan933 - thanks for applying to be a Notary! The initial scored rubric can be found here: https://docs.google.com/spreadsheets/d/1_DchYgSfDoY_KLK2Iiff_TbKZ2ZTxDcZaHyA-2x62Wk/edit?usp=sharing. 

The main ask you will see in the comments is to give a little more detail around the implementation or some frameworks behind the tooling/processes you plan to create for the Allocation Plan section of the application. Column H has additional details for you to look through. 

Please also note that there is a rubric change coming in https://github.com/filecoin-project/notary-governance/pull/36 which is likely to affect your scoring (especially around Industry Reputation). Thanks!

**Comment by Dylan933** [comment]
Hi Kapur,I would like to elaborate further on some of these points.
1、Reference questions:About #Time Commitment--Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github Handles, Miner ids,significant projects or contributions (with links). #
--As we described in detail in this article, we started to operate the community and spread IPFS/Filecoin technology in the form of a company in 18. we also held an IPFS technology forum in Shanghai on January 13, 2019. at that time, Simon686(1475IPFS), Steven Li (IPFSForce) and Leng Bo have all become Filecoin miners.We are honored to continue to contribute to IPFS/Filecoin for more than 2 years.

2、Reference question: About # in-Protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. #
--We are a media information platform that has been working with the IPFS Chinese community for more than two years.

3、Reference question: About #External Reputation
--Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception. #
We set up and run IPFSNEWS columns in multiple Chinese media outlets to expand our reach.In particular, official wechat and Weibo @IPFS star vision have been highly active in the community. At present, the number of subscribers has exceeded 10,000 and is growing continuously.

**Comment by Dylan933** [comment]
Hi Kapur, I'd like to elaborate a little bit more on the questions that are involved in grading, and I hope to answer your questions.
1、About #Time Commitment--Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github Handles, Miner ids,significant projects or contributions (with links). #
--As we described in detail in this article, we started to operate the community and spread IPFS/Filecoin technology in the form of a company in 18. we also held an IPFS technology forum in Shanghai on January 13, 2019. at that time, Steven Li (@IPFSForce) Simon686(@1475IPFS), and Leng Bo（@storswift）have all become Filecoin miners.We are honored to continue to contribute to IPFS/Filecoin for more than 2 years.(https：// www .huodongxing.com / event / 2473723064000)

2、About # in-Protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. #
--Just think of the reply to the last question，We are a media information platform that has been working with the IPFS Chinese community for more than two years.

3、About #External Reputation
--Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception. #
We set up and run IPFSNEWS columns in multiple Chinese media outlets to expand our reach.In particular, official wechat and Weibo @IPFS star vision have been highly active in the community. At present, the number of subscribers has exceeded 10,000 and is growing continuously.（https://weibo.com/u/5691539082）

**Comment by Dylan933** [comment]
Hi Kapoor, I'd like to elaborate a little bit more on the questions that are involved in grading, and I hope to answer your questions.
1、Reference questions:About #Time Commitment--Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github Handles, Miner ids,significant projects or contributions (with links). #
--As we described in detail in this article, we started to operate the community and spread IPFS/Filecoin technology in the form of a company in 18. we also held an IPFS technology forum in Shanghai on January 13, 2019. at that time, Steven Li (@IPFSForce) Simon686(@1475IPFS), and Leng Bo（@storswift）have all become Filecoin miners.We are honored to continue to contribute to IPFS/Filecoin for more than 2 years. (https://www.huodongxing.com/event/2473723064000)

2、Reference question: About # in-Protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. #
--We are a media information platform that has been working with the IPFS Chinese community for more than two years.

3、Reference question: About #External Reputation
--Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception. #
We set up and run IPFSNEWS columns in multiple Chinese media outlets to expand our reach.In particular, official wechat and Weibo @IPFS star vision have been highly active in the community. At present, the number of subscribers has exceeded 10,000 and is growing continuously. (https://weibo.com/u/5691539082)

**Comment by Dylan933** [comment]
Hi Kapur, I'd like to elaborate a little bit more on the questions that are involved in grading, and I hope to answer your questions.

**Comment by Dylan933** [comment]
Hi Kapur, I'd like to elaborate a little bit more on the questions that are involved in grading, and I hope to answer your questions.

**Comment by Dylan933** [comment]
Hi Kapur, I'd like to elaborate a little bit more on the questions that are involved in grading, and I hope to answer your questions.
First, Reference questions: About #Time Commitment#, # in-Protocol Reputation#, #External Reputation#。

The second also supplemented the specific allocation plan and plan of the notary. Reference question: About #Use Case Diversity#、#Concreteness of Allocation Plan#

Third, we have also added a plan related to Filecoin notary scoring and management.
The above is a further answer to these questions, thank you for your suggestions.

**Comment by Dylan933** [comment]
@dkkapur  Hi Kapur, I'd like to elaborate a little bit more on the questions that are involved in grading, and I hope to answer your questions.
First, Reference questions: About #Time Commitment#, # in-Protocol Reputation#, #External Reputation#。

The second also supplemented the specific allocation plan and plan of the notary. Reference question: About #Use Case Diversity#、#Concreteness of Allocation Plan#

Third, we have also added a plan related to Filecoin notary scoring and management.
The above is a further answer to these questions, thank you for your suggestions.

**Comment by jnthnvctr** [comment]
Hi @Dylan933  - thank you for your application. Unfortunately after our request was sent on Sunday, we still don't have access to the supporting documents you shared. 

As a result we've scored your application as follows: https://docs.google.com/spreadsheets/d/1H4nhLrJAE1_Xxx5oZAh5CFzJQVBByXLfapFITCwI20c/edit#gid=327015220

Eligibility score: 1
Unrounded score: 1.3

**Comment by Dylan933** [comment]
@jnthnvctr  Hi jnthnvctr,our schedule table is open and updated for #Stake Sure#. Thank you very much.

**Comment by Dylan933** [comment]
@jnthnvctr Hi jnthnvctr,our plan form is open for access, in addition, there is also an update on #Stake Sure#, please give me your evaluation again, thank you very much. (https://drive.google.com/file/d/1pmtiClZqsQysqvgImIJX1_89Jt-OH6zU/view?usp=sharing)

**Comment by Dylan933** [comment]
@jnthnvctr  Hi,JNTHNVCTR, our plan form is open for access, in addition, there is also an update on #Stake Sure#, please give me your evaluation again, thank you very much.
（https://drive.google.com/file/d/1pmtiClZqsQysqvgImIJX1_89Jt-OH6zU/view?usp=sharing）
Our notary application is https://github.com/filecoin-project/notary-governance/issues

**Comment by dkkapur** [comment]
@Dylan933 - just wanted to let you know that Notary applications are currently open again until May 25. In case you'd be interested in applying again, please create a new Issue of type "Notary Application" and fill in the form (it is completely reasonable to reuse material from your prior application).
