### ISSUE TITLE
Notary Application:YPOOL

### ISSUE THREAD

**Issue by Melody-He** [filecoin-project/notary-governance#32]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
- Name:YPOOL
- (Optional) Affiliated Organization: YPOOL（https://ypool.io/major/home）
- Website / Social Media:https://ypool.io/major/home
http://www.cloud-eyes.com/
https://ypool.io/major/home
- On-chain Address(es) to be Notarized:f1jx2hhmrivugs7remgq423xyx5mapomjzgixoeyy
- Region of Operation: [Greater China]
- Use case(s) to be supported: [-Precious human data in five fields/ including human history/ natural science/ medical data/astronomical imaging and Web3.0 network.]
- DataCap Requested:
-100TB or a reasonable estimate based on our team's role in the IPFS ecosystem and the results of our hard work to promote the IPFS ideal.
_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Please answer here.
YPOOL started to pay attention to Filecoin in 2017, and the formal component team began to study Filecoin mining in 2018. At that time, we established "YPOOL Community" with friends who were interested in Filecoin in southwest and western China. We carried out online activities and offline salons in Chengdu from time to time and published Filecoin information in various media.
Mars finance: https://www.huoxing24.com/userCenter/d1d7d788f4f0448fa2632e01deff4d01
Golden finance: https://www.jinse.com/member/376668
In December 2019, the first day of Filecoin test line, we released the Filecoin test net mining tutorial text version and video version for the whole network miners, formed the Filecoin miners exchange group, and called on everyone to explore the best mining hardware configuration.
Video tutorial https://www.huoxing24.com/videoDetails/20191212122403933000
Graphic tutorial https://news.huoxing24.com/20191212124219904144.html
Mining hardware assessment: https://news.huoxing24.com/20191231093839711371.html
https://news.huoxing24.com/20191229120937581658.html
Due to the outbreak, we launched many online activities in 2020 to follow and discuss the latest developments of Filecoin. At the same time, we also participated in test Net, Calibration Net, Space Race 1, Space Race 2 and now the main net, with good results, as well as Slingshot.
Miner ID: F01800, F068096
Slingshot project https://github.com/Filecoin-ypool/cloud-eyes
Online activities: https://mp.weixin.qq.com/s/mn8eSE9fGtgZyeSZJ3fTEg
https://mp.weixin.qq.com/s/nJM5pvDYC_s07_1No1M7Hg
https://mp.weixin.qq.com/s/L78vP8gKqbCE19z-LGlmxg

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Please answer here.
By December 2020, we have about 100,000 FIL with two miner nodes of F01800 and F068096

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Please answer here.
As a member of Filecoin ecology, we actively promote the development of ecology in the community and mining. We participate in every online meeting and AMA of Filecoin, and timely sync the latest content to the miners in the community. I actively participated in ecological activities such as space race and Slingshot, and organized a lot of dry mineral products for everyone to learn and participate in Filecoin ecology.
https://news.huoxing24.com/20200930164700660868.html
https://news.huoxing24.com/20200306155749326989.html
https://news.huoxing24.com/20200922154254232428.html
https://news.huoxing24.com/20201106101643486478.html
https://news.huoxing24.com/20200519182816588107.html
https://news.huoxing24.com/20200626175828514719.html
https://github.com/Filecoin-ypool/cloud-eyes

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
Please answer here. 
In 2019 and 2020, we submitted a few bugs and suggestions, generally on Github and Slack to contact WHY. A suggested link to the Matrix web page ishttps://riot.im/app/#/room/#fil-lotus:matrix.org/$xyU9-n8cwM3sUx44wn4F-gtsvl38RoNftyZJsT7ZhpI
filecoin-project/lotus#3242
https://app.slack.com/client/TEHTVS1L6/C017CCH1MHB/thread/C017CCH1MHB-1597730093.083900?cdn_fallback=1

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Please answer here.
YPOOL team was founded in 2018 and the company was registered in Chengdu, Sichuan province, China in September 2019.
At the beginning, there were only 4 people in our team. Up to now, there are more than 35 employees in our company.

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Please answer here.
Mine Pool website: www.ypool.io
Official website: www.ypool.org
Weibo: YPOOL Yao Pool
WeChat official number: yao pool block chain
Slack, Github: YPOOL, Xiaoyazi, Xiaoyaozi

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Please answer here.
https://baijiahao.baidu.com/s?id=1684434397966756557&wfr=spider&for=pc
https://www.btcfans.com/article/35693
https://www2.fn.com/column/119210.html
https://baijiahao.baidu.com/s?id=1677883724585594348&wfr=spider&for=pc
http://www.rinconstone.cn/post/1381.html
https://www.jinse.com/news/blockchain/830685.html
https://www.jinse.com/blockchain/871676.html

## Diversity and Decentralization
### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Please answer here.
Yes.

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
Please answer here.
Allocation policy
When assigning DataCap, we plan to perform the data assignment by means of customer condition evaluation and feedback comprehensive evaluation.
In terms of objective conditions, we will grade the information provided by customers from the following dimensions:

1.Degree of completeness and transparency of information disclosure
2.Team size and capital strength/individual strength
3.Reputation of the individual or team
4.The scale and dispersion of storage devices
5.Organize miners' customer resources and customer quality
After the initial review of the above conditions, we will have a level division. In the later stage, we will continue to track the distribution data of customers and make continuous adjustment of the level. The feedback in the later stage is mainly evaluated from the following aspects:
1.Feedback rate and transparency of DataCap distribution information
2.Dispersion degree of DataCap data distribution
3.Success rate of DataCap data storage

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Please answer here. 
-There are plans to add the above content to the internal process ,which is of course a dynamically balanced process based on the actual Filecoin network.This will be a dynamic balancing process. I would also like to hear about the application of actual commercial storage after the launch of the Filecoin mainnet. At present, we are more concerned about data storage in the following areas:
1.Slingshot data in the Filecoin network
2.Important data native to various blockchain main networks (data on blockchain, smart contracts, user DID, etc.)
3.Large-scale cold data in the Internet industry (such as scientific data such as medical imaging, astronomy and geography)

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Please answer here.
-The safe and reasonable use of DataCap is the core of notary's work. In terms of security, we initially plan to establish a security team within the organization and implement a multi-layer authorization model at the executive level.
During the test period, I hope that Protocol Labs will establish a platform for notary public information disclosure and supervision, and at the same time launch verification tools, authorized multi-signature platforms and other measures.

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
Please answer here.
-First of all, we need to understand the relevant information of the customer.Secondly, we require the customer to clarify the distribution method of DataCap.Form a good trust mechanism with each other again; and finally archive all information for review.We are preparing the following data record sheets for customers to provide reference for Datacap usage review and evaluation.

Customer information registration form (customer status, project progress)
Datacap requirement application form (source, quantity, use case, frequency, etc.)
Customer Credit Rating Form
Customer safety rating table
Customer Datacap individual entity allocation plan
Formation of report retention and registration

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
Please answer here. 
-In the initial testing phase, we plan to set up demand tables (including customer detailed information, demand and data attribute descriptions) for different levels of customers and regularly organize review meetings; review results will be announced through an open platform. Steps:

We plan the different qualifications of customers (from the customer information registration form and the Datacap demand application form to classify customers' credit and security levels)
Please submit project information and project progress
Customers are requested to submit a list of datacap individual entity allocations
Customers are requested to submit the Datacap single entity distribution plan
Regularly organize review meetings and publicize review results

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Please answer here. 
-I believe that good systems and procedures are still needed to ensure that the work of notaries can be carried out in a fair and transparent environment. Every notary should carry out work in a cautious and pragmatic manner.I will implement the above plan and adopt the common plan of the community to ensure the reasonable distribution of DataCap; I look forward to the technical realization of these plans and processes.

Ask the customer to submit the DataCap list of individual entities and allocation plan when auditing the customer
In the process of allocation, the list of individual entities assigned to DataCap and the allocation plan should be synchronized timely
Supervise customers after the assignment.

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Please answer here.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Please answer here. 
-Yes, I fully support the recording of the entire allocation decision, similar to publishing on GitHub or based on the Filecoin blockchain network to ensure transparency and credibility.

## Track Record
### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Please answer here.
None

Cumulatively, how much DataCap have you previously successfully allocated? 
```
Please answer here. 
None

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
Please answer here.
None

**Comment by jnthnvctr** [comment]
Hi - we have an initial scoring put together here: https://docs.google.com/spreadsheets/d/1RzYTQV7_0QBVf8WRATOUJizmG2QHe5u4392mnQEdQbA/edit#gid=0

Please take a look at column H - if you have questions, please ask them here - if you have edits to your application, just edit them above!

Please note - there is a pending rubric change which might change the scoring for your application. Please see the proposed changes here: https://github.com/filecoin-project/notary-governance/pull/36

**Comment by Melody-He** [comment]
Thank you for your reply,and now I would like to request the editing permission of this form.Please pass it.

**Comment by Melody-He** [comment]
> 嗨-我们在这里汇总了一个初始评分：[https](https://docs.google.com/spreadsheets/d/1RzYTQV7_0QBVf8WRATOUJizmG2QHe5u4392mnQEdQbA/edit#gid=0) : [//docs.google.com/spreadsheets/d/1RzYTQV7_0QBVf8WRATOUJizmG2QHe5u4392mnQEdQbA/edit#gid=0](https://docs.google.com/spreadsheets/d/1RzYTQV7_0QBVf8WRATOUJizmG2QHe5u4392mnQEdQbA/edit#gid=0)
> 
> 请查看H栏-如有疑问，请在此处提问-如果您对应用程序进行了编辑，只需在上方进行编辑即可！
> 
> 请注意-待定的专栏更改可能会更改您的应用程序评分。请在此处查看建议的更改：[＃36](https://github.com/filecoin-project/notary-governance/pull/36)

Thank you for your reply.Now I would like to request the editing permission of this form.Please pass it.

**Comment by Melody-He** [comment]
> 嗨-我们在这里汇总了一个初始评分：[https](https://docs.google.com/spreadsheets/d/1RzYTQV7_0QBVf8WRATOUJizmG2QHe5u4392mnQEdQbA/edit#gid=0) : [//docs.google.com/spreadsheets/d/1RzYTQV7_0QBVf8WRATOUJizmG2QHe5u4392mnQEdQbA/edit#gid=0](https://docs.google.com/spreadsheets/d/1RzYTQV7_0QBVf8WRATOUJizmG2QHe5u4392mnQEdQbA/edit#gid=0)
> 
> 请查看H栏-如有疑问，请在此处提问-如果您对应用程序进行了编辑，只需在上方进行编辑即可！
> 
> 请注意-待定的专栏更改可能会更改您的应用程序评分。请在此处查看建议的更改：[＃36](https://github.com/filecoin-project/notary-governance/pull/36)



> 嗨-我们在这里汇总了一个初始评分：[https](https://docs.google.com/spreadsheets/d/1RzYTQV7_0QBVf8WRATOUJizmG2QHe5u4392mnQEdQbA/edit#gid=0) : [//docs.google.com/spreadsheets/d/1RzYTQV7_0QBVf8WRATOUJizmG2QHe5u4392mnQEdQbA/edit#gid=0](https://docs.google.com/spreadsheets/d/1RzYTQV7_0QBVf8WRATOUJizmG2QHe5u4392mnQEdQbA/edit#gid=0)
> 
> 请查看H栏-如有疑问，请在此处提问-如果您对应用程序进行了编辑，只需在上方进行编辑即可！
> 
> 请注意-待定的专栏更改可能会更改您的应用程序评分。请在此处查看建议的更改：[＃36](https://github.com/filecoin-project/notary-governance/pull/36)

As for the score information in the table, how to add the information? Shall I add it directly in the shared file or in the comments?

**Comment by Melody-He** [comment]
We have updated the information in the form, please check it. @jnthnvctr

**Comment by jnthnvctr** [comment]
Hi @Melody-He  - see your scoring here: https://docs.google.com/spreadsheets/d/1LLWYsCtR2jz28ak1tmuMwbmTiwd5Atg2Q5_utgqkBzQ/edit?usp=sharing

Eligibility score: 2
Unrounded score: 2

**Comment by dkkapur** [comment]
@Melody-He - just wanted to let you know that Notary applications are currently open again until May 25. In case you'd be interested in applying again, please create a new Issue of type "Notary Application" and fill in the form (it is completely reasonable to reuse material from your prior application).
