### ISSUE TITLE
 Next Governance Call: Tues Nov 23 4pm UTC AND Nov 23 12am UTC

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/notary-governance#322]
We will again have 2 Notary Governance call times this week, covering the same agenda but supporting more timezone attendance. These will occur at 8am PT // 4pm UTC AND 4pm PT // 12am UTC, and you are welcome to attend both! These will be recorded, and video links will be posted here.

Agenda topics will include: program metrics and stats, updates to the stats Dashboard, work towards Q1 goals, notaries presenting on their open "Discussion Topics", LDN audit process & mindsets, and open discussion time.

If you have items to add to the agenda, please comment below!

Zoom meeting details:
https://fil-org.zoom.us/j/89234863880?pwd=YWR3WmtTdmNNQ3l3NXdsTVlsdW12QT09

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/FIPs/issues/204 / https://github.com/filecoin-project/notary-governance/discussions/318

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/discussions/319

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/discussions/321

**Comment by galen-mcandrew** [comment]
Second timeslot (12am UTC 4pm Pacific) zoom link: 
Join Zoom Meeting
https://fil-org.zoom.us/j/81768681049?pwd=OEJZcHdNTURBeDJDQi9xN2N6VmEwQT09

Meeting ID: 817 6868 1049
Passcode: 607590

**Comment by KwrayFF** [comment]
Thanks for all that participated on last weeks call.  For historical reference, here is the link to the recordings for both sessions. 
https://youtu.be/bNl7wIszMcg
