### ISSUE TITLE
Next Governance Call: Tues Dec 07 4pm UTC AND Dec 07 12am UTC

### ISSUE THREAD

**Issue by KwrayFF** [filecoin-project/notary-governance#325]
This issue is intended to be used for the communications ahead of the upcoming Notary Governance Call 
**8am PT // 4pm UTC** AND **4pm PT // 12am UTC**

You are welcome to attend both! These will be recorded, and video links will be posted here.

Agenda topics will include: Program metrics and stats, updates to the stats Dashboard, work towards Q1 goals, notaries presenting on their open "Discussion Topics", LDN audit process & mindsets, and open discussion time.

If you have items to add to the agenda, please comment below!

Zoom meeting details:
https://fil-org.zoom.us/j/89234863880?pwd=YWR3WmtTdmNNQ3l3NXdsTVlsdW12QT09

**Comment by galen-mcandrew** [comment]
We are approaching the 100 PiB experiment for the large dataset v2 process, as outlined in issue #217 . We should decide if we will continue running this v2 process through Q1, or if we feel strongly that we need to make changes before the end of the year.

**Comment by KwrayFF** [comment]
There were lots of great input around [FIP 204](https://github.com/filecoin-project/FIPs/issues/204) during the last Nov 23rd meeting.  Adding time during this call for any additional input.

**Comment by MegTei** [comment]
HI @KwrayFF Could you consider the possibility of moving the 8am PT // 4pm UTC call to **11am PT// 7pm UTC** - while this is early, 6am for Australia we will join this call if you can shift it forward a couple hours

**Comment by galen-mcandrew** [comment]
Flagging here, 11am PT works for US, is evening for Europe, but it is 3am Beijing time. The second call, at 4pm PT is 8am Beijing. Just to make sure I am understanding, are you suggesting still running two calls every two weeks, one at 11am Pacific and the other at 4pm Pacific?

**Comment by MegTei** [comment]
HI @galen-mcandrew yes, correct still suggesting 2 calls. It seems most of the energy and discussion is in the first call, and as we are working hard to uplift representation in our region, joining the first one may add more value. I cant guarantee what we will look like at 6am (cameras off) but I will show up if its possible to shift fwd a couple hours.

**Comment by KwrayFF** [comment]
For the calls for this Governance, please check out Youtube: https://www.youtube.com/watch?v=Z1L7eZwkpcE
