### ISSUE TITLE
Notary Application: Diancun Tech - David

### ISSUE THREAD

**Issue by lastingman** [filecoin-project/notary-governance#33]
# Notary Application

### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form.

## Core Information

• Name: `David`
• (Optional) Affiliated Organization: `Diancun Tech`
• Website / Social Media: `https://diancun.net`
• On-chain Address(es) to be Notarized: `f1r5idduxae7ecopashldq7ptfyj2zzskm2rojtva`
• Region of Operation: `Greater China`
• Use case(s) to be supported: `Web 3.0, User Content, Scientific Data, Media & Entertainment, Other`
• DataCap Requested: `100 TiB`

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment

Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

```
Early 2018, I founded Diancun Tech, aim to become a comprehensive edge-clouding computing infrastructure service provider. In the meantime, IPFS, as a leading distributed storage solution, catches my eye. As a member of IPFS community, I am actively following the progress of IPFS, participating in and holding many offline and online activities. In 2020, Diancun Tech joined Filecoin Devnet, made a huge contribution to launch Filecoin Mainnet. In the Slingshot competition, Diancun Tech won first place in Phase 1 with the dragonfly project.
```

### Stake Exposure

Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

```
The total amount is about 450,000 Fil, which is growing at a speed of about 1% every day. Here are some of my miner IDs, and we can sign messages with the private keys:
- f01155
- f010038
- f010202
- f014686
- f014699
- f029585
- f033462
- f082730
- f060805
- f086204
```

### In-protocol Reputation

Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow.

```
we've partitcipated proof parameters generating: https://github.com/filecoin-project/phase2-attestations/blob/master/b288702/README.md

Our team members' github handles: yaohcn, strahe, hexcola

Ask & Discuss issues:
- https://github.com/filecoin-project/lotus/issues/1917
- https://github.com/filecoin-project/lotus/pull/4653
- https://github.com/filecoin-project/lotus/issues?q=is%3Aissue+author%3Ayaohcn

PRs:
- https://github.com/filecoin-project/lotus/commits?author=yaohcn
- https://github.com/filecoin-project/lotus/pull/4785/commits

We helped to answer questions on the Slack channel.
```

### In-protocol Security

Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side).

```
Our team are working to solve the current drawback of the wallet issues (frequent transfer and authorization requirements since seal sectors need to pledge first) with an attempt of dual factor authenticaition & authorization method, and we are still working on the details, and will try to finalize it before the end of the year.
```

### External Reputation

Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

```
Diancun Tech is a private limited liability company, founded on August 22nd, 2018. It is registration in China. Right now, we have around 80 employees.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

```
Official Website: https://www.diancun.net
WeChat Official Account: 点存科技（ipfsdiancun）
Weibo: 杭州点存科技有限公司
Tiktok China: 点存科技
https://www.zhihu.com/org/dian-cun-ke-ji
https://www.huoxing24.com/userCenter/c8b5a2ebf17e49448040649c50f43338
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

```
http://news.iresearch.cn/yx/2019/04/289410.shtml
http://www.cnr.cn/rdzx/cxxhl/zxxx/20190529/t20190529_524631740.shtml
http://d.youth.cn/newtech/201906/t20190604_11973084.htm
https://new.qq.com/omn/20190617A0IBGP00
http://www.cntechw.com/html/news/20190626/4689397506004028946.shtml
https://c.m.163.com/news/a/EK7MGGO9000189DG.html?spss=wap_refluxdl_2018
https://finance.qq.com/a/20190426/009847.htm
https://www.sohu.com/a/308843059_120011750?sec=wd&spm=smpc.author.fd-d.1.1555590300549IV05EoA
http://news.iresearch.cn/yx/2019/04/288108.shtml
http://news.iresearch.cn/yx/2019/04/288108.shtml
http://www.chinaz.com/news/mt/2019/0410/1007599.shtml
https://www.sohu.com/a/306575206_132894?
http://news.iresearch.cn/yx/2019/04/289410.shtml
https://finance.qq.com/a/20190426/009847.htm
https://www.csdn.net/article/a/2019-04-23/15972452
http://telecom.chinabyte.com/480/14610480.shtml
https://finance.qq.com/a/20190422/008095.htm
https://www.sohu.com/a/324234281_120035092
https://www.sohu.com/a/323577986_120035092
https://www.sohu.com/a/325526239_120035092
https://www.jianshu.com/p/951f566640ef
https://www.toutiao.com/i6682620104116535812/
https://www.toutiao.com/i6680060184225645060/
https://www.toutiao.com/i6677844785199317512/
https://www.toutiao.com/i6677471462711886349/
https://www.toutiao.com/i6681545933324288519/
https://www.jianshu.com/p/249b05c5c80e
https://baijiahao.baidu.com/s?id=1672445813680298407&wfr=spider&for=pc
https://new.qq.com/rain/a/20201120A0B4YG00
https://www.btc126.com/view/103256.html
https://www.bilibili.com/video/av370896681/
```

### Use Case Diversity

(Optional) Any additional information you'd like to share about the use case(s) you plan to support?

```
N/A
```

# Allocation Plan

### Allocation Strategy

How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.

```
In order to prevent clients from maliciously using DataCap, we plan to establish a credit mechanism and cooperate with offline investigations and discussions to screen clients. The credit score depends on the following categories: registered capital, establishment time, the continuity of the amount of stored data, and the authenticity of the stored data. There will be a threshold for the credit score, and clients below the threshold will be banned. The higher the credit score, the more DataCaps can be allocated.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap?

```
All processes will be published to Github, including the results of discussions.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
As the legal person of the company, the person in charge of the organization, will personally participate in it to ensure the safety of DataCap.
```

### Client Due Diligence

How will you vet your Client to ensure they are spending that DataCap responsibly?

```
Similarly, the use of DataCap by each client is continuously monitored through the credit mechanism. Clients below the threshold will be banned.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them?

```
Based on credit mechanism, the following question might be asked:
1. What is the purpose of applying for DataCap? Can you provide relevant supporting materials?
2. How much DataCap do you need?
3. How would you distribute the DataCap you applied for?
4. Basic information of individuals or organizations.
5. etc..
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?

```
Base on the credit score of the client.
```

### Bookkeeping Plan

Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?

```
All processes will be published on Github repository.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both?

```
Yes, it will be public.
```

### Past allocation

Have you previously received DataCap to allocate before? If so, please link to any previous applications.

```
N/A
```

Cumulatively, how much DataCap have you previously successfully allocated?

```
N/A
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations?

```
N/A
```

**Comment by jnthnvctr** [comment]
Hi @lastingman - we took a pass at giving an initial scoring. Please see Column H for feedback: https://docs.google.com/spreadsheets/d/13wMIB-9nt7fagpCjswfleolY-jVKav_zSFrO47U1nm4/edit?usp=sharing

If you make edits, can you update the issue with your changes - and if you have questinos, please comment here! 

Please note also, the rubric for notaries has pending changes - which if approved would potentially affect your scoring: https://github.com/filecoin-project/notary-governance/pull/36

**Comment by lastingman** [comment]
@jnthnvctr I can't open the feedback link. It asks for a permission request. I requested, and the google account is kei*****ves@gmail.com.

> Hi @lastingman - we took a pass at giving an initial scoring. Please see Column H for feedback: https://docs.google.com/spreadsheets/d/13wMIB-9nt7fagpCjswfleolY-jVKav_zSFrO47U1nm4/edit?usp=sharing
> 
> If you make edits, can you update the issue with your changes - and if you have questinos, please comment here!
> 
> Please note also, the rubric for notaries has pending changes - which if approved would potentially affect your scoring: #36

**Comment by jnthnvctr** [comment]
Hi @lastingman - we've scored your application here: https://docs.google.com/spreadsheets/d/1qYHDspT7YvcT0PpL10n5YfwDsDwKzCoaDG7n6GpuCOs/edit?usp=sharing

Eligibility score: 1
Unrounded score: 1.3

**Comment by lastingman** [comment]
@jnthnvctr Is this issue always updateable? Is there a deadline?

**Comment by jnthnvctr** [comment]
You can update this issue for future Notary submissions - but for this wave
I think we need to keep it as is.

If you can join the governance call later today we want to talk about a few
items - including reasonable timeframes where we should evaluate adding
more Notaries and the Foundation has some ideas for tools that they might
open RFPs for the community to help build (to ensure the Notaries who are
picked are abiding by the Principles)!
