### ISSUE TITLE
Proposal: Intermediary Notary Governance call on December 16th at 12am UTC

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/notary-governance#35]
As we draw closer to the end of the year, I propose we add an additional Governance call to the calendar. I propose the Agenda for this call to be contingent on the decisions from the December 8th Governance call and the confirmation of a few key points. 

Specifically - in the December 8th Governance call, if we have confirmed the changes to the Notary Rubric, teams have been given feedback on their applications, and have been given time to propose changes to their application I propose we confirm the next set of Notaries to work alongside the Filecoin Foundation. The reason for adding additional Notaries would be to help accelerate the availability of DataCap for clients, and to scale this mechanism at a reasonable pace. 

In order for the above to possible the following need to be defined and agreed upon: 
- The Dispute / Audit mechanism 
- The confirmation of changes to the Notary rubric (if any)
- The agreement about reasonable guidelines for operation for Notaries acting as Miners and/or Clients. 

Please add additional comments or feedback below.

**Comment by s0nik42** [comment]
Anychance we add this : 

https://github.com/filecoin-project/notary-governance/issues/8#issuecomment-734973234
