### ISSUE TITLE
Next Governance Call: Tues January 11 4pm UTC AND 12am UTC 

### ISSUE THREAD

**Issue by KwrayFF** [filecoin-project/notary-governance#364]
The first Notary Governance Call of 2022 will take place on January 11th at 8am PT // 4pm UTC AND 4pm PT // 12am UTC

You are welcome to attend both! These will be recorded, and video links will be posted in this issue. 
https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx

Agenda topics will include: 
- Updates around the Slingshot Restore Program 
- Check in on the LDN audit process 
- Notaries Discussion Topics 
- Community issues and input

To add to your schedule, the Fil+ Notary Governance calendar is available at
https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles

If you have items to add to the agenda, please comment below!

**Comment by f8-ptrk** [comment]
we'd like to discuss the possibilities of "2nd tier" notaries that are given a datacap they are exclusively allowed to hand out to their projects users. 

Problem: decentralized projects that store data want to offer filecoin backed data storage to their users. right now the project either centralizes the storage deals or each user has to apply for data caps continuously on their own. not only can datacap allocation take a long time - the experience of doing it might hinder the projects adaption and especially the adaption of the filecoin storage features a project might include/offer.

the project that triggered the thought process about this is: https://fx.land/ . I'd like to discuss the general possibility of a notary scheme like this and then, if necessary bring on the project to discuss their specific challenges they, we try to overcome with this scheme

**Comment by KwrayFF** [comment]
> we'd like to discuss the possibilities of "2nd tier" / project-notaries that are given a datacap they are exclusively allowed to hand out to their projects users.
> 
> Problem: decentralized projects that store data want to offer filecoin backed data storage to their users. right now the project either centralizes the storage deals or each user has to apply for data caps continuously on their own. not only can datacap allocation take a long time - the experience of doing it might hinder the projects adaption and especially the adaption of the filecoin storage features a project might include/offer.
> 
> the project that triggered the thought process about this is: https://fx.land/ . I'd like to discuss the general possibility of a notary scheme like this and then, if necessary bring on the project to discuss their specific challenges they, we try to overcome with this scheme in a later call

Can do - thanks for flagging this. Sending a friendly confirmation its been added to the discussion agenda.

**Comment by KwrayFF** [comment]
Link to recorded video: https://youtu.be/p7xGWnf6dMQ

Deck from presentation: https://docs.google.com/presentation/d/1WLY0sVkwyVFKnKaumswcsJDyT9ci_K3o34kqxzTJGJw/edit#slide=id.gfa2d56312a_0_0
