### ISSUE TITLE
Help - Slack Notary Channel

### ISSUE THREAD

**Issue by UnionLabs2020** [filecoin-project/notary-governance#382]
Our former colleague in charge of the slack account has resigned. Can you help me join the notary channel?  Thanks. @Fenbushi-Filecoin @ozhtdong @neogeweb3 @steven004 @swatchliu @wjywood @MRJAVAZHAO @galen-mcandrew @dkkapur

**Comment by neogeweb3** [comment]
@IPFSUnion, sure thing, welcome back. Just ping me on slack (@neogeweb3) and I will invite you.

**Comment by IPFSUnion** [comment]
Happy to be invited by Neo, thanks and  close this issue!

**Comment by IPFSUnion** [comment]
Due to some unresolvable problems of our former colleague, we need to update our notary signing address to f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i . We have also left the message on Slack. @galen-mcandrew @dkkapur @Kevin-FF-USA
