### ISSUE TITLE
Notary Application: CoinSummer

### ISSUE THREAD

**Issue by yuwenhui** [filecoin-project/notary-governance#39]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
- Name: `CoinSummer Labs`
- (Optional) Affiliated Organization: `CoinSummer`
- Website / Social Media: https://coinsummer.com
- On-chain Address(es) to be Notarized: `f163yrswdzukl2oywmgcx3wgtkuljpqc3wlrsae6i`
- Region of Operation: `Greater China`
- Use case(s) to be supported: `Web 3.0, User Content, Developer Tools, Scientific Data, Media & Entertainment, Other`
- DataCap Requested: `200TiB`

_Please respond to the questions below in pargraph form, replacing the text saying "answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
answer here:
```
CoinSummer provide cryptocurrency market insights and reliable data analysis, dedicated to creating a one-stop crypto market research platform. Our products include: crypto market observation, bitcoin analysis, blockchain data, crypto videos, lightning network payment application.

We following the progress of IPFS and Filecoin from the beginning of 2018, and partitcipated on many offline and online activities.

In the early 2020, we joined Filecoin DevNet, TestNet, MainNet, partitcipated on Devgrants and Slingshot, made a huge contribution for Filecoin community. 

More information:
- Github handles: 
  - [Filecoin Awesome resources repo with 109 stars and 57 forks](https://github.com/CoinSummer/filecoin)
  - [Lotus-jsonrpc-provider](https://github.com/CoinSummer/lotus-jsonrpc-provider) and [NPM package](https://www.npmjs.com/package/@coinsummer/lotus-jsonrpc-provider)
- Miner ID: [f02299](https://filfox.info/zh/address/f02299)
- Slack: @K
- Participating to DevNet, TestNet, SR1, SR2, Devgrants, Slingshot(Project: [Yolo](https://yolo.coinsummer.io))

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
answer here:
```

Locked as collateral, vesting over time: 611 FIL
Space Race and Slingshot currently available: 2502 FIL
Evidence: 
- https://filfox.info/zh/address/f02299
- https://filfox.info/zh/address/f3vstwsqdzgtzgldsdll2by4bnah5yzbe5nlgmavuzntsrbk25ks3djnws43lza6ppxp23kjb7irhusahgqqna

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
answer here:
```
We created and maintaining Filecoin Chinese technology WeChat group with more than 1k miners and developers. There are tens of thoursands of messages every day including hardware configuration, mining tutorial, troubleshooting, development sharing,  bug trace and so on. We believe that these are the most active and useful technical community for Filecoin ecosystem.

We also provide proof parameters(v25, v26, v27) and Filecoin blockchain synchronization datastore backup mirrors on Mainland China from the Filecoin TestNet. More than 200 miners use our download service for free.

- [CoinSummer Filecoin proofs parameters mirrors](https://filecoin.coinsummer.io/)
- [Blockchain synchronization datastore backup](https://filecoin.coinsummer.io/datastore.html)

Additionally, we organized and collected [awesome Filecoin resources repo](https://github.com/CoinSummer/filecoin) for Chinese commuity. Including common resource links, lotus node operations, common storage miner operations, seal worker operations, deal operations, environment variables, debugging, benchmarks, frequently asked questions, etc.

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
answer here:
```
We actively participating on slack with more than 1k messages and several github issues. What's more, we have also invited to join the fil-fsrf before MainNet launch for our hard work on Filecoin testing.

Ask, Discuss and Suggestion issues:
- [Issue: failed to load miner actor: actor not found](https://github.com/filecoin-project/lotus/issues/4307)
- [Issue: failed to register deal data for retrieval error](https://github.com/filecoin-project/lotus/issues/4587)
- [Issue: Add tag for each key in the api package](https://github.com/filecoin-project/lotus/issues/3820)
- [Multi-GPU supported for precommit phase 2 discussion](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1594049806157900)
- [Bus error again with latest code of interopnet with 512MiB sector size for the lotus-storage-miner](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1586355098381000)
- [Got an seed changed error in latest interopnet branch after pledging a bunch of sectors (e.g, 192 sectors,  and sector size is 512MB)](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1587908215050900)
- [Fork detected with interopnet for the lotus process](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1586421892412100)
- [Panic: assignment to entry in nil map](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1584534361076200)
- [Finalize sector: prepare move sealed: no available storage: no suitable path for sector fond](https://filecoinproject.slack.com/archives/DU58JPXR8/p1582728758000400)

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
answer here:
```
CoinSummer is a private limited liability company, founded on February 26, 2018. Right now, we have around 20 employees.

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
answer here:
```

Official Website: https://www.coinsummer.io
Weibo: [币夏CoinSummer](https://weibo.com/coinsummer)
Github: [CoinSummer](https://github.com/CoinSummer)

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
answer here:
```
- https://www.sohu.com/a/356903039_468071
- https://zhuanlan.zhihu.com/p/302627217
- https://ipfs.cn/live/info-221453.html
- https://news.huoxing24.com/20201023154220077580.html
- https://www.chainnode.com/post/499616
- https://www.jinse.com/news/blockchain/904620.html
- https://www.chainnews.com/articles/393790899102.htm
- https://www.jinse.com/news/blockchain/904890.html
- https://www.sohu.com/a/432421288_592464

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
answer here:
```
We are keep building decentralized data storage applications based on Filecoin and IPFS. Use cases we are planning to support as follows:
- Through a decentralized, safe and private storage methods, permanently store user generated texts, pictures, videos and other type of data on social media networks like Twitter, Weibo, Instagram, in order to solve the security and privacy issues brought by centralized data storage.
- Store and build opensource image dataset to develop ML and AI models for AI algorithm engineer, Computer vision researcher, Computer Science Students etc.
- Store crypto currency data on Filecoin, like Bitcoin price data, transactions data over the past 10 years.

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
answer here:
```

We will focus on the system rules, improvement and process construction of DataCap allocation. We plan to build an online distribution management system, and will generate a unique CID and IPFS link for all data. These data will be distributed publicly through the management system, and all the distribution processes will  online and publicly.

When assigning DataCap, we plan to establish a credit and scoring mechanism to screen out the highest-scoring clients through investigation and discussion. The credit score depends on the following factors:
- Provide completeness and transparency of registration information;
- Company registered capital, establishment time, team/personal background and reputation;
- Storage cluster capacity, redundancy design and security strategy;
- Continuity and authenticity of stored data.

The data score will have a threshold, and clients below this threshold will be banned. The higher the score, the more DataCap quota can be allocated.

After the pre-review of the above conditions, we will screen out eligible storage clients, and continue to tracking, continue to optimize and adjust the process, the subsequent tracking and feedback mainly reference to the following elements:
- The degree of dispersion and fairness of DataCap allocation;
- Data storage success rate of each client;
- Transparency of distribution;

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
answer here: 
```

All processes including the results of discussions will be published to Github. Online management system will collect the github repo pull requests by github open api.

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
answer here:
```

We plan to use a multi-signature authorization model for DataCap allocation.

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
answer here:
```
We need to investigate and understand clients detailed. Clients need to clarify how the DataCap will be allocated, build a fair mechanism, and store all operation history and information in database for review and tracking.

We are preparing the following questions to vet our client:
- Basic clients information, project information and progress;
- Why they apply the DataCap?
- Client credit rating information;
- Client security evaluation;
- Client DataCap allocation quota;

The above questions will be calculated to obtain a comprehensive score. Clients whose score and credit are lower will not be allocate DataCap.

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
answer here: 
```

Based on credit mechanism, the following question might be asked:
- What's your project? Could you provide project progress?
- Can you provide relevant supporting materials for the purpose of DataCap allocation?
- Hou many DataCap you want to apply?
- How will you distribute your allocated?
- Your basic information of individuals and organizations?

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
answer here: 
```
We believe that open and transparent distribution rules, and strict and pragmatic execution are important factors to ensure that there will be no over-allocating DataCap to a single entity. All allocation processes will be publish online, and distributions that are too centralized will not be allowed.

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
answer here:
```
Yes, I fully support the recording of the allocation decision, all processes will be published on Github repository.

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
answer here:
```

Sure thing, we will take the public allocation on Github repo to make sure the principle of fairness, transparency and openness.

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
answer here:
```
None

Cumulatively, how much DataCap have you previously successfully allocated? 
```
answer here:
```
None

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
answer here:
```
None

**Comment by jnthnvctr** [comment]
Hi @yuwenhui - we've scored your application here: https://docs.google.com/spreadsheets/d/171WUhryD8MnKjImM_7psjYesJPQ8XT4swIYIzYJs0PU/edit?usp=sharing

Eligibility score: 2
Unrounded score: 1.7
