### ISSUE TITLE
Modification: Notary Rubric - Typos and usability fixes

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/notary-governance#393]
## Issue Description
Small fixes made to the Notary Application Scoring Rubric. Full list of changes recommended is below.

## Impact
Minimal impact, improves readability, speed of scoring, and audit trail for future. Always good to hold our resources and tools at a high standard.

## Proposed Solution(s)
Specific issues and recommended fixes:

- "Use Case Diversity" row has "geography" instead of "use case" at the L2 cell -> change this to "use case"
- "Use Case Diversity" row has inconsistent spelling of use case (in some cells, it is "usecase") -> update to make this consistent, "use case"
- "Bookkeeping Plan" L5 requirements are same as L4 -> move them to L5, and remove L4 instead, making it consistent with other rows in the spreadsheet
- "In-protocol Security" L5 requirements are same as L4 -> move them to L5, and remove L4 instead, making it consistent with other rows in the spreadsheet
- Reorder rows in the spreadsheet to make data processing and following the math more intuitive. Here is a screenshot of the recommended solution (with the changes in https://github.com/filecoin-project/notary-governance/issues/391): ![image](https://user-images.githubusercontent.com/2343218/150936527-a22b5852-505a-415a-91c7-3ce4728caf78.png)

**Comment by Kevin-FF-USA** [comment]
Based on feedback and approval during the January 25th [Notary Governance Meeting, ](https://youtu.be/HCsFAGxbGAk) will be implementing these updates to the scoring rubric.
