### ISSUE TITLE
Modification: Notary Rubric - Change to final allocation amount score formula

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/notary-governance#394]
## Issue Description
Recommending a change to the `Final Allocation Amount` formula for Notary Application scoring, which is used to calculate the final score used in ranking applicants. This is also used to identify how much DataCap can be allocated to a notary (up to the eligibility specified in the "Allocation Ranking" of the rubric).

## Impact
The current final score calculation formula in the notary rubric is `Final Allocation Amount =MIN(ROUND(0.5*Track Record + 0.3*Weighted Notary Leveling + 0.2*Concretness of Allocation Plan), Scale of Allocation)`. This is suboptimal for the following reasons: 
- it incentivizes notary applicants to put in a high target of DataCap allocation regardless of whether or not they have the time to support the clients needing it. If this factor is replaced with Engagement in Program (as described in #391) then this has an even stranger impact on the outcome - where a Notary willing to commit a reasonable minimum amount of time to the program suddenly undermines their entire application.
- while Track Record is weighted at 50%, this still does not appropriately adjust incentives for current notaries to serve to their best ability and makes it harder for them to re-apply in the future. In general, as the Fil+ program continues to expand, it makes more sense, at least in the near term, to prioritize having more notaries that are active rather than constraining growth.
- Concreteness of Allocation Plan is only weighted at 20% - as notaries shift more towards being guardians of the network, due diligence expectations will increase and dependency on good audit trail is important. 

## Proposed Solution(s)
`Final Allocation Amount = MAX(ROUND(0.3*Scale of Allocation/Engagement in Program+ 0.3*Weighted Notary Leveling + 0.4*Concreteness of Allocation Plan), Track Record)`
- adjust weight of Concreteness of Allocation Plan to 40%
- swap Scale of Allocation/Engagement in Program with Track Record in the formula, adjust weight to 30%
- switch function MIN to MAX-> highly performing notaries auto-rescore at the allocation they scored in the past

Additional considerations / ideas:
- Take (Track Record - 1) instead of just Track Record, ensuring that re-applying notaries still have to put in similar effort into net new applications for the position and update their profile in the community. Most re-applicants copy-paste a majority of their past application, so not sure how useful this is.
- This basically ensures well performing notaries will get re-elected... so we should take this opportunity to more concretely define what it actually means to be a well performing notary so that a notary that deserves high reputation in the system has earned it and should be rewarded for it. Specifically, this could mean:
  -  following through on their allocation plan 
  - maintaining high responsiveness, i.e., TTD < 3d, Slack responses in < 1d
  - being engaged in the community (come to governance calls, participate in issues/discussions)

## Related Issues
#391 
#392

**Comment by Kevin-FF-USA** [comment]
Based on input collected during the January 25th Notary Governance call, and no other comments here, proposing to close this issue and finalize the proposed changes to the scoring rubric.
