### ISSUE TITLE
Next Governance Call: Tues Feb 8 4pm UTC AND 12am UTC (Feb 9)

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#395]
The third Notary Governance Call of 2022 will take place on Feb 8 at 8am PT // 4pm UTC AND 4pm PT // 12am UTC (Feb 9th depending on time zones)

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](url)

Agenda topics will include:
Program Metrics
Notary Election Updates
Notary Election Scoring 
Community discussion of issues and input
> If you would like to add an item to the agenda, please comment in this issue.

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles

**Comment by xinaxu** [comment]
I'd like to present my projects to get approval from notaries. They are related to Slingshot and Slingshot recovery.

**Comment by davidthoms** [comment]
Hi, Dave from Coffee Cloud here. I'd also like to present tomorrow. The deck is linked below: 
https://docs.google.com/presentation/d/1Da9Ogg4xywq4PX1q8Wv67xKf6xXi2MBQDgVGDgzI5qg/edit?usp=sharing

**Comment by MasaakiNawatani** [comment]
Hi Kwray, good day! I was wondering when will the video and deck for Feb 8th call be available? Thank you so much.

**Comment by Kevin-FF-USA** [comment]
Thanks for your patience - Feb 8th call is now online.
https://youtu.be/YNdyT-PGQIM
