### ISSUE TITLE
Notary Application: Filecoin Foundation

### ISSUE THREAD

**Issue by philippbanhardt** [filecoin-project/notary-governance#4]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Philipp Banhardt
- (Optional) Affiliated Organization: Filecoin Foundation
- Website / Social Media: @philipp on the Filecoin Slack 
- On-chain Address(es) to be Notarized: f1sdzgaqmitbvgktkklpuaxohg6nuhce5eyvwxhaa
- Region of Operation: Europe
- Use case(s) to be supported: General
- DataCap Requested: 100TB

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
As an individual, I’ve worked to help support a number of prominent community members (notably Protocol Labs, Textile, & OB1). More recently, I’ve transitioned to help set up the Filecoin Foundation, where my role is to help steward the Filecoin ecosystem and foster growth.

Across these two forms of involvement, I’ve been a part of the Filecoin community since 2016. 

As an organization, the [Filecoin Foundation](https://fil.org/about) is an independent organization dedicated to supporting Filecoin.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
100mm tokens, per the vesting [schedule](https://coinlist.co/filecoin). 
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Besides supporting Protocol Labs in building Filecoin financially, I have spent time working on Ecosystem development while both being part of Protocol Labs in 2019, and now with my role at the Filecoin Foundation. At Protocol Labs I was involved in helping draw up the early roadmap for developer engagement. At the Foundation I am managing the developer grants program.

The Filecoin Foundation is an independent organization dedicated to supporting Filecoin, an open source, decentralized storage network designed to preserve humanity’s most important information.The Filecoin Foundation facilitates governance of the Filecoin network, funds critical development projects, supports the growth of the Filecoin ecosystem, and advocates for Filecoin and the Decentralized Web.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
None
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
https://fil.org/about/

The Filecoin Foundation is an independent organization dedicated to supporting Filecoin, an open source, decentralized storage network designed to preserve humanity’s most important information.The Filecoin Foundation facilitates governance of the Filecoin network, funds critical development projects, supports the growth of the Filecoin ecosystem, and advocates for Filecoin and the Decentralized Web.

The Filecoin Foundation was founded in 2020 is registered in the US. 
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://fil.org/ 
https://www.linkedin.com/in/philipp-banhardt-24646834/
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://finance.yahoo.com/news/filecoin-foundation-appoints-initial-staff-103014932.html
https://traderszone.net/filecoin-foundation-says-tech-luminaries-will-help-project-suceed
https://news.huoxing24.com/20201022204827321479.html
https://www.enterpriseai.news/2020/10/23/filecoin-foundation-and-ffdw-launch-to-advance-the-dweb/ 

```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
The intent with this allocation is to help beta test the entire Filecoin Plus mechanism. As such, all use cases will be considered - with the primary focus being on identifying strategies for future notaries to best approach vetting clients. 
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
The high level strategy is to set thresholds with varying degrees of trust. As a standard practice, for relatively small amounts of DataCap (gigabyte scale) the aim is to make the process relatively painless - with higher thresholds requiring greater scrutiny.

Several factors will be considered when making allocation decisions: 
Reputation of organization
Scale of allocation
Frequency of allocation
Security considerations
Transparency of Client

```

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Currently, none - however the aim will be to allocate the limited DataCap I have (during this beta) to a diverse set of Clients to enable early key use cases: (1) public datasets that are high trust, unambiguous, and easy to maintain; (2) distinguished slingshot teams; (3) Web3 data.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The address that will be allocated DataCap will have it’s keys be secured on a hardware wallet. 
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
Depending on the scale of the allocation this may vary. For higher levels of allocation, there will be greater care and attention to both the quality of the Client, the diligence with which they intend to spend the DataCap, and the acknowledgement of the overarching Principles of this process.  

Generally I expect due diligence for public datasets to surface strong evidence that a thriving maintainer base exists that exhibits a high trust reputation within its universe. Distinguished slingshot teams will be active participants within the Filecoin community and on a high growth / product trajectory. Web3 data are key dapps with an engaged and growing user base. 

During this process, I intend to share basic strategies for Clients to consider as they make their storage deals.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
The plan is to try and keep asks for information matched with the amount of DataCap being requested. Some of the questions, but not all, can be found [here](https://github.com/filecoin-project/notary-governance/blob/main/notaries/templates/sample-client-application.md).
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
During the initial phase of this test this process will follow our intuition on clients and good will, however we plan to invest in building technology that can help manifest a process that is robust, secure and pragmatic. 
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
All allocation decisions will happen in public in the following [repository](https://github.com/keyko-io/filecoin-notaries-onboarding) - all communications will also take place through the repository and the issue tracking. 
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will happen in public in the following [repository](https://github.com/keyko-io/filecoin-notaries-onboarding)
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None
```

**Comment by jnthnvctr** [comment]
@zixuanzh  and I took a pass to go through the Notary Rubric and assign a score: 

For more detail: 
https://docs.google.com/spreadsheets/d/19p4ivDykWxj3TmeVuCAP7SctlHHDZmUbJAlllKv8KhI/edit?usp=sharing

Summarized: 
Long Term Network Alignment | 5
Industry Reputation | 0
Diversity and Decentralization  | 5
Weighted Notary Leveling (see cell) | 3
--
Concreteness of Allocation Plan  | 1
Track Record | 1
Scale of Allocation | 3
--
Final Allocation Amount | 2

Since the amount requested was 100TB, and at a L2 you're eligible up to 100TB - we propose allocating 100TB of DataCap to your address.

**Comment by jnthnvctr** [comment]
With no other comments, based on the call earlier today - I believe we can confirm this is approved. 

## Request Approved
#### Address 
> f1sdzgaqmitbvgktkklpuaxohg6nuhce5eyvwxhaa
#### Datacap Allocated
> 100TB

**Comment by jnthnvctr** [comment]
Reopening for the filecoinplus.on.fleek.co app

**Comment by jnthnvctr** [comment]
Allocated: https://filfox.info/en/message/bafy2bzaced5mqh2wim4ffcrpyncwjlyj36m75lr3lxw6t7kzprjszjuy7f64k
