### ISSUE TITLE
Next Governance Call: Tues Feb 22 8am PT / 4pm UTC -and- 4pm PT / 12am UTC

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#404]
The forth Notary Governance Call of 2022 will take place on Feb 22 at 8am PT // 4pm UTC AND 4pm PT // 12am UTC (Feb 23th depending on time zones)

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:
Program Metrics
Notary Elections
Community discussion of issues and input

    If you would like to add an item to the agenda, please comment in this issue.

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/issues/407 got added today, let's discuss in this call!

**Comment by Kevin-FF-USA** [comment]
https://www.youtube.com/watch?v=r-f8CqHgqmk&list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx&index=1&t=55s
