### ISSUE TITLE
[Notary Application] - Blockchain World - Sounghwan Park

### ISSUE THREAD

**Issue by psh0691** [filecoin-project/notary-governance#408]
# Notary Application
To apply to be a Fil+ Notary, please review the Notary Overview and then fill out the following form. 

## Core Information
- Name: Sounghwan Park
- Affiliated Organization: BlockchainWorld
- Website / Social Media: http://bcwnews.com/, @psh0691 on the Filecoin/Slack and Github
- On-chain Address to be Notarized: f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
- Region of Operation: Asia-GCN
- Use case(s) to be supported: general, blockchain data, other
- DataCap Requested: 1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
(1) I'm Sunghwan Park. I'm a researcher at Blockchain World News(bcwnews.com) and I'm working hard to expand the filecoin ecosystem by providing filecoin information, publishing news, and testing filecoin node operation.

(2) Since 2020, we have been distributing more than 300 filecoin related information on document translation, news issuance, planning series, websites, and social networks. In addition to Blockchain World, "IPFS Today," a channel specializing in IPFS/filecoin, has recently been established and is contributing to the expansion of the filecoin ecosystem by providing in-depth information.
(Note: Latest news release)
http://bcwnews.com/6622
http://www.ipfstoday.co.kr/421

(3) Although not an engineer, it operates a filecoin node, collects, analyzes, and distributes related filecoin information. A day before the mainnet of Filecoin was opened in October 2020, I received 100FIL of Filecoin from Protocol Labs.(t010590, t019208, t022309, f022309)
https://drive.google.com/file/d/1dqHOHLJg-R9H2PHzrZVVuCBdBuLj3ME8/view?usp=sharing

(4) Account(f096173), which is currently operating on a single PC for filecoin network analysis and test data collection, actually tests FilePlus(FIL+) using hyperdrive and DataCap, analyzes and provides information on theories and actual results.

(5) I applied for registration in the first ESPA program to contribute more to the FileCoin Network, but the spread of Omicron in COVID-19 has delayed the initial schedule and prevented me from attending, and I am waiting to attend the next round. The following are emails exchanged after applying.
https://drive.google.com/file/d/1L3myOGJ9JGuVxtWHwrX23q1kFwmyicKF/view?usp=sharing


(6) Recently, we applied for a large datasets through Blockchain World News and received approval, and are preparing to board the filecoin network.
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/166
```
### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
I prefer not to disclose.
```
### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
(1) In the early days of the 2020 Filecoin TestNet, I received an e-mail response by requesting Korean language support from the Filecoin Forum without any Korean documents, and there were difficulties at the time due to the weak Korean community. Thank you for the creation of a Korean community in Slack. The following picture is the mail reply received at the time.
https://drive.google.com/file/d/1MJGvlpTZK1l-xSz4vlWkbHqs-zeqZfYh/view?usp=sharing


(2) In the absence of the Korean community, the original texts such as "Filecoin White Paper", "Introduction of Filecoin" and "Filecoin Economics" were translated and distributed, and are currently uploaded to the Korean community. In addition, we created a "Lotus Commands" and distributed it free of charge for the operation of the Filecoin Node.

https://filecoinproject.slack.com/files/U015UM4ETJL/F01GGKL3ABU/lotus_command.pdf
https://filecoinproject.slack.com/archives/C02BK7L2ZGC/p1644071999307739

(3) Since May 2020, three promotional videos of Protocol Labs' filecoin have been produced in Korean subtitles and uploaded to YouTube.
https://youtu.be/e0gcQqegmpA

```
### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
I have never submitted a filecoin bug because I am not an engineer. However, we provided the latest news to the general public and storage providers through various media such as Filecoin-related websites, social networks, and Slack.
```
### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
- Organization : Blockchain World
- Nature : Blockchain news, IPFS/Filecoin news, Economic news
- Registration Country : Seoul, Republic of Korea
- Size : 10 employees
- Since : Jan, 2021
```
Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
- Blockchain world : http://bcwnews.com/ 
- IPFS Today : http://ipfstoday.co.kr
```
Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
- Blockchain world(BCW) & IPFS Today
(1) It is a medium that intensively covers and reports economic and blockchain news and provides various media such as text, photos, cartoons, and videos so that news subscribers can make correct judgments. In particular, the latest IPFS/file coin information is distributed through the 'IPFS Today' channel. 
Currently, the number of members is about 3,000, which varies depending on the news, but an average of 500 visitors a day visit.

(2) Personally, a total of 105 planned serials were conducted on Blockchain World News by dividing blockchain knowledge into three stages: basic, advanced, and application.
http://www.bcwnews.com/sub.html?section=sc30

(3) It operates a blockchain world blog to collect only headline news every day, produce and distribute videos, and provide basic knowledge about blockchain, cryptocurrency, and filecoin.
https://blog.naver.com/bcwnews
```
### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Any data that helps the growth of the filecoin network other than illegal, harmful, or unverified encrypted files is fine. However, first of all, I hope it is useful for mankind, and next, it is highly searchable.
In particular, I am interested in blockchain-related data in addition to public data in line with the trend of the times, and I hope there will be many cases of use in K-pop(music videos), K-drama(movies), and e-sports(game videos) considering the regional characteristics of Korea.
```
# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
(1) The allocation plan is largely divided into data with customers, and customers classify their type(reputation) and reliability(performance) into data types(importance), distribution(storage SP, region), and volume(size) from L1 ~ L5, and score them. 
The detailed allocation plan is as follows.
https://docs.google.com/spreadsheets/d/1SrzXI4pe1QHkBgDCu9Ot0Li8oxB38jcxFnra2HepAI4/edit#gid=622434591

(2) The most important evaluation of DataCap allocation is to first store important and useful data to preserve humanity's important history, such as the vision of Filecoin.

(3) We will share detailed allocation plans and results with customers, determine whether fair scores are given or not, and cooperate with each other to help grow the Filecoin network.
```
Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
(1) We saw a case where the allocated data upper limit was not loaded into the actual Filecoin network. Rather than the DataCap allocation goal, the company plans to teach customers how to understand DataCaps and become verified customers through 1:1 online and offline support so that useful data can be mounted on the actual network as much as possible.

(2) The procedure for basic acceptance approval and follow-up measures is as follows.
  1. DataCap applications are received in the form of including basic customer information.
  2. The assignment requirements are notified to the customer, and the results are notified after a fair score is given.
  3. We receive additional data submissions along with the period to correct and compensate for defects.
  4. It will be approved once an agreement has been reached with the customer on the DataCap allocation.
  5. Maintain a continuous relationship with customers after approval to track whether data is loaded into the Filecoin network and support and communicate with necessary parts.
```
How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
As a person who wants the growth of Filecoin more than anyone else, we will help both storage providers and customers, eventually helping the growth of Filecoin networks.
If you unconditionally approve illegal data and data that adversely affects society by creating customers who have not been verified for abuse of DataCap, this will also undermine Filecoin's reputation.
Therefore, we will pay close attention to ensure that the approval of the applied customer is not omitted, while ensuring fair and fair DataCap approval.
```
### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
(1) Offline verification of the customer's data will be the surest way, but we will look at all channels that can verify the data online.
(2) In the case of institutions, we will verify the industry, business license, website, news search, data source, size, and storage plan.
(3) In the case of individuals and others, we will examine whether it is public data, illegal or harmful data, and verify data sources, data volumes, and storage plans.
```
What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
(1) What is the purpose of requesting DataCap?
(2) Can you tell me the name, region, country, type, homepage address, and data manager of the institution?
(3) Are personal information, illegal content, and harmful content in the data?
(4) What size would you like to request for DataCap?
(5) Have you ever been assigned a DataCap? If you have any, please let me know the details.
(6) Which country and region will use DataCap?
(7) How long are you planning to save the data?
(8) Are you a storage provider?
(9) I will ask you a question referring to the following.
(https://github.com/filecoin-project/notary-governance/blob/main/notaries/templates/sample-client-application.md)
```
What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
As stated in the allocation plan, we will allocate within 10% of the total amount of the requested DataCap initially and gradually increase and allocate depending on whether or not to board.
```
### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
1. All all allocation decisions and DataCap use will be publicly recorded in the File Plus dashboard.
   https://filplus.d.interplanetary.one/notaries
2. A list of customers who requested all data caps will be created and the allocation level for each order according to the allocation plan will be observed.
```
Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
I think the non-disclosure application and approval of the DataCap should be carried out entirely publicly to prevent misunderstandings and misuse. If there are customers who apply privately (e-mail, Telegram, etc.), we will provide detailed information on the open application process.
```
### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No
```
Cumulatively, how much DataCap have you previously successfully allocated? 
```
No
```
Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
No
```

**Comment by galen-mcandrew** [comment]
[BlockChain World - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320884/BlockChain.World.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by psh0691** [comment]
> [BlockChain World - 3차 공증인 선거 스코어카드.pdf](https://github.com/filecoin-project/notary-governance/files/8320884/BlockChain.World.-.Round.3.Notary.Election.Scorecard.pdf)

1. Do you have an example of SLA/participation?

**Comment by psh0691** [comment]
Thank you for your feedback

Here are some corrections and additions to the feedback.

**1. Fil+ related activites**
- Automatic DataCap
For FilePlus testing, we have stored a total of 22 data in f096173 automatically allocated data. 
We have produced and distributed recent news related to FilePlus and news to promote Filecoin. The following is a link to FilePlus and related news publication.
http://bcwnews.com/6917
http://bcwnews.com/6834
http://bcwnews.com/5398

- General DataCap
- I have applied for General DataCap directly to the notary public and am currently waiting for approval.
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1637

- Large DataCap
We applied for a large datasets through Blockchain World News and received approval, and are preparing to board the filecoin network.
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/166


**2. Client Due Diligence**
- Due Diligence / Questions
Personal clients are mostly verified through online accounts. For organizational clients, it should be easy to check with applications and related evidence. 
Ensure that any customer who wants to store data on the file coin network is unencrypted public data that anyone can access. If the data is not accessible, it is not easy to store it on the file coin network at the moment, so if it is encrypted data, a separate due diligence process will be required to view the data in advance.  
This is the due diligence procedure for the agency client.
I would like to borrow the KYC procedure of the cryptocurrency exchange to check the necessary information. 
First, check the certificate of business registration, corporate certificate, and other government-issued organization certificates with the agency information, and check the certificate or other evidence to prove the ownership of the data.
Next, we will check the certificate issued by the head of the agency for the applicant and check the photo of the desired posture and memo at the same time with the government-issued ID card or passport.

- QUESTIONS TO KNOW YOUR CUSTOMER
1. Please introduce yourself. Please let me know which social media I can contact.
2. Please introduce your organization. And what is your role in the organization?
3. How did you find out about the file coin network and file plus? 
4. In what area are you going to use DataCap? 
5. Please introduce the data ou want to store using DataCap.
6. How many storage providers will use DataCap to store data?
7. Do you have any storage providers around you that you know or are working with? Please let me know if you have any.
8. Are you in favor of disclosing the allocation procedures and usage of DataCap so that it does not harm the file coin network ecosystem in a dishonest way?

- additional previously validated client DataCap allocation procedures
First, check the previously allocated DataCap usage history using the File Plus dashboard and tools. To increase network growth and file coin network reputation scores, make sure that there are no unfair or abnormal transactions and that normal data is stored. In addition, in order to improve data storage and stability, you must allocate it to at least different 5 SPs.
https://filplus.d.interplanetary.one/clients
https://pluskit.io/home
https://www.atpool.com/en/dataCap/myIndex/customer
https://metawave.info/#/
https://filecoin.tools/

Then, I will check with the customer through questions and start the process of allocating additional DataCap.
The questions are as follows.
1. How much is the cumulative DataCap you received before?
2. Where do you use DataCap?
3. How many SPs did you allocate or distribute to?
4. What kind of method did you mainly use to deliver data? online, offline, and other methods
5. What is the special agreement with SP?
6. Was there any difficulty in dealing with SP?
7. Have you searched the data stored after dealing with SP?
8. What DataCap are you trying to add? Is it an increase in existing data? Or is it a new kind of material?
9. Do you have any other questions or requirements?
10. Is there any service to improve?

**3. Bookkeeping plan**
- Publicly accessible record-keeping plan
Github : https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues
Website : https://filplus.info/

The allocation of DataCap will be carried out by a public scorecard. Therefore, it is determined by the objective judgment and interaction of notaries, customers, and outsiders, and each person is responsible for the decisions.
Objections are made online(filecoin-plus-client-onboarding) and published.
Customers can apply to notary-governance for dispute resolution if the notary fails to provide a reasonable reason for two weeks after receiving the objection.
In order to resolve the dispute, the notary public will appoint an arbitrator and deal with RKH at the arbitrator's decision within one month.

**4. SLA/participation**
 - More than 20hours per week(4h/day)

**5. Social media**
 - Telegram : Park sounghwan,
 - Twitter : SounghwanP,
 - KakaoTalk : (open chat https://open.kakao.com/o/sv2h2k7d), 
                (General chat : 0691psh)

If there is anything else that needs to be corrected, please let me know.

**Comment by galen-mcandrew** [comment]
[Sounghwan Park - UPDATED - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8373140/Sounghwan.Park.-.UPDATED.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by psh0691** [comment]
Hi @psh0691 based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm that the region of operation for client applications you will focus on is Asia minus GCN.  
> Acknowledged
Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

• Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .

• Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 

• Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 

• No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

• Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

• Community Governance Participation: It is expected that you will participate in the program 20 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 

Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

(If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
• If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by galen-mcandrew** [comment]
@psh0691 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by psh0691** [comment]
@galen-mcandrew
I'm sorry.
I recently received Ledger nano X.
Request to change the address.

f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i

Thank you.

**Comment by Kevin-FF-USA** [comment]
Hello @psh0691!

We have updated the tracker with: f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i

We will communicate with you on Slack via psh0691.

**Comment by galen-mcandrew** [comment]
I have updated the parent comment for your new ledger address. Please confirm your ledger address using the verification tool in the [Fil+ Registry app](https://plus.fil.org/).

[Here](https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing) is a troubleshooting guide.

Thanks!

**Comment by psh0691** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebiwbok3nngjr3vzhgi6stitpkwcaqj7mfs5jfsv463fqa3sxdjsg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebiwbok3nngjr3vzhgi6stitpkwcaqj7mfs5jfsv463fqa3sxdjsg

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Datacap Allocated
> 1PiB

**Comment by psh0691** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecespx6tvxqaogsrslbsvgvqalesx5fbgrhlk7gwtarpsvuwgvgmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecespx6tvxqaogsrslbsvgvqalesx5fbgrhlk7gwtarpsvuwgvgmq

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzaceckxjhh6hxvdeogpttgtbruvc7aiw2neutbs3vplduiyicg4s4g2i
