### ISSUE TITLE
[Notary Application] - Kernelogic - Fei Yan 

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/notary-governance#409]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Fei Yan
- Affiliated organization: Kernelogic (sole corporation / self-employed)
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address): f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
- Region of Operation: North America
- Use case(s) to be supported: Slingshot Restore, Scientific Data
- DataCap Requested: 5PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Joined filecoin mining since testnet f010617.
Successfully finished a dev grant https://github.com/filecoin-project/devgrants/blob/4267d83cf06219aec464ea143090480a089733da/open-grant-proposals/open-proposal-music-nft-portal.md
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Vested FIL on f010617: 3000
Other available FIL: 9000
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Participated in SpaceRace
Participated in Slingshot 1, 2.1-2.7, restore.
Selected as MinerX 1, 2, 3.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Reported and participated a lot lotus github issues https://github.com/filecoin-project/lotus/issues?q=kernelogic
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
I have a 100% self owned Canadian corporation. Incorporated since 2011-06-29.
https://opencorporates.com/companies/ca/7906943
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Not much, my Linkedin https://www.linkedin.com/in/feiya200/
Twitter https://twitter.com/activecollabmod
Slack @Fei Yan
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Linkedin https://www.linkedin.com/in/feiya200/
Twitter https://twitter.com/activecollabmod
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Linkedin https://www.linkedin.com/in/feiya200/
Twitter https://twitter.com/activecollabmod
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
I have been granted and used several PiBs of LDN and I wish to contribute back to the LDN program as I am very familiar with the process.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
I plan to allocate 500TiB to 1PiB per client on the LDN program. I can grant within 2 business days from a request is submitted.
I have been in the program long enough to know the time sensitivity matters.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Do personal due diligence with the help of allocation percentage, community exposure and adhoc chats.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Do personal due diligence with the help of google, social media, community exposure and adhoc chats.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Do personal due diligence with the help of various statistics from https://filplus.d.interplanetary.one/ as well as filfox.info
If it's suspicious I will raise it in the notary channel for future process. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
In public via github repo.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
I can make a google sheet for it.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
8 hours
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/46
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/59
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/60
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/136
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/134
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/198
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
About 2PiB, all distributed and satisfied with notaries.
```

**Comment by galen-mcandrew** [comment]
[Kernelogic - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320954/Kernelogic.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by kernelogic** [comment]
I think the scores for Stake exposure could use a different set of numbers for individual applicants. The current minimum stake is 100K FIL (market value of 1.8MM USD) which is very high for an individual.

Also to amend my terms, I will also consider validating non-LDN requests when there is no more LDN requests to approve within my time limit. As I am known to be very responsive on slack and emails, I think I will be a great addition to the Time-to-Datacap.

**Comment by Kevin-FF-USA** [comment]
Hi  @kernelogic  **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is North America.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 8 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by galen-mcandrew** [comment]
@kernelogic 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @kernelogic!

This is a friendly ping - we have received your information, but we cannot find the Slack handle you provided (@Feiya200). In order to receive Notary communications via Slack we need you to: 

- Provide a Slack handle within this GitHub ticket (for public record)
- Message Kevin_FF on Slack with that same Slack handle you entered in this ticket.

**Please provide this information by April 25th. Thank you!**

**Comment by Kevin-FF-USA** [comment]
Hello @kernelogic!

I have updated your information and added you to all notary communications. Thank you!

**Comment by galen-mcandrew** [comment]
@kernelogic 

Is f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa the most recent? Are you able to verify your ledger address using the verification tool in the [Fil+ Registry app](https://plus.fil.org/).

[Here](https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing) is a troubleshooting guide.

**Comment by kernelogic** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebvcilqmb4l746yjdj6jyoydxytseia4ypmbvpcsuuszh33clqmna
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvcilqmb4l746yjdj6jyoydxytseia4ypmbvpcsuuszh33clqmna

**Comment by kernelogic** [comment]
@galen-mcandrew thanks for the reminder. Seems it went through. I did try to verify a few weeks ago but it wasn't working before.

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Datacap Allocated
> 1PiB

**Comment by kernelogic** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedq4vl2gayvytmrizbfvvs5stnwxldluh3irgogfnz2jza47fsuvy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedq4vl2gayvytmrizbfvvs5stnwxldluh3irgogfnz2jza47fsuvy

**Comment by kernelogic** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecbckuvpdla74cfly25r3ybiwidnovgvy3zu7e3vzpi3j3bli7juo
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbckuvpdla74cfly25r3ybiwidnovgvy3zu7e3vzpi3j3bli7juo

**Comment by kernelogic** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceasqefumyevoton67uro47liuvxzcyfj4ncye4nvnxaqouioixfzo
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasqefumyevoton67uro47liuvxzcyfj4ncye4nvnxaqouioixfzo

**Comment by kernelogic** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebuag6gfbuhaowktxgxqy6kjxhz24quvtrranjxro6xqvwjpts5zq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebuag6gfbuhaowktxgxqy6kjxhz24quvtrranjxro6xqvwjpts5zq

**Comment by kernelogic** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedxly5wlczdk55ti7cztkavdl7tpted2fmocg25v676r7c4slpmae
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxly5wlczdk55ti7cztkavdl7tpted2fmocg25v676r7c4slpmae
