### ISSUE TITLE
[Notary Application] IPFS Japan Consortium - Masaaki Nawatani

### ISSUE THREAD

**Issue by MasaakiNawatani** [filecoin-project/notary-governance#410]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Masaaki Nawatani
- Affiliated organization: IPFS Japan Consortium
- Website / Social Media:
- On-chain address to be notarized: f1ciu27vn3r7htmanzvwrm6ksx6y774gqsz3cot3i 
- Region of Operation: Asia minus GCN
- Use case(s) to be supported: Web 3.0 / Decentralized Applications
- DataCap Requested: 1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
We are committed to push meaningful distributed storage to as many verifiable, high-value clients as possible. 
As one of the first Notaries elected since the inception of Filecoin Plus, my team and I have spent a large amount of time in helping the cause and being an active Notary member in the community. 
I have a near perfect attendance in all of the Notary Governance Calls and have had good working relationships with the Notary Admins via Slack and Github, and other Notaries as well.
In 2021, I was elected as a director of the IPFS Japan consortium - a nonprofit organization which educates and encourages Japanese people to use IPFS and filecoin. I applied as a Notary under the organization name of Blotocol for the 1st and 2nd round, and will now be applying under **IPFS Japan Consortium** for this round. My profile on IPFS Japan consortium is here https://ipfsjapan.org/about/Masaaki Nawatani is 縄谷正明 in Japanese

Github handle is MasaakiNawatani
Slack handle is Masaaki Nawatani.

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
I prefer not to disclose.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As one of the pioneer Notaries assigned to the Asia-GCN region, I have spent a considerable amount of time helping the cause. I have made good working relations with Deep Kapur, Jonathan Victor, KWray and Galen McAndrew, as well as with other notaries. The strategy that I use in conducting due diligence to my clients has been efficient and definitely contributed to the growth of clients coming from Asia, especially in South Korea. I was able to assist 52 client applications in this round and was able to allocate a total of 104.23 TB of Datacap to clients that I have verified. After I got in the position of director for IPFS Japan consortium, I had some conferences and seminars and made articles and video contents to educate Japanese people and encourage them to use IPFS and filecoin. As a result of these efforts, I was able to open opportunities for several clients who are interested in the filecoin plus program, and more than 8 new clients applied for the filecoin plus program. [Reference](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues?q=is%3Aissue+assignee%3AMasaakiNawatani+is%3Aclosed).

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Being part of the pioneer group of Notaries elected, there were many obstacles and technical challenges that we faced. I have raised concerns, not as an issue on Github, but via Slack, when we experience any inconvenience or impediment to the allocation flow and was instrumental in the improvement of certain components of the Client onboarding experience.  

```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
IPFS Japan Consortium aims to improve Japan's industrial competitiveness through technologies centered on IPFS. For this reason, companies and experts whose core businesses are Internet communication and data center-related businesses play a central role in promoting industrial utilization, human resource development, making proposals to public institutions and industries, international cooperation, and dialogue with society. We will carry out activities necessary for sound development.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://ipfsjapan.org
Officers on Slack: @obbie-one 
LinkedIn: https://www.linkedin.com/in/masaaki-nawatani/
https://www.facebook.com/IJCFB/?ref=pages_you_manage
https://twitter.com/IPFS94660609

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
 The articles which I supervise
https://note.com/ijc
https://media.ipfsjapan.org/


//YouTube Education video contents for IPFS and filecoin
These contents are made by me.

https://www.youtube.com/channel/UCw6G6MIt3f26e8pglcbJ18Q

Part1：https://www.youtube.com/watch?v=cb3kxJW3Kw8&t=98s
Part2：https://www.youtube.com/watch?v=i_nrZgruz_g
Part3：https://www.youtube.com/watch?v=2rC6C0CegdA
Part4：https://www.youtube.com/watch?v=y75pzq5eVt0
Part5：https://www.youtube.com/watch?v=n0qdUVytXWA
Part6：https://www.youtube.com/watch?v=OTN27G1DY3A


//The conference of 1th anniversary of filecoin.
This conference is hosted by me.

https://ipfsjapan.org/filecoin-1th-anniversary/
https://www.youtube.com/watch?v=9qHCk0KmmYs

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
YouTube Channel: https://www.youtube.com/channel/UCw6G6MIt3f26e8pglcbJ18Q
Facebook: https://www.facebook.com/IJCFB/?ref=pages_you_manage
Twitter: https://twitter.com/IPFS94660609
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We plan to support the majority of use cases that we consider to be our expertise. We are currently supporting the Arts and Media Entertainment industry over the past year and are moving into strengthening the industrial competitiveness of Japan using IPFS. We also play a central role in promoting industrial utilization, human resource development, making proposals to public institutions and industries, international cooperation and dialogue with society about the benefits of IPFS. 

```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
I plan to allocate DataCap to clients who will be able to provide verifiable information about their organization and have their data storage plan made available to the public and their end-users. Same as what I have implemented in the past 2 rounds, I will be setting up thresholds with varying degrees of trust to promote consistency across the board. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
By using a Ledger Wallet, which is accessible by me alone. 
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
The vetting process to ensure Clients are/will spend DataCap responsibly will comprise of the following required elements: 

1. Company / Organization Proof of Existence
 - Company documents such as Business Registration, License to Operate and other government issued documents to validate their business rights and existence.
 
2. Stakeholders
 - Acquire the core information of all authorized signatory’s that will act on behalf of the application entity. Which may include a signed authorization letter from the Board of Directors or CFO/CTO/CEO. In the event that there are multiple shareholders, a comprehensive core information for each actor will be required along with a photo of their government issued ID and a selfie while holding the document. 

3. Checking related reputations
-We will check not only his Website but also SNS such asTwitter, facebook, instagram and so on. And also we will check the local news site and company database by chamber of commerce in which his company registered. 

4. Proof of Deals (for 2nd time requests)
I will request for some sort of proof that the previous allocation was indeed used as stated on by the client

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
To promote a completely decentralized system of storage, as well as strengthen redundancy - ultimately minimizing the possibility of ‘gaming’ the system, I will clearly communicate the importance of storing with multiple miners (3-5 is recommended).  Also I will be more conservative, even though I I think his business plan is worth being allocated DataCap, I will allocate less than 5Tb first and ask him to apply again if it is not enough in future. When he applies then I will check his business and ask him questions in more detail. 

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
During my first two stints as Notary - my team and I have kept records of all allocation decisions made. These decisions are based on the latest rubric of Filecoin Plus which are available publicly. For any audit requests, it must be raised as a public issue on Github and follow the process agreed upon during Notary governance calls. 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We plan to continue using Github as a public platform to provide the source of truth for allocation decisions made. We also have a process in place for any disputes or provide justification if necessary. 
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
We plan to dedicate at least 12 hours per week in the Fil+ program. This includes conducting due diligence, allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
I received 100TiB. See this issue for reference. 
https://github.com/filecoin-project/notary-governance/issues/131

```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
104.23 TB
```

**Comment by galen-mcandrew** [comment]
[IPFS Japan - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320880/IPFS.Japan.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by MasaakiNawatani** [comment]
Hi @galen-mcandrew @dkkapur @Kevin-FF-USA , thank you for the update and we appreciate your team's continued commitment to the Fil+ cause. 

We wish to reiterate a few things (Industry/Organization Reputation) and (Allocation Strategy) about our application to improve our scores. I feel like our current score for those categories are a bit lower than what we expected and does not reflect the efforts that we have committed in the past year or so, therefore we respectfully would like to expound on these points.

**Industry Reputation**

IPFS Japan Consortium, where I am one of the Directors, is a non-profit organization that is pioneering the growth and development of IPFS / Filecoin projects in Asia. Our goal is to educate people and nurture their knowledge about IPFS and Filecoin and encourage people to use services that can help open opportunities for Web 3.0. 

We may not have a loud presence in all of Asia and most of our core campaigns are within Japan (due to the pandemic situation last year), but we are already working on extending our network in HK, Philippines, Malaysia, Singapore, Taiwan, Vietnam and mainland China within the year. Then we will expand our network even more by 2023. 

During the 1st Filecoin Mainnet anniversary, we held an online event where top executives from different companies in Japan have participated and shown interest in getting involved in the Web3 space, as they are convinced that this is the future. 

![ipfsjapanconsortium-5](https://user-images.githubusercontent.com/75875000/159641341-418bc39b-d9ca-4bb3-bd86-31a61e9aa7a6.PNG)
![ipfsjapanconsortium-2](https://user-images.githubusercontent.com/75875000/159641360-15e2fbf6-7eac-4858-8e9c-06a16ba65c40.PNG)

We also have public press releases on a regular basis via social media and our own [newsletter ](https://media.ipfsjapan.org/filecoin-knowledge-44/?fbclid=IwAR1QhyTpUXF5Swihawn7fXecOWwdOgdwXwIGSulQoOfkYOw9rEOJRVy155M) This is our way of pushing awareness to a wider audience and removing the frictions in getting into the IPFS business. 

![ipfsjapanconsortium-4](https://user-images.githubusercontent.com/75875000/159642054-eb31a478-c25c-49af-ae3f-71274ba938e2.PNG)

![ipfsjapanconsortium-1](https://user-images.githubusercontent.com/75875000/159642603-3b525046-c75a-4f1a-8bf0-6a6163bb7d09.PNG)
![ipfsjapanconsortium-2](https://user-images.githubusercontent.com/75875000/159642610-f49161b0-76e3-4546-aeec-4a6fa4d88b4d.PNG)

Localization of Filecoin Documentation

I also want to mention that we have been doing localization work for the Japanese Community over the past few months. We translate Filecoin/IPFS news and documents on a regular basis to help push awareness. We are the only organization in Japan that currently offers free localization of Filecoin documentations and meeting notes.

--------------------------------------------------------------------------------------------------------------------------

**Allocation Strategy**

Our allocation strategy will be a much improved version of what we used back in Round 2. 

We currently allocate datacap to clients that have a clear vision and strategy for how the datacap will be used, but more importantly, who will enjoy the benefits of it. The end goal should always benefit the end-users and not the organizations that were given datacaps. 

Using the Rubric established by Filecoin Plus as a guiding principle, we're able to identify clients that will demonstrate and uphold the values and principles of the community. Below is the due diligence guide that we have been using as a Notary since Round 1 and 2, and we wish to continue using it and make improvements as the Fil+ program evolves. 

With more volunteers helping our non-profit organization, we can improve the quality of our due diligence even more and eliminate frictions and bottlenecks in the due diligence process. 

![duediligenceguide](https://user-images.githubusercontent.com/75875000/159643549-c120a6b6-79d5-477b-8a3c-f94fa4b508cd.PNG)

**Geographic Distribution / Use Case Diversity**

IPFS Japan Consortium has a dynamic global team of volunteers which allows us to get local information in major countries in Asia, and conduct due diligence and check the consistency between the application and the local situation. We are able to leverage all these factors when doing checks for clients in Asia. 

As an example in Round 2, we were able to perform due diligence on clients outside of Japan. In fact, the majority of our approved clients are from Korea, and we are ready to receive applications from other countries such as Singapore, Malaysia, Philippines etc. This speaks of how well we can perform our duties and our productivity speaks for itself. During Round 2, we processed **52 applications** and was one of the most requested Notary in our region, mainly due to our efficiency and approach. 

We wish to continue serving the Filecoin Plus Community as a Notary for as long as you deemed our qualifications fit. 

Thank you Deep, Galen and Kwray for your time and have a great day ahead.

**Comment by MasaakiNawatani** [comment]
Hi @Kevin-FF-USA , thank you so much for considering us again. This is great news! I will get these items completed asap.

**Comment by galen-mcandrew** [comment]
[Masaaki Nawatani - UPDATED - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8373128/Masaaki.Nawatani.-.UPDATED.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by MasaakiNawatani** [comment]
> Hi @MasaakiNawatani **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.
> 
> In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:
> 
> 1. Please confirm that the region of operation for client applications you will focus on is Asia minus GCN.

**> Acknowledged**

> 2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).        

**> **We acknowledge all of the items below:****

>    •	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship    .
>    •	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.    
>    •	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.    
>    •	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.    
>    •	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.    
>    •	Community Governance Participation: It is expected that you will participate in the program 12 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.

> 3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

**>None**

> 4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

**> We will abide by the allocation/client due diligence process that we laid out on our application.** 

> 5. This is the address that we will use for this round - - **f1fp5f7bhqom4wdypuw44p47uyajbxohqga2l3t5i**

Thank you again.

**Comment by galen-mcandrew** [comment]
@MasaakiNawatani 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @MasaakiNawatani!

Really appreciate you filling out the acknowledgments for the Notary kickoff in this ticket. There is some additional information needed in order to finalize, **can you please follow this link to complete by April 15th?**
[Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)

**Comment by MasaakiNawatani** [comment]
Hello Kevin, all done. Thank you for the follow up.

**Comment by Kevin-FF-USA** [comment]
Thank you @MasaakiNawatani!

We will be communicating with Masaaki Nawatani on Slack. If there are any other members of your organization you wish to be included, please comment their Slack handles below.

**Comment by MasaakiNawatani** [comment]
@Kevin-FF-USA Please add my assistant Jessie (jesslee.blotocol@gmail.com) to all appropriate Slack channels. He is helping our organization with all Notary related tasks.

**Comment by galen-mcandrew** [comment]
@MasaakiNawatani I edited the parent comment with your new address, please confirm your ledger address using the verification tool in the [Fil+ Registry app](https://plus.fil.org/).

[Here](https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing) is a troubleshooting guide.

Thanks!

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1fp5f7bhqom4wdypuw44p47uyajbxohqga2l3t5i
#### Datacap Allocated
> 1PiB

**Comment by MasaakiNawatani** [comment]
Hi @fabriziogianni7 @galen-mcandrew 

I'm sorry but there seems to be some misunderstanding and I need help here. The address that was signed by RKH - **f1fp5f7bhqom4wdypuw44p47uyajbxohqga2l3t5i**  --- although that is an address that we own, its not the one showing on my ledger, therefore I'm unable to verify that address. 

Can we move the 1 PB datacap allocation to my verified address please which is --> **f1ciu27vn3r7htmanzvwrm6ksx6y774gqsz3cot3i** (2nd one on the address list)

![image_2022_05_30T11_35_01_764Z](https://user-images.githubusercontent.com/75875000/170986078-4922f588-cda8-45bb-a396-8cf772feea26.png)

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1ciu27vn3r7htmanzvwrm6ksx6y774gqsz3cot3i
#### Datacap Allocated
> 1PiB

**Comment by galen-mcandrew** [comment]
Re-allocating through https://github.com/filecoin-project/notary-governance/issues/570
