### ISSUE TITLE
Notary Application - Genesis 

### ISSUE THREAD

**Issue by 1ane-1** [filecoin-project/notary-governance#411]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:Anne
- Affiliated organization: Genesis Browser
- On-chain address to be notarized (recommend using a new address):f3qsgpfo3i6l5ugweytxml2xj4z7otc367o3z2pnpuvi7ow3w5b2ktpvl5mlajuh3q74rx5e4y4iu5rpc7pcdq
- Region of Operation: [ Greater China]
- Use case(s) to be supported: [Building surveillance video / SDCloud user personal data / disaster recovery data]
- DataCap requested for allocation (10TiB - 10 PiB):1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
In March 2019, the founders of Genesis and his team noticed the development of IPFS in the field of distributed storage, planned the layout of IPFS&Filecoin, then participated in and held IPFS-related conferences for many times. 
In April 2020, the Genesis team made code contributions to the filecoin project and actively participated in the network test project. （https://github.com/filecoin-project/sector-storage/pull/16）In September 2020, IPFS started a global competition-Slingshot, and the core team of Genesis defeated the crowd and achieved the top five achievements in the world. 
In 2020, The Filecoin main network was successfully launched at 22:45 on the evening of October 15. At the same time, the data storage space of Genesis power reached the top six in the entire network, and the storage efficiency of data storage packaging continued to be higher than the industry average. 
Genesis team focus on the field of distributed storage, with blockchain and filecoin data storage track as the major development business sectors.It currently has more than 80 members, invested about 300 million yuan, and deployed more than 4,000 storage server equipment in four cities across the country. The current daily growth rate is 500TB to 1.5PiB.
About filecoin products developed by Genesis team :
 Firstly, The Genesis Browser is a Filecoin blockchain browser and data service platform. It provides users with various data, information and visible charts related to Filecoin steadily. It can also enable users to understand the entire network information and node data changes more comprehensively and timely, at the same time ,it can monitor node-related risks, avoid losses, ensure node output, and master market conditions and node power anytime, anywhere.
Secondly,"SD Cloud" filecoin storage cloud service platform, which solves the problems of data storage, data security and data transmission. It adopts transmission protocol, git modular technology, SFS self-certified naming technology, and is based on a blockchain integrated architecture design. It can support PiB-level mass storage. It helps enterprises to solve the problems of high cost of data storage, slow transmission, security risks, low availability, and expansion difficulties in one stop. Let data returns to its original source and realize data right confirmation and data distribution. Let the whole people share knowledge, all people search knowledge, and build a data center with high efficiency, strong privacy, and low cost.
Thirdly, Integrated cabinet:We are deeply involved in the field of edge computing and distributed storage. Relying on the self-developed integrated data storage micro-cabinet, we integrate multiple systems such as refrigeration, monitoring, fire protection, and edge computing. Through the monitoring system, we implement overall management of subsystems and realize one-stop data. Deployment and operations management. Enterprises can customize the nodes, resources and service methods used in the entire edge computing network, and build a highly secure global private network suitable for their own business applications..More details view photos：https://docs.google.com/document/d/1uBaPHk_bpJ1wVTQjvkj7YDqbrBtrgQAg_6jRxBFrDgc/edit
Regarding the event, we participated in the Wanxiang Blockchain IPFS Developer Competition and entered the finals. We also participated in Tianchi Aliyun Hackathon, minerX project, Slingshot and other activities. Actively participated in Near ecological construction, submitted relevant proposals and received official recognition and approval,（https://github.com/filecoin-project/devgrants/issues/375） and won awards in the space race. We are currently participating in the Slingshot 2 project and Near Meta build Hackathon competition.
In addition, we actively participated in cooperation and signed contracts with the local Guancheng government. Genesis adopts the distributed storage technology of Zhongchuang Computing Co., Ltd..and Baidu Smart Cloud signed a strategic cooperation agreement, reached a cooperation agreement with the Chinese Academy of Sciences cloud computing, reached a cooperation with the National Big Data Disaster Recovery Center. At the same time, we cooperated with People's Data Management (Beijing) Co., LTD to hold the cooperation signing ceremony of "Computing power Data Center" project. In-depth cooperation will be conducted on big data storage, resource sharing and application, privacy protection, "Internet plus Data product processing" and data computing standardization.We obtained 12 national software patents in the field of blockchain distributed storage, including value-added telecommunications services Business license, intellectual property management system certification, etc. For more information , please visit: [https://photos.app.goo.gl/wZH3XCEqoA3xBi266](https://docs.google.com/document/d/16EhnDQ_TjhlOKUitcMWzxXh046ImouTeO0Zc_-FlqSE/edit)
We are also constantly updating the filecoin industry dynamics on social media platforms. Including Weibo 
https://weibo.com/u/7583724940?is_hot=1&sudaref=s.weibo.com with12000 fans 
TIKTOK（in China）Official Account:https://www.douyin.com/search/%E4%B8%AD%E5%88%9B%E7%AE%97%E5%8A%9B?source=normal_search&aid=02791d7a-cc95-44ae-ada6-6e2b517e38a6&enter_from=recommend  
ID：zhongchuangsl  with8171 fans  
Finally, we have 5 miners running on the filecoin network, and the total amount of fil is 1.27Million
f020330  f025002  f024483  f0101020  f0101021 with 143.22PiB
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
f020330  f025002  f024483  f0101020  f0101021 with 143.22PiB 
and the total amount of fil is 1.27Million
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As the world's leading provider of decentralized storage solutions, Genesis has been actively participating in and organizing various activities to promote the Filecoin ecosystem and has achieved remarkable results.
1.In October 2021, we participated in the Wanxiang Blockchain IPFS Developer Competition and entered the finals, as well as the Aliyun Tianchi Hackathon. We actively participated in the Near ecological construction, submitted relevant proposals and got official approval , participated in the Slingshot race, and organized exchange meetings with Alibaba Cloud, and some Salon activities are held from time to time.In 2022, we participated in slingshot2 and Near Metabuild Hackathon competition.
2.Actively discuss filecoin issues on Github and participate in the filecoin ecological construction.
https://github.com/filecoin-project/bellperson/issues/175
https://github.com/filecoin-project/devgrants/issues/375
https://github.com/filecoin-project/sector-storage/pull/16
https://github.com/filecoin-project/lotus/issues/5130
https://github.com/filecoin-project/lotus/issues/6669
https://github.com/filecoin-project/lotus/issues/6077
https://github.com/filecoin-project/lotus/issues/3826
3.The Genesis Browser is a filecoin browser , which provides users with  various data, information and visual charts related to Filecoin stably. Please check  http://www.ipfs6.com/
4.SD Cloud is the first cloud service platform based on the IPFS and filecoin storage network, which solves the problem of data transmission. Pls check:  https://sdcloud.on.fleek.co/
5.We build Integrated cabinet. Check pictures here：https://photos.app.goo.gl/wZH3XCEqoA3xBi266
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Genesis Browser actively participated in the early network testing and presented some codes bug to the authorities in slack. During the launch of the main network, our f020330 nodes contributed 148888 of the first block of the main network. 
Also actively participate in the discussion on github, the link is as follows:
https://github.com/filecoin-project/bellperson/issues/175
https://github.com/filecoin-project/devgrants/issues/375
https://github.com/filecoin-project/sector-storage/pull/16
https://github.com/filecoin-project/lotus/issues/5130
https://github.com/filecoin-project/lotus/issues/6669
https://github.com/filecoin-project/lotus/issues/6077
https://github.com/filecoin-project/lotus/issues/3826
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Company Nature: Co. Ltd
Country of registration: Henan, China
Organization scale: nearly 80 employees
Date of establishment: January 26, 2021
Organization reputation:
The Genesis team is a leading domestic platform solution provider based on IPFS and blockchain storage. The representative products of our company are the self-developed Genesis browser and SD Cloud storage platform.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Wechat Official Account: https://mp.weixin.qq.com/s/X_soXjNUsU5OkeGNb1uwGg
Weibo: https://weibo.com/u/7583724940?is_hot=1&sudaref=s.weibo.com
SDCloud: https://sdcloud.on.fleek.co/
Genesis Browser: http://www.ipfs6.com/
Tiktok in China https://www.douyin.com/search/%E4%B8%AD%E5%88%9B%E7%AE%97%E5%8A%9B?source=normal_search&aid=02791d7a-cc95-44ae-ada6-6e2b517e38a6&enter_from=recommend
Twitter：https://twitter.com/IPFSZC
https://medium.com/me/stories/public
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
[Please answer here.](https://weibo.com/u/7583724940?is_hot=1&sudaref=s.weibo.com
https://www.zhihu.com/people/ipfszhong-chuang-suan-li/posts
https://blog.csdn.net/weixin_57995426
https://www.shilian.com/shilianhao/448732.html
https://www.douban.com/note/819866424/
https://tieba.baidu.com/f?ie=utf-8&kw=%E4%B8%AD%E5%88%9B%E7%AE%97%E5%8A%9B&fr=search
https://xueqiu.com/u/3878285823
https://www.sohu.com/a/500896771_121114728
https://beepcrypto.com/home?userId=20168
https://www.odaily.com/
https://beepcrypto.com/home?userId=20168
https://v.douyin.com/RQgBJqW/)
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
[Please answer here.](https://weibo.com/u/7583724940?is_hot=1&sudaref=s.weibo.com with12000 fans 
TIKTOK（in China）Official Account:https://www.douyin.com/search/%E4%B8%AD%E5%88%9B%E7%AE%97%E5%8A%9B?source=normal_search&aid=02791d7a-cc95-44ae-ada6-6e2b517e38a6&enter_from=recommend  
ID：CS_Genesi  with 6100 fans  
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Building surveillance video / SDC user personal data / disaster recovery data
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
In order to prevent customers from malicious use or abuse of DataCap, we will carefully review customers, examining their needs, and allocate them on demand. So I first specify some rules to figure out the true identity of the applicant.Browse its official website to get a general understanding of the company or individual.
* Browse its official website to get a general understanding of the company or individual. If necessary, go to the company for on-site inspections and review whether the data is valid.
* Check the company's registration information on relevant government websites to ensure that the information submitted is true.
* Ask some questions to understand the applicant's position/organization/plan/use case, etc.
* Then we will classify the applicants according to their industry reputation and scale.
https://docs.google.com/spreadsheets/d/1ZZVv7ubFyXG8jdx6lXQi48yJ2U1MdjVzpMFwhIF9rXE/edit?usp=sharing
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The hardware wallet will be used to securely store the key associated with the address assigned by DataCap.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In order to ensure the fairness and justice of DataCap distribution, we have formulated separate online and offline application procedures based on the number of DataCap applications and individual and corporate users.
For individual users:
We will review their Github registration years (180 days at least) to prevent malicious application bots. The amount of approval will also be controlled below 0.5 TiB.
For business users:
We have developed different review methods and requirements based on the number of their DataCap applications.
If it is less than or equal to 5TiB, we will use online review. The following points will be reviewed.
• Business license
• Enterprise authorization letter (CEO's signature + seal)
• All shareholders who account for more than 25% of the total number of shareholders must provide ID cards or passport photos.
• Sample data submission (accounting for 0.2% of its total DataCap requests)
If the application is larger than 5TiB, we will add offline comments based on online surveys (visit customers on business trips or invite them to our company).
Enterprise business type
• data source
• Data volume (monthly)
• What companies think about Filecoin
• Data storage plan
Question:
Please introduce yourself and your personal information on social media (official website, WeChat, LinkedIn,, GitHub).
• What is the purpose of your application for DataCap?
• Please provide the wallet address you want to apply for DataCap
• Please provide the quota of Datacap you want to apply for.
• Please provide the name of the organization, nationality, country of registration, time of registration, name of the executive, and relevant website (if you are an institutional user).
• Please provide the region where you want to use DataCap, if it is more than one region, please pay attention.
• How many miners do you plan to distribute DataCap to, if there are specially designated miners, please pay attention.
• Have you assigned DataCap before? If so, please provide details.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Applicants need to distribute Datacap to at least 3 or more miners, which will increase storage redundancy and help maintain decentralization and reduce the possibility of abuse. The more miner clients allocate, the more Datacap clients may get.
We will regularly monitor and record the usage of all distributed Datacaps every month.
For applicants who abnormal usage, we will contact them to understand the situation and record it.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, all allocation decisions will follow the guidelines published on Github. The same is true for all communications.
Since all interactions are intended to be done publicly, most allocation decisions should be self-explanatory.
Any challenges related to allocation decisions should first be discussed publicly in the Github repository.
If the notary public can’t provide a convincing reason, it can submit a dispute resolution application to the Notary Public Administration 14 business days from the date of the initial challenge. After submitting the dispute resolution application, the notary public can appoint an arbitrator among the root key holders to resolve the dispute. According to the decision of the arbitrator, a hearing may be held within 30 business days after the dispute resolution application is made. 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
All allocation decisions will be made publicly on GitHub-all communication will also be made through the repository and issue tracking, and we will send two email notifications to customers to ensure effectiveness
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
We plan to dedicate at least 40 hours per week in the Fil+ program. This includes conducting due diligence, allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
(https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1009
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/720
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1374)
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
We received a total of 37TiB datacap, and all distributed and satisfied with notaries
```

**Comment by galen-mcandrew** [comment]
[Genesis - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320907/Genesis.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by 1ane-1** [comment]
I want to add some additional information whether it can benefit for the score or not.Since our company started in 2021 Jan,we started mining since 2019, and cooperate with ipfs -force(Venus) many times. Now we are the leader in distributed storage, and always dedicated to filecoin and ipfs ecosystem-building. So we developed the blockchain Genesis browser and SD cloud stoage app.
About use cases,we’re willing to support all kinds of use cases.Because of our storage platform SD cloud, our app user will storage all types of files. About ourself, the use cases are Building surveillance video/ disaster recovery data/ charity data/media data such as movie and pictures.
Bookkeeping Plan
All allocation decisions will be made publicly on GitHub& some public websites: 
- [filecoin-plus-client-onboarding](https://github.com/filecoin-project/filecoin-plus-client-onboarding) 
- [filplus.info](https://filplus.info/)
All allocation decisions will be guided by the rubric publicly on Github.  
Since all interactions are intended to occur publically, most allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly, e.g., the Github repo.
If convincing justifications can't be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
Depending on the arbitrator's decisions, a hearing may be given within 30 calendar days of the dispute resolution application.

**Comment by Kevin-FF-USA** [comment]
Hi  @1ane-1 **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Greater China.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 40 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by 1ane-1** [comment]
> Hi @1ane-1 **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.
> 
> In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:
> 
> 1. Please confirm that the region of operation for client applications you will focus on is Greater China.

confirmed
> 2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).      

confirmed  
>    •	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship    .

confirmed  
>    •	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.    

confirmed  
>    •	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.    

confirmed  
>    •	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.    

confirmed  
>    •	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.    

confirmed  
>    •	Community Governance Participation: It is expected that you will participate in the program 40 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.

confirmed  
> 3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

 Here is the miner list owned by Genesis:f020330  f025002  f024483  f0101020  f0101021  
> 4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

confirmed
> 5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.    

The address is f3qsgpfo3i6l5ugweytxml2xj4z7otc367o3z2pnpuvi7ow3w5b2ktpvl5mlajuh3q74rx5e4y4iu5rpc7pcdq (exactly same as the address listed in the Core Information section above). it is brand new, no DataCap grant.
>    •	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: [https://shop.ledger.com/pages/ledger-nano-x)    ](https://shop.ledger.com/pages/ledger-nano-x)%E2%80%A8)

Thanks for your kind reminder. we have got one already.

**Comment by galen-mcandrew** [comment]
@1ane-1 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @1ane-1!

Really appreciate you filling out the acknowledgments for the Notary kickoff in this ticket. There is some additional information needed in order to finalize, **can you please follow this link to complete?**
[Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)

**Comment by 1ane-1** [comment]
> Hello @1ane-1!
> 
> Really appreciate you filling out the acknowledgments for the Notary kickoff in this ticket. There is some additional information needed in order to finalize, **can you please follow this link to complete?** [Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)

thank you so much, i complete the link information but changed the notary address into f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri, and hope your check.

**Comment by Kevin-FF-USA** [comment]
Got your information, very much appreciated!

We have updated your notary address to f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri,
and your Slack handle is chuangshiIPFS.

**Comment by Kevin-FF-USA** [comment]
Hello @1ane-1!

Just some final verification:

We have your address on file as: f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri

And we will be communicating with 创世ipfs on Slack. If there are any other handles you wish to have included in communications via Slack, please comment them below.

**Comment by neogeweb3** [comment]
I believe it's worth flagging because of the excessive self-dealing history from this applicant, where all of the DataCaps were used to their own Storage Provider. The applicant also didn't list their SP f01164500 in the Stake Exposure section. 

I wonder if this applicant is qualified for the notary election? If so, what are extra measures to ensure there will be no self-dealing from this notary in the future? 

I want to propose kicking off an investigation on this. Here are some links that would help the investigation: [Link#1](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1688), [Link#2](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1024#issuecomment-957135007), [Link#3](https://filplus.d.interplanetary.one/miners/f01164500)

**Comment by cryptowhizzard** [comment]
@galen-mcandrew @Kevin-FF-USA @dkkapur can you please put this application on hold until this is clarified?

**Comment by 1ane-1** [comment]
> @galen-mcandrew @Kevin-FF-USA @dkkapur can you please put this application on hold until this is clarified?

Dear galen-mcandrew  Kevin-FF-USA  dkkapur， sorry to bother you~ I will clarify the question for you as below. f1164500 is our offline data, and there are customer-owned nodes. Description 1. The data of these transactions comes from users who demand our real data  2. All data are encapsulated to the node of the data provider, we are only technical.3. We are continuing to receive such customers. We also received many customers with such needs in this application.4. We are real storage, isn't that the real use and purpose of filcoin?

**Comment by 1ane-1** [comment]
> @galen-mcandrew @Kevin-FF-USA @dkkapur can you please put this application on hold until this is clarified?
1. Dear @galen-mcandrew @Kevin-FF-USA @dkkapur, we are deeply sorry for causing trouble to your work, and we are also very grateful for Neo's supervision.
2. Regarding the self-trading rules mentioned by neo, as a technology provider, f1164500 is our offline data, and the nodes owned by customers. The data of these transactions comes from our real data demand users. In addition, all data is encapsulated to the node of the data provider, we are only the technical side. Because the nodes and quotas are reviewed and packaged one after another, so far the high allocation is f01164500, but we have two other customers whose nodes have not yet been packaged, f01832584 and f0101021, and the final allocation ratio is f01164500, accounting for 40 %, f01832584 accounts for 30%, and f0101021 accounts for about 30%.
3. Regarding the future, we have increased the number of nodes in the organization, and will further disclose the distribution plan and fully comply with the self-trading rules. I also hope that you will continue to monitor us and build a better community.
4. We are also working hard to contribute to the filecoin community by developing a genesis block browser and SDcloud. At the same time, the storage of real data is also the focus of our work. With the continuous growth of user data, we also believe that filecoin will become better and better. Finally, hopefully we can still retain notary status and do our part for the community while adhering to the notary guidelines. Thank you very much for your understanding!

**Comment by Kevin-FF-USA** [comment]
Hi @1ane-1 ,

We sure can.  With this current election, the Datacap disbursement will be distributed next week. Per your request I'll hold this application off that disbursement, and reengage in the round of Notary election. 

Even though you wouldnt receive data this round, you are still welcome and encouraged to remain active in the community and continue to join Governance Calls.

Should you have any questions or wish to discuss this further, I would be very happy to.

Warmly,
-Kevin

**Comment by 1ane-1** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec5lthnwkpefdtw5v3j7pglyspq7mmsu6zx24wwmdzcojwebl5spg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5lthnwkpefdtw5v3j7pglyspq7mmsu6zx24wwmdzcojwebl5spg

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacedndspdezk2tcfsuscf3fhpyeyaxeiij6whbtqkqciimxjr2trgjq

**Comment by 1ane-1** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecsbrkgfdb7rbipcrc5evqppnxf4wjagrkhn6fsmrdou22n4zjcgo
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsbrkgfdb7rbipcrc5evqppnxf4wjagrkhn6fsmrdou22n4zjcgo
