### ISSUE TITLE
[Notary Application] IPFSForce - Steven Li 

### ISSUE THREAD

**Issue by steven004** [filecoin-project/notary-governance#412]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Steven Li
- Affiliated organization: IPFSForce
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address):  f1ozt3gaqbnzfic6f2zsj4vppncws36ik5nqofhka
- Region of Operation: Greater China
- Use case(s) to be supported: User Content, Scientific Data, Media & Entertainment
- DataCap Requested: 1 PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
As an individual, I have been deeply cultivating distributed storage for over 10 years in multinational and startup companies.

I was the head of Cisco (China) Cloud Object Storage and the core developer of China's first-generation security routers. With my knowledge and experience in networking, security, and storage, I feel perfectly aligned with Filecoin's vision as a DSN infrastructure for humanity's information storage.

As an advocate and practitioner of distributed storage and Web 3.0, I started focusing on IPFS study and development since 2017. In early 2018, I joined in Filecoin Community and worked as Co-Founder & CTO of IPFSForce. Since then, all of my working time is on IPFS and Filecoin ecosystem buildup.

At present, I am committed to the design and ecological construction of key modules such as Filecoin's consensus algorithm, proof of replication, economic model, and mining cluster architecture.

More information:
- GitHub handles: steven004
- IPFSForce Miner ID: f02438, f02425, f02731, f020604, f02726, f03266, f03287, f02610, f02721
- Slack: @steven
- Participating in DevNet/ TestNet/ HackFS/ SR1/ SR2/ Slingshot 1(as reviewer)/Filecoin Community activities as one of the top testers, core developers, and storage providers
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Total stake: 1.07MM FIL with Miner ID f02438, f02425, f02726, f03266, f03287, f02721, f0144547, f0218283, f0397561 as collateral(viewed on February 25th, 2022).
Substantiating evidence: https://filscan.io/tipset/pool-detail?address=f0874295
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As an Individual, I have been working as an IPFS/Filecoin ecosystem advocate and builder:
- Weekly IPFS/Filecoin/Web3 technical or marketing articles (over 400 articles in Chinese/English published)
- Speaker of IPFS/Filecoin/Web3 conferences
- Organizer and lecture of Protocol School Shanghai Chapter
- Contributor of Filecoin protocol and code development via issues/PRs commitments

Recently Filecoin Community activities
- Filecoin Mainnet Anniversary Cloud Summit, Oct. 19th, 2021, https://www.huoxing24.com/live/24312878
- HyperDrive Upgrade - Data Analysis of ProveCommitAggregate Usage by Steven Li, Aug. 18th, 2021, https://www.youtube.com/watch?v=CJWm8H85teI
- Miner Financing: Putting Filecoin Tokens to Work - Steven Li, Dec. 17th, 2020, https://www.youtube.com/watch?v=J-_jmDVfDRY
- Filecoin Core Devs #35, Feb. 3rd, 2022, https://www.youtube.com/watch?v=2kVQ5qwegok&list=PL_0VrY55uV1-9t74K-eFQN7Bc7ROG06hT&index=26
- How We Won Space Race, Oct. 21th 2020, https://www.youtube.com/watch?v=1QVa48Eela8
- Filecoin Protocol Implementation: What's next?, Oct. 21th 2020, https://www.youtube.com/watch?v=JmvQ0F1qtYQ
- Filecoin Chain Explorers, Oct. 21th 2020, https://www.youtube.com/watch?v=f2sk2WqrIjs
- Space Race Miner Show & Tell, Spe. 4th 2020, https://www.youtube.com/watch?v=pHi85ZNs3AY

As the technical lead and co-founder of IPFS-Force, led and helped the team: 
- Established and lead IPFS/Filecoin activities in China: 
	- Force Open Day: from March 13rd, 2019 to now (#218 on Feb. 22nd 2022)
	- Protocol School Shanghai & Chengdu
	- EOS & IPFS HackFS
- Published IPFS/Filecoin related reports and articles:
	- whitepaper translation
	- 1-120 Filecoin Weekly Report
	- 1-156 IPFS Weekly Report
	- 1-18 Web3 Weekly Report
	- IPFS/Filecoin Ecological Report
	- SpaceRace Report
	- Filecoin Mining Guidelines (1-3 series)
	- 100 Questions about IPFS/Filecoin
	- Filecoin Annual Report
	- and other reports and articles wrote by IPFS-Force researchers and analyzers
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Security is the first priority and the most important factor of a chain. As the key engineer of China's first generation of the secure router, I paid a lot of attention to the security of the system and contributed to Filecoin via publicly submitted issues or privately discussion due to the sensibility of some security issues.

Some of the issues submitted related to security: 
- https://github.com/filecoin-project/specs/issues/559
- https://github.com/filecoin-project/venus/issues/3308 
- https://github.com/filecoin-project/venus/issues/3349
- https://github.com/filecoin-project/venus/issues/3523

There are some discussions in the private Slack channel or via email, too, e.g. 
- Nondeterministic signature of round winner calculation
- Owner change proposal from the security perspective
- deterministic winner of big miners, to drive the winning algorithm change
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
IPFSForce is a non-profit leading Web3 community that started in May 2017 in Shanghai, China. It has been sponsored by Shanghai Kunyao Network S&T Co., Ltd. since Kunyao was set up in July 2018 as a company.

We believe in the strength of blockchain, which can empower the next generation of the Internet. To realize our vision, we regularly conduct meetups and events and support the industry in developing applications, the technology of Filecoin mining, and providing services.

Here, people can get the latest updates about the development of the Web3 ecosystem, and with years of experience within the blockchain industry, IPFSForce encourages and support people to build around Web3, the Next Big Thing!

Currently, we have near 100 team members working on IPFS/Filecoin software development and services, helping the ecosystem growing.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://forcecommunity.io/
Twitter: https://twitter.com/force_ipfs
Medium: https://ipfsforce-official.medium.com/
WeChat Oifficial Account: 原力区
Vlog: https://www.huoxing24.com/userCenter/32098576c5c348c3aec576e254eb55f4
Telegram: @Ipfsforce
Evenbrite: https://www.eventbrite.hk/o/force-web3-community-36225766643
TikTok: 原力区
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.jinse.com/lives/200205.html
https://36kr.com/newsflashes/973370131575041
https://36kr.com/newsflashes/669046320289795
https://news.huoxing24.com/flash/20200706192231201068.html
https://news.huoxing24.com/flash/20200706191320331822.html
https://www.jinse.com/lives/200205.html
https://www.jinse.com/lives/175039.html
https://news.huoxing24.com/20210710113426608771.html
https://news.huoxing24.com/flash/20200706192231201068.html
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter: @Steven004_Li, 58 followers
WeChat Oifficial Account: 胡飞瞳, 156 articles, 1800 subscribers
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Scientific Data(AI training, geological data, autonomous driving) 
Media & Entertainment(video & music)
User Content(personal user storage)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The purpose of allocating the DataCap is to make sure clients use these DataCap in the right way.
For new clients, there will be offline investigation and discussion regarding who they are, what they will use Filecoin as storage to save, and how to do it. Based on that, I would have the first judgment to qualify or not as verified clients.
For qualified clients, my allocation strategy emphasizes historical reputation and also the plan for new-required data investigation.
We plan to allocate DataCap with a small incremental amount(<10%) and build a reputation mechanism.
Each allocation will be considered an assessment of clients' reputations with score accumulation and corresponding trust degree.
For example, if a client applies for DataCaps, provides valid data, and spends these DataCap responsibly, his reputation credit will increase. With higher credit, Clients can apply for more DataCaps in the future.
We are also willing to use tools, such as Filecoin Plus Registry and filplus.info to make all allocations public.

Internal process of allocation strategy:
Referring to the Filecoin Plus Client Rubric & Allocation Draft, I edited a draft of the credit and scoring mechanism of clients and communities or individuals behind, with the limitation of minimum 1GiB and maximum 100TiB DataCap. See the details from: https://drive.google.com/file/d/1Zy7TLZN1dEqYNWubgMUdnog_c885-1KB/view?usp=sharing
At this moment, I think it's a good time to attract more external data providers to come into the Filecoin Network, become verified clients, and store valuable data. For this reason, my audit mechanism will evaluate the value of data as well. Clients with high-value data can prioritize allocation and a larger amount of DataCap. The initial rules are listed in the table: https://drive.google.com/file/d/13w0H3DMrKMeXFP4x1COFWx03Ohhhk0Ap/view?usp=sharing.
Basically, the more value the data can bring to the network, the more can be granted.
Besides, there will also be a 20% incremental allocation strategy.
For example, suppose clients(applied DataCap from me) provide valid data without improperly over-allocating as promised, and all checked data are qualified. In that case, when they apply for DataCap allocation from me the next time, their allocation could have a maximum 20% increase.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The offline wallet had been developed and verified for the accounts associated with the Datacap allocation.
And multi-sig wallet is to be used when more clients are coming in.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 

All clients have to go through a strict process to be qualified in the early stage. Firstly, I need to collect information including:  
1. Entity Information
 - Formation documents: includes certificates of registration/incorporation/information
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory's authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary's certificate, a signed letter from the applicant's CFO, or may be included in the company operating agreement); 
 - close-up photo of the signatory's face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners
If there are any 25%+ shareholders, we need a document, such as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
	 - legal name;
	 - date of birth; 
	 - street address (P.O. box number is not acceptable); 
	 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 	- a copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

With this provided information, an interview and data source checking process need to go through. After that, an agreement should be signed for the next step: gradually allocate DataCap and let the client gather more credit. 

Question for clients:
1. Introduction of yourself/ your organization(with links)
2. Use case
3. Location
4. Max DataCap Allocation
5. Filecoin address
6. Miners you intend to allocate DataCap with allocation proportion
7. Specific requirement of miners and storage service
8. For-profit or not
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Periodical inspection and audit of DataCap usage
- Use incentive mechanism: encourage clients to report unfair allocation
- Audit of DataCap usage: filplus.info is a useful tool to check the usage of DataCap and the flow of verified deals. After call-back, I'll retrieve stored data to verify whether clients stored data as they mentioned. At the same time, I really value the clients' services for their users and how the data stored in Filecoin can benefit others.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
The record of my allocation decisions will be accessible and in public(tentatively on GitHub) to be supervised by Filecoin Community.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub
All allocation decisions will be guided by the rubric publicly on Github.  
Since all interactions are intended to occur publically, most allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly, e.g., the Github repo.
If convincing justifications can't be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
Depending on the arbitrator's decisions, a hearing may be given within 30 calendar days of the dispute resolution application. 
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
In plan, 4-6 hours per week on average.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
YES
The 1st round: https://github.com/filecoin-project/notary-governance/issues/14
The 2nd round: https://github.com/filecoin-project/notary-governance/issues/158
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
185.50 TiB in total
```

**Comment by galen-mcandrew** [comment]
[IPFSForce - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320898/IPFSForce.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi  @steven004 **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Greater China.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 4-6 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by steven004** [comment]
Please see my answers below inline: 

> 1. Please confirm that the region of operation for client applications you will focus on is Greater China.

Confirmed 

> 2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).        
>    •	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship    .

Confirmed

>    •	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.   

Confirmed
 
>    •	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.    

Confirmed

>    •	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.    

Confirmed

>    •	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.    

Confirmed

>    •	Community Governance Participation: It is expected that you will participate in the program 4-6 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.

Confirmed

> 3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

f02438, f02425, f02731, f020604, f02726, f03266, f03287, f02610, f02721
These are nodes maintained by IPFSForce for customers. 

> 4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

Confirmed 

> 5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.    

f1w2vyp4w6df44gbh4vxqle4w65zfrfnwhrl3hojy 

>    •	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: [https://shop.ledger.com/pages/ledger-nano-x)    ](https://shop.ledger.com/pages/ledger-nano-x)%E2%80%A8)

I will continue to use an offline tool to sign the message, because of the long leading time and uncertainty of the shipment of ledger Nano.  And, I suggest the filplus could support offline signing.

**Comment by galen-mcandrew** [comment]
@steven004 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by galen-mcandrew** [comment]
@steven004 I edited the parent comment with your new address, please confirm your ledger address using the verification tool in the [Fil+ Registry app](https://plus.fil.org/).

[Here](https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing) is a troubleshooting guide.

Thanks!

**Comment by steven004** [comment]
Hey @galen-mcandrew , sorry that I'm not using a ledger for  Fil+, but an offline signature tool. I had been done this for one year. 
Due to the supply-chain problem, partially impacted by the pandemic, I do not expect the notaries located in China could get a ledger in a short time. 

If we are required to use [ Fil+](https://plus.fil.org/) for granting datacap or approve a request, could we implement offline-signing feature, which will make it more flexible.

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1w2vyp4w6df44gbh4vxqle4w65zfrfnwhrl3hojy
#### Datacap Allocated
> 1PiB

**Comment by steven004** [comment]
@galen-mcandrew , 
Just checked, the datacap is not arrived yet. Should be another root key holder approve this?

**Comment by steven004** [comment]
The datacap is received.

**Comment by panges2** [comment]
@steven004 Hi Steven, could you please verify your ledger?

**Comment by steven004** [comment]
@panges2, I am not using a ledger, but an offline signature tool. 
My address is already granted as a notary, I can move forward to approve an LDN proposal, or approve a normal datacap application now.

**Comment by steven004** [comment]
@galen-mcandrew , 
Finally, I got my ledger, and the ledger address is: `f1ozt3gaqbnzfic6f2zsj4vppncws36ik5nqofhka` 
I had edited the application and changed the address the this one. Would you please help change my address in Fil+ Registry App? 

Sorry for taking a long time for this, and thanks for your help very much.

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1w2vyp4w6df44gbh4vxqle4w65zfrfnwhrl3hojy
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzacecfht2qqfosvd6ooaonorjvypo2qtejv66vswzo46ehqs2eybmoec
