### ISSUE TITLE
Notary Application: IPFSMain - Neo Ge

### ISSUE THREAD

**Issue by neogeweb3** [filecoin-project/notary-governance#413]
# Notary Application

## Core Information
- Name: Neo Ge
- Affiliated organization: IPFSMain
- Website / Social Media:
- On-chain address to be notarized: f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
- Region of Operation: Greater China
- Use case(s) to be supported: Personal user storage, scientific datasets, video & music
- DataCap Requested: 1PiB

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
I have worked as a crypto miner for over 9 years. 
I’ve been a part of the Filecoin community since 2017 and founded IPFSMain in 2018. 
I am also one of the Slingshot community reviewers who were helping evaluate applicant projects. 
I am one of the members of the Filecoin Foundation Mining Working Group. 
Besides the Vice President role at IPFSMain, I am currently helping and advising multiple web3 startups on storage solutions. 

More information: 

- Github/Slack/Twitter handle: @neogeweb3
- IPFSMain Miner ID: f01235, f09037, f022361, f022373, f022374, f023626, f023627

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
The total FIL at stake is over 2.85MM, with the following miners f01235, f09037, f022361, f022373, f022374, f023626 & f023627 by the date of Feb 24, 2022. 
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As a member of the Filecoin community, we have
- joined the Lab Day's Panel on August 18th, 2018, at San Francisco: https://youtu.be/ztPi2e21Mw4  
- presented at the GDIS on October 1st, 2018, at Santa Clara: https://youtu.be/ZHMejeZJdXY  
- joined the IPFS Camp on June 27-30, 2019, in Barcelona: https://youtu.be/kc_dxO-V8YM 
- held the DSAS on July 13th, 2019, in Shenzhen and invited PL members to present: https://www.youtube.com/playlist?list=PL2Vjsl9pQ2TJAbx8JZLsfRQZj0yZPgPhf  
- sponsored the Tokyo and Osaka IPFS Meetups during Devcon V in Japan: https://gihyo.jp/news/report/2019/10/2302?page=2  
- contributed some translation work to help the ecosystem grow: https://blog.ipfs.io/46-ipfs-weekly-12/ 
- contributed our resources to help complete both phase 1 & 2 of the trusted ceremony setup: https://filecoin.io/blog/roadmap-update-august-2020/ 
- sponsored the HackFS Hackathon: https://hackfs.com/
- joined the Miner Show & Tell panel during Space Race: https://youtu.be/M8rFiweyKyk
- ranked at the top of the SR1 leaderboard: https://spacerace.filecoin.io/
- helped set up the Bootstrap Node: https://github.com/filecoin-project/lotus/blob/master/build/bootstrap/bootstrappers.pi 
- joined multiple events like the Mining Hardware & Architecture talk and the Miner Spotlight panel during Filecoin Liftoff Week: https://filecoin.io/blog/mainnet-liftoff-day2/
- sponsored NFTHack (https://nfthack.ethglobal.co/) and Scaling Ethereum (https://scaling.ethglobal.co/) virtual Hackathons and summits

More recently, we have sponsored the second HackFS Hackathon: https://hackfs.com/
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Our team and I have identified several bugs during the past two years and have informed the Filecoin team accordingly. 
Please check with @why, who will be able to substantiate our contributions. 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
IPFSMain is a leading service provider committed to comprehensive Filecoin mining solutions in a cost-effective way. 
We have built quite an extensive relationship with the Filecoin community since its initial launch back in 2017, 
and as a result, have sustained countless contributions to the overall network. 
Just to name a few, we've helped out with both phase 1 & 2 of the trusted ceremony setup, ranked #1 in the Space Race, 
and presented in multiple Filecoin talks and panels (i.e., Miner Show & Tell, Mining Hardware & Architecture, etc.). 
We’ve also held and participated in over 100 events around the world. 
These events include blockchain summits, conferences, online and offline meetups, hackathons, and online streaming events. 
With these events, we have influenced over 3 million people globally. 
Pictures and snapshots of some of these events can be found on our Chinese website: https://www.ipfsmain.cn/aboutus 
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
IPFSMain Website: https://www.IPFSMain.cn 
IPFSMain Twitter: https://twitter.com/IPFSMain 
IPFSMain LinkedIn: https://www.linkedin.com/company/IPFSMain 
IPFSMain Facebook Page: https://www.facebook.com/IPFSMain 
IPFSMain Instagram: https://www.instagram.com/IPFSMain 
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://decrypt.co/41702/space-race-filecoin-hackathon-video 
https://forkast.news/filecoin-space-race-miners-challenged-with-network-upgrades/ 
https://www.chaintalk.tv/tv/10-questions-about-filecoin-with-ipfs-main/ 
https://hackernoon.com/we-plan-to-establish-the-first-ipfs-node-on-mars-says-filecoin-miner-neo-ge-ke2c3whe 
(Some other relevant external news links in Chinese: 
https://cointelegraphcn.com/news/beep-with-ipfsmain-ceo-li-yandong 
https://www.chaindd.com/3326120.html 
http://www.pcpop.com/article/6317692.shtml 
http://www.shilian.com/baike/185381.html 
https://www.zilian8.com/33547.html) 
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter: https://twitter.com/neogeweb3 - 5800 followers
Linkedin: https://www.linkedin.com/in/neoge/ - 1200 connections 
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
I plan to support multiple use cases; the percentage will be determined by my knowledge and usage expectation, 
which may vary depending on the variable circumstances of each scenario and different regions. 
- 45% - user content (personal user storage)
- 35% - scientific datasets (AI training, geological data, autonomous driving) 
- 20% - media & entertainment (video & music)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.

> Allocating the DataCap is all about distinguishing rational clients from malicious clients, and as such, my allocation strategy seeks to emphasize the key question "how much does the Notary trust the client?" rather than "does the Notary trust the client?". I have set up thresholds with varying degrees of trust. The way we traditionally audit Notaries can also be used to audit clients as well. Below, I've created 7 varying degrees of trust. The [Rubric ](https://docs.google.com/spreadsheets/d/1zQ3FXJmmBMmynDIdRjYTYp-K95Dp95ypVoBfRhABPC0/edit?usp=sharing)will be the primary guideline I use when evaluating a client and determining their DataCap allocation. These scoring guidelines can serve as a tool of assessment and further add a level of consistency across the board.

> Update#1: I have created my allocation [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq) and [workbook](https://docs.google.com/spreadsheets/d/1k0GWJUVYCFQcquxTuitLLlLTntBR18PtZjhljD8d5I4/edit?usp=sharing).

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

> A hardware wallet (Ledger) will be used to store the keys associated with the DataCap allocation address securely. 

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 
For individual clients, online identity will be verified by both account age and account activity perspectives, 
and this will serve to prove that they are valid users and not bots or sybils. 
Third-party tools like twitteraudit may also be used to verify online identities. 

For organizational clients, application organizations should be easy to verify through the appearance of their application. 
The developing applications may require further stringent investigation; 
this is to ensure that the application is valid and enclosed with meaningful content, rather than the shell of a malicious client. 
Large public datasets hosted by organizational clients are easy to verify because the data should be unencrypted and accessible to anyone. 
However, in the event that the organizational client has large private encrypted datasets(i.e., law firms), the Due Diligence procedure will be executed.

Below is the proposed procedure of Due Diligence. We need 3 types of information for review by myself or our compliance team depending on the volume of clients required Due Diligence:
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information; 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name;
 - date of birth; 
 - street address (P.O. box number is not acceptable); 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

There are two questionnaires to help me get to know our clients. The first one is about the basic information collection of new clients. 

Questionnaire #1
Please describe answers as much specificity as you can.

1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.)
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
6. How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify.
7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
I will use the second questionnaire to collect follow-up answers about previous allocations for returning clients. 

Questionnaire #2
Since you have requested DataCap from me before, I have some questions regarding your previous DataCap allocation.

1. How much cumulative DataCap was allocated to you from me?
2. In which region(s) did you use the DataCap?
3. What was your use case for the previous allocation?
4. Did you specify any advanced features for the previous allocation?
5. How many miners did you allocate the DataCap to? Please specify transaction links to the storage deals.
6. In your previous allocation, did you violent any community principles like excessive/unfair self-dealing?
7. Is there anything I could improve to serve you better in future allocations?

Utilizing the information collected will help me confirm that the client is not improperly using the DataCap they were previously granted. 
Clients are encouraged to allocate the DataCap to more than 5 different miners, 
which not only increases storage redundancy but also helps maintain decentralization and reduce the possibility of potential misuse. 
The more miners clients allocate, the more DataCap clients are likely to get. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, all allocation decisions will be conducted in the Github repository. 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Github. 
Since all interactions are intended to occur publically, most of the allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly in the Github repo first. 
If convincing justifications can’t be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions. 
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
I am currently dedicating 4 hours per week on average. 
I am trying to spend 2 more hours per week, especially attending the governance call, as I missed a few calls in the past several months. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.

> Yes. #11 & #168 

Cumulatively, how much DataCap have you previously successfully allocated? 

> 209.12TiB in total.

**Comment by galen-mcandrew** [comment]
[IPFSMain - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320899/IPFSMain.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by neogeweb3** [comment]
> 1. Please confirm that the region of operation for client applications you will focus on is Greater China.

ACK
> 2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).        
>    •	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .

ACK
>    •	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.    

ACK
>    •	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.    

ACK
>    •	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.    

ACK
>    •	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.    

ACK
>    •	Community Governance Participation: It is expected that you will participate in the program 4-5 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.

ACK
> 3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

We change the owner/worker/controller addresses from time to time for security reasons, but the miner ID will stay the same.
The MainPool miner list: f01235, f09037, f022361, f022373, f022374, f023626, f023627
All the miners are managed by IPFSMain and owned by investors.
Other addresses that are not related to the above miner list will be listed below and updated from time to time:
`f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa`
> 4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

ACK
> 5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.    

Can I use the same address and refresh on it like last time? Thanks.

**Comment by galen-mcandrew** [comment]
@neogeweb3 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by neogeweb3** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceavrbfyh4w65xlw7ysnzycsowk662pkttknn2r75ooav6j6lghcx6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavrbfyh4w65xlw7ysnzycsowk662pkttknn2r75ooav6j6lghcx6

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### Datacap Allocated
> 1PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacedyt3az33jit2ql353jolekhx7d65jm4ij3vjlqyd3k37yl5hoh7a

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzacedqnuuz2nyim3lbjfommgfffug6ionyjbm7u2klvtdqoqngq2fqeo
