### ISSUE TITLE
Notary application - Speedium - Wijnand Schouten

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/notary-governance#414]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Wijnand Schouten
- Affiliated organization:  Speedium / DCENT BV.
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address): f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
- Region of Operation: Europe
- Use case(s) to be supported: Personal user storage, scientific datasets, video & music.
- DataCap Requested: 10 PB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
As an individual, I have worked as a crypto miner and programmer / developer for over 4 years. 
I’ve been a part of the Filecoin community since 2020 and founded Speedium and DCENT together with Hidde.
I am also one of the MinerX community members who are helping to make Filecoin better and grow.

As an organization, Speedium is a leading Usenet Service Provider. We have made many steps in onboarding data to the filecoin network and have worked with many notaries ( Phillip , Neowebg3, and AndrewHill ). Speedium is aiming to bring our populair cache to the filecoin network, decentralising the Usenet space and improving the enduser experience.
Dcent is one of Europe’s largest decentralized Filecoin nodes, capable of serving many clients across the globe with reliable storage. We want to provide clients with 100PiB of mirrored storage by the end of 2022. With our networking capabilities, private IP backbone, and 100Gbit/s of throughput, we are far ahead of most companies, who are only getting started learning about this new technology.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
7218 f01199442
4918 f01199430
5873 f01201327
8176 f01207045
5459 f01208862
8693 f01240
4845 f0707721
900  f01608291
3032 f01720359

SubTotal : 49114 FIL

Available on Exchange / Ledger : 16341 ( If evidence is needed it can be shown privately b/c security reasons. )

Total : 65455 FIL
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We have made substantial input on github improving dealmaking and reporting bugs. As a usenet organization, Speedium has been engaged with blockchain technology since day one. We are extremely interested in all sorts of decentralized storage and have been experimenting with multiple blockchain storage projects since 2019. Since the launch of Filecoin we have been participating in Testnet, Spacerace 1, Spacerace 2 and Mainnet.  
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Our team and I have identified several critical bugs during the past two years and have informed the Filecoin team accordingly. 
Please check with Dudley who will be able to substantiate our contributions. 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Speedium ( https://speedium.network ) is the first Blockchain Usenet Platform. We operate our own fully independent backbone ( IPV4/IPV6 ) and Usenet storage.
Currently we are connected with 30 Gb/s with multiple exchanges like Speed-IX / NL-IX proving extreme low latency and high speed transfers throughout Europe.
To find more statistics on how we are connected, see peedingdb.com/net/23120. 
We are currently providing our peering partners with a combined Usenet feed of +/- 140 TB daily and we are fully storing this for over a month in our spool arrays.
We are a Dutch usenet provider and we are operating with three board members, fully operational since 2019.

Dcent has been building a new datacenter in the Netherlands Heerhugowaard where we host Filecoin equipment for ourselves and customers.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Speedium ( https://speedium.network ) is the first Blockchain Usenet Platform. We operate our own fully independent backbone ( IPV4/IPV6 ) and Usenet storage.
Currently we are connected with 30 Gb/s with multiple exchanges like Speed-IX / NL-IX proving extreme low latency and high speed transfers throughout Europe.
To find more statistics on how we are connected, see peedingdb.com/net/23120. 
We are currently providing our peering partners with a combined Usenet feed of +/- 140 TB daily and we are fully storing this for over a month in our spool arrays.
We are a Dutch usenet provider and we are operating with three board members, fully operational since 2019.

Dcent has it's website on www.dcent.nl. All information about us can be found there.

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Organisation: Speedium
Website: https://speedium.network
founded in 2019 
headquartered in Oudkarspel
Number of employees: 4
Discord: https://discord.gg/2hxXZBS
Telegram: https://t.me/speedium

Organisation: Dcent
Website: https://dcent.nl
founded in 2021
headquartered in Heerhugowaard
Number of employees: 4

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Slack : ( WijnandSchouten)
Slack : ( Hiddehoogland )

```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
All usecases that befenit the Filecoin network and humanity.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We intend to work on principles of limited thrust and we only onboard requests where agreements are made to who the verified data will be send with the respective ratios. Below is the proposed procedure of Due Diligence. We need 3 types of information for review depending on the volume of clients required Due Diligence:
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information; 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name;
 - date of birth; 
 - street address (P.O. box number is not acceptable); 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 
 ```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
On a ledger
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle) 
2. What is your use case for the DataCap being requested and what miners will be storing it? 
3. What is the Filecoin address you would like me to allocate the DataCap? 
4. How much DataCap would you like to request? 
For organizational clients: 
5. What is the name, nature, registration country, time since inception, and named officers of your organization? Please link to relevant websites. 
6. In which region do you intend to use the DataCap? If you intend to use the DataCap in multiple regions, please specify. 
7. How many miners do you plan on allocating a DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
8. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
*9. Have you previously received DataCap? If so, please share some details on how you spent the previous allocated DataCap in terms of question number 6, 7 & 8. 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We plan to support multiple use cases; the percentage will be determined by my knowledge and usage expectation, 
which may vary depending on the variable circumstances of each scenario and different regions. 
- 35% - user content (personal user storage)
- 25% - scientific datasets (AI training, geological data, autonomous driving) 
- 40% - media & entertainment (video & music)
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 

```
Yes, all allocation decisions will be guided by the rubric publicly on Github. So are all communications. 
Since all interactions are intended to occur publically, most of the allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly in the Github repo first. 
If convincing justifications can’t be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions. 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
All allocation decisions will be conducted in the Github repository. 
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.

```
That depends if there is coverage for the costs endured for the labour. If not i guess 2 hours per week. If there is i can spend around 16.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes,[ here]([url]https://github.com/filecoin-project/notary-governance/issues/122(url)).
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
10TB
```

**Comment by galen-mcandrew** [comment]
[Speedium - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320888/Speedium.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi  @cryptowhizzard **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Europe.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 2 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by cryptowhizzard** [comment]
>>
Please confirm that the region of operation for client applications you will focus on is Europe.  
>>

Correct.

>>
Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

• Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
>>

Ack.

>>
• Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
>>

Ack

>>
• Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
>>

Ack.

>>
• No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
>>

Ack.

>>
• Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
>>

Ack.

>>
• Community Governance Participation: It is expected that you will participate in the program 2 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
>>

Ack.

>>
Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  
>>

7218 f01199442
4918 f01199430
5873 f01201327
8176 f01207045
5459 f01208862
8693 f01240
4845 f0707721
900  f01608291
3032 f01720359

SubTotal : 49114 FIL

Available on Exchange / Ledger : 16341 ( If evidence is needed it can be shown privately b/c security reasons. )

Total : 65455 FIL

>>
Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  
>>

Ack.

>>
(If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
• If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x) 
>>

Same as last time - > f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa

**Comment by galen-mcandrew** [comment]
@cryptowhizzard 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @cryptowhizzard!

Just a friendly ping - There is some additional information needed in order to finalize, **can you please follow this link to complete by April 15th?**
[Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)

**Comment by cryptowhizzard** [comment]
@Kevin-FF-USA already did that a days ago! ? ;)

Please check.

**Comment by Kevin-FF-USA** [comment]
Received it; thank you very much!

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebca36mhu2v3tnwageqc6low54l7q24ws5ecnbnbcsowc22fquf3e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebca36mhu2v3tnwageqc6low54l7q24ws5ecnbnbcsowc22fquf3e

**Comment by Kevin-FF-USA** [comment]
Hello @cryptowhizzard!

We have your address on file: f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa

We will be communicating with Wijnand Schouten on Slack. If there are any other handles you wish to have included, please comment those handles below.

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> Personal user storage, scientific datasets, video & music.
#### Datacap Allocated
> 1PiB

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecdpfkhqilf4gz7w7brsuqyeykcmhwig2u4u6qblfyxeyrcyv67ae
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdpfkhqilf4gz7w7brsuqyeykcmhwig2u4u6qblfyxeyrcyv67ae

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedfvtczbjwrgk4b6gshhwwcnjkziek66w7lanjsc3niyjnquiehqg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfvtczbjwrgk4b6gshhwwcnjkziek66w7lanjsc3niyjnquiehqg

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceaynu2wwt2lf43dcxsi2d6ynbpt35tap26bmiclbufc4pd3ruzhzi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaynu2wwt2lf43dcxsi2d6ynbpt35tap26bmiclbufc4pd3ruzhzi

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebbvvs6xsp772nlprxzwtjwdk5l5ug2xrami3glbo3kg753ho6m7k
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbvvs6xsp772nlprxzwtjwdk5l5ug2xrami3glbo3kg753ho6m7k

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzacedfuhfancjabfhjk7vjahys7n45en2sewvjgeqb6ec7ol5emb63ze
