### ISSUE TITLE
Notary Application: MathWallet

### ISSUE THREAD

**Issue by rayshitou** [filecoin-project/notary-governance#417]
# Notary Application

## Core Information
- Name: MathWallet
- Affiliated organization: MathWallet
- On-chain address to be notarized: f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
- Region of Operation: Asia minus GCN
- Use case(s) to be supported: general, blockchain data, web3 dapp
- DataCap requested for allocation (10TiB - 10 PiB): 1PB

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
MathWallet's main contribution and work in Filecoin Ecoystem includes:
* Has supported Filecoin since Testnet, and is one of the earliest wallets to support Filecoin testnet. See: http://blog.mathwallet.org/?p=1637
* Developed Filecoin App wallet. See: https://mathwallet.org/filecoin-wallet/
* Developed Filecoin custodial wallet system and Swap system.
* Runs two open Filecoin sync nodes for community use.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
N/A
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
* There are currently over 7,000 Filecoin wallets in MathWallet, with a cumulative total of over 15,000 transfers.
* We have collected and sorted various Filecoin eco-applications through our MathDAppStore for users to find and use. See: https://mathdapp.store/?blockchain=filecoin
* We provide a relevant API of Filecoin wallet, which helps DAPP developers to aggregate relevant functions. See: http://doc.mathwallet.org/en/filecoin  for developers' integration function
* We have written various Filecoin wallet operation tutorials to spread relevant knowledge to the community
For English, see: http://blog.mathwallet.org/?tag=filecoin
For Chinese, see: http://blog.mathwallet.xyz/?tag=filecoin
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
* MATH is a multi-chain and cross-chain blockchain assets hub whose products include:
MathWallet (supports 50+ blockchains including BTC, ETH, Filecoin etc and 1.2M users); MATH VPoS Pool, MathDAppStore, MathStaking, MathCustody, MathNFT, MathChain, MathHub, MathDEX, MathID, MathPay, and others.
Our investors includes Fenbushi Capital, Alameda Research, FundamentalLabs, Multicoin Capital.
* Registered country: Singapore
* Organization Size: 30 people
* Date of establishment: November 2017
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://mathwallet.org
https://twitter.com/mathwallet
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Official Website: https://mathwallet.org

News:
* MathWallet Raises $7.8 Million From Alameda Research and Multicoin
https://www.financemagnates.com/cryptocurrency/news/mathwallet-raises-7-8-million-from-alameda-research-and-multicoin/
* Fenbushi Capital Roundtable Series 3: MathWallet COO Eric talks about the role of Wallet in Filecoin ecosystem:
https://mp.weixin.qq.com/s/pdHYXpEDViSgjaVYXsCp2w
* The development history of wallets in China:
https://www.theblockbeats.com/news/19632
* MathWallet and Hurun Report reached strategic cooperation:
http://news.iresearch.cn/yx/2019/01/282439.shtml

Social Media:
MathNews https://news.mathwallet.xyz
MathBlog (CN) http://blog.mathwallet.xyz
MathBlog (EN) http://blog.mathwallet.org
Twitter https://twitter.com/Mathwallet
Weibo https://weibo.com/2803855662/
Medium https://medium.com/@mathwallet
Bilibili https://space.bilibili.com/526464306
Youtube https://youtube.com/c/MathWallet
Bishijie https://i.bishijie.com/home/math/dynamic
Bihu https://bihu.com/people/397093
Jinse https://www.jinse.com/member/88928
Tuoluocaijing https://www.tuoluocaijing.cn/columns/author311997/
Chainnews https://www.chainnews.com/u/748716797548.htm
Huoxing24 https://www.huoxing24.com/userCenter/360b0e7fc498439f8ade74568f96c393
Odaily https://www.odaily.com/user/2147493170
Xueqiu https://xueqiu.com/u/5676556297
Ccvalue https://www.ccvalue.cn/column/%E9%BA%A6%E5%AD%90%E9%92%B1%E5%8C%85
Jianshu https://www.jianshu.com/u/e0bab1403fe8
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter
https://twitter.com/mathwallet
followers: 274K

Discord
https://discord.com/invite/gXSfnk5eP5
members: 3K
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We will support a variety of use cases to ensure diversity. Based on the multi-chain and cross-chain nature of MathWallet, we will focus on use cases for blockchain data storage, particularly in IPLD related application scenarios.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
In making the plan, we will consider the following factors:
* Reputation of the organization
* Scale of allocation
* Frequency allocation
* Safety Precautions
* Transparency of customers
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The key allocated to the DataCap is protected on the multi-signature hardware wallet.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
* For due diligence on public datasets, we will look for strong evidence that they have a good maintenance foundation and a high reputation in their field.
* For due diligence on blockchain data, we will investigate the authenticity and feasibility of their requirements based on our experience in the development of multi-chain wallets.
* For due diligence on Web3 data, we will use our experience in operating DappStore to investigate the DApp team, product planning and implementation.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will ask Client to seperate DataCap to different entity.
We will review the Client status and if Client is not improperly over-allocating DataCap to a single entity, we will reject the Client's applicaiton during the next allocation.
We will publicize all requests and assignments which are subject to community’s supervision.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will happen in public, at the following repository:
(https://github.com/mathwallet/filecoin-notaries-onboarding)
We will have focal point to answer any questions through email and telegram group.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
https://github.com/mathwallet/filecoin-notaries-onboarding
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
About 5 Hours
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes, [Application 1](https://github.com/filecoin-project/notary-governance/issues/26) and [Application 2](https://github.com/filecoin-project/notary-governance/issues/123)
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
110TB
```

**Comment by galen-mcandrew** [comment]
[MathWallet - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320882/MathWallet.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
We are very sorry to let you know that this application was not selected in this round of Notary Elections.  

Each application was scored according to the Rubric and [assigned a Scorecard](https://github.com/filecoin-project/notary-governance/issues/394). That score was then applied for each of the [geographic regions and the top scored applications were selected](https://github.com/filecoin-project/notary-governance/issues/479). 

We are humbled by your commitment, and grateful for your interest in the Filecoin Plus program. Looking forward to seeing you in the program and hope you resubmit in the future elections.

Should you have any questions please feel free to raise here, or DM me in Slack @Kevin_FF

**Comment by rayshitou** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebivs3hx5bdjycftgmdbofo4ryzf6t7pzzhud4urzah6z43chrzgc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebivs3hx5bdjycftgmdbofo4ryzf6t7pzzhud4urzah6z43chrzgc
