### ISSUE TITLE
Notary Application: ByteBase

### ISSUE THREAD

**Issue by Destore2023** [filecoin-project/notary-governance#419]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Eric
- Affiliated organization: ByteBase
- Website / Social Media: 
- On-chain address to be notarized (recommend using a new address): f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
- Region of Operation: [Greater China]
- Use case(s) to be supported:  General (user content, enterprise data, scientific data etc.)
- DataCap Requested: 1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
1. In the second half of 2018, Mr.Wangsongping got to know miners from Filecoin through friends' introduction, provided a lot of help on IDC room design and training, and provided IT technical support for several miners in China. During this time, he also gained a detailed understanding of the overall nature of the Filecoin network, which, in addition to mining, can serve as a great storage tool for real-world individuals, studios, or enterprises.
2. After a year and a half of market research and system infrastructure analysis and research and development, Mr. Wang Songping co-founded ByteBase in 2020 and built the independently developed ByteBase data storage platform. With Filecoin sharing incentive as the driving engine, the platform makes full use of the immutable and data rights confirmation features of the blockchain. Fusion of widely distributed globally decentralized network node resources, and to provide the organization, the copyright backup, maintenance, important subject since the card, mass storage, and many other scenarios and business customers, provide more reliable, more safe and higher cost performance of distributed data storage card services, to further build and energize sustainable development of ecological chain data assets application. 
3. ByteBase become a Fil+ notary since July 2021. 98.6TiB DC was allocated to 13 clients. More than 25+ hours per week work on Filecoin community (Slack and GitHub)

Github handle  swatchliu
Slack handle     ByteBae
Miner ID            f0111007

```

### Stake Exposure
Please cite the total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
we have got 100,000+ Fil with the miner ID: f0111007.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
[ByteBase](https://www.bytebase.cn/) Milestone 

•  June 2019, ByteBase set up the project of Filecoin storage
•  April 2020, Mr. Wang songping and other 2 developers set up the company prototype.
•  Nov. 2020, after the 6 months of learning with Filcoin network and IPFS architecture, Bytebase start their storage system from 0.1-0.5 version
•  Dec. 2020 Bytebase officially registered, total 27 employee.
•  March 2021, the beta version 1.0 was launched, and 8 enterprises became the core users and participated in the experience.
•  April 2021, the official version is launched, and nearly 50 companies have partnered with ByteBase to continuously store information about IT, entertainment, healthcare, and the arts into the Filecoin network.
•  July 2021, became a Fil+ Notary in China
•  Sep. 2021, ByteBase Gateway launched, help storage providers upload user data into Filecoin network
•  Jan. 2022, PowerDealer launched, to improve the sealing capability of verified deals for SPs

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Filecoin Plus project terminology definition proposal
https://github.com/filecoin-project/FIPs/issues/159

```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
ByteBase was registered and established in Shanghai in 2020. ByteBase is a leading platform solution provider based on IPFS and blockchain storage in China.

Currently, there are nearly 100 team members, mainly focusing on system development, mainly from Alibaba, Huawei, Tencent, UCloud, and other traditional Cloud service manufacturers.

The representative products of the company are the independently developed ByteBase data storage platform, and the solution of the storage platform driven by the Filecoin shared incentive engine. Platform to make full use of the tamper-resistant and data made by the characteristic of the block-chain has the world's widely distributed fusion decentralized network node resources, and to provide the organization, the copyright backup, maintenance, important subject since the card, mass storage, and many other scenarios and business customers, provide a more reliable, more safe and higher ratio of distributed data storage card service, Further build and enable a sustainable block-chain data asset application ecosystem.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
ByteBase website: https://www.bytebase.cn/

WeChat Official Account: 冰塔数科, 130 articles, 418 subscribers

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://mp.weixin.qq.com/s?__biz=Mzg2MjU1OTU5Nw==&mid=2247484644&idx=1&sn=77d5e9953ffddaf5614dda1e5c09f23b&chksm=ce0748e6f970c1f033083431926d866476657a3789c8a1e95ed991639637dda21956918e4c78&token=1825079802&lang=zh_CN#rd 

https://mp.weixin.qq.com/s?__biz=Mzg2MjU1OTU5Nw==&mid=2247484677&idx=1&sn=ce76264010236f4e02a21ee07dcbc924&chksm=ce074907f970c01111e9357eb8c66872af25c3f09545266003c4a5d7b5aba75106062f71ac8f&token=1825079802&lang=zh_CN#rd 

https://mp.weixin.qq.com/s?__biz=Mzg2MjU1OTU5Nw==&mid=2247484648&idx=1&sn=831fa086d1e431ab30ee8bd776c9e692&chksm=ce0748eaf970c1fc04c67b2f618846850d4629ba01e229d18471944351608658e5dab1ccfa24&token=1825079802&lang=zh_CN#rd 

https://mp.weixin.qq.com/s?__biz=Mzg2MjU1OTU5Nw==&mid=100000953&idx=2&sn=9d2459775d523c8eb64aa9cf49383f42&chksm=4e0748bb7970c1add6295c8b8533df7362ef8c6171b277434b1ae64046cff593d3c574e9b6a3#rd 

https://mp.weixin.qq.com/s/s3gg3WeZMhIfJuUgQaOgaA 

https://mp.weixin.qq.com/s/lZsBlJdBejmGh3mYnqv_HQ 

https://mp.weixin.qq.com/s/YYxAiofLEC6Pt_sg9RTyHg 

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Linkedin https://www.linkedin.com/in/%E9%A2%82%E5%B9%B3-%E6%B1%AA-753885201/ 

WeChat Official Account: 冰塔数科, 130 articles, 418 subscribers

```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We plan to support the majority of use cases that we consider to be our expertise like copyright pictures and NFT. 
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and the rate at which you'll allocate DataCap.
```
We have developed a set of scoring criteria for clients to apply to DataCap, which has been uploaded to Google Docs.
https://docs.google.com/spreadsheets/d/1VEdGP0m03d0nrqzqWikOINzOe3wa_WLx-a6Ij73Ydxc/edit?usp=sharing

On our platform, we have developed and integrated the Filecoin DataCap application process in our official website: [www.bytebase.cn](http://www.bytebase.cn/) 

We also provide an online form for clients to submit application information.
Link: [https://www.wenjuan.com/s/qAVFfuN/#](https://www.wenjuan.com/s/qAVFfuN/)
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hardware wallet will be used to store the keys associated with the DataCap allocation address securely. 
4 people will be 2 teams, one keeps the GitHub account and one keeps the hardware wallet account.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In order to ensure the fairness and impartiality of DataCap allocation, we have developed separate online and offline application processes according to the number of DataCap applications and individual users and corporate users.

For individual users:
we will review their GitHub registration years (minimum of 180 days) to prevent bots from malicious applications. The amount of approval will also be controlled below 0.5TiB.

For corporate users:
We have developed different review methods and requirements depending on the number of their DataCap applications.
If it is less than or equal to 20TiB, we will adopt an online review. The following points will be reviewed.
•  Business license
•  Enterprise power of attorney (CEO signature + seal)
•  Data sample submission (0.2% of their total DataCap request)

If the application is larger than 50TiB, we will add an offline review (business trip to visit customers or invite them to ByteBase) based on the online survey method. There are:
•  Enterprise Business Type 
•  Data sources
•  Data volume (monthly)
•  Enterprise perceptions of Filecoin 
•  Data storage plans
 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. Audit the DC via statistics from https://filplus.d.interplanetary.one or www.filfox.info

2. Applicants are required to distribute DataCap to at least 3 or more SPs, which will increase storage redundancy and help maintain decentralization and reduce the potential for misuse.

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, in public.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
1. GitHub repo
2. https://www.bytebase.cn/#/dashboard 
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
20+ hours per week.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
https://github.com/filecoin-project/notary-governance/issues/169 
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
96.8TiB in total 
https://filplus.d.interplanetary.one/notaries/f01105814 
```

**Comment by galen-mcandrew** [comment]
[ByteBase - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320904/ByteBase.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi  @swatchliu **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Greater China.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 20 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by swatchliu** [comment]
Thanks for your support, Kevin! Please refer to below confirmation.

> Hi @swatchliu **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.
> 
> In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:
> 
> 1. Please confirm that the region of operation for client applications you will focus on is Greater China.
**Confirm**

> 2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).        
>    •	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship    .
**Confirm**

>    •	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.    
**Confirm**

>    •	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.    
**Confirm**

>    •	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.    
**Confirm**

>    •	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.    
**Confirm**

>    •	Community Governance Participation: It is expected that you will participate in the program 20 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.
**Confirm**

> 3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.
**f0111007**

> 4. Please affirm that you will abide by the allocation/client due diligence plan you laid out above.
**Yes, I will abide by the allocation/client due diligence plan I laid out above.**

> 5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.    
**Yes, we confirm our address is _f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi**_

>    •	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: [https://shop.ledger.com/pages/ledger-nano-x)    ](https://shop.ledger.com/pages/ledger-nano-x)%E2%80%A8)

**Comment by swatchliu** [comment]
Thanks for your support, Kevin! Please refer to the below confirmation.

Hi @swatchliu based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

Please confirm that the region of operation for client applications you will focus on is Greater China.

**Confirm**

Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).   

• Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship  .

**Confirm**

• Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 

**Confirm**

• Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 

**Confirm**

• No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

**Confirm**

• Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

**Confirm**

• Community Governance Participation: It is expected that you will participate in the program 20 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.

**Confirm**

Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

**f0111007**

Please affirm that you will abide by the allocation/client due diligence plan you laid out above.

**Yes, I will abide by the allocation/client due diligence plan I laid out above.**

(If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 

**Yes, we confirm our address is f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi**

**Comment by galen-mcandrew** [comment]
@swatchliu 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by swatchliu** [comment]
@Kevin-FF-USA  Hi Kevin, please add Slack handle EVS to the notary channel as a speaker of ByteBase.

**Comment by Kevin-FF-USA** [comment]
Hello @swatchliu!

We have your address on file as: https://github.com/filecoin-project/notary-governance/issues/419

We will be communicating with Eric and EVS via Slack.

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Datacap Allocated
> 1PiB

**Comment by swatchliu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec7nzwdigtl7yj3ca7w5kmnwnsvvm7a5j7vqxgpl3hhcsotckjyng
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7nzwdigtl7yj3ca7w5kmnwnsvvm7a5j7vqxgpl3hhcsotckjyng

**Comment by swatchliu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedvfjkcgslmwljs7xrpbbc3m4mrgby44wwtlbgvk4l2g6yijicj6e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvfjkcgslmwljs7xrpbbc3m4mrgby44wwtlbgvk4l2g6yijicj6e

**Comment by swatchliu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec4x5rbplyam5nezrs6h2yfxtekkqtzw2bju7zz2ny6isvw2ewgxe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4x5rbplyam5nezrs6h2yfxtekkqtzw2bju7zz2ny6isvw2ewgxe

**Comment by swatchliu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecliin7f325ee3pxsrgun7frgoak57ncf35s4rudcwu4cnfej5mzw
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecliin7f325ee3pxsrgun7frgoak57ncf35s4rudcwu4cnfej5mzw

**Comment by swatchliu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceafyr3t6ar7wq5ko3xcw2n7oavd6eig6ub6qeujt2nutq5q6pjo5a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafyr3t6ar7wq5ko3xcw2n7oavd6eig6ub6qeujt2nutq5q6pjo5a

**Comment by swatchliu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec6ezm3abwgwsj44fjhfvtc72bqfi3kpgwuerplk3p7fb6vx6i5ic
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6ezm3abwgwsj44fjhfvtc72bqfi3kpgwuerplk3p7fb6vx6i5ic

**Comment by swatchliu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceamvln73z5wxevypyu32xhov5viiuqr3o5wyosoedre2foty7dn26
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamvln73z5wxevypyu32xhov5viiuqr3o5wyosoedre2foty7dn26

**Comment by swatchliu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedpuxvy4fhjnwfjbcuujj3fown4wpw2zbij65a4wrkttkophtytbe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpuxvy4fhjnwfjbcuujj3fown4wpw2zbij65a4wrkttkophtytbe

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzacebfuw5rh33mzvd5aufoe6k4o4sw4hf2vdrld2uchfsplvpspg3ioy
