### ISSUE TITLE
Notary Application: Tim Williams

### ISSUE THREAD

**Issue by TimWilliams00** [filecoin-project/notary-governance#420]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here]
(https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Tim Williams
- Affiliated organization: self-employed
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address): f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
- Region of Operation: North America
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 10 PiB): 1PiB

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects, or contributions (with links).
```
Participated in Filecoin as Notary for community's daily work. Governance Meeting, checking and signatures for issues, staying active in slack. 
```

### Stake Exposure
Please cite the total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
I prefer not to disclose.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
I came into filecoin commuinty through Mr.Brozena in 2021. I am a freelancer of IT. I used to live and study in the US and now live in Singapore.
In June 2021, Mr.Brozena (VP of Business Development at Performive) was no longer performed the work obligations of a notary on behalf of Performive due to personal reasons and handed over the relevant responsibilities to me. I also announced on Slack - the notary channel, and explained to the community and requested updates, including GitHub, slack, and wallet addresses.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
I didn't build any nodes because it's difficult for me. My mainly work is to check various application materials according to Fil+ program's rules and if these allocations are under the rules.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Now my application for a notary is personal behavior.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
N/A
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
N/A
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you can use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Slack: Tim Williams
Github: https://github.com/TimWilliams00
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Considering the principle of Filecoin, being a decentralized storage network designed to store humanity's most important information, we should encourage, instead of preventing; people to store any public and useful data for human society.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and the rate at which you'll allocate DataCap.
```
Notary responsibilities are as follow:
•	Allocate DataCap to clients to subsidize reliable and useful storage on the network.
•	Verify that clients receive a DataCap commensurate with the level of trust that is warranted based on information provided.
•	Ensure that in the allocation of the DataCap no party is given excessive trust in any form that might jeopardize the network.
•	Follow operational guidelines, keep a record of decision flow, and respond to any requests for audits of their allocation decisions.

Lesson and Learn from AWS: Incentives over $10,000 to SMB generate all sorts of fraudulent activities, especially from crypto miners. DataCap for any applicant will only be allocated by batch, and the granted DataCap will be gradually available to the Client over time with a view to my continuing control of the Client’s proper spending. The applicant must meet the requirements pre-specified in my allocation decision to have the subsequent portions of the granted DataCap unlocked, which requirements are expected to include, inter alia, low concentration of miners and storage of approved data only. Accordingly, failure to meet the aforementioned requirements will result in a delay of allocation or even cancellation of the remaining DataCap.

For the time being, I would only take requests of 100TB or under, until the Notaries committee agrees to the allocation strategy guidelines as a group for requests>100TB.

Other than the list of factors (reputation, allocation, security, and transparency) Philipp pointed out, I am also interested in if the Clients know exactly what they are doing with clear expectations; instead of being lured onto GitHub by miners. I would be more confident if the Clients already have the resources and even budget ready for storing at Filecoin network, regardless of the amount of DataCap being allocated. 

Furthermore, I try not to weigh much on time/effort factors, but more on result-oriented factors, as either tenure or time spent in the field is not much correlated with contribution or reputation. Some people prefer to give heavyweight to “Diversity and Decentralization” and look to encourage Clients to store their data across multiple regions in multiple ways. It’s probably good for notaries being in different regions so that I better understand my clients; for DataCap Clients, I would encourage them to do what’s best for them, as the purpose of DataCap is meant to get Clients to the network easier, not the other way around.  
The following tool will be the primary guideline for DataCap allocation. Each applicant will be rated by the following factors and criteria. A sample Client, Protocol Labs, is scored at 3.4 for references.
https://docs.google.com/spreadsheets/d/1GUEgNkfZRrju-ihkdD5e7LxLMeDa2ahs6WsBU_FnJVI
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
At the moment, the address that will be allocated DataCap will have its keys be secured on a hardware wallet only for myself.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
This includes both on-boarding due diligence and post-allocation vetting
1.	On-boarding due diligence
First, I will collect KYC & onboarding documents as follows to identify the client. I may also employ a KYC Registry to consolidate all KYC data (may use third-party tooling), depending on the scale of the applications.
•	Entity Information: Formation documents (this includes certificates of registration/incorporation/information); government-issued identification number 
•	Authorized Signatory Information: evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operating agreement) 
•	Beneficial Owners - If there are any 25%+ shareholders, I need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: Name, DOB, Address, IDs, etc. 
•	References: contract information of at least 2 people, e.g., executives, partners, or board members. 

2.	Post-allocation Vetting
Post-allocation Vetting is performed regularly and constantly to avoid the allocated DataCap being abused or misused. The fundamental principle is that the Client is obliged to spend the DataCap exclusively for the approved uses. 
To this end, at any time of the Client’s spending the DataCap, I may ask the Client to provide:
•	A consolidated Content Identifier (“CID”) list for verified deals that includes deal CID and miner ID (showing how the allocated DataCap has been used)
•	Description of the data being stored and how the data has been processed
•	Instructions on data retrieval

Receiving the foregoing information, I will perform random-sample inspections on the verified deals sent out by the Client on the chain by checking the deal CID and retrieving it from the corresponding miners to verify the data authenticity.

My DataCap allocation rating tool already gives a heavyweight on Clients being responsible for DataCap spending.
•	A Client either needs to have good knowledge of the Filecoin network or has a clear expectation of spending the DataCap.
•	A Client needs to be fully prepared and has a detailed plan on applying DataCap for the good of the organization.  
•	A DataCap subsidization and reliable storage identification strategy need to be planned with P/L analysis.

I expect Clients to be responsible for continuously receiving DataCap in batches. During the DataCap allocation growing stage, I would investigate and ensure that DataCap allocated to Clients does not exceed their actual data storage needs. I would trust Clients for small DataCap allocation and continuously monitor the usage. For an LDN allocation, I would consult an external domain of experts, as well as scheduled online/offline meetups with Clients.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Diligence with the previous allocation statistics via https://filplus.d.interplanetary.one// and http://[www.filfox.info](http://www.filfox.info/)  
Any application in doubt will be discussed in governance call or notary channel for future processes.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, both on GitHub and email.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
I plan to use GitHub as a public platform to keep those records. 
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
3-4 hours per week.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
https://github.com/filecoin-project/notary-governance/issues/50
https://github.com/filecoin-project/notary-governance/issues/132
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
70TiB  https://filplus.d.interplanetary.one/notaries/f01284159
```

**Comment by galen-mcandrew** [comment]
[Performive - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320951/Performive.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi  @TimWilliams00  **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is North America.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 4 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by galen-mcandrew** [comment]
@TimWilliams00 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by rdirocco** [comment]
This request is 100% not affiliated with Performive

**Comment by TimWilliams00** [comment]
Dear Mr. DiRocco, sorry for the misunderstanding.
 
This is Tim Williams from Filecoin Community.
Mr. Brozena (VP of Business Development at Performive) applied and successfully acted as Filecoin's notary on behalf of Performive in December 2020, 

In June 2021, after continued to apply to be a notary of Filecoin for the second time, Mr.Brozena was no longer performed the work obligations of a notary due to personal reasons and handed over the relevant responsibilities to us. We also announced on Slack - the notary channel, and explained to the community and requested updates, including GitHub, slack, and wallet addresses.

I believe you have communicated with Mr. Brozena in these situations. In order to avoid unnecessary misunderstandings, we are willing to use the name of Tim Williams to act as a notary instead of Performive and we apologize for any misunderstanding caused to you. The updated information will be submitted here, please refer to the community: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by galen-mcandrew** [comment]
@TimWilliams00 We need some more details to verify your identity and relationship with Performive, as you are citing being an official representative of that US-based company. 

Please reach out to us here and at filplus@fil.org with more evidence to verify your identity.

**Comment by TimWilliams00** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebzo5slr5d33relipuiz56bjqbjyh5ln22aztlv5xc2hgvlruglbg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzo5slr5d33relipuiz56bjqbjyh5ln22aztlv5xc2hgvlruglbg

**Comment by galen-mcandrew** [comment]
@TimWilliams00 still hoping for some more diligence and evidence to verify your identity and previous relationship with Performive.

**Comment by galen-mcandrew** [comment]
@TimWilliams00 still hoping for some more diligence and evidence to verify your identity and previous relationship with Performive. Please provide some more details and evidence of your identity here, and reach out to us at filplus@fil.org

**Comment by TimWilliams00** [comment]
> Dear Mr. DiRocco, sorry for the misunderstanding.
> 
> This is Tim Williams from Filecoin Community. Mr. Brozena (VP of Business Development at Performive) applied and successfully acted as Filecoin's notary on behalf of Performive in December 2020,
> 
> In June 2021, after continued to apply to be a notary of Filecoin for the second time, Mr.Brozena was no longer performed the work obligations of a notary due to personal reasons and handed over the relevant responsibilities to us. We also announced on Slack - the notary channel, and explained to the community and requested updates, including GitHub, slack, and wallet addresses.
> 
> I believe you have communicated with Mr. Brozena in these situations. In order to avoid unnecessary misunderstandings, we are willing to use the name of Tim Williams to act as a notary instead of Performive and we apologize for any misunderstanding caused to you. The updated information will be submitted here, please refer to the community: https://airtable.com/shrs55Lzbm1wJTIRw

Thanks Galen,  Please see my detailed reply as above, promise the above information is true and reliable.

**Comment by galen-mcandrew** [comment]
@TimWilliams00 The team from Performive has reached out directly to dispute this request and challenge your affiliation with their organization. Please verify your legal name and provide some additional evidence of your role in the community and your relationship with Mr. Brozena since 2021. You can provide that evidence here or directly at [filplus@fil.org](mailto:filplus@fil.org)

**Comment by TimWilliams00** [comment]
The internal opinions of Performive will be unified and I will get back to you soon.

**Comment by TimWilliams00** [comment]
@galen-mcandrew 
I'm pretty sorry for the late response. My opinion finally reached a consensus with Jason.

I've never work for Performive. Just because I am familiar with Jason, I refered to Jason's previous notary application and continued using the name 'Performive' as a notary. It is  indeed inappropriate behavior. So I change this application into my own notary application formally this time.

1.If I can continue working as a notary, I will strictly do my duty;
2.If it is improper for me to work as a notary, I will go on focusing on the development of Filecoin and hope that I can have an apportunity to apply for a notary again in the future.

I will respect the decision of Filecoin community. Thanks all!

**Comment by TimWilliams00** [comment]
@galen-mcandrew 
I'm pretty sorry for the late response. My opinion finally reached a consensus with Jason.

I've never worked for Performive. Just because I am familiar with Jason, I refered to Jason's previous notary application and continued using the name 'Performive' as a notary. It is indeed inappropriate behavior. So I change this application into my own notary application formally this time.

1.If I can continue working as a notary, I will strictly do my duty;
2.If it is improper for me to work as a notary, I will go on focusing on the development of Filecoin and hope that I can have an apportunity to apply for a notary again in the future.

I will respect the decision of Filecoin community. Thanks all!

**Comment by TimWilliams00** [comment]
@galen-mcandrew @Kevin-FF-USA @dkkapur  Have you got my mail? Please let me know if you have a result of this updated application. Thanks a lot!
