### ISSUE TITLE
[Notary Application] Xinan Xu - Tech Greedy

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/notary-governance#421]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Xinan Xu
- Affiliated organization: Tech Greedy Inc (corporation)
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address): f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
- Region of Operation: North America
- Use case(s) to be supported: Web 2/3 applications, storing public data
- DataCap Requested: 1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Engaged in Filecoin ecosystem since the mainnet as
1. storage provider - example miner - f064218
2. Consultation service provider
3. slingshot participant startin phase 2.1, onboarded 30+ different dataset.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Storage provider f064218, f0838923, f01752548 and pending rewards from Slingshot and slingshot restore.
Around 30k summing up available, locked and vesting over time.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Slingshot participant from 2.1 to 2.7, onboarded 30+ various dataset.
Part of Miner X.2 program
Part of Slingshot restore program, recovered 6 lost dataset.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Report mulitple bugs in https://github.com/filecoin-project/lotus/issues?q=xinaxu
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Corporation incorporated 1/11/2022 in Washington state, USA. Previously a sole proprietorship since 2016.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
LinkedIn profile - https://www.linkedin.com/in/xinan-xu-b868a326/
Named officer - Xinan Xu
Website for Slingshot UI - https://three_w_dot_techgreedy_dot_net
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.linkedin.com/company/79118189
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://www.linkedin.com/in/xinan-xu-b868a326/
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
I'd like support for two major use cases
1. Slingshot restore and slingshot program
2. web application development to promote Filecoin influence
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
For web application development. I want to always start with a small amount (1TiB) for developer to test their application with. Once the application is launched, I plan to support up to total 1PiB depending on the actual data needed. 
- If it is a new project, I plan to gradualyl increase the datacap grant amount, starting from 10TiB.
- If it is an existing project, I plan to actively check the application's use base and grant a proper amount according to the influence of the application.
For Slingshot project, I want to support the program by allocating proper amount according to below factors
- The client will need to follow the slingshot and slingshot rules. This will be checked before each grant
- For existing slingshot participant, the datacap amount will be determined by their past performance and dataset size
- For new slingshot participant, the amount will always start small (100TiB) and gradually increase as they follow rules and demonstrate their performance.
- I will perform retrieval test and actually look at the data. Any cheater will be blacklisted from further allocation.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
I plan to use hardware secured wallet to make sure only I have the permission to sign datacap requests.
If a security breach happens, I will revoke my wallet and remove any datacap that was granted without permission.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
For grant smaller than 1TiB, I will perform less verification to encourage new people to enter Filecoin ecosystem
For grant larger than 100TiB, I will ommunicate with clients through messaging channel such as slack to understan their backgrounds, motivations and goals. The client will need to demonstrate their past success in deal making with multiple storage providers via either verified or unverified deals. 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
In general, I will utilize tools such as https://filplus.d.interplanetary.one/ to understand how they are making deals with various SP entities. I will also perform random retrieval test and look at the data to make sure actual data is stored.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
In public via github repo.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
In public via github repo.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
1 hour per day. Typical response time is < 24 hours via Slack or < 72 hours via Github
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/138
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/181
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/182
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/227
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
I have not allocated any datacap as I was not a notary.
I have received and distributed 1 PiB of datacap as part of Slingshot restore program.
```

**Comment by galen-mcandrew** [comment]
[Tech Greedy - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320952/Tech.Greedy.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi  @xinaxu  **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is North America.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 5 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by xinaxu** [comment]
Hi @Kevin-FF-USA 
1. Yes I can confirm that the region is North America
2.
> Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .

I agree with the upfront disclosures

> Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 

I agree to promote client best practices

> Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 

I agree to commit to efficiently serving the Network

> No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

I agree to perform no self sealing

> Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

I agree to operate in Good Faith

> Community Governance Participation: It is expected that you will participate in the program 5 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context with discussions and input. 

I agree to participate community governance

3. Storage Provider: `f064218`, `f0838923`, `f01049918`, `f01752548` and their owner/worker addresses, `f17vpk5gq7vctuilti2mwspsyf6i6f2nzwbaw3mxy` - direct ownership
4. Yes, I confirm that I will abide by the allocation plan I laid out above
5. TBD

**Comment by galen-mcandrew** [comment]
@xinaxu 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Yes - I have just gotten your information on my end, I must have missed it the first time around. Thank you, much appreciated.

**Comment by xinaxu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebr2ek7vrb5vorycswyvpvkg3mwjm54l7sleo4ojwowdugba6l4pi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebr2ek7vrb5vorycswyvpvkg3mwjm54l7sleo4ojwowdugba6l4pi

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### Datacap Allocated
> 1PiB
