### ISSUE TITLE
[Notary Application] New Web Group

### ISSUE THREAD

**Issue by newwebgroup** [filecoin-project/notary-governance#422]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information

- Name: New Web HK Group Holdings Limited
- Affiliated Organization: New Web Group
- Website / Social Media:  http://www.newwebgroup.com  /   twitter: NewWebGroup
- On-chain Address to be Notarized: f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
- Region of Operation: Greater China
- Use case(s) to be supported: General
- DataCap Requested: 1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

```

In 2017, the founding team of New Web Group was involved in IPFS and formed a technical team.
In August 2020, we participated in the FIL Space Race.
In 2019, NWG established a deep long-term partnership with GCR local IDC operators. 
December 2020, New Web Group Technology was established and now has 100+ employees and has gained a very good reputation in China.
In August 2021, New Web Group's international office was established and is building an international computing platform, hoping that more people internationally will come to focus on FileCoin.
In January 2022, we cooperated with the FileCoin retrieval market and submitted a development proposal for a distributed shared CDN to help FileCoin improve the reward mechanism for retrieval service providers and enhance the experience of the Filecoin retrieval market and the ecological construction of FileCoin.
In March 2022, we officially became a member of the orbit community, and as a founding member, we are ready to work with the community to do a good job of educating the world and making more people aware of and enjoy FileCoin.
On top of that, our company has a great group of employees who each promote Filecoin on social media and in total have gained a following of over 50,000 people and influenced 5 million crypto digital currency investors.

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
So far, we hold tokens Close to 5 MM FILs (Details upon request).

```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```

New Web Group is one of the world's leading FileCoin miners with a leading IPFS mining pool.
New Web Group can provide customers with one-stop storage services, including storage resource management, storage resource trading, and storage token trading across different blockchains.
Meanwhile, New Web Group provides decentralized cloud computing services based on Web 3.0 infrastructure with blockchain technology as the backbone.
We held the 2021 Western World IPFS Strategy Conference: https://www.jinse.com/news/blockchain/1038626.html
We participated in the following conferences.
Supercomputing Convergence Conference in Chengdu, China. https://www.chainnode.com/hashcon-2021; https://www.8btc.com/wbc-2021.
2021 World Blockchain Conference in Hangzhou, China https://www.8btc.com/article/6666759
New Web Group is also working with Protocol Labs to improve the user experience in the Filecoin retrieval marketplace. Our development team is working on a high-performance CDN that will provide a better infrastructure and greatly improve the ecosystem at the application layer. https://filecoinproject.slack.com/archives/C015G3B5RQE/p1645022344865649
Most recently, New Web Group has become a member of our inaugural Community Track Program queue.

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Organization: New Web HK Group Holdings Limited
Nature:  Private Company
Registration Country: Hong Kong, China
Established: Jan, 2021
Size: over 100 employees
New Web Group is a technology-based enterprise focusing on distributed storage server hardware development, cluster cloud storage equipment sales, IDC server room hosting, cloud storage operation and maintenance industries, and is committed to building a world-class decentralized storage operation service provider. It is the purpose of the platform to provide butler service for customers.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Homepage: http://www.newwebgroup.com
Twitter: NewWebGroup

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
We held 2021 West World IPFS Strategy Conference: https://www.jinse.com/news/blockchain/1038626.html
We participated in the following conferences:
Super Computing Fusion Conference in Chengdu, China. https://www.chainnode.com/hashcon-2021; https://www.8btc.com/wbc-2021.
2021 World Blockchain Conference in Hangzhou, China https://www.8btc.com/article/6666759

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Insight Financial News: https://m.youtube.com/channel/UCRCJkQttdjzJYpbur5Qut6A with approximately 32.8k subscribers
Blockchain Metaverse: https://www.youtube.com/c/WorldBlockchainRobert  with approximately 40.5k subscribers
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We plan to support all user cases by providing FileCoin protocol development of high performance CDN networks, which will increase the network efficiency and provide better user experience for all developments.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Allocation Plan:
1.We will verify customers into two categories: Existing customers and New Customers
2.For existing customers, we need to check if there is any violation of international and local laws, filecoin’s standards and ethics. For new customers, we will go through a specific KYC for individual clients or corporate clients.
3. After the KYC and client identify verification, the client who apply for the DataCap will go through a scoring process based on their applications and evidence as below: https://docs.google.com/spreadsheets/d/1MkVkIgVduJDq3ic02X-r60epc3Fa62APM9kD88q4DBo/edit?usp=sharing
4. The final sore will be given based on the Client Identity, Diversity, Decentralization, Allocation Strategy. For each sector we give a score of 0-7, eventually, the total score will be fit into a DataCap table to give the final granted amount of DataCap.
5. The granted amount of DataCap will be confirmed and verified with remaining DataCap, then the granted amount will be allocated to client.

```
![allocationPicNewWebGroup](https://user-images.githubusercontent.com/100118145/156306939-f84f6146-0249-4e6d-9918-30953e23f6a7.jpg)

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```

A hardware wallet will be used to store the keys for DataCap address.

```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will go through a comprehensive due diligent process to make sure the client spending DataCap responsibly.
Firstly, we need to confirm their identification.
For individual customers, the verification of their identity will be verified through:
1.Identification number
2.Name
3.Data of birth
4.Copy of Passport
5.Address
6.Social media account (Facebook/LinkedIn/Twitter)
7.Local Offices Contact Details
8.Social reputation (Prize, Achievement)
For corporate clients, the verification of their identity will be verified through:
1.Company Registration Certificate/Operating Licence
2.Address
3.Website
4.Social media account (Facebook/Linkedin/Twitter)
5.Record of law suits and legal reputation
6.Company equity structure and key stakeholders
7.Scanned copy of letter from company with stamps and signature of director/stakeholder from the company
Stakeholder due diligence process for company shares/equity over 20%. (Stakeholder due diligence process will be similar to the above process, until the final beneficiary/the-actual-stakeholder is found.)

We will ask the following questions:

We will ask customers the following questions:
1.Can you identify yourself as organization or individual?  Your name/Your organization name?
2.What is your/ your organization social media/website link?
3.how much data you want to store? Can you specify the data you want to store according to use case type, source and by how much in each category? 
4.Are you receiving DataCap from other notaries? If yes, can you list their names?
5.What cloud service/platform do you use, can you describe to me your usage frequency, volume, price/rates and purpose?
6.How many miners do you want to allocate your data to? How much data for each miner?
7.Can you provide transparency on your DataCap allocation/decision/ execution respectively? 
8.What are the advance FileCoin features do you use to apply your DataCap allocation?
9.What content you’re going to store, does this content comply with local law and FileCoin community standards and regulation?
is there any potential client will paid for the content you store? 
10.Where do you store these data, how much in total, and how much do you pay respectively per year?

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```

Firstly, we will carry out a very detailed KYC and due diligence process. We will encourage customers to allocate DataCap to new miners, and we will design a plan for each new miner, new allocation will have some incentives.
Also, we will record the DataCap data including trading data, allocation data etc., and ask the client to disclose the relevant information.
We will develop a software tool to automatically check for over-allocation and make sure the DataCap for last allocation was fully used before next round of application.In addition, we will hire some technical compliance analysts to manually check for over-allocation.
And all the allocation results will be published on the GitHub.

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```

We will keep every detail record for all allocation decisions on Github, including time, amount, allocated customers, reason for allocation, etc. Since all interactions and decisions will be carried out openly, most of the allocation decisions should be self-explanatory. Any challenges raised regarding allocation decisions should be discussed publicly, e.g. the Github Repo.

```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
In both, we will keep the public GitHub records and a private chat via Slack or Telegram.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
60 Hours per week to attend governance calls, messaging on slack, make DataCap allocations etc.

```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
N.a.
```

**Comment by galen-mcandrew** [comment]
[New Web Group - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320910/New.Web.Group.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi  @newwebgroup **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Greater China.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 60 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by newwebgroup** [comment]
Our team is very happy to receive this email message. Thank you very much.

We will continue to work hard to make the filecoin ecology better and
healthier.

Kevin ***@***.***>于2022年3月29日 周二下午10:36写道：

**Comment by newwebgroup** [comment]
> Hi @newwebgroup **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.
> 
> In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:
> 1. Please confirm that the region of operation for client applications you will focus on is Greater China.
Confirmed!

> 2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).        
>    •	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship    .
>    •	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.    
>    •	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.    
>    •	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.    
>    •	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.    
>    •	Community Governance Participation: It is expected that you will participate in the program 60 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.
Confirmed All!

> 3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.
 if you want to know the details, you can consult "Yuan" on Slack.

> 4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.
Affirmed!

> 5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.    
>    •	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: [https://shop.ledger.com/pages/ledger-nano-x)    ](https://shop.ledger.com/pages/ledger-nano-x)%E2%80%A8)
Thanks, we already have it.

**Comment by galen-mcandrew** [comment]
@newwebgroup 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by newwebgroup** [comment]
> @newwebgroup
> 
> Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

Hi, Kevin and Galen，Thank you very much for your support. I resubmitted the link information. In the latest link information, I applied to change the notary's address to
**“F1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq”**

The previous **"f1q55myrpvozgdaetcdh7lvixsrd2dg46xiy3o5gq"** is invalid. 
I hope you can check it.

**Comment by Kevin-FF-USA** [comment]
Hello @newwebgroup!

This is a friendly ping - we have received your information, but the field for your Slack handle was not filled. In order to receive Notary communications via Slack we need you to: 

- Provide a Slack handle within this GitHub ticket (for public record)
- Message Kevin_FF on Slack with that same Slack handle you entered in this ticket.

**Please provide this information by April 25th. Thank you!**

**Comment by newwebgroup** [comment]
Sorry, Kevin, I just saw this message.
The ID of slack is  **U027SDP1PGD**
Slack's name is **Yuan**

**Comment by Kevin-FF-USA** [comment]
Thanks for confirming.  Pasting a screenshot of chat to ensure correct address.  
![image](https://user-images.githubusercontent.com/94004586/166452831-292f05ff-46ec-48f7-8176-af9b6d601c13.png)

**Comment by newwebgroup** [comment]
Hi @Kevin-FF-USA 
Thank you very much for your reminder.
New web group will add another contact.
His slack ID is: Axe 欧阳
<img width="394" alt="image" src="https://user-images.githubusercontent.com/100118145/167330114-5cbcdfff-2e3a-4aa6-839e-c6c1518f4913.png">

**Comment by fabriziogianni7** [comment]
I updated the parent comment with the new address. this is probably the reason for this notary ledger not to have been verified.
cc @dkkapur @galen-mcandrew

**Comment by newwebgroup** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceciltlj6dldc5szwnh4vk3ai5jjmgwne4v6t2zwtjoru7tncijegm
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceciltlj6dldc5szwnh4vk3ai5jjmgwne4v6t2zwtjoru7tncijegm

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Datacap Allocated
> 1PiB

**Comment by newwebgroup** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecvbpleupx7kkm6q4wcbucdyz7hrzettyaoobyvuxhubvsj57sf2o
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvbpleupx7kkm6q4wcbucdyz7hrzettyaoobyvuxhubvsj57sf2o

**Comment by newwebgroup** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecoarmfvqkf74x3qpfhxmplwbrowvslinzhj25mh2ralghw2f66ig
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecoarmfvqkf74x3qpfhxmplwbrowvslinzhj25mh2ralghw2f66ig

**Comment by newwebgroup** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecennxexabdfssgueth67y2o6cw3gjud4752du53im7id5mydrd4u
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecennxexabdfssgueth67y2o6cw3gjud4752du53im7id5mydrd4u

**Comment by newwebgroup** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebadzy7lfikz3pytcpimnmuvqhx3dgdvt3rkb72wnkbgrt7b2pr36
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebadzy7lfikz3pytcpimnmuvqhx3dgdvt3rkb72wnkbgrt7b2pr36

**Comment by newwebgroup** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecbavlxobelcyshxrnzxpqeqdnj4glrei7ymndxprxgysoqdw3ltk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbavlxobelcyshxrnzxpqeqdnj4glrei7ymndxprxgysoqdw3ltk

**Comment by newwebgroup** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacea5mlmtjgfiekxe23ghewciufclbyfm2jmidhsxwcq5sdjk3ggyhe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5mlmtjgfiekxe23ghewciufclbyfm2jmidhsxwcq5sdjk3ggyhe

**Comment by westlabsventure** [comment]
Hi there,

I'm responsible for following up with you on how to keep our Filecoin Notary status. Is there any form or anything we need to fill out now? Please let me know.

Thanks
