### ISSUE TITLE
[Notary Application] Fatman13 - Guazi Dynamic

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/notary-governance#424]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Fatman13
- Affiliated organization: Guazi Dynamic
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address): f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
- Region of Operation: Greater China
- Use case(s) to be supported: Web 3.0 / Decentralized Applications, Web 2.0 Applications, User Content, Scientific Data, Media & Entertainment
-DataCap requested for allocation (10TiB - 10 PiB): 100TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Github handle: @fatman13 
Slack handle: @fatman13
Miner ID: f02731, f0694916, f01016254 (> 100k token at stake @ the time of this application)
Closely followed Filecoin project since 2017 and started full-time participation in 2020 since Space Race. Have been contributing to the network through mining, community discussions, governance and promotion of filecoin.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
f02731, f0694916, f01016254 (> 100k token at stake @ the time of this application)
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- Major contributor to [venus-docs](venus.filecoin.io)
- Major contributor to [Venus online meetups](https://www.youtube.com/watch?v=th8QJGFcNH8)
- Core member of Storage Provider Working Group; Maintainer of [SPWG-CN](https://github.com/stuberman/MWG/tree/main/mwg-aisa)
- Contributor to [FIP](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md)
- Volunteer of ProtoSchool
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Organization name: Guazi Dynamic
Size: ~10
Country: China
Founded: Sep 1st, 2020
We offer turnkey mining solution to clients in east Asia including South Korea, Japan and China.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: guazi.io
Wehcat public account: 瓜子动力
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://mp.weixin.qq.com/s/sD6kTsuYZhilUdcwzcXGHg
https://www.tuoniaox.com/news/p-469057.html
http://www.btb8.com/fil/2010/97772.html
https://www.jiemian.com/article/5196371.html
https://www.jinse.com/news/blockchain/800936.html
https://page.om.qq.com/page/OiP1FgLD5z1rasQf9EWQwWcw0
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter: [fatman13](https://twitter.com/FATman13CC); ~2k followers
Weibo: [fatman13](https://weibo.com/u/1767457232); ~8k followers
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We are open to new use cases if storage client could make its case.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
I draw inspiration (with regard to allocation strategy) heavily from https://github.com/filecoin-project/notary-governance/issues/413, https://github.com/filecoin-project/notary-governance/issues/414 and https://github.com/filecoin-project/notary-governance/issues/412.

I will be adopting the [Rubric](https://docs.google.com/spreadsheets/d/1zQ3FXJmmBMmynDIdRjYTYp-K95Dp95ypVoBfRhABPC0/edit?usp=sharing) defined by issue#413 with 7 varying degrees of trust.
The above rubric will be my primary guideline when evaluating a client and determining their dataCap target amount.
By adopting this rubric, I expect to add a level of consistency across the board.
I also plan on allocating dataCap with a small incremental amount(<10%) and build a reputation mechanism.
For new clients, they start small and gradually increase their allowance through good behavior under filecoin plus guidelines.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Will be using an off-line wallet whose private key is only known by me.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Again I draw inspiration (with regard to due diligence) heavily from https://github.com/filecoin-project/notary-governance/issues/413, https://github.com/filecoin-project/notary-governance/issues/414 and https://github.com/filecoin-project/notary-governance/issues/412.

I plan to have the vetting process functional yet not too cumbersome. 
I expect to engage with the client's request quickly, thus optimizing the overall experience.

The information needed for vetting a client will be as the following...

1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information; 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name;
 - date of birth; 
 - street address (P.O. box number is not acceptable); 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

Questions we will use to know client better are as the following...

1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.)
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
6. How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify.
7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Using filplus.info can easily reveal if a storage client is only sending deals with a single SP miner id. 
To make sure deals are not distributed within a single SP entity, I plan to sync with other notaries and cross check with them on a regular basis to eliminate the concerns.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Github repo only.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
I expect that all decision be tacked on Github and filplus.info publicly.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
5-10 hours per week.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
A bit confused about the terminology here. I see some notary applicants put allocation as in distributing storage deals to storage providers and others put their approval of datacap to storage clients.

- [LDN application](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/84)
- [application1](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/459)
- [application2](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/132)
- [application3](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/127)
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
Active role in distributing [~1000TiB](https://filplus.info/allocation_record?client_address=f3qaipvxrz2gxexc7mcvjsxifmscfiw7c7zfhrmq76j5ee4hcbvg3gbtpea7wgz72kkjcjmwzhm5uo2onxyocq&obj=eyJvcmdfbmFtZSI6Ikd1YXppIER5bmFtaWMiLCJsZG5fYWRkcmVzcyI6ImYydDVrdTRmZ2RhaDdld210d3FyNmg2d3NtYWRndHRzbG56MmZndXVpIn0%3D) of datacap to small to medium sized storage providers in Asia using Venus according to stats on filplus dashboard. 
```

**Comment by galen-mcandrew** [comment]
[Guazi Dynamic - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320919/Guazi.Dynamic.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Fatman13** [comment]
Hello, @galen-mcandrew, would like to supply more materials for the application.

## For time commitment & In-protocol Reputation

(A lot of them are overlapping with each other as I see people score high points in these two areas)

Github handle: @fatman13 
Slack handle: @fatman13
Miner ID: f02731, f0694916, f01016254 (> 100k token at stake @ the time of this application)
Closely followed Filecoin project since 2017 and started full-time participation in 2020 since Space Race. Have been contributing to the network through mining, community discussions, governance and promotion of filecoin.

- Participation in testNet in April, 2020
- Participation in Space Race in August, 2020
- Participation in Slack community with more than ~10K messages
- One of the hosts for a monthly filecoin [meetup](https://youtube.com/playlist?list=PLvmxExuDQi1nxFrwZGtnuURKoCNbovCpw)
- Active contributor to filecoin-project on Github with PRs, issues, discussions etc

https://github.com/filecoin-project/venus-docs/pull/289
https://github.com/filecoin-project/venus-docs/pull/288
https://github.com/filecoin-project/venus-docs/pull/287
https://github.com/filecoin-project/venus-docs/pull/286
https://github.com/filecoin-project/venus-docs/pull/285
https://github.com/filecoin-project/venus-docs/pull/284
https://github.com/filecoin-project/venus-docs/pull/283
https://github.com/filecoin-project/venus-docs/pull/282
https://github.com/filecoin-project/venus-docs/pull/281
https://github.com/filecoin-project/venus-docs/pull/276
https://github.com/filecoin-project/venus-docs/pull/275
https://github.com/filecoin-project/venus-docs/pull/273
https://github.com/filecoin-project/venus-docs/pull/257
https://github.com/filecoin-project/venus-docs/pull/248
https://github.com/filecoin-project/venus-docs/pull/237
https://github.com/filecoin-project/venus-docs/pull/236
https://github.com/filecoin-project/venus-docs/pull/234
https://github.com/filecoin-project/venus-docs/pull/233
https://github.com/filecoin-project/venus-docs/pull/232
https://github.com/filecoin-project/venus-docs/pull/231
https://github.com/filecoin-project/venus-docs/pull/228
https://github.com/filecoin-project/venus-docs/pull/225
https://github.com/filecoin-project/venus-docs/pull/217
https://github.com/filecoin-project/venus-docs/pull/204
https://github.com/filecoin-project/venus-docs/pull/192
https://github.com/filecoin-project/venus-docs/pull/190
https://github.com/filecoin-project/venus-docs/pull/184
https://github.com/filecoin-project/venus-docs/pull/183
https://github.com/filecoin-project/venus-docs/pull/181
https://github.com/filecoin-project/venus-docs/pull/180
https://github.com/filecoin-project/venus-docs/pull/164
https://github.com/filecoin-project/venus-docs/pull/157
https://github.com/filecoin-project/venus-docs/pull/153
https://github.com/filecoin-project/venus-docs/pull/149
https://github.com/filecoin-project/venus-docs/pull/146
https://github.com/filecoin-project/venus-docs/pull/144
https://github.com/filecoin-project/venus-docs/pull/141
https://github.com/filecoin-project/venus-docs/pull/140
https://github.com/filecoin-project/venus-docs/pull/136
https://github.com/filecoin-project/venus-docs/pull/134
https://github.com/filecoin-project/venus-docs/pull/131
https://github.com/filecoin-project/venus-docs/pull/127
https://github.com/filecoin-project/venus-docs/pull/124
https://github.com/filecoin-project/venus-docs/pull/122
https://github.com/filecoin-project/venus-docs/pull/121
https://github.com/filecoin-project/venus-docs/pull/118
https://github.com/filecoin-project/venus-docs/pull/117
https://github.com/filecoin-project/venus-docs/pull/115
https://github.com/filecoin-project/venus-docs/pull/113
https://github.com/filecoin-project/venus-docs/pull/112
https://github.com/filecoin-project/venus-docs/pull/111
https://github.com/filecoin-project/venus-docs/pull/110
https://github.com/filecoin-project/venus-docs/pull/59

- Major contributor to [venus-docs](venus.filecoin.io)
- Major contributor to [Venus online meetups](https://www.youtube.com/watch?v=th8QJGFcNH8)
- Core member of Storage Provider Working Group; Maintainer of [SPWG-CN](https://github.com/stuberman/MWG/tree/main/mwg-aisa)
- Contributor to [FIP](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md)
- Volunteer of ProtoSchool

https://github.com/filecoin-project/venus/issues/4824
https://github.com/filecoin-project/venus/issues/4820
https://github.com/filecoin-project/venus/issues/4819
https://github.com/filecoin-project/venus/issues/4818
https://github.com/filecoin-project/venus/issues/4800
https://github.com/filecoin-project/venus/issues/4794
https://github.com/filecoin-project/venus/issues/4793
https://github.com/filecoin-project/venus/issues/4792
https://github.com/filecoin-project/venus/issues/4790
https://github.com/filecoin-project/venus/issues/4775
https://github.com/filecoin-project/venus/issues/4774
https://github.com/filecoin-project/venus/issues/4760
https://github.com/filecoin-project/venus/issues/4759
https://github.com/filecoin-project/venus/issues/4758
https://github.com/filecoin-project/venus/issues/4757
https://github.com/filecoin-project/venus/issues/4752
https://github.com/filecoin-project/venus/issues/4745
https://github.com/filecoin-project/venus/issues/4744
https://github.com/filecoin-project/venus/issues/4743
https://github.com/filecoin-project/venus/issues/4742
https://github.com/filecoin-project/venus/issues/4741
https://github.com/filecoin-project/venus/issues/4728
https://github.com/filecoin-project/venus/issues/4727
https://github.com/filecoin-project/venus/issues/4726
https://github.com/filecoin-project/venus/issues/4725
https://github.com/filecoin-project/venus/issues/4724
https://github.com/filecoin-project/venus/issues/4723
https://github.com/filecoin-project/venus/issues/4722
https://github.com/filecoin-project/venus/issues/4721
https://github.com/filecoin-project/venus/issues/4720
https://github.com/filecoin-project/venus/issues/4719
https://github.com/filecoin-project/venus/issues/4718
https://github.com/filecoin-project/venus/issues/4701
https://github.com/filecoin-project/venus/issues/4700
https://github.com/filecoin-project/venus/issues/4699
https://github.com/filecoin-project/venus/issues/4698
https://github.com/filecoin-project/venus/issues/4684
https://github.com/filecoin-project/venus/issues/4683
https://github.com/filecoin-project/venus/issues/4682
https://github.com/filecoin-project/venus/issues/4681
https://github.com/filecoin-project/venus/issues/4680
https://github.com/filecoin-project/venus/issues/4652
https://github.com/filecoin-project/venus/issues/4651
https://github.com/filecoin-project/venus/issues/4650
https://github.com/filecoin-project/venus/issues/4649
https://github.com/filecoin-project/venus/issues/4648
https://github.com/filecoin-project/venus/issues/4647
https://github.com/filecoin-project/venus/issues/4646
https://github.com/filecoin-project/venus/issues/4645
https://github.com/filecoin-project/venus/issues/4644
https://github.com/filecoin-project/venus/issues/4643
https://github.com/filecoin-project/venus/issues/4642
https://github.com/filecoin-project/venus/issues/4618
https://github.com/filecoin-project/venus/issues/4617
https://github.com/filecoin-project/venus/issues/4616
https://github.com/filecoin-project/venus/issues/4615
https://github.com/filecoin-project/venus/issues/4614
https://github.com/filecoin-project/venus/issues/4613
https://github.com/filecoin-project/venus/issues/4612
https://github.com/filecoin-project/venus/issues/4611
https://github.com/filecoin-project/venus/issues/4610
https://github.com/filecoin-project/venus/issues/4609
https://github.com/filecoin-project/venus/issues/4607
https://github.com/filecoin-project/venus/issues/4606
https://github.com/filecoin-project/venus/issues/4347

## For Diversity and Decentralization

In addition to Scientific Data(AI training, geological data, autonomous driving), Media & Entertainment(video & music) Internet archive, we are open to new use cases if storage client could make its case.

**Comment by Kevin-FF-USA** [comment]
Hi  @Fatman13 **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Greater China.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 5-10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by Fatman13** [comment]
Hello, @Kevin-FF-USA, great to hear that! 

> 1. Please confirm that the region of operation for client applications you will focus on is Greater China.  

Confirmed!

> 2. Please confirm each of the following items below.

> Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .

Agree to abide by above operational principles. Nodes under control of Guazi Dynamic are f02731, f0694916, f01016254. We provide devOps and daily maintenance services to clients of these said nodes.

 > Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 

Agree to abide by above operational principles. @Kevin-FF-USA, is this `Some reference information can be found here` supposed to be a link?

> Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 

Agree to abide by above operational principles.

> No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

Agree to abide by above operational principles.

> Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

Agree to abide by above operational principles.

> Community Governance Participation: It is expected that you will participate in the program 5-10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 

Agree to abide by above operational principles. Will definitely attend more Governance calls. Have been directing people to #fil-plus channel and participating discussions in Slack.

 > 3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

Nodes under control of Guazi Dynamic are f02731, f0694916, f01016254. We provide devOps and daily maintenance services to clients of these said nodes. Also f3qaipvxrz2gxexc7mcvjsxifmscfiw7c7zfhrmq76j5ee4hcbvg3gbtpea7wgz72kkjcjmwzhm5uo2onxyocq for datacap application.

> 4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

Affirmed!

> 5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 

Will get back to this soon!

**Comment by Fatman13** [comment]
> please verify and confirm that you are only requesting 10TiB of total DataCap to allocate to clients.

@galen-mcandrew, sorry for the late reply. Quick question, this doesn't have to do with LDN, correct?

**Comment by galen-mcandrew** [comment]
@Fatman13 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Fatman13** [comment]
@galen-mcandrew Got it!

**Comment by Kevin-FF-USA** [comment]
Hello @Fatman13!

Just some final verification: we have your address on file as: f15ofoeeq57euuha3ig273lhkcpjhhnlbgyylqdii

And we will be communicating with fatman13 via Slack. If there are any other handles you wish to have included in notary communications, please comment them below.

**Comment by Fatman13** [comment]
@Kevin-FF-USA yes @Fatman13 will be the Slack handle to find me. We don't have additional personal for notary communication. 

> Just some final verification: we have your address on file as: f15ofoeeq57euuha3ig273lhkcpjhhnlbgyylqdii

Regarding the address, yes that is my current address for use of notary related things. One thing to note is that we ordered Nano X from Ledger about a month and half ago, but due to lockdown in Shanghai we still haven't been able to receive the package. So the address might change in future if we are not able to transfer the address to Nano X.

**Comment by galen-mcandrew** [comment]
@Fatman13 2 questions:

This 10TiB is not related to allocations made using the Large Dataset clients; that DataCap does not come from a single notaries pool. The 10TiB you are requesting here would be used to complete direct client requests, such as in [this repo](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues). **Do you only want 10TiB? I think we should at least do 100TiB**

It sounds like you do not have your ledger yet. You will need a ledger to access the tooling at plus.fil.org, which is also required for verifying your ledger address (steps [here](https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing)). We should wait to send you DataCap to another address (such as f1...qdii) because to my knowledge you will not be able to import an existing address into a ledger device. 

Please let us know when you are able to get your ledger set up! That way we can send you your DataCap and add you to the LDN multisigs.

**Comment by Fatman13** [comment]
@galen-mcandrew Hello! Sure we can handle 100TiB.

**Comment by galen-mcandrew** [comment]
@Fatman13 , No problem, we hope you are all able to stay safe and get your essentials. We understand these are difficult and unexpected times, and we are happy to work with onboarding you once the ledger arrives. In the meantime, we hope you can still help us review and audit clients, such as large dataset requests; as well as joining governance calls and the discussions there. Thanks!

**Comment by Fatman13** [comment]
Hello, @galen-mcandrew @Kevin-FF-USA, finally got my Nano S+ shipped to me after the lockdown is lifted in Shanghai. I just initiated a new address using filecoin app on Ledger Nano. 

f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy

Please use the above for my notary address. Thank you!

**Comment by Fatman13** [comment]
Hello, @galen-mcandrew @Kevin-FF-USA, please let me know if I can proceed to verify on https://plus.fil.org/

**Comment by Fatman13** [comment]
Hello, team, any news on if we can proceed to verify yet? @galen-mcandrew @Kevin-FF-USA

**Comment by Fatman13** [comment]
Hello, team, any update on the verification?

**Comment by Fatman13** [comment]
Address verified! @Kevin-FF-USA

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Datacap Allocated
> 100TiB

**Comment by galen-mcandrew** [comment]
This address will also need to be added to the v3 msig, https://filfox.info/en/address/f01858410, https://github.com/filecoin-project/notary-governance/issues/509

Governance team can approve this change, and RKH will approve the 100TiB for direct allocations.

**Comment by Fatman13** [comment]
Hello, team, @galen-mcandrew @Kevin-FF-USA 

On my notary dashboard, everything is still greyed out which preventing me from signing anything. Could anyone please kindly to take a look? Thank you in advance!

**Comment by Fatman13** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedfk5ywufnijz2suj5aw4hodr4grwojvpqtshuzmhzjtzi2cwk6da
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfk5ywufnijz2suj5aw4hodr4grwojvpqtshuzmhzjtzi2cwk6da
