### ISSUE TITLE
Discussion: Rubric: Geographic Distribution to Power Distribution

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/notary-governance#425]
## Abstract

Change `Geographic Distribution` in Rubric to `Power Distribution`.

## Motivation

Given the unstable nature of intercontinental online data transfer, `Geographic Distribution` doesn't make practical sense in being a rubric for a notary as there won't be enough regional storage power to use the datacap granted. If the goal is to push for more datacap usage, then use power distribution based on geo location (replacing `Geographic Distribution`) is much better suited to that end. The more power concentrated in one geo location the more potential datacap approved can be used by said regional power. 

Besides, dispersing storage power around the globe should be an effort by the community based on free market behavior (like how BTC mining is dispersed around world by economic incentives), not a target for filecoin plus.

## Design 

Proposed design as following...

| Category | Combination Logic | L1 | L2 | L3 | L4 | L5 | 
|-|-|-|-|-|-|-|
|Power Distribution||Located in region represents 10% of network power|Located in region represents 30% of network power|Located in region represents 50% of network power|Located in region represents 70% of network power|Located in region represents 90% of network power|

**Comment by dkkapur** [comment]
Recording of Mar 08 Governance Call, where this was discussed: https://www.youtube.com/watch?v=CVoZx666HYE. 

Notes from the discussion: 
- this could disincentivize distribution of DataCap to regions that are underserved, resulting in making it harder to get network productivity and business development in regions with currently low demand 
- LDNs are not restricted by region at the moment, so large-scale clients in overserved regions like China/NA are not blocked
- DataCap is a client-side resource, and clients may be interested in distributing deals across different regions; as a result, tying DataCap availability to current power distribution does not make sense, and our priority should be to ensure clients have a good user experience
- similar to above point: network power and Fil+ are on different dimensions of network productivity

Proposed next steps (my opinion, please feel free to disagree):
- Geo distribution as a notary selection logic needs to be tweaked, especially with continued focus on LDN
- this proposal is likely not the way we should proceed in the near term, but can be a starting point for discussion for the following election cycle

**Comment by dkkapur** [comment]
Closing this one out for now based on the points flagged above and in the past few governance calls.
