### ISSUE TITLE
Notary Application: Tim Guo@Force Web3 Community

### ISSUE THREAD

**Issue by TimGuo7** [filecoin-project/notary-governance#426]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [[here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview)](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information

- Name: Tim Guo (柏礼）
- Affiliated organization: Force Web3 Community
- On-chain address to be notarized (recommend using a new address): 
- Region of Operation: Asia minus GCN
- Use case(s) to be supported: General, Media & Entertainment, User Content. 
- DataCap requested for allocation (10TiB - 10 PiB): 100TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment

Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

```
I've been working with memory storage over the past 10 years, previously working at Micron Technology Singapore(7 years) as an engineer kept focusing on bringing memory solutions to the worldwide market and 2 years ago joined the Force Community as a brand lead. I've been focused to push and encourage the development of IPFS/Filecoin ecosystem through content creation, events organised and report written, and have witnessed the rapid development of Filecoin from the devnet to SpacRace and Mainnet and now to a 15EiB. 

More than 100+ events have been successfully held with my focus on the decentralised storage network, such as SpaceRace One Year Anniversary and Filecoin Mainnet One Year Anniversary, with more meetups and events held regularly every Tuesday with focus on IPFS/Filecoin. 

Other than events and meetups held, I've led projects like Filecoin Annual Report which has recorded the huge progress of Filecoin after the mainnet launch and Space Race I report which recorded the huge milestone that pushed the Mainnet Launch. And now i am leading the team for a Web3 Infinity Hackathon organized by Force Community. 

I am also one of the Filecoin builders as I've been working with Filscan chain explorer, to utilise the UI and initiated more data coverage of the whole network. 

Links 
Github: https://github.com/TimGuo7 
Linkedin: https://www.linkedin.com/in/jinhaoguo/
Events organized: https://www.huodongxing.com/org/250766031931
Reports- Filecoin Annual Report https://mp.weixin.qq.com/s/8aKm91W-XoLeRPb-l9dVXg 
Reports- Space Race I Report tracked about 416 nodes:https://www.webxlab.net/article/detail/LNglaNKwBa
Filscan chain explorer: filscan.io      
```

### Stake Exposure

Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

```
personally, I hold hundreds of fils in the network.
```

### In-protocol Reputation

Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

```
Organized hundreds of events like force community meetups(online and offline)https://www.huodongxing.com/org/250766031931

Filecoin One Year Anniversary Summit: https://www.eventbrite.com/e/filecoin-mainnet-one-year-anniversary-cloud-summit-tickets-190974238087?keep_tld=1#

Blockchain City Tour with IPFS/Filecoin: https://mp.weixin.qq.com/s/4-3YcsXepHH5ul7gd2Oh8w

Decentralized Storage related summit: https://mp.weixin.qq.com/s/KdnPKnD3FzTwyu_feA2-Zg 

Dev/Explorers-Filscan https://www.youtube.com/watch?v=f2sk2WqrIjs 

Reports wrote: https://mp.weixin.qq.com/s/8aKm91W-XoLeRPb-l9dVXg

Speeches gave about Filecoin in the conferences: 
https://www.shilian.com/kuangye/463512.html    
https://www.asiaott.net/h/183385#:~:text=柏礼表示，分布式存储可以引领未来%E3%80%82,分布式存储将会更加安全、可信，更为经济，并且真正推动从IT时代到DT时代的发展路径%E3%80%82%20在众多分布式存储项目中，又为何选中了Filecoin？
```

### In-protocol Security

Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 

```
N/A, contributions about implementations: https://github.com/TimGuo7
```

### Organizational Reputation

Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

```
Force Community is a non-profit leading Web3 community. We do believe in the strength of blockchain, which can empower the next generation of the Internet. Here you can get the latest updates about the development of the Web3 ecosystem, and with our years of experience within the blockchain industry, we encourage and support people to build around Web3, the Next Big Thing!
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

```
Website: https://forcecommunity.io/
Twitter: https://twitter.com/force_ipfs
Medium: https://forcecommunity-official.medium.com
Evenbrite: https://www.eventbrite.hk/o/force-web3-community-36225766643
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

```
https://www.mytokencap.com/news/145380.html
https://www.shangyexinzhi.com/article/4128123.html
```

### Individual Reputation

Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.

```
Github: https://github.com/TimGuo7 
Twitter: https://twitter.com/TimGuo27471869
Linkedin: https://www.linkedin.com/in/jinhaoguo/
https://www.shilian.com/kuangye/463512.html    
https://www.asiaott.net/h/183385#:~:text=柏礼表示，分布式存储可以引领未来%E3%80%82,分布式存储将会更加安全、可信，更为经济，并且真正推动从IT时代到DT时代的发展路径%E3%80%82%20在众多分布式存储项目中，又为何选中了Filecoin？

```

### Use Case Diversity

(Optional) Any additional information you'd like to share about the use case(s) you plan to support?

```
General stuff like entertainment and media will be more suitable for me, but open for general stuff too. 
```

# Allocation Plan

### Allocation Strategy

How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.

```
I will try my best to be fair and allocate the datacap to the clients. I will ask questions for clients not limited to below: 

1. Introduction of yourself/ your organization(with links)
2. Use case
3. Location
4. Max DataCap Allocation
5. Filecoin address
6. Miners you intend to allocate DataCap with allocation proportion
7. Specific requirement of miners and storage service
8. For-profit or not

I tend to allocate more to non-profit organizations who request datacap from me and use it to store valuable info. like historical data, health and medical data alike. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
There are numerous ways to ensure this, for example to use multi-sig wallet to allocate to more clients and with filecoin supported wallet to verify the accounts associated with the Datacap allocation.
```

### Client Due Diligence

How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 

```
All clients have to go through a strict process to be qualified in the early stage. Firstly, I need to collect information including:  
1. Entity Information
 - Formation documents: includes certificates of registration/incorporation/information
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory's authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary's certificate, a signed letter from the applicant's CFO, or may be included in the company operating agreement); 
 - close-up photo of the signatory's face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners
If there are any 25%+ shareholders, we need a document, such as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
	 - legal name;
	 - date of birth; 
	 - street address (P.O. box number is not acceptable); 
	 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 	- a copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

With this provided information, an interview and data source checking process need to go through. After that, an agreement should be signed for the next step: gradually allocate DataCap and let the client gather more credit. 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.

```
Do check and inspections regualrly (weekly or bi-weekly);
check all the deals reguarly through useful tools developed by filswan, bytebase and filedrive team. 
```

### Bookkeeping Plan

Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 

```
Github Repo and open to the public 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?

```
GitHub will be the place to conduct all the requirements, changes and fixes regarding allocation
```

### Engagement in Program

How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.

```
I can commit at least 10 hrs per weeek to process all the allocations in a time manner 
```

### Past allocation 

Have you previously received DataCap to allocate before? If so, please link to any previous applications.

```
N/A
```

Cumulatively, how much DataCap have you previously successfully allocated? 

```
N/A
```

**Comment by galen-mcandrew** [comment]
[Force Web3 - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320873/Force.Web3.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by TimGuo7** [comment]
Hi @galen-mcandrew, thanks for the feedback, here modified a bit about the allocation strategy. 

For allocation strategy, other than above, i will also check these methods before make any allocation. 

For new clients, online and offline surveys will be conducted as much as possible to determine whether they are qualified to become verified clients.
-Browse the company / personal information and websites provided by them, and query the authenticity of the information from relevant government websites.
-Confirm the applicant's use case and storage plan through questions.
-For verifiable clients, historical reputation is equally important. Each allocation will be regarded as an evaluation of client reputation, including score accumulation and corresponding trust, to determine the upper limit of the data they will receive.

For the amount of Datacap that i am going to allocate, i will started with 1TiB first for requesters with lower reputation, then followed by 2-5TiB  and 5 TiB and more for those who have proved themselves in the network. 

By the way, I request for a reconsideration of scores goes with organizational reputation and personal reputation, thanks.

**Comment by TimGuo7** [comment]
Hi @galen-mcandrew 
for organizational reputation, Force Community has successfully become one of the Spaceship of the Filecoin [Orbit Community ](https://filecoin.io/blog/posts/orbit-community-program/#:~:text=The%20Orbit%20Community%20Program%20follows%20the%20Filecoin%20Orbit,events%20exploring%20and%20celebrating%20the%20potential%20of%20web3.)program, and we will continue to support the development of Filecoin Community as an organization. 
![image](https://user-images.githubusercontent.com/94029052/159676940-942bea65-8eef-44a1-bcce-9fb64fc9d082.png)

Followed by that, we have a schedule for this year and will bring web3 developers, newcomers to the Filecoin community with events, books and reports.

**Comment by galen-mcandrew** [comment]
[Tim Guo - UPDATED - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8373141/Tim.Guo.-.UPDATED.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by TimGuo7** [comment]
> Hi @TimGuo7 **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.
> 
> In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:
> 
> 1. Please confirm that the region of operation for client applications you will focus on is Asia minus GCN.

**Confirm**
> 2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).        
>    •	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship    .

**Confirm**
>    •	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.    

**Confirm**
>    •	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.    

**Confirm** 
>    •	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.    

**Confirm**
>    •	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.    

**Confirm**
>    •	Community Governance Participation: It is expected that you will participate in the program 10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.

**Yes, Confirm**
> 3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

**NA**
> 4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

**Confirm**
> 5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.    

**Confirm**
>    •	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: [https://shop.ledger.com/pages/ledger-nano-x)    ](https://shop.ledger.com/pages/ledger-nano-x)%E2%80%A8)

**Noted with many thanks**

**Comment by galen-mcandrew** [comment]
@TimGuo7 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @TimGuo7!

Really appreciate you filling out the acknowledgments for the Notary kickoff in this ticket. There is some additional information needed in order to finalize, **can you please follow this link to complete?**
[Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)

**Comment by TimGuo7** [comment]
@Kevin-FF-USA Thanks Kevin for the reminder, I need work out my on-chain address first, wanna generate one with Nano wallet.

**Comment by TimGuo7** [comment]
Yes, submitted, thanks @Kevin-FF-USA

**Comment by Kevin-FF-USA** [comment]
Got your submission, thank you very much!

**Comment by Kevin-FF-USA** [comment]
Hello @TimGuo7!

Thank you, we will be communicating with Tim Guo（柏礼）on Slack.

**Comment by galen-mcandrew** [comment]
Please confirm your ledger address using the verification tool in the [Fil+ Registry app](https://plus.fil.org/).

[Here](https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing) is a troubleshooting guide.

Thanks!

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1mxtcba3l5qnzkh2wjmnynnrrht35bya6ec53pnq
#### Datacap Allocated
> 100TiB

**Comment by TimGuo7** [comment]
Hello @Kevin-FF-USA @galen-mcandrew  
Finally I got my Ledger delivered to me, could you help me to replace the on-chain address as below:
**f1yslbnnqzrjlyuxsmyxfbqcc7xthcavgpripjevi** 
I will use this address for the notary work, sorry for the inconvenience.

**Comment by TimGuo7** [comment]
Hi @Kevin-FF-USA @galen-mcandrew  Could you help to take a look of my current status for the next move?
Thank you.
