### ISSUE TITLE
Next Governance Call: Tues Mar 08 8am PT / 4pm UTC -and- 4pm PT / 12am UTC

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#427]
The fifth Notary Governance Call of 2022 will take place on Mar 08 at 8am PT // 4pm UTC AND 4pm PT // 12am UTC (Mar 09th depending on time zones)

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:
Notary Election Application Questions
Notary Election Scoring Questions
FIP 28 + Removal of Datacap
Community discussion 

If you would like to add an item to the agenda, please comment in this issue.

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles

**Comment by Kevin-FF-USA** [comment]
Item for Agenda: 
https://github.com/filecoin-project/notary-governance/issues/428

**Comment by Kevin-FF-USA** [comment]
Item for Agenda:
https://github.com/filecoin-project/notary-governance/issues/425

**Comment by scharfstein** [comment]
DataCap App / large data sets #274

pls add to agenda. thanks

**Comment by dkkapur** [comment]
@pooja - just to confirm, you'll be joining the afternoon session to discuss DGM (https://www.dgm.xyz/grants/kWQa2elNDgkVI24GvyGy)?

**Comment by Kevin-FF-USA** [comment]
@scharfstein  - Confirming this issue https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/274

**Comment by pooja** [comment]
Yes I'll join!

**Comment by Kevin-FF-USA** [comment]
Link to recordings: https://youtu.be/CVoZx666HYE
