### ISSUE TITLE
STCloud

### ISSUE THREAD

**Issue by bary321** [filecoin-project/notary-governance#429]
### Notary Application
To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/issues/429#overview) and then fill out the following form.

## Core Information
- Name: Barry
- Affiliated organization: STCloud
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address): f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
- Region of Operation: [Greater China]
- Use case(s) to be supported: Individual user storage, enterprise user storage, public project storage, scientific data sets, video and music
- DataCap requested for allocation (10TiB - 10 PiB): 1PiB

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects, or contributions (with links).
```
It has been 7 years since we have been deeply involved with IPFS and Filecoin. 
Since 2015, our team has been following and propagating IPFS.
In October 2017, in order to better promote IPFS and Filecoin in China, we established the IPFS China Community (ipfs.cn). So far, it has more than 100,000 fans.
From 2017 to 2021 based on the original intention of "Propagating for IPFS and Voice for Filecoin", our team successively conducted IPFS and Filecoin themed promoted sermons in Shenzhen, Guangzhou, Beijing, Hangzhou, Hefei, Changsha, Wuhan and so on. 
In 2020, our team actively participated in Filecoin testnet and achieved superior results in Space Race 1 and Space Race 2.
On October 15, 2020, Filecoin mainnet was officially launched. Our node have been operated and maintained smoothly so far, and miner ID: f0688165 has been ranked No. 1 in the Adjusted Power rankings. Also, we provide mining technical support for the mining pools FILPool.me and BPool.io, which is serving Filecoin investors.
Our team has been deeply involved in the storage industry for more than 12 years. We have rich experience in data storage, cluster architecture construction and emergency handling. The storage products we have developed have now cooperated with the multinational giant-China Unicom and served nearly one million people.
We not only have advantages in storage technology, but also are committed to developing the ecological construction of IPFS and Filecoin. To help fans understand IPFS & Filecoin faster, we have created the IPFS China Community (ipfs.cn). In order to help teams with ideas to develop the ecology, we have established the IPFS Ecological Fund for investing in applications that are beneficial to the ecology. According to the economic model of filecoin, in order to increase the liquidity of filecoin, we participated in the investment and incubation of the Defil platform.
Links：
STCloud Official Website: https://yunos.io/
IPFS China Community：http://ipfs.cn Or http://cipfs.io/ ;
Telegram: https://t.me/ipfscn2018
Miner ID: f0688165/f0127595
FILPool: https://filpool.me/
BPool: https://bpool.io/
Promotional activities: 
https://drive.google.com/file/d/1xQDkNcckyinYfkLuOCWF2med4dTfAHzR/view?usp=sharing
https://v.qq.com/x/page/s3219a9ooi1.html
Interview: 
https://v.qq.com/x/page/j3017ziwzri.html
https://v.qq.com/x/page/t3219mnjjvt.html
```
### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Total：5,321,670.52 FIL
Currently Available：61,608.25 FIL
Initial Pledge: 4,430,938.85 FIL
Locked Rewards: 828,214.21 FIL
The above data are from the blockchain browser: FILFOX. The miner ID used for statistics is the ID published on the official websites of FILPool and BPool.
Miner ID: f084135; f0688165; f0128559; f02770; f02775; f02767; f073525; f0127595; f0724216; f02769
Website:
FILFOX: https://filfox.info/en
FILPool: https://filpool.me/
BPool: https://bpool.io/
```
### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
1. For enthusiasts to understand IPFS & Filecoin faster and better, create an IPFS Chinese community: http://cipfs.io/.
2. Many community ama has been held in the community to help users better understand its ecology, such as FLow, Polygon, Chainlink, Near, Mask Network, FILSwan, etc.
https://t.me/ipfscn2018
https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzkyMDIyMTY3Ng==&scene=124&uin=&key=&devicetype=Windows+10+x64&version=6302019c&lang=zh_CN&a8scene=7&fontgear=2
3. Increase liquidity for Filecoin, invest and incubate DEFIL platform: https://defil.org/#/home
4. In order to incubate its ecological development and provide financial support, the IPFS&Filecoin ecological fund was established:  http://dongxicaijing.com/portal.php?mod=view&aid=928
4. Investment incubation filecoin wallet: Filwallet.io
```
### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Our team have discovered some errors in the past two years and actively submitted feedback.
Such as:
WindowPost not submitted, but the power was not drop:
https://github.com/filecoin-project/lotus/issues/1812
Synchronous abnormal:
https://github.com/filecoin-project/lotus/issues/1833
The expiration of a user order can cause a contract error:
https://github.com/filecoin-project/lotus/issues/1929
Uneven distribution of sectors in the deadline in windowPost:
https://github.com/filecoin-project/lotus/issues/1813
In addition, our team participated in two chain maintenance and assisted the PL to perform multiple upgrades, and we assist the official to solve the following problems in the slack private channel:
1. User order blocking problem
2. Gas fees in the test network skyrocket 
```
### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
STCloud is headquartered in Shenzhen, China. STCloud is a high-tech company focusing on the research and development of distributed storage, distributed computing, and distributed database technology. It invests in and incubates sub-brands such as "IPFS China Community", "FILPool Mining Pool", and "Spider Mining Machine". Filecoin mining machine research and development, mine construction, mining pool development, IPFS ecological investment incubation, distributed network technology research and development, etc., ST cloud committed to becoming the next generation of distributed network operators.
-Registration Country: China
-Organization size: 100+
-Time since establishment: 2018
```
Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
STCloud Official Website: https://yunos.io/
IPFS China Community：http://ipfs.cn Or http://cipfs.io/ ;
Telegram: https://t.me/ipfscn2018
```
Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Interview: 
https://v.qq.com/x/page/j3017ziwzri.html
https://v.qq.com/x/page/t3219mnjjvt.html
```
### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter: @cn_ipfs, 127 followers
WeChat Oifficial Account: 时空云, 8000 subscribers 
Slack: @Barry
```
### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
We plan to support all use cases that comply with the law.
```
To be more specific, I will set a specific ratio based on the actual situation and the development of the network, and I will also refer to Filecoin Discover, such as:
1. User content (individual user storage)
2. Scientific data (artificial intelligence training, geological data, autonomous driving)
3. Media and Entertainment (Video and Music)
4. Historical data (weather, books)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
First of all, the allocation requirement is planned to be divided into 5 categories from L1-L5 by the data volume. The larger data volume clients request, the more strict requirements will be. We want to inspect these clients by reputation, data, diversity and decentralization, allocation strategies, track record, etc.
We will consider the following factors while allocation the DataCap:
1. Reputation of the organization
2. Use cases diversity
3. Scale&Frequency of allocation
4. Safety Precautions
5. Transparency of customers
6. The relationship between customer and miner
In addition, we will also conduct offline investigations to understand their true identity, work content, reputation, etc., and how they use Filecoin for storage. We even plan to conduct a comprehensive review and evaluation of customers reputation every three months, and Reserve the right to adjust the customer's quota to ensure that the share can be fully allocated to the greatest extent.
Customers are rated through the above methods and the quota is allocated as follows:
L1-50 GiB
L2-500 GiB
L3-1 TiB
L4-5 TiB
L5-10TiB
```
How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will do a detailed due diligence on the clients who apply for datacap and the judgement criteria are listed in the table above. I will score clients' situation and determine whether or not to allocate datacap to them and how many according to the score. For me, every client is equal so that everyone can apply for the DataCap and their demands will be approved once they are qualified. If they are not qualified, then they can not get the DataCap but I will give them some suggestions. After all, we still hope that more people can join the filelcoin ecosystem, and hope that the system restrictions or cold rules will not inhibit people's enthusiasm for Filecoin.
```
### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Generally, the higher the DataCap threshold, the greater the limit for client review. In the early stages, all customers must go through a rigorous process to qualify. First, we will collect relevant information about customers.
1. Entity Information
1.1 Formation documents , this includes certificates of registration/incorporation/information; 
1.2 government-issued identification number for the entity
2. Authorized Signatory Information
2.1 evidence of the authorized signatory’s authority to act on behalf of the application entity 
2.2 Sign and press fingerprints (official seal and corporate seal are required)
2.3 ID card and a photo of the individual and ID card to prove it is the person;
3. Company operation direction and turnover
3.1 Company goals, company's main business
3.2 Annual turnover in the last two years
```
What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. The number of miners allocated to the datacap of each level of customer from L1 to L5 is required.
2. Set up customer tracking records to prevent customers from making wrong assignments.
3. Regularly check and audit the usage of DataCap.
4. Use incentives: encourage customers to report unfair distribution and listen to the voices from the community.
According to the amount obtained by the customer, we require the customer to decentralize the allocation of DataCap. For example, the L1 level can be allocated to only one miner, but the L5 level must be allocated to at least 5 miners, because the more dispersed the DataCap, the more beneficial it is to reduce the potential The possibility of misuse is also conducive to a more decentralized network and reduce the possibility of centralized power.
```
### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we will keep detailed records for review requests, and the records will be published on Github.
In addition, we allow the community to provide different opinions and report, and there will be a 14 working day publicity period for DataCap customer allocation. If there is a dispute, we will consider holding a hearing to make another decision.
```
Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Github.
```
### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
4-6 hours per week.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.
```
Cumulatively, how much DataCap have you previously successfully allocated? 
```
None.
```

**Comment by galen-mcandrew** [comment]
[STCloud - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320921/STCloud.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by bary321** [comment]
@galen-mcandrew
Hello, Gallen. 
Regarding the question you mentioned in your scorecard: is there any relationship to the IPFS Metaverse Community.
STCloud is one of the investors in the IPFS Metaverse Community. We have been committed to letting more people know about IPFS and Filecoin, delivering the latest news, and sharing ecological development. At the same time, we also support the development of projects which is related to IPFS and Filecoin. We have great expectations for the future of ipfs, filecoin, metaverse, and web 3.0. To this end, we have established relevant committees to search, evaluate and support the development of related projects.
Thanks to your team for the evaluation. Have a good day.

**Comment by bary321** [comment]
In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:
1.Please confirm that the region of operation for client applications you will focus on is Greater China.  
-Confirmed.
2.Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  
• Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
-Confirmed.
• Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
-Confirmed.
• Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
-Confirmed.
• No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
-Confirmed.
• Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
-Confirmed.
• Community Governance Participation: It is expected that you will participate in the program 4-6 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.  
-Confirmed.
3.Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  
f084135; f0688165; f0128559; f02770; f02775; f02767; f073525; f0127595; f0724216; f02769
4.Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  
-Confirmed.
5.(If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
f3quxrlpczk5brdiese3zcmdn2malpy3cop2zcl2wqpg6wh2rzb7jynoj6e6ljwnv2e543j5dupn6ftjnlarfa

• If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: [https://shop.ledger.com/pages/ledger-nano-x) ](https://shop.ledger.com/pages/ledger-nano-x)%E2%80%A8)
       Thanks for your advice.

**Comment by galen-mcandrew** [comment]
@bary321 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by bary321** [comment]
Hi, Kevin and Galen，Thank you very much for your support. I resubmitted the link information. In the latest link information, I applied to change the notary's address to
“f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci”

The previous 
"f3quxrlpczk5brdiese3zcmdn2malpy3cop2zcl2wqpg6wh2rzb7jynoj6e6ljwnv2e543j5dupn6ftjnlarfa" is invalid.
I hope you can check it.

**Comment by fabriziogianni7** [comment]
I updated the parent comment with the new address. this is probably the reason for this notary ledger not to have been verified.
cc @dkkapur @galen-mcandrew

**Comment by 1LISA2** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecroo5uogaegj7nf3h5l2fdbq5dszaiyvh6cybmq2svjgalgtmtba
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecroo5uogaegj7nf3h5l2fdbq5dszaiyvh6cybmq2svjgalgtmtba

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Datacap Allocated
> 1PiB

**Comment by 1LISA2** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacechepbabvrpy3jmcevwidjxahh4r5jrbi466hsn3zvwlsnzssuvsu
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechepbabvrpy3jmcevwidjxahh4r5jrbi466hsn3zvwlsnzssuvsu

**Comment by 1LISA2** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedt4nfs3fz6nofkpeqz3gmqe2puwoegolbz62qu5nqibahlgz3hem
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedt4nfs3fz6nofkpeqz3gmqe2puwoegolbz62qu5nqibahlgz3hem

**Comment by 1LISA2** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceakjnf4fl2essbwlkejctj37gflinieb4w3rdtsxskxrdieiwjc7s
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceakjnf4fl2essbwlkejctj37gflinieb4w3rdtsxskxrdieiwjc7s

**Comment by 1LISA2** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedk6mccpehvkxbvuwl6mv3mkniawnrtdstlzzs7rqki5cikueao7q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedk6mccpehvkxbvuwl6mv3mkniawnrtdstlzzs7rqki5cikueao7q

**Comment by stcouldlisa** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacea4ax5sawvmh3jj2qnmulew2qkydmjiqtt5puj72rgspkcrjmykzs
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4ax5sawvmh3jj2qnmulew2qkydmjiqtt5puj72rgspkcrjmykzs

**Comment by dkkapur** [comment]
Notary address verified. Closing this issue for now.
