### ISSUE TITLE
Modification: Notary Rubric / Application Process - Tiebreaking

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/notary-governance#43]
## Issue Description
In case the number of Notary Applications received for a given region of operation exceeds the number of entities that will be granted notary status in a particular round of selection, we don't have a clear and objective way in tiebreaking between entities that have the same score on the rubric. 

## Impact
In order to make the best decisions in notary selection for the Filecoin Community, we should have a clear set of agreed upon criteria by which we select between entities that score the same on the Notary Rubric. 

## Proposed Solution(s)

There are a few different ways in which we can do this. The initial proposal is the following -  

The current formula uses a `MIN(ROUND(...` - just using the unrounded calculated score could serve as a tiebreaker since the additional significant figures will help disambiguate between applicants with the same score

Additional options include: 
- Using the raw score sum across all rows on the rubric
- Introduce new formula to calculate a "Notary Score" that takes into account additional weighting for reputation, quality of allocation plan, or other factors we agree to prioritize at a particular point in time, etc. 
- Attribute bonus points for tooling that will be open sourced for other entities in the Filecoin Plus ecosystem, or other similar contributions
- Attribute bonus points for strong commitment shown towards promoting diversity and decentralization in allocation plan

Let's use this issue to discuss these options / consider other alternatives.

**Comment by jnthnvctr** [comment]
I think the "unrounded" scoring of application (considering the Notary and Allocation strategy) seems like a reasonable starting metric. We can included this easily as a part of the scoring. 

And if we still have a tie after that, perhaps we look at what use cases are being supported, what teams are committing to build / supply to the ecosystem - and perhaps can agree based on contributions that a prospective Notary is willing to commit to building / open sourcing in their tenure, and based on the potential contributions break a tie off of that.
