### ISSUE TITLE
Notary Application: West Labs Venture

### ISSUE THREAD

**Issue by westlabsventure** [filecoin-project/notary-governance#430]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
-Name: West Labs Venture
-Affiliated Organization: West Capital Group Limited
-Website / Social Media: http://westlabs.io /twitter:WestLabsVenture
-On-chain Address to be Notarized: f1b5wse72uiusm4n2waqx4vuvsnvadz4ltcfruksa
-Region of Operation: Oceania
-Use case(s) to be supported: General
-DataCap Requested: 100TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
WestLabs is a venture capital company that focusing on blockchain technology and infrastructure incubation since 2021. We are one of the leading crypto funds that invest in Web 3.0 projects that in the area of NFTs, Gamefi, DeFi and Metaverse. Our Filecoin Infrastructure Fund started with $25 million in funding to incentivize storage providers (or miners) to build on the network. We have operations in APEC region(Australia, Hong Kong and Singapore).
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Prefer not to disclose.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
N.a.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N.a.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Organization: West Capital Group Limited
Nature:  private company
Registration Country: Cayman Islands
Established: 02 November, 2021
Size: over 20 employees
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
WestLabsVenture
Homepage: https://westlabs.io/
Twitter: @WestLabsVenture

Investor Relation Director:
Mia 	
Linkedin : https://www.linkedin.com/injobs/in/mia-deng-3052b4233
Twitter：@dengmiamia
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
WestLabs is a Venture Capital focusing on blockchain technology and infrastructure incubation.
Westlabs believes that Filecoin is the future of cloud storage, and therefore, proposed the Filecoin Fund. The Filecoin Fund has invested over $10 million in funding to incentivize storage providers (or miners) to build the infrastructure layer of Web 3.0. 
Details in our Web 3.0 investment portfolio can be seen at link below: https://mobile.twitter.com/WestLabsVenture/status/1494128416924127235

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
N.a.
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We plan to support user cases in Dapp, Storage Infrastructure, NFTs etc.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Here is our allocation process:
1.We will verify customers into two categories: Existing customers and New Customers
2.For existing customers, we need to check if there is any violation of international and local laws, filecoin’s standards and ethics. For new customers, we will go through a specific KYC for individual clients or corporate clients.
3. After the KYC and client identify verification, the client who apply for the DataCap will go through a scoring process based on their applications and evidence as below: https://docs.google.com/spreadsheets/d/1DBRygcUpdGMnhRq3mSgOkyKjyd9MyuTPnJj86WvMUwg/edit?usp=sharing
4. The final sore will be given based on the Client Identity, Diversity, Decentralization, Allocation Strategy. For each sector we give a score, eventually, the total score will be fit into a DataCap table to give the final granted amount of DataCap.
5. The granted amount of DataCap will be confirmed and verified with remaining DataCap, then the granted amount will be allocated to client.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will use hardware wallet to store the keys for DataCap address.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 
In the early stage, all clients are required for an onboarding process to be qualified. 
Firstly, I need to collect information including:  
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information. 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name.
 - street address (P.O. box number is not acceptable). 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence. 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 
 With these provide, an interview and data source checking process need to go through. After that, an agreement should be signed for the next step - gradually allocate datacap and let the client gather more credit. 

The questions will cover the following areas that to ensure the DataCaps are properly allocated:

1.Introduction of yourself/ your organization (with links);
2.Use case examples and scope;
3.Geographic location of the client;
4.DataCap Allocation Requests Amount;
5.Filecoin On-Chain Address;
6.Declaration of Copy rights and Legal Compliance Requirements;
7.Specific requirement of miners and storage service
Nature Of Business (Government, Public, Private, NGO)

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1.DataCap usage monitoring and auditing;
2.Trade Deal monitoring;
3.Content Monitoring. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes. We are open to any audit request from private and public channels.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Yes. We will use github repo to make allocation decisions and keep records.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
We will have one full-time employee(40 hours/ Week) responsible for communication and DataCap management. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
No.
```

**Comment by galen-mcandrew** [comment]
[West Labs - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320970/West.Labs.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi  @westlabsventure   **Congratulations! based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is the Oceania area.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program ~10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by westlabsventure** [comment]
Hi @westlabsventure Congratulations! based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.Please confirm that the region of operation for client applications you will focus on is the Oceania area.  
Confirm.

2.Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  
Confirm.

• Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
Confirm.

• Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
Confirm.

• Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
Confirm.

• No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
Confirm.

• Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
Confirm.

• Community Governance Participation: It is expected that you will participate in the program ~10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
Confirm.

3.Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  
No.

4.Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  
Confirm.

5.(If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
f1klzdpelwhffqls3xcgl6v2hmgzz5sxvxydidhaq

• If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x) 
 Thanks.

**Comment by westlabsventure** [comment]
Our team has great confidence in FIL and is particularly looking forward to
FVM's progress and is already looking for quality projects in the ecosystem
and investing in them. Let's work together.

Thank you very much.

Kevin ***@***.***>于2022年3月30日 周三上午4:58写道：

**Comment by galen-mcandrew** [comment]
@westlabsventure 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by westlabsventure** [comment]
Hi, @Kevin-FF-USA  and  @galen-mcandrew ,

Good morining.

I applied to change On-chain Address to be Notarized:

"f1b5wse72uiusm4n2waqx4vuvsnvadz4ltcfruksa"

The previous Address is invalid.

Thank you so much.

**Comment by Kevin-FF-USA** [comment]
We have received your application, thank you very much!

I have double checked and made sure we have your correct address; f1b5wse72uiusm4n2waqx4vuvsnvadz4ltcfruksa.

**The only other thing we need from you is a slack handle**, I see the link westlabsventure.slack.com, but am unable to find a specific account where I can message someone.

**Comment by westlabsventure** [comment]
@Kevin-FF-USA 
Hi~
I sent you a message  on Slack, please check ~ Thanks.

**Comment by newwebgroup** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceanh76msmarroqbpvszag5cdauvzrpcp6kcuz36ogdfxlxhw7tnoy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanh76msmarroqbpvszag5cdauvzrpcp6kcuz36ogdfxlxhw7tnoy

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1b5wse72uiusm4n2waqx4vuvsnvadz4ltcfruksa
#### Datacap Allocated
> 100TiB

**Comment by westlabsventure** [comment]
Hi there,

As I've understood it, there needs to be a new application in order to become this season's Notary. Is this the case? Is there any sort of form West Labs needs to fill out? Thank you.
