### ISSUE TITLE
Notary Application: Joss Hua - Filecoin Venus

### ISSUE THREAD

**Issue by Joss-Hua** [filecoin-project/notary-governance#431]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Joss Hua
- Affiliated organization:  Venus team @ IPFSForce
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address): f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
- Region of Operation: Greater China
- Use case(s) to be supported: User Content, Scientific Data, Media & Entertainment, Other
- DataCap requested for allocation (10TiB - 10 PiB): 100TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
I always think Filecoin is an indispensable part of the next-generation Internet in storage, which is the main reason why I have worked on Filecoin for more than three years.

Starting from practice, I began to pay attention to IPFS and Filecoin at the end of 2018. I joined the Filecoin community in early 2019. So far, I have spent all my working time in the ecosystem construction of IPFs and Filecoin, facing community members, developers, service providers, project parties, and so on.

At present, I am mainly committed to expanding the ecosystem of Filecoin service providers, users, developers, and supporters through Filecoin Venus.

More:
- GitHub handles: Joss-Hua
- Venus Miner ID: f0128788
- Slack: @Joss-Venus
- Participating in DevNet / TestNet / SR1 / SR2 / Filecoin Venus / Filecoin community contents and activities as participants of the project and operators of the community.

We contributed code to lotus, proof, etc. before 2020. 
* https://github.com/filecoin-project/lotus/pull/1571
* https://github.com/filecoin-project/lotus/issues/1930
* https://github.com/filecoin-project/lotus/issues/2183
After that, we focused on the implementation of Venus and did some important marketing work. For example, we launched the Filecoin Storage Provider Incubation Center Program and Master Fellowship program to help more small and medium-sized SPs grow and help engineers master Filecoin at a lower threshold. They are still running this year.
* https://medium.com/@filecoinfoundation/introducing-the-filecoin-storage-provider-incubation-center-ea8743e18e
* https://www.youtube.com/watch?v=Sj-lP8wwoB8&t=778s

In addition, we joined the FVM early builder, which is a big thing of Filecoin this year. We will continue to work for the early realization of the milestone of FVM.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Total stake: more than 8k FIL
Miner ID: f0128788
Substantiating evidence: https://filscan.io/address/miner?address=f0128788
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
I have always been a supporter and builder of the Filecoin ecosystem:
- Marketing articles of IPFS / Filecoin / Web3: Filecoin annual report, Web3 books, irregular;
- IPFS / Filecoin / Web3 conference host or speaker;
- Contribute relevant documents of Filecoin Venus via issue / PRS commitments;

Recently community activities:
- Venus virtual meetup: January 21, 2022, https://www.youtube.com/watch?v=M1kaNy3lqh0&list=PLvmxExuDQi1nxFrwZGtnuURKoCNbovCpw&index=2&t=1201s
- Filecoin storage provider Incubation Center: https://venus.filecoin.io/incubation/#storage-provider-incubation-center-program
- Filecoin virtual community meetup: January 21, 2022, https://www.youtube.com/watch?v=FghO20DdEgg
- New book Seminar on the 《元宇宙基石：Web3.0与分布式存储》, December 23, 2021, https://www.huoxing24.com/live/24313188
- Online Summit for the first anniversary of the launch of the main network: October 19, 2021, https://www.huoxing24.com/live/24312878
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Venus team leads the development and practice of Filecoin Venus, estabilshed in 2020, Shanghai, China.
Now we have decades of members from all over the world focus on code dev and community.
Through the core dev and ecological activities and programs, we hope (and already) to have more storage service providers, users, and enthusiasts join Filecoin or provide more contributions after joining Filecoin.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
WeChat Oifficial Account: Filecoin-Venus
Website: https://venus.filecoin.io
Github: https://github.com/filecoin-project/venus
Slack: https://filecoinproject.slack.com/archives/CEHHJNJS3
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://filecoin.io/blog/posts/welcome-venus-to-the-filecoin-mainnet/
https://www.jinse.com/lives/258069.html
https://news.huoxing24.com/flash/20210203221804593594.html
https://filecoinfoundation.medium.com/introducing-the-filecoin-storage-provider-incubation-center-ea8743e18e
https://filecoinfoundation.medium.com/venus-v1-0-0-passes-least-authority-security-audit-133cca8b5132
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Tiktok：二文说，146 Followers
Weibo: https://weibo.com/u/3115848193, 501 Followers
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Scientific Data (Weather data, artificial intelligence, life services, etc) 
Media & Entertainment (picture & video & music)
User Content (personal user storage)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and the rate at which you'll allocate DataCap.
```
Concerning the use of DataCap, it is necessary to ensure that clients correctly use DataCap to store real data because "who" and "what" are very important.

For new clients, online and offline surveys will be conducted as much as possible to determine whether they are qualified to become verified clients.
-Browse the company / personal information and websites provided by them, and query the authenticity of the information from relevant government websites.
-Confirm the applicant's use case and storage plan through questions.
-For verifiable clients, historical reputation is equally important. Each allocation will be regarded as an evaluation of client reputation, including score accumulation and corresponding trust, to determine the upper limit of the data they will receive.

If the client successfully applies for DataCap and correctly stores the real data, the client can apply for more DataCaps here in the future.

Here you can see my detailed strategy for DataCap allocation, with the minimum limit being 1GiB and the maximum limit being 10TiB.
https://docs.google.com/spreadsheets/d/1aAdDnAJurRjy7_Git-mbDky5Egd5ZA7f0bsNeOTDNLc/edit?usp=sharing
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
I plan to use an offline wallet to secure the Notary address with DataCap.

And a multi-wallet will be used if other members in the Venus group work together on DataCap allocation.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
All clients must go through a rigorous process to qualify, and the higher the DataCap threshold, the greater the review limit. I will collect information through GitHub, Slack, or Email.

The first step is to collect:
   1. Company entity information;
   2. Information of authorized signatory;
   3. Beneficial Owners;
The second step is interview and data source inspection.
The third step is to sign an agreement and gradually allocate DataCap.

More questions:
   1. Introduction of yourself/ your organization(with links)
   2. Use case
   3. Location
   4. Maximum DataCap allocation
   5. Filecoin address
   6. SPs you intend to allocate DataCap with allocation proportion
   7. Specific requirement of SPs and storage service
   8. For-profit or not
   9. Follow up plan
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Regularly check and audit the usage of allocated DataCaps through tools such as filplus.info.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
My allocation decision records will be made public on GitHub and monitored by the Filecoin community.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
As mentioned above, in GitHub.

Since all application records are publicly available, allocation decisions are transparent.

Suppose community members challenge the notary's decision; in that case, they can submit a dispute resolution application to the notary's management organization after giving clear evidence, and the management department can appoint arbitrators to resolve the dispute.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
On average, there can be 10 hours a week.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None
```

**Comment by galen-mcandrew** [comment]
[Venus Team - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320913/Venus.Team.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Joss-Hua** [comment]
> [Venus Team - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320913/Venus.Team.-.Round.3.Notary.Election.Scorecard.pdf)

thanks

**Comment by Joss-Hua** [comment]
> > [Venus Team - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320913/Venus.Team.-.Round.3.Notary.Election.Scorecard.pdf)
> 
> thanks

Thanks for your time. I updated **Time Commitment**.

**Comment by Joss-Hua** [comment]
> Hi @Joss-Hua **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.
> 
> In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:
> 

> 1. Please confirm that the region of operation for client applications you will focus on is Greater China.

**Yes**

> 2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).    
 

>    •	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship    .

**Yes, I abide by it.**

>    •	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.    

**Yes, clients should store their data in at least four different SPs to maintain data dispersion and security. At the same time, customers can choose to back up their data in different SPs, but there should be no excessive redundancy.**

**If clients store their public data on the Filecoin network in strict accordance with the rules of Filecoin plus, it will be easier for clients to get more help. We can provide the necessary help, from the perspective of the community, including consultation on problems, review of the quality of SPs, etc.**

>    •	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.    

**Yes, you can contact me at @Joss on slack.**

>    •	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.    

**Yes, for the same person, one should be transparent about the behavior of their notary role and client role.**

>    •	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.    

**Yes, the beginning of any application will be discussed and a reasonable decision will be made through open channels.**

>    •	Community Governance Participation: It is expected that you will participate in the program 10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.

**Will handle applications and discussions according to the requirement, and participate in each meeting when the jet lag allows.**

> 3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

**f0128788: it is the node managed by our team and the first node in the whole network to run Filecoin protocol using Venus. It may be encapsulated according to some specific test requirements. Therefore, the wallet address of f0128788 is related to Venus, but it has no commercial purpose.**

**f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq: it is the address we use to apply for Datacaps. It is used for some Venus community programs, but not for commercial purposes.**

> 4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

**Yes, I abide by it.**

> 5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.    
>    •	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: [https://shop.ledger.com/pages/ledger-nano-x)    ](https://shop.ledger.com/pages/ledger-nano-x)%E2%80%A8)

**The address is still the one submitted in the application: 
 f1zzyvpsitfnoh5fnd3eybolupecsjxv22kb2ofyy**

**Comment by galen-mcandrew** [comment]
@Joss-Hua please verify and confirm that you are **only requesting 10TiB** of total DataCap to allocate to clients.

**Comment by Joss-Hua** [comment]
> @Joss-Hua please verify and confirm that you are **only requesting 10TiB** of total DataCap to allocate to clients.

**Yes.**
But if 100TiB can be allocated, it will be perfect. I am confident to complete it.
Thanks.

**Comment by galen-mcandrew** [comment]
Per above, I'm going to modify the requested amount to 100TiB of DataCap. Thanks!

**Comment by galen-mcandrew** [comment]
@Joss-Hua 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Joss-Hua** [comment]
Thank you @galen-mcandrew. I've submitted it.

**Comment by Joss-Hua** [comment]
Awaiting Ledger @galen-mcandrew @Kevin-FF-USA

**Comment by galen-mcandrew** [comment]
@Joss-Hua Have you received your ledger? It is non-trivial to transition the DataCap and notary status to a different address, and (to my knowledge) there is not a way to import an existing address into a new physical ledger device.

Please let us know if you are able to get your ledger and confirm your ledger address using the verification tool in the [Fil+ Registry app](https://plus.fil.org/).

[Here](https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing) is a troubleshooting guide.

Thanks!

**Comment by Joss-Hua** [comment]
> @Joss-Hua Have you received your ledger? It is non-trivial to transition the DataCap and notary status to a different address, and (to my knowledge) there is not a way to import an existing address into a new physical ledger device.
> 
> Please let us know if you are able to get your ledger and confirm your ledger address using the verification tool in the [Fil+ Registry app](https://plus.fil.org/).
> 
> [Here](https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing) is a troubleshooting guide.
> 
> Thanks!

Hey @galen-mcandrew, so sorry, because of the impact of the COVID-19, express cannot be collected in Shanghai, so I can't start verification. But in my judgment, I may receive Ledger within one to two weeks and complete the on-boarding according to the steps.

After receiving Ledger, I should regenerate the notary address through Ledger and tell you, right?

**Comment by galen-mcandrew** [comment]
@Joss-Hua We understand, hope you are able to stay safe and healthy! Once you get your ledger, let us know and we'll award the DataCap to that address. It is harder to transfer, and you cannot import an existing address into a ledger device.

In the meantime, we hope you can help us audit clients (such as large datasets) and join the community discussion in the governance calls. Thanks!

**Comment by Joss-Hua** [comment]
Hey @galen-mcandrew , sorry for waiting. I finally got the ledger and used it to generate the Filecoin address, which should be the address I used to work as a notary. 

I updated it here to replace the address in the above application information. If you need me to modify the above information at the same time, please let me know. Thank Galen.

# Notary Application
## Core Information
- On-chain address to be notarized (recommend using a new address): **f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi**

**Comment by Joss-Hua** [comment]
hi @galen-mcandrew @Kevin-FF-USA @dkkapur 
I updated the address here last week. It has not been verified yet. 
What do I need to do? Or just wait now?

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Datacap Allocated
> 100TiB

**Comment by galen-mcandrew** [comment]
Added by RKH to v3 multisig
https://filfox.info/en/message/bafy2bzaceadtib7bhg6e4ukadzi22i5pptve6fjndfqojyzud3swp25rz5ehy

**Comment by Joss-Hua** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebvg4qkt4pi5n4gb3hmb2fhsxqn5on4ghciucacqitiwovqlw3vbk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvg4qkt4pi5n4gb3hmb2fhsxqn5on4ghciucacqitiwovqlw3vbk

**Comment by Joss-Hua** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec6yqrsveibf7j32yeq7qm7erkblemjwcra4bvipolh5aobw3x6lm
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6yqrsveibf7j32yeq7qm7erkblemjwcra4bvipolh5aobw3x6lm

**Comment by Joss-Hua** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebnzi4uao7azrjfju343wtbpwhcv7jxb4cpsv57ihb6eyxhw4vyhk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnzi4uao7azrjfju343wtbpwhcv7jxb4cpsv57ihb6eyxhw4vyhk
