### ISSUE TITLE
Notary Application: Waterdrop Lab

### ISSUE THREAD

**Issue by jggapp** [filecoin-project/notary-governance#432]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Waterdrop Lab
- Affiliated organization: SSDMINER CLOUD INTELLIGENT 
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address): f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
- Region of Operation: Greater China
- Use case(s) to be supported: General
- DataCap Requested: 1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Waterdrop Lab is a leading distributed storage technology research institution in China. It is jointly initiated by Waterdrop Cloud and distributed storage experts, hardware manufacturers and software service providers. Waterdrop Cloud is China's leading IPFS distributed storage service provider.The company has been deeply involved in the field of cloud storage and IDC for many years, and focuses on the ecological construction of distributed storage. It has full-link service capabilities and is committed to outputting the best distributed storage solutions in the industry.

-Since 2018, the core members of Waterdrop Cloud have gradually transformed and expanded the distributed storage ecosystem with years of experience in cloud storage and IDC fields, and R&D team have begun to study the basic technology of distributed storage.

-In September 2020, Waterdrop Cloud launched the first Filecoin miner node f022853.

-Based on its own technological innovation, Waterdrop Cloud provides users with high-quality distributed storage solutions.In December 2020, Waterdrop Cloud launched its self-developed dynamic income calculator and GAS check tool, which includes all Filecoin economic models and provides accurate and dynamic FIL income calculation capabilities. 

-In September 2021, Waterdrop Cloud launched the FILMeet intelligent platform to provide the best cluster operation and maintenance solutions for Filecoin cluster customers.

-With the technical accumulation of Waterdrop Cloud, the company will continue to develop rapidly, and will continue to be committed to the infrastructure construction of blockchain, participate in ecological construction together, and provide customers with more competitive and completely reliable products, solutions and services. 

https://mp.weixin.qq.com/s/zWZTOTTsHj2J8A0fLmd77w
https://calculator.ssdminer.cn
https://gasssc.ssdminer.cn/#/
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
f0701056  f0216849  f022853    f066563
f065141   f0110442  f0120983   f0123931
f0763048  f0844271  f01365756  f060754
f01632832 f01684950 f01741664  f01752730

Up to now，we have over 16 Miner ID and the total amount of FIL is around to 629780.

```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```

Because Filecoin has a relatively complex economic model, the Filecoin income calculators on the market in the early days were all static income calculators, and the calculation results were far greater than the real income that could be obtained, resulting in a certain degree of chaos in the early market. 
In December 2020, Waterdrop Cloud launched its self-developed dynamic income calculator and GAS check tool, providing users with accurate and dynamic FIL income calculation capabilities. 
In addition, based on the years of IDC experience of Waterdrop Cloud, in September 2021, Waterdrop Cloud launched the FILMeet intelligent operation and maintenance platform to provide the best cluster operation and maintenance solutions for Filecoin cluster customers.
-https://mp.weixin.qq.com/s/zWZTOTTsHj2J8A0fLmd77w
-https://calculator.ssdminer.cn
-https://gasssc.ssdminer.cn/#/

On April 9, 2021, the "Web3.0 China Summit and Distributed Storage Industry Conference" opened in Hall 6 of Shenzhen Convention and Exhibition Center. As a high-tech enterprise focusing on the research and development of distributed storage, distributed computing, and distributed database technology, Waterdrop Cloud was also invited to participate in the conference.
-https://mp.weixin.qq.com/s/vfwYIHrHP6_6I565__de9g

On July 15, 2021, "2021 Web3.0 China Summit" and "IPFS Blockchain Distributed Storage Industry Conference" opened in Hall 2 of Chengdu Century City New International Convention and Exhibition Center, and Waterdrop Cloud was invited to participate. On July 16th, at the theme roundtable conference "Blockchain Technology Helps "East and West Counting"", Mr. Wang Kuan, founder of Waterdrop Cloud, also discussed with the guests how blockchain technology can help the country's new infrastructure development strategy "East Data and Western Computing" project to discuss the distributed storage industry together.
-https://mp.weixin.qq.com/s/3XpR88YlxLFuh3v6MLH--Q

In August 2020, Meng Saili, Secretary General of Shenzhen Nanshan District Blockchain Application Association (English abbreviation: NABA), visited Shenzhen Waterdrop Cloud Intelligent Co., Ltd. to understand the development history of Waterdrop Cloud, and made suggestions on the company's cultural concept and team work. Highly appraised and issued a membership certificate, Waterdrop Cloud officially joined the Shenzhen Nanshan District Blockchain Application Association!
-https://mp.weixin.qq.com/s/tHg6q9uWPL_UJznJoXpM0Q
-https://mp.weixin.qq.com/s/JeCvMRMCH6vMsQeMQJ58nQ

In September 2021, Mr. Wang Kuan, co-founder of Waterdrop Cloud, was invited to participate in the 2nd Shenzhen Blockchain Week Cloud Summit to discuss the future of distributed storage with on-site industry scholars and experts.
-https://mp.weixin.qq.com/s/0n54t-z6ArrkN6bCCft8bQ

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Waterdrop Cloud is a leader in China and the first technology-based service provider in Fujian Province to provide IPFS distributed storage services. Founded on December 22, 2020, the members of Waterdrop Cloud include:
1. Hardware Manufacturers: Dell China, H3C,HUAWEI, etc.
2. Distributed Storage Service Providers: SandStone, etc.
3. Ecological Application Companies: Waterdrop Cloud, PSCC盘石云，Jujie Technology, etc.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
1. Social Media
Website: http://www.cloudtron.pro/
WeChat Official Account: ssdminer/水滴云链(more than 1,500 community members)
Telegram: https://t.me/+-JmBLd3Cf685NjFl
Youtube: https://www.youtube.com/channel/UCcOuCQSDIfr-ojy9c9F-uRg

2.Related Personnel
Co-founder: Wang Kuan
WeChar Channels: fil宽
Douyin: fil宽

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://zhuanlan.zhihu.com/p/406188652
https://www.qklw.com/blockchain/20210902/215224.html
https://www.qklw.com/blockchain/20210902/215224.html
https://mp.weixin.qq.com/s/0n54t-z6ArrkN6bCCft8bQ
https://mp.weixin.qq.com/s/N_O_jpXzUBPl_cVODqecWA
https://mp.weixin.qq.com/s/GHBMsheA07P4_zzt49nB7g

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://v.douyin.com/Ndu3QV1/(around 1200 followers)
https://www.youtube.com/channel/UCcOuCQSDIfr-ojy9c9F-uRg

```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
N/A
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We are inexperienced in how to allocate data caps, so we will gradually build a good data cap allocation mechanism through continuous summarization、improvement and iteration.
We believe that the main responsibility of a notary is to verify the validity of the client. Therefore, we will focus on the authenticity and impact of our clients. When making allocation decisions, the following factors will be considered:
1. Basic information and reputation of the client organization.
2. Development planning and completion of the project.
3. Distribution size of DataCap
4. Customer's DataCap usage.
5. Safety Precautions
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Everyone can apply for DataCap, and we will conduct due diligence on each client applying for DataCap. Eligible customers will be approved. Additionally, I plan to use a multi-signature hardware wallet to store the keys assigned to DataCap.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will collect the following information to determine eligibility:
1. Customer reputation. Include the company's registered capital, time of establishment, team/personal background and reputation, and the client's name displayed on the company's website/social media link.
2. Project planning and project progress. Clients need to tell me what kind of data they want to store. Also, I will occasionally review the data during/after the assignment.
3. Data scale and data redundancy strategy, the type of data stored.
4. Allocation strategy. Clients should have detailed methods or tools to check miners, and we will occasionally review client performance to disqualify bad allocations.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. We will establish customer tracking records to prevent customers from making wrong allocation.
2. Customers need to disclose their allocation records, if customers do not allocate DataCap to a single entity, we will adopt a blacklist mechanism to limit customers' application in the future
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we do. GitHub repo will be in public. 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
In public via github repo.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
10+ hours per week
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
N/A
```

**Comment by galen-mcandrew** [comment]
[Waterdrop Lab - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320927/Waterdrop.Lab.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by jggapp** [comment]
Hi @jggapp based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary! You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

Please confirm that the region of operation for client applications you will focus on is Greater China.  
**Confirmrd**.
Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

• Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
**Confirmed**.

• Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
**Confirmed**.
• Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
**Confirmed**.
• No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
**Confirmed**.
• Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
**Confirmed**.
• Community Governance Participation: It is expected that you will participate in the program 10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
**Confirmed**.
Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

N/A

Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  
**Confirmed**.
(If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 

f1lmqy5b4nui5h6xssfd3svfnmie2nb6hvpabucdy

• If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x) 
Thanks for your reminder.

**Comment by galen-mcandrew** [comment]
@jggapp 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by galen-mcandrew** [comment]
Please confirm your ledger address using the verification tool in the [Fil+ Registry app](https://plus.fil.org/).

[Here](https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing) is a troubleshooting guide.

Thanks!

**Comment by xiaoyuaiheshui** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecnuv2jixf2gkaq3rifcyxyt2p2xno7nlce43emvjwthuhg4kgfws
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnuv2jixf2gkaq3rifcyxyt2p2xno7nlce43emvjwthuhg4kgfws

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Datacap Allocated
> 1PiB

**Comment by xiaoyuaiheshui** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceddqw4o3h6yvyvb3ebomjguovdnq4dnng7lumri7vutwwyrqfv5sk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddqw4o3h6yvyvb3ebomjguovdnq4dnng7lumri7vutwwyrqfv5sk

**Comment by xiaoyuaiheshui** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaced3nqbib4gysx6e2bdtyf6nom4tikjpypkyvnxm32vghpmugqmv7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3nqbib4gysx6e2bdtyf6nom4tikjpypkyvnxm32vghpmugqmv7i

**Comment by xiaoyuaiheshui** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecrjaphnpdjgt6s6gli3nr4fvsvdn4svzfkp2t4cvus5jepepyga6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrjaphnpdjgt6s6gli3nr4fvsvdn4svzfkp2t4cvus5jepepyga6

**Comment by xiaoyuaiheshui** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebcitgn5bovzzhr2srt7m4bzllbi6vz5ytdzg7jlen3yh35zzmm22
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcitgn5bovzzhr2srt7m4bzllbi6vz5ytdzg7jlen3yh35zzmm22

**Comment by xiaoyuaiheshui** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaced54s63udkzw2sadn7zcbgdi3ylo652f22egppl5uhvhv2c5p6tjy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced54s63udkzw2sadn7zcbgdi3ylo652f22egppl5uhvhv2c5p6tjy

**Comment by xiaoyuaiheshui** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebver5lsn35p3zquihzsdvxukmryi5lnbcao3dlbtqfde7hng2ag4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebver5lsn35p3zquihzsdvxukmryi5lnbcao3dlbtqfde7hng2ag4

**Comment by xiaoyuaiheshui** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceci6y44fmsclwzrkixukvjcflnvoskb2j27f7zjmyc7ntwfkpbjj2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceci6y44fmsclwzrkixukvjcflnvoskb2j27f7zjmyc7ntwfkpbjj2

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzacedjkr6wtfimvlddnqc5jr3np4cpaaxngrc5jgiovclvdqbdcn6vq4
