### ISSUE TITLE
 [Notary Application] Filswan

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/notary-governance#433]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Charles Cao
- Affiliated organization:  FilSwan
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address): f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
- Region of Operation: North America
- Use case(s) to be supported: Scientific Data, Media & Entertainment
- DataCap requested for allocation (10TiB - 10 PiB): 100TiB

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Founded at 2017 Nebula AI  is aiming at building a global decentralized computing system cross continent. 
- December 2017, we create a write paper to demonstrate the usage of  IPFS/Filcoin as the storage layer for DAPP.
- https://www.fxempire.com/education/article/nebula-ai-nbai-the-convergence-of-ai-and-blockchain-513273
```
> Decentralized encrypted data storage
> With NBAI no central organization has access to all your data. That is obtained by the combined usage of IPFS, multiple - private keys for access control and data verification which makes sure the data cannot be tampered with. This way you can be sure that your data won’t be misused or even accessed by who shouldn’t have access to it.
```
- 2018 Nebula AI whitepaper about IPFS/Filecoin published on IEEE Access, 29, 2019. Digital Object Identifier 10.1109/ACCESS.2018.2890507

- April 2020  participated testnet of filecoin project, we build the brand NBFS for filecoin project which finally incorporated as a sub-company called NBFS inc, The major business for NBFS is Filecoin mining and decentralized storage service. 

NBFS also builds Filswan project to help the Fil plus, Filecoin deal market, Filswan team has 8 people dedicated the platform over the last year. The platform has sent over 15000 deals and storge over 300 TB data on NBFS miners node.

We participate daily discussion on slack (more than 35k messages)，wechat group( more than 10k messages) and more than 20 GitHub issues

* https://github.com/filecoin-project/lotus/issues/5245
* https://github.com/filecoin-project/lotus/issues/4370
* https://github.com/filecoin-project/lotus/issues/6027
* https://github.com/filecoin-project/lotus/issues/5821
* https://github.com/filecoin-project/lotus/issues/2314
* https://github.com/filecoin-project/slingshot/issues/434
* https://github.com/filecoin-project/neptune/issues/42
* https://github.com/filecoin-project/notary-governance/issues/78
* https://github.com/filecoin-project/lotus/issues/3902
* https://github.com/filecoin-project/lotus/issues/6237

- Jan – May 2021, we were selected as minerX fellow, participated in early stage testing , release testing, deal management, and help improve louts and other ecosystem projects. It took several hours per week to participant all the activities.

Charels Cao, CEO of NBFS, is elected as ambassador of Filecoin, and help all the new comers and community as well as spread all the information and news to different groups on twitter and other platform.

Github handles: https://github.com/filswan
Miner ids: f019104, f02401,f01276,f0165400,f0145874,f0157535
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
We have 20000 Fil currently at stake, 36,000 locked as collateral
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We are working with Chainlink with data provider project.
We have several project list in filecoin community project roadmap
Flink: https://github.com/filecoin-project/community/pull/481
FS3/mcp: https://github.com/filecoin-project/community/discussions/456

Actively participating and helping the Filecoin miner community (more than 13k messages on slack)
- Participating to HackFS/ SR1 / SR2 Orbital burn / Slingshot 1 (project orion deep learning) / program
- Rank 5th in space race North America Region https://spacerace.filecoin.io/?region=021
- Rank 7th in slingshot phase 2 
- report bugs and other issues: https://github.com/filecoin-project/lotus/issues/created_by/flyworker
- Discussion in devgrants https://github.com/filecoin-project/devgrants/blob/6e12c1659cb588235010d27618623295db2a0249/rfps/new-mining-tools-rfps.md
- fil-starling-collab, providing miners and collaboration with storage deal testing
Filecoin space race community lead reward.
Filecoin Onboarding client granted https://github.com/keyko-io/filecoin-clients-onboarding/issues/38, setup miners list for sending deals

Recently Filecoin Community activities:
-Space Race Miner Show & Tell, Spe. 4th 2020,https://www.youtube.com/watch?v=jqbfETY3v6Q&t=1136s
-Slingshot - Phase 1 Closing Ceremony, 28 Oct 2020 https://www.youtube.com/watch?v=qheNJZ1DClM&t=4089s
- Filecoin as a Decentralized Substrate for Computing, 28 Oct 2020 https://www.youtube.com/watch?v=pvJaOhbGhGw

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Please answer here. 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Founded in 2021, FilSwan is the leading Filecoin application development company based in Montreal Canada. It has more than 30 employees and running more than 10 nodes to support the filecoin ecosystem.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
💻Website：https://filswan.com
📱Telegram：https://t.me/filswan
📱Twitter: https://twitter.com/0xfilswan
💻Facebook： https://www.facebook.com/filswan.technology
💻Medium：https://filswan.medium.com
💻Discord: https://discord.com/invite/KKGhy8ZqzK
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://www.linkedin.com/in/charles-cao-09a79526 has over 1600 followers.
Facebook https://www.facebook.com/taotao.cao.15 332 friends.
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Scientific Data(AI training, geological data, autonomous driving) 
Media & Entertainment(video & music)
Internet archive
slingshot 
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.

| Factors  | Details | Rating Weight |
| :---         |     :---      |          :--- |
| Ecosystem Value | The data should be meaningful for the Filecoin ecosystem. e.g. some data record random or meaningless data will be rejected.| 40% |
| Technology | Client should show they have enough technology to manage the deal transfer and result tracking. Data used in slingshot is not qualified since participants already get the reward from competition.  | 20% |
| Past History | Client past successfully complete the data quota will be a plus, other wise it will be decrease the allocation | 20% |
| Legal | The content upload should have no copywrite issue and qualified the local law and governance. | 20% |
```
The purpose of allocating the DataCap is to make sure clients use these DataCap in a manner fit the ecosystem needs.
For new applied clients, we need background check about his/her information, usually individual will be granted less Datacap than organizations.
We are building an internal tool about the reputation system, clients have a score from 1 to 10, factors be calculated will include but not limited to: contribution to the community, working terms inside the system, community reputation, GitHub activity, past allocation credit history, deal success rate, miner behavior (if they have miners), decentralization of the storage, duplications of the copies, compliance with local regulations, data quality, data cited by users.

With Filswan.com we have built a system shows the clients task sending history, the miners paster deal reputation history, you can check a sample here: https://www.filswan.com/#/miner/f010479
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Yes. With all the applications we asked a tracking record from submission – review-approval -deal tracking. The approval needs two sign officers’ approval, and the system tracking record need to be in place. 

Individual DataCap start from 1GB up to maximum 5TB, organizations start from 10GB to maximum 10TB. They can ask for a 10% incremental of next application after used current Datacap, but a cool time of 7 days is mandatory between two allocation requests. 

Client allocation can also be decreased or cancelled if they violated the terms , policy can conduct of Filecoin community.

Client can apply for arbitrage if they believe any process or conclusion in incorrect.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 

In the early stage, all clients are required for an onboarding process to be qualified. Firstly, I need to collect information including:  
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information. 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name.
 - street address (P.O. box number is not acceptable). 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence. 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

 With these provide, an interview and data source checking process need to go through. After that, an agreement should be signed for the next step - gradually allocate datacap and let the client gather more credit. 

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Periodical inspection and audit of DataCap usage

Scan tools for monitoring verified deals with miners, content scanning tools for violation of local law and policies, usage of the data, verified data distribution. https://github.com/nebulaai/trusted-miner
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 

In the early stage, all clients are required for an onboarding process to be qualified. Firstly, I need to collect information including:  
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information. 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name.
 - street address (P.O. box number is not acceptable). 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence. 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

 With these provide, an interview and data source checking process need to go through. After that, an agreement should be signed for the next step - gradually allocate datacap and let the client gather more credit. 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Yes, I plan on keeping records of our allocation decisions via a GitHub repo. We will also build a open source project for auditing purpose.
- The allocation plan and criteria is public accessible  
- Each approval and allocation is on GitHub
- All the conversation of datacap interview with client is recorded under the awareness with the client and saved in secure place.
- Client submission related documents are securely saved for future auditing.
- Client data quatation usage is online traceable.  All the datacap alocated will be saved in database for future analysis and auditing. 
We are open to any audit requests.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
10h
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes
https://github.com/filecoin-project/notary-governance/issues/157

```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
0, nobody applied in North America, I mainly in charge of LDN allocation
```

**Comment by galen-mcandrew** [comment]
[Filswan - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320944/Filswan.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi  @flyworker **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is North America.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by galen-mcandrew** [comment]
@flyworker 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by galen-mcandrew** [comment]
@flyworker Please verify which ledger address you would like to use, and then confirm your ledger address using the verification tool in the [Fil+ Registry app](https://plus.fil.org/).

[Here](https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing) is a troubleshooting guide.

Thanks!

**Comment by flyworker** [comment]
the filplus website only shows the first 5 addresses with ledger , I cannot switch to the 6th.
Maybe I should use the old address I have for last round of notary?

**Comment by flyworker** [comment]
@galen-mcandrew  thanks a lot. the previous one is better for me

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Datacap Allocated
> 100TiB

**Comment by flyworker** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaced5jjjtu4cotenzayrql3pcy2gtb55jo6yuvnk6cx7gyqermbjct6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5jjjtu4cotenzayrql3pcy2gtb55jo6yuvnk6cx7gyqermbjct6
