### ISSUE TITLE
Notary Application：IPFS Metaverse Community

### ISSUE THREAD

**Issue by ipfscn** [filecoin-project/notary-governance#434]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Nic
- Affiliated organization:  IPFS Metaverse Community
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address): f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a 
- Region of Operation: Greater China
- Use case(s) to be supported: General, Media & Entertainment, User Content.
- DataCap Requested: 100TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
IPFS.CN (IPFS China Community), officially established in October 2017, is the most influential and well-known IPFS Chinese community media in the world, with a community of over 100,000 people, and is one of the first groups of communities dedicated to IPFS evangelism in China.

In December 2021,  Response to the trend and national call, IPFS.CN officially changed its name to IPFS Metaverse Community.We will deeply analyze the core values of IPFS & Filecoin, Web3.0, Metaverse and other related fields, and build a complete ecology from IPFS to Metaverse.

IPFS Metaverse Community is committed to building a global IPFS ecological community, providing IPFS and Filecoin industry information, trend insights, in-depth reports, project incubation, mining pool development and other services for IPFS enthusiasts. In May 2021, IPFS Metaverse Community (formerly IPFS.CN) As a community partner of the Filecoin Grant online hackathon, assisted the developer platform Dorahacks with an online hackathon that lasted nearly two and a half months.

In addition, on May 31, 2021, IPFS Metaverse Community (formerly IPFS.CN) & Rhythm BlockBeats jointly launched the first podcast in the field of distributed storage - IPFS Enthusiasts Speak. It is the first podcast in the field of distributed storage in China.

In July 2021, 『IPFS.CN AMA』 was officially launched, dedicated to the content around IPFS & Filecoin ecology, and regularly invites value projects in the blockchain field to discuss the industry focus and future pattern together. After the launch of this column, many famous partners including ：Seedao, celer, polygon, Near, Dapper, Chainlink, DoraHacks, FILSWAN...


The IPFS Metaverse Community is also one of the builders of Filecoin, and we have led a number of developers in the community, giving them technical support assistance. One of these developers has participated in many Filecoin hackathon competitions and has achieved excellent results.

Links：
-https://mp.weixin.qq.com/s/dvG2cgwAKSbWk9A6zFaZdw
-https://twitter.com/Filecoin/status/1394015047886725121
-https://www.theblockbeats.info/radioinfo/66
-https://mp.weixin.qq.com/s/AltvVwI4dPUvV6DvqimHTg
-https://mp.weixin.qq.com/s/rMkbHn-IeMSxWdw9xa8n3Q
-https://mp.weixin.qq.com/s/c1NRp0j9NrTYi3PJTXyR6g
-https://mp.weixin.qq.com/s/UXACwDREC9j7bmmSspGNJw
-https://twitter.com/cn_ipfs/status/1448596977709555719
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
As a neutral media organization, IPFS Metaverse Community is not directly or indirectly involved in mining, so we do not hold tokens. However, we plan to launch a developer hackathon for soliciting Filecoin in May this year. After that we will apply for a wallet and get tokens.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
1.We started the IPFS Metaverse Community (formerly IPFS.CN) to research and evangelize about IPFS & Filecoin, and on the first anniversary of the IPFS mainnet, we launched the "Filecoin First Anniversary Poster" which documents Filecoin has made great progress since the launch of the mainnet.

Links：
-http://cipfs.io/
-https://twitter.com/cn_ipfs/status/1448892719921647618
-https://twitter.com/cn_ipfs/status/1448892689156493316

2.On December 8, 2019, the "China Distributed Storage Industry Alliance" was officially launched by IPFS Metaverse Community, together with LINGDAI Community, FANDER Community and CCTF.

3.June 22, 2020, IPFS Metaverse Community (formerly IPFS.CN) received the "Most Cohesive Community Award.

4. ICAA Global NFT Festival South America's first NFT exhibition partner.

Link：https://twitter.com/theTingDAO/status/1457556403917369344

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
IPFS Metaverse Community (formerly IPFS.CN) was officially established in October 2017, and is the most influential and well-known IPFS Chinese community media in the world, with a community of over 100,000 people, and is one of the first communities in China dedicated to IPFS evangelism.

-Foundation：IPFS Ecological Fund
-Distributed Storage Service Providers：STCloud
-Media Cooperation：BlockBetas
-Project Partners：Seedao、celer、polygon、Near、Dapper、Chainlink、DoraHacks、FILSWAN.
-Registration Country: China
-Organization size: 100
-Time since establishment: 2017
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
-Twitter：@cn_ipfs
-Website：http://cipfs.io/
-Telegram：https://t.me/ipfscn2018
-Medium：[@cn_ipfs ](https://medium.com/@cn_ipfs)
-Discord：https://discord.gg/Sr9BE3V5
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://twitter.com/theTingDAO/status/1457556403917369344
https://www.tuoluocaijing.cn/columns/author394970
https://baijiahao.baidu.com/s?id=1667242108605237884&wfr=spider&for=pc)
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter:(https://twitter.com/buboo_m

```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
In order to better serve community participants, IPFS Metaverse Community will not impose strict restrictions on use cases, but as a technology research institution, we prefer to support developer tools, Web 3.0, Web3 DApp, Web 2.0 applications and other technology-related applications.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We will focus on the authenticity, influence, allocation decisions, etc. of our customers.
In addition, we will conduct offline surveys to find out who they really are, what they do, their reputation, etc., and how they use Filecoin for storage. We even plan to conduct a full review and assessment of our clients' reputation every three months and reserve the right to adjust client quotas to ensure that shares are allocated to the fullest extent possible.

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will use a wallet with multiple signatures launched by our partner FIL WALLET to distribute to more customers and use a wallet that supports file coins to verify accounts associated with Datacap distributions.

The private keys will be stored in the hard wallet and will be accessible only by the principal.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
First, we will collect relevant information about customers.

1.Entity Information
- Formation documents , this includes certificates of registration/incorporation/information; 
- government-issued identification number for the entity；

2. Authorized Signatory Information
- evidence of the authorized signatory’s authority to act on behalf of the application entity ；
- Sign and press fingerprints (official seal and corporate seal are required)；
- ID card and a photo of the individual and ID card to prove it is the person;

3.Company operation direction and turnover
- Company goals, company's main business；
- Annual turnover in the last two years；

Question List:
1.Please provide information about the project, including the name of the organization, scale of operation, social media accounts & follwers, business license (can be sent by email); if you are an individual, please provide your name, date of birth, workplace and scale, proof of employment, social media accounts & follwers, ID card (can be sent by email).

2.When did you first learn about Filecoin? Please tell us about the projects you have participated in ? What do you want to get from Filecoin? What are your suggestions or expectations for the Filecoin network?

3.What is your data volume, source and post planning? Please describe the type, format, source, storage capacity, and public nature of the data that will be stored in Filecoin (if the data is publicly available, how will others retrieve it?

4.For application developers, will you act as a client on behalf of the user or will you apply for a notary on behalf of the user? If so, how much DataCap approval do you expect each user to receive?

After verifying this provided information, an interview and data source checking process is required. After that, an agreement should be signed for the next step: progressive assignment of DataCap, allowing the client to collect more credits
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Do check and inspections regualrly (weekly or bi-weekly);
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we will keep detailed records for review requests, and the records will be published on github.
In addition, we allow the community to provide different opinions and report, and there will be a 14 working day publicity period for DataCap customer allocation. If there is a dispute, we will consider holding a hearing to make another decision.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub will be the place to conduct all the requirements, changes and fixes regarding allocation
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
I can commit at least 20 hrs per weeek to process all the allocations in a time manner .
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None
```

**Comment by galen-mcandrew** [comment]
[IPFS Metaverse - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320918/IPFS.Metaverse.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi  @ipfscn **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Greater China.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 20 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by ipfscn** [comment]
@[Kevin-FF-USA](https://github.com/Kevin-FF-USA)  Thank you for the notice, we are very excited，Here are our answers.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1. Please confirm that the region of operation for client applications you will focus on is Greater China.  

- Confirmed.

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

• Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .

- Confirmed.

• Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 

- Confirmed.

• Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 

- Confirmed.

• No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

- Confirmed.

• Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

- Confirmed.

• Community Governance Participation: It is expected that you will participate in the program 4-6 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 

- Confirmed.

3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

- None

4.Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

- Confirmed.

5.(If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 

- f3styhh3ldl36oz3t2s4leavvuyarmqw5jwj4xk3w5lf3ictfrjm5qwpwdzapiksrfsig5oqrsj45olw3icldq

• If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: [https://shop.ledger.com/pages/ledger-nano-x) ](https://shop.ledger.com/pages/ledger-nano-x)%E2%80%A8)

- Thanks for your advice.

**Comment by galen-mcandrew** [comment]
@ipfscn 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by ipfscn** [comment]
@[galen-mcandrew](https://github.com/galen-mcandrew)   
 Hi, I have filled out this form, please check. Thanks

**Comment by ipfscn** [comment]
@[galen-mcandrew](https://github.com/galen-mcandrew)、 @[Kevin-FF-USA](https://github.com/Kevin-FF-USA)
The original address submitted has been invalid. This is the latest notary's address confirmed by IPFS Metaverse Community：f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a

**Comment by Kevin-FF-USA** [comment]
Hello @ipfscn!

Some final verification:

We have your updated address on file as: f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
previous address: (f3styhh3ldl36oz3t2s4leavvuyarmqw5jwj4xk3w5lf3ictfrjm5qwpwdzapiksrfsig5oqrsj45olw3icldq)

And we will be communicating with Nic-IPFS Metaverse Community on Slack. If there are any other handles you wish to have included in communications, please comment them below.

**Comment by ipfscn** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceademfdj5qya2v3ss5hnmky75qsgfvtr3k2tlbknef56l26vjd7w6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceademfdj5qya2v3ss5hnmky75qsgfvtr3k2tlbknef56l26vjd7w6

**Comment by Kevin-FF-USA** [comment]
HI @ipfscn 
For compliance and reporting, we need to have the full legal name of the person who will be responsible for the address connected to this application.  Feel free to post here in application, or DM me in SLACK if you wish to keep that out of the public. 
TY

**Comment by ipfscn** [comment]
@[galen-mcandrew](https://github.com/galen-mcandrew)、 @[Kevin-FF-USA](https://github.com/Kevin-FF-USA)
Hi，Kevin，The full legal name of the person responsible for the address associated with this application is “Nic Wong”.
Thank you for the notice, I hope I can pass successfully.

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Datacap Allocated
> 100TiB

**Comment by ipfscn** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedsldtmd5xlqsi7znahpklbal3zb7daflhzju2ehrehqdiywkw5ic
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsldtmd5xlqsi7znahpklbal3zb7daflhzju2ehrehqdiywkw5ic

**Comment by ipfscn** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceaxujh6xywntfqml4r6nid2ywp23xm7il5xyak2eeq346ujatsbwo
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxujh6xywntfqml4r6nid2ywp23xm7il5xyak2eeq346ujatsbwo
