### ISSUE TITLE
Notary Application：MatrixStorage

### ISSUE THREAD

**Issue by MatrixStorage** [filecoin-project/notary-governance#436]
To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form.

## Core Information 
- Name: Matrix Storage 
- Affiliated organization:
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address): f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley 
- Region of Operation: Greater China 
- Use case(s) to be supported: General, prefer cases on IPFS ecological applications, not limited to Web3.0 or Dapp, and big data service. 
- DataCap Requested: 10 PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment 
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

```
Matrix Storage officially started the project construction and technical pre-research in 2020. At present, Matrix Storage have been working in the IPFS/Filecoin for about 2 years. Nature of Matrix Storage Relying on the combination of blockchain technology and the IPFS protocol, it integrates storage resources across the entire network, provides easy-to-use PaaS software including OpenAPI and an encrypted storage toolkit. It is committed to efficiently linking the next generation of Internet storage requirements with decentralized storage networks.

Duration 
The team was established in 2020. The project has been officially launched on April 22, 2021. Currently, distributed storage services are provided for customers.The iterative history: https://github.com/MatrixStorage/Matrix-Storage/projects/1

Storage provider: Nodes: In cooperation with global cloud storage providers, it has more than 100 nodes. Related links: https://hackerlink.io/buidl/896
https://mp.weixin.qq.com/s?__biz=Mzg5NjY0NDUwMw==&mid=2247484645&idx=1&sn=93fda36155e8b91758736a1a96a48f1b&chksm=c07ca01df70b290bd9a6e0d76c1a89e0f500abf6faee9c8948aa67a1742c32de3e685440649d&token=897903839&lang=zh_CN#rd

Decentralized storage data introduction: Top3 
Release: 11 versions
Since its launch in April 2021, Matrix Storage has continued to provide fast, stable and reliable distributed storage services based on IPFS/Filecoin for enterprise customers. We are committed to giving full play to the advantages of distributed storage network, creating storage products (distributed storage service platform) that can compete with centralized storage, and laying a solid and credible foundation for the new storage mode in the Web3.0 era. MatrixStorage has introduced more than 30 enterprise storage users to Filecoin so far. Through continuous, step-by-step advocacy, education, and guidance, we have instilled confidence in the project into businesses that had no idea about distributed storage, and created a truly easy-to-use storage interface for them to store their data and files to the Filecoin network in any way that works for them.

Cooperation
Ecological and strategic cooperation: 20
Enterprise users: 30+
The enterprises we cooperate with are involved in 10+ segments such as medical care, big health care, media, justice and finance, and most of them have higher requirements for storage.

Cooperation cases include but are not limited to:
23Mofang: China's leading consumer gene testing company. The two sides jointly launched IPFS co-branded consumer genetic testing tool. More than 2PiB of genetic test data from more than 10,000 users will be stored on the chain via Matrix Storage. (Official website: https://www.23mofang.com)

Zhongjing Tianping: a subsidiary of The State Information Center (China Economic Network). Provide legal evidence combined with block chain technology, protect the copyright of users' electronic data through electronic signature, time stamp, distributed cloud storage, hash verification and other ways, and realize the safe archiving and backtracking of stored data. (Official website: https://www.bjzjtp.com)

Codoon: The ecological enterprise of Codoon, China's largest intelligent sports big data and service platform. Matrix storage, based on a decentralized IPFS network, provides permanent storage and invocation of encrypted individual user health data. (corporate website: https://www.codoonhealth.com)

Chengdu Digital Media: one of the four national digital media technology industrialization bases established by the Ministry of Science and Technology of China; Its data storage involves Tibetan, Qiang, Yi culture, film enthusiasts, production organizations download and use. (Official website: http://www.cd-szmt.com)

In addition, we have cooperated with several leading cloud service providers in China to provide them with distributed storage interface and technical support. It reduces the storage cost of massive audio and video files brought by the radio and television industry and expands more business scenarios.

Seven Niuyun: https://www.qiniu.com
China habitat cloud: http://www.chinamcloud.com

In addition to the active introduction of storage needs of enterprise users, MatrixStorage also in the content output activities held on matters such as show a positive attitude. Here are some of our results:

Activities
IPFS Knowledge Raffle 
https://mp.weixin.qq.com/s/BRxZX3hH2_Xv2hqVliSoUg 
https://mp.weixin.qq.com/s/PJ5vCBI-F7A1KAp8TGltog

Overseas Online Discussion
We launched an online sharing session with Holobase technology community to share knowledge points and distributed storage advantages of Web3.0 with enterprise users from 16 countries.
https://www.holobase.io/recap/6167f914d592574837604e5b 
https://mp.weixin.qq.com/s/Ro2m68luAD0G0iEClPy8KA

The First Anniversary Celebration
We united Computing Planet, hosted the celebration of the 1st anniversary of mainnet's launch, and accepted the invitation of the Force region to participate in the 1st anniversary event 
https://mp.weixin.qq.com/s/6ae6MSZmAFPj8uQk4TheKg 
https://twitter.com/MatrixStorage/status/1448948410074103811

Product Launch 
To release an IPFs-based distributed storage product to hardware suppliers and B-end customers https://filecoinproject.slack.com/archives/C022L2R1474/p1632822550000200

Content
Matrix Storage has accumulated attention and reputation in the industry by operating its own account and releasing original content. At present, Matrix Storage has produced a total of more than 40 original articles in the industry, distributed on more than 30 media platforms, with a cumulative reading of more than 60,000 times, involving more than 5,000 readers and users. It has made significant contributions to the spread of Filecoin and IPFS knowledge and ecological development.

Outstanding works
In August 2021, Filecoin Plus Periodic Notary Report (In English and Chinese) was well received by the community for its detailed analysis of the Filecoin Plus project's information statistics, share allocation details, and global distribution of DataCap.
In September 2021, Fil+ Phased Big Data Set Report (In English and Chinese) made a global survey and forecast of Filecoin Plus's initiatives to promote ecological implementation, including details of the Filecoin Plus project application, community approval preferences, and changes in application duration since the opening of the Filecoin Plus big data set application channel. By the community praise. Up to now, the two reports have been downloaded more than 500 times and viewed 3 + times on multiple platforms.

Related links:
Twitter: 
https://twitter.com/MatrixStorage
Filecoin Plus Large Datasets Periodic Report: https://drive.google.com/file/d/1J__E67B6ym6tgXIv5tOYT8NP1n42HaK_/view?usp=sharing
Filecoin Plus Periodic Report:https://drive.google.com/file/d/11T4SRoKBLnsHyEM2375xKNaj3U1G_lH2/view?usp=sharing
Slack:
Filecoin Plus Large Datasets Periodic Report:https://filecoinproject.slack.com/archives/C01KCAAURAN/p1630036161002600 Filecoin Plus Periodic Report:https://filecoinproject.slack.com/archives/C01KCAAURAN/p1629275531053000
*Note: Due to policy influence, the above report was temporarily transferred to "private" in China and was not made public. 
```

### Stake Exposure 
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence. 
``` 
Matrix Storage serves as a distributed storage trading platform and do not hold any token. 
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow.
```
Over the past 2 years, We have established data storage cooperation with many domestic enterprises with stored data reaching 23 TiB, which is uploading. With the large-scale promoting of Matrix Storage within the next year, we expect that there will be more than 1PiB effective data stored through Matrix Storage. Industry leading enterprise, such as 23Mofang, the largest consumer gene testing product in China, Zhongjing Tianping, the subordinate enterprises of State Information Center (China Economic Network), Digital Media Industry Base, one of the four national digital media technology industrialization bases, Huaqi Cloud and Qiniu Cloud, China's leading cloud media service provider, have became our cooperative parters.
At the same time, we set up WeChat groups. These WeChat groups have linked storage users and storage resource providers. Users can release their demands and storage
resource providers can accept storage requirements. We will also regularly publish updates of industry and product to the WeChat group, expanding the reach of the matrix storage and IPFS/Filecoin.
Although the Matrix Storage project was officially launched in April 2021, early technology research based on IPFS and Filecoin networks began as early as July 2019. Therefore, after the mainnet was launched, a special project team was quickly set up to do product research and development, complete products were presented in a short period of time, and market customers were accumulated in the early stage. Matrix Storage product system based on IPFS and Filecoin network is built. The system consists of an enterprise-class storage platform, a storage tool set and a C-terminal application.

1.Production Line of Matrix Storage Business-oriented Platform
Functions implemented in this version 1.0.0:
-Upload/archive of files
Files are uploaded to the IPFS network as warm data, and archived to the Filecoin network maintained by miners as cold data.
-Extraction/download of files
The archived files need to be extracted from miners' distributed network to the IPFS network/matrix storage centralized server for download service.
-Access control of files
Files storage can be divided into public or private storage. The publicly stored files will reside in the public IPFS network and can be accessed from any public IPFS network.The files in private storage can only be accessed through the IPFS network built by Matrix Storage.
Functions implemented in this version 1.0.1:
-List Multipart Uploads added in API
Users can choose the data size while uploading and synthesize a complete file to form a CID after completely uploading, which improve upload success rate.
-Multiple uploading of the same file. 
Multiple uploading of the same file is supported for users.
-Filecoin address import function 
Import existing Filecoin address into matrix storage systems to make full use of existing FIL is supported for users.
-The single uploading file jumped from 512MB to 64GB on Web. 
Meet the needs of using the web console to transfer large file

2.Core function of Matrix storage -IPFS cloud disk (Unopen)
-Upload/download of image V1.0.0
Upload the phone photo and download it from the IPFS network
-Preview/Share of image V1.0.0
Images are previewed via IPFS gateway and shared in WeChat applet/Moments via CID .
-Import of third-party partner data V1.1.0
Third party partners (23 Mongfang mentioned above) is supported to upload specific data to customer's specific IPFS cloud disk and download.

3.Matrix Storage provides open API interface; visual debugging and online command-line tools, helping users to upload data files easily. Application SDK provides JAVA, Python, C and other multi-language SDK, so that users with development ability can directly complete the secondary development, effectively improving efficiency and performance.

4.We are developing NFT middleware, which is the first Web3.0 oriented middleware product of Matrix Storage. NFT developers can easily access IPFS/ Filecoin network through EasyNFT middleware.

5.In addition, we have also posted a project profile about Matrix Storage on the Slack channel to let more industry participants know more about our service.
https://www.kejixun.com/article/210521/527318.shtml
https://tech.sina.com.cn/roll/2021-05-21/doc-ikmxzfmm3845980.shtml
http://news.ikanchai.com/2021/0521/422452.shtml
http://www.citnews.com.cn/news/202105/128329.html
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions.
```
[BUG] GenerateUnsealedCID,more than 32 GB file,return Piece is large then sector #6292https://github.com/filecoin-project/lotus/issues/6292
Matrix Storage is developing tools to provide notaries with a trading display of clients and miners' nodes. At the same time, miners and clients can post/bid on the trading market online. Making all transactions fair and transparent, so as to achieve trade compliance from the source.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Matrix Storage is a decentralized cloud computing infrastructure service provider, based on web3.0 infrastructure construction, providing individuals and enterprises with the world's leading cloud computing, big data, artificial intelligence and other technology products and services. Team size of more than 50 people, the establishment of nearly 2 years of rapid development, the size of the team is still expanding.
Matrix Storage provides an intermediate bridge between data storage requirements and data storage providers by providing easy-to-use PaaS services, OpenAPI services, and a storage toolset. In order to connect the underlying technology with the real business needs, Matrix storage has established deep cooperation with key people in the upstream and downstream industries.
Storage Providers:
We have established a cooperative relationship with global storage providers, the top in the industry, and provided stable storage nodes for storage users, which ensure the stability and reliability of the storage cluster and achieve the effective balance between the performance and cost. There will be more high-quality and stable nodes joining Matrix Storage in the future, and provide users with more storage options and storage space.
https://www.donews.com/news/detail/4/3151551.html
http://news.yesky.com/hotnews/211/725744711.shtml
http://www.itbear.com.cn/html/2021-05/405335.html
Clients:
Matrix Storage is implemented in the fields of radio, television and video, big data of genes, big data of health, judicial storage and AI agents, as mentioned above.
At present, we are pushing forward to try more cooperation with traditional storage service providers. We are also looking for more enterprise users who have real data storage needs to provide them with more secure, more reliablemore convenient , and less costly storage products.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Matrix Storage's official website: https://storage.easymeta.io/index?lang=zh
Matrix Storage team was established in 2020, with independent r&d, promotion and operations personnel. There are more than 30 r&d staff and more than 10 promotion/operation staff. The average working experience of r&d staff is more than 5 years.
https://github.com/lucifercd ，lu is involved in the issue of encryption currency and promotion.
https://github.com/kiba-zhao
https://github.com/lei286394973
https://github.com/back0893
https://filecoinproject.slack.com/archives/CR98WERRN/p1620384716043500
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.) 
```
https://www.donews.com/news/detail/4/3151551.html
http://news.yesky.com/hotnews/211/725744711.shtml
http://www.itbear.com.cn/html/2021-05/405335.html
https://www.kejixun.com/article/210521/527318.shtml
https://tech.sina.com.cn/roll/2021-05-21/doc-ikmxzfmm3845980.shtml
http://news.ikanchai.com/2021/0521/422452.shtml
http://www.citnews.com.cn/news/202105/128329.html
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter: https://mobile.twitter.com/MatrixStorage
GitHub: https://github.com/MatrixStorage ( followers: 118 )
Wechat official account: MatrixStorage (followers: 1843)
Wechat ID: MatrixStorage_ (followers: 100+)
Slack: https://filecoinproject.slack.com/archives/CR98WERRN/p1620384716043500
Bilibili: At the same time, we invited 晓说web3 to become our marketing consultant [followers: 1353] 
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Matrix Storage provides IPFS - based decentralized storage services for users in various industries. As long as the data and business comply with laws and regulations, we do not make too many requirements in terms of type. In addition, we believe that big data can benefit humanity, so we encourage more enterprises to store searchable public data. 
```

# Allocation Plan 
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We calculated the level of applicants through scoring, and set maximum amount for each level in first allocation, so that we could fully follow up the usage of applicants; All individuals and businesses are encouraged to get involved in the IPFS business, but we prefer organizations in order to build the IPFS ecosystem more quickly.
We judge the qualification on a scale of 1 to 4 (round), and our scoring mechanism is as follows:
```
![image](https://user-images.githubusercontent.com/82867405/156406586-a553ca5e-a950-4235-b32b-fce7380bb815.png)
```
1.The entire application and allocation process will be transparent and open;
2.Strictly review the information provided by users, including but not limited to some written evidence;
3.Establish online communication audit mechanism and offline investigation audit as far as possible;
4.Score will be given after reviewing the information provided by clients;
5.We will confirm the previous DataCap usage when clients submit next application.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap? 
```
The private keys will be stored in the hard wallet. 
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them?
```
According to the business & technology planning submitted by the applicant, we will conduct a sample survey on the applicant's business in effectiveness, continuity and usage after DataCap have been granted:
1.Communicate with organization, contact person online/offline from time to time;
2.Submit the information to prove the business is in operation;
3.Extract and view data samples;
4.Query the usage of DataCap.
If the applicant is found that they use DataCap irresponsibly or exchange benefits existing, the applicant shall immediately disclose this information to the authorities and cooperate in the verification. If it is true, the applicant shall be disqualified from the allocation. The processing result and the true situation shall be published to the community.
1.Why did your company choose IPFS industry and decentralized storage?
2.Can you give more details about duration, nature, scale of your company?
3.What industry does the company mainly serve/how many people are served?
4.Can you present future business or technology plans?
5.Can you explain in detail about data type, and copyright ownership? And how much data will your company store?
6.Does your company need to call for stored data, and if so, how often it happens?
7.How many miners do you want to choose for storing the data? How much DataCap will be allocated to each miner?
8.Will you publicly record allocation decisions?Which platform will you use?

In the application process, We will confirm with the client whether there are cooperative miners. If there are, we will ask them to clarify the location of the miners, miners' ID, the proportion of distribution and the reason for selecting the miners;
If not, we will actively guide them on how to find miners (e.g. Slack, Matrix Storage, Miner reputation system, etc.);
After allocation, we will require the customer to timely publish the trasaction information, including the location of the miners, miners' ID, the proportion of distribution, etc.
We will follow up every week. If no abnormality is found, we will gradually expand the allocation;
If there is any abnormality, we will remind you in time. If the client does not cooperate, we will terminate the subsequent allocation and confirm with the official whether the previous allocation can be recovered from the technical level.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
During the review phase, we will ask questions about the allocation, the allocation preference of the applicant, and encourage collaboration with several miners. After the allocation, we will track the user's DataCap usage and business development to ensure that the allocation plan provided by the applicant is real. If you have any questions or other questions, we will keep abreast of the situation.
We will continue to clarify and track customer allocation during the application review stage, including allocation and after allocation. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both?
```
All allocation decisions will be public. 

* Update:
We will follow the rules of community Governance, making all of our allocation decisions public and posting them on Github.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We will record in the form of table
(https://docs.google.com/spreadsheets/d/1o0QzgKRB7sdQFKWkViTpkLjlkuoyxFq0lGg_7 EjotOE/edit?usp=sharing), including Issue Number; Applicants; Current State; DataCap Requirements; Application Date; Website/Social Media; Nodes and Proportions; Filecoin Address; GitHub Account; Result; Result Time; DataCap Allocation; Remarks.
At the same time, We will store deal reputation information and basic client information in a distributed and irreversible manner, including but not limited to datacap allocation decisions;
The user handle the registration, login, edit the basic information, submits the datacap request and other actions through Matrix Storage. All information are recorded by the matching system.
All allocations will be updated and published on the GitHub issue to follow up on DataCap allocations and related informations of allocation.
All allocation information is recorded on GitHub, table, and Matrix Storage. The information is open and transparent. If there is any abnormality, we will update it on the GitHub issue simultaneously.

* Update:
- First, all assignments will be available on Github and can be looked up on filecoin plus tools, like filplus.info.
- and we will record every allocation in the tab (links:https://docs.google.com/spreadsheets/d/1o0QzgKRB7sdQFKWkViTpkLjlkuoyxFq0lGg_7EjotOE/edit#gid=0), making the tab public for all to see;
- When we decide to allocate, we will publish the client's score and allocation in the filecoin-plus-client-onboarding repository and confirm with the client's address. After the distribution, we will continue to follow up the client's usage and record it in the tab.

If there is any audit/review request, we will take every audit/review request very seriously, but reject unreasonable complaints;  We will submit the audit materials within 3 working days after the request is initiated, and actively conduct real-time communication and email archiving with officials on Github/Slack.  
```
![table](https://user-images.githubusercontent.com/82867405/159431184-391a60f3-e617-4c64-9f67-7fa1ea154c5d.png)

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
We are willing to spend approximately 10 hours per week on DataCap applications, major share applications, and community governance related issues. We monitor Slack and Github on a daily basis to get as much timely feedback as possible. 
```

### Past allocation
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None. 
```

Cumulatively, how much DataCap have you previously successfully allocated?
```
None. 
```

**Comment by galen-mcandrew** [comment]
[Matrix Storage - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320909/Matrix.Storage.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by MatrixStorage** [comment]
Hello, Galen.
We noticed that we got low score in Bookkeeping Plan, and we made the following adjustments.
The document link of bookkeeping Plan in the previous application materials could not be opened. Here is the latest link: https://docs.google.com/spreadsheets/d/1o0QzgKRB7sdQFKWkViTpkLjlkuoyxFq0lGg_7EjotOE/edit#gid=0. In addition, we would like to add the following points to our bookkeeping plan:
### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both?
```
We will follow the rules of community Governance, making all of our allocation decisions public and posting them on Github.
```
Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
- First, all assignments will be available on Github and can be looked up on filecoin plus tools, like filplus.info.
- and we will record every allocation in the tab (links:https://docs.google.com/spreadsheets/d/1o0QzgKRB7sdQFKWkViTpkLjlkuoyxFq0lGg_7EjotOE/edit#gid=0), making the tab public for all to see;
- When we decide to allocate, we will publish the client's score and allocation in the filecoin-plus-client-onboarding repository and confirm with the client's address. After the distribution, we will continue to follow up the client's usage and record it in the tab.
```
![table](https://user-images.githubusercontent.com/82867405/159430545-3c30ceb6-4c91-4c5d-aa17-672a46fdcb8e.png)

**Comment by MatrixStorage** [comment]
In addition, we would like to explain some of your questions about the platform.
As an intermediate bridge between clients and storage providers, Matrix Storage enables more clients to store data in decentralized networks through the platform provided by Matrix Storage.
1. Most of the storage providers we currently cooperate with are domestic storage providers. In the past year, we have promoted the use of IPFS/Filecoin network for storage to clients in China. However, because of the particularity of industry or enterprise background, these clients require that data can only be stored in storage nodes of China.
2. Matrix Storage also launched the international version (https://storage.anmaicloud.com/index?lang=en) provide for the use of overseas clients and storage providers. But they also have more options in the Filecoin distributed storage market. We are improving the popularity of the product in foreign market.  
3. In addition to Client, we also have the console used by operation and management personnel. In the console, we can clearly see the number, size, region selection, storage provider selection and other information uploaded by clients and storage providers through Matrix Storage. Here are some screenshot of console.

![image](https://user-images.githubusercontent.com/82867405/159649844-7285a898-9202-4cd4-8adc-1ec5f26371de.png)

**Comment by Kevin-FF-USA** [comment]
Hi  @MatrixStorage **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Greater China.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by galen-mcandrew** [comment]
[Matrix Storage - UPDATED - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8373144/Matrix.Storage.-.UPDATED.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by MatrixStorage** [comment]
Thank you very much, Kevin! Here is my response:
- Please confirm that the region of operation for client applications you will focus on is  Great China.
ACK
**Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).**
- Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship
ACK
- Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.
ACK
- Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.
ACK
- No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.
ACK
- Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.
ACK
- Community Governance Participation: It is expected that you will participate in the program 10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.
ACK
- Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.
We have no address we are affiliated with.
- Please affirm that you will abide by the allocation / client due diligence plan you laid out above.
ACK
- (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.
The address is  f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley. it is brand new, no DataCap grant.
- If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: [https://shop.ledger.com/pages/ledger-nano-x)](https://shop.ledger.com/pages/ledger-nano-x)%E2%80%A8)
Thanks for your kind reminder. we have got one already.

**Comment by galen-mcandrew** [comment]
@MatrixStorage 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by MatrixStorage** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecoulvldnhnfn2z6whytnnueqnr6lrxta6we54sybgrt4vjotzzrk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecoulvldnhnfn2z6whytnnueqnr6lrxta6we54sybgrt4vjotzzrk

**Comment by sam-fk** [comment]
@MatrixStorage 
May I ask the owner of this Notary account-MatrixStorage #436. Are you still at  XnMatrix Group?  We all know that Matrix Storage is a platform that  XnMatrix Group has invested heavily in developing, and you left with your account.The platform does not belong to you personally, but to the company. Can you prove that you represent the company? Can you prove that you still own the matrix storage platform? Can you prove which Miner ID you still hold? If you can't prove it, please return the account to the company! The company needs it badly.Please also ask filplus team Preside over justice. @galen-mcandrew @Kevin-FF-USA

**Comment by MatrixStorage** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedmwmpnbx6wbluruw63hvskk2jbxwqmifmnifwqum37h2w4ildips
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmwmpnbx6wbluruw63hvskk2jbxwqmifmnifwqum37h2w4ildips

**Comment by MatrixStorage** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedikp77txd5pywtr5kdsheqgmt2cjurkedzcxrmauf5t7rw3xljt6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedikp77txd5pywtr5kdsheqgmt2cjurkedzcxrmauf5t7rw3xljt6

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzaceamms3snolhxnrzofcn4brgunyvcimmjbf7jmek53iuze2bm7cbnq
