### ISSUE TITLE
[Notary Application] IPOLLO

### ISSUE THREAD

**Issue by IPOLLO-OFFICIAL** [filecoin-project/notary-governance#439]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: M
- Affiliated organization: IPOLLO
- On-chain address to be notarized (recommend using a new address):f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq
- Region of Operation: [North America]
- Use case(s) to be supported: [General]
- DataCap requested for allocation (10TiB - 10 PiB):1 PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
IPOLLO has focused on the FILECOIN ecosystem since 2018, and sponsored some decentralized storage-related conferences in 2019 and 2020. During the Filecoin Space Race, IPOLLO's R&D team has conducted in-depth research and test on the hardware required by FIL. At the end of 2020, we officially launched the IPOLLO Dark Steel (IPOLLO DARKSTEEL http://ipollo.com) series, and hopes to provide global and high-quality hardware supply for storage service providers in the FIL ecosystem.
As one of the main series of IPOLLO, the Black Steel, together with the servers of IPOLLO B series (BTC) and E series (ETH), was exhibited around the world. We have operation in Asia, the United States, Canada, and Europe. IPOLLO hopes each of our customers believe that FIL is as great as BTC and ETH.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
N/A
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
N/A
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
IPOLLO Miner is a supercomputer equipment designer, headquartered in Singapore. The company has evolved as a competitive player on the global market with robust designs since its inception. iPollo’s product line includes not only Ethereum V series, Bitcoin B series, and world-first Grin Asic miner G series, but also Filecoin, Chia, Swarm, and other Proof of Capacity consensus crypto miners. Aided by iPollo’s rapid growing footprints, the company is eager to serve our institutional and retail clients worldwide with a mission statement of “improving computing power and stability; reducing power consumption and user cost; maintaining blockchain network security.”iPollo’s value lies deeply in the supreme quality and prestige reputation amongst our clients and ecosystem. With a strong commitment to continuous exploration and development, iPollo strives to succeed with our clients across the world.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website：www.ipollo.com

Twitter：@iPolloGlobal
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
1、youtube ：https://www.youtube.com/watch?v=mLgLny3huCA

2、Bloomberg：https://www.bloomberg.com/press-releases/2021-10-30/ipollo-launches-b1-series-and-darksteel-series-mining-machines-available-for-sale-in-november-2021

3、newsfile：
     https://www.newsfilecorp.com/release/101333
     https://bitcoinist.com/ipollo-launches-a-series-of-limited-edition-nft-themed-mining-rigs/

4、YouTube：
      https://www.youtube.com/watch?v=9kP6aVN2MC4&t=164s
      https://www.youtube.com/watch?v=T9_pNxA7gKg&t=207s
      https://www.youtube.com/watch?v=Nu7AscpV3T4
      https://www.youtube.com/watch?v=p8vOuOb4BB8&t=20s
      https://www.youtube.com/watch?v=MpTHpqgAjAs&t=2s

5、ipollo cooperating business：
     https://www.laoyaoba.com/html/share/news?source=app_android_v2&news_id=791982
     https://cn.investing.com/news/cryptocurrency-news/nano-labs-raises-tens-of-millions-of-dollars-in-a-funding-round-led-by-yongwan-capital-to-build-infrastructure-for-the-metaverse-ecosystem-2619957
     https://www.bloomberg.com/press-releases/2021-12-28/the-successful-tape-out-of-800mm2-large-chip-under-the-fpu-architecture-of-nano-labs
     https://www.marketwatch.com/press-release/the-successful-tape-out-of-800mm2-large-chip-under-the-fpu-architecture-of-nano-labs-2021-12-28
     https://finance.yahoo.com/news/successful-tape-800mm2-large-chip-203100914.html
     https://news.yahoo.com/successful-tape-800mm2-large-chip-203100914.html
     https://sg.news.yahoo.com/successful-tape-800mm2-large-chip-203100914.html
     https://uk.news.yahoo.com/successful-tape-800mm2-large-chip-203100914.html
     https://ca.news.yahoo.com/successful-tape-800mm2-large-chip-203100914.html
     https://au.news.yahoo.com/successful-tape-800mm2-large-chip-203100914.html

6、IPOLLO conference：
     https://mp.weixin.qq.com/s/KmtHxUOQq_qdBqhX6-Y_7A
     
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twiteer：ipollominer （follower：18）
Twiteer：ipollo global  （follower：7451）
Facebook：ipollominer 
Facebook：ipollo global  
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
In order to achieve Filecoin's mission of becoming the most important information foundation for the humanities, we support any trusted public data set. in addition to commercial data (user content, scientific data sets, media entertainment, etc.), we also welcome non-internet business store their data on Filecoin network. i think that will also improve diversification for Filecoin.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Scoring system is showing in the following table: 
https://docs.google.com/spreadsheets/d/1faW7jgF23ZgXvpA_8QxHJaxqoARg9Mj8/edit?usp=sharing&ouid=116818884075544984934&rtpof=true&sd=true
We will review the application information submitted by the customer, and the scoring standard form for reviewing information is in the link. 
First we will divide the datacap into two parts, the first part (30%) is for the initial allocation. 
In the evaluation of the initial allocation, it will separate into two directions: the background investigation of the client and the rationality of the data. Then, we will observe whether there is a willingness to contribute to Filecoin in the application form submitted by the client, and if necessary, we may communicate through Github or slack. Based on the above conditions, we will determine whether the client is trustworthy. Trusted clients will pass the first allocation step. 
The second part is the tracking approval phase. This will be 70% of our total datacap. We will continuously track the usage after the client received the datacap. 
Ps. In order to improve the effectiveness of the network as soon as possible, we will strictly follow the principles specified by the official requirements for our behavior. In addition, I think that in this process, the efficiency of communication with the client is necessary. After seeing the application submitted by the customer, if we have any questions, we will ask them as soon as possible and reply quickly. At the same time, we will encourage the client who receive the datacap to allocate to storage providers quickly. 

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We have a colleague to keep the keys, which are kept on the hardware wallet. The colleague is the financial controller at the company level. We will not have too much communication on this program to ensure that the power is sufficiently decentralized and balances.

```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
 According to the principle of the Filecoin Plus project, including the principles of low-cost dispute resolution and limited trust gained over time, we believe that the first and most basic condition is the content of the application form submitted by the client on github. We will strictly review their content to ensure its authenticity. Besides, We made two forms includes both due diligence of Client before first allocation and post-allocation vetting.
https://docs.google.com/spreadsheets/d/1faW7jgF23ZgXvpA_8QxHJaxqoARg9Mj8/edit?usp=sharing&ouid=116818884075544984934&rtpof=true&sd=true
1.	Due diligence of Client before first allocation
First, we will collect the information in the excel (sheet 1) below to identify whether the customer meets the standard. Then, combined with other scoring conditions, we will judge whether the client of the application is a trusted client.
2.	Post-allocation Vetting
The post-allocation vetting of Clients will be performed regularly and constantly to avoid the allocated DataCap being abused or misused.  The fundamental principle is that the Client is obliged to spend the DataCap exclusively for the approved uses (which will be specified in our allocation decision).  
To this end, at any time of the Client’s spending the DataCap, we may ask the Client to provide:
(i)	a consolidated Content Identifier (“CID”) list for verified deals that includes deal CID and miner ID (showing how the allocated DataCap has been used);
(ii)	description of the data being stored and how the data has been processed; and
(iii)	instructions on data retrieval. 
After receiving the above information, we will conduct random sampling surveys from time to time, and retrieve the corresponding miners to verify the authenticity of the data.
During the DataCap allocation growth phase, we investigate and ensure that the DataCap allocated to the Client does not exceed its actual data storage needs. 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
First of all, we will confirm the potential allocation intention of the client, which includes: the number of miners and the percentage of each client's allocation not exceeding each miner’s.
In the allocation stage, we will conduct a follow-up review to see whether the customer's behavior conforms to the information submitted in the application. When tracking, we want to ensure that datacap od client is allocated enough to increase the diversity and decentralization of the network. At the same time, we will make it clear that if the client can maintain it perfectly and trustworthy of the network, then, the datacap applied for the future will easily. Such incentives, I believe, will push client to make reasonable allocations.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions are publicly traceable and stored in github repositories. Anyone can access and submit challenges. You can ask in Github directly , or you can ask by email. Contact details are included in our application form to ensure that we will respond promptly.

```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
All decisions will be public in the Github repository
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
2-3h every day. I will participate in governance calls every week. Be active in the community. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
NO
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
N/A
```

**Comment by galen-mcandrew** [comment]
[IPOLLO - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320947/IPOLLO.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by IPOLLO-OFFICIAL** [comment]
@galen-mcandrew Hi there,
We have update for a partial:

**1. Use case Diversity**
We mainly store data related to user content, scientific datasets, media entertainment, and web3:
30%: Relevant public data generated by web2.0 software service users
20%: Web3.0 related data, including NFT, Gamefi, SocialFi and other
30%: Research data, and machine algorithm related model data, etc.
20%: Promotional videos related to business, and other media video data files

Appreciate for your feedback, thanks!

**Comment by IPOLLO-OFFICIAL** [comment]
@galen-mcandrew @Kevin-FF-USA 
Hi there, 
I saw the other applications has got the updated score, and the organizations whose score lower than IPOLLO has pass the review. 
Is there anything else that we can offer?

**Comment by AnthnoySmith** [comment]
Just came from that Slack thread.  Is this IPOLLO really high-related to the other three applicants? Suggested to suspend these applications as below until things are clear.
https://github.com/filecoin-project/notary-governance/issues/444
https://github.com/filecoin-project/notary-governance/issues/447
https://github.com/filecoin-project/notary-governance/issues/449

**Comment by Kevin-FF-USA** [comment]
Hello @IPOLLO-OFFICIAL!

Just a friendly ping - there is some additional information needed in order to finalize, **can you please follow this link to complete by April 15th?**
[Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)

**Comment by IPOLLO-OFFICIAL** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebtdbjv3jsv5divzra7pk7psnhajgauy7pokxgpz5e5oamb3t477u
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebtdbjv3jsv5divzra7pk7psnhajgauy7pokxgpz5e5oamb3t477u

**Comment by galen-mcandrew** [comment]
@IPOLLO-OFFICIAL Can you please verify your Ledger address that you would like to use as a notary? We received a different address in the form that you submitted, compared to here.

**Comment by galen-mcandrew** [comment]
Can you please provide some details about your relationship with these three addresses:

> f1iyqehvamuqwicm7zhd6jc5wr4re2p5yfkzsuwdi
f1t5aeedonkpewe4qye4swbewx5fakrvo5nsdceci
f1xs26csaa2sh562tqfx2tic2vfzn525nhohrc2ea

Seeing some transactions and interactions between your address and these three, along with the address in other notary applications: [Pow Power](https://github.com/filecoin-project/notary-governance/issues/447), [NFTStar](https://github.com/filecoin-project/notary-governance/issues/444), [ND Labs](https://github.com/filecoin-project/notary-governance/issues/449), [IPOLLO](https://github.com/filecoin-project/notary-governance/issues/439), & [Bitrise Capital](https://github.com/filecoin-project/notary-governance/issues/443).

**Comment by IPOLLO-OFFICIAL** [comment]
@galen-mcandrew Hi，Galen。Ipollo, as a team established in 2015 years, has been focused on  the field of BTC and ETH, and is now also the leading company in this field.  I strongly believe that  you are not unfarmiliar with Ipollo, because you can find "Ipollo" this brand in many industrial information and events. Since 2018, IPOLLO has been dedicating on the FILECOIN ecosystem and launched several conferences related to decentralized storage in 2019 and 2020. During the Filecoin space race, IPOLLO's R&D team conducted a overall  research and test of the hardware required by FIL.  At the end of 2020, we officially launched IPOLLO Black Steel (IPOLLO DARKSTEEL http://ipollo.com) series) and intended to provide a global and high quality hardware for storage service providers in the FIL ecosystem.
Black Steel is exhibited worldwide as one of IPOLLO's main series, along with IPOLLO B-Series (BTC) and E-Series (ETH) servers. We have presence in Asia, USA, Canada and Europe. IPOLLO wants every one of our customers to believe that FIL is as great as BTC and ETH. We also would like to work with many partners in this field to build the FIL ecosystem, and we are looking forward to becoming a notary of FIL and making contributings to the ecosystem. We still have a lot of things to grasp on the way to the notary, and we hope there would be more hands when we are in need.Thanks！

**Comment by IPOLLO-OFFICIAL** [comment]
@Kevin-FF-USA 
Hey, confirmed here: 
My slack handle is @Ipollo 
Ledger address: f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri

**Comment by iPollo** [comment]
> 

What?

**Comment by IPOLLO-OFFICIAL** [comment]
Hi, @galen-mcandrew @Kevin-FF-USA 
Ipollo's information：
1. Ipollo LDN address: f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq
2. Nano Labs is the holding company of Ipollo. We operate completely independently of each other. Address for Nano Labs: f1zxmwo3kwapc6axatwuia4lsowvpasco3znfbuvi
3. We don't have any other business cooperation with NDLabs. However, NDLabs has recommend some sps for us and invited us in LDN application. 
Thanks.

**Comment by cryptowhizzard** [comment]
Hello,

I strongly object moving forward here. There is a very long discussion going in slack about this application and why we should not do this.

https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1654530346802849

I would recommend to merge these and keep one notary per organisation (NDlabs in this case). 

![B0BCE17F-973E-4AD5-808C-22AA1DDB2148](https://user-images.githubusercontent.com/36404435/177009983-7e0e26c5-493a-4a61-ae82-1eea5a031578.png)

**Comment by IPOLLO-OFFICIAL** [comment]
Hi, @cryptowhizzard 
We know that NDLabs has the ability to be a notary, but Ipollo also has such ability to be a notary.
Ipollo has also contributed a lot to Filecoin network, so we strongly disagree with your suggestion that others can replace us.
thanks！
