### ISSUE TITLE
[Notary Application] Cabrina Huang

### ISSUE THREAD

**Issue by NiwanDao** [filecoin-project/notary-governance#440]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Cabrina Huang
- Affiliated organization: self-employed
- Website / Social Media: 
- On-chain address to be notarized (recommend using a new address): f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
- Region of Operation: Greater China 
- Use case(s) to be supported: Web 2.0 Applications,Web 3.0 / Decentralized Applications, Scientific Data
- DataCap requested for allocation (10TiB - 10 PiB): 5 PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
1. Participated in Filecoin as SP since Mainnet with minderID f022289, f039940. 
2. Engaged in Space Race, Slingshot, and Slingshot Restore. 
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Around 22000Fil staked and available in Storage Provider.  (f039940, f022289)
Around 5000Fil available from the exchange.

```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

```
1. Engaged in Space Race, Slingshot, and SlingshotRestore.. Worked with more than 30SPs from NA, Europe, Australia, and Asia.
2. Contribute to Slingshot Curated Datasets 
3. In Development Phase with Storage Provider Reputation System. 
``` 

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
 Stay active in Github and Slack, including file bugs, and answer questions of what I know. 

```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Does not apply. My interaction with Filecoin so far is personal behavior. I will set up an organization if there is a need. 
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
N/A
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
N/A
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
LinkedIn: 
https://www.linkedin.com/in/cabrina-h-b392bb109/
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Anything that has a positive impact on the growth of Filecoin and web3. 
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.

```
My allocation goal is to ensure I grant eligible clients the appropriate amount of DataCap and with smooth onboard into Filecoin. Authenticity,  allocation fairness, client's correct usage of DataCap are the key. 

Authenticity :
1. Verify the client's basic information, including operation's registration of place and time, Business license, operation size, and industry reputation. 
2. Investigate the total amount of requested data, data type, the previous storage method, and whether it is open public or encrypted. 

Allocation fairness:
1. I am open to reviewing the application from all the regions and various data types. 
2. I will not allocate more than 30% of DatCap to the same client. 

Client usage of DataCap: 
Make sure the client has a clear, feasible plan on data generation, ways of deal-making, and SP selection from a big pool. 
If it is not the client's first-time allocation, I will refer to the client's previous DataCap consumption and ensure the deal-making is not heavily made to few SP. I will also randomly retrieve the deal to confirm the requested data is stored into Filecoin. 

Allocation Speed:
I plan to allocate 50% of DataCap within half a year. 

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A ledger that can only be accessible by me.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1. Ask the client to provide the fundamental introduction to the business entity, including but not limited to the operation size, operation year, registration country, operation regions, reputation in its industry, Business License, and any social media page. 
2. Explain the relationship between the Datacap Requester and the Business.   
3. Describe the type of the data, and provide a sample. 
4. Elaborate on the plan to onboard into Filecoin. Familiarity with deal sending?  Do you send online deal or offline deal?  Any tools you plan to use to prepare the data?  How do you find the SPs? How do you allocate your DataCap among SPs? How many copies do you intend to store?  Which geo-location will you onboard the data? 
5. Do you run an SP on your own?  If so, what percentage you plan to store yourself. 
6. Plan to avoid the DataCap waste. 

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Check client address on https://filplus.d.interplanetary.one/ to make sure the usage of DataCap is not heavily used in one SP. 

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, I will document the supporting details on the decisions I make with each client in public through Github. 

```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
A public Google Sheet that can be easily viewed by others. 
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
10 hours/week 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
I am not a previous notary. But I received DataCap Allocation from them. 

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/249
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/232
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/171
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
I did not grant DataCap to others, but I have been granted over 1PiB by other Notaries before. 
```

**Comment by galen-mcandrew** [comment]
[Cabrina Huang - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320942/Cabrina.Huang.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by xingjitansuo** [comment]
@galen-mcandrew 
Thanks for your review, I updated the Allocation Strategy, Due Diligence, and Bookkeeping plan in Notary Application.

**Comment by Kevin-FF-USA** [comment]
Hi  @xingjitansuo **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Greater China.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by xingjitansuo** [comment]
1. I confirm that the region of operation for client applications you will focus on is Greater China.  


Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

> • Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .

Acknowledged. 

> • Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 

Acknowledged. 


> • Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 

Acknowledged. 

> • No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

Acknowledged. 

> • Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

Acknowledged. 


> • Community Governance Participation: It is expected that you will participate in the program 10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 

Acknowledged. 


> Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  


Owner of Storage Provider: f039940, f022289. 

> Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

Acknowledged


> (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 

Address is f1e7q65mxmvsrtwqyujehrj7m4eo4rkqa2xhvt7ri.

@galen-mcandrew

**Comment by galen-mcandrew** [comment]
@xingjitansuo 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @xingjitansuo!

Really appreciate you filling out the acknowledgments for the Notary kickoff in this ticket. There is some additional information needed in order to finalize, **can you please follow this link to complete?**
[Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)

**Comment by xingjitansuo** [comment]
@Kevin-FF-USA 
I just received my ledger, and I update the notarized address to f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q

**Comment by Kevin-FF-USA** [comment]
We have received your information; thank you for completing that form!

We have also updated your notary address to reflect these changes.

**Comment by Kevin-FF-USA** [comment]
Hello @xingjitansuo!

We have your address on file as: f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q

We will be communicating with Cabrina Huang via Slack; if there are any other handles you wish to have included in communications, please comment them below.

**Comment by fabriziogianni7** [comment]
I updated the parent comment with the new address. this is probably the reason for this notary ledger not to have been verified.
cc @dkkapur @galen-mcandrew

**Comment by xingjitansuo** [comment]
@fabriziogianni7 @galen-mcandrew 
Notary Governance Onboarding Bot is not triggered in my case. 
I Just manually add Notary ledger verification message here for reference.

Message sent to Filecoin Network
message CID: bafy2bzaced4ixk7wgjxkibgp3cvyzs55ajrwcq7zitdav4mocf3r4223bdryu 

You can check the status of the message here: 
https://filfox.info/en/message/bafy2bzaced4ixk7wgjxkibgp3cvyzs55ajrwcq7zitdav4mocf3r4223bdryu

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Datacap Allocated
> 1PiB

**Comment by xingjitansuo** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaced6inuwnr475iojir4tb6ghgt57xutuo53wpx5qbcqqkefhcgw472
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6inuwnr475iojir4tb6ghgt57xutuo53wpx5qbcqqkefhcgw472

**Comment by xingjitansuo** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebdlqfse7gsdrcrlyixnxjjntqj5scobdocqfchmgwbojy7rucqmk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdlqfse7gsdrcrlyixnxjjntqj5scobdocqfchmgwbojy7rucqmk

**Comment by xingjitansuo** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec5nvzvm55ruzgef5tkgpl7eztktzhp5bhcyybzh5ljfuixilubca
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5nvzvm55ruzgef5tkgpl7eztktzhp5bhcyybzh5ljfuixilubca

**Comment by xingjitansuo** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedg2vjf3e6grpkgcn3lalbyuu6kzzs6usnnxvrwfgdswvsqkmvteu
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedg2vjf3e6grpkgcn3lalbyuu6kzzs6usnnxvrwfgdswvsqkmvteu

**Comment by xingjitansuo** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec7z7kakj757bqw6trv7e7o6kzf4fniv7fosoxocuyu5oc3w2sreq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7z7kakj757bqw6trv7e7o6kzf4fniv7fosoxocuyu5oc3w2sreq
