### ISSUE TITLE
Notary Applicaiton - BingHe Web3.0 Lab

### ISSUE THREAD

**Issue by MRJAVAZHAO** [filecoin-project/notary-governance#441]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: BingHe Web3.0 Lab
- Affiliated organization:  None
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address): f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
- Region of Operation: Greater China
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 10 PiB): 10 PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
BingHe Web3.0 Lab(hereinafter referred to as Binghe Lab), formerly known as Binghe Distributed Storage Lab, is a world-leading decentralized IPFS distributed storage technology research institution, dedicated to outputting professional knowledge, the latest technology public evaluation, cutting-edge distributed storage information and the best distributed storage solutions to the industry. The research results of Binghe Lab are widely used in products such as distributed storage systems, customized customer service solutions, Athena explorer, and so on. 

As early as June 2020, the team's R&D members have begun to study the underlying technology. In July 2020, Binghe Lab was officially established and upgraded to BingHe Web3.0 Lab in October 2021.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
None.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Binghe Lab was established in July 2020, but as early as June 2020, our R&D members had began to study the underlying technology. In October 2021, Binghe Lab was officially upgraded to BingHe Web3.0 Lab.

As a promoter of IPFS/Filecoin, Binghe Lab has actively carried out knowledge popularization, organized technology evaluations, outputted various types of analysis reports to the industry and held industry events. 

In  March 2021, the 2021 global computing power summit——"Peak Computing Power" , hosted by China Software Industry Association and co-organized Binghe Lab, has attracted nearly 1,000 people to participate in and more than 300,000 people watched the online broadcast.

In addition, Binghe Lab has successively reached cooperation with more than 50 enterprises, including Inventec, Sugon, Super Cloud, Qiniu Cloud, SandStone, Lexun. The scope of cooperation spans over 10 different industries, and  the market value of partners exceeds tens of billions of dollars.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Binghe Lab is a world-leading decentralized IPFS distributed storage technology research institution and established on July 18, 2020 in China. The members of Binghe Lab includes academic institutions, hardware manufacturers, distributed storage service providers, IDC service providers, ecological application companies, and industry investment funds.

In October 2021, Binghe Lab was officially upgraded to Binghe Web3.0 Lab, which further extends the scope of research and services to provide professional knowledge and solutions for the entire Web3.0 ecosystem.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
1. Social Media
Slack: BingHe Web3.0 Lab
WeChat Official Accounts: 冰河Web3实验室

2. Related Personnel
Technology Consultant: Leng Bo (@coder-lb on Slack&GitHub）
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
- ​https://www.chinaz.com/2020/0803/1166086.shtml
- https://www.jinse.com/blockchain/1049551.html
- https://www.jinse.com/news/blockchain/785622.html
- https://www.jinse.com/news/blockchain/768399.html
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Wechat official account: 冰河Web3实验室, with nearly 10,000 followers
Weibo: @熊越XiongYue (Industry consultant of Binghe Lab), with 312,000 followers
Weibo: @不胖的胖妮 (Industry consultant of Binghe Lab), with 134,000 followers
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We will not impose strict restrictions on use cases, but prefer to support developer tools, Web 3.0, Web3 DApp, Web 2.0 applications and other technology-related applications.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
What we understand the primary responsibility of a notary is to verify the validity of the client, not of data. Therefore, we will focus on clients' authenticity, influence, allocation decision, etc.

Since there is currently no good way for us to verify privacy/encrypted data, we will pay great attention to the publicity of data.

As a non-profit research institution, in order to serve more clients and maximize the scope of industry coverage, we do not limit the nature of clients.

For more effective verification, we will give priority to accepting applications from clients in Greater China or clients who are not in Greater China but choose Chinese miners.

In order to prevent fraud, our distribution strategy will be "level ladder+ stage ladder" .
Level ladder: The results were divided into 5 levels. The higher the level, the more DataCap will be granted.
Stage ladder: We will initially grant a small amount of DataCap. If no abnormal situation happens, the allocation amount will be gradually increased.

As a technology research institution, we also attach great importance to the implementation of application ecology. Therefore, we will give additional 5% to 40% of DataCap to applicants who have developed IPFS/Filecoin-related applications or have contributions to IPFS/Filecoin industry.

We have updated the Scoring Standards for DataCap Allocationin in August 2021.
https://docs.google.com/spreadsheets/d/12ItWjuddDPZpFBE84dzNJxBM24AhZHDJcWsu9RY3xG4/edit#gid=0

With regard to target amount and rate, our ideas are as follows:

We will restrict the first allocation at 10TiB and the single allocation at 20TiB. Besides, we will set an upper limit of 50TiB for a single clients.

In addition, we will daily monitor the application submission and reply them within 2 working days. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The private keys will be stored in the hard wallet and will be accessible only by the principal.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
When accepting the application, we will confirm whether they have potential miners. If so, we will ask them to clarify the miner number, allocation proportion and the source of miners; if not, we will recommend channels such as Slack to guide them to find better miners.

After approval, we will require clients to display transaction information, including miner number, allocation proportion and the source of miners, etc., and then follow up weekly on this basis.

If no abnormality is found, we will gradually expand the allocation amount in the follow-up. If there is any abnormality happens, we will send remind messeage for the first time and put the client on a blacklist for the second time（ application will not be accepted within one year）. Meanwhile, the matter will be synchronized with the PL.

In order to get more clients involved in the Filecoin network, we're not going to ask too many complicated questions, but focus on questions about the validity of clients. 
Question List:
1. Please provide organization name, business scale, social media accounts&follwers, and business license (could be sent by email);  if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&follwers, and ID card (can be sent by email);
2.When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?
3. Is there any law risk? What percentage of questions are yours?
4. Please describe your organization, such as established time, the number of employees, users volumn, the number of social media followers.
5. How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.
6. In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.
7. Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.

We may add additional questions and requests based on responses and client due diligence.

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
During the application phase, it is required to clarify the miner ID and other information. 

After the application, it is required to publish transaction information, including miner ID, allocation proportion and the source of miners, etc. , and will be reviewed at a fixed time each week.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All decisions will be made public on Github.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We will make comment on this issue and update the allocation decision form weekly.
DataCap Allocation Records：https://docs.google.com/spreadsheets/d/1G5XO5pyn97bFdB8cOXzp9s1bwXTqyj-CUy4mooP3ijo/edit?usp=sharing
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
We will participate in at least 10 hours a week, of which 2-3 hours a day will be fixed to process applications and Slack information, and we will participate in at least one notary governance meeting every month.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
https://github.com/filecoin-project/notary-governance/issues/149
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
100TiB.
```

**Comment by galen-mcandrew** [comment]
[BingHe - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8326420/BingHe.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by galen-mcandrew** [comment]
@MRJAVAZHAO  Sorry for missing this in the first round, thanks for coming to the call and letting us know!!

**Comment by MRJAVAZHAO** [comment]
@galen-mcandrew Thanks for your update.

**Comment by MRJAVAZHAO** [comment]
@galen-mcandrew Thanks for your review and hard work. We are pleased to add audit/dispute plan to our bookkeeping plan.

1. Notary team

To ensure accurate and transparent records, and to avoid audit/dispute, we will adopt and strictly follow these processes:
We will established a notary team. The team members include reviewer, assigner, calibration personnel, and external communication personnel, a total of 4 people.
a. The reviewer
To record the application information after completing the review process, record the key information of the applicant
b. Assigner(person in charge)
To Perform assignment and record
c. Calibration staff
Follow up the allocation of clients, record allocation information, and calibrate the rationality of allocation
d. External communication personnel:
If there is an audit requirement, the person will be responsible for carefully cooperating with the audit; if part of the information is uncertain, the person will be responsible for communicating with officials and clients.
The above information will be recorded in the form of an online document. After completion, the offline document will be exported and saved as an archive.

2. Recording Principles

(1) All distribution records will be made public in accordance with community norms.
(2) Get clients consent before disclosing information, and communicate with the Filecoin Plus team if it is not sure whether to disclose or if the client does not agree to disclose non-private information
(3) All information will be stored in Google docs and Github repositories for the long term.
In the event of an audit/dispute, we are ready to provide any necessary information on all allocation decisions, without violating community norms and with the client's consent. We'll check with the Filecoin Plus team in case of uncertainty.
Our allocation records will be recorded and synchronously published on Github in the form of Google Docs and it will be backed up offline. Relevant allocation records link: https://docs.google.com/spreadsheets/d/1G5XO5pyn97bFdB8cOXzp9s1bwXTqyj-CUy4mooP3ijo/edit?usp=sharing

**Comment by Kevin-FF-USA** [comment]
Hi  @MRJAVAZHAO **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Greater China.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by galen-mcandrew** [comment]
[BingHe Web3.0 Lab - UPDATED - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8373142/BingHe.Web3.0.Lab.-.UPDATED.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by MRJAVAZHAO** [comment]
@[Kevin-FF-USA](https://github.com/Kevin-FF-USA) It's really an excited news! Thanks a lot!

1.We confirm that we will focus on [Greater China Region]

2.We confirm all items below:

• Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .

• Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 

• Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 

• No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

• Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

• Community Governance Participation: It is expected that you will participate in the program 10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 

3.None.

4.We will abide by the allocation / client due diligence plan we laid out above.

5.f17t5mdzkgehygg24xk6fwdai3eoybfmfmek6l5ii

**Comment by galen-mcandrew** [comment]
@MRJAVAZHAO 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @MRJAVAZHAO!

We have your address on file as: f17t5mdzkgehygg24xk6fwdai3eoybfmfmek6l5ii

We will be communicating with BingHe Web3.0 Lab(冰河web3实验室) via Slack. If there are any other Slack handles you wish to have included in communications, please comment them below.

**Comment by MRJAVAZHAO** [comment]
@galen-mcandrew @Kevin-FF-USA @dkkapur We want to use our previous address: f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi. Thanks very much.
(Because we use the 6th address as our notary address. But we can't choose it on Fil+ APP.)

**Comment by fabriziogianni7** [comment]
I updated the parent comment with the new address. this is probably the reason for this notary ledger not to have been verified.
cc @dkkapur @galen-mcandrew

**Comment by MRJAVAZHAO** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebonj5jlhk3qxoqq4fwkn4rwgkzou2euoyk72rthvez2udxrxsou2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebonj5jlhk3qxoqq4fwkn4rwgkzou2euoyk72rthvez2udxrxsou2

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### Datacap Allocated
> 1PiB

**Comment by MRJAVAZHAO** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecb4secrims5fcfnqw3nlrcyhaocx3spcnegctpifvbsn7e5o3rvc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecb4secrims5fcfnqw3nlrcyhaocx3spcnegctpifvbsn7e5o3rvc

**Comment by MRJAVAZHAO** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebwdmsrclxi7ny66lgiki427atnnzqsqtuwosqp2qkr34wot5bdeq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwdmsrclxi7ny66lgiki427atnnzqsqtuwosqp2qkr34wot5bdeq

**Comment by MRJAVAZHAO** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebybfjmnnh3amc4k3benaucf5jq27vcnwsuz37hfgk3d24a7k5gy2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebybfjmnnh3amc4k3benaucf5jq27vcnwsuz37hfgk3d24a7k5gy2

**Comment by MRJAVAZHAO** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceczm5c4l56pz4govstgd2hhe6ndbta7xz54g6w2xevupxlezj2hfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczm5c4l56pz4govstgd2hhe6ndbta7xz54g6w2xevupxlezj2hfi

**Comment by MRJAVAZHAO** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedvd36g6l3edhnzstoqyigrn2nrzgbfhgxz6heiyyb2n45ythg3ve
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvd36g6l3edhnzstoqyigrn2nrzgbfhgxz6heiyyb2n45ythg3ve

**Comment by MRJAVAZHAO** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaced357ngemjh4jgopdbq6e5yojcn2xwh3rnga6b4zucpauwlipgpbi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced357ngemjh4jgopdbq6e5yojcn2xwh3rnga6b4zucpauwlipgpbi

**Comment by MRJAVAZHAO** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebqx2iwgp3y52ddwbet62orbz4wpuh4anq5iupwyzlktmztim4s5u
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqx2iwgp3y52ddwbet62orbz4wpuh4anq5iupwyzlktmztim4s5u

**Comment by MRJAVAZHAO** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedjo2l7yp3e44vvcwjy4glr4wcdhlwgwjnxmjahec5d3kdozifsqw
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjo2l7yp3e44vvcwjy4glr4wcdhlwgwjnxmjahec5d3kdozifsqw

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzaceb3urd7yuhadotoloew4uag2ys6qrbxgk2dsz4ldj3snobkuz744q
