### ISSUE TITLE
Notary Application - ShengZhen

### ISSUE THREAD

**Issue by Zhangyiqiang01** [filecoin-project/notary-governance#442]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:jiajun
- Affiliated organization: ZhongLianZhiYun(ShengZhen)
- On-chain address to be notarized (recommend using a new address):f1cgmf7qzy243pdrzigtibpsxbux7fqkee6s2efja
- Region of Operation: [North America, South America, Europe, Africa, Greater China, Asia minus GCN, Oceania] : GCN
- Use case(s) to be supported: [Please select from [here](/notaries/templates/README.md#definitions)]:Smart cities (weather data, urban planning data, smart transportation, smart grid data, etc.)
- DataCap requested for allocation (10TiB - 10 PiB):1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
In the past year or so, ZhongLianZhiYun has actively deployed blockchain storage business, introduced various social resources, including but not limited to governments, commercial organizations and individuals, and introduced capital of more than 300 million RMB. ZhongLianZhiYun has entered the filecoin community since 2020, with a total of more than 20Pib of packaged data, and continues to grow, and the future can be expected.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
1000000 fil
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
There are more than 100 filecoin investment institutions and individuals introduced by ZhongLianZhiYun, which has made great contributions to the promotion of filecoin in China.
In Shenzhen, ZhongLian has established six subsidiaries, including ZhongLian University, ZhongLianZhiYun, and ZhongLian Consulting, to fully deploy web3.0.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Nature: group company, 
country of registration: China, 
registered capital: 100000000RMB 
registration time: 2016
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
www.zljt168.net
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.zljt168.net/article/245362.html
https://www.zljt168.net/article/245874.html
https://www.zljt168.net/article/245967.html
https://www.zljt168.net/article/245976.html
https://www.zljt168.net/article/245977.html)
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://twitter.com/ZhongLianZhiYun
https://twitter.com/ZhongLianShenZhen
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
https://farmersworld.medium.com/
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We will support various use cases to ensure diversity. Based on the large layout of ZhongChain, we will focus on the use cases of blockchain data storage, especially the application scenarios related to IPFS.
Now, our server data has been directly stored on ipfs supported by filecoin, which provides a friendly application interface for users to store data on ipfs, and provides support for actively exploring the implementation of related applications of filecoin.
At the same time, we will try to avoid junk data from entering the filecoin network.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
In making the plan, we will consider the following factors:
* Reputation of the organization
* Scale of allocation
* Frequency allocation
* Safety Precautions
* Transparency of customers
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
* For due diligence on public datasets, we will look for strong evidence that they have a good maintenance foundation and a high reputation in their field.
* For due diligence on blockchain data, we will investigate the authenticity and feasibility of their requirements based on our experience in the development of multi-chain wallets.
* For due diligence on Web3 data, we will use our experience in operating DappStore to investigate the DApp team, product planning and implementation.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
The key allocated to the DataCap is protected on the multi-signature hardware wallet.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
email or telephone
We will have focal point to answer any questions through email and telephone.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
https://github.com/users/Zhangyiqiang01/projects/1
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
50 hour/week
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
N/A
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
N/A
```

**Comment by galen-mcandrew** [comment]
[ShengZhen - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320943/ShengZhen.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
We are very sorry to let you know that this application was not selected in this round of Notary Elections.  

Each application was scored according to the Rubric and [assigned a Scorecard](https://github.com/filecoin-project/notary-governance/issues/394). That score was then applied for each of the [geographic regions and the top scored applications were selected](https://github.com/filecoin-project/notary-governance/issues/479). 

We are humbled by your commitment, and grateful for your interest in the Filecoin Plus program. Looking forward to seeing you in the program and hope you resubmit in the future elections.

Should you have any questions please feel free to raise here, or DM me in Slack @Kevin_FF
