### ISSUE TITLE
[Notary Application]NFTstar

### ISSUE THREAD

**Issue by NFTStar1** [filecoin-project/notary-governance#444]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Vito
- Affiliated organization: NFTstar
- On-chain address to be notarized (recommend using a new address):f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy
- Region of Operation: [North America]
- Use case(s) to be supported: [General]
- DataCap requested for allocation (10TiB - 10 PiB): 1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
The NFT collectibles minted and traded on the NFTSTAR platform will be stored on the IPFS and Filecoin networks to enhance the security of NFT products with decentralized storage technology;

As a bridge to promote fil to establish key strategic relationships in Asia, nftstar not only helps fil to promote geographical diversification, but also promotes the diversification of fil's usage scenarios in different fields. 

In addition, NFTSTAR also cooperates with Polygon and Filecoin development team Protocol Labs in GameFi projects.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
N/A
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
N/A
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
The9 Limited (The9) is an Internet company listed on Nasdaq in 2004. The9 aims to become a global diversified high-tech Internet company, and is engaged in blockchain business including a Non-Fungible Token platform NFTSTAR. 

NFTSTAR is a NFT community and trading platform for users to purchase, trade, and interact. The major transaction contents of the platform are NFT collections developed with global superstar licensed IPs. Each NFT collectible has a unique record on the blockchain, and the users will obtain the ownership of the unique NFT collectible through purchase on the platform, or through trading on NFTSTAR’s marketplace. NFTSTAR will accept general payment methods such as credit cards to make it easy for global users to participate.

The NFTSTAR community platform will cover superstars in various fields, including but not limited to sports, entertainment, art and celebrities in different industries. NFTSTAR community platform aims to create a significant portal to the future metaverse through superstars’ NFT collections, trading, and community interaction.

NFTSTAR has announced several partnering stars including the NFL football star Christian McCaffrey, Portuguese football legend Luís Figo, Korean football star Son Heung-Min, and two-time NBA MVP winner basketball star Giannis Antetokounmpo and his three brothers. Until November 19, 2021, NFT community and trading platform NFTSTAR (www.nftstar.com) has proliferated to 180,000 pre-registered users from 176 countries. 
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
www.the9.com 
www.nftstar.com
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```

https://www.jinse.com/lives/277720.html
https://www.jinse.com/lives/277875.html
https://www.jinse.com/lives/278557.html

https://m.chinaipo.com/news/199823.html

YouTube:
https://www.youtube.com/watch?v=2asn3jWTFOU
https://www.youtube.com/watch?v=E0Pl5_Ytb3c

https://www.prnewswire.com/news-releases/the9-limited-announced-its-nftstar-is-planned-to-be-officially-launched-on-december-17-global-pre-registered-users-exceeded-180-000--301428951.html

the9：
https://www.the9.com/cn/news-detial.html?act=new&articleId=579

panews：
https://www.panewslab.com/zh/sqarticledetails/1640090242566871.html
https://www.panewslab.com/zh/sqarticledetails/1637223737125297.html
https://www.panewslab.com/zh/sqarticledetails/1632373864135377.html
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter：THENFTSTAR（follower：20094）
Twitter：The9NCTY（follower：157）
Twitter：ZHUTHE9（follower：10821）
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
General, especially NFT related datasets, and will also support celebrity information including but not limited to sports, entertainment, art and different industries.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
In order to make more effective data to the network and make the data diverse and effective, the strategy we develop mainly depends on the data type. 
Firstly, data types will account for 40%.
We will judge data based on: 
//1, data type; 2, data rarity; 3, data volume; 4, future data storage capability //
Secondly, we will confirm whether the client is reliable and trustworthy, which will account for 20%.
The rules for client is similar to the process of reviewing notaries, but more rigorous:
//1.Organization basic information, 2.Github account, 3.association with Filecoin//
After confirming that the client is reliable, we will check whether the data description submitted by the client is consistent with the sample data they provided.
In the case that the two subjects are equally qualified with same score, the data that meets the requirements will be given priority for approval
The allocation strategy of customers will account for 40%,including //1.miners amount, 2.miners distribution 3.retrieval frequency 4.transparency//
The table of allocation strategy link: https://docs.google.com/spreadsheets/d/1IIbJiT27XrAIltytS_64Q5YilmqoeAPY/edit?usp=sharing&ouid=114673061298272060233&rtpof=true&sd=true

After the first step of review is passed, and the datacap is allocated to client, we will continue to follow up, including
//The concentration of miner; the number of deals; whether to start storing in time...//
There will be another table as a standard for the track record as follows:
https://docs.google.com/spreadsheets/d/1Cq249kHWsBO3RvWHAtZRdKO5vrFU6rGA/edit?usp=sharing&ouid=114673061298272060233&rtpof=true&sd=true
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We have a cooperating company, SlowMist, to do the custody of the hardware wallet, which can be sufficiently secure.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1.For the organizational client, we will conduct inquiries and audits through external process, such as: Twitter, LinkedIn. We will try our best to find out the contact information of the official contact person of the organization, and ask whether the organizational client has actually submitted the application. What’s more, Is there any blockchain relevance for organizational client? If yes, please provide proof?
In addition, for individual applicants, we will make public inquiries in Github, such as: Do you have enough knowledge about the FilPlus project? Where did you learn about this project? What are your thoughts on the entire ecology of Filecoin? etc. to ensure that the client is really wants to do something good for Filecoin.
2.We will confirm whether the client has potential miners. If there is, we will ask them to specify the number of miners and the distribution ratio; if the client passes the first step, we will monitor whether they conduct the right transactions according to the information submitted during the application in the subsequent allocation stage. After each application for DataCap is used up, we will ask the applicant to provide detailed usage description, including miner ID, storage ratio, timestamp, data content, etc., and conduct regular inspections based on the disclosed information.
Also, questions about allocation strategies will also be asked, like: Are there additional tools to ensure consistent allocation of transactions? Can it be public in network? Do you understand the principles of the ideal allocation strategy for the FilPlus project? If you understand, please give a brief overview.
If there are obvious exceptions, we will ask and warn through Github. In the next allocation stage, if it has not been fixed in time, it will be blacklisted by us and public to everyone, no longer cooperating.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will encourage customers to allocate Datacap to at least 5 miners to increase the decentralization of the network. If a client's allocation is too concentrated, we will issue a warning and ask them to explain why. If the customer fails to submit a good reason and continues to concentrate allocation, then we will reject the customer's next allocation request, and public the customer's application in the community to inform everyone that this customer is not trustworthy. Conversely, if a client's applications and allocations achieve the diversification we hope and actually increase the effectiveness for network, then their next application will be easier and they will get more credit.

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We make all distribution records public and keep them continuously and updated to ensure everyone on the network can see them. And we welcome everyone to review our approvals. This will promote the improvement of network efficiency. At the same time, if necessary, we will also supervise the fairness of signatures with other notaries.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
A google sheet, and will be published in Github.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
Probably 10 to 15 hours a week in making allocations. 
The time we're talking about here doesn't include the time we spend in our day-to-day community engagements. We will follow the progress of the community on a daily basis. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
N/A
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
N/A
```

**Comment by galen-mcandrew** [comment]
[NFTStar - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320950/NFTStar.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by NFTStar1** [comment]
@galen-mcandrew Thanks for your scoring. 
Here are some corrections and additions to the feedback.

**1. Time Commitment**
2/16/2021 The9 SignedaUS$10 million Framework Agreement on the Purchase of Filecoin (FIL) Mining Machines
https://www.the9.com/news-detial.html?act=new&articleId=513
3/30/2021 The9 Signed Filecoin Mining Machine Purchase and Hosting Agreement to Enhance Filecoin (FIL) Mining
https://www.the9.com/news-detial.html?act=new&articleId=533
9/23/2021 The9 Limited, Polygon, and Protocol Labs Announced Ecosystem Collaboration on NFTSTAR and GameFi Play-to-earn Projects
https://www.the9.com/news-detial.html?act=new&articleId=567
Also, in the blog of “Filecoin in 2021”, Nftstar was mentioned in the part of “Asia expansion”. 

**2. External Reputation**

**The9 stock num (NCTY）**

![image](https://user-images.githubusercontent.com/96470134/159894203-364733fe-4057-4e36-8c1f-1b25f1e16e41.png)


**3. Bookkeeping plan**
All allocation decisions will follow the standards published on Github.
Any challenges to allocation decisions should be discussed openly on GitHub and slack. 
If the notary cannot provide a compelling reason, a dispute resolution application may be submitted to the notary governance after 14 calendar days from the date of the original challenge.
After submitting a dispute resolution application, the notary governance can assign an arbitrator among the root key holders to resolve the dispute.
Depending on the arbitrator's decision, a hearing may be held within 30 calendar days of the application for dispute resolution.

If there is anything else needed, please contact me.

**Comment by dkkapur** [comment]
Hi @NFTStar1 - thanks for sharing this! Scores are being updated based on the above information. One question I have for you - I see that NFTstar is registered as a Hong Kong company, but you are applying as a notary in NA. Can you confirm that you have operations in North America and will be focused on serving North American client applications?

**Comment by NFTStar1** [comment]
@dkkapur Our company is listed on NASDAQ. Our business covers around the world and the US business is now our key project for NFTSTAR. 
Yes, we confirm that we want to focusing on serving NA applications.

**Comment by Kevin-FF-USA** [comment]
Hi  @NFTStar1 **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is North America.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 10-15 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by galen-mcandrew** [comment]
[Vito - UPDATED - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8373168/Vito.-.UPDATED.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by NFTStar1** [comment]
Hi! @Kevin-FF-USA

Please confirm that the region of operation for client applications you will focus on is Asia minus GCN.  

**Confirmed**

• Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .

**Confirmed**

• Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 

**Confirmed**

• Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 

**Confirmed**

• No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

**Confirmed**

• Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

**Confirmed**

• Community Governance Participation: It is expected that you will participate in the program 20 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 

**Confirmed**

Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

**None**

Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

**Yes, we will abide by the plan**

(If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 

**f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy**

**Comment by galen-mcandrew** [comment]
@NFTStar1 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @NFTStar1!

Just a friendly ping - there is some additional information needed in order to finalize, **can you please follow this link to complete by April 15th?**
[Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)

**Comment by NFTStar1** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceauu4dzzx2rqd6wmtzvwbn2x7uk7ehpxpuv33hj3vmv67dohgutug
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceauu4dzzx2rqd6wmtzvwbn2x7uk7ehpxpuv33hj3vmv67dohgutug

**Comment by galen-mcandrew** [comment]
@NFTStar1 Please confirm which Ledger address you would like to use, since we have received two conflicting addresses.

Is f1c36q3bpodeddiers557j6e2mafw3oglitx56vty the correct one? 
Or is f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy the one you'd like to use?

**Comment by cryptowhizzard** [comment]
@galen-mcandrew 

There is an outstanding request for clarification regarding selfdealing and datacap requested by @NFTStar1 

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/177

May i recommend to pause this application parallel to the other issues untill @dkkapur questions are answered?

**Comment by galen-mcandrew** [comment]
Can you please provide some details about your relationship with these three addresses:

> f1iyqehvamuqwicm7zhd6jc5wr4re2p5yfkzsuwdi
f1t5aeedonkpewe4qye4swbewx5fakrvo5nsdceci
f1xs26csaa2sh562tqfx2tic2vfzn525nhohrc2ea

Seeing some transactions and interactions between your address and these three, along with the address in other notary applications: [Pow Power](https://github.com/filecoin-project/notary-governance/issues/447), [NFTStar](https://github.com/filecoin-project/notary-governance/issues/444), [ND Labs](https://github.com/filecoin-project/notary-governance/issues/449), [IPOLLO](https://github.com/filecoin-project/notary-governance/issues/439), & [Bitrise Capital](https://github.com/filecoin-project/notary-governance/issues/443).

**Comment by NFTStar1** [comment]
Hello， @galen-mcandrew 
NFTSTAR is controlled by Nasdaq Listed Company “The9 Limited”, and now we control these private keys below : f1c36q3bpodeddiers557j6e2mafw3oglitx56vty, the other address that mentioned is not ours.

view more about NFTStar:

Twitter：https://twitter.com/THENFTSTAR
Official Website：https://www.nftstar.com/
Son HeungMin Collection：https://opensea.io/collection/hm-son
Neymar’s related tweet: https://twitter.com/neymarjr/status/1506646931073814532

**Comment by NFTStar1** [comment]
Hello,  @dkkapur  @galen-mcandrew  @Kevin-FF-USA 
these three addresses belong to the SP that does sealing for us, and they transferred some $FIL to my address to activate the sealing.
We have no ideas about their relationship with the rest of the entities. NFTSTAR just acts as a client for Roingying. Rongying provides us with storage services.

Also, we disclose more relationships of our company on the list. Waiting for your comments to see if we need any more updates.
