### ISSUE TITLE
[Notary Application] NonEntropy

### ISSUE THREAD

**Issue by junyaoren** [filecoin-project/notary-governance#445]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form.

## Core Information

- Name: Junyao Ren
- Affiliated Organization: NonEntropy Tech
- Website / Social Media:
- On-chain Address(es) to be Notarized: f1xzff5xup63o5sygr2swp4zvcajg54lotliimdty
- Region of Operation: Greater China
- Use case(s) to be supported: Web 3.0 / Decentralized Applications, Web 2.0 Applications, User Content, Scientific Data, Media & Entertainment
- DataCap Requested: 300TiB

*Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!*

### Time Commitment

Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects, or contributions (with links).

```
We have been with IPFS/Filecoin since 2017. Initially, we studied IPFS and aimed to let more people be aware of this new decentralized storage solution by hosting online/offline meetups, translating related materials, and publishing blogs. We established our company in both China and Japan to promote IPFS/Filecoin and we have cooperations with governments, enterprises, and colleges. Then we also actively took part in testnet, spacerace, and mainnet as miners. Besides those, we participated in Slingshots (music prize, ranking 11) and Filecoin Frontier Accelerate to seek the ecology applications landing. Below is a list of projects we lead:

We Rave You (Music Prize in Slingshots 1)
Nonentropy Intelligence Drive (Ranking 11 in Slingshots 1)
Candlekeep (Filecoin Frontier Accelerate)

One of our Filecoin technical document translations published in March 2018:
https://twitter.com/mitchellxsoo/status/970853272788463617

Some of our miners: f0133509, f01111111, f010056, f020331, f021525, f019074, f0107916, etc. Our miners are distributed in Mainland China, Japan, Vietnam, Hongkong China, Singapore, South Korea, and Malaysia.
```

### Stake Exposure

Please cite the total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

```
We have more than 1 MM FIL that most are pledged as collateral or locked in miners above.
```

### In-protocol Reputation

Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow.

```
I have actively taken part in IPFS/Filecoin related research and promotion since 2017. 

In earlier days, we translated a large amount of IPFS/Filecoin documents https://twitter.com/mitchellxsoo/status/970853272788463617 and hosted tens of community meetings.

On Lab Day 2018, I made a presentation (titled "When IPFS/Filecoin meet China") and took part in a panel session. (https://www.youtube.com/watch?v=KONGvS51cJM, https://www.youtube.com/watch?v=ztPi2e21Mw4)

After Lab Day, we kept close interactions with Protocol Labs and kept communicating on technical and community topics. I met several times with Ms. Michelle Brous and Jeromy in person when I was in Bay Area.

We make videos to educate the public about how IPFS, Filecoin, and Blockchain work.
https://www.youtube.com/channel/UCBSLrIJPC-_0J0QIOJVSL8A

I have also promoted government cooperation in IPFS applications landing. http://m.nyzshzzx.com/index.php?m=content&c=index&a=wap_show&catid=3&id=1461

We built collaboration with Osaka University on Filecoin research.
https://prtimes.jp/main/html/rd/p/000000002.000072230.html
https://re-how.net/all/1056398/
```

### In-protocol Security

Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions.

```
We have discovered and fixed several bugs in lotus code, in the form of Github pull requests, slack discussions, and DM's. Here are some of the accepted PRs we have submitted. 
https://github.com/filecoin-project/lotus/pull/6623
https://github.com/filecoin-project/rust-fil-proofs/pull/1535
https://github.com/filecoin-project/lotus/pull/3927 
```

### Organizational Reputation

Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

```
Established in 2017 and registered in early 2019, NonEntropy Tech. Co. is a technical team of about 80 people, including the blockchain technology team, operation, and maintenance team, and application development team that are located in China and Japan.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

```
Official Website:
 https://www.nonentropy.com/ (in maintenance)
 https://nonentropy.jp/

WeChat Account:
 逆熵科技

Youtube:
 https://www.youtube.com/channel/UCBSLrIJPC-_0J0QIOJVSL8A

Official Twitter account:
 https://twitter.com/NonEntropyTech
 https://twitter.com/Nonentropy_
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

```
The team of NonEntropy Tech. has been all in IPFS/Filecoin ecology since 2017, and the main work and achievements are as follows.
1. Translated a large number of technical documents.
2. Multiple MeetUp sessions were conducted.
3. IPFS/Filecoin technology sharing has been carried out in Xiamen University, Xiamen Institute of Technology, Overseas Chinese University, and Northeast University.
4. Since 2018, we have tried to develop many IPFS-based applications, including Distributed cloud drive (2018), the Distributed multimedia player (2018). Onchain solution for administrative data (2019), Short & live video platform (2019), Distributed storage solution for smart agriculture data (2020), Cloud courses assistant app (2020).
5. Based on the scarcity of IPv4 addresses in China's network, we explored a variety of nat solutions and exchanged them with Jeromy (Why) in 2018.
6. Optimized the Filecoin code to make it easier to use for large-scale mining.
7. Participated in Filecoin Frontier Accelerate with edtech application Candlekeep.

Some links about our work:
https://twitter.com/chaintalktv/status/1285885716367466496
https://twitter.com/Filecoin/status/1349151708274974723
https://prtimes.jp/main/html/rd/p/000000002.000072230.html
https://finance.ifeng.com/c/85MSaH1GJLI
https://www.ccvalue.cn/article/414701.html
https://www.huoxing24.com/videoDetails/20201119182933736564
https://www.youtube.com/channel/UCBSLrIJPC-_0J0QIOJVSL8A
```

### Individual Reputation

Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.

```
https://www.linkedin.com/in/junyaoren/
https://twitter.com/Jren_abc
```

### Use Case Diversity

(Optional) Any additional information you'd like to share about the use case(s) you plan to support?

```
1. Some hot and latest blockchain applications appear recently like NFT, Defi, and GameFi. We are very willing to allocate DataCap to these projects.
2. Some music application data. (In addition to regular audio data, we also hope to use Filecoin to store some music data, especially some exploration and non-mainstream music data, such as Metal Archives https://www.metal-archives.com/)
3. Some scientific research data. (We have contacted Beidou Satellite Data Analysis Center and hope that they will try to store a small amount of non-sensitive data in Filecoin)
4. We will focus on the practice of importing Web 2.0 data into Filecoin. It is also keen to explore how to use the characteristics of IPLD and Multiformats to establish a strong extensible semantic network and deploy applications in Web 3.0 networks.
```

# Allocation Plan

### Allocation Strategy

How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and the rate at which you'll allocate DataCap.

```
Just as Filecoin is exploring a new way to support the operation of blockchain through useful work, we have no experience in how to allocate DataCap, so we will gradually establish a good DataCap allocation mechanism by continuous summary and improvement and continuous iteration. In the overall work, we will follow the working principles of PDCA: Plan → Do → Check → Act → Plan → …, and promote the gradual improvement of the mechanism through continuous cycle improvement.
Applicants will be scored using this rubric form:  
Application Form with examples[https://docs.google.com/spreadsheets/d/14xLS4HucccTDkx2JK60uYBa-q6UiJrZo/edit?usp=sharing&ouid=114786731006772610377&rtpof=true&sd=true]
We will publish our DataCap management process, which customers can use to complete their applications:  
Flowchart[https://drive.google.com/file/d/1aTtr4W-MawoKB7O9ozrnZdLC_eU9Lhll/view?usp=sharing]
Data legal compliance is the priority we consider. With this in mind, the allocation strategy will determine the DataCap quota a customer can receive based on the following elements:
1. Basic organizational and personal information of customers.
2. Development planning and completion of the project.
3. Verifiability of data authenticity and validity. (We will regularly download the relevant data for spot checks, so there are certain requirements for the openness of the data)
4. The customer's historical DataCap usage.
5. We will also evaluate the applicability of the data to Filecoin storage and whether it will contribute to the Filecoin ecosystem based on the scenario of the data use case.
6. We will allocate DataCaps to applicants in installments and judge whether applicants can make good use of these DataCaps. For high-quality projects, we are also willing to increase the amount of DataCap allocation.
7. We will plan the allocation of DataCap in phases based on the DataCap management cycle. For example, if 300 TiB is allocated in half a year, 50 TiB will be granted every month, which will be adjusted flexibly according to the situation.
8. Applicants with less than the minimum score will not be eligible for a DataCap allocation.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
As blockchain practitioners, we fully recognize the importance of private keys, so we have developed internal dedicated offline signature wallets and multi-signature wallets, and have formulated strict internal private key management protocols. If we become a notary public, we will also use this set of management tools/protocols to ensure the security of private keys and the fairness of decisions.
```

### Client Due Diligence

How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them?

```
We collect the following information to determine eligibility:
1. Registered capital of the company, establishment time, team/personal background, and reputation.
2. Project planning and project progress.
3. Data scale and data redundancy strategy.
4. The type of data stored.
5. Customer's understanding of the impact of DataCap distribution on the Filecoin network (as a supporting reference).
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.

```
We will set up a dedicated database to record all the storage deals initiated from the application address, and regularly analyze and summarize the collected data to ensure that the applicant uses DataCap fairly and impartially.
```

### Bookkeeping Plan

Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both?

```
Of course, we will retain all the information and accept the relevant audit. All DataCap-managed information is managed hierarchically.
1. For information that can be made public in real-time, we will make it public on a special web page. As also stated earlier, we will announce the application rules on Github, and all applications should be initiated with an issue for records, and so that we can track our conversations with applicants. 
2. For information that is not suitable for disclosure (for example, we may download some application data in data authenticity verification), we will issue corresponding inspection results.
3. Our management of all information will be as open and transparent as possible based on abiding by relevant laws and regulations and respecting the privacy of data owners.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?

```
Github, Google Sheet.
```

### Engagement in Program

How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.

```
3-5 hours per week on average.
```

### Past allocation

Have you previously received DataCap to allocate before? If so, please link to any previous applications.

```
No.
```

Cumulatively, how much DataCap have you previously successfully allocated?

```
No. 
```

**Comment by junyaoren** [comment]
@Kevin-FF-USA  Hi, just want to make sure this application is not missed and is good for evaluation(since I notice you have self-assigned all other applications but missed this one)

**Comment by Kevin-FF-USA** [comment]
Thanks for the tag @junyaoren  - Confirming receipt and will be scoring this week and next. Will ping back to this issue if we need anything additional, but application is received!

**Comment by galen-mcandrew** [comment]
[Junyao Ren - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8326418/Junyao.Ren.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by junyaoren** [comment]
> [Junyao Ren - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8326418/Junyao.Ren.-.Round.3.Notary.Election.Scorecard.pdf)

@galen-mcandrew @Kevin-FF-USA Thanks for your efforts on scoring our application! In response to your questions, we would like to add some follow-ups and supplementations. We hope you can take a look, re-evaluate our application and hopefully update our score. Thank you.

**Comment by junyaoren** [comment]
Please confirm that the region of operation for client applications you will focus on is Greater China.  
- Confirmed

Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

• Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
- Confirmed

• Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
- Confirmed

• Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
- Confirmed

• No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
- Confirmed

• Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
- Confirmed

• Community Governance Participation: It is expected that you will participate in the program 3-5 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
- Confirmed

Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  
- Owned addreesses: f0133509, f01111111, f020331, f019074, f010056, f0107916, f01111110, f021525, f01111112

Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  
- We will abide by the allocation / client due diligence plan we laid out above

(If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
• If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x) 
- f1y5rllqjmhqj6ppz64ixl42pqe7hua3nzjbd5bpy

**Comment by galen-mcandrew** [comment]
@junyaoren 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by junyaoren** [comment]
@galen-mcandrew  We have submitted the form.

**Comment by galen-mcandrew** [comment]
@junyaoren Please confirm your ledger address using the verification tool in the [Fil+ Registry app](https://plus.fil.org/).

[Here](https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing) is a troubleshooting guide.

Thanks!

**Comment by junyaoren** [comment]
Hi Galen,

The nano X we ordered came all the way from Paris to Shenzhen but was held
by customs clearance authorities. DHL had to return the parcel to Ledger.
This might be a new policy from the Chinese customer. So I wonder if there
are or will there be any workarounds for such an issue?

Thanks,
Junyao

**Comment by galen-mcandrew** [comment]
@junyaoren Sorry to hear about the hurdle getting your ledger! At this time, our registry app uses that physical device for signing in and approving messages. We hope to build more supports in the future, but those are not yet in scope. 

To my knowledge, there is not a way to 'import' another existing address (for example, one created using Lotus) onto a Ledger device. So, if you do not have your Ledger yet, then I think we should wait to award the DataCap to another address, since we would then have to adjust everything and remove that DataCap to transfer to a new notary ledger address.

In the meantime, you can still help us investigate and audit clients, such as large datasets. You can also join our governance calls and engage in the different community discussions!

**Comment by galen-mcandrew** [comment]
@junyaoren Any update on getting a ledger device and setting up a wallet address that way?

**Comment by junyaoren** [comment]
Hi Galen, thanks for asking! My colleague in Singapore has received the
ledger device, and I am trying to guide him to set up an address. Will get
back to you as soon as he gets back to me.

**Comment by panges2** [comment]
Hey @junyaoren,

Just wanted to bump on this again, did your colleague in Singapore manage to set up a wallet address with your ledger?

**Comment by junyaoren** [comment]
Hey, thanks for asking. We apologize for having so much trouble getting the
ledger. Our colleague in  Singapore could not figure out how to set up an
address with the ledger.

The good news is that one of my other colleagues has been able to take the
ledger back to China after visiting  Singapore for the FIL- Singapore
meetings, though he is currently in quarantine because he unfortunately got
COVID-19 during the meeting. So I think we are really close to getting the
ledger and setting up an address, as soon as the quarantine time is over.
I'll let you know immediately when I do so. Thank you very much for your
support!

Best,
Junyao

**Comment by junyaoren** [comment]
Hey, we have finally got our ledger and set up a new notary address on it: f1xzff5xup63o5sygr2swp4zvcajg54lotliimdty. I have updated the address on the GitHub issue as well. Could you help us proceed with the following steps? Many thanks! @panges2 @Kevin-FF-USA
