### ISSUE TITLE
Notary Application：DeFIL

### ISSUE THREAD

**Issue by Edenwu777** [filecoin-project/notary-governance#446]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Eden
- Affiliated organization: DeFIL
- Website / Social Media: 
- On-chain address to be notarized (recommend using a new address): f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
- Region of Operation: Greater China
- Use case(s) to be supported: Individual user storage, enterprise user storage, public project storage, scientific data sets, video and music
- DataCap Requested: 1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
DeFIL is a decentralized Filecoin lending and financial services platform designed to bridge the gap between FIL's primary and secondary markets. It provides miners with access to pledged currency or risk hedging through the issuance of standard computing power tokens. It also provides ordinary investors with access to FIL mining and benefits to existing FIL users.

The DeFIL platform is funded by IPFS Eco-Fund, Fenbushi Capital, FBG Capital, Gate Labs, ZB Capital, and others. The platform's TVL once reached a maximum of $250 million, pledging FIL amounted to 1.667 million, and lending FIL amounted to 1.186 million. As the Filecoin industry's first truly decentralized financial platform, we have solved the problem of insufficient liquidity in the industry, which is a significant milestone for the Filecoin circuit.

Evidence：
https://www.jinse.com/lives/267735.html
https://www.jinse.com/lives/247059.html

2021 is a year of rapid growth for the Filecoin industry. In this year, we have held several IPFS and Filecoin talks in Chengdu, Shenzhen, Hangzhou and other cities, enabling tens of thousands of people to learn about IPFS&Filecoin. In August of that year, DeFIL won a prize at the Filecoin Grant Hackathon.

Evidence：
https://www.jinse.com/news/blockchain/1130655.html
https://www.jinse.com/lives/262689.html

We've also formed the DeFIL community to make a better place for people to learn and interact Filecoin. In the future, we will continue to work on the IPFS&Filecoin track to create more value for the industry.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
We have 663.05PiB of adjusted power on our platform and mining partners, you may search in the official website (https://app.defil.org/miners)，the following are some of the cooperative miner nodes:

https://filfox.info/en/address/f0688165
https://filfox.info/en/address/f0127595
https://filfox.info/en/address/f0123261
https://filfox.info/en/address/f0128559
https://filfox.info/en/address/f01108594
https://filfox.info/en/address/f01173170
https://filfox.info/en/address/f01173139

At present, users have deposited 350,000 FIL tokens on the DeFIL platform. eFIL is the mapping of FIL tokens on the ETH and BSC chain. You can find it on the official website:

https://app.defil.org/pools/lend/efil

(Tips: To query the website data, you need to connect wallet)
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
In 2020, we launched Filecoin lending and financial services platform DeFIL, which is expected to help dozens of miners solve the problem of pledging their coins. Miners get FIL by pledging their mining machines and computing power to the platform, and then continue to participate in Filecoin mining without having to pledge additional assets. This greatly saves the miners the cost of digging.

The platform also helps FIL owners make more money by lending FIL to miners on the DeFIL platform at a steady interest rate.

In May 2021, the maximum number of FIL tokens pledged by the DeFIL platform was 1.667 million, and the maximum number of FIL tokens lent was 1.186 million.

Evidence：
https://www.jinse.com/lives/247059.html

We have also established a community based on the concept of IPFS, serving nearly 10,000 users. Not only do we actively promote IPFS in the community, but we also talk to Filecoin officials on slack channels. The DeFIL platform has become one of the most important infrastructures in the Filecoin ecosystem.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
We made an even more important contribution to Filecoin, which is the cross-chain bridge. The DeFIL platform allows FIL holders to safely convert Filecoin from FIL to ETH or BSC in a cross-chain manner and carry out on-chain activities. This feature not only provides liquidity to the Filecoin industry, but also maximizes revenue for FIL holders.

Cross-chain bridge link:
  https://app.defil.org/bridge
Cross chain bridge use tutorial:
  https://defilofficial.gitbook.io/support-center/v/english/jiao-cheng/kua-lian-qiao/how-to-convert-efil-to-fil
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
We are a mining pool alliance formed by more than 20 large mining nodes such as FILPool and LDPool, all decisions are made by public voting. Investment institutions include Fenbushi Capital, IPFS Eco-Fund, FBG Capital, ZB Capital, ZBG Capital, Gate Labs, etc. DeFIL is a decentralized Filecoin lending and financial services platform designed to bridge the gap between FIL's primary and secondary markets.

-Registration Country: China
-Organization size: More than 20 institutions
-Time since establishment: 2020
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website：https://defil.org/
TG-CN：http://t.me/defilorg
TG-EN：https://t.me/defilorgEN
Twitter：https://twitter.com/defilofficial
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://v.qq.com/x/page/f32580b0tus.html
https://xw.qq.com/cmsid/20210831A035O100
https://www.beekuaibao.com/article/789271716885016576
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter
https://twitter.com/defilofficial
followers: 2.1K

Telegram
TG-CN：http://t.me/defilorg
TG-EN：https://t.me/defilorgEN
members: 5K
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We plan to support all use cases within the law and adjust our plans as practical conditions arise as the project evolves. For now, we will mainly support the following use cases:

1.User content (individual user storage)
2.Historical data (weather, books)
3.Media and Entertainment (Video and Music)
4.Scientific data (artificial intelligence training, geological data, autonomous driving)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We will consider the following factors while allocation the DataCap:
1.Basic customer information and industry reputation
2.Binding relationship between customer and mining machine
3.Use cases diversity
4.Scale&Frequency of allocation
5.Safety Precautions

At the same time, we will verify the authenticity of customers and the validity of data through offline audit. Conduct spot check once a month and general survey every quarter to grasp the basic information and update progress of customers in time, and then change the allocation proportion according to the investigation.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will strictly implement the allocation strategy and conduct a detailed investigation of the customer's information. For the clients who apply, we will make a file and score each client. We will distribute according to the score. It is worth noting that we will update the archives regularly. For clients who are progressing, they deserve more attention. We hope to build a healthy system in which people can make continuous progress and welcome more and more people to participate.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Customer Information and purpose of application is one of the important criteria for our audit. We conduct in-depth research on customer information and ask about the purpose of application, so that we can understand the real demand of customers and avoid the subsequent risk.

1.Research company entity information

Anyway Basic information: Company registration qualification/Business license/Information certificate, etc
Additional information: Certificate of Honor/Computer software copyright, etc

2.Investigate the company

Principal business/Product introduction/Other business
Fiscal Annual financial statement/Asset management statement

3.Signing cooperation agreements

The application form is signed and sealed by the legal person or responsible person
Submit a copy of the company's business license, etc.


We will ask the following questions:

What type of data do you want to store and for what purpose?

What are your plans for the number of miners to store the data, the area, and the assigned number of miners per miner?

What safety precautions do you have?

Do you comply with local laws and regulations and accept the miners'Terms of service?

We regularly spot check users to see if they are as well as they say.

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. We require customers to disclose their addresses, set up tracking records, and rigorously investigate the customer's stored data

2. We will have a special customer rating database, for low-scoring, poor performance of the customer will be a warning or punishment

3. For storage data diversity, high data authenticity of the customer we will improve the score, and make public praise

4. Finally, we will recruit community volunteers to participate in the monitoring
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
The final decision is made public on Github and notified to each customer in at least three ways. For customers' different opinions, we will set up a two-week publicity period, customers can submit personal suggestions, and we will hold an online meeting to make a final decision.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Github and official website.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
About 15 hours a week.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None.
```

**Comment by galen-mcandrew** [comment]
[DeFil - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320915/DeFil.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Edenwu777** [comment]
> [DeFil - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320915/DeFil.-.Round.3.Notary.Election.Scorecard.pdf)

Thanks for your reply！

**Comment by Edenwu777** [comment]
> Hi @Edenwu777 **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.
> 
> In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:
> 
> 1. Please confirm that the region of operation for client applications you will focus on is Greater China.

Confirmed.

> 2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).        
>    •	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship    .

Confirmed.

>    •	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.    

Confirmed.

>    •	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.    

Confirmed.

>    •	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.    

Confirmed.

>    •	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.    

Confirmed.

>    •	Community Governance Participation: It is expected that you will participate in the program 15 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.

Confirmed.

> 3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

Here is the list of our cooperative miners:

https://filfox.info/en/address/f0688165
https://filfox.info/en/address/f0127595
https://filfox.info/en/address/f0123261
https://filfox.info/en/address/f0128559
https://filfox.info/en/address/f01108594
https://filfox.info/en/address/f01173170
https://filfox.info/en/address/f01173139

> 4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

Confirmed.

> 5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.    

f3tbbw3vn7xnd5zkehxuvqqb54eyushqln757vr2qgvumxo5lp2mciqrbn36xhvvzdit6it6fipqycjunubuca

>    •	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: [https://shop.ledger.com/pages/ledger-nano-x)    ](https://shop.ledger.com/pages/ledger-nano-x)%E2%80%A8)

**Comment by galen-mcandrew** [comment]
@Edenwu777 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Edenwu777** [comment]
The original address submitted has been invalid. This is the latest notary's address confirmed by DeFIL：

f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea

**Comment by Edenwu777** [comment]
> The original address submitted has been invalid. This is the latest notary's address confirmed by DeFIL：
> 
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea

@Kevin-FF-USA @galen-mcandrew @

**Comment by Kevin-FF-USA** [comment]
Hello @Edenwu777!

We have your address on file as: f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea

We are communicating with DeFil and Eden Wu (DeFIL.org) on Slack. If there are any other Slack handles you wish to have included in communications, please comment them below.

**Comment by Edenwu777** [comment]
> Hello @Edenwu777!
> 
> We have your address on file as: f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
> 
> We are communicating with DeFil and Eden Wu (DeFIL.org) on Slack. If there are any other Slack handles you wish to have included in communications, please comment them below.

Thank you @Kevin-FF-USA  DEFIL is my associate's account

**Comment by DeFIL123** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacea24blybi53e775uepi3mazfylqusp74twqon3u3ygbkqkwpsyf6m
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea24blybi53e775uepi3mazfylqusp74twqon3u3ygbkqkwpsyf6m

**Comment by Kevin-FF-USA** [comment]
HI @DeFIL123  @Edenwu777 

For compliance and reporting, we need to have the full legal name of the person who will be responsible for the address connected to this application. Feel free to post here in application, or DM me in SLACK if you wish to keep that out of the public.
TY

**Comment by Edenwu777** [comment]
> HI @DeFIL123 @Edenwu777
> 
> For compliance and reporting, we need to have the full legal name of the person who will be responsible for the address connected to this application. Feel free to post here in application, or DM me in SLACK if you wish to keep that out of the public. TY

Marvin Zhang

**Comment by Edenwu777** [comment]
> > HI @DeFIL123 @Edenwu777
> > For compliance and reporting, we need to have the full legal name of the person who will be responsible for the address connected to this application. Feel free to post here in application, or DM me in SLACK if you wish to keep that out of the public. TY
> 
> Marvin Zhang

My colleague messaged you on Slack but didn't get a reply, so I replied at the top @Kevin-FF-USA

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Datacap Allocated
> 1PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacebiap7ijsecst5lcczo3gkceidhux53225g4kkmqpgqbsxlm73bou

**Comment by szalongdzyxgs** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceajlcjxxmmxludyve7jt2qivoxytj4e2qaqklc3h3gw3kk75t5wec
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajlcjxxmmxludyve7jt2qivoxytj4e2qaqklc3h3gw3kk75t5wec

**Comment by szalongdzyxgs** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebj4hhvwncdylfkrndubi7xoksajwwd47er7lrk34gncifrle4p4e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebj4hhvwncdylfkrndubi7xoksajwwd47er7lrk34gncifrle4p4e

**Comment by Defil2022** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacectvww6vnkh7fw6nszmhs7d6cweyegvgcnlhxnkestozblijxoggw
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectvww6vnkh7fw6nszmhs7d6cweyegvgcnlhxnkestozblijxoggw
