### ISSUE TITLE
Notary Application：POW Power

### ISSUE THREAD

**Issue by POWPOWER2021** [filecoin-project/notary-governance#447]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: ZHIHUI
- Affiliated organization: POW Power
- On-chain address to be notarized (recommend using a new address):f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq
- Region of Operation: [Greater China]
- Use case(s) to be supported: [General]
- DataCap requested for allocation (10TiB - 10 PiB):1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
POW POWER has been promoting the Filecoin to users in the blockchain industry in the form of evangelists and media.
On July 3, 2020, POW POWER hosted the world's first 1,000-person IPFS ecological theme summit - "2020 IPFS Ecology and Decentralized Storage Industry Summit" in Hangzhou, China, with over 200,000 offline participants and online participation. At the same time, the summit invited institutions such as Protocol Labs, Amazon Cloud, Alibaba Cloud, and JD Cloud to participate. This summit further expanded the popularity of Filecoin in the blockchain industry and attracted a large number of industry practitioners Learn about the Filecoin network.
https://play.yunxi.tv/livestream/flash?id=e1eecab932304450b9e332502dbbf490#/

In April 2021, POW POWER held 1,000-person summit in Chengdu, China - "Data Royal Future - 2021 Data and Storage Industry Summit". The number of offline participants of the summit exceeded 3,000, and the number of online participants exceeded 100,000. At the same time, the summit invited Dozens of institutions such as distributed storage track institutions and data service providers participated. The publicity of the Filecoin network at this summit was further expanded.
https://www.huodongxing.com/event/5592487124100

POW POWER has held more than 10 online summits, AMAs, offline salons and other activities for Filecoin.
https://www.huodongxing.com/go/8556390175400
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
N/A
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
POW POWER, a well-known media in the blockchain industry, reports real-time industry news and regularly holds industry summits, etc. Regularly update Filecoin's official news and project progress.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
POW POWER, located in CBD center of Hangzhou, China, is a global service platform across project incubation, Blockchain news report, Blockchain product R&D, industry sharings (exhibition/ conference/ live broadcasting/ forum...) , ecosystem construction, etc..

Attracted by Web 3.0 style of storage, POW POWER get involved in IPFS & Filecoin since 2018 for promotion,  ecosystem construction and R&D of distributed storage related product. Over 100 online & offline sharings on IPFS & Filecoin are held till now.

Following are some relative instances:
1.We have held several IPFS, Filecoin, distributed storage related summits such as the first “IPFS Ecology and Distributed Storage Industry Summit”  in July,2020， “Data & Future: 2021 Data and Storage Industry Summit” in April, 2021 and there are over 5,000 visitors for single summit. 
2.During 2019-2020, We have held over 10 nationwide blockchain related POW POWER sharings in many cities such as Beijing, Shanghai, Shenzhen, Chengdu, Hangzhou, etc.. Over 10,000 people have joined the sharings and over 1,000,000 people have viewed related news.
3.In 2020, POW POWER has held over 50 online AMA related to IPFS, Filecoin, distributed storage, in which we invite company leaders, industry KOL,etc. And more than 1,000,000 people have viewed related live streaming.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```

Twitter: @POWPOWER2020
Facebook: Pow Power
WeChat: POW POWER、POW POWER Official
Weibo:https://weibo.com/u/7444675513
Instagram: powpower_official
Github:powpower2021
Discord: POW POWER
Email: powpower2020@gmail.com
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```

https://mp.weixin.qq.com/s/C8sVvUX9mjUHyYaQQ31phw
https://mp.weixin.qq.com/s/CKQBC0C73JfLU-Fp7lzN6A
https://mp.weixin.qq.com/s/DdRRRvtlsJtCezxJbjEz5w

https://weibo.com/ttarticle/x/m/show/id/2309404618332409299098?_wb_client_=1
https://weibo.com/ttarticle/x/m/show/id/2309404616453893783653?_wb_client_=1

https://www.huoxing24.com/userCenter/570d6e96c7034b29b84146fa40413069
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
WECHAT:POW POWER(5000+)
Telegram:https://t.me/POWPOWERGlobal(5000+)
Twitter: @POWPOWER2020(1000+)
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We plan to support the following use cases
1. Video recording, video, playback of summit activities, online activities, offline activities and other activities
2. News reports, industry articles and other manuscript materials.
3. Character interview videos, live event videos, original videos and other materials.
4. Gallery material resources (PSD layered material, advertising picture material, poster design picture material, vector material, album design picture material)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Here is our strategy:
https://docs.google.com/spreadsheets/d/1T8eEzBz-LCJMSpTIdM-OVRt3r-7TTlyw/edit?usp=sharing&ouid=109592846968506244474&rtpof=true&sd=true
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We have our own DataCap allocation protection process. The detailed rules are as follows:
1. The assignment of DataCap will mainly involve three departments: the business department, the risk control department, and the finance department
2. When the business department accepts the user's DataCap application, it will conduct the first round of review of the application record
3. After the business department has passed the review, it will submit the application form in the OA system to the risk control department
4. The risk control department will verify the applicants submitted by the business department by phone call,  and transfer the OA to the finance department after the verification is passed.
5. The Finance Department keeps the assigned private key account numbers in a unified manner, and the Finance Department finally conducts a unified distribution operation
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
The post-allocation vetting of Clients will be performed regularly and constantly to avoid the allocated DataCap being abused or misused.  The fundamental principle is that the Client is obliged to spend the DataCap exclusively for the approved uses (which will be specified in our allocation decision).  
To this end, at any time of the Client’s spending the DataCap, we may ask the Client to provide:
(1)	a consolidated Content Identifier (“CID”) list for verified deals that includes deal CID and miner ID (showing how the allocated DataCap has been used);
(2)	description of the data being stored and how the data has been processed; and
(3)	instructions on data retrieval. 
(4) Pow power will randomly sample the verified transactions sent by the client on the chain, and will verify the authenticity of the data based on the transaction CID and miner retrieval. Filecoin public monitoring and auditing will also play a role
(5) Collect and score questionnaires for customers

Do you store data in one or more geographic areas?
What key features (such as fast retrieval) do you use in your storage transactions?
How do you secure DataCaps to ensure that your organization (and its delegates) are the ones who assign DataCaps?
Describe how you allocate data between miners
Does the data you store comply with local regulations and the recipient miner's terms of service?
Are there any disputes with you about your previous DataCap assignments? or any violation?
Additionally, we may use automated tools such as https://www.fil.deals/

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We mainly confirm through the application user points table established internally by POW Power. The following is our implementation process:

1. We will ask questions about the usage plan of DataCap allocation for the applied client. The more entities allocated by the user, the higher the points. (Scores from 1 to 10)
2. We will allocate a certain proportion (20%) of DataCap to the applying users, and track the usage of the customer for a period of time after the allocation, and score points according to the usage of the customer (from 1 to 10 points)
3. According to the user's condition, the second round of DataCap allocation will be made to the customer, and the ratio is the percentage of the points score (if the points are 2 points, 2% will be allocated, and the highest in this round is 20%)
4. Track the customer usage in the second round, and also score the customer usage. However, if the total points of the customer this time are less than 5 points, they will not be allocated.  (up to 30% this round)
5. In this process, if the score of each round is lower than the average of the total points, the customers in this round will not pass the DataCap allocation until the user's total datacap allocation is completed.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we will announce each round of allocation on github, and will also notify applicants by email. 
In addition, we will also publish allocation information on TG and twitter
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Github
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
20hours, anytime needs me, i will be here. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
no
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
no
```

**Comment by galen-mcandrew** [comment]
[POW Power - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320914/POW.Power.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by POWPOWER2021** [comment]
@galen-mcandrew 

For the part of individual reputation, there was a mistake. 
Our official account has more than 10k followers. 
Twitter: @POWPOWER2020 (followers:12k+)

Thank u so much.

**Comment by Kevin-FF-USA** [comment]
Hi  @POWPOWER2021 **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Greater China.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 20 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by galen-mcandrew** [comment]
[ZHIHUI - UPDATED - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8373152/ZHIHUI.-.UPDATED.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by POWPOWER2021** [comment]
Hi! @Kevin-FF-USA

> Please confirm that the region of operation for client applications you will focus on is Asia minus GCN.  

Confirmed



> • Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .

Confirmed

> • Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 

Confirmed

> •  Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 

Confirmed

> • No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

Confirmed

> • Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 


Confirmed

> • Community Governance Participation: It is expected that you will participate in the program 20 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 

Confirmed

> Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

None

> Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

Yes

> (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 

f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq

**Comment by galen-mcandrew** [comment]
@POWPOWER2021 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @POWPOWER2021!

Really appreciate you filling out the acknowledgments for the Notary kickoff in this ticket. There is some additional information needed in order to finalize, **can you please follow this link to complete?**
[Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)

**Comment by Kevin-FF-USA** [comment]
Hi @POWPOWER2021 

We haven't received your acknowledgement confirmation yet. [Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)
Need this completed so we can collect the contact information for Datacap distribution next steps.

**Comment by Kevin-FF-USA** [comment]
Hello @POWPOWER2021!

This is a friendly ping - we have received your information, but the field for your Slack handle was not filled. In order to receive Notary communications via Slack we need you to: 

- Provide a Slack handle within this GitHub ticket (for public record)
- Message Kevin_FF on Slack with that same Slack handle you entered in this ticket.

**Please provide this information by April 25th. Thank you!**

**Comment by POWPOWER2021** [comment]
Hello Kevin

This is a link to the slack channel dedicated to Fil plus, from our POW POWER slack.

https://powpower.slack.com/archives/C03A6BNK7DH

**Comment by POWPOWER2021** [comment]
@Kevin-FF-USA Hello！Kevin.

-  slack handle: POW POWER
- DM you already

Thank you!

**Comment by Kevin-FF-USA** [comment]
Great! I have updated your information and added you to all notary communications on Slack. Thank you.

**Comment by POWPOWER2021** [comment]
@Kevin-FF-USA 
THANK YOU Kevin.
I have changed the address as ledger address.

**Comment by jiangproc663** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecwmhb7tygbkragbxey7izmbhhc5mappvlhsud57m5xpyugor6acg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwmhb7tygbkragbxey7izmbhhc5mappvlhsud57m5xpyugor6acg

**Comment by galen-mcandrew** [comment]
@jiangproc663 and @POWPOWER2021 

Please verify which single ledger address you would like to use for your notary activity. You have listed two here in this application and other forms:

f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq
f1u2c7dpdqmlfk5zknafigcycrpzltcjd6nmjnuia

**Comment by galen-mcandrew** [comment]
Can you please provide some details about your relationship with these three addresses:

> f1iyqehvamuqwicm7zhd6jc5wr4re2p5yfkzsuwdi
f1t5aeedonkpewe4qye4swbewx5fakrvo5nsdceci
f1xs26csaa2sh562tqfx2tic2vfzn525nhohrc2ea

Seeing some transactions and interactions between your address and these three, along with the address in other notary applications: [Pow Power](https://github.com/filecoin-project/notary-governance/issues/447), [NFTStar](https://github.com/filecoin-project/notary-governance/issues/444), [ND Labs](https://github.com/filecoin-project/notary-governance/issues/449), [IPOLLO](https://github.com/filecoin-project/notary-governance/issues/439), & [Bitrise Capital](https://github.com/filecoin-project/notary-governance/issues/443).

**Comment by POWPOWER2021** [comment]
@galen-mcandrew Hi galen. Being  the first time to apply for a notary,  we did not have a hardware wallet, that’s why we had to use the initial F1 address （f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq  ）as the application. After we purchased the ledger wallet, then we changed the address to f1u2c7dpdqmlfk5zknafigcycrpzltcjd6nmjnuia.  Three addresses you’ve mentioned above  are not relevant to each other. So I'm not sure the  exact address. We have consulted a lot of sp and notary to assist us on technical issues.Thank you！

**Comment by POWPOWER2021** [comment]
> Can you please provide some details about your relationship with these three addresses:
> 
> > f1iyqehvamuqwicm7zhd6jc5wr4re2p5yfkzsuwdi
> > f1t5aeedonkpewe4qye4swbewx5fakrvo5nsdceci
> > f1xs26csaa2sh562tqfx2tic2vfzn525nhohrc2ea
> 
> Seeing some transactions and interactions between your address and these three, along with the address in other notary applications: [Pow Power](https://github.com/filecoin-project/notary-governance/issues/447), [NFTStar](https://github.com/filecoin-project/notary-governance/issues/444), [ND Labs](https://github.com/filecoin-project/notary-governance/issues/449), [IPOLLO](https://github.com/filecoin-project/notary-governance/issues/439), & [Bitrise Capital](https://github.com/filecoin-project/notary-governance/issues/443).

Hi, @galen-mcandrew 
Those three addresses are controlled by an SP we found. This SP is named RongYing. 
NDLABS was recommended RongYing for us. We don't have any relationship with RongYing. 
Thank you.

**Comment by POWPOWER2021** [comment]
> Hi! @Kevin-FF-USA
> 
> > Please confirm that the region of operation for client applications you will focus on is Asia minus GCN.
> 
> Confirmed
> 
> > • Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship > .
> 
> Confirmed.
> 
> 1. The relationship with NDLABS is: NDLABS introduced us to participate in Fil+ through the gravity project. NDLABS LDN address: f1y7xmlneep3qtxcumqlmqrja3fhqdxdaxwou6mdq
> 2. POW Power LDN address: f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq
> 3. Powpower has business cooperation and sales relationship with Ipollo, but no Filecoin-related relationship.
>    ipollo address: f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq
>    Tips*  Except for Pow Power own LDN address, there are no other related addresses that we control.
> 
> > • Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.
> 
> Confirmed
> 
> > •  Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.
> 
> Confirmed
> 
> > • No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.
> 
> Confirmed
> 
> > • Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.
> 
> Confirmed
> 
> > • Community Governance Participation: It is expected that you will participate in the program 20 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.
> 
> Confirmed
> 
> > Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.
> 
> None
> 
> > Please affirm that you will abide by the allocation / client due diligence plan you laid out above.
> 
> Yes
> 
> > (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.
> 
> f1u2c7dpdqmlfk5zknafigcycrpzltcjd6nmjnuia

Hey @galen-mcandrew 
Updated here
