### ISSUE TITLE
Notary Applicaiton - ND LABS

### ISSUE THREAD

**Issue by NDLabs** [filecoin-project/notary-governance#449]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:Leo
- Affiliated organization: ND LABS
- On-chain address to be notarized (recommend using a new address):f1y7xmlneep3qtxcumqlmqrja3fhqdxdaxwou6mdq
- Region of Operation: [Singapore]
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 10 PiB):1P

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
ND LABS has technical operation centers and nodes in Singapore, Hong Kong, the United States, and Dubai. Since Fil has launch of the mainnet in 2020, ND has begun to provide technical services to partners to help them complete the construction of storage services. At present, the accumulated storage power of ND exceeds 160P globally. The largest node has 84P storage power, and the node owns exceeds more than 1.4 million FIL. 
ND LABS is positioned as a decentralized storage service provider for WEB3. For a long time, ND not only focuses on building nodes for partners, but also explores how to provide better storage services for potential clients of web3. Since October 2021, ND has been deeply involved in the FilPlus project, vigorously promoting the Filplus project to partners who has effective data storage needs. We also providing them with a complete set of solutions and technical services for storing data in the FIL network. The Singapore and US nodes are the main storage nodes, which was provide real data storage for early customers.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
f0152799(329,791.9335fil)、
f01168661(71,800.6255fil)、
f01137150(570,579.5868fil)、
f01715155(28,565.5908fil)、
f01740934(11,930.8110 fil)、
total：1012668.5476 fil
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
N/A
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Founded in 2019, ND LABS PTE.LTD. has offices in China, Singapore and America. ND LABS is committed to becoming an enterprise that provides distributed storage infrastructure construction and distributed storage service support for the "the meta-universe".
At present, we are mainly engaged in two business lines:
1. Infrastructure construction of distributed storage. At present, we have set up our own nodes in the United States and Singapore. In the future, we can provide our customers with storage and computing power cooperation services.
2. Distributed storage related software services, including online storage, SaaS services, etc. At present, we have developed a website to help users store effective data online, which is now for promotion and operation. In the future, we will also iterate on the platform and develop our own SaaS storage services.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Twitter：@imNDLABS
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://drive.google.com/file/d/1jZyJeO1Sw2HGwBDQXgEXjRyuytsrRMJH/view?usp=sharing https://drive.google.com/file/d/10Y3Ufml0QxZSUbf3q5itJvz1I8-ymCb5/view?usp=sharing https://drive.google.com/file/d/1-8r7rT3zZsrr1jlZncC4LFUiMwQ-1viJ/view?usp=sharing https://drive.google.com/file/d/1bRcnny0rIALDpgow327mntCjlI7TBIkn/view?usp=sharing https://drive.google.com/file/d/1j2OMawo3B5CT9DuGl-OwF0jukeMrAqxf/view?usp=sharing https://drive.google.com/file/d/13OlsAyp5KAEZDsfcnaqrvz4Xn4gIInbT/view?usp=sharing https://drive.google.com/file/d/1uOAEI1awVXdqdi-t5kRi53RoYSyHyHse/view?usp=sharing https://drive.google.com/file/d/12EWAFbcedk9L2wxKHsRZl5TA3qpf1-md/view?usp=sharing https://drive.google.com/file/d/1jgjMRL0LBNGxH6tRCksDLnPElcBQKhRC/view?usp=sharing https://drive.google.com/file/d/1uShHie9rYnGBPMTMLEkgYYubEZoh5cgl/view?usp=sharing https://drive.google.com/file/d/1x9oCbv_ozVoV6htj3v7Z72SfWvf_pAep/view?usp=sharing https://drive.google.com/file/d/1R0Ae2P19103A9P07FXM-lSTyn-fzr8Hg/view?usp=sharing https://drive.google.com/file/d/1DOIOuPfjsXC0qnl1ksuyU_6hXwoliDRE/view?usp=sharing https://drive.google.com/file/d/1XlGv1w5Eq9knU2Q4IFUgH_VHMkVuFtW0/view?usp=sharing https://drive.google.com/file/d/1Q2vWEBulrSOCz16-OCyYQghfGf5T1fVO/view?usp=sharing https://drive.google.com/file/d/1Gm1alwYuL3_WD-XmFXPm0dWkG9oY-vDk/view?usp=sharing https://drive.google.com/file/d/19P0OxqmL7IXIGw4wBIc1wIlixwubHbLd/view?usp=sharing https://drive.google.com/file/d/1IlUIA_b7BmcrzACX0yeoYsfQnANc7vHB/view?usp=sharing https://drive.google.com/file/d/1mAuuZU9py2S3AdbOeXZ2cXhCY-lg46pr/view?usp=sharing https://drive.google.com/file/d/1z-HXjJMtByMR82wYCnq__S-hSB5yuzTh/view?usp=sharing https://drive.google.com/file/d/1jX53udWAOpKOOvK33nuIHvrb3wGTHtUd/view?usp=sharing https://drive.google.com/file/d/1lYD5JeKQcXTG56U26NJ-_aXJvEC5QlER/view?usp=sharing https://drive.google.com/file/d/1htH1q8aScViFWbLo07ju41v6J8rNSoCR/view?usp=sharing https://drive.google.com/file/d/1YcHS70Q-OmNoxb47ioMNi7XTxrSaqqx7/view?usp=sharing https://drive.google.com/file/d/1VH4AX-PtqU4h052VdeAo0W-0TZP2aoYR/view?usp=sharing https://drive.google.com/file/d/1R1mu42qxXgXvfd3gxx3eNc0_ibJ0Wx4n/view?usp=sharing https://drive.google.com/file/d/1SHzo5V-Aaur0SnyyAcVVnnfzS_QxHwbL/view?usp=sharing)
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter：@imNDLABS
Twitter：@omgjennyyyy

```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We plan to support the following data:

30%: Video data, including videos related to film and television and surveillance
20%: web3.0 related data, including NFT, gamefi, SocialFi and other data
30%: Relevant data with social contribution, such as e-books, art, etc.
20%: Stored data of ND-related business customers
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We will use the assessment model to score clients, according to the standard scale of 1 to 5 to evaluate and assign their DataCap needs. 
We have made a scoring table for clients reviews :
https://docs.google.com/spreadsheets/d/17h4X9lvE4Sdr47mHiwAJzYyXwtW743KV/edit?usp=sharing&ouid=118364709155675277156&rtpof=true&sd=true

We will assign DataCap to the clients who can provide real information of their company and ensure that the data is publicly available. We have a series of rules to determine the true and valid identity information of clients：

1.We will browse the client's official website to understand the basic information of the their organization.

2.We will require the clients to provide verifiable information such as the organization's business registration and establishment documents by mail

3. We will conduct a review of the clients company's data storage content, and we prioritize the clients who store high-value data.
We will use the assessment model to score clients, according to the standard scale of 1 to 5 to evaluate and assign their DataCap needs. 
We have made a scoring table for clients reviews :
https://docs.google.com/spreadsheets/d/17h4X9lvE4Sdr47mHiwAJzYyXwtW743KV/edit?usp=sharing&ouid=118364709155675277156&rtpof=true&sd=true

We conduct our internal review process through 4 stages
1. The primary reviewer will conduct a basic review of the application submitted by the client. The applicant's data storage must be open and valid data, and there are real storage requirements.
2. According to the results of the basic review, the junior reviewers will submit the allocation process to the intermediate reviewers, and the intermediate reviewers will give a score based on the content of the evaluation model.
3. According to the scoring results of the intermediate reviewers, the senior reviewers will further conduct a detailed investigation of the business ecology of the company, as well as verify the true information of the applicant and the company, and make a final decision and signature.
4. After the decision of the senior reviewer is approved and signed, the DataCap will be assigned a certain amount to the client. If not passed, we will inform the client of the review result.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We use a hardware wallet to store the private key to ensure the security of the account. After being reviewed by our internal decision makers, the data caps will be allocated to applicants by those who have the right to execute the hardware wallet.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In order to ensure the authenticity of the information and reputation of our clients, we will verify the online and physical identity and reputation of our clients through the following content.


Online information:
1.Review third-party public data provided by clients, such as Twitter-type social media accounts. We will observe the activity of the account, and the activity of the Github usage period.
2.Browse clients and their company's official website and review the company's history, news, ecology and products.
3.Make a query on the enterprise information website in the clients country/region
4.Use official email to confirm whether the clients is applying for Data Cap, and confirm their identity information and job information.

Entity Information:
1.We will require our clients to provide business registration, establishment documents, public registration information and relevant certificates.
2.Will require our clients to provide government-issued ID or passport information.
3.Our clients need to provide us with sample data they want to store, and we will check that their data is valid and publicly available.
4.For the privacy of the clients, we will recommend that our clients send entity information by email.

We will require our clients to promise not to have any violations. We will give a reminder if there is any of the following behaviors. The clients with serious violations will be blacklisted by us.

1.We require our clients to comply with the laws of the country and region where they are located, and shall not have any violations of laws and regulations.
2.We require our clients to comply with Filecoin's community regulation..
3.Our clients must ensure the stored content is legal, valid and insensitive.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We require clients to disclose transaction information. After the clients obtain Data Cap, we will continue to follow up their transaction information every week. Once the clients are found to have violation operations, we will give a reminder. If the violation circumstances are serious, we will disclose the violating operations of this client in the public community, and pulled into the blacklist to reject the future application. If the client refuses to disclose, we will deny his application.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Our allocation strategy and auditing process will public on Github to ensure our impartiality.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Github
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
20+ hours per week on average, including  participating in the program and making allocations. i will also attend in governance calls and response messages in slack. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Never had
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
Never had
```

**Comment by galen-mcandrew** [comment]
[ND Labs - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320861/ND.Labs.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by NDLabs** [comment]
@galen-mcandrew 
Hi, Galen. really appreciate for your feedback. 

Here are some points we want to update.

**1. Stake Exposure**

f0152799(329,791.9335fil)、
f01168661(71,800.6255fil)、
f01137150(570,579.5868fil)、
f01715155(28,565.5908fil)、
f01740934(11,930.8110 fil)、
total：1012668.5476 fil
Besides this nodes, the assets we disclose are part of our assets, accounting for 1/6 of our total assets.

**2. Industry Reputation**
https://twitter.com/imNDLABS/status/1501126179512012801
https://twitter.com/imNDLABS/status/1504695558795149321
https://twitter.com/imNDLABS/status/1504159515423363083
https://twitter.com/imNDLABS/status/1503801081704329216
https://twitter.com/imNDLABS/status/1502052551570690050
https://twitter.com/imNDLABS/status/1502047484729831427
https://twitter.com/imNDLABS/status/1501593768067280897
https://twitter.com/imNDLABS/status/1501207713313062912
https://twitter.com/imNDLABS/status/1495731744989126663
https://twitter.com/imNDLABS/status/1478313717016055808
Links above shows the events that ND has attend these days around the world. 

**3. Individual reputation** 

@web3jennie    Followers: 3954
@Vicky777670  Followers: 50k 
Vicky is the cofounder of NDLABS. 

**4. Bookkeeping Plan**

We will follow the FIL+ guidelines and conduct all our allocation decisions publicly on Github.
- filecoin-plus-client-onboarding
- filplus.info

We are going to do a google sheet to keep all the work records in relation to our  allocation decisions. 
1. The google sheet is an internal database for storing the foregoing files. However, if it needed, we will authorized visitors to access the file. 
2. Besides, without disclosing any confidential information about our clients, we are happy to respond to reasonable inquiries or inquiries that community members may have regarding our DataCap allocation decisions.

THANKS A LOT!

**Comment by Kevin-FF-USA** [comment]
Hi @NDLabs  **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

    Please confirm that the region of operation for client applications you will focus on is Asian minus GCN. 

    Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles). 

    Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

    Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

    Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

    No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

    Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

    Community Governance Participation: It is expected that you will participate in the program 20 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.

    Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt. 

    Please affirm that you will abide by the allocation / client due diligence plan you laid out above. 

    (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

    If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by galen-mcandrew** [comment]
[Leo - UPDATED - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8373122/Leo.-.UPDATED.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by NDLabs** [comment]
Hi! @Kevin-FF-USA

> Please confirm that the region of operation for client applications you will focus on is Asia minus GCN.

Confirmed

> • Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .

Confirmed

> • Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 


Confirmed

> • Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 

Confirmed

> • No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

Confirmed

> • Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 


Confirmed

> • Community Governance Participation: It is expected that you will participate in the program 20 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 

Confirmed

> Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

Nodes we pointed above f0152799、f01168661、f01137150、f01715155、f01740934

> Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

 Confirmed

> (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 

f1y7xmlneep3qtxcumqlmqrja3fhqdxdaxwou6mdq

**Comment by galen-mcandrew** [comment]
@NDLabs 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hey @NDLabs!
Really appreciate you filling out the acknowledgments for the Notary kickoff in this ticket.  There is some additional information needed in order to finalize, can you please follow this link to complete?  
[Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)

**Comment by Kevin-FF-USA** [comment]
Hello @NDLabs!

This is a friendly ping - we have received your information, but the field for your Slack handle was not filled. In order to receive Notary communications via Slack we need you to: 

- Provide a Slack handle within this GitHub ticket (for public record)
- Message Kevin_FF on Slack with that same Slack handle you entered in this ticket.

**Please provide this information by April 25th. Thank you!**

**Comment by NDLabs** [comment]
Hi Kevin,
Slack handle: https://filecoinproject.slack.com/archives/D03CQDHGRCY
Name: NDLabs
Already DM you. 
Thanks a lot!

**Comment by Kevin-FF-USA** [comment]
Hi @NDLabs ,
Appreciate you messaging on SLACK and confirming here.  There is also a SLACK handle I have been communicating with with ND identification, would you like communications to also be authorized with IRMA?

https://filecoinproject.slack.com/team/U02LFL80VBP

**Comment by NDLabs** [comment]
Hi, @Kevin-FF-USA,
I've just updated the address.

**Comment by NDLabs** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacea7dsanakwqmz2cem23c3mxemlnp3k24y4r7vcd5tewh5vzrvjrzy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7dsanakwqmz2cem23c3mxemlnp3k24y4r7vcd5tewh5vzrvjrzy

**Comment by galen-mcandrew** [comment]
@NDLabs 

Can you please verify your Ledger address that you would like to use as a notary? We received a different address in the form that you submitted, compared to here.

**Comment by galen-mcandrew** [comment]
Can you please provide some details about your relationship with these three addresses:

> f1iyqehvamuqwicm7zhd6jc5wr4re2p5yfkzsuwdi
f1t5aeedonkpewe4qye4swbewx5fakrvo5nsdceci
f1xs26csaa2sh562tqfx2tic2vfzn525nhohrc2ea

Seeing some transactions and interactions between your address and these three, along with the address in other notary applications: [Pow Power](https://github.com/filecoin-project/notary-governance/issues/447), [NFTStar](https://github.com/filecoin-project/notary-governance/issues/444), [ND Labs](https://github.com/filecoin-project/notary-governance/issues/449), [IPOLLO](https://github.com/filecoin-project/notary-governance/issues/439), & [Bitrise Capital](https://github.com/filecoin-project/notary-governance/issues/443).

**Comment by NDLabs** [comment]
Hello, @galen-mcandrew 
Please excuse my late reply, I just saw your question.

These three address is provided by the SP who we cooperate with. They have transfered some $fil from these addresses to support our initialization(active market deals).
As a recommender, NDLABS has recommended 9 organizations with data storage requirements to participate in Project Gravity. Those organizations you mentioned are in the recommended list and have conducted a conference call with the gravity team to introduce these projects. 
According to their own wishes and abilities, they are also recommended to participate in Filplus and Notary issue. Currently,NDLABS and cooperating SPs are guiding these organizations to following up on FIL+. 

Recently, we are preparing for notary onboarding, which may have ignored github's reply. I hope our communication will be smooth in the future, whether in github or slack.

By the way, our address is  f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei

Thank you.

**Comment by NDLabs** [comment]
Hi @galen-mcandrew @Kevin-FF-USA @dkkapur , Update here
NDLABS has recommened following 9 organizations take participated in Gravity Project. 
> 1.POW Power：f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq
> 2. NFTStar：f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy
> 3. Bitrise capital：f1dfkdmjhuvvol6okun57mix447wdpolwcd323ktq
> 4. IPOLLO：f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq
> 5. NHASH：f1gmiepn73zoa5gz2oiqyugjmrsecwj5qxd42vmyi
> 6. NSWAP： f1u3rzf5re6nvnyjjixcmbk5tderq55vjhudmapny
> 7. Gameway：f1qpkmibcsitxtxwg6ayghxwkssoxs4bfyzwzslza
> 8. Metadata Labs Inc：f17d2n363326qlln4uva7ylxteamtdj3lq6wuaewi
> 9. ABGA games：f1ewwoms3aiairedun4h2uayqhlmtjsulnqy2xnrq
> NDLABS  LDN address: f1ewwoms3aiairedun4h2uayqhlmtjsulnqy2xnrq

Storage Provider(RongYIng MinerIDf01834253) is a company that we used to cooperated in migration nodes from China to US. RongYing and NDLABS has no more cooperation in operation for now. Thus, they only support storage service for us. 

We confirmed here that, as a notary, we wouldn’t allocate datacap to any organizations related to us.
