### ISSUE TITLE
[Notary Application] 4EVERLAND

### ISSUE THREAD

**Issue by 4everlandorg** [filecoin-project/notary-governance#450]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Deon Erda
- Affiliated Organization: 4EVERLAND.inc
- Website / Social Media: https://www.4everland.org/
- On-chain address to be notarized (recommend using a new address): f1xwmv2xedai23ajasnmewvdpoxsnfu6o72ihzo5a
- Region of Operation: Europe
- Use case(s) to be supported: Web 3.0 Applications/ Web 2.0 Applications/ Developer Tools/ Scientific Data/ User Content/ Professional Services/ Media & Entertainment
- DataCap requested for allocation (10TiB - 10 PiB): 1 PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
4EVERLAND is a Web 3.0 cloud computing platform that integrates storage, computing, and network core capabilities. It aims to help the user to make a smooth leap from Web 2.0 to Web 3.0 and become the infrastructure for millions of Web3.0 developers and applications. 4EVERLAND realizes the need for inter-blockchain communication and interoperability between multiple chains and so it utilizes the IBC technology to integrate with the underlying public chains such as Ethereum, BSC, Solana, Polygon, and Filecoin. Similarly, 4EVERLAND also provides a distributed, high-efficiency, self-incentivized, and low-cost data hosting network based on an open protocol system like IPFS to meet developers' requests for inter-blockchain communication, decentralized front-end, and write once, run any blockchain, making it easier to quickly build Web 3.0 applications.
We have also obtained grants from Filecoin Foundation.

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
NA
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We have obtained grants from Filecoin Foundation.
https://filecoinfoundation.medium.com/dev-grant-spotlight-4everland-6b07da0aade6

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
NA
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
We are a company limited by guarantee called 4EVERLAND FOUNDATION Ltd, which was established in Singapore on May 29, 2021 and currently has 30 team members.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://4everland.org/
Telegram: https://t.me/org_4everland (13k members)
Twitter: https://twitter.com/4everland_org (9k Followers)
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://filecoinfoundation.medium.com/dev-grant-spotlight-4everland-6b07da0aade6
https://4everland.medium.com/
https://finance.yahoo.com/news/4everland-launches-beta-version-hosting-162700092.html
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Telegram: https://t.me/org_4everland (13k members)
Twitter: https://twitter.com/4everland_org (9k Followers)
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Web 3.0 Applications
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We’ve studied several cases from previous notary applications, and we totally agree with what IPFSUnion has proposed. 
Base on some allocation rubrics shared by Andrew Hill at Fil+ Day, we have further standardized our allocation strategy in detail. The most important thing about DataCap allocation is to ensure that client utilizes DataCap to store real data. so I firstly specify some rules to figure out the true identity of the applicant.
* Browse their official website to get a general understanding of the company or the individual. 
* Query the company's registration information from government related websites to make sure the information he submitted is truth.
* Ask some questions to know about the applicant's position/organization/plan/use case etc. 
* Then We will classify applicants based on their industry reputation and scale etc. All applicants will be divided into eight categories to determine the amount of datacap they will get. The following Rubric will be the primary guideline I use when evaluating a client and determining their DataCap allocation.   
You can see it: https://docs.google.com/spreadsheets/d/1dD8aI3lsZGRp5rUWiULeRaPwFc7Z2z8tkzpdnTY-tyo/edit?usp=sharing
These scoring guidelines can serve as a tool of assessment and further to add a level of consistency across the board. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Using a hardware wallet.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1. Ensuring that the client's datacap is used distributely to different storage entities, so that the malicious party has no incentive to illegally use the datacap;
2. All the user's basic information and apply records will be required to be signed with their private key, and these records will be unvealed publicly;
3. Evidence of abusing datacap will also be unvealed publicly;
4. The reputation and punishment mechanism of the deal matching system will ensure that the client will suffer corresponding losses if he does evil;
The questions we’ll be asking: 
1. Please sign a specific piece of data with your private key, so that we can verify your identity in filecoin;
2. Please fill in the legal person's name, ID card and other basic information, and perform real-name authentication (for example, using Alibaba Cloud’s real-person authentication service)；
3. What is your application scenario?
4. Do you agree to sign a declaration of compliant use of datacap?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Firstly, from the questions about use plan and further investigation, I can know some details about his allocation plans. When scoring applicants according to the above sheet, the more geographical distribution, use cases and miners assign, the higher score he will get and the more datacap clients are likely to get.  
Next, we will keep tracking clients’ information such as the DataCap distribution records, related miner addresses and storage providers, to ensure that they are consistent with their words and deeds.
Finally, a reward and punishment mechanism will be established. If someone over-allocating datacap to a single entity, I will refuse further allocation and issue a warning which will be public to the Filecoin community. On the contrary, reputable client have the opportunity to obtain more datacap.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
1. All allocation decisions will happen in public in the following[repository](https://github.com/filecoin-project/filecoin-plus-client-onboarding). Since all interactions are intended to occur publicly, most of the allocation decisions should be self-explanatory.
2. I will build a profile of every client who obtained DataCap from me in a public place
3. If there are any complaints about notary, a dispute resolution application can be filed to the Notary Governance after 14 days since its original challenge data. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Github Only 
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
9 hours per week.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No. But we‘re applying for DataCap.
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/255
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
NA
```

**Comment by galen-mcandrew** [comment]
[4Everland - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320887/4Everland.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by 4everlandorg** [comment]
Yes, although our team is registered in Singapore, the team has a majority of European members, so we chose to apply in Europe.

**Comment by galen-mcandrew** [comment]
Thank you for confirming! We're excited to have more notary support for clients and storage providers operating in Europe.

**Comment by 4everlandorg** [comment]
Hi @Kevin-FF-USA, thanks a lot!
1. We confirm that we will focus on Europe.
2. We confirm all the items below:
• Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
Confirmed.
• Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
Confirmed.
• Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
Confirmed.
• No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
Confirmed.
• Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
Confirmed.
• Community Governance Participation: It is expected that you will participate in the program 9 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
Confirmed.
3. We don't have any addresses.
4. We will abide by the allocation/client due diligence plan we laid out above.
5. We confirm that our address is: f1wp5enznnbgzyoaiafzlox3h3bkwcl347iwqivga

**Comment by galen-mcandrew** [comment]
@4everlandorg 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @4everlandorg!

We have your notary address on file, and we will be communicating with Deon Erda via Slack. If there are any other handles you wish to have included, please comment those handles below.

**Comment by 4everlandorg** [comment]
Hello Kevin,

Thank you for your reply, please also include user ID: U03APBNCJKB for further communication.

**Comment by galen-mcandrew** [comment]
Please complete the steps to verify your ledger wallet address using https://plus.fil.org/

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1wp5enznnbgzyoaiafzlox3h3bkwcl347iwqivga
#### Datacap Allocated
> 1PiB

**Comment by galen-mcandrew** [comment]
Please confirm your ledger address using the verification tool in the [Fil+ Registry app](https://plus.fil.org/). 

[Here](https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing) is a troubleshooting guide.

Thanks!

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1wp5enznnbgzyoaiafzlox3h3bkwcl347iwqivga
#### Datacap Allocated
> 1PiB

**Comment by DeonErda** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacearyqsszwpxool5ewrwnex3qud5ftv4ela2xgabxxulquw5koasaa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearyqsszwpxool5ewrwnex3qud5ftv4ela2xgabxxulquw5koasaa

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1wp5enznnbgzyoaiafzlox3h3bkwcl347iwqivga
#### Datacap Allocated
> 0PiB
