### ISSUE TITLE
Notary Applicaiton - LuckyHash

### ISSUE THREAD

**Issue by bary321** [filecoin-project/notary-governance#451]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Simon
- Affiliated organization:  LuckyHash
- On-chain address to be notarized (recommend using a new address): f3v6iy3olhfjuyuopqatvfnjud32qvr5hroclfouimqm6cbeng36yumngtvqxfcivtvnkeodjxqulyxvwodjeq
- Region of Operation: [Asia minus GCN]
- Use case(s) to be supported: [Individual user storage, enterprise user storage, public project storage, scientific data sets, video and music]
- DataCap requested for allocation (10TiB - 10 PiB): 1PiB

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
It has been 2 years since we have been deeply involved with IPFS and Filecoin. 
Since 2020, our team has been following and propagating IPFS.
In June 2021, in order to better promote IPFS and Filecoin globally, we created LuckyHash. So far, it has more than 500,000 users.

LuckyHash is now fully operational for Filecoin and IPFS customer service. We are committed to providing comprehensive All-in-One cloud hosting services ranging from miner purchase - Filecoin mining farm selection - miner hosting - Filecoin mining real-time data monitoring - electricity bill settlement and so on, with a focus on providing multi-mode and multi-strategy Filecoin mining solutions for individuals and organizations.

and our miner ID: f01173170 has been ranked top 30 in the Adjusted Power rankings. 

We not only have advantages in storage technology but also are committed to developing the ecological construction of IPFS and Filecoin. To help more people understand IPFS & Filecoin, we have created the LuckyHash community https://t.me/luckyhashgroup. According to the economic model of Filecoin, to increase the liquidity of Filecoin, we participated in the investment and incubation of the Defil platform.
Reference URL:
LuckyHash Official Website: www.luckyhash.com
The LuckyHash community: https://t.me/luckyhashgroup;
Telegram: https://t.me/luckyhashgroup and https://t.me/luckyhash_official
Miner ID: f01173170
Promotional activities: 
https://www.facebook.com/luckyhashofficial/videos/542708173644804/
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Total：365,595.4 FIL
Currently Available：34,617.8720 FIL 
Initial Pledge: 296,890.008 FIL 
Locked Rewards: 34,087.5327 FIL
The above data are from the blockchain browser: FILFOX. The miner ID used for statistics is the ID published on the official website of LuckyHash.
Miner ID: f01173170
Website: FILFOX: https://filfox.info/en 
LuckyHash: www.luckyhash.com
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
1. To help enthusiasts understand IPFS & Filecoin, we created the LuckyHash community(https://t.me/luckyhashgroup)
2. We shared many materials with the public in the hopes that Filecoin and IPFS are known by more people.
https://www.quora.com/What-is-Filecoin-s-lucky-value
https://www.facebook.com/luckyhashofficial/posts/154044223626493
https://luckyhash.tumblr.com/post/666646585451692032/luckyhashs-ambition-make-filecoin-mining-as-easy?
https://www.facebook.com/luckyhashofficial/posts/137088048655444
https://www.facebook.com/luckyhashofficial/posts/132539435776972
https://www.facebook.com/luckyhashofficial/posts/123627630001486
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
LuckyHash is headquartered in Singapore. LuckyHash is a high-tech company focusing on the research and development of distributed storage, distributed computing, and distributed database technology. We have devoted to Filecoin mining machine research and development, mine construction, mining pool development, IPFS ecological investment incubation, distributed network technology research and development, etc., LuckyHash is committed to building web3.0.
-Registration Country: Singapore
-Organization size: 100+
-Time since establishment: 2021
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
LuckyHash Official Website: https://luckyhash.com
Telegram EN: https://t.me/luckyhashgroup
Telegram KR: https://t.me/luckyhash_official
Twitter：https://twitter.com/LuckyHash_
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
[Please answer here.](https://www.digitaljournal.com/pr/luckyhash-launched-cryptocurrency-card-game-to-loot-unlimited-rewards
https://coin.fyi/news/ethereum/luckyhash-review-layer2-dark-horse-metisdao-achieved-225-3-increase-in-the--rsrgzh
https://menafn.com/1103202308/A-Deep-Look-Into-Crypto-Mining-Luckyhash-a-Mining-Financing-Platform-That-Worths-Invest-in&source=359
https://www.sahyadritimes.com/2021/09/01/luckyhash-official-website-was-live-on-sep-1st-to-add-fuels-to-filecoin-growth/
https://zexprwire.com/luckyhashs-ambition-to-make-filecoin-mining-as-easy-as-online-shopping/)
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Telegram EN: https://t.me/luckyhashgroup  15975 members
Twitter：https://twitter.com/LuckyHash_ 26238 followers
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
1. User-generated material (individual user storage)
2. Valuable information (weather, books) 
3. Media & Entertainment(video & music)
4. Scientific evidence (artificial intelligence training, geological data, self-driving)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
LuckyHash assigns Datacaps based on use cases for different customers. We will make the allocation according to customers' actual business needs. Instead of allocating DataCap to one customer ata time, we increase the amount over time based on actual demand.
We distribute the Datacap requests in three times: First Time 20%,  Second time 30%, and 50% in the third time.
We'll also be conducting offline surveys to learn more about who they really are, what they do, their reputation, and how they store Filecoin. Each allocation will be regarded as an assessment of the client's reputation, with a cumulative score and a corresponding level of trust. We plan to conduct a thorough analysis and assessment of our clients' reputation every three months and reserve the right to change our clients' quotas to ensure that they are allocated as fully as possible.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will strictly implement the allocation strategy and conduct a detailed investigation of customer information. Applications submitted are reviewed on a daily basis. If any information submitted or the sample information is incomplete, we will ask the applicant to replenish it. Applicants' detailed proposals will be evaluated and the amount allocated will be based on the final score. We also developed and validated offline wallets for accounts associated with Datacap assignments. Multiple signature wallets will be used as more customers come in.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1. We require customers to disclose their addresses, set up tracking records, and strictly investigate customer storage data

2. We will have a special customer rating database, and will give warnings or penalties to customers with low scores and poor performance

3. For the diversity of stored data and the high authenticity of customer data, we will improve the score

If a customer incorrectly assigns Datacap to a single entity, we will issue a warning. For customers who continue to violate the rules after the warning, we will stop the next allocation. The Filecoin community will be warned. Cooperation is no longer acceptable. For customers with good reputation, we will make the next distribution.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1.We require customers to disclose their addresses, set up tracking records, and strictly investigate customer storage data
2. We will have a special customer rating database, and will give warnings or penalties to customers with low scores and poor performance
3. For the diversity of stored data and the high authenticity of customer data, we will improve the score
If a customer incorrectly assigns Datacap to a single entity, we will issue a warning. For customers who continue to violate the rules after the warning, we will stop the next allocation. The Filecoin community will be warned. Cooperation is no longer acceptable. For customers with good reputation, we will make the next distribution.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We will keep a detailed record of the review, which will be made public on GitHub. Allowed customers to put forward different views. We will set a two-week public notice period for different views of DataCap customer allocation, and then hold an online meeting to make a final decision.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Github.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
4-6 hours per week.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None.
```

**Comment by galen-mcandrew** [comment]
[LuckyHash - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320881/LuckyHash.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by bary321** [comment]
@galen-mcandrew
Hello, Gallen. 
Regarding the question you mentioned in your scorecard: is there any relationship to the IPFS Metaverse Community.
STCloud is one of the investors in the IPFS Metaverse Community. We have been committed to letting more people know about IPFS and Filecoin, delivering the latest news, and sharing ecological development. At the same time, we also support the development of projects which is related to IPFS and Filecoin. We have great expectations for the future of ipfs, filecoin, metaverse, and web 3.0. To this end, we have established relevant committees to search, evaluate and support the development of related projects.
Thanks to your team for the evaluation. Have a good day.

**Comment by Kevin-FF-USA** [comment]
We are very sorry to let you know that this application was not selected in this round of Notary Elections.  

Each application was scored according to the Rubric and [assigned a Scorecard](https://github.com/filecoin-project/notary-governance/issues/394). That score was then applied for each of the [geographic regions and the top scored applications were selected](https://github.com/filecoin-project/notary-governance/issues/479). 

We are humbled by your commitment, and grateful for your interest in the Filecoin Plus program. Looking forward to seeing you in the program and hope you resubmit in the future elections.

Should you have any questions please feel free to raise here, or DM me in Slack @Kevin_FF
