### ISSUE TITLE
Notary Application: ORIGIN Storage

### ISSUE THREAD

**Issue by llifezou** [filecoin-project/notary-governance#452]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: ORIGIN Storage
- Affiliated Organization:  ORIGIN Storage
- Website / Social Media: https://www.originstorage.io/
- On-chain Address to be Notarized: f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
- Region of Operation:  North America
- Use case(s) to be supported: General, Web3.0 application data and web2.0 p2p cdn data
- DataCap Requested: 1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
As a distributed storage and blockchain practitioner, we started the research and application of IPFS in 2018 and caught up with Filecoin again in 2019. After closely studying the Filecoin white paper and related technologies, we believe it was the only business scenario that could be landed since the development of blockchain technology. ORIGIN storage was finally set up, and lots of human and material resources were invested into Filecoin during the continuous operation.

1. In 2018,  some of our codes were merged. For example: 
https://github.com/btfslib/go-libp2p-quic-transport/commit/944de2ea4fec3bbab65d9d36577b7128142b361a

2. We went through all the test networks of Filecoin (T02417 is still active in the main network: https://filfox.info/en/address/f02417):
Testnet1: T017267
Testnet2: T01030
Spacerace: T02417, T017273

3. Co-developed a decentralized netdisk with Blockcasting Cloud in slingshot. (Slingshot registration ID: 676715867) (https://github.com/litianc/slingshot/blob/master/participants/BlockcastingCloud.md) 

4. After continuous investment and efforts, the company has become an essential contributor to the Filecoin network, with a total of 600P+ computing power. We also have an integrated Filecoin storage solution covering IDC server room, hardware, and software. To improve data encapsulation and storage efficiency, we conduct deep optimization in the modules of encapsulation efficiency, scheduling, space-time proof, cluster architecture, etc.

5. We strive to promote the development of IPFS and Filecoin by establishing partnerships with several web 2.0 industry giants and facilitating the storage of valid data in Filecoin.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

```
The total disclosed is 3,046,372 FIL, the rest are not disclosed. 
List of disclosed SPs：https://docs.google.com/spreadsheets/d/1KHXyg4hVqRIiSYu5gIQ535gKFDYONi__D2EYoPLKmG0/edit?usp=sharing
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
1. Participated in the entire process of Filecoin's test net/space race/mainnet development(https://filfox.info/en/address/f02417)

2. Started in 2019, actively promoted IPFS and Filecoin technology. In October 2020, while many miners did not understand the protocol lab, we wrote many articles to explain the Filecoin economic model and spoke in public to support PL.

3. We developed the decentralized network disk in Slingshot (ID: 676715867) together with Blockcasting Cloud. 
(https://github.com/litianc/slingshot/blob/master/participants/BlockcastingCloud.md)

4. We continuously participate in the development of Filecoin, issue reporting, and code contribution.
(https://github.com/filecoin-project/lotus/issues/7833.
https://github.com/filecoin-project/lotus/pull/6635)

5. We became Venus Master to participate in the construction of the community and make contributions: slack: cryptostack-zou (https://filecoinproject.slack.com/archives/CEHHJNJS3/p1635833794026900)
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
1. We keep working on Filecoin, and our colleague has proposed several issues and pr involved in the development of Filecoin.
https://github.com/filecoin-project/lotus/issues/7833
https://github.com/filecoin-project/lotus/issues/7132
https://github.com/filecoin-project/lotus/issues/6669
https://github.com/filecoin-project/lotus/pull/6635
https://github.com/filecoin-project/lotus/pull/7834
https://github.com/filecoin-project/lotus/pull/7844
https://github.com/filecoin-project/lotus/pull/7512
https://github.com/filecoin-project/lotus/pull/8208

2. We are planning to launch the lotus extension of the scheduling plugin, which can give miners a boost in packaging efficiency while also improving filecoin community activeness (will be open source): https://github.com/filecoin-project/community/pull/465
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
We are now located worldwide (USA, Canada, Singapore, Hong Kong) with over 60 employees. We have been using IPFS since March 2018 and have been involved in Filecoin since the very beginning.

We have over 10 IDC server room resources worldwide, 500P+ computing power under management.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Official website: https://www.originstorage.io/
Twitter：https://twitter.com/OriginStorage_
Named officer: 
Andy Guo CEO, ex Node Capital (one of the biggest crypto fund of China)  Director of Investment;
Hover Fang CMO, ex CEO assitant of 21 Vianet ( Nasdaq listed company);
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Youtube: Originstorage Introduction
https://www.youtube.com/watch?v=dJXJOvCdmP4&ab_channel=ORIGINStorage

(ORIGIN Storage focuses on IPFS distributed storage, helping to upgrade Web 3.0 comprehensively.)
https://www.sohu.com/a/460685605_381979

(Top 4 Open Source Distributed Storage_ORIGIN Storage Wins "2020 IPFS Most Influential Company" Award)
https://blog.csdn.net/weixin_39776787/article/details/111390399

(AndyGuo, Partner of ORIGIN Storage: Three Differences Between Filecoin and Traditional Mining)
https://www.btcfans.com/flash/id-42242

(ORIGIN Storage Andy Guo: Filecoin mining is the world's most challenging but profitable mining business.)
https://www.bitcoin86.com/live/99592.html

ORIGIN Storage provides an efficient FIL mining solution to help achieve the multi-billion dollar distributed storage market
https://www.marketwatch.com/press-release/origin-storage-provides-an-efficient-fil-mining-solution-to-help-achieve-the-multi-billion-dollar-distributed-storage-market-2021-12-06?tesla=y

Thriving Filecoin Ecosystem, Promising Future | ORIGIN Storage
https://www.asiaone.com/business/thriving-filecoin-ecosystem-promising-future-origin-storage

IPFS & Filecoin – The Cornerstone of Building a Metaverse Ecosystem | ORIGIN Storage
http://wdpp.org/press-release/ipfs-filecoin-the-cornerstone-of-building-a-metaverse-ecosystem-origin-storage-33118/

ORIGIN Storage: Store NFTs with IPFS & Filecoin in Seconds
https://www.rfdtv.com/story/45780564/origin-storage-store-nfts-with-ipfs-filecoin-in-seconds

FVM: The Next Milestone for Filecoin, Welcome All Developers | ORIGIN Storage
https://www.marketwatch.com/press-release/fvm-the-next-milestone-for-filecoin-welcome-all-developers-origin-storage-2022-02-16
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
ORIGINStorage Twitter: https://twitter.com/OriginStorage_ 
ORIGINStorage channel: https://t.me/originstoragec
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
1. For general user data and web3.0 application data, we are building a scalable distributed storage facility using the IPFS standard API. Web3 developers or general users can store static resources/videos/images etc. to the IPFS network and choose to persist the data fixed in the IPFS to the Filecoin network.

2. We plan to do something with our ally company to test the storage and retreival on p2p cdn network.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The allocation strategy is to make DataCap better used. We adopt different review strategies according to customer types and a phased allocation strategy for each allocation of DataCap, which can be outlined as follows.
(i) Different types of customers have different allocation and review rules.
(ii) Approved DataCap will be delivered to customers gradually to ensure that we are able to monitor the correct use of DataCap shares by our customers.

1. Allocation of shares by customer type
First, we divide the applicants into (i) general users and web3 developers (ii) corporate entities or organizations. It is expected that 30% of our DataCap quota will be allocated to general users and web3 developers, and the remaining 70% will be allocated to corporate entities or organizations.

Therefore, there are different rules that apply to these two types of applicants.
(i) For regular users, identity verification (the real name verification) will be performed. In order to promote the use of Filecoin among the general user community, the verification for general users will be minimized by allocating a maximum of 3 times per person, with a maximum of 1Tib per application, and the approval of the second application will be based on the applicant's rating.


(ii) For web 3.0 developers, who will be the ones strongly supported. Only the time of their GitHub registration and the site of their web3.0 application will be verified to ensure their authenticity. There is no limit to the number of applications, with a maximum of 10Tib per application. The approval of the second application will be based on the applicant rating and the impact of the applicant's application.

(iii) For entities, 70% of the DataCap quota is used on data storage for social enterprises, well-known Internet companies, research institutes, public welfare organizations, and other organizations. Since the early DataCap quota market is not mature enough, we will be proactive in acquiring valuable applicants. We have worked with several web2.0 companies who are potential applicants for our quota and are well known in China and the world. We are bringing this applicant data to Filecoin, which will help the ecological landing of Filecoin.

2. Phased allocation of shares
First, any applicant's DataCap will be allocated in stages, and the applicant will usually only receive 20% of the allocated share in the first stage. Only when it is determined that the current stage share is being used correctly will it be possible to receive the allocation of the next stage share. Applicants must meet the requirements: (i) storing only approved and compliant data (ii) not trading with a single SP.
Secondly, we will evaluate the applicant's score for each phase, which will affect their next application.

Applicant's scoring adjustment rules: Refer to the scoring rules form to rate applicants: https://docs.google.com/spreadsheets/d/1elUmUpJlQbsVoJlL3K8ibLQP88t0oLCL36TaTiq5KoU/edit?usp=sharing

The allocation process is basically as follows.
(i) Each applicant provides application information to initiate the review process.
(ii) Based on the information provided by the applicant, an initial review will be conducted, and the applicant must have a reasonable need for data storage. The requested share size must match the data storage requirements.
(iii) Applicants who fail the initial review will be asked to provide additional information, and applicants who fail the re-examination and refuse to provide additional information will be rejected.
(iv) For corporate entities or organizations, applicants that pass the initial screening will proceed to the due diligence phase; for individual users and web3 developers, they will proceed to the DataCap review phase.
(v) For entities or organizations that pass the due diligence and individual users and web3 developers that pass the preliminary review, the rating scoring process will begin. There may be cases where the allocated share is less than the share applied for by the applicant, which will be awarded based on their storage needs and the rating results.
(vi) Notify applicants in written form whether they have been awarded or denied.
(vii) Tracking and spot-checking the applicant's DataCap usage on an ongoing basis.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The key allocated to the DataCap is protected on the multi-signature hardware wallet.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
The following content will include a survey of applicant information prior to approval and a review of DataCap usage after approval.

1. Information survey of applicants
(i) Only their identity will be verified for individual users, and the basic verification will be ensured. In contrast, another verification is minimized to promote the use of Filecoin in the general user community.
(ii) For web 3.0 developers, we will verify their GitHub registration years and project websites to minimize other verifications and promote the use of Filecoin in decentralized applications.
(iii) For corporate entities or organizations, we will verify their entity information (including but not limited to registration number, registration date, registration certificate, board members, and beneficiaries), business type, data source, data samples, detailed usage plans, etc.

2. Review of usage
Post-allocation review will be conducted on an ongoing basis to avoid misuse of DataCap, guarantee the original purpose of Filecoin plus, and perform the duties of a notary. The review is based on the principle that it is the responsibility and obligation of the applicant to use the DataCap only for approved purposes. Since DataCap is allocated on the principle of phased distribution, subsequent quotas for applicants who do not pass the review will be delayed and even canceled. The specific review path is as follows (not excluding the continuation of additional review provisions).
(i) We require DataCap applicants to provide transaction Cid and minerID. For unencrypted data, we conduct random retrieval spot checks, and if the applicant has any violations of DataCap distribution, we will take measures to stop further distribution.
(ii) We verify that the user distributes the requested DataCap to at least three SPs to improve data storage security while reducing the possibility of misuse.
(iii) We establish a reputation scoring system to rate the applicant during the usage process, which will affect the applicant's next phase of quota distribution and the next DataCap application, further promoting the applicant's proper use of the quota he/she has received.

During the process of performing due diligence, we will ask the following basic questions to the applicant first:
(i) Self-introduction
(ii) Knowledge of Filecoin
(iii) Business requirements and data format
(iv) Data sources and data samples
(v) If the application is approved, the minerID that costs DataCap, and the detailed usage plan such as the quota between miners
(vi) Data security, any violation of local laws
(vii) Profitable or not

We will maintain the principle of conducting reasonable investigations without burdening the applicants with investigations and combine this with a phased distribution mechanism to ensure proper use of DataCap by our customers and do our best to promote Filecoin.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. Conduct regular and continuous reviews with the help of various statistics from https://filplus.d.interplanetary.one/ and filfox.info to ensure that the assigned DataCap is not abused or misused according to the deal.

2. DataCap will be allocated in stages. If any improper use or misuse of the allocated DataCap is found, the unallocated DataCap may be reduced or even canceled. The score may be penalized to further ensure the proper use of the DataCap.

Applicants with abnormal usage will be contacted and dealt with promptly.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Github repo
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Saving more detailed information in own GitHub repo, while making it public in the public repository：
https://github.com/filecoin-project/filecoin-plus-client-onboarding
https://filplus.info/
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
10h+
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
N/A
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
N/A
```

**Comment by galen-mcandrew** [comment]
[Origin Storage - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320945/Origin.Storage.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by llifezou** [comment]
> [Origin Storage - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320945/Origin.Storage.-.Round.3.Notary.Election.Scorecard.pdf)

For Allocation Strategy

- We will further improve our [allocation strategy](https://docs.google.com/spreadsheets/d/1elUmUpJlQbsVoJlL3K8ibLQP88t0oLCL36TaTiq5KoU/edit?usp=sharing) based on our use case and referring to the existing excellent Allocation Strategy. This is our allocation guide (and will be constantly improved):  [allocation strategy](https://docs.google.com/spreadsheets/d/1elUmUpJlQbsVoJlL3K8ibLQP88t0oLCL36TaTiq5KoU/edit?usp=sharing)

For Bookkeeping Plan

- We will fully follow the FIL+ guidelines and will publish our allocation decisions on Github.
- First we will make all the information public:
  https://github.com/filecoin-project/filecoin-plus-client-onboarding
  https://filplus.info/
  And, we will build our own more detailed database for data auditing and analysis. We will be open to any audits.

**Comment by Kevin-FF-USA** [comment]
Hi  @llifezou **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is North America.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by llifezou** [comment]
Thank you very much! Here is my response:
> Please confirm that the region of operation for client applications you will focus on is North America. 

ACK

> Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

> • Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .

ACK

> • Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 

ACK

> • Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 

ACK

> • No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

ACK

> • Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

ACK

> • Community Governance Participation: It is expected that you will participate in the program 10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 

ACK, We are on `slack`, @cryptostack-zou and @abc

> Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

Our SPs list: [ORIGIN Storage](https://docs.google.com/spreadsheets/d/1KHXyg4hVqRIiSYu5gIQ535gKFDYONi__D2EYoPLKmG0/edit?usp=sharing)

> Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

ACK

> (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
> • If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x) 

Thank you for your kind reminder. We have purchased ledger-nano-x.
The address is still the one submitted in the application: f15pdtdfufssdirb4fxdvdlbwbwm6ig6dbvuf23dy

**Comment by galen-mcandrew** [comment]
@llifezou 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by llifezou** [comment]
> @llifezou
> 
> Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

Thank you! We have submitted it.

**Comment by llifezou** [comment]
@galen-mcandrew @Kevin-FF-USA  I'm very sorry, the nano x we ordered was only received today, but I found that the wallet generated by lotus could not be imported into the nano x, and now I have to change a notary's address. Generated a new address with nano x, and it has been determined that nano x can log in https://plus.fil.org/
Our new address is: f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga

**Comment by Kevin-FF-USA** [comment]
Thanks @llifezou  - I've updated your application with this new address.

**Comment by Kevin-FF-USA** [comment]
Hi

**Comment by Kevin-FF-USA** [comment]
Hi @llifezou,
I'm trying to link your application and wallet to your SLACK address in the Filcoin board. Will you please send me a SLACK DM to confim your account?
Kevin - Filecoin Foundation
https://filecoinproject.slack.com/archives/D02KTGPJ36F

**Comment by llifezou** [comment]
> 

Thanks, I sent you a message on slack

**Comment by Kevin-FF-USA** [comment]
Thanks @llifezou 
For tracking, I'm pasting the name of the SLACK handle here. If this is NOT you, please let me know.
![image](https://user-images.githubusercontent.com/94004586/167343637-e401fab6-8ce0-472c-a17b-2e312f88a108.png)

**Comment by llifezou** [comment]
accountable to the organization/ledger: Tuo Qi

**Comment by llifezou** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedznkkpwozkuswhzc2gzdoz3lo42srusdwhctxewdlekibwtwoyq4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedznkkpwozkuswhzc2gzdoz3lo42srusdwhctxewdlekibwtwoyq4

**Comment by derricktan23** [comment]
Derrick is part of the organization and can communicate on our behalf in SLACK.

**Comment by llifezou** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacea43ea2mwxcklhf6mfwcxfnbtul732dhj2auvo6fpj2ewias5ssvg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea43ea2mwxcklhf6mfwcxfnbtul732dhj2auvo6fpj2ewias5ssvg

**Comment by llifezou** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebzubzui47cedstypbrtbql2nphntbymhif6tzfifq6ondtkbdvce
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzubzui47cedstypbrtbql2nphntbymhif6tzfifq6ondtkbdvce

**Comment by llifezou** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecw7v6u4ocwrzgqjjd23s25pvxxs2ll5mhqoenwcyphvngoalq3hq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecw7v6u4ocwrzgqjjd23s25pvxxs2ll5mhqoenwcyphvngoalq3hq

**Comment by Tom-OriginStorage** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceb5akx7gcdjq5w4ez5nr757eooagj2orsssypbqhwekbkrpbcypkk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5akx7gcdjq5w4ez5nr757eooagj2orsssypbqhwekbkrpbcypkk

**Comment by Tom-OriginStorage** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceaeirgcug5cgsskiswvvoqhcbj37geed3qvohyt3foywb2zd4r6eo
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaeirgcug5cgsskiswvvoqhcbj37geed3qvohyt3foywb2zd4r6eo

**Comment by Tom-OriginStorage** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaced7mewwzabvwmt4zogtonikmhsayrgyo2umna2zgduvdwdb454dfe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7mewwzabvwmt4zogtonikmhsayrgyo2umna2zgduvdwdb454dfe

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzacedwzxclr5vxt2kibi42lrgiihh42ytlknllcscqz634iafcelakym
