### ISSUE TITLE
Notary Application: Tianji Studio

### ISSUE THREAD

**Issue by liyunzhi-666** [filecoin-project/notary-governance#453]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Bailey-li
- Affiliated organization: Tianji Studio
- Website / Social Media:
- On-chain address to be notarized: f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
- Region of Operation: Greater China
- Use case(s) to be supported: Web 3.0 / Decentralized Applications, User Content, Scientific Data, Media & Entertainment
- DataCap Requested: 1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
GitHub handles: IPFS-grandhelmsman
slack handles: Patrick-li
- Participated in Trusted Setup Ceremony Phase 1 https://github.com/arielgabizon/perpetualpowersoftau/blob/master/README.md
- Participate in the first phase of the testnet that started in December 2019, ID: t019125, and the final storage capacity exceeds 1PiB
- PB-scale Miner Testing,E-mail submitted the relevant test plan,the email was sent to the Filecoin team, and Filecoin team members like @why @keren knew about it https://github.com/filecoin-project/devgrants/blob/master/rfps/rfp-pbscale-miner-testing.md
- Selected as a member of Filecoin Security Research Fellowship by Filecoin team,@why is one of the organizers, he can prove it https://security.filecoin.io/
- Participated in Trusted Setup Ceremony Phase 2 https://filecoin.io/blog/trusted-setup-complete/
- Participate in HackFS, the project is called Filecoin123 https://hack.ethglobal.co/showcase/filecoin123-recBa27E4zfpHRRln
- Participated in Space Race, and finally ranked 22nd in the world (name: Five Star-Helmsman&Heiben) Miner ID: t03176 https://spacerace.filecoin.io/
- Participated in the slingshot competition, project name: 1. Starry sky in Yunnan 2. Filecoin-Crawl
- Participated in Slingshot-Phase 1 Closing Ceremony https://www.youtube.com/watch?v=qheNJZ1DClM&list=PL_0VrY55uV19nu6orLLCaGCGocsjvpiGZ&index=1
- Participated in Trusted settings for V15 network upgrade https://filecoin.io/blog/posts/trusted-setup-complete-for-network-v15-upgrade/

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Until March 1, 2022
The total Address Balance is about 530680.5907 FIL
The total Initial Pledge is about 615573.9679 FIL
The total Power is about 60.25 PiB
The details are as follows: https://github.com/liyunzhi-666/IMG/blob/main/miner%20id.png  
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- Participated in Trusted Setup Ceremony Phase 1 https://github.com/arielgabizon/perpetualpowersoftau/blob/master/README.md
- Participate in the first phase of the testnet that started in December 2019, ID: t019125, and the final storage capacity exceeds 1PiB
- PB-scale Miner Testing,E-mail submitted the relevant test plan,the email was sent to the Filecoin team, and Filecoin team members like @why @keren knew about it https://github.com/filecoin-project/devgrants/blob/master/rfps/rfp-pbscale-miner-testing.md
- Selected as a member of Filecoin Security Research Fellowship by Filecoin team,@why is one of the organizers, he can prove it https://security.filecoin.io/
- Participated in Trusted Setup Ceremony Phase 2 https://filecoin.io/blog/trusted-setup-complete/
- Participate in HackFS, the project is called Filecoin123 https://hack.ethglobal.co/showcase/filecoin123-recBa27E4zfpHRRln
- Participated in Space Race, and finally ranked 22nd in the world (name: Five Star-Helmsman&Heiben) Miner ID: t03176 https://spacerace.filecoin.io/
- Participated in the slingshot competition, project name: 1. Starry sky in Yunnan 2. Filecoin-Crawl
- Participated in Slingshot-Phase 1 Closing Ceremony https://www.youtube.com/watch?v=qheNJZ1DClM&list=PL_0VrY55uV19nu6orLLCaGCGocsjvpiGZ&index=1
- Participated in Trusted settings for V15 network upgrade https://filecoin.io/blog/posts/trusted-setup-complete-for-network-v15-upgrade/
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
We have submitted a lot of bugs that can help Filecoin improve its security. Here are some bugs
filecoin-project/rust-fil-proofs 
a sanity check failed of window post haven't catch.
https://github.com/filecoin-project/rust-fil-proofs/issues/1308
The ability to read files in parallel is required when window post occurs
https://github.com/filecoin-project/rust-fil-proofs/issues/1281
Suggest to add more sector information in case of fault.
https://github.com/filecoin-project/rust-fil-proofs/issues/1261

filecoin-project/lotus
it's very slow to called `lotus-miner info` when the sectors number is 
over 10000.
https://github.com/filecoin-project/lotus/issues/3913
miner attempting to prove commit over 200 sectors in epoch
https://github.com/filecoin-project/lotus/issues/3638
Some new deals from storage markets have append to a old sector which one have a 
invalid deal.
https://github.com/filecoin-project/lotus/issues/3594
It seems have a dead lock in messagepool when push message.
https://github.com/filecoin-project/lotus/issues/3115
`lotus state wait-msg` can not wait the `mpool replace` messages.
https://github.com/filecoin-project/lotus/issues/2943
invalid proof (compute error?): failed to fill whole buffer
https://github.com/filecoin-fivestar/lotus/issues/71
How can i get a rpc error return when define a chan response in rpc call?
https://github.com/filecoin-project/go-jsonrpc/issues/14
Suggest adding IP output of client to log when JWT Verification failed.
https://github.com/filecoin-project/lotus/issues/1870
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Tianji Data was established in Shenzhen, China, and the team was established in 2018. Since its establishment two years ago, it has been committed to the ecological construction of blockchain. Its products include DappOnline, TJWallet, Filecoin ecological construction, etc, we are the best data service provider and distributed storage solution provider.
DappOnline is the world’s leading blockchain ecological application store. It uses “DApp big data + DApp application + blockchain ecology” as the framework. Information, evaluation, analysis, recommendation, etc. can all be consulted. It is loved by many users all over the world;
TJWallet is another product of Tianji Data. It provides a one-stop digital asset management solution with a dual ecological guarantee of “software wallet + hardware wallet”, which fully combines the security of hardware wallets and the ease of use of software wallets. 
Software wallets can manage blockchain assets with one click, and provide BTC, ETH, TRX, Filecoin, ACL, and all ERC20, TRC10, TRC20 and other digital asset transactions and transfers and other fullchain asset management; hardware wallets act as flash drives and Offline storage of the user’s blockchain private key, the full name is offline disconnection operation, the private key will not leave the hardware wallet, the entire transaction verification process is completed in the hardware wallet itself. The encrypted currency stored in the wallet remains offline and cannot be hacked.
TJWallet is the first digital wallet tool in the 2020 star project IPFS/Filecoin ecosystem that supports F1/F3 full-chain full-function transaction transfer.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://dapponline.io/
https://tjwallet.net
https://twitter.com/DappOnline
https://twitter.com/TJ_Wallet
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://dapponline.io/
https://tjwallet.net
https://twitter.com/DappOnline
https://twitter.com/TJ_Wallet
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://twitter.com/DappOnline
https://twitter.com/TJ_Wallet
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
I hope to help and support the development of filecoin. I hope different types of real data are stored in the filecoin network. In my previous survey, I especially hope to meet these types of data stored in the network:

- Data is static and infrequently accessed
- Data does not require encryption
- Dataset needs to have "public good" characteristics — have social justice, life sciences, environmental or cultural heritage value (e.g., climate change, scientific research datasets, museum or art collection archives)

```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
After several months of conference calls, I think the plan is feasible
Define thresholds with different levels of trust.The higher the requirements, the stricter the review：
Several important factors:

- Reputation of the applicant organization
- Is there any contribution to the Filecoin ecosystem (not necessarily a factor, but it will be a bonus item)
- Scale of allocation
- Assigned rating
- Safety Precautions
- Customer transparency

The type of data applied for (the public data set will be given priority)
The specific distribution plan can be viewed in the Google shared table：https://docs.google.com/spreadsheets/d/1AsAyaW1mV-eKyaqLWWTIAsaWHf24YNCriinHc-naJrs/edit?usp=sharing
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Fix the key of the address assigned to DataCap in the hardware wallet.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Divided into individuals and organizations

- personal account:
- Can use third-party authentication information

Organize customers:

- Review organization entity information (registration information, etc.)
- Corporate identity

I will ask these questions:

- Personal information (Github, Twitter, Linkedin handle)
- In which regions do you plan to use DataCap
- Can the data set be shared
- Provide data set sharing list

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
I will regularly check and review the use of datacap to determine
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, I will publish these records in the GitHub repo. For the sake of transparency and fairness, I do not intend to send them via email or telegram.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
I intend to keep records of allocation decisions and make these records public in the GitHub repo. I will respond to all review requests
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
About seven hours a week
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None
```

**Comment by galen-mcandrew** [comment]
[Tianji Studio - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320925/Tianji.Studio.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by liyunzhi-666** [comment]
Regarding "Client Due Diligence" I would like to make the following modifications @galen-mcandrew @dkkapur  @Kevin-FF-USA 
In order to ensure the fairness and justice of DataCap distribution, we have formulated separate online and offline application procedures based on the number of DataCap applications and individual and corporate users.
For individual users:
We will review their Github registration years (180 days at least) to prevent malicious application bots. The amount of approval will also be controlled below 5 TiB.
For business users:
We have developed different review methods and requirements based on the number of their DataCap applications.
If it is less than or equal to 20 TiB, we will use online review. The following points will be reviewed.
• Business license
• Enterprise authorization letter (CEO's signature + seal)
• All shareholders who account for more than 25% of the total number of shareholders must provide ID cards or passport photos.
• Sample data submission (accounting for 0.2% of its total DataCap requests)
If the application is larger than 20 TiB, we will add offline comments based on online surveys (visit customers on business trips or invite them to our company).
Enterprise business type
• data source
• Data volume (monthly)
• What companies think about Filecoin
• Data storage plan
Question:
Please introduce yourself and your personal information on social media (official website, WeChat, LinkedIn,, GitHub).
• What is the purpose of your application for DataCap?
• Please provide the wallet address you want to apply for DataCap
• Please provide the quota of Datacap you want to apply for.
• Please provide the name of the organization, nationality, country of registration, time of registration, name of the executive, and relevant website (if you are an institutional user).
• Please provide the region where you want to use DataCap, if it is more than one region, please pay attention.
• How many miners do you plan to distribute DataCap to, if there are specially designated miners, please pay attention.
• Have you assigned DataCap before? If so, please provide details.

**Comment by Kevin-FF-USA** [comment]
Hi  @liyunzhi-666 **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Greater China.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 7 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by galen-mcandrew** [comment]
[Bailey-li - UPDATED - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8373160/Bailey-li.-.UPDATED.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by liyunzhi-666** [comment]
In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

Please confirm that the region of operation for client applications you will focus on is Greater China.  
-confirmed

Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

• Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
-confirmed

• Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
-confirmed

• Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
-confirmed

• No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
-confirmed

• Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
-confirmed

• Community Governance Participation: It is expected that you will participate in the program 7 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
-confirmed

Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  
-We provide storage and routine maintenance services to these miners: f03176 f065113 f066302 f066476 f080868 f01246563

Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  
-confirmed

(If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
• If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x) 
f3qyxn5wagcfqysm53cfyon2b5lxes35w6v2bnhuxpmwujko3vy4rrobiw6rl62n2et7276gu2gm4tw527cqzq
As of now I don't have a Ledger, and I've reached out to Kevin in slack with my questions. If other wallets can't replace Ledger wallet, then I will buy a Ledger as soon as possible

**Comment by galen-mcandrew** [comment]
@liyunzhi-666 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by liyunzhi-666** [comment]
@Kevin-FF-USA 
Request to change the address
f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq

**Comment by Kevin-FF-USA** [comment]
Hi @liyunzhi-666 
Received the request for change to this application.  For safety and security, can please confirm and link your SLACK ID handle here for accountability?

**Comment by liyunzhi-666** [comment]
of course @Kevin-FF-USA 
Request to change the address
f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
SLACK ID
Patrick-li

**Comment by liyunzhi-666** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaced4rrwa7z2ooaq6547xsdgd3nrk4qbbmwjnqog5lrxwrm7hpt475s
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4rrwa7z2ooaq6547xsdgd3nrk4qbbmwjnqog5lrxwrm7hpt475s

**Comment by galen-mcandrew** [comment]
We've now updated the address, but the 1FIL was already sent to the previously supplied f3 address. You can move that from the f3 address to your new address, f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq

Thanks!

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Datacap Allocated
> 1PiB

**Comment by liyunzhi-666** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebfl7dvx7b2hjgsyzfbpfzoalhzika73bqepldext2jotebztegf2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfl7dvx7b2hjgsyzfbpfzoalhzika73bqepldext2jotebztegf2

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzaceat72il2oaq3z5sp7d36fqmcolbie6qkcs5au4sh32cbxzv6xnrbi
