### ISSUE TITLE
Notary Application: LendMi

### ISSUE THREAD

**Issue by Rongze92** [filecoin-project/notary-governance#455]
# Notary Application
To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form.

## Core Information

- Name: LendMi
- Affiliated organization: LendMi team
- On-chain address to be notarized (recommend using a new address): f1j2v2uoziz5uiaeh54fx7vjipju23xpzbzcnf2hy
- Region of Operation: Asia minus GCN
- Use case(s) to be supported: User Content, Scientific Data, Media & Entertainment, Other
- DataCap requested for allocation (10TiB - 10 PiB): 10TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

```
At the beginning of 2021, the LendMi team started the Filecoin joint mining activities and cooperated with many larger Filecoin nodes.
In April 2021, LendMi launched smart contracts on Heco chain, raised Fil, and issued revenue through smart contracts. There was over 1 million Fil raised in total, with over 110,000 transactions accessed by smart contracts and over 350 people involved. The data is traceable on the chain.
In June 2021, LendMi synchronized to BSC chain and launched smart contracts. More than 300k Fil raised with over 5600 transactions accessed by smart contracts and over 150 people involved in the process. The data is traceable on the chain.

More:
Heco Smart Contract Adress: 0x1a2f689677e5f4e2cc07743e524922bb126d5a81
BSC Smart Contract Adress: 0x4ca004fd6d24f3db88d321f1c37cc7a89af82018
Official Site：lendmi.finance
Telegram：t.me/lendmi
Twitter：twitter.com/LendMi_Official
```

## Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

```
| ID | Adress Balance | Initial Pledge | Locked Rewards |
| f0155049 | 8269 | 442623 | 82140 |
| f0154335 | 2455 | 330176 | 77785 |
| f0153078 | 158 | 28417 | 5007 |
| f0137594 | 437 | 20213 | 6048 |
| f01488667 | 55 | 2259 | 0 |

Total 1,006,042 FIL

Substantiating evidence: Node Owner signature (https://lendmi.finance/vfil)
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow.

```
Contributions for FIL holders on Heco and BSC chains:
- Over 500 people use LendMi smart contracts to make deposits and earn income.
- High interest rate on deposits, varying from 10% to 45% APY depending on lock-up time.
- More than 2 million FIL in accumulated deposit flow.
- More than 100k FIL of accumulated earnings distributed to users.

LendMi's contribution to miners:
- Worked with over 10 Filecoin nodes and lent FIL to them.
- Provided FIL pledges for 151 PiB computing power.
```
### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions.

`None`

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

```
LendMi team has been working on Filecoin mining since the beginning of 2021, having experimented with Defi innovation on Ethereum chain previously, founded in 2020, Singapore.
LendMi currently has proven experience in Filecoin mining and smart contracts and is researching FVM and Near network.
LendMi team consists of DeFi researchers, smart contract engineers, Web3 front-end engineers, UI, UE, testing, etc., 11 members in total.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

```
Website: https://lendmi.finance
Telegram：t.me/lendmi
Twitter：twitter.com/LendMi_Official
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

```
https://www.jinse.com/news/blockchain/1144872.html
http://xueqiu.com/5828221731/194470253
Many articles and reports were taken down due to policy reasons.
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.

```
Telegram：t.me/lendmi
Twitter：twitter.com/LendMi_Official
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?

`We are open to use cases.`

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and the rate at which you'll allocate DataCap.

```
The storage that has passed the application is released in stages, and the usage situation will be tracked continuously. If the storage is used properly, the release will be continued. On the contrary, if the storage is insufficiently used, the subsequent release will be ceased so as to follow the rule of survival of the fittest. 
First stage: 20%
Second stage: 30%
Third stage: 50%

Evaluation criteria:
Successfully allocated storage scale (20%)
Storage sealing speed (20%)
Quality of the storage (30%)
Diversity of miners (10%)
Diversity of use cases (10%)
Transparency (10%)
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
We will use multi-signature hardware wallets to protect the keys used to distribute DataCap.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them?

```
1. First of all, only verified customers are eligible to apply. The following criteria need to be met to become a verified customer.
The company
-has been established for more than six months.
-has an existing project website and ready-to-use products.
-has over 100T of storage capacity and a complete available storage solution.
-has proof of ability to ensure data integrity.
-has reasonable use cases and storage plans.

2.For verified customers, we will evaluate their applications and communicate remotely about the applied storage and evaluation criteria.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.

```
First, we will regularly review our clients' usage plans and publish their transactions' details. We will calculate whether the percentage of transactions allocated is reasonable.

We will send a warning if a customer allocates Datacap to a single entity by mistake. We will cease the next allocation for clients who keep violating the rules after a warning. A warning will be issued to the public in the Filecoin community. Further cooperation will no longer be accepted.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both?

`GitHub and Telegram.`

Where do you plan on keeping a publicly accessible record of all your allocation decisions?

```
In GitHub.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.

`10-20 hours per week.`

### Past allocation
Have you previously received DataCap to allocate before? If so, please link to any previous applications.

`None`

Cumulatively, how much DataCap have you previously successfully allocated?

`None`

**Comment by galen-mcandrew** [comment]
[LendMi - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320876/LendMi.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
We are very sorry to let you know that this application was not selected in this round of Notary Elections.  

Each application was scored according to the Rubric and [assigned a Scorecard](https://github.com/filecoin-project/notary-governance/issues/394). That score was then applied for each of the [geographic regions and the top scored applications were selected](https://github.com/filecoin-project/notary-governance/issues/479). 

We are humbled by your commitment, and grateful for your interest in the Filecoin Plus program. Looking forward to seeing you in the program and hope you resubmit in the future elections.

Should you have any questions please feel free to raise here, or DM me in Slack @Kevin_FF
