### ISSUE TITLE
Notary Application: FBG Capital

### ISSUE THREAD

**Issue by GaryGJG** [filecoin-project/notary-governance#458]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Gary Gao 
- Affiliated organization:  FBG Capital 
- Website / Social Media: 
- On-chain address to be notarized (recommend using a new address): f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
- Region of Operation:  Asia minus GCN 
- Use case(s) to be supported: Web 3.0 Applications/ Web 2.0 Applications/ Developer Tools/ Scientific Data/ User Content/ Professional Services/ Media & Entertainment 
- DataCap Requested: 1 PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Founded in 2017, FBG Capital is Asia’s leading digital asset management and investment firm.

We started Filecoin mining back in 2020. As of Feb 2022, we have data center setup in Singapore and 
North America.

We are dedicated to supporting the whole Filecoin ecosystem. We’ve invested a few Filecoin eco projects & funds, 
such as CID Gravity, FilSwan and Fenbushi Capital. We’re also planning to set up a stand-alone Filecoin eco fund
to further support the Filecoin eco projects.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
<pre>
About 1.36 MM FIL (Miner ID: <a href="https://filfox.info/en/address/f092228">f092228</a>, <a href="https://filfox.info/en/address/f0130884">f0130884</a>, <a href="https://filfox.info/en/address/f0112667">f0112667</a>, <a href="https://filfox.info/en/address/f0402661">f0402661</a>, <a href="https://filfox.info/en/address/f0155050">f0155050</a>, <a href="https://filfox.info/en/address/f01372912">f01372912</a>, <a href="https://filfox.info/en/address/f01238519">f01238519</a>) 
</pre>

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- We started Filecoin mining back in 2020.
- We’ve invested a few Filecoin eco projects & funds, such as CID Gravity, FilSwan and Fenbushi Capital. 
  We’re also planning to set up a stand-alone Filecoin eco fund to further support the Filecoin eco projects.
- We’ve co-hosted an online Filecoin anniversary event (Enter the metaverse - Anniversary of Filecoin Mainnet 
  Launch) with FilSwan on 19-20 Oct 2021.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
NA
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Founded in 2017, FBG Capital is Asia’s leading digital asset management and investment firm with 50 employees 
worldwide.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
<pre>
<a href="https://www.crunchbase.com/organization/fbg-capital">https://www.crunchbase.com/organization/fbg-capital</a>
<a href="https://twitter.com/FBGCapital">https://twitter.com/FBGCapital</a> (~13k Followers) 
</pre>

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
<pre>
<a href="https://www.forbes.com/sites/jeffkauflin/2018/08/01/tricks-of-a-crypto-trader-meet-asias-hottest-crypto-hedge-fund/amp/">https://www.forbes.com/sites/jeffkauflin/2018/08/01/tricks-of-a-crypto-trader-meet-asias-hottest-crypto-hedge-fund/amp</a>
<a href="https://www.coindesk.com/business/2021/09/28/clearpool-raises-3m-to-build-decentralized-capital-markets-ecosystem-on-ethereum/">https://www.coindesk.com/business/2021/09/28/clearpool-raises-3m-to-build-decentralized-capital-markets-ecosystem-on-ethereum</a>
<a href="https://nairametrics.com/2021/10/26/deal-coinlist-raises-100-million-in-funding-round-now-valued-at-1-5-billion/">https://nairametrics.com/2021/10/26/deal-coinlist-raises-100-million-in-funding-round-now-valued-at-1-5-billion</a>
<a href="https://www.coindesk.com/tech/2021/11/17/oasis-launches-160m-ecosystem-fund-with-backing-from-jump-capital-and-others/">https://www.coindesk.com/tech/2021/11/17/oasis-launches-160m-ecosystem-fund-with-backing-from-jump-capital-and-others</a>
</pre>

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
<pre>
<a href="https://twitter.com/FBGCapital">https://twitter.com/FBGCapital</a> (13k Followers)
<a href="https://www.linkedin.com/company/fbgcapital/">https://www.linkedin.com/company/fbgcapital</a> (2k Followers)
</pre>

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We’re willing to support all kinds of use cases.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
<pre>
We will leverage some existing best practices.

Allocating the DataCap is all about distinguishing rational clients from malicious clients, and as such, 
Our allocation strategy seeks to emphasize the key question "how much does the Notary trust the client?" 
rather than "does the Notary trust the client?". We will set up thresholds with varying degrees of trust. 

The way we traditionally audit Notaries can also be used to audit clients as well. 
We define 7 varying degrees of trust. The <a href="https://docs.google.com/spreadsheets/d/1zQ3FXJmmBMmynDIdRjYTYp-K95Dp95ypVoBfRhABPC0/edit#gid=819225433">Rubric</a> will be the primary guideline we use when 
evaluating a client and determining their DataCap allocation. 

These scoring guidelines can serve as a tool of assessment and further add a level of consistency 
across the board.
</pre>

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will use hardware wallet to store the keys associated with the DataCap allocation address securely. 
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 
For individual clients, online identity will be verified by both account age and account activity perspectives, 
and this will serve to prove that they are valid users and not bots or sybils. 
Third-party tools like twitteraudit may also be used to verify online identities. 

For organizational clients, application organizations should be easy to verify through the appearance of their application. 
The developing applications may require further stringent investigation; 
this is to ensure that the application is valid and enclosed with meaningful content, rather than the shell of a malicious client. 
Large public datasets hosted by organizational clients are easy to verify because the data should be unencrypted and accessible to anyone. 
However, in the event that the organizational client has large private encrypted datasets(i.e., law firms), the Due Diligence procedure will be executed.

Below is the proposed procedure of Due Diligence. We need 3 types of information for review by myself or our compliance team depending on the volume of clients required Due Diligence:
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information; 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name;
 - date of birth; 
 - street address (P.O. box number is not acceptable); 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

There are two questionnaires to help me get to know our clients. The first one is about the basic information collection of new clients. 

Questionnaire #1
Please describe answers as much specificity as you can.

1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.)
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
6. How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify.
7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
I will use the second questionnaire to collect follow-up answers about previous allocations for returning clients. 

Questionnaire #2
Since you have requested DataCap from me before, I have some questions regarding your previous DataCap allocation.

1. How much cumulative DataCap was allocated to you from me?
2. In which region(s) did you use the DataCap?
3. What was your use case for the previous allocation?
4. Did you specify any advanced features for the previous allocation?
5. How many miners did you allocate the DataCap to? Please specify transaction links to the storage deals.
6. In your previous allocation, did you violent any community principles like excessive/unfair self-dealing?
7. Is there anything I could improve to serve you better in future allocations?

Utilizing the information collected will help me confirm that the client is not improperly using the DataCap they were previously granted. 
Clients are encouraged to allocate the DataCap to more than 5 different miners, 
which not only increases storage redundancy but also helps maintain decentralization and reduce the possibility of potential misuse. 
The more miners clients allocate, the more DataCap clients are likely to get. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We will follow the FIL+ guidelines and conduct all our allocation decisions publicly on Github.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
<pre>
GitHub & some public websites: 
- <a href="https://github.com/filecoin-project/filecoin-plus-client-onboarding">filecoin-plus-client-onboarding</a> 
- <a href="https://filplus.info/">filplus.info</a>

All allocation decisions will be guided by the rubric publicly on Github.  
Since all interactions are intended to occur publically, most allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly, e.g., the Github repo.
If convincing justifications can't be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
Depending on the arbitrator's decisions, a hearing may be given within 30 calendar days of the dispute resolution application. 
</pre>

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
About 10 hours per week.  
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No. 
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
NA
```

**Comment by galen-mcandrew** [comment]
[FBG Capital - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320856/FBG.Capital.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
**Hi @GaryGJG  based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!**  You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring. 

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

	1.	Please confirm that the region of operation for client applications you will focus on is Asian minus GCN. 
	
	2.	Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles). 
	
	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

	•	Community Governance Participation: It is expected that you will participate in the program 10 hours a week.  Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.

	3.	Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt. 
	
	4.	Please affirm that you will abide by the allocation / client due diligence plan you laid out above. 
	
	5.	(If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.
	
	⁃	**If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X** (link: [https://shop.ledger.com/pages/ledger-nano-x](https://shop.ledger.com/pages/ledger-nano-x))

**Comment by GaryGJG** [comment]
>

**Comment by GaryGJG** [comment]
Thank you very much, Kevin! Here is my response:

>   Please confirm that the region of operation for client applications you will focus on is Asia minus GCN. 

ACK 

>    Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles). 

>    Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

ACK
 
>    Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

ACK

>    Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

ACK

>    No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

ACK

>    Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

ACK

>    Community Governance Participation: It is expected that you will participate in the program 10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.

ACK

>    Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt. 

Here is the miner list owned by FBG: f092228, f0130884, f0112667, f0402661, f0155050, f01372912, f01238519

>    Please affirm that you will abide by the allocation / client due diligence plan you laid out above. 

ACK

>    (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

The address is f1jwmlgcjjmmknc5u43yxuxaghxylexwzbyfwjcgq (same as the address listed in the Core Information section above). it is brand new, no DataCap grant. 

>   If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x) 

Thanks for your kind reminder. we got one already.

**Comment by galen-mcandrew** [comment]
@GaryGJG 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @GaryGJG!

We have updated the address to: f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq

We will communicate via Slack: Gary Gao-FBG.

**Comment by GaryGJG** [comment]
> 

Thank you very much!

**Comment by GaryGJG** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedetnsl3z55nb5re74a6t7bq4amohgonwierkwyidj2ck6lkt6qle
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedetnsl3z55nb5re74a6t7bq4amohgonwierkwyidj2ck6lkt6qle

**Comment by dkkapur** [comment]
Notary address needs to be verified at plus.fil.org for direct allocations. Closing this issue for now.
