### ISSUE TITLE
Notary Application - Banyan

### ISSUE THREAD

**Issue by laudiacay** [filecoin-project/notary-governance#459]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Claudia Richoux
- Affiliated organization: Banyan
- Website / Social Media: 
- On-chain address to be notarized: f1oc6qvenzp7wsriu7edyebb325gnaovktmujl7jq
- Region of Operation: North America
- Use case(s) to be supported: Professional Services/Web 3.0/Other
- DataCap Requested: 100TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
My github is @laudiacay, and I am a former Protocol Labs developer working mainly on the Filecoin runtime. I have made contributions to Lotus, specs-actors, FVM, several dependency libraries of those, and contributed to internal tokenomics discussions daily during the term of my employment. I recently nucleated a startup (Banyan) in the PLN, and I'm applying as a DataCap Notary on behalf of Banyan DAO.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
I have my own personal limited amount of Filecoin that I got as part of my employment package. It's not a lot. However, my entire startup is building on filecoin, so there's a substantial amount of reputational stake... We will probably convert some fraction of our treasury/investor money into Filecoin at some point because the DAO needs to be holding Filecoin as a hedge/diversification, but we haven't done a round yet.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
My contributions are in my GitHub history, between September 2021 and February 2022, to various filecoin-affiliated repositories- FVM/ref-fvm, forest, specs-actors, lotus, and a few private security-patch repositories. You can also find my contributions in the PL slack by searching my handle, probably the ones I'm most proud of have to do with tokenomics in various crypto-econ threads.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
I patched several security bugs during my tenure as a Protocol Labs employee with zenground as my work manager.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Banyan's legal entity is an american corporation, but we intend to do most of our governance and work on-chain as a ve-tokenized DAO. The idea for the project has been in the works since December 2021, research and prototyping has been ongoing since, and we registered our corporation last month. I am currently the only full-timer, but we are working closely with engineers at FilSwan, as well as 4 advisors and part-time collaborators from PrimeDAO, a part time head of bizdev, and a senior UI/UX engineer who is working hourly on an as-needed basis. We're waiting on grant money to hire, but needed a legal entity and bank account first, which took a surprisingly long time to set up... As soon as that deposits we'll be hiring probably 3-4 more developers split evenly between frontend and smart contracts.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
banyan.computer (may not be updated by the time you see this- we are in build mode- but can send internal prototype docs as needed)
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
We'll be posting medium articles soon, which will be linked to from our website.
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
I usually stay off Twitter... That's not a great way to judge reputation. However, I do have a network of builders and investors in DeFi.
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Yes. Our Datacap will be given to users of our bridge who want to store files from L1s and L2s through our platform. The users will be paying for a service (to the DAO, to the infrastructure providers, and gas fees), so it's not exactly a profitable self-dealing situation.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
At first, we'll probably use it for people storing data from large, reputable B2B clients that are valuable high-profile entities using our service, like other protocols, in order to get them a discount and extra-reliable service from miners.

Our product takes clients (Alice) who want files stored in on one end, and has people (Bob) stake tokens in order to "promise" that they'll upload the requested file to a reliable Filecoin SP (sector faults will get Bob's stake slashed and given to Alice, so Bob has good reason to pick a reliable SP). We will allocate DataCap to Bob if Bob posts a stake, so that he can make a verified deal with Alice's data in it. Bob and the Filecoin SP may be the same person, holding the same keys- but they are bonded to storing Alice's very real paid-for data, or they cannot get any DataCap from us. This mechanism will prevent self-dealing, provided that we ensure that Bob's stake is high enough, and that we are careful about relaxing which Alices we grant DataCap for to ensure we don't create any strange arbitrage opportunities (we'll start with major un-filecoin-affiliated protocols, and slowly become more permissive from there).

"Bobs" will get one sector of DataCap at a time, as they stake to store "Alices"' files. The speed of allocation will depend on our platform's growth.

This is basically an economic L2 of Fil+, in a sense.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will start with it on a ledger device owned by me, and move control of the key over to a multisig of trusted core DAO contributors when the time comes. I will seek advice from connections at PL and FF about this, however, and follow their advice if it differs from my current plan.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
They will be economically bonded with a cryptocurrency stake on Ethereum, and given precisely enough datacap to store exactly the files they agreed to store, otherwise they lose their stake. They have no economic incentive to apply for this datacap if they act dishonestly (i.e., aren't planning to responsibly store the files that the DAO asked them to), as long as the Filecoin price does not rise substantially within the "grace period" of their SLA (before they start getting slashed on Ethereum for not uploading the requested CAR to Filecoin). That's a risk that can be somewhat mitigated by including some Filecoin in the ETH-side stake, but not entirely.

This is a permissionless, trustless system, so the incentives are probably a little different than most notaries, but this system works out to "I don't have to do any due diligence on the people I give the data cap to, because I have a smart contract ensuring that they use it honestly" and "I probably need to do light due diligence on the entities my DAO is storing files for, but if I make sure the tokenomics are properly balanced against weird arbitrage situations, I can maybe avoid needing to do due diligence on them as well".

When investigating the entities my DAO is storing files for, I will be prioritizing protocols with real users, where I know where the data is coming from, and where the brand is more or less a household name in DeFi. They need to have a real product that I can try and reputable investors/customers I can talk to. We'll formalize this more and create more guardrails (if an arbitrage opportunity exists by then) if: situations become less cut-and-dry with client reputability, when decisionmaking about this decentralizes more into the hands of tokenholders, and as we open up the program to more kinds of client data.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
In our system, we are pretty agnostic to SP, as long as the SP doesn't drop the requested files. The "Bob" client of Filecoin (a service provider to our DAO) can make deals with any entity they want to, as long as the "Alice" party in the example above has her files stored reputably. We don't really care about which SP the DataCap goes to, as long as the files stay up.

However... if it's required for the DataCap Notary program, it would be extremely easy to smart-contractually enforce (on Ethereum) that Bob must round-robin through some directory of reputable SPs, via some sufficiently-fair algorithm. The DAO is pretty indifferent to this, tokenholder incentive-wise. Either way, I'll ensure that we're in line with standards of not sending too much DataCap to any one SP.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Public, GitHub and DAO Discord.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
The GitHub repo isn't set up yet, email me at c@banyan.computer if you'd like Discord access (we're keeping it small for now as we build).
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
I'm active in the Filecoin slack already, and am planning to become more engaged with the ecosystem as the Banyan CEO as we've built more and are more prepared for partnerships. If I'm pinged, I'll respond.

We will only be making DataCap allocations to parties who are uploading data that our clients want uploaded, but these will be an integral part of our product and will occur with every upload. So we will be spending a lot of time on that, I guess :). If we do this, we'll also be doing some kind of instrumentation with the Verified Deals actor state so we can report things about it to Eth using chainlink, so I suppose that'd also be a pretty big contribution to the program.

I can attend governance calls as needed, probably an hour twice a month would be reasonable? I think Banyan will probably be one of the most exotic/weird protocol/usecase/thing represented in DataCap Notaries, we're entirely programmatic and our method of allocation is "vetted" entirely by decentralized economic incentives encoded in smart-contracts. So I think my and other Banyan DAO contributors' ideas will be helpful for growing and sustaining Fil+.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
N/A
```

other slack handles in filecoin slack for administration: @Maya Krasovsky, @ita, @krondor

**Comment by galen-mcandrew** [comment]
[Banyan - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320963/Banyan.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi  @laudiacay   **Congratulations! based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is North America.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program ~4 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by galen-mcandrew** [comment]
@laudiacay 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by laudiacay** [comment]
Whoops! filled it out there. confirming the address from the airtable link to here: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/307

**Comment by laudiacay** [comment]
Wow that's not the address lol, here's the correct one. `f1oc6qvenzp7wsriu7edyebb325gnaovktmujl7jq`

**Comment by Kevin-FF-USA** [comment]
Your form has been received; thank you very much! Also - I double checked your address and it is accurate.

**Comment by Kevin-FF-USA** [comment]
Hi @laudiacay,

Friendly check in.  We need you to please update the CORE INFORMATION of this application to include your updated Ledger Address. 

Also need to confirm your handle on the FILECOIN SLACK

Once you have done both, please follow the steps in the Fil-Plus-Notary SLACK channel (or this attached guide)
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing

Thanks,
-Kevin

**Comment by laudiacay** [comment]
Ok- ledger address updated above, Filecoin slack handle is @laudiacay.

**Comment by galen-mcandrew** [comment]
The 'formatting' may not get picked up by the bot, so I edited the parent comment. 

Please confirm your ledger address using the verification tool in the [Fil+ Registry app](https://plus.fil.org/).

[Here](https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing) is a troubleshooting guide.

Thanks!

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1oc6qvenzp7wsriu7edyebb325gnaovktmujl7jq
#### Datacap Allocated
> 100TiB

**Comment by laudiacay** [comment]
Are we good to go? We attempted to verify on the site, but had issues and reported them in Slack. Please let me know when this bug is resolved!

**Comment by laudiacay** [comment]
Hi Kevin, thanks! This is super exciting…

1. We will be focusing on NA, but will probably eventually service clients elsewhere due to the nature of our company as described in the application.
2. Upfront disclosures: I am only affiliated with my grants address from my employment at PL.
Client education: we will be building tools that promote client best practices and help with vetting as part of their operation as we continue to scale!
Efficiently serving the network: we will redirect within 3 days until our services are operational, and then we hope to be able to respond immediately!
No self dealing: confirmed.
Operating in good faith: confirmed
Community governance: confirmed
3. Affiliated addresses: would rather not dox this publicly on GitHub, but my PL grants address (the one on my grants multisigs) is my only affiliated filecoin address. Please contact me privately for this if needed.
4. Abiding by client due diligence: confirmed!
5. Address: can a multisig work for this? Let me know!
