### ISSUE TITLE
Notary Application - Holon Innovations 

### ISSUE THREAD

**Issue by MegTei** [filecoin-project/notary-governance#460]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Holon Innovations 
- Affiliated Organization: Holon Global Investments PTY Ltd 
- Website / Social Media: https://holon.investments/ 
- On-chain Address to be Notarized: f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i  
- Region of Operation: Oceania & Global 
- Use case(s) to be supported: https://docs.google.com/document/d/10_pe0R-_LE-VX1PBCFdCCnLELY93uo67/edit?usp=sharing&ouid=104356171406112013597&rtpof=true&sd=true 
- DataCap Requested: 100 TiB 

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

1) In 2017 Heath Behncke Holon co-founder participated in the Filecoin SAFT 
2) Holon Global is among a small number of funds that have an investment philosophy open to digital assets in Oceania and is working to make access to Web3.0 opportunities open to everyone. 
3) Holon Innovations (part of the Holon Global group) has invested $40mUSD infrastructure to set up our own mining operation, and raising another $50USD in 2022 
4) In true web3 collaborative fashion, Holon (https://github.com/MegTei) has been an active notary dedicating time & skills to contribute to governance improvement and evolution. For our team & investors its key that they know we are working in and with the team to make this a success.  

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

Significant, Prefer not to state 

### In-protocol Reputation 
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow.  

Holons' founder Heath Behncke was an early advocate and investor in FIL, having analysed the problems of web2.0 and discovering the potential of decentralised storage models and the Filecoin proposition. Filecoin is now an investment focus for Holon with the following underway: 
1) Growing at 100TiB capacity per day, 85TiB verified deals to date 
2) Holon Innovations set up the Holon FIL Wholesale Fund with custody partner Gemini. The fund is dedicated to investing in growing Holon's FIL mining operation. 
3) Commenced a thought leadership campaign working with ProtoSchool (https://proto.school/) targeting the tertiary education sector in Oceania to build awareness and the Filecoin community with the student and academia community - a 'grass-roots' tactic to excite Grads and inform educators of disruptive technologies. This involves sponsoring education/ masterclasses, presentations/ webinars and sharing resources. (https://holon.investments/wp-content/uploads/2021/04/IPFS_masterclass-flyer.pdf) 
4) Commenced awareness and marketing campaigns including a hackathon (https://taikai.network/en/holon/hackathons/holon-innovate/overview) to build both knowledge of IPFS and Filecoin and the community in Oceania  

Fundamentally, the Holon team see the potential and believe in the value Filecoins decentralised storage can offer the world and are working to help make it a success. Our own mission is to look after the wealth of our clients, to ensure they benefit from disruption, not suffer. 

### In-protocol Security 
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions.  

Holon has made contributions to the development of an enterprise grade Filecoin Storage Solution, working with other SPs and PL globally on technical issues, ingress efforts and automation of operations. This includes forming partnership with PikNik, DSM & Dcent. We will face constraints in our ability to scale if the scope of the system continues to remain public data only. 

**PROPOSAL: Something that is growing in demand, and the reason it is mentioned in this application is, this  will influence our future investment in the network is - “FIL+ for private data” – we are seeking to understand if the program be expanded to include private data where the applicant/ company is KYC, and the KYC system is a global standard. 80% of the worlds data is private, could there be sub "FIL-Priv" program for private data?** 

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

Holon Global Investments was founded in 2018 at a time when it was clear digital assets will become an investment class and that everyone should have access to investing in them.  
Our mission is to be the 'next generation Fund Manager' with an evolutionary philosophy. Having worked in wealth management for decades, this experienced team came together over a desire to solve the issues investors face around declining returns and access to investing in digital assets which offer yield potential. Holon Global Investments (HGI) has 3 entities: 
1) Holon Global Investments - delivering a range of investment funds, diversified across digital assets 
2) Holon Innovations - builds tacit know-how through getting involved in Web3.0 and decentralised projects, the first is a Filecoin mining operation starting in Sydney AUS and expanding across Oceania 
3) Holon Principal Investments & VC - The first strategic investment in Avanti bank (https://holon.investments/why-we-invested-in-avanti-the-future-of-banking/) is part of creating a safe legal structure for digital assets and in the future the VC arm with fund accelerators and other Web 3.0 ventures.  
With Wealth creation now taking place through innovation and disruptive new business models and we are working to make these opportunities available to everyone. 

Ref here for all media & press https://holon.investments/insights/ 

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

Holon Global Founders: Heath Behncke [www.linkedin.com/in/heath-behncke-a164971a/](https://auc-word-edit.officeapps.live.com/we/www.linkedin.com/in/heath-behncke-a164971a/)   
Luke Behncke [www.linkedin.com/in/luke-behncke-3a945723/](https://auc-word-edit.officeapps.live.com/we/www.linkedin.com/in/luke-behncke-3a945723/)  
MD of Holon Innovations: Jonathan Hooker [www.linkedin.com/in/jonathan-hooker-syd/](https://auc-word-edit.officeapps.live.com/we/www.linkedin.com/in/jonathan-hooker-syd/)  
Head of Ops & ecosystem & current notary: Meg Dennis https://www.linkedin.com/in/megdennis/ 
Website: [www.holon.investments](https://auc-word-edit.officeapps.live.com/we/www.holon.investments) 2000 subscribers 
Linkedin: Holon Global Investments 1000 followers  
Livewire: Holon Global Investments 2000-3000 views per story  
Twitter: @GlobalHolon

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

All media and insights here https://holon.investments/insights/ 
Fund Manager profile - The Australian Financial Review http://www.afr.com/markets/equity-markets/it-s-not-just-about-value-or-growth-for-holon-s-behncke-20210408-p57hfq?btis 
Web 3.0 interview - The Eureka report https://www.eurekareport.com.au/investment-news/investing-in-the-internet-of-value/149674 
Holon investment in Avanti Bank https://www.finextra.com/pressarticle/86821/avanti-comples-37-million-series-a-funding-ahead-of-launch-of-digital-asset-bank 
Commentator on digital assets - Coinbase - Sydney Morning Herald https://www.smh.com.au/technology/watershed-moment-as-coinbase-ipo-widens-crypto-investor-pool-20210414-p57j45.html 
https://holon.investments/holon-global-partners-with-gemini-to-launch-wholesale-filecoin-fund/ 
https://holon.investments/holon-collaborates-with-protocol-labs-to-drive-adoption-of-decentralised-data-storage-in-oceania/ 
Ref here for all media & press https://holon.investments/insights/ 

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.

MD of Holon Innovations: Jonathan Hooker [www.linkedin.com/in/jonathan-hooker-syd/](https://auc-word-edit.officeapps.live.com/we/www.linkedin.com/in/jonathan-hooker-syd/)  
Head of Ops & ecosystem & current notary: Meg Dennis https://www.linkedin.com/in/megdennis/

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?

I have been the lead on the definition of Filecoins market assessment, working with Stefaan Vervaet and IDC. Over the last 12 months I have developed this profile and assumptions which will be validated by IDC in the next couple of months and shape our Commercialisation strategy https://docs.google.com/document/d/10_pe0R-_LE-VX1PBCFdCCnLELY93uo67/edit?usp=sharing&ouid=104356171406112013597&rtpof=true&sd=true 

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.

The mission of our DataCap strategy is to build network effect. Our role as a Notary and how we will generate the market are strategically aligned. Oceania is lagging the Northern Hemisphere's awareness and adoption of decentralized protocols and solutions, our use case diversity will target the most ideal clients/ data who will become advocates. The end to end customer journey from ‘acquire to ‘retire’ and all service in between will be managed in the following way  
(1) Application DD. As a Notary we triage for completeness before processing using this question set https://docs.google.com/spreadsheets/d/1ZEM2emL2sfF3IChsJKWKnKGKlvfUgqGEDOe5WNrvxlw/edit?usp=sharing 
(2) Following client response, these are evaluated: 
- Reputation of business 
- Storage request and growth rate 
- Low retrieval rates 
- Security considerations/ sensitivity of data 
- Ability to become a Filecoin ambassador/ advocate  
(3) Should the application be approved, we monitor usage or where this is an LDN, ref to the bot stats in GitHub 

There are many issues with the current LDN process which is one of the two key reasons we considered not renewing the Notary role. The LDN process is calibrated to manage bad actors. It's almost at odds with a Web3 trustless world. Its introduced a lot of friction for notaries and is a poor customer experience. 

**PROPOSAL: 
(1) Many issues could be solved up front with KYC and a client application not in GitHub but with a decent UX and CRM  
(2) LDNs need audit automation and automatic allocation rather than the friction occurring in Github over subsequent tranches   
(3) The entire process is not a positive CX experience which is not aligned with Holons values and how we work, causing friction for us. Filecoins commercialisation stage needs a focus on the customer and a service design blueprint & customer journey is very necessary**   

##How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

The address that will be allocated DataCap will have its keys be secured with custody partner Gemini 

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 

Following onboarding of the client and allocation of their first tranche, clients will be monitored and vetted regularly against their decentralised data storage strategy and execution plan to ensure the allocated DataCap is being spent exclusively as approved. Additionally during this ‘probation’ term Holon Notary Ops will ask the Client to provide some or all of the following:  
(1) A consolidated Content Identifier (“CID”) list for verified deals that includes deal CID and miner ID (showing how the allocated DataCap has been used);  
(2) A description of the data being stored and how the data has been processed;  
(3) Instructions on data retrieval.  
(4) Random-sample inspections by Holon Notary Ops on the verified deals sent out by the Client on chain will be checked against the deal CID and retrieval from miners to verify the data authenticity. Filecoin public monitoring and auditing will be in play also  
(5) “In-life” client questionnaire https://docs.google.com/spreadsheets/d/1ZEM2emL2sfF3IChsJKWKnKGKlvfUgqGEDOe5WNrvxlw/edit?usp=sharing 

##What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
As above.

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 

All allocation decisions will conform to standards using the repo https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues . We will store all the work records of clients, their artefacts and allocation decisions. 
1.The allocation guidelines and other supporting rules will be publicly available following approval.  
2. The client record/ data, application, correspondence and decision reports will be kept for at least 3 years.  
3. Audits to be conducted by professional lawyers or accountants appointed through Filecoin community governance procedure. Auditors will have access to all relevant files ensuring confidentiality and that certain data may be withheld without permission of the Client authority. 

The second reason Holon was considering not renewing the Notary role: We are unclear if the Notary role could be in conflict with commercialisation which is Holons primary focus  
**PROPOSAL: We would like to be a storage provider on some of the LDNs we approve and/or be a proxy to allocate non LDN datacap. If we are investing time/ effort in Biz dev, how might SPs be able benefit from this?  This extends to: 
(1) KYC should be also applied to Notaries which would help manage bad actors and the use of reputation systems could surface SP quality/ behaviour  
(2) Another solution to this could be, apply a new notary service level – advisory vs actor – advisory supports process and governance but not transactional (approvals) 
WE NEED CLARITY AND RESPONSE ON THIS ASAP.** 

##Where do you plan on keeping a publicly accessible record of all your allocation decisions?

All allocation decisions will conform to standards using the repo https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues, made public for transparency in this phase. In future some clients and their storage needs may be complex or sensitive and records may be then maintained on Holon Database 

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.

Holon has been contributing around 1 day per week to Governance, the IDC work and other side streams. I get many direct DMs daily on LDN applications (which shouldn’t be occurring) which is time consuming taking a few hours each week. What this time commitment going forward depends on answers to these questions (and this application can be updated if this becomes clearer).

**PROPOSAL:**  
**(1) We would like to be a storage provider on some of the LDNs we approve and/or be a proxy to allocate non LDN DataCap. We are investing significant time/ effort in Biz dev, how might SPs be able benefit from this?**   
**(2) A potential solution is to apply a new notary service level – advisory vs actor – advisory supports process and governance but not transactional (approvals)**

**Holons focus is to continue to invest in Filecoin and commercialise it in 2022. This focus and the Notary role don’t need to be mutually exclusive, but we need the following to continue as a notary:** 
**- The DataCap process needs to be improved (KYC, auditing and automatic allocation rather than the friction occurring in Github over subsequent tranches)**
**- SPs who are notaries need clear boundaries**
**- Private enterprise data needs to be supported - an expectation when this can be offered**   

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
YES 100 TiB 

Cumulatively, how much DataCap have you previously successfully allocated? 
70 TiB

**Comment by galen-mcandrew** [comment]
[Holon Innovations - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320968/Holon.Innovations.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi  @MegTei     **Congratulations! Based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!**   You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.  Looking forward to great things in 2022!  Thank you

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is the Oceania area.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program ~1 to 2 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. (**we appreciate your past participation these calls and input to strengthen the community - thank you!)**  As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

**Comment by MegTei** [comment]
Thanks @Kevin-FF-USA responses below:

1. Please confirm that the region of operation for client applications you will focus on is the Oceania area.  
- Region of operation is Oceania
2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  
• Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
- Agreed. Holon Innovations is also an SP, you can see via FilFox (or we can provide all of our mining activity, to date has been Slingshot)
• Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
- Agreed
• Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
- Agreed
• No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
- Agreed
• Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
- Agreed
• Community Governance Participation: It is expected that you will participate in the program ~1 to 2 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. (we appreciate your past participation these calls and input to strengthen the community - thank you!) As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
- Agreed
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  
- TBC
4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  
- Agreed
5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
- TBC

**Comment by MegTei** [comment]
Hi @Kevin-FF-USA Two Q's above need more info:
1. Do you want/ need all of Holons miner IDs?
2. We will come back to you with a new wallet as we still have datacap from previous allocation

**Comment by galen-mcandrew** [comment]
@MegTei 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by fabriziogianni7** [comment]
I updated the parent comment with the new address. this is probably the reason for this notary ledger not to have been verified.
cc @dkkapur @galen-mcandrew

**Comment by MegTei** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebjuqvtz2k3ag25sgwzkgo4hm3goo564egrzu3mawpfangil6f23m
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjuqvtz2k3ag25sgwzkgo4hm3goo564egrzu3mawpfangil6f23m

**Comment by galen-mcandrew** [comment]
@MegTei Getting requests in Slack to change your notary address, and want to have this conversation publicly here for the record. We need to confirm your ledger address, and which single ledger address you would like to use for the LDN's and the direct notary requests.

In this application, you listed f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i and the RKH sent the third round of DataCap, add put this address on the LDN v3 multisig. This address was used recently to sign direct allocations and LDNs, so can you explain why we need to change to a new address?

https://filfox.info/en/message/bafy2bzacebt6bsb5s2yziv4ribtsom37qhdtserfuacokzu3f2jqkt37ehk5a -> https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1937

https://filfox.info/en/message/bafy2bzacedtexjmvcmb4dawnrbimjwysz4kx2ho2zn5bvsjgb4japlmeh3ite -> https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/327

**Comment by MegTei** [comment]
HI @galen-mcandrew as we still had 30TiB datacap on wallet ending in ...we5i we were asked to set up another wallet.
f1r4rwdbl2zo5kbtsd56kqg2ksa6yneq66uxvngpq
I cannot approve public requests using either. have no preference to have two wallets would rather just one.

**Comment by MegTei** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacea7oydctcvfvp5togxl4ipzsma73j57fwh77yepxytehfjbnuxzwg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7oydctcvfvp5togxl4ipzsma73j57fwh77yepxytehfjbnuxzwg

**Comment by mjroddy** [comment]
Hello all!

I am mark and will be assuming notary responsibilities on behalf of Holon.

LinkedIn Profile for reference

https://www.linkedin.com/in/mark-roddy-40b2ba36

**Comment by Kevin-FF-USA** [comment]
Thanks @mjroddy,
Appreciate you confirming that you will be taking ownership on the wallet address and will now be representing HOLON as an organization.
