### ISSUE TITLE
Notary Applicaiton - Gate.io 

### ISSUE THREAD

**Issue by gateio** [filecoin-project/notary-governance#461]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:Fafa
- Affiliated organization: Gate.io
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address): f1blw3s545cgl7bwkrvojtbkdyd6oyvg3vxfldqqa
- Region of Operation: North America
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 10 PiB): 1 PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Gate.io is one of the top 10 Exchanges with more than 10mm registered users from over 130 countries, which is committed to offer solutions on cryptocurrencies.
We learned decentralized storage and IPFS from 2017 and we are deeply moved by the economic system that everyone can be a storage provider of Filecoin afterwards. Then we started to offer FIL token related business from Fil6 to Fil distribution to serve for Fil community.
Gate.io business on Fil:
- 2017 Renrenico user migration, Fil (IOU) 
FIL (IOU) is the token with the shortest maturity period after the launch of mainnet. The circulation of FIL (IOU) is 2.4 million and Gate.io is the largest FIL (IOU) circulation and trading market in the world.
- 2020 Oct, Gate. IO completed the conversion of FIL IOU to FIL6
FIL6 is partially unlocked and converted into the mainnet FIL token every day after the mainnet launched. The mainnet FIL token transaction service was online as soon as the mainnet launched. Currently Gate.io is the largest FIL (IOU) stock and trading market in the world.
Related article：https://www.gate.io/tw/article/17994
- 2021 Aug, released all Fil6 and removed Fil6
According to the conversion rules for FIL6, Gate. io removed the FIL6 exchange on August 31st and converted the user's FIL6 balance 1:1 to FIL balance. Users can trade in the FIL market.
Related article：https://www.gate.io/tw/article/22158
- 2021 Oct, completed Fil mainnet upgrate
Filecoin (FIL) planned to launch a major network upgrade on Epoch1231620, October 26 at 21:30 UTC+8.
Related article：https://www.gate.io/tw/article/23289
Our Github handle: https://github.com/gateio

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
No statistics yet
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Gate. io, the world's TOP 10 trading exchange, which supports live streaming, research reports, blogs and other products on supporting Fil financial management, lock-in gains,etc.. In the past 6 years of supporting filecoin, we had held dozens of events including the relevant financial management, lock-in, trading contests and other activities.
Related link:
https://www.gate.io/tw/article/20673  （FIL management wave 11）
https://www.gate.io/article/18194    （increase market demands of FIL management）
Other announcements:
https://www.gate.info/cn/article/19302
https://www.gate.info/cn/article/20673
https://www.gate.info/cn/article/19250
https://www.gate.info/cn/article/19248
https://www.gate.info/cn/article/19190
https://www.gate.info/cn/article/19185
https://www.gate.info/cn/article/18255
https://www.gate.info/cn/article/25096

https://www.gate.io/articlelist/ann/0（You can type “Fil” to search）

Since 2017 when we started to pay attention to Fil, Gate. io product live broadcast and research report conducted interviews with relevant important people, the whole live broadcast online, and users can interact with the community at any time.

The following is a transcript of the live broadcast and links of relevant interviews with kols:

https://www.gate.info/cn/video/4b95793dad5f4cb3a023eebe9c4e6b2a
https://www.gate.info/cn/video/bf6c8c73011343c6b5fc6dad4f614acd
https://www.gate.info/cn/video/4ebc5f1c0b0e4135a186964c7ee1c1f3
https://www.gate.info/cn/live/5c64ddb151314f8691783b8b335288ed

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
 None.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Founded in 2013, Gate.io is an exchange mainly committed to offer token store and exchange service for global users. At present, we have more than 10 million users, support more than 1,800 currency types, and can flow more than 1 billion funds in 24 hours.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Social media link:
https://twitter.com/gate_io
https://t.me/gateio
Website:
https://gate.io/
E-mail address:
support@mail.gate.io

CoinGecko introduction of gate.io
https://www.coingecko.com/zh/exchanges/gate-io
CoinMarketCap introduction of gate.io:
https://coinmarketcap.com/zh/exchanges/gate-io/

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://news.huoxing24.com/noticeDetail/0f0d9739b0973caec22e3a7cdc577c37
https://www.qklw.com/blockchain/20200716/102325.html

https://www.fromgeek.com/blockchain/144407.html

https://www.jinse.com/news/blockchain/1064077.html
https://weibo.com/ttarticle/p/show?id=2309404570188631900556
https://weibo.com/ttarticle/p/show?id=2309404534859027841295
http://finance.sina.com.cn/blockchain/roll/2020-04-21/doc-iirczymi7547231.shtml?wm=3049_0032
https://weibo.com/ttarticle/p/show?id=2309404499469038125189
https://weibo.com/ttarticle/p/show?id=2309404494398556602563
http://www.jpm.cn/article-85808-1.html

https://baijiahao.baidu.com/s?id=1660314716001287049&wfr=spider&for=pc
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
1.https://twitter.com/gate_labs?s=21  Followers：1413
2.https://www.youtube.com/channel/UCKtbVFVa1llpfCo-7r2ZwAA  Followers：10
3.https://twitter.com/gateio_es?s=21   Followers：36997
4.https://twitter.com/gateiovietnam?s=21  Followers： 2502
5.https://twitter.com/gateiorussia?s=21  Followers： 30016
6.https://twitter.com/gateiofutures?s=21  Followers： 41865
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We are deeply moved by the security of Filecoin storage. So we would like to support data which needs high security such as data on the police,medical treatment, educational institutions, government agencies,financing institutions, etc..

```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
https://docs.google.com/spreadsheets/d/1Enys9n2vedbPn456e-vuzpQygDF5CZG22F8YYY6l8iI/edit?usp=sharing
Following is our process:
Get more detailed information from clients according to our requirements
Verify the validity and authenticity of the information submitted, and reject applications which contacted invalid or false information.
Communicate with the applicant to provide additional information based on the suspicious points 
Score the application and find out the qualified clients.
Determine the DataCap amount according to the score
Regular audit of clients’ allocations
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We have our own official authentication system: https://www.gate.io/tw/officialverify
We can guarantee that our members are official staff of the Exchange and that the verification system will be updated in the event of personnel changes. We recommend that the list of organizations that allocate DataCap be published for review during implementation.
Also, we would like to use ledger to protect our datacap.

```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
First of all, we will review the applicants, who need to upload relevant information, including the years of registration, industry influence and so on. After the approval, we will conduct regular verification. Customers who meet the requirements can continue to use or apply for a higher volume. Those who do not meet the requirements and do not provide reasons will be rejected. We will try to find out high-quality clients with long-term storage needs.

We have the corresponding audit, such as the allocation of policy table information, and communicate with customers of different levels on different issues, including (no limit) as follows:
① Team/personal introduction
② How much DataCap do you want, and why?
③ How will you allocate your DataCap?
④Have you ever allocated before? If yes, could you give us more details?
⑤ What will you do to avoid the datacap waste?


```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Periodically review and audit DataCap usage (as metioned above, records are tracked and reviewed periodically to determine disqualification or demotion of nonconforming customers)
Users can upgrade according to the actual situation to meet the requirements
Communicate with customers regularly to understand relevant requirements and progress, and provide better service to customers
Of course, try to avoid this situation in the initial review of the application and improve the initial application information supplement during the continuous record review process.


```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, as mentioned above, all records will be public. Also, if we have detailed communication needs E-mail, we will save the screenshots.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
 We would reserve our allocation record and make it public through our github：https://github.com/gateio

```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
About 12-24 hours per week.  
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.

```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None.

```

**Comment by galen-mcandrew** [comment]
[Gate.io - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320949/Gate.io.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by gateio** [comment]
More on Client Due Diligence:
1. When verifying client information, we will request verification from the applicant organization. For example, enterprises need to submit information including country, company type, company name, business license, business registration certificate number, information query website, etc. Enterprises are also required to provide information of the legal person (name/ID information, etc.), upload minutes of the board meetings and share the shareholding structure.
2. We will inspect the use of DataCap to promptly avoid waste. Less DataCap will be granted to clients that handle their assigned DataCap improperly. Clients that demand more DataCap will be granted more after a serious investigation of how they use their DataCap.

The allocation of DataCap will be carried out in 3 rounds. The allocation decisions of one round are made according to the DataCap usage of the client in the previous round.


More on Bookkeeping Plan:
1. While keeping the records, clients' demands will also be considered and discussed in a conference on GitHub for a solution. If you disagree with the result, you can file an appeal, and a voting event will be held to determine the final decision. All clients whose applications are approved are eligible to vote. If the number of votes accounts for over 80% of the total number of approved applications, the appeal will be deemed valid. If over 50% of clients vote in favor, the appeal will be approved.

@galen-mcandrew

**Comment by Kevin-FF-USA** [comment]
Hi  @gateio  **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is North America.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 12-24 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by gateio** [comment]
1.Please confirm that the region of operation for client applications you will focus on is North America.
Confirmed

2.Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).



• Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship
Confirmed

• Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.
Confirmed

• Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.
Confirmed

• No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.
Confirmed

• Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.
Confirmed

• Community Governance Participation: It is expected that you will participate in the program 12-24 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.
Confirmed

3.Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.
None

4.Please affirm that you will abide by the allocation / client due diligence plan you laid out above.
Confirmed

5.(If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

• If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)
f14o2wn7otoo5pj4bxkdpqsxekavpim3fsdsvy7zi

**Comment by galen-mcandrew** [comment]
@gateio 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @gateio!

Just a friendly ping - there is some additional information needed in order to finalize, **can you please follow this link to complete by April 15th?**
[Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)

**Comment by gateio** [comment]
Greetings, due to we used our customer support email address when we submitted airtable.com the first time.
after the internal discussion we made a email to deal relative business: filecoin_notary@gate.io 

Please refer to our final submission as the correct version.
Thank you very much

**Comment by Kevin-FF-USA** [comment]
We have received your submission, it is very much appreciated. I have double checked and we are using the submission with the correct email: filecoin_notary@gate.io.

**Comment by Kevin-FF-USA** [comment]
Hello @gateio!

Still unable to find you in slack - can you please confirm your Slack handle?

**Comment by gateio** [comment]
Maybe you can give me an invitation link
Or you can invite me after you join my newly created workspace：https://join.slack.com/t/filecoin-zoe1213/shared_invite/zt-17kj5wp4h-Ax1KFfHElGU8mQecIeRZ5g @Kevin-FF-USA

**Comment by gateio** [comment]
I have joined the filecoin slack, and my handle is filecoin_ notary@gate.io
Display name
Gate.io
And has sent a DM to Kevin FF，please check

**Comment by Kevin-FF-USA** [comment]
Pasting for record to connect SLACK to this application. Thank you
![image](https://user-images.githubusercontent.com/94004586/166452038-4d132aa8-7a59-48dd-83fe-cbf9bc377c58.png)

**Comment by Kevin-FF-USA** [comment]
Hello @gateio!

I have updated your information and added you to the notary communications on Slack. Thank you!

**Comment by galen-mcandrew** [comment]
@gateio Can you please clarify your ledger secured address that you will use to make DataCap allocations as a notary? We see "f14o2wn7otoo5pj4bxkdpqsxekavpim3fsdsvy7zi" here, but a different address in the forms submitted. 

Please try signing into the plus.fil.org registry app with your ledger, and confirm that the address matches the one in the parent comment here. Then use the "verify ledger" flow, which will send a message from your ledger address and paste a comment here.

**Comment by gateio** [comment]
I have been having difficulty verifying the wallet address in the registry due to ledger setting issues. I ordered a new ledger device, but it seems like it’s going to be a long wait until it arrives because of the covid control policies here.We will finish processing as soon as the ledger device arrives

**Comment by Kevin-FF-USA** [comment]
Hello @gateio 
Thanks for your patience while I looked into this.  So sorry to hear about the ledger getting stuck in shipping, thats the worst.
So unfortunately with the new LDN v3 system you won’t be able to receive any datacap without a physical ledger verified. You can however remain as a Notary, reviewing applications and participating in the Governance Calls.
Once you receive your ledger, we can then send the Datacap your way.

**Comment by gateio** [comment]
Due to ledger problem, the address needs to be corrected, which has been corrected in CORE INFORMATION. The new address is: f1blw3s545cgl7bwkrvojtbkdyd6oyvg3vxfldqqa   This address has been verified.

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1blw3s545cgl7bwkrvojtbkdyd6oyvg3vxfldqqa
#### Datacap Allocated
> 1PiB

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1blw3s545cgl7bwkrvojtbkdyd6oyvg3vxfldqqa
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzaceam3wytlupnmmhkoziti7dsemksbvuuv5kqf2bohaf4jwd3rc4ur6
