### ISSUE TITLE
Notary Application -  SlLtd

### ISSUE THREAD

**Issue by iMiamas** [filecoin-project/notary-governance#462]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: johano
- Affiliated organization: SlLtd
- On-chain address to be notarized (recommend using a new address):f3vbwgywf2xgfugny7qy4pn2nhxdbmf2e2zfozhe5xuufvgdtjstuhynnnkaq65gmxv6fdxdlofdtip3pd4llq
- Region of Operation: [Africa, Greater China]
- Use case(s) to be supported: Media,Professional Services, User Content
- DataCap requested for allocation (10TiB - 10 PiB): 1PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
github handle：iMiamas
minerID:  f01032903 f0451936 f0398286
1. In the middle of 2018, our previous business was sluggish, and we began to look for a new direction. This year, we learned about IPFS and Filecoin projects in Shenzhen on China's National Day, and established Filecoin as the main business at the end of the year. direction company.
2. I actively participated in all the tests of Filecoin, and from the beginning of obscurity to the famous, from go-filecoin to lotus, from sector-builder to filecoin-ffi, from 256M sectors to the current 32G and 64G sectors, It has also witnessed the continuous changes of Protocol Labs in the project, and found problems and progress. From the very beginning, it was difficult to store a few TiB on the chain. Now it can easily accommodate more than 15EiB.
3. When the former company had a disagreement with me, I chose to set up a new company in 2021 and continued to pay attention to the Filecoin business, hoping to work with all partners in the community to promote the development of Filecoin’s real data storage and ecology. 
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Total stake: about 400000 FIL with Miner ID f01032903 f0451936 f0398286 as collateral(viewed on February 28th, 2022).
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
When go-filecoin first transferred to the Lotus network, our computing power accounted for more than 90% of the total network computing power, which made Protocol Labs aware of the possible threat of super miners to the decentralized network.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
A piece of black history. I was the earliest attacker of the Filecoin chain (of course, the purpose was for the better development of the network). At that time, the chain had just started to test. I modified the block time to milliseconds, and then I quickly let the chain's The height has grown rapidly and basically all block rewards have been obtained.

```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
SlLtd is a company established in Hangzhou, China in 2021. At present, the company has more than 50 employees. The company focuses on storage technology and blockchain technology, pays attention to the development of Web3, and hopes to stand in the center of the hurricane in the new technological revolution. Witness the blockchain technology changing the world together, and look forward to the final push into the human community 
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
N/A
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
N/A
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
N/A
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Media & Entertainment(video & music)
User Content(personal user storage)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The purpose of DataCap is to promote the implementation of Filecoin's real storage, so we mainly ensure the real availability of customer storage.
1. We will verify all data to ensure the legality, authenticity and availability of the data source
2. We have already cooperated with some organizations on storage, and these organizations have a lot of data to store
3. For individual users, we will establish an internal evaluation mechanism for evaluation according to the usage. For some untrusted customers, they will not be allowed to store DataCap data.
4. We will allocate 70% of the storage space to organizational customers and 30% to individuals. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will perform authorization authentication for each DataCap data operation
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1. First of all, I will ask the customer's situation to determine whether there is said data that can be stored
2. I will judge whether the magnitude of the data is consistent with what the customer said according to the customer's situation
3. I will often maintain good communication with customers to increase muscle mutual understanding and trust 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. Regularly check and audit DataCap usage
2. Use punishment and incentive mechanism, give more shares to those who use it well, and reduce the share otherwise 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
There is no such plan for the time being, but I think it can be arranged according to the subsequent development of the request
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
The current preparation is on our own website, but for better use later, there may be an App ，and put it on our github website
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
about 8-10 hours per week
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
N/A
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
N/A
```

**Comment by galen-mcandrew** [comment]
[SILtd - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320940/SILtd.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
We are very sorry to let you know that this application was not selected in this round of Notary Elections.  

Each application was scored according to the Rubric and [assigned a Scorecard](https://github.com/filecoin-project/notary-governance/issues/394). That score was then applied for each of the [geographic regions and the top scored applications were selected](https://github.com/filecoin-project/notary-governance/issues/479). 

We are humbled by your commitment, and grateful for your interest in the Filecoin Plus program. Looking forward to seeing you in the program and hope you resubmit in the future elections.

Should you have any questions please feel free to raise here, or DM me in Slack @Kevin_FF
