### ISSUE TITLE
Notary Application: Define Platform

### ISSUE THREAD

**Issue by Alex11801** [filecoin-project/notary-governance#463]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Alex Kim
- Affiliated organization: Define Platform
- Website / Social Media: 
- On-chain address to be notarized (recommend using a new address): f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
- Region of Operation: Asia minus GCN (Republic of Korea)
- Use case(s) to be supported: Web 3.0 / Decentralized Applications, Web 2.0 Applications, User Content (Personal Storage, User Generated Media), Media & Entertainment, and others
- DataCap Requested: 1 PiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Define has participated in the Filecoin Plus Program as a client since November 2021. We have applied 5PiB DataCap (https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/91), made storage deals and allocated 150 TiB DataCap to the storage miners.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
N.A.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Define has participated in the Filecoin Plus Program as a client since November 2021. We have applied 5PiB DataCap (https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/91), made storage deals and allocated 150 TiB DataCap to the storage miners.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N.A.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
DeFine is the social NFT platform for all creators including artists, musicians, influencers, gamers, and athletes. The platform facilitates all social interaction, engagement and communication for creators and their fanbase with digital assets like NFTs and social/fan tokens, and real assets on the blockchain. Owners of social/fan tokens will have many benefits including special access to the creators’ NFTs, merchandise, content, etc. while being part of a private community. It is also the social platform for all participants in the digital world where they can identify and interact with each other through their NFT social profiles which are based on their contribution and achievements in the digital world. Ultimately, the DeFine will serve as a social platform for creators and users to define how to engage with each other and build communities in the digital world.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
- Website: http://www.define.one
- Twitter: https://twitter.com/DeFinePlatform
- Telegram: https://t.me/DeFinePlatform
- Discord: https://discord.com/invite/UYahw74GdG
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
- DeFine Partners With Cere Network To Build a Decentralized and Secure NFT Ecosystem 
https://www.newsbtc.com/press-releases/define-partners-with-cere-network-to-build-a-decentralized-and-secure-nft-ecosystem/

- DeFine and Tron Form Strategic Partnership to Build NFT Ecosystem and Bring Social Profile System on Tron Network 
https://www.prnewswire.com/news-releases/define-and-tron-form-strategic-partnership-to-build-nft-ecosystem-and-bring-social-profile-system-on-tron-network-301350452.html

- DeFine Will Be Listed on the Huobi Pioneer Zone Following by Primepool Mining Activity 
https://www.dailyadvent.com/news/bb9d3bc4d3250bc945253b9de01d3c75-DeFine-Will-Be-Listed-on-the-Huobi-Pioneer-Zone-Following-by-Primepool-Mining-Activity
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
- Twitter: https://twitter.com/DeFinePlatform, 23.2k Followers
- Telegram: https://t.me/DeFinePlatform, https://t.me/DeFinePlatform_kr, 6460 members
- Discord: https://discord.com/invite/UYahw74GdG, 5612 members
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We plan to support more NFT collections, NFT/Media storage tool projects, etc. 
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We refer to the allocation strategy of Filswan and UnionLabs because they are excellent notaries in Filecoin Plus Program as they are known. So we prefer to follow and learn from the great predecessors for better working in the program.

The most important thing about DataCap allocation is to ensure that the client utilizes DataCap to store real data. so I firstly specify some rules to figure out the true identity of the applicant.
* Browse their official website to get a general understanding of the company or the individual. 
* Query the company's registration information from government related websites to make sure the information he submitted is true.
* Ask some questions to know about the applicant's position/organization/plan/use case etc. 
* Then We will classify applicants based on their industry reputation and scale etc. All applicants will be divided into eight categories to determine the amount of datacap they will get. The following Rubric will be the primary guideline I use when evaluating a client and determining their DataCap allocation.   
You can see it: https://docs.google.com/spreadsheets/d/1ED8dgWkAkPh3z9x2KxPeYbt3HlwTa04HpRATErLFTIA/edit?usp=sharing
These scoring guidelines can serve as a tool of assessment and further to add a level of consistency across the board.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will use an offline hardware wallet exclusively to verify for the accounts associated with the Datacap allocation. And multi-sig wallet is to be used when more clients are coming in.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We refer to the Client Due Diligence strategy of Filswan and UnionLabs  because they are excellent notaries in Filecoin Plus Program as they are known. So we prefer to follow and learn from the great predecessors for better working in the program.
There will be three stages in the verification process to ensure the DataCap is used properly. Moreover, the greater the amount of DataCap requested, the more restricted the client scrutiny will be. The details are as follows:
![image](https://user-images.githubusercontent.com/68763845/155881506-8a28f618-6510-4435-8729-7c26c6005f9b.png)

[1] Details include but not limited to these:
     1. Entity Information
     - Formation documents - this includes certificates of registration/incorporation/information.
     - government-issued identification number for the entity
     2. Authorized Signatory Information
     - evidence of the authorized signatory’s authority to act on behalf of the application entity
     3. Beneficial Owners(optional)
     - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or something similar to verify the ownership, and also the following information for each of them:
     - legal name;
     - date of birth;
     - street address (P.O. box number is not acceptable);

[2] Punishment actions may include disqualify the applicant certification, public its wrong actions in the community, stop further allocation forever, fine the Filecoin pledged by the client etc. In the extreme scenario, legal option will also be taken based on the aforementioned DataCap allocation agreement.

Question for clients:
1. Introduction of yourself/ your organization(with links)
2. Use case
3. Location
4. Max DataCap Allocation
5. Filecoin address
6. Miners you intend to allocate DataCap with allocation proportion
7. Specific requirement of miners and storage service
8. For-profit or not
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Firstly, from the questions about the use plan and further investigation, I can know some details about his allocation plans. When scoring applicants according to the above sheet, the more geographical distribution, use cases and miners assign, the higher score he will get and the more datacap clients are likely to get.  
Next, we will keep tracking clients’ information such as the DataCap distribution records, related miner addresses and storage providers, to ensure that they are consistent with their words and deeds.
Finally, a reward and punishment mechanism will be established. If someone over-allocating datacap to a single entity, I will refuse further allocation and issue a warning which will be public to the Filecoin community. On the contrary, reputable clients have the opportunity to obtain more datacap.
We will also employ the scan tools developed by Filswan for monitoring verified deals with miners, content scanning tools for violation of local law and policies, usage of the data, verified data distribution. https://github.com/nebulaai/trusted-miner. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
The record of my allocation decisions will be accessible and in public on GitHub to be supervised by the Filecoin governance team, notaries and the community.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Yes, We plan on keeping records of our allocation decisions via a Github repo https://github.com/filecoin-project/filecoin-plus-client-onboarding and the website: https://filplus.info/#/
We will also try to build an open source project for auditing purposes.
- The allocation plan and criteria is public accessible  
- Each approval and allocation is on Github
- All the conversation of a datacap interview with the client is recorded under the awareness of the client and saved in a secure place.
- Client submission related documents are securely saved for future auditing.
- Client data quotation usage is online traceable. All the datacap allocated will be saved in the database for future analysis and auditing. 
We are open to any audit requests.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
15 hours per week on average
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
We have applied 5 PiB DataCap and allocated 150 TiB DataCap to SP miners for now. Link to the application, https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/91
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
150 TiB
```

**Comment by galen-mcandrew** [comment]
[Define Platform - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320863/Define.Platform.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi  @Alex11801 **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Asia minus GCN.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 15 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by Alex11801** [comment]
Thanks so much, @Kevin-FF-USA ! Here is my reply:
1.Please confirm that the region of operation for client applications you will focus on is Asia minus GCN. 
**Confirmed**

2.Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles). 

- Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

**Confirmed**

- Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

**Confirmed**

- Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

**Confirmed**

- No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

**Confirmed**

- Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

**Confirmed**

- Community Governance Participation: It is expected that you will participate in the program 10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.

**Confirmed**

3.Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt. 
**None**

4.Please affirm that you will abide by the allocation / client due diligence plan you laid out above. 
**Affirmed**

5.(If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.

The address is f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi . It is a brand new one, with no DataCap granted.

If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by galen-mcandrew** [comment]
@Alex11801 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @Alex11801!

Really appreciate you filling out the acknowledgments for the Notary kickoff in this ticket. There is some additional information needed in order to finalize, **can you please follow this link to complete?**
[Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)

**Comment by Alex11801** [comment]
> 
I just completed the form. Please check and let me know the following progress. Also, will Filecoin Foundation announce this on twitter?

**Comment by Kevin-FF-USA** [comment]
We have received it, thank you!

There will be a public social media announcement coming soon.

**Comment by Kevin-FF-USA** [comment]
Hello @Alex11801! 

This s a friendly ping - we cannot confirm your Slack handle as there are multiple users with the Slack handle you provided. In order to confirm, we need you to send a message on Slack to Kevin_FF by April 25th - otherwise we cannot add you to our Notary communications.

**Comment by Alex11801** [comment]
My Slack handle is Alex Kim.I sent the message to Kevin_FF yesterday,
please take a look and add me to the notary channel.

**Comment by Kevin-FF-USA** [comment]
Hi there @Alex11801 ,
Thanks for the patience to verify. Added your Alex Kim SLACK address to the official Notary channel. 
![image](https://user-images.githubusercontent.com/94004586/166303456-9046c7a0-6d4a-40f1-8dca-53f17802186a.png)

**Comment by Alex11801** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceayb73qvbm6r5bohffr4scppqrnudk34h2paic6qwjpditaeyyo5c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayb73qvbm6r5bohffr4scppqrnudk34h2paic6qwjpditaeyyo5c

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
#### Datacap Allocated
> 1PiB

**Comment by Alex11801** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecwpzudsnep7dlbcp2himrjyj7uih4xxudsmsydarjuxp26gd2l2q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwpzudsnep7dlbcp2himrjyj7uih4xxudsmsydarjuxp26gd2l2q

**Comment by Alex11801** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebunvtwmoealylu6s4osoruf33wcqpllqg2tdn275udq5meczosyy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebunvtwmoealylu6s4osoruf33wcqpllqg2tdn275udq5meczosyy

**Comment by dkkapur** [comment]
Notary address verified. Closing this issue for now.
