### ISSUE TITLE
[Notary Application] YuanHe Tech（Firefly）

### ISSUE THREAD

**Issue by fireflyHZ** [filecoin-project/notary-governance#465]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:   embedsky
- Affiliated organization:  YuanHe Tech ( Firefly ) 
- Website / Social Media: 
- On-chain address to be notarized (recommend using a new address): f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
- Region of Operation: Asia minus GCN 
- Use case(s) to be supported: Web 3.0 / Decentralized Applications
- DataCap Requested: 500TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
At the end of 2016, I saw great value and potential of IPFS protocol from hundreds of blockchain projects and believed it to be the only project that could be implemented in business scenarios since the appearance of blockchain technology. After careful study of the Filecoin white paper, Thereafter, I have kept a very close attention to this project during 2018 and finally decided to work with some partners to create a company specialized in Filecoin project named Firefly. As an organization, Firefly was founded in 2018 with an aim to build a more secured, efficient and liberated Web of 3.0 and the company has quickly become a major player in the Filecoin field. In addtion, our official website is http://fireflyblock.com
As an individual, I have worked as a crypto miner for over 6 years. I’ve been a part of the Filecoin community since 2017 and founded Firefly  in 2018. As an organization, Firefly is a leading service provider committed to comprehensive Filecoin mining solutions in a cost-effective way. 
We have built quite an extensive relationship with the Filecoin community since its initial launch back in 2017, and as a result, have sustained countless contributions to the overall network. 
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
We have 50000 Fil currently at stake, 300,000 locked as collateral
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As a member of Filecoin community, I have dedicated all my working time in promoting the ecological development of Filecoin industry with the company since 2018.Starting from August 2019，Firefly has been pushing a large number of articles about the latest developments in Filecoin on major social platforms weekly including WeChat official account, Twitter, Zhihu,Tiktok ， and has led thousands of people to get into Filecoin storage
Provide block de-rights source code- 
Commit code（urugang）
-https://github.com/filecoin-project/lotus/commit/69bfe7b7a8eeff6888e51cac3f1bfaa2d76c0c43
Consultation and questioning（embedsky、urugang）
- https://github.com/filecoin-project/lotus/issues/931
- https://github.com/filecoin-project/lotus/issues/495
- https://github.com/filecoin-project/lotus/issues/50447
(jackmimil、urugang)
- https://github.com/filecoin-project/lotus/issues/2929
- https://github.com/filecoin-project/lotus/issues/3973
- https://github.com/filecoin-project/lotus/issues/5042
```
Open-sourced two filecoin-related projects
- https://github.com/yuanheTeck-fireflyblock/ff-wallet
- https://github.com/yuanheTeck-fireflyblock/block-back-trace
### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Firefly is a reputable decentralized storage solution provider based in Hangzhou, China. The company was founded in July 2018, then rapidly developed into a leader in the field of IPFS network. Currently, we have about 100 employees, many of whom come from Microsoft, Alibaba, Huawei, Giant Network, AMD, and other well-known enterprises. Our team has been deeply engaged in the field of cloud storage and Internet for more than ten years and has built strategic partnership with major cloud service providers such as Alibaba Cloud and telecom operators globally. 
We will work harder to promote the development of Filecoin ecosystem and lead the upstream and downstream evolution of the distributed storage industry. In addition, Firefly has established a complete sales channel globally, providing thousands of users with the most cost-efficient products and software services. In China, there are more than 100 agents and distributors. Apart from the headquarter in Hangzhou, we have another Operation Centers in different locations, covering all Tier-1 cities and mostTier-2/3 cities in China. Although we are based in China, but we always harbor an international vision. 
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
[Please answer here.](https://www.bilibili.com/video/BV1Ky4y187RT?from=search&seid=13745773048619813785
https://twitter.com/fireflyblock1
http://www.fireflyblock.com/
www.fireflypool.com
https://weibo.com/7329627144/profile?
https://baike.baidu.com
https://www.chainnews.com/u/095136341312.htm
Tiktok：Firefly萤火虫
Bilibil：Firefly萤火虫区块链)
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
[Please answer here.](https://news.163.com/20/0403/17/F9A9TMPC00019OH3.html
Cooperate with Chinese colleges and universities to develop FPGA chips and build a perfect Ipfs ecosystem)
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Slack："search" changed to "FireflyHZ"
Github：embedSky、liuwencheng9527@gmail.com
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
I plan to support multiple use cases; the percentage will be determined by my knowledge and usage expectation, 
which may vary depending on the variable circumstances of each scenario and different regions. 
-    60% - user content (personal user storage) 
-   25 % - scientific datasets (AI training, geological data, autonomous driving) 
-    15% - media & entertainment (video & music)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The general strategy is to provide access to DataCap by types of Client and by stages, which means (i) different types of Client will be subject to respective on-boarding requirements and procedures to have access to DataCap; and (ii) the granted DataCap will be gradually available to the Client over time with a view to our continuing control of the Client’s proper spending. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 
For individual clients, online identity will be verified by both account age and account activity perspectives, and this will serve to prove that they are valid users and not bots 
Third-party tools like twitteraudit may also be used to verify online identities. 
For organizational clients, application organizations should be easy to verify through the appearance of their application. 
The developing applications may require further stringent investigation; 
this is to ensure that the application is valid and enclosed with meaningful content, rather than the shell of a malicious client. 
Large public datasets hosted by organizational clients are easy to verify because the data should be unencrypted and accessible to anyone. 
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1.Onboarding due diligence First, we will collect KYC & onboarding documents to identify the client. We may also employ a KYC Registry to consolidate all KYC data (may use third-party tooling), depending on the scale of the applications. Typical KYC & onboarding documents are as follows (which may vary across different jurisdictions): the Client’s name, contact details, registration number, registration date, registration certificate, scope of business, members of board and senior management and beneficial ownership structure. 
2. Post-allocation Vetting The post-allocation vetting of Clients will be performed regularly and constantly to avoid the allocated DataCap being abused or misused. The fundamental principle is that the Client is obliged to spend the DataCap exclusively for the approved uses (which will be specified in our allocation decision). To this end, at any time of the Client’s spending the DataCap, we may ask the Client to provide: (i) a consolidated Content Identifier (“CID”) list for verified deals that includes deal CID and miner ID (showing how the allocated DataCap has been used); (ii) description of the data being stored and how the data has been processed; and (iii) instructions on data retrieval. Receiving the foregoing information, we will perform random-sample inspections on the verified deals sent out by the Client on chain by checking the deal CID and retrieve it from the corresponding miners to verify the data authenticity. In addition to the foregoing, other monitoring measures such as public monitoring, auditing (we will elaborate more on Q3 in this section). Since the DataCap will be allocated by stages, we may penalize the Client by delaying or even cancelling the outstanding DataCap if discovering any improper or fraudulent spending the allocated DataCap.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle) 
2. What is your use case for the DataCap being requested? 
3. What is the Filecoin address you would like me to allocate the DataCap? 
4. How much DataCap would you like to request? 
For organizational clients: 
5.First of all, the Client’s Filecoin address is required to be disclosed for us to closely monitor after the DataCap allocation.  Moreover, we will keep our eyes open on such Client’s storage orders placed from time to time (especially for verified deals) and relevant storage providers. 
6.As set forth above, the granted DataCap will be available to the Client by stages.  So usually we can withhold the remaining DataCap from being allocated if the Client is found over-allocating its available DataCap to any single entity.
7.We will set up a Client rubrics mechanism that scores the Clients with varying trust.  Among others, the more diversified the Client allocates its granted DataCap, the higher scores the Client will get.  The Client may get bonus score if deploying less than 30% DataCap to any storage provider while it will suffer score deduction for deploying ≥70% Datacap to any storage miner for a period of time.
8.Penalties - if a Client gets a too low score in terms of diversification of storage providers, a warning will be issued and all the other notaries will be notified of the aforementioned “Over-Concentrated Allocation”.  Further punitive actions, such as cancellation of the remaining DataCap, may be taken in response to any Client’s persistent neglection of our warning.
9.Audits - both external and internal audits will be conducted throughout the data deployment process. The community members are encouraged to take part as the external auditor to expose any Client’s over-concentration on Datacap allocation.  
10.What is the name, nature, registration country, time since inception, and named officers of your organization? Please link to relevant websites. 
11. In which region do you intend to use the DataCap? If you intend to use the DataCap in multiple regions, please specify. 
12. How many miners do you plan on allocating a DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
It depends on the particular Client whether we are going to conduct our decision in public or private.  Some Clients are reluctant to be too much exposed and may require us to minimize publicity.  We are generally fine either way.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Yes, all allocation decisions will be guided by the rubric publicly on Github. So are all communications. 
Since all interactions are intended to occur publically, most of the allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly in the Github repo first. 
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
20h
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
no
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
no
```

**Comment by galen-mcandrew** [comment]
[Firefly - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320868/Firefly.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi  @fireflyHZ  **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Asia minus GCN.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 20 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by liuwencheng9527** [comment]
> Hi @fireflyHZ **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.
> 
> In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:
> 
> 1. Please confirm that the region of operation for client applications you will focus on is Asia minus GCN.
confirm. 
> 2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).        
>    •	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship    .
>    •	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.    
>    •	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.    
>    •	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.    
>    •	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.    
>    •	Community Governance Participation: It is expected that you will participate in the program 20 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.
confirm
> 3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.
f02420/f099132/f044315/f0104398/f0122533/f0117450/f0130686/f0148452/f0734053/f0839133/f01115279/f01694118/f0144528/f0839084
> 4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.
confirm
> 5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.    
>    •	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: [https://shop.ledger.com/pages/ledger-nano-x)    ](https://shop.ledger.com/pages/ledger-nano-x)%E2%80%A8)
f1hoovird56f7rb2dzruwnkah2b247n2mbarfqycy

**Comment by fireflyHZ** [comment]
> Hi @fireflyHZ **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.
> 
> In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:
> 
> 1. Please confirm that the region of operation for client applications you will focus on is Asia minus GCN.
confirm
> 2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).        
>    •	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship    .
>    •	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.    
>    •	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.    
>    •	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.    
>    •	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.    
>    •	Community Governance Participation: It is expected that you will participate in the program 20 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.
confirm all.
> 3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.
f02420/f099132/f044315/f0104398/f0122533/f0117450/f0130686/f0148452/f0734053/f0839133/f01115279/f01694118/f0144528/f0839084
> 4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.
confirm
> 5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here.    
>    •	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: [https://shop.ledger.com/pages/ledger-nano-x)    ](https://shop.ledger.com/pages/ledger-nano-x)%E2%80%A8)
f1hoovird56f7rb2dzruwnkah2b247n2mbarfqycy

**Comment by galen-mcandrew** [comment]
@fireflyHZ 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by fireflyHZ** [comment]
@galen-mcandrew @Kevin-FF-USA we need change our DataCap address, because our old ledger unable to use . We will print  our new address here later.

**Comment by fireflyHZ** [comment]
> @galen-mcandrew @Kevin-FF-USA we need change our DataCap address, because our old ledger unable to use . We will print our new address here later.

f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa

**Comment by fireflyHZ** [comment]
For better identification, we change our slack name to "FireflyHZ"

**Comment by Kevin-FF-USA** [comment]
Hello @fireflyHZ!

We have updated your wallet to: f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa

We will be communicating via Slack with embedsky.

**Comment by Kevin-FF-USA** [comment]
Also @fireflyHZ  

For security - can you please verify if you would like to authorize BOTH FIREFLYHZ and Embedsky handles to represent you in SLACK?

**Comment by Kevin-FF-USA** [comment]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/94004586/167268982-da71b044-02bc-4a8d-a79d-b8a38646efd4.png">

**Comment by fireflyHZ** [comment]
> Hello @fireflyHZ!
> 
> We have updated your wallet to: f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
> 
> We will be communicating via Slack with embedsky.

I am sorry ,I can not login the slack account named 'embedsky'.  When I filled out this form, I thought the Name in the form was just a username. And I filled out my slack name here 
![2022-05-09 10-53-43屏幕截图](https://user-images.githubusercontent.com/100905326/167332683-9af97d36-d5cf-4bdb-a46e-5a51334b6075.png)

**Comment by fireflyHZ** [comment]
Hi @Kevin-FF-USA , Embedsky slack account should have been caused by a mistake in my understanding. I personally use the name embedsky. For example, my email is called embed_sky@163.com. My personal github account is also called embedsky.  I am sure the FIreflyHZ account is right.

**Comment by fireflyHZ** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacediilwuwwsm5ceuws7fauruqzmuedkxyl37nvebhglj7tnnvpbubc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacediilwuwwsm5ceuws7fauruqzmuedkxyl37nvebhglj7tnnvpbubc

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Datacap Allocated
> 500TiB

**Comment by dkkapur** [comment]
Notary address needs to be verified. Closing this issue for now.

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzacedodkglm42km7afsfstqkadqopqoolirjjn7dhk6voiovwyvz4mka
