### ISSUE TITLE
Notary application - Julien NOEL Twinquasar / CID gravity

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/notary-governance#468]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Julien NOEL
- Affiliated Organization: Twinquasar
- Website / Social Media: http://twinquasar.io / Slack :  Julien NOEL - Twin Quasar (s0nik42) 
- On-chain Address(es) to be Notarized: f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
- Region of Operation: I operate and I’m physically based in France / Europe
- Use case(s) to be supported: Any
- DataCap Requested: 100 TiB or any allocation that can be granted to my profile.

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
I’m the founder of Twin Quasar a Filecoin ecosystem mining and CID gravity a software development fully engaged with  Filecoin for many years. We invest money and all our time to support and help the Filecoin ecosystem.  We will do as much as we can for Filecoin to succeed.
Personally, I've been using  IPFS for years, I joined filecoin community 15months ago.
- Running miner : f010479
- Granted 3 times for Lotus-farcaster
- CID gravity is funded by Filecoin main player and ecosystem. 
- Presenting for miner show and tell : https://www.youtube.com/watch?v=1JtQnhvxlVg
- Presenting for Celebration week : https://www.youtube.com/watch?v=cyer6_gSv78
- Participating to SR1 / SR2 Orbital burn / Slingshot 1/2.2/2.3 (project dCompute) / Apollo program
- Participating to Dorahack Hackathon
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
~10 000Fil
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- Developing Farcaster an opensource software for the miner community
- Current Notary for EU. Participating to weekly calls and actively helping to scructure the Fil+ program.
- Leading the EMEA storage provider group
- Funder of CID gravity. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
- CID gravity help storage-providers to protect their platform. 
- CID gravity will support new  features to protect the network against illegal content. 
```

### Organizational Reputation
Please describe the nature of your organisation, including the country of registration, size of the organisation, and time since inception.
```
Twinquasar is a storage providers managing internal and client miners
CID gravity is a platform aiming to participate to Filecoin enablement for B2B market)  

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Linkedin : https://twitter.com/cidgravity (1000+ followers)
Slack : cidgravity-x.slack.com (500+ members)
Website : http://twinquasar.io
Website: http://cidgravity.com
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.youtube.com/watch?v=VODTRCMEPe4
https://www.youtube.com/watch?v=s6A6v7qeK-c&t=290s
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
I spent 17 years working for Tech companies with an expertise in Datacenters, Operating Systems, network and secuirty. My last position was Head of a Business Unit for a fortune 100 company.

Linkedin : https://www.linkedin.com/in/julien42/ (900+)
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
I’m looking to help and support filecoin growth. After working closely with the Notary during the first wave of notaries to define process to on-board large client, I would like to work on onboarding such client. 
In // I'm interesting to small project of the ecosystem like Lighthouse or MooseDar 
I'm also interested in supporting the Fil+ LDN objectives and initiative like Filecoin Restore, etc... 
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
PRINCIPLES : 
My approach is similar to What I did until now  : 

Defining thresholds with varying degrees of trust.
Higher the request, Higher the scrutiny

Several factors will be considered when making allocation decisions: 
- Reputation of organisation
- Scale of allocation over a certain period of time
- Security considerations
- Transparency of Client
- Client engagement to respect guidelines :
	- Process
	- Delegation
	- Contractual terms. 
	- etc…
- Sucess of a Probation period for new client (described below)
- Public or Private Data

Allocation plan : 
1. All new client start with 1-2TiB max
2. After successfully consuming the first allocation and only if it's in line with it's commitments,  client can request and get allocation for more datacap (max 5TiB)
3. Continue 5TiB iterations
```

How do you plan on securing the DataCap to ensure your organisation (and its delegated members) are the ones allocating the DataCap?
```
Ledger
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
 - Type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. 
 - public data vs private data etc
 - Your relationship with the data, especially with regard to copyright
 - How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
 - Have you already ask datacap to another notary that have been accepted or rejected.
 - Do you run a storage miner ?
 - How much data are you considering storing to your own miner ?
 - Please describe the nature of the relationship with this miner especially if you've got any interests in storing these miners ?
 - Will you agree to share here all the CIDs related to the datacap ?
 - Did you already have datacap from another notary ?
 - Adress confirmation
 - Entity proof : 
     - certificate of incorporation, business evidence and reputation
     - business address and location, etc..
 - Requester personal information : 
     - Bylaws / authorization from the company / title
     - Identity card / passport delivered by government and valid. 

 
If the data is private, I ask much more information and authorization from the client to audit the data unencrypted.

- Asking for commitment and transparency from the client
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. Commit the client on how the datacap will be consumed : 
2. Verify once the datacap is consumed : 
- Check on https://filplus.d.interplanetary.one how the data is spread across miners
- Audit a few deals (as soon its achievable),  
3. Iterate
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
For transparency purpose, I plan to provide all the allocation decisions in public via a GitHub repo. I will also agree to align the process the other notaries and the community; keeping in mind the processes we put in place have to be efficient. 
I will answer to any audits requests. 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
For transparency purpose, I provide all the allocation decisions in public via a GitHub repo. I will also agree to align the process the other notaries and the community. 
Private allocation will need more tooling and tracking that are not here yet. Depending on the volume of such requests I may consider accepting private requests.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
In current conditions, I will say 2Hours a week
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
https://github.com/filecoin-project/notary-governance/issues/5
https://github.com/filecoin-project/notary-governance/issues/136 
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
108TiB
```

**Comment by galen-mcandrew** [comment]
[Twinquasar - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320889/Twinquasar.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by dkkapur** [comment]
![image](https://user-images.githubusercontent.com/2343218/159535752-a76557a2-fa2c-4a8e-a67a-f2158cd1d1b3.png)

@s0nik42 I think you might have accidentally overridden G20 with "3" instead of leaving it as "=G21". Math lines up for me, 2.4 unrounded.

**Comment by s0nik42** [comment]
Oh ! I see ! thank you @dkkapur

**Comment by Kevin-FF-USA** [comment]
Hi  @s0nik42  **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Europe.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 2 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by galen-mcandrew** [comment]
@s0nik42 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @s0nik42!

Just a friendly ping - there is some additional information needed in order to finalize, **can you please follow this link to complete by April 15th?**
[Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)

**Comment by Kevin-FF-USA** [comment]
Hello @s0nik42!

We have your address on file as: f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii

We will be communicating with Julien NOEL - Twin Quasar - CID gravity via Slack. Thank you!

**Comment by s0nik42** [comment]
perfect ! :)

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### Datacap Allocated
> 100TiB

**Comment by s0nik42** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceceevx5vrpym24cgmx7ciflituax2ebru645b47szj256v2w3oun2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceceevx5vrpym24cgmx7ciflituax2ebru645b47szj256v2w3oun2

**Comment by dkkapur** [comment]
Notary address verified. Closing this issue for now.
