### ISSUE TITLE
Notary Application from Filecoin Foundation

### ISSUE THREAD

**Issue by dannyob** [filecoin-project/notary-governance#469]
## Core Information
- Name: Danny O'Brien
- Affiliated Organization: Filecoin Foundation
- Website / Social Media: https://fil.org/ 
- On-chain Address to be Notarized: f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
- Region of Operation:  EU/NA 
- Use case(s) to be supported: All use cases, with an institutional emphasis on our aim to preserve "Humanities most important open and public data"
- DataCap Requested: 1 PiB

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
I am Senior Fellow at the Filecoin Foundation Foundation. As an organization, the [Filecoin Foundation](https://fil.org/about) is an independent organization dedicated to supporting the growth and long term success of Filecoin.  The Foundation was also the first beta notary for Filecoin Plus, as well as a notary for Europe in the first round of notary selections where @philippbanhardt represented the Filecoin Foundation and distributed 100TiB of Data Cap. 

I have been operating the Filecoin Foundation Notary process since [July 2021](https://github.com/filecoin-project/notary-governance/issues/187#issuecomment-883627535), as part of my duties at the Filecoin Foundation to monitor and steward the long-term health of the Filecoin ecosystem.

Note that, should this application be successful, the Foundation plans to work on expanding the notarising role within the organization so that it can be managed by more than one person, in order to increase the level of commitment and due diligence we can perform, and to explore how to provide a notary service in a way that is more closely tied to our organizational reputation, versus individual reputations. I/We (@dannyob) plan to continue to operate oversight over the notary process, both in external examination of potential clients, and in oversight and development of our internal process.

Nicole Blystone, Operations Manager for the organization, will also be performing diligence on client applications in order to increase oversight and contribute to the overall organizational repututation as a part of this plan to expand notarization within the organization. Under direction of Danny O'Brien, Nicole will work to perform diligence with the mission of supporting the long-term success of Filecoin and help Filecoin Foundation act as stewards for the ecosystem.
```

### Stake Exposure

Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
100 million tokens, per the vesting [schedule](https://coinlist.co/filecoin). 
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
The Filecoin Foundation is an independent organization dedicated to supporting Filecoin, an open source, decentralized storage network designed to preserve humanity’s most important information.The Filecoin Foundation facilitates governance of the Filecoin network, funds critical development projects, supports the growth of the Filecoin ecosystem, and advocates for Filecoin and the Decentralized Web.

As a Filecoin Foundation Senior Fellow, I spent the majority of my time working towards the long term sustainable development of the Filecoin community. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
The Foundation employs a [full-time computer security team](http://fil.org/governance/#panel-2-title), who maintain our bounty program, and organizes audits of key components of the Filecoin stack.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
The Filecoin Foundation is an independent organization dedicated to supporting Filecoin, an open source, decentralized storage network designed to preserve humanity’s most important information.The Filecoin Foundation facilitates governance of the Filecoin network, funds critical development projects, supports the growth of the Filecoin ecosystem, and advocates for Filecoin and the Decentralized Web.

The Filecoin Foundation was founded in 2018 is registered in the US. It currently employs 40 staff.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://fil.org/ 
https://twitter.com/FilFoundation
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
http://filecoin.io/blog/posts/meet-the-filecoin-foundation/
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://www.twitter.com/mala (8000)
https://www.linkedin.com/in/dannyo2/ (500+)
https://keybase.io/malaclyps (192)
https://github.com/dannyob (247)
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We will primarily support (1) open data sets (high trust, unambiguous, and easy to maintain), that truly feed into Filecoin's mission of being the foundation for humanities most important information, and (2) support strategic growth initiatives for the Filecoin project as a whole. Across all use cases we expect they foster decentralization across the entire network.

The mission of the Filecoin Foundation is to ensure the long term success of the Filecoin Network. Through our work with members of the Filecoin Ecosystem the foundation has a unique understanding of the reliability of ecosystem partners. The Filecoin Foundation can apply data cap through these trusted relationships to ensure onboarding of useful data to the Filecoin Network.  
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We use application judgement modeled after the one used by https://github.com/filecoin-project/notary-governance/issues/29# 

We also use our knowledge of teams needing data cap through our work with them in programs such as our developer grant program, and our ecosystem development programs, and real-world partners supported by our sibling non-profit organization, the Filecoin Foundation for the Decentralized Web, to help promote the public interest goals of verified clients and help facilitate their onboarding of useful data to the filecoin network. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The address that allocates DataCap has its keys secured on a hardware wallet. Foundation employees acting in the role of notary have and will been be vetted by the foundation. 

```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Clients who apply for DataCap for a project associated with other Foundation services will have the allocated data evaluated in conjunction with their other milestone check ins. 

Clients who apply for DataCap from the general public will have submitted a detailed proposal and have been vetted according to the criteria in the above rubric 

Clients behavior will be compared to the plan they had submitted and if there are significant deviations, especially with publicly available data, the foundation will investigate.  We continue to utilize tooling that will automate verification of on chain data vs what was proposed in the clients initial application. We also expect the community to flag any broad cases of wrong doing and to work with our dispute management system. Additionally those found to have misallocated data will be strongly discouraged from engaging in other forms of Filecoin Foundation support. 

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We monitor the outlay of previous datacap, and ensure that it is being widely allocated (barring mitigating explanations of a temporary nature).
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will happen in public in the appropriate github repository - communications will take place through the repository and the issue tracking. Occasionally, we will use private email to confirm identities or reputation: for example to confirm  whether a Github use is legitimately representating the organization that it claims to be. The result of these inquiries will be made public on the repo.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
All allocation decisions will happen in public in the appropriate filecoin-project repositories.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
We anticipate spending 1-5 hours a week on this work, depending on load. Our hope is that by increasing the staff dedicated to the notary process, we can also increase the amount of time we can spend in due diligence and examination of client plans, as well as supporting better tooling for clients and notaries.

```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
@philippbanhardt acted as a representative of the Filecoin Foundation in our first application:
https://github.com/filecoin-project/notary-governance/issues/54

@meganklimen acted as representative of the Filecoin Foundation in the previous application:
https://github.com/filecoin-project/notary-governance/issues/187
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
354.10 TiB
```

**Comment by galen-mcandrew** [comment]
[Filecoin Foundation - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320885/Filecoin.Foundation.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi  @dannyob  **based on this Notary election cycle's final scoring, you/your organization has qualified to be a Fil+ Notary!** You will be receiving your final scored rubric soon, along with the total allocation of Datacap based on rubric scoring.

In order to confirm your participation as a Notary in the Fil+ ecosystem, please respond to the following:

1.  Please confirm that the region of operation for client applications you will focus on is Europe.  

2. Please confirm each of the following items below (you can do this by quoting each of the following bullets and adding a line under each section agreeing that you'll abide by these operational principles).  

	•	Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .
	
	•	Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 
	
	•	Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected. 
	
	•	No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 
	
	•	Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 
	
	•	Community Governance Participation: It is expected that you will participate in the program 1-5 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input. 
	
3. Please list any addresses you are affiliated with, and state the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.  

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.  

5. (If ready) Please confirm the address that should receive DataCap. This is the address which you will use to sign messages on-chain to verify clients (through using a Ledger and the Fil+ Registry App). If you have an active (non-zero) DataCap grant from a previous election cycle, please provide a different address here. 
	•	If you do not have a ledger already, we recommend ordering directly from the Manufacturer for the Nano S or Nano X (link: https://shop.ledger.com/pages/ledger-nano-x)

**Comment by galen-mcandrew** [comment]
@dannyob 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @dannyob!

Just a friendly ping - there is some additional information needed in order to finalize, **can you please follow this link to complete by April 15th?**
[Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)

**Comment by dannyob** [comment]
Done! Sorry about the delay

**Comment by dannyob** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceacmkgpjll3yujfwka6zmdtp3ziqnj23g46fkollr2h75mwt7mtri
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacmkgpjll3yujfwka6zmdtp3ziqnj23g46fkollr2h75mwt7mtri

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### Datacap Allocated
> 1PiB

**Comment by dannyob** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedxhnt45wifuj7q6s2n2u53fp2hg5dc44q7gh2rcur4pm6iod37eq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxhnt45wifuj7q6s2n2u53fp2hg5dc44q7gh2rcur4pm6iod37eq

**Comment by dkkapur** [comment]
Notary address verified. Closing this issue for now.

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzaceb2qh3utcoaq53ha7badudkbp3l52c5o72nlfu7b7v4gkwbqu7ez2
