### ISSUE TITLE
Tinfra Notary Application

### ISSUE THREAD

**Issue by bmcnabb25** [filecoin-project/notary-governance#470]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Tinfra LLC
- Affiliated organization: Telnyx LLC
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address): f1jqk7xok5kautet2knhwlg74jvcfbrqlj47kbp2i
- Region of Operation: North America
- Use case(s) to be supported: General
- DataCap Requested: 10 PiB 

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
We attended the ESPA Accelerator last week (Feb 21 2022 - Feb 25 2022)

We have also made significant investments in hardware, and are planning on adding 700 Petabytes in storage capacity and 1 Petabyte of sealing capacity to the network this year alone. We are close to getting our first storage miner operational in Denver, and hope to have nine other storage miners up and running in the fastest growing cities across the US by the end of the year. We are also planning on making further investments into adding storage miners in other regions.

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
We currently hold more than 1MM  FIL, all of which are available.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
N/A
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Tinfra LLC is a fully-owned Subsidiary of Telnyx LLC

Country of registration: United States
Nature: Private Company
Size of Organization: ~350 employees and growing
Date of Inception: Founded in 2009

Telnyx is a next-gen communications platform that provides carrier-grade services on a global, private IP network. By unlocking the power of intelligent connectivity, we’re laying the foundation for a future of endless innovation and interconnected technology, where communication flows seamlessly between people, devices and applications across the globe
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://telnyx.com/
Linkedin: https://www.linkedin.com/company/telnyx/mycompany/
Twitter: https://twitter.com/telnyx?lang=en
Instagram: https://www.instagram.com/telnyx/?hl=en 
David Casem, CEO: https://www.linkedin.com/in/dcasem/ 
Ian Reither, COO: https://www.linkedin.com/in/ianreither/ 

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
G2 Reviews: https://www.g2.com/products/telnyx/reviews 
Capterra Reviews: https://www.capterra.com/p/173804/Telnyx/reviews/
Glassdoor Reviews: https://www.glassdoor.com/Reviews/Telnyx-Reviews-E841349.htm
G2 Grid Report: https://telnyx.com/resources/telnyx-named-cloud-communications-leader-in-the-2022-g2-grid-report 
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Linkedin(~6400 followers): https://www.linkedin.com/company/telnyx/mycompany/
Twitter (~2975 followers): https://twitter.com/telnyx?lang=en
Instagram (~613 followers): https://www.instagram.com/telnyx/?hl=en 
David Casem, CEO (~3300 followers) : https://www.linkedin.com/in/dcasem/ 
Ian Reither, COO (~4300 followers): https://www.linkedin.com/in/ianreither/
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We are open to supporting any use case.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Please answer here.
All potential clients will submit an application to us, answering the questions outlined in the “Client Due Diligence” section of this application. Based on the information they provide, we will evaluate their application given the following scoring matrix (https://docs.google.com/spreadsheets/d/1yo5RLdCV-p6nUH3y3LjXFoEY1i-JN1NyFRE_Qfh_oyQ/edit?usp=sharing). The client will be allocated the appropriate amount of DataCap based on their final score and the amount that they requested.

Given the information provided by the client, if we do not feel confident that the client has proved their identity, or if the responses from the client do not line up with the Principles of the program, we will refuse allocation of DataCap.

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The key allocated to the DataCap is protected on the multi-signature hardware wallet.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will follow the scoring matrix referenced in the “Allocation Strategy” section.

Questions we will ask potential clients are as follows:
Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin, etc.)
If you represent an organization, what is the name, nature, registration country, size, time since inception, and named officers of your organization?
Why are you applying for DataCap? What is your intended use case?
How much DataCap are you requesting?
Have you participated in the Filecoin network before? If yes, please elaborate.
Have you applied for DataCap before? If yes, was the application successful? If publicly available, could you provide links to your application?
How many storage miners are you planning on allocating the DataCap to? If there are specific storage miners, please list their IDs
Which region(s) are you planning to store your data in?
Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will ask the clients to provide information on the storage deals they previously made with their DataCap allocation. We will review their deals to see whether they were spread across multiple storage providers, and whether there are any signs of misuse. After evaluating the client’s previous DataCap usage, we will follow the same DataCap allocation process outlined above to determine how much DataCap the client will receive.

We will also ask clients to be transparent and make a commitment to share their DataCap allocations in public. We will periodically inspect and audit the DataCap usage of the clients as well.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be guided by the scoring matrix and made publicly available on Github.  
Any challenges raised regarding allocation decisions should be discussed publicly, e.g. via the Github repo.
If convincing justifications can't be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since the original challenge date. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions.

```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We plan on making all allocation decisions public by recording them in a Github repo. If selected, we will establish a Discord and Telegram as well. 
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
A team will screen and review all applications once per day. Any application that passes the screening given our outlined criteria will be allocated DataCap accordingly.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No we have not
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
N/A
```

**Comment by galen-mcandrew** [comment]
[Tinfra - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320956/Tinfra.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by bmcnabb25** [comment]
> [Tinfra - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320956/Tinfra.-.Round.3.Notary.Election.Scorecard.pdf)

@galen-mcandrew thank you for reviewing our application. What does the Unrounded Score mean? I.e. are we going to become notaries? And if so, how much DataCap will we be responsible for?

We can provide a 1 business day SLA to score applications, or respond to any related comments/issues

I can have some other members of the team address your other comments/concerns in follow up comments

**Comment by bmcnabb25** [comment]
Realistically we will dedicate 5-10 hours per week, and any additional time if necessary to meet the 1 business day SLA

**Comment by jurica-curic** [comment]
Just wanted to confirm @bmcnabb25 request. I can confirm info in this request and I will be one of the engineers working on this project. If you need any additional info, plz let me know

**Comment by bmcnabb25** [comment]
1. Confirming we will focus on client applications from North America

2. We agree to abide by the following operational principles (quoted below):
> Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship

> Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here. 

> Commitment to efficiently serving the Network: Notaries agree to serve as fiduciaries of the Network, striving to work towards bringing useful data onto Filecoin and improving the experience for clients to do so. Notaries should generally be able to respond to Client applications and updates within 3 days, and should be comfortable communicating with Clients and Notaries if an application needs to be redirected.

> No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

> Operating in Good Faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

> Community Governance Participation: It is expected that you will participate in the program 10 hours a week. Along with data allocation, participation in Github issues and Slack conversations, Notaries are to make an effort to regularly attend the scheduled Governance calls. As these calls are a forum to shape this process, it is important to ensure Notaries are present to provide their context, with discussions and input.

3. Close to getting our first miner operational. When it is running, I can add a follow up comment to this application with the miner address. And as we continue to deploy more miners, I will continue to follow up and comment on this application with those addresses as well

4. We will abide by the allocation / client due diligence plan we laid out in the application.  

5. Need to confirm the address that will receive DataCap, and that we are using a ledger. Will post a follow up comment soon

**Comment by galen-mcandrew** [comment]
@bmcnabb25 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by bmcnabb25** [comment]
@galen-mcandrew @Kevin-FF-USA
1. We need to generate a new wallet address for this. Will update the application and post a comment once done
3. I don't believe I have been added to the Fil+ slack channel yet. And I don't believe I have received any emails either about onboarding. When can I expect to see those? Just want to make sure stuff isn't getting lost in my inbox

**Comment by Kevin-FF-USA** [comment]
Hello @bmcnabb25!

We have your address on file as: f3rxsadodcupkqtxuh5lf3yn2i4z3ktmljfcuzfft4dm6kcy7znm2qzrbqfda3e4rjtdhq7vfqknt2yvqvn7ca

We will be communicating with Brandon McNabb and David (Tinfra) via Slack. Communication approval for xd pending verification below.

**Comment by bmcnabb25** [comment]
@Kevin-FF-USA new wallet address is f3v63yoyzreflprzyhwlactgrjompw5yzouto3sbj2hv435ym65o2qjynfb6vuhx3jlapiyjusz5jsqudsglha

Should I update the application as well?
Thanks!

**Comment by bmcnabb25** [comment]
Final wallet address is f1jqk7xok5kautet2knhwlg74jvcfbrqlj47kbp2i

And has been updated in the application

**Comment by bmcnabb25** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebtz2twx2zhc6qwpqc4keccmbloqv5caxjms3gxenftsfa32hhwpe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebtz2twx2zhc6qwpqc4keccmbloqv5caxjms3gxenftsfa32hhwpe

**Comment by galen-mcandrew** [comment]
@bmcnabb25 We have your new f1 address updated, but the 1FIL was already sent to your previously supplied f3 address. You can move that FIL from your f3 address to your new address, f1jqk7xok5kautet2knhwlg74jvcfbrqlj47kbp2i

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1jqk7xok5kautet2knhwlg74jvcfbrqlj47kbp2i
#### Datacap Allocated
> 1PiB

**Comment by bmcnabb25** [comment]
Update:

Have a few miners up and running now. Their addresses are as follows:
- f01847751
- f01858235
- f01872811
- f01882569

We plan on setting up a few more miners in the coming months. Will disclose with a new comment when up and running

**Comment by dkkapur** [comment]
Thanks. Let us know what the new SP IDs are @bmcnabb25.

Closing the application out for now.

**Comment by bmcnabb25** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebpzvsezsbk4mbocl3smlch6kexgl5zggisjwqnm2lybb45uitxry
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpzvsezsbk4mbocl3smlch6kexgl5zggisjwqnm2lybb45uitxry

**Comment by bmcnabb25** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceatjxcd72wn3tkkygjwnxnqwa7qrbhhavmgzvsjpm25vnobeafb5m
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatjxcd72wn3tkkygjwnxnqwa7qrbhhavmgzvsjpm25vnobeafb5m

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1jqk7xok5kautet2knhwlg74jvcfbrqlj47kbp2i
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzaceb3wrpkrixscvlb5fauj2frbb5qeyeewybm3rovl4ennatmhahclm
