### ISSUE TITLE
Nicklas Reiersen / TechHedge Notary Application

### ISSUE THREAD

**Issue by Reiers** [filecoin-project/notary-governance#471]
# TechHedge Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Nicklas Reiersen
- Affiliated Organization: TechHedge
- Website / Social Media: www.filecoin.no - (password protected) Slack: @Reiers
- On-chain Address to be Notarized: f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
- Region of Operation: Norway, Europe
- Use case(s) to be supported: any
- DataCap Requested: 100 TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
TechHedge - Not incorporated. TechHedge was initially just a investment group interested in tech, 4 members. 
We found IPFS years ago and been using it frequently ever since. We fell in love and invested in Filecoin under the ICO. 
Now we have converted a house into a DC and are committed to help out in anyway we can. 
- minerID : f022352
- Active member in Community since Nov 2019. 
- Participated in SR1 / SR2 Orbital burn
- Participated in MinerX, MinerX.2, MinerX.3
```
- **Full disclosure: I also work as a Technical Support Engineer (Lotus) for Protocol Labs and because of this I cannot review or sign any Datacap applications that are affiliated with Protocol Labs.** 

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
50000 FIL
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- Proud and active MinerX member
- Actively participating and helping out in the Filecoin Community.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
Added issues on GitHub. 
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
TechHedge - Investments, Marketing, Networking, Data Center, Web Design. 
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website : http://www.filecoin.no
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
-
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Nothing
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
Defining thresholds with varying degrees of trust.
Higher the request, Higher the scrutiny

Several factors will be considered when making allocation decisions: 
Reputation of organization
Scale of allocation over a certain period of time
Security considerations
Transparency of Client
Client engagement to respect guidelines :
	- Process
	- Delegation
	- Contractual terms. 
	- etc…
Sucess of a Probation period for new client (described below)
Public or Private Data
```

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
No. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Separate node with a cold storage wallet - or a ledger. 
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
- Asking for commitment and transparency from the client
- Phasing 
- Approbation phase : 2TiB
- Verify the process is understood from the client and correctly apply
- Allocate More + Audit iteration (5TiB max)
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
 - Yourself , e.g. include links to social media / news mentions etc
 - Your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
 - Type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. 
 - public data vs private data etc
 - Your relationship with the data, especially with regard to copyright
 - How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
 - Have you already ask datacap to another notary that have been accepted or rejected.
 - Do you run a storage miner ?
 - How much data are you considering storing to your own miner ?
 - Please describe the nature of the relationship with this miner especially if you've got any interests in storing these miners ?
 - Will you agree to share here all the CIDs related to the datacap ?
 - Did you already have datacap from another notary ?
 - Address confirmation
 
If the data is private, I ask much more information and authorization from the client to audit the data unencrypted.
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
I ask the client to publish all the deals to the GitHub repo. Then I go through all deals, verify they are correct, and calculate the % of allocation per miners.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
For transparency purpose, I plan to provide all the allocation decisions in public via a GitHub repo. I will also agree to align the process the other notaries and the community; keeping in mind the processes we put in place have to be efficient. 
I will answer to any audits requests. 
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
For transparency purpose, I provide all the allocation decisions in public via a GitHub repo. I will also agree to align the process the other notaries and the community. 
Private allocation will need more tooling and tracking that are not here yet. Depending on the volume of such requests I may consider accepting private requests.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
- Reviewed and Signed multiple Large Dataset Applications.
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
No.
```

**Comment by galen-mcandrew** [comment]
[TechHedge - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320892/TechHedge.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by galen-mcandrew** [comment]
@Reiers 

Please fill out this form to move forwards with the ratification process: https://airtable.com/shrs55Lzbm1wJTIRw

**Comment by Kevin-FF-USA** [comment]
Hello @Reiers!

Just a friendly reminder - there is some additional information needed in order to finalize, **can you please follow this link to complete by April 15th?**
[Acceptance Form](https://airtable.com/shrs55Lzbm1wJTIRw)

**Comment by Reiers** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedbrswhvouhkj3hynmjcqouqacxn34mkobmkeslmhwptl35jy5yzi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbrswhvouhkj3hynmjcqouqacxn34mkobmkeslmhwptl35jy5yzi

**Comment by Kevin-FF-USA** [comment]
Hello @Reiers!

We have your address on file as: f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq

We will be communicating with Reiers on Slack; if there are any other Slack handles you wish to have included, please include them in a comment below.

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### Datacap Allocated
> 100TiB

**Comment by Reiers** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebncjvzdq45podgua2ymk6yaec36uiebz2sm2avhisb5zphvvlu7m
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebncjvzdq45podgua2ymk6yaec36uiebz2sm2avhisb5zphvvlu7m

**Comment by Reiers** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaced4kwshnesiovu2ujosys4xazoox7xq4okvqt36trwrvha22pttd2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4kwshnesiovu2ujosys4xazoox7xq4okvqt36trwrvha22pttd2

**Comment by Reiers** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceard2o2q7aeirydsex5galvlvwrmtlmd35x37dlm7oaksgi7nppo6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceard2o2q7aeirydsex5galvlvwrmtlmd35x37dlm7oaksgi7nppo6

**Comment by Reiers** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedb3rgsgfm46slvtpevwamkbxs2yjfisupryzvpefdmm3yhfnhxok
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedb3rgsgfm46slvtpevwamkbxs2yjfisupryzvpefdmm3yhfnhxok

**Comment by dkkapur** [comment]
Notary address verified. Closing this issue for now.
