### ISSUE TITLE
Notary Application: Sxxfuture 

### ISSUE THREAD

**Issue by janckerchen** [filecoin-project/notary-governance#473]
Sxxfuture Notary Applicationx

# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Sxxfuture 
- Affiliated organization: SAN XIA XING FUTURE DATA TECHNOLOGY(YICHANG)CO..LTD, (三峡星未来数据科技（宜昌）有限公司)
- On-chain address to be notarized (recommend using a new address): f17hvhz4upnakx6cwg4kuji442aopmjwate3eh7ay
- Region of Operation: GCN, Asia
- Use case(s) to be supported: Media & Entertainment, Web 3.0/Dapp, NFTs, Web 2.0 App, User Content,
- DataCap requested for allocation (10TiB - 10 PiB): 1 PiB

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
We are firmly involved in filecoin based on long-termism. 

Against the background of a significant ebb in FIL industry fever, a not-so-friendly policy environment in GCN and a long-term downturn in coin prices, we invest in technology development, set up application teams, build server production and testing centers, scale arithmetic bases and highly friendly IDC server rooms to create a full industry service capability focused on filecoin. 

We advocate open and transparent to investor, embrace policy regulation, and strive to create a fair and healthy new ecology of FIL in GCN; 

we explore blockchain application in the field of agricultural industry, and develop blockchain authentication and large-scale distributed storage depository for high-quality agricultural products. 

We are located in the Three Gorges(三峡) area, which has **the world's largest** hydropower resources and we have built huge scale green machine rooms, with 100% green energy used for all operations and arithmetic, which is fully consistent with the Carbon Neutral goal pursued by Filecoin Green. 

The source of our confidence is to see filecoin's efforts in the future direction of Web3, and we are willing to participate in it and face the future together.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
sxxfuture serves as a distributed storages fullstack solution provider and do not hold any token.

Our investment clients hold FILs and it is not convenient to disclose.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We are committed to building a more open filecoin ecosystem, actively embracing the open source community, and providing various open source tools and support for DAPP applications on filecoin. 

We strive to explore the interconnection and value exchange between filecoin and other blockchains and ecologies, and establish a wider range of filecoin application possibilities. 

We actively assist independent customers in storing their valuable data in the filecoin network, giving users full ownership and control of the data, and working to build convenient data access channels and DAPPs to make it easier for customers to share and get the rewards they deserve from this data.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
company name: SAN XIA XING FUTURE DATA TECHNOLOGY(YICHANG)CO..LTD.(三峡星未来数据科技（宜昌）有限公司)
Country of registration: GCN
registered capital: 20,000,000RMB(about $3,000,000)
registration time: 2021/7/29
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
webchat: 三峡星
website: https://www.sxxfuture.com/
Github: https://github.com/sxxfuture
Twitter: https://twitter.com/SxxFuture
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://mp.weixin.qq.com/s?__biz=Mzk0MTMwODQxNA==&mid=2247483875&idx=1&sn=93f280cbcc560ec9c7023e6f7952434e&chksm=c2d52172f5a2a8647c0208f4e9ab5644b4ec2d50b054e13a53b04db9ad11a61adaab8872bf1e&token=1109639824&lang=zh_CN#rd
https://mp.weixin.qq.com/s?__biz=Mzk0MTMwODQxNA==&mid=2247484237&idx=1&sn=a1ccb6818fc779817a31e9e0914a187e&chksm=c2d523dcf5a2aaca1f13a49a29e61a09ddc211c4a7ba3faf57afe396455f3dc44970e1500ded&token=1109639824&lang=zh_CN#rd
https://baijiahao.baidu.com/s?id=1721917672055579353&wfr=spider&for=pc
https://mp.weixin.qq.com/s?__biz=Mzk0MTMwODQxNA==&mid=2247484199&idx=1&sn=35c628d5cdf2d291c7555b5f6ee70093&chksm=c2d523b6f5a2aaa09076e35edc454b8179a5c3d1de26e4a7e21e2314334e4ab288c4064bbf97&token=1109639824&lang=zh_CN#rd
https://mp.weixin.qq.com/s?__biz=Mzk0MTMwODQxNA==&mid=2247484120&idx=1&sn=e7ada6d2046136e057f977057961fba7&chksm=c2d52249f5a2ab5f570c21ec3e0e839e29c6c32b031d26d114cf8c4a46a1deb76e0dfe000c97&token=1109639824&lang=zh_CN#rd

```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We are open to supporting any use case.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Defining thresholds with varying degrees of trust.
Higher the request, Higher the scrutiny

Several factors will be considered when making allocation decisions: 
Reputation of organization
Scale of allocation over a certain period of time
Security considerations
Transparency of Client
Client engagement to respect guidelines :
	- Process
	- Delegation
	- Contractual terms. 
	- etc…
Sucess of a Probation period for new client (described below)
Public or Private Data
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The key allocated to the DataCap is protected on the multi-signature hardware wallet.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will follow the scoring matrix referenced in the “Allocation Strategy” section.

Questions we will ask potential clients are as follows:
Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin, etc.)
If you represent an organization, what is the name, nature, registration country, size, time since inception, and named officers of your organization?
Why are you applying for DataCap? What is your intended use case?
How much DataCap are you requesting?
Have you participated in the Filecoin network before? If yes, please elaborate.
Have you applied for DataCap before? If yes, was the application successful? If publicly available, could you provide links to your application?
How many storage miners are you planning on allocating the DataCap to? If there are specific storage miners, please list their IDs
Which region(s) are you planning to store your data in?
Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
- Yourself , e.g. include links to social media / news mentions etc
 - Your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
 - Type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. 
 - public data vs private data etc
 - Your relationship with the data, especially with regard to copyright
 - How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
 - Have you already ask datacap to another notary that have been accepted or rejected.
 - Do you run a storage miner ?
 - How much data are you considering storing to your own miner ?
 - Please describe the nature of the relationship with this miner especially if you've got any interests in storing these miners ?
 - Will you agree to share here all the CIDs related to the datacap ?
 - Did you already have datacap from another notary ?
 - Address confirmation
 
If the data is private, I ask much more information and authorization from the client to audit the data unencrypted.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be guided by the scoring matrix and made publicly available on Github.  
Any challenges raised regarding allocation decisions should be discussed publicly, e.g. via the Github repo.
If convincing justifications can't be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since the original challenge date. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We plan on making all allocation decisions public by recording them in a Github repo. If selected, we will establish a Discord and Telegram as well. 
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
A team will screen and review all applications once per day. Any application that passes the screening given our outlined criteria will be allocated DataCap accordingly.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
N/A
```

**Comment by galen-mcandrew** [comment]
[Sxxfuture - Round 3 Notary Election Scorecard.pdf](https://github.com/filecoin-project/notary-governance/files/8320941/Sxxfuture.-.Round.3.Notary.Election.Scorecard.pdf)

**Comment by Kevin-FF-USA** [comment]
We are very sorry to let you know that this application was not selected in this round of Notary Elections.  

Each application was scored according to the Rubric and [assigned a Scorecard](https://github.com/filecoin-project/notary-governance/issues/394). That score was then applied for each of the [geographic regions and the top scored applications were selected](https://github.com/filecoin-project/notary-governance/issues/479). 

We are humbled by your commitment, and grateful for your interest in the Filecoin Plus program. Looking forward to seeing you in the program and hope you resubmit in the future elections.

Should you have any questions please feel free to raise here, or DM me in Slack @Kevin_FF

**Comment by Kevin-FF-USA** [comment]
Onboarded in 4th Rd.
