### ISSUE TITLE
Discussion: Banning requests for data review in the Slack Fil-plus channel

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#475]
## Issue Description
As flagged in a few of the more recent Notary Governance Meetings, there has been a surge in requests for application reviews posted in the Fil-Plus public channel in slack. This channel has over 1,380 members in the channel, so the for the majority of members see this type of message as irrelevant spam. This has lead to the intent of collaboration and sharing in the channel to be lost and the thread to becoming noisy. 

As always, the motivating guide are the [principles](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0003.md) - so proposals / constructions should be mapped to how we can best promote those ideals.

## Impact
Newer members of the community are unable to sift through the noise of data application review requests. Existing Notaries and community members are unable to locate relevant and important community updates. 

## Proposed Solution(s)
Remove posts to the Fil-Plus channel requesting application reviews. 
Direct this type of review request to a  new channel [fil-plus-application-review](https://filecoinproject.slack.com/archives/C036JKD8NVA).

Escalation Steps
If a community member continues to post in Fil-Plus with requests for application review. 

- 1st occurrence: SLACK admin will remove post from Fil-plus channel and to re-post in fil-plus-application-review channel. Poster will be sent a template on the recommendation information to include for sharing updates on their project instead of just a request for review

- 2nd occurrence: Slack post removed by an admin member. Will not be reposted in fil-plus-application-review by Admin. Community member receives a final warning that review requests should not be posted to the fil-plus channel.

- 3rd occurrence: Post is deleted. Community member is removed from fil-plus channel

## Related Issues
https://github.com/filecoin-project/notary-governance/issues/427

**Comment by dkkapur** [comment]
Generally agree with the motivation, always good to have clear locations where people know where to go for specific resources. However, splitting notary attention and ensuring more channels are kept track of is hard. 

Some thoughts:
- even for the 1st occurrence, I think the onus should be on the client/requesting entity to repost in the right place (i.e., same as 2nd occurrence escalation)
- for 3rd occurrence - not sure how banning/removal works for a public channel on a public Slack. is this worth it?

**Comment by MegTei** [comment]
This is great idea, adds a clear filter for Notaries to be able to act faster. Support the change
