### ISSUE TITLE
[Proposal] Extending Review period for Third round of Notary elections

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#477]
Received an overwhelming large number of applications for this round Notary elections. In the scoring process, the time to review and comment on issues has taken longer than the initial 2 weeks allocated.  Proposing extending the Scoring and Additional Follow up time by another 2 weeks to allow additional time for applicants to respond to clarifying questions questions. 

Proposed Updated timeline:
Applications open: Feb 21 - Mar 04
Application scoring and additional follow-up: Mar 07 - Mar 25
New Notaries announced: April 1 

Previous timeline:
Applications open: Feb 21 - Mar 04
Application scoring and additional follow-up: Mar 07 - Mar 18
Initial set of new Notaries announced at Governance call on Mar 22

Seeking discussion in thread for thoughts/comments.

https://github.com/filecoin-project/notary-governance/issues/392

**Comment by MasaakiNawatani** [comment]
Hi Kevin, thanks for the update. And yes, I am in favor of extending the review period if it will help in coming up with the right decisions that is fair for everyone in the Fil+ community.

**Comment by psh0691** [comment]
There are cases of illegal approval and abuse of DataCap due to collusion between Notary, SP, and Clients.
Applications for notaries by these institutions and individuals should be considered.

**Comment by dkkapur** [comment]
@galen-mcandrew posted comments and initial scores for all notary applications. Would be great for applicants to review and respond based on the timeline proposed above (by March 25).

**Comment by dkkapur** [comment]
@psh0691 do you have any specific examples that you can share? 

I do think that we've seen examples of this already and appropriate action needs to be taken. However, I think this is non-blocking for the elections, and can be reviewed on an ongoing basis, i.e., even if a bad-acting notary is re-elected, we can still file a dispute and work towards removing their status immediately afterwards.

**Comment by psh0691** [comment]
https://docs.google.com/document/d/1gYso-yIAw2oiiADiwsoQeaY9Lj-ntHqmUv3RcL7yNVk/edit?usp=sharing



2022년 3월 22일 (화) 오후 5:40, Deep Kapur ***@***.***>님이 작성:

**Comment by Kevin-FF-USA** [comment]
3rd Round of elections has now been closed and finalized.
