### ISSUE TITLE
Next Governance Call: Tues Apr 05 8am PT / 4pm UTC -and- 4pm PT / 12am UTC

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#484]
The seventh Notary Governance Call of 2022 will take place on April 5th at 8am PT // 4pm UTC AND 4pm PT // 12am UTC (April 6th depending on time zones)

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:
- Notary Election Results
- Fil Austin [(Save the Date)](https://fil.org/filaustin/)
- Community discussions

If you would like to add an item to the agenda, please comment in this issue.

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
(https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D

**Comment by Leviiee** [comment]
Hello Kevin, we also want to attend the meeting. Thank you!

**Comment by Leviiee** [comment]
Hello Kevin @Kevin-FF-USA , we also want to attend the meeting. Thank you!

**Comment by Kevin-FF-USA** [comment]
@Leviiee - great, these meetings are open to all.  Was there something specific you'd like to share or discuss on the call?

**Comment by Kevin-FF-USA** [comment]
Hi @TGShopping  - Will do.  I'll allocate you 5 minutes during the DISCUSSION portion.  If there is a deck you wish to present, please attach it here to this issue.

**Comment by scharfstein** [comment]
@Kevin-FF-USA 

Seal plans to attend the early call to discuss our proposal [https://github.com/filecoin-project/notary-governance/issues/489] with the community.

Gregg

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/issues/490

**Comment by Leviiee** [comment]
> @Leviiee - great, these meetings are open to all. Was there something specific you'd like to share or discuss on the call?

Yes! Create coach would like to share details about their application.

**Comment by Caraae** [comment]
Mooc will give a talk about the application. Can we attend the meeting? @Kevin-FF-USA

**Comment by TGShopping** [comment]
@Kevin-FF-USA  Thanks，The material is still being prepared. I will share my screen at the meeting.

**Comment by Mooc-1** [comment]
@Kevin-FF-USA Kevin, I want to attend the meeting on April 6th to give the talk about my issue.

**Comment by Leviiee** [comment]
> > @Leviiee - great, these meetings are open to all. Was there something specific you'd like to share or discuss on the call?
> 
> Yes! Create coach would like to share details about their application.

Hello Kevin. Create coach will share on April 6th.

**Comment by TGShopping** [comment]
Hi @dkkapur @Kevin-FF-USA @galen-mcandrew When could our application move forward?
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/303

**Comment by Leviiee** [comment]
> > > @Leviiee - great, these meetings are open to all. Was there something specific you'd like to share or discuss on the call?
> > 
> > 
> > Yes! Create coach would like to share details about their application.
> 
> Hello Kevin. Create coach will share on April 6th.

This is the issue of Create coach. https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/225 Please approve it! Thank you!

**Comment by Mooc-1** [comment]
Waiting for your approval! @dkkapur @Kevin-FF-USA @galen-mcandrew
Our issue https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/223

**Comment by Kevin-FF-USA** [comment]
Closing this issue out. Thank you to all who participated and presented. 
You can find the video of the recorded meetings here: https://www.youtube.com/watch?v=CymcRVh3o9k&list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx&index=1
