### ISSUE TITLE
Notary Application: Fenbushi Capital

### ISSUE THREAD

**Issue by Rin-huang** [filecoin-project/notary-governance#49]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Fenbushi Capital
- (Optional) Affiliated Organization: 
- Website / Social Media: https://fenbushi.vc
- On-chain Address(es) to be Notarized: f1ukiwt57z4ppt6odze7pvd7nihkxxuzwsde6qcty
- Region of Operation: Greater China
- Use case(s) to be supported: General
- DataCap Requested: 50PB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
1. In 2017, a couple of partners of Fenbushi Capital participated in Filecoin’s public sale on Coinlist.
2. Fenbushi Capital is the earliest and one of a few crypto-investors in China that have been investing and supporting Filecoin miners since the beginning of 2020.  We invested the equity interest of the top mining solution provider “1475 IPFS”, and are also in close discussions with a few major Chinese miners for potential equity investments.
3. Fenbushi Capital has been lending its Filecoin to a few .Chinese miners for mining.
4. Fenbushi Capital has committed 500,000 USD investments for the Singapore-based “Filecoin Frontier Accelerator” co-founded by Protocol Labs and LongHash Ventures (a portfolio company of Fenbushi Capital).  A couple of partners of Fenbushi Capital are taking active part in the foregoing accelerator as named mentors.
We do not own, whether directly or indirectly, any mining address and do not play the role of miner in the Filecoin ecosystem.  We only cooperate with miners in the form of Fil lending, equity investment (with minority stake below 10%) or similar transactions.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
As a token of our long-term commitment to Filecoin, we chose the longest vesting period (3 years) in our subscription in 2017. The details of Fenbushi Capital partners’ purchase in 2017 are all shown in the account on Coinlist.
As of December 7, 2020, only some 4.63% of the purchased FIL have been released and most of them are lent to various miners for staking.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
1. Fenbushi Capital is in the middle of setting up Fenbushi.IPFS Fund (the “Fund”), an investment fund dedicated to IPFS ecosystem projects, with target funding amount of 15M-20M USD (500K – 666K Fil worth).  Protocol Labs will be involved as the technical advisor to the Fund.  The Fund, as scheduled to launch in Q1 2021, will be raised and invest projects in FIL exclusively;
2. Fenbushi Capital promoted the collaboration between Protocol Labs and LongHash Ventures in terms of the “Filecoin Frontier Accelerator”;
3. A partner of Fenbushi Capital, Ms. Rin Huang, serves as the community reviewer of Slingshot;
4. The partners of Fenbushi Capital delivered speeches in several events related to Filecoin.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
None. 
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Fenbushi Capital, founded in 2015, is the first and most active blockchain-focused venture capital firm in Asia.  We have group companies registered in China, Singapore, the United States and a few tax-haven jurisdictions and maintain offices in Shanghai, New York, Atlanta and Singapore.
Our mission is to drive healthy and sustainable growth in the global Web 3.0 ecosystem, and aims to be a long-term strategic partner to its portfolio projects.  We actively seek to build synergistic partnerships across our broad portfolio, and leverage our deep roots in Asia to build a bridge between Asia and the global blockchain community.
o date, Fenbushi Capital has supported over 100 projects on six continents across our funds, investing across all layers of the tech stack from protocol to applications, and across various blockchains and use cases.   Approximately 70% of our portfolios are outside China, thanks to our extensive global reach.  Apart from Filecoin, our representative cases include Ethereum (the earliest backer in China), Polkadot (&Parity Inc.), Dfinity, Circle Finance, Sygnum Bank, Blockstack, BloxRoute, Sia, Status, Kyber, Omisego, Certik, Nucypher Celer, Dapper Labs and so on.  We are regularly named as one of the most active crypto investors by CBinsights.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Founders: Bo Shen, Xiao Feng and Vitalk Buterin
Website: www.fenbushi.vc
Twitter: Fenbushi
Linkedin: Fenbushi
Facebook: Fenbushi
Medium: fenbushi.medium.com
WeChat: 分布式资本.
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
We have more than forty articles related to Fenbushi Capital on The Block and about 32 articles on Coindesk.  Here are some examples:
1.Mapping out Fenbushi Capital's portfolio (https://www.theblockcrypto.com/genesis/20194/mapping-out-fenbushi-capitals-portfolio)
2.Mapping out investors in the crypto ecosystem (https://www.theblockcrypto.com/genesis/17915/mapping-out-the-investors-in-the-crypto-ecosystem)
3.Inside the Craze for Filecoin Crypto Mining in China (https://www.coindesk.com/filecoin-mining-craze-in-china)
Moreover, the followings are the billboards of blockchain investors where Fenbushi Capital was named as one of the most active investors:
1. Billboard of China-based investors
(https://www.cbinsights.com/research/china-blockchain-cryptocurrency-investment-trends/)
2.Billboard of investors worldwide
(https://www.cbinsights.com/research/bitcoin-blockchain-top-startup-investors/).
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We plan to explore and support the following use cases (in addition to garden-variety commercial data), which involve fast-growing open unclassified data and crave for low-cost storage according to our recent surveys:
1.Geographical and meteorological data;
2.Paperwork (writs, rulings, judgments and forensic evidences) and video records of judicial proceedings; and
3.E-copies of books, journals, magazines and files of public libraries and archives.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
The general strategy is to provide access to DataCap by types of Client and by stages, which means (i) different types of Client will be subject to respective on-boarding requirements and procedures to have access to DataCap; and (ii) the granted DataCap will be gradually available to the Client over time with a view to our continuing control of the Client’s proper spending.
1.  Allocation by Client Types
First of all, we will allocate the available DataCap by types (business entity vs. non-profit organization) and scores of the Clients who request such allocations (“applicants”).
It is envisaged that 70% of our available DataCap will be allocated to business entity applicants while the rest 30% will be set aside for non-profit organizations that serve the public welfare of the society, inter alia, public health, education and environmental protection. 
Accordingly, different requirements and procedures will apply to these two types of applicant:
1)Business Entity Applicants
Each business entity applicant will be rated by us in accordance with the following factors and criteria in order to be granted any amount of the DataCap:
```

Factors | Details | Rationale & Considerations | Rating Weight
-- | -- | -- | --
Business Model | 1. Product model <br>2. Data type and size <br>3. State of vertical Industries | To analyze how solid the upstream/downstream industries’ demands will be for the applicant’s product, and evaluate the potential size of overall data storage needed, and etc. | 30%
Operating Data | 1. Demographics of users <br>2. Users activity <br>3. Data usage | To know the current data size and user profiles of the applicant’s product and assess its growth velocity. | 50%
Technology | 1. Technological level of the applicant’s business / product <br>2. Technological synergies with IPFS/Filecoin | To assess applicant’s technological capability and resource, and analyze how its business/product would technologically synergize with or benefit from IPFS/Filecoin. | 10%
Track Record and Background | 1. Credential and track record of the applicant (and its top management). <br>2. Legal standing and history of the applicant as a business entity. <br>3. Branding and social reputation of the applicant | To ascertain the applicant’s <br>(i) experience in and dedication to its business; <br>(ii) legal compliance; and <br>(iii) reputation; furthermore, to verify the authenticity of the information provided by the applicant. | 10% (but If anything illegal or fraudulent is spotted, the applicant will be disqualified outright).

```
A business entity applicant who scores 60 or above will be allocated 0.1-10% of the total DataCap available to us.  Generally speaking, the higher score it gets, the more DataCap will be allocated, subject to the actual data size concerned.
2）Non-Profit Organization Applicants
Unlike a business entity applicant, a non-profit organization will not be rated as above to be on board for DataCap allocation.  Instead, a non-profit organization will be allocated 0.1-5% of our available DataCap (subject to the actual data size concerned) upon duly proving its legal standing and existing data.

2.Allocation by Stages
Furthermore, the DataCap for any applicant will only be allocated by stages (as opposed to in one batch). 
Usually only 20%-30% of the granted DataCap will be available to the relevant applicant in the first trial stage, whereupon we will keep monitoring how that applicant will spend the same to ensure its proper use. 
The applicant must meet the requirements pre-specified in our allocation decision to have the subsequent portions of the granted DataCap unlocked, which requirements are expected to include, inter alia, low concentration of miners and storage of approved data only.  Accordingly, failure to meet the aforementioned requirements will result in delay of allocation or even cancellation of the remaining DataCap.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
The process will basically be as follows:
1.Each applicant requesting DataCap is required to formally submit a written application (in pre-specified form) and other relevant supporting information to us for our review process to kick off;
2.A preliminary review of the foregoing application will be made by our internal “Notary Taskforce” to pre-qualify the applicant, who must be a serious and well-established business entity or non-profit organization having plausible data storage demands;
3.Each applicant failing the pre-qualification will be requested to provide additional information or be simply denied, as the case may be;
4.For the pre-qualified applicant, our “Notary Taskforce” will conduct a due diligence to scrutinize its legal standing, operations and data concerned;
5.Based on the due diligence result, a rating will be performed by us for each business entity applicant in accordance with the preceding factors and criteria, following which we will assign a score to that applicant.  Rating for non-profit organization applicants will be dispensed with; and
6.We will resolve, in the form of a written decision, the denial or grant of requested DataCap allocation and (if granted) the amount of DataCap allocated, taking into account the applicant’s score (for business entity only) and data size concerned, and will then implement the same. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will adopt cutting-edge third-party authentication solution in this verification process to ensure duly authorized allocation of DataCap, such as using multi-signature to control the allocation process.
To be specific, under the key management system that we currently envisage to adopt, private keys are disseminated into key shards by hardware security module (“HSM”), which isolates user CA and private keys.  Such key shards are then distributed among and respectively kept by delegated members of us (as a notary), and will have to be signed by such number of notary’s private key holders that meets the pre-designated threshold to prove the allocation decision.  All the records will be entered on the relevant blockchain to be transparent and traceable to the community and to prove the ‘verified deal’ between the DataCap applicant and us.
Regardless, we are open to other established mechanism and will keep exploring state-of-the-art solutions as long as we remain a notary.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
This includes both on-boarding due diligence of Client and post-allocation vetting.
1.Onboarding due diligence
First, we will collect KYC & onboarding documents to identify the client.  We may also employ a KYC Registry to consolidate all KYC data (may use third-party tooling), depending on the scale of the applications.
Typical KYC & onboarding documents are as follows (which may vary across different jurisdictions) the Client’s name, contact details, registration number, registration date, registration certificate, scope of business, members of board and senior management and beneficial ownership structure.
2.Post-allocation Vetting
The post-allocation vetting of Clients will be performed regularly and constantly to avoid the allocated DataCap being abused or misused.  The fundamental principle is that the Client is obliged to spend the DataCap exclusively for the approved uses (which will be specified in our allocation decision). 
To this end, at any time of the Client’s spending the DataCap, we may ask the Client to provide:
1)a consolidated Content Identifier (“CID”) list for verified deals that includes deal CID and miner ID (showing how the allocated DataCap has been used);
2)description of the data being stored and how the data has been processed; and
3)instructions on data retrieval.
Receiving the foregoing information, we will perform random-sample inspections on the verified deals sent out by the Client on chain by checking the deal CID and retrieve it from the corresponding miners to verify the data authenticity.
In addition to the foregoing, other monitoring measures such as public monitoring, auditing (we will elaborate more on Q3 in this section).
Since the DataCap will be allocated by stages, we may penalize the Client by delaying or even cancelling the outstanding DataCap if discovering any improper or fraudulent spending the allocated DataCap.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
We are going to ask the following basic questions initially:
1.Description of your major business as well as the type and size of the data you plan to store;
2.What do you know about FIlecoin network and what motivates you to choose it for your data storage;
3.What is your past practice on data storage;
4.Why do you apply for DataCap and what makes you think your data storage worth of spending DataCap;
5.Allocation among miners - who are the miners you plan to store the data with and the reasons (including allocation proportion with each miner);
6.Specific requirements for intended miners (e.g. redundancy, location, encryption requirements;
7.Any measures (technical or/and non-technical) to ensure proper allocation of DataCap;
8.Will you be cooperative to our ongoing inspections (and resulting disciplinary actions) on the verified deals that you may place to miners after DataCap allocation;
In addition to the above questions, we also note the client template proposed at (https://github.com/filecoin-project/notary-governance/blob/main/notaries/templates/sample-client-application.md), which covers areas in Client reputation, allocation strategy and track record and provides a good foundation that we may refer to for assessing prospective Clients.
We believe that the essence of the Client onboarding process is to conduct reasonably sufficient level of scrutiny without creating onerous burden to the Clients.  Therefore, instead of imposing a full but lengthy questionnaire in the first instance, we would like to make the process more interactive and pointed – we will come up with Client-specific questions based on the DataCap threshold requested and the answers provided by the very Client, doing it back and forth for a few rounds. 
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
1.First of all, the Client’s Filecoin address is required to be disclosed for us to closely monitor after the DataCap allocation.  Moreover, we will keep our eyes open on such Client’s storage orders placed from time to time (especially for verified deals) and relevant storage providers.
2.As set forth above, the granted DataCap will be available to the Client by stages.  So usually we can withhold the remaining DataCap from being allocated if the Client is found over-allocating its available DataCap to any single entity.
3.We will set up a Client rubrics mechanism that scores the Clients with varying trust.  Among others, the more diversified the Client allocates its granted DataCap, the higher scores the Client will get.  The Client may get bonus score if deploying less than 30% DataCap to any storage provider while it will suffer score deduction for deploying ≥70% Datacap to any storage miner for a period of time.
4.Penalties - if a Client gets a too low score in terms of diversification of storage providers, a warning will be issued and all the other notaries will be notified of the aforementioned “Over-Concentrated Allocation”.  Further punitive actions, such as cancellation of the remaining DataCap, may be taken in response to any Client’s persistent neglection of our warning.
5.Audits - both external and internal audits will be conducted throughout the data deployment process. The community members are encouraged to take part as the external auditor to expose any Client’s over-concentration on Datacap allocation. 
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Yes, we do plan to keep all the work records in relation to our allocation decisions.  Specifically:
1.The allocation guidelines and other supporting rules will be publicly available as soon as they are adopted, subject to updates from time to time.
2.Working paper, Client correspondences. supporting materials and decision reports that are generated or collected during our work, whether in electronic or physical copies, will be kept for at least 2 years.
3.We may maintain an internal database for storing the foregoing files and will grant authorized visitors access to the same whenever needed.
In most cases, our work records involve significant amount of Clients’ classified information that have not entered the public domain, for which we will usually be bound by certain confidentiality obligation, whether legally or contractually.  As a result, we can only accept private audits conducted by professionals (such as lawyers or accountants admitted in relevant jurisdictions) who are appointed through Filecoin community governance procedure.  Such an audit shall cover only such particular case as specified by the community governance and shall not expand to any other case or Client.  We will provide the auditors with full access to all the relevant files kept by us, provided that (i) such auditors shall be bound by the same level of confidentiality requirement; and (ii) certain data may be withheld until necessary prior permission of the relevant Client or governmental authority is obtained.
Besides, to the extent not to disclose any classified information of the Clients, we are glad to respond, in the designated venues of community governance, to such reasonable queries or interrogatories relating to our DataCap allocation decisions that may be raised by the community members from to time to time.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
It depends on the particular Client whether we are going to conduct our decision in public or private.  Some Clients are reluctant to be too much exposed and may require us to minimize publicity.  We are generally fine either way. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None. 
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
No.
```

**Comment by jnthnvctr** [comment]
Hi @Rin-huang - based on your submission, we've scored your application https://docs.google.com/spreadsheets/d/1-R_iAbPhB18K2Ux5ZSgS6yuRZDqVB5xhgAgxf5vp_c0/edit?usp=sharing

Eligibility score: 3
Unrounded score: 2.5

**Comment by jnthnvctr** [comment]
Hi @Rin-huang  - as mentioned on the governance call yesterday, your team was in the top of your region for being a prospective Notary! Prior to confirming your role as a Notary, there are a few items that need to be affirmed: 

1. Please acknowledge the region of operation in which you tend to primarily focus: [GCN]

2. Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.

* **Upfront Disclosures**: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship. 

* **Promoting Client Best Practices**: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found [here](https://github.com/filecoin-project/notary-governance/issues/9).

* **No Self Dealing**: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

* **Operating in good faith**: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

3. Please list any addresses you are affiliated with below - stating the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt. 

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above. 

5. (If ready) - Please confirm the address that should receive DataCap.

**Comment by jnthnvctr** [comment]
Additionally, if you plan on being listed in the Filecoin Plus Registry - please confirm what information you'd like to have displayed below. Please note that public requests currently write to a public repository (and we can work with you to configure the requests as needed). 

"name": "Your Name",
"use_case": [
    "List",
    "of",
    "Use Cases"
],
"location": "EUR",
"github_user": "notaryc",
(optional) "website": "google.com",
(optional) "max_datacap_allocation": "100 GB", // To indicate to clients what size allocations you might support. 
(optional) "private_request": "false",                       // set as true if you plan on supporting private requests. 
(optional) "email": "youremail@a.com",                 // only needed if you are supporting private requests
"info": ""                                                                            // You can use this to share information with Clients about your allocation strategy / reqs

**Comment by dkkapur** [comment]
@Rin-huang - when possible, can you please explicitly acknowledge and confirm the previous points raised by @jnthnvctr so we can proceed with confirming you as a Notary.

**Comment by Rin-huang** [comment]
OK. Apologies for the late reply. @jnthnvctr  @dkkapur dkkapur
I have some confusion about the region of notaries. "Asia-GCN" means Asia including China or Asia excluding China. Thanks.

**Comment by jnthnvctr** [comment]
Ah - Asia excluding GCN. In your application, I believe you'd put down GCN!

**Comment by Rin-huang** [comment]
OK. Thanks. Here is confirmed the points:

"name": "Fenbushi Capital",
"use_case": [General],
"location": "GCN",
"github_user": "Rin-huang",
(optional) "website": "https://fenbushi.vc",
(optional) "max_datacap_allocation": "50PB, for each client datacap is above 0.1% and below 10%", // To indicate to clients what size allocations you might support.
(optional) "private_request": "true", // set as true if you plan on supporting private requests.
(optional) "email": "r.huang@fenbushi.vc", // only needed if you are supporting private requests
"info": "The general strategy is to provide access to DataCap by types of Client and by stages, which means (i) different types of Client will be subject to respective on-boarding requirements and procedures to have access to DataCap; and (ii) the granted DataCap will be gradually available to the Client over time with a view to our continuing control of the Client’s proper spending.
1.  Allocation by Client Types
First of all, we will allocate the available DataCap by types (business entity vs. non-profit organization) and scores of the Clients who request such allocations (“applicants”).
It is envisaged that 70% of our available DataCap will be allocated to business entity applicants while the rest 30% will be set aside for non-profit organizations that serve the public welfare of the society, inter alia, public health, education and environmental protection. 
Accordingly, different requirements and procedures will apply to these two types of applicant:
1)Business Entity Applicants
Each business entity applicant will be rated by us in accordance with the following factors and criteria in order to be granted any amount of the DataCap:"

Factors | Details | Rationale & Considerations | Rating Weight
-- | -- | -- | --
Business Model | 1, Product model   2, Data type and size   3, State   of vertical Industries | To analyze   how solid the upstream/downstream industries’ demands will be for the applicant’s   product, and evaluate the potential size of overall data storage needed, and   etc. | 30%
Operating Data | 1, Demographics   of users   2, Users   activity   3, Data   usage | To know   the current data size and user profiles of the applicant’s product and assess   its growth velocity. | 50%
Technology | 1. Technological level   of the applicant’s business / product   2. Technological synergies   with IPFS/Filecoin | To assess   applicant’s technological capability and resource, and analyze how its   business/product would technologically synergize with or benefit from IPFS/Filecoin. | 10%
Track Record and Background | 1, Credential   and track record of the applicant (and its top management).   2, Legal   standing and history of the applicant as a business entity.   3. Branding   and social reputation of the applicant | To ascertain   the applicant’s (i) experience in and dedication to its business; (ii) legal   compliance; and (iii) reputation; furthermore, to verify the authenticity of   the information provided by the applicant. | 10% (but If   anything illegal or fraudulent is spotted, the applicant will be disqualified   outright).

"A business entity applicant who scores 60 or above will be allocated 0.1-10% of the total DataCap available to us.  Generally speaking, the higher score it gets, the more DataCap will be allocated, subject to the actual data size concerned.
2）Non-Profit Organization Applicants
Unlike a business entity applicant, a non-profit organization will not be rated as above to be on board for DataCap allocation.  Instead, a non-profit organization will be allocated 0.1-5% of our available DataCap (subject to the actual data size concerned) upon duly proving its legal standing and existing data.

2.Allocation by Stages
Furthermore, the DataCap for any applicant will only be allocated by stages (as opposed to in one batch). 
Usually only 20%-30% of the granted DataCap will be available to the relevant applicant in the first trial stage, whereupon we will keep monitoring how that applicant will spend the same to ensure its proper use. 
The applicant must meet the requirements pre-specified in our allocation decision to have the subsequent portions of the granted DataCap unlocked, which requirements are expected to include, inter alia, low concentration of miners and storage of approved data only.  Accordingly, failure to meet the aforementioned requirements will result in delay of allocation or even cancellation of the remaining DataCap." // You can use this to share information with Clients about your allocation strategy / reqs

**Comment by jnthnvctr** [comment]
Hi @Rin-huang - apologies for the lag here - would you be able to paste responses to each of these (you can just comment `Confirmed` under each paragraph): 

https://github.com/filecoin-project/notary-governance/issues/49#issuecomment-746442724 ? 

Also confirmation that this is the right address to approve: `f1ukiwt57z4ppt6odze7pvd7nihkxxuzwsde6qcty`

Reminder that if you're using the https://plus.fil.org app it currently supports ledgers - so confirm this is an address on a ledger!

**Comment by jnthnvctr** [comment]
Hi @Rin-huang  - just a bump here!

**Comment by Rin-huang** [comment]
> Hi @Rin-huang - as mentioned on the governance call yesterday, your team was in the top of your region for being a prospective Notary! Prior to confirming your role as a Notary, there are a few items that need to be affirmed:
> 
> 1. Please acknowledge the region of operation in which you tend to primarily focus: [GCN]
> 2. Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.
> 
> * **Upfront Disclosures**: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship.
> * **Promoting Client Best Practices**: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found [here](https://github.com/filecoin-project/notary-governance/issues/9).
> * **No Self Dealing**: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.
> * **Operating in good faith**: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.
> 
> 1. Please list any addresses you are affiliated with below - stating the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.
> 2. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.
> 3. (If ready) - Please confirm the address that should receive DataCap.

All confirmed. Thanks.

For the addresses you are affiliated with below: f1smam7vhb7houfntsl?????rlkt5d4n5z3emvq7q  [This is the address we receive FILs on Coinlist. We hope to keep the investment amount confidential, so five characters are hidden. Thanks for the understanding.]

Also confirmation that this is the right address to approve: f1ukiwt57z4ppt6odze7pvd7nihkxxuzwsde6qcty
Confirmed.

Apologies for the late reply and thanks for the patience.

**Comment by jnthnvctr** [comment]
Thank you for this!

## Request Approved
#### Address 
> f1ukiwt57z4ppt6odze7pvd7nihkxxuzwsde6qcty
#### Datacap Allocated
> 1PiB

**Comment by jnthnvctr** [comment]
hi @Rin-huang  per my message in slack can you confirm this address is correct? please ping me in slack if you have questions.

**Comment by Rin-huang** [comment]
> hi @Rin-huang per my message in slack can you confirm this address is correct? please ping me in slack if you have questions.

Hi @jnthnvctr , we have some problems while testing the ledger. We are dealing with them and will reply to you tomorrow. Thanks.

**Comment by Rin-huang** [comment]
Hi @jnthnvctr , we would like to change the notary address to: f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
Please reply to us when you get the message. Thanks.

**Comment by jnthnvctr** [comment]
## Request Approved
#### Address 
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### Datacap Allocated
> 1PiB

**Comment by jnthnvctr** [comment]
hi @Rin-huang - please note I've updated this

**Comment by Rin-huang** [comment]
Hi @jnthnvctr  Noted. Thanks.
