### ISSUE TITLE
Next Governance Call: Tues Apr 19 8am PT / 4pm UTC -and- 4pm PT / 12am UTC

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#492]
The eighth Notary Governance Call of 2022 will take place on April 19th at 8am PT // 4pm UTC AND 4pm PT // 12am UTC (April 20th depending on time zones)

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:

    Notary Onboarding
    More about Fil+ day in Austin [(Save the Date)](https://fil.org/filaustin/)
    Community discussions 
    Application Presentations

If you would like to add an item to the agenda, please request via a comment in this issue.
*Application presentation times will be allocated for 5minutes. If you would like to share your project you must have your request submitted in this issue at least 48hrs before the Governance meeting. Please provide a brief description of your presentation, link to your deck, and link to your application. 

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
(https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D

**Comment by TGShopping** [comment]
Hi @Kevin-FF-USA , When can we get the approval or some feedback from you after attending the last Governance Call?

**Comment by Kevin-FF-USA** [comment]
@megtei - Will be presenting a proposal for qualitative interviews   

[GC_FIL-E_proposalV0.1.pptx](https://github.com/filecoin-project/notary-governance/files/8491680/GC_FIL-E_proposalV0.1.pptx)

**Comment by Kevin-FF-USA** [comment]
> Hi @Kevin-FF-USA , When can we get the approval or some feedback from you after attending the last Governance Call?

Of course 
Please send me a DM in Slack and we can discuss. 
"Kevin-FF"
https://filecoinproject.slack.com/team/U02KQGP29S9

**Comment by galen-mcandrew** [comment]
Hello community! I will be on vacation during this call, so I cannot join live to discuss this topic. I went ahead and drafted some thoughts here: https://github.com/filecoin-project/notary-governance/issues/509

Summary: transition from many large dataset 'notaries' to a single multisig entity with all ratified notaries, that multisig would allocate out to all approved Large Dataset clients.

Looking forward to hearing what the community thinks about the problem, as well as my proposed solution. Thanks!

**Comment by stonechu108** [comment]
Hi Kevin，we'd like to attend the meeting and introduce our application([Common primitive universe](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/330)). I sorry for  the late message.

**Comment by liuwencheng9527** [comment]
Hi @Kevin-FF-USA , Can we attend the meeting and introduce our [application(Online education)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/301) in this meeting ?

**Comment by stonecopy** [comment]
Hi @Kevin-FF-USA ，we'd like to attend the meeting and introduce our application

**Comment by Edenwu777** [comment]
Hi @Kevin-FF-USA I want to demonstrate our Dapp (https://github.com/filecoin-project/notary-governance/issues/446)  DeFIL is a decentralized Filecoin lending and financial services platform

**Comment by Zhenshu-AI** [comment]
@Kevin-FF-USA Hi, we would like to attend the meeting and show our application. https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/332

**Comment by Kevin-FF-USA** [comment]
Hi @Zhenshu-AI @Edenwu777 @stonecopy @liuwencheng9527 @stonechu108 

Thanks for your interest in presenting.  Unfortunately the agenda for this meeting has already been finalized and I wont be able to review and get your presentations onto this meeting today.  For future reference, you will need to submit 48 hours in advance.

I'd be happy to allocate time during the next meeting on May 3rd for you.  Just need
1. Brief description of your presentation
2. Attached your slides in this (or May 3rd) Github issue
3. Link to your application

Looking forward to hearing from you.

**Comment by TGShopping** [comment]
Hi @Kevin-FF-USA , Any questions about https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/303?  We found the other applications have moved to the next step.

**Comment by stonecopy** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/324

**Comment by stonecopy** [comment]
@Kevin-FF-USA Hi, we would like to attend the meeting and show our application https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/324

**Comment by xinaxu** [comment]
@Kevin-FF-USA I'd like to present my application https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/335

**Comment by zhonghdadi** [comment]
Hi @Kevin-FF-USA , Can we attend the meeting and introduce our [application(ZhongHe Survey and Design)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/310)

**Comment by Kevin-FF-USA** [comment]
Link to Governance Calls: https://youtu.be/6z5kk6pPwhg
