### ISSUE TITLE
Notary Application : s0nik42/Twin Quasar

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/notary-governance#5]
To apply as a notary, please fill out the following form. 

## Core Information
- Name: Julien NOEL
- Website / Social Media: @s0nik42 on slack
- On-chain Address(es) to be Notarized: f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
- Region of Operation: I operate and I’m physically based in France / Europe
- Use case(s) to be supported: Any
- DataCap Requested: 100 TiB or any allocation that can be granted to my profile.

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
I’m an individual  fully engaged with  Filecoin for many years and I’m investing money and all my time in the Filecoin ecosystem.  I want to support Filecoin development and ecosystem as much as I can.
I've been using  IPFS for years, I joined filecoin community in Feb.
- Running miner : f010479
- Actively participating and Helping on slack(more than 10k messages)
- Developing a monitoring tool part of the Filecoin  dev grant program :  https://github.com/s0nik42/lotus-farcaster (currently Private until release one, ask and I will give you access. PL employee like @ribasushi have already access to it)
- Presenting for miner show and tell : https://www.youtube.com/watch?v=1JtQnhvxlVg
- Presenting for Celebration week : https://www.youtube.com/watch?v=cyer6_gSv78
- Participating to SR1 / SR2 Orbital burn / Slingshot 1 (project dCompute) / Apollo program
- Member of the dCompute project a Filecoin integration with Golem https://golem.network/) we’ve been contacted for Filecoin Frontier Accelerator (application ongoing)
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
1300 Fil (SR1 Rewards 1000) + (SR2 Pledge Colaterals) 
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- Actively participating and Helping the Filecoin miner community (more than 10k messages on slack)
- Developing a monitoring tool part of the Filecoin  dev grant program :  https://github.com/s0nik42/lotus-farcaster (Private until release one, ask and I will give you access)
- Presenting for miner show and tell : https://www.youtube.com/watch?v=1JtQnhvxlVg
- Presenting for Celebration week : https://www.youtube.com/watch?v=cyer6_gSv78
- Participating to SR1 / SR2 Orbitalburn / Slingshot 1 (project dCompute) / Apollo program
- Member of the dCompute project a Filecoin integration with Golem https://golem.network/) we’ve been contacted for Filecoin Frontier Accelerator
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
I identified a security bug on the faucet during SR2 not publicly disclose. Please liaise with @Why if you need more information.
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organisation, and time since inception.
```
I’m a Freelance.  I spent 17 years working for Tech companies with an expertise in Datacenters, Operating Systems, network and secuirty. My last position was Head of a Business Unit for a fortune 100 company.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
linkedin : https://www.linkedin.com/in/julien42/
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Please answer here.
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
I’m looking to help and support filecoin growth. Participating to this beta is my contribution to help defining Filecoin+ roles and processes attached to it. 
I will also envisage allocating time to this activity once the beta phase will be over. Maybe at that point, I will have a better understanding of the different cases and where I will have more value. For now, I’m happy to support any use cases.   
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
My apporach is similar to Philip’s : 

Defining thresholds with varying degrees of trust.
Higher the request, Higher the scrutiny

Several factors will be considered when making allocation decisions: 
Reputation of organization
Scale of allocation over a certain period of time
Security considerations
Transparency of Client
Client engagement to respect guidelines :
	- Process
	- Delegation
	- Contractual terms. 
	- etc…
Sucess of a Probation period for new client (described below)
```

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
I will develop internal tooling and process and expect to share them publicly.  I will be also open to test 3rd parties tooling part of the beta phase.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
I will be the only one accessing the key. It will be stored Offline
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
As this is all new for clients and notaries, my initial intend, is to start  by a probation  period for client without track record with a small amount of DataCap, ask them for evidence on how they allocate the DataCap before unlocking the rest of the dataCap. 
The main goals are to :
   -  ensure the client asks himself the right questions
   -  put the appropriate control and processes into place 
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
At first my plan  is to qualify clients from the GitHub template. Depending on the answers, I plan to ask more questions on "grey areas". By doing this, I expect to improve the set of questions over time and iterations. 
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Review at the end of  the probation period. If feasible random audit of customers.    
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
For transparency purpose, I plan to provide all the allocation decisions in public via a github repo. I will also agree to align the process the other notaries and the community; keeping in mind the processes we put in place have to be efficient. 
I will answer to any audits requests.  
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
For transparency purpose, I plan to provide all the allocation decisions in public via a github repo. I will also agree to align the process the other notaries and the community. 
Private allocation will need more tooling and tracking that are not here yet. Depending on the volume of such requests I may consider accepting private requests.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None
```

**Comment by jnthnvctr** [comment]
Hi - first, thank you for this application! We've taken a first pass at scoring your application using the rubric and left comments on the side: 

https://docs.google.com/spreadsheets/d/1bk61OBtg7LFSkd7Z4RyPdm-hN3Htu5OH6K4nTh4jxFY/edit?usp=sharing

I'd call attention to rows 11, 21, 22, and 23. 

Row 11: After discussion, we determined that this should be ranked as zero as written the rubric says registered organizations, and you're applying as an individual. However, it also seems clear that this is a limitation of the rubric, not a limitation of you as a prospective notary. We will work on a PR that we will share with the community (hopefully in time for the next governance call) to approve. 

Row 21: Allocation strategy, I think as with the FF this quite minimally specified in your application - though I think if after the Beta (or reviewing other applications) you can come up with a more fleshed out strategy we could improve the scoring here. 

Row 22: Same comment as 21 - I think this is exactly why we want to have the Beta, so there is a reasonable baseline that can be suggested for folks to work against. 

Row 23: Just a note (and may be your intention) - I scored this as a 3 assuming you plan on using the same format as the Filecoin Foundation. If you have a different plan in mind, please update your application such that we can ask questions to determine if a 3 is appropriate.

**Comment by jnthnvctr** [comment]
Hi, based on the new rubric - I've done a first scoring here: https://docs.google.com/spreadsheets/d/1zyNhLzLSNOiHuEPJV-BPI81xuM8nGmWpRwegpe4eJnM/edit?usp=sharing

Eligibility score: 1
Unrounded score (for tiebreaking): 1.3

**Comment by jnthnvctr** [comment]
Hi @s0nik42   - as mentioned on the governance call yesterday, your team was in the top of your region for being a prospective Notary! Prior to confirming your role as a Notary, there are a few items that need to be affirmed: 

1. Please acknowledge the region of operation in which you tend to primarily focus: [EUR]

2. Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.

* **Upfront Disclosures**: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship. 

* **Promoting Client Best Practices**: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found [here](https://github.com/filecoin-project/notary-governance/issues/9).

* **No Self Dealing**: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

* **Operating in good faith**: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

3. Please list any addresses you are affiliated with below - stating the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt. 

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above. 

5. (If ready) - Please confirm the address that should receive DataCap.

**Comment by jnthnvctr** [comment]
Additionally, if you plan on being listed in the Filecoin Plus Registry - please confirm what information you'd like to have displayed below. Please note that public requests currently write to a public repository (and we can work with you to configure the requests as needed). 

"name": "Your Name",
"use_case": [
    "List",
    "of",
    "Use Cases"
],
"location": "EUR",
"github_user": "notaryc",
(optional) "website": "google.com",
(optional) "max_datacap_allocation": "100 GB", // To indicate to clients what size allocations you might support. 
(optional) "private_request": "false",                       // set as true if you plan on supporting private requests. 
(optional) "email": "youremail@a.com",                 // only needed if you are supporting private requests
"info": ""                                                                            // You can use this to share information with Clients about your allocation strategy / reqs

**Comment by s0nik42** [comment]
Please acknowledge the region of operation in which you tend to primarily focus: [EUR]

YES

    Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.

    Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship.

Agreed

    Promoting Client Best Practices: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found here.

Agreed

    No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

Agreed

    Operating in good faith: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.

Agreed

    Please list any addresses you are affiliated with below - stating the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

f1wvaimrz3bmspcaz6isukgixth2sbbrw4dneonpy  (own miner address)
f3rpqqflz4bhyylporz3kjhejftvfs2gbjxv7gcw3imvviklmrqgee2jqsgp6hrl35ufckv76kdd245q352dtq   (own miner address)
f3ssplfnru6berbcj2mg6mjieb3idcht2wblmuyxrbemh5gsm5xopp3varhcfnxvnz2zurbvx5fdvgx4m6bzaa   (own miner address)
f3v3lj5jrsvv3nwmsvvj57yyty6ndb27oyi4yaqhwzst3emdv25hefna6vxhtpjb5pytwahdod67syxjyzba3q   (own miner address)
f3waqhsynu4a3w2a4mcwfaprd4fu6rgd3uuvt7mwj5v24br7u6vcb37xbvgbdgekaav3vcc3m6spz6etuh4aja    (own miner address)

    Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

I will
    (If ready) - Please confirm the address that should receive DataCap.

**Comment by jnthnvctr** [comment]
@s0nik42  to confirm this addresses is the one that DataCap should be allocated to: f1aj7ne6ljnnetkjbys645j2wrfzcvhpqlhg4zfwq ? 

(Also can follow up on Slack for the details for the Filecoin Plus registry as well)

**Comment by s0nik42** [comment]
Yes I updated my previous comment

**Comment by s0nik42** [comment]
Regarding the registry, I will prepare something by the end of the year

**Comment by jnthnvctr** [comment]
@s0nik42 - thanks for all the above. One last question (more logistic) - are you planning on using the same web app as the Filecoin Foundation? If you do, you'll want to make sure that f1a... address is actually on a Ledger (or you won't be able to sign from the app). 

You can still sign from your local set up (node) and use the Filecoin Plus Registry for inbound requests / github repo for iteration + pushing messages after you send DataCap, but just wanted to confirm you're set up properly!

**Comment by dkkapur** [comment]
@s0nik42 - quick ping on the above, let us know what your plan is for using the web app that the Foundation is using, and if you'd still like to wait on being listed on the Filecoin Plus Registry. Will accordingly take the final step in confirming you as a Notary. Thanks!

**Comment by s0nik42** [comment]
@dkkapur hello, I talked to Jonathan earlier this week, I'm waiting to get my ledger so I will have to confirm again the new f1. I will use the webapp. All of this should be done early next year. Is that good for you ?

**Comment by s0nik42** [comment]
@dkkapur I updated the adress in the first message with a ledger one : f16odmi46devwle357u6i4nsvzczxz42xiu3aiapy . Please let me know what is next.

**Comment by jnthnvctr** [comment]
## Request Approved
#### Address 
> f16odmi46devwle357u6i4nsvzczxz42xiu3aiapy
#### Datacap Allocated
> 10TiB

**Comment by jnthnvctr** [comment]
hi @s0nik42  - apologies, but can you please double check the address above before we send it DataCap?

**Comment by s0nik42** [comment]
the address is : f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
