### ISSUE TITLE
Notary Application: Performive

### ISSUE THREAD

**Issue by Broz221** [filecoin-project/notary-governance#50]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Performive
- (Optional) Affiliated Organization: 
- Website / Social Media: https://performive.com/
- On-chain Address(es) to be Notarized: f143inv7thba3qlgkizrsntlns6yryhfb5gz2btfq
- Region of Operation: North America, Greater China
- Use case(s) to be supported: General
- DataCap Requested: 1PB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Performive: A Pre-IPO company specializes in providing growing SMBs and mid-sized companies enterprise grade solutions scaled and priced right. For IPFS/Filecoin, we provide data center solutions for years. 
Affiliation with Filecoin started from 2015 in Seattle, while IPFS just gained some usage in the Ethereum and Filecoin was just an idea. When we expanded our business in Seattle, Y-Combinator brought us Protocol Labs, the Star from Summer 2014 Class. Although there has not been large IPFS/Filecoin communities in North America, we hold online/offline meetups. Most active members are Stratecore in Seattle, Datacenter.com in Denver, and Performive in Atlanta. 
Selected projects and contributions:
•	Meetup and knowledge sharing with Canadian Ethereum Mining Groups
•	Colocation and miner leasing services for miners across 16 countries and 6 continents
•	AMD CPU and GPU supply chain and logistics to Asia countries
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
I prefer not to disclose
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
In 2015, Juan and Jeromy (aka “whyrusleeping”/”Why”) introduced IPFS to us and a few other domain experts in our industry. It solves many problems of Centralized Storage such as high maintenance cost, unassured user privacy security, etc. With the belief of IPFS and later Filecoin as an incentive layer would eventually become something big, we started to involve in IPFS/Filecoin ecosystem, and to engage friends, partners, and clients into the communities.
What goes around comes around. We talked The Benaroya Family (owner of Benaroya Hall) into providing additional services and incentives to IPFS ecosystem companies at its data center in Seattle. Although not a money-making business at the beginning, it did bring them quite some mini-contracts and a few years later quite sizeable contracts from overseas during Filecoin Spacerace. Our Tampa partner, the largest Ethereum mining pool in the States, started to invest in Filecoin mining data center facilities right after we got them to Filecoin ICO. Not immediately, but their business finally started to boost since June. Our Brazil partner Maxihost.com, a cloud service provide in San Paulo, even received million dollar contracts from Filecoin miners after 3 years involvement of our IPFS/Filecoin communities.
As the “bridges” of global miners and clients, as well as other community members, Performive offers technical support and expertise of cloud service to the community.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
We don’t do much coding and we didn’t file any bugs. We did somewhat contribute during different stages of testnet. 20 locations were tested global for over 10 miners, including a couple of top miners on the leading board. 
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Performive, founded in 2005, is headquartered in Marietta, Georgia with 220 full-time employees spread over 20+ global locations. We specialize in providing growing SMBs and mid-sized companies enterprise grade solutions scaled and priced right. Performive delivers secure, hyperconverged solutions with world-class support and on-demand engineering assistance.
Performive received Series-B valuation of US$ 160 million, and aimed to file initial public offering (IPO) at Nasdaq Exchange as soon as the Q2, 2021.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: performive.com
LinkedIn: https://www.linkedin.com/company/performive/
Twitter: https://twitter.com/BePerformive
Gary Simat, CEO: https://www.linkedin.com/in/garysimat/
Ryan DiRocco, CTO: https://www.linkedin.com/in/ryan-dirocco-5453447/
Jason Brozena, VP and IPFS Product Leader: https://www.linkedin.com/in/jasonbrozena/
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Atlanta's fastest-growing private companies 3 year in a row:
https://markets.businessinsider.com/news/stocks/total-server-solutions-earns-pacesetter-award-listed-as-one-of-2020-s-top-100-fastest-growing-private-companies-in-atlanta-1029501713#

Inc. 5000 list of fastest-growing private companies 4 year in a row:
https://markets.financialcontent.com/ibtimes/news/read/40288126

Performive timeline: https://performive.com/about/
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Considering the principle of Filecoin, being a decentralized storage network designed to store humanity's most important information, we should encourage, instead of preventing; people to store any public and useful data for human society.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
Notary responsibilities as follow:
•	Allocate DataCap to clients in order to subsidize reliable and useful storage on the network.
•	Verify that clients receive a DataCap commensurate with the level of trust that is warranted based on information provided.
•	Ensure that in the allocation of the DataCap no party is given excessive trust in any form that might jeopardize the network.
•	Follow operational guidelines, keep record of decision flow, and respond to any requests for audits of their allocation decisions.
Notaries, on behalf of the network, on one hand bring in trustful Clients by allocating DataCap in order to subsidize storage from miners; on the other hand identify fraud or misuse of DataCap. We recently had a survey with 5 of the top miners and 15 other miners randomly from 4 continents. Miners value each TB of DataCap between $170 and $3,050, and many would compensate DataCap clients with 10-30% of that amount. 
Lesson and Learn from AWS: Incentives over $10,000 to SMB generates all sorts of fraudulent activities, especially from crypto miners. DataCap for any applicant will only be allocated by batch, and the granted DataCap will be gradually available to the Client over time with a view to our continuing control of the Client’s proper spending. The applicant must meet the requirements pre-specified in our allocation decision to have the subsequent portions of the granted DataCap unlocked, which requirements are expected to include, inter alia, low concentration of miners and storage of approved data only. Accordingly, failure to meet the aforementioned requirements will result in delay of allocation or even cancellation of the remaining DataCap.
For the time being, we would only take request of 100TB or under, until Notaries committee agrees the allocation strategy guidelines as a group for request >100TB.
Other than the list of factors (reputation, allocation, security, and transparency) Philipp pointed out, we are also interested in if the Clients know exactly what they are doing with clear expectation; instead of being lured onto github by miners. We would be more confident if the Clients already have the resources and even budget ready for storing at Filecoin network, regardless of the amount of DataCap being allocated. 
Furthermore, we try not to weight much on time/effort factors, but more on result-oriented factors, as either tenure or time spent in field is not much correlated with contribution or reputation. Some people prefer to give heavy weight to “Diversity and Decentralization” and looking to encourage Clients to store their data across multiple regions in multiple ways. It’s probably good for notaries being in different regions so that we better understand our Clients; for DataCap Clients, we would encourage them to do what’s best for them, as the purpose of DataCap is meant to getting Clients to the network easier, not the other way around.  
The following tool will be the primary guideline for DataCap allocation. Each applicant will be rated in accordance with the following factors and criteria. A sample Client, Protocol Labs, is scored at 3.4 for references.
https://docs.google.com/spreadsheets/d/1GUEgNkfZRrju-ihkdD5e7LxLMeDa2ahs6WsBU_FnJVI
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
I totally agree Philipp that public datasets, slingshot teams, and Web3 data are probably high trust; however, we are to evaluate clients instead of data itself. I would follow strictly with my allocation strategy, which 100% opens to the public at the moment. 
The process as follows:
•	Application submission in written with all supporting documents
•	Align application with the DataCap rating system tool for initial rating
•	Request additional information if needed
•	Due diligence/on line interview/reference check
•	Offline due diligence if needed
•	Generate final rating and amount of DataCap allocation
•	Final Decision in writing with detailed allocation plan for large DataCap allocation
Due Diligence process and result will also be public, upon agreement from Clients. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
At the moment, the  address that will be allocated DataCap will have it’s keys be secured on a hardware wallet. 
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
This includes both on-boarding due diligence and post-allocation vetting
1.	On-boarding due diligence
First, we will collect KYC & onboarding documents as follows to identify the client. We may also employ a KYC Registry to consolidate all KYC data (may use third-party tooling), depending on the scale of the applications.
•	Entity Information: Formation documents (this includes certificates of registration/incorporation/information); government-issued identification number 
•	Authorized Signatory Information: evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement) 
•	Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: Name, DOB, Address, IDs, etc. 
•	References: contract information of at least 2 people, e.g. executives, partners, or board members. 

2.	Post-allocation Vetting
Post-allocation Vetting is performed regularly and constantly to avoid the allocated DataCap being abused or misused. The fundamental principle is that the Client is obliged to spend the DataCap exclusively for the approved uses. 
To this end, at any time of the Client’s spending the DataCap, we may ask the Client to provide:
•	A consolidated Content Identifier (“CID”) list for verified deals that includes deal CID and miner ID (showing how the allocated DataCap has been used)
•	Description of the data being stored and how the data has been processed
•	Instructions on data retrieval
Receiving the foregoing information, we will perform random-sample inspections on the verified deals sent out by the Client on chain by checking the deal CID and retrieve it from the corresponding miners to verify the data authenticity.
Our DataCap allocation rating tool already gives a heavy weight on Clients being responsible for DataCap spending.
•	A Client either needs to have good knowledge in Filecoin network, or has clear expectation of spending the DataCap.
•	A Client needs to be fully prepared and has detailed plan on applying DataCap for the good of the organization.  
•	A DataCap subsidization and reliable storage identification strategy needs to be planned ahead with P/L analyzed.
We expect Clients being responsible to continuously receive DataCap in batchs. During the DataCap allocation growing stage, we would investigate and ensure that DataCap allocated to Clients do not exceed their actual data storage needs. We would trust Clients for small DataCap allocation and continuously monitor the usage. For large amount of DataCap allocation, we would consult external domain of experts, as well as schedule online/offline meetup with Clients.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
1. Could you introduce yourself and your organization? include links to social media / news mentions etc.
2. Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links).
3. How much do you know about Filecoin network and what motivates you to choose it for your data storage?
4. How much do you know about Filecoin DataCap and what’s your expectation from using your DataCap once approved?
5. Do you have resources and budget from your organization for your Filecoin data storage project?
6. Why do you apply for DataCap and what kind of your data storage worth of spending DataCap?
7. Do you plan to store more data than DataCap allocated? 
8. How much DataCap would you like to request?
9. What is your use case for the DataCap being requested? 
10. What is the Filecoin address you would like me to allocate the DataCap?
11. How long has your company been using cloud storage? How much do you store in cloud?
12. How much DataCap would you be requesting in future? What % would you expect to allocated from current cloud storage to Filecoin network?
13. What type and source of the data you are looking to store on Filecoin, e.g. public data vs private data etc.?
14. Would you be open to post transaction links to the public, once awarded data cap?
15. In which country/region do you intend to use the DataCap? If you intend to use the DataCap in multiple country/regions, please specify. 
16. Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners? If you have a specific miner(s) you would like to allocate a DataCap, please specify.
17. What’s your process for ensuring proper allocation of your DataCap?
18. Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals? If so, please specify the feature. 
19. How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
20. Will you be cooperative to our ongoing inspections on the verified deals that you may place to miners after DataCap allocation?
21. Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?
22. Have you been approved for a DataCap previously? If so, please link to any previous decisions that have been made, and the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 
23. Are there any disputes open against you from your previous DataCap allocations?
24. Have you ever previously violated 1. your own attested allocation / audit plan? 2. been found to be in violation of the Principles of Filecoin Plus?
We believe that the essence of the Client onboarding process is to conduct reasonably sufficient level of scrutiny without creating onerous burden to the Clients. Therefore, instead of imposing a full but lengthy questionnaire in the first instance, we would like to make the process more interactive and pointed – we will come up with Client-specific questions based on the DataCap threshold requested and the answers provided by the very Client, doing it back and forth for a few rounds.
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
The purpose is not to discourage Clients find and work with the best reliable and useful storage. Processes we employ as follows is to identify the “improper” activities.
•	Clients’ Filecoin addresses will be closely monitored immediately after DataCap allocation
•	Client’s storage orders, verified deals, and relevant storage providers will be Periodically inspected 
•	Single-miner allocation to be flag out and investigated; multi-miner allocation might be still to a single entity behind those miners, and the investigation will be conducted as well.
•	Post-allocation due diligence with Clients to understand the logic behind with the purpose of helping Client achieve what’s best for their data storage needs.
•	As DataCap is granted in batches, we could withhold the remaining DataCap anytime we identify the “improper” over-allocating activities, and further disqualify the client for next DataCap allocation.
•	Audits will be conducted throughout the data deployment process, internally and externally. Community members are encouraged to take part as the external auditor to expose any Client’s “improper” activities on Datacap allocation.
I would expect an automated fraud detection tool to closely monitor all Clients’ activities to report any “improper” behavior real-timely. We recently had an interview survey with 5 of the top miners on the leader board; a couple of them already have the tool under developed and very likely make it available for communities. 
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Yes, we do plan to keep all the work records in relation to our allocation decisions.  
Specifically:
1.	All allocation decisions will happen in public in the following [repository](https://github.com/keyko-io/filecoin-notaries-onboarding) - all communications will also take place through the repository and the issue tracking. 
2.	The allocation guidelines and other supporting rules will be publicly available as soon as they are adopted, subject to updates from time to time.
3.	Working paper, Client correspondences, supporting materials and decision reports that are generated or collected during our work, whether in electronic or physical copies, will be kept for at least 2 years.
4.	We may maintain an internal database for storing the foregoing files and will grant authorized visitors access to the same whenever needed.
5.	Any challenges raised regarding allocation decisions should be discussed publicly in the Github repo first, unless confidentiality issues then we keep in our internal database.
In most cases, our work records involve significant amount of Clients’ classified information that have not entered the public domain, for which we will usually be bound by certain confidentiality obligation, whether legally or contractually. As a result, we can only accept private audits conducted by professionals (such as lawyers or accountants admitted in relevant jurisdictions) appointed through Filecoin community governance procedure. Such an audit shall cover only such particular case as specified by the community governance and shall not expand to any other case or Client. We will provide the auditors with full access to all the relevant files kept by us, provided that such auditors shall be bound by the same level of confidentiality requirement and certain data may be withheld until necessary prior permission of the relevant Client or governmental authority is obtained.
Besides, to the extent not to disclose any classified information of the Clients, we are glad to respond, in the designated venues of community governance, to such reasonable queries or interrogatories relating to our DataCap allocation decisions that may be raised by the community members from to time to time.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
At the moment, All allocation decisions will happen in public in the following [repository](https://github.com/keyko-io/filecoin-notaries-onboarding) for transparency purpose. Long-termly, some Clients might be reluctant to be too much exposed and may require us to minimize publicity. We could conduct our decisions privately for such Clients.  
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
No
```

**Comment by jnthnvctr** [comment]
Hi @Broz221 - we have a few questions to follow up on your application. Do you have an email or a contact person we can reach? 

I've pinged your IPFS Product Lead on linkedin - (you can also reach out to me @jnthnvctr on the filecoin slack).

**Comment by brucexie99** [comment]
> Hi @Broz221 - we have a few questions to follow up on your application. Do you have an email or a contact person we can reach?
> 
> I've pinged your IPFS Product Lead on linkedin - (you can also reach out to me @jnthnvctr on the filecoin slack).

Feel free to reach me at jason.brozena@performive.com or brozenajason@gmail.com for IPFS/Filecoin notary and DataCap related issues

**Comment by Broz221** [comment]
Thanks, Bruce/Lei.

Yes, feel free to reach us at jason.brozena@performive.com or
brozenajason@gmail.com.

**Comment by Broz221** [comment]
Region of Operation: added Greater China

One resourceful notary applicant, and our long term trustful business partner, reached out to us and offered online/offline due diligence support for Greater China region, specifically, China mainland. We are now confident to take DataCap request from mainland China.

**Comment by jnthnvctr** [comment]
Hi @Broz221 based on your submission, we've ranked your application here: https://docs.google.com/spreadsheets/d/1pQ5MW8YEbC9hTEiSySiNlfvlHq55TUkXnRV8U8MslWo/edit#gid=327015220

Eligibility score: 2
Unrounded score: 1.6

**Comment by jnthnvctr** [comment]
Hi @Broz221 - as mentioned on the governance call yesterday, your team was in the top of your region for being a prospective Notary! Prior to confirming your role as a Notary, there are a few items that need to be affirmed: 

1. Please acknowledge the region of operation in which you tend to primarily focus: [NA]

2. Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.

* **Upfront Disclosures**: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship. 

* **Promoting Client Best Practices**: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found [here](https://github.com/filecoin-project/notary-governance/issues/9).

* **No Self Dealing**: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

* **Operating in good faith**: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

3. Please list any addresses you are affiliated with below - stating the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt. 

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above. 

5. (If ready) - Please confirm the address that should receive DataCap.

**Comment by jnthnvctr** [comment]
Additionally, since you've indicated you plan on being listed in the Filecoin Plus Registry (and associated repository) - please confirm what information you'd like to have displayed here: 

"name": "Your Name",
"use_case": [
    "List",
    "of",
    "Use Cases"
],
"location": "EUR",
"github_user": "notaryc",
(optional) "website": "google.com",
(optional) "max_datacap_allocation": "100 GB", // To indicate to clients what size allocations you might support. 
(optional) "private_request": "false",                       // leave as true if you plan on supporting private requests. 
(optional) "email": "youremail@a.com",                 // only needed if you are supporting private requests
"info": ""                                                                            // You can use this to share information with Clients about your allocation strategy / reqs

**Comment by Broz221** [comment]
> Hi @Broz221 - as mentioned on the governance call yesterday, your team was in the top of your region for being a prospective Notary! Prior to confirming your role as a Notary, there are a few items that need to be affirmed:
> 
> 1. Please acknowledge the region of operation in which you tend to primarily focus: [NA] 
North America

> 2. Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.
> 
> * **Upfront Disclosures**: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship.
Confirmed

> * **Promoting Client Best Practices**: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found [here](https://github.com/filecoin-project/notary-governance/issues/9).
Confirmed

> * **No Self Dealing**: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.
Confirmed

> * **Operating in good faith**: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.
Confirmed

> 
> 1. Please list any addresses you are affiliated with below - stating the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.
We are not affiliated, and we do not control, or have a financial stake in, or are strongly connected to any address at the moment. We will disclose all addresses if and whenever we are in the future.

> 2. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.
Yes, we will.

> 3. (If ready) - Please confirm the address that should receive DataCap.
f143inv7thba3qlgkizrsntlns6yryhfb5gz2btfq

**Comment by jnthnvctr** [comment]
Thanks for the above @Broz221 ! If in the future there are other relevant miner IDs to disclose, please just add them as comments on this issue stating the on-chain ID and nature of the relationship. It doesn't necessarily need to be just the miner IDs, really any ID where there might be a potential for a conflict of interest.

And to confirm - in you app you mentioned using a hardware wallet, are you planning on using the same tooling as the Filecoin Foundation for the actual signing of transactions (https://filecoinplus.on.fleek.co/wallet)? 

If so, just be aware the only hardware wallet that this app supports for signing is a Ledger.

You do not need to use a Ledger to list yourself on the Registry section or to process applications in the Github repo, just for the signing portion (if you intend to use it to manage the signing). 

If all that sounds fine, I can mark this ready for allocation.

**Comment by Broz221** [comment]
> Thanks for the above @Broz221 ! If in the future there are other relevant miner IDs to disclose, please just add them as comments on this issue stating the on-chain ID and nature of the relationship. It doesn't necessarily need to be just the miner IDs, really any ID where there might be a potential for a conflict of interest.
> 
> And to confirm - in you app you mentioned using a hardware wallet, are you planning on using the same tooling as the Filecoin Foundation for the actual signing of transactions (https://filecoinplus.on.fleek.co/wallet)?
Yes. Confirmed
> 
> If so, just be aware the only hardware wallet that this app supports for signing is a Ledger.
Thanks. We have a Ledger for signing in.
> 
> You do not need to use a Ledger to list yourself on the Registry section or to process applications in the Github repo, just for the signing portion (if you intend to use it to manage the signing).
> 
> If all that sounds fine, I can mark this ready for allocation.

Information to Display:
"name": "Jason Brozena / Performive",
"use_case": [
"Open datasets that serve as a foundation for humanities most important information",
"data affiliated with strategic growth initiatives of the Filecoin project",
"data from centralized cloud storage clients looking to switch to Filecoin network"
],
"location": "NA",
"github_user": "Broz221",

**Comment by dkkapur** [comment]
## Request Approved
#### Address 
> f143inv7thba3qlgkizrsntlns6yryhfb5gz2btfq
#### Datacap Allocated
> 100TiB

**Comment by jnthnvctr** [comment]
hi @Broz221  per my message in slack can you confirm this address is correct? please ping me in slack if you have questions.

**Comment by Broz221** [comment]
> hi @Broz221 per my message in slack can you confirm this address is correct? please ping me in slack if you have questions.

Got a new ledger. Here we go with the confirmed address: f13vzzb65gr7pjmb2vsfq666epq6lhdbanc4vfopq

**Comment by jnthnvctr** [comment]
## Request Approved
#### Address 
> f13vzzb65gr7pjmb2vsfq666epq6lhdbanc4vfopq
#### Datacap Allocated
> 100TiB
