### ISSUE TITLE
Next Governance Call: Tues May 3 8am PT / 4pm UTC -and- 4pm PT / 12am UTC 

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#513]
The ninth Notary Governance Call of 2022 will take place on May 3rd at 8am PT // 4pm UTC AND 4pm PT // 12am UTC (May4th depending on time zones)

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:

Notary Onboarding Cont. FAQ
Presentation Solicitations for Fil+ (June 7)
Community discussions 
Application Presentations

If you would like to add an item to the agenda, please request via a comment in this issue.
***Application presentation times will be allocated for 5minutes. If you would like to share your project you must have your request submitted in this issue at least 48hrs before the Governance meeting.** 
Please provide a brief description of your presentation, link to your slides, and link to your application.

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
(https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D

**Comment by zhonghdadi** [comment]
Hi @Kevin-FF-USA ,  ZhongHe Survey and Design Co., Ltd. has always been committed to the large-scale application of environmental Internet of Things, agricultural intelligent hardware research and development and agricultural big data analysis, providing technical and data support services for scientific planting, food safety traceability, and agricultural brand building. For more details, please see our slides([ZhongHe Survey and Design.pptx](https://docs.google.com/presentation/d/1I2q1tEkvkfGrcVUpoW_FS9iBPPX49ewl/edit?usp=sharing&ouid=111672845528063224174&rtpof=true&sd=true)) and our application([ZhongHe](http://www.dadikancha.cn/) ).  Can we attend the meeting and introduce our https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/310in this meeting ?

**Comment by Lei-MOLeMART** [comment]
@Kevin-FF-USA I want to do attend the meeting. I will do a presentation about my application---MOLeMART.
Hope to have the chance!

**Comment by stonechu108** [comment]
Hi Kevin，we'd like to attend the meeting and introduce our application(https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/330). [ppt](https://docs.google.com/presentation/d/1m4cwNY_PyTVqw8m2MCIo9jLSJRmkPqx-qvwoGWCksMY/edit#slide=id.p3)

**Comment by liuwencheng9527** [comment]
we'd like to attend the meeting and introduce our application(https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/301). [share ppt](https://docs.google.com/presentation/d/15t4lDLj2Zlom44ymgsY-ReL4K-fePZ9P0mLk6I5OOWU/edit?usp=sharing)

**Comment by Zhenshu-AI** [comment]
@Kevin-FF-USA Hi, we would like to attend the meeting and show our application. https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/332 I'll dm you the slide via slack.

**Comment by stonecopy** [comment]
@Kevin-FF-USA Hi, we would like to attend the meeting and show our application. https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/324

**Comment by Kevin-FF-USA** [comment]
Hi @stonecopy, @Zhenshu-AI @liuwencheng9527 @stonechu108 @MOLeMART @xinaxu @zhonghdadi.  

Have you all confirmed for (5) minutes to present in the upcoming Notary Meeting.  To ensure we can incorporate your slides into the main presentation - PLEASE 
1. ATTACH YOUR SLIDE PRESENTATION TO THIS GITHUB ISSUE.  
2. PROVIDE A BRIEF SUMMARY OF YOUR DISCUSSION

(In the same general format used by @zhonghdadi )

**Comment by MegTei** [comment]
HI @Kevin-FF-USA Can you line me up for a discussion slot at the NEXT governance call 18-May pls

**Comment by stonecopy** [comment]
As there is not enough time to present, I have recorded the video and put it on YouTube（ https://www.youtube.com/watch?v=OhQykyr3_CY）. Please feel free to communicate if necessary.  https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/324 @Kevin-FF-USA @galen-mcandrew @dkkapur

**Comment by Kevin-FF-USA** [comment]
Thank you.
Here is the link to both meetings for the May 3rd Notary Governance Call - https://youtu.be/OrQSxvP16uY

The slide deck can be found here - https://docs.google.com/presentation/d/1XTpssUBRkCxusxELyhhfzadQkYiOQ9BiYsUMKWnUK0E/edit?usp=sharing

**Comment by stonecopy** [comment]
I have submitted a  video on YouTube（https://www.youtube.com/watch?v=OhQykyr3_CY), do you have any questions? I see that other posts in the same batch have been successfully approved. Is there anything we need to add? https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/324
