### ISSUE TITLE
Proposal: MOLeMART-50PiB DataCap

### ISSUE THREAD

**Issue by MOLeMART** [filecoin-project/notary-governance#514]
We've opened an issue for storage of approximately 11PiB data which needs 5 copies. That's total 50PiB DataCap. For further discussion, we'd like to attend the meeting to show details about our item on Tuesday, May 3, 2022.

Project Description

We are an E-commerce Platform with Real-time Big Data Analytics Engine to provide smart choice for our clients.
We have: 60,000+ Suppliers; 50,000,000 Products; 1000+ Variables.
Currently, we have over 2,000 servers distributed across 4 data centers. Although MOLeMART carries 160 million chemical compounds, 50 million compounds cover 99% of demands, and 1 million compounds cover 90% of demands. 
We’ve been looking for a storage place to reduce the cost for our less demanded chemical products, e.g. Those data will be retrieval less than once per year.  So we focus on Filecoin and want to find a solution for storage. (History data)

Dateset

We store our AI dataset like pictures, videos from our websites and compounds' information, and suppliers' information.(DB and server images) 
In addition, we store over 400 attributes of compounds, such as synthetic routes, chemical structures, MSDS (Material Safety Data Sheet), etc. This is our enterprise data, we don't want to share them with others.

KYC Policy

We'd like to invite 5 notaries to have a 5-10mins call about sharing who we are and what's our data.

DataCap Application

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/336

**Comment by Kevin-FF-USA** [comment]
Hi @MOLeMART  
Have time set aside for discussion of this issue during the May 3rd Notary Governance Call.  I'm going to close this duplicative ticket, but should you need anything else with this issue please let us know.

**Comment by MOLeMART** [comment]
Hi @galen-mcandrew @dkkapur @Kevin-FF-USA 
I noticed that other applications discussed in the same period have go through to the next stage, but my application is still there. May I know why?

I can make the presentation again on the next call or launch a seprate call with you all.

**Comment by dkkapur** [comment]
@MOLeMART thanks for checking on this! As far as we are aware, the next step here is for you to get 5 notaries on board that support your application. In line with the precedence set here #489 you should identify 5 notaries from at least 3 regions to support you and do the needful KYC. You are welcome to use the governance call chat for this or request more time from @Kevin-FF-USA at the call itself. Else - I would recommend using #fil-plus-application-review channel in Filecoin Slack. 


Can we get additional clarification here?
>This is our enterprise data, we don't want to share them with others. 
Does this mean that the data is encrypted but can be stored with other SP orgs?
Does this mean the data can only be stored by you? If so - this is does not fit under the current Fil+ guidelines of distributing replicas to other SPs.

**Comment by MOLeMART** [comment]
@dkkapur Yes, you are right. This is my enterprise data, so we will encrypt data before uploading it to the Filecoin. We welcome SPs to store it for copies.

**Comment by MOLeMART** [comment]
> @dkkapur Yes, you are right. This is my enterprise data, so we will encrypt data before uploading it to the Filecoin. We welcome SPs to store it for copies.
> 
> I'd like to have a zoom call with you to introduce my project. When will you be available this week?

@dkkapur When can we confirm the time of zoom call?

**Comment by dkkapur** [comment]
@MOLeMART if the zoom call is to introduce us to the project, I think it would be better to do that at the next governance call to share with the community!

**Comment by dkkapur** [comment]
Which are the SPs you have identified so far for this?

**Comment by MOLeMART** [comment]
@dkkapur Yes, last time I presented my issue at previous Notary Meeting, but I thought that 5 minutes was too short to show all parts about my company. The purpose of the meeting I want to invite you is to let the community know more about my project and get community support. 

There are SPs f0734759, f01830428, f01844135, f01845667, f01851465 that we are currently cooperating with. In the future, we'll find 10-15 SPs for cooperation. And we certainly welcome more SPs from Filecoin community to accept our deals!

**Comment by MOLeMART** [comment]
@MegTei @DarnellWashington @MRJAVAZHAO @wjywood @swatchliu @neogeweb3 @steven004 @ozhtdong @Fenbushi-Filecoin @cryptowhizzard @Reiers @s0nik42 @dannyob @MasaakiNawatani @rayshitou @IreneYoung @TimWilliams00 @XnMatrixSV @IPFSUnion

Hi notaries, can you help support my application? We are an E-commerce Platform with Real-time Big Data Analytics Engine to provide smart choice for our clients. Hope we can get your support!

My issue: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/336

Thank you all!

**Comment by MOLeMART** [comment]
Hi @Kevin-FF-USA ,
May I take 10-15 mins in next governance call (Tues June 14)?
I'd like to let every notary know my issue in detail. I've communicated with some notaries and waited for their responses several days ago. I hope that I can answer questions about my application from notaries via this meeting.

**Comment by Kevin-FF-USA** [comment]
Evening @MOLeMART,
Appreciate your request for time, there just isn't bandwidth in the schedule for a single application review of that length.  

A significant reason for the processing times see was due in part to the recent Notary election and onboarding. In the upcoming June 14th call all Notaries will receive the prepared videos of projects for discussion.  
Did you prepare one? 

![image](https://user-images.githubusercontent.com/94004586/173480753-0355bc69-d5a8-4af5-aeb1-553582661054.png)

**Comment by raghavrmadya** [comment]
Forwarded to E Fil+ WG. Please coordinate KZ.  Closing for now and please let us know if you are blocked on anything.

**Comment by kevzak** [comment]
@MOLeMART is this a project you want to onboard? It may be eligible for E-Fil+ pilot, we have some SPs that could support you @trevor-k-smith FYI
