### ISSUE TITLE
Next Governance Call: Tues May 17 8am PT / 4pm UTC -and- 4pm PT / 12am UTC

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#518]
The tenth Notary Governance Call of 2022 will take place on May 17rd at 8am PT // 4pm UTC AND 4pm PT // 12am UTC (May18th depending on time zones)

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:

Notary Onboarding Cont review and FAQ
Fil+ (June 7) Schedule outline
Community discussions
Application Presentations

If you would like to add an item to the agenda, please request via a comment in this issue.
*Application presentation times will be allocated for 5minutes. If you would like to share your project you must have your request submitted in this issue at least 48hrs before the Governance meeting.
Please provide a brief description of your presentation, link to your slides, and link to your application.

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
(https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D

**Comment by Kevin-FF-USA** [comment]
Allocating 15minutes for Notary Training and Q&A following the recent Onboarding Trainings.

**Comment by MegTei** [comment]
HI @Kevin-FF-USA can I have a 5 min slot to present the outline of the Enterprise proposal with a 5 min Q&A pls.

**Comment by stonecopy** [comment]
Curious that most of the other issues in the same governance call have moved forward to the next round.  Is there anything we need to provide after uploading our presentation video on YourTube （https://www.youtube.com/watch?v=OhQykyr3_CY). Could you help to review our issue as: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/324  Thanks a lot! @Kevin-FF-USA

**Comment by Fibo-AI** [comment]
Kevin, can I attend this meeting?https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349
[FIboAI.pptx](https://github.com/filecoin-project/notary-governance/files/8688999/FIboAI.pptx)FiboAI is committed to the research and application of artificial intelligence technology.

**Comment by Pangodbj** [comment]
Pangod would like to attend the meeting and briefly introduce our business and dataset. Please help arrange it. Thank you very much @Kevin-FF-USA 
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/347

**Comment by HolaSpace** [comment]
I apply to give an introduction about my issue https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362
Please give me the chance! Thanks! @Kevin-FF-USA

**Comment by Kevin-FF-USA** [comment]
Hello @Pangodbj + @Fibo-AI  @Aitester66 @NFT-SCAN,

To ensure there is time in the meeting to discuss open issues for the Notaries and clients, requesting you provide the following updates to your requests in this issue in order to receive live time in the meeting.

1. Attach to this issue the slides you would like to present in the meeting
2. In comment to this issue - Provide a brief summary of 
- Why you would like to present your application.  (this should be something additional to your application that explains the need of the data and why it is important to the network)
- How long your application has been open
- What are you hoping to get from the Notaries and Fil+ community.

Will need this by 0700UTC Sunday.  If not received by then, encourage you to share your project a-sync in the [Fil-plus-application-review](https://filecoinproject.slack.com/archives/C036JKD8NVA
) channel on Slack

**Comment by vetetable360** [comment]
Hi @Kevin-FF-USA , could you give me a chance to present my application([#309](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/309)) at this meeting？Vetetable.com, also known as Plant Elements, was founded in 2019. It was initiated by 5 professors and 12 scholars from Agricultural University, and a plant science website jointly built by several plant enthusiasts from all over the country. Preserve originals and copies of botanical photographs, negatives, slides, digital image source files, and other botanical-related images. Nearly 10,000 original pictures of plants, pictures of wild plants such as ferns, and 100,000 digital photos have been collected, which have produced a significant effect of building a library in scientific research, popular science education, book publishing, and economic and social services. The website aims to promote plant science, popularize plant knowledge, and let more people understand the habits and characteristics of different plants, so as to achieve peaceful coexistence between humans and nature, and make the earth full of green and oxygen. If you want to know more, you can see our slide([#Plant Elements.ppt](https://docs.google.com/presentation/d/1d4vgr-o4znDOnspgTfFtocxSquv4DDfLM8CYwSTiLL8/edit?usp=sharing)).

**Comment by filtakes** [comment]
Hi @Kevin-FF-USA  Hi Kevin, could you give me a chance to present my application([#363](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/363)) at this meeting？This is my slides([filtakes.ppt](https://docs.google.com/presentation/d/14lKuGXPw2KnpDihKepoo4YK4u4yyFnSEjxkPvRzPIt8/edit?usp=sharing))

**Comment by MOLeMART** [comment]
@Kevin-FF-USA , is there any information we need to provide for our issue?https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/336 Because I haven't seen any progress about my issue after last governance meeting. Please help me check it. Thank you.

**Comment by huangqian2021** [comment]
@Kevin-FF-USA , can I attend this meeting?https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/323

Blue Storm is committed to promoting the sustainable development of society through professional and technological innovation.

1.Why you would like to present your application.
We have extensive amount of data looking to store with cost-efficient providers. We decided to store with Filecoin our public data and would be willing to take this opportunity to share our thoughts and concerns with Filecoin team. Hopefully, we could start from here and partner with Filecoin in long run, especially our private data, which counts 80% of our yearly storage cost at centralized storage service providers. .
2.How long your application has been open
We submitted the application on 7th April.
3.What are you hoping to get from the Notaries and Fil+ community.
Suggestions and hopefully support to help us benefit from filecoin’s cost-efficient storage service in long term. In return, we will allocate quality time and efforts to support Filecoin community if possible.

**Comment by huangqian2021** [comment]
@Kevin-FF-USA can I attend this meeting?https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/323
[BlueStorm Inf.1.pptx](https://github.com/filecoin-project/notary-governance/files/8705760/BlueStorm.Inf.1.pptx)

Blue Storm is committed to promoting the sustainable development of society through professional and technological innovation.

1.Why you would like to present your application.
We have extensive amount of data looking to store with cost-efficient providers. We decided to store with Filecoin our public data and would be willing to take this opportunity to share our thoughts and concerns with Filecoin team. Hopefully, we could start from here and partner with Filecoin in long run, especially our private data, which counts 80% of our yearly storage cost at centralized storage service providers. .
2.How long your application has been open
We submitted the application on 7th April.
3.What are you hoping to get from the Notaries and Fil+ community.
Suggestions and hopefully support to help us benefit from filecoin’s cost-efficient storage service in long term. In return, we will allocate quality time and efforts to support Filecoin community if possible.

**Comment by vetetable360** [comment]
Hi, @galen-mcandrew @dkkapur 

1. We have prepared slides for the Governance Call on 5.17, but unfortunately the time is too short, and we have not had the opportunity to give a speech. For this reason, we specially recorded[ a video](https://drive.google.com/file/d/17WewJi_1qcE3iebUHPdMUMd0UHV1u9Ci/view?usp=sharing), hoping that notaries will have a better understanding of our application. Our vast amounts of data are stored on traditional cloud storage servers. Hope to get more support and help through the application ([big application link](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/309)) of filecoin.
2. We have passed the Fil+ client on-boarding and DataCap applications ( [application](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1684)) on April 22, and have been successfully allocated to 6 SPs in the form of online and offline orders within two weeks.

Could you process our application  to the next stage? If you need  more information, we are glad to provide it.
