### ISSUE TITLE
Alyale - Rommel

### ISSUE THREAD

**Issue by melgalvez** [filecoin-project/notary-governance#52]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Rommel Galvez
- (Optional) Affiliated Organization: Alyale Philippines, Inc.
- Website / Social Media: www.alyale.com
- On-chain Address(es) to be Notarized: f3qqhbwhgorbtymzhq5wxnointwl4tl5riqvxv35utyuhlisbz4247io32oshff2emysu5fzc2t4msh64ahlpq
- Region of Operation: Southeast Asia/Manila
- Use case(s) to be supported: Media and Entertainment
- DataCap Requested: 100TiB or any allocation

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
I am currently working with the infrastructure setup of Filecoin lotus chain and lotus-miners which uses by our development team to create an application for music and entertainment that store and retrieve media files into Filecoin and IPFS network. 
https://weraveyou.ipfssys.info/
Miners ID: f024952 Owned Miner: f029421 f047327 f094018

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
I prefer not to disclose
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Although I don’t have made such contributions to the Filecoin Community for the implementation of the specs and documents but as a member of slack Filecoin community, I’m actively participating with some discussions and raising issues when building and making lotus nodes and lotus miners into local and cloud environment setup.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
None.
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Alyale Philippines, Inc. is a software company based in Philippines, that build and provides blockchain related application, infrastructure and data center (hardware), application for remote work monitoring and management, private block chain and hyperledger. The team of hard working software engineers and Infrastructure engineers are working remotely in building state of the art applications that suite with our client needs.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://www.alyale.com/
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
None.
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We would like to support the media and entertainment industry when it comes to data storing and retrieving of media files and other related data in more efficient ways and making them more connected with people involved in such many ways.   
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
With the DataCap allocation of 100TiB for logging in and uploading media files such as artist performance video files and live video files for seminars and other related data will be good enough allocations for us to test and experiment the Filecoin Storage use cases. 
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
In such event that we need to implement internally, we will be needing at least 50% of the DataCap for storing data files, another 50% of the allocated DataCap into experimenting the Filecoin Storage use cases.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We already implemented our own Lotus node to our environment, although we started with the testnet and later on migrated to mainnet when Filecoin launched it. We are keeping a small amount of FIL currently with our wallet addresses and plan to continue such amount for security purposes, retaining only the amount needed for experimentation is what we are thinking and securing the environment for any DDOS attack and Bot attack. Protection is our main priority by increasing security and following the best practices that necessary to apply.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
Allocation of DataCap will be limit to each client or user, so not to abuse it. Monitoring and insuring that the request from the client will be legitimate and out of any potential suspicious network activities. 
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
None.
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
The process of limiting the DataCap allocation, it means that the user will be much easier to monitor when abused and over-allocated. 
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
No, we don’t plan to keep records of any allocation decision to prevent disclosing any security and privacy issues in the future.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We can conduct our allocation decision in both public and private if necessary.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None.
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None.
```

**Comment by jnthnvctr** [comment]
Hi @melgalvez - this application is for allocating DataCap to others. If you'd like DataCap to support your own use case, please go to https://filecoinplus.on.fleek.co and fill out a request!
