### ISSUE TITLE
Proposal: Project Bearded - 1.15 PiB Data Set / 10 PiB DataCap

### ISSUE THREAD

**Issue by scharfstein** [filecoin-project/notary-governance#536]
For the purposes of community transparency, Seal Storage Technology would like to present a collaborative plan for onboarding a total of 6.9 PiB to the Filecoin Network. This will represent 6 full replicas of a 1.15 PiB public data set. 

Project Description

The project is a 1.15 PiB project to prove out the value propositions of decentralized data storage. A set of two DataCap Applications have been submitted by Seal Storage on behalf of our Customer, who wishes to remain confidential for the duration of this project project. Our Customer is a world-class scientific research organization and the data set is climate data.

Data Set

The data set is public climate data.

Transparency in KYC

Our Customer is a world-class scientific organization and we have completed a KYC process to verify this customer including meeting the Customer Lead face-to-face, numerous meetings with the broader technical team, data transfer tests with the Customer Team and their collaborators, and verification of sample data.

We understand that a confidential customer complicates the ability of the Filecoin Community to verify this project.

Seal is committed to transparency and we have completed NDAs with notaries and storage providers, including Filecoin Foundation, and disclosed the name of the Customer along with evidence of the project such as email communications, a statement of work document, data transfer details and sample data.

Transparency in Filecoin Plus Guidelines

We would like to show our appreciation to the community for allowing this project project to move forward.

In working closely with Protocol Labs and The Filecoin Foundation, Seal is following these recommendations as a path forward to make the project a success for the Customer and the Network.

Submit a Proposal Issue in the Notary Governance repo for your entire project
Submit two datacap applications, one for 5 PiB and one for 1.9 PiB, each referencing the Project
Five notaries have agreed to support these LDNs

Data Storage Plan

Six full replicas, total of 6.9 PiB of Datacap

W3b Cloud [USA] / 1.15 PiB
f01506844

PikNik [San Diego, USA] / 1.15 PiB
f01732189

Holon [Sydney, AUS] / 1.15 PiB
f01206408 
f01207874 
f01207954 
f01208042 
f01206207 
f01206260

ElioVP [Antwerp, Belgium and Utrecht, Netherlands] / 1.15 PiB
f01345523 is Antwerp, Belgium
f01392893 is Utrecht, Netherlands

Seal Montreal, Canada / 1.15 PiB
f01829181

Seal Las Vegas, USA / 1.15 PiB
f098770

For Customer project, Seal must also keep a full unsealed replica (1.15 PiB)

Notaries that Support the Project [person / org / region / Github app]

Danny O'Brien / Filecoin Foundation / @dannyob / f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
Kobby Chen / Fenbushi / @Fenbushi-Filecoin / f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
Neo Ge / IPFS Main / @neogeweb3 / f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
Meg Dennis / Holon / @MegTei / f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
Eric / ByteBase / @swatchliu / f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi

DataCap Applications

Bearded LDN-01 Seal Storage Technology, 5 PiB
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/326

Bearded LDN-02 Seal Storage Technology, 1.9 PiB
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/327

**Comment by galen-mcandrew** [comment]
The root key holders have approved these two LDN apps, and they are ready to sign by notaries.

**Comment by scharfstein** [comment]
Thanks!



GREGORY SCHARFSTEIN

Director of Business Operations


SEAL STORAGE TECHNOLOGY

(410) 961-2464 <1-410-961-2464>

***@***.***

sealstorage.io

333 Bay Street | Toronto, CA

**Comment by salstorage** [comment]
Seal Las Vegas, USA / 1.15 PiB
f098770
f01829137
f01886690
f01886704
f01886706

**Comment by scharfstein** [comment]
Good day community.

In response to this comment: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/327#issuecomment-1191761175

Seal has submitted this LDN application: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/955 as per @dkkapur 

Danny O'Brien / Filecoin Foundation / @dannyob 
Kobby Chen / Fenbushi / @Fenbushi-Filecoin 
Neo Ge / IPFS Main / @neogeweb3 
Meg Dennis / Holon / @MegTei 
Eric / ByteBase / @swatchliu 

@galen-mcandrew 
@salstorage

**Comment by dkkapur** [comment]
Moving forward with creating an LDN for the remaining 3.1 PiB of DataCap required, which we will associate with the new application.

**Comment by dkkapur** [comment]
Tracking here: https://github.com/filecoin-project/notary-governance/issues/615
