### ISSUE TITLE
Modification: Record presentations - Share projects async rather than live on Notary Governance Calls

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#537]
**Issue**
We have seen an increase in clients/applicants who wish to share their project details during the bi-weekly Notary Governance call. While this is great (!) that more members of the community wish to share and highlight their projects built in the Filecoin Plus ecosystem, this has added significant time constraints to the weekly calls. If each applicant is provided with 5minutes of time to present live, the 1hr meetings would either extend in multiple hours - or - there would be not time for issues impacting the Notaries and broader community.

We need to have a solution that allows clients/applicants a way to share more details about their projects in a recorded a-sync format, vs presenting live.

**Proposal**
To present your application/project. Record a short 5 minute video. The video should cover the following topics (listed as a presentation guide, not a requirement)

1. What is the organization 
- How long has org been around
- Where is org located
- What industry of org

2. What is the data 
- Where is the data currently being stored 
- How will the data be verified to be open

3. What are you looking for? 
- What is needed from Notaries

4. What is the current status of the application? 
- How long has it been open
- What is needed for next steps

Videos can be screen recorded in whichever format the applicant feels best presents their material. There is no required template or topics to cover!

Once video is recorded, upload the video file to this Google Drive Folder. (parent to this doc)
https://drive.google.com/drive/folders/1wNr0_0sBuRJlAfF7vdktD9M4SSg3wxyN?usp=sharing
Create an comment in the [Filecoin Github Notary Governance](https://github.com/filecoin-project/notary-governance/issues) in the upcoming Notary Governance call

- Include link to the application
- Organization represented
- Location
- Length of time application has been open

Link to your recorded video (which you have saved in the Google Drive folder linked in step 2) 

On the day PRIOR to the Governance call.

- Kevin from Filecoin Foundation will then compile videos and share in the fil-plus-Application-review channel as well as a thread in the fil-plus channels. *Intent is to ensure the highest possible level of transparency and visibility.

- Kevin from Filecoin Foundation will add a line in the Notary Governance Meeting Agenda for each comment in the Github sign up.  

- Due to time limitations. 
- PRESENTATIONS WILL TAKE PLACE A-SYNC AND VIEWED AS RECORDINGS.
- SIGN UPS WILL BE FOR APPLICANTS TO FACILITATE Q&A WITH NOTARIES AND COMMUNITY. 
   - During the Notary Governance call, any Notary wishing to ask additional information to the applicant can do so.

Summary: Transition from having demo/presentations LIVE, to a pre-recorded format and save the Notary Governance meeting time for questions.

https://docs.google.com/document/d/1FT7JFpwUqy6objR1y7Lr04ta06sjEKTH69yX-mqyl3g/edit?usp=sharing

**Comment by dannyob** [comment]
I like this!

**Comment by MegTei** [comment]
This could work. Test it!

**Comment by neogeweb3** [comment]
Go for it!

**Comment by liyunzhi-666** [comment]
try it!

**Comment by HolaSpace** [comment]
@Kevin-FF-USA  Kevin. We don't have permission to upload content to this folder, please open it.
Thank you!
![google](https://user-images.githubusercontent.com/105311153/169965164-2a4ab5f7-9f6b-4786-8a4b-0f16db442300.png)
https://drive.google.com/drive/folders/1wNr0_0sBuRJlAfF7vdktD9M4SSg3wxyN?usp=sharing

**Comment by CoinPhD-official** [comment]
@Kevin-FF-USA I also can not upload videos to google drive. Can you give us a new way for it?

**Comment by HolaSpace** [comment]
> @Kevin-FF-USA Kevin. We don't have permission to upload content to this folder, please open it. Thank you! ![google](https://user-images.githubusercontent.com/105311153/169965164-2a4ab5f7-9f6b-4786-8a4b-0f16db442300.png) https://drive.google.com/drive/folders/1wNr0_0sBuRJlAfF7vdktD9M4SSg3wxyN?usp=sharing

Can it be ready now?

**Comment by Kevin-FF-USA** [comment]
Thanks for flagging.  Link should be updated to allow you to CONTRIBUTE to the folder.
https://drive.google.com/drive/folders/1ktv4y1mRxa9kpTWjzQJj5wc2m1t-oaUs?usp=sharing

@HolaSpace @CoinPhD-official please let me know if still unable to upload

**Comment by HolaSpace** [comment]
Can do now, Tks Kevin~

> Thanks for flagging. Link should be updated to allow you to CONTRIBUTE to the folder. https://drive.google.com/drive/folders/1ktv4y1mRxa9kpTWjzQJj5wc2m1t-oaUs?usp=sharing
> 
> @HolaSpace @CoinPhD-official please let me know if still unable to upload

**Comment by Xingchi-Media** [comment]
Hi @Kevin-FF-USA 
I have no permission to upload files on Google's hard disk. I will mark them here again to avoid missing them.

LDN demo video
https://drive.google.com/file/d/1whxzY2DK5i0TkrAgWO7-5NhfY0JzuqkU/view?usp=sharing
PPT
https://drive.google.com/file/d/1u4r3MUWTeleeDM_cF3qb-Tr_4pVz98DR/view?usp=sharing

> We want to share our LDN application https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1051

**Comment by jacktree7** [comment]
Hi @Kevin-FF-USA
I have no permission to upload files on Google's hard disk. I will mark them here again to avoid missing them.

LDN Link
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1198

LDN demo video
https://drive.google.com/file/d/1__jNTEr0xsTwjnvTL8-NFVVanZ704VqZ/view?usp=sharing
https://drive.google.com/file/d/1WzLedrg-w87s2wHxhqSamLTMRfQpIbER/view?usp=sharing

PPT
https://drive.google.com/file/d/1J4vVlS1PyLctLMRjv2OemOmuz0UaUHr6/view?usp=sharing

**Comment by beegoathz** [comment]
@Kevin-FF-USA Kevin. We don't have permission to upload content to this folder, please open it. Thank you!
