### ISSUE TITLE
Notary Application: Filecoin Foundation

### ISSUE THREAD

**Issue by philippbanhardt** [filecoin-project/notary-governance#54]
# Notary Application

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Philipp Banhardt
- (Optional) Affiliated Organization: Filecoin Foundation
- Website / Social Media: @philipp on the Filecoin Slack 
- On-chain Address(es) to be Notarized: f1sdzgaqmitbvgktkklpuaxohg6nuhce5eyvwxhaa
- Region of Operation: Global
- Use case(s) to be supported: Humanities most important *open* and *public* data, as well as official Filecoin affiliated growth initiatives such as Slingshot or Discover  
- DataCap Requested: 1 PiB

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
As an individual, I’ve worked to help support a number of prominent community members (notably Protocol Labs, Textile, & OB1). More recently, I’ve transitioned to help set up the Filecoin Foundation, where my role is to help steward the Filecoin ecosystem and foster growth. The Foundation was also the first beta notary for Filecoin Plus where we have allocated ~ 60 TiB across a broad range of client requests.

Across these various forms of involvement, I’ve been a part of the Filecoin community since 2016. 

As an organization, the [Filecoin Foundation](https://fil.org/about) is an independent organization dedicated to supporting Filecoin.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
100mm tokens, per the vesting [schedule](https://coinlist.co/filecoin). 
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Besides supporting Protocol Labs in building Filecoin financially, I have spent time working on Ecosystem development while both spending time at Protocol Labs in 2019, and now with my role at the Filecoin Foundation. At Protocol Labs I was involved in helping draw up the early roadmap for developer engagement. At the Foundation I'm managing developer grants and other strategic initiatives.

The Filecoin Foundation is an independent organization dedicated to supporting Filecoin, an open source, decentralized storage network designed to preserve humanity’s most important information.The Filecoin Foundation facilitates governance of the Filecoin network, funds critical development projects, supports the growth of the Filecoin ecosystem, and advocates for Filecoin and the Decentralized Web.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
None
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
https://fil.org/about/

The Filecoin Foundation is an independent organization dedicated to supporting Filecoin, an open source, decentralized storage network designed to preserve humanity’s most important information.The Filecoin Foundation facilitates governance of the Filecoin network, funds critical development projects, supports the growth of the Filecoin ecosystem, and advocates for Filecoin and the Decentralized Web.

The Filecoin Foundation was founded in 2020 is registered in the US. 
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://fil.org/ 
https://www.linkedin.com/in/philipp-banhardt-24646834/
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://finance.yahoo.com/news/filecoin-foundation-appoints-initial-staff-103014932.html
https://traderszone.net/filecoin-foundation-says-tech-luminaries-will-help-project-suceed
https://news.huoxing24.com/20201022204827321479.html
https://www.enterpriseai.news/2020/10/23/filecoin-foundation-and-ffdw-launch-to-advance-the-dweb/ 

```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We will exclusively support (1) open data sets (high trust, unambiguous, and easy to maintain), that truly feed into Filecoin's mission of being the foundation for humanities most important information, and (2) support strategic growth initiatives for the Filecoin project as a whole (e.g. Discover or Slingshot). Across all use cases we expect they foster decentralization across the entire network.

Note that we will apply extra scrutiny for (1) and will be heavily biased towards clients that either directly represent or have a strong affiliation with the data they are looking to store on the Filecoin network.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
The high level strategy is to set thresholds with varying degrees of trust. As a standard practice, for relatively small amounts of DataCap (gigabyte scale) the aim is to make the process relatively painless - with higher thresholds requiring greater scrutiny. 

Several factors will be considered when making allocation decisions: 

- Reputation of organization and key individuals involved, e.g. we expect links to social profiles, for very large requests also direct recommendations from third parties, as well as any references to their history working with IPFS / Filecoin 
- Source, size and type of data, e.g. who owns, collects or produces the data - where does it live today and who is requesting it with what frequency etc
- Client storage strategy, e.g. redundancy, location preferences, how they will engage with miners etc - *note* that we expect all applicants to disclose any potential conflict of interests with the mining community
- Scale of allocation, e.g. we generally will keep the process to a minimum if the request is sub 500 GiB, but additional requests for anything above
- Frequency of allocation
- Security considerations
- Transparency of Client



```

Are there any internal processes you plan on implementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
We aim to pursue a conservative strategy in regard to frequency and amount of allocations. Our learnings from the Filecoin Plus beta have shown that it typically takes 5-7 days until we approve a new requests after submission, and we expect to maintain that pace. We are generally not prepared to allocation more than 5 TiB per requests, but in special circumstances can make an exception (e.g. if the data is high value and much larger than 5 TiB).

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The address that will be allocated DataCap will have its keys be secured on a hardware wallet. 
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
Initially we will expect clients to make public deal transactions after having been awarded DataCap. Long term we expect to utilize tooling that will automate verification of on chain data vs what was proposed in the clients initial application. We also expect the community to flag any broad cases of wrong doing and will be working towards setting up a dispute management system.

```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
The plan is to try and keep asks for information matched with the amount of DataCap being requested. Some of the questions, but not all, can be found [here](https://github.com/filecoin-project/notary-governance/blob/main/notaries/templates/sample-client-application.md) or see here for an application during the Filecoin Plus beta: https://github.com/keyko-io/filecoin-clients-onboarding/issues/62. 
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
We plan to invest in building technology that can help manifest a process that is robust, secure and pragmatic. We also expect all clients to make public their deal transactions with miners.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
All allocation decisions will happen in public in the following [repository](https://github.com/keyko-io/filecoin-notaries-onboarding) - all communications will also take place through the repository and the issue tracking. 
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will happen in public in the following [repository](https://github.com/keyko-io/filecoin-notaries-onboarding)
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes, all previous applications can be found here: https://github.com/keyko-io/filecoin-clients-onboarding/issues?q=is%3Aissue+is%3Aclosed 
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
60 TiB
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None
```

**Comment by jnthnvctr** [comment]
Hi @philippbanhardt  - based on your application, we have scored as follows; https://docs.google.com/spreadsheets/d/1miQXm_uzg7i6lzxCn3yEPSmOyL-aDnjt8tw8oThYIz0/edit?usp=sharing

Eligibility score: 2
Unrounded score: 2.4

**Comment by jnthnvctr** [comment]
Hi @philippbanhardt - as mentioned on the governance call yesterday, your team was in the top of your region for being a prospective Notary! Prior to confirming your role as a Notary, there are a few items that need to be affirmed: 

1. Please acknowledge the region of operation in which you tend to primarily focus: [EUR]

2. Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.

* **Upfront Disclosures**: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship. 

* **Promoting Client Best Practices**: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found [here](https://github.com/filecoin-project/notary-governance/issues/9).

* **No Self Dealing**: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

* **Operating in good faith**: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

3. Please list any addresses you are affiliated with below - stating the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt. 

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above. 

5. (If ready) - Please confirm the address that should receive DataCap.

**Comment by jnthnvctr** [comment]
Additionally, since you've indicated you plan on using the Filecoin Plus Registry - please confirm what information you'd like to have displayed here: 

"name": "Your Name",
"use_case": [
    "List",
    "of",
    "Use Cases"
],
"location": "EUR",
"github_user": "notaryc",
(optional) "website": "google.com",
(optional) "max_datacap_allocation": "100 GB", // To indicate to clients what size allocations you might support. 
(optional) "private_request": "false",                       // leave as true if you plan on supporting private requests. 
(optional) "email": "youremail@a.com",                 // only needed if you are supporting private requests
"info": ""                                                                            // You can use this to share information with Clients about your allocation strategy / reqs

**Comment by philippbanhardt** [comment]
Hi @jnthnvctr 

1. Yes I am in EUR zone
2. Address affiliation: f1sdzgaqmitbvgktkklpuaxohg6nuhce5eyvwxhaa (used as notary during the Filecoin Plus beta)
3. Promoting Client Best Practices: Yes
4. No Self Dealing: Yes
5. Operating in good faith: Yes
6. > Please affirm that you will abide by the allocation / client due diligence plan you laid out above: < Yes
7. Address to receive datacap: **f14bww6lntw66psewkotnnq5zdhx5drq4wqytnziq**

"name": "Philipp Banhardt / Filecoin Foundation",
"use_case": [
"Open datasets that serve as a foundation for humanities most important information",
"data affiliated with strategic growth initiatives of the Filecoin project, e.g. Discover"
],
"location": "EUR",
"github_user": "philippbanhardt",

One additional note: the Foundation has been allocated 100m Filecoin, however as of today we are not yet in control of that wallet - so that is why we can not disclose it yet.

**Comment by jnthnvctr** [comment]
## Request Approved
#### Address 
> f14bww6lntw66psewkotnnq5zdhx5drq4wqytnziq
#### Datacap Allocated
> 100TiB

**Comment by jnthnvctr** [comment]
hi @philippbanhardt per my message in slack can you confirm this address is correct? please ping me in slack if you have questions.

**Comment by philippbanhardt** [comment]
Per our slack convo: the above address is not correct, correct address is
*f1pns2ivst3kwrxatogpoucfk32ugebnn3medd73a*

Am Mi., 13. Jan. 2021 um 03:11 Uhr schrieb jnthnvctr <
notifications@github.com>:

**Comment by jnthnvctr** [comment]
## Request Approved
#### Address 
> f1pns2ivst3kwrxatogpoucfk32ugebnn3medd73a
#### Datacap Allocated
> 100TiB
