### ISSUE TITLE
Next Governance Call: Tues June 14 8am PT / 3pm UTC -and- 4pm PT / 2300 UTC

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#549]
The eleventh Notary Governance Call of 2022 will take place on June 14 8am PT / 3pm UTC -and- 4pm PT / 2300 UTC

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:

Fil+ Day review and Highlights
LDN v3 Completion
Notary Questions
Community discussions
Application Presentations

If you would like to add an item to the agenda, please request via a comment in this issue.

- Application presentation times will be allocated for 5minutes. If you would like to share your project you must have your request submitted in this issue at least 48hrs before the Governance meeting

- Requests to showcase an Application or LDN should be submitted via a recorded video following the guidance in ([Proposal](https://github.com/filecoin-project/notary-governance/issues/537))

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
(https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D
@[Kevin-FF-USA](https://github.com/Kevin-FF-USA) Kevin-FF-USA added the[ Governance Call ](https://github.com/filecoin-project/notary-governance/labels/Governance%20Call)label [25 days ago](https://github.com/filecoin-project/notary-governance/issues/518#event-6567707810)

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/538

**Comment by huangqian2021** [comment]
Hi @Kevin-FF-USA ,I have uploaded our video to Google Drive Folder you specified and some details as below:

link to the [application:](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/323)
Organization represented:
Hunan BlueStorm Information Technology Co., Ltd. was established in 2018 and headquartered in Changsha ,China.
It is a supplier focusing on the application field of "Internet + public security" industry and providing comprehensive service solutions. Based on big data + AI technology , the company has created intelligent and innovative police application platform and mobile application.
We will always be committed to promoting the sustainable development of society through professional and technological innovation.
Location: Changsha,China
Length of time application has been open:  nearly 2 month
Link to my recorded video:[https://drive.google.com/drive/folders/1ktv4y1mRxa9kpTWjzQJj5wc2m1t-oaUs](url)

**Comment by huangqian2021** [comment]
Hi @Kevin-FF-USA ,I have uploaded our video to Google Drive Folder you specified and some details as below:

link to the application：[https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/323
](url)
Organization represented:
Hunan BlueStorm Information Technology Co., Ltd. was established in 2018 and headquartered in Changsha ,China.
It is a supplier focusing on the application field of "Internet + public security" industry and providing comprehensive service solutions. Based on big data + AI technology , the company has created intelligent and innovative police application platform and mobile application.
We will always be committed to promoting the sustainable development of society through professional and technological innovation.
Location: Changsha,China
Length of time application has been open: nearly 2 month
Link to my recorded video:[https://drive.google.com/drive/folders/1ktv4y1mRxa9kpTWjzQJj5wc2m1t-oaUs](url)

**Comment by huangqian2021** [comment]
Hi @Kevin-FF-USA ，I have uploaded our video to the Google Drive Folder you specified and hope to have the opportunity to present our corporation . Some details as below:
Link to the application:
[https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/323](url)
Organization represented:
Hunan BlueStorm Information Technology Co., Ltd. was established in 2018 and headquartered in Changsha ,China.
It is a supplier focusing on the application field of "Internet + public security" industry and providing comprehensive service solutions. Based on big data + AI technology , the company has created intelligent and innovative police application platform and mobile application.
We will always be committed to promoting the sustainable development of society through professional and technological innovation.
Location: Changsha,China
Length of time application has been open: 2 month
Link to your recorded video:
[https://drive.google.com/drive/folders/1ktv4y1mRxa9kpTWjzQJj5wc2m1t-oaUs](url)

**Comment by huangqian2021** [comment]
Hi @Kevin-FF-USA ，I have uploaded our video to the Google Drive Folder you specified and hope to have the opportunity to present our corporation . Some details as below:
Link to the application:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/323

Organization represented:
Hunan BlueStorm Information Technology Co., Ltd. was established in 2018 and headquartered in Changsha ,China.
It is a supplier focusing on the application field of "Internet + public security" industry and providing comprehensive service solutions. Based on big data + AI technology , the company has created intelligent and innovative police application platform and mobile application.
We will always be committed to promoting the sustainable development of society through professional and technological innovation.
Location: Changsha,China
Length of time application has been open: 2 month
Link to your recorded video:
https://drive.google.com/drive/folders/1ktv4y1mRxa9kpTWjzQJj5wc2m1t-oaUs

**Comment by huangqian2021** [comment]
Hi @Kevin-FF-USA ，I have uploaded our video to the Google Drive Folder you specified and hope to have the opportunity to present our corporation . Some details as below:
Link to the application:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/323

Organization represented:
Hunan BlueStorm Information Technology Co., Ltd. was established in 2018 and headquartered in Changsha ,China.
It is a supplier focusing on the application field of "Internet + public security" industry and providing comprehensive service solutions. Based on big data + AI technology , the company has created intelligent and innovative police application platform and mobile application.
We will always be committed to promoting the sustainable development of society through professional and technological innovation.
Location: Changsha,China
Length of time application has been open: nearly 2 month
s
Link to your recorded video:
https://drive.google.com/drive/folders/1ktv4y1mRxa9kpTWjzQJj5wc2m1t-oaUs

**Comment by Fibo-AI** [comment]
@Kevin-FF-USA 
Link to the application: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349
Organization represented: Shanghai Fibonacci Artificial Intelligence Technology Co., Ltd. (FiboAI) is committed to the research and application of artificial intelligence technology. The core team comes from Shanghai Jiaotong University, financial industry, insurance and other industries with many years of experience in the Internet, finance, and artificial intelligence industries. The company has carried out industry-research cooperation with the APEX Laboratory of Shanghai Jiaotong University and the AI Research Institute all year round. At present, we have served dozens of customers in banking, insurance, logistics and other industries. In the future, FiboAI will continue to improve technology and services to help clients make business decisions simpler, smarter and more scientific.

Location: Shanghai, China
Length of time application has been open: 1 month
Link to your recorded video: https://drive.google.com/file/d/1ELCj2dIWzijpHGWE9IBwR3vaf1a-ekBh/view?usp=sharing

**Comment by HolaSpace** [comment]
@Kevin-FF-USA Hi, this is the information of my application.
Link to the application:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362

Organization represented:
HolaSpace provides storage solutions around personal and commercial data applications; a real "private field", reduces the risk of users in data storage, protects data and privacy security; has the characteristics of high efficiency and stability, friendly interface, simple the operation, and high-cost performance. Combined with blockchain technology to realize distributed storage, create higher value for personal and enterprise data security.

Location:
Singapore.

Length of time application has been open:
Close to 1 month.

Link to your recorded video:
https://drive.google.com/file/d/1H20cLGNncscmvvCKQQdteSJOHY_0k-Am/view?usp=sharing

**Comment by CoinPhD-official** [comment]
@Kevin-FF-USA Check it please.
**Link to the application**: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/364
**Organization represented:** The CoinPhD team is from well-known Internet and financial companies at home and abroad. It has deep accumulation of big data and AI technology, and has rich experience in intelligent quantitative strategy, graph calculation, data mining and blockchain data analysis.
CoinPhD is committed to advancing the development of digital assets through distributed big data AI analysis technology, helping individuals to obtain greater digital asset business value.
**Location**: China.
**Length of time application has been open:** Almost 1 month.
**Link to your recorded video:** https://drive.google.com/file/d/1ELCj2dIWzijpHGWE9IBwR3vaf1a-ekBh/view?usp=sharing

**Comment by KONGFU-VR** [comment]
@Kevin-FF-USA 
Link to the application: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372
Organization represented: KONGFU VR is the world's first metaverse VR GameFi. It has PVE + PVP mode and a huge view of the universe like Marvel Universe, a variety of mythical characters, famous heroes and other rich characters in the East and the west, and more than 100 kinds of props, weapons and skin. In the future, an open, immersive, sustainable and in-depth 3A level large-scale game will be built. The game has a perfect sustainable economic model. Upgrade Play-To-Earn mode to 2.0 “ Playing Fun, Keep Earning ! ”. This is a cross-era subversive VR GameFi.
Location: Japan.
Length of time application has been open: 23 days.
Link to your recorded video:https://drive.google.com/file/d/1B7pVf1Nls3axEVYp3geW9IKieeEWkJxl/view?usp=sharing

**Comment by MOLeMART** [comment]
Hi @Kevin-FF-USA ,
May I take 10-15 mins in next governance call (Tues June 14)?
I'd like to let every notary know my issue in detail. I've communicated with some notaries and waited for their responses several days ago. I hope that I can answer questions about my application from notaries via this meeting.

**Comment by Kevin-FF-USA** [comment]
@KONGFU-VR @CoinPhD-official @HolaSpace @Fibo-AI @huangqian2021 ,

Thank you. Confirming receipt of your organization and application view presentations. 

Per the direction from Proposal #538, there will no longer be live Application presentations on the call. In the last section of the call agenda, should Notaries have questions they can refer to your videos and ask questions live. Should you be in attendance, this will be your opportunities to address any issues that they have with the application

**Comment by Kevin-FF-USA** [comment]
@MOLeMART,

Apologies, there just isn't time in the schedule to afford that much of a time review to a single application.  Recommend you follow the steps outlined in the comment from Deep in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/336#issuecomment-1150638516 since your request for data allocation includes private enterprise data.  

If you would like to provide a detailed explanation video, I can ensure that it is included in future meetings (along with a line item for Notary Q&A where needed)

**Comment by Kevin-FF-USA** [comment]
Link to youtube recording for this meeting:https://youtu.be/FlHE2UWezC0

Link to the collected Application Presentations:  https://drive.google.com/drive/folders/1Q05bJ-YtRF1PBwS_Wi85OLG26oPRfZIf?usp=sharing
