### ISSUE TITLE
Notary Application: ABMatrix

### ISSUE THREAD

**Issue by Kayryu** [filecoin-project/notary-governance#55]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
- Name: ABMatrix
- (Optional) Affiliated Organization:  ABMatrix
- Website / Social Media: http://www.abmatrix.cn
- On-chain Address(es) to be Notarized:   f1ve2i6g7tptolme3kpa3m6azzmusq7ytdewobtcy
- Region of Operation: China
- Use case(s) to be supported: Industrial IoT data
- DataCap Requested: 100TB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
ABMatrix's main contribution and work in Filecoin Ecoystem includes:
* Filecoin browser. Link https://filup.io/
* Developed Filecoin bridge to substrate. see https://github.com/boolnetwork/filecoin-bridge.git
* Run multiple miner nodes.  f01289.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
N/A
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Our team runs multiple miner nodes and users provide storage services. And carry out industrial Internet business and filecoin storage integration.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
N/A
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Hangzhou Encryption Matrix Technology Co., Ltd. was established in May 2018 and is the second batch of blockchain companies in the country approved by the Ministry of Industry and Information Technology. With four invention patents since its establishment two years ago, it has become a professional cross-chain gateway technical service provider with strong comprehensive strength in China.

* Registered country: China
* Organization Size: 40 people
* Date of establishment: May 2018
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
N/A
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.ipfshub.com/sites/537.html/
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
N/A
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
We prefer development, so we consider the following factors:
1. Contribution to the community.
2. Developer activity.
3. Application scenarios.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Most are used for industrial data storage.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The easy way is through a multi-signature hardware wallet.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
We use privacy-based computing technology in the software to make sure that users are using it properly. Encrypt and store users' data.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
We will review the request according to the list of questions linked below:
https://github.com/filecoin-project/notary-governance/blob/main/notaries/templates/sample-client-application.md
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
N/A
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
All the process and decisions are made public on Github.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Only on Github.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Please answer here.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
Please answer here. 
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
Please answer here.
```

**Comment by jnthnvctr** [comment]
Hi @Kayryu - based on your application we've taken a pass at scoring your application: https://docs.google.com/spreadsheets/d/1YcUwla5RdlxALSy50ZNl37gxRAvuq-Akl4Duz_CKjvQ/edit?usp=sharing

Eligibility score: 1
Unrounded score: 1

**Comment by dkkapur** [comment]
@Kayryu - just wanted to let you know that Notary applications are currently open again until May 25. In case you'd be interested in applying again, please create a new Issue of type "Notary Application" and fill in the form (it is completely reasonable to reuse material from your prior application). **

**Comment by nathanusask** [comment]
> @Kayryu - just wanted to let you know that Notary applications are currently open again until May 25. In case you'd be interested in applying again, please create a new Issue of type "Notary Application" and fill in the form (it is completely reasonable to reuse material from your prior application). **

Thanks for the heads-up, we are working on the new application.

**Comment by nathanusask** [comment]
@dkkapur just for confirmation purposes, can you kindly indicate the timezone of the _May 25_ deadline? UTC?

**Comment by dkkapur** [comment]
@nathanusask - great question! we usually align to UTC time (but this can be a little more flexible, so assume PST worst case)!
