### ISSUE TITLE
Large dataset multisig request: LDN v3 multisig

### ISSUE THREAD

**Issue by galen-mcandrew** [filecoin-project/notary-governance#557]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED
    
To apply as a notary, please fill out the following form. 
    
## Core Information
- Name: LDN v3 multisig
- (Optional) Affiliated Organization: Filecoin Plus Program
- Website / Social Media: https://plus.fil.org/ldn-application
- On-chain Address(es) to be Notarized: f01858410
- Region of Operation: n/a
- Use case(s) to be supported: https://github.com/filecoin-project/notary-governance/issues/509
-  DataCap requested for allocation (10TiB - 10 PiB): 25PiB

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address
> f01858410
#### Datacap Allocated
> 25PiB

**Comment by dkkapur** [comment]
Manually adjusting these labels since the first signature did go through. Will reattempt using UI with second RKH signer tomorrow and report back, cc @fabriziogianni7

**Comment by dkkapur** [comment]
https://filfox.info/en/message/bafy2bzacechxco22ycq47hewbxtojtuyzqn64csdbt437ktsmqo3b6s2kcbnc

**Comment by dkkapur** [comment]
Manually adjusting request - was undefined again cc @fabriziogianni7 @huseyincansoylu

**Comment by dkkapur** [comment]
There's a bug here - bog should have detected completion of signature and allocation made of 49.9 PiB. To get this moving, I'm going to manually push though the request for the next allocation.

**Comment by dkkapur** [comment]
In line with this proposal - doubling the anticipated allocation from ~50 PiB to 100 PiB. Issue here: https://github.com/filecoin-project/notary-governance/issues/702

**Comment by dkkapur** [comment]
## Request Approved
#### Address
> f01858410
#### Datacap Allocated
> 100PiB

**Comment by huseyincansoylu** [comment]
## The request has been signed by a new Root Key Holder
#### Message sent to Filecoin Network
>

**Comment by galen-mcandrew** [comment]
RKH had to manually push the approval message: https://filfox.info/en/message/bafy2bzacecznupdmbucfctz6eqfm4yv5cpyi3zh6drjyr7x7mb3ce4lrd6ikm

**Comment by kernelogic** [comment]
Why was it requested 100PB but allocated 55.4PB? limitation on the system?

**Comment by galen-mcandrew** [comment]
Looks like RKH were able to push the top-up. Front-end may not be updating here from the recent network upgrade.

https://filfox.info/en/message/bafy2bzacedaw246yohric3gqmbyaemlhfckv53qpvmoooqzjudwsky6hj4djo

`lotus filplus check-notary-datacap f01858410
`
is returning 76718819652256400 bytes, ~= 68.14PiB

**Comment by kernelogic** [comment]
Bot is down, interplanetary browser is messed up....

**Comment by panges2** [comment]
Looks like RKH were able to push the top-up. Front-end may not be updating here from the recent network upgrade.

https://filfox.info/en/message/bafy2bzaceci2gs7hc2dpakrjj6hylunkwwscwzgxqgwp7chti6zblklqg2g7m

lotus filplus check-notary-datacap f01858410
is returning 76718819652256400 bytes, ~= 68.14PiB

**Comment by panges2** [comment]
fixed the links from Galen's comment. It was causing the interplanetary dashboard to mess up.

**Comment by dkkapur** [comment]
SSA bot is down - https://plus.fil.org/status, requesting allocation manually.
<img width="899" alt="Screen Shot 2022-12-31 at 10 09 05 PM" src="https://user-images.githubusercontent.com/2343218/210150078-9cf1482c-7bbc-44e1-bd37-8f814fafb018.png">

**Comment by dkkapur** [comment]
## Request Approved
#### Address
> f01858410
#### Datacap Allocated
> 68.14PiB

**Comment by galen-mcandrew** [comment]
Filfox is down, posting message from Filscan: https://filscan.io/tipset/message-detail?cid=bafy2bzacedigs7f4zi4e3shh5qaksai3lwi42xch72mnstrvr34mck53h4kri

RKH approved, checking Lotus confirms v3 msig now has 68PiB of DataCap

**Comment by galen-mcandrew** [comment]
Proposal: https://filfox.info/en/message/bafy2bzaceb3zktxidiefowxxaxfoxlnau73lzduwupjejcw2uppaoikwvyaom
Approval: https://filfox.info/en/message/bafy2bzaced5pvhbq4ssskl2yozxbostoepjzvabgmbcyc6kuaioz3qf7ahcsu

LDN has 119PiB of DataCap

**Comment by galen-mcandrew** [comment]
Looks like this v3 notary is out of DataCap, and there are still ~40 open allocation requests with at least one pending signature from notaries. Requesting more DataCap from the RKH to clear those 40 allocations.

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address
> f01858410
#### Datacap Allocated
> 50PiB

**Comment by stcouldlisa** [comment]
1. V3 410 only has 108T left
2. v4 cannot be signed yet
3. Now most robots are still triggered by the v3 multi-signature address f01858410, and v4 f02049625.

V3 410 needs to be recharged as soon as possible to solve the current confusion of the transition from v3 to v4.
<img width="1387" alt="WX20230302-105211@2x" src="https://user-images.githubusercontent.com/112812896/222318847-3f51b163-e126-4df8-8610-ffbf2ce0e4e5.png">

**Comment by galen-mcandrew** [comment]
Checking Lotus and Filfox, RKH should have completed this v3 top-up.

https://filfox.info/en/message/bafy2bzacebl34gwtahid25fhpglt7gtj2zk3ymv2gnpyn7ojm6cagcayo4hbu

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address
> f01858410
#### Datacap Allocated
> 100PiB

**Comment by galen-mcandrew** [comment]
First RKH Signature: https://filfox.info/en/message/bafy2bzacecpkyeysnf5d4lp5marqf2ignbucaschm6z3sn2lpfzqxidskqtu4

**Comment by galen-mcandrew** [comment]
Looks like second RKH signature came through, https://filfox.info/en/message/bafy2bzacecvzet2sxjhsjvrmfhlhctvxv2q7t2fuiqvalls6lbv2ji77yhdug

`lotus filplus check-notary-datacap f01858410
112589990684262400
` =100PiB
