### ISSUE TITLE
Notary Application: Performive:Blotocol Japan

### ISSUE THREAD

**Issue by MasaakiNawatani** [filecoin-project/notary-governance#56]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
- Name: Masaaki Nawatani
- (Optional) Affiliated Organization:  Blotocol Japan
- Website / Social Media: https://blotocol.com/
- On-chain Address(es) to be Notarized: N/A
- Region of Operation: Asia-GCN
- Use case(s) to be supported: Media and Entertainment
- DataCap Requested:N/A

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
My team and I have worked closely with admins of the Filecoin Community to develop a decentralized media and entertainment ecosystem. I led a team of developers in building a music and entertainment platform that uses the Filecoin Network to store and retrieve data. 
Link here -> https://weraveyou.ipfssys.info
```
### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
I prefer not to disclose.
```
 
### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We currently have not made any significant contributions to the Filecoin ecosystem’s growth, however, I have been consistently participating in all Filecoin Community events especially during the Slingshot contest period. We are in charge of researching and development for We Rave You project which is participating on Slingshot Phaze 1 and this project won the first award in the Music category.  Link here -> https://weraveyou.ipfssys.info
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
Currently have not made any contributions in that regard.
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Blotocol Japan is a software engineering company based in Japan. We build blockchain applications and crypto projects since 2018 and have been shifting our focus on Web 3.0 technology. I have a team of Software Engineers currently working remotely in different parts of Southeast Asia especially in Japan. We have a development team in Japan , Philippine and China. We can use multiple languages such as English , Japanese and Chinese.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://blotocol.com/
Officers: Toyko (Japan) , Kobe(Japan), Manila (Philippines), SHenzhen(China)
Social Media: N/A
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
N/A
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
N/A
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
In my understanding, the cheated dataCap issue has occurred because it is judged based on the miner's application. But in fact, any service  by a service provider not by a miner. We now have no way to access or contact the service provider directly. A service provider is alway hid behind of a miner. So if we give a miner DataCap incentive I suggest that a service provider needs to apply for a new DataCap program together with his miner. The we will check these points.

1. The relationship between a client and his miner. (A client needs to be independent from his miner)
2. What kind of service this client wants to do.
3. The transparency of this service.
```

If a service provider applies to a new DataCap program, he also has the right to get a DatCap incentive but he needs to accept our audit anyhow. We will organize an independent volunteer jury, then let them judge this service is useful and worth giving DataCap incentive.

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
DataCap will be allocated each 8 giga bit but this incentive should be divided between a client and a miner. 70 % will be given to a miner , 30% will be given to a service provider.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will make a specific application work with our Lotus. We always check a client node situation and a service provider's situation at the same time. Then this automated process is always watching if any weird or triky action happens in our system.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
We will put more importance on a service. 
1. Our system always watches this service and updates it.
2. Our system always watches data increasing ratios appropriately.
3. Our system always watches the number of users increasing appropriately.
4. Volunteer jury occasionally checks this service manually.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
None. The process is automated by our system.
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Please answer here. 
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
1. All detailed information records related to allocation decisions on Github will be retained, including time, amount, allocated customers, judgment reasons, etc.
2. All information is open and transparent. Based on this, everyone can supervise this area.
3. Any challenges raised by allocation decisions should first be discussed publicly in the Github repository.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Allocation decisions are made objectively against a set of predefined criteria mentioned above. These criteria will be made public in all our online portals. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
none
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
noen
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
none
```

**Comment by jnthnvctr** [comment]
Hi @MasaakiNawatani - thank you for your submission, based on your application we've scored it as follows: https://docs.google.com/spreadsheets/d/1EdW5czIpAU0hYl7IPtX7Qghowj9XOV6Lu0nlhCqxg5E/edit#gid=327015220

Eligibility score: 1
Unrounded score: 0.8 

Note - on the allocation strategy and client due diligence it seemed that you might be proposing allocating DataCap to miners directly. The role of the Notary is to help ensure real use cases on the Network are supported - so primarily focusing on ensuring Clients who _request_ DataCap are using it in responsible ways. 

You can see some suggestions on what Notaries should be encouraging Clients to do here: https://github.com/filecoin-project/notary-governance/issues/9

**Comment by jnthnvctr** [comment]
Hi @MasaakiNawatani    - as mentioned on the governance call yesterday, your team was in the top of your region for being a prospective Notary! Prior to confirming your role as a Notary, there are a few items that need to be affirmed (in addition to the Note above): 

1. Please acknowledge the region of operation in which you tend to primarily focus: [Asia-GCN]

2. Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.

* **Upfront Disclosures**: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship. 

* **Promoting Client Best Practices**: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found [here](https://github.com/filecoin-project/notary-governance/issues/9).

* **No Self Dealing**: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request. 

* **Operating in good faith**: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind. 

3. Please list any addresses you are affiliated with below - stating the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt. 

4. Please affirm that you will abide by the allocation / client due diligence plan you laid out above. 

5. (If ready) - Please confirm the address that should receive DataCap.

**Comment by jnthnvctr** [comment]
Additionally, since you've indicated you plan on using the Filecoin Plus Registry - please confirm what information you'd like to have displayed here: 

"name": "Your Name",
"use_case": [
    "List",
    "of",
    "Use Cases"
],
"location": "EUR",
"github_user": "notaryc",
(optional) "website": "google.com",
(optional) "max_datacap_allocation": "100 GB", // To indicate to clients what size allocations you might support. 
(optional) "private_request": "false",                       // leave as true if you plan on supporting private requests. 
(optional) "email": "youremail@a.com",                 // only needed if you are supporting private requests
"info": ""                                                                            // You can use this to share information with Clients about your allocation strategy / reqs

**Comment by dkkapur** [comment]
@MasaakiNawatani - please respond to the above points so we can proceed with confirming you as a Notary

**Comment by MasaakiNawatani** [comment]
> 1. Please acknowledge the region of operation in which you tend to primarily focus: [Asia-GCN]

Yes,it is Asia-GCN

> 2. Please confirm each of the following items below (you can do this by adding a line under each section agreeing that you'll abide by these operational principles.
> 
> * **Upfront Disclosures**: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship.

Yes, I accept this.

> * **Promoting Client Best Practices**: Notaries agree to educate approved clients about the best practices for using their DataCap (e.g. how to request additional services from miners, storing data redundantly across many miners, etc). Some reference information can be found [here](https://github.com/filecoin-project/notary-governance/issues/9).

Yes, I accept this and will do.


> * **No Self Dealing**: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

Yes, I accept this.

> * **Operating in good faith**: Notaries hold a position of trust in the network, and as such it is expected that they operate keeping the Principles of this mechanism in mind. While each form of abuse cannot be exhaustively defined, Notaries are expected to bias towards caution and act in a way that promotes transparency. Notaries should expect to potentially receive requests or questions for allocation decisions (within reason) - and should make decisions with this in mind.
> 

Yes, I accept this and will do.

> 1. Please list any addresses you are affiliated with below - stating the nature of the relationship. Please refer to the first bullet point in (2) for the definition of "affiliated", and bias towards transparency when in doubt.

As I applied. I was involved in development for We Rave You project. (https://weraveyou.ipfssys.info)
So I list addresses related this project.

 t3r2hi62gfsitu3fpmeysc62yqns6ydyv67gukvosduf3jozngjmmg5cxktrqtvaqpwwsmdrtfekvyfdeanhqq

> 2. Please affirm that you will abide by the allocation / client due diligence plan you laid out above.

Yes, I do. I confirmed.

> 3. (If ready) - Please confirm the address that should receive DataCap.

Please use this address.
f3rnnecpx2n5cxs5fsjrnqq32r3hacubkt45mnbywvcaskgwpfuzixdmydpcdmujwqwoe6l2oi4tzyj2zakjsq

Thank you.

**Comment by jnthnvctr** [comment]
## Request Approved
#### Address 
> f3rnnecpx2n5cxs5fsjrnqq32r3hacubkt45mnbywvcaskgwpfuzixdmydpcdmujwqwoe6l2oi4tzyj2zakjsq
#### Datacap Allocated
> 10TiB

**Comment by jnthnvctr** [comment]
Hi @MasaakiNawatani - are you on the Filecoin slack? If so, could you message @jnthnvctr there?

**Comment by jnthnvctr** [comment]
hi @MasaakiNawatani - per my message in slack can you please confirm your address is correct?

**Comment by MasaakiNawatani** [comment]
Sorry for late reply. Yes, that address is correct.
