### ISSUE TITLE
Next Governance Call: Tues June 28 8am PT / 3pm UTC -and- 4pm PT / 2300 UTC 

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#560]
The twelveth Notary Governance Call of 2022 will take place on June 28 8am PT / 3pm UTC -and- 4pm PT / 2300 UTC

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:

Notary Questions
Community discussions
Application Q&A (based on video submissions)

If you would like to add an item to the agenda, please request via a comment in this issue.

    Application presentation times will be allocated for 5minutes. If you would like to share your project you must have your request submitted in this issue at least 48hrs before the Governance meeting

    **Requests to showcase an Application or LDN should be submitted via a recorded video following the guidance in** (https://github.com/filecoin-project/notary-governance/issues/537)

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
(https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D
@[Kevin-FF-USA](https://github.com/Kevin-FF-USA) Kevin-FF-USA added the[ Governance Call ](https://github.com/filecoin-project/notary-governance/labels/Governance%20Call)label https://github.com/filecoin-project/notary-governance/issues/518#event-6567707810

**Comment by David-MyTrade** [comment]
@Kevin-FF-USA I want to join this governance call.
Link to the application: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/386

Organization represented: Founded in 2020, MyTrade is a next generation DEX that looks and feels like a centralized exchange with a wide variety of quality tradable assets.

Location: Britain.

Length of time application has been open: 1 month.

Link to your recorded video: https://drive.google.com/file/d/1D4w6lBK9VhcPtxXnHFBJf7_X97kCNW10/view?usp=sharing

**Comment by AiYueKeJi** [comment]
@Kevin-FF-USA Hi，Kevin，I want to join this governance call.
Link to the application: filecoin-project/filecoin-plus-large-datasets#440（Hangzhou Aiyao Medical Health Technology Co., Ltd.）

Organization represented: Hangzhou Aiyao Medical Health Technology Co., Ltd ("Aiyao") was established in Hangzhou in 2019 by divesting itself from Tencent Group, with Tencent Group still as its controlling shareholder.

The company was founded based on the informationization of the medical industry, while focusing on the creation of health education short video content, and gradually transformed into a life entertainment health management ecological builder "with the core goal of achieving a comfortable and enjoyable healthy life for users".

Location: China

Link to your recorded video: Will be submitted prior to the meeting.

**Comment by Kevin-FF-USA** [comment]
Hi @David-MyTrade,
Received your video, thank you.  Will add it to the application-review SLACK for Notaries. Looks like you have been asked to send an email to verify your account. Have you completed that step yet?

**Comment by Kevin-FF-USA** [comment]
HI @AiYueKeJi,
I'm closing the video applications for submissions to finalize the agenda and content for the June 28th call.  You are still encouraged to submit your recorded video, it will just need to be linked to the next Notary Governance call.

**Comment by Kevin-FF-USA** [comment]
[Fil+ Enterprise Governance_callV0.1 .pdf](https://github.com/filecoin-project/notary-governance/files/8994921/Fil%2B.Enterprise.Governance_callV0.1.pdf)

@Meg will be presenting a 10m update and Q&A on the Proposal.

**Comment by Kevin-FF-USA** [comment]
Agenda item:  Updated 2nd call time slot **Starting in August, will adjust the schedule for the second Notary Call to begin at 6pm PT// 1am UTC // 9am BJT for a temporary test of the updated start time.** 

https://github.com/filecoin-project/notary-governance/issues/538

**Comment by Kevin-FF-USA** [comment]
Agenda Item:  Notary Verification Status, Datacap allocation, open support (for blocked issues)

**Comment by AiYueKeJi** [comment]
@Kevin-FF-USA Hi，Kevin，I want to join this governance call.
Link to the application: filecoin-project/filecoin-plus-large-datasets#440（Hangzhou Aiyao Medical Health Technology Co., Ltd.）

Organization represented: Hangzhou Aiyao Medical Health Technology Co., Ltd ("Aiyao") was established in Hangzhou in 2019 by divesting itself from Tencent Group, with Tencent Group still as its controlling shareholder.

The company was founded based on the informationization of the medical industry, while focusing on the creation of health education short video content, and gradually transformed into a life entertainment health management ecological builder "with the core goal of achieving a comfortable and enjoyable healthy life for users".

Location: China

Length of time application has been open: 1 month.

Link to your recorded video: https://drive.google.com/drive/folders/1pPTb7lVTrmDlt8fBEaTWUNoRIUDahOEn

**Comment by David-MyTrade** [comment]
@Kevin-FF-USA Already completed it.

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/issues/565

**Comment by Alexkim9** [comment]
Hi @Kevin-FF-USA
I'm new here, and i was wondering when the governance call video will be released?

**Comment by Kevin-FF-USA** [comment]
https://youtu.be/yW3LhK1BzDU @Alexkim9
