### ISSUE TITLE
Next Governance Call: Tues July 12 8am PT / 3pm UTC -and- 4pm PT / 2300 UTC

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#567]
The thirteenth Notary Governance Call of 2022 will take place on July 12 8am PT / 3pm UTC -and- 4pm PT / 2300 UTC

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:
- Proposal for 2nd round Notaries to be added to v3 LDN
- Community Projects 
- Application Q&A (based on video submissions)

If you would like to add an item to the agenda, please request via a comment in this issue.

Application presentation times will be allocated for 5minutes. If you would like to share your project you must have your request submitted in this issue at least 48hrs before the Governance meeting

**Requests to showcase an Application or LDN should be submitted via a recorded video following the guidance in** (https://github.com/filecoin-project/notary-governance/issues/537)

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
(https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D

**Comment by AiYueKeJi** [comment]
> The thirteenth Notary Governance Call of 2022 will take place on July 12 8am PT / 3pm UTC -and- 4pm PT / 2300 UTC
> 
> You are welcome to attend both! These will be recorded, and video links will be posted in this issue. [https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)
> 
> Tentative Agenda topics will include:
> 
>     * Proposal for 2nd round Notaries to be added to v3 LDN
> 
>     * Community Projects
> 
>     * Application Q&A (based on video submissions)
> 
> 
> If you would like to add an item to the agenda, please request via a comment in this issue.
> 
> Application presentation times will be allocated for 5minutes. If you would like to share your project you must have your request submitted in this issue at least 48hrs before the Governance meeting
> 
> **Requests to showcase an Application or LDN should be submitted via a recorded video following the guidance in** (#537)
> 
> If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at (https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D

【@Kevin-FF-USA Hi，Kevin，I want to join this governance call.
Link to the application: filecoin-project/filecoin-plus-large-datasets#440（Hangzhou Aiyao Medical Health Technology Co., Ltd.）

Organization represented: Hangzhou Aiyao Medical Health Technology Co., Ltd ("Aiyao") was established in Hangzhou in 2019 by divesting itself from Tencent Group, with Tencent Group still as its controlling shareholder.

The company was founded based on the informationization of the medical industry, while focusing on the creation of health education short video content, and gradually transformed into a life entertainment health management ecological builder "with the core goal of achieving a comfortable and enjoyable healthy life for users".

Location: China

Length of time application has been open: 1 month.

Link to your recorded video: https://drive.google.com/file/d/1Nlbk9B_KBWeevN-MI2WZpyvGoPYXKXLa/view?usp=sharing

**Comment by AiYueKeJi** [comment]
【@Kevin-FF-USA Hi，Kevin，I want to join this governance call.
Link to the application: filecoin-project/filecoin-plus-large-datasets#440（Hangzhou Aiyao Medical Health Technology Co., Ltd.）

Organization represented: Hangzhou Aiyao Medical Health Technology Co., Ltd ("Aiyao") was established in Hangzhou in 2019 by divesting itself from Tencent Group, with Tencent Group still as its controlling shareholder.

The company was founded based on the informationization of the medical industry, while focusing on the creation of health education short video content, and gradually transformed into a life entertainment health management ecological builder "with the core goal of achieving a comfortable and enjoyable healthy life for users".

Location: China

Length of time application has been open: 1 month.

Link to your recorded video: https://drive.google.com/file/d/1Nlbk9B_KBWeevN-MI2WZpyvGoPYXKXLa/view?usp=sharing

**Comment by AiYueKeJi** [comment]
@Kevin-FF-USA Hi，Kevin，I want to join this governance call.
Link to the application: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/440（Hangzhou Aiyao Medical Health Technology Co., Ltd.）

Organization represented: Hangzhou Aiyao Medical Health Technology Co., Ltd ("Aiyao") was established in Hangzhou in 2019 by divesting itself from Tencent Group, with Tencent Group still as its controlling shareholder.

The company was founded based on the informationization of the medical industry, while focusing on the creation of health education short video content, and gradually transformed into a life entertainment health management ecological builder "with the core goal of achieving a comfortable and enjoyable healthy life for users".

Location: China

Length of time application has been open: 1 month.

Link to your recorded video: https://drive.google.com/file/d/1Nlbk9B_KBWeevN-MI2WZpyvGoPYXKXLa/view?usp=sharing

**Comment by mamimami666** [comment]
@Kevin-FF-USA Hi,Kevin,this is the information of my application.

Link to the application:filecoin-project/filecoin-plus-large-datasets#459

Organization represented:Founded in 2019, Chenggong (Hangzhou) Cultural Media is a film and television cultural communication team dedicated to brand strategy services, new media development and operation, film and television filming and production and live streaming pushing services on various platforms.

Location:
China

Length of time application has been open:1 month.

Link to your recorded video:https://drive.google.com/file/d/1Sde3TCSlZFQiM22L1MHUEWaxC_ZDWEtX/view?usp=sharing

**Comment by AiYueKeJi** [comment]
@Kevin-FF-USA 
Hi,Kevin,I hope all is well, is there anything else I need to do please? I couldn't make it in time last time due to timing issues, can I attend the governance meeting this week? Looking forward to it.

**Comment by scharfstein** [comment]
Seal Storage would like to give a short update on Project Antarctic ... ~ 3 minutes

**Comment by Kevin-FF-USA** [comment]
Hi @AiYueKeJi ,
Got you.  Have your recording (in the comments above)  Will compile into the deck and link the video for Notaries to watch

**Comment by Kevin-FF-USA** [comment]
link to Video: https://youtu.be/yqPc-0Wd75M
