### ISSUE TITLE
Notary Address Change Correction:  IPFS Japan Consortium - Masaaki Nawatani

### ISSUE THREAD

**Issue by galen-mcandrew** [filecoin-project/notary-governance#570]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Masaaki Nawatani
- Affiliated organization: IPFS Japan Consortium
- Website / Social Media:
- On-chain address to be notarized (recommend using a new address): f1ciu27vn3r7htmanzvwrm6ksx6y774gqsz3cot3i 
- Region of Operation: Asia minus GCN
- Use case(s) to be supported: Web 3.0 / Decentralized Applications
- DataCap requested for allocation (10TiB - 10 PiB): 1PiB

Correcting allocation. Removing through https://github.com/filecoin-project/notary-governance/issues/569

**Comment by galen-mcandrew** [comment]
## Request Approved 
#### Address 
> f1ciu27vn3r7htmanzvwrm6ksx6y774gqsz3cot3i
#### Datacap Allocated
> 1PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacebrjshr62yaftpgtvbx3bd7ea3xwukdeh57zthtp4gdixnyvypts6

Signed by Root Key Holder

**Comment by galen-mcandrew** [comment]
Approved by RKH 

https://filfox.info/en/message/bafy2bzacecwtiokxu6gsbdc3egr4wo7wcixa3yrjow52iuxf2hqc2dxfe4x7w

**Comment by MasaakiNawatani** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceawy22faa2jglygm6bmhhtd5tgoupbrakdi3jxtlp2pb5ik7nd52o
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawy22faa2jglygm6bmhhtd5tgoupbrakdi3jxtlp2pb5ik7nd52o

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1ciu27vn3r7htmanzvwrm6ksx6y774gqsz3cot3i
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzaceczg6a2hgbogkhyif4qvg7ramp3eh7yrt67p3dkzkw3cjbbbe7zde
