### ISSUE TITLE
Proposal: Spexigeo

### ISSUE THREAD

**Issue by peteszym** [filecoin-project/notary-governance#574]
## Objective
The objective of this proposal is to have 5 PiBs of data approved for data cap. The following sections below will explain 
Why this data is valuable
The dataset description
Why it must be encrypted

## Project Description and it’s Value
Spexigeo is building the most engaged drone pilot community and aerial data ecosystem. We currently operate a drone collaboration system that empowers organizations to collect drone-based data for their own projects. We will be expanding our network and covering much larger territories which will create much larger datasets on a continual basis.

The data of this project brings value to a multitude of industries including (but not limited to): 

Real Estate: Providing aerial listing footage of the property. Features include 360 panorama of the neighborhood, 3d models of the building and structural features. 
Sample footage here: https://projects.spexigeo.com/541-abbs-road

Construction: Providing rapid aerial surveys to analyze a site with volumetric estimates, elevation maps, and 3D models. They are high resolution visual records of construction sites with interactive 360 degree panoramas, orbits, up-to-date map views, and even 3D flythroughs. 
A sample of this use case can be found here: https://projects.spexigeo.com/player-demo. Demo of usage here: https://spexigeo.com/assets/video/volume-example.mp4

Agriculture: Providing those in the agricultural industry to measure, observe, and respond to what is happening in the field. Spexigeo allows an even richer and deeper view into crop health, moisture content, biomass estimation and crop health analysis with our spatially accurate, 3-D crop analysis products.

There are over 800 users that are actively using the Spexi platform thus proving value to a community of people and proving a growing community that finds our service and data valuable.

## Data Set 
Images and 3D point clouds/3D meshes. Imagery collected from the drones will be the prime datasource that will be stored. The imagery will be approximately 3cm GSD (ground sample distance), and in various forms; 1) raw data collected from the drone 2) processed orthorectified and mosaicked tiles, and 3) 360 panoramic images. The 3D point cloud as well as 3D meshes will be in object tiles in manageable sizes. (taken from their LDN og app).

## Encryption for our Clients
There are privacy concerns related to publicly collected high-resolution aerial data and Spexigeo’s ability to be the gatekeeper when individuals, corporations and governments have those concerns. 

Although the footage may be publicly collected, does not necessarily mean that all those associated with the footage are comfortable with having it public. Because this data is beyond pure visual footage, it contains detailed, and sensitive information about the location of the drone footage.

Each of Spexigeo’s clients are requesting aerial footage for their project, whether it be for marketing, planning, building, or studying. Allowing their requested aerial footage would reveal not only the footage but their projects. Thus, it is inappropriate for all their data to be public and when we are the gatekeeper of their privacy, we choose to protect it via encryption.

## KYC
Link to site: https://spexigeo.com/
LinkedIn: https://www.linkedin.com/company/spexi-geospatial/
Facebook: https://www.facebook.com/spexigeo
Twitter: https://twitter.com/spexigeo
Instagram: https://www.instagram.com/spexigeo/

## Original Application
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/431

**Comment by Carohere** [comment]
Hi @peteszym, the drone industry is a very popular and promising field right now. It's great to see new areas joining in to build the ecosystem together. 

But I am curious how you plan to introduce the data samples? Will you verify the authenticity of the data with the relevant notaries and PL officials under NDA or through any other methods?

For me, it's not hard to understand that data encryption is inevitable due to customer privacy concerns. In fact, I think encrypted data will be a huge part of Filecoin data body in the near future. But i believe there still has to be some verification for the data to better facilitate the development of Filecoin.

Again, welcome to the community!

**Comment by peteszym** [comment]
@Carohere we're going to be ingesting the data through our web and mobile applications. You're right that verification is going to be a critcal piece. We're currently working on some internal mechanisms to handle our v1 approach to that problem.

Thanks for the warm welcome!
