### ISSUE TITLE
Large dataset multisig request Project Beacon 12 LDNs #444

### ISSUE THREAD

**Issue by galen-mcandrew** [filecoin-project/notary-governance#576]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED
    
To apply as a notary, please fill out the following form. 
    
## Core Information
- Name: Project Beacon, 12 LDNs LDN # 444, 446, 447, 448, 474, 475, 476, 477, 479, 480, 481, 482
- (Optional) Affiliated Organization: Project Beacon 12 LDNs
- Website / Social Media: 
- On-chain address to be notarized (recommend using a new address):  f01885528
- Region of Operation: n/a
- Use case(s) to be supported: [Link 444](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/444), [Link 446](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/446),  [Link 447](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/447), [Link 448](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/448), [Link 474](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/474), [Link 475](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/475), [Link 476](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/476), [Link 477](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/477), [Link 479](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/479), [Link 480](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/480), [Link 481](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/481), [Link 482](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/482)
- DataCap requested for allocation (10TiB - 10 PiB): 7PiB

Calculating this based on 12 LDN applications, with weekly rates of 300TiB. 7PiB should be approximately 2 weeks worth of DataCap, and the root key holders can top-up as this is utilized with more.

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address
> f01885528
#### Datacap Allocated
> 7PiB

**Comment by swatchliu** [comment]
Hi @galen-mcandrew @dkkapur, we are pleased to see that Project Beacon has been approved. Thanks for the governance team's engagement and advice throughout. However, some notaries were missed in the multisig. Please help us add @UnionLabs2020, @1475Notary, @MatrixStorage, and @newwebgroup in.

**Comment by dkkapur** [comment]
@swatchliu - this can be done pretty easily. Notaries, please confirm your addresses ASAP: 

- @UnionLabs2020 - f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
- @1475Notary - f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
- @MatrixStorage - f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
- @newwebgroup - f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq

**Comment by swatchliu** [comment]
Please assist us in adding these three notaries first. Thanks @dkkapur

**Comment by swatchliu** [comment]
Hi @dkkapur @galen-mcandrew, any updates here?

**Comment by galen-mcandrew** [comment]
Re-opening for RKH top-up

**Comment by galen-mcandrew** [comment]
Looks like RKH were able to push the 7PiB top-up. Front-end may not be updating here from the recent network upgrade.

https://filfox.info/en/message/bafy2bzaceci2gs7hc2dpakrjj6hylunkwwscwzgxqgwp7chti6zblklqg2g7m

`lotus filplus check-notary-datacap f01885528
`
is returning 7881299347898368 bytes, ~= 7PiB

**Comment by panges2** [comment]
Looks like RKH were able to push the 7PiB top-up. Front-end may not be updating here from the recent network upgrade.

https://filfox.info/en/message/bafy2bzacedaw246yohric3gqmbyaemlhfckv53qpvmoooqzjudwsky6hj4djo

lotus filplus check-notary-datacap f01885528
is returning 7881299347898368 bytes, ~= 7PiB

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address
> f01885528
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzacecbt4xabqfwetclv4oyzcgliocurgcllfwomd52s62aa7fwaywiwc
