### ISSUE TITLE
Next Governance Call: Tues July 26 8am PT / 3pm UTC -and- 4pm PT / 2300 UTC 

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#585]
The forteenth Notary Governance Call of 2022 will take place on July 26 8am PT / 3pm UTC -and- 4pm PT / 2300 UTC

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:

    Forming of Notary Specific LDN review channels
    FILter bot updates (temp) hold
    Multisig updates (for 2nd round notaries)
    Project Proposals
    *Reminder - In August the 2nd call will shift to 6pm/0100UTC

If you would like to add an item to the agenda, please request via a comment in this issue.

Application presentation times will be allocated for 5minutes. If you would like to share your project you must have your request submitted in this issue at least 48hrs before the Governance meeting

Requests to showcase an Application or LDN should be submitted via a recorded video following the guidance in (https://github.com/filecoin-project/notary-governance/issues/537)

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
(https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/issues/564

^ let's make sure we set aside ample time for this one.

**Comment by AlexxNica** [comment]
I guess there's a typo in the date. This is happening on July 26, right?

**Comment by kevzak** [comment]
@Kevin-FF-USA - I'd love a time slot to give an overview of the newly opened E-Fil+ Discussion Topics:
https://github.com/filecoin-project/notary-governance/discussions/580
https://github.com/filecoin-project/notary-governance/discussions/582
https://github.com/filecoin-project/notary-governance/discussions/584
https://github.com/filecoin-project/notary-governance/discussions/583
https://github.com/filecoin-project/notary-governance/discussions/579

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/571

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/464

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/489
Onboarding Status

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/discussions/327
Update Status

**Comment by Kevin-FF-USA** [comment]
https://youtu.be/ot_BVgZoTcQ
