### ISSUE TITLE
Next Governance Call: Tues August 9 8am PT / 3pm UTC -and- 6pm PT / 0100 UTC  (wednesday)

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#588]
The fifthteenth Notary Governance Call of 2022 will take place on August 9 8am PT / 3pm UTC -and- 6pm PT / 0100 UTC (10th)

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:
4th Notary Election: Tentative Date for Q4
Recent Proposals
Community Discussion: Recent Hack
*Reminder - In August the 2nd call will shift to 6pm/0100UTC

If you would like to add an item to the agenda, please request via a comment in this issue.

Application presentation times will be allocated for 5minutes. If you would like to share your project you must have your request submitted in this issue at least 48hrs before the Governance meeting.

Requests to showcase an Application or LDN should be submitted via a recorded video following the guidance in (https://github.com/filecoin-project/notary-governance/issues/537)

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
(https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D

**Comment by iPolloverse1** [comment]
Hi, @Kevin-FF-USA,  I'd like to join in the governance call 
Link to the application: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/538 (iPolloverse SG PTE. LTD.)

Organization represented: 
Industry belonging: gaming, cloud computing
iPolloverse is to provide rendering computing power for metaverse, thus it is virtually for gaming industry and can be categorized into cloud computing (decentralized IaaS) field.

Location: Singapore

Length of time application has been open: 2 weeks

Link to your recorded video: https://drive.google.com/file/d/1D_A2dciSxQffUI_swgMzgPjA1IBBd6ZC/view?usp=sharing

**Comment by Kevin-FF-USA** [comment]
Link to the recordings for these meetings:   https://youtu.be/y7DGyGot8GQ
