### ISSUE TITLE
Notary Application:BeeLantern

### ISSUE THREAD

**Issue by 8hfq** [filecoin-project/notary-governance#59]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
- Name:Edison chan
- (Optional) Affiliated Organization: BeeLantern
- Website / Social Media:@8hfq on the filecoin slack
- On-chain Address(es) to be Notarized: f1iw7igcgfcdizoqyfu6hoqo7msjiyuhdezzgdu5q

- Region of Operation: Greater China
- Use case(s) to be supported: Medical field data / Blockchain data / Financial data / Public government enterprise data / Entertainment audio and video text data
- DataCap Requested:100Tib

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
As an individual, I have been a student in the blockchain investment space for 7 years. I have been following IPFS & FILECOIN since 2017. And then set up a business in 2018 to follow the growth trend of Web3.0.

As a company, Beelantern has been doing the most professional research reports and solutions for investors who want to enter the Filecoin ecology. one of Beelantern's products - Filnest is a visual filecoin operation and maintenance platform, helping miners can be more Beelantern also collaborates with H3C & Lenovo and other international storage solution providers to research storage solutions in Filecoin scenarios. beelantern has served 6 Filecoin nodes:,Meanwhile, Beelantern has been exploring the combination of Filecoin and traditional data market, such as storage of medical data and open government enterprise data.
```
More information:
Beelantern Miner ID: t015877,t042855,t023678,t015885,f085435,f085437
Slack: @8hfq
Participated in Testnet/Calibration/SR1/SR2.
Release of visual O&M product: Filnest
### Stake Exp

**Comment by jnthnvctr** [comment]
Hi! Thank you for the submission, but this application is unfortunately incomplete. There will be future opportunities to apply to be a Notary - please feel free to update this app and reopen when the next wave of Notaries are being selected!
