### ISSUE TITLE
Next Governance Call: Tues August 23 8am PT / 3pm UTC -and- 6pm PT / 0100 UTC (Wednesday)

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#596]
The sixteenth Notary Governance Call of 2022 will take place on August 23 8am PT / 3pm UTC -and- 6pm PT / 0100 UTC (10th)

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:
Recent Proposals
Community Discussions

If you would like to add an item to the agenda, please request via a comment in this issue.

Application presentation times will be allocated for 5minutes. If you would like to share your project you must have your request submitted in this issue at least 48hrs before the Governance meeting.

Requests to showcase an Application or LDN should be submitted via a recorded video following the guidance in (https://github.com/filecoin-project/notary-governance/issues/537)

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
(https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D

**Comment by kevzak** [comment]
Hi @Kevin-FF-USA , I'll be OOO on 23rd, but see this slack update with details that I'd love to be reviewed on the calls. 

https://filecoinproject.slack.com/archives/C03MHVAABFV/p1661111315018619

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/602

**Comment by scharfstein** [comment]
Good afternoon @Kevin-FF-USA ... we would like to add a topic to this call - thank you!

For Project Bearded DataCap 

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/326
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/327

We are requesting more datacap as per this comment: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/327#issuecomment-1191761175

We can talk over these slides, if required: https://docs.google.com/presentation/d/1lEYya9d2xMQzVaUAync1f-ldFcJqJRg9D0xz0G5z4mg/edit?usp=sharing

The goal is to get feedback on how to complete this project.

**Comment by xxcisco** [comment]
Hello, @Kevin-FF-USA ,  We want to add a topic to this conference call 

about F3 LDN 
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/497

We   will show  F3  for you 

We wish you can agree to our DC as soon as possible

**Comment by Kevin-FF-USA** [comment]
Hi @xxcisco , Hi @scharfstein ,
Always happy to add items onto the agenda, reason these 2 requests didnt make it onto this weeks call was the time frame submitted. I finalize the agenda/deck in the day prior. Earlier you can submit the better.  

@xxcisco  - Have you recorded a video presentation?

**Comment by Kevin-FF-USA** [comment]
Recordings of the August 23rd Notary Governance Calls: https://youtu.be/i1AFQYKIpFY
