### ISSUE TITLE
Proposal: Project CognoCloud - 500 TiB Dataset / 2 PiB DataCap

### ISSUE THREAD

**Issue by jessie8o8** [filecoin-project/notary-governance#599]
## Project Description
We propose the onboarding of 2 PiBs of data to the Filecoin Network to help one of the first ESPA participants onboard their very first customer who provides MSP services to major Canadian and international firms.

Original Application: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/388

## Client Background
Client we are representing : CognoCloud
Site: https://cognocloud.ca/
Founded: 2014
LinkedIn: https://www.linkedin.com/company/cognocloud/about/

ESPA Participant that sourced the client: Moose Mining LLC
Cohort: One
ESPA Cohort One Testimonial Video that features Moose Mining: https://youtu.be/dRD0OIxjPeU?t=136

## Transparency in KYC
CognoCloud is an Ontario-based company and leading provider of disaster recovery as a service, data center design, virtualization & hyperconverged infrastructure. Founded in 2014, the company specializes in modern day enterprise IT infrastructure to allow other companies to grow and scale while protecting the environment from any disasters that may occur. They work to solve problems of modern day data centers at the enterprise scale. The organization serves major companies such as EY, Red River Mutual and AccessSMT.

We are completing a KYC process with CognoCloud with the help of trusted community notaries. Additionally, an email thread has been forward to [filplus@fil.org](mailto:filplus@fil.org) to validate our relationship with senior leadership at CognoCloud.

## Dataset
CognoCloud protects its significant volume of data in the form of VMDKs and VHDs. Because it is pertinent to the privacy of the customers of CognoCloud, these data should remain private and are considered confidential.

## Why is it useful to the Filecoin network?
CognoCloud further proves the value of Web2 use cases on our Web3 storage platform. They provide disaster recovery and protect their customers from ransomware, data loss, and hardware failure. Its data is not only useful to CognoCloud, but also their end customers and the data marketplace itself.

Another reason why CognoCloud is useful to the Filecoin network is because they are one of the first private clients willing to work with the ESPA community’s newly trained storage provider participants (Moose Mining, Lucky Strike, etc.), which increases the diversity of SPs willing to support real enterprise and FIL+ data beyond the usual few entities who have recently been dominating LDN requests.

## Data Storage Plan
4 copies of the 500 TiB dataset will be distributed to 4 SPs with one copy to each: PiKNiK and 3 North American ESPA Participants (MooseMining, HPI3, Ideal Storage)

## Notaries that Support the Project [person / org / region / Github app]

The following notaries have expressed support in the original application via emote or comment:
Wijnand / DCENT / Speedium, DCENT BV / Europe / https://github.com/filecoin-project/notary-governance/issues/414
Meg Dennis / Holon / Oceania & Global / https://github.com/filecoin-project/notary-governance/issues/460
Julien / Twinquasar/ Europe / https://github.com/filecoin-project/notary-governance/issues/468
Kobby Chen / Fenbushi / Greater China / https://github.com/filecoin-project/notary-governance/issues/418
Fei Yan/ kernelogic / North America/ https://github.com/filecoin-project/notary-governance/issues/409

Answer to [Galen's Questions](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/388#issuecomment-1218261050)
For this application we are acting as representatives of the Cognocloud (confirmed with an email thread forwarded to [filplus@fil.org](mailto:filplus@fil.org)) . CognoCloud was sourced by MooseMining, an ESPA cohort one participant, and have asked PiKNiK for help with the datacap process. The client has requested the data remain in North America, thus the SP's chosen are all in North America.

Yes, PiKNiK is a notary but we are not acting a notary on this application.

**Comment by jessie8o8** [comment]
Hi @galen-mcandrew and @raghavrmadya. Let me know what else is needed to move forward with this :)

**Comment by Kevin-FF-USA** [comment]
Hi @jessie8o8 ,
Since this information is now included in the comments section of the LDN application, I'm going to close out this issue.  Should there be additional comments,input needed, using the https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/388 would be the best source to reach the highest audience.
