### ISSUE TITLE
Proposal: Global Computer -  5 PiB Datacap

### ISSUE THREAD

**Issue by Kormakornchip** [filecoin-project/notary-governance#601]
## Objective
The objective is to develop use cases for enterprise clients to take advantage of the filecoin network. We are exploring different possibilities and services we can offer to clients. We have two immediate objectives. The first is to archive complete backup datasets and the second is to store historical logs from a large number of network devices. These logs will be used for forensics in the case of a breach.

## Project Description 
The data is being stored on the filecoin network because of the immutability of the data set once it is stored on the network. As we all know ransomware attacks are devastating to business and the hackers usually don't strike until they have complete control of the backups to ensure clients have no other alternative but to pay the ransom. A data set on the filecoin network could not be ransomware encrypted and therefore would provide a full proof recovery strategy.

The second project is to consolidate a massive amounts of telemetry logs from intrusion detection, firewall and routers and store them on the filecoin network. The thinking is that breaches sometimes take very long to discover and the problem often faced is that the historical data needed to determine pathways used by hackers is no longer available for forensics. We believe the availability of such data can prove to be invaluable in solving this problem.

## Data Set
The data sets will be backups in one case and logs in the second example

## Transparency in KYC
The clients are heterogenous distribution of attorneys, accountants, manufacturers, health care facilities etc… 
Because the data will contain a complete backup of a client’s enterprise system it is necessary to protect the confidentiality of the information and as such, we will encrypt the contents.
As an IT provider for these organizations, we can attest to the legitimacy of these clients. All are respectable businesses that have been operating for years and are managed by good people.
With respect to the security logs, these will contain information that in turn could be used to reverse engineer the topology of the environment. Our clients will want these encrypted as well.

## Notaries that Support the Project 
As this proposal is being reviewed, we are actively contacting Filecoin Plus notaries in the filecoin slack to explain and gather support for this proposal. 
## Online Presence 

Website: global-usa.com

Reference Link:  https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/522

**Comment by Kevin-FF-USA** [comment]
Hi @Kormakornchip ,
Reads like this proposal is providing additional information on your LDN application (522).  Unless there is something I'm overlooking for proposing changes to the Governance process, recommend posting this information in your LDN. That way, the Notaries can comment, question, and approve.

**Comment by psh0691** [comment]
I'm all for storing personal encrypted data in Filecoin. However, there is a lack of confidence in the data you store and there is a risk of abuse of the data cap. 

As a countermeasure against this, it will be solved by matching public data storage and equity. 

In other words, when trying to store personal data on a file coin network, the customer pays the SP for the storage, and the SP deducts the amount received from the customer (1 to 5X, not 10X) to avoid increasing or decreasing File Plus's compensation for FilePlus.
