### ISSUE TITLE
Next Governance Call: Tues September 06 8am PT / 3pm UTC -and- 4pm PT / 1100 UTC 

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#603]
The seventeenth Notary Governance Call of 2022 will take place on September 06 8am PT / 3pm UTC -and- 4pm PT / 1100 UTC 

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:
- General Timelines for the upcoming 4th Elections
- Recent Modifications and FIPs
- Trust and Transparency Updates
- Issues brought up from the Community for Discussion

If you would like to add an item to the agenda, please request via a comment in this issue.

Application presentation times will be allocated for 5minutes. If you would like to share your project you must have your request submitted in this issue at least 48hrs before the Governance meeting.

Requests to showcase an Application or LDN should be submitted via a recorded video following the guidance in (https://github.com/filecoin-project/notary-governance/issues/537)

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
(https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/608

**Comment by Kevin-FF-USA** [comment]
As a reminder, tomorrows 2nd Governance call will be taking place at the normal time slot of 4pm PT / 1100 UTC  (NOT 6pm//0100UTC)

**Comment by Fatman13** [comment]
Are there any reason why we are not sticking to the old time slot?

**Comment by AlanGreaterheat** [comment]
We think 09:00 Singapore time is a good time for most Asian miners.

**Comment by GaryGJG** [comment]
Missed this meeting, when I login at 9:00am UTC+8....

**Comment by Fatman13** [comment]
Thanks for the reply! @Kevin-FF-USA 

> Feedback was an even split on if the new time should be maintained or reverted

Which channel are people sending feedbacks? I can see that on Github most people are still in favor of the August time?

**Comment by Kevin-FF-USA** [comment]
@Fatman13,
Good flag/question.
We ran polls during the August 9th, and again on August 23 calls to get a check in from the people who were attending the 2nd time slot. That is where the split is coming from. There are more comments on the Github issue, but just one of the data points collected and doesnt capture all of the feedback.  Its good to note this isnt finalized or set in stone. During the upcoming 4th Election cycle, we will be asking each applicant their ideal time slots for the two Notary calls and setting a time that is selected by the majority of the active participating Notary community.

**Comment by Kevin-FF-USA** [comment]
https://youtu.be/9W5Kp5R-iKY
