### ISSUE TITLE
Next Governance Call: Tues September 20 8am PT / 3pm UTC -and- 4pm PT / 1100 UTC

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#609]
The eighteenth Notary Governance Call of 2022 will take place on September 20 8am PT / 3pm UTC -and- 4pm PT / 1100 UTC

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:

   
    Recent Proposals and FIPs
    Trust and Transparency Updates
    Issues brought up from the Community for Discussion

If you would like to add an item to the agenda, please request via a comment in this issue.

Application presentation times will be allocated for 5minutes. If you would like to share your project you must have your request submitted in this issue at least 48hrs before the Governance meeting.

Requests to showcase an Application or LDN should be submitted via a recorded video following the guidance in (https://github.com/filecoin-project/notary-governance/issues/537)

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
(https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D

**Comment by sufyio** [comment]
@Kevin-FF-USA Hi， Kevin，I want to join this governance call.
Link to the application: https://filecoin-project/filecoin-plus-large-datasets#974(HuiDi-Data）

An organization represented: HuiDi Technology (Shanghai), It is a technology company focusing on providing customers with innovative application development and complete technical solutions.   Relying on years of core technology precipitation and rich project development experience, it is committed to providing customers with the best software products and services; with the help of a "multi-speed IT" strategy, Enterprises realize the "same frequency resonance" of IT and business.  

Project “Data Hub” 
It is a data service project of Huidi Technology for commercial companies and individuals.
- Long-term data storage and transmission 
- Artificial Intelligence and machine learning training
- Historical data rollback
- Video Content Analysis

Location: China

Length of time application has been open: 1 month.

Link to your recorded video: https://drive.google.com/drive/folders/1ArzkV3fDJRbUUybB6mOunb3LlPmcShgX

**Comment by Carohere** [comment]
Hi Kevin, I would like to get more community inputs for #587 #602 #608(especially). If it's too much for time concerns, would it be possible to book a meeting with the governance team? Thanks!

**Comment by kevzak** [comment]
Hi @Kevin-FF-USA I'd like some time to review the E-Fil+ Pilot Proposal: https://github.com/filecoin-project/notary-governance/issues/611

**Comment by Kevin-FF-USA** [comment]
https://youtu.be/giuHjAZogFc
