### ISSUE TITLE
Notary Application: cdcdx

### ISSUE THREAD

**Issue by cdcdx** [filecoin-project/notary-governance#610]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: cdcdx
- Affiliated organization: x-pool
- On-chain address to be notarized (recommend using a new address): f1z6cibrwkwmwqmcgar2puiokezo6drvswi4ymhxy
- Region of Operation: Greater China
- Use case(s) to be supported: Web 3.0 / Decentralized Applications, User Content (Personal Storage, User Generated Media), Media & Entertainment
- DataCap requested for allocation (10TiB - 10 PiB): 1PiB

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Founded at 2020-08, aimed to play as an important role of web3 industry. We found IPFS at 2016 when we're development some large scale P2P storage infrastructure for telecommunication organization. After that we research IPFS deeply. Then at 2020, we start current organization beginning with Filecoin mining. We develop HA miner cluster and HA lotus cluster based on official lotus version, and integrate S3 storage as the persistent storage. We plan to open source those to community but it's really a huge work and need S3 storage to support http multi range header.

- f01279, f09693, f01210520, f0883083
- Active member in Community since Nov 2020
- Selected as Slingshot 2 reviewer
- https://github.com/XbeautifulTomorrow
- Take part in the mainet parameter setup
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
4000000 FIL
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- Slingshot 2 reviewer
- Helping miner through slack and github.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
1.Open sourced wallet encryption scheme to the community to improve the security of private keys.
https://github.com/filecoin-project/lotus/pull/8558
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Founded at 2020-08, X-Pool is a Filecoin cluster operator based in China. We have 20 empolyees currently and run several miner nodes. Moreover, we build our cloud infrastructure combined micro service and block chain.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Please answer here.
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Please answer here.
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
1.Open sourced the sector recovery solution to the filecoin community on September 13, 2021. 
https://github.com/cdcdx/lotus/commits/sector-recovery 

2.Open sourced the wallet encryption solution to the filecoin community on April 27, 2022. 
https://github.com/cdcdx/lotus/commits/wallet-security 
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Web3.0 Application
Media & Entertainment
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
| Factors | Details | Weight |
|--------|------------------------------------------------------------------------|----|
| Real Data to Filecoin	| The data should be from application which can store real data to Filecoin | 50% |
| Valuable | The application which provide the data should be valuable to the society | 30% |
| Client Ability | Client who was not able to complete deal process will lost their quota, inversely their quota will increase | 20% |
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We have a KYC work flow for the client. Client need to sign a commercial terms with us before they get the quota. The quota of the client will be increased step by step, until the client prove they meet all the requirements.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
- KYC is required for client
- Allocate quota step by step
- Sample data review
- Trial application to prove things all good
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
- Review deals history and data cid
- Sample check the data content
- Review deals successful rate
- Sample check the data allocation of miner
- Sample check the data copies
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Public
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Via a github repo at beginning. I think later we'll have a better tools for easy checking.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
2 work days
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
No
```

**Comment by raghavrmadya** [comment]
Hi, can you share how you are going to maintain the lines between your role as a notary and client? I can see that you have an active LDN and a previous one which was closed due to no response. - https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/436

**Comment by cdcdx** [comment]
> Hi, can you share how you are going to maintain the lines between your role as a notary and client? I can see that you have an active LDN ([filecoin-project/filecoin-plus-large-datasets#696](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/696)) and a previous one that was closed due to no response. - [filecoin-project/filecoin-plus-large-datasets#436](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/436)

Yes, I applied for them all, ([filecoin-plus-large-datasets#436](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/436)) no response is Because waiting for a reply is too slow and long, I forgot when I waited, and it was closed when I found it, so I used ([filecoin-plus-large-datasets#696](https://github.com/filecoin-project/filecoin- plus-large-datasets/issues/696)) Reapply.
Regarding the line between notary and client:
1. Self-transaction is prohibited: Notaries should not assign DataCaps to clients whose private keys they control, and can publicize the miners’ nodes and IPs of the notaries in advance;
2. Publicity of certification behavior: All projects and clients approved by the notary public are publicized, accepting community supervision, punishing or canceling notaries who have fraudulent behaviors;

**Comment by Kevin-FF-USA** [comment]
Hello @cdcdx ,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Please email NOTARYELECTION@FIL.ORG from the email account linked to this GitHub account. *The email MUST COME from the same account you used 

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Are you applying as an individual or Organization
3. Your Country of Operation
4. The updated SLA participation Level (https://github.com/filecoin-project/notary-governance/issues/630) 
5. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
6. Link to this GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by cdcdx** [comment]
Hi @Kevin-FF-USA ,
Thanks for your reply.
An email has been sent to NOTARYELECTION@FIL.ORG from [cdcdx888@gamil.com](mailto:cdcdx888@gamil.com), please check it.

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by raghavrmadya** [comment]
What's your connection with https://github.com/filecoin-project/notary-governance/issues/607. Also provide the address to prove that you have the amount of FIL you mention

**Comment by cdcdx** [comment]
> What's your connection with #607. Also provide the address to prove that you have the amount of FIL you mention

It has nothing to do with 607, and all the information filled in is true.
Some nodes and wallets have been selected, and can continue to be provided if necessary.
[node.txt](https://github.com/filecoin-project/notary-governance/files/10146792/node.txt)

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[610.pdf](https://github.com/filecoin-project/notary-governance/files/10159320/610.pdf)

**Comment by Kevin-FF-USA** [comment]
@cdcdx 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
