### ISSUE TITLE
Large dataset multisig request - CognoCloud

### ISSUE THREAD

**Issue by raghavrmadya** [filecoin-project/notary-governance#617]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: LDN CognoCloud
- Affiliated organization: CognoCloud
- On-chain address to be notarized (recommend using a new address): f2xafwr26rlc6j2x57snxwuytxtv3lfpqyclaytgi
- Region of Operation: N/A
- Use case(s) to be supported: [[Please select from [here](/notaries/templates/README.md#definitions)]](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/388)
- DataCap requested for allocation (10TiB - 10 PiB): 2 PiBs

**Comment by raghavrmadya** [comment]
## Request Approved
#### Address
> f01924203
#### Datacap Allocated
> 2PiB

**Comment by dkkapur** [comment]
doing a quick audit, this should explicitly not be signed. the initial 2 PiB did go through, and client has received their first allocation successfully https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/388.

**Comment by dkkapur** [comment]
adjusting labels, will follow up with RKH to cancel second tx.

**Comment by dkkapur** [comment]
actually looks like tooling duplicated this request already once, so DataCap was topped up back to 2 PiB after a 50 TiB allocation. Should be set to 1998 TiB. Could pursue explicit override with RKH cc @galen-mcandrew for your thoughts as well.

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f2xafwr26rlc6j2x57snxwuytxtv3lfpqyclaytgi
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzacec4rzi4zbs36gi5o42kf527wbmb4iw5nngwrutcqu5mw3dqmytzuq
