### ISSUE TITLE
Proposal: Increase LDN weekly allocation limit

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/notary-governance#619]
## Issue Description
Currently the total amount of LDN is between 500 TiB and 5 PiB, there is an existing issue #594 discussing to increase it to 25PiB.

In this issue I want to propose increase the recommended weekly allocation from between 1-100TiB to 1-1000TiB.

In reality when working with larger LDNs like 5PiB ones, having the weekly allocation capped at 100TiB is ineffective. The first allocation would be 25TiB, then 50TiB, 100TiB etc. The whole process of allocate 5PB with 100TiB weekly will need at least 8 rounds of signing. Sometimes when duplicate proposal bug happens, it will take even more rounds.

Each top up will require several business days for notaries to check and approve, this blocks the onboarding stream and increase the work of notaries.

## Impact
Reduce TTD, improve client onboarding experience, reduce notary repetitive work effort.

## Proposed Solution(s)
Increase the recommended weekly allocation from between 1-100TiB to 1-1000TiB.

## Risks and mitigations 
There are datacap abuses and large effort has been put together by PL to fight them. I think giving a large weekly allocation to all new clients indeed increase the difficulty of fighting abuse. 

I recommend RKH utilize the full weekly allocation amount with discretion.

## Related Issues
#594

**Comment by Chris00618** [comment]
There are lots of proposals recently. Why can't we use voting tool to make quick decisions and let the REAL clients participate in making rules related to themselves? This can reflect the spirit of web3.

**Comment by Kevin-FF-USA** [comment]
#620

**Comment by jhookersyd** [comment]
Holon can seal at 200TB per day, turning our system on and off due to data cap running out is a waste of time.
If want to scale real client data to EIB level 1000TiB needs to happen. Thanks all!

**Comment by raghavrmadya** [comment]
@Chris00618 usually we don't do a poll right away as we want to give the community an opportunity to assess the specifics and recommend any changes to the proposal.

**Comment by raghavrmadya** [comment]
As a governance team member who often triggers allocation requests, I can see the benefit of increasing the recommendation. 

From a Trust and Transparency perspective, this does not make a big difference as the weekly allocation is a guideline and we already have LDNs that have more than 100TiBs weekly allocation of DataCap.

**Comment by salstorage** [comment]
Seal Storage SP, supports this LDN to increase weekly allocation limit to 1000TiB
Seal Storage SP sealing power is approx. 150TiB's per day and increasing rapidly, the 50,100,200TiB DC tranches are easily exhausted adding unnecessary administrative overhead to sealing operations.
Furthermore additional administrative overhead is required from a Notary signing perspective. As an example 50/100/200TiB tranche would require 3 notary approval touchpoints in the space of 48hrs.
Thanks

**Comment by jamerduhgamer** [comment]
I also agree that the weekly allocation limit should be increased. However, we need to make sure that we have a more refined KYC process in place (which I know is also in the works) as there will be more potential for abuse with larger tranches.

For example, a client could abuse the datacap and seal all 1000 TiB to one SP before we can catch them and stop approving the next few tranches. Though this wouldn't be a problem if we had a way to remove datacap (which I believe is also in the works / in discussion).

**Comment by Patapon0702** [comment]
I also agree that the weekly allocation limit should be increased. The lower storage cost , the more organizations or individuals will be attracted. 
The more participants in DC, the higher  transfer rate it will be. It will set off a chain reaction in the filecoin ecosystem.
