### ISSUE TITLE
Proposal - Cancel Dec 22nd Governance call and reconvene Jan 5th

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/notary-governance#62]
Given we've had two back to back governance calls (the latest being Dec 16th - 12am UTC), and given the upcoming holidays in parts of the world - I propose we treat this last governance call as having pulled forward the meeting scheduled for Dec 22nd. 

This would mean our next governance call is scheduled for Jan 5th, 5pm UTC.

**Comment by rjan90** [comment]
Sounds good! +1 for the proposal here
