### ISSUE TITLE
Notary Application: Bitmain Technologies Limited 

### ISSUE THREAD

**Issue by HeliosAI** [filecoin-project/notary-governance#621]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Allen
- Affiliated organization: Bitmain Technologies Limited
- On-chain address to be notarized (recommend using a new address): f3qkxwggmup3troacakwz6u6f3u2cytfp5rkf3qxtksbruoffahyhd37krbosa4j2oywzql3vyqdvyu2skjqea
- Region of Operation: Greater China
- Use case(s) to be supported: General (user content, enterprise data, scientific data etc.)
- DataCap requested for allocation (10TiB - 10 PiB): 10 PiB

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Bitmain has been paying attention to the development of FIL since 2017. We believe that Filecoin is an indispensable part of the next-generation Internet in storage and established our own mining farm in 2021. The mining farm currently has a scale of 10PiB. We have cooperated with a few of Filecoin software service providers to help them succeed.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
We have about 1000,000+ Fil in the Cobo wallet. Treasurer's wallet ID: f01884537 and f01707111. 
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Bitmain has been paying attention to the development of FIL since 2017, and established our own mining farm in 2020. The  mining farm currently has a scale of 10PiB. We have cooperated with a few of Filecoin software service providers to help them succeed.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None. 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Bitmain is the world's leading blockchain server manufacturer. Its brand ANTMINER has long maintained a leading position in technology and market in the industry, and its customers cover more than 100 countries and regions around the world. The company has subsidiaries in the United States, Singapore, Malaysia, Kazakhstan and other places.
Bitmain has a unique computing power and energy efficiency ratio technology to provide the global blockchain network with the best computing power infrastructure and solutions. Since its establishment in 2013, it has reduced the computing power and energy efficiency ratio of its products by two amounts class.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Bitmain website: https://www.bitmain.com
Bitmain Official Youtube Account: https://www.youtube.com/c/Bitmain_official  , 6880 subscribers
Bitmain Official Twitter Account: https://twitter.com/bitmaintech  , 103,000 subscribers
WeChat Official Account: 比特大陆BITMAIN, 18 articles
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://news.bitcoin.com/cryptocurrency-investment-platform-hashfrog-partnered-with-bitmain-and-antpool-to-enter-the-kda-ecosystem/
https://www.bitmain.com/news
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Bitmain Official Youtube Account: https://www.youtube.com/c/Bitmain_official  , 6880 subscribers
Bitmain Official Twitter Account: https://twitter.com/bitmaintech  , 103,000 subscribers
Linkedin: https://www.linkedin.com/company/bitmain , 14,499 subscribers
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
we plan to support multiple use cases:
- 30% - user content (personal user storage)
- 30% - scientific datasets (AI training, geological data, autonomous driving) 
- 40% - media & entertainment (video & music)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The purpose of datacap is to ensure that customers are storing real and valid data in right way. we need to have a rigorous review program on whether client have that much data and how to store this data to assess whether they should be granted credits.
The following Rubric will be the primary guideline we use when evaluating a client and determining their DataCap allocation.   
You can see it: https://docs.google.com/spreadsheets/d/1Y9c3ERpzGSfzINl3FuuOI6owOStMIGSaUjyx9GUZG5M/edit#gid=0
And each client needs to fill out this complete questionnaire when applying datacap:
https://www.wjx.cn/vm/mz77Nzt.aspx
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hardware wallet will be used to store the keys associated with the DataCap allocation address securely. 
We set up a Filecoin working group dedicated to communicating with the community and managing account. There are 5 people in the working group. 
github account and hardware wallet account will be held by two people respectively.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
All clients’ applications must be strictly reviewed. The more datacap applied, the stricter the review. Referring to the practice of filecoin notary application, the datacap is determined based on the client’s background investigation. It mainly involves the following:
Establishment time/Registered Capital/ Organization size and regions/Individual Reputation/Miner Decentralization/Diversity of Distribution Region/Track Record.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Through the filplus.info website it is easy to display if a client deals with a miner. I will check regularly.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All my allocation decisions will be conducted publicly in the Github repository ( https://github.com/filecoin-project/filecoin-plus-client-onboarding ).
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub repo.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
There can be 12+ hours per week on average.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None.
```

**Comment by Kevin-FF-USA** [comment]
Hello @HeliosAI,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Please email NOTARYELECTION@FIL.ORG from the email account linked to this GitHub account. *The email MUST COME from the same account you used 

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Are you applying as an individual or Organization
3. Your Country of Operation
4. The updated SLA participation Level (https://github.com/filecoin-project/notary-governance/issues/630) 
5. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
6. Link to this GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[621.pdf](https://github.com/filecoin-project/notary-governance/files/10159323/621.pdf)

**Comment by Kevin-FF-USA** [comment]
@HeliosAI 
Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.  

Thank you for the hard work your application represents. 

Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.
