### ISSUE TITLE
<KABAT> - <Motowizja> #928

### ISSUE THREAD

**Issue by FILDCKabat** [filecoin-project/notary-governance#622]
## Application information 

Link to existing LDN application(s)
- _link to applocation(s) in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues_928
  
Are you the data owner?
- [x] Yes
- [ ] No

Is the data private i.e., encrypted or not meant to be retrieved by anyone else on the network?
- [x] Yes
- [ ] No

## Data owner information
- Data owner: AGENCJA PROMOCJI MOTORYZACJI A.P.M.AUTO / Motowizja Sp. z o.o.
- Data owner's website: https://motowizja.pl/
- Data owner's social media account(s): https://www.facebook.com/motowizja

### Data owner description 
_Details on the data owner background, source of funding, etc._
AGENCJA PROMOCJI MOTORYZACJI A.P.M.AUTO makes motorsport movies for over 20 years, they have been doing motorsport content for different televisions and also for private teams, as well as for YouTube's channels. For today they make realizations mainly for Motowizja televisions which is the biggest motorsport TV in Poland. 
I will clarify with the customer while the next meeting who is going to store files from a legal point fo view, Agencja Promocji, who manufacture them or Motowizja who is a television.

## Project Description
They would like to store big archives of motorsport movies. 

### What is the motivation behind onboarding this data to Filecoin? 
safety and cost 

### What organizations are involved in this project? Sources of funding, SPs partnering in onboarding, other service providers, etc.?
Kabat/FILDC => SP

## Transparency in KYC
_If you are not the data owner, please email filplus@fil.org with you and the data owner on a thread so at least the Fil+ governance team can act as a lightweight KYC check._

Are you going to offer NDAs to notaries?
- [ ] Yes
- [x] No
  
## Dataset description 
_What is being stored on the network? Please provide as many details as possible on the dataset and its size._
it is going to be stored movie files of over 1PiB, going tbc in 1st week of Oct

### Why is it useful to the Filecoin network?
_Please share details on how your project may use Filecoin in a novel way, extend or experiment with different use cases, or result in useful development in the ecosystem._
Customer is open for blockchain technology because of safety and see it as a perfect solution to store over 20Y of motorsport movies making 
  
## Storage needs

Is the data to be stored in a single region, either due to geopolitical constraints or data owner policy?
- [x] Yes
- [ ] No

### Which SPs will you/the data owner be working with to store the data? 
KABAT/FILDC f01127678

_If all the SPs have not been chosen at the time of issue submission, feel free to edit and update the form as they are chosen. If you need support on finding reputable SPs, please check out filgram.io, filrep.io, plus.fil.org/miners, or Filecoin Slack channels: #fil-plus, #fil-deal-market_
  
| SP ID | SP org | SP region |
| --- | --- | --- |
| _minerID_ | _org_ | _region_ |

### How were these SPs identified?
_Answer here_

## Notaries that support the project 
 _Notaries perform KYC/KYB to validate the legitimacy of data and organizations. To find supporting notaries please view the list of [round 3 notaries](https://github.com/filecoin-project/notary-governance/tree/main/notaries) and post your LDN application in the Filecoin slack channel #fil-plus-application-review. Feel free to update the form as you gain support over time and more notaries are willing to support your application._

| Notary name | Notary org | Notary region |
| --- | --- | --- |
| _name_ | _org_ | _region_ |

**Comment by kevzak** [comment]
Keeping a copy here: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/928#issuecomment-1312016207

**Comment by kevzak** [comment]
Data Storage Plan

Five full replicas, total of 25 PiB of Datacap

Primary SP Partner:
FILDC, receiving 5 PiB of Datacap for one full replica,
Location: Lodz, Poland, Europe

1 additional SP from EU / North America / Australia receiving 5 PiB, for the 2nd full replica
Many SPs around the world except Russia and Ukraine
Partial replicas, size: 100-1000TiB
Max 2 copies per SP if stored on different miners / locations.

Unsealed copy is not needed.
