### ISSUE TITLE
Next Governance Call: Tues October 18 8am PT / 3pm UTC -and- 4pm PT / 1100 UTC

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#624]
The twentieth Notary Governance Call of 2022 will take place on October 18 8am PT / 3pm UTC -and- 4pm PT / 1100 UTC

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:

Notary Elections
Recent Proposals 
Issues brought up from the Community for Discussion

If you would like to add an item to the agenda, please request via a comment in this issue.

Application presentation times will be allocated for 5minutes. **If you would like to share your project you must have your request submitted in this issue at least 48hrs before the Governance meeting**.

Requests to showcase an Application or LDN should be submitted via a recorded video following the guidance in (https://github.com/filecoin-project/notary-governance/issues/537)

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
(https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D

**Comment by kevzak** [comment]
@Kevin-FF-USA I'd like to review https://github.com/filecoin-project/notary-governance/issues/625

**Comment by Xingchi-Media** [comment]
We want to share our LDN application [#1051](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1051)

**Comment by Xingchi-Media** [comment]
Hi @Kevin-FF-USA 
**LDN demo video**
https://drive.google.com/file/d/1whxzY2DK5i0TkrAgWO7-5NhfY0JzuqkU/view?usp=sharing
**PPT**
https://drive.google.com/file/d/1u4r3MUWTeleeDM_cF3qb-Tr_4pVz98DR/view?usp=sharing

> We want to share our LDN application https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1051

**Comment by Kevin-FF-USA** [comment]
Hi @Xingchi-Media ,
I cant seem to locate the video file (but can see the link).
Can you please upload to this folder https://drive.google.com/drive/u/0/folders/1ktv4y1mRxa9kpTWjzQJj5wc2m1t-oaUs?

*have you confirmed for the Agenda tomorrow and will save 5mins for you to answer questions. Its recommended to not use the time to duplicate the content from video, but answer any questions Notaries may have

**Comment by Xingchi-Media** [comment]
Okay, thanks, Kevin
It seems that I still have no permission to upload
<img width="916" alt="image" src="https://user-images.githubusercontent.com/91602385/196333784-409e9e71-2b57-4ee7-88d2-979f68c359fb.png">

**Comment by Kevin-FF-USA** [comment]
#625 
#630

**Comment by Kevin-FF-USA** [comment]
https://youtu.be/iMocCKY0bTc
