### ISSUE TITLE
Modification: LDN Application template - addition of country and industry questions

### ISSUE THREAD

**Issue by kevzak** [filecoin-project/notary-governance#625]
## Issue Description
The LDN application today does not include any specific questions related to the data owner country or industry. 

## Impact
Collecting this additional more specific information will create better application metadata 

## Proposed Solution(s)
Modify template:
- Remove region
- Add country
- Add Industry (with standard drop-down options)
  1. Life sciences/ healthcare
  2. Arts & recreation
  3. Education & training
  4. Environment
  5. Web3/Crypto
  6. IT & technology services
  7. Professional services (legal, consulting, advice)
  8. Government
  9. Not-for-Profit
  10. Financial services
  11. Utilities
  12. Resources, agriculture & fisheries
  13. Construction, property & real estate
  14. Information, media & telecommunications
  15. Transport services
  16. Other

### Timeline
Should be a pretty quick fix. Recommending that we:
- Review for feedback at a governance call
- Add the questions to the template

### Technical dependencies 
- Update the plus.fil.org ux to also include these questions and map to github template

**Comment by simonkim0515** [comment]
This looks great!

**Comment by jamerduhgamer** [comment]
I second the country and industry section!

**Comment by panges2** [comment]
+1 to this, We can use this information to really improve the process in two ways:
- We can make the notary DD process faster by picking a notary from the same region that speaks the same language (maybe we can add language spoken to the applications)  
- We can create a more fair process by picking notaries from other regions to have lower probability of collusion.

**Comment by kevzak** [comment]
feedback from governance call is to add two categories to industry dropdown:
-Web3/Crypto
-Government

**Comment by psh0691** [comment]
Let's include entertainment such as movies, dramas, music videos.

**Comment by bjchend** [comment]
@kevzak @psh0691  I would like to caution that there are some categories of data that may raise copyright issues. Doing so can pose a legal risk to fil.
