### ISSUE TITLE
Modification: [Notary Application] - [Industry Reputation]

### ISSUE THREAD

**Issue by Firefly2020-cloud** [filecoin-project/notary-governance#63]
#In-protocol Reputation
As an Individual, I have been working as an IPFS/Filecoin ecosystem advocate and builder:
- Weekly IPFS/Filecoin/Web3 technical or marketing articles
- Speaker of IPFS/Filecoin/Web3 conferences
- Organizer and lecture of Protocol School Shanghai Chapter
- Contributor of Filecoin protocol and code development via issues/PRs commitments

#In-protocol Security
Security is the first priority and the most important factor of a chain. I, as the key engineer of the China's first generation of secure router, paid a lot of attention on security of the system, and contributed to Filecoin via publicly submitted issues, or privately discussion due to the sensibility of some security issue.
Some of the issues submitted related to security: 
There are some discussion in slack private channel or via email too, e.g. 
- Nondeterministic signature of round winner calculation
- Owner change proposal from security prospective
- determiistic winner of big miners, to drive the winning algorithm change

## External Reputation
Firefly I is a private company founded on July 5, 2018, in HangZhou, China. 
The company is for-profit, and its country of registration is China. 
At the moment, we have over 100 employees working at the HangZhou and Shenzhen headquarters since its inception 2 years ago.

**Comment by jnthnvctr** [comment]
Hi @Firefly2020-cloud  - can you just add this to your Notary application? It'll make it easier to track! We've closed the applications for this wave, but you can always re-open your old one (with these edits as comments!) and we'll update at the next time we open applications!
