### ISSUE TITLE
Next Governance Call: Tues November 15 8am PT / 3pm UTC -and- 6pm PT / 0100 UTC

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#632]
The twenty first Notary Governance Call of 2022 will take place on November 15 8am PT / 3pm UTC -and- 6pm PT / 0100 UTC

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

Tentative Agenda topics will include:

Notary Elections
Recent Proposals
Issues brought up from the Community for Discussion

If you would like to add an item to the agenda, please request via a comment in this issue.

Application presentation times will be allocated for 5minutes. If you would like to share your project you must have your request submitted in this issue at least 48hrs before the Governance meeting.

Requests to showcase an Application or LDN should be submitted via a recorded video following the guidance in (https://github.com/filecoin-project/notary-governance/issues/537)

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
(https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D

**Comment by hugesmartda** [comment]
Hi @Kevin-FF-USA ,We hope to attend this notary meeting to discuss our application [301](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/301). 

We attended a notary meeting on [May 3rd](https://github.com/filecoin-project/notary-governance/issues/513#issuecomment-1112944299) and shared our application. And galen created the [RKH](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/301#issuecomment-1124208818) for our app on May 12th.We haven't found enough notaries to sign us since, and finding an active 2rd notary is too difficult. In September, we approached Fenbushi-Filecoin and asked him to review our app and follow his advice to add something to our app. But we accidentally edited our issue directly. Now that our app can't be signed, what should we do next?

**Comment by Kevin-FF-USA** [comment]
> 

Cc @galen-mcandrew who may know more

**Comment by beegoathz** [comment]
Hi，@Kevin-FF-USA，I want to join this governance call.
Link to the application: filecoin-project/filecoin-plus-large-datasets#1230 (Hangzhou Zilaiyun Network Technology Co., Ltd  - Zilaiyun Design）

Organization represented: Zilaiyun Design focuses on interior design, soft decoration design and furnishings, landscape design, and interior decoration. Its core team was established in 2015; 
in 2020, we established Hangzhou Zilaiyun Network Technology Co., Ltd. 
during the COVID-19 period, we launched a "pure design + self-construction" delivery model to meet customers' needs of individual needs. 
In the past 7 years, with the efforts of the team, the company has produced a total of 10,000+ items, which have been widely praised by customers.

Location: China

Length of time application has been open: 1 month.

Link to your recorded video: https://drive.google.com/file/d/1RWToFm2YkjKleekY66n77xlenwFGm-eX/view?usp=share_link

**Comment by OpenGate01** [comment]
Hi, @Kevin-FF-USA.
Is it available for us to attend this meeting and make a briefly introduce of our notarial application:https://github.com/filecoin-project/notary-governance/issues/673.
It probably will take 5 minutes.

**Comment by cqh2022** [comment]
@Kevin-FF-USA Hi，Kevin，I want to join this governance call.
Link to the application:(https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1236) (Hangzhou Yu Quan Technology Co.）
Organization represented: Hangzhou Yu Quan Technology Co., Ltd 
Hangzhou Yuquan Technology was established in 2018. Faced with the historical mission of building a beautiful China and the increasing public attention to nature conservation in recent years, especially the emergence of problems related to public health such as haze, water pollution and climate change, society is more concerned about environmental safety and sustainable development and expects to learn about it actively; nature's rich biodiversity and the behavior of insects are of great importance to The rich biodiversity of nature and the behavior of insects are very attractive to urban dwellers, and the public is very willing to participate in nature education activities. For children in particular, the alienation between childhood and nature is a major dislocation. It is a new educational concept to allow children to gain a variety of experiences and learn a variety of skills in nature and to achieve an effective connection between children and nature, thus maintaining children's intellectual growth and healthy physical and mental development.
We provide one-stop nature education activities and related nature products for adults aged 30-45 and children aged 6-12 with online sharing and offline experience.
The project includes: 1) an offline experience store model with cross-border cooperation; 2) the construction of the social effect of the brand such as nature classroom on campus and second classroom; 3) an interactive platform for nature education preferences, bringing together high-quality nature education institutions, protected areas and related industries at home and abroad; 4) continuous fun science and wilderness discovery through a large number of short videos to spread nature knowledge and advocate green concepts.
Location: China
Length of time application has been open: 1 month.
Link to your recorded video: https://drive.google.com/file/d/1LZlwTndbWM3C0nE-Sg0vIpHNrDchyARC/view?usp=share_link

**Comment by jacktree7** [comment]
Hi，@Kevin-FF-USA，I want to join this governance call,Please check,thanks!

Link to the application: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1198(Sichuan Jingzhi Education Technology Co.,Ltd.）

Organization represented: Jing career education system belongs to the independent brand of Sichuan Jingzhi Education Technology Co.,Ltd.We Provide online college entrance examination volunteer application, new college entrance examination subject selection, career planning, comprehensive quality assessment, strong foundation plan and other college planning services for more than 9 million college students.

Since 2016, we have provided professional services for more than 3 million candidates nationwide and become an influential career planning and volunteer application platform in the industry. After years of research and accumulation, Jing Career has covered 29 provinces and cities nationwide, with nearly 10,000 registered users.

Location: China

Length of time application has been open: 1 month.

Link to your recorded video: （There are differences in format, the content is the same, a mp4 format, a mov format, if the display can not read, please contact me first, thank you!）
https://drive.google.com/file/d/1__jNTEr0xsTwjnvTL8-NFVVanZ704VqZ/view?usp=sharing
https://drive.google.com/file/d/1WzLedrg-w87s2wHxhqSamLTMRfQpIbER/view?usp=sharing

**Comment by beegoathz** [comment]
Hi, @Kevin-FF-USA Kevin. 

So far, we have no permission to upload videos to this folder

https://drive.google.com/drive/folders/1ktv4y1mRxa9kpTWjzQJj5wc2m1t-oaUs

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/636

**Comment by Kevin-FF-USA** [comment]
Hi @beegoathz 
Give this folder a try: https://drive.google.com/drive/folders/1QxzFyc21JkKkKCuG-WXZNS8wCFO4lWrP?usp=sharing

Otherwise, if you loaded it to a private folder just link here and I'll migrate over on your behalf.  Thanks!

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/631

**Comment by decmob** [comment]
@Kevin-FF-USA  hi Kevin , here is our team to application the LDN : https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1176 ,thanks for your time, and the video https://drive.google.com/file/d/1KzOU4ndpfMhTLz1UKQNI-YIlXo5ofUAB/view?usp=share_link have uploaded to google driver as you mentioned above.

**Comment by fairy-and-flower** [comment]
hello, kevin , this is my company's request of LDN, would you like to see it ? https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1250. 
oh ,right, the video have sent to driver of google, and the number is : #1250. 
thank you

**Comment by beegoathz** [comment]
> Hi @beegoathz Give this folder a try: https://drive.google.com/drive/folders/1QxzFyc21JkKkKCuG-WXZNS8wCFO4lWrP?usp=sharing
> 
> Otherwise, if you loaded it to a private folder just link here and I'll migrate over on your behalf. Thanks!

Hi @Kevin-FF-USA , regarding the 11.15 governor's meeting, we made a meeting process note 5 days in advance, but it looks like all the ones than we applied later are on the meeting, but we are not, do you need us to do anything else?
![9ef01220d3349d6b2ced7e1b42dc086](https://user-images.githubusercontent.com/16235303/202064655-d15c004f-5f41-4e0b-a67a-6a0887cf47e0.png)

**Comment by beegoathz** [comment]
Hi,@Kevin,We found that there may be a little problem with the LDN part of the conference ppt, the video link of LDN1236 hangzhou yuquan belongs to our company (Hangzhou Zilaiyun Network Technology Co., Ltd - Zilaiyun Design).
Screenshots are attached as follows.
![image](https://user-images.githubusercontent.com/16235303/202072161-ac6c59c2-c2f9-4c5b-a7d3-7c26a50e3fe6.png)

------
The video link for LDN 1236 is: https://drive.google.com/file/d/1LZlwTndbWM3C0nE-Sg0vIpHNrDchyARC/view

**Comment by Kevin-FF-USA** [comment]
Hi @beegoathz,
Your application and video was included in the Governance call - then shared with the Notaries and teams to ensure its reviewed.
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/94004586/202456893-a0ffc781-8e2d-49e8-9acb-e6c92102b6b9.png">

**Comment by Kevin-FF-USA** [comment]
https://www.youtube.com/watch?v=1ZbCCXCuIWc

**Comment by beegoathz** [comment]
> Hi @beegoathz, Your application and video was included in the Governance call - then shared with the Notaries and teams to ensure its reviewed. <img alt="image" width="1193" src="https://user-images.githubusercontent.com/94004586/202456893-a0ffc781-8e2d-49e8-9acb-e6c92102b6b9.png">

Hi [Kevin-FF-USA](https://github.com/Kevin-FF-USA)

Hangzhou Zilaiyun Network Technology Co., Ltd - Zilaiyun Design.  LDN#1230
LDN1230 video is  https://drive.google.com/file/d/1RWToFm2YkjKleekY66n77xlenwFGm-eX/view?usp=share_link
or https://drive.google.com/file/d/1LZlwTndbWM3C0nE-Sg0vIpHNrDchyARC/view?usp=sharing (PPT)

Hangzhou Yu Quan Technology Co.  LDN#1236
LDN 1236 video is: https://drive.google.com/file/d/1LZlwTndbWM3C0nE-Sg0vIpHNrDchyARC/view

We found that there may be a little problem with the LDN part of the "15 Nov Fil+ Notary Governance Call" ppt, the video link of LDN1236 hangzhou yuquan belongs to our company (Hangzhou Zilaiyun Network Technology Co., Ltd - Zilaiyun Design).
