### ISSUE TITLE
Notary Application: UII-AI

### ISSUE THREAD

**Issue by micheel394402** [filecoin-project/notary-governance#633]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: uii-ai
- Affiliated organization: https://www.uii-ai.com
- On-chain address to be notarized (recommend using a new address): f14wgtv6f7rpnabjdwlm7pjc74lgidw77dlrwdkxq
- Country of Operation: Greater China
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: [Please select from [here](/notaries/templates/README.md#definitions)]: Medical Imaging and AI
- DataCap requested for allocation (10TiB - 1PiB): 4.2PiB
- Are you applying on behalf of yourself or an organization?: Organization-uii-ai

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
When we were faced with massive amounts of medical image data, the existing storage solutions encountered great problems. Later, we know about Filecoin project, we hoped that Filecoin project. could solve our problems.
Our miner ID is: f0463030, the hashrate is 43.62 PiB
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Sorry, it is difficult to disclose at this time depending on the customer's requirements.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
I knew about Filecoin in 2020, and started learning Filecoin in 2021; I have been trying to find a suitable application scenario for Filecoin. Now we want to store our medical imaging data on Filecoin and try to build a new medical imaging scene based on Filecoin.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Sorry, not yet, I am more of a user for Filecoin.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Shanghai United Imaging Intelligent Medical Technology Co., Ltd. is an artificial intelligence company under United Imaging Medical Technology Group. It was established in Shanghai at the end of 2017 and is an important strategic layout of United Imaging Group in the field of artificial intelligence. The company has brought together a group of top medical AI talents at home and abroad. Relying on the high-performance software and hardware technology platform and resource advantages of United Imaging Group, United Imaging Intelligence has become one of the few in the world that can provide comprehensive services including imaging, screening, follow-up, diagnosis, treatment, and evaluation. A medical AI enterprise with full-stack and full-spectrum intelligent solutions covering all diseases, empowering doctors and medical equipment to improve efficiency, and working with users and partners for a win-win situation, making AI the best partner for users.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://mp.weixin.qq.com/s/-I7uNrvLD0yw9W0IqoRqkQ
https://mp.weixin.qq.com/s/_AgBO2dlQefZVvSQsiyg6w
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://mp.weixin.qq.com/s/PmVfkjxqZSjVT6aaq2Oiug
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://mp.weixin.qq.com/s/PmVfkjxqZSjVT6aaq2Oiug
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
https://uiiaidcm.pek3b.qingstor.com/1.2.156.115186.1.5.159303471752314.1948.20191122090327.19.DCM
https://uiiaidcm.pek3b.qingstor.com/1.2.156.115186.1.5.159303471752314.1948.20191122090327.2.DCM
https://uiiaidcm.pek3b.qingstor.com/1.2.156.115186.1.5.159303471752314.1948.20191122090327.20.DCM
https://uiiaidcm.pek3b.qingstor.com/1.2.156.115186.1.5.159303471752314.1948.20191122090327.21.DCM
https://uiiaidcm.pek3b.qingstor.com/1.2.156.115186.1.5.159303471752314.1948.20191122090327.3.DCM
https://uiiaidcm.pek3b.qingstor.com/1.2.156.115186.1.5.159303471752314.1948.20191122090327.5.DCM
https://uiiaidcm.pek3b.qingstor.com/1.2.156.115186.1.5.159303471752314.1948.20191122090327.6.DCM
https://uiiaidcm.pek3b.qingstor.com/1.2.156.115186.1.5.159303471752314.1948.20191122090327.7.DCM
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
All the customers who use DataCap  are the customers we have served for many years; among these customers, we will choose the top 300 hospitals with a large amount of data to use DataCap.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
All data uploaded to the DataCap will be encrypted asymmetrically, and only we can decrypt the data.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will allocate 1/3 of the DataCap to our top 100 customers, and then the other 2/3 will be used for DCM storage and AI training.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```

The data of these hospitals is comes from the CT/DR of the hospital, so there will be no junk data.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
No.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
No.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
As the company's storage administrator, if the File can be used as our main storage, I will need 2-3days per week to allocate to the file related
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
120GB，most of its is Movies and some dcm files.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L2
```

**Comment by Kevin-FF-USA** [comment]
Hi @micheel394402,

Confirming receipt of your Notary application.  There were some updates to the questions since the final Proposals closed. Can you please include the additional questions in a comment in this issue?

**Comment by micheel394402** [comment]
> Hi @micheel394402,
> 
> Confirming receipt of your Notary application. There were some updates to the questions since the final Proposals closed. Can you please include the additional questions in a comment in this issue?

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
We have nothing relationship with any other existing notaries or their organizations.
```


Is there any other questions I need to answer?

**Comment by Kevin-FF-USA** [comment]
Hello @micheel394402,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Please email NOTARYELECTION@FIL.ORG from the email account linked to this GitHub account. *The email MUST COME from the same account you used 

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Are you applying as an individual or Organization
3. Your Country of Operation
4. The updated SLA participation Level (https://github.com/filecoin-project/notary-governance/issues/630) 
5. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
6. Link to this GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[633.pdf](https://github.com/filecoin-project/notary-governance/files/10159326/633.pdf)

**Comment by Kevin-FF-USA** [comment]
@micheel394402 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
