### ISSUE TITLE
LDN Dataset Application Template – Standardize the answers and adjust questions

### ISSUE THREAD

**Issue by celine3650** [filecoin-project/notary-governance#636]
## Issue Description
The LDN application does not support anything other than text fields for data entry which led to poor meta data quality caused by some basic application formatting issues. There are also a few questions that are outdated and lack the information notaries need to evaluate the clients. The needs to standardize answers and adjust questions are backed up by analyzing results from 600 applications.

## Impact
Standardizing answers using a form vs markdown for LDN application provides better UX experience and reduces the barriers for clients. It leads to better application metadata and more efficient validation to reduce back-and-forth for notary and PL members. 

## Proposed Solution(s)
https://github.com/xinaxu/filecoin-plus-large-datasets/issues/new?assignees=&labels=application%2C+Phase%3A+Diligence&template=large-dataset-datacap-application.yaml&title=%5BDataCap+Application%5D+%3COrganization%3E+-+%3CProject+Name%3E

### Timeline
Apply ASAP after the community agree upon 

## Related Issues
https://github.com/filecoin-project/filecoin-plus-large-datasets/pull/455

**Comment by psh0691** [comment]
Thank you for the improvement.

**Comment by sekimlan** [comment]
Very useful improve.

**Comment by bjchend** [comment]
Can improve user experience, very good.

**Comment by Sunnyiscoming** [comment]
Some advice for this proposal

![image](https://user-images.githubusercontent.com/105098820/202898274-165eb48d-cb07-4268-9f46-2bf908a8f6b8.png)
This item is not required as a necessity.

![image](https://user-images.githubusercontent.com/105098820/202898213-adf05f80-7409-4caf-84b4-7bb3a472c122.png)
Add a question here about the relationship between applicant and organization

![image](https://user-images.githubusercontent.com/105098820/202898449-265d7641-040b-4e02-9519-82b9fb5dbce8.png)

1. Confirm that this is a public dataset that can be retrieved by anyone on the Network or this is a Fil-E dataset.

i.e., public dataset means no specific permissions or access rights are required to view the data
- Public dataset
- Fil-E dataset
2. Remove the second question

![image](https://user-images.githubusercontent.com/105098820/202898011-81ea239a-b84d-4ab6-8107-d61734515a30.png)
To add a standard in the data sample item. To provide at least 10 data samples for each type of data.

**Comment by kevzak** [comment]
@simonkim0515 I would add to this question:
 If you already have a list of storage providers to work with, _fill out their names and provider IDs below_

change end of question to: fill out their names, **city, country** and provider IDs below
