### ISSUE TITLE
Notary Application: Coffee Cloud 

### ISSUE THREAD

**Issue by davidthoms** [filecoin-project/notary-governance#637]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Coffee Cloud
- Affiliated organization:  N/A
- On-chain address to be notarized (recommend using a new address): f14qmuid2b6ne4342m5dk56f4rcr7y5sz4sg5fiwy
- Region of Operation: Greater China
- Use case(s) to be supported:  None at this time
- DataCap requested for allocation (10TiB - 10 PiB): 10 PiB would be preferred, as it would give us more flexibility with projects and supporting partners. 

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
CoffeeCloud has studied IPFS and Filecoin projects since 2019, and participated in the Filecoin Space Race in August 2020 with 12 Miners:
Competition Ranking(Region: Global) | Miner Name | Miner IDs
----------------------------------- | ---------- | --------
11 | Zillion-6Block | f02415, f02633, f02645, f03491, f07990, f08025
15 | Zillion-6Block | f018780, f018781, f018782, f018783, f018784, f018785

With new project developments and optimization projects, we are keen on participating and working with the community, these could be helping with Filecoin Green projects, as well as more traditional Web3 or Data Centre management solutions.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Up to 2022-01–22, the 12 miners who participated in the Filecoin Space Race have tokens at stake about 1,660,816 FIL:
Initial Pledge: 336,655 FIL
Total Reward: 1,324,161 FIL

```
To begin with, we have our current process layout in our GitHub.

How to Guide: https://github.com/davidthoms/.github

Our CC Client form: https://github.com/davidthoms/.github/issues/new?assignees=octocat&labels=data+cap,client+app.,filecoin&template=cc_client_test_application.yml&title=[CoffeeCloud+Client+Application]:+

Ongoing table and bookkeeping process: https://github.com/users/davidthoms/projects/2/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C2629832%2C2629833%2C2629870%2C2629880%2C2629899%2C2630739%2C2630700%2C2629974%2C2629964%2C2630710%2C2630711%5D

Example of ongoing client: https://github.com/davidthoms/.github/issues/8

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As a local Hong Kong start-up, we have been enthusiastic participants in the Filecoin community since 2019. We participated in the Filecoin Space Race in August 2020 and were very successful, after which we continued to participate in the Filecoin mining community. With recent want to take exciting steps into blockchain technology, developing our organization to specialize in decentralized storage and farthing our participation within Filecoin Community and ecosystem. With this in mind, we want to support projects and new technology in Hong Kong, the Greater Bay area, and around the world, helping them take advantage of Filecoin’s unique decentralized storage solutions.

We are trying hard to optimize Filecoin Lotus and related projects for efficient mining, please refer to GitHub projects conducted by our teammates:

https://github.com/zhiquan911/lotus
https://github.com/jobdeng/lotus

They are not only optimizing the Lotus scheduler written in Golang but also the proving subsystem was written in Rust. We are planning to contribute code to the community after testing it completely. We are expanding our team of developers to focus specifically on software and hardware optimization. And more and more manpower we are adding incrementally will support our research and develop applications built on the Filecoin project. We here at Coffee Cloud believe that Filecoin should store useful data for the good of society, consequently, we position new developments and projects towards these goals. 

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Currently, we are participating in the weekly Notary Governance and the enterprise calls. We have coordinated with some small local businesses, but they have paused projects, mid-way through. We have been approached by a couple of projects, but are limited to participate as we want to allocate our Data Cap for local projects in the Greater Bay area and HK, emphasizing centralized storage projects within the Hong Kong technology community.

```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

```
### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```

We are a local dynamic Hong Kong start-up, specializing in Data Centre solutions and maintenance. Our international teams support our clients here, in the Greater Bay Area, providing the ultimate data center management solution. In addition to this, we have solutions specializing in cloud computing, web services and software development. We want to be the go-to source for premium data storage in the Greater Bay Area, supporting Local Hong Kong Organizations, Relocating Chinese Enterprises or other international institutions. We are proud partners of the Hong Kong Blockchain, and look to develop further partnerships within APAC region. 

Coffee Cloud’s reputation has steadily grown over the course of the year, we’ve applied to be a member of the Hong Kong Sciecne and Technology Park incubation program and were accepted. Proudly becoming one of the a rising member of the technology and novation community in Hong Kong.

On top of this, we are keen on developing our outreach programs to work with educations institutions, to help nurture the next generation of technology specialists in Hong Kong. 

Organization: Coffee Cloud Ltd. 
Nature:  Data Centre Solutions
Registration Country: Hong Kong, SAR
Established: August 2021
Size: Under 25 employees 

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website:  https://coffeecloud.io/home
Facebook: https://www.facebook.com/Coffee-Cloudio-100883849079709
Twitter: https://twitter.com/coffeecloud_io
Linked: https://www.linkedin.com/company/76643557/admin/

Address: 
Coffee Cloud Ltd., 
Unit 707, 7/F,
 Building 19W,
 No. 19 Science Park West Avenue,
 Hong Kong Science Park, 
Park Shek Kok, 
N.T., 
Hong Kong

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
```
Limited coverage at this time.

Social Media Channels:
Facebook: https://www.facebook.com/Coffee-Cloudio-100883849079709
Twitter: https://twitter.com/coffeecloud_io

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Paul Wong - 
https://www.linkedin.com/in/paul-wong-99b622210/
David Thoms - 
https://www.linkedin.com/in/david-thoms-3589045b/
https://www.instagram.com/shadowmancer101/
```

```

## Diversity and Decentralization
### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
60% - Media & entertainment (video & music & game)
20% - User content (personal user storage，such as file, photo)
20% - Scientific datasets (Health data, AI training, Meteorology data)

```


# Allocation Plan
## Concreteness of Allocation Plan 
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We will review each individual applicant for the DataCap in detail, as well as review any historical data available. Clients will need to proceed through the verification process below, through parts 1 to 3. Any outstanding problems or issues regarding the clients answers will be given time to clarify. If the answers that raise concerns will be flagged for further review and research. Any not satisfactory answers that the client is unable to verify or provide appropriate clarification will result in the application being dismissed. 

Start Verification Process:
Part 1:
Is the client’s GitHub or Social Account older than 6 Months?
Has the client shown activity on this account over this 6 Month Period?

Part 2:
Is the Client is to answer the following questions
Where are you located? Are you located in the APAC Region? Where?

The client is required to provide the following details:
Name?
Individual / Company? (date established)
The number of employees?
Media Coverage?
Website?
Social links?
Filecoin address?
Region?
Past Projects?

Data Declaration:
Data Source? Where is come from?
Relationship to Data? 

Where are you assigned the data? 
Which miners/miner are you looking to assign it to?

Part 3:
The Client is to provide Clarity on any outstanding information so far presented.

To support this process we have created a reference document, table and monitoring from Form in GitHub that is automatically generated when the prospective client fills it in.
Link to GitHub form (as an issue) :
https://github.com/davidthoms/.github/issues/new/choose
or
https://github.com/davidthoms/.github/issues/new?assignees=octocat&labels=data+cap%2Cclient+app.%2Cfilecoin&template=cc_client_test_application.yml&title=%5BCoffeeCloud+Client+Application%5D%3A+

Review Current Client Applications & details: https://github.com/davidthoms/.github/issues
The form is then listed on GitHub with full transparency allowing for anyone to make notes, comments or recommendations. All client evaluations will be done in public, showing step by step how we are evaluating and grading the data client appropriately. We have a detailed Client Rubric, based on Filecoin’s own review Rubric. 

Please see a link to the Google Doc below:
https://docs.google.com/spreadsheets/d/1TizxLZlAuqRxUEXs5Th3UtvqHa1u26PEEZ8BJosCynE/edit?usp=sharing
This scoring system will be placed under the client application, showing how we are evaluating our clients for the community.

As part of the Data Allocation and Client Review process, we create GitHub projects (which is publicly available). Here:https://bit.ly/3Is45WR

Potential Coffee Cloud Clients would be directed to here to our README file: https://github.com/davidthoms/.github/blob/main/README.md

We wanted to make it clear and easy for clients to apply for data cap and explain a little about how we are monitoring and coordinating things. 

Within the README section of our project (https://github.com/davidthoms/.github/blob/main/README.md), we detailed our bookkeeping process, data monitoring (for ourselves and our clients), as well as our sign off and review process.
All of this we want to be as transparent and clear with the community as possible. We also provided a way for clients to respond and address disputes within each individual application (issue) in our system.
https://github.com/davidthoms/.github/blob/main/README.md

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```

Outside of this 3 step review process, other factors need to be considered when apply for the DataCap. These will be:

1. The DataCap will be mainly allocated to APAC customers, initially with an emphasis on other local Hong Kong and China clients. This allows for easier support and guidance with local teams. Over the coming months our service team will expand further to support even more regions and customers.

2. We will classify customers by 2 methods reputation and scale. 
Scale is broken down into 3 categories:  

Top team customers, 
medium team customers, 
small team/individual customers

Reputation will be broken down accordingly:

A: Establish business/web and social presence. Previous Filecoin Experience. Previous Datacap allocation.
B: Establish business/web and social presence. Previous Filecoin Experience. No previous Datacap allocation.
C: Establish business/web and social presence. No Filecoin Experience. No previous Datacap allocation.
D: Recently establish business/web and social presence in the last 6 months. No Filecoin or Datacap experience
E: Recently establish business/web and social presence in the last 3 months. No Filecoin or Datacap experience

3. Throughout the allocation and use of the DataCap, we will establish a corresponding review mechanism.   Good customers will be rewarded, while a bad customers will be punished and not allocated accordingly. 

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

We built an internal wallet server to store the notarized address with very restricted access control, only our staff with proper permission can access the internal server via a specific machine in the whitelist. The DataCap can only be granted to clients by the notarized address completely controlled by Coffee Cloud. So, it is ensured that the DataCap can not be allocated by others unless Coffee Cloud.

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will work closely with clients while they implement the DataCap, supporting them through every step. In order for clients to use Data Cap, they must variety and agree with specific restrictions and use. 

If they cannot agree to this, or at the initial final stages of review any criteria are not met we pause allocation. We will vet my client according to the process listed above. Looking at:

Clients Reputation (online presence, any reviews) 

Data (type of data they are using, We will vet the data from time to time to ensure it is as agreed)

Diversity and Decentralization, (how and where they are storing it, on which miner)

Allocation Strategy (should provide detailed tools and inspection strategy for inspecting the miners).

Track Record (Able to provide details on any previous projects)

If clients will be recorded and noted upon performance. Any unacceptable behavior will be noted and blacklisted. 

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will monitor and track the use of DataCap strictly. Each assignment will be used to evaluate the clients' reputations, and where they are assigning the DataCap to. This record will be taken into consideration during the review process (as mentioned above).

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, in addition to the DataCap allocation and whole process I recorded publicly on GitHub for review purposes and transparency.  All ongoing projects at different stages can be reviewed here: https://github.com/users/davidthoms/projects/2/views/1?visibleFields=[%22Title%22,%22Assignees%22,%22Status%22,2629832,2629833,2629870,2629880,2629899,2630739,2630700,2629974,2629964,2630710,2630711] 

All communication with Client will be flagged shown in GitHub for community review. 

Coffee Cloud colleagues would try and provide quick feedback and reviews as efficiently as possible. As mentioned in the call, time frames are very important. We want to help support this, despite this larger framework and formal approach. As you mentioned, it is a “work in progress” and we will look to optimize elements over time to make things work better and faster.
I hope that helps explain things a little clearer.

We've made some initial ventures into with HK clients, but progress has slowed due to shifting business priorities on there end.


```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Initially will only focus on allocated DataCap with specific clients, either one we have a relationship with, or within the Filecoin community via slack channels. This will initially be in Private but may move to public allocation if clients find it appropriate. This will depend on the client, their needs and specific requirements (some clients may not wish for information to be public). 
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
Our team takes participating in the Filecoin community very seriously. We are active on Slack every day and try to stay on top of the latest discussions, despite being a small team. We want to be involved in new technology being develop and implement within the Filecoin community. 

Our team will spend a minimum of 2 hours per week, including attending the governance calls (for general and enterprise), and other interactions on GitHub and slack. We likely rack up about 3 to 4 hours per week. 



## Track Record
### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes, we previously received Data Cap, you can find our previous application here: https://github.com/filecoin-project/notary-governance/issues/386 

As mentioned before I believe we need more data cap, 1 to 5 Pib as it will make it easier for allocation as we are being approached to the allocation data cap 

```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
1 Pib
```

This is quite a lot of information, taking into account our previous application. We want support and develop our process further in line with our new processes being developed within the community. Any additional information, clarification or details required please let us know. 

Kind Regards,
Dave, Sayon and all the Coffee Cloud Team

**Comment by Kevin-FF-USA** [comment]
Hi @davidthoms.

Confirming we have received this application, thank you.
There were (2) proposals that updated some of the questions.  Requesting that you please copy the new questions and paste into this application.  Ok to resbumit, or just add a comment with the newly requested information.

**Comment by davidthoms** [comment]
Hi @Kevin-FF-USA Thank you for getting back to us. 

Can you please provide web links to the proposal questions I will update them ASAP? 

We want to have everything sorted in the new few days as we have a number of projects in Q4.

**Comment by davidthoms** [comment]
**Throughout the allocation and use of the DataCap, we will establish a corresponding review mechanism.   Good customers will be rewarded, while bad customers will be punished and not allocated accordingly. 

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?**

We monitor the allocation of data cap to clients who meet certain criteria. Usually, within our review process, we ask for detailed information ensuring that e appropriate organizations are allocated Data Cap. 

During our Due Diligence process (KYC), you are able to determine if he client is who they say they are. And if there is any question of legitimacy, specific data, certifications, and other supporting documents or materials can by requested. Usually, most “bad customers” credentials can’t stand up to detailed scrutiny by the community and allow for identification. 


This process can also be used for spot checks while the Data Cap is being allocated, to ensure it is where it is supposed to be.

**Comment by davidthoms** [comment]
@Kevin-FF-USA @dkkapur @galen-mcandrew As mentioned previously, we are keen on answering the other questions. It would be very helpful if you can provide a link to the proposals you mentioned so we don't miss any details.

**Comment by Kevin-FF-USA** [comment]
Hi @davidthoms 

Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Please email NOTARYELECTION@FIL.ORG from the email account linked to this GitHub account. *The email MUST COME from the same account you used 

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Are you applying as an individual or Organization
3. Your Country of Operation
4. The updated SLA participation Level (https://github.com/filecoin-project/notary-governance/issues/630) 
5. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
6. Link to this GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Kevin-FF-USA** [comment]
Hey @davidthoms 

These are the links to the application updates you asked for: 
https://github.com/filecoin-project/notary-governance/issues/630
https://github.com/filecoin-project/notary-governance/issues/635

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[637.pdf](https://github.com/filecoin-project/notary-governance/files/10159328/637.pdf)

**Comment by davidthoms** [comment]
@Kevin-FF-USA Can you email me the "Token Verification Code". I haven't received it and am wanting to complete the full disclosure form. https://airtable.com/shrjx52lvefitwdq6

**Comment by Kevin-FF-USA** [comment]
Hi @davidthoms ,
As of this writing we never received your Disclosure form. Since this form was not provided we were unable to perform a sanctions check or send a FIL to your address to verify the address.

Without those required security steps - we are unable to allocate DataCap to you as a Notary in this 4th Round.
We would still like you to remain in the program and will retain your Notary status, but you will not be able to receive/sign/distribute DataCap until the next time we open up disclosures for verification. 

Cc @galen-mcandrew @panges2

**Comment by davidthoms** [comment]
Hi @Kevin-FF-USA , sorry for the delay in replying. We were keen on completing the form, however, we did not receive the Token Verification Code. Was this emailed to me? can you please confirm it is david@coffeecloud.io? Please let me know as soon as possible, and we'll submit the form immediately.

**Comment by Kevin-FF-USA** [comment]
Hi @davidthoms ,
The pasted the email The Goverannce Team sent with your token code (December) into our SLACK private DM running with Phil and I.  We never received a Disclosure form, which is going to cause delays for your onboarding onto the multisig.  When you complete the full disclosure form, please update this issue as well as respond in the SLACK channel (
<img width="301" alt="image" src="https://user-images.githubusercontent.com/94004586/221046936-07779146-7827-4ae8-9f02-699bee993481.png">

**Comment by davidthoms** [comment]
Dear @Kevin-FF-USA,

Thank you for getting back to us so quickly. We have completed the form an returned to you. Sincere apologies for the delays.

**Comment by Kevin-FF-USA** [comment]
Hi @davidthoms,
As of this writing, we have not received f14qmuid2b6ne4342m5dk56f4rcr7y5sz4sg5fiwy as VERIFIED in the registry. Until this verification happens, you can remain a Notary but will be unable to allocate DataCap.  

If you need technical support, please contact Phil and I in the private SLACK channel for Coffecloud

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f14qmuid2b6ne4342m5dk56f4rcr7y5sz4sg5fiwy
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzacedo7drv2lxs2yochkgx2mpoiz24hzklihxk4wif7tln44yis46uam
