### ISSUE TITLE
Notary Application:  MovieLife

### ISSUE THREAD

**Issue by laff2022** [filecoin-project/notary-governance#639]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: MovieLife
- Affiliated organization: MovieLife
- On-chain address to be notarized (recommend using a new address):f1zl66tinwktxjihilj422tzh2v2pe2772u6zrfza
- Country of Operation: Australia
- Region of Operation: Oceania
- Use case(s) to be supported: Media & Entertainment, Scientific datasets, https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1109
- DataCap requested for allocation (10TiB - 10PiB): 10PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
As an innovative NFT media platform, MoveLife has been using IPFS to store media data from 2021.
In 2022, we participated in Coding with Filecoin for 8 weeks, participated in the Filecoin community activities actively, and then began to try to store media data to the Filcoin network.
Coding with Filecoin [https://github.com/ipfs-and-filecoin/Coding-with-Filecoin-Homework]
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Sorry, can't reveal too many details
We have a lot of FIL, which are mainly used to pay the SP suppliers as cost for data storage.
```

How did you acquire the FIL cited above?
```
These tokens are mainly obtained through exchanges.	
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
In 2022, we participated in Coding with Filecoin and participated in the entire event, which lasted for 8 weeks. During the event, we completed the requirements and tasks of the Filecoin community and participated in various interactions actively .
It is a pity that after the event, I was not shortlisted as a Filecoin community ambassador, I only got a souvenir from Filecoin.
Coding with Filecoin [ https://github.com/ipfs-and-filecoin/Coding-with-Filecoin-Homework ]
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
MovieLife is an emerging media platform, registered in Melbourne, Australia. We got investment from the US and we have over 30 people in our team. Focusing on converting media content to NFT since 2021.
Our main business strategy is to develop media content first, to attract a large number of users' attention, to hold offline activities, to help artists to transform their works into NFT and promote the NFT ecology.
	
Organization:  MoveLife Melbourne Office
Nature:  private company
Registration Country: Victoria, Australia
Established: April, 2021
Size: over 30 employees
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://movielife.top/
Twitter: https://twitter.com/NFT_peer 
Join Discord: https://discord.gg/3F4MaBKQwG 
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
The offline activities we organize and participate in, the artists communicate on the spot, create on the spot, and convert the works into NFT. Details of the event can be found at the link below
https://twitter.com/NFT_peer/status/1586967164040323072?cxt=HHwWgICprciOhYYsAAAA

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
github:  https://github.com/laff2022
Twitter: https://twitter.com/NFT_peer 
Discord: laff#7473
Slack: laff2022

```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://twitter.com/NFT_peer/status/1586967164040323072?cxt=HHwWgICprciOhYYsAAAA
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
1. DataCap will be priority allocated to the applicants from Oceania, Africa and Europe. Due to the current unbalanced development of Filcoin, there are few customers in Oceania, Africa and Europe, and they should got priority to be served.
2. We will classify customers based on their industry reputation and scale. 
   All customers will be divided into four categories: big team customers, medium team customers, small team customers, and individual. 
   The four categories of customers are allocated 40%, 30%, 20%, and 10% respectively.

3. The client classification rules are as follows:
https://docs.google.com/spreadsheets/d/1LjVLLmV0GxEDZf4eH5hv3m2v00qDzbKlez9g0-t95RY/edit?usp=sharing

4. In the initial stage of specific allocation, we will take out a small part (<10%) of each category for testing, and gradually establish a reputation mechanism (including incentive, punishment, supervision)

5. Each assignment will be used to evaluate the customer's reputation.
   For example, if a customer applies the DataCap which is valid and efficient, the reputation credit will increase.
   With higher credit, the customer can apply more DataCap (maximum increase 200%).

6. Throughout the allocation and use the DataCap, we will establish a corresponding review mechanism.   
   Good customer will be rewarded, bad customer will be punished. The quality of the customer will be optimized gradually.

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hardware wallet will be used to store the keys for DataCap address.
Do personal due diligence with the help of operational records, community exposure and chat logs.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
General principles:
	Noteary system is for better, faster and fairer development of Filcoin ecosystem.
	In order to promote Filecoin and  improve service to customers, it should be inclined to help customers in innovative industries, Web 3.0, NFT applications, etc. 

	For individual applicants, their identity will be verified through account activity and third party account, such as Twitter, slack, Discord, which will prove that the customer is a valid user and not a machine.

	For organizations, we will set up a due diligence team to conduct a complete review of the application form submitted by the applicant to ensure proper allocation and effective use of DataCap, and to conduct random spot checks after allocation to establish a credit system.

	The following is the recommended due diligence procedure.
	Depending on the level of customer requiring due diligence, the following questions are required to be submitted by the customer (on the basis of protecting personal privacy).

	1. Introduce yourself/your organization (with links)
	2. Applicant's relationship to the organization
	3. use case and scope.
	4. Nature of business (government, public, private, NGO)
	5. Geographical location of the client.
	6. Data sources
	7. Proof of data capacity requirements
	8. The process of using the data
	9. Whether to agree to the use of data after a sample check.
	8. DataCap allocation request amount.
	9. disclaimer of liability
	10. Reproduction rights statement and legal compliance requirements.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will monitor and track the use of DataCap strictly.
Each assignment will be used to evaluate the clients' reputation. 
We encourage customers to allocate DataCap to more new miners, and each new miner allocation will have some incentives.
Also, we will develop a tool to randomly check verified transactions of all customers to ensure they comply with the agreement.
If some problems are found, there will be a person to communicate and coordinate in time, and give the right to explain to the customer. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We plan on making all allocation decisions public by recording them in a Github repo.  if we have detailed communication needs E-mail, we will save the screenshots.. 
If selected, we will establish a Discord and Telegram as well.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We keep records of all missions and make them public
We will also build Discord and Telegram gradually.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4:
Our team will do out duty as a notary to review very application carefully. and we will to take part in the Filecoin community actively.
Our team will spend at least 20 hours per week, including participating in governance calls (for general and corporate), and other interactions on GitHub and Slack.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes, we previously received Data Cap, you can find our previous application here:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1109
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None
```

**Comment by laff2022** [comment]
Hi @Kevin-FF-USA 
Thank you for your feedback. Feel free to ask us if you have any question.

**Comment by Kevin-FF-USA** [comment]
Hi @laff2022, 

Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. 
***This cannot be from your personal account. You Must include the address of your Organization.**  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [[filecoinproject.slack.com](http://filecoinproject.slack.com/)](http://filecoinproject.slack.com/)
5. Link to this GitHub application

**This step needs to be completed by 28NOV.**  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[639.pdf](https://github.com/filecoin-project/notary-governance/files/10159332/639.pdf)

**Comment by Kevin-FF-USA** [comment]
@laff2022 


Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
