### ISSUE TITLE
Niulian Technology Notary Public Application

### ISSUE THREAD

**Issue by Super-ipfs** [filecoin-project/notary-governance#64]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
- Name:Kuanyong Peng
- (Optional) Affiliated Organization: Niulian Technology
- Website / Social Media:
- On-chain Address(es) to be Notarized:
- Region of Operation: [North America, South America, Europe, Africa, Greater China, Asia-GCN, Oceania]China
- Use case(s) to be supported: [Please select from [here](/notaries/templates/README.md#definitions)]
- DataCap Requested:

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_
Share some of Filecoin's technology and communicate with peers   f034592
### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Please answer here.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Please answer here.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Please answer here.
```

The promotion and publicity of Filecoin will explain the principles and development prospects of Filecoin for customers
### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
Please answer here. 
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Please answer here.
```
Niulian Technology is an enterprise blockchain infrastructure service operator and distributed ledger technology solution provider. It focuses on providing cloud-based blockchain platform services and independently deployed blockchain trust systems for finance, taxation, and insurance. Provide industry solutions, blockchain system construction, business process outsourcing and operation promotion in fields such as information security, digital copyright and real estate.
Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Please answer here.
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Please answer here.
```
https://www.sohu.com/a/312107108_120147230
http://www.chidaolian.com/article-48246-1

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Please answer here.
```
https://www.sohu.com/a/312107108_120147230

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
Please answer here.
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Please answer here. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Please answer here.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
Please answer here.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
Please answer here. 
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
Please answer here. 
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
Please answer here.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Please answer here. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Please answer here.
```
None

Cumulatively, how much DataCap have you previously successfully allocated? 
```
Please answer here. 
```
None

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
Please answer here.
```
None

**Comment by jnthnvctr** [comment]
Apologies, we've already closed the application for notaries. You may re-open this when the next window comes up - please join #fil-plus to stay up to date when that happens.
