### ISSUE TITLE
Notary Application: Zhongchuang

### ISSUE THREAD

**Issue by zcfil** [filecoin-project/notary-governance#643]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:zhongchuang
- Affiliated organization:  ZC LABS
- On-chain address to be notarized (recommend using a new address):f17xummecmkqgjhm4fesktesaieumn7ugarwucwty
- Country of Operation: China
- Region of Operation: [North America, South America, Europe, Africa, Greater China Region (GCR), Asia minus GCR, Oceania] 
Greater China
- Use case(s) to be supported: [Please select from [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries)]:
README.md
- DataCap requested for allocation (10TiB - 1PiB): 1PiB 
- Are you applying on behalf of yourself or an organization?: [Individual, Organization]
Organization
_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
ZC Labs has technology operations centers and nodes in Guangzhou, Shenzhen, Dongguan and Hong Kong, China. Since Fil has launch of the mainnet in 2020, ZC has begun to provide technical services to partners to help them complete the construction of storage services. At present, the accumulated storage power of  ZC exceeds 120P globally. The largest node has 20P storage power, All nodes have more than 1 million FIL in total. 
ZC LABS is positioned as a decentralized storage service provider for WEB3. For a long time, ZC not only focuses on building nodes for partners, but also explores how to provide better storage services for potential clients of web3. Since January 2022, ZC has been deeply involved in the FilPlus project, vigorously promoting the Filplus project to partners who has effective data storage needs. We also providing them with a complete set of solutions and technical services for storing data in the FIL network. 
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f02528(192,000 FIL)	23.18PiB
f080468(53,000 FIL) 6.52PiB
f0842171(101,000 FIL) 15.4PiB
f01660795(105,000 FIL) 17PiB
f01756683(70,000 FIL) 10PiB
f01836766(115,000 FIL) 17.46PiB
f01877184(58,000 FIL) 8.72PiB
f01128206(51,000 FIL) 7.8PiB
f01859603(60,000 FIL) 10PiB
f01923786(65,000 FIL) 10PiB
f01923787(60,000 FIL) 10PiB
f0723827(114,000 FIL) 14.29PiB

Total：1,004,000 FIL
Power: 150PiB
Besides this nodes, the assets we disclose are part of our assets,accounting for 1/2 of our nodes
```

How did you acquire the FIL cited above?
```
These are a lot of block awards for participating in FIL project since October 2020，And the investment of some of our clients and partners
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Block Browser：http://www.filtrace.cc/
Gas Use：http://www.filtrace.cc/
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Founded in 2020, YG LABS PTE.LTD. has offices in China. YG LABS is committed to becoming an enterprise that provides distributed storage infrastructure construction and distributed storage service support.
At present, we are mainly engaged in two business lines:
1.Construction of filecoin distributed storage. At present, we have set up our own nodes in Guangzhou, Shenzhen, Dongguan and Hong Kong, China. In the future, we will set up nodes around the world and provide storage services for customers.

2. Distributed storage related software services,providing online storage platforms for enterprises and hospitals
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: http://www.szfil.com/
Twitter：@zc_labs
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://twitter.com/zc_labs/status/1575729909749915648
https://twitter.com/zc_labs/status/1578346451146805248
https://twitter.com/zc_labs/status/1581132916775858176
https://twitter.com/zc_labs/status/1582655198107144192
https://twitter.com/zc_labs/status/1584162256413085697
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter: @zc_labs : 679 followers
Twitter:  @zc_company;
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
n/a
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We will assign DataCap to customers who can provide real information about the company and ensure that the data is publicly available. We will have several validation processes:

1.We will browse the client's official website to understand the basic information of the their organization.

2.We will judge whether the company's business ecology meets our conditions through recruitment websites, news media, etc

3.We will ask customers to provide verifiable information such as business registration and establishment documents of the organization

4. We will conduct a review of the clients company's data storage content, and prioritize more meaningful data

5.We will carry out layer by layer audit to verify whether the user information is true and the business ecology is normal. Only when there is no abnormality can we finally approve the allocation of DataCap

We will implement a 0 to 100 point scoring mechanism for all users to screen more active customers with higher storage value data.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We use the hardware wallet to store the private key to ensure the security of the account. After the audit, the data upper limit will be assigned to the applicant by the person who has the right to execute the hardware wallet.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In order to ensure the authenticity of customer information, we will verify customer information through the following contents, and assign special personnel to continuously follow up and verify after allocating DataCap
1.Browse the official website of the customer company to view the company's history, news, ecology and products.

2.Check the customer's third-party media updates, such as Twitter and Slack's social media accounts. We will observe the activity of the account and Github usage period.
3.Query the enterprise information website of the customer's country/region
4.We will require our customers to provide business license, establishment documents, public registration information and relevant certificates.
5.Our customers will be asked to provide government issued ID card or passport information.
6.We will ask our customers to provide stored sample data for review to confirm whether the data is open, stored content is legal, valid and insensitive.
7.Do not violate the laws, anti laws and regulations of the country and region where you are located and the regulations of the Filecion community,Customers with serious violations will be blacklisted by us.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
After the customer obtains DataCap, we will have a specially assigned person to continuously follow up the customer's transaction information. If any violation is found, we will remind him first. If he does not listen to the advice, it will be deemed as a serious violation. The customers who seriously violate the rules will be blacklisted to reject future applications.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Our allocation strategy and audit process will be disclosed in Github to ensure our fairness. A communication group will be set up on the social software similar to telegrams to publish announcements, help customers solve various problems, or discuss the future development of filpuls with each other
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We will establish a management system for users to submit DataCap applications, audit processes and DataCap allocation records. If necessary, we will provide an administrator account for the community to reasonably query our DataCap allocation
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L5.
(20+ hours per week on average.I will actively participate in the discussion/question comments, the presence of the governance phone, the message reply in Slack, etc.)
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Never had
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
Never had
```

**Comment by lzj469230** [comment]
Thank you. This is my Slack username @ lzj469230. You can also contact me through Slack if it is convenient for you










At 2022-11-07 18:03:23, "Kevin" ***@***.***> wrote:

Hi @lzj469230,

Confirming receipt of your application. I will be in touch in the coming days with further questions and follow up.

**Comment by Kevin-FF-USA** [comment]
Hi @lzj469230,
 
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. 
***This cannot be from your personal account. You Must include the address of your Organization.**  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to this GitHub application

**This step needs to be completed by 28NOV.**  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by a295461148** [comment]
I am very happy to finally receive your reply

**Comment by a295461148** [comment]
I am very happy to finally receive your reply

**Comment by a295461148** [comment]
I am very happy to finally receive your reply，Our team will reply immediately

**Comment by lzj469230** [comment]
Hi @Kevin-FF-USA @panges2,
Thank you for your reply,I have submitted the basic information through the team email: service@szfil.com

**Comment by Fil-ZC** [comment]
Please approve our organization as soon as possible, and you want to join the notary organization earlier. At present, it is found that the notary selectively checks the dc, and the notary reviews the unidentified dc. Our real layout of the filecoin organization can not get a renewal, resulting in everywhere stuck. We want to join us in sustaining justice as soon as possible.

**Comment by ZC-FILSZ** [comment]
@galen-mcandrew @Fil-ZC 
[In-protocol Security] :This security contribution I think means submitting code for lotus,we introduced Filecoin's multi-signature feature. multi-signature is of great help to SP.And we will use it in the "filecion graphical operations" project.In addition, we have implemented the function of separating the private key signature from lotus, which eliminates the need to save the private key on the lotus server. We only need to sign the good message offline and push the message to lotus without the private key to realize the transaction function

**Comment by ZC-FILSZ** [comment]
@galen-mcandrew @Kevin-FF-USA 
[In-protocol Security] :This security contribution I think means submitting code for lotus,we introduced Filecoin's multi-signature feature. multi-signature is of great help to SP.And we will use it in the "filecion graphical operations" project.In addition, we have implemented the function of separating the private key signature from lotus, which eliminates the need to save the private key on the lotus server. We only need to sign the good message offline and push the message to lotus without the private key to realize the transaction function

**Comment by zcfil** [comment]
@galen-mcandrew @Kevin-FF-USA
**[In-protocol Reputation]** :We are developing a trading platform and an operation and maintenance platform. The main function of the trading platform is because we have customer resources with fil and some supplier resources. We can bring them together through the trading platform to achieve cooperation. With fil investment, more meaningful data can be stored in filecion, making a little contribution to the realization of human data permanence. The main purpose of the operation and maintenance platform is to reduce the threshold of filecion users through graphical interfaces, enable more ordinary people to participate in data storage, and achieve more discrete distributed storage.In addition, we have also realized the remote sector C2 cluster function, which can send sector C2 tasks to other equipment suppliers through the network, thus realizing the business of leasing GPUs on our trading platform. The operation and maintenance platform also serves the transaction platform

**Comment by zcfil** [comment]
@galen-mcandrew @Kevin-FF-USA 
**[Allocation Strategy]** :We plan to support the following data:
40%: Video data, including videos related to film and Documentary and surveillance
30%: Relevant data with social contribution, such as Hospital data,Educational Institution data and e-books, etc.
15%: Stored data of YG-related business customers
15%: Web3.0 related data

**Comment by zcfil** [comment]
@galen-mcandrew  @Kevin-FF-USA 
**[Client Due Diligence]** This DataCap is mainly provided to users of our trading platform, and we will often spot check user data samples from equipment suppliers

**Comment by zcfil** [comment]
Hi, @galen-mcandrew @Kevin-FF-USA 
I added that the application materials for notaries have been submitted. Please help me to score again. I hope I can participate in the notaries industry and make a little contribution to the progress of the filecion community and even the whole mankind
Thank you.

**Comment by zcfil** [comment]
Hi, @galen-mcandrew @Kevin-FF-USA
I added that the application materials for notaries have been submitted. Please help me to score again. I hope I can participate in the notaries industry and make a little contribution to the progress of the filecion community and even the whole mankind
Thank you.

**Comment by Kevin-FF-USA** [comment]
@zcfil 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by zcfil** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebrczrf5gwtmd54w44viaw4ygkjzp7dy6hyzn62mmbtwdmnxib2wk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebrczrf5gwtmd54w44viaw4ygkjzp7dy6hyzn62mmbtwdmnxib2wk

**Comment by zcfil** [comment]
Hi，@Kevin-FF-USA @galen-mcandrew 
I have resubmitted Complete the CONTACT AND DISCLOSURES form
