### ISSUE TITLE
Notary Application: FILWallet

### ISSUE THREAD

**Issue by a1991car** [filecoin-project/notary-governance#644]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: a1991car
- Affiliated organization: FILWallet
- On-chain address to be notarized (recommend using a new address): f16mmglamiv2lyvcdvjwl2hebaayq2472rgqnf74i
- Country of Operation:  [Greater China]
- Region of Operation: Greater China Region (GCR) 
- Use case(s) to be supported: Developer Tools、Decentralized Applications、Media & Entertainment 、Public or Open Data
- DataCap requested for allocation (10TiB - 1PiB):  500TiB
- Are you applying on behalf of yourself or an organization?:  Organization——FILWallet

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).

```
With so many ecosystems of Filecoin, we choose to in the field of wallets.Because our team has experience in the development of blockchain wallets, our person in charge even once worked in imtoken. Therefore, to maximize the functions, UI and experience of FILWallet to serve Filecoin ecological users, this is the goal of our team. And we are confident we can make it happen.

In June 2021, FILWallet will launch V1.0.0. version
In June 2021, FILWallet will launch V1.0.5, which integrates the following functions:
Support FIL full account system (f0, f1, f2, f3)
Support FIL multi-signature

In August 2021, FILWallet V1.1.1 launched, which integrate the following functions:
    Support node management, can change Owner to multi-signature, node exit, observe node dynamics
Support the function of re-signing after FIL multi-signature signature fails
In October 2021, FILWallet V1.1.5 will be launched, which integrates the following functions:
    Support message push, content unified management
    Support international languages​(English, Traditional Chinese, Korean, Japanese)
    Support FIL multi-signature red envelope function, red envelopes are distributed through multi-signature addresses
In January 2022, FILWallet V2.0.0 will be launched. The version integrates the following functions:
Access to ETH, BSC, Filecoin public chain
The on-chain ecological DApp can be accessed through FILWallet

Asset security:
Security is the most important thing to FILWallet and we always place at the top of the development. FILWallet completes a comprehensive security review by two security auditing companies (Certik and Artemis). At the same time,  the user's mnemonic and private key are only stored in the ciphertext on the mobile phone, and the stored ciphertext is generated by complex strategies and secure encryption algorithms to ensure security. The user needs to enter the password to decrypt the data before using the private key to sign the data. The platform will not access and store any user's mnemonic or private key, and will not transmit it through the network; and has also made more security protections to prevent illegal attacks.


FILWallet currently has a 3000+ user base, with a daily FIL transfer of nearly 100000+, and has won unanimous praise from ecological users. In the future, Filecoin will support smart contracts, and FILWallet will explore financial-based derivatives services and provide on-chain data analysis services. Ultimately, it will provide FIL users with access to the Filecoin ecosystem. FILWallet will also continue to pay attention to the voices of ecological participants and meet the needs of the community as much as possible; iteratively upgrade according to the needs of the community, and keep providing the most professional and safe digital asset services for participants in the Filecoin ecosystem.

FILWallet has grown rapidly, not only serving many users, but also taking third place in the Filecoin hackathon competition, and has become the most popular Filecoin wallet in China and Asia.

Links：
Telegram：https://t.me/filwalletio
Official Site：https://filwallet.co
Twitter：https://twitter.com/filwalletio
github：https://github.com/filwallet

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Our total holdings of FIL exceed 3 million.

Among them, f0688165 is our largest node, with a total computing power close to 100P and 1,577,889.6538 FIL.

https://filfox.info/en/address/f0688165

The total computing power of f0724216 is 29.07P, 600,454.944FIL
https://filfox.info/en/address/f0724216

The above are just some of our nodes. Because customers are very satisfied with Filwallet, they contacted us to provide FIL pledge service. We have also served many customers, but due to customer requirements, most of the nodes are kept confidential.

We have cooperative IDC computer rooms in many regions around the world, and our customers are also all over the world.

f0724216 in Guangdong, China, f0688165 in Vietnam

```

How did you acquire the FIL cited above?
```
First, filwallet is popular. We have been invited to many Filecoin events and speeches, and through our speeches, many customers know us and want us to help him get involved in Filecoin.
Therefore, filwallet helps customers build nodes and provides operation and maintenance support.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
1. Provide the most professional and secure digital asset services for participants in the Filecoin ecosystem.
At present, most of the mining methods of filecoin are cluster or joint mining. There will be some mistrust problems in how to store the produced coins. FILWallet launched the FIL multi-signature wallet to solve this problem. Several people manage this FIL multi-signature wallet at the same time. .
Through the FIL multi-signature wallet, the Owner can be multi-signed, and the FIL red envelope can be issued through the FIL multi-signature wallet
2. In the v2.0.0. version of FILWallet, ETH&BSC is added. Through the FILWallet DApp browser, users can experience the current popular DApps based on the ETH&BSC ecology, which greatly reduces the threshold for digital asset users.
3. FILWallet has held a number of community ama, and DoraHacks allows participants of the Filecoin ecosystem to better understand the ecosystem.

https://hackerlink.io/zh/buidl/916?roundProj=711

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
We introduced Filecoin's multi-signature feature.
According to market feedback, multi-signature is of great help to SP.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
FILWallet is based in Shenzhen. FILWallet is a decentralized digital asset wallet focusing on WEB3.0. It fully supports the WEB3.0 basic storage facility Filecoin, and provides a multi-signature wallet on the FIL chain that is simple to interact, safe and easy to use. It has expanded to support BSC&ETH public chain and its ecological Dapp.
Country of registration: China
Employee: 35+
Established time: 2021


Telegram：https://t.me/filwalletio
Official website：https://filwallet.co
Twitter：https://twitter.com/filwalletio
github：https://github.com/filwallet

https://www.jinse.com/news/blockchain/1155688.html
https://mp.weixin.qq.com/s/SnqJO89bJunR1bf0bBqJqg

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Telegram：https://t.me/filwalletio
Official website：https://filwallet.co
Twitter：https://twitter.com/filwalletio
github：https://github.com/filwallet

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://mp.weixin.qq.com/s/GX4_RHHwibsir9Mu2ZzPAw
https://mp.weixin.qq.com/s/2v4G49TzCkWl-ux33lW_eg
https://mp.weixin.qq.com/s/9mhxsPkK4VA2dA80cxqCFg
https://mp.weixin.qq.com/s/Uy9aARZNFWoPP6VHFfuS_w
https://mp.weixin.qq.com/s/SnqJO89bJunR1bf0bBqJqg
https://www.jinse.com/news/blockchain/1155688.html

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter: @filwalletio   931followers
Telegram：495 people 
Wechat： 2751 people
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
As a technology, not a market. I'm low-key, but still get some accolades.
Filecoin ambassador  
IPFS ecological innovator   
Filecoin star    

I also hosted an AMA with the IPFS community.
https://mp.weixin.qq.com/s/GX4_RHHwibsir9Mu2ZzPAw

```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```

First of all, we believe that Filecoin is better at storing data of WEB3 enterprises than Amazon Cloud, so we will give priority to NFT data, DeFi data, gamefil data, WEB3 based video, audio and other Dapp data -- 50%
Secondly, the amount of enterprise level data is huge, and the demand for storage is also huge. Therefore, we will also use high-quality enterprise level data storage -- 40%
Finally, whether to apply for personal data will depend on the situation. We believe that the storage needs of individual users do exist, but the amount of data generated by individual users is relatively small, so we may use a small number of individual users -- 10%

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will buy a ledger wallet, which will be managed by me personally. I will write down the mnemonic words of the wallet and put them in the filing cabinet of our company (the key of the cabinet is kept by me alone).
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
First of all, we will collect customer information and strictly screen to determine whether he meets the qualifications of DataCap;
Find out whether it is legal and review the registration documents of the client company;
Sign and fingerprint (official seal and company seal are required);
Customer ID card and photo;
The operating conditions, objectives and main businesses of the client company.
Then, we will ask the customer these questions:
Are you an individual or an enterprise? How much data storage do you plan to apply for?
How can you prove that you have so much data? Please provide evidence to prove it?
What kind of data do you want to store? Please give an example to prove it?
How do you plan to store and which SPs to cooperate with? Please list the node number of the SP.
Can you share your distribution plan and ensure compliance with FIL+rules, with no more than 30% per SP?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Before allocating DC, I will confirm to the customer again:
1. Please list the cooperation nodes and clearly give the reasons for cooperation.
2. Can you ensure that at least 4 nodes are used, and each node does not exceed 30%?
3. Is there any understanding, investment relationship and interest exchange between sp and customers?
4. We will clearly tell the customer that the DC encapsulation will be monitored and reviewed by the community. We will review the DC encapsulation before giving the next quota. If a node occupies more than 35%, we will stop delegating the quota.
5. We will clearly tell the customer that we always pay attention to the DC allocation through some tools, such as the filfox browser and other tools. Please remain in awe.

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we will definitely publish all records on GitHub.
If necessary, we may also communicate with customers in slip or email.
But we will publish these records on github.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
github、slack、email
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
I log in to slot and GitHub to check messages every day, and I also participate in FIL+and E-FIL meetings.
I will spend at least 15 hours a week on slack, GitHub, YouTube, checking relevant news and replying to relevant content.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None
```

**Comment by Kevin-FF-USA** [comment]
Hi @a1991car,
Confirming receipt of your application.  I will be in touch in the coming days with further questions and follow up.

**Comment by a1991car** [comment]
There seems to be something wrong, always reminding me that "Datacap requested" is missing. But I have revised the format many times and submitted it, if there is any problem, please remind me, thank you

**Comment by Kevin-FF-USA** [comment]
Hi @a1991car,

Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. 
***This cannot be from your personal account. You Must include the address of your Organization.**  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to this GitHub application

**This step needs to be completed by 28NOV.**  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by a1991car** [comment]
hello，We posted the email as requested，Looking forward to becoming Filecoin notary
![1093f6539d580680ced9e6a6891fbde](https://user-images.githubusercontent.com/32447611/203919406-1129e87c-725e-4e04-aa68-980acf614d8f.png)

**Comment by a1991car** [comment]
Glad，Filwallet is record in the official Filecoin documentation, https://docs.filecoin.io/about-filecoin/managing-assets/

**Comment by a1991car** [comment]
![WechatIMG69](https://user-images.githubusercontent.com/32447611/206475675-884d4aed-690c-4f33-9149-27ae6a373815.jpeg)

**Comment by a1991car** [comment]
Welcome to download and experience：https://filwallet.co/

**Comment by a1991car** [comment]
![WX20221208-224627@2x](https://user-images.githubusercontent.com/32447611/206476607-7c714f27-dd35-4ef5-b37f-d6ba2a98e7ab.png)

**Comment by Kevin-FF-USA** [comment]
@a1991car 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by a1991car** [comment]
hi, we write it t，hanks

**Comment by a1991car** [comment]
@galen-mcandrew @Kevin-FF-USA ，
My Ledger has arrived and we want to change the address:
The previous address“f16mmglamiv2lyvcdvjwl2hebaayq2472rgqnf74i” is invalid 
Our address is ： f1xn46mwgqjz45qm3li765qvza3rbjxgys4pas2ly

**Comment by a1991car** [comment]
@Kevin-FF-USA @galen-mcandrew  Thank you for use the new address as the correct address:
f1xn46mwgqjz45qm3li765qvza3rbjxgys4pas2ly

**Comment by a1991car** [comment]
@Kevin-FF-USA @galen-mcandrew ，I just changed the address of the GitHub application form and replaced the old one with the new one. What else do I need to do?

**Comment by Kevin-FF-USA** [comment]
@a1991car  
As long as the top section CORE INFORMATION is updated with your current address - you're good to go.
*Also, please ensure that this address is reflected on your disclosure form.

**Comment by a1991car** [comment]
@Kevin-FF-USA , I filled out the form: https://airtable.com/shrjx52lvefitwdq6，thanks

**Comment by panges2** [comment]
Hi @a1991car, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and setup your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by a1991car** [comment]
@panges2 @Kevin-FF-USA @galen-mcandrew @ I have encountered some problems, can you help me？

**Comment by a1991car** [comment]
![微信图片_20230206104118](https://user-images.githubusercontent.com/32447611/216871203-673ed951-ebe8-448c-8214-aeefe0ad03cb.jpg)

**Comment by a1991car** [comment]
![微信截图_20230206103711](https://user-images.githubusercontent.com/32447611/216871243-247eff47-e17c-44a3-91da-62260fa03b2f.png)

**Comment by a1991car** [comment]
https://user-images.githubusercontent.com/32447611/216878152-4388745a-8f28-423c-bb19-a282d3feed83.mp4

**Comment by a1991car** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedsiwinjt7szxtwqvkdzh4e3dxzckbsnoe2q665cmst3ebsmqqgea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsiwinjt7szxtwqvkdzh4e3dxzckbsnoe2q665cmst3ebsmqqgea

**Comment by a1991car** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedwrkhds2mdcskdbudi5pzuwdsikbl32ctybp5wmlytjb5lmdizjq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwrkhds2mdcskdbudi5pzuwdsikbl32ctybp5wmlytjb5lmdizjq

**Comment by a1991car** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceaxf4vpdylrlg4yjc36kh6yuhfzfa2smgfuunmfyntk7xex45usnm
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxf4vpdylrlg4yjc36kh6yuhfzfa2smgfuunmfyntk7xex45usnm

**Comment by a1991car** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceacm3xtzcauj2splba7i2b7ntprwqqkva6gcnv4yeledykfzg5nww
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacm3xtzcauj2splba7i2b7ntprwqqkva6gcnv4yeledykfzg5nww
