### ISSUE TITLE
Notary Application: Venus - Joss Hua

### ISSUE THREAD

**Issue by Joss-Hua** [filecoin-project/notary-governance#645]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Joss Hua
- Affiliated organization: Venus Team
- On-chain address to be notarized (recommend using a new address): f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
- Country of Operation: [Greater China]
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: User Content, Public or Open Data, Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization - Venus Team

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
I always think Filecoin is an indispensable part of the next-generation Internet in storage, which is the main reason why I have worked on Filecoin for more than four years.

Starting from practice, I began to pay attention to IPFS and Filecoin at the end of 2018. I joined the Filecoin community in early 2019. So far, I have spent all my working time in the ecosystem construction of IPFs and Filecoin, facing community members, developers, service providers, project parties, and so on.

At present, I am mainly committed to expanding the ecosystem of Filecoin service providers, users, developers, and supporters through Filecoin Venus.

More:
* GitHub handles: Joss-Hua
* Venus Miner ID: f0128788
* Slack: @Joss-Venus
* my team participated in DevNet / TestNet / SR1 / SR2 / Filecoin Venus / Filecoin community contents and activities as participants of the project and operators of the community.

We contributed code to lotus, proof, etc. before 2020. 
* https://github.com/filecoin-project/lotus/pull/1571
* https://github.com/filecoin-project/lotus/issues/1930
* https://github.com/filecoin-project/lotus/issues/2183

After that, we continued to focus on the improvement of Venus and did some other important work.

For example, in the community, we launched the Venus SP Incubator Program, the Venus Master Program, and the Venus Deal Accelerator Program, etc, and integrated them into the VenusHub platform to help more members interested in Filecoin and Venus grow, and help engineers master Filecoin at a lower threshold. The VenusHub is currently running steadily.

In terms of development, we have participated in the construction of FVM from the beginning. At present, we are developing **GO-FVM-SDK**. Next, we are going to work on sealing-as-a-service, data-on-boarding and other aspects. Here you can view our [roadmap](https://github.com/filecoin-project/venus/discussions/5062#discussioncomment-3877253) (which may also be adjusted).

* https://github.com/filecoin-project/venus
* https://venus.filecoin.io
* https://venushub.io
* https://lu.ma/filecoinvenus01?past=1
* https://www.youtube.com/watch?v=Sj-lP8wwoB8&t=778s
* https://medium.com/@filecoinfoundation/introducing-the-filecoin-storage-provider-incubation-center-ea8743e18e
* https://twitter.com/venus_filecoin
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Total stake: more than 9.5k FIL
Miner ID: f0128788
Substantiating evidence: https://filscan.io/address/miner?address=f0128788
```

How did you acquire the FIL cited above?
```
f0128788 is the first Venus node in Filecoin network, which was started in early 2021. Then, we took it as an usecase to show the availability and stability of Venus for Filecoin community. It has been running ever since.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
I have always been a supporter and builder of the Filecoin ecosystem:

* Marketing articles of IPFS / Filecoin / Web3: Filecoin annual report, Web3 books, irregular;
* IPFS / Filecoin / Web3 conference host or speaker;
* Contribute relevant documents of Filecoin Venus via Issues / PRs commitments;

Recently community activities:

* Venus Meetup recording list: https://www.youtube.com/playlist?list=PLvmxExuDQi1nxFrwZGtnuURKoCNbovCpw
* VenusHub website: https://venushub.io
* FIL-Toronto Speech:  https://www.youtube.com/watch?v=ugxSlNoLRbg&list=PLIaBaBnqVttsEKgeLV7MO3UTklqpt3Mmz&index=9
* New book Seminar on the 《元宇宙基石：Web3.0与分布式存储》, December 23, 2021, https://www.huoxing24.com/live/24313188
* Online Summit for the first anniversary of the launch of the main network: October 19, 2021, https://www.huoxing24.com/live/24312878
* FVM SDK via Go: https://github.com/ipfs-force-community/go-fvm-sdk
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Venus team leads the development and practice of Filecoin Venus, estabilshed in 2020, Shanghai, China.

Now we have decades of members from all over the world focus on code dev and community.

Through the core dev and ecological activities and programs, we hope (and already) to have more storage service providers, users, and enthusiasts join Filecoin or provide more contributions after joining Filecoin.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
* WeChat Oifficial Account: Filecoin-Venus
* Twitter: https://twitter.com/venus_filecoin
* Website: https://venus.filecoin.io
* Github: https://github.com/filecoin-project/venus
* Slack: https://filecoinproject.slack.com/archives/CEHHJNJS3
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
* https://filecoin.io/blog/posts/welcome-venus-to-the-filecoin-mainnet/
* https://www.jinse.com/lives/258069.html
* https://filecoinfoundation.medium.com/introducing-the-filecoin-storage-provider-incubation-center-ea8743e18e
* https://filecoinfoundation.medium.com/venus-v1-0-0-passes-least-authority-security-audit-133cca8b5132
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
* DouYin (Tiktok)：@二文说, 152 Followers
* Weibo: @Joss0001, https://weibo.com/u/3115848193, 519 Followers
* Individual Wechat and Wechat official account: 2000+ Followers
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
* https://www.youtube.com/watch?v=ugxSlNoLRbg&list=PLIaBaBnqVttsEKgeLV7MO3UTklqpt3Mmz&index=9
* https://weibo.com/7637562608/Loif5FQim
* https://www.youtube.com/watch?v=YgUA2D9jqTU
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Concerning the use of DataCap, it is necessary to ensure that clients correctly use DataCap to store real data because "who" and "what" are very important.

For new clients, online and offline surveys will be conducted as much as possible to determine whether they are qualified to become verified clients.
* Browse the company / personal information and websites provided by them, and query the authenticity of the information from relevant government websites.
* Confirm the applicant's use case and storage plan through questions.
* For verifiable clients, historical reputation is equally important. Each allocation will be regarded as an evaluation of client reputation, including score accumulation and corresponding trust, to determine the upper limit of the data they will receive.

If the client successfully applies for DataCap and correctly stores the real data, the client can apply for more DataCaps here in the future.
Here you can see my detailed strategy for DataCap allocation, with the minimum limit being 1 TiB and the maximum limit being 100 TiB.
https://docs.google.com/spreadsheets/d/1CEi7SisVoTwIwpV2kTsB5MGNqeprLeZINBzP1XAEYr4/edit?usp=sharing
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
I will use an offline wallet (Ledger) to secure the Notary address with DataCap.
And a multi-wallet will be used if other members in the Venus group work together on DataCap allocation.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
All clients must go through a rigorous process to qualify, and the higher the DataCap threshold, the greater the review limit. I will collect information through GitHub, Slack, or Email.

The first step is to collect:
   1. Company entity information;
   2. Information of authorized signatory;
   3. Beneficial Owners;
The second step is interview and data source inspection.
The third step is to sign an agreement and gradually allocate DataCap.

More questions:
   1. Introduction of yourself/ your organization(with links)
   2. Use case
   3. Location
   4. Maximum DataCap allocation
   5. Filecoin address
   6. SPs you intend to allocate DataCap with allocation proportion
   7. Specific requirements of SPs and storage service
   8. For-profit or not
   9. Follow up plan
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Regularly check and audit the usage of allocated DataCaps through tools such as filplus.info. If necessary, the “filplus.info” team will be invited to provide more help.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
My allocation decision records will be made public on GitHub and monitored by the Filecoin community.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
As mentioned above, in GitHub.

Since all application records are publicly available, allocation decisions are transparent.

Suppose community members challenge the notary's decision; in that case, they can submit a dispute resolution application to the notary's management organization after giving clear evidence, and the management department can appoint arbitrators to resolve the dispute.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
I am willing to provide level4 services for participating in the Fil+ program.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None. 
The data I see shows that new clients prefer to submit applications to notaries holding more Datacaps. I only have 100TiB in total, and maybe I have set more restrictions.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
@Steven Li from IPFSForce
```

**Comment by Joss-Hua** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecetn44kf6yejo4shq2mib2dv7zfl4r2haebjzxpvrarobcvwp2e2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecetn44kf6yejo4shq2mib2dv7zfl4r2haebjzxpvrarobcvwp2e2

**Comment by Joss-Hua** [comment]
> ## Notary Ledger Verified
> #### Message sent to Filecoin Network
> > message CID: bafy2bzacecetn44kf6yejo4shq2mib2dv7zfl4r2haebjzxpvrarobcvwp2e2
> 
> #### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecetn44kf6yejo4shq2mib2dv7zfl4r2haebjzxpvrarobcvwp2e2

Interesting.

I used the same address as V3 to apply for V4. Then when I worked in the notary app today, the system prompted me that I needed to verify the address (perhaps the app or Ledger was upgraded a few days ago), After I verified the address, this message appeared on [#645](https://github.com/filecoin-project/notary-governance/issues/645), not [#431](https://github.com/filecoin-project/notary-governance/issues/431).

**Comment by Kevin-FF-USA** [comment]
HI @Joss-Hua,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. 
***This cannot be from your personal account. You Must include the address of your Organization.**  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to this GitHub application

**This step needs to be completed by 28NOV.**  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Joss-Hua** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedusdym24icow7k3oxsdyo6ka6ruagscquifzdrotkwyu6sozczjc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedusdym24icow7k3oxsdyo6ka6ruagscquifzdrotkwyu6sozczjc

**Comment by Joss-Hua** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec4q6m3v2nt4cpl3xvwkymmngwkwqto4t5fyrlq7myljtfzkvrw3m
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4q6m3v2nt4cpl3xvwkymmngwkwqto4t5fyrlq7myljtfzkvrw3m

**Comment by Kevin-FF-USA** [comment]
Added to multisig - closing application.  All set and good to go as Notary!
