### ISSUE TITLE
Large dataset multisig request: E-Fil+ multisig

### ISSUE THREAD

**Issue by raghavrmadya** [filecoin-project/notary-governance#646]
# Notary Application
    
To apply as a notary, please fill out the following form. 
    
## Core Information
- Name: E-Fil+ multisig
- Affiliated Organization: Filecoin Plus Program
- Website / Social Media: efilplus.super.site
- On-chain Address(es) to be Notarized: f2ldxnlo7st7qhvdc2lp3pgxku2bfaitisrcd347q
- Region of Operation: n/a
- Use case(s) to be supported: https://github.com/filecoin-project/notary-governance/issues/611
-  DataCap requested for allocation (10TiB - 10 PiB): 50PiB

**Comment by raghavrmadya** [comment]
## Request Approved
#### Address
> f01940930
#### Datacap Allocated
> 50PiB

**Comment by galen-mcandrew** [comment]
Reopening so RKH can top-up E-Fil+ notary multisig.

**Comment by galen-mcandrew** [comment]
RKH approval: https://filfox.info/en/message/bafy2bzacebe6rbet5wlwyoo27lresyey5ztynq4kd62rpdmjlxdayca5qd6v6
