### ISSUE TITLE
Notary Application: Blockchain World - Sounghwan Park

### ISSUE THREAD

**Issue by psh0691** [filecoin-project/notary-governance#648]
# Notary Application
To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Sounghwan Park
- Affiliated organization: BlockchainWorld (http://bcwnews.com)
- On-chain address to be notarized (recommend using a new address): f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
- Country of Operation : Republic of Korea
- Region of Operation: Asia minus GCR
- Use case(s) to be supported: Public or Open Datat, Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization
_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
(1) I'm Sunghwan Park. I'm a researcher at Blockchain World News(bcwnews.com) and I'm working hard to expand the Filecoin ecosystem by providing Filecoin information, publishing news, and testing Filecoin node operation.

(2) Since 2020, we have been distributing more than 500 Filecoin related information on document translation, news issuance, planning series, websites, and social networks. In addition to "Blockchain World", "IPFS Today," a channel specializing in IPFS/Filecoin, has recently been established and is contributing to the expansion of the Filecoin ecosystem by providing in-depth information.
(Note: Latest news release)
http://bcwnews.com/10419
http://www.ipfstoday.co.kr/505

(3) Although not an engineer, it operates a Filecoin node, collects, analyzes, and distributes related filecoin information. Before the mainnet, I ran a testnet node and received 100FIL a day before the mainnet opened.

(4) Which is currently operating on a single PC for Filecoin network analysis and test data collection, actually tests FilePlus(FIL+) using hyperdrive and DataCap, analyzes and provides information on theories and actual results.
https://filfox.info/ko/address/f096173

(5) I attended Filecoin-related events and discussed the expansion of Filecoin's ecosystem with officials.
 - Cohort #3 ESPA : LasVegas, 2022. 7. 25. ~ 29
   http://bcwnews.com/9231
   https://www.youtube.com/watch?v=wsEjoOTCsEQ
 - Fil-Korea : Seoul, Korea, 2022. 8. 12.
   http://bcwnews.com/9489, 
 - Fil-Singapore : Singapore, 2022. 9. 26 ~ 27
   http://bcwnews.com/10028
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
https://filfox.info/ko/address/f096173
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

```
(1) It informed the public about Filecoin and held events to expand the ecosystem.
K-pop & Filecoin Day, IPFS & Filecoin korea meetup event was held.
 - IPFS & Filecoin Korea : Seoul, Korea, 2022. 7. 29.
   http://bcwnews.com/9266,
   http://bcwnews.com/9267, 
 - k-pop & Filecoin Day : Seoul, Korea, 2022. 8. 11.
   http://bcwnews.com/9385, 
   http://bcwnews.com/9476,
   https://youtu.be/ikyGnSwtZQE 

(2) It contributed to the expansion of the base of the file coin ecosystem in Korea by collecting, translating, and distributing file coin-related data.
- Information of Filecoin / Filecoin Enterprise solution and Governance
  https://filecoinproject.slack.com/archives/C02BK7L2ZGC/p1662028539050319
- Filecoin whitepaper, Filecoin economics, Filecoin distribution supply, block rewards policy
  https://filecoinproject.slack.com/archives/C02BK7L2ZGC/p1644071999307739
- Lotus command collection, already produced and distributed before distribution to Lotus Doc.
https://filecoinproject.slack.com/archives/CPFTWMY7N/p1619431097084700?thread_ts=1619145194.008900&cid=CPFTWMY7N

(2) He was selected as the third notary and participated in question-and-answer sessions, various discussions, opinions, information provision, error reporting, and governance calls at Slack and GitHub.
In addition, as a notary, the client was verified more than 55 times and signed the LDN.
https://github.com/filecoin-project/notary-governance/issues/408
https://filplus.d.interplanetary.one/notaries/f01817605/ldn-activity
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
While working as a File Plus notary, he participated in the governance call and reported system errors.
https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1661266255889249
![1667361644556](https://user-images.githubusercontent.com/69004801/200504096-f43cf893-a46a-48f9-a100-b0ab21a160f9.jpg)

https://filecoinproject.slack.com/archives/C01HRNU4VBK/p1661756726121349
https://filecoinproject.slack.com/archives/C01HRNU4VBK/p1660036766282769

Participate in the GitHub discussion and present your opinion
https://github.com/filecoin-project/notary-governance/discussions/581
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
- Organization : Blockchain World
- Nature : Blockchain news, IPFS/Filecoin news, Economic news
- Registration Country : Seoul, Republic of Korea
- Size : 10 employees
- Since : Jan, 2021
```
Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
- Blockchain world : http://bcwnews.com/
- IPFS Today : http://ipfstoday.co.kr
```
Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
- Blockchain world(BCW) & IPFS Today
(1) It is a medium that intensively covers and reports economic and blockchain news and provides various media such as text, photos, cartoons, and videos so that news subscribers can make correct judgments. In particular, the latest IPFS/file coin information is distributed through the 'IPFS Today' channel. 
Currently, the number of members is about 5,000, which varies depending on the news, but an average of 500 visitors a day visit.

(3) It operates a blockchain world blog to collect only headline news every day, produce and distribute videos, and provide basic knowledge about blockchain, cryptocurrency, and filecoin.
https://blog.naver.com/bcwnews
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
(1) Personally, a total of 105 planned serials were conducted on Blockchain World News by dividing blockchain knowledge into three stages: basic, advanced, and application.
http://www.bcwnews.com/sub.html?section=sc30

(2) Social media
- KakaoTalk : 0691psh
- Open KakaoTalk : https://open.kakao.com/o/sv2h2k7d
- Slack : psh0691
- Instargram : 0691psh
- Twetter : Sounghwan Park @SounghwanP
- Telegram : Park sounghwan @heavenwish
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
In addition to illegal, harmful, and unverified encrypted files on the file coin network, any data that helps the file coin network grow is fine. However, I hope it will be useful to mankind first, and then searchability is high.
In particular, in addition to public data in line with the trend of the times, we are interested in blockchain-related data, and we hope that there will be many cases of use in K-pop (music video), K-drama (movies), and e-sports (game video) considering Korea's regional characteristics.
In addition, there is a lot of interest in the metaverse, industrial/agricultural/technical data, and AI/autonomous driving-related data.
I think it would be nice to do offline direct transactions with SP, not FIL (+), for enterprise-encrypted large-capacity data.
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
(1) The allocation plan is largely divided into data with customers, and customers classify their type(reputation) and reliability(performance) into data types(importance), distribution(storage SP, region), and volume(size) from L1 ~ L5, and score them. 

(2) The most important evaluation of DataCap allocation is to first store important and useful data to preserve humanity's important history, such as the vision of Filecoin.

(3) We will share detailed allocation plans and results with customers, determine whether fair scores are given or not, and cooperate with each other to help grow the Filecoin network.

(4) The detailed allocation plan is as follows.
https://docs.google.com/spreadsheets/d/1SrzXI4pe1QHkBgDCu9Ot0Li8oxB38jcxFnra2HepAI4/edit#gid=622434591
```
How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
(1) A notary public is an employee belonging to an organization, and the organization actively supports and protects notary activities because the organization's reputation may vary depending on its activities.

(2) The organization investigates notarization activities for misuse of data cap assignments on a monthly basis. Unless problems such as disputes arise, the organization shall protect from other members so as not to interfere with notarization activities, and notary activities, and devote time to notarization activities.

(3) The notary will use a personal Ledger to access the site and specify a data cap. Therefore, it does not grant permission for non-notary users to access the site or assign data limits.

(4) Therefore, we will pay close attention to ensure that the approval of the applied customer is not omitted, while ensuring fair and fair DataCap approval.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Personal clients are mostly verified through online accounts. For organizational clients, it should be easy to check with applications and related evidence.
Ensure that any customer who wants to store data on the file coin network is unencrypted public data that anyone can access. If the data is not accessible, it is not easy to store it on the file coin network at the moment, so if it is encrypted data, a separate due diligence process will be required to view the data in advance.
This is the due diligence procedure for the agency client.
I would like to borrow the KYC procedure of the cryptocurrency exchange to check the necessary information.
First, check the certificate of business registration, corporate certificate, and other government-issued organization certificates with the agency information, and check the certificate or other evidence to prove the ownership of the data.
Next, we will check the certificate issued by the head of the agency for the applicant and check the photo of the desired posture and memo at the same time with the government-issued ID card or passport.

QUESTIONS TO KNOW YOUR CUSTOMER
(1) Please introduce yourself. Please let me know which social media I can contact.
(2) Please introduce your organization. And what is your role in the organization?
(3) How did you find out about the file coin network and file plus?
(4) In what area are you going to use DataCap?
(5) Please introduce the data ou want to store using DataCap.
(6) How many storage providers will use DataCap to store data?
(7) Do you have any storage providers around you that you know or are working with? Please let me know if you have any.
(8) Are you in favor of disclosing the allocation procedures and usage of DataCap so that it does not harm the file coin network ecosystem in a dishonest way?
```
What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
First, check the previously allocated DataCap usage history using the File Plus dashboard and tools. To increase network growth and file coin network reputation scores, make sure that there are no unfair or abnormal transactions and that normal data is stored. In addition, in order to improve data storage and stability, you must allocate it to at least different 4 SPs.

Use the following tools:
https://filplus.d.interplanetary.one/clients
https://pluskit.io/home
https://www.atpool.com/en/dataCap/myIndex/customer
https://metawave.info/#/
https://filecoin.tools/

Then, I will check with the customer through questions and start the process of allocating additional DataCap.

The questions are as follows.
(1) How much is the cumulative DataCap you received before?
(2) Where do you use DataCap?
(3) How many SPs did you allocate or distribute to?
(4) What kind of method did you mainly use to deliver data? online, offline, and other methods
(5) What is the special agreement with SP?
(6) Was there any difficulty in dealing with SP?
(7) Have you searched the data stored after dealing with SP?
(8)What DataCap are you trying to add? Is it an increase in existing data? Or is it a new kind of material?
(9) Do you have any other questions or requirements?
(10) Is there any service to improve?
```
### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we will make the assignment decisions publicly where possible Github customers have applied for the DataCap. 
We plan to use e-mail, Telegram, Slack DM, KakaoTalk, etc. if we need to make a decision based on the private data required for verification of the customer.
https://docs.google.com/spreadsheets/d/1doaaGUR9Ujzg3iHopkxXm95RsnolKlyT3jgcz0V7cT4/edit#gid=0
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
(1) Publicly accessible record management plan
Github : https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues
Website: https://filplus.info/
(2) Private record management
We plan to encrypt and store private customer verification data in the cloud and disclose the necessary data in the event of an objection or dispute.

Bookkeeping Form :
https://docs.google.com/spreadsheets/d/1doaaGUR9Ujzg3iHopkxXm95RsnolKlyT3jgcz0V7cT4/edit#gid=0
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L5:
 - Maintain a ranking in Leaderboard in the top 5% of Notaries.
 - Attend 2 Governance calls a month - with webcam turned on
 - Join 2 working groups
 - Respond to SLACK inquiries within 24 hours
 - Vote/Comment on all proposals submitted
```
### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes,
https://github.com/filecoin-project/notary-governance/issues/408

I received requests for the allocation of general data caps from several customers but failed to allocate them due to a system error.
I have reported this error several times.
https://filecoinproject.slack.com/archives/C01HRNU4VBK/p1660036766282769
```
## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None.
```

**Comment by psh0691** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebhe4e7c5wqrzxahkil5ertjxrljoqaaxj3vsvhfzmrhczlufddjq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhe4e7c5wqrzxahkil5ertjxrljoqaaxj3vsvhfzmrhczlufddjq

**Comment by Kevin-FF-USA** [comment]
Hi @psh0691,

Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. 
***This cannot be from your personal account. You Must include the address of your Organization.**  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to this GitHub application

**This step needs to be completed by 28NOV.**  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[648.pdf](https://github.com/filecoin-project/notary-governance/files/10159350/648.pdf)

**Comment by Kevin-FF-USA** [comment]
@psh0691 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by psh0691** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedtlotoimxcmhgzi56sqlggebtun6x6gu5tpvzit24zjnrbzp6z5k
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtlotoimxcmhgzi56sqlggebtun6x6gu5tpvzit24zjnrbzp6z5k

**Comment by psh0691** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceajcsyqbmayn6u75yajlufthiklfp6i2ajf7cjsxtvapgebpsvmia
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajcsyqbmayn6u75yajlufthiklfp6i2ajf7cjsxtvapgebpsvmia

**Comment by psh0691** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacechfkajenhvsdlea64ti3gpvkfu7lgeidgr4twi74ppdnfkp6i5o6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechfkajenhvsdlea64ti3gpvkfu7lgeidgr4twi74ppdnfkp6i5o6

**Comment by psh0691** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebprcsqpciqai7qpdw65c7okhxmhemhijvj7kwkqgeccz2vzcqrys
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebprcsqpciqai7qpdw65c7okhxmhemhijvj7kwkqgeccz2vzcqrys

**Comment by psh0691** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec7cizdv4bbowzncipoclkpjknsmdmwrzx3yzsozk3we7xoyjpyb2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7cizdv4bbowzncipoclkpjknsmdmwrzx3yzsozk3we7xoyjpyb2

**Comment by psh0691** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedfakx7huk5oawieesnxzt6ynkrbwcspbm6qsjxecigd636xnngjc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfakx7huk5oawieesnxzt6ynkrbwcspbm6qsjxecigd636xnngjc

**Comment by psh0691** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebatbmh4xr7nfodacrclkmdkuv6ihw52i7c7vw3nylmm2obhhd6jc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebatbmh4xr7nfodacrclkmdkuv6ihw52i7c7vw3nylmm2obhhd6jc

**Comment by psh0691** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaced64nbrqj55mmyimqz7me4vf3nggzzch3zxmsnvuxhrwwfd23wht6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced64nbrqj55mmyimqz7me4vf3nggzzch3zxmsnvuxhrwwfd23wht6

**Comment by psh0691** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebtbv7d3boy5k6zg62wgiy7ablywxb22kj2fc6grrcwmak4jjbwn4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebtbv7d3boy5k6zg62wgiy7ablywxb22kj2fc6grrcwmak4jjbwn4
