### ISSUE TITLE
Notary Application: ICP FOUNDATION

### ISSUE THREAD

**Issue by ICP-Foundation** [filecoin-project/notary-governance#649]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: ICP FOUNDATION
- Affiliated organization: ICP FOUNDATION LTD.
- On-chain address to be notarized (recommend using a new address):f1n2xhbbrecwdi6ldzoe65mjlvmjizh2qpze46yni
- Country of Operation: Singapore
- Region of Operation: Asia minus GCR
- Use case(s) to be supported: Professional Services, Developer Tools, DApp, User Content, Public or Open Data, Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
June 2021, We are a special ecological foundation of ten million dollars that comprehensively support the future of Web3.0. 
Sep 2021, Chain-Cloud, our self-operated project, received a grant from the DFINITY Foundation. Chain-cloud is a middleware which helps to deploy DAPPs on Dfinity easily. Also, it can monitor the operation of canisters, optimize the cycles consumption mechanism and etc.

GitHub: ICP-Foundation
Grants link: https://github.com/icpfoundation/chain_cloud_util 
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
We don't want to disclose.
```

How did you acquire the FIL cited above?
```
Our foundation.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We invest in FIL, setup a Filecoin nodes which provide 20PiB storage space, and hope the Filecoin network gets better and better.
We introduced Hola Space to the Fil+ project and became a part of the eco-system.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
We are ICP FOUNDATION LTD, a web3 tech-lead venture fund, aiming at investing blockchain infrastructure from layer0 to layer2, and revolutionary Dapps based on IC ecosystem. 
Firstly, we are not just a venture but have over 50 engineers in house and have been researching deeply on cross chain and Filecoin network(which is in the decentralized storage domain), so that we have the ability to offer tech support for projects no matter whether we invested or not.
Second, we have already invested the projects inner IC network such as Catalyze, Canistore, Dmail and etc. So compared with other candidates, we are looking from very different angles as both investor and eco-builder. 
Third, in order to have a deep and further understanding of IC network, we created a project named “chain-cloud”, an one-stop compile and deployment platform, which also got $25,000 grant in October Last year. 
We are also tightly following up on the newest updates on BTC/ETH integration, HTTPS outcall, ICRC-1 token, storage subnet, SNS, etc. Based on the endeavor/attempt we tried above, we can confidently say that Filecoin Network is going to have a bright future and we’ll always consistent with the growth of Filecoin.
Investment Record:
2022.1.5   Catalyze
2021.6.25  Canistore
2022.1.13  Dmail
Here's the certificate confirming information of our company:
```
![ICP200](https://user-images.githubusercontent.com/85664636/200736715-e85dec62-ff6d-4d3e-9b03-006a885972eb.jpg)

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://twitter.com/ICP_Foundation0 
http://www.icp33.com/
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://twitter.com/ICP_Foundation0
http://www.icp33.com/
 ```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://twitter.com/ICP_Foundation0
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://twitter.com/ICP_Foundation0
https://xueqiu.com/1594919329/183093460
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The purpose of allocating the DataCap is to make sure clients use these DataCap in the right way to store real and valid data. We firstly specify some rules to figure out the true identity of the applicant.
* Browse their official website to get a general understanding of the company or the individual. 
* Ask some questions to know about the applicant's position/organization/plans/use case etc. 
* Then we will classify applicants based on their industry reputation and scale etc. All applicants will be divided into five levels of grading to determine the amount of DataCap they will get. 
For detailed scoring guidelines, please see:[ICP Foundation - Filecoin Plus Notary Allocation Leveling Rubric.xlsx](https://github.com/filecoin-project/notary-governance/files/9959871/ICP.Foundation.-.Filecoin.Plus.Notary.Allocation.Leveling.Rubric.xlsx)
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hardware wallet (Ledger) will be used to store the keys associated with the DataCap allocation address securely.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
For indiviual clients:
1. Can you introduce yourself? Please provide your social media accounts. (Github, Twitter, Linkedin handle) 
2. What is your use case for the DataCap being requested and what SPs will be storing it? 
3. What is the Filecoin address you would like me to allocate the DataCap? 
4. How much DataCap would you like to request? 

For organizational clients:
5. What is the name, nature, registration country, time since inception, and your position of your organization? Please provide official websites or social media accounts. 
6. How many SPs do you plan on allocating a DataCap? 
7. Can you share some details on how and where you found SP(s)? 
8. In which region do you intend to use the DataCap?
9. Have you previously received DataCap? If so, please share some details on how you spent the previous allocated DataCap.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. To make sure deals are not distributed within a single SP entity, I plan to sync with other notaries and cross check with them on a regular basis to eliminate the concerns.
2. Audit the DC allocation statistics from https://filplus.d.interplanetary.one 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Both.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub Repo.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No. 
```

**Comment by Kevin-FF-USA** [comment]
Hi @ICP-Foundation,

Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. 
***This cannot be from your personal account. You Must include the address of your Organization.**  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to this GitHub application

**This step needs to be completed by 28NOV.**  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by ICP-Foundation** [comment]
@Kevin-FF-USA OK. I've finished! Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[649.pdf](https://github.com/filecoin-project/notary-governance/files/10159352/649.pdf)

**Comment by Kevin-FF-USA** [comment]
@ICP-Foundation 
Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.  

Thank you for the hard work your application represents. 

Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.
