### ISSUE TITLE
Notary Application：【Firefly】

### ISSUE THREAD

**Issue by Firefly2020-cloud** [filecoin-project/notary-governance#65]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
Name:Nickole zhu
(Optional) Affiliated Organization: Firefly
Website / Social Media: http://fireflyblock.com
On-chain Address(es) to be Notarized: f3rmhlmqfaph6czwiqwlg3kfjgejugt5thcviowlmt3l42464q25ptk3znphuuiwrdbyumun3ui7q2gut7v2da
Region of Operation: Greater China
Use case(s) to be supported: [Web 3.0 / Decentralized Applications, Web 2.0 Applications, User Content, Scientific Data, Media & Entertainment, Other]
DataCap Requested: 100TiB

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

As an individual, I have worked as a crypto miner for over 5 years. 
I’ve been a part of the Filecoin community since 2017 and founded Firefly  in 2018. 
As an organization, Firefly is a leading service provider committed to comprehensive Filecoin mining solutions in a cost-effective way. 
We have built quite an extensive relationship with the Filecoin community since its initial launch back in 2017, 
and as a result, have sustained countless contributions to the overall network. 
SR1——The effective storage reaches 2.8PiB, and the reward is 20,000 FIL
After the main network is online, continue to increase the computing power to the current 3.7 PiB
Contact industry users and actively promote effective data uplink

## Industry Reputation

Since joining the community, I have paid close attention to official information, hoping to participate more in various official activities.

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 

#Problem list
- urugang https://github.com/filecoin-project/lotus/issues/5042 
- urugang https://github.com/filecoin-project/lotus/issues/4957 
- embedsky https://github.com/filecoin-project/lotus/issues/3973
# Code submission
- urugang https://github.com/filecoin-project/lotus/pull/4956
- hznuksco https://github.com/filecoin-project/sentinel-visor/pull/271 
- hznuksco https://github.com/filecoin-project/go-statemachine/pull/22
- embedsky https://github.com/filecoin-project/rust-fil-proofs/issues/830
# slack Communication
- urugang https://filecoinproject.slack.com/archives/C0179RNEMU4/p1606541798457900
- search https://filecoinproject.slack.com/archives/CPFTWMY7N/p1591981759420700
- search https://filecoinproject.slack.com/archives/CPFTWMY7N/p1591981759420700
Please check with @Keren  who will be able to substantiate our contributions. 

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

Firefly I is a private company founded on July 5, 2018, in HangZhou, China. 
The company is for-profit, and its country of registration is China. 
At the moment, we have over 100 employees working at the HangZhou and Shenzhen headquarters since its inception 2 years ago. 

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

https://twitter.com/fireflyblock1
http://www.fireflyblock.com/
www.fireflypool.com
https://weibo.com/7329627144/profile?
https://baike.baidu.com
https://www.chainnews.com/u/095136341312.htm

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

https://news.163.com/20/0403/17/F9A9TMPC00019OH3.html

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?

I plan to support multiple use cases; the percentage will be determined by my knowledge and usage expectation, 
which may vary depending on the variable circumstances of each scenario and different regions. 
-    60% - user content (personal user storage) 
-   25 % - scientific datasets (AI training, geological data, autonomous driving) 
-    15% - media & entertainment (video & music)

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.

The acquired valid data is preferentially used for personal data storage，Use industry resources, contact potential users (enterprises, governments), and broaden the use scenarios of filecoin network

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 

This is an ecological environment that we need to guard together, and it needs commitment and common progress

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

The offline wallet had been developed and verified for the accounts associated with the Datacap allocation.
And, multisig wallet is to be used when there are more clients coming in.

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 
For individual clients, online identity will be verified by both account age and account activity perspectives, and this will serve to prove that they are valid users and not bots 
Third-party tools like twitteraudit may also be used to verify online identities. 
For organizational clients, application organizations should be easy to verify through the appearance of their application. 
The developing applications may require further stringent investigation; 
this is to ensure that the application is valid and enclosed with meaningful content, rather than the shell of a malicious client. 
Large public datasets hosted by organizational clients are easy to verify because the data should be unencrypted and accessible to anyone. 

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 

1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle) 
2. What is your use case for the DataCap being requested? 
3. What is the Filecoin address you would like me to allocate the DataCap? 
4. How much DataCap would you like to request? 
For organizational clients: 
5. What is the name, nature, registration country, time since inception, and named officers of your organization? Please link to relevant websites. 
6. In which region do you intend to use the DataCap? If you intend to use the DataCap in multiple regions, please specify. 
7. How many miners do you plan on allocating a DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
8. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?

1) the private key adopts hardware key, which is kept by a special person and a responsibility system is established
2) Increase software implementation and limit the use range of private keys
3) Establish a risk control system to limit the application account number, IP and capacity
4) Monitor datacap application in real time and establish post-event alarm processing
5) conduct self-inspection, and regularly issue data distribution reports
6) Special personnel track the community situation and eliminate illegal use scenarios

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
Yes, all allocation decisions will be guided by the rubric publicly on Github. So are all communications. 
Since all interactions are intended to occur publically, most of the allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly in the Github repo first. 

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
In pubblic(tentatively on GitHub) in order to be supervised by Filecoin Community
### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.

None. 

Cumulatively, how much DataCap have you previously successfully allocated? 
None. 

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 

None.

**Comment by jnthnvctr** [comment]
Apologies, we've already closed the application for notaries. You may re-open this when the next window comes up - please join #fil-plus to stay up to date when that happens.
