### ISSUE TITLE
LDN Application Exception Propasal <WelVape>

### ISSUE THREAD

**Issue by WelVape** [filecoin-project/notary-governance#655]
## Application information 

Link to existing LDN application(s)
- _link to applocation(s) in  https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1155 
  
Are you the data owner?
 Yes

Is the data private i.e., encrypted or not meant to be retrieved by anyone else on the network?
 Yes

## Data owner information
- Data owner:  WelVape
- Data owner's website:  www.wel.top
- Data owner's social media account(s):None

### Data owner description 
_Details on the data owner background, source of funding, etc._
Background: Wel Vape is a Vape brand aiming to provide a healthier and more free lifestyle for smokers worldwide. Our team has over ten-year experience in consumer electronics and novel cigarette design and have won red dot design award, iF product design award, etc.. 
Wel Vape has already be an internet-famous brand among the young in Korea. In additional, we also started to actively layout the Chinese market, now we have over 1000 offline stores.
Primary source of funding : 10 million USD from institutions such as Shunwei, Qualcomm,, Foxconn, etc..

### What is the motivation behind onboarding this data to Filecoin? 
Due to recent policies in China, e-cigarette related companies are unable to publicly advertise and disclose their business. We wish to store on the Fil network for several reasons.
1. Cost optimization. Due to the change in business direction caused by the policy change, a large amount of operational content, production data, and other data from the past must be stored for cost optimization.
2. Privacy protection. We want to find a private space for storage. Although our data is not allowed to be public anymore, it is equally important for our business. 
Thus, Filecoin is a perfect way to store our data.

### What organizations are involved in this project? Sources of funding, SPs partnering in onboarding, other service providers, etc.?
NDLABS (Lead SP) - Singapore
Tenet - Korea
Maike Storage - Vietnam
Rongyin - USA
INTERPLANETARY STORAGE PTE. LTD. - HK

## Transparency in KYC
_If you are not the data owner, please email filplus@fil.org with you and the data owner on a thread so at least the Fil+ governance team can act as a lightweight KYC check._

Are you going to offer NDAs to notaries?
 Yes
  
## Dataset description 
_What is being stored on the network? Please provide as many details as possible on the dataset and its size._
Development history of tobacco industry
Industry/health Knowledge Popularization
Industry/product research
Product evaluation
Experiment record

### Why is it useful to the Filecoin network?
_Please share details on how your project may use Filecoin in a novel way, extend or experiment with different use cases, or result in useful development in the ecosystem._
  We use Filecoin for storage and hope to have a better combination of Filecoin and web2's companies.

## Storage needs

Is the data to be stored in a single region, either due to geopolitical constraints or data owner policy?
 No

### Which SPs will you/the data owner be working with to store the data? 
_If all the SPs have not been chosen at the time of issue submission, feel free to edit and update the form as they are chosen. If you need support on finding reputable SPs, please check out filgram.io, filrep.io, plus.fil.org/miners, or Filecoin Slack channels: #fil-plus, #fil-deal-market_
  
| SP ID | SP org | SP region |
| f01740934 | NDLABS | Singapore |
| f01250837| Tenet| Korea|
| f01900537| Maike Storage| Vietnam|
| f01834253| Rongyin| USA |
|f01215819 | INTERPLANETARY STORAGE PTE. LTD. | HK|

### How were these SPs identified?
Community members may contact them through slack. 

## Notaries that support the project 
 _Notaries perform KYC/KYB to validate the legitimacy of data and organizations. To find supporting notaries please view the list of [round 3 notaries](https://github.com/filecoin-project/notary-governance/tree/main/notaries) and post your LDN application in the Filecoin slack channel #fil-plus-application-review. Feel free to update the form as you gain support over time and more notaries are willing to support your application._

| Notary name | Notary org | Notary region |
| name| org| region|

**Comment by kevzak** [comment]
Let's move forward with the updated notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@PluskitOfficial
@cryptowizzard

A few notes for assigned notaries:

This is technically the second allocation (it says third but it was because of trigger issue). 

Please review the usage thus far via CID checker report and leave a comment for the client as needed. 

Please comment on the application by Feb 16th.

If you chose not to sign, please leave a comment why so I can assign another notary if needed.

**Comment by cryptowhizzard** [comment]
Same abuse , still ongoing.

Notary's , please do not sign.
