### ISSUE TITLE
Notary Application: Ht Cloud

### ISSUE THREAD

**Issue by y905699146** [filecoin-project/notary-governance#656]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:  Kikou
- Affiliated organization:  Ht Cloud
- On-chain address to be notarized (recommend using a new address):  f1g2y5wwbal3zffqpydq72sjretjxzde4hefpnyqi
- Region of Operation: Greater China
- Country of Operation: China
- Use case(s) to be supported: Enterprise Monitoring Data
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: [Organization]

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
Ht Cloud is a company focusing on distributed storage technology, We started working on distributed storage technology since 2020,We have a lot of enterprise monitoring type data, We are very optimistic about Filecoin and want to put this data on the Filecoin network
our miner ID is : f01901379,f01909429,f0765071,f01030442,f01030424,f01030435,f01171513,f01870888,f01868918,f01125371,f01915287,f01922865,f01901351 with 144PiB
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
Through November 1, 2022:
total token: 1,019,122 FIL
Initial Pledge: 816,816 FIL
To tal Reward: 653,837 FIL
```

How did you acquire the FIL cited above?
```
It is mainly the proceeds from the company's business development and some institutional borrowings.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Ht Cloud is the world's leading Filecoin service miners, We've been active in the Filecoin community since 2020,We participated in the Filecoin Space Race in August 2020,We have been providing distributed storage technology services for enterprises that want to participate in Filecoin, We work in depth with a lot of data centers,Our goal is to help central enterprises build a complete storage system.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Company Nature: Co. Ltd
Nature:  Private Company
Registration Country: ShenZhen, China
Date of establishment: January 23, 2020
Size: over 50 employees
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Ht Cloud
HomePage: http://www.htymeta.com/
Wechat Official Account: https://mp.weixin.qq.com/s/vFI8WPVSXPECyerhS8XPqA
https://juejin.cn/user/360295547020487m
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://mp.weixin.qq.com/s/TOKtbQWl1n7JbsE_ameuMA
https://www.jinse.com/news/blockchain/1071858.html
https://www.jinse.com/news/blockchain/1149318.html
https://mp.weixin.qq.com/s/RL_xt1nU0odO4F2f8vvZaw
https://mp.weixin.qq.com/s/hRpeptongpi6KPuGjz-VHw
https://mp.weixin.qq.com/s/q_NCHUUHaVrNEnyc2IRHQA
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://github.com/y905699146
https://twitter.com/HCloud2020
Slack: imcracktopone
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
Please answer here.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
1. we will browse the official website of the client and some social media accounts to understand the main purpose of the client
2. we will evaluate and classify the customers according to the information of the survey
3. The client classification rules are as follows: https://docs.google.com/spreadsheets/d/1FLOJ3fVw3q-8Oa9AK_PSsyx7FhY3ceJuAKPQjZjH6Tc/edit#gid=0
4. Throughout the allocation and use the DataCap, we will establish a corresponding review mechanism.
5. We will continue to make follow-up visits and follow up on the follow-up results. Good customers will get more allocation and improve the quality of customers
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hardware wallet will be used to store the keys associated with the DataCap allocation address securely. 
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
First of all, we will do a detailed review of the applicant, including the customer's qualifications, information, industry influence and so on, At the same time, we will also check regularly to ensure that customers who meet the requirements can continue to use, and those who do not meet the requirements will be rejected.

For individual applicants, their identity will be verified through account activity and third party account, such as Twitter, slack, Discord, which will prove that the customer is a valid user and not a machine.

For organizations, we will set up a due diligence team to conduct a complete review of the application form submitted by the applicant to ensure proper allocation and effective use of DataCap, and to conduct random spot checks after allocation to establish a credit system.

We will review through the following questions:
1. Team/personal introduction
2. Applicant's relationship to the organization
3. How many datacaps do you need.
4. Where does the data come from.
5. How to use this data.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We strictly monitor the use of datacap,Applicants need to assign datacap to at least three miners,We ask our customers to disclose relevant information and regularly record it in the github repository
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we will be releasing all the records to the github repository
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub repo.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None
```

**Comment by Kevin-FF-USA** [comment]
Hi @y905699146,

Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. 
***This cannot be from your personal account. You Must include the address of your Organization.**  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to this GitHub application

**This step needs to be completed by 28NOV.**  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[656.pdf](https://github.com/filecoin-project/notary-governance/files/10159354/656.pdf)

**Comment by Kevin-FF-USA** [comment]
@y905699146 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
