### ISSUE TITLE
Notary Application: Define

### ISSUE THREAD

**Issue by Alex11801** [filecoin-project/notary-governance#657]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Alex Kim
- Affiliated organization: Define Platform
- On-chain address to be notarized (recommend using a new address): f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
- Country of Operation: Republic of Korea
- Region of Operation: Asia minus GCR
- Use case(s) to be supported: Web 3.0 / Decentralized Applications, Web 2.0 Applications, User Content (Personal Storage, User Generated Media) and Media & Entertainment.
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Define has participated in the Filecoin Plus Program as a client since November 2021. We have applied 5PiB DataCap (https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/91), made storage deals and allocated 150 TiB DataCap to the storage miners.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
N.A.
```

How did you acquire the FIL cited above?
```
N.A.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Define has participated in the Filecoin Plus Program as a client since November 2021. We have applied 5PiB DataCap (https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/91), made storage deals and allocated 150 TiB DataCap to the storage miners.
Also, we applied to be a Fil+ Notary and got 1 PiB DataCap though no client made a request from Define. 
Link to the application, https://github.com/filecoin-project/notary-governance/issues/463
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N.A. 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
DeFine is the social NFT platform for all creators including artists, musicians, influencers, gamers, and athletes. The platform facilitates all social interactions, engagements and communications for creators and their fanbase with digital assets like NFTs and social/fan tokens, and real assets on the blockchain. Owners of social/fan tokens will have many benefits including special access to the creators’ NFTs, merchandise, content, etc. while being part of a private community. It is also a social platform for all participants in the digital world where they can interact with each other and be identified through their NFT social profiles which are based on their contributions and achievements in the digital world. Ultimately, the DeFine will serve as a social platform for creators and users to define how to engage with each other and build communities in the digital world.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
- Website: http://www.define.one
- Twitter: https://twitter.com/DeFinePlatform
- Telegram: https://t.me/DeFinePlatform
- Discord: https://discord.com/invite/UYahw74GdG
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
- DeFine Partners With Cere Network To Build a Decentralized and Secure NFT Ecosystem 
https://www.newsbtc.com/press-releases/define-partners-with-cere-network-to-build-a-decentralized-and-secure-nft-ecosystem/

- DeFine and Tron Form Strategic Partnership to Build NFT Ecosystem and Bring Social Profile System on Tron Network 
https://www.prnewswire.com/news-releases/define-and-tron-form-strategic-partnership-to-build-nft-ecosystem-and-bring-social-profile-system-on-tron-network-301350452.html

- DeFine Will Be Listed on the Huobi Pioneer Zone Following by Primepool Mining Activity 
https://www.dailyadvent.com/news/bb9d3bc4d3250bc945253b9de01d3c75-DeFine-Will-Be-Listed-on-the-Huobi-Pioneer-Zone-Following-by-Primepool-Mining-Activity
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
- Twitter: https://twitter.com/DeFinePlatform, 49.4k Followers
- Telegram: https://t.me/DeFinePlatform, https://t.me/DeFinePlatform_kr, 12000 members
- Discord: https://discord.com/invite/UYahw74GdG, 5612 members
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
- DeFine Partners With Cere Network To Build a Decentralized and Secure NFT Ecosystem 
https://www.newsbtc.com/press-releases/define-partners-with-cere-network-to-build-a-decentralized-and-secure-nft-ecosystem/

- DeFine and Tron Form Strategic Partnership to Build NFT Ecosystem and Bring Social Profile System on Tron Network 
https://www.prnewswire.com/news-releases/define-and-tron-form-strategic-partnership-to-build-nft-ecosystem-and-bring-social-profile-system-on-tron-network-301350452.html

- DeFine Will Be Listed on the Huobi Pioneer Zone Following by Primepool Mining Activity 
https://www.dailyadvent.com/news/bb9d3bc4d3250bc945253b9de01d3c75-DeFine-Will-Be-Listed-on-the-Huobi-Pioneer-Zone-Following-by-Primepool-Mining-Activity
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We refer to the allocation strategy of Filswan and Union Labs because they are excellent notaries in the Filecoin Plus Program as they are known. So we prefer to follow and learn from the great predecessors for better working in the program.

The most important thing about DataCap allocation is to ensure that the client utilizes DataCap to store real data. so I firstly specify some rules to figure out the true identity of the applicant.
1. Browse their official website to get a general understanding of the client. 
2. Require clients to provide the company's registration information(usually by email) from government related websites to ensure the authenticity of client information.
3. Inquire about the client's position/organization/R&D team/allocation plan/use case etc. 
4. Then I will classify clients based on their industry reputation and scale etc. All applicants will be divided into eight categories to determine the amount of datacap they will get. The following Rubric will be the primary guideline I use when evaluating a client and determining their DataCap allocation.   
For your reference: https://docs.google.com/spreadsheets/d/1ED8dgWkAkPh3z9x2KxPeYbt3HlwTa04HpRATErLFTIA/edit?usp=sharing
These scoring guidelines can serve as a tool of assessment and adding a level of consistency across the board.
5. Throughout the allocation and use the DataCap, we will establish a corresponding review mechanism. Good client will be rewarded, bad client will be punished. The quality of the client will be optimized gradually.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will use an offline hardware wallet exclusively to verify for the accounts associated with the Datacap allocation. And multi-sig wallet is to be used when more clients are coming in.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We refer to the Client Due Diligence strategy of Filswan and UnionLabs because they are excellent notaries in the Filecoin Plus Program as they are known. So we prefer to follow and learn from the great predecessors for better working in the program.
There will be three stages in the verification process to ensure the DataCap is used properly. Moreover, the greater the amount of DataCap requested, the more restricted the client scrutiny will be. The details are as follows:

```
| Stage | New Client/small DataCap request | Repeat Client/large DataCap request |
| -- | -- | -- |
| Before the allocation | 1. Ask for some details about his organization and use plan<br>2. Verify the submitted information<br>3. Score them according to our score sheet | 1. Learn about his DataCap usage<br>2. Collect details<sup>[1]</sup>about his organization and use plan.<br>3. Detailed review of related information<br>4. Score them according to our score sheet |
| During the allocation | 1. 2-day waiting period for possible adjustments or disagreements<br>2. Allocate a small amount of DataCap (less than 5TB) for trial | 1. At least a 7-day waiting period for due diligence, usage review, possible adjustments or disagreements.<br>2. A DataCap allocation agreement will be signed to clarify the rights &amp; responsibilities of each party.<br>3. Allocate DataCap carefully after scoring |
| After the allocation | 1. Provide help and guidance for DataCap users<br>2. Communicate with customers on a regular basis to know his DataCap usage and leave him a good impression on Filecoin | 1. Conduct routine verification to ensure the DataCap is used properly<br> 2. Introduce a feedback mechanism to sync DataCap usage list and to optimize suggestion<br>3. If the applicant commits any violation, we will take actions to stop further allocation or even take punishment actions<sup>[2]</sup>. |
```

[1] Details include but not limited to:
     1. Entity Information
     - Formation documents - this includes certificates of registration/incorporation/information.
     - government-issued identification number for the entity
     2. Authorized Signatory Information
     - evidence of the authorized signatory’s authority to act on behalf of the application entity
     3. Beneficial Owners(optional)
     - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or something similar to verify the ownership, and also the following information for each of them:
     - legal name;
     - date of birth;
     - street address (P.O. box number is not acceptable);

[2] Punishments may include disqualifying the applicant certification, publicizing wrong actions in the community, stopping further allocation forever and fining the Filecoin pledged by the client etc. In the extreme scenario, legal options will also be taken basing on the aforementioned DataCap allocation agreement.

Question for clients:
1. Introduction of yourself/ your organization(with links)
2. Use case
3. Location
4. Max DataCap Allocation
5. Filecoin address
6. Miners you intend to allocate DataCap with allocation proportion
7. Specific requirement of miners and storage service
8. For-profit or not
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Firstly, from the answers about the use plan and further investigation, I can know some details about his allocation plans. When scoring applicants according to the above sheet, the more geographical distribution, use cases and miners’ assignments, the higher the score and larger datacap he will likely get. 
Next, we will keep tracking clients’ information such as the DataCap distribution records, related miner addresses and storage providers, to ensure that they are consistent with their words and deeds.
Finally, a reward and punishment mechanism will be established. If someone over-allocating datacap to a single entity, I will refuse further allocation and issue a warning which will be public to the Filecoin community. On the contrary, reputable clients have the opportunity to obtain more datacap.
We will also employ the scan tools developed by Filswan for monitoring verified deals with miners, content scanning tools for violation of local law and policies, usage of the data, verified data distribution. https://github.com/nebulaai/trusted-miner. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
The record of my allocation decisions will be accessible and public on GitHub to be supervised by the Filecoin governance team, notaries and the community.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We plan on keeping records of our allocation decisions via a Github repo https://github.com/filecoin-project/filecoin-plus-client-onboarding and the website: https://filplus.info/#/
We will also try to build an open source project for auditing purposes.
- The allocation plan and criteria is public accessible  
- Each approval and allocation is on Github
- All the conversation of a datacap interview with the client is recorded under the awareness of the client and saved securely.
- Client submission related documents are securely saved for future auditing.
- Client data quotation usage is online traceable. All the datacap allocated will be saved in the database for future analysis and auditing. 
We are open to any audit requests.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
Level 5
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
We have applied 5 PiB DataCap and allocated 150 TiB DataCap to SP miners for now. Link to the application, https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/91
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
N.A.
```

**Comment by Alex11801** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecjh2hwgyet3u6pytlz6bclsfl5n7gsu4fg2vhqmhab3duwapsz72
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjh2hwgyet3u6pytlz6bclsfl5n7gsu4fg2vhqmhab3duwapsz72

**Comment by Kevin-FF-USA** [comment]
Hi @Alex11801,

Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. 
***This cannot be from your personal account. You Must include the address of your Organization.**  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to this GitHub application

**This step needs to be completed by 28NOV.**  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Alex11801** [comment]
Verification email has been sent to NOTARYELECTION@FIL.ORG. Please check. Thank you!

**Comment by Kevin-FF-USA** [comment]
@Alex11801 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by Alex11801** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebt6lgdeic4dfr2yzusvqxkflqsp5xaxk6yqajbfwazoyanqfrgok
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebt6lgdeic4dfr2yzusvqxkflqsp5xaxk6yqajbfwazoyanqfrgok

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzacec6caqpqpgpual4it27nz3kr7neqnnzrtibbu4oigcw3xkouo3q56
