### ISSUE TITLE
Notary Application: Greaterheat

### ISSUE THREAD

**Issue by AlanGreaterheat** [filecoin-project/notary-governance#659]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:Neo
- Affiliated organization: Greaterheat Pte.Ltd.
- On-chain address to be notarized (recommend using a new address):f13wcousautmwszugqciilvo4vwz6zcntjul23rja
- Country of Operation: Asia minus GCN
- Region of Operation: Asia minus GCN
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Greaterheat is a Singapore-based Web3 technology company dedicated to using cutting-edge web3 technologies to meet the needs of large-scale applications. filecoin is an open source distributed storage marketplace and protocol that can truly do the job of storing the most important information in human society. Distributed storage is considered the underlying infrastructure for web3, and GH has therefore chosen to work with the Filecoin network to build a web3 infrastructure.

Greaterheat's predecessor, Hangzhou Diancun Technology, was founded in Hangzhou, China in 2018, and GH headquartered in Singapore in June 2021, and currently has data centers in Singapore, the US, and Hong Kong, with a total on-chain size of 500 PiB+. The largest node (f0134867), the company size is over 100 people. GH as a storage provider, actively participates in filecoin ecological projects, such as Datacap, Moon Landing, Slingshot V3, Orbit, etc.

GH historical development milestones
2018.6 The predecessor of GREATER HEAT, Diancun Technology, was established in Hangzhou, China, and established a distributed storage team; 
2019.2 Became the first node [dcnode] of Filecoin Developer Network in Asia;
2019.11 Released distributed storage server DC-M9, which was well received by the market;
2020.8 Participated in SPACE RACE and became the first node [t01155] to appear, and the cluster technology was certified and recognized;
2021.4 Storage scale exceeds 200 PB;
2021.6 Established GREATER HEAT in Singapore, web3 business is globalized
2021.10 From China to Singapore, completed the 3 00PB Filecoin survival migration, making history;
2022.4 The scale of storage power exceeds 500PB
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f0134867 (518,950.2191 FIL)
f01135819 (375,866.7586 FIL)
f0145060 (346,510.6492 FIL)
f01880047 (96,528.7804 FIL)
f01877571 (102,490.3299 FIL)
f01882184 (116,860.8496 FIL)
Fil total 1557207.587, we only disclose part of our nodal assets, which is about 1/4 of our total assets
```

How did you acquire the FIL cited above?
```
It is mainly the proceeds from the company's business development and some institutional borrowings.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
GH has been following fil developments since 2018 and has been promoting and publishing Filecoin community related activities on Youtube, Twitter, Facebook, Medium and other platform channels, providing some of the links below.
https://www.greaterheat.com/
https://www.youtube.com/watch?v=lc8jIIup2PA
https://www.youtube.com/watch?v=pKLpm6korMs
https://www.youtube.com/channel/UCqT8pfW8hzAseJv2IRvq7DA/videos
https://sg.linkedin.com/company/greaterheat
https://medium.com/@greaterheat
https://twitter.com/GreaterHeat/status/1575321180956856320
https://twitter.com/GreaterHeat/status/1574331633754218501
https://twitter.com/GreaterHeat/status/1574275456492179457
https://twitter.com/GreaterHeat/status/1574238975966867456
https://twitter.com/GreaterHeat/status/1573859131198300160
https://twitter.com/GreaterHeat/status/1573612515694505987
https://twitter.com/GreaterHeat/status/1573253396353753089
https://twitter.com/GreaterHeat/status/1571800421974560769
https://twitter.com/GreaterHeat/status/1569949276096331776
https://twitter.com/GreaterHeat/status/1569529775177474048
https://twitter.com/GreaterHeat/status/1559734690374123520
https://twitter.com/GreaterHeat/status/1559468664424140801
https://twitter.com/GreaterHeat/status/1559121273019834368
https://twitter.com/GreaterHeat/status/1559121278015275009
https://twitter.com/GreaterHeat/status/1558025664615198720
https://twitter.com/GreaterHeat/status/1557245772995112960
https://twitter.com/GreaterHeat/status/1557187691573563392
https://twitter.com/GreaterHeat/status/1554010169650315264
https://twitter.com/GreaterHeat/status/1553928809048846336
https://twitter.com/GreaterHeat/status/1552862509505208321
https://twitter.com/GreaterHeat/status/1549999124849647617
https://twitter.com/GreaterHeat/status/1549641761253113858
https://twitter.com/GreaterHeat/status/1547509632037711879
https://twitter.com/GreaterHeat/status/1547509027336519680
https://twitter.com/GreaterHeat/status/1535831088953978880
https://twitter.com/GreaterHeat/status/1534358452104929280
https://twitter.com/GreaterHeat/status/1534724968361054208
https://twitter.com/GreaterHeat/status/1509001800598552576
https://twitter.com/GreaterHeat/status/1574227214563913730
https://twitter.com/GreaterHeat/status/1577841676009160704
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
GH related technical staff actively make suggestions and issue on github to promote the whole Filecoin ecological security construction, some links are as follows：
https://github.com/filecoin-project/lotus/issues?q=is%3Aissue+author%3Ayhio+
https://github.com/filecoin-project/lotus/pulls?q=is%3Apr+author%3Ayhio+is%3Aclosed
https://github.com/filecoin-project/lotus/pull/4785
https://github.com/filecoin-project/lotus/issues/1917
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Organization: Greaterheat 
Positioning: Greater Heat is a Singapore-based Web3 technology company dedicated to using cutting-edge web3 technology to meet the needs of large-scale applications. Currently GreaterHeat has been a part of the Filecoin community for 4 years, and has been growing at over 500% per year for the past 3 years. It currently holds about 3% of the total storage capacity of the entire network, with customers in Southeast Asia and South Korea, and a team of over 100 people, with revenues of about $60 million in 2021.
Data centers: Singapore, Hong Kong, USA
Nature: Private Company
Registration Country: Singapore
Established: Jun, 2021, formerly known as Hangzhou Diancun Technology Co.
Size: over 100 employees
Services: cloud mining, zero-knowledge proof application development, technology export and support [open source technology and software
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://www.greaterheat.com/
https://hub.filecoin.io/case-study-greaterheat
https://twitter.com/GreaterHeat
https://www.youtube.com/channel/UCqT8pfW8hzAseJv2IRvq7DA/videos
https://sg.linkedin.com/company/greaterheat
https://medium.com/@greaterheat
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://hub.filecoin.io/case-study-greaterheat
https://hub.fil.org/sp-singapore-workshop
https://www.defidaonews.com/article/6765418
https://www.luxuo.com/leaders/tech/david-li-greaterheat-sets-his-sights-on-sea-and-beyond.html
https://new.qq.com/rain/a/20220725A098HL00
https://twitter.com/GreaterHeat
https://www.youtube.com/channel/UCqT8pfW8hzAseJv2IRvq7DA/videos
https://sg.linkedin.com/company/greaterheat
https://medium.com/@greaterheat
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter: @GreaterHeat 4,116 Followers
WeChat public platform: Diancun Technology 8862Followers（Please check the link：https://greaterheat.larksuite.com/file/boxusgMAkTS8VurqWAFAkI9iIAe）
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://hub.filecoin.io/case-study-greaterheat
https://hub.fil.org/sp-singapore-workshop
https://www.defidaonews.com/article/6765418
https://www.luxuo.com/leaders/tech/david-li-greaterheat-sets-his-sights-on-sea-and-beyond.html
https://new.qq.com/rain/a/20220725A098HL00
https://twitter.com/GreaterHeat
https://www.youtube.com/channel/UCqT8pfW8hzAseJv2IRvq7DA/videos
https://sg.linkedin.com/company/greaterheat
https://medium.com/@greaterheat
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We support all industries, with no restrictions on regions, industries, or types of company entities, as long as the data meets the specifications and regional legal and regulatory requirements. Accordingly, we have designed a special evaluation model to score our clients as a whole, please see the link at
https://greaterheat.larksuite.com/sheets/shtusYJarxTabJTszgs9zVpEcSb

We plan to allocate approximately 25% of Datacap on a quarterly basis, with each client requesting no more than 20% of the Datacap we have.

When reviewing applications, we will evaluate the applicant's basic information, time of establishment, number of employees, registered capital, social reputation, data distribution, data volume, and history in a comprehensive manner. We can
1、Browse the official website, media platform, business information, etc. to understand the basic information of the organization.
2、Require customers to verify information through the company's domain email.
3、We make a form file to record customer sealed information for subsequent verification
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We use a hardware wallet to store the private key to secure the account. github account and hardware wallet account are held by two separate people.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
All clients' applications must undergo a rigorous review, and the more datacaps applied for, the more rigorous the review.

We will review through the following ways.
1. requesting the necessary business licenses, business registration certificates, passport information documents, etc. (email communication is recommended to protect privacy).
2. checking the company's product type, business model and news status through social media accounts, official websites and other platform information.
3. check the online corporate information of the country/region where it is located, and initially verify the business information such as business scope, establishment time, registered capital, organization scale, and equity information.
4. confirming with the official mail whether the client subject is applying for Data Cap and confirming the identity and work information of the applicant.
5. Make certain tracking records to ensure customer storage compliance.

We will ask the following questions (flexible according to the client's reality).
1. Can you share some information about yourself/your organization, including online social media/website links, etc.?
2. How much data do you want to store, what is your data source, and can you provide some evidence to prove it?
3. What is your initial data storage plan like? What are the appropriate SPs being communicated with? Can you list their names?
4. What are you currently using for storage, and what is the approximate price, quantity, and frequency of use?
5. What is your strategy for uploading data to Filecoin?
6. Can you share the reality of your Datacap allocation usage to ensure Datacap usage compliance?
7. What data content are you storing and does this content comply with local laws and Filecoin community standards and regulations?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will proceed in the following ways and means.
1. upfront detailed and effective KYC, due diligence and explanation of rules are essential to encourage clients to assign Datacap to different SPs.
2. requiring clients to regularly disclose transaction information.
3. we will conduct regular checks through the filplus.info website to record Datacap transactions and allocations and verify them in conjunction with client disclosures.
4. we will give a reminder once we find that the client has violated the rules. If the violation is serious, we will disclose the customer's illegal operation in the slack public community.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We will follow FIL+ guidelines and make our allocation decisions and audit process publicly available on Github.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
we will keep the public GitHub records and a private chat via Slack or Telegram.Besides, without disclosing any confidential information about our clients, we are happy to respond to reasonable inquiries or inquiries that community members may have regarding our DataCap allocation decisions.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
GH is determined to build the Filecoin ecosystem with the officials, so participation in the fil+ program is an important part of the job, no less than 20 hours per week. We have chosen the L5 level of service commitment.

L5: Average participation of more than 8 hours per week
* Maintain a top 5% ranking in the notary rankings
*Participate in 2 governance conference calls per month - Turn on webcam
*Join 2 workgroups
*Respond to SLACK inquiries within 24 hours
*Vote/comment on all proposals submitted
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
As a new notary applicant, no previous Datacap allocation was received.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
We currently have some business cooperation with Fei Yan - Kernelogic, Dcent and Piknik. Also in view of the concept of building Filecoin ecology together, we have regular filecoin ecology communication with newwebgroup, Nd labs, fatman and other organizations and notaries.
```

**Comment by Kevin-FF-USA** [comment]
Hi @AlanGreaterheat,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

    Your First and Last name
    Your Organization
    Your Country of Operation
    Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
    Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by AlanGreaterheat** [comment]
Hi, official partner、Kevin, the verification information is as follows, please check, thanks！～ Subject Line: Neo（Organizational Notary）, Notary Application: Greaterheat #659 Email Body: Your First and

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[659.pdf](https://github.com/filecoin-project/notary-governance/files/10159363/659.pdf)

**Comment by Kevin-FF-USA** [comment]
@AlanGreaterheat 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by AlanGreaterheat** [comment]
![image](https://user-images.githubusercontent.com/110453718/215659039-033f2c97-df36-46d0-8c74-6c461ba6ca7e.png)

@raghavrmadya @Kevin-FF-USA This is our new wallet address.

On-chain address to be notarized (recommend using a new address):f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui

**Comment by AlanGreaterheat** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedrkethp2zaszvghgae732rnzbogmnsyjsrtzevpjhead2znj7vlu
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrkethp2zaszvghgae732rnzbogmnsyjsrtzevpjhead2znj7vlu
