### ISSUE TITLE
Notary Application: Sequoia Protocol

### ISSUE THREAD

**Issue by zhen2010** [filecoin-project/notary-governance#660]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:Adam Chan
- Affiliated organization: Sequoia Protocol Foundation
- On-chain address to be notarized (recommend using a new address):f1kgikv44577jis2zvj4baltbbqcifho5th4apdgy
- Country of Operation: Australia
- Region of Operation: Oceania
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Sequoia Protocol members first focused on the filecoin project in 2017. We encourage users to participate in filecoin infrastructure building through NFT. Our project was launched with $40 million and has contributed more than 100PiB storage space to the filecoin network. We currently have operations in the APEC regions such as Australia, Hong Kong and Singapore.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
As of today, we have a total of over 800,000 Filecoin tokens.
f01169721
f01169722
f01169723
f01169724
f01169725
```

How did you acquire the FIL cited above?
```
It is mainly the proceeds from the company's business development and some institutional borrowings.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We develop the SEQ project, so that users can participate in the construction of filecoin network through NFT or games.
https://finance.ifeng.com/c/8KkstEFUGAK
https://www.ctoutiao.com/3099600.html
http://www.jinsecaijing.cn/open/4qnz6n.html
https://twitter.com/official_seq/status/1583029920015736833
https://twitter.com/GiveAwayHost/status/1587741072427393024
https://twitter.com/official_seq/status/1580737282583064577
https://discord.com/invite/YAVaKA2B7W
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N.a.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Organization: Sequoia Protocol
Nature:  private company
Registration Country: Cayman Islands
Established: 09 March, 2021
Size: over 50 employees
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://www.seqnft.cc/
Twitter：https://twitter.com/official_seq
Discord：https://discord.com/invite/YAVaKA2B7W
Telegram：https://t.me/SEQofficial
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://finance.ifeng.com/c/8KkstEFUGAK
https://www.ctoutiao.com/3099600.html
http://www.jinsecaijing.cn/open/4qnz6n.html
https://twitter.com/official_seq/status/1583029920015736833
https://twitter.com/GiveAwayHost/status/1587741072427393024
https://twitter.com/official_seq/status/1580737282583064577
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Personal social media:
Telegram：https://t.me/SEQofficial 
Twitter：https://twitter.com/official_seq
Discord：https://discord.com/invite/YAVaKA2B7W
Follower base:
Telegram:5000+
Twitter:4000+
Discord:7000+
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://finance.ifeng.com/c/8KkstEFUGAK
https://www.ctoutiao.com/3099600.html
http://www.jinsecaijing.cn/open/4qnz6n.html
https://twitter.com/official_seq/status/1583029920015736833
https://twitter.com/GiveAwayHost/status/1587741072427393024
https://twitter.com/official_seq/status/1580737282583064577
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We will conduct a completed KYC audit of the customer, and we believe that we should collect the following information to confirm the authenticity of the customer:
1. Basic information
- Physical documents (company registration information, certificates, etc.)
- Certificate number issued by the government
2. Signature information / authorization document
Evidence that authorizes the signatory to act on behalf of the entity
3.Authorized person information
- Name
-Personal identification code (ID card / social security number / passport number)
- Street address
4.Customer profile, use case
Customers should provide a detailed introduction to the use of DataCap, including an introduction to entity information, examples of use cases, customer's geographic location, requested quota, copyright notice, etc
After completing the above basic information review, we will allocate DataCap according to the development plan and completion of the project, and monitor the customer's DataCap usage in the subsequent process.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will use hardware wallets for DataCap-related accounts, and monitor and audit DataCap usage.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 
In the early stage, all clients are required for an onboarding process to be qualified. 
Firstly, I need to collect information including:  
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information. 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name.
 - street address (P.O. box number is not acceptable). 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence. 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 
 With these provide, an interview and data source checking process need to go through. After that, an agreement should be signed for the next step - gradually allocate datacap and let the client gather more credit. 

The questions will cover the following areas that to ensure the DataCaps are properly allocated:

1.Introduction of yourself/ your organization (with links);
2.Use case examples and scope;
3.Geographic location of the client;
4.DataCap Allocation Requests Amount;
5.Filecoin On-Chain Address;
6.Declaration of Copy rights and Legal Compliance Requirements;
7.Specific requirement of miners and storage service
Nature Of Business (Government, Public, Private, NGO)
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
First of all, we establish an allocation schedule for each customer so that we can continuously track and monitor it. If the customer does not allocate DataCap, we will impose penalties through mechanisms such as deduction, reduction of quota, blacklist, etc.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes. We are open to any audit request from private and public channels.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Yes. We will use github repo to make allocation decisions and keep records.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
We will have one full-time employee(40 hours/ Week) responsible for communication and DataCap management. We have chosen the L5 level of service commitment.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No other associations.
```

**Comment by Kevin-FF-USA** [comment]
Hi @zhen2010,

Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

    Your First and Last name
    Your Organization
    Your Country of Operation
    Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
    Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by zhen2010** [comment]
> Hi @zhen2010,
> 
> Thanks for applying to become a Notary in the Fil+ program!
> 
> As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. *This cannot be from your personal account. You Must include the address of your Organization.
> 
> Subject Line: Notary Name, Application Number Email Body:
> 
> ```
> Your First and Last name
> Your Organization
> Your Country of Operation
> Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
> Link to this GitHub application
> ```
> 
> This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.
> 
> Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2
> 
> Thank you!

Hi @Kevin-FF-USA ，We have already sent the email as required

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[660.pdf](https://github.com/filecoin-project/notary-governance/files/10159366/660.pdf)

**Comment by Kevin-FF-USA** [comment]
@zhen2010 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
