### ISSUE TITLE
Notary Application: RawTech Ventures

### ISSUE THREAD

**Issue by RawTechVentures** [filecoin-project/notary-governance#661]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: RawTech Ventures
- Affiliated organization: RawTech Ventures
- On-chain address to be notarized (recommend using a new address): f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
- Country of Operation: UK
- Region of Operation: Europe
- Use case(s) to be supported: General 
- DataCap requested for allocation (10TiB - 1PiB):500TiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
May. 2021 we invested our first Filecoin project. (Storage Space Provider)
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
We do not intend to make it public.
```

How did you acquire the FIL cited above?
```
Our own foundation.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We provide below service:
1. Smart Contract Code Auditing(ETH/BSC/Polygon)
Code audit is a comprehensive analysis of source code in a programming project with the intent of discovering bugs, security breaches or violations of programming conventions.

2. Tokenomics Advisory
The study of the economics of crypto tokens or cryptocurrencies is called tokenomics. It fundamentally involves studying the factors that impact the demand and supply of tokens.

3. DAO Governence Advisory
A decentralized autonomous organization (DAO) is an organization that runs on a blockchain protocol fully and autonomously in accordance with rules encoded via smart contracts.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Mission: 
Make raw Web3 technologies well-done. 
Feature: 
First Tech-driven Crypto Ventures with more than 20+ Web3 engineers.
Brief Information:
RawTech is an investment firm focused on supporting the innovative Web3 projects and protocols of next era. Our approach is strategic, long-term, ecosystem-oriented. We not only support our portfolio with additional capital, but also empower our portfolio with the best Web3-related technical support, exclusively on internet computing and distributed storage. 
RawTech is featured with its strong technology middle-office. Our middle-office usually supports our portfolio on engineering, code audit, smart contract security. Our front-office also specialized in helping our portfolio on governance mechanism design and token omics design. Our investment: Metaloop (Airdrop Platform for college student worldwide)
MPC Vault (Secure Multi-Party Computation for Enterprises)
MeMusic (Web3 music platform)
Gamefi.ai (Gamefi Asset Trading Platform）
![RawTechVentures](https://user-images.githubusercontent.com/117442528/201018622-22dc6be4-11b6-4619-8981-5329c8b96551.png)
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: http://www.rawtechvc.com/ 
Twitter:@RawTechVC https://twitter.com/rawtechvc
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Twitter:@RawTechVC https://twitter.com/rawtechvc
https://www.romestartupmap.com/investors/rawtech_ventures/portfolio
https://www.jinse.com/lives/303402.htm    
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter:@RawTechVC https://twitter.com/rawtechvc
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
Twitter:@RawTechVC https://twitter.com/rawtechvc
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Our allocation strategy seeks to emphasize the key question "how much does the Notary trust the client?"
I have set up thresholds with varying degrees of trust, which includes KYC. 
We define 7 varying degrees of trust. The Rubric will be the primary guideline we use when evaluating a client and determining their DataCap allocation. Please refer below sheet for detail.
These scoring guidelines can serve as a tool of assessment and further add a level of consistency across the board.
![RawTech](https://user-images.githubusercontent.com/117442528/201019031-597e649f-2bdc-4b97-b438-404e691abc83.png)
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Via Ledger. We have dedicated staff to manage ledger.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will ask questions under the client's application.
Please describe answers as much specificity as you can.
1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.)
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. How many miners do you plan on allocating the DataCap? If you have a specific SP(s) ,how you would like to allocate a DataCap, please specify.
6. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing? 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e. making deals with a single SP entity.
```
We will also use Filecoin-related platforms to confirm. https://filplus.info/
To make sure deals are not distributed within a single SP entity, I plan to check on a regular basis to eliminate the concerns.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Both GitHub and my email can do it.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L3
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No.
```

**Comment by Kevin-FF-USA** [comment]
Hi @RawTechVentures,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

    Your First and Last name
    Your Organization
    Your Country of Operation
    Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
    Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[661.pdf](https://github.com/filecoin-project/notary-governance/files/10159367/661.pdf)

**Comment by Kevin-FF-USA** [comment]
@RawTechVentures 

Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @RawTechVentures, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by RawTechVentures** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebvgtrryebuuj6xv5pnsra6skkvlrxv7mp4ydhehcdq5je62miun6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvgtrryebuuj6xv5pnsra6skkvlrxv7mp4ydhehcdq5je62miun6

**Comment by RawTechVentures** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedzimgxa4b6dmygzsvws7d423ftswr4vng2slglzlkkpcih7ag4tg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzimgxa4b6dmygzsvws7d423ftswr4vng2slglzlkkpcih7ag4tg
