### ISSUE TITLE
Notary Application: StorSwift

### ISSUE THREAD

**Issue by coder-lb** [filecoin-project/notary-governance#663]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: StorSwift
- Affiliated organization: StorSwift
- On-chain address to be notarized (recommend using a new address): f1dktm3abgn7wkpepxab4q3eaw24qktizk4esfzyy
- Country of Operation: China
- Region of Operation:  Greater China Region (GCR)
- Use case(s) to be supported: User Content (Personal Storage)，Public or Open Data (Scientific datasets, research data, government or historic), Professional Services (Hosting Reseller, Long-term Backups, Data Warehousing), Developer Tools (Package Managers, Automatic Notaries, Web2 to Web3 integrations), Decentralized applications 
- DataCap requested for allocation (10TiB - 1PiB): 1 PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, **Storage Provider IDs**, significant projects or contributions (with links).

```
StorSwift has been contributing to Filecoin Project since Filecoin was still in its testnet phase from 2019. The contributions, including but not limited to, can be summarized in a variety of ways such as:   
1) Offer technical solutions for operating storage provider from testnet to mainnet; 
2) Participate in Space Race and help to run several storage providers; 
3) Provide additional technical services like sealing as a service, devops optimization, and security enhancement. 

GitHub:https://github.com/storswiftlabs, https://github.com/storswift

Significant contributions(with links):
A: we provide multiple patches to Filecoin projects, including:  
https://github.com/filecoin-project/lotus/pull/6658 
https://github.com/filecoin-project/lotus/pull/8751  
https://github.com/filecoin-project/lotus/pull/8854  
https://github.com/filecoin-project/lotus/pull/8787  
https://github.com/filecoin-project/lotus/pull/8696  
https://github.com/filecoin-project/lotus/pull/8545  
https://github.com/filecoin-project/lotus/pull/7310  
https://github.com/filecoin-project/lotus/pull/7027  

B: we develop multi-Sector Memory Pool Support for the Sealing Precommit Phase 1
code: https://github.com/storswiftlabs/rust-fil-proofs-mpool  

C: we develop Lotus offline signature solution
Code: https://github.com/storswift/lotus-offline-sign

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
No disclosing for now
```

How did you acquire the FIL cited above?
```
SR1/SR2/Filecoin Storage Provider Technical Services
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We have been participating in Filecoin community from testnet phase in 2019.
Firstly,StorSwift, as a Web3 development team, has provided multiple patches to Filecoin projects, including:  
https://github.com/filecoin-project/lotus/pull/6658 
https://github.com/filecoin-project/lotus/pull/8751  
https://github.com/filecoin-project/lotus/pull/8854  
https://github.com/filecoin-project/lotus/pull/8787  
https://github.com/filecoin-project/lotus/pull/8696  
https://github.com/filecoin-project/lotus/pull/8545  
https://github.com/filecoin-project/lotus/pull/7310  
https://github.com/filecoin-project/lotus/pull/7027  

Besides, StorSwift has also developed related Filecoin modules, and successfully got the dev-grants. Please note the following examples and links.  

1. Multi-Sector Memory Pool Support for the Sealing Precommit Phase1  
This module seeks to largely reduce memory consumption for PreCommit Phase. Hence, more tasks can run on the same machine, which effectively cuts costs.  
Code: https://github.com/storswiftlabs/rust-fil-proofs-mpool  
Documents: https://github.com/storswiftlabs/rust-fil-proofs-mpool/blob/master/storage-proofs-porep/src/stacked/vanilla/create_label/mem_pool_arch.md

2. Lotus offline signature solution  
This module makes Filecoin accounts more secure. That means there is no need to keep the owner keys and other keys on the servers.  
Code: https://github.com/storswift/lotus-offline-sign
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
StorSwift has made the security solution available to many partners in Filecoin ecosystem.  
Additionally, StorSwift has provided the offline signature solution. It adds an extra layer of security to Filecoin accounts. So it's unnessary to keep the owner keys and other keys on the servers any more.  
Code: https://github.com/storswift/lotus-offline-sign  
```

### Organizational Reputation
Please describe the nature of your organization, **including the country of registration, size of the organization, and time since inception.**

```
StorSwift is a HK-based technology company that specializes in Web3 infrastructure solution with its branch offices in Shanghai & Wuhan. It was found in 2014. It provides technical services globally. StorSwift has tons of experience in developing, deploying and maintaining large-scale storage and computing systems. We actively bring in enterprise storage, devops and security technology to Web3 industry.  
Since 2018, StorSwift has made enormous contributions to the ecosystem of IPFS & Filecoin, involving hardware & software solutions, security enhancement, implementing patches and dedicated software modules.
```

Please share any relevant details to help substantiate information about your organization (**website, named officers, links to social media profiles**).

```
Website: https://storswift.com
Twitter: https://twitter.com/StorSwift
Github: https://github.com/storswiftlabs, https://github.com/storswift
Github handle: @spaceT9
Slack account: coder-lb, marco-StorSwift, hy (StorSwift)  
Zhihu column: https://www.zhihu.com/column/storage (31 articles, 749 followers)
Wechat public account: storswift (1000+ followers)
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)  
  
```
StorSwift has been striving for technical optimization for Filecoin. Please read this news to get the details.  
https://twitter.com/Filecoin/status/1439380971376291842
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Slack account: coder-lb, marco-StorSwift, hy (StorSwift)  
Github handle: @spaceT9
Zhihu column: https://www.zhihu.com/column/storage (31 articles, 749 followers)
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
StorSwift has been striving for technical optimization for Filecoin. Please read this news:
https://twitter.com/Filecoin/status/1439380971376291842
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.

The detailed scoring criteria & allocation sample is attached below:    
https://docs.google.com/spreadsheets/d/17zxUuOvuLQnnMqmU9svinMAodMXopWw6/edit?usp=sharing&ouid=113881245671608158343&rtpof=true&sd=true

```
We carefully read the roles/responsibilities as a notary and well acknowledge that DataCap allocation must be commensurate with the level of trust of a certain client. To prevent any bias harming the network ecosystem, we worked out a plan to make sure the DataCap is granted fair and square. The base principles are divided into two parts, one is for first allocation and the other is for later rounds of allocation.

First allocation:
DataCap amount decision will strictly abide by the general principles - lesser of 5% of total DataCap requested or 50% weekly allocation rate, whichever lower should prevail. Plus, we will consider the following factors.
1) Client identity. We will score every client on a scale of 1-5 based on the information of official website authenticity and age, the social media account age and followers, in a bid to prove the identity and true intention for application.
2) Organization reputation. Judging from the time engaged in FileCoin system, we will know whether or not the client is a mature participant for long-term development. And from the size of company, business revenue  and staff number, we can tell if the business has the real storage demand for the amount requested or not.
3) DataCap usage strategy. Clarify how many SPs will be selected, which regions will be located, the more decentralized the geography location, the higher score it will be; more details will be welcome such as sealing speed or other preference like retrieval service.
4) Performance history. If a client applied dataCap before and successfully made deals with SPs, that makes the Client more reliable; the allocation decision transparency and execution performance also matter to evaluate the past performance.

The detailed scoring criteria is attached below, link: https://docs.google.com/spreadsheets/d/17zxUuOvuLQnnMqmU9svinMAodMXopWw6/edit?usp=sharing&ouid=113881245671608158343&rtpof=true&sd=true

Additionally, we value the data quality, but it's hard to set specific standards to evaluate that. We will carefully inspect the data with sufficient amount of samples, to avoid any artificial data used for self-dealing. 

Second allocation and onwards:
1) DataCap distribution in alignment with the aforementioned allocation plan. No single SP can make deals over 25%, we will withhold the DataCap outstanding if still no modifications made after kind warning.
2) 75% or above of granted DataCap used up.  If the requirement not met, then no more DataCap will be approved. 
3)  The data stored will be retrieved occasionally, to verify whether or not the data is useful and stored as agreed.
No obvious problem found, usually twice the amount of former allocation will be approved, we will keep monitoring the usage of DataCap at regular basis.

In summary, we value the authenticity and validity of data, we will exercise our rights pursuant to the scoring card attached above; we will make every decision with caution and promise to respond to the client within two working days. We will take small steps at first and then necessary social trust will be shown in a bid to benefit the clients with real demands for data storage.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The private keys will be stored in the hardware wallet with very restrict rules of usage.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Given the basic information provided in the application, we are going to ask rounds of questions for additional information, in a bid to prevent any fraud jeopardizing the community.  The questions can not be exhaustive, but the basic ones are as follows:

Before approval:
1. Can you please provide organization name both in Chinese and English, business license, official website, the stakeholder list with control over 25% of the entity; for individuals, please provide ID card copy, job title in which company, or other certificates to prove the identity. The abovementioned info will be sent by official email where applicable.
2. Why do you want to save your data in Filecoin system? Where did you hear of Filecoin system? Do you know some notaries or SPs, list the contact info if any. Did you act on behalf of notary or SP before? How long have you involved in the FileCoin system? Did you participate in any programs like Slingshot competition? Provide relevant links if any.
3. Can you describe your data in details? In what types? How much data in your hands for now? How many replicas as planned, explain the data composition (like 25% about project 1, 20% about project 2 and so forth)
4. Can you explain the increase rate of data per week in future if the total dataCap requested is larger than the amount you hold at present?
5. Can you explain the data is generated from business operations or research? Judging from the samples, whether or not the data is highly sensitive? Any personal privacy involved? Any violation against laws if the public has easy access to the data?
6. Have you contacted any SP? if any, please list their storage provider numbers; if not, do you know the ways to find SPs? What kinds of SPs will you choose? Do you have any preference for additional service like quick retrieval?
7. How many SPs as planned? How about the proportion of the storage for each SP? (25% or lesser)? In which area do you want to store your data?
8. Do you agree to make the transaction information publicly available after application is approved?

After approval:
1.	If the DataCap remains unallocated for a certain time, explain the reason why this happens? Any help needed from the notary to find some SPs?
2.	If a single SP stores over 25% of data, or the number of SP is lower than promised in application, ask them to make modifications as soon as possible and explain why?

The questions we are going to ask may vary due to different information provided by clients, we will ask further questions to clear the doubts as we see fit. Hopefully, if all the responses make sense, then the application will  be approved. But if we can not decide on our own, in fairness, we will invite other notaries to decide.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.

```
It is required to publish transaction information, including storage provider ID, allocation proportion and the source of storage providers, etc. , and will be reviewed at a fixed time.
We will check if or not >75% dataCap used up or not? and then check if or not the SP number is the same as planned, no single SP stores >25% of the deal, ask them to make adjustment if required; besides, we will pay attention to the  github/slack messages, detecting any risk for self-dealing; any misconduct about DataCap using is not allowed.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All decisions will be made public on Github. And we are willing to accept any audit from the community members when dispute arises.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?

```
We will make the allocation decision tracker public on Github.  
Our allocation decisions are self-explanatory to a high degree,because we made client scoring table and allocation decision tracker, the allocation amount is calculated by a formula automatically, it is relatively fair and objective.
In case of any disagreement/dispute, then initiate an allocation decision discussion publicly on slack or github, if the decision still remains controversial after that, then send a dispute resolution application to Notary Governance team within 10 business days, the governance team will rule accordingly. Besides, we can escalate the dispute issue to Notary Govenance call for discussion, all the notaries and  governance team will decide on the dispute.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 

```
We prefer Level 5. We guarantee that 10~15 hours per week will be spent on processing applications and responding to messages or leaving comments on proposals. We will attend 2 notary governance meetings every month. We plan to attend 2 or more working groups. Hopefully we will become new notary for this round,that means it is unrealistic to main a good ranking in Leaderboard for now, but we will spare no effort to raise the ranking in future. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No, we don't have any one.
```

**Comment by Kevin-FF-USA** [comment]
Hi @coder-lb,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

    Your First and Last name
    Your Organization
    Your Country of Operation
    Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
    Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[663.pdf](https://github.com/filecoin-project/notary-governance/files/10159369/663.pdf)

**Comment by Kevin-FF-USA** [comment]
@coder-lb 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by coder-lb** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceb6hhc2o3eujpes6d7h4aellfltlmpbz6ethr7zdbrr6nkknfzzpc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6hhc2o3eujpes6d7h4aellfltlmpbz6ethr7zdbrr6nkknfzzpc

**Comment by coder-lb** [comment]
I am from StorSwift which specializes in Web3 infrastructure solution. We are an agile team with rich experience in developing, deploying and maintaining large-scale storage and computing systems. 
As the business grows and evolves, too much business is mingled together. For avoid confusion, here I request to change the GitHub handle from @coder-lb to @spaceT9. The new account is only for Filecoin-related matters and the ledger address stays the same as old one.

**Comment by Kevin-FF-USA** [comment]
Hi @coder-lb
One final request/step before we change the Github handle on this application, Can you please modify the Individual reputation to include this new @spaceT9. 

![image](https://user-images.githubusercontent.com/94004586/236339596-f4f14be4-bdae-4f10-b05d-c5c57698eb1d.png)

**Comment by coder-lb** [comment]
> Hi @coder-lb One final request/step before we change the Github handle on this application, Can you please modify the Individual reputation to include this new @spaceT9.
> 
> ![image](https://user-images.githubusercontent.com/94004586/236339596-f4f14be4-bdae-4f10-b05d-c5c57698eb1d.png)

Updated. Thanks!

**Comment by Kevin-FF-USA** [comment]
Public Record:  Received confirmation and verification that @coder-lb  will be removed from the Registry and @spaceT9 will be the address on record.

**Comment by galen-mcandrew** [comment]
@ spaceT9 can you also comment here please? Currently not seeing any activity on that GitHub handle. https://github.com/spaceT9
<img width="1265" alt="Screen Shot 2023-05-24 at 11 49 00 AM" src="https://github.com/filecoin-project/notary-governance/assets/85587348/7050aaef-59fc-4cfd-9708-0a08077f9a6b">

**Comment by spaceT9** [comment]
> @ spaceT9 can you also comment here please? Currently not seeing any activity on that GitHub handle. https://github.com/spaceT9 <img alt="Screen Shot 2023-05-24 at 11 49 00 AM" width="1265" src="https://user-images.githubusercontent.com/85587348/240712539-7050aaef-59fc-4cfd-9708-0a08077f9a6b.png">

Yes, I am here. From now on, I will use my Github account to perform notary duties.
