### ISSUE TITLE
Notary Application: Tech Greedy

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/notary-governance#664]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Xinan Xu
- Affiliated organization: Tech Greedy
- On-chain address to be notarized (recommend using a new address): f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
- Country of Operation: United States
- Region of Operation: North America
- Use case(s) to be supported: Open dataset and enterprise data
- DataCap requested for allocation (10TiB - 1PiB): 1 PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Engaged in Filecoin ecosystem since the mainnet as
1. storage providers
2. Consultation service provider
3. slingshot participant starting phase 2.1, onboarded 30+ different dataset.
4. Developer for Filecoin onboarding tool Singularity
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Storage provider f064218, f0838923, f01752548 and pending rewards from Slingshot and slingshot restore.
Around 30k summing up available, locked and vesting over time.
```

How did you acquire the FIL cited above?
```
Block rewards, competition prize, grant, consulting, profit sharing.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Slingshot participant from 2.1 to 2.7, onboarded 30+ various dataset.
Part of Miner X.2 program
Part of Slingshot restore program, recovered 6 lost dataset.
Builder of Filecoin data onboarding tool Singularity
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Posted opinions and feedback for important FIPs such as FIP-36 and FIP-45
https://github.com/filecoin-project/FIPs/discussions/453
Report multiple bugs in https://github.com/filecoin-project/lotus/issues?q=xinaxu
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Corporation incorporated 1/11/2022 in Washington state, USA. Previously a sole proprietorship since 2016.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
LinkedIn profile - https://www.linkedin.com/in/xinan-xu-b868a326/
Named officer - Xinan Xu
Website for Slingshot UI - https://three_w_dot_techgreedy_dot_net
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.linkedin.com/company/79118189
Featured in Radius Blog https://mirror.xyz/joinradius.eth/vwmrtaEcas5Ei3Ff6kNor6FB2i9zTvp0SMRuxOv6l_A
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://www.linkedin.com/in/xinan-xu-b868a326/
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
Featured in Radius Blog https://mirror.xyz/joinradius.eth/vwmrtaEcas5Ei3Ff6kNor6FB2i9zTvp0SMRuxOv6l_A
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
I want to support the program by allocating proper amount according to below factors
- The client will need to follow the fil-plus or e-fil rules. This will be checked before each grant
- For existing clients, the datacap amount will be determined by their past performance and dataset size
- For new clients, the amount will always start small (100TiB) and gradually increase as they follow rules and demonstrate their performance.
- I will perform retrieval test and actually look at the data. Any cheater will be blacklisted from further allocation.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
I plan to use hardware secured wallet to make sure only I have the permission to sign datacap requests.
If a security breach happens, I will revoke my wallet and remove any datacap that was granted without permission.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
For grant smaller than 1TiB, I will perform less verification to encourage new people to enter Filecoin ecosystem
For grant larger than 100TiB, I will communicate with clients through messaging channel such as slack to understand their backgrounds, motivations and goals. The client will need to demonstrate their past success in deal making with multiple storage providers via either verified or unverified deals. 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
In general, I will utilize tools such as https://filplus.d.interplanetary.one/ to understand how they are making deals with various SP entities. I will also perform random retrieval test and look at the data to make sure actual data is stored.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
In public via github repo.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
In public via github repo.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
1 hour per day. Typical response time is < 24 hours via Slack or Github
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2141
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
My organization is not associated with any other organizations.
I myself am also employed by Protocol Lab so I will not perform notary activities that are related to Protocol Lab, such as approving datacaps proposed by PL.
```

**Comment by xinaxu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebkrvq7qbbabh5zab6m7xvhbzj3dgeqcdmvvh5bgy2xy3huxtvqxi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkrvq7qbbabh5zab6m7xvhbzj3dgeqcdmvvh5bgy2xy3huxtvqxi

**Comment by Kevin-FF-USA** [comment]
Hi @xinaxu,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

    Your First and Last name
    Your Organization
    Your Country of Operation
    Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
    Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Kevin-FF-USA** [comment]
@xinaxu,
We never received an email. Wanted to send a friendly follow up that this step is needed in order to verify your connection to the organization. Failure to reply will result in a decrease in your score and possible non-selection as a Notary.  If you have already replied (and we are overlooking), please paste the time stamp from sent message in this thread.

**Comment by xinaxu** [comment]
@Kevin-FF-USA Somehow I missed the github notification. Email just sent.

**Comment by Kevin-FF-USA** [comment]
@xinaxu 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by xinaxu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebavkvvl572ljocnuj3dsmaf57bzkepdvoauhcyymtxj3blwg3gkk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebavkvvl572ljocnuj3dsmaf57bzkepdvoauhcyymtxj3blwg3gkk

**Comment by xinaxu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebib4hhx2ikz26mgvxox6tqvegc4mmii26emt3efjmou7z4yolm5q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebib4hhx2ikz26mgvxox6tqvegc4mmii26emt3efjmou7z4yolm5q

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
bafy2bzaceawoo2mpespf2wvetkmvr7kazey4cqifnjjdpmua7cd2vg2epwrx4
