### ISSUE TITLE
Notary Application: Mkccstorage

### ISSUE THREAD

**Issue by han344906637** [filecoin-project/notary-governance#665]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:Hunter
- Affiliated organization: mkccstorage
- On-chain address to be notarized (recommend using a new address):f1hzdl5clst6ohd2mnkr2ldvrmcwiteaxyhhhp7ki
- Country of Operation: [Greater China]
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: Professional Services 、Developer Tools、Decentralized Applications、Public or Open Data、Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB):500TiB
- Are you applying on behalf of yourself or an organization?: Organization—— mkccstorage

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
mkccstorage is a web3.0 infrastructure provider, the company was founded in 2019 and has branches in China Beijing, Shanghai, Ganzhou, Shenzhen, Hong Kong, Chengdu and Vietnam, Korea Seoul. The core team started to evangelize IPFS in 2017, and in June 2018, we invested in constructing the first IDC in China. In August 2018, we became a co-organizer of the first IPFS Application Industry Summit and officially became a member of the Blockchain Professional Committee of the China Communications Industry Association, which marks that after our efforts, IPFS has been recognized by the China Communications Industry Association.

https://docs.qq.com/document/DWFNSS1p2UW5pa0hW?u=e89b1e9ec0f34958b7a6060f07db7969


From 2018-2022, we continued to evangelize IPFS globally, and we hosted the mkccstorage IPFS StarTour Conference in nearly 30 cities, including Shenzhen, Guangzhou, Hangzhou, Shanghai, Nanjing, Suzhou, Dalian, Beijing, Chengdu, Wuhan, Changsha, Xi'an, Nanning, Kunming, and Dali. We also hosted the IPFS Technology and Application Seminar Forum, and invested $1 million for two consecutive times, totaling $2 million, to be the co-organizer and diamond sponsor of the 3rd Shenzhen Distributed Storage Industry Conference in 2019 and 2020, and to hold the IPFS & Filecoin Distributed Storage Dinner with a capacity of 1000 people. We have directly and indirectly engaged at least 100,000 people in IPFS and Filecoin.

mkcctorage participated in Korea Smart Technology Exhibition：https://docs.qq.com/doc/DWEJJSmxIb0xYSVhJ?&u=7e32142d3a1c4e648074cebc4c828446

mkcctorage: NATIONAL TOUR SUMMIT: https://docs.qq.com/doc/DWFF5blpPc0tZUXNn

Events hosted by mkcctorage:
https://docs.qq.com/doc/DWHprTGlzYXhyWVZJ

We have won many awards, including the Global Blockchain IPFS Emerging Enterprise of the Year Award and the Top 20 Blockchain Technology and Application Design Project Award. We are also the vice president of Shenzhen Nanshan District Blockchain Application Association and the executive president of Huobi University Alumni Association.

Honors received by mkccstorage:
https://docs.google.com/document/d/1LlZ9INaBJjbJTocc-FxQ3Y8aMbS1SBO6/edit

In cooperation with government of Ganzhou, Jiangxi Province, we have invested a total of RMB 600 million to build a data center with an area of 50,000 square meters, which is specifically designed for distributed data storage and can accommodate 500,000 storage servers to work simultaneously.

We have worked closely with Binance, and we have successfully gotten Binance to onboard products such as FIL pledge and deposit , promote Binance's support for Filecoin.

Binance's strategic cooperation: 
https://docs.qq.com/pdf/DWExIVFhCSEd2dGpx

Meanwhile, our technical strength is also excellent, our total computing power globlally is close to 400P, and we have IDC in China Hong Kong, Qingyuan, Vietnam, Singapore and Korea Seoul. During the space race, our test node id "t0121681" ranked first in terms of effective computing power growth.

technology strength demonstration：
https://docs.qq.com/doc/DWFFmVHBrWmRjcnNa

Our contribution to IPFS & Filecoin does not stop here, we set up IPFS Eco Fund, among which we invested in New Web Group, which is not only a notary but also undertakes the development of TiTan. We also invested in SFIL, which is known as Filecoin Standard Full Hashrate Token, a token collateralized by real Filecoin algorithm, which allows more users to participate in Filecoin.

In addition, we drove FIL+ forward by understanding that https://crypts.cn/ (the largest NFT trading platform in China) had a need for real data storage and we promoted them to become an enterprise level user of FIL+.

Some media reports:
https://www.jinse.com/lives/179704.html
https://www.jinse.com/lives/201003.html
https://www.jinse.com/lives/183801.html
https://www.bihuoji.com/176439.html
https://www.coinvoice.cn/articles/5291
https://www.aicoin.com/article/144807.html
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
The total amount of FIL held by us and our customers exceeds 3 MM FILs, and some of our customers’ nodes (such as some of Binance’s nodes) are inconvenient to disclose. Therefore, the following a part of our nodes:

Total：1,702,185 FIL
Currently Available：2,0742 FIL
Initial Pledge: 144,3114 FIL
Locked Rewards: 238,959 FIL
The above data are from the blockchain browser: FILFOX. The miner ID used for statistics is the ID published on the official websites of FILSCAN.
Miner ID: f0772766, f066270, f0222674, f01777789, f01873760, f01909251, f01415710, f0513878 
Website:
FILFOX: https://filfox.info/en
FILSCAN: https://filscan.io/

The total disclosed is 1,702,815 FIL, the rest are not disclosed. 
List of disclosed SPs：https://docs.google.com/spreadsheets/d/1yuuo6LrtiOJUY4-K0GlhEKn0WauPsNXl_kT4jNDk8po/edit?usp=sharing
```

How did you acquire the FIL cited above?
```
We are Filecoin enthusiasts, and we are also Filecoin SP.  We have purchased a lot of FIL from the secondary market and are participating in Filecoin mining.

At the same time, we also provide technical services to many customers, serve many customers who want to participate in the Filecoin ecosystem, and help them become Filecoin SPs.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
In 2021, invest in to New Web Group (New Web Group is a notary and involved in TiTan development)
In 2020, invest in SFIL (SFIL is called Filecoin Standard Full Hashrate Token, is a token collateralized by real Filecoin algorithm, Every SFIL is Pegged to 0.01T Filecoin Full Hash Rate.)
April 2021: Established Filecoin mining machine financing lease cooperation with Binance, and promoted the onboarding of FIL mining products and FIL deposit products in Binance exchange.
December 2019: We established a strategic cooperation with Quanan government of Jiangxi and invested 600 million RMB to build a distributed storage server production plant.
August 2020: We invested 2 million in total as co-organizer to hold "2020 Shenzhen International Big Data & Storage Summit & Exhibition" and title sponsorship of Filecoin & IPFS dinner, which is a global summit held in Shenzhen's largest convention and exhibition center, directly affecting at least 20,000 people.

Since 2017 to 2022, we have hosted the mkccstorage IPFS Star Tour Conference several times in nearly 30 cities, including Shenzhen, Guangzhou, Hangzhou, Shanghai, Nanjing, Suzhou, Dalian, Beijing, Chengdu, Wuhan, Changsha, Xi'an, Nanning, Kunming, and Dali.

https://www.bihuoji.com/176439.html
Binance's strategic cooperation: 
https://docs.qq.com/pdf/DWExIVFhCSEd2dGpx
mkcctorage: NATIONAL TOUR SUMMIT: https://docs.qq.com/doc/DWFF5blpPc0tZUXNn
Events hosted by mkcctorage:
https://docs.qq.com/doc/DWHprTGlzYXhyWVZJ
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
While we are working, we found bugs and came up with solutions:

fix the lost sector tasks during scheduling 
https://github.com/filecoin-project/lotus/pull/9058

boost service order index build timeout or failure causes store deals display error
https://github.com/filecoin-project/boost/issues/920

scheduling optimization, add a limit on the number of concurrent pre worker tasks
https://github.com/filecoin-project/lotus/pull/8688
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
mkccstorage was founded in 2019 and has 110+ employees.

The company is headquartered in Shenzhen, China and has branches in Beijing, Jinan, Hefei, Hangzhou, Shanghai, Ganzhou, Shenzhen, Hong Kong, Chengdu and Vietnam and Korea Seoul.

As a Web3.0 infrastructure provider, the company has a number of businesses, including sales of high-performance storage equipment, stable and secure server room network systems, and data center construction and maintenance. The core members of our team come from famous universities such as Hong Kong Polytechnic University, Peking University, Stanford University, etc. We have 1 PhD and 5 masters who have worked for giants such as Tencent, Alibaba, Google, Vanke, etc. All of them are senior technical professionals in the industry and have written over 60,000 words of IPFS books.

We are a company that has received many recognitions and honors。

In 2019, we won the "Best Technology Application Innovation Award" issued by IPFS Summit.
In 2019, we were awarded "Top 10 Distributed Storage Enterprise" by China Blockchain Professional Committee.
In 2020, we were awarded the "Filecoin Mining Machine Quality Award Top 10" by Koala Finance.
In 2020, we were awarded the "IPFS Ecological Contribution Award" by Golden Finance.
In 2020, we won the "Gold Award of Blockchain Technology and Application Design Project" issued by Huobi University and China Industrial Communication Association Blockchain Special Committee.
In 2021, we will be awarded the "IPFS Brand Award" by World Chain Finance at the "World Blockchain Conference and Global Mining Summit" with over 30,000 people.
........
Awards received by mkcctorage.
https://docs.google.com/document/d/1LlZ9INaBJjbJTocc-FxQ3Y8aMbS1SBO6/edit

Book written by mkcctorage teams, over 60,000 words:
https://drive.google.com/file/d/10Ai0OMyBOl0ye9NIzWNmc60uJ0DJ4Q4y/view?usp=share_link
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Official website: https://maike.mkccstorage.com/
Bilibili:
https://space.bilibili.com/662264529?spm_id_from=333.337.search-card.all.click
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.jinse.com/lives/179704.html
https://www.jinse.com/lives/201003.html
https://www.jinse.com/lives/183801.html
https://www.bihuoji.com/176439.html
https://www.coinvoice.cn/articles/5291
https://www.aicoin.com/article/144807.html
https://docs.qq.com/doc/DWFF5blpPc0tZUXNn
https://docs.qq.com/doc/DWHprTGlzYXhyWVZJ
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
As the founder of mkccstorage, I paid attention to IPFS in 2017, started to set up IPFS & Filecoin team in 2018, founded mkccstorage in 2019, and led mkccstorage to cooperate with Quanan government of Ganzhou city, and became a strategic partner of Huobi, as well as successfully made Binance to onboard FIL products such as Filecoin pledge and deposit, and promoted Binance's support for Filecoin.

In 2020 I led the writing of an IPFS & Filecoin book, 132 pages and 60,416 words in total. Link to the electronic version of the book: https://drive.google.com/file/d/10Ai0OMyBOl0ye9NIzWNmc60uJ0DJ4Q4y/view?usp=share_link

On github, I proposed optimizations for  boost, etc., and they were adopted. In particular, the FIP I proposed not only raised bugs, but also provided solutions from the source code.

Github：https://github.com/han344906637
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
I have a master's degree from Hong Kong Polytechnic University, and I am the vice president unit of Shenzhen Nanshan District Blockchain Application Association, as well as the executive president of Huobi University Alumni Association.

My personal honors:
https://docs.google.com/document/d/1bmJhwkR-gIQhG4XEYBHnreJibAbYlRzv/edit

I have been interviewed by more than 40 media such as CCTV:
https://docs.qq.com/doc/DWEhqV1p6ZHlSaFpm
https://www.jinse.com/lives/183801.html
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We plan to support reasonable data requests for.

1.45%: Data that is meaningful to the Filecoin network,  web3 data is more meaningful to the Filecoin network, e.g. NFT data, DeFi data, gamefi data, Developer Tools、Filecoin's DAPP data, etc.
2、20%: Data meaningful to human society, for example, covid19 data, weather data, geological data, educational data, medical data, scientific data, etc.
3、20%: company level data, for example, web2 companies want to store data on Filecoin network, such as internet industry data, e-commerce data, clothing data, beauty data, restaurant data, etc.
4、10%: Storage of personal data, such as storing personal photos, exam papers, etc.
5、5%: Other legal and compliant data.

Firstly, corporate level applications are from  0-50T. Individual level applications are from 0-10T.

Secondly, we will divide the clients into 5 categories from L1-L5 according to their situation. The larger the amount of data requested by the customer, the stricter the requirements.

L1: 0--1GiB
L2: 1GiB--500GiB
L3: 500GiB--5TiB
L4: 5TiB--10TiB
L5: 10TiB--50TiB

We then check these customers by whether they are individuals or companies, their industry, data, diversity and decentralization, allocation strategy, tracking history, etc.

When assigning DataCap, we will consider the following factors.
1. whether the customer is an individual or a company
2. the customer's industry/data type
3. the amount of data the customer has
4. the onboarding information submitted by the customer
5. the customer's allocation plan
6. the client's relationship with the miner

we will also conduct offline surveys to find out who they really are, what they do, their reputation, etc., and how they use Filecoin for storage. We even plan to conduct a full review and assessment of client reputation every three months and reserve the right to adjust client quotas to ensure maximum and full allocation of shares.

Finally, we will set up a DataCap group to score customers, and give customers the corresponding DC according to the level of the customer. if the customer is rated as L1 level, we will communicate with the community. to decide whether to give the customer DC, the following is the scoring table: https://docs.qq.com/sheet/DWGRzb1NLb0RhdUJT?tab=BB08J2

```
<img width="490" alt="img" src="https://user-images.githubusercontent.com/16487322/201246191-709a4897-271e-4c42-aabc-237ce3c7c206.png">

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Yes, this is an important issue.
1, We plan to store the private key in a hard wallet.
2, We will create a DataCap group, every approval of a customer, or signing of an LDN, needs to be discussed in our DataCap group, and only after 90% of the people agree, can the signature be made.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We believe that all clients must go through a rigorous process to qualify, and the more DataCap applications there are, the more stringent the vetting of clients .

First, we collect information about the client:

For individual customers, KYC will verify through the following.
1.Name
2.Nationality
3. School
4. Nature of work and work address
5. ID card
6. Social media accounts (Facebook/LinkedIn/Twitter)
7. local office contact information
8. whether the type of data they store matches the content of their life and work (screening for malicious access to datacap), e.g. individuals in the photography industry may need to store a large number of photos rather than cartoons.

For enterprise level customers, their KYB will be verified through the following.
1. Business license, including date of establishment/address/industry/taxpayer identification number.
2. Website
3. Social media accounts
4. Company legal person information: ID number
5. Authorized signatory information: ID card and photo identification of the person himself
6. Evidence that the authorized signatory is authorized to act on behalf of the applicant entity
7. Emails issued with the company's domain email to confirm that it is the company's application
8. In the enterprise search and other channels to check whether the company is operating normally and whether there are litigation records to determine its industry reputation
9. Company business direction and turnover
10, the company's objectives, the company's main business


We ask our clients the following questions.
1. Are you an individual or a company/organization? If you are an individual, please indicate your name, date of birth and nationality; if you are a company/organization, please indicate the name of the company, the time of registration and the region of registration. Please also provide the appropriate supporting documents (ID card for individuals, license for companies/organizations, which can be sent via E-mail).
2. What is your social media/website link?
3. What is your industry? What data will be stored? What are the types of each.
4. Please share your data case and say how much backup you plan to make of your data?
5. Can you be sure that you are storing data that is publicly available and can be checked by everyone at random?
6. Have you received any accolades? Please provide relevant supporting documents or links.
7. Please provide your social media accounts and indicate the number of followers.
8. Please indicate the storage location, miner ID and storage ratio of the data you want to store.
9. Have you obtained DataCap before and do you have any relevant experience?
10. Can you send us an email with your domain email with your business license attached?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will categorize customers into L1-L5 levels according to their situation and give different DataCap according to the different levels. Granting DataCap is just the beginning, we will also continuously follow up on the use of DataCap and make sure it is used correctly:

1. We will give the amount requested by the client in batches and follow up with the allocation records of each batch to make sure that each round meets the requirements before proceeding to the next round of signatures
2. Ask customers to list the nodes they plan to work with for continuous follow-up
3.Check DataCap usage periodically through https://filplus.info/ and https://filplus.d.interplanetary.one/
4. Use incentives: encourage the community to report unfair allocations.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we will research our clients in several ways to make better decisions.

1. We will research the customer's application in detail, and the customer must provide enough information to complete the onboarding.
2、We will keep a record of every detail of all allocation decisions on Github, including time, amount, clients allocated, reasons for allocation, etc.
3、The content on GitHub is public. If there is a question, we will contact the client on GitHub to ask the question and contact the client by sending an email or slack so that the client can see the message in time.
4. If there is a question about a customer's request, we will discuss it at a notary meeting and hear from the community, as appropriate.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
First, all records, will be publicly available on GitHub so that the community can have permanent access.
Second, we will communicate via slack or telegram so that slack and telegram can do secondary backups.
Finally, our technical team is strong and innovative, and we are discussing whether to build an audit-friendly open source project so that it can be permanently traceable.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
I will have slack installed on my phone and computer, and I will keep up with FIL+ news daily，and actively reply to messages on slack
I will attend notary meetings as scheduled
I will conduct due diligence before signing the DC
We will focus on FIP, and comment on FIP
Therefore, I will spend a minimum of 30 hours per week on the FIL+ program
So we are at L4or L5
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None，but, we promoted the largest NFT trading platform in China (https://crypts.cn/) to become an enterprise user of FIL+. 
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/510
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
Although we have invested in New Web Group, we are completely independent.
```

**Comment by Kevin-FF-USA** [comment]
Hi @han344906637,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

    Your First and Last name
    Your Organization
    Your Country of Operation
    Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
    Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by han344906637** [comment]
The email has been sent, please check it, thank you

**Comment by han344906637** [comment]
![WechatIMG34](https://user-images.githubusercontent.com/16487322/203893811-1f5a2a68-f217-4410-bf69-b0b52821476e.png)

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[665.pdf](https://github.com/filecoin-project/notary-governance/files/10159372/665.pdf)

**Comment by han344906637** [comment]
Add on my newly obtained invention patent:Computer data information processing method based on blockchain network for your reference as well.
[发明专利证书-麦客.pdf](https://github.com/filecoin-project/notary-governance/files/10165898/-.pdf)

**Comment by han344906637** [comment]
I'd like to introduce myself to you again, I'm the founder of MkccStorage, I have a Master's degree from Hong Kong Polytechnic University, I'm excited about IPFS and Filecoin, I firmly believe that Filecoin will definitely become the infrastructure of web 3.0, as you can see on my GitHub, I've provided some fixes for Filecoin's bugs https://github.com/filecoin-project/lotus/pull/9058, https://github.com/filecoin-project/boost/issues/920; and as a Filecoin evangelist, I am actively involved in industry As an evangelist for Filecoin, I am actively involved in industry "talks" and "roundtable discussions" at conferences, and I actively share our technical achievements, for which I have received accolades, such as "2020 CEO of the Year ".
![image](https://user-images.githubusercontent.com/16487322/206610867-3f53d8a0-1930-4cd3-bcdd-bab8fdcbd799.png)

Finally, I would also like to show you some of the patent certificates that we have been awarded.
![image](https://user-images.githubusercontent.com/16487322/206610929-01a90008-46c4-4e1a-b3ae-030a9b02ecfa.png)
![image](https://user-images.githubusercontent.com/16487322/206610949-ffde9adb-5a97-4c6a-b0b2-5084d1829843.png)

**Comment by han344906637** [comment]
@galen-mcandrew @Kevin-FF-USA @Kevin-FF-USA
Hello，In order to imporve our scores, we update some information here, hope it can help us.

**Comment by Kevin-FF-USA** [comment]
@han344906637 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections _(pending a finalization of the recorded event history listed in Google Docs in application)_ 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by han344906637** [comment]
@Kevin-FF-USA  
We have filled in the form as required. Thank you for your review. If you have any questions, please contact me.

**Comment by han344906637** [comment]
@Kevin-FF-USA ；@galen-mcandrew 
Hello, this is our address: f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy .
The previous address f1hzdl5clst6ohd2mnkr2ldvrmcwiteaxyhhhp7ki is invalid, we are now sure to use this address: f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy .
thank you!

**Comment by Kevin-FF-USA** [comment]
Hi @han344906637 
You will need to update this Github issue to include your NEW address in the top section.  (the bot will pull addresses from that top line when populating in the Registry)  (Also this new address MUST HAVE BEEN SENT TO DISCLOSURE)

**Comment by han344906637** [comment]
@kevin ,
Thanks for your reminding. We have changed the address. The address on the top is the new one now, please check it.

**Comment by igoovo** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedgnbovskl5hkbifwmanqyupd7mcelvdbsws2spym2a65qb5yejsw
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedgnbovskl5hkbifwmanqyupd7mcelvdbsws2spym2a65qb5yejsw

**Comment by igoovo** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec2eywrma4lkexwqr2tvvwl6bsfgqdyvoryail6ktqpgh2rg66k5g
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2eywrma4lkexwqr2tvvwl6bsfgqdyvoryail6ktqpgh2rg66k5g

**Comment by igoovo** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebgzx33kc5zdb6qpepoyelu6ljkbpidsqgzaylilsum63hw457wpw
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgzx33kc5zdb6qpepoyelu6ljkbpidsqgzaylilsum63hw457wpw
