### ISSUE TITLE
Notary Application: CoinSummer Labs

### ISSUE THREAD

**Issue by maxvint** [filecoin-project/notary-governance#669]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Max
- Affiliated organization: CoinSummer Labs
- On-chain address to be notarized (recommend using a new address): f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
- Country of Operation:  Singapore
- Region of Operation: Asia minus GCR
- Use case(s) to be supported: [Please select from [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries)]  User Content (Personal Storage)，Public or Open Data (Scientific datasets, research data, government or historic), Professional Services (Hosting Reseller, Long-term Backups, Data Warehousing), Developer Tools (Package Managers, Automatic Notaries, Web2 to Web3 integrations), Decentralized applications
- DataCap requested for allocation (10TiB - 1PiB):  1PiB
- Are you applying on behalf of yourself or an organization?: [Individual, Organization] Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
CoinSummer provide cryptocurrency market insights and reliable data analysis, dedicated to creating a one-stop crypto market research platform.

Our products include: crypto market observation, ethereum analysis, blockchain data, crypto videos, bitcoin lightning network payment application, ctypto wallet.

We following the progress of IPFS and Filecoin from the beginning of 2018, and partitcipated on many offline and online activities.

In the early 2020, we joined Filecoin DevNet, TestNet, MainNet, partitcipated on Devgrants and Slingshot, made a huge contribution for Filecoin community. 

More information:
- Github handles: 
  - Filecoin Community China repo with 399 stars and 130 forks: https://github.com/filecoin-project/community-china
  - CoinSummer Labs: https://github.com/coinsummer
- Miner ID: f0152866, f0158335, f020489, f0465286, f01824405, f0818235
- Slack: @Max
- Contributions:
  - Take part in the mainet parameter setup.
  - Created and maintaining Filecoin Community China.
  - As one of Interplanetary Community Ambassadors.
  - Participated in Filecoin MinerX for early testing of FVM.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
No disclosing for now
```

How did you acquire the FIL cited above?
```
SR1/SR2, Block rewards, competition prize
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We created and maintaining Filecoin Chinese technology WeChat group with more than 5k miners and developers.

There are tens of thousands of messages every day including hardware configuration, mining tutorial, troubleshooting, development sharing, bug trace and so on.

We believe that these are the most active and useful technical community for Filecoin ecosystem.

We also organized and collected Filecoin Community China(https://github.com/filecoin-project/community-china) for Chinese community.

Including common resource links, lotus node operations, common storage miner operations, seal worker operations, deal operations, environment variables, debugging, benchmarks, frequently asked questions, etc.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
We actively participating on Filecoin slack channel and github issues.
Ask, Discuss and Suggestion issues:
- Issue: Add tag for each key in the api package: https://github.com/filecoin-project/lotus/issues/3820
- Issue: failed to register deal data for retrieval error: https://github.com/filecoin-project/lotus/issues/4587
- Multi-GPU supported for precommit phase 2 discussion: https://filecoinproject.slack.com/archives/CPFTWMY7N/p1594049806157900
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
CoinSummer is a HK-based technology company, founded on February 26, 2018. Right now, we have around 50 employees.  
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Official Website: https://coinsummer.io
Weibo: [币夏CoinSummer](https://weibo.com/coinsummer)
Github: [CoinSummer](https://github.com/CoinSummer)
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
- https://www.sohu.com/a/356903039_468071
- https://zhuanlan.zhihu.com/p/302627217
- https://ipfs.cn/live/info-221453.html
- https://news.huoxing24.com/20201023154220077580.html
- https://www.chainnode.com/post/499616
- https://www.jinse.com/news/blockchain/904620.html
- https://www.chainnews.com/articles/393790899102.htm
- https://www.jinse.com/news/blockchain/904890.html
- https://www.sohu.com/a/432421288_592464
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Github: https://github.com/yuwenhui
Twitter: https://twitter.com/0xmaxmillion
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
None
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We will focus on the system rules, improvement and process construction of DataCap allocation.

By carefully reading the roles/responsibilities as a notary, we worked out a plan to make sure the DataCap is granted fair, square and publicly.

When assigning DataCap, we plan to establish a credit and scoring mechanism to screen out the highest-scoring clients through investigation and discussion. 

The detailed scoring criteria is attached below, link: https://docs.google.com/spreadsheets/d/19FvtvUNHOViD885xdZ5QZO-zdlTAEtLlZWvy40meuqI/edit?usp=sharing

The credit score depends on the following factors:
- Provide completeness and transparency of registration information;
- Company registered capital, establishment time, number of employees, bisiness reputation, team/personal background;
- Storage cluster capacity, redundancy design and security strategy;
- Continuity and authenticity of stored data.

The data score will have a threshold, and clients below this threshold will be banned. The higher the score, the more DataCap quota can be allocated.

After the pre-review of the above conditions, we will screen out eligible storage clients, and continue to tracking, continue to optimize and adjust the process, the subsequent tracking and feedback mainly reference to the following elements:
- The degree of dispersion and fairness of DataCap allocation;
- Data storage success rate of each client;
- Transparency of distribution;
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We plan to use a hardware wallet like Ledger to manage the DataCap allocation wallet.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We need to investigate and understand clients detailed. Clients need to clarify how the DataCap will be allocated, build a fair mechanism.

Given the basic information provided in the application, we are going to collect detailed and reliable information of clients.

Before approval, we need collect information including:
1. Entity or individual Information
  - Organization name, business license, official website, the stakeholder list with control over 25% of the entity;
  - Government-issued identification number for the entity;
  For individuals, please provide:
  - ID card copy;
  - Job title in which company, or other certificates to prove the identity.

  The above mentioned info will be sent by official email where applicable.

2. Data details and use case
  Describe the data that will be saved in Filecoin system in details;
  - Data types with what format;
  - Data capacity in client hands for now;
  - Increase rate of data per week in future;
  - Data sourced from (business operations, research or others);
  - Whether or not the data is highly sensitive, any personal privacy involved;
  - Any violation against laws if the public has easy access to the data;

3. Information on how to interact with SPs
  - How many copies of these data will be saved to SPs;
  - SP lists that client have contacted;
  - The ways where to find SPs;
  - How to package these data and send them to SPs;
  - Areas that client want to save their data;
  - The proportion of the storage for each SP (no more than 25%);

After approval, keep an eye on datacap usage:
1. If the DataCap remains unallocated for a certain time, explain the reason why this happens?
2. Any help needed from the notary to find some SPs?
3. If a single SP stores over 25% of data, or the number of SP is lower than promised in application, ask them to make modifications as soon as possible and explain why?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
It is required to publish transaction information, including storage provider ID, allocation proportion and the source of storage providers, etc. , and will be reviewed per week.

We will check if or not >75% dataCap used up or not? and then check if or not the SP number is the same as planned, no single SP stores >25% of the deal, ask them to make adjustment if required; besides, we will pay attention to the  github/slack messages, detecting any risk for self-dealing; any misconduct about DataCap using is not allowed.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, I fully support the recording of the allocation decision, all processes will be published on Github repository.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Sure thing, we will take the public allocation on Github repo to make sure the principle of fairness, transparency and openness.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
Maintain a ranking in Leaderboard in the top 10% of Notaries.
Attend 2 Governance calls a month.
Join 2 working groups
Respond to SLACK inquiries within 2 days
Vote/Comment on >2 proposals a month
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None
```

**Comment by Kevin-FF-USA** [comment]
Hi @yuwenhui,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You must use/send the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by yuwenhui** [comment]
@Kevin-FF-USA  Hi, Kevin, the send address of my Organization means i can send from max@coinsummer.io?

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[669.pdf](https://github.com/filecoin-project/notary-governance/files/10159379/669.pdf)

**Comment by Kevin-FF-USA** [comment]
@yuwenhui 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by yuwenhui** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceabnpvrlsmqldu4uyckjc2clg33xza6bhj2d5oppxf43uxn2tpewc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabnpvrlsmqldu4uyckjc2clg33xza6bhj2d5oppxf43uxn2tpewc

**Comment by yuwenhui** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebjg3gigduuaccv4vi4so6jxrskgpfi7ozuws7nxtcrzbr4wo5442
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjg3gigduuaccv4vi4so6jxrskgpfi7ozuws7nxtcrzbr4wo5442

**Comment by maxvint** [comment]
@Kevin-FF-USA Hello, sir, i have changed my Github username from yuwenhui  to [maxvint](https://github.com/maxvint), and also requested to change the Github handles on the https://notaries.datacapstats.io/notary/f01991109 profile page, thanks a lot.

**Comment by Kevin-FF-USA** [comment]
Reopening Issue while we update the GITHUB manager for this Notary is processed
