### ISSUE TITLE
Notary Application: Fatman13 - Guazi Dynamic

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/notary-governance#670]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: @Fatman13
- Affiliated organization: Guazi Dynamic 
- On-chain address to be notarized (recommend using a new address): f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
- Country of Operation: China
- Region of Operation: Greater China Region (GCR), Asia minus GCR
- Use case(s) to be supported: Web 3.0 / Decentralized Applications, Web 2.0 Applications, User Content, Scientific Data, Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB): 300TiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Github handle: @fatman13 
Slack handle: @fatman13
Miner ID: f02731, f0694916, f01016254 (> 100k token at stake @ the time of this application)
Closely followed Filecoin project since 2017 and started full-time participation in 2020 since Space Race. Have been contributing to the network through mining, community discussions, governance and promotion of filecoin.

- Participation in testNet in April, 2020
- Participation in Space Race in August, 2020
- Participation in Slack community with more than ~10K messages
- One of the hosts for a monthly filecoin [meetup](https://youtube.com/playlist?list=PLvmxExuDQi1nxFrwZGtnuURKoCNbovCpw)
- Active contributor to filecoin-project on Github with PRs, issues, discussions etc

https://github.com/filecoin-project/venus-docs/pull/289，https://github.com/filecoin-project/venus-docs/pull/288，https://github.com/filecoin-project/venus-docs/pull/287，https://github.com/filecoin-project/venus-docs/pull/286，https://github.com/filecoin-project/venus-docs/pull/285
https://github.com/filecoin-project/venus-docs/pull/284，https://github.com/filecoin-project/venus-docs/pull/283，https://github.com/filecoin-project/venus-docs/pull/282，https://github.com/filecoin-project/venus-docs/pull/281，https://github.com/filecoin-project/venus-docs/pull/276
https://github.com/filecoin-project/venus-docs/pull/275，https://github.com/filecoin-project/venus-docs/pull/273，https://github.com/filecoin-project/venus-docs/pull/257，https://github.com/filecoin-project/venus-docs/pull/248，https://github.com/filecoin-project/venus-docs/pull/237
https://github.com/filecoin-project/venus-docs/pull/236，https://github.com/filecoin-project/venus-docs/pull/234，https://github.com/filecoin-project/venus-docs/pull/233，https://github.com/filecoin-project/venus-docs/pull/232，https://github.com/filecoin-project/venus-docs/pull/231
https://github.com/filecoin-project/venus-docs/pull/228，https://github.com/filecoin-project/venus-docs/pull/225，https://github.com/filecoin-project/venus-docs/pull/217，https://github.com/filecoin-project/venus-docs/pull/204，https://github.com/filecoin-project/venus-docs/pull/192
https://github.com/filecoin-project/venus-docs/pull/190，https://github.com/filecoin-project/venus-docs/pull/184，https://github.com/filecoin-project/venus-docs/pull/183，https://github.com/filecoin-project/venus-docs/pull/181，https://github.com/filecoin-project/venus-docs/pull/180
https://github.com/filecoin-project/venus-docs/pull/164，https://github.com/filecoin-project/venus-docs/pull/157，https://github.com/filecoin-project/venus-docs/pull/153，https://github.com/filecoin-project/venus-docs/pull/149，https://github.com/filecoin-project/venus-docs/pull/146
https://github.com/filecoin-project/venus-docs/pull/144，https://github.com/filecoin-project/venus-docs/pull/141，https://github.com/filecoin-project/venus-docs/pull/140，https://github.com/filecoin-project/venus-docs/pull/136，https://github.com/filecoin-project/venus-docs/pull/134
https://github.com/filecoin-project/venus-docs/pull/131，https://github.com/filecoin-project/venus-docs/pull/127，https://github.com/filecoin-project/venus-docs/pull/124，https://github.com/filecoin-project/venus-docs/pull/122，https://github.com/filecoin-project/venus-docs/pull/121
https://github.com/filecoin-project/venus-docs/pull/118，https://github.com/filecoin-project/venus-docs/pull/117，https://github.com/filecoin-project/venus-docs/pull/115，https://github.com/filecoin-project/venus-docs/pull/113，https://github.com/filecoin-project/venus-docs/pull/112
https://github.com/filecoin-project/venus-docs/pull/111，https://github.com/filecoin-project/venus-docs/pull/110，https://github.com/filecoin-project/venus-docs/pull/59

- Major contributor to [venus-docs](venus.filecoin.io)
- Major contributor to [Venus online meetups](https://www.youtube.com/watch?v=th8QJGFcNH8)
- Core member of Storage Provider Working Group; Maintainer of [SPWG-CN](https://github.com/stuberman/MWG/tree/main/mwg-aisa)
- Contributor to [FIP](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md)
- Volunteer of ProtoSchool

https://github.com/filecoin-project/venus/issues/4824，https://github.com/filecoin-project/venus/issues/4820，https://github.com/filecoin-project/venus/issues/4819，https://github.com/filecoin-project/venus/issues/4818
https://github.com/filecoin-project/venus/issues/4800
https://github.com/filecoin-project/venus/issues/4794，https://github.com/filecoin-project/venus/issues/4793
，https://github.com/filecoin-project/venus/issues/4792，https://github.com/filecoin-project/venus/issues/4790，https://github.com/filecoin-project/venus/issues/4775
https://github.com/filecoin-project/venus/issues/4774，https://github.com/filecoin-project/venus/issues/4760，https://github.com/filecoin-project/venus/issues/4759，https://github.com/filecoin-project/venus/issues/4758，https://github.com/filecoin-project/venus/issues/4757
https://github.com/filecoin-project/venus/issues/4752，https://github.com/filecoin-project/venus/issues/4745，https://github.com/filecoin-project/venus/issues/4744，https://github.com/filecoin-project/venus/issues/4743，https://github.com/filecoin-project/venus/issues/4742
https://github.com/filecoin-project/venus/issues/4741，https://github.com/filecoin-project/venus/issues/4728，https://github.com/filecoin-project/venus/issues/4727，https://github.com/filecoin-project/venus/issues/4726，https://github.com/filecoin-project/venus/issues/4725
https://github.com/filecoin-project/venus/issues/4724，https://github.com/filecoin-project/venus/issues/4723，https://github.com/filecoin-project/venus/issues/4722，https://github.com/filecoin-project/venus/issues/4721，https://github.com/filecoin-project/venus/issues/4720
https://github.com/filecoin-project/venus/issues/4719，https://github.com/filecoin-project/venus/issues/4718，https://github.com/filecoin-project/venus/issues/4701，https://github.com/filecoin-project/venus/issues/4700，https://github.com/filecoin-project/venus/issues/4699，https://github.com/filecoin-project/venus/issues/4698
https://github.com/filecoin-project/venus/issues/4684
https://github.com/filecoin-project/venus/issues/4683，https://github.com/filecoin-project/venus/issues/4682，https://github.com/filecoin-project/venus/issues/4681，https://github.com/filecoin-project/venus/issues/4680，https://github.com/filecoin-project/venus/issues/4652
https://github.com/filecoin-project/venus/issues/4651，https://github.com/filecoin-project/venus/issues/4650，https://github.com/filecoin-project/venus/issues/4649，https://github.com/filecoin-project/venus/issues/4648，https://github.com/filecoin-project/venus/issues/4647
https://github.com/filecoin-project/venus/issues/4646，https://github.com/filecoin-project/venus/issues/4645，https://github.com/filecoin-project/venus/issues/4644，https://github.com/filecoin-project/venus/issues/4643，https://github.com/filecoin-project/venus/issues/4642
https://github.com/filecoin-project/venus/issues/4618，https://github.com/filecoin-project/venus/issues/4617，https://github.com/filecoin-project/venus/issues/4616，https://github.com/filecoin-project/venus/issues/4615，https://github.com/filecoin-project/venus/issues/4614
https://github.com/filecoin-project/venus/issues/4613，https://github.com/filecoin-project/venus/issues/4612，https://github.com/filecoin-project/venus/issues/4611，https://github.com/filecoin-project/venus/issues/4610，https://github.com/filecoin-project/venus/issues/4609，https://github.com/filecoin-project/venus/issues/4607，https://github.com/filecoin-project/venus/issues/4606，https://github.com/filecoin-project/venus/issues/4347
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f02731, f0694916, f01016254 (> 100k token at stake @ the time of this application)
```

How did you acquire the FIL cited above?
```
Mainly through storage providing and offer storage providing services to our clients.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- Core contributor to [venus-docs](venus.filecoin.io)
- Core contributor to [Venus meetups](https://venushub.io/meetup/)
- Core member of Storage Provider Working Group; Maintainer of [SPWG-CN](https://github.com/stuberman/MWG/tree/main/mwg-aisa)
- Contributor to [FIP](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md)
- Volunteer of ProtoSchool
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
n/a
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Organization name: Guazi Dynamic
Size: ~10
Country: China
Founded: Sep 1st, 2020
We offer turnkey mining solution to clients in east Asia including China, Japan and  South Korea.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: guazi.io
Wehcat public account: 瓜子动力
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://mp.weixin.qq.com/s/sD6kTsuYZhilUdcwzcXGHg
https://www.tuoniaox.com/news/p-469057.html
http://www.btb8.com/fil/2010/97772.html
https://www.jiemian.com/article/5196371.html
https://www.jinse.com/news/blockchain/800936.html
https://page.om.qq.com/page/OiP1FgLD5z1rasQf9EWQwWcw0
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter: [fatman13](https://twitter.com/FATman13CC); ~2k followers
Weibo: [fatman13](https://weibo.com/u/1767457232); ~8k followers
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
We are open to new use cases if storage client could make its case.
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We draw inspiration (with regard to allocation strategy) heavily from https://github.com/filecoin-project/notary-governance/issues/413, https://github.com/filecoin-project/notary-governance/issues/414 and https://github.com/filecoin-project/notary-governance/issues/412.

We will be adopting the [Rubric](https://docs.google.com/spreadsheets/d/1zQ3FXJmmBMmynDIdRjYTYp-K95Dp95ypVoBfRhABPC0/edit?usp=sharing) defined by issue#413 with 7 varying degrees of trust.
The above rubric will be my primary guideline when evaluating a client and determining their dataCap target amount.
By adopting this rubric, I expect to add a level of consistency across the board.
I also plan on allocating dataCap with a small incremental amount(<10%) and build a reputation mechanism.
For new clients, they start small and gradually increase their allowance through good behavior under filecoin plus guidelines.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Will be using an off-line wallet whose private key is only known by me.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Again we draw inspiration (with regard to due diligence) heavily from https://github.com/filecoin-project/notary-governance/issues/413, https://github.com/filecoin-project/notary-governance/issues/414 and https://github.com/filecoin-project/notary-governance/issues/412.

We plan to have the vetting process functional yet not too cumbersome. 
We expect to engage with the client's request quickly, thus optimizing the overall experience.

The information needed for vetting a client will be as the following...

1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information; 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name;
 - date of birth; 
 - street address (P.O. box number is not acceptable); 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

Questions we will use to know client better are as the following...

1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.)
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
6. How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify.
7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Using filplus.info can easily reveal if a storage client is only sending deals with a single SP miner id. 
To make sure deals are not distributed within a single SP entity, I plan to sync with other notaries and cross check with them on a regular basis to eliminate the concerns.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Github repo only.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
I expect that all decision be tacked on Github and filplus.info publicly.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
5-10 hours per week.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
n/a
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None.
```

**Comment by Kevin-FF-USA** [comment]
Hi @Fatman13 
Thanks for (re)applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You must use/send the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Fatman13** [comment]
Hey @Kevin-FF-USA KE, sorry that I missed your comment. Have just sent the email. 

![image](https://user-images.githubusercontent.com/1591330/204700089-6ffbf918-9267-4606-bf43-7e1dde5f65ac.png)

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[670.pdf](https://github.com/filecoin-project/notary-governance/files/10159383/670.pdf)

**Comment by Kevin-FF-USA** [comment]
@Fatman13 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to continue as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by Fatman13** [comment]
https://airtable.com/shrjx52lvefitwdq6 Disclosure form done!

**Comment by Fatman13** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceayc6o6useh4gtcibhwn5timwqfn5cohd7fh7hhd73busvfknfmx4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayc6o6useh4gtcibhwn5timwqfn5cohd7fh7hhd73busvfknfmx4

**Comment by Fatman13** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceb2gjrtuw7h7lsvdirz57lpuprce3b4nnsvcmgt3fu5zpj5ta7kaa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2gjrtuw7h7lsvdirz57lpuprce3b4nnsvcmgt3fu5zpj5ta7kaa

**Comment by Fatman13** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedyz2epvsp4psetzw56ljdy4rkpmnhbu4cseymravz644kou6ki2i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyz2epvsp4psetzw56ljdy4rkpmnhbu4cseymravz644kou6ki2i
