### ISSUE TITLE
Notary Application: Rivtower Technology

### ISSUE THREAD

**Issue by abrahampalovickas** [filecoin-project/notary-governance#671]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Matt Wang
- Affiliated organization: Rivtower
- On-chain address to be notarized (recommend using a new address): f1stjz2inu3og7qm3jgwnshcx37tgjpydyluxgnea
- Country of Operation: Greater China Region (GCR)
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
We joined the Filecoin network in the first half of 2022 and have control over a certain number of nodes. Among them, the invested and owned nodes are listed below and will be increasing in the future.
f01916645
f01924258
f01924189
f01924048
f01923930
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f01916645=68k
f01924258=36k
f01924189=29k
f01924048=33k
f01923930=33k
Overall=200k
```

How did you acquire the FIL cited above?
```
Those nodes are mine.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
N/A
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Rivtower was founded in 2019 and is headquartered in Hangzhou, China. It has wholly-owned subsidiaries in Beijing, Shanghai and Suzhou. The company is mainly engaged in the research and development of blockchain basic technology and blockchain application tools, blockchain management platform, development projects covering the core aspects of the blockchain field, design and development of enterprise-level high-performance blockchain kernel CITA open-source projects, and the establishment of open source technology exchange community CITAHub to help the combination of technology and business. In 2020 World Internet Conference released China's first cloud-native blockchain framework CITA-Cloud, and in 2021 World Internet Conference released the RivSpace enterprise-grade blockchain management platform and RivTrust data asset management platform. Rivtower focuses on the research and development of basic blockchain technology and has applied for more than 200 invention patents in the fields of consensus algorithms, smart contracts, and privacy protection.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Official [Web: https://www.rivtower.com/index](https://www.rivtower.com/index)
Tech Blog: https://tech.citahub.com/categories/   Follower: 93k
CITA Community: https://talk.citahub.com   Members: >100k
CITA Hub: https://docs.citahub.com/en-US/welcome
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://36kr.com/p/1921590111870726
https://www.prnasia.com/story/300855-1.shtml
https://www.sohu.com/a/567702162_439726
https://www.toutiao.com/article/7091950035583713829/?wid=1666946175756
https://caifuhao.eastmoney.com/news/20211116112611607811450
https://www.defidaonews.com/writer/629168   Pageviews：430k
https://my.oschina.net/u/4582573/blog/5565682
https://my.oschina.net/u/4582573/blog/5554397
https://www.grosir-onlinee.com/article/1017148.html
https://rustmagazine.github.io/rust_magazine_2021/chapter_1/cita_protobuf-ext.html
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
SIna Weibo : [@溪塔科技](https://weibo.com/u/7243995427)  Follower ： 10K
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
N/A
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
To prevent clients from malicious or abusing dataCap, we will conduct due diligence and ask clients to fill out our application form. At the same time, we also hope to encourage more clients to participate in the network. The datacap requested directly from the notary will not exceed 100T. Clients must want to understand how the Filecoin network works. Therefore, we will gradually allocate datacap to clients under the standard.

1. Due Diligence and KYC.
*Real identity of the applicant, official website of the company, data type and volume
*Checking the company's registration information on the relevant government website to ensure that the information submitted is true and legal
* Confirm whether the company is applying for Datacap by email, and confirm the applicant's identity and employment information.
2.Allocation track
* DataCap assignments will be approved on the following basis.
Attach the link to the form： https://docs.google.com/spreadsheets/d/1PbFEuJdp9NCpitNNe_xiRSfEqiaqRpJw/edit?usp=sharing&ouid=109625342377150582787&rtpof=true&sd=true
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We have an internal vetting process, and after vetting, Datacap allocations are made to applicants by colleagues with ledger execution rights.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
To ensure the fairness and integrity of Datacap distribution and the authenticity of that client's information, we have developed different review processes for individuals and businesses.
For individual client:
*We will review their Github registration time (at least 30 days) Approval volume will also be limited no more than 20 TiB.
*Sample data submission (at least 10) we will verify if their data is valid and publicly available.

For business client:
*Provide business license, incorporation documents, public registration information, relevant certificates.
*Government issued ID or passport number
*Review third-party public data provided by the applicant, such as social media accounts, the official website. We will observe the activity of the account, and the activity of Github usage period.
*Review the company's history, news, ecology and products, etc.
*Confirm whether the company is apply Datacap by email, and confirm the applicant's identity information, and incumbency information.
*Sample data submission (at least 10). e will check if their data is valid and publicly available.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Clients are required to distribute Datacap to at least 5 or more SPs, which increases storage redundancy and helps keep it decentralized and reduces the potential for abuse.
Second, all information is available at https://filplus.d.interplanetary.one/clients
We monitor and log all Datacap usage on a regular monthly basis.
We will notify and log unusual usage of clients.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Both.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
All decision be tacked on Github.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L5
· Maintain a ranking in Leaderboard in the top 5% of Notaries.
· Attend 2 Governance calls a month - with webcam turned on
· Join 2 working groups
· Respond to SLACK inquiries within 24 hours
· Vote/Comment on all proposals submitted
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No.
```

**Comment by Kevin-FF-USA** [comment]
Hi @abrahampalovickas,

Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You must use/send the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[671.pdf](https://github.com/filecoin-project/notary-governance/files/10159387/671.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi @abrahampalovickas,

Sending a friendly follow up, I never received a verification of your email address.  If you havent sent it, please do so by 06DEC. If you did send it already, will you please resend or post a screenshot in this thread?

**Comment by Kevin-FF-USA** [comment]
@abrahampalovickas 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
