### ISSUE TITLE
Notary Application: NewToken

### ISSUE THREAD

**Issue by jomozz** [filecoin-project/notary-governance#674]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: NewToken
- Affiliated organization:  Hangzhou Niutong Information Technology Co., Ltd.
- On-chain address to be notarized (recommend using a new address): f1at2u5yout2jvydogkftoveqmp5uo6cglvxgkdfa
- Country of Operation: China
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Founded in 2019, NewToken focuses on the research and development of new technologies in the blockchain industry.
One of our investors has been following the filecoin project since 2019 and participated in the space race in 2020.
We participated in the filecoin slingshot 2.8 phase.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f01193812(115,000 Fil) 18.96PiB
f01644444(55,000 Fil) 9PiB
f079719(92,000 Fil) 0PiB
f01395673(4355 FIL) 471.59TiB

Total：266,355 FIL
Power: 28.4PiB

In addition, the number of FIL held by our investors has exceeded 500k.
```

How did you acquire the FIL cited above?
```
These are our own nodes, the FIL mainly from investors.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Participated in slingshot 2.8
Help with testing data onboarding tool Singularity
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Organization: Hangzhou Niutong Information Technology Co., Ltd.
Country: Hangzhou China
Size: over 20 employees
Since： 2019
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Wechat: 牛通信息
Twitter: https://twitter.com/NewToken20
Website: http://www.ntkblock.com/
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://mp.weixin.qq.com/s/mfZ9ngd-mM-NKCvFTfN8Tw
NewToken focuses on the research and development of new technologies in the blockchain industry, providing customers with technology development services including smart contracts, distributed storage, NFT, and Defi etc.
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
slack: @jomozz
github: https://github.com/jomozz

```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
None
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
First, we will conduct due diligence on the clients to ensure that their information and data are true and compliant.

Second, we will score the client's credit through the following aspects: Size of Company,Establishment Time,Number Of SPs,Data Type,Distribution Region.

Third, we divide clients into 5 levels by scoring: L1 - L5:

L1: 0-5TiB
L2: 5-10TiB
L3: 10-20TiB
L4: 20-50TiB
L5: 50-100TiB

link: https://docs.google.com/spreadsheets/d/1UaKivN5ePQs8gQeUmzqhu6gmTxaoLvIpsy3vpSH9hFs/edit?usp=sharing

Finally, we will continue to follow up on the usage of client datacap to ensure that data is stored as agreed.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We plan to use a hardware wallet to manage the DataCap allocation wallet.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will conduct strict KYC audits for clients who apply for datacap, including:
1. Confirm the authenticity of the client's organization information and whether the organization's nature meets the data requirements through government's official enterprise inquiry platform and recruitment website
2. Ask clients to provide verifiable information, such as business licenses, authorization documents, etc.
3. Ask clients to provide a certain amount of data samples to ensure that the data is publicly available and that the organization is the actual owner of the data
4. If necessary, we will further confirm the detailed distribution plan and results of Datacap through online video calls.
5. After that, our team will score clients through the following dimensions: completeness of client information, data volume, data storage value, and Datacap distribution plan integrity.
6. After Datacpa has passed the review, we will conduct retrieval from time to time to ensure the authenticity of the stored data and whether the storage provider has opened the retrieval function


Organization questions:
1. Are you an individual or an organization
2. For individuals, please provide ID card copy, job title in which company, and social media links to prove the identity.
3. For organization, please provide organization name both in Chinese and English, business license, official websit.
4. Individual/organization introduction


Data related questions:
1. What's the type and format of your data.Can you describe your data in details?
2. The increase rate of data per week in future.
3. Can you make sure your data is publicly storable？
4. How many copies you want to store.
5. Can you provide enough sample data for us to review?



Datacap related questions:
1. How many SPs as planned?
2. Do you know the ways to find SPs? What kinds of SPs will you choose?
3. If you have contacted SPs, please list them?
4. What kind of method did you mainly use to deliver data? online, offline, and other methods
5. Will you search the data stored after dealing with SP?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. The client is required to disclose all previous transaction information, and we will confirm the authenticity and validity of the data through retrieval.
2. We will check the previous datacap usage, whether it is used in accordance with community requirements and distribution rules, and whether there is a single sp occupying too much datacap
3. We will check the community feedback to see if anyone has complained about the client
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, all our allocation decisions will be made public on github
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
1. All allocation decisions can be found on github
2. We will also save this data on Google doc and make it accessible
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
Maintain a ranking in Leaderboard in the top 10% of Notaries.
Attend 2 Governance calls a month.
Join 2 working groups
Respond to SLACK inquiries within 2 days
Vote/Comment on >2 proposals a month
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None
```

**Comment by Kevin-FF-USA** [comment]
Hi @jomozz,

Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You must use/send the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by jomozz** [comment]
@Kevin-FF-USA  Sorry for the late sending, our company did not reply in time due to COVID-19.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[674.pdf](https://github.com/filecoin-project/notary-governance/files/10159392/674.pdf)

**Comment by jomozz** [comment]
Hi @Kevin-FF-USA @galen-mcandrew we have received the new ledger wallet, and want to change the on-chain address, please help, the new address is : f1qpdwt2f2fse74nl5wi27uk5jcyqqqyil47yqt7i

**Comment by jomozz** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceda3mxd7gstobyv6v2olerkqxkqzrqgz24qtnptzutrkxrodevhgg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceda3mxd7gstobyv6v2olerkqxkqzrqgz24qtnptzutrkxrodevhgg
