### ISSUE TITLE
Notary Application: TopBlocks

### ISSUE THREAD

**Issue by woshidama323** [filecoin-project/notary-governance#675]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [[here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview)](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information

- Name: Harry Ma
- Affiliated organization:  TopBlocks
- On-chain address to be notarized (recommend using a new address): f1t2s67uli6pzgei5drbonmko2ej2333jw64wyzty
- Country of Operation: Global
- Region of Operation: North America
- Use case(s) to be supported: Professional Services, Developer Tools, Decentralized Applications ,Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment

Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).

```
TopBlocks was founded in 2020 which invested by TOP Network. 
TOP Network is the world's leading blockchain platform and it has followed IPFS and decentralized storage technology since 2018. The developed platform of TOP Network will be deeply integrated with the Filecoin ecosystem. Till now, we have developed two cryptocurrency wallets supporting Filecoin chain, one is the plug-in wallet Topia, the other is HiWallet. 
TopBlocks participated in the Filecoin Space Race in 2020 and won third place in North America.
Filet Finance, which was developed by the TOP Network team, has helped storage providers increase more than 60PiB mining power. 
Our four miners, f02301 f0240185 f0143858 f03223, have sealed about 70PiB of mining power now, and most of which are DataCap. 


```

### Stake Exposure

Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).

```
We have more than 500K FIL that most are pledged as collateral or locked in miners above.
```

How did you acquire the FIL cited above?

```
We got these FIL tokens from the rewards of Space Race & Slingshot, the purchase from market, the mining rewards, and the staked token from Filet. 
```

### In-protocol Reputation

Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

```
We are deeply involved in multiple projects in the Filecoin community (slack name: HarryM_Filet, Jenny_Filet)
1. FIL+E: https://filecoinproject.slack.com/archives/C03MHVAABFV
2. FEVM earlier builder: https://filecoinproject.slack.com/archives/C0454HR5B6H
3. Saturn-sunrise:https://filecoinproject.slack.com/archives/C044QRWQPUY
4. We’ve completed the Slingshot Restore with community members @Feiyan @Cabrina Huang
5. We assisted @Hidde Hoogland to complete multiple network testing: https://filecoinproject.slack.com/archives/C02GQUMFQVA/p1654692719180769
6. Between 2020-2021, we actively participated in offline activities and organize activities to introduce Filecoin to users in China, the United States and Southeast Asian countries. We also participated in exhibitions in Beijing, Shenzhen, Chengdu and Hangzhou to introduce Filecoin, and held 2 events in Hangzhou as the organizer. Under the influence of policies in Greater China, we provide corresponding help for SPs who need to relocate to North America.
https://www.8btc.com/article/6658961
https://www.jinse.com/news/blockchain/1155004.htmlhttps://zhuanlan.zhihu.com/p/389633370
7. We delivered a keynote at FIL Austin in June 2022. 
https://www.youtube.com/watch?v=3sO-0FRLf8U
8. Filecoin Orbit member, engage with Filecoin and Filecoin foundation on social media, and provide content to crypto users about Filecoin. 
robert@fil.org
yuliia.deriuhina@protocol.ai
9.	John the Filecoin hackathon in July 2022 and win the third prize and the most innovative prize. 
https://topnetwork.medium.com/tops-partner-topblocks-participated-in-the-filecoin-hackathon-and-achieved-great-results-d7341e3f2735
```

### In-protocol Security

Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 

```
1.	Help with error correction rust-fil-proofs project code. 
https://github.com/filecoin-project/rust-fil-proofs/pull/1566
2.	Raise potential bug issues to the lotus team. 
https://github.com/filecoin-project/lotus/issues/9104
```

### Organizational Reputation

Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

```
TopBlocks was established and registered in California, USA in 2020. It is invested by TOP Network. Registered in California, USA.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

```
Website: https://www.topblocks.io/
Facebook: https://www.facebook.com/TopBlocks2020
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

```
About TOP Network
https://www.linkedin.com/company/topnetwork
Publication:
https://topnetwork.medium.com/first-round-of-filecoin-space-race-ends-top-blocks-mining-efficiency-ranked-first-in-the-1835e7283280
TOP Network CEO Steve Wei can confirm about this.
https://www.linkedin.com/in/stevenwee/
```

### Individual Reputation

Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.

```
Twitter: 
https://twitter.com/Filet_finance         Follower: 1,000+
https://twitter.com/topnetwork_top       Follower: 11.8K
Facebook:
https://www.facebook.com/filet.finance/   Follower:152
https://www.facebook.com/topnetworktop/  Follower: 12K
Telegram:
https://t.me/filet_finance  Followers: 800+
https://t.me/topnetwork_top  Followers: 4K+
IG:
https://www.instagram.com/filetfilecoinstaking/
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)

```
https://www.8btc.com/article/6658961
https://www.jinse.com/news/blockchain/1155004.htmlhttps://zhuanlan.zhihu.com/p/389633370
```

# Allocation Plan [[refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)

### Allocation Strategy

How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.

```
1. Ensure the authenticity and validity of the applicant and prevent deception
    Newly applied clients need to provide the necessary information to review:
A.	Basic information of the client entity name, data type, business scope, etc. If there is a referrer, ask the referrer for the client's history information. 
B.	The geographical location of the server used to propose deal. We will require a specific domain name or IP address for later tracking and must also meet the proposing rules of FIL+. 
C.	Sack name. It is required a valid slack name, used to collect information, or further contact. 
D.	Has there been any projects involved in the community in the past? If yes, how did the projects involved perform, whether there is a negative history. It is necessary to communicate with the person in charge of the projects involved, and get necessary information, etc.
We will give a comprehensive score according to multiple latitudes, please refer to the attachment for specific information 
https://docs.google.com/spreadsheets/d/12ItWjuddDPZpFBE84dzNJxBM24AhZHDJcWsu9RY3xG4/edit?usp=sharing
)

2.	Ensure the client follows the rules after getting the DC
After the review is passed, the DCs are allocated in a step-by-step manner. 
After the entire DC is allocated, it will continue to track whether the entire packaging process meets the deal rules. If any doubts are found, the distribution will be paused, and the review process will be restarted. 
The monitoring process will rely on https: //filplus.info/ github slack channel / Comprehensive monitoring of information on the chain
The entire review rules will also be updated and iterated according to the actual situation, the progress of the project, and new features. 

Given that a lot of non-distribution according to the rules occurred during the Slingshot v2, we will increase the requirements for applicants with a negative history. 
In short, our idea is to ensure that the client is real and effective and strictly follow the rules of the FIL+. Our team will have a member responsible for managing the entire process, responsible for organizing the allocation of resources, and strictly control to ensure that the project is running as required

Notes: Due to the different allocation requirements of multiple projects in the community, we will keep up with it. Meanwhile, the changes of FIL+E, Slingshot V3 and other projects will be continuously updated, and the allocation rules will be adjusted if necessary.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
By using Ledger Nano X wallet and  multisig-wallet.
```

### Client Due Diligence

How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 

```
1.We will conduct due diligence on all clients applying and review the usage of DataCap upon approval.
For corporate entities or organizations, we will verify their entity information, including business licenses, official websites, media accounts, beneficiaries, business types, data sources, usage plans, etc.
For customers who have been allocated DataCaps, we will continue to review them to determine whether customers are using DataCaps as promised. If it does not pass the review, we will add it to the blacklist and make it public. 
We mainly review customers from the following aspects:
A. We require clients assigned to DataCap data to provide transaction CID and miner ID.
B. For public data, we will conduct random checks.
C. For customers assigned to DataCap, we will verify whether it is distributed to storage providers in at least three different cities or regions to improve the security of data storage.
D. If the above data fails to pass the review, the score of the applicant will be lowered and the next quota will be affected. In serious cases, it will be directly entered into the blacklist and publicized.

2.For new clients, we will ask them the following questions to know about the client and to be clear about the client's handling of DataCap.
A. Please introduce yourself, including but not limited to business model, business scale, etc.
B. Your website or social medias, such as Twitter and Linkedin.
C. The name, nature, country of registration, time of establishment, business license, number of employees, number of customers/users, etc. of your organization.
D. What do you want from Filecoin? Any suggestions or expectations for the Filecoin network?
E. Please describe your data volume, source, and later planning, and whether it can be made public.
F. Whether your DataCap has requirements for the storage area, whether you have an intentional storage service provider, and how many storage service providers you plan to allocate to. If you are interested in a storage service provider, please list the miner's ID and the storage ratio of each miner. 
G. Do you agree to disclose trading information? If agreed, where can we check these information. 

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.

```
As metioned above
A. We require clients assigned to DataCap data to provide transaction CID and miner ID.
B. For public data, we will conduct random checks.
C. For customers assigned to DataCap, we will verify whether it is distributed to storage providers in at least three different cities or regions to improve the security of data storage.
D. If the above data fails to pass the review, the score of the applicant will be lowered and the next quota will be affected. In serious cases, it will be directly entered into the blacklist and publicized.
etc
```

### Bookkeeping Plan

Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 

```
Yes,Both 
We will publish our allocation decisions on Github. To ensure fair, accurate and transparent allocation, we will do it from the following aspects:
1. Set up a notary team
We will set up a notary team, responsible for reviewing information, assigning DataCap, and tracking after distribution. All these information will make to public on Github.
2. Open and fair
All our decisions will be discussed within the notary team to ensure that each decision is compliant and fair.
and also will send to filecoin community for more feedback,  
All our distribution records will be made public in accordance with community norms.
3.	Dispute resolution
If there is a dispute over the allocation decision, we will review it within the team ASAP to confirm the result and publicize it on Github.
If the client is not satisfied with the settlement result of the dispute, he/she may submit a dispute resolution application to the notary management agency within 14 natural days. The notary agency may appoint another notary for arbitration to resolve the dispute. Based on arbitrator's decision, a hearing may be held within 30 calendar days of the dispute resolution application.

Will ternimate the allocation if no correct action is done or still not  satisfied with the settlement result of the dispute

We will update the allocation of DataCap and also current feedback on a weekly basis, and the update link is [here](https://docs.google.com/spreadsheets/d/1Hxr0BMhpdtou92PRWnfIdU_Qe0vD2rSXwPyoqRszbtI/edit#gid=0)

```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?

```
All decisions will be made public on public Github and  public google sheet
more details will be show bellow

```
![allocation](https://user-images.githubusercontent.com/11014169/206917542-ef4131fb-80af-459c-ac57-285dbaff9b29.png)

### Engagement in Program

Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [[rubric](https://github.com/filecoin-project/notary-governance/issues/630)](https://github.com/filecoin-project/notary-governance/issues/630) 

```
L4

Here is our plan:
1.	We will set up a special group of notaries, consisting of 6 members.
2.	We plan to participate in 2 governance calls per month.
3.	We have currently joined more than 2 working groups, namely Filecoin Orbit Spaceship member, FIL+E, FEVM earlier builder, Saturn-sunrise, and so on. 
4.	We respond to related questions on Slack within 2 days or even less. 
5.	We plan to vote/comment on more than 2 proposals per month, or we will raise the proposal for the community if applicable. 
In addition to the above matters, we hope to truly promote the entire ecology of Filecoin Network and deepen the ecological application.

```

### Past allocation 

Have you previously received DataCap to allocate before? If so, please link to any previous applications.

```
None, First time to apply
```

## Disclosures

Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.

```
None
```

**Comment by Kevin-FF-USA** [comment]
Hi @woshidama323,

Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You must use/send the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[675.pdf](https://github.com/filecoin-project/notary-governance/files/10159393/675.pdf)

**Comment by woshidama323** [comment]
Hi , @Kevin-FF-USA @galen-mcandrew we've done some improvements on the Bookkeeping Plan part 
But it seems that the new update triggered filecoin-notaries-onboarding-bot action ?
Is that a problem ?

**Comment by woshidama323** [comment]
Actually we update this part 
### Bookkeeping Plan

Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 

```
Yes,Both 
We will publish our allocation decisions on Github. To ensure fair, accurate and transparent allocation, we will do it from the following aspects:
1. Set up a notary team
We will set up a notary team, responsible for reviewing information, assigning DataCap, and tracking after distribution. All these information will make to public on Github.
2. Open and fair
All our decisions will be discussed within the notary team to ensure that each decision is compliant and fair.
and also will send to filecoin community for more feedback,  
All our distribution records will be made public in accordance with community norms.
3.	Dispute resolution
If there is a dispute over the allocation decision, we will review it within the team ASAP to confirm the result and publicize it on Github.
If the client is not satisfied with the settlement result of the dispute, he/she may submit a dispute resolution application to the notary management agency within 14 natural days. The notary agency may appoint another notary for arbitration to resolve the dispute. Based on arbitrator's decision, a hearing may be held within 30 calendar days of the dispute resolution application.

Will ternimate the allocation if no correct action is done or still not  satisfied with the settlement result of the dispute

We will update the allocation of DataCap and also current feedback on a weekly basis, and the update link is [here](https://docs.google.com/spreadsheets/d/1Hxr0BMhpdtou92PRWnfIdU_Qe0vD2rSXwPyoqRszbtI/edit#gid=0)

```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?

```
All decisions will be made public on public Github and  public google sheet
more details will be show bellow

```
![allocation](https://user-images.githubusercontent.com/11014169/206917542-ef4131fb-80af-459c-ac57-285dbaff9b29.png)

**Comment by woshidama323** [comment]
Hi @Kevin-FF-USA 
We've  updated  a new address from a new ledger nano s 

and We've also updated the Disclosures Form with https://airtable.com/shrjx52lvefitwdq6

please check

**Comment by panges2** [comment]
Hi @woshidama323, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by woshidama323** [comment]
Hi @panges2  Thanks for your reminder
There is no any item listed in verify client part when browse in plus.fil.org
And cannot to verify operating, Could you help to have a check ?

**Comment by woshidama323** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedkaxwj4sduk6sq2oi7dc4dc745t3yxfjhmlv7rwbdceusin6pxug
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkaxwj4sduk6sq2oi7dc4dc745t3yxfjhmlv7rwbdceusin6pxug

**Comment by woshidama323** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedyv5swpvcwhr2j64n24rmyo56poxl2rwqhxyvq6vzxbwbjzsizy2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyv5swpvcwhr2j64n24rmyo56poxl2rwqhxyvq6vzxbwbjzsizy2

**Comment by woshidama323** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedq3ap6jhflybtylqoigynhrit336rmtjnvndlj62qrvbuizi7or2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedq3ap6jhflybtylqoigynhrit336rmtjnvndlj62qrvbuizi7or2
