### ISSUE TITLE
Notary Application: Carohere/Carolina

### ISSUE THREAD

**Issue by Carohere** [filecoin-project/notary-governance#676]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Carohere/Carolina
- Affiliated organization: None
- On-chain address to be notarized (recommend using a new address): f1pynuve3pi2fwvhlkco6dl3ipspkgzmb25syv5ca
- Country of Operation: (Residence) Austria, Slovenia, and Spain 
- Region of Operation: (Residence) Europe
- Use case(s) to be supported: [Please select from [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries)] Decentralized Applications, User Content (Personal Storage), Public or Open Data (Scientific datasets, research data, government or historic, Media & Entertainment (Videos, photos, NFTs)
- DataCap requested for allocation (10TiB - 1PiB): 10TiB
- Are you applying on behalf of yourself or an organization?: Individual

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
-In 2019, I stumbled upon the news that Facebook would launch Libra and got to know cryptocurrency. Since then I have invested in ETH, Terra (Luna), BTC, etc. 
-The first time I learned about filecoin was in 2021 when I saw a video posted by [Coin Burea](https://www.youtube.com/watch?v=R0aAmh3PMMA) on youtube.
-The price of Luna plummeted in May of this year and I saw many of my peers around suffer financially. This made me realize the importance of investing choices. 

-AND WHY FILECOIN? 
The reason why I chose filecoin was that the concept of DataDAO caught my eye. Unlike the usual cloud-based storage, decentralized distributed storage looks very impressive and interesting. The most important thing is that storage-based cryptocurrencies are extremely different from the usual unpredictable trending ones.
After joining slack I found that anyone's opinion has been heard and appreciated in the whole community, making me feel more in line with the spirit of web3. This is one of the main reasons I've always been keen to explore more here.

Github/Slack Handle: Carohere/Carolina 
Storage Provider IDs: N/A
Contributions: two proposals and several reviews shared under applications, please refer to https://github.com/search?q=carohere&type=issues.

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Around 2830 available FIL. 

```

How did you acquire the FIL cited above?
```
Purchased on Binance.

```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
-I joined the Filecoin community in May this year, and spent about three months studying the whitepaper and the issues discussed on slack in my spare time. 
-In August, I submitted https://github.com/filecoin-project/notary-governance/issues/602 and in early September, I submitted https://github.com/filecoin-project/notary- Governance/issues/608, both of which I think would be good for community transparency, application credibility and prevent DC abuse. I agree with the governance team that the proposals are theoretically correct, but will be difficult to implement in practice. BTW Both proposals are still open, although they are not approved so far, I am still happy to mention a few points that I think may cause confusion and can better reach consensus.
-I am active in several channels of slack, providing some help to beginners who are new to the Filecoin as I was.
-I am multilingual, and with LDN involving companies from many countries, I can better use my language skills to validate data samples & websites, etc. to provide more perspective to the community.
-I have translated for client, goverance team and notaries in governance call.

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A

```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
I joined Filecoin to get a better view of FIL trends so I can make proper investments and I have been an active community member out of personal interest since May. 
At the moment, as a graduate school student, I don't see the need to start a company. However, I would consider registering as an independent contractor if necessary or if I have extra income from Filecoin such as notary incentives in the future.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
N/A

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
N/A

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
-I had raised my concerns about some of the LDN applications, and one person DMed me on slack with some rather excessive and slightly offensive words. I do not feel comfortable revealing my personal account. 
-I have joined a lot of governance call and shared my opinions before. I'll still attend GC at least once per month and I hope these could be considered as sufficient proof of my identity. 

```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
N/A

```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
I will ask questions from three perspectives: Applicant, Data & Storage, and Allocation.

a. applicant related
-for individuals
How did you hear about the FIL+ project? 
Have you been or are you currently involved in the web 3.0 community? Please share the link to your account or any presence if you do. 
-for organizations
Please provide a description of your organization, the industry, the country of registration, size of the organization, and the position you held. 
Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

b. data and storage related
1. What kind of data do you plan to store? Can you share any kind of sample data?
2. What is the size of the data you expect to store?
3. How long do you plan to store your data with Filecoin?
4. How often do you plan to retrieve data stored on Filecoin, e.g., monthly, a few times a year, or infrequently?

c. allocation related
1. Have you previously received DataCap and have you finished with the whole usage? If so, please share the link to your previous request/ github issue. 
2. Have you applied for DataCap from another notary, and has it been accepted or rejected? If yes, please share the link to the previous application
3.Do you agree to publicly provide transparency of DataCap allocation decisions and execution details to prevent excessive/unfair (20% of DataCap allocation) self-dealing?

Since I'm only applying for 10TB, I don't think I'll be processing a lot of applications. Two or even one application would take up all my quota.

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
-I'm the only one with access to my account. 
-I just got a ledger and it will be only used by me.

```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
filecoin-plus-client-onboarding via https://github.com/filecoin-project/filecoin-plus-client-onboarding N/A

filecoin-plus-large-datasets via https://github.com/filecoin-project/filecoin-plus-large-datasets
I will go through all the information in the application and focus mainly on 1) the company qualifications and its website 2) the samples and the data description.

For 1)
I will verify the company's credentials through the official inquiry system of each country. For instance, I will use the following official websites that cover the maximum information for applications from Chinese, Spanish and Korean companies, 
https://www.qcc.com/ https://www.tianyancha.com/
https://www.incibe.es/
https://www.kreport.co.kr/

For 2)
-I hope that the applicant could preferably adhere to the sample amounts suggested by trust& transparency lead RG. 
-I will verify that the Datacap amount requested is consistent with what is outlined in the sample description.
-I will give more feedback based on reviews from the governance team and other community members.

In addition, in order to avoid the recurrence of disappearing applications due to account flags, I will keep track of every LDN application I propose or approve and will share the application information with community members for review if any issues arise.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
-For clients who have been involved in suspicious and non-compliance behavior with Filecoin rules in the past, I think more stringent due diligence is needed. For example, an application that has been flagged by multiple people, or has drawn significant community attention can be put on hold until it is clarified. 
-The detailed process needs to be decided on a case-by-case basis for each application.

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
-I am applying for the minimum quota of 10TB. All allocations will be publicly available at https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues.
-In order to avoid the recurrence of disappearing applications due to account flags, I will update each allocation in the public google document for community members to review.
-If it is for personal storage/user content, I will confirm with the applicant that he/she is willing to disclose it. If the applicant wishes not to make their application public, the record will only be kept under the application and won't be updated in the online doc.

```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Please see above.

```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
-Applying for L2 as I can't accurately estimate the amount of time I can spend on Filecoin each week. I will try to keep it at 2 to 4 hours though.
-As a part time filecoin-er, I won't be active as much as notaries from web3 organizations. But if anyone wants to contact me when I'm offline on slack, please feel free to reach me via email at carolinalinhere@outlook.com.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No

```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
-In terms of personal contact, I am close to Partick from Factor8 Solutions and Fei from Kerenlogic. As a non-technical participant, there are many technical aspects that I could not understand and they are very kind to help me out. Other than this, I have no contact with any organization or notary. 
-In the future, if I am in contact with more notaries or organizations, I will also update on time under this application.

```

**Comment by Carohere** [comment]
Just added the allocation and the bookkeeping plan. I mistakenly thought L1 notary would not be receiving any Datacap. @Kevin-FF-USA could you help me with the labels again? Thanks!

**Comment by Carohere** [comment]
I just added the allocation and the bookkeeping plan as mistakenly thought L1 notary would not be receiving any Datacap. @Kevin-FF-USA could you help me with the labels again? Thanks!

**Comment by Kevin-FF-USA** [comment]
Hi @Carohere,

Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Please email NOTARYELECTION@FIL.ORG from the email account linked to this GitHub account. *The email MUST COME from the same GitHub account you used in this application.

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Carohere** [comment]
Hi @Kevin-FF-USA @panges2, I didn't receive the token code after the email was sent. Could you guys check it out for me? Thanks!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[676.pdf](https://github.com/filecoin-project/notary-governance/files/10159394/676.pdf)

**Comment by Kevin-FF-USA** [comment]
@Carohere 

Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @Carohere, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by Carohere** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebijfj7ezysorvd4cdevm3zs3v33s3mubi4hobv3gwym4yj4zgyem
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebijfj7ezysorvd4cdevm3zs3v33s3mubi4hobv3gwym4yj4zgyem

**Comment by flyworker** [comment]
@galen-mcandrew  I am questioning if this notary is real in EU.
If she is not clam herself in EU, she won't be elected. I want the team to do a DD.
Can I get more information about her?

**Comment by Carohere** [comment]
@galen-mcandrew willing to send my ID or anything needed, feel free to contact me on slack!

**Comment by The-Wayvy** [comment]
Someone whose introduction to crypto was Libra doesn't have the instincts needed to build a Web3 protocol. 

I propose revoking her privileges.

**Comment by The-Wayvy** [comment]
Her Linkedin profile says she is located in NYC https://www.linkedin.com/in/caroxcai/

**Comment by Carohere** [comment]
> Someone whose introduction to crypto was Libra doesn't have the instincts needed to build a Web3 protocol. 
> 
> 
> 
> I propose revoking her privileges. 

Appreciate you taking the time to check my application @The-Wayvy.  Unfortunately, you found the wrong Caro. I don't work for PL or FF. I don't understand what privilege you are referring to. Nor do I see any relevance in the arguments you have given on Caroline Cai. However, if you still think I am an unqualified notary, please feel free to initiate a proposal in https://github.com/filecoin-project/notary-governance. I would be more than happy to hear you out.
