### ISSUE TITLE
Notary application - Dcent - Wijnand Schouten

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/notary-governance#678]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Wijnand Schouten
- Affiliated organization:  Speedium / DCENT BV.
- Website / Social Media: www.filecoin.nl
- Country of Operation:  The Netherlands
- On-chain address to be notarized (recommend using a new address): f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
- Region of Operation: Europe
- Use case(s) to be supported: Personal user storage, scientific datasets, video & music.
- DataCap Requested: 10 PB
- Are you applying on behalf of yourself or an organization?: Organisation

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
As an individual, I have worked as a crypto miner and programmer / developer for over 4 years. 
I’ve been a part of the Filecoin community since 2020 and founded Speedium and DCENT together with Hidde.
I am also one of the MinerX community members who are helping to make Filecoin better and grow.

As an organization, Speedium is a leading Usenet Service Provider. We have made many steps in onboarding data to the filecoin network and have worked with many notaries ( Phillip , Neowebg3, and AndrewHill ). Speedium is aiming to bring our populair cache to the filecoin network, decentralising the Usenet space and improving the enduser experience.
Dcent is one of Europe’s largest decentralized Filecoin nodes, capable of serving many clients across the globe with reliable storage. We want to provide clients with 100PiB of mirrored storage by the end of 2022. With our networking capabilities, private IP backbone, and 100Gbit/s of throughput, we are far ahead of most companies, who are only getting started learning about this new technology.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
7218 f01199442
4918 f01199430
5873 f01201327
8176 f01207045
5459 f01208862
8693 f01240
4845 f0707721
900  f01608291
3032 f01720359

SubTotal : 49114 FIL

Available on Exchange / Ledger : 16341 ( If evidence is needed it can be shown privately b/c security reasons. )

Total : 65455 FIL
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We have made substantial input on github improving dealmaking and reporting bugs. As a usenet organization, Speedium has been engaged with blockchain technology since day one. We are extremely interested in all sorts of decentralized storage and have been experimenting with multiple blockchain storage projects since 2019. Since the launch of Filecoin we have been participating in Testnet, Spacerace 1, Spacerace 2 and Mainnet.  
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Our team and I have identified several critical bugs during the past two years and have informed the Filecoin team accordingly. 
Please check with Dudley who will be able to substantiate our contributions. 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Speedium ( https://speedium.network ) is the first Blockchain Usenet Platform. We operate our own fully independent backbone ( IPV4/IPV6 ) and Usenet storage.
Currently we are connected with 30 Gb/s with multiple exchanges like Speed-IX / NL-IX proving extreme low latency and high speed transfers throughout Europe.
To find more statistics on how we are connected, see peedingdb.com/net/23120. 
We are currently providing our peering partners with a combined Usenet feed of +/- 140 TB daily and we are fully storing this for over a month in our spool arrays.
We are a Dutch usenet provider and we are operating with three board members, fully operational since 2019.

Dcent has been building a new datacenter in the Netherlands Heerhugowaard where we host Filecoin equipment for ourselves and customers.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Speedium ( https://speedium.network ) is the first Blockchain Usenet Platform. We operate our own fully independent backbone ( IPV4/IPV6 ) and Usenet storage.
Currently we are connected with 30 Gb/s with multiple exchanges like Speed-IX / NL-IX proving extreme low latency and high speed transfers throughout Europe.
To find more statistics on how we are connected, see peedingdb.com/net/23120. 
We are currently providing our peering partners with a combined Usenet feed of +/- 140 TB daily and we are fully storing this for over a month in our spool arrays.
We are a Dutch usenet provider and we are operating with three board members, fully operational since 2019.

Dcent has it's website on www.dcent.nl. All information about us can be found there.

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Organisation: Speedium
Website: https://speedium.network
founded in 2019 
headquartered in Oudkarspel
Number of employees: 4
Discord: https://discord.gg/2hxXZBS
Telegram: https://t.me/speedium

Organisation: Dcent
Website: https://dcent.nl
founded in 2021
headquartered in Heerhugowaard
Number of employees: 4

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Slack : ( WijnandSchouten)
Slack : ( Hiddehoogland )

```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
All usecases that befenit the Filecoin network and humanity.
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We intend to work on principles of limited thrust and we only onboard requests where agreements are made to who the verified data will be send with the respective ratios. Below is the proposed procedure of Due Diligence. We need 3 types of information for review depending on the volume of clients required Due Diligence:
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information; 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name;
 - date of birth; 
 - street address (P.O. box number is not acceptable); 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 
 ```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
On a ledger
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle) 
2. What is your use case for the DataCap being requested and what miners will be storing it? 
3. What is the Filecoin address you would like me to allocate the DataCap? 
4. How much DataCap would you like to request? 
For organizational clients: 
5. What is the name, nature, registration country, time since inception, and named officers of your organization? Please link to relevant websites. 
6. In which region do you intend to use the DataCap? If you intend to use the DataCap in multiple regions, please specify. 
7. How many miners do you plan on allocating a DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
8. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
*9. Have you previously received DataCap? If so, please share some details on how you spent the previous allocated DataCap in terms of question number 6, 7 & 8. 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We plan to support multiple use cases; the percentage will be determined by my knowledge and usage expectation, 
which may vary depending on the variable circumstances of each scenario and different regions. 
- 35% - user content (personal user storage)
- 25% - scientific datasets (AI training, geological data, autonomous driving) 
- 40% - media & entertainment (video & music)
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 

```
Yes, all allocation decisions will be guided by the rubric publicly on Github. So are all communications. 
Since all interactions are intended to occur publically, most of the allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly in the Github repo first. 
If convincing justifications can’t be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions. 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
All allocation decisions will be conducted in the Github repository. 
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.

```
That depends if there is coverage for the costs endured for the labour. If not i guess 2 hours per week. If there is i can spend around 16.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes,[ here]([url]https://github.com/filecoin-project/notary-governance/issues/122(url)).
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
10TB
```

**Comment by Kevin-FF-USA** [comment]
Hi @cryptowhizzard,

Thanks for (re)applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedcha2wmsxdfhbi3jnoo766h72ovaz63ta7edjljqmllzesj4nis4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcha2wmsxdfhbi3jnoo766h72ovaz63ta7edjljqmllzesj4nis4

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[678.pdf](https://github.com/filecoin-project/notary-governance/files/10159398/678.pdf)

**Comment by cryptowhizzard** [comment]
Hi @galen-mcandrew 

## Service Level Agreement
### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630)

L4 is fine. I have been less active for 2 months due family reasons but have already started work again.

**Comment by Kevin-FF-USA** [comment]
@cryptowhizzard 

Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to continue as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedmrgza5wfsqbtgvnokrz5lf4kzsyhriv47t6i5we2oprdxozplhu
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmrgza5wfsqbtgvnokrz5lf4kzsyhriv47t6i5we2oprdxozplhu

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceb5gg37ma7kk3og7fvesdsdgeydqtdes33ci74obiibfquqxttfza
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5gg37ma7kk3og7fvesdsdgeydqtdes33ci74obiibfquqxttfza

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecpufxlqb6ndazfbu3yqkvjvzocnsdcc37arszrwondizjrebcolq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecpufxlqb6ndazfbu3yqkvjvzocnsdcc37arszrwondizjrebcolq

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedfadr3nbr4peysj47q63frqv572lqlosrlbg7qwqh2kvcz533dva
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfadr3nbr4peysj47q63frqv572lqlosrlbg7qwqh2kvcz533dva

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedzdlchudn74gya346glu5uu7ytiswwab2xuyfbkmso5rfx5z4hvu
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzdlchudn74gya346glu5uu7ytiswwab2xuyfbkmso5rfx5z4hvu

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecz3bmce6rjnwtzwvddbrlcwbgeuejocbiag6kxyau5mwmb3qieuu
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecz3bmce6rjnwtzwvddbrlcwbgeuejocbiag6kxyau5mwmb3qieuu

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedpcjptqemg4p3rky72g6zz5bl7le5og4jy6fdueeiu5qoxio2gqs
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpcjptqemg4p3rky72g6zz5bl7le5og4jy6fdueeiu5qoxio2gqs

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaced7ddtgs7qqmglhj5wxluh4hdkg6n7scv4oqx4ykpjzc2nb6275m4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7ddtgs7qqmglhj5wxluh4hdkg6n7scv4oqx4ykpjzc2nb6275m4

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceauwbpcj3eeu3i5cwltmow2of2t7apzd5x2lato5h5cja6cejqus4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceauwbpcj3eeu3i5cwltmow2of2t7apzd5x2lato5h5cja6cejqus4

**Comment by cryptowhizzard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceb6pqbjqyrcnw37xpm3x53h7ym7wcd23ctcqunmk5cm2iel7txwmw
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6pqbjqyrcnw37xpm3x53h7ym7wcd23ctcqunmk5cm2iel7txwmw
