### ISSUE TITLE
Notary Applicaiton: Bewell Technology Limited

### ISSUE THREAD

**Issue by Aaron01230** [filecoin-project/notary-governance#679]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Aaron Hu
- Affiliated organization: Bewell Technology Limited
- On-chain address to be notarized (recommend using a new address):f1hwasapc3rej67muohecn4woa4ctbmyfvaikdxga
- Country of Operation: Hongkong, Singapore, Australia
- Region of Operation: Greater China Region (GCR), Asia minus GCR, Oceania
- Use case(s) to be supported: We want to store data that is valuable to the development of the Filecoin network and meaningful to human development, such as data from Web2 or Web3 applications, NFT, music, movies, educational videos, model training base datasets, etc.
- DataCap requested for allocation (10TiB - 1PiB):1 PiB
- Are you applying on behalf of yourself or an organization?: On behalf of an Organization (Bewell Technology)

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Node f0110261 participated in the slinshot competition. As SP, the nodes that have completed sealing are as follows:
f0567567 
f01773162 
f01814416  
f01839946   
f01852324 
f01928097 
f01825301
f01859905 
f01882234
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Bewell has sealed 100+PiB data with 600,000+ FILs pledged.
```

How did you acquire the FIL cited above?
```
By borrowing from third-party providers such as platforms.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Bewell (http://www.bewelltech.me/) As a large local storage service company in Hong Kong, we have been following IPFS and Filecoin projects since 2018 and have been keenly involved in the Filecoin community since 2019. We participated in the Filecoin Space Race (f0110261) in August 2020 and have since formed a 20+ person technical R&D team specialising in decentralised storage technology development and applications. We want to support projects and new technologies in Hong Kong and around the world to help them take advantage of Filecoin's unique distributed storage solution.
Aug. 2020: Participate in slinshot competition
Sep. 2022: Follow to E-Fil+ Pilot and submit Lead SP application
Jun. 2021-Oct. 2022 Participate in storage construction as SP for a total of 100P+ capacity.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Our technical team often submit error messages or technical queries via Slack, for example:
https://filecoinproject.slack.com/archives/C03CKDLEWG1/p1665408208828499?thread_ts=1665107635.209699&cid=C03CKDLEWG1 https://filecoinproject.slack.com/archives/C01D42NNLMS/p1640139409054200 https://filecoinproject.slack.com/archives/CPFT. 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Country of registration: Hong Kong, China
Employees: Over 20 employees work for Bewell
Founded: Bewell Hong Kong was founded in 2021, its parent company OAKbay was founded in 2016. Our operation locations involves multiple countries including Australia, Singapore and Hongkong as employees work in distributed mode.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website:http://www.bewelltech.me/
Twitter：https://twitter.com/Bewell_SG
Name Officers: Aaron Hu，Linda Li, Kevin Lv;.
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
N/A.
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
twitter: @404notfoundwho（767 followers)
twitter: @MidasWireless (2051 followers)
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
N/A.
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Please refer to the links below to check out rubric used to evaluate client’s application and allocation rate
https://docs.google.com/spreadsheets/d/13t8WAEfOnP9cYsTIiSu51SZO5qlmaCJmlca0AnTB8bQ/edit?usp=sharing
We will conduct the following allocation strategies:

Diversity: Applicants from Oceania will be prioritized because of the unbalance development of Filecoin, we will contribute to this point from perspective of balances.
Applicants Classification: Applicants will be classified into tow basic groups: organization and individuals. Each group is divided into three levels ( small, medium, large)in terms of their organizational reputation, business scale or individual reputation in the community.
Testing allocation: As a new notary, we will do a round of testing allocation for each client category as per the allocation strategy in the initial stage and adjust accordingly in case there is any unreasonable situation for both organizational and individual clients.
Credit review: We will set up a reputation credit mechanism for applicants to encourage honest, active and qualified applicants with valid and efficient DataCap usage. Each allocation will be followed by our track and review.
Rewards and punishment: For applicants with good performances, higher credit scores will be given and increased DataCap will be offered for the following DataCap application. Correspondingly, for those clients with unqualified behaviors, they will be evaluated and flagged, punished or even put into blacklist in serious conditions after investigations.
Ultimate goal: good applicants will be rewarded, bad will be punished and optimized gradually to form a healthy, fair, and sustainable allocation mechanism.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hardware-secured wallet will be used to store the private key and ensure that DataCap permissions can only be signed by myself.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1.we will do online or offline verification, depending on the client's situation
2.For institutional customers, we will review the customer's company business license, business status, official website, business scope, business scale, storage plan, content and source of stored data, etc.
3.We plan to make our audit records public through Github, including all communication records with customers during the audit process.
4.To ensure that customers can make use of the data in correct way, we will ask the potential users the following questions:

- 1)What is the purpose of your DataCap application?
- 2). What is your region and country of residence?
- 3). What is the main source of the DataCap data you are applying for?
- 4). What are the main types of data stored in the DataCap you are applying for?
- 5). How many DataCap do you plan to request and what are the planned storage area and backup quantity requirements?
- 6)How long do you plan to store?
- 7). Are you willing to pay for the storage service?
- 8). How often do you need to retrieve the stored data?

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will ask customers to provide information about their previous DataCap storage transactions, including the type of data stored, node information, etc., to verify that node information is not spread across multiple providers and to assess whether there is any misuse of data. We also require customers to be open and transparent and commit to share their DataCap allocation publicly so that we can regularly check and audit user DataCap usage. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We plan to conduct all allocation decisions in public through Github. 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We plan to create a list via Github to publicly record each user, including all interactions with clients during the review process.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
We commit to no less than 8 hours of engagement per week.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
N/A.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No, neither me nor our organization has any relationship with other existing notaries.
```

**Comment by Kevin-FF-USA** [comment]
Hi @Aaron01230,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Aaron01230** [comment]
Hi, Kevin,

The email is sent from our Organizations email account (bewell88.hk@gmail.com), pls let me know if there is anything incorrect or addtional required information. Thanks so much!

**Comment by Kevin-FF-USA** [comment]
Hi @Aaron01230 ,

You can only pick ONE region of operation - which would you like to have?   Greater China Region (GCR), Asia minus GCR, Oceania

**Comment by Aaron01230** [comment]
> Hi @Aaron01230 ,
> 
> You can only pick ONE region of operation - which would you like to have? Greater China Region (GCR), Asia minus GCR, Oceania

Hi, Kevin,
Thanks for your remind. We'd like to pick the Asia minus GCR if only one is allowed. Thanks!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[679.pdf](https://github.com/filecoin-project/notary-governance/files/10159400/679.pdf)

**Comment by Aaron01230** [comment]
For the Engagement in Program part, we'd like to ud5te our answer as " Level 5".

**Comment by Aaron01230** [comment]
For the Engagement in Program part, we'd like to update our answer as " Level 5".

**Comment by Aaron01230** [comment]
We'd like to update SLA section (Engagement in Program) as "level 5". We are aware of that for this level, we will attend the governance calls with webcam turned on, and comments/votes on all submitted proposals. We are happy to make such commitment and will do as what we've promised.

**Comment by Aaron01230** [comment]
We'd like to update the "Stake Exposure" as follows:

Q: _Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts)._

Answer:

Miner ID       Currently available    Locked as collateral     Vesting over time 
f0567567      41,022.2982 FIL         35,384.4552 FIL            57,281.6138 FIL 
f01773162    86,906.2876 FIL         73,465.207 FIL              52,852.3891 FIL 
f01814416    97,351.1057 FIL         82,589.5133 FIL            47,676.9285 FIL 
f01839946    97,860.7144 FIL         82,926.6932 FIL            39,599.1718 FIL 
f01852324    90,096.5063 FIL         79,550.8488 FIL            20,273.1629 FIL 
f01928097    56,787.2419 FIL         53,931.2226 FIL            4,353.9718 FIL 
f01825301    89,800.5216 FIL         82,926.6932 FIL            41,001.0985 FIL 
f01859905    100,444.3304 FIL       83,862.9944 FIL            37,760.1215 FIL 
f01882234    111,093.4766 FIL       93,935.3991 FIL            32,617.536 FIL 
We disclosed 9 miners with total 668573.03 FIL locked as collateral. All these data can be explored and verified via https://filscan.io/.

Q: How did you acquire the FIL cited above?
Answer: It is mainly the proceeds and investment from the company's business development and some institutional borrowings.

**Comment by Aaron01230** [comment]
Allocation Strategy
_How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap._

Answer is updated as follows:

We support all industries and there are no restrictions on regions, industries or types of corporate entity, as long as the data meets the norms and regional legal and regulatory requirements. 
Please refer to the links below to check out rubric used to evaluate client’s application and allocation rate
https://docs.google.com/spreadsheets/d/13t8WAEfOnP9cYsTIiSu51SZO5qlmaCJmlca0AnTB8bQ/edit?usp=sharing

We will conduct the following allocation strategies:

**Progress distribution plan:** We plan to allocate approximately 25% of Datacap on a quarterly basis, with each client requesting no more than 20% of the Datacap we have.

**Application Assessment through KYC/KYB**: the applicant's basic information will be assessed such that the date of establishment, quantity of employees, registered capital, social reputation, data distribution, data volume, history, etc. completely by the following ways:
	viewing official websites, media platforms, business information, etc. to understand the basic information of the organization.
	Asking the client to verify the information through the company's domain email.
	Creating a form file to record the client's sealed information for subsequent verification

**Diversity**: We will pay attention to the diversities of clients in terms of industries and physical locations. 

**Applicants Classification**: Applicants will be classified into two basic groups: organization and individuals. Each group is divided into three levels ( small, medium, large)in terms of their organizational reputation, business scale or individual reputation in the community.

**Testing allocation**: As a new notary, we will do a round of testing allocation for each client category as per the allocation strategy in the initial stage and adjust accordingly in case there is any unreasonable situation for both organizational and individual clients.

**Credit review**: We will set up a reputation credit mechanism for applicants to encourage honest, active and qualified applicants with valid and efficient DataCap usage. Each allocation will be followed by our track and review.

**Rewards and punishment**: For applicants with good performances, higher credit scores will be given and increased DataCap will be offered for the following DataCap application. Correspondingly, for those clients with unqualified behaviors, they will be evaluated and flagged, punished or even put into blacklist in serious conditions after investigations.

**Ultimate goal**: good applicants will be rewarded, bad will be punished and optimized gradually to form a healthy, fair, and sustainable allocation mechanism.

**Comment by Aaron01230** [comment]
**Client Due Diligence**
_How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them?_

**Answer is updated as follows:**

All customer applications are subject to rigorous scrutiny, and the more Datacap requested, the more rigorous the scrutiny.

We will conduct the review in the following ways.
1. Request necessary business licences, business registration certificates, passport information documents, etc. (email communication is recommended to protect privacy)
2. Check the company's product type, business model and press status through information on social media accounts, official websites and other platforms.
3. Check online information about the company in the country/region to initially verify business information such as business scope, establishment date, registered capital, organisation size, shareholding information, etc.
4. Confirm with the official email whether the client subject is applying for DataCap and confirm the applicant's identity and work information.
5. Make certain tracking records to ensure customer storage compliance.

We will ask clients the following questions (flexible in terms of the client's reality).
1. Can you share some information about yourself/your organization, including online social media/website links/region or country of residence/aim of DataCap application,etc.?
2. How much data do you want to store and what are your sources of data and can you provide some evidence to prove this?
3. What is your initial data storage plan (i.e. how long plan to store, storage area, backup quantity requirements)? What are the appropriate SPs to communicate with? Can you list their names?
4. what are you currently using for storage and what is the approximate price, volume and frequency of use?
5. what is your strategy for uploading data to Filecoin?
6. Can you share the actual use of your Datacap allocation to ensure Datacap usage compliance?
7. What data content do you store and does this content comply with local laws and Filecoin community standards and regulations?

_What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity._

**Answer is updated as follows:**

We will do this in the following way and manner.
1. Detailed and effective KYC, due diligence and explanation of rules upfront are rather critical to encourage customers to allocate Datacap to different SPs.
2. Clients are required to disclose transaction information on a regular basis.
3. We will conduct regular checks via the filplus.info website to record Datacap transactions and allocations and verify them in conjunction with the information disclosed by the client.
4. We will alert our clients to irregularities if they are identified. If the breach is serious, we will disclose the client's breach in the slack public community.

**Comment by Aaron01230** [comment]
**Bookkeeping Plan**
_Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both?_

**Answers are updated as follows:**
We will keep a record on Github of every detail of all allocation decisions, including time, quantity, which clients were allocated, why they were allocated, why they were not allocated, etc. All interactions and decisions will be made public and any queries or questions about allocation decisions will be openly discussed e.g. on Github Repo. The community will be open to scrutiny and questioning while ensuring that the privacy of the client or business is not compromised, and community opinion or voting results will be respected for controversial allocation decisions.

_Where do you plan on keeping a publicly accessible record of all your allocation decisions?_

**Answers are updated as follows:**
We will maintain public GitHub records and conduct private chats via Slack or Telegram. In addition, without revealing any confidential customer information, we are happy to respond to reasonable enquiries or queries from community members about our DataCap allocation decisions.

**Comment by Kevin-FF-USA** [comment]
@Aaron01230 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. _(score was updated to reflect discussions during Dec08 Office Hours)_

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by Aaron01230** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceazsmqyzqrow4rzer6qmwpkgjq7l4bvjax2wb2s27axqut622uwsc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazsmqyzqrow4rzer6qmwpkgjq7l4bvjax2wb2s27axqut622uwsc
