### ISSUE TITLE
Notary Application - Meibuy Cloud

### ISSUE THREAD

**Issue by Meibuy** [filecoin-project/notary-governance#681]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Meibuy
- Affiliated organization: Meibuy Cloud
- On-chain address to be notarized (recommend using a new address):f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
- Country of Operation: Seychelles
- Region of Operation: [ Africa]
- Use case(s) to be supported: [Professional Services, Decentralized Applications, Public or Open Data, Media & Entertainment]
- DataCap requested for allocation (10TiB - 1PiB): 100TiB
- Are you applying on behalf of yourself or an organization?: [Organization]

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
We have worked as a crypto miner for over 5 years. 
We founded Meibuy Cloud in 2019,and we’ve been a part of the Filecoin community since 2020 and. Filecoin is one of our exploration  projects.
We participated in the FVM Early Bird Program and joined the Sunrise Retrieval Project.
We are the members of many Filecoin Storage Provider Working Groups. 

More information: 

- Github/Slack handle: @meibuy
- Storage Provider ID: f0133505,  f0680529, f089173
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
The total FIL at stake is over 2MM, with the following miners  f0133505,  f0680529, f089173 by the date of Nov 11, 2022. 
```

How did you acquire the FIL cited above?
```
Block rewards, Storage Providing as a Service. 
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- joined multiple events like the Mining Hardware & Architecture talk and the Miner Spotlight panel during Filecoin Liftoff Week: https://filecoin.io/blog/mainnet-liftoff-day2/
- 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```
### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Meibuy was established in Seychelles in 2019 and currently has 85 employees, and  offers on-demand  edge cloud services in over 130 PoPs around the world, with expertise in fast-growing emerging markets like India, China, and South America. Businesses utilize Meibuy’s global edge cloud platform to instantly improve digital experiences for their users with ultra-low latency and worldwide connectivity on demand.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://www.meibuy.info/
House of Francis, Room 303, Ile Du Port, Mahe, Seychelles.
marketing@Meibuy.info
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.meibuy.info/Partners.html
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter: @joanna57630112
Wechat: @Meiybuyweb3 
more than 800 followers.
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://forkast.news/filecoin-space-race-miners-challenged-with-network-upgrades/ 
https://startups.hackernoon.com/south-asia/jaipur-india
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We will reference heavily on the allocation strategies we used in the past year. 

The purpose of allocating the DataCap is to make sure clients use these DataCap in the right way to store real and valid data. We firstly specify some rules to figure out the true identity of the applicant.
* Browse their official website to get a general understanding of the company or the individual. 
* Query the company's registration information from government related websites to make sure the information he submitted is true.
* Ask some questions to know about the applicant's position/organization/plans/use case etc. 
* Then We will classify applicants based on their industry reputation and scale etc. All applicants will be divided into eight levels of grading to determine the amount of DataCap they will get. 

The following Rubric will be the primary guideline we use when evaluating a client and determining their DataCap allocation.
https://docs.google.com/document/d/1ruQTWvKthsiAGi97CrJhwo3hSsquHowRSdT3DLYwc48/edit?usp=sharing

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hardware wallet (Ledger) is currently used to store the keys associated with the DataCap allocation address securely.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 
For individual clients, online identity will be verified by both account age and account activity perspectives, 
and this will serve to prove that they are valid users and not bots or sybils. 
Third-party tools like twitteraudit may also be used to verify online identities. 

For organizational clients, application organizations should be easy to verify through the appearance of their application. 
The developing applications may require further stringent investigation; 
this is to ensure that the application is valid and enclosed with meaningful content, rather than the shell of a malicious client. 
Large public datasets hosted by organizational clients are easy to verify because the data should be unencrypted and accessible to anyone. 
However, in the event that the organizational client has large private encrypted datasets(i.e., law firms), the Due Diligence procedure will be executed.

Below is the proposed procedure of Due Diligence. We need 3 types of information for review by myself or our compliance team depending on the volume of clients required Due Diligence:
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information; 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name;
 - date of birth; 
 - street address (P.O. box number is not acceptable); 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

There are two questionnaires to help me get to know our clients. The first one is about the basic information collection of new clients. 

Questionnaire #1
Please describe answers as much specificity as you can.

1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.)
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
6. How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify.
7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
I will use the second questionnaire to collect follow-up answers about previous allocations for returning clients. 

Questionnaire #2
Since you have requested DataCap from me before, I have some questions regarding your previous DataCap allocation.

1. How much cumulative DataCap was allocated to you from me?
2. In which region(s) did you use the DataCap?
3. What was your use case for the previous allocation?
4. Did you specify any advanced features for the previous allocation?
5. How many miners did you allocate the DataCap to? Please specify transaction links to the storage deals.
6. In your previous allocation, did you violent any community principles like excessive/unfair self-dealing?
7. Is there anything I could improve to serve you better in future allocations?

Utilizing the information collected will help me confirm that the client is not improperly using the DataCap they were previously granted. 
Clients are encouraged to allocate the DataCap to more than 5 different miners, 
which not only increases storage redundancy but also helps maintain decentralization and reduce the possibility of potential misuse. 
The more miners clients allocate, the more DataCap clients are likely to get. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, all allocation decisions will be conducted in the Github repository. 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Github. 
Since all interactions are intended to occur publically, most of the allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly in the Github repo first. 
If convincing justifications can’t be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions. 
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L3
Maintain a ranking in Leaderboard in the top 25% of Notaries.
Attend 2 Governance calls a month
Join 1 working group
Respond to SLACK inquiries within 2 days
Vote/Comment on 1 proposal a month
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
N/A
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
N/A
```

**Comment by Kevin-FF-USA** [comment]
Hi @Meibuy,

Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[681.pdf](https://github.com/filecoin-project/notary-governance/files/10159405/681.pdf)

**Comment by Kevin-FF-USA** [comment]
@Meibuy 

Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @Meibuy, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by Meibuy** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceckqzek6f4gldzw3o7sfqhur4lcqihbtywuk4ijyeo23y6n7l6lls
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceckqzek6f4gldzw3o7sfqhur4lcqihbtywuk4ijyeo23y6n7l6lls

**Comment by Kevin-FF-USA** [comment]
Hi @Meibuy 
Wanted to send one final note here - still need to receive a HUMAN name of the controller of your ledger wallet.  Feel free to follow up here or in our SLACK DM. If not received, you will not be able to allocate DataCap

**Comment by Kevin-FF-USA** [comment]
Hi @Meibuy 
Sending a final check in on the name question for your application.  In the disclosure form you submitted, there is no name.  Need a full human FIRST and LAST for the completion of the sanctions checks. Without this, we not be able to move forward with your Notary onboarding.
