### ISSUE TITLE
Notary Application : Antalpha Digital Pte. Ltd.

### ISSUE THREAD

**Issue by nj-steve** [filecoin-project/notary-governance#683]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Xin Jin
- Affiliated organization: Antalpha Digital Pte. Ltd. 
- On-chain address to be notarized (recommend using a new address): f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
- Country of Operation: Singapore
- Region of Operation: Asia minus GCR
- Use case(s) to be supported: Professional Services,Developer Tools,User Content,Public or Open Data,Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).

1.I personally participated in Filecoin network in 2019 and I create and operate my own nodes (such as f02725,f03249) when Filecoin main network started in August 25, 2020. 
2.Antalpha participated in the Filecoin network since 2021, currently actively preparing for IDC resources in the United States and Canada, and hope to provide the high quality IDC infrastructure for filecoin miners in the future, and also provide the beneficial solutions for the miners who need to relocate their data.
3.Aso,Antalpha provided a lot of financial services to miners,help them with financial problems.

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
Antalpha as a financial company has invested about 500,000 FIL.All the FIL was deposited in a fund company account.And we will increase investment to 1,000,000 FIL or more in the near future. 

How did you acquire the FIL cited above?
We bought through the exchanges,and the miners mortgaged to us.

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
1.We have lent USDT to some miners at low interest rates to help them run their companies.
2.We are actively preparing to launch the Filecoin Fund,and that will help more people to participate in Filecoin network.
3.There will be active investment in the disaster data field, and the plan will be integrated with Filecoin and IPFS.

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
In a bear market, some miners can't afford to pay IDC room fees or the company has financial difficulties, we pay a very low interest rate，lend them USDT.They can stay online in filecoin net,avoid causing penalties.

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
1.Antalpha Technologies Ltd is a key player in enabling institutional investors from both traditional finance and the blockchain space to transition towards the global adoption of the emerging megatrend of digital assets. 
2.We were established in 2021 in Singapore, Antalpha have 300+ employees,and Antalpha manages over $800mm crypto asset and provides our customer with inistitutional
grade financial services.
3.We invest in the world's future infrastructure for Web 3.0, blockchain and digital asset technology.

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
Antalpha Official website: http://www.antalpha.com
Twitter：@AntalphaGroup
Twitter：@Antalpha_Labs
Medium: @Antalpha
Linkedin: @Antalpha

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
https://finance.yahoo.com/news/antalpha-attends-hsbc-future-technology-090600573.html
https://finance.yahoo.com/news/antalpha-speaks-ubs-private-wealth-080500600.html
https://www.antalpha.com/Details
https://www.coindesk.com/business/2022/07/26/bitmain-partner-antalpha-unveils-a-host-of-needed-lending-products-for-miners/

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
https://twitter.com/antalphagroup
https://twitter.com/antalpha_labs
https://antalpha.medium.com/

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
https://www.antalpha.com/Insights
https://www.prnewswire.com/news-releases/antalpha-enters-licensing-agreement-with-sp-dow-jones-indices-301638364.html
https://www.coindesk.com/business/2022/07/26/bitmain-partner-antalpha-unveils-a-host-of-needed-lending-products-for-miners/

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.

1.Allocating the DataCap is all about distinguishing rational clients from malicious clients, and as such, my allocation strategy seeks to emphasize the key question "how much does the Notary trust the client?" rather than "does the Notary trust the client?". I have set up thresholds with varying degrees of trust. The way we traditionally audit Notaries can also be used to audit clients as well. The Rubric will be the primary guideline I use when evaluating a client and determining their DataCap allocation. These scoring guidelines can serve as a tool of assessment and further add a level of consistency across the board.The Rubric in the following form will be our guide we use to evaluate client DataCap.  
https://docs.google.com/spreadsheets/d/1Mq2-bjn0ch1jBC_4wqjKuEbrqQDeTrU4UbNmRKjpRD8/edit?usp=sharing

2.We plan to support multiple use cases; the percentage will be determined by my knowledge and usage expectation, 
which may vary depending on the variable circumstances of each scenario and different regions. 
- 10% - User Content
- 20% - Professional Services
- 20% - Developer Tools
- 20% - Media & Entertainment
- 30% - Public or Open Data

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
A hardware wallet will be used to store the key associated with the DataCap allocation address securely.And the github account and wallet are managed by two people.

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
We will read and study the applicants carefully.
1.We will research the background of the client organization.
2.We will research the sample data,I will check if the data has relationship between the client.
3.We will research the client organization authenticity and size, if the client has ability to hold the so much data.
4.We will allocate DataCap to client in three stages.If the client do it well,we will expand the DataCap to the client in next stage.
Below will be what we want to ask:
1.Do you know the rules that we store data in filecoin? Please describe it briefly.
2.Could you tell me briefly about your organization background? I will check if the data type is generated or owned by the client.
3.Could you know the SPs you want to send deal?
4.How do you find the SPs you want to send deal?
5.How do you send data to SP？
6.Could you send me picture of the business license or certificate information of the organization? 
7.Could you tell me how much data do you have now,and where do you store the data in?

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
1.We will check the client in filplus.info,then we will find the num of SPs.
2.We will search the client deal in filscout.com or filfox.info,is there one or two handle most deals. No SP can get more than 30% DataCap allcation.
3.We will search the SPs,if they are in a same region.

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
Mostly we will conduct all allocation our decisions in public through github or slack. When someome will need, email will be used.

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
Mostly in public via github repo, when needed a few will be on slack.

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
Level 4 please.

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
No.

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
No.

**Comment by Kevin-FF-USA** [comment]
Hi @nj-steve,

Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[683.pdf](https://github.com/filecoin-project/notary-governance/files/10159409/683.pdf)

**Comment by Kevin-FF-USA** [comment]
@nj-steve 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by Kevin-FF-USA** [comment]
@nj-steve 
As of this writing we have not received your DISCLOSURE form. If this was previously submitted, please fwd me the email confirmation received to NOTARYELECTIONS@FIL.ORG

If not completed, you will have until COB Feb 6 to complete for each member of your organization. Without this verification you will NOT receive DataCap

**Comment by nj-steve** [comment]
@Kevin-FF-USA Thanks Kevin, I have written the DISCLOSURE form , please check it. And just now I modified the sign wallet to f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii  in the github application (https://github.com/filecoin-project/notary-governance/issues/683) to match the Ledger hardware wallet.Please check it together.

**Comment by nj-steve** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecn7lsofjbliour734zzeffvwwpsw7kjrhdz7g4hhpwo2dpafz7e2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecn7lsofjbliour734zzeffvwwpsw7kjrhdz7g4hhpwo2dpafz7e2

**Comment by nj-steve** [comment]
@Kevin-FF-USA Hello Kevin , we have completed the verification of our ledger.And have recieved the  "Notary Ledger Verified" information . Please help me to check it out . Thanks.

**Comment by Kevin-FF-USA** [comment]
Closing Application - Completed. Shifting future support questions/comms into the SLACK channels. Warmly!, -Kevin
