### ISSUE TITLE
Notary Application: FileDrive Labs - Laura Ren

### ISSUE THREAD

**Issue by laurarenpanda** [filecoin-project/notary-governance#684]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [[here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview)](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information

- Name: Laura Ren
- Affiliated organization: FileDrive Labs
- On-chain address to be notarized (recommend using a new address): f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
- Country of Operation: PRC
- Region of Operation: [Greater China Region (GCR)]
- Use case(s) to be supported: [Professional Services, Developer Tools, Decentralized Applications, Public or Open Data]
- DataCap requested for allocation (10TiB - 1PiB): 1 PiB
- Are you applying on behalf of yourself or an organization?: [Organization]

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment

Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).

```
After finishing my Master's Degree at the University of Melbourne, I returned to Shanghai, joined FileDrive Labs, and started my career in the Blockchain industry.

As a Web 3.0 enthusiast and advocate of decentralized storage, I have been focusing on IPFS/Filecoin research and development since 2020 and working full-time as Co-founder of FileDrive Labs.

Since November 2020, Filecoin Plus launched its Beta version, I have been following this program and led the development and iteration of its first dashboard filplus.info, which could efficiently assist Notaries and community members in tracing the usage and flow of each DataCap allocation.

More info about myself:
- GitHub: @laurarenpanda
- Slack: @Laura Panda
- Deeply involved in: Slingshot/FIL+/FVM/Retrieval Market
```

### Stake Exposure

Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).

```
f072550
4001 FIL
https://filscan.io/address/general?address=f072550
```

How did you acquire the FIL cited above?

```
Filecoin Slingshot Competition/Filecoin DevGrants/Hackathon Awards
```

### In-protocol Reputation

Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

```
Since 2020 I joined FileDrive Labs as a core member, I have been concentrating on IPFS/Filecoin ecosystem and contributing to the Filecoin community as a member of it.

Filecoin Community activities:
1. Panelist Speaker at FIL-Singapore Summit, September 27th, 2022:
- https://youtu.be/Y3rO5hRWZ80
2. Winners' Call at Web3 Infinity Hackathon, July 31st, 2022: 
- https://www.bilibili.com/video/BV1VG4y1v7UE/?share_source=copy_web&vd_source=3cd9c8f7cb0677474a2b2f6383369985
3. Presentation at Slingshot Phase 2.4: Closing Ceremony, August 3rd, 2021:
- https://youtu.be/WZjl5jwLnpA
4. Presentation at Slingshot Phase 2.3: Closing Ceremony, June 10th, 2021:
- https://youtu.be/uG8RtJuFcqc 
5. Filecoin Plus Day, May 11th, 2021:
- https://youtu.be/wP4Bk8lBNUc

As Program Manager of FileDrive's technical programs and tools to contribute to Filecoin implementation:
- Go-Graphsplit: A tool for splitting a large dataset into graph slices to make deals in Filecoin Network.
- filplus.info: The 1st visual dashboard for Filecoin Plus, recording DataCap allocation and verified deal transactions on Filecoin.
- FileDrive Datasets: A use case to effectively connect Filecoin storage market with large public datasets.
- Go-DS-Cluster: A storage layer solution gathering distributed key-value datastores to become a cluster to improve data split function and management.
- FileDAG Storage: A distributed storage service built on the IPFS technology stack, focusing more on data management, reliability, availability, fault tolerance, and clustering storage nodes.

IPFS/Filecoin activities and articles to help ecosystem grow:
- FileDrive Meetup: monthly event started on March 2022
- Articles in Chinese and English: published on FileDrive's WeChat Offical Account and Medium
```

### In-protocol Security

Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 

```
None.
```

### Organizational Reputation

Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

```
FileDrive Labs is a technical team aiming to provide a high-customized decentralized storage service for Web3 data and develop storage applications with more reliability and availability based on IPFS/FIlecoin.
In 2019, FileDrive Labs was established by core members in Shanghai, China, and began to do in-depth research and development around the IPFS technology stack.
Now, FileDrive Labs has ten core team members focusing on self-developed tools and programs contributing to IPFS/Filecoin ecosystem and Web 3.0 World.

Open-source programs:
- Go-Graphsplit: https://github.com/filedrive-team/go-graphsplit
- Go-Parallel-Graphsync: https://github.com/filedrive-team/go-parallel-graphsync
- Go-DS-Cluster: https://github.com/filedrive-team/go-ds-cluster
- FileDAG Storage: https://github.com/filedag-project/filedag-storage

Tool for FIL+:
- filplus.info: https://filplus.info/

Part of Filecoin ecosystem:
- Filecoin Data Onboarding WG with FileDrive Storage Solutions: https://dataonboarding.filecoin.io/
- Filecoin Retrieval Market with ParallelGrapgSync: https://retrieval.market/
- Protocol Labs Network Directory: https://www.plnetwork.io/directory/teams
- Member of FVM Early Builder Foundry
- Spaceship Member of Filecoin Orbit Community: https://orbitcommunity.filecoin.io/
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

```
Website: https://filedrive.io/
Twitter: https://twitter.com/FileDrive1
WeChat Official Account: FileDrive
Medium: https://medium.com/@FileDrive1
GitHub: https://github.com/filedrive-team
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

```
Tweets posted by Filecoin/FF:
- https://twitter.com/FilFoundation/status/1574586175255244806?s=20&t=TbJHj1NFBaXRaXzy6apxow
- https://twitter.com/Filecoin/status/1563169402719154177?s=20&t=TbJHj1NFBaXRaXzy6apxow
- https://twitter.com/Filecoin/status/1467189376824143875?s=20&t=TbJHj1NFBaXRaXzy6apxow
- https://twitter.com/FilFoundation/status/1408824913675395084?s=20&t=TbJHj1NFBaXRaXzy6apxow
- https://twitter.com/momack28/status/1408853172366450692?s=20&t=TbJHj1NFBaXRaXzy6apxow

Articles:
- https://filecoin.io/blog/posts/large-datasets-filedrive/
- https://filecoin.io/blog/posts/slingshot-phase-2.3-recap/
- https://filecoinfoundation.medium.com/introducing-the-wave-7-developer-grant-recipients-e302c44c35f6
```

### Individual Reputation

Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.

```
Twitter: @LauraPandaR,5 followers
Weibo: https://weibo.com/u/2277287193, 5400+ followers
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)

```
Panelist Speaker at FIL-Singapore Summit
- https://youtu.be/Y3rO5hRWZ80
Presentation at Slingshot Phase 2.4: Closing Ceremony
- https://youtu.be/WZjl5jwLnpA
Presentation at Slingshot Phase 2.3: Closing Ceremony
- https://youtu.be/uG8RtJuFcqc
```

# Allocation Plan [[refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)

### Allocation Strategy

How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.

```
FileDrive Labs supports all types of industries and entities, especially start-ups willing to use Filecoin to store real and useful data created from their business. So we would like to decrease the threshold and requirement of clients' 1st DataCap allocation application.
For detailed info about allocation strategy, please check https://docs.google.com/spreadsheets/d/1riBmGJhgLbnZia-i9HReGeAHu_C6m7-UyITEbpJyVcU/edit?usp=sharing.

For due diligence, it is necessary to collect basic information from applicants, including:
- Detailed information about their teams/companies/entities
- In-protocol or social reputation
- Data/use-case details
- DataCap allocation plan
- History of previous DataCap allocation

With the required info, we could know better about applicants and their businesses, verify their qualifications and authenticity, review data samples, and decide to allocate certain DataCap according to our allocation strategy rating form.

Clients with great credit and reputation in Filecoin Plus could gradually increase their limitations for their one-kick DataCap allocation application.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
An offline wallet will be used for DataCap allocation only.
And multi-sig wallet will be used when more team members join the Notary work.
```

### Client Due Diligence

How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 

```
All clients have to go through a strict process to be qualified in the early stage.

Questions about the Client's qualifications:
1. Entity Information
 - Formation documents: includes certificates of registration/incorporation/information
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory's authority to act on behalf of the application entity (evidence include written consent of the company board of directors, a secretary's certificate, a signed letter from the applicant's CFO, or may be included in the company operating agreement); 
 - close-up photo of the signatory's face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners
If there are any 25%+ shareholders, we need a document, including a capitalization table, operating agreement, or similar, to verify the ownership, and also the following information for each of them: 
	 - legal name;
	 - date of birth; 
	 - address; 
	 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 	- a copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence, which bears a photograph of the individual. 


Question about the DataCap allocation plan:

1. Introduction of yourself/ your organization(with links)
2. Use case
3. Location
4. Max DataCap Allocation
5. Filecoin address
6. SPs you intend to allocate DataCap with allocation proportion
7. Specific requirements of SPs and storage service
8. For-profit or not
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.

```
Audit of DataCap usage
- using filplus.info to check the usage of DataCap and the flow of verified deals to ensure these DataCaps were not improperly used.

Retrieval usability test
- randomly do retrieval usability tests and detect whether its content is consistent with its DataCap application.
```

### Bookkeeping Plan

Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 

```
All my allocation decisions will be accessible and in public.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?

```
Yes.
All allocation decisions and records will be public on GitHub, and support to be checked on filplus.info.
Any challenges and discussions about my allocation decisions must also be raised, discussed, and solved publicly.
The response time should be limited to a maximum of 14 work days.
```

### Engagement in Program

Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [[rubric](https://github.com/filecoin-project/notary-governance/issues/630)](https://github.com/filecoin-project/notary-governance/issues/630) 

```
L4
- Maintain a ranking in Leaderboard in the top 10% of Notaries.
- Attend 2 Governance calls a month.
- Join 2 working groups
- Respond to SLACK inquiries within 2 days
- Vote/Comment on >2 proposals a month
```

### Past allocation 

Have you previously received DataCap to allocate before? If so, please link to any previous applications.

```
No.
```

## Disclosures

Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.

```
No.
```

**Comment by Kevin-FF-USA** [comment]
Hi @laurarenpanda,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by laurarenpanda** [comment]
> Hi @laurarenpanda, Thanks for applying to become a Notary in the Fil+ program!
> 
> As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. *This cannot be from your personal account. You Must include the address of your Organization.
> 
> Subject Line: Notary Name, Application Number Email Body:
> 
> Your First and Last name Your Organization Your Country of Operation Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/) Link to this GitHub application
> 
> This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.
> 
> Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2
> 
> Thank you!

The verification email has already been sent. Please take a look.
Thanks!

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by laurarenpanda** [comment]
> Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

Hey @raghavrmadya & @Kevin-FF-USA .
More proofs have been sent to [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG).
Please check it.
Thanks!

**Comment by Kevin-FF-USA** [comment]
@laurarenpanda 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @laurarenpanda, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by laurarenpanda** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceb774ok6mnqkg5wcykb7vk36oohbqdxyt4aliuksmh5pzxkg633vm
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb774ok6mnqkg5wcykb7vk36oohbqdxyt4aliuksmh5pzxkg633vm

**Comment by laurarenpanda** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecsuegk2pjq3tzfhinvdrj2xjkoxvpssla2dczzv3ncss4ximrbna
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsuegk2pjq3tzfhinvdrj2xjkoxvpssla2dczzv3ncss4ximrbna

**Comment by laurarenpanda** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceaik6a5xqzxazzmjwuowh7khqnycrn5x2ynvunud7jgml2ovycfva
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaik6a5xqzxazzmjwuowh7khqnycrn5x2ynvunud7jgml2ovycfva
