### ISSUE TITLE
Notary Application：Allan

### ISSUE THREAD

**Issue by Xalanii** [filecoin-project/notary-governance#685]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Allan
- Affiliated organization: Charles Schwab Corporation
- On-chain address to be notarized (recommend using a new address): f1oa7kmecgitjl4pu2wtswgz6u7kgmbkeqpj77gfa
- Country of Operation: USA
- Region of Operation: North America
- Use case(s) to be supported: Media , Entertainment
- DataCap requested for allocation (10TiB - 10PiB):10PiB
- Are you applying on behalf of yourself or an organization?: Individual

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
The Charles Schwab Corporation (NYSE: SCHW) has been a leader in financial services for more than three decades. Through advocacy and innovation, the company has worked to make investing more affordable, more accessible and more understandable to all. 
The company began to focus on the investment and management of digital assets in 2019. Invested in a number of blockchain R&D and operation companies, our team started started paying attention to Filcoin in 2021, and set up a professional team to invest in Filcoin.
Charles Schwab maintains a presence on third-party social media sites including Twitter, Facebook, LinkedIn, YouTube, Vimeo, Google+, and Instagram.

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Can't disclose relevant details per company policy
```

How did you acquire the FIL cited above?
```
This filcoin is investment income, in the Coinbase exchange.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
I am currently an investment manager at Charles Schwab. I have been focusing on the field of digital currency, currently working and living in Los Angeles. I started paying attention to the growth of filecoin in 2021. So far, my team has invested in several filcoin-related projects, and has been actively participating in the community and staying active on Slack.

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Charles Schwab Corporation is a public traded company on the New York Stock Exchange

NYSE: SCHW 

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://www.aboutschwab.com/

YouTube:  https://www.youtube.com/channel/UCLOkwpc70MlIDNlqarBAfhg

Instagram: https://www.instagram.com/charlesschwab/

facebook: https://www.facebook.com/CharlesSchwab/
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.mg21.com/schw.html
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Discord: Koby #0465
Slack: Allan Ni
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://www.schwab.com/research/etfs/quotes/summary/stce
https://www.schwab.com/cryptocurrency
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```

The allocation strategy is to make DataCap more effectively. We adopt different review strategies according to customer types and a phased allocation strategy for each allocation of DataCap, which can be outlined as follows.

(i) Different types of customers have different allocation and review rules.

(ii) Approved DataCap will be delivered to customers gradually to ensure that we are able to monitor the correct use of DataCap shares by our customers.


1. Allocation of shares by customer type:

First, we divide the applicants into (i) general users and web3 developers (ii) corporate entities or organizations. It is expected that 30% of our DataCap quota will be allocated to general users and web3 developers, and the remaining 70% will be allocated to corporate entities or organizations.

Therefore, there are different rules that apply to these two types of applicants.

(i) For regular users, identity verification (the real name verification) will be performed. In order to promote the use of Filecoin among the general user community, the verification for general users will be minimized by allocating a maximum of 3 times per person, with a maximum of 1Tib per application, and the approval of the second application will be based on the applicant's rating.
(ii) For web 3.0 developers, who will be the ones strongly supported. Only the time of their GitHub registration and the site of their web3.0 application will be verified to ensure their authenticity. There is no limit to the number of applications, with a maximum of 10Tib per application. The approval of the second application will be based on the applicant rating and the impact of the applicant's application.
(iii) For entities, 70% of the DataCap quota is used on data storage for social enterprises, well-known Internet companies, research institutes, public welfare organizations, and other organizations. Since the early DataCap quota market is not mature enough, we will be proactive in acquiring valuable applicants. We have worked with several web2.0 companies who are potential applicants for our quota and are well known in China and the world. We are bringing this applicant data to Filecoin, which will help the ecological landing of Filecoin.

2. Phased allocation of shares
First, any applicant's DataCap will be allocated in stages, and the applicant will usually only receive 20% of the allocated share in the first stage. Only when it is determined that the current stage share is being used correctly will it be possible to receive the allocation of the next stage share. Applicants must meet the requirements: (i) storing only approved and compliant data (ii) not trading with a single SP.
Secondly, we will evaluate the applicant's score for each phase, which will affect their next application.
Applicant's scoring adjustment rules: Refer to the scoring rules form to rate applicants: https://docs.google.com/spreadsheets/d/1elUmUpJlQbsVoJlL3K8ibLQP88t0oLCL36TaTiq5KoU/edit?usp=sharing

The allocation process is basically as follows.
(i) Each applicant provides application information to initiate the review process.
(ii) Based on the information provided by the applicant, an initial review will be conducted, and the applicant must have a reasonable need for data storage. The requested share size must match the data storage requirements.
(iii) Applicants who fail the initial review will be asked to provide additional information, and applicants who fail the re-examination and refuse to provide additional information will be rejected.
(iv) For corporate entities or organizations, applicants that pass the initial screening will proceed to the due diligence phase; for individual users and web3 developers, they will proceed to the DataCap review phase.
(v) For entities or organizations that pass the due diligence and individual users and web3 developers that pass the preliminary review, the rating scoring process will begin. There may be cases where the allocated share is less than the share applied for by the applicant, which will be awarded based on their storage needs and the rating results.
(vi) Notify applicants in written form whether they have been awarded or denied.
(vii) Tracking and spot-checking the applicant's DataCap usage on an ongoing basis.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hardware wallet will be used to store the keys for DataCap address.

The notary will use a personal Ledger to access the site and specify a data cap. Therefore, it does not grant permission for non-notary users to access the site or assign data limits.

Therefore, we will pay close attention to ensure that the approval of the applied customer is not omitted, while ensuring fair and fair DataCap approval.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
First, check the certificate of business registration, corporate certificate, and other government-issued organization certificates with the agency information, and check the certificate or other evidence to prove the ownership of the data.
Next, we will check the certificate issued by the head of the agency for the applicant and check the photo of the desired posture and memo at the same time with the government-issued ID card or passport.


QUESTIONS：

1. Please introduce yourself. Please let me know which social media I can contact.

2. Please introduce your organization. And what is your role in the organization?

3. How did you find out about the file coin network and file plus?

4. In what area are you going to use DataCap?

5. Please introduce the data you want to store using DataCap.

6. How many storage providers will use DataCap to store data?

7. Do you have any storage providers around you that you know or are working with? Please let me know if you have any.

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. First of all, the Client’s Filecoin address is required to be disclosed for us to closely monitor after the DataCap allocation.  Moreover, we will keep our eyes open on such Client’s storage orders placed from time to time (especially for verified deals) and relevant storage providers. 

2. We will set up a Client rubric mechanism that scores the Clients with varying trust.  Among others, the more diversified the Client allocates its granted DataCap, the higher scores the Client will get.  The Client may get bonus score if deploying less than 30% DataCap to any storage provider while it will suffer score deduction for deploying ≥70% Datacap to any storage miner for a period of time.

3. Audits - both external and internal audits will be conducted throughout the data deployment process. The community members are encouraged to take part as the external auditor to expose any Client’s over-concentration on Datacap allocation. We as a team also have many internal resources we can leverage at the Company.

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we will make the assignment decisions public where possible Github customers have applied for the DataCap. 

We plan to use e-mail, Telegram, Slack , etc. if we need to make a decision based on the private data required for verification of the customer.

```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
(1) Publicly accessible record management plan

Github : https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues

Website: https://filplus.info/

(2) Private record management

We plan to encrypt and store private customer verification data in the cloud and disclose the necessary data in the event of an objection or dispute.

```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
At least 10h+ per week
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
N.A.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None
```

**Comment by Kevin-FF-USA** [comment]
Hi @Xalanii,

Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Please email NOTARYELECTION@FIL.ORG from the email account linked to this GitHub account. *The email MUST COME from the same GitHub account you used in this application.

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Confirm that you are NOT applying on behalf of the organization Charles Schwab or using their reputation-and that you are applying only as an individual.
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to this GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Kevin-FF-USA** [comment]
Hey @Xalanii ,
See that you updated from ORGANIZATION to INDIVIDUAL.  Did you wish to update/remove the references to Charles Schwab from other areas of your application.  We wont be able to consider anything from that organization and must score based on your Individual categories.

**Comment by Xalanii** [comment]
Hi Kevin,

Thanks for the email. We can keep it as Individual. Thank you.
________________________________

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by Xalanii** [comment]
Hi, what are the next steps for me? Thank you.
________________________________

**Comment by Kevin-FF-USA** [comment]
@Xalanii 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
