### ISSUE TITLE
Notary Application: Vogo Networks 

### ISSUE THREAD

**Issue by achnir97** [filecoin-project/notary-governance#686]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Nirmal Acharya 
- Affiliated organization:  Vogo Networks Inc.
- On-chain address to be notarized (recommend using a new address): f1a7a2z4lcjuyz6lryexsbxh7rjqoqmmhn7e2fz5i
- Country of Operation: South Korea
- Region of Operation: Asia minus GCR
- Use case(s) to be supported: education, entertainment, and E-sports [E3-data], scientific datasets, historical documentaries of public importance & public data. 
- DataCap requested for allocation (10TiB - 1PiB): 1PiB 
- Are you applying on behalf of yourself or an organisation?: Individual
_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).

```
-Operating data mining facility with data center since 2021 Feb.
-FILECOIN sealing Performance Test Project with AMD Ryzen PRO, Threadripper, and EPYC CPU-Powered system
  (https://www.amd.com/system/files/documents/vogo-networks-accelerates-content-distribution-with-amd-cpus.pdf)
-IPFS R & D lab experimenting with technologies based on powergate, Estuary that has played crucial role to lessen the difficulties of boarding data on Filecoin network.
- Miner id f01624021, f01918123 
-Registered miner in Estuary tech list. 
-github: https://github.com/achnir97
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
NA
```

How did you acquire the FIL cited above?
```
NA
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
-participated in Seoul Storage meet up organised by PL on September 2022 and presented our road map of expanding distributed data storage services collaborating with multiple stakeholders and making it reach greater scale. 
-have tested lotus client, indexer and boost with hands on experience and daily interaction in Filecoin community in Slack to be updated about new changes in technologies. 
- contributed to update the lotus documentation taking reference of errors that i discovered while surfing the lotus client daemon.
link:https://filecoinproject.slack.com/archives/CPFTWMY7N/p1664871309053249?thread_ts=1664415789.131329&cid=CPFTWMY7N- 

-have already published filbytes.com that makes api call from filfox.com and render real time chain data of miner with customisation based on our need and demand of our investor. link: http://www.filbytes.com 
 
-currently, we working on a project called pinbytes.com where we will be creating a platform for CDN services that will play an important role for the client to store and retrieve E3 (education, entertainment and e-sports) data which will be fundamentally based on IPFS and Filecoin. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
NA 
```

### Organizational Reputation
Please describe the nature of your organisation, including the country of registration, size of the organisation, and time since inception.
```
-based in Seoul, South Korea. 
- inception of data centre in 2021 February. 
- IPFS research and Development Lab. 
- Strong team of competent and professional Engineers with full capacity and ability to handle software and technical issues. 
- Leading storage provider with 40TiB sealing capacity per day. 
- running the Saturn L1 test node and IFPS server contributing to retrieval market in Filecoin Network. 
```

Please share any relevant details to help substantiate information about your organisation (website, named officers, links to social media profiles).
```
- broader presence in distributed storage network and have provided the enormous data storage service. 
- working with multiple stakeholders and partners to store their data and develop the software system based on their needs and demand. 
- cater CDN services based on IPFS and Filecoin with multiple Edge servers. 
- active laision role between Filecoin technologies and local community by facilitating the information in local languages. 
- onboarding process for possible collaboration with ESPA to bring it to South Korea and beyond. 
- our webpage is as follows: http://www.vogogrp.com 

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
AMD had done case study about our mining facility where we have installed computing power with enormous speed for fast sealing 
of data which is the core necessity of data onboarding process in Filecoin network.
link: https://www.amd.com/system/files/documents/vogo-networks-accelerates-content-distribution-with-amd-cpus.pdf
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
linkedin: https://www.linkedin.com/in/nirmal-acharya-242a08120
Telegram: achnir 
DIscord: Nirmal Acharya#8231
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
NA
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Our allocation plan will be distinctive based on who client who had received data cap previously and new client who are applying for the first time. 
- survey with rigorous method for the legal verification of client with cross check online through website, zoom meeting, their past status and past use cases. 
- meticulous analysis on Client's proposal for their uses cases and future storage plan. 
- taking into consideration of time sensitivity, we will allocate the data cap with due diligence with in 1 week client request after client meets all standards and requirement. 
```

How do you plan on securing the DataCap to ensure your organisation (and its delegated members) are the ones allocating the DataCap?
```
I will use an offline wallet(ledger) in order to secure the verified notary address with dat cap. 
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Review of the applicant with relevant information, including the year of registration, industrial influences etc.  No boundaries in questions but we will focus on the following:
- team/personal/Company introduction
-In what way you are involved in file coin community and if any contribution and significant difference you have made to the             community, explain us in detail with reference links/ sources.
-elaborate us in detail about the past data cap received (if any) and use cases with reference?
-how much datacap do you want, and why?
-explain your long term needs of the data storage and current needs.
- how will you allocate your datacap?
- how will you make us assure the absence of data cap waste?

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Since filplus.info easily gives us the information if a client has only made deals with a single SP or not,  so to make sure deals are not made within a single SP, we plan to work with other notaries and cross check with them on a regular basis and assure the  decentralize of data cap with fairness. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be conducted on public (GitHub Repo) https://github.com/filecoin-project/filecoin-plus-client-onboarding ). 
```
Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We will book keep all the record of data allocation decisions on GitHub and google spreadsheet so that  public can have access and raise a question in any circumstances, and we will be ready to answer in all occasions with justification when challenged or dispute. 
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
-we will commit to level 5 of service commitment with regular basis of 1 video call on every 2 weeks. 
-active and effective response in slack within 1 day. 
-prompt response on github issues and comments. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
NA
```

## Disclosures
Do you/your organisation have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
NA
```

**Comment by achnir97** [comment]
> **Thanks for your request!** ❗ We have found some problems in the information provided. We could not find any answer to: **Are you applying on behalf of yourself or an organization?** in the information provided
> 
> ```
>     Please, take a look at the request and edit the body of the issue providing all the required information.
> ```

I have updated the information as suggested. Thank you for the feedback.

**Comment by achnir97** [comment]
I updated as individual.

**Comment by achnir97** [comment]
> **Thanks for your request!** ❗ We have found some problems in the information provided. We could not find any answer to: **Are you applying on behalf of yourself or an organization?** in the information provided
> 
> ```
>     Please, take a look at the request and edit the body of the issue providing all the required information.
> ```i have updated the information as an individual.

**Comment by achnir97** [comment]
Can you clarify in details?
I have updated the information.

**Comment by achnir97** [comment]
@galen-mcandrew  I would be grateful if you can have a look on why bot is giving me the same issue even if updated the information.

**Comment by Kevin-FF-USA** [comment]
Hi @achnir97,

Hello ______,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Please email NOTARYELECTION@FIL.ORG from the email account linked to this GitHub account. *The email MUST COME from the same GitHub account you used in this application.

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization or Self name
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[686.pdf](https://github.com/filecoin-project/notary-governance/files/10159415/686.pdf)

**Comment by achnir97** [comment]
> 

<How will you remain separate?>
I am not involved in Storage provider section of the Vogo Networks but has been fully independent Software Developer building Web application for the company.  My main motive of applying notary is to contribute to Filecoin network from the skills that I carry and make an impact for Filecoin to reach greater scale.  With the full understanding of the platform and possibilities it carries, I remain as separate individual regardless of me working in the company. 
If working in company stops somebody from being qualified as notary, I completely understand. 


<How will you commit to not engaging in signing of the same issues/applications?>
On behalf of the issue that comes forth behind, I remain as an invidual and carry the sole right under that norms and conditions to be followed  by the notary incase I am selected. Since all the allocation  will be done with full transparency and publishing in public records will assure that I will not be engaging in signing of the same issues/application.


Finally I will commit in the SLA portion.

**Comment by Kevin-FF-USA** [comment]
@achnir97 
Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
