### ISSUE TITLE
Notary Application: Tianji Studio

### ISSUE THREAD

**Issue by liyunzhi-666** [filecoin-project/notary-governance#687]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Bailey-li
- Affiliated organization: Tianji Studio
- On-chain address to be notarized (recommend using a new address): f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
- Country of Operation: Greater China Region (GCR)
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: Professional Services (Hosting Reseller, Long-term Backups, Data Warehousing), Developer Tools (Package Managers, Automatic Notaries, Web2 to Web3 integrations), Decentralized Applications, User Content (Personal Storage), Public or Open Data (Scientific datasets, research data, government or historic, Media & Entertainment (Videos, photos, NFTs)
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
GitHub handles: @metagates-dev（former name@Grandhelmsmen）
slack handles: @Patrick-li
- Participated in Trusted Setup Ceremony Phase 1 https://github.com/arielgabizon/perpetualpowersoftau/blob/master/README.md
- Participate in the first phase of the testnet that started in December 2019, ID: t019125, and the final storage capacity exceeds 1PiB
- PB-scale Miner Testing,E-mail submitted the relevant test plan,the email was sent to the Filecoin team, and Filecoin team members like @why @keren knew about it https://github.com/filecoin-project/devgrants/blob/master/rfps/rfp-pbscale-miner-testing.md
- Selected as a member of Filecoin Security Research Fellowship by Filecoin team,@why is one of the organizers, he can prove it https://security.filecoin.io/
- Participated in Trusted Setup Ceremony Phase 2 https://filecoin.io/blog/trusted-setup-complete/
- Participate in HackFS, the project is called Filecoin123 https://hack.ethglobal.co/showcase/filecoin123-recBa27E4zfpHRRln
- Participated in Space Race, and finally ranked 22nd in the world (name: Five Star-Helmsman&Heiben) Miner ID: t03176 https://spacerace.filecoin.io/
- Participated in the slingshot competition, project name: 1. Starry sky in Yunnan 2. Filecoin-Crawl
- Participated in Slingshot-Phase 1 Closing Ceremony https://www.youtube.com/watch?v=qheNJZ1DClM&list=PL_0VrY55uV19nu6orLLCaGCGocsjvpiGZ&index=1
- Participated in Trusted settings for V15 network upgrade https://filecoin.io/blog/posts/trusted-setup-complete-for-network-v15-upgrade/
- Joined  China SPWG
- Round 3 Notary
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Until November 8, 2022
The total Address Balance is about 408917.2957 FIL
The total Initial Pledge is about 357292.9556 FIL
The total Power is about 50.25 PiB
Details can be found in the statistics here：https://github.com/liyunzhi-666/picture/blob/main/IMG.png

```

How did you acquire the FIL cited above?
```
Mainly to provide storage services, block rewards, competition rewards.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- Participated in Trusted Setup Ceremony Phase 1 https://github.com/arielgabizon/perpetualpowersoftau/blob/master/README.md
- Participate in the first phase of the testnet that started in December 2019, ID: t019125, and the final storage capacity exceeds 1PiB
- PB-scale Miner Testing,E-mail submitted the relevant test plan,the email was sent to the Filecoin team, and Filecoin team members like @why @keren knew about it https://github.com/filecoin-project/devgrants/blob/master/rfps/rfp-pbscale-miner-testing.md
- Selected as a member of Filecoin Security Research Fellowship by Filecoin team,@why is one of the organizers, he can prove it https://security.filecoin.io/
- Participated in Trusted Setup Ceremony Phase 2 https://filecoin.io/blog/trusted-setup-complete/
- Participate in HackFS, the project is called Filecoin123 https://hack.ethglobal.co/showcase/filecoin123-recBa27E4zfpHRRln
- Participated in Space Race, and finally ranked 22nd in the world (name: Five Star-Helmsman&Heiben) Miner ID: t03176 https://spacerace.filecoin.io/
- Participated in the slingshot competition, project name: 1. Starry sky in Yunnan 2. Filecoin-Crawl
- Participated in Slingshot-Phase 1 Closing Ceremony https://www.youtube.com/watch?v=qheNJZ1DClM&list=PL_0VrY55uV19nu6orLLCaGCGocsjvpiGZ&index=1
- Participated in Trusted settings for V15 network upgrade https://filecoin.io/blog/posts/trusted-setup-complete-for-network-v15-upgrade/
- Joined  China SPWG
- Round 3 Notary
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
We have submitted a lot of bugs that can help Filecoin improve its security. Here are some bugs
filecoin-project/rust-fil-proofs 
a sanity check failed of window post haven't catch.
https://github.com/filecoin-project/rust-fil-proofs/issues/1308
The ability to read files in parallel is required when window post occurs
https://github.com/filecoin-project/rust-fil-proofs/issues/1281
Suggest to add more sector information in case of fault.
https://github.com/filecoin-project/rust-fil-proofs/issues/1261

filecoin-project/lotus
it's very slow to called `lotus-miner info` when the sectors number is 
over 10000.
https://github.com/filecoin-project/lotus/issues/3913
miner attempting to prove commit over 200 sectors in epoch
https://github.com/filecoin-project/lotus/issues/3638
Some new deals from storage markets have append to a old sector which one have a 
invalid deal.
https://github.com/filecoin-project/lotus/issues/3594
It seems have a dead lock in messagepool when push message.
https://github.com/filecoin-project/lotus/issues/3115
`lotus state wait-msg` can not wait the `mpool replace` messages.
https://github.com/filecoin-project/lotus/issues/2943
invalid proof (compute error?): failed to fill whole buffer
https://github.com/filecoin-fivestar/lotus/issues/71
How can i get a rpc error return when define a chan response in rpc call?
https://github.com/filecoin-project/go-jsonrpc/issues/14
Suggest adding IP output of client to log when JWT Verification failed.
https://github.com/filecoin-project/lotus/issues/1870

Participated in Trust & Transparency WG
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Tianji Data was established in Shenzhen, China, and the team was established in 2018. Since its establishment two years ago, it has been committed to the ecological construction of blockchain. Its products include DappOnline, TJWallet, Filecoin ecological construction, etc, we are the best data service provider and distributed storage solution provider.
DappOnline is the world’s leading blockchain ecological application store. It uses “DApp big data + DApp application + blockchain ecology” as the framework. Information, evaluation, analysis, recommendation, etc. can all be consulted. It is loved by many users all over the world;
TJWallet is another product of Tianji Data. It provides a one-stop digital asset management solution with a dual ecological guarantee of “software wallet + hardware wallet”, which fully combines the security of hardware wallets and the ease of use of software wallets. 
Software wallets can manage blockchain assets with one click, and provide BTC, ETH, TRX, Filecoin, ACL, and all ERC20, TRC10, TRC20 and other digital asset transactions and transfers and other fullchain asset management; hardware wallets act as flash drives and Offline storage of the user’s blockchain private key, the full name is offline disconnection operation, the private key will not leave the hardware wallet, the entire transaction verification process is completed in the hardware wallet itself. The encrypted currency stored in the wallet remains offline and cannot be hacked.
TJWallet is the first digital wallet tool in the 2020 star project IPFS/Filecoin ecosystem that supports F1/F3 full-chain full-function transaction transfer.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://dapponline.io/
https://tjwallet.net/
https://twitter.com/DappOnline
https://twitter.com/TJ_Wallet
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://dapponline.io/
https://tjwallet.net/
https://twitter.com/DappOnline
https://twitter.com/TJ_Wallet
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter 
https://twitter.com/DappOnline
Follower:4574

https://twitter.com/TJ_Wallet
Follower:1697
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
Slingshot-Phase 1 Closing Ceremony（project name: 1. Starry sky in Yunnan 2. Filecoin-Crawl）
https://www.youtube.com/watch?v=qheNJZ1DClM&list=PL_0VrY55uV19nu6orLLCaGCGocsjvpiGZ&index=1
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
After a few months of working as a notary, I think this plan is doable
Define thresholds with different levels of trust.The higher the requirements, the stricter the review：
Several important factors:
- Reputation of the applicant organization
- Is there any contribution to the Filecoin ecosystem (not necessarily a factor, but it will be a bonus item)
- Scale of allocation
- Assigned rating
- Safety Precautions
- Customer transparency
The type of data applied for (the public data set will be given priority)
The specific distribution plan can be viewed in the Google shared table：https://docs.google.com/spreadsheets/d/1AsAyaW1mV-eKyaqLWWTIAsaWHf24YNCriinHc-naJrs/edit?usp=sharing
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
It will be up to me to sign the DataCap. The Ledger hardware will be kept by the people on our team responsible for security, and the signature distribution DataCap will be done by me. Because this may involve some interest issues, this matter cannot involve multiple people. Other members of my organization can participate in notary meetings and review of previous materials and data samples.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In order to ensure the fairness and justice of DataCap distribution, we have formulated separate online and offline application procedures based on the number of DataCap applications and individual and corporate users.
For individual users:
We will review their Github registration years (180 days at least) to prevent malicious application bots. The amount of approval will also be controlled below 5 TiB.
For business users:
We have developed different review methods and requirements based on the number of their DataCap applications.
If it is less than or equal to 20 TiB, we will use online review. The following points will be reviewed.
• Business license
• Enterprise authorization letter (CEO's signature + seal)
• All shareholders who account for more than 25% of the total number of shareholders must provide ID cards or passport photos.
• Sample data submission (accounting for 0.2% of its total DataCap requests)
If the application is larger than 20 TiB, we will add offline comments based on online surveys (visit customers on business trips or invite them to our company).
Enterprise business type
• data source
• Data volume (monthly)
• What companies think about Filecoin
• Data storage plan
Question:
Please introduce yourself and your personal information on social media (official website, WeChat, LinkedIn,, GitHub).
• What is the purpose of your application for DataCap?
• Please provide the wallet address you want to apply for DataCap
• Please provide the quota of Datacap you want to apply for.
• Please provide the name of the organization, nationality, country of registration, time of registration, name of the executive, and relevant website (if you are an institutional user).
• Please provide the region where you want to use DataCap, if it is more than one region, please pay attention.
• How many miners do you plan to distribute DataCap to, if there are specially designated miners, please pay attention.
• Have you assigned DataCap before? If so, please provide details.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
With the help of these tools (https://filplus.d.interplanetary.one/clients
https://pluskit.io/home, https://www.atpool.com/en/dataCap/myIndex/customer, https://metawave.info/#/, https://filecoin.tools/) first investigation. If in doubt, I will raise it in GitHub or slack channel.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, I will publish these records in the GitHub repo. For the sake of transparency and fairness, I do not intend to send them via email or telegram.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
I intend to keep records of allocation decisions and make these records public in the GitHub repo. I will respond to all review requests
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L5: >8 hours of engagement per week, averaged monthly

- In the third round of Notary work, I have participated in three working groups: Notary WG, E-Fil+ WG, Trust & Transparency WG.
- I attend bi-weekly meetings of these working groups. For meetings that conflict with my time, I will also review the meeting recordings.
- Participated in some working group proposal comments or votes (these are all available on GitHub).
- Approval signed 76 LDNs (https://filplus.d.interplanetary.one/notaries/f01841196/ldn-activity)
- At the same time, someone in slack DMed me to ask about FIL+, and I will actively reply and guide them on how to participate in FIL+. These replies are basically within 24 hours.

```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
In the third round of notary work, I got a DataCap quota of 1PiB, but no one from Greater China asked me to apply for DataCap.https://github.com/filecoin-project/notary-governance/issues/453
But I approved and signed 79 LDNs. （https://filplus.d.interplanetary.one/notaries/f01841196/ldn-activity）
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None
```

**Comment by liyunzhi-666** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceddm375nn7hnrlnpdkgq3pvwehzszm7vlcois7c354ourcp2wfbua
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddm375nn7hnrlnpdkgq3pvwehzszm7vlcois7c354ourcp2wfbua

**Comment by Kevin-FF-USA** [comment]
Hi @liyunzhi-666,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by liyunzhi-666** [comment]
hey @Kevin-FF-USA  @panges2 , I want to clarify here that our organization uses .dapponline as the mailbox suffix for one of our projects.
<img width="502" alt="image" src="https://user-images.githubusercontent.com/52949274/204585523-438d0f5e-b523-47d9-9abb-8ae1d6f5b127.png">

**Comment by liyunzhi-666** [comment]
Dapponline integrates some applications in the Filecoin ecosystem https://dapponline.io/dapp
cc @raghavrmadya 
![image](https://user-images.githubusercontent.com/52949274/205193450-2a861e05-8f3f-4982-b984-fdb3249d6cdb.png)

**Comment by liyunzhi-666** [comment]
The wallet(TJWallet) we made also supports Filecoin transfer, and you can also directly access these Dapps through our wallet https://en.tjwallet.net/
Welcome T&T WG to download and check.
cc @raghavrmadya 
![image](https://user-images.githubusercontent.com/52949274/205194110-afe8ab37-7c48-4c29-87d1-ae6dd4d65f83.png)

**Comment by liyunzhi-666** [comment]
I sent the relevant email on November 24th, but have not received the token code until now. Can you guys check again? @Kevin-FF-USA  @panges2

**Comment by raghavrmadya** [comment]
T&T flag removed based on further evidence provided by applicant

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[687.pdf](https://github.com/filecoin-project/notary-governance/files/10159418/687.pdf)

**Comment by Kevin-FF-USA** [comment]
@liyunzhi-666 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by liyunzhi-666** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebka5fe7tfri3vooh7viwyfmhmsqje4sbtdafwvn42kby5ahryy7k
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebka5fe7tfri3vooh7viwyfmhmsqje4sbtdafwvn42kby5ahryy7k

**Comment by liyunzhi-666** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecp7weophs4ncjnjbhoglfentrtflccqfeb7is3usanxgd7it2zbm
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecp7weophs4ncjnjbhoglfentrtflccqfeb7is3usanxgd7it2zbm

**Comment by liyunzhi-666** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaced5znfndzodzw6xspz7tdwnnnmjaudwaswb5yvmy4uptmknnokzei
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5znfndzodzw6xspz7tdwnnnmjaudwaswb5yvmy4uptmknnokzei

**Comment by liyunzhi-666** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceaph7grkcfftlhyayhloy4crtbf4dimihc25ypjkeerjwrjal6e5u
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaph7grkcfftlhyayhloy4crtbf4dimihc25ypjkeerjwrjal6e5u

**Comment by liyunzhi-666** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedc4ci5ztymol7rztxxeeftpqzc75zzaagl7cbbhle6sv3jqva5bi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedc4ci5ztymol7rztxxeeftpqzc75zzaagl7cbbhle6sv3jqva5bi
