### ISSUE TITLE
Notary Applicaiton: TP Labs - OC

### ISSUE THREAD

**Issue by devtplabs** [filecoin-project/notary-governance#688]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: TPLABS
- Affiliated organization: TPLABS.
- On-chain address to be notarized (recommend using a new address): f1s33dcyfb4s2pmg4de5d44fjp4wbu6kfsuapekii
- Country of Operation: Singapore
- Region of Operation: Greater China & Asia minus GCN
- Use case(s) to be supported: Web2 / Web3 business data,including but not limited to Scientific Data, Media & Entertainment,etc.
- DataCap requested for allocation (10TiB - 1PiB): 10TiB
- Are you applying on behalf of yourself or an organization?: Organization

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Over the past two years, the TPLabs R&D and operation team has been committed to promoting the development of the Filecoin ecological project in the field of Web3 infrastructure.
The R&D team with dozens of people has provided reliable services in key technical architectures such as lotus persistent storage and PoST. The solutions is delivered to community partners (SPs, developers) to assist in the construction of super-large (>100PiB+) storage nodes to ensure the stable and reliable operation of customer business data systems,
which are still working well until now.
At present, TPLabs is willing to invest more customer resources and technical service capabilities, focus on the construction and development of IPFS/Filecoin data ecology, and focus on promoting ecological prosperity and development through data computing and storage.

More information as bellow:
- Github: https://github.com/tplabsio
- SP_IDs: f01936456,f01111112,f022277
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f01936456 (29,003.3639 FIL)
f01111112 (312,539.2192 FIL)
f022277 (47,695.3278 FIL)

Total : 389,238 FIL
```

How did you acquire the FIL cited above?
```
Most of FILs comes from participating in FIL project 、the investment of partners.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
TPLabs is involved in the development of the Filecoin community ecosystem with substantial help:
- Around August 2020, the first partner to deliver a distributed storage solution for IPFS/Filecoin,including storage architecture, data security, storage migration, disaster recovery and other multi-storage solutions.
- As of today, TPLabs provides high performance, reliable and stable permanent storage solutions for over 100+ storage providers, with an estimated total computing power of over 5 EB+, effectively supporting the stability of Filecoin's underlying infrastructure.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
We have optimized and enhanced the data access control, data reliability, transmission security and other aspects compared with the file system storage.
- Data access control layer: The file system implements data access control based on IP or user name, which is extremely vulnerable and insecure. At the data access control level, we store and verify the credentials of each access request, and use AK and SK as the upload, download and management credentials to eliminate security risks.
- Data reliability layer: Most SPs do not take any redundancy measures in data storage to save hardware costs. The data which users storaged are suffering great security risks. We pool the storage resources through software, and achieve data redundancy through EC model algorithm, which greatly improves the data fault tolerance.
- Transmission layer: SSL encrypted data transmission, white list strategy, anti-theft chain mechanism, etc. are used to ensure link security. 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
TECHPARALLEL (TPLabs) was established in 2021 with offices in Singapore, Hong Kong and Mainland China, we are committed to be a Web 3.0 infrastructure and platform technology service provider with the following main business lines.
- We provide products and solutions for large scale storage and computing clusters with high throughput and low latency storage capabilities, and continue to expand the global data storage and distribution node construction.
- Multi-chain computing-related decentralized application services, including: dAPIs, scenario-based, intelligent audio and video processing, edge computing, data rendering, etc.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website:https://www.tplabs.io/
Email:hi@tplabs.io
Twitter: @tplabsio
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.tplabs.io/.
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter: @xioliwe,@tplabsio
https://twitter.com/tplabsio/status/1590528424002871296
https://twitter.com/tplabsio/status/1590957469010128898
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://www.tplabs.io/.
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The purpose of assigning DataCap to the FIL+ project is to ensure that customers are using these DataCap to store real and valid data correctly, so we will use the DataCap evaluation model to rate customer reputation, evaluate and assign their DC requirements on a scale of Level 1 to level 5,
The specific ratings can be viewed at the following link:
https://tplabsio.sharepoint.com/:x:/s/IPFSFIL/EVRqFxiPqKxMux3CbFoIcjEBwHHwOz4KZ35G_Umxa28dMg?e=jVMZC3

In addition, we use rules and vetting schemes to determine the true identity of the applicant and the real business scenario: 
- Visit the applicant's official website for information about the company entity and, more importantly, to confirm the real business scenario and data types, attributes, etc.
- Check the company's registration information from the relevant government websites to ensure that the information submitted is true and valid.
- Based on the results obtained from the evaluation model, the applicants are classified according to their industry reputation and size to determine the amount of data they will receive.

These evaluation systems are designed to increase the level of consistency in all aspects of the applicant.

The entire application process should be open and transparently presented (application records, Github communication, etc.), but we will also use some internal review processes as necessary.

- A junior reviewer will conduct a basic information review of the application submitted by the customer. The applicant's data storage must also be open, valid data and have real business storage requirements.
- Based on the results of the basic review, the primary reviewer will again conduct a detailed investigation of the company's business ecology to further understand whether the business model is reasonable and whether the data is real, and finally forward the review process sheet to the review director.
- Once the reviewer's decision is approved and signed, DataCap will allocate a certain amount of money to the client. If the review is not approved, the client will be notified of the results.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The hardware wallet will be better solution to store the private key to ensure the security of the account. After being reviewed by our internal decision makers, the data caps will be allocated to applicants by those who have the right to execute the hardware wallet.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In order to ensure the fairness and impartiality of DataCap distribution, regarding the authenticity and reputation of evaluating client information, we will adopt the following methods for review:  

Online information analysis:  
- Require third-party information provided by the client, such as social media accounts and observe the activity of the account. If there is a Github account, evaluate its activity.
- Search and view the official website of the client company to learn about the company's history, news, ecology and product services.
- Check on the enterprise information website of the customer's country/region
- Use the team's official email to confirm whether the client is applying for a Data Cap, and confirm its identity information and work information.  

Entity/Business Information:
- Require clients to provide business registration, establishment documents, public registration information and relevant certificates.
- Ask clients to provide sample data they want to store and we will check that their data is valid and publicly available.
- Ask the client to provide information about the actual business, including but not limited to the business situation introduction and business model description related to the sample data, who the final customer is, whether the data has ownership, etc.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will use the following process to ensure that clients do not improperly use previously granted DataCaps:
- Use technical solutions to monitor clients addresses, and require clients to regularly close transaction information for data analysis and tracking.
- If a clients is found to be over-allocating its available DataCaps to any single entity, we will communicate with the clients and issue a warning and, if it recurs, suspend allocating the remaining DataCaps.
- Introduce an audit mechanism, conduct an audit plan with internal and external assistance within the team throughout the data deployment process, and encourage community members to questions as an external assistance method. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be conducted publicly in the Github repository to ensure community impartiality,meanwhile,conduct in-depth communication through the slack channel.(filecoin-plus-client-onboarding).
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Online sheet to store records,and make it restricted access,if needed, We will open authorization to visitors. It will be here: [https://tplabsio.sharepoint.com/:x:/s/IPFSFIL/ESsPmCGyTW9OmFCpt2AKdj0BXF6-Vv2srtBkYAs-Ij8Bhg?e=BheMUs]
Additionally, without disclosing any sensitive information about our customers, our team is happy to answer reasonable inquiries that community members may have about our DataCap allocation decisions.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
We prefer leval 2. 
To make sure around 2 hours per week on average,including:
- participating in the FIL+ and making allocations.
- will also attend in governance calls and discussions in slack. 
- Participate in the compute over data projects..
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Not yet, it's our first time to apply notary.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
Not yet.
```

**Comment by Kevin-FF-USA** [comment]
Hi @devtplabs,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by devtplabs** [comment]
Sure thing, Thanks so much ,Kevin~

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[688.pdf](https://github.com/filecoin-project/notary-governance/files/10159420/688.pdf)

**Comment by Kevin-FF-USA** [comment]
@devtplabs 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.

**Comment by devtplabs** [comment]
@Kevin-FF-USA  
Thanks Kevin , would you like to share more details that why we won't be chosen for reasons? or we should improving points in the future? 
Thx.
