### ISSUE TITLE
Notary Application: ByteBase

### ISSUE THREAD

**Issue by swatchliu** [filecoin-project/notary-governance#689]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Eric
- Affiliated organization: ByteBase
- On-chain address to be notarized (recommend using a new address): f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
- Country of Operation: People’s Republic of China
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: Professional Services, Public or Open Data, Media & Entertainment, Developer Tools, Decentralized Applications, User Content 
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer! _

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects, or contributions (with links).
```
1.	2022.10 - The first private data use case in Greater China Region supported – Project Beacon.
2.	2022.06 - ByteBase became the R3 notary of the Filecoin community in the Greater China region.
3.	Uses the Filecoin Network to Keep a Competitive Edge in the Photo Sharing Industry”
4.	2022.01 – Power Dealer launched, to improve the sealing capability of verified deals for SPs
5.	2021.01-12 - ByteBase has developed the "ByteBase Data Storage Platform" based on the storage provider's hardware. The platform utilizes the IPFS protocol to provide individuals and enterprises with more cost-effective distributed data backup services.
6.	2021.07 - ByteBase became the R2 notary, 98.6TiB DC was allocated, and More than 25+ hours per week working on the Filecoin community.

GitHub handle    swatchliu
Slack handle     ByteBase
```

### Stake Exposure
Please cite the total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on a chain with their corresponding FIL amounts).
```
f1mckc25zndr6xw5lkwxo3zuxlqqms3yj2zst3otq 803FIL
```

How did you acquire the FIL cited above?
```
Company Purchased
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
ByteBase Milestone 

•  June 2019, ByteBase set up the project Filecoin storage
•  April 2020, Elvis and the other 2 developers set up the company prototype.
•  Nov. 2020, after 6 months of learning with Filcoin network and IPFS architecture, Bytebase start their storage system from 0.1-0.5 version
•  Dec. 2020 Bytebase officially registered, a total of 27 employees.
•  March 2021, beta version 1.0 was launched, and 8 enterprises became the core users and participated in the experience.
•  April 2021, the official version is launched, and nearly 50 companies have partnered with ByteBase to continuously store information about IT, entertainment, healthcare, and the arts in the Filecoin network.
•  July 2021, became the R2 notary of the Filecoin community in the Greater China region.
•  Sep. 2021, ByteBase Gateway launched, helping storage providers upload user data into the Filecoin network
•  Jan. 2022, Power Dealer launched, to improve the sealing capability of verified deals for SPs
•  Jun. 2022, ByteBase became the R3 notary of the Filecoin community in the Greater China region.
•  Oct. 2022, the first private data use case in Greater China Region supported – Project Beacon.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Filecoin Plus project terminology definition proposal
https://github.com/filecoin-project/FIPs/issues/159 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
ByteBase was registered and established in Shanghai in 2020. ByteBase is a leading platform solution provider based on IPFS and blockchain storage in China.

Currently, there are nearly 100 team members, mainly focusing on system development, mainly from Alibaba, Huawei, Tencent, UCloud, and other traditional Cloud service manufacturers.

ByteBase was incorporated in Shanghai in 2020. ByteBase is a leading domestic platform solution provider based on IPFS and blockchain storage.
At present, there are 20 team members, mainly from traditional cloud service providers such as Alibaba, Huawei, Tencent, and UCloud.
The company developed the “ByteBase Data Storage Platform” to facilitate Web2 users to upload data into the Filecoin network. The company has also developed the “ByteBase Gateway”, which is convenient for storage providers to quickly distribute and seal verification data all over the world. This year, the company upgraded the gateway to becoming a Power Dealer. A brand new “go file market” component was rewritten with go-lang, it fully used the multicore of the modern CPUs to improve the efficiency of PieceCID calculation and transformation of CAR files.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
website: https://www.bytebase.cn/ 
WeChat: 冰塔数科 
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://mp.weixin.qq.com/s?__biz=Mzg2MjU1OTU5Nw==&mid=2247484644&idx=1&sn=77d5e9953ffddaf5614dda1e5c09f23b&chksm=ce0748e6f970c1f033083431926d866476657a3789c8a1e95ed991639637dda21956918e4c78&token=1825079802&lang=zh_CN#rd  

https://mp.weixin.qq.com/s?__biz=Mzg2MjU1OTU5Nw==&mid=2247484677&idx=1&sn=ce76264010236f4e02a21ee07dcbc924&chksm=ce074907f970c01111e9357eb8c66872af25c3f09545266003c4a5d7b5aba75106062f71ac8f&token=1825079802&lang=zh_CN#rd  

https://mp.weixin.qq.com/s?__biz=Mzg2MjU1OTU5Nw==&mid=2247484648&idx=1&sn=831fa086d1e431ab30ee8bd776c9e692&chksm=ce0748eaf970c1fc04c67b2f618846850d4629ba01e229d18471944351608658e5dab1ccfa24&token=1825079802&lang=zh_CN#rd  

https://mp.weixin.qq.com/s?__biz=Mzg2MjU1OTU5Nw==&mid=100000953&idx=2&sn=9d2459775d523c8eb64aa9cf49383f42&chksm=4e0748bb7970c1add6295c8b8533df7362ef8c6171b277434b1ae64046cff593d3c574e9b6a3#rd  

https://mp.weixin.qq.com/s/s3gg3WeZMhIfJuUgQaOgaA  

https://mp.weixin.qq.com/s/lZsBlJdBejmGh3mYnqv_HQ  

https://mp.weixin.qq.com/s/YYxAiofLEC6Pt_sg9RTyHg  
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Linkedin https://www.linkedin.com/in/%E9%A2%82%E5%B9%B3-%E6%B1%AA-753885201/  

WeChat Official Account: 冰塔数科, 155 articles, 418 subscribers

```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://mp.weixin.qq.com/s?__biz=Mzg2MjU1OTU5Nw==&mid=2247484644&idx=1&sn=77d5e9953ffddaf5614dda1e5c09f23b&chksm=ce0748e6f970c1f033083431926d866476657a3789c8a1e95ed991639637dda21956918e4c78&token=1825079802&lang=zh_CN#rd  

https://mp.weixin.qq.com/s?__biz=Mzg2MjU1OTU5Nw==&mid=2247484677&idx=1&sn=ce76264010236f4e02a21ee07dcbc924&chksm=ce074907f970c01111e9357eb8c66872af25c3f09545266003c4a5d7b5aba75106062f71ac8f&token=1825079802&lang=zh_CN#rd  

https://mp.weixin.qq.com/s?__biz=Mzg2MjU1OTU5Nw==&mid=2247484648&idx=1&sn=831fa086d1e431ab30ee8bd776c9e692&chksm=ce0748eaf970c1fc04c67b2f618846850d4629ba01e229d18471944351608658e5dab1ccfa24&token=1825079802&lang=zh_CN#rd  

https://mp.weixin.qq.com/s?__biz=Mzg2MjU1OTU5Nw==&mid=100000953&idx=2&sn=9d2459775d523c8eb64aa9cf49383f42&chksm=4e0748bb7970c1add6295c8b8533df7362ef8c6171b277434b1ae64046cff593d3c574e9b6a3#rd  

https://mp.weixin.qq.com/s/s3gg3WeZMhIfJuUgQaOgaA  

https://mp.weixin.qq.com/s/lZsBlJdBejmGh3mYnqv_HQ  

https://mp.weixin.qq.com/s/YYxAiofLEC6Pt_sg9RTyHg 
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We have developed a set of scoring criteria for clients to apply to DataCap, which has been uploaded to Google Docs.
https://docs.google.com/spreadsheets/d/1VEdGP0m03d0nrqzqWikOINzOe3wa_WLx-a6Ij73Ydxc/edit?usp=sharing

On our platform, we have developed and integrated the Filecoin DataCap application process in our official website: http://www.bytebase.cn/

We also provide an online form for clients to submit application information.
Link: https://www.wenjuan.com/s/qAVFfuN/
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A Ledger will be used to store the keys associated with the DataCap allocation address securely. 
4 people will be 2 teams, one keeps the GitHub account and one keeps the Ledger access.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In order to ensure the fairness and impartiality of DataCap allocation, we have developed separate online and offline application processes according to the number of DataCap applications and individual users and corporate users.

For individual users:
we will review their GitHub registration years (minimum of 30 days) to prevent bots from malicious applications. The amount of approval will also be controlled below 0.5TiB.

For corporate users:
We have developed different review methods and requirements depending on the number of their DataCap applications.
If it is less than or equal to 20TiB, we will adopt an online review. The following points will be reviewed.
•  Business license
•  Enterprise power of attorney (CEO signature + seal)
•  Data sample submission (0.2% of their total DataCap request)

If the application is larger than 50TiB, we will add an offline review (business trip to visit customers or invite them to ByteBase) based on the online survey method. There are:
•  Enterprise Business Type 
•  Data sources
•  Data volume (monthly)
•  Enterprise perceptions of Filecoin 
•  Data storage plans
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. Audit the DC via statistics from https://filplus.d.interplanetary.one/  or [www.filfox.info](http://www.filfox.info/) 
2. Applicants are required to distribute DataCap to at least 3 or more SPs, which will increase storage redundancy and help maintain decentralization and reduce the potential for misuse.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, Both.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
1. GitHub repo
2. https://www.bytebase.cn/#/dashboard 
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
I would like to be an L5 Notary.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
https://github.com/filecoin-project/notary-governance/issues/419
https://github.com/filecoin-project/notary-governance/issues/169  
```
## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
Fenbushi is one of our stakeholders, they don’t participate in our managerial decision-making in any manner.
```

**Comment by Kevin-FF-USA** [comment]
Hi @swatchliu 

Thanks for (re)applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by swatchliu** [comment]
> Country of Operation

Email sent, Thanks @Kevin-FF-USA & @panges2

**Comment by swatchliu** [comment]
> Hi @swatchliu
> 
> Thanks for (re)applying to become a Notary in the Fil+ program!
> 
> As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. *This cannot be from your personal account. You Must include the address of your Organization.
> 
> Subject Line: Notary Name, Application Number Email Body:
> 
> Your First and Last name Your Organization Your Country of Operation Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/) Link to this GitHub application
> 
> This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.
> 
> Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2
> 
> Thank you!

Email sent, Thanks @Kevin-FF-USA & @panges2

**Comment by swatchliu** [comment]
> Hi @swatchliu
> 
> Thanks for (re)applying to become a Notary in the Fil+ program!
> 
> As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. *This cannot be from your personal account. You Must include the address of your Organization.
> 
> Subject Line: Notary Name, Application Number Email Body:
> 
> Your First and Last name Your Organization Your Country of Operation Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/) Link to this GitHub application
> 
> This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.
> 
> Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2
> 
> Thank you!

Waiting for the token code, Tks

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[689.pdf](https://github.com/filecoin-project/notary-governance/files/10159421/689.pdf)

**Comment by Kevin-FF-USA** [comment]
@swatchliu 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to continue as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by swatchliu** [comment]
> @swatchliu Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to continue as a Notary in this 4th round of elections.
> 
> In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in https://plus.fil.org/ as well as outline the best practices and responsbilities for a Notary in the Program.
> 
> Next steps
> 
> 1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
>    
>    1. https://airtable.com/shrjx52lvefitwdq6
> 2. **By 30 December** - Ensure that the Governance meeting time is on your calendar and make scheduling plans which allow you to commit to attending per your SLA level expectations. (L1-L5)
> 
> Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

 CONTACT AND DISCLOSURES form completed.

**Comment by swatchliu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceayoachjalwz2jize7n44vxksh7o36ebh5rt4mb26u6s4gqwd4swk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayoachjalwz2jize7n44vxksh7o36ebh5rt4mb26u6s4gqwd4swk

**Comment by swatchliu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecpcbib247ka2ofckl4wq5zchr7iskaqg7i5q7ydbs7h6wos65d6e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecpcbib247ka2ofckl4wq5zchr7iskaqg7i5q7ydbs7h6wos65d6e

**Comment by swatchliu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebujceyjdhk23o52s6ottvbljetq5abpj5tsvzdzrstaf6wogptxk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebujceyjdhk23o52s6ottvbljetq5abpj5tsvzdzrstaf6wogptxk

**Comment by swatchliu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceachejpfz3mmfsiuuitahklakugsxrv7tfvilpiarktydllwhyab2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceachejpfz3mmfsiuuitahklakugsxrv7tfvilpiarktydllwhyab2

**Comment by swatchliu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceab55gecnxttiwou4fxfrskddc2nnj56yjzzww7td7nutmu6vydds
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceab55gecnxttiwou4fxfrskddc2nnj56yjzzww7td7nutmu6vydds

**Comment by swatchliu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacednpoy2x2yihy6gjkzybbfqtgjqmrl72kk3mixzbozg2eddbuects
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednpoy2x2yihy6gjkzybbfqtgjqmrl72kk3mixzbozg2eddbuects

**Comment by swatchliu** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecch3xho4nq4awpdg2gxpux5aznd5ybk7t2sagm6xugpurohqhu7a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecch3xho4nq4awpdg2gxpux5aznd5ybk7t2sagm6xugpurohqhu7a
