### ISSUE TITLE
Notary Application：DAYOU

### ISSUE THREAD

**Issue by DaYouGroup** [filecoin-project/notary-governance#690]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:Eunice
- Affiliated organization: BigFrog Technology
- On-chain address to be notarized (recommend using a new address):f1w2jy6trpxrs34sjnnzzzdi457vzwqngrmluv2oa
- Country of Operation: HongKong
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: Public or Open Data,Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
BigFrog Technology is a blockchain team established in 2017, focusing on project investment and Bitcoin mining. And after the ICO of FILECOIN, I paid attention to it, and also did some research and publicity about FILECOIN.

Many of the core members of the BigFrog team are early Bitcoin evangelists. They have worked in the encryption field for more than eight years, participated in the investment of projects such as ETH in the early stage, and have experience in exchange platforms.

Since 2019, members of BigFrog Technology have used DAYOU to contribute to the filecoin network for a long time; at present, DAYOU has a strong brand influence in the Chinese community; it has been popularizing the filecoin ecology for the community for a long time, so that more people can understand and enjoy filecoin; we have been committed to To be a high-quality SP, we have served more than 60,000 customers through DAYOUAPP (https://www.dayou8.com/), and currently contribute more than 80Pib of storage space to filecoin.

In the past two years, nearly 1,000 articles about FILECOIN have been published in GCR's traditional media (Wechat: Dayou IPFS Research Institute) to promote FILECOIN.

DAYOU under BigFrog has been focusing on the ecological development of Filecoin technology and the establishment of more storage providers since its inception, and plans to allow more users to enter the Web3/Metaverse through distributed storage technology. In the future, we will focus on developing a series of ecological applications to serve the vast number of Internet users, such as distributed storage cloud disk, Filecoin staking, distributed tiktok, etc.

Some promotional links:
https://bytecj.com/news/detail/691.html
https://bytecj.com/news/detail/326.html
https://bytecj.com/news/detail/301.html
http://www.qqcjzk.com/news/2352.html
https://finance.ifeng.com/c/8KlbIn7X3KM
https://mp.weixin.qq.com/s/JfFRa3MNsTPm_5OpV5rg7g
https://mp.weixin.qq.com/s/ulNpG16f4MpjRhu8zlJQRg
https://mp.weixin.qq.com/s/BLRF-SJbnzIWRhluZdrzMA
https://www.jinse.com/writings/1591462.html
https://www.jinse.com/writings/2209427.html
https://bytecj.com/news/detail/101.html

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
As of today, we have a total of over 500K Filecoin tokens.
f01132569
f01169722
f01545883
f01852193
f01860256
f01865864
f01942420
f01942425
```

How did you acquire the FIL cited above?
```
It is mainly the proceeds from the company's business development and some institutional borrowings.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
1. Nearly 1,000 articles about FILECOIN have been published in the past two years (Wechat: 大有 IPFS 研究院).
2. Wechat media will hold online promotions every week to help users better understand the progress of FIL, etc.
3. We use DAYOU to promote filecoin externally and popularize filecoin in multiple social media.
https://bytecj.com/news/detail/691.html
https://bytecj.com/news/detail/326.html
https://bytecj.com/news/detail/301.html
http://www.qqcjzk.com/news/2352.html
https://finance.ifeng.com/c/8KlbIn7X3KM
https://mp.weixin.qq.com/s/JfFRa3MNsTPm_5OpV5rg7g
https://mp.weixin.qq.com/s/ulNpG16f4MpjRhu8zlJQRg
https://mp.weixin.qq.com/s/BLRF-SJbnzIWRhluZdrzMA
https://www.jinse.com/writings/1591462.html
https://www.jinse.com/writings/2209427.html
https://bytecj.com/news/detail/101.html
4. We develop DAYOU Staking products（ https://www.dayou7.com/financial） to enable customers to participate in filecoin network construction with extremely high liquidity and flexibility.
5. We are testing the retrieval network combined with filecoin and IPFS. After the preliminary completion, we will broaden source of our code on github.
6. Everyone can quickly and easily become an SP through the DAYOU APP.
7. To incubate fil’s ecological development and provide financial support, BigFrog established an ecological fund in 2018 (https://bytecj.com/news/detail/152.html).
8. Investment incubation filecoin cloud disk (expected to be launched in 2023Q1, prototype drawings can be submitted).
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N.a.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Organization: BigFrog Technology
Nature:  private company
Registration Country: Hong Kong
Established: 19 Sep, 2019
Size: over 80 employees
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://www.dyfil.com
App:https://www.dayou8.com
Twitter：[@wuHr10](https://twitter.com/wuHr10)
Wechat：@Rich--Blockchain__Ci
Wechat：@wuhr_online
Wechat：@DayouCici
Telegram：[@Frogbt_Global](https://t.me/Frogbt_Global)
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
http://www.qqcjzk.com/news/2352.html
https://finance.ifeng.com/c/8KlbIn7X3KM
https://mp.weixin.qq.com/s/JfFRa3MNsTPm_5OpV5rg7g
https://mp.weixin.qq.com/s/ulNpG16f4MpjRhu8zlJQRg
https://mp.weixin.qq.com/s/BLRF-SJbnzIWRhluZdrzMA
https://twitter.com/wuHr10
https://t.me/Frogbt_Global
https://www.jinse.com/writings/1591462.html
https://www.jinse.com/writings/2209427.html
Wechat：@Rich--Blockchain__Ci
Wechat：@wuhr_online
Wechat：@DayouCici
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Personal social media:
Wechat：@Rich--Blockchain__Ci (6000+follwers)
Wechat：@wuhr_online (25000+follwers)
Wechat：@DayouCici (11000+follwers)
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://www.jinse.com/writings/1591462.html
https://www.jinse.com/writings/2209427.html
http://www.qqcjzk.com/news/2352.html
https://finance.ifeng.com/c/8KlbIn7X3KM
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We will conduct a completed KYC audit of the customer, and we believe that we should collect the following information to confirm the authenticity of the customer:
1. Basic information
- Physical documents (company registration information, certificates, etc.)
- Certificate number issued by the government
2. Signature information / authorization document
Evidence that authorizes the signatory to act on behalf of the entity
3.Authorized person information
- Name
-Personal identification code (ID card / social security number / passport number)
- Street address
4.Customer profile, use case
Customers should provide a detailed introduction to the use of DataCap, including an introduction to entity information, examples of use cases, customer's geographic location, requested quota, copyright notice, etc
After completing the information review, we will assign it according to the customer rating. You can see our grading system here:
https://docs.google.com/spreadsheets/d/1DqlnvdacUfiLDb6LR0p7hxUiP7iKjlLe/edit?usp=sharing&ouid=114674816332909266997&rtpof=true&sd=true
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will use hardware wallets for DataCap-related accounts, and monitor and audit DataCap usage.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 
In the early stage, all clients are required for an onboarding process to be qualified. 
Firstly, I need to collect information including:  
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information. 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name.
 - street address (P.O. box number is not acceptable). 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence. 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 
 With these provide, an interview and data source checking process need to go through. After that, an agreement should be signed for the next step - gradually allocate datacap and let the client gather more credit. 

The questions will cover the following areas that to ensure the DataCaps are properly allocated:

1.Introduction of yourself/ your organization (with links);
2.Use case examples and scope;
3.Geographic location of the client;
4.DataCap Allocation Requests Amount;
5.Filecoin On-Chain Address;
6.Declaration of Copy rights and Legal Compliance Requirements;
7.Specific requirement of miners and storage service
Nature Of Business (Government, Public, Private, NGO)
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
First of all, we establish an allocation schedule for each customer so that we can continuously track and monitor it. If the customer does not allocate DataCap, we will impose penalties through mechanisms such as deduction, reduction of quota, blacklist, etc.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes. We are open to any audit request from private and public channels.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Yes. We will use github repo to make allocation decisions and keep records.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
We will have one full-time employee(40 hours/ Week) responsible for communication and DataCap management. We have chosen the L5 level of service commitment.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
We have not allocated DataCap. As SP, we used two nodes f01942420 and f01942425 to receive a total of about 1024Tib of DataCap.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No other associations.
```

**Comment by Kevin-FF-USA** [comment]
Hi @DaYouGroup,

Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by DaYouGroup** [comment]
> Hi @DaYouGroup,
> 
> Thanks for applying to become a Notary in the Fil+ program!
> 
> As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. *This cannot be from your personal account. You Must include the address of your Organization.
> 
> Subject Line: Notary Name, Application Number Email Body:
> 
> Your First and Last name Your Organization Your Country of Operation Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/) Link to this GitHub application
> 
> This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.
> 
> Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2
> 
> Thank you!

Hi @Kevin-FF-USA ,We have sent an email to NOTARYELECTION@FIL.ORG and updated the github link of slack, please confirm if you received it.

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[690.pdf](https://github.com/filecoin-project/notary-governance/files/10159422/690.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi @DaYouGroup,

I'm unable to locate the email verification that you sent. Can you please fwd the response you sent for verification or paste the token code you may have received in a response from Phil or myself?  Appreciate the additional verification.

**Comment by DaYouGroup** [comment]
> Hi @DaYouGroup,
> 
> I'm unable to locate the email verification that you sent. Can you please fwd the response you sent for verification or paste the token code you may have received in a response from Phil or myself? Appreciate the additional verification.

Hi, I have sent the email again and I am pasting the content of the email here.
First and Last name：  Eunice Zhao
Organization：  BigFrog Technology
Country of Operation：  HongKong
Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/) Link to this GitHub application：My Slack account: [dyglobal@dyfil.com](mailto:dyglobal@dyfil.com), joined filecoinproject.slack.com
, and the GitHub address has been added to the personal information https://github.com/filecoin-project/notary-governance/issues/690

**Comment by Kevin-FF-USA** [comment]
Hi @DaYouGroup,
The labels are linked to the core information in the top section of the application. Whenever an application is modified, it will remove the labels (which we then re-add) so that there is an indication the application was modified. The bot will then rescan.  *I'll re-add shortly

**Comment by Kevin-FF-USA** [comment]
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. **After re verifying you identity.** A review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections.  

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in https://plus.fil.org/ as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

    By 20 December - Complete the CONTACT AND DISCLOSURES form
        https://airtable.com/shrjx52lvefitwdq6
    By 30 December - Ensure that the Governance meeting time is on your calendar and make scheduling plans which allow you to commit to attending per your SLA level expectations. (L1-L5)

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.
