### ISSUE TITLE
Notary Application: moonlight233

### ISSUE THREAD

**Issue by moonlight233** [filecoin-project/notary-governance#691]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: moonlight233
- Affiliated organization: self-employed
- On-chain address to be notarized (recommend using a new address):f3vh3igpzhyytstih3gwyyhqrwq63jqhm4c5wnouklfl66zedg5pixlzgmbnwitisaldev7z3acqnfvm2zdkta
- Country of Operation: Greater China Region (GCR)
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: Web 2.0 Applications,Web 3.0 / Decentralized Applications, Scientific Data
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: [Individual, Organization]
Individual
_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
1. Participated in Filecoin as SP since Space Race with minderID f02654. 
2. Engaged in Space Race and Slingshot 
### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
Around 3000Fil staked and available in Storage Provider.  (f02654, f0161916)
How did you acquire the FIL cited above?
Around 3000Fil available from the exchange.

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
1.Engaged in Space Race and Slingshot. (f02654, f0161916)

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
 Stay active in Github and Slack, including file bugs, and answer questions of what I know. (ID:moonlight233)

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
Does not apply. My interaction with Filecoin so far is personal behavior. I will set up an organization if there is a need. 

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
N/A

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
N/A

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
twitter:https://twitter.com/Web3HealingClub

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
N/A

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
My allocation goal is to ensure I grant eligible clients the appropriate amount of DataCap and with smooth onboard into Filecoin. Authenticity,  allocation fairness, client's correct usage of DataCap are the key. 

Authenticity :
1. Verify the client's basic information, including operation's registration of place and time, Business license, operation size, and industry reputation. 
2. Investigate the total amount of requested data, data type, the previous storage method, and whether it is open public or encrypted. 

Allocation fairness:
1. I am open to reviewing the application from all the regions and various data types. 
2. I will not allocate more than 30% of DatCap to the same client. 

Client usage of DataCap: 
Make sure the client has a clear, feasible plan on data generation, ways of deal-making, and SP selection from a big pool. 
If it is not the client's first-time allocation, I will refer to the client's previous DataCap consumption and ensure the deal-making is not heavily made to few SP. I will also randomly retrieve the deal to confirm the requested data is stored into Filecoin. 

Allocation Speed:
I plan to allocate 50% of DataCap within half a year. 

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
A ledger that can only be accessible by me.

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
1. Ask the client to provide the fundamental introduction to the business entity, including but not limited to the operation size, operation year, registration country, operation regions, reputation in its industry, Business License, and any social media page. 
2. Explain the relationship between the Datacap Requester and the Business.   
3. Describe the type of the data, and provide a sample. 
4. Elaborate on the plan to onboard into Filecoin. Familiarity with deal sending?  Do you send online deal or offline deal?  Any tools you plan to use to prepare the data?  How do you find the SPs? How do you allocate your DataCap among SPs? How many copies do you intend to store?  Which geo-location will you onboard the data? 
5. Do you run an SP on your own?  If so, what percentage you plan to store yourself. 
6. Plan to avoid the DataCap waste. 

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
Check client address on https://filplus.d.interplanetary.one/ to make sure the usage of DataCap is not heavily used in one SP. 

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
Yes, I will document the supporting details on the decisions I make with each client in public through Github. 

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
Github and email.

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
L5.

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
No.

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
SPACE ID
Halo nft
martian wallet
BNB chain

**Comment by Kevin-FF-USA** [comment]
Hi @moonlight233,

Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Please email NOTARYELECTION@FIL.ORG from the email account linked to this GitHub account. *The email MUST COME from the same GitHub account you used in this application.

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[691.pdf](https://github.com/filecoin-project/notary-governance/files/10159423/691.pdf)

**Comment by Kevin-FF-USA** [comment]
@moonlight233 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
