### ISSUE TITLE
Notary Application: Bit Engine 

### ISSUE THREAD

**Issue by Bitengine-reeta** [filecoin-project/notary-governance#692]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Reeta
- Affiliated organization: Bit Engine Pte Ltd
- On-chain address to be notarized (recommend using a new address): f1ckboubyaqhk7wslrd2pgvbykf5eekkwpk4kpb5a
- Country of Operation: Singapore
- Region of Operation: [North America, South America, Europe, Africa, Greater China Region (GCR), Asia minus GCR, Oceania] Asia minus GCR
- Use case(s) to be supported: [Please select from [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries)] Professional Services, Developer Tools, Decentralized Applications, User Content, Public or Open Data, Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: [Individual, Organization] Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```

1. Bit Engine has joined the world of Web3 and the blockchain industry for more than ten years. Tomi Wen, the founder of our company, is also a pioneer in the blockchain industry. The company has been researching IPFS technology since 2016, and has been involved in constructing Filecoin node and researching technology since 2019. There are part of some minerIDs we operated for nearly 2 years, such as f081977(20/11/2020),f081978(20/11/2020),f081979(10/8/2021),f081986(3/9/2021),f081995(27/7) /2021), f0408629 (16/3/2021), etc.
2. Tomi Wen founded "Beijing Digital Engine Technology Co., Ltd." in Beijing in 2009, which is the predecessor of Bit Engine Singapore, and received tens of millions of financing from China's top venture capital firms. That company focused on Web3 and blockchain markets. The DBXChain was created in 2016 by their team, and the ecological applications on this public chain use IPFS as the underlying storage technology. [https://github.com/dbxone/dbxchain](url)
3. In 2019, Beijing Digital Engine began to develop the Web3 business with IPFS and Filecoin as the underlying storage technology, and set up a professional technical team to help the development of IPFS and Filecoin ecological technologies. They helped to develop Voodfy, a decentralized video platform based on Filecoin. They did a ot of contributions to the development of the underlying technology of that project. [https://github.com/Voodfy](url)
4. Company founder Tomi moved to Singapore in 2021 and founded Bit Engine Pte Ltd. Since then, all of the company's businesses have been operating in Singapore. At the same time, we hope to develop a wider business in Singapore and have a brighter future in the field of distributed storage.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
total: 118,121fil
f081977：46,382fil
f081978：12,967fil
f081979：7,168fil
f081986：6,555fil
f081995：13,578fil
f0408629：12,736fil
f01741924：3,338fil
f01771695：7,115fil
f01753006：5,237fil
f01782338：3,045fil
```

How did you acquire the FIL cited above?
```
Through block rewards and buying from exchanges. 
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```

1. As a web3 company, Bit Engine has been committed to the development of blockchain technology and ecology since its inception. Our company started to construct Filecoin nodes as early as 2019, and has been paying a lot attention to the development of distributed storage. At the same time, we are really interested in the Fil-plus project that encourages real data storage, and we hope to join the fil-plus to become a notary and contribute to community governance.
2. At the same time, as FVM is about to be released and the technical conditions are approaching maturity, our company has also started to build the FilDeFi project. With more and more small investors getting involved in Filecoin, we hope to construct a smart contract to coordinate all stakeholders. And to integrate resources and share the benefits in an open and transparent way duuring the lifecycle of a node.  [https://docs.google.com/document/d/1e0fHstbofxBZuffeW23L5JZ25DAUXStqylfUa0afGQs/edit?usp=sharing]
3. At present, we are also developing a decentralized Filecoin offline wallet, which is a digital wallet with fully functions, such as creating and importing wallets for clients to manage Fil private keys and addresses, tracking account balances, scanning codes to sign for messages, creating multi-signatures, withdraw cash, and querying the upchain information, etc.
4. Reeta, a member of the company, participated in the notary governance call actively, hoping to take these opportunities to be close to the official and get more communicateions with the official to follow up on the latest developments in the community, and help promote the Fil-plus project in Singapore and other parts of Asia.
5. Reeta actively participates in community communication on the slack channel, helping to answer community governance, notary application and some technical questions. She also keeps a close eye on the Datacap application in the Fil+ channel to learn the clients due diligence plan and distribution plan of excellent notaries,hoping to play a greater value in the follow-up community governance.   Slack: @bitengine-reeta [https://app.slack.com/client/TEHTVS1L6/search/search-eyJkIjoicmVldGEiLCJxIjoiVTA0NjJMWUFFRTUiLCJyIjoicmVldGEifQ==/thread/CRK2LKYHW-1665441857.759369](url)
6.  We also actively pay attention to new proposals in the GitHub community, follow up and learn official news, and actively post comments to help participate in community governance. At the same time, we pay close attention to the ecological growth of filecoin and hope to participate more in it.  Github: @Reeta [https://github.com/Bitengine-reeta](url)
7. We spread information about web3, metaverse, IPFS, and filecoin on public media, and lead tens of millions of fans to understand and enter the world of Web3.  [https://twitter.com/mometaio](url)
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```

1. Bit Engine focuses on the advanced next-generation blockchain infrastructure technologies, namely MemChain (ultra-ecologically friendly PoW blockchain infrastructure) and MoMeta (metaverse infrastructure), and has developed a large number of ecosystems applications based on IPFS/Filecoin storage technology. Such as MoMeta Marketplace, a smmart contract for NFT trading. It can offer a rich and colorful immersive virtual reality experience, where people see, hold and buy like reality. Also, it supports all mainstream wallets and could access major NFT trading platforms together with our own platform to serve multiple transaction protocols.  We also launched MoMeta DAO Launchpad, which is a token-based credible voting tool on proposals with onchain and offchain voting technology. It is also a decentralized community treasury co-management smart contract for representatives and authorization. Besides, it also can be a toolbox of honors and incentives based on Metaverse user behavior data. Our existing ecological user base exceeds one million people. Currently, Bit Engine is receiving pre-listing counseling by HSBC, and the listing target is the Singapore Stock Exchange.
8. Tomi, the founder of Bit Engine, is an experienced IT entrepreneur who has been deeply involved in the blockchain industry for many years. He established Beijing Digital Engine Technology Co., Ltd. in 2009 and served as CEO. This company is considered to be the longest-lived entity company in the blockchain world and the predecessor of Bit Engine Singapore. Since then, Tomi started his blockchain business. As a serial entrepreneur, Tomi led the team to develop multiple blockchain products, including DBXChain, trading platform, decentralized data storage applications, NFT tools and markets, etc. , to provide technical services to global customers, and these products also use IPFS/Filecoin storage technology. In addition, as a practitioner and pioneer in the cryptocurrency industry, he has been building Bitcoin nodes since 2011. Due to his outstanding contributions to the blockchain industry, he and the CEO of Huobi were awarded the "Outstanding Blockchain Individual Award" presented by Jim Rogers. In addition, he is also promoting the development of the blockchain industry around the world. In 2018, he accepted an interview with CCTV "focusing on the blockchain", and popularized blockchain for the entire Chinese people. He also taught blockchain courses in the EMBA program of the Renmin University of China Business School and gave a speech at the University of California, Los Angeles (UCLA).
9. Bit Engine made successful acquisition of two professional Web3 construction teams: Shenzhen Toploong Technology Co., Ltd. and Shenzhen Interplanetary Storage Technology Co., Ltd.. Toploong is a high-tech enterprise established in 2000, which integrates sales and service of industrial control chassis, server chassis, portable computer and special computer accessories. In 2020, Toploong and Interstellar Storage, as the leading distributed storage server manufacturer in China, will be invited to participate in the "Web3.0 China Summit and Distributed Storage Industry Conference". Looking forward to the bright future of Web3.0 online, this conference is the largest IPFS and distributed storage industry event with the largest number of people and the highest specifications held in China so far. At the same time, Toploong has been paying attention to the development of distributed storage ecology for many years. So, it provides technical and equipment support for tens of thousands of enterprises developing ecology in the field of IPFS and Filecoin. It also participate in its ecological construction actively. It constantly accumulates, explores, practices and innovates, looking forward to the early arrival of the WEB3.0 era. Interstellar Storage is a company that focuses on the development of blockchain technology, and builds a globally distributed cloud database based on IPFS technology.
10. As the promoters of the Web3 industry, Tomi and Bit Engine will continue to actively carry out the popularization of industry knowledge, and will focus more on IPFS and Filecoin to output various analysis reports for the industry, and hold more industry events, etc. We also believe that with our years of experience in the blockchain industry, we will be able to help and support more clients to grow and develop in the Web3 industry.
Registered and operation country: Singapore
Organizational scale: 16 people in the core team, 55 people in total
Beijing Digital Engine Technology Co., Ltd. was established on 28th September, 2009
Singapore Bit Engine was established on 9th November, 2021
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: [https://www.mometa.io/](url)
Twitter: [https://twitter.com/mometaio](url)
Interview with Tomi Wen: [https://mq.mbd.baidu.com/r/P9WqKEXoKk?f=cp&u=de16be70db605292](url)
Tomi won "Outstanding Blockchain Personality Award" presented by Jim Rogers: [https://www.bightbc.com/action/59752.html](url)
Tomi gave a special lecture on "Blockchain Technology Application" for leading officials in Zhanjiang: [http://paper.gdzjdaily.com.cn/html/2019-02/27/content_160831_958936.htm](url)
CEO Muyuan(Tomi) Wen of DBXChain：[https://www.aicoin.com/article/62841.html](url)
Interview with the Tomi Wen founder of DBXChain: [https://tehmoonwalker.medium.com/interview-with-the-tomi-wen-founder-of-dbxchain-437047b46a25](url)
CCTV "Focus on Blockchain" interview Tomi Wen: [https://www.sohu.com/a/246320069_100244239](url)
Tomi talks about "All behaviors in the blockchain era are 'data exchange'": [https://mr.mbd.baidu.com/r/P9UZhN9tHW?f=cp&u=d9eaccd4ac890571](url)
Interplanetary storasge and Toploong participate in the Blochchain Distributed Storage industry Conference： [https://www.jinse.com/news/blockchain/1020598.html](url)
Toploong showed the strength at the Web3 China Summit and the Distributed Storage industry Conference： [https://www.toploong.com/index.php/Index/news/b/5/id/55/i/84.html](url)
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
DBXChain launched the first real estate blockchain landing project in China: [https://gu.qq.com/resources/shy/news/detail-v2/index.html#/?id=neuSN20190622230007b91aa5e4&s=b](url)
DBXChain complete the development of DBXVM：[https://www.blockex.ai/news/205559.html](url)
Interview DBXChain：[https://blockonomi.com/dbx-guide/](url)
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter:
[https://twitter.com/mometaio](url)（2.5k followers）
[https://twitter.com/DBXFoundation](url)（1.9k followers）
Facebook:
[https://www.facebook.com/profile.php?id=100066305514257](url) (8.9k followers)
YouTube:
[https://www.youtube.com/watch?v=XB8xdlzcE98](url) (50.8k followers)
[https://www.youtube.com/c/IcoInvestorOfficial/videos](url) （66.7k followers）
[https://www.youtube.com/c/MiningWorldEra/featured](url) （17.3k followers）
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
Pictures of interviews and awards of Tomi Wen： [https://docs.google.com/presentation/d/1mLalJmYKjeq6BuqS3bH6AKW5cMl7Ge57NOpAdMjXOgc/edit?usp=sharing](url)
Tomi Wen gave a speech at Stanford:  [https://www.facebook.com/watch/?v=570210706755068](url)
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The main purpose of allocating these DataCaps is to help store real and useful data that is beneficial to human development. Based on this principle, we will evaluate and allocate from various aspects, such as customer information, reputation, data information, and historical records. See this table for details:  [https://docs.google.com/spreadsheets/d/15HwSPTPkywwvsbP0q6Xxb-tJl-XRTcw6QEMgdRuIKWM/edit?usp=sharing](url)
Based on all the allocation strategies described in the above table, we plan to allocate no more than 20% of our holdings to each client, and each client can be allocated at most once a week.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will use hardware wallets to securely store keys associated with DataCap assigned addresses.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
The basic principles of our customer review are as follows:
1. For users who request more DataCaps, the restrictions on review will increase accordingly. For large-amount applications, we will add a jury to conduct in-depth investigations on the following basis to prevent malicious applications
2. Our initial distribution will be very small, and we will choose to increase or stop the distribution according to the usage of DataCap by the client. Our punishment measures may include canceling the applicant's certification qualifications, disclosing its wrong behavior in the community, permanently stopping further distribution, and pledging clients Filecoin fines, etc.
3. There are different review methods for individual users and corporate users to review
First of all, for individual clients: we will review their account registration time, account activity, account content review, and fan audience review. In addition, some third-party software, such as twitteraudit, can also help verify their identity.
Secondly, for enterprise clients: We will review the following three types of information: One is entity information, including establishment documents and registration certificates, and entity identification numbers issued by the government; The second is the information of the authorized signatory, evidence that the authorized signatory has the authority to act on behalf of the applicant entity (evidence includes written consent from the company’s board of directors, or certificate from the secretary, a signed letter from the applicant’s CFO, or may be included in the company’s operating agreement), and visible Passport or other ID photo; The third is the beneficiary information, if there are any shareholders above 25%, we need a document such as a capitalization form, operating agreement or similar document to verify ownership, and a passport or other ID photo that can prove personal identity.
Questions we will ask our clients:
1. Are you representing an individual or an organization? Please give a detailed self-introduction/unit-introduction, including organization name, nature, registration country, establishment time, official personnel information, etc. (attach media links that can prove your identity, such as official website, GitHub handles). It would be better if you can attach the honors and proof links of individuals/organizations.
2. What kind of data will you store? Please describe the data type and provide an example.
3. How much data do you intend to store? Is the data publicly available (and if not, can we do random spot checks at any time?)
4. How many miners do you plan to allocate to? Please indicate the storage location, miner ID and storage ratio of the data you want to store.
5. If you get a DataCap, do you agree to send the storage records back here within 15 days of storage?
6. Do you have DataCap? If yes, please attach all application links and advise current remaining amount.
7. Plan how to avoid the waste of DataCap?
8. Do you have specific requirements for miners and storage services?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We require that clients must distribute DataCaps to at least 4 or more SPs, and the number of DataCaps on one same node cannot exceed 30% of the total allocated DataCaps. At the same time, clients need timely feedback on their storage details.
We will track the clients' use of previous DataCap allocations using Fil+ specific dashboards like [https://filplus.d.interplanetary.one/ ](url) or [https://filplus.info/](url) .
After tracking the client's usage of DataCap, we will continue to ask some questions:
1. What's your use cases for our previous allocation, and could we take a look?
2. Do you have some problems while using your Datacap?
3. Do you have more request for the next allocation? Or is there anything we could improve to serve you better?
Through the initial small size of allocation and continuous follow-up investigation, if the client can use the DataCap as required, we will gradually increase the number of DataCap, otherwise, if it is used improperly, we will suspend the allocation.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we will publish our allocation on Github repo.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub repo
[https://filplus.info/](url)
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
We choose to be L5 notary, because there will be two full-time employees in our team who are responsible for the official docking of Filecoin to ensure at least 40 hours of notary governance work per week.
Their work as a notaries includes but not limited to: Learn the allocation plans and cases of excellent notaries to help companies better conduct customer due diligence and DC allocation, attend notary governance meetings, follow up or respond to customer inquiries on slack, join at least two fil+ related working groups, and follow up with the community Share comments and comment or vote on the most proposals within.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
N/A
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
N/A
```

**Comment by Kevin-FF-USA** [comment]
Hi @Bitengine-reeta,

Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Bitengine-reeta** [comment]
Hi @Kevin-FF-USA @panges2, I have sent an email as you required, please check. But we didn't revive the token code as you mentioned, is there anything wrong?
![Uploading DDFBFFB8-EF4A-48BF-88D0-D480AFDF590A.jpeg…]()

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[692.pdf](https://github.com/filecoin-project/notary-governance/files/10159427/692.pdf)

**Comment by Bitengine-reeta** [comment]
Hi @Kevin-FF-USA @galen-mcandrew , here we information we want to add through the continuous learning of these days, please check, thanks~
Allocation Plan
We have carefully read the responsibilities of being a notary again, and studied many previous cases of LDN application and allocation, and we hope to make further supplements to our previous allocation strategy:
1. Allocation principle: We will insist that the DataCap allocated for the first request is 5% of the total amount or 50% of the weekly allocation, whichever is smaller. In addition, we have also limited the amount of our initial allocation to between 1T and 100T, and determined the specific amount of our initial allocation based on various factors such as the authenticity and quality of customer information and data. The specific information is included in in this table: https://docs.google.com/spreadsheets/d/15HwSPTPkywwvsbP0q6Xxb-tJl-XRTcw6QEMgdRuIKWM/edit#gid=0
2. Data review before distribution: For the purpose of the Fil+ project to store real and valuable data, we will focus on data review to determine the authenticity and compliance of customer data in various ways. At the same time, we will focus on customers with high-quality data, and do our best to help them store their data in the Filecoin network to help the long-term healthy development of the Filecoin network. In this context, we have formulated a data review plan (the richer the data sample, the more support we can get). https://docs.google.com/spreadsheets/d/1OxRnuiSPGupW8J1hUzeiJSkzc21WGnSucwCyQUWxZ8E/edit?usp=sharing
3. Follow-up plan after allocation: After the initial allocation, we will promptly follow up the allocation of the customer's DataCap through tools such as filplus.info, and timely discover and control possible risks. For example, check whether the customer is allocated according to the allocation plan made by himself; whether the DataCap quota is allocated to different storage providers; whether the stored data meets the requirements, etc. At the same time, we will also follow up the customer's transaction after allocation in time to help them complete the project smoothly.
4. For verifiable customers, we will focus on the customer's allocation and use of the previously acquired DataCap. First, we will check the previous DataCap usage through https://filplus.d.interplanetary.one/ or https://filplus.info/ to judge their reputation. The higher the reputation, we will assign The ratio will increase accordingly. Secondly, we will ask to search and spot-check the data they have packaged. If their data is authentic and reliable, their credibility will be increased accordingly.
5. For the protection of private keys, in addition to secure storage through hardware wallets, all distribution decisions and signatures will be confirmed and executed by two full-time employees who are responsible for performing the duties of notaries, so as to prevent DataCap from being arbitrarily distributed.
Client Due Dilligence
First of all, since our company will arrange two full-time employees to be responsible for the role of notary public, we promise that we will respond to the customer's request for DC within 48 hours and start with due diligence.
Review process for new clients:
1. Ask questions one by one according to the questions in our application and ask for responses, and then sort out and judge their information.
2. The customer is required to send a confirmation email to the unified mailbox for KYB verification through the official domain name mailbox, and send a copy to the designated mailbox of all notaries. Paste the verification screenshot on GitHub for reference by other notaries.
3. Disclose the results on GitHub after completing the due diligence, avoiding the repeated due diligence process of the notary and improving the efficiency of customer onboarding. At the same time, disclose the reasons for your support before signing for reference by other notaries.
Review process for assigned clients:
1. The customer is required to provide the "CID" of the previously encapsulated data for data retrieval, and check whether the encapsulated data is consistent with the previous commitment and plan. After receiving the above information, we will conduct a sample check on the verified transactions sent by the customer on the chain, check the transaction CID, and retrieve it from the corresponding miner to verify the authenticity of the data. As DataCaps will be allocated in stages, if we discover any improper or fraudulent spending of allocated DataCaps, we may penalize customers by delaying or even canceling outstanding DataCaps.
2. Check the previously assigned DataCap usage history using the File Plus dashboard and tools. To increase network growth and Filecoin network reputation score, ensure no unfair or abnormal transactions, and store normal data. Also, to improve data storage and stability, it must be assigned to at least 4 different SPs. Use the following tools:
      https://filplus.info/
      https://filplus.d.interplanetary.one/clients
      https://pluskit.io/home
      https://www.atpool.com/en/dataCap/myIndex/customer
      https://metawave.info/#/
      https://filecoin.tools/
3. Finally, we will establish a corresponding reward and punishment mechanism. If a client over-allocates Datacap to a single entity, I will deny further allocations with a warning and disclose this behavior to the Filecoin community (e.g. on Slack, GitHub, or a governance call). Conversely, customers in good standing have the opportunity to receive more allocations of DataCap.
Bookkeeping Plan
1. As mentioned above, all our allocation decisions will be made public on GitHub, disclosing the results of our due diligence, screenshots of emails for KYC verification, and our reasons for supporting the application. Moreover, every approval will be saved on Github.
2. All conversations with clients conducting Datacap interviews and related documentation are recorded with the client's knowledge and kept securely for future audit.
3. If there is any dispute, open the discussion on the allocation decision on slack or github, or put the issue on the Notary Govenance call for discussion. We accept all audits and queries and will provide evidence we retain for the queries.

**Comment by Kevin-FF-USA** [comment]
@Bitengine-reeta 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by Bitengine-reeta** [comment]
Hi @Kevin-FF-USA , I update the on-chain notary address, please check.

**Comment by Bitengine-reeta** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceahxf62bfafz5lbohna3qlve6w4f3sp4n7guwceal3lci5m4dneny
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahxf62bfafz5lbohna3qlve6w4f3sp4n7guwceal3lci5m4dneny
