### ISSUE TITLE
Notary Application:NFTSTAR

### ISSUE THREAD

**Issue by NFTSTAR02** [filecoin-project/notary-governance#693]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Vivian
- Affiliated organization: NFTSTAR
- On-chain address to be notarized (recommend using a new address): f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy
- Country of Operation: North America
- Region of Operation: North America
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
The NFT collectibles minted and traded on the NFTSTAR platform will be stored on the IPFS and Filecoin networks to enhance the security of NFT products with decentralized storage technology;

As a bridge to promote fil to establish key strategic relationships in Asia, nftstar not only helps fil to promote geographical diversification, but also promotes the diversification of fil's usage scenarios in different fields. 

In addition, NFTSTAR also cooperates with Polygon and Filecoin development team Protocol Labs in GameFi projects
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
N/A
```

How did you acquire the FIL cited above?
```
N/A
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We were selected be the third round of Notaries. During that time, we actively participate in discussions and governance calls. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
The9 Limited (The9) is an Internet company listed on Nasdaq in 2004. The9 aims to become a global diversified high-tech Internet company, and is engaged in blockchain business including a Non-Fungible Token platform NFTSTAR. 
NFTSTAR is a NFT community and trading platform for users to purchase, trade, and interact. The major transaction contents of the platform are NFT collections developed with global superstar licensed IPs. Each NFT collectible has a unique record on the blockchain, and the users will obtain the ownership of the unique NFT collectible through purchase on the platform, or through trading on NFTSTAR’s marketplace. NFTSTAR will accept general payment methods such as credit cards to make it easy for global users to participate.
The NFTSTAR community platform will cover superstars in various fields, including but not limited to sports, entertainment, art and celebrities in different industries. NFTSTAR community platform aims to create a significant portal to the future metaverse through superstars’ NFT collections, trading, and community interaction.
NFTSTAR has announced several partnering stars including the NFL football star Christian McCaffrey, Portuguese football legend Luís Figo, Korean football star Son Heung-Min, and two-time NBA MVP winner basketball star Giannis Antetokounmpo and his three brothers. Until November 19, 2021, NFT community and trading platform NFTSTAR (www.nftstar.com) has proliferated to 180,000 pre-registered users from 176 countries. 
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
www.the9.com 
www.nftstar.com
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.jinse.com/lives/277720.html
https://www.jinse.com/lives/277875.html
https://www.jinse.com/lives/278557.html
https://m.chinaipo.com/news/199823.html
https://www.youtube.com/watch?v=2asn3jWTFOU
https://www.youtube.com/watch?v=E0Pl5_Ytb3c
https://www.prnewswire.com/news-releases/the9-limited-announced-its-nftstar-is-planned-to-be-officially-launched-on-december-17-global-pre-registered-users-exceeded-180-000--301428951.html
https://www.the9.com/cn/news-detial.html?act=new&articleId=579
https://www.panewslab.com/zh/sqarticledetails/1640090242566871.html
https://www.panewslab.com/zh/sqarticledetails/1637223737125297.html
https://www.panewslab.com/zh/sqarticledetails/1632373864135377.html
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter：https://twitter.com/THENFTSTAR（follower：64000）
Twitter：@ZHUTHE9（follower：6000）
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://linktr.ee/nftstar.official
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
In order to make more effective data to the network and make the data diverse and effective, the strategy we develop mainly depends on the data type. 
Firstly, data types will account for 40%.
We will judge data based on: 
//1, data type; 2, data rarity; 3, data volume; 4, future data storage capability //
Secondly, we will confirm whether the client is reliable and trustworthy, which will account for 20%.
The rules for client is similar to the process of reviewing notaries, but more rigorous:
//1.Organization basic information, 2.Github account, 3.association with Filecoin//
After confirming that the client is reliable, we will check whether the data description submitted by the client is consistent with the sample data they provided.
In the case that the two subjects are equally qualified with same score, the data that meets the requirements will be given priority for approval
The allocation strategy of customers will account for 40%,including //1.miners amount, 2.miners distribution 3.retrieval frequency 4.transparency//
The table of allocation strategy link: https://docs.google.com/spreadsheets/d/1DLR53Q6HmNJ3vm5J9M2zsN4fPa9i-z8d/edit?usp=share_link&ouid=116589947800312890681&rtpof=true&sd=true

After the first step of review is passed, and the datacap is allocated to client, we will continue to follow up, including
//The concentration of miner; the number of deals; whether to start storing in time...//
There will be another table as a standard for the track record as follows:
https://docs.google.com/spreadsheets/d/1JuUUZmbk52JnZmQLSviDOhapaMMLlpHH/edit?usp=share_link&ouid=116589947800312890681&rtpof=true&sd=true
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We have a cooperating company, Dark Shield, to do the custody of the hardware wallet, which can be sufficiently secure.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1.For the organizational client, we will conduct inquiries and audits through external process, such as: Twitter, LinkedIn. We will try our best to find out the contact information of the official contact person of the organization, and ask whether the organizational client has actually submitted the application. What’s more, Is there any blockchain relevance for organizational client? If yes, please provide proof?
In addition, for individual applicants, we will make public inquiries in Github, such as: Do you have enough knowledge about the FilPlus project? Where did you learn about this project? What are your thoughts on the entire ecology of Filecoin? etc. to ensure that the client is really wants to do something good for Filecoin.
2.We will confirm whether the client has potential miners. If there is, we will ask them to specify the number of miners and the distribution ratio; if the client passes the first step, we will monitor whether they conduct the right transactions according to the information submitted during the application in the subsequent allocation stage. After each application for DataCap is used up, we will ask the applicant to provide detailed usage description, including miner ID, storage ratio, timestamp, data content, etc., and conduct regular inspections based on the disclosed information.
Also, questions about allocation strategies will also be asked, like: Are there additional tools to ensure consistent allocation of transactions? Can it be public in network? Do you understand the principles of the ideal allocation strategy for the FilPlus project? If you understand, please give a brief overview.
If there are obvious exceptions, we will ask and warn through Github. In the next allocation stage, if it has not been fixed in time, it will be blacklisted by us and public to everyone, no longer cooperating.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will encourage customers to allocate Datacap to at least 5 miners to increase the decentralization of the network. If a client's allocation is too concentrated, we will issue a warning and ask them to explain why. If the customer fails to submit a good reason and continues to concentrate allocation, then we will reject the customer's next allocation request, and public the customer's application in the community to inform everyone that this customer is not trustworthy. Conversely, if a client's applications and allocations achieve the diversification we hope and actually increase the effectiveness for network, then their next application will be easier and they will get more credit.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We make all distribution records public and keep them continuously and updated to ensure everyone on the network can see them. And we welcome everyone to review our approvals. This will promote the improvement of network efficiency. At the same time, if necessary, we will also supervise the fairness of signatures with other notaries.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Both Github and web. Also will provide a google sheet for it.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L5
For the third round of notary, I have attend almost every governance call. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yep, https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/960
We are also work with PL team to do a case study.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
NDLABS 
We participate in the Filecoin network through the recommendation of NDLABS. Also as their client doing a case study program.
```

**Comment by Kevin-FF-USA** [comment]
Hi @NFTSTAR02,

Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[693.pdf](https://github.com/filecoin-project/notary-governance/files/10159429/693.pdf)

**Comment by NFTSTAR02** [comment]
Hello Team members @galen-mcandrew @Kevin-FF-USA @raghavrmadya 
I'd like to add the following information and hope this helps. 

_1. Time commitment_
As a wholly-owned subsidiary of Thenine, we will participate in the construction of the Fiecoin ecosystem from 2020.
Among them, we are very honored to be mentioned in the Filecoin 21-year review blog that NFTstar has established a strategic bridge for the Asian region. 
(https://filecoin.io/blog/posts/filecoin-orbit-filecoin-year-one-in-review/ )
quto from the blog: "Another notable initiative has been the promotion of geographical diversification from storage providers in China to other countries, as well as building key strategic relationships across Asia, such as NFTStar and more."

_2. Client due diligence_ 
For the organizational client：
1.we will conduct inquiries and audits through external process, such as: Twitter, LinkedIn. 
2.We will try our best to find out the contact information of the official contact person of the organization. 
3.ask whether the organizational client has actually submitted the application. 
4.Is there any blockchain relevance for organizational client? If yes, please provide proof?
In addition, for individual applicants: 
1.We will make public inquiries in Github, Questions are following:
2.Do you have enough knowledge about the FilPlus project? 
3.Where did you learn about this project? 
4.What are your thoughts on the entire ecology of Filecoin? etc. to ensure that the client is really wants to do something good for Filecoin.
We will confirm whether the client has potential miners. If there is, we will ask them to specify the number of miners and the distribution ratio; 
if the client passes the first step, we will monitor whether they conduct the right transactions according to the information submitted during the application in the subsequent allocation stage. 
After each application for DataCap is used up, we will ask the applicant to provide detailed usage description, including: 
*miner ID, storage ratio, timestamp, data content, etc., and conduct regular inspections based on the disclosed information.
Also, questions about allocation strategies will also be asked, like: 
1.Are there additional tools to ensure consistent allocation of transactions? 
2.Can it be public in network? 
3.Do you understand the principles of the ideal allocation strategy for the FilPlus project? 
4.If you understand, please give a brief overview.
If there are obvious exceptions, we will ask and warn through Github. In the next allocation stage, if it has not been fixed in time, it will be blacklisted by us and public to everyone, no longer cooperating.

_3. Bookkeeping Plan_
We make all distribution records public and keep them continuously and updated to ensure everyone on the network can see them. Github : https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues
Official Website: https://filplus.info/
And we welcome everyone to review our approvals. This will promote the improvement of network efficiency. At the same time, if necessary, we will also supervise the fairness of signatures with other notaries.
Both Github and web. we will keep the public GitHub records and a private chat via Slack or Telegram. All account name are "NFTSTAR"

**Comment by Kevin-FF-USA** [comment]
@NFTSTAR02 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @NFTSTAR02, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by panges2** [comment]
Hi @NFTSTAR02, I just want to remind you again to get your ledger verified as soon as possible. Thank you!

**Comment by NFTSTAR02** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedvjfau73krvpdhvuvmnorwa2elbtckeo3ubay6i3bicv3pikpfpi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvjfau73krvpdhvuvmnorwa2elbtckeo3ubay6i3bicv3pikpfpi

**Comment by NFTSTAR02** [comment]
@Kevin-FF-USA @panges2 
Sry the inconvenience! I thought i wasn’t need to verify again as i was V3 notary.
