### ISSUE TITLE
Notary Application: Pluskit

### ISSUE THREAD

**Issue by PluskitOfficial** [filecoin-project/notary-governance#694]
## Core Information
- Name: Pluskit
- Affiliated organization: Pluskit
- On-chain address to be notarized (recommend using a new address):f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
- Country of Operation: Japan
- Region of Operation:  Asia minus GCN
  [North America, South America, Europe, Africa, Greater China Region (GCR), Asia minus GCR, Oceania]
- Use case(s) to be supported: General
 [Please select from [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries)]
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization
 [Individual, Organization]

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Pluskit team was founded in June 2021, and the product was officially launched in October 2021.
In December 2021, Pluskit team was invited to participate in the Notary Governance Call to present a project showcase, which won a large number of likes from community members;
In January 2022, Pluskit received Next Step Microgrant;
In February 2022, Pluskit was included in the Filecoin Community Roadmap.
In March 2022, Pluskit was elected as Notary in the 3rd round of Notary Elections. During the tenure, we actively performed the duties as a notary:
a. Attended almost every Governance calls. 
b. Timely process applications. We received four general applications with an average processing time of 1 day and we dealt LDN for more than 60 times.
c. Actively participate in community discussions and express our own views, such as E-Fil+, project Beacon, issue of the third round of notary signing etc.
d. Join E-Fli+ group and attend the meetings.
Github: @PluskitOfficial
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
None.
```

How did you acquire the FIL cited above?
```
None.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Pluskit team was established in June 2021, and the product was officially launched in October 2021.
In March 2022, Pluskit was elected as Notary in the 3rd round of Notary Elections. During the tenure, we actively performed the duties as a notary:
a. Attended almost every Governance calls. 
b. Timely process applications. We received four general applications with an average processing time of 1 day and we dealt LDN for more than 60 times.
c. Actively participate in community discussions and express our own views, such as E-Fil+, project Beacon, issue of the third round of notary signing etc.
d. Join E-Fli+ group and attend the meetings.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Pluskit team was established in June 2021. The team consists of 3 members with many years of experience in the Filecoin industry. Pluskit is developed mainly for overseas markets and serves the entire ecosystem.

Since launched, we has received close attention and recognition from Protocol Labs and the Filecoin Foundation. In December 2021, we were invited to participate in the Notary Governance Call to present a project showcase. Since then, we have been actively contacted and recognized by a large number of community members. 
In March 2022, Pluskit was elected as Notary in the 3rd round of Notary Elections. During the tenure, we actively performed the duties as a notary.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Twitter：@PluskitOfficial
Slack：@PluskitOfficial
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
None.
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter：@PluskitOfficial
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
None.
```

# Allocation Plan
 [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)

### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We still believe that the entire industry needs to allow more real data to be stored. For this purpose, we will keep trying our best to relax the application restrictions on the basis of strict screening with real storage purposes: no restriction on the region, the type of subject and the type of legitimate data.

At the same time, in order to avoid private transactions, we will have strict requirements for data storage:
1. For the same application subject, the storage amount of the same node is not more than 30% of the amount of DataCap acquired in the same batch.
2. When the remaining amount of the applicant's DataCap is greater than 25% of the total amount of data (including applications from other notaries), new applications will not be accepted.
3. Only full public data or non-public data subject to random checks are accepted.
4. We will only accept those who will agree to give feedback with storage records (for the first time, only commitments are made, and subsequent actual feedback should be used as the basis for judgment)

When reviewing the application, we will evaluate and allocate from six aspects, including applicant's basic information, data information, industry reputation, time commitment, usage plan, and historical records.

As for the vetting process, we will take action according to the following principles and plans:
Timeliness: Reply within 1 working day after receiving the application.
Compatibility: We will give opportunity for clients to modify their information, and review within 1 working day.
Rigour: If clients do not reply within 7 working days, the application will be closed.
Please check out our scoring sheet and previous allocation record.
https://shimo.im/sheets/Ee32MrWoXxh5JYA2/MODOC/ 
The amount of DataCap we allocate to each client will not exceed 20% of our holdings, and each client can be allocated at most once a week.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We plan to store private keys in hard wallets.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1. We will evaluate clients from various aspects, such as qualifications, industry honors, etc., to ensure that people with bad intentions are filtered to obtain DataCap to the greatest extent possible before allocation.
2. We will confirm the usage plan in the questioning session, and ask for feedback on the actual usage after obtaining the DataCap, and will also continue to follow up the actual usage.
3. Our initial allocation will be relatively small. If the client is responsible for using DataCap, we will gradually increase allocation; if it is used improperly, we will suspend the subsequent vetting and allocation for this client.

We plan to ask the following questions:
1.Are you an individual or a business/organization? If an individual, please specify the name, date of birth, and nationality; if a company/organization, please specify the company name, registration time, and registration area. At the same time, please provide the corresponding supporting documents (individuals provide ID cards, enterprises/organizations provide licenses, which can be sent by E-mail).
2.What is your industry? What data will be stored? How much do you plan to store? Can the data be made public (if not, are we allowed to conduct random checks at any time?)
3.Please share information and relevant supporting documents or links that illustrate your industry status.
4.Did you get any honors? Please provide relevant supporting documents or links.
5.Please provide your social media account and indicate the number of followers.
6.Please describe the duration of your involvement in your industry and give a brief description of your industry.
7.Please specify the storage location, miner ID and storage proportion of your data to be stored. We require any data to be stored on the same node no more than 30% of the same batch of DataCap acquisitions.
8.If you get a DataCap, do you agree to send the storage record back here within 15 days of storage?
9.Did you get a DataCap? If yes, please attach all application links and inform the current remaining amount.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will clearly require in advance that the DataCap used by the same clients on the same node shall not more than 30% of the amount acquired in the same batch.

We will require clients to announce storage details in a timely manner and check the storage proportion before additional allocations.

Our initial allocation will be relatively small. If the client is responsible for using DataCap, we will gradually increase it; if it is used improperly, we will suspend subsequent vetting and allocation for the client.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, our allocation decisions will be made public online.

If there is any dispute about the allocation, community members can also send a message to us directly via Github/Slack(both@PluskitOfficial). We will promptly deal with it and contact the clients for confirmation when necessary. We will disclose the information collected during the vetting process and the allocation basis.

At the same time, we are constantly optimizing our allocation strategy to make it easier for clients to join the Filecoin Network while following community rules.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
All allocation decisions will be kept/updated both on online and locally.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric]
(https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
```

### Past allocation
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
https://github.com/filecoin-project/notary-governance/issues/448
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None.
```

**Comment by Kevin-FF-USA** [comment]
Hi @PluskitOfficial,

Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by PluskitOfficial** [comment]
@Kevin-FF-USA Hi, Kevin,
We've sent email with information as requested.

**Comment by PluskitOfficial** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceaq5c4gvkjb7inbxpqoe4ogda46k5rp6xclf3v6e4jruvcwz2t2rg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaq5c4gvkjb7inbxpqoe4ogda46k5rp6xclf3v6e4jruvcwz2t2rg

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[694.pdf](https://github.com/filecoin-project/notary-governance/files/10159431/694.pdf)

**Comment by PluskitOfficial** [comment]
@galen-mcandrew Received with many thanks.

**Comment by PluskitOfficial** [comment]
### Allocation Strategy

> We still believe that the entire industry needs to allow more real data to be stored. For this purpose, we will keep trying our best to relax the application restrictions on the basis of strict screening with real storage purposes: no restriction on the region, the type of subject and the type of legitimate data.
> 
> At the same time, in order to avoid private transactions, we will have strict requirements for data storage:
> 1. For the same application subject, the storage amount of the same node is not more than 30% of the amount of DataCap acquired in the same batch.
> 2. When the remaining amount of the applicant's DataCap is greater than 25% of the total amount of data (including applications from other notaries), new applications will not be accepted.
> 3. Only full public data or non-public data subject to random checks are accepted.
> 4. We will only accept those who will agree to give feedback with storage records (for the first time, only commitments are made, and subsequent actual feedback should be used as the basis for judgment)
> 
> When reviewing the application, we will evaluate and allocate from six aspects, including applicant's basic information, data information, industry reputation, time commitment, usage plan, and historical records.
> 
> As for the vetting process, we will take action according to the following principles and plans:
> Timeliness: Reply within 1 working day after receiving the application.
> Compatibility: We will give opportunity for clients to modify their information, and review within 1 working day.
> Rigour: If clients do not reply within 7 working days, the application will be closed.
> The amount of DataCap we allocate to each client will not exceed 20% of our holdings, and each client can be allocated at most once a week.


In addition to the above plan, we would like to add following idea:
1. We will also determine the allocation amount according to the different nature of the subject. To be specific, we will allocate 60% of standard amount to individuals and subjects with private data. 
Please check following updated table:

![image](https://user-images.githubusercontent.com/94815279/206859487-1b5c5ac6-3392-4d75-a9b3-cc97fee48e20.png)

2. During the vetting process, we will also use search tools and community members to assist in verifying the authenticity of applicants. We'll also use some tools, such as https://filplus.d.interplanetary.one/ and [https://pluskit.io/](https://pluskit.io/)), to kown the actual storage conditions. At the time of allocation, we will use the online documentation tools to record the storage and verify the client's subsequent storage status in a timely manner. In addition, we will also add clients' social accounts, including Slack and LINE, to facilitate timely communication with clients.
3. As long as clients are found to use DataCap privately or not as promised, we will warn them at the first time, ask them to explain the reasons, and then allocate 50% of the previous amount even though that they give reasonable reasons. If non-compliance is found again, we will terminate the allocation.

### Client Due Diligence

> 1. We will evaluate clients from various aspects, such as qualifications, industry honors, etc., to ensure that people with bad intentions are filtered to obtain DataCap to the greatest extent possible before allocation.
> 2. We will confirm the usage plan in the questioning session, and ask for feedback on the actual usage after obtaining the DataCap, and will also continue to follow up the actual usage.
> 3. Our initial allocation will be relatively small. If the client is responsible for using DataCap, we will gradually increase allocation; if it is used improperly, we will suspend the subsequent vetting and allocation for this client.
> 
> We plan to ask the following questions:
> 1.Are you an individual or a business/organization? If an individual, please specify the name, date of birth, and nationality; if a company/organization, please specify the company name, registration time, and registration area. At the same time, please provide the corresponding supporting documents (individuals provide ID cards, enterprises/organizations provide licenses, which can be sent by E-mail).
> 2.What is your industry? What data will be stored? How much do you plan to store? Can the data be made public (if not, are we allowed to conduct random checks at any time?)
> 3.Please share information and relevant supporting documents or links that illustrate your industry status.
> 4.Did you get any honors? Please provide relevant supporting documents or links.
> 5.Please provide your social media account and indicate the number of followers.
> 6.Please describe the duration of your involvement in your industry and give a brief description of your industry.
> 7.Please specify the storage location, miner ID and storage proportion of your data to be stored. We require any data to be stored on the same node no more than 30% of the same batch of DataCap acquisitions.
> 8.If you get a DataCap, do you agree to send the storage record back here within 15 days of storage?
> 9.Did you get a DataCap? If yes, please attach all application links and inform the current remaining amount.
> 
> We will clearly require in advance that the DataCap used by the same clients on the same node shall not more than 30% of the amount acquired in the same batch.
> 
> We will require clients to announce storage details in a timely manner and check the storage proportion before additional allocations.
> 
> Our initial allocation will be relatively small. If the client is responsible for using DataCap, we will gradually increase it; if it is used improperly, we will suspend subsequent vetting and allocation for the client.


Regarding Client Due Diligence, we would like to add the following information:
1. First of all, we will designate specialized personnel and develop standardized audit procedures and fixed working hours.
2. Upon receipt of the application, we will ask clients to answer fixed questions, and vet the authenticity of the clients' identity, the amount of the clients' real data, the openness of the data, and the storage plan of the clients' data (such as how many nodes exist, how many copies will be stored, and which areas will be stored) according to the key questions.
3. In addition to the information answered by clients, we will also take the initiative to search the relevant information of the client online to verify the real situation of the clients. Specifically:
a.Subject Authenticity
We will ask clients to send the subject certification documents by email, and ask the clients to send the verification email to us by official email address. If needed, we'll post the application on slack to get more community members to verify the subject's authenticity.
b. Real Data Volume
We will ask the clients to explain the data form and corresponding quantity ratio, and also ask them to show a screenshot of the current data volume.
c. Storage Plan
We will force clients to specify storage locations and nodes prior to actual allocation.
4. After allocation, we will also use the official data and community tools (such as https://filplus.d.interplanetary.one/ and our https://pluskit.io/) auxiliary verify clients' actual storage. At the same time, we will add clients' social accounts, including Slack, LINE, etc., so that when clients fail to give feed back on github in time, we can timely contact them and ask them to reply promptly.

### Bookkeeping Plan

> Yes, our allocation decisions will be made public online.
> 
> If there is any dispute about the allocation, community members can also send a message to us directly via Github/Slack(both@PluskitOfficial). We will promptly deal with it and contact the clients for confirmation when necessary. We will disclose the information collected during the vetting process and the allocation basis.
> 
> At the same time, we are constantly optimizing our allocation strategy to make it easier for clients to join the Filecoin Network while following community rules.
> 
> All allocation decisions will be kept/updated both on online and locally.


With regard to the bookkeeping plan, we would like to be further clear and add the following information:
1. We have prepared the allocation record form, and will make a real record of the content after each allocation.
2. We will publish the recorded information on Github repo and update it once a month; At the same time we will also save the table locally in real time.o
Our allocation record sheet is as follows:
![image](https://user-images.githubusercontent.com/94815279/206859539-ffce806f-610c-474e-babc-fb566e47f34e.png)

3.After the allocation, we will also according to the time to check the clients' actual storage situation. We'll use the tools include https://filplus.d.interplanetary.one/ and https://pluskit.io/, etc.
4.When someone questions the allocation, we will reply within 2 working days and provide corresponding proof. If the client needs to provide proof, we will contact the them to provide corresponding explanation and evidence. If the doubter is still not satisfied, we will timely report to PL and have a meeting together for communication.

**Comment by PluskitOfficial** [comment]
@galen-mcandrew @raghavrmadya @Kevin-FF-USA Please see our supplementary information. Thank you so much.

**Comment by Kevin-FF-USA** [comment]
@PluskitOfficial 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.
