### ISSUE TITLE
Notary Application: BlockMaker

### ISSUE THREAD

**Issue by BlockMakeronline** [filecoin-project/notary-governance#695]
## Core Information
- Name: BlockMaker
- Affiliated organization: BlockMaker
- On-chain address to be notarized (recommend using a new address): f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
- Country of Operation: Japan
- Region of Operation:  Asia minus GCN
  [North America, South America, Europe, Africa, Greater China Region (GCR), Asia minus GCR, Oceania]
- Use case(s) to be supported: General
 [Please select from [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries)]
- DataCap requested for allocation (10TiB - 1PiB)DataCap: 1PiB
- Are you applying on behalf of yourself or an organization?: Organization
 [Individual, Organization]

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
BlockMaker has been in the Japanese blockchain market for four years, formerly known as ビットマイニング cluster Co., LTD. We hope to promote the infrastructure and future development of the distributed storage market in Japan and elsewhere in Asia. We have been involved in Filecoin technology research since last year, currently operating storage nodes, such as f01451690 and so on.

In March 2021, BlockMaker was elected as Notary. Till now, we have completed nearly 40 LDN approvals. We also participated in Goverance Call nearly every time and  reply in Slack very timely.

In March 2021, BlockMaker was elected as Notary. Till now, we have completed nearly 40 LDN approvals. We also participated in Goverance Call nearly every time and  reply in Slack very timely.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
We prefer to not disclose.
```

How did you acquire the FIL cited above?
```
None.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
In March 2021, BlockMaker was elected as Notary. Till now, we have completed nearly 40 LDN approvals. We also participated in Goverance Call nearly every time and  reply in Slack very timely.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Registered country: Japan
Organization scale: Over 50 parters working for BlockMaker
Date of establishment: November 29, 2018
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website:https://www.bm.land/
Related Links:https://cryptocurrency-association.org/member/block-maker/
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Related Links:https://cryptocurrency-association.org/member/block-maker/
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://twitter.com/fil_lab（Twitter, FIL-Lab, followers:563）
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
None.
```

# Allocation Plan
 [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)

### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Application Process
Client application --> List application materials -->Client response --> Investigation and vetting--> Allocation

Application Materials List
Background investigation
[Enterprise] provide business license, applicant's identity certificate 
[individual] provide identity certificate, work certificate
Main project industry share
Main project monthly active users

Use cases
Sample diversity and sample description

Data storage on Filecoin survey
To check 2 files every 1T

Basic requirements: Storage constraints
It shall not be stored in the miner node in which it has an interest, and at least three or more miners

Allocation Mechanism
https://github.com/BlockMakeronline/Bookkeeping-Records/files/8331038/Scoring.Standard.xlsx

Each client receives different maximum approved share based on the score, as detailed in the table above.
Allocation Rate: expected 50TB/ month
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We plan to store private keys in hard wallets.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
The review of new clients is mainly carried out through two aspects: the clients themselves and the data to be stored.

For regular clients, responsible and adequate investigation is mainly carried out from three aspects: clients themselves, data to be stored and interest association.

Background investigation of clients mainly includes business license, identity certificate and project status; The variety and size of the data to be stored will be investigated.

In terms of the main interest associations of storage, we will set basic constraints (not stored in miners' nodes with any their interest, stored in at least 3 miners) and conduct responsible and effective investigations after the data is stored by clients.

We will not complete grading and distribution immediately after submitting an application.
We usually use offline and online methods to verify.
Offline
We will try to negotiate with applicants and visit their office for further investigation, including the authenticity of the office location and business;
After confirming the allocation, we will also conduct survey during the use of DataCap to confirm its sustainability;
Online
Before allocation, we will query clients status through the Internet and assess clients' risk.
1.Proof of incorporation 
a) Organization License 
b) ID/Passport for individuals who hold more than 25% ownership in the organization is a listed company officer
c) A photo of a company officer holding their driver's license or other government
2. Website / Social Media
To check applicants' website, social media, reports, news, etc. so that we can verify the authenticity and sustainability of the applicant
3 Dataset
Authorization if client will store data from other organizations
4 Storage Providers
a)Do not have any interest in the storage providers
b)at least 3 storage providers, and each storage provider proportion does not exceed 35%
After confirming the allocation, we will communicate with the applicant on a regular basis and supervise their storage in accordance with the rules; If the applicant is found break our/community rules, we will disqualify it if DataCap has not been allocated. We will reclaim its remaining DataCap if DataCap has been allocated.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. Conduct effective preliminary investigation on clients and data to be stored.
2. Survey client usage of previously approved DataCap, if any.
3. Set certain thresholds for clients to avoid excessive allocation.
4. Check client's DataCap usage and data to be stored.
5. If there is excessive allocation of clients, the relevant information of clients will be disclosed in the community and listed in the industry blacklist.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
1. All details of client interactions will be recorded through an open and transparent Github repository.
2. Effectively record the situation of each client and establish a list base for each client.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We plan to conduct most of my work through public means, and we will not rule out using private means if clients' private materials involved.
Besides, we will set up a dedicated repository on Github(https://github.com/BlockMakeronline/Bookkeeping-Records) to display all allocations so that they can be viewed and monitored at any time.
As a notary, all of our allocation strategy and operations are accessible through public channels and we will update when strategy being optimized; If the applicant's information is involved, I would like to follow the particularity of their business and choose whether to disclose it or not.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric]
(https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
```

### Past allocation
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
https://github.com/filecoin-project/notary-governance/issues/454
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None.
```

**Comment by BlockMakeronline** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacea5gq5wsmmejv6c5facj3g4apw7d3ofjcnjed3ngxmtj2zda5iwxo
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5gq5wsmmejv6c5facj3g4apw7d3ofjcnjed3ngxmtj2zda5iwxo

**Comment by Kevin-FF-USA** [comment]
Hi @BlockMakeronline,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by BlockMakeronline** [comment]
Hi,@Kevin-FF-USA , we‘ve sent email last week. 
Should more information/documents needed, please feel free to contact us.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[695.pdf](https://github.com/filecoin-project/notary-governance/files/10159434/695.pdf)

**Comment by BlockMakeronline** [comment]
@Kevin-FF-USA @galen-mcandrew ### Allocation Strategy
We have rearranged the allocation strategy as follows:
I .Application object that we accept
a.We accept subjects from all over the worldwide
b.Both organization and an individual are acceptable
c.Data holders over 10TiB
d.Prefer to public data. As for private data, we will be more careful (we need two samples per TiB).
e.Subject applications that have not been previously challenged by the community or have been clearly clarified after being challenged.
f.The one whose current DC amount is less than 1TiB

Ⅱ. Allocation Process
a. The client answers the questions and explains any follow-up questions
b. Collect online information and query other information related to clients for supplementary verification
c. Inform clients that we will allocate but ask them to promise to disclose the allocation information within 7 working days after the completion of storage, and promise to store it on at least 3 nodes that are not associated with interests
d. Allocation
e. Record the allocation information, synchronize it to Github, and inform the client on issue that the allocation has been completed.

ⅲ. Allocation Amount and Rate
a. Allocation shall be carried out step by step: the allocation shall be small at the first time, and gradually increase after subsequent verification and compliance, but the maximum amount corresponding to the score shall not be exceeded by a single subject. See the score table for details
https://github.com/BlockMakeronline/Bookkeeping-Records/files/8331038/Scoring.Standard.xlsx
b: Expected  50 tibs per month

Ⅳ. Allocation personnel and time
a. We will have two people to carry out the allocation work. One is responsible for vetting, and another is responsible for allocation (keeping Ledger).
b. Vetting and allocation work will be conducted every Monday, Wednesday and Friday from 2:00 PM to 4:00 PM.

### Client Due Diligence
We will vet our clientis by following ways:
Ⅰ. Vetting Methods and Contents
As a whole, we will focus on vetting different content according to different clients' conditions. Therefore, before asking questions, we will first search whether clients and their address have application records.
1. If the client has applied for Datacap elsewhere, we'll check the surplus volume and storage conditions;
a. If the client's DataCap is greater than 1TiB, we will inform them to apply for DataCap after using it up.
b. If the DataCap surplus is less than 1TiB, we will examine whether there is abuse. If there is no abuse, or if there is abuse but can be clearly stated, we will start to ask normal questions.
2. When a client has applied for DataCap and the remaining amount is less than 1TiB, we will focus on vetting client authenticity, data to be saved, and abuse behaviors.
a. client authenticity: mainly includes business license, identity certificate, project status, etc.
b. Data to be stored: Mainly vet the type and amount of data, and will require them to provide data samples.
c. Abusive behavior: We will set the basic constraint (not to store in the mine site where there is any interest, to store in at least 3 miners), require them to show the storage and to match the actual storage.
3. If a client has not applied for DataCap, check the client authenticity and data to be stored.
a. client authenticity: It mainly includes business license, identity documents, project status, etc. During this period, we will try to negotiate with the applicant and go to their office for further investigation, including the authenticity of office location and business status.
b. Data to be stored: Mainly vet the type and amount of data, and will require them to provide data samples.

More specifically, we will focus on vetting the following aspects:
Before allocation, we will query clients status through the Internet and assess clients' risk.
1.Proof of incorporation 
a) Organization License 
b) ID/Passport for individuals who hold more than 25% ownership in the organization is a listed company officer
c) A photo of a company officer holding their driver's license or other government
2. Website / Social Media
To check applicants' website, social media, reports, news, etc. so that we can verify the authenticity and sustainability of the applicant
3 Dataset
Authorization if client will store data from other organizations
4 Storage Providers
a)Do not have any interest in the storage providers
b)at least 3 storage providers, and each storage provider proportion does not exceed 35%
After confirming the allocation, we will communicate with the applicant on a regular basis and supervise their storage in accordance with the rules; If the applicant is found break our/community rules, we will disqualify it if DataCap has not been allocated. We will reclaim its remaining DataCap if DataCap has been allocated.

Ⅱ Vetting Tools
1. Check the authenticity of clients: We will ask clients to send the main documents, such as business license, via official email. At the same time, we will use the Internet to collect clients' information.
2. Abusive behavior: We will ask clients to display storage providers on GitHub. We'll also use Filecoin browsers to verify the storage status.
3. Allocation tools: We will document the allocation information online and post it on the github repo for community members to view.

Ⅲ Vetting personnel and time
1. We will have two people to carry out the Fil+ work, one of them will be responsible for vetting.
2. Vetting and allocation work will be conducted every Monday, Wednesday and Friday from 2:00 PM to 4:00 PM.

We will ask the following questions:
1. Please briefly introduce yourself and your organization.
2. Please email us your or your organization's supporting documents. In particular, if you apply in the name of the organization, please send us all supporting documents such as the organization's license, personal ID cards/passports of company executives who hold more than 25% of the organization's equity, and photos of company officials or other government officials who hold driving licenses;
3. Please provide links to your company or personal website, social media accounts, news, etc.;
4. Please specify the type and size of the data you will store.
5. Please provide at least three storage providers that you will cooperate with this time, and explain the storage quantity or proportion of each one.
6. Have you ever obtained DataCap before? If so, please indicate how much is left and display the storage records here.

### Bookkeeping Plan
With regard to the bookkeeping plan, in addition to the above, we would like to add:
1. We will record the allocation information in real time immediately after each allocation. This allocation information will be uploaded to the Github repo in real time and recorded on our local table.
https://github.com/BlockMakeronline/Bookkeeping-Records
2. After clients show the storage situation, we will add it to the table in time and upload it to Github immediately. If any abnormal situation is found, we will synchronously send the information to PL and slack when the client is found to have abused behavior through communication.
3. When we or our clients are questioned, we will immediately cooperate with the investigation and provide all possible supporting materials.

**Comment by Kevin-FF-USA** [comment]
@BlockMakeronline 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by BlockMakeronline** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaced5g3sxgbpev5zgnjbu3hqritucy6cceq4v2c5e5pet2wdrntlp7e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5g3sxgbpev5zgnjbu3hqritucy6cceq4v2c5e5pet2wdrntlp7e

**Comment by BlockMakeronline** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecyh2q2eqvczvhu4yegubqslbqusaakciohp5z6kox33uyvxozy6m
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyh2q2eqvczvhu4yegubqslbqusaakciohp5z6kox33uyvxozy6m

**Comment by BlockMakeronline** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacealaxms2eeqwl54wctxtoxrid54wdf567cgxdtv2u46zggydtahrw
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealaxms2eeqwl54wctxtoxrid54wdf567cgxdtv2u46zggydtahrw
