### ISSUE TITLE
Notary Application: IPFS Japan Consortium (Masaaki Nawatani)

### ISSUE THREAD

**Issue by MasaakiNawatani** [filecoin-project/notary-governance#696]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Masaaki Nawatani
- Affiliated organization: IPFS Japan Consortium
- On-chain address to be notarized (recommend using a new address):  f1ciu27vn3r7htmanzvwrm6ksx6y774gqsz3cot3i
- Country of Operation: Japan
- Region of Operation: Asia-minus GCR
- Use case(s) to be supported: Professional services
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Individual

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
My team and I are committed to push meaningful distributed storage to as many verifiable clients as possible. As an existing Notary since the inception of Filecoin Plus, I have been a contributor in getting clients verified in a timely manner. I have maintained active participation and attendance in Governance calls and have effectively communicated with the Notary Admins via Slack when necessary. In 2021, I was elected as a director of the IPFS Japan Consortium, a nonprofit organization that educates and encourages Japanese individuals and businesses to find value in IPFS and Filecoin. 

I will continue to apply under IPFS Japan Consortium for this round. My profile on IPFS Japan consortium can be found here https://ipfsjapan.org/about/ Masaaki Nawatani is 縄谷正明 in Japanese. 

Github handle is MasaakiNawatani
Slack handle is Masaaki Nawatani.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
I prefer not to disclose. 
```

How did you acquire the FIL cited above?
```
I prefer not to disclose. 
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As one of the first 3 Notaries assigned to the Asia-GCN region, I have spent a considerable amount of time helping the cause. I have good working relations with Deep Kapur, Jonathan Victor, Kevin Wray and Galen McAndrew, as well as with other notaries. The strategy that I use in conducting due diligence to my clients has been efficient and definitely contributed to the growth of clients coming from Asia, especially in South Korea and Japan. I was able to allocate datacap to 52 clients in Round 3, and four (4) clients in Round 4. This number would have been much larger had I not experienced an ongoing technical issue in allocating datacap using the Filecoin Plus Dashboard. 

As a Director for IPFS Japan Consortium, I was able to facilitate conferences and seminars within the Japanese Web3 community. I also published articles and video contents to share my knowledge and experience in IPFS with businesses and investors in Japan. 

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Being part of the 1st ever batch of Notaries elected, there were many obstacles and technical challenges that we faced. I have participated in FIPS and raised concerns when we find an area for improvement within the ecosystem, as well as for any technical issues we face. 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
IPFS Japan Consortium aims to improve Japan's industrial competitiveness through technologies centered on IPFS. For this reason, companies and experts whose core businesses are Internet communication and data center-related businesses play a central role in promoting industrial utilization, human resource development, making proposals to public institutions and industries, international cooperation, and dialogue with society. We will carry out activities necessary for sound development.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://ipfsjapan.org
Officers on Slack: @jessie-ipfsjapan @obbie-one 
LinkedIn: https://www.linkedin.com/in/masaaki-nawatani/
https://www.youtube.com/channel/UCw6G6MIt3f26e8pglcbJ18Qhttps://twitter.com/IPFS94660609
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
**Articles published by Masaaki Nawatani:** 
- https://note.com/ijc) which has over 10k PV, 100+ articles
- https://media.ipfsjapan.org/

**YouTube Education video contents for IPFS and filecoin**
- https://www.youtube.com/channel/UCw6G6MIt3f26e8pglcbJ18Q
- https://www.youtube.com/watch?v=cb3kxJW3Kw8&list=PLs8L0zPmKAi84BNiSbVNKgLf53KHg9nip

**The Filecoin 1st Anniversary Conference:**
This conference was hosted by Masaaki Nawatani
- https://ipfsjapan.org/filecoin-1th-anniversary/
- https://www.youtube.com/watch?v=9qHCk0KmmYs

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
**Twitter URL(IPFS Japan consortium)**
- https://twitter.com/IPFS94660609

**Facebook URL(IPFS Japan consortium)**
- https://www.facebook.com/IJCFB/?ref=pages_you_manage
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
**The Filecoin 1st Anniversary Conference:**
This conference was hosted by Masaaki Nawatani
- https://ipfsjapan.org/filecoin-1th-anniversary/
- https://www.youtube.com/watch?v=9qHCk0KmmYs
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
I plan to allocate DataCap to clients who will be able to provide verifiable information about their organization and have their data storage plan made clear and available to their end-users. Same as what I have implemented in the past 3 rounds, I will be setting up thresholds with varying degrees of trust to promote consistency across the board. I plan to allocate DataCap to duly registered and end-user transparent Clients by performing due diligence. The same conservative approach and method that I currently use as Notary. If a client requires a large amount of DataCap and the business is worth being allocated, I will first allocate >= 5Tb and ask the client to start small. If they need more, they can come back to me with proof of use or deals before I grant more datacap to uphold the integrity of the program. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
By using a Ledger Wallet, which is accessible by me alone. 
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
The vetting process to ensure Clients are/will spend DataCap responsibly will comprise of the following required elements: 

1. Company / Organization Proof of Existence
 - Company documents such as Business Registration, License to Operate and other government issued documents to validate their business rights and existence.
 
2. Stakeholders
 - Acquire the core information of all authorized signatory’s that will act on behalf of the application entity. Which may include a signed authorization letter from the Board of Directors or CFO/CTO/CEO. In the event that there are multiple shareholders, a comprehensive core information for each actor will be required along with a photo of their government issued ID and a selfie while holding the document. 

3. Checking related reputations
-We will check not only his Website but also SNS such asTwitter, facebook, instagram and so on. And also we will check the local news site and company database by chamber of commerce in which his company registered. 

4. Proof of Deals (for 2nd time requests)
-I will request for some sort of proof that the previous allocation was indeed used as stated on by the client
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
I will request for proof that the previous allocation was indeed used as stated on by the client by asking for the address involved and cross-verifying that information with the tools and resources available. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We intend to carry out all decisions in public via Github repo
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We intend to create a github repo that is accessible to the public for transparency and visibility. 
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
Level 4
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes. 

```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None.
```

**Comment by Kevin-FF-USA** [comment]
Hi @MasaakiNawatani,

Thanks for (re)applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Please email NOTARYELECTION@FIL.ORG from the email account linked to this GitHub account. *The email MUST COME from the same GitHub account you used in this application.

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Country of Operation
3. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
4. Link to this GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by MasaakiNawatani** [comment]
Got it Kevin. Will do this today. Thank you.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[696.pdf](https://github.com/filecoin-project/notary-governance/files/10159436/696.pdf)

**Comment by Kevin-FF-USA** [comment]
@MasaakiNawatani 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to continue as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by MasaakiNawatani** [comment]
Wonderful. Thank you so much @Kevin-FF-USA and Filecoin Notary Team. We will do our best for this round as always.

**Comment by panges2** [comment]
Hi @MasaakiNawatani, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by panges2** [comment]
Hi @MasaakiNawatani,  this is another reminder to get your ledger verified as soon as possible. Thank you!
