### ISSUE TITLE
Notary Application: Aifabot

### ISSUE THREAD

**Issue by Aifabot-Cloud** [filecoin-project/notary-governance#698]
Notary Application-Aifabot
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Benny
- Affiliated organization: Aifabot
- On-chain address to be notarized (recommend using a new address): f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
- Country of Operation: Canada
- Region of Operation: North America
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 1PiB):500TiB
- Are you applying on behalf of yourself or an organization: Organization

Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Jan. 2021 we invest  the first SP of Filecoin network.
Mar. 2021 we invest the second SP of Filecoin network.
SP ID:  f0131822 f0429122 
GitHub: Aifabot-Cloud
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Total 728,520 FIL
```

How did you acquire the FIL cited above?
```
Company Investment and block reward
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
In 2017, we learned about the IPFS protocol and in 2020 we learned about the Filecoin network, and after the mainnetlaunched, we invested in the Filecoin network in Jan. 2021, became a storage provider. 2022, we introduce Filecoin's storage to our customers. 

We are  a public cloud service provider, providing access to Google Cloud, AWS, Azure, Alibaba Cloud, etc. We also provide server rental and network services for our customers through data center partnerships.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```

- We are Aifabot, providing the revolutionizing global connectivity(public cloud service）
 
- Our mission is to take everything we know about traditional networking – flip it and reverse it – and put the power back into the hands of the consumer.

- Based on the IPFS protocol and the Filecoin network, Enterprises that double down on control, choice, and cost-efficiency have the ability to do smart business today, while building for the future. We’re giving consumers the network connectivity they deserve with global availability, right-sized bandwidth, and on-demand consumption. 

- In the future, we will actively participate in building WEB3 decentralized storage to accelerate its adoption by enterprises.
- We are tech-heads, creatives, developers, cyclists, problem solvers, gamers, animal lovers, parents, engineers, cooks, and much more. We don’t sit and watch the world go by. We challenge the status quo and push the boundaries.

- With our vision at the core of everything we do, our company is brought to life through innovation and interconnection.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
www.aifabot.net 
https://www.canadacorporation.info/companies/9049207/
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
www.aifabot.net 
https://www.canadacorporation.info/companies/9049207/

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
GitHub: Aifabot-Cloud 
www.aifabot.net 
Linkedin：https://www.linkedin.cn/incareer/in/bennybinwang
```
Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
www.aifabot.net
https://www.canadacorporation.info/companies/9049207/
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Please refer the link for detail
https://docs.google.com/spreadsheets/d/1OXTzB8cj5ubtak4_QYjxga3F-BdVn8BQx3cGUdNkjGs/edit?usp=sharing
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Ledger will be used for datacap allocation and the GitHub account will be keep in my hand
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
**Individual Applicants**
Details include but not limited to these:
1. Personal /Organization Information
2. Beneficial Owners
3. A file list that contains the size and data CID of each stored file.

**Enterprise Applicants:**
**Basic Info**
1. What's your name and your position in your company?
2. Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide ≥2 Github accounts or email addresses of them?
3. For your organization, Please describe its business, its history since inception, registration country, scale, employee counts, operation regions, named executive officers, relevant projects, industry reputation, etc.
5. Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation. 
6. Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. And also could send me via email for privacy concerns. My contact: irene@12ships.com
7. How long have the team core members been engaged in development?
8. What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?
9. Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?
10. Where is your data stored now? 

**Track Record**
1. Has your organization obtained DataCap before? if so, please answer the following sub-questions.
2. Please share all the links and recordings of your applications before.
3. How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
4. What was your allocation strategy plan then and how did you execute it?
5. Are there any disputes open against you from your previous DataCap allocations? If any, please describe any of your honors or disputes in the field of Filecoin.

**Allocation Plan**
1. Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc. 
2. How many regions do you plan to store the data in? 
3. How many storage providers you intend to make dealing with?
4. Do you plan to record your allocation decisions and execution details in public? And how to realize it?
5. Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?

**Punishment actions may according to rule of the the FIL+ Team**
https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0028.md
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
A hardware wallet will be controlled for datacap allocation.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, both GitHub and email.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
All allocation decisions will be conducted publicly in the Github repository (https://github.com/filecoin-project/filecoin-plus-client-onboarding).
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L3
```
### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No, I don't.
```

**Comment by Kevin-FF-USA** [comment]
Hi @Aifabot-Cloud,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[698.pdf](https://github.com/filecoin-project/notary-governance/files/10159442/698.pdf)

**Comment by Aifabot-Cloud** [comment]
Hello @galen-mcandrew @Kevin-FF-USA , thank you for the score given by the community. In order to be more likely to act as a notary, we'd like to add the following information and hope to get the score updated:

1、about  Stake Exposure
We have missed three nodes, and we want to add disclosure: f01344987, f0136399 and f01841133. Now we have 1M FILs at stake. 

2、about Allocation Strategy
Concerning the use of DataCap, it is necessary to ensure that clients correctly use DataCap to store real data because "who" and "what" are very important.

For new clients, online and offline surveys will be conducted as much as possible to determine whether they are qualified to become verified clients.
* Browse the company / personal information and websites provided by them, and query the authenticity of the information from relevant government websites.
* Confirm the applicant's use case and storage plan through questions.
* For verifiable clients, historical reputation is equally important. Each allocation will be regarded as an evaluation of client reputation, including score accumulation and corresponding trust, to determine the upper limit of the data they will receive.

If the client successfully applies for DataCap and correctly stores the real data, the client can apply for more DataCaps here in the future.

3 、about Client Due Diligence
Regularly check and audit the usage of allocated DataCaps through tools such as 
#1: filplus.d.interplanetary.one . 
#2: Metawave.info
#3: Pluskit.io
#4: Ehume.com
#5: filplus.info/#/
If necessary, our dedicated team will be invited to provide more help.

4、about Bookkeeping Plan
As mentioned above, in GitHub.
Since all application records are publicly available, allocation decisions are transparent.
Suppose community members challenge the notary's decision; in that case, they can submit a dispute resolution application to the notary's management organization after giving clear evidence, and the management department can appoint arbitrators to resolve the dispute.

Looking forward to hearing from you, let's join the team of notaries ASAP.

**Comment by Kevin-FF-USA** [comment]
@Aifabot-Cloud 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by Aifabot-Cloud** [comment]
> @Aifabot-Cloud Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections.
> 
> In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in https://plus.fil.org/ as well as outline the best practices and responsbilities for a Notary in the Program.
> 
> Next steps
> 
> 1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
>    
>    1. https://airtable.com/shrjx52lvefitwdq6
> 2. **By 30 December** - Ensure that the Governance meeting time is on your calendar and make scheduling plans which allow you to commit to attending per your SLA level expectations. (L1-L5)
> 
> Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.



> @Aifabot-Cloud Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections.
> 
> In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in https://plus.fil.org/ as well as outline the best practices and responsbilities for a Notary in the Program.
> 
> Next steps
> 
> 1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
>    
>    1. https://airtable.com/shrjx52lvefitwdq6
> 2. **By 30 December** - Ensure that the Governance meeting time is on your calendar and make scheduling plans which allow you to commit to attending per your SLA level expectations. (L1-L5)
> 
> Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

Thanks Kevin,  Form submited

**Comment by panges2** [comment]
Hi @Aifabot-Cloud, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by Aifabot-Cloud** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebbpjkdsj7y4jx32s4xh6d5go5brxg2u4hm44ysqojb3c544m54c6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbpjkdsj7y4jx32s4xh6d5go5brxg2u4hm44ysqojb3c544m54c6

**Comment by Aifabot-Cloud** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedkqym7pn5x4shi6bn3cuvxpcrfwixf6nuhpa2rppoabvqyhckbcw
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkqym7pn5x4shi6bn3cuvxpcrfwixf6nuhpa2rppoabvqyhckbcw

**Comment by Bennyyangpu** [comment]
I am Benny, founder of Aifabot, my github username has changed to bennyyangpu from Aifabot Cloud because i will be directly replacing our former colleague for future signings.
