### ISSUE TITLE
Notary Application：TJWallet

### ISSUE THREAD

**Issue by TJWallet** [filecoin-project/notary-governance#7]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
- Name:Tianji Data
- (Optional) Affiliated Organization: 
- Website / Social Media:
https://dapponline.io/
https://tjwallet.net
https://twitter.com/DappOnline
https://twitter.com/TJ_Wallet
- On-chain Address(es) to be Notarized:f17zuwk5bwvugni3de4pw5dcrmxngqepakbw44gia
- Region of Operation: Greater China, Asia-GCN
- Use case(s) to be supported: Any
- DataCap Requested:100 TiB or any allocation that can be granted to my profile.

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
I’m an individual  fully engaged with  Filecoin for many years and I’m investing money and all my time in the Filecoin ecosystem.  I want to support Filecoin development and ecosystem as much as I can.
I've been using  IPFS for years, I joined filecoin community in Feb.
1. A secure wallet that supports the complete transaction function of the Filecoin blockchain. All data (news, DApp, etc.) of the wallet will be backed up to the IPFS node.https://github.com/TJWallet/Android
2. A Filecoin blockchain browser, project development is nearing completion but has not yet been launched.https://github.com/TJWallet/FileCoinScan
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
20FIL
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Participate in Filecoin community HackFS, project homepage address:
https://hack.ethglobal.co/showcase/tj-wallet-lite-recLlsXBMBtX0sHeX
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 
```
None
```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
I am an entrepreneur and founded Tianji Data in China. We focus on blockchain, big data, DApp ecology, etc. My team members have more than 6 years of experience in the blockchain industry.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://dapponline.io/
https://tjwallet.net
https://twitter.com/DappOnline
https://twitter.com/TJ_Wallet

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://dapponline.io/
https://tjwallet.net
https://twitter.com/DappOnline
https://twitter.com/TJ_Wallet
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
I’m looking to help and support filecoin growth. Participating to this beta is my contribution to help defining Filecoin+ roles and processes attached to it. 
I will also envisage allocating time to this activity once the beta phase will be over. Maybe at that point, I will have a better understanding of the different cases and where I will have more value. For now, I’m happy to support any use cases.  
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
```
When a client requests DataCap from us, we will review some of the client's conditions:
client size, historical situation (if it is a new client, it is considered to allocate from a small scale, and a higher quota will be given with a good follow-up record), security (low security will not give high quota), transparency, allocation scale of this request, etc
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 
```
Not yet, but we'll launch plans and tools later, and we'll make them public and share them.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
will have a private key. These private keys are stored in the cold hardware wallet. Each authorization allocation must have the authorization of all members.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?
```
For new users, we will give a smaller DataCap and as much as possible to collect and verify the reliability of data, in order to improve their reputation. For the old users, we will give higher quota and irregular check the usage of DataCap and the authenticity of data. We will try our best to track the usage of datacap throughout the process.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 
```
First, the client must pass the "basic standards". Then try to ask some sensitive questions and make the distribution plan according to the client's answers. But in any case, it starts with a small quota. Slowly through the more stringent inspection, can get the higher quota.
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
```
At the beginning of the project, we will closely track the use of client's DataCap. As time moves on, we will audit at any time, but if there is any behavior that does not conform to the rules, we will impose a certain degree of punishment.
```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
```
For keeping fairness and openness of the project, we will provide records of our allocation decisions of the past period on the official website and github regularly. No matter what audit requests, we will try our best to answer and provide.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
For tracking of allocation decisions and keeping them in public, In the future, we will build some browsers and make some tools to support.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
None
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 
```
None
```

**Comment by jnthnvctr** [comment]
HI @TJWallet  - we have some initial feedback here - please see column H: https://docs.google.com/spreadsheets/d/1-_ffAhXwj8sUTbYukbUBPJuVZHYmgICGqz3USItJoUM/edit?usp=sharing

Please note that there is a pending rubric change which might affect the scoring here: https://github.com/filecoin-project/notary-governance/pull/36

If you have questions please ask!

**Comment by jnthnvctr** [comment]
Based on the new rubric, here is your new scoring: https://docs.google.com/spreadsheets/d/1C-HCll6a0dAYyobv6vKLvNIphW1zmH4vfuQ11lCFYO4/edit?usp=sharing

Please note the fixes for geography were not made, but I assumed GCN for your application (given your other information). 

Eligibility score: 2 
Unrounded score (for tiebreaking): 1.5

**Comment by TJWallet** [comment]
Hello,
There is a little problem, our page rating on Github is
Eligibility score: 1
Unrounded score (for tiebreaking): 1.3
This is a little different from my mail.


At the same time, I still don’t have permission to view the table file

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by jnthnvctr** [comment]
Hi this was a transcription error - the sheet is correct.

**Comment by dkkapur** [comment]
@TJWallet - just wanted to let you know that Notary applications are currently open again until May 25. In case you'd be interested in applying again, please create a new Issue of type "Notary Application" and fill in the form (it is completely reasonable to reuse material from your prior application).
