### ISSUE TITLE
Notary Application: Haute S Planning Inc

### ISSUE THREAD

**Issue by baiciao** [filecoin-project/notary-governance#701]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Baiciao Ren
- Affiliated organization: Haute S Planning Inc
- On-chain address to be notarized (recommend using a new address): f1s7p3iputcqpmua2ugrcksuntclfrilv33yamwea
- Country of Operation: United States
- Region of Operation: North America
- Use case(s) to be supported: Public or Open Data
- DataCap requested for allocation (10TiB - 1PiB): 100 TiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
I am personally an active participant of the Filecoin community and attend governance calls regularly. The goal here is to really take a step forward and have a deeper engagement with the Filecoin community by becoming a notary. We wish to help speed-up the adoption of Filecoin and the use of the decentralized network. By becoming a notary, we will be in a better position to spur the utilization & growth of Filecoin.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
N/A
```

How did you acquire the FIL cited above?
```
N/A
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- I have been in the Filecoin community for over half a year, and spend a great deal of time on Filecoin
- I am active in various channels such as Slack, in-person events and providing assistance & engaging with other fellow filecoin community members
- I have also conducted events together with Filecoin such as Fil-Summit
- I am also multilingual, acting as a translator many times for various entities within the Filecoin community 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Haute S Planning Inc was established on Nov 17 2015 as a domestic business corporation type registered at 740 New Dorp Ln Staten Island. It has a long history of operation of almost 7 years.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
N/A
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
N/A
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://www.linkedin.com/in/baiciao-jodi-ren-77110a25/
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
N/A
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We will first use the [client allocation form](https://github.com/filecoin-project/notary-governance/blob/main/notaries/templates/sample-client-application.md) provided by the governance team. This includes:
* Browse their official website to get a general understanding of the company or the individual. 
* Query the company's registration information from government related websites to make sure the information he submitted is true.
* Ask some questions to know about the applicant's position/organization/plans/use case etc. 

We will also be looking into adopting other **successful** notaries scoring models such as: 
- https://docs.google.com/spreadsheets/d/12ItWjuddDPZpFBE84dzNJxBM24AhZHDJcWsu9RY3xG4/edit#gid=0
- https://docs.google.com/spreadsheets/d/1UYY7AcXMAy376kjqKcCgcwb4-WrTKBEshYgJllNQtlk/edit?usp=sharing
and trying out which model best suit us.

We will also be tracking the allocations closely and only released sufficient datacap to ensure there is no foul spending and abuse of Datacap.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The private keys will be stored in the hard wallet and will only be accessible by me.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1. We will use part of the framework Kevin has established for Fil-E to vet our clients.
- https://github.com/filecoin-project/notary-governance/issues/611
This includes using established tools to perform KYB to ensure authenticity of the company.
2. Next, we will perform due diligence on the data that is to be stored. We will see if it is inline with Filecoin goals, and that the data are truly humanity's most important data. In the event in which the data consists of encrypted enterprise data, we will also direct them to Fil-E program, and provide them with utmost assistance. 
3. We will check if the clients have already secured Storage Providers. In the event that they do not, we will do our best to provide guidance based on our knowledge of various SPs in the Filecoin community. 
4. We will also perform a background check on the client's history of Filecoin storage, if we discover any misbehavior and foul play, we will no longer entertain the client.
5. We will do random spot checks on our clients (and others) to ensure that the data they are storing is what was agreed on. Miners will also be checked to see if it respects the replica allocation rules, and that the data are stored evenly across different parties of miners.

1. We will ask thorough background questions, requiring proof of company existence, social media and even financial statements.
2. We will ask for proofs that they are able to represent the company they claim to be representing. There is a need to perform these sanity checks to see if the applicant is indeed representing the company, we have noticed that impersonation is becoming more common these days.
3. We will ask for their list of Storage Providers, if any, to prevent potential Datacap abuse.
4. We will ask for samples of the data, and if needed, go down to the ground in their data centers and perform a physical spot check.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. We will do the same process as above. The checks perform in the past may no longer be relevant today.
2. On top of that, we will also track and check their on-chain behaviors. If any foul play and misbehavior is detected, we will not grant the client additional Datacap.
3. We will also check the data that were stored previously by the client on Filecoin. We will confirm with our own eyes that the previously verified data is indeed verified.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All decisions will be made public on Github.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
All decisions will be made public on Github. We will also back it up to Filecoin itself regularly and the data should be retrievable by everyone.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No. But I have assisted DataCap allocation duties before and is familiar with the workflow.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
I used to be the VP of Origin Storage.
```

**Comment by Kevin-FF-USA** [comment]
Hi @baiciao,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by baiciao** [comment]
Hi @Kevin-FF-USA , I have send the email using my organization email: [baiciao@hautesplanning.com](mailto:baiciao@hautesplanning.com). Please let me know if you have any further questions or instructions. Thanks!

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by baiciao** [comment]
Thank you for the update. I understand that my application has been flagged for further audit by the Trust & transparency Working Group. I appreciate the diligence of the governance team in ensuring the integrity of the process, and I am happy to cooperate with any additional steps that may be necessary. Please let me know if there is anything else that I can do to assist with the audit. I look forward to hearing from the Working Group and continuing the application process.

**Comment by baiciao** [comment]
Just an update, I have confirmed the token codes too on Slack!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[701.pdf](https://github.com/filecoin-project/notary-governance/files/10159445/701.pdf)

**Comment by Kevin-FF-USA** [comment]
@baiciao 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
