### ISSUE TITLE
Notary Application: BigData Exchange

### ISSUE THREAD

**Issue by BDE-io** [filecoin-project/notary-governance#703]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: BigData Exchange
- Affiliated organization: We have no direct affiliation with any storage provider or data client
- On-chain address to be notarized (recommend using a new address): f1dvvrjur7tstos2paxdsvdpljqx53c74wsp5cl4q
- Country of Operation: Singapore
- Region of Operation: Asia minus GCR
- Use case(s) to be supported: All
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
- Timeline: May 2022-present
- GitHub: https://github.com/BigD-Exchange 
- Contributions: BigData Exchange is a data storage marketplace connecting Filecoin storage providers with data communities. 
- We aim for liquidity and a fair price discovery process for data storage services. In 5 months, we have facilitated more than 26 PiB of data transactions between data clients and SPs by November 14, 2022, as shown on https://www.bigdataexchange.io/.

- As transactions are on chain, our marketplace offers visibility and transparency of payment and verified deals flows, which we hope can help with governance.
- We have also participated extensively in ecosystem events, including FIL Austin (June 2022), FIL Singapore (September 2022, co-hosted Data Onboarding Day with Protocol Labs), and FIL Lisbon (November 2022, Network Analytics Day and Crypto Econ Day).
- Due to Fil+ crypto economics incentives, storage providers have expressed willingness to bid for verified deals, resulting in a paradigm shift of negative price storage services. BigData Exchange hopes that these incentives can motivate more people to source, migrate, and store valuable public data on Filecoin.
- Through our social media presence, we are also actively promoting Filecoin’s mission and value propositions, broadcasting and educating the broader community on data onboarding initiatives and ecosystem work groups.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
- We are a marketplace to match storage providers with verified deals.
- We have facilitated > 100,000 FIL for data storage transactions. 
```

How did you acquire the FIL cited above?
```
- We managed to facilitate > 100,000 FIL in data storage transactions because our platform serves the needs of both storage providers and data clients 
- For reference: https://polygonscan.com/address/0x5CCAda6Ab97c29EC43A81c65C4E2227Dac08Da67
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
BigData Exchange is a data storage marketplace connecting Filecoin storage providers with data communities.
We aim for liquidity and a fair price discovery process for data storage services.
In 5 months, we have facilitated more than 25 PiB of data transactions between data clients and SPs, as shown on https://www.bigdataexchange.io/

- As transactions are on chain, our marketplace offers visibility and transparency of payment and verified deals flows, which we hope can help with governance.
- Due to Fil+ cryptoeconomics incentives, storage providers have expressed willingness to bid for verified deals, resulting in a paradigm shift of negative price storage services. BigData Exchange hopes that these incentives can motivate more people to source, migrate, and store valuable public data on Filecoin. 
- We have also participated extensively in ecosystem in-person events, including FIL Austin (June 2022), FIL SG Data Onboarding Day (September 2022, co-hosted with Protocol Labs) and FIL Lisbon Network Analytics Day and CryptoEconDay.
- Through our social media presence, we are also actively promoting Filecoin’s mission and value propositions, broadcasting and educating the broader community on data onboarding initiatives and ecosystem work groups.
- We want to reach more data communities and facilitate more data storage transactions between them and the decentralised network of storage providers on Filecoin.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
BigData Exchange has made several contributions to the Large Data Notary program of Filecoin Plus.
- https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1663553503078359
- https://filecoinproject.slack.com/archives/C036JKD8NVA/p1663642009833699
- https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1663566802901949?thread_ts=1663320029.158639&cid=C01DLAPKDGX

We are also actively monitoring the DataCap utilisation rate among different storage providers to establish a transparent overview of deal making
- https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1666067621537679

Additionally, we are increasing the security of Filecoin data storage by providing a diverse range of storage provider services to Filecoin Plus data clients.
- For example, https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/431#issuecomment-1313086976

We’ve detected a potential DataCap abuse during our daily operation and raised the issue on GitHub and Slack (#fil-plus-trust-wg)
- https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/523
- https://filecoinproject.slack.com/archives/C0405HANNBT/p1668139652934889 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
BigData Exchange is a Filecoin data storage auction house and marketplace that connects clients with valuable public data and storage providers with storage capacity. We aim to provide liquidity for data storage services and have a fair and transparent price discovery process, determined by market participants. We are registered and headquartered in Singapore. Our team comprises of 6 members globally.

- With the current demand for Filecoin plus deals, there are several benefits that BigData Exchange brings to the Filecoin network:
- An innovative storage platform to incentivize more people to source, migrate, and store valuable public data on Filecoin
- A transparent marketplace to connect storage providers with data communities, which adds visibility to the SP selection process and prevents potential self-dealing activities
- Transactions on BDE are on-chain and thus provide transparency. The governance team, notaries, and community members can choose to use the information in their due diligence or governance efforts.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
- Our website: https://www.bigdataexchange.io/
- The founder is CB Tan (Filecoin Slack: CB Tan, Twitter: [@choonboontan](https://twitter.com/choonboontan))

On BigData Exchange slack workspace and Filecoin #bigdata-exchange channel, we are actively engaging in conversations with storage providers and data clients to provide help and convenience in data onboarding and deal making
- https://filecoinproject.slack.com/archives/C03NWV8RAN7/p1657968959414389 
- https://bde-join.slack.com/archives/C048SG1BSUT/p1667293791646719 

We collect feedback constantly from our users and Filecoin community members in order to build up a more transparent pipeline of data onboarding and deal making
- https://filecoinproject.slack.com/archives/C026EUH6YPM/p1663002402504709?thread_ts=1662997698.469829&cid=C026EUH6YPM 
- https://bde-join.slack.com/archives/C03PSUBH947/p1660287604435349
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Social media: 
- https://twitter.com/bigd_exchange (twitter); 
- bde-join.slack.com (slack); 
- https://github.com/BigD-Exchange (GitHub); 
- https://medium.com/@bigdata_exchange (Medium)
- We are also active on the #bigd-exchange channel on Filecoin slack

- We have participated in ecosystem initiatives and community building like FVM Foundry Early Builders, Data Onboarding WG (https://dataonboarding.filecoin.io/), Storage Providers Meet Up, Storage Providers WG
- We also organised the Data Onboarding Day Event at FIL Singapore, where we invited ecosystem partners to give talks and provide insights about the Filecoin network
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
CB Tan
Github account: [@cbtan21](https://github.com/cbtan21)
Twitter account: [@choonboontan](https://twitter.com/choonboontan), 121 followers 

Jack Fan
Github account: [@JackFsy](https://github.com/JackFsy)
Twitter account: [@JackFsy77](https://twitter.com/JackFsy77), 3 followers 

Ines Wu
Github account: [@ineswu](https://github.com/ineswu)
Twitter account: [@ineswu99](https://twitter.com/ineswu99), 40 followers
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
We were present and had given talks at many Filecoin ecosystem events in 2022:
- FIL Austin 22 - https://www.youtube.com/watch?v=RrAGvjTS_nI (June 2022)
- FIL Austin CryptoEconDay - https://www.youtube.com/watch?v=kEECkZKo76c  (June 2022)
- FIL Austin Fil+ Day - https://www.youtube.com/watch?v=ZCvObK7pymg (June 2022)
- Singapore Storage Provider Onboarding Workshop - https://www.youtube.com/watch?v=kEECkZKo76c (June 2022)
- FIL Singapore Data Onboarding Day - https://www.dataonboardingday.com/ (September 2022)
- FIL Lisbon CryptoEconDay - https://www.cryptoeconday.io/event-schedule/cryptoeconday-lisbon  (November 2022)
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We plan on allocating the DataCap based on the community governance principles of Trust, Transparency, and Accountability. 
We will support use cases that validate and encourage decentralisation and diversity, building towards a useful storage network. 

To successfully implement the target amount of DataCap, we’ll look into the following:
- Client’s website, social media, and/or any external media information;
- Client’s legal and business entity information (if available publicly);
- The relationships between the data sample, use cases, and client industries to make sure that the applicant(s) are rightful owners of the data.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
- DataCap will be allocated from the notarized address that is secured via a multi-sig.
- The Filecoin wallet private key would be kept by two dedicated persons in our team.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will make sure that clients provide the on-chain address for which the datacap is currently requested, as well as addresses that have been used in the past. Many data clients have use [bigdataexchange.io](https://www.bigdataexchange.io/) to source for a diverse range of storage providers.
During our daily operations, we check in regularly on the on-chain transactions based on wallet addresses and CIDs and ensure that the allocated DataCaps are not abused. Therefore, it’s highly likely that we will help detect any abnormal or potential abusive behaviors.

We will condcut due diligence on clients with the following questions:

**Client background**
- The nature of the clients’ organisation, project, or use case. 
- Please link to relevant website, Github repos, or social media links
- Please include as much relevant external media to provide contextual information

**Track record**
- Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, and how you executed that plan)?
- How do you plan on securing the DataCap to ensure your organisation (and its delegated members) are the ones allocating the DataCap?

**Reputation**
- Are there any disputes open against you from your previous DataCap allocations?
- Have you ever previously violated: Your own attested allocation/audit plan? Been found to be in violation of the Principles of Filecoin Plus?
- Do you agree to use the DataCap to only store data that abides by local regulations and is in compliance with the recipient miner’s terms of service?

**Network alignment**
- Do you intend to store your data in a single geography or many?
- Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?
- Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?
```
What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
BigData Exchange will document and monitor the IP addresses of SPs that are deal making with clients 
- From the IP address, we could largely tell if the miners are from the same entity

Not to ignore the case where storage providers are using proxies, we will also check with the historical behaviour of the IPs to investigate if some of the miners have similar behaviour on past deal makings. 
- For example, if one group of storage providers constantly appears in the deal makings with different clients, there is a possibility that they are from the same entity.
- This adds another layer of investigation to confirm that a client is not improperly over-allocating to a single entity.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We plan on conducting our allocation decisions in public - GitHub repositories. 
We may use email, Telegram, or other communication tools to help the due diligence process.
All progress documentation will be publicly available on the GitHub repositories.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We plan on keeping a publicly accessible record of all our allocation decisions in collaborative and shareable docs, which would be published via GitHub.

We plan on documenting and providing the following details:
- Name
- Application #
- GitHub application link
- Website
- Social media
- Contact information
- Sample data address
- Requested amount
- First allocation date & amount
- Allocation progress (%)
- Last allocation date & amount
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
We are willing to dedicate ourselves to the L2 service commitment in the Fil+ program.

We will devote a total of 10+ hours/week to governance activities, including but not limited to the following:

- We will attend the biweekly Governance Calls (approx. 2 hrs);
- We will also join at least 1 Filecoin Plus working group (2 hrs); 
- We will vote and/or comment on 1 Filecoin Plus proposal a month (2 hrs/month);
- We will respond to any Slack or GitHub questions/comments within 2 days (4 hrs/month);
- We will have internal documentation for the above process and it can be shared with the community for transparency and due diligence when necessary.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes, https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/391. 

Our goal is neither to receive DataCap nor to profit from them. For any proceeds, we will donate them back to the data client organisation and/or use them to fund/incentivize useful data onboarding initiatives in the Filecoin ecosystem. More detailed information regarding the allocation of this DataCap can be found by searching “Smithsonian” on the BigData Exchange platform (https://www.bigdataexchange.io/search?words=smithsonian). There have not been any disputes raised against us.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
We have no direct relationship with any existing notary or organisation.
```

**Comment by Kevin-FF-USA** [comment]
Hi @BigD-Exchange,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by BDE-io** [comment]
Hi @Kevin-FF-USA , we have just updated the Filecoin address to a Ledger address. Please kindly help us add back the application labels.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[703.pdf](https://github.com/filecoin-project/notary-governance/files/10159446/703.pdf)

**Comment by Kevin-FF-USA** [comment]
@BDE-io 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @BDE-io, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by BDE-io** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceaib7sfn2xm2tnid6poe47og5iy6yr4zgdcooayosohjmvrnvevec
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaib7sfn2xm2tnid6poe47og5iy6yr4zgdcooayosohjmvrnvevec

**Comment by BDE-io** [comment]
@panges2 may you confirm if we are all set now? Thanks!

**Comment by BDE-io** [comment]
@panges2 Followed your formatting on this [doc](https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit) but now it is asking me to put back the following:

> We could not find your Filecoin address in the information provided
> We could not find any Country in the information provided
> We could not find any answer to: Are you applying on behalf of yourself or an organization? in the information provided

May you advise if we should put those back in and if yes, do we put at lines after "DataCap Requested" in Core Information? Also, Filecoin address is stated already; unsure why it is requesting for it again.

Thanks.

**Comment by BDE-io** [comment]
@Kevin-FF-USA looks like review is needed. may you take a look at our application? just want to ensure everything is correct and good to go. thanks.

**Comment by BDE-io** [comment]
@panges2 @Kevin-FF-USA just want to follow up and make sure we are okay with this application. it states that review is needed.

**Comment by cbtan21** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecmgxlmvy6qswsclc6rjzgfnsty6vodxp4xagfp43sac6sb226rte
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmgxlmvy6qswsclc6rjzgfnsty6vodxp4xagfp43sac6sb226rte
