### ISSUE TITLE
Notary Applicaiton: Gate.io

### ISSUE THREAD

**Issue by Gate-io** [filecoin-project/notary-governance#704]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:Fafa
- Affiliated organization: Gate.io
- On-chain address to be notarized (recommend using a new address):f1inb55gnhypa7ygz43g4a6icgcnlovs2xdxfj62a
- Country of Operation: North America
- Region of Operation: North America
- Use case(s) to be supported: [General]
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: [Organization]

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Gate.io is one of the top 10 Exchanges with more than 10mm registered users from over 130 countries, which is committed to offer solutions on cryptocurrencies.
We learned decentralized storage and IPFS from 2017 and we are deeply moved by the economic system that everyone can be a storage provider of Filecoin afterwards. Then we started to offer FIL token related business from Fil6 to Fil distribution to serve for Fil community.
Gate.io business on Fil:
- 2017 Renrenico user migration, Fil (IOU) 
FIL (IOU) is the token with the shortest maturity period after the launch of mainnet. The circulation of FIL (IOU) is 2.4 million and Gate.io is the largest FIL (IOU) circulation and trading market in the world.
- 2020 Oct, Gate. IO completed the conversion of FIL IOU to FIL6
FIL6 is partially unlocked and converted into the mainnet FIL token every day after the mainnet launched. The mainnet FIL token transaction service was online as soon as the mainnet launched. Currently Gate.io is the largest FIL (IOU) stock and trading market in the world.
Related article：https://www.gate.io/tw/article/17994
- 2021 Aug, released all Fil6 and removed Fil6
According to the conversion rules for FIL6, Gate. io removed the FIL6 exchange on August 31st and converted the user's FIL6 balance 1:1 to FIL balance. Users can trade in the FIL market.
Related article：https://www.gate.io/tw/article/22158
- 2021 Oct, completed Fil mainnet upgrate
Filecoin (FIL) planned to launch a major network upgrade on Epoch1231620, October 26 at 21:30 UTC+8.
Related article：https://www.gate.io/tw/article/23289
Our Github handle: https://github.com/gateio

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
No statistics yet
```

How did you acquire the FIL cited above?
```
N/A
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Gate. io, the world's TOP 10 trading exchange, which supports live streaming, research reports, blogs and other products on supporting Fil financial management, lock-in gains,etc.. In the past 6 years of supporting filecoin, we had held dozens of events including the relevant financial management, lock-in, trading contests and other activities.
Related link:
https://www.gate.io/tw/article/20673  （FIL management wave 11）
https://www.gate.io/article/18194    （increase market demands of FIL management）
Other announcements:
https://www.gate.info/cn/article/19302
https://www.gate.info/cn/article/20673
https://www.gate.info/cn/article/19250
https://www.gate.info/cn/article/19248
https://www.gate.info/cn/article/19190
https://www.gate.info/cn/article/19185
https://www.gate.info/cn/article/18255
https://www.gate.info/cn/article/25096

https://www.gate.io/articlelist/ann/0（You can type “Fil” to search）

Since 2017 when we started to pay attention to Fil, Gate. io product live broadcast and research report conducted interviews with relevant important people, the whole live broadcast online, and users can interact with the community at any time.

The following is a transcript of the live broadcast and links of relevant interviews with kols:

https://www.gate.info/cn/video/4b95793dad5f4cb3a023eebe9c4e6b2a
https://www.gate.info/cn/video/bf6c8c73011343c6b5fc6dad4f614acd
https://www.gate.info/cn/video/4ebc5f1c0b0e4135a186964c7ee1c1f3
https://www.gate.info/cn/live/5c64ddb151314f8691783b8b335288ed

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
 None.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Founded in 2013, Gate.io is an exchange mainly committed to offer token store and exchange service for global users. At present, we have more than 10 million users, support more than 1,800 currency types, and can flow more than 1 billion funds in 24 hours.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Social media link:
https://twitter.com/gate_io
https://t.me/gateio
Website:
https://gate.io/
E-mail address:
support@mail.gate.io

CoinGecko introduction of gate.io
https://www.coingecko.com/zh/exchanges/gate-io
CoinMarketCap introduction of gate.io:
https://coinmarketcap.com/zh/exchanges/gate-io/

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://news.huoxing24.com/noticeDetail/0f0d9739b0973caec22e3a7cdc577c37
https://www.qklw.com/blockchain/20200716/102325.html

https://www.fromgeek.com/blockchain/144407.html

https://www.jinse.com/news/blockchain/1064077.html
https://weibo.com/ttarticle/p/show?id=2309404570188631900556
https://weibo.com/ttarticle/p/show?id=2309404534859027841295
http://finance.sina.com.cn/blockchain/roll/2020-04-21/doc-iirczymi7547231.shtml?wm=3049_0032
https://weibo.com/ttarticle/p/show?id=2309404499469038125189
https://weibo.com/ttarticle/p/show?id=2309404494398556602563
http://www.jpm.cn/article-85808-1.html

https://baijiahao.baidu.com/s?id=1660314716001287049&wfr=spider&for=pc
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
1.https://twitter.com/gate_labs?s=21  Followers：1413
2.https://www.youtube.com/channel/UCKtbVFVa1llpfCo-7r2ZwAA  Followers：10
3.https://twitter.com/gateio_es?s=21   Followers：36997
4.https://twitter.com/gateiovietnam?s=21  Followers： 2502
5.https://twitter.com/gateiorussia?s=21  Followers： 30016
6.https://twitter.com/gateiofutures?s=21  Followers： 41865
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
Please view our account.
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
https://docs.google.com/spreadsheets/d/1Enys9n2vedbPn456e-vuzpQygDF5CZG22F8YYY6l8iI/edit?usp=sharing
Following is our process:
Get more detailed information from clients according to our requirements
Verify the validity and authenticity of the information submitted, and reject applications which contacted invalid or false information.
Communicate with the applicant to provide additional information based on the suspicious points 
Score the application and find out the qualified clients.
Determine the DataCap amount according to the score
Regular audit of clients’ allocations
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We have our own official authentication system: https://www.gate.io/tw/officialverify
We can guarantee that our members are official staff of the Exchange and that the verification system will be updated in the event of personnel changes. We recommend that the list of organizations that allocate DataCap be published for review during implementation.
Also, we would like to use ledger to protect our datacap.

```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
First of all, we will review the applicants, who need to upload relevant information, including the years of registration, industry influence and so on. After the approval, we will conduct regular verification. Customers who meet the requirements can continue to use or apply for a higher volume. Those who do not meet the requirements and do not provide reasons will be rejected. We will try to find out high-quality clients with long-term storage needs.

We have the corresponding audit, such as the allocation of policy table information, and communicate with customers of different levels on different issues, including (no limit) as follows:
① Team/personal introduction
② How much DataCap do you want, and why?
③ How will you allocate your DataCap?
④Have you ever allocated before? If yes, could you give us more details?
⑤ What will you do to avoid the datacap waste?
When verifying client information, we will request verification from the applicant organization. For example, enterprises need to submit information including country, company type, company name, business license, business registration certificate number, information query website, etc. Enterprises are also required to provide information of the legal person (name/ID information, etc.), upload minutes of the board meetings and share the shareholding structure.

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Periodically review and audit DataCap usage (as metioned above, records are tracked and reviewed periodically to determine disqualification or demotion of nonconforming customers)
Users can upgrade according to the actual situation to meet the requirements
Communicate with customers regularly to understand relevant requirements and progress, and provide better service to customers
Of course, try to avoid this situation in the initial review of the application and improve the initial application information supplement during the continuous record review process.
We will inspect the use of DataCap to promptly avoid waste. Less DataCap will be granted to clients that handle their assigned DataCap improperly. Clients that demand more DataCap will be granted more after a serious investigation of how they use their DataCap.
The allocation of DataCap will be carried out in 3 rounds. The allocation decisions of one round are made according to the DataCap usage of the client in the previous round.

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, as mentioned above, all records will be public. Also, if we have detailed communication needs E-mail, we will save the screenshots.
While keeping the records, clients' demands will also be considered and discussed in a conference on GitHub for a solution. If you disagree with the result, you can file an appeal, and a voting event will be held to determine the final decision. All clients whose applications are approved are eligible to vote. If the number of votes accounts for over 80% of the total number of approved applications, the appeal will be deemed valid. If over 50% of clients vote in favor, the appeal will be approved.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
 We would reserve our allocation record and make it public through our github：https://github.com/gateio

```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L5
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
N/A
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
N/A
```

**Comment by Kevin-FF-USA** [comment]
Hi @Gate-io,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[704.pdf](https://github.com/filecoin-project/notary-governance/files/10159448/704.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi @Gate-io,

I cant find a record of receiving your email verification. If you havent done so already, please submit by 06DEC. If you have already sent, can you please re forward or paste a screenshot here to verify

**Comment by Kevin-FF-USA** [comment]
@Gate-io 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections _(pending your verification of email and slack affiliation)_.

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by Kevin-FF-USA** [comment]
@Gate-io 
(as of this writing) I not received your verification email sent to NOTARYELECTION@FIL.ORG.   If this is not received and verified with a token code response, this application will be suspended and held for the next round of elections. Please provide by the 20DECEMBER deadline along with your disclosure form.  Should there be any complications, please let me know.
