### ISSUE TITLE
Notary Application：GameWonderlab

### ISSUE THREAD

**Issue by bjchend** [filecoin-project/notary-governance#705]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Omi  
- Affiliated organization: Game Wonderlab
- On-chain address to be notarized (recommend using a new address): f1hk2tuv5qqlkcrzxxdh7sznraptqsnfhykskn2iy
- Country of Operation: Singapore
- Region of Operation:  Asia minus GCR
- Use case(s) to be supported:  Media & Entertainment, Public or Open Data, Decentralized Applications
- DataCap requested for allocation (10TiB - 10PiB): 10PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```

Game Wonderlab, the full-fledged blockchain gaming and media platform, has been using IPFS to store various data since 2019 and started to connect IPFS to the Filcoin network in 2021.

In 2022, Participate in learning <Coding with Filecoin> [http://www.studycn.work/]
https://github.com/ipfs-and-filecoin/Coding-with-Filecoin-Homework/blob/main/2.IPFS%20%26%20Filecoin%E7%AE%80%E4%BB%8B%E4%B8%8E%E6%8A%80%E6%9C%AF%E5%9F%BA%E7%A1%80/bjchend.md

The TOKEN2049 conference in Singapore at the end of September 2022, during which the ABGA (Asian Blockchain Gaming Alliance) held the Blockchain Gaming Hackathon 2022, saw a fierce battle between 100 teams, culminating in GameWonderlab winning the Silver Award.

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```

It is not convenient to disclose more details.
We bought about 6000 fil from the exchange, mainly for paying filcoin storage fees.
```

How did you acquire the FIL cited above?
```

The FIL come from exchanges. Such as Binance, OKX.

```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Participated Space Race
Participated Slingshot v1 and v2.x
Participate in learning <Coding with Filecoin>
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```

Organization: GameWonderlab 
Nature:  private company
Registration Country: Singapore
Established: 8 Sep, 2018
Size: over 100 employees
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Official Website: https://gamewonderlab.io/
Discord: https://discord.gg/gamewonderlab
Telegram ：https://t.me/GameWonderlabGW
Twitter: https://twitter.com/game_wonderlab
Medium: https://medium.com/@gamewonderlab
Youtube: https://www.youtube.com/channel/UCjvUWlPTXgnEVZ93pJYfY1w
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```

https://www.aicoin.com/article/317158.html
https://www.linkedin.com/search/results/all/?keywords=game%20wonderlab&origin=HISTORY&sid=D7l
https://www.linkedin.com/search/results/all/?keywords=game_wonderlab&origin=GLOBAL_SEARCH_HEADER&sid=%3Bmb
https://www.techflowpost.com/article/1415
https://galxe.com/gamewonderlab
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```

Twittr: https://twitter.com/bjchend
Discord: bjchend#4591
Telegram ：https://t.me/bjchend
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
As a member of GameWonderlab, I mainly spread GameWonderlab on media sites.
https://twitter.com/bjchend/status/1590725813460422656
https://twitter.com/bjchend/status/1590731389045182464
https://www.linkedin.com/posts/bj-chend-57155b256_horizon-invited-to-join-dorahacks-binance-activity-6997808628313284608-P0AF?utm_source=share&utm_medium=member_android
https://www.linkedin.com/posts/bj-chend-57155b256_zeroverses-closed-beta-test-ended-activity-6997807624234651648-VhzP?utm_source=share&utm_medium=member_android
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```

1. Based on the client's application form, due diligence will be conducted to ensure that the information and data are true and compliant.
2. Customers are rated according to company size, time of establishment, and data type.
(https://github.com/filecoin-project/notary-governance/files/10008733/Newtoken.Notary.Application.xlsx)

3. I can conduct due diligence within 5 business days of request submission.
4. I can award DataCap within 2 business days of passing the survey.
5. I plan to allocate 100TiB, 500TiB to 1PiB per client in the LDN program.

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
1. A hardware wallet will be used to store the keys for DataCap address.
2. Conduct personal due diligence with the help of operational records, community exposure and chat logs.

```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```

1. verify the application information submitted by the business user and verify the ownership of the certificate or other supporting information. Do due diligence on the business
2. Check the applicant's social media, chat or email logs, and other publicly available information. Do applicant due diligence

Questions.
1. Please introduce yourself. Through which social accounts can you be reached?
2. Please introduce your organization. Through which social accounts can you be contacted by your organization?
3. What is your role in the organization?
4. How do you plan to use DataCap?
5. What data will be stored with DataCap? Please provide a sufficient sample of data.
6. justify why you need such a large number of DataCap's?
7. how many storage providers will be using DataCap to store data?
8. Is there a storage provider you know or are working with nearby? If so, please let me know.

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```

1. Conduct personal due diligence with the help of https://filplus.d.interplanetary.one/ and various statistics from filfox.info.
2. Review a sample of DataCap already in use.
3. We will create a customer integrity mechanism that will score customers by different directions.
For example, a customer can earn bonus points for deploying less than 25% of DataCap on any storage provider; bonus points will be deducted for an excess of 50% of DataCap.

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
In public via github repo.
 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
In public via github repo.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4:  >10 hours of engagement per week
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None.
```

**Comment by Kevin-FF-USA** [comment]
Hi @bjchend,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[705.pdf](https://github.com/filecoin-project/notary-governance/files/10159449/705.pdf)

**Comment by Kevin-FF-USA** [comment]
@bjchend 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
