### ISSUE TITLE
Notary Application: Bocheng

### ISSUE THREAD

**Issue by bocheng456** [filecoin-project/notary-governance#706]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:bocheng
- Affiliated organization: Xi'an Bocheng Space-Time Data Technology Co., Ltd.
- On-chain address to be notarized (recommend using a new address):f1d3m2gb35rgwchyxkfap5d5hy6ect5lgbhm3wcky
- Country of Operation: China
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
The company joined the Filecoin project in June 2021, bringing together capital from Xi'an, Beijing, and Shanghai to deeply participate in the construction and development of IPFS. The company has achieved a storage scale of PB level, and has five domestic leading positions in software algorithm optimization, hardware acceleration, architecture design, system security, and operation and maintenance expertise, and maintains good cooperative relations with upstream companies such as Inspur, DELL, and Dawning. . In 2021, the company has obtained software copyrights for multiple IPFS server network monitoring and alarm systems, making continuous contributions to the development and long-term development of the IPFS ecosystem. 3 absenteeism, node numbers: f01075086, f01871353, f01207045.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f01075086: 7294 FIL
```

How did you acquire the FIL cited above?
```
We obtained these FIL tokens from market purchases, mining rewards, and staking tokens from Filet.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
1. The company has now stored an effective computing power of 1.2PiB, ranking: 2325. （https://filfox.info/zh/address/f01075086）
2. Create a WeChat official account to publicize IPFS and Filecoin
    https://mp.weixin.qq.com/s/rJMf2cTJmBv5B0HNkeMtyQ
    https://mp.weixin.qq.com/s/80YpqovmK2uWe0DYLeF65A
    https://mp.weixin.qq.com/s/y0cbJR3Qjv_v5Zmdh44Zaw
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
I have not submitted filecoin bugs, I have developed monitoring software, https://github.com/sanxunl/lotus-monitor
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Xi'an Bocheng Space-Time Data Technology Co., Ltd. was established on March 25, 2021. It is a limited liability company registered for industry and commerce in mainland China and has more than ten employees. The company is a professional IPFS storage provider of the whole industry chain, and a high-tech company integrating software and hardware research and development, production and sales. The company focuses on the research and development of core software and hardware technologies such as distributed cloud servers, cloud computing ecological architecture, AI artificial intelligence, parallel computing, etc. The company has established a domestic top software and hardware research and development technical team, mainly composed of professors from the computer department of a key university in Northwest China. Its scientific research team, the chief architect of a listed company in the city, and the professional team of capital operation and investment are led.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Weixin Official Account: 博骋科技
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://m.weibo.cn/7500377140/4830683308232690
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
douyin: 行走的催先生 followers: 4.6w 
douyin: 车圈李sir followers: 541
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
None.
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We’ve studied several cases from previous notary applications, and we totally agree with what IPFSUnion has proposed. 
Base on some allocation rubrics shared by Andrew Hill at Fil+ Day, we have further standardized our allocation strategy in detail. The most important thing about DataCap allocation is to ensure that client utilizes DataCap to store real data. so I firstly specify some rules to figure out the true identity of the applicant.
* Browse their official website to get a general understanding of the company or the individual. 
* Query the company's registration information from government related websites to make sure the information he submitted is truth.
* Ask some questions to know about the applicant's position/organization/plan/use case etc. 
* Then We will classify applicants based on their industry reputation and scale etc. All applicants will be divided into eight categories to determine the amount of datacap they will get. The following Rubric will be the primary guideline I use when evaluating a client and determining their DataCap allocation.   
You can see it: https://docs.google.com/spreadsheets/d/1dD8aI3lsZGRp5rUWiULeRaPwFc7Z2z8tkzpdnTY-tyo/edit?usp=sharing
These scoring guidelines can serve as a tool of assessment and further to add a level of consistency across the board.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Use hardware wallets, make distribution plans in advance, strictly screen applicants for information security, and accept the supervision of the filecoin network at any time
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Select customers with stable operation and practical storage experience, conduct detailed investigations on the actual background, and have no violations before
1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, WeChat, etc.)
2. If you represent an organization, what is the name, nature, country of incorporation, date of establishment and appointed officers of your organization?
3. In which regions do you intend to use DataCap?
4. What is the use case for the DataCap you are requesting?
5. How many miners do you plan to allocate? Specify if you have a specific miner you want to allocate DataCap to.
6. Have you applied for a DataCap to another notary and was it accepted or rejected? Are there still reliable DataCaps?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Firstly, from the questions about use plan and further investigation, I can know some details about his allocation plans. When scoring applicants according to the above sheet, the more geographical distribution, use cases and miners assign, the higher score he will get and the more datacap clients are likely to get.  
Next, we will keep tracking clients’ information such as the DataCap distribution records, related miner addresses and storage providers, to ensure that they are consistent with their words and deeds.
Finally, a reward and punishment mechanism will be established. If someone over-allocating datacap to a single entity, I will refuse further allocation and issue a warning which will be public to the Filecoin community. On the contrary, reputable client have the opportunity to obtain more datacap.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
1. All allocation decisions will happen in public in the following[repository](https://github.com/filecoin-project/filecoin-plus-client-onboarding). Since all interactions are intended to occur publicly, most of the allocation decisions should be self-explanatory.
2. I will build a profile of every client who obtained DataCap from me in a public place
3. If there are any complaints about notary, a dispute resolution application can be filed to the Notary Governance after 14 days since its original challenge data. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Github.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L5. 10+ hours per week on average.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
NA.
```

**Comment by Kevin-FF-USA** [comment]
Hi @bocheng456,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[706.pdf](https://github.com/filecoin-project/notary-governance/files/10159450/706.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi @bocheng456,
I cant find a record of receiving your email verification. If you havent done so already, please submit by 06DEC. If you have already sent, can you please re forward or paste a screenshot here to verify

**Comment by bocheng456** [comment]
At 2022-12-06 13:37:26, "Kevin" ***@***.***> wrote:

Hi @bocheng456,
I cant find a record of receiving your email verification. If you havent done so already, please submit by 06DEC. If you have already sent, can you please re forward or paste a screenshot here to verify

**Comment by Kevin-FF-USA** [comment]
@bocheng456 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
