### ISSUE TITLE
NOtary Application: EMO Capital

### ISSUE THREAD

**Issue by Bruce0726** [filecoin-project/notary-governance#707]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:  Bruce
- Affiliated organization: EMO capital
- On-chain address to be notarized (recommend using a new address):f16r3tvdn5fbngym3by6a6nrmne5iznrg3ev3imxa
- Country of Operation: Asia Pacific Region
- Region of Operation:  Asia minus GCR
- Use case(s) to be supported: Professional services (storage hosting service provider, disaster recovery, data warehouse), development tools (package manager, automatic notary, Web2 to Web3 integration), apps, DApps, user content (personal storage), public or open data (scientific data sets, research data, government or history, media and entertainment (video, photos, NFT)
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Please answer here.
Since joining the ipfs-filecoin ecosystem in 2019:
We invested and incubated filecoin ecological technology service provider (mining technology service company 1475IPFS, mining technology service company FILMINE);
We funded and incubated the finddata Eco-Development Application Project filecoin (fido);
We provide f01823264 f01840219, f01794835 f034258... Miners provide fil margin support;

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Please answer here.
We are currently holding and management from the fund circulation of about 800000 LP fil, of which about 130000 have been put into cooperation fil miners node in the margin (f01823264 f01840219, f01794835, f034258...)

How did you acquire the FIL cited above?
```
Please answer here.
Input from our fund LP

## Industry Reputation
### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Please answer here.
Emo capital was founded in 2017 in China (now relocated to Singapore). The founding team of EMO Capital came from NOAH Holdings, China's largest private wealth management company, Harvest Fund, CICC... In 2017, he participated in the initiation and decision of the raising and investment management of the first "blockchain industry fund" in mainland China (investing in Bitland equity, etc.), and was the pioneer of the first batch of traditional financial institutions in mainland China to the "blockchain digital economy". emo is committed to industrial investment in the field of blockchain digital economy /web3. With cycle investment as our core value, we decentralize the first-level VC market, second-level spot market and first-level semi-mining market of the entire blockchain digital economy industry, leading the traditional wealth compliance in mainland China and the Asia-Pacific region to enter the field of blockchain digital economy /web3 and help the industry development.
Since entering the industry in 2019, it has successively invested in filecoin Ecological mining technical service company 1475IPFS, and invested and incubated the mining technical service company FILMINE).
Invested and incubated filecoin eco-development application projects: finddata,fido
Preach and promote the development of filecoin in the Chinese community, and have been invited to participate in many filecoin Chinese community meetings, such as 20201026 with Distributed Capital, hashkey was invited by Protocol LABS Chinese community to attend the filecoin Open House and speak as a guest of the roundtable forum.

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Please answer here. 
N/A

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Please answer here.
Founded in 2017, Emo capital is currently registered in China, Singapore (headquarters) and several tax haven jurisdictions, and has offices in China/Singapore.

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Please answer here.
Official website: http://www.emocapital.io; 
College official twitter: @ capital_emo

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Please answer here.
(http://www.emocapital.io/en/nd.jsp?id=22&fromColId=106)
(https://twitter.com/colinevran/status/1576266833291714561)

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Please answer here.
http://www.emocapital.io; 
twitter: @ capital_emo  2300+


Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
Please answer here.
(https://twitter.com/colinevran/status/1576266833291714561)(https://twitter.com/capital_emo/status/1576123277105561601)
(http://www.emocapital.io/en/nd.jsp?id=19&fromColId=106)
(http://www.emocapital.io/en/nd.jsp?id=20&fromColId=106)
(http://www.emocapital.io/en/nd.jsp?id=21&fromColId=106)
(http://www.emocapital.io/en/nd.jsp?id=22&fromColId=106)

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Please answer here.
We plan to allocate 100% data cap within 6 months; 
College we ensure that a single client application amount does not exceed the limit of my income authorized by 20%; 
College to ensure that our audit a single client application limit the frequency of no more than once a week; 
College we ensure that a single client access lines will not less than three phases release rather than a one-time release, in order to prevent the excessive centralization; 
College we ensure that each grant our amount will not less than 5% of the shares reserved for non-profit organizations to the client.

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Please answer here.
We will use the hardware wallet for DataCap related accounts and monitor and audit DataCap usage on a weekly basis.

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Please answer here. 
We do a full KYC audit of our clients to ensure that we give the appropriate number of data caps to clients that meet our standards and have smooth access to the filecoin storage network. We will confirm our key work from the aspects of authenticity requirements, rationality requirements, consistency requirements, and the ability of clients to use datacap, while ensuring that clients can accumulate more credit.

Authenticity requirements:
1. Verify the basic information of the client, including the registration place, registration time, business license, business scale, industry reputation, the relationship between the entity and the handler, the written evidence of the authorized handler of the entity, etc. (provide the official website/social media account that can be publicly verified);
2. Investigate the amount of data requested, the data type, the address on the filecoin chain, the copyright notice and legal compliance, the previous storage method, and whether it was public or encrypted.

Requirements for reasonableness:
Verify the application demands of the client and the actual needs of the operating subject, verify the business demands of the operating subject's counterparts in different regions, and finally evaluate the deviation between the application data limit and the approval limit, and check the applications from all regions and various data types.

Consistency requirements:
Verify the consistency of the data types requested by the client application and the data samples provided; In the later stage, the method of random retrieval transaction is not excluded to confirm that the data promised by the client when applying for data quota is stored in the corresponding storage end.

DataCap capabilities used by clients:
Ensure that the client provides a clear and feasible execution plan for data generation, transaction mode, and SP selection. This helps us allocate DataCap quotas and monitor the actual DataCap usage on the client in the future.

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Please answer here. 
1. To ensure that transactions are not distributed among individual SP entities, we will synchronize with other notary public and cross-check with them regularly to address these concerns.
2. The audit data center distribution statistics from https://filplus.d.interplanetary.one.

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Please answer here. 
both

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Please answer here.
We're going to have a publicly searchable, public Google table.

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
Please answer here.
L4


## Track Record
### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Please answer here.
N/A

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
Please answer here.
N/A

**Comment by Kevin-FF-USA** [comment]
Hi @Bruce0726,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Bruce0726** [comment]
Relevant questions have been answered by email@Kevin- FF-USA

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by Bruce0726** [comment]
Thank you. I haven't received your reply in my email. If necessary, you can communicate through email or reply here.

**Comment by Bruce0726** [comment]
> Thank you. I haven't received your reply in my email. If necessary, you can communicate through email or reply here（bruce@emocapital.com.cn

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[707.pdf](https://github.com/filecoin-project/notary-governance/files/10159452/707.pdf)

**Comment by Bruce0726** [comment]
<img width="461" alt="截屏2022-12-06 21 27 51" src="https://user-images.githubusercontent.com/112363493/205924948-7c50e736-4a0e-4a47-aa77-b0409a16cff2.png">

I have sent you a confirmation email of relevant information through the corporate email address 11.25。

**Comment by Bruce0726** [comment]
thanks！I have replied to you about kyc through the corporate email on November 25.
Thanks for your rating. I tried again to send an email to you through the corporate email address.

<img width="466" alt="截屏2022-12-06 21 24 31" src="https://user-images.githubusercontent.com/112363493/205934022-b35de8fd-bf3a-4bd6-93c2-f9c35fc58837.png">

**Comment by Kevin-FF-USA** [comment]
@Bruce0726 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by Bruce0726** [comment]
i got it , thanks！

**Comment by panges2** [comment]
Hi @Bruce0726, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by panges2** [comment]
Hi @Bruce0726,  this is another reminder to get your ledger verified as soon as possible. Thank you!
