### ISSUE TITLE
Notary Application: New Huo Pool

### ISSUE THREAD

**Issue by NewHuoPool** [filecoin-project/notary-governance#708]
# Notary Application 

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:New Huo Pool
- Affiliated organization: 
- On-chain address to be notarized (recommend using a new address):f17vbgxycvxodtfjgsz5dimbgp33sdsnmbyirmdmq
- Country of Operation: North America
- Region of Operation: [North America, Europe, Greater China Region (GCR), Asia minus GCR]
- Use case(s) to be supported: [Developer Tools (Package Managers, Automatic Notaries,  Web2 to Web3 integrations), Decentralized Applications, User Content (Personal Storage), Public or Open Data (Scientific datasets, esearch data, government or historic, Media & Entertainment (Videos, photos, NFTs)]
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: [Organization]

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
New Huo Pool (former HuobiPool) belongs to  frontier technology business segment  of New Huo Technology (HK1611) (former Huobi Technology) ,our major business is mining and mining-pool development. New Huo Pool is committed to a comprehensive service platform for blockchain infrastructure construction and operation. Relying on our own hardware and software technology and professional operation and maintenance team, New Huo Pool provides mine construction, mining machine sales, mining machine hosting, mining-pool operation, wallet scheme, mining machine maintenance and other businesses. Our team has been deeply engaged in BTC and FIL mining, and we will continue to pay attention to other innovative projects.
In October 2020, Huobi Global officially launched FIL.  With 7 years of experience in digital asset trading services and the world's top security and risk control system, Huobi Global has provided secure and reliable digital asset trading and asset management services to tens of millions of users in over 130 countries around the world!

 
In February 2021,Huobi Mall launched "Filecoin Full Storage Computing Power", a Filecoin hardware rental and software management service business, aiming to provide users with a safe, transparent, reliable and convenient channel to participate in IPFS mining.
In March 2021, Huobi launched the FIL Lodo event and trading ranking competition.
In March 2021, the "FIL Limited Time Mining" campaign was launched on the Huobi Global  Site.
In April 2022, Huobi Asset Management, a wholly-owned subsidiary of FireCoin Technology, released the Blockchain Storage IPFS Infrastructure Mining Fund, as an important Web3.0 layout for professional investors. IPFS Infrastructure Mining Fund invests in relevant crypto-firecoin mining industry activities and supports enterprises covering the ecology of the relevant crypto-firecoin mining industry, and is the only special fund in the industry that runs through the entire industry chain.
Firecoin Technology Academy produces IPFS and Filecoin related videos to help users get involved.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f01885280: 78,028.56 fil
f01768970: 63,505.02 fil
f01885260: 60,940.92 fil
f01845679: 35,553.22 fil
f01825841: 103,143.97 fil
f01807389: 64,384.80 fil
f01825842: 58,204.34 fil
f01882234: 93,935.40 fil
f01805566：132,386.07 fil
f01916645：60,301.36 fil
f01395920：157,574.77 fil
f01250204：157,501.11 fil
f01114807：105,196.68 fil
f01210520：79,945.17 fil
total: 1,250,601.39 fil
```

How did you acquire the FIL cited above?
```
We provide technical services and build storage nodes by combining multiple parties.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
The Huobi Group, in collaboration with Protocol Labs, has announced the launch of the Huobi Filecoin Incubation Center with a $10M USD fund dedicated to supporting the Filecoin ecosystem.

The center will focus on three main areas: incubation, investment, and community development. It will support promising Filecoin developers, promote Filecoin-related academic research, and foster ecosystem development. Both Huobi and Protocol Labs believe that IPFS and Filecoin will be the foundation of the next generation of internet, creating a safer, more equal, and accessible system to distribute and store data - our most valuable asset in the 21st century.

Seeing the Filecoin ecosystem’s enormous potential, Huobi believes that similar to decentralized finance, decentralized storage solutions such as Filecoin will lead a new wave of blockchain revolution and bring more innovation opportunities to developers. With Protocol Labs as the technical advisor to the investment fund, the incubation center will provide support for Filecoin developers and the community.

The launch of the Huobi Filecoin Incubation Center and the ecosystem fund mark an important collaboration between the Filecoin community and a digital asset services provider. The two together will promote academic research and technical development of Filecoin and foster a stronger Filecoin ecosystem globally,” Wu added.
To help develop Filecoin globally, the Huobi Filecoin Incubation Center and ecosystem fund will focus on the following key areas:
Incubation. Collaborate with existing Filecoin accelerators and incubators, providing additional courses leveraging Huobi’s advantages in exchange solutions and Asia community.
Investment. Huobi would provide funding to promising projects in the Filecoin ecosystem, with Protocol Labs providing technical guidance and support.
Community development. Huobi and Protocol Labs will co-host annual summits and quarterly meetups globally, creating more cross border connections and communications among developers, miners, users, and token holders.

This incubation center is the second of its kind following the Huobi DeFi Labs and will help Huobi Group conduct research, investment, incubation, and community building in the Filecoin ecosystem.
URL:https://filecoin.io/blog/posts/huobi-group-launches-filecoin-incubation-center/
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
New Huo Pool (former HuobiPool) belongs to  frontier technology business segment  of New Huo Technology (HK1611) (former Huobi Technology) ,our major business is mining and mining-pool development.. New Huo Pool is committed to a comprehensive service platform for blockchain infrastructure construction and operation. Relying on its own hardware and software technology and professional operation and maintenance team, New Huo Pool provides mine construction, mining machine sales, mining machine hosting, mining pool operation, wallet scheme, mining machine maintenance and other businesses. The team has been deeply engaged in BTC and FIL mining, and continues to pay attention to other innovative projects.
Registered country: BVI(British Virgin Islands) 
Number of staff: 30-50 people
Date of establishment: June 2021 (original HPT main body in 2019)
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website：[https://pool.newhuotech.com/](https://pool.newhuotech.com/home)
twitter：@Huobi_pool
Facebook：Huobi Pool
instagram：huobipool
YouTube：https://www.youtube.com/channel/UCNM-cVsa41TDdKv2IMBZRPw
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://filecoin.io/blog/posts/huobi-group-launches-filecoin-incubation-center/
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
@HuobiTech，46.4K+Followers，https://twitter.com/HuobiTech 
@Huobi_pool，11.5K+Followers，https://twitter.com/Huobi_pool
@HuobiGlobal，1.2M+Followers，https://twitter.com/HuobiGlobal
@TheHuobiNFT，77.4K+Followers，https://twitter.com/TheHuobiNFT 
@HuobiEdu，5.4K+Followers，https://twitter.com/HuobiEdu
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
N/A
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
In the allocation plan, clients will be rated L1-L5 based on their personal reputation and allocation plan. Different levels of clients correspond to different DataCap. The higher the level, the larger the DataCap.
The detailed scoring criteria is attached below：https://docs.google.com/spreadsheets/d/18GZoSt1xDTrlu0oO1fJbmyyNalha0rA-JWYgdCFos1M/edit#gid=0
The above is for commercial entity clients. We reserve another 50% DataCap for priority allocation to non-profit public welfare organizations, especially those committed to education, healthcare, Web3.0 and environmental protection. We conduct thorough due diligence on public welfare organizations. The first step is to check the legitimacy of the organization's establishment from the government website of the jurisdiction where it is located. The applicant of the DataCap needs to provide a certificate issued by the local government to support it, and also investigate the governance of the organization from the official website and external news media to see its project operation process.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will exclusively use offline hardware wallets to verify accounts associated with Datacap allocations. Multi-signature wallets will be used in the future when we have more clients.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will conduct a detailed due diligence on the client, which is divided into two stages: pre-allocation evaluation and follow-up audit while the allocation is in progress.
Before approve the allocation, we will evaluate the client's principal name, principal jurisdiction, registration number, business location, contact person and title, email address, description of main business, DataCap requested for allocation, data sample link, source of data to be stored, proof of ownership or authorization, whether the data is confidential (industry secrets, state secrets or national security), list of SPs to distribute storage deals, storage location and allocation ratio, the principle of selecting the above SPs, the wallet address of the DataCap application, etc., and the above information will be made public on GitHub to be monitored by the governance team and the community. Customer due diligence form is available at the link:  https://github.com/NewHuoPool/DataCap-Application//issues/new?template=Client-Due-Diligence-Form.yml
In addition, other more private information including but not limited to the subject registration certificate, proof of principal business address and other information will be sent by email to (nhp@xinhuotech.com). The subject registration certificate, proof of principal business address, and other materials that are inconvenient to disclose will only be used for New Huo Pool's due diligence on the client, and a confidentiality agreement will be signed with the client, which will be open to the governance team and monitored by the governance team .
In the allocation process, we will continuously track the client's DataCap distribution records, related SPs addresses, storage providers and other information to ensure that their words and actions are consistent, including
A list of consolidated content identifiers ("CIDs") for verified transactions, including transaction CIDs and SPs IDs (showing the usage of the allocated DataCap).
A description by the customer of the data being stored and how it is being handled, and that we will conduct random spot checks of the stored data and take action if it does not comply with the Filecoin Plus principles and the initial allocation plan, with warnings or restrictions on subsequent DataCap allocations, as appropriate.
Credit rating of clients who have successfully allocated DataCap, which will affect  the next DataCap application, and users with a good credit rating may increase the DataCap.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. Regular and continuous checks are performed using various statistical tools such as https://filplus.d.interplanetary.one/ and filfox.info to ensure that the allocated DataCap has not been abused or misused.
2. DataCap will be allocated in stages. If any improper use or abuse of the allocated DataCap is detected, we will immediately contact the clients and may reduce or even cancel the unallocated DataCap depending on the circumstances.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be public in the Github repo, and be monitored by the Filecoin Plus governance team, notaries and the community.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
In addition to keep records in GitHub, we also plan to cast all distribution records as NFT or use smart contract backup storage when FVM launch in the future. Considering the diligence data that clients don't wanna to go public, we will create a special database to store for data auditing and analysis, and we will be welcome to any auditing.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4. Maintain a ranking in Leaderboard in the top 10% of Notaries. Attend 2 Governance calls a month. Join 2 working groups. Respond to SLACK inquiries within 2 days. Vote/Comment on >2 proposals a month
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
N/A
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
N/A
```

**Comment by Kevin-FF-USA** [comment]
Hi @NewHuoPool,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[708.pdf](https://github.com/filecoin-project/notary-governance/files/10159453/708.pdf)

**Comment by NewHuoPool** [comment]
Hi, @galen-mcandrew，we have received the score. Thank you for your hard work! We've made some updates to improve the score, so please check it out!

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will conduct a detailed due diligence on the client, which is divided into two stages: pre-allocation evaluation and follow-up audit while the allocation is in progress.

Before approve the allocation, we will evaluate the client's principal name, principal jurisdiction, registration number, business location, contact person and title, email address, description of main business, DataCap requested for allocation, data sample link, source of data to be stored, proof of ownership or authorization, whether the data is confidential (industry secrets, state secrets or national security), list of SPs to distribute storage deals, storage location and allocation ratio, the principle of selecting the above SPs, the wallet address of the DataCap application, etc., and the above information will be made public on GitHub to be monitored by the governance team and the community. 
Customer due diligence form is available at the link: https://github.com/NewHuoPool/DataCap-Application//issues/new?template=Client-Due-Diligence-Form.yml

In addition, other more private information including but not limited to the subject registration certificate, proof of principal business address and other information will be sent by email to (nhp@xinhuotech.com). The subject registration certificate, proof of principal business address, and other materials that are inconvenient to disclose will only be used for New Huo Pool's due diligence on the client, and a confidentiality agreement will be signed with the client, which will be open to the governance team and monitored by the governance team .

In the allocation process, we will continuously track the client's DataCap distribution records, related SPs addresses, storage providers and other information to ensure that their words and actions are consistent, including，
A list of consolidated content identifiers ("CIDs") for verified transactions, including transaction CIDs and SPs IDs (showing the usage of the allocated DataCap).
A description by the customer of the data being stored and how it is being handled, and that we will conduct random spot checks of the stored data and take action if it does not comply with the Filecoin Plus principles and the initial allocation plan, with warnings or restrictions on subsequent DataCap allocations, as appropriate.
Credit rating of clients who have successfully allocated DataCap, which will affect  the next DataCap application, and users with a good credit rating may increase the DataCap.
```
We have made a flow chart for our clients to better engage in the Filecoin project.
![流程图](https://user-images.githubusercontent.com/117884185/206401964-394f242e-d789-4a1b-8415-aa0bbafb7f88.png)
We will do a simple survey of our customers before allocation, and the survey can be filled out directly on GitHub and disclosed in GitHub. Customer due diligence form is available at the link: https://github.com/NewHuoPool/DataCap-Application//issues/new?template=Client-Due-Diligence-Form.yml

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1.Upfront detailed and effective KYC, due diligence and explanation of rules are essential to encourage clients to assign Datacap to different SPs.
2. Regular and continuous checks are performed using various statistical tools such as https://filplus.d.interplanetary.one/ and filfox.info to ensure that the allocated DataCap has not been abused or misused.
3. DataCap will be allocated in stages. If any improper use or abuse of the allocated DataCap is detected, we will immediately contact the clients and may reduce or even cancel the unallocated DataCap depending on the circumstances.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be public in the Github repo, and be monitored by the Filecoin Plus governance team, notaries and the community.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
In addition to keep records in GitHub, we also plan to cast all distribution records as NFT or use smart contract backup storage when FVM launch in the future. Considering the diligence data that clients don't wanna to go public, we will create a special database to store for data auditing and analysis, and we will be welcome to any auditing.

In case of any disagreement/dispute, then initiate an allocation decision discussion publicly on slack or github, if the decision still remains controversial after that, then send a dispute resolution application to Notary Governance team within 10 business days, the governance team will rule accordingly. Besides, we can escalate the dispute issue to Notary Govenance call for discussion, all the notaries and  governance team will decide on the dispute.
```

**Comment by Kevin-FF-USA** [comment]
@NewHuoPool 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by NewHuoPool** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecrtt6gejivqosusrkfs3yvlnrnv7zscqiqchfbduudq4glanm2lc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrtt6gejivqosusrkfs3yvlnrnv7zscqiqchfbduudq4glanm2lc

**Comment by NewHuoPool** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebijrdh6lkvobrluredh24f3sllwxnrmseuhskmpxwedboqni2gja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebijrdh6lkvobrluredh24f3sllwxnrmseuhskmpxwedboqni2gja

**Comment by NewHuoPool** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebj4bx3wf637ix7dniv4zxbahkms2iv6tnprnxcxgopqksar5rfgg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebj4bx3wf637ix7dniv4zxbahkms2iv6tnprnxcxgopqksar5rfgg
