### ISSUE TITLE
Notary Application:METAVERSE DATA MINING

### ISSUE THREAD

**Issue by METAVERSEDATAMINING** [filecoin-project/notary-governance#709]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: MDM
- Affiliated organization: METAVERSE DATA MINING PTE.LTD.
- On-chain address to be notarized (recommend using a new address): f1g2qkuam73a6lhhhmzz4clc6w2ljbn5qfxu2sjmi
- Country of Operation:  Singapore, Korea.
- Region of Operation:  Asia minus GCR
- Use case(s) to be supported: We support all cases, but especially focus on public welfare and  Decentralized Applications related data.
- DataCap requested for allocation (10TiB - 1PiB): 500TiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
We have joined the Filcoin project in 2021, and have been committing to the construction of the Filcoin community, Filcoin mining, and Filcoin ecosystem.
Our github account is:  https://github.com/METAVERSEDATAMINING
These are our nodes: f01877862、f01846877、f01840776 、f01846857
For better helping the development of Filecoin network, we have developed the following products:
Filecoin Data Center: https://open.mdmlab.io/
Pledge Joint-mining platform: https://pledge.mdmlab.io
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
We have 240K pledges and 43PiB power for now.(f01877862、f01846877、f01840776 、f01846857)
```

How did you acquire the FIL cited above?
```
We got these with the growth of our business.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
MetaVerse Data Mining was invited to join the Filecoin project in 2020 and as a member of the Filecoin community, our team has been working on Filecoin community building and network development.

During the construction, we launched the Filecoin Data Center(https://pledge.mdmlab.io/)
This Center is a Filecoin blockchain data service platform that provides developers with an API interface to easily and quickly access relevant data and statistical analysis on the Filecoin chain.
Through our data center, you can search the data of sector, node, even whole network,and assess the real value of nodes through the financial reporting model. From a professional perspective, our platform focuses on node production costs, records historical data, and analyzes the stability of nodes.

In order to further help the development of Filecoin network, we have also launched a Pledge Joint-mining platform platform for servicing the major participants of the network (owners, equipment owners, token holders, technical service providers) https://pledge.mdmlab.io/

Because considering the current situation, these participants face the following challenges:
1. Owners: Most of owners joined in Filecoin in 2021 and have great expectations for the development of the Filecoin network. They have been supporting the stability and growth of the Filecoin network and they are eager to have more pledged tokens to expand their production.
2. Equipment Owners: Most of equipment owners provide leasing services of sealing for owners since 2021, especially sealed equipment owners,but most of their equipment is spare now.
3. Token holders: At present, most token holders are optimistic about the future growth of Filecoin , but considering the market price, the Fil token they hold can not bring them additional interest.
4. Technical service providers: These participants are mostly dependent on the node owner or device owner. Generally, they are R&D or O&M personnel. At present, they are faced with the problem that there is no more sealing demand and they are in a state of loss of income.

Every partial participants have their value, and if you want to form a team of these participants ,it would require a significant investment in labour power and capital.


This Pledge Joint-mining platform we designed aims to organise these participants and make advantage of their strengths and values.

With our platform, we expect that owners can reasonably assess the true value of their nodes through this professional and perfect evaluation system, deposit their nodes to our platform, borrow tokens from holders at the real value of their nodes, so they can invest in a new round to pledge and seal, and return a portion of the output to the holders.
And in this process, they will look for more equipment owners and package service providers in the market to contribute their value, and allow them to use their own equipment and services in exchange for their returns.

In addition to this, our Pledge Joint-mining platform has a mature procedure of node evaluation, cost measurement, revenue monitoring and risk protection. It also allows for the complete migration of nodes to a safer location in the event of an unavoidable risk, thus protecting the token that loaned to the owners from further loss.

We believe that with the launch of the pour Pledge Joint-mining platform, more and more participants will gather around us and rely on this platform to leverage their strengths and to get their fair share of returns. It will also play a more positive role in the stability and growth of the Filecoin network.

At the same time, we also pay close attention to the progress of FVM and retrieval. We are looking for suitable partners to enter this network all the time. We expect that we give our own value and gain profits in the process of the birth, growth and maturity of Filecoin network.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
We are a Chinese team which has been formed since 2003.
And we have been in the software development industry since the C++ epoch, mainly involved in large scale application development,which covers various areas such as Disk Driver, Network Drivers, large scale of P2P transmission, etc.

We were invited by a famous SP to participate in the Filecoin Slingshot race in 2020. And after that, we constantly provide a series of underlying technical services in Filecoin area,such as mining, data analysis, cluster optimization and reconstruction, operation and maintenance monitoring and alerting,etc.
So far, we have supported over 100 nodes ,and with 1.4EiB power.

But with the change of policy in Greater China since 2021, we chose to  establish our new company MetaVerse Data Mining in Singapore and moved our business to a more policy friend region.

In addition to the above services and products we mentioned, we are planning to devote more in the Web3.0, join more blockchain projects, and expand our research and service in blockchain security. 
And after the launch of FVM, we will focus more on developing smart contracts, NFT and other applications on FVM.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Official Website:https://www.mdmlab.io/
Filecoin Data Center: https://open.mdmlab.io/
Pledge Joint-mining platform: https://pledge.mdmlab.io
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Our company focus on technical services and haven't paid much attention to propaganda. Twitter is the only social media we have for now, view here: https://twitter.com/METAVERSEDATA_
You can find more information about us on our website and related product pages.
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://twitter.com/METAVERSEDATA_
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
None
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
For ensuring the fair and decentralization of DC allocation, and ensure that we will grant the appropriate DataCap to the clients,Our review procedure will follow this  steps:

1.Investigate the authenticity of data:
(1)Fully verify the basic information of the clients, including the company's registration location and time, company size,the authenticity of the business license, and proof of qualifications.
(2)Review whether the requested datacap is reasonable, and review the data types, diversity of stored data, and whether they are public or encrypted are required.

2.The fair of allocation
1. In principle, we support all reasonable use cases.
2. For the Fil+,we will not assign more than 20% of dc to the same SP,and it also suitable to the limits of clients when they apply ldn.
3. For the LDN,we plan to distribute our data to at least 2 SPs in different regions.For the ldn,we require clients to have at least 3 SPs.

3、 Review the use of clients
In order to prevent abuse, we require clients to have a specific plan about data allocation and the criterion of SP selection.
If the clients has the experience in Datacap application, we will refer to the previous DataCap consumption and allocation as judgement . And make sure the share has not been allocated to a same SP.
We will also regularly retrieve the clients' data,about three times a month.

Allocation criteria:
We have create a template of score mechanism,focusing on company's business type, data type, selection of SP, etc. We will mark application based on this mechanism, and determine the scale and speed of our allocation based on the final score.

You can view the allocation criteria and plan here:https://docs.google.com/spreadsheets/d/1Yen03EH4Y7hMibyWO-mbdztbSQPqZKpFsnjln1yDfKU/edit?usp=sharing
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hardware wallet will be used to store the keys associated with the DataCap allocation address securely. 
We will form a team of four to control the multisig-wallet,and every signature will be monitored.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
There are our review procedure:

I. Client information survey
For individuals
Conduct identity authenticity and verify basic information. Check the client's Slack account and Github, and to prevent abuse,the registration time of github need to be more than 30 days.

For companies/organizations
We will review the following information(including but not limited to):
Company registration certificate/registration number
Registration date
Legal person information
Type of business
Authoritative websites where can identity the company's main information 
Official website/social media where can prove the company's business
Data source
Data sample
Allocation plan
List and information of selected SPs

II. KYC procedure

We will ask clients the following questions and make detailed review to ensure that there is no abuse.

- What is your relationship with the this entity? For your company, please describe its size, business type, industry reputation,  real operation location, other related entity.All the client need to pass the qualification verification.

-Where did you learn about Filecoin? When did you join Filecoin?

-Do you have any contributions or any disputes in Filecoin, please describe.

-Regarding the data you intend to store, where it sources from? Do you have any proof of ownership or authorization? Are there any other relevant entities associated with this data?

-Has your company or organization applied for DataCap before？If it has, please note the link，and it is better to show the details of DC allocations and SPs information.

-Please provide a sample of data that can prove the authenticity of your data, no less than three types.

-Please describe your DataCap allocation plans . Include percentage of allocation, time of allocation, number of allocations, area of allocation, number of SPs, etc.The more detailed, the better.

-Please confirm that you data is a public database that can be retrieved by anyone on the Network.

-How do you intend to prevent the abuse of DataCap.

-If there is a dispute during the application procedure? Can you guarantee response in time?
```
Client need to answer these question a form on github:https://github.com/METAVERSEDATAMINING/Client-form-of-Filecoin-Plus/issues/new?template=client_Information.yaml

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. We will constantly review the various statistics from https://filplus.d.interplanetary.one/ and filfox.info to avoid DataCap abuse.
2. The clients list we create will be a ledger that can track the allocation process in time.This is the list we made:https://docs.google.com/spreadsheets/d/1pHvhQsCAMSR9Z6BYVJPjE6L5G_s71Jlzz4WTm8Z9WiE/edit?usp=sharing
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Without a doubt, we will make all our allocation records publicly available on the Github repository and keep a real-time record of all allocated clients and their corresponding SPs via publicly available online documentation.
Where a review involves client privacy, we disclose details of the application process if there is a private application (email, telegram, etc.) process. In the event of a customer dispute, we will respond to the information available and review it again in the first instance.
```
Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We will make the allocation decision tracker public on Github,and will constantly review the various statistics from https://filplus.d.interplanetary.one/and filfox.info to avoid DataCap abuse.
 
We will keep records of clients' information, including company details, email address and the source of data.Clients' information will be strictly review when we make the allocation decision.This  is list we mentioned before:
https://docs.google.com/spreadsheets/d/1pHvhQsCAMSR9Z6BYVJPjE6L5G_s71Jlzz4WTm8Z9WiE/edit?usp=sharing
 
If there are any disputes, we will be responsible for initiating a public discussion of the allocation decision on slack or github and if a dispute remains after the decision, a dispute resolution request will be sent to the notary governance team within 7 working days and the governance team will decide accordingly. In addition to this, when a dispute arises on a matter of community principle, for better governance we recommend that the dispute is escalated to a notary governance call for discussion and all notaries and the governance team will adjudicate the dispute.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
I would like to be an L4 Notary.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No,it‘s our first time to apply.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None.
```

**Comment by Kevin-FF-USA** [comment]
Hi @METAVERSEDATAMINING,

Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by METAVERSEDATAMINING** [comment]
Hi,@Kevin-FF-USA.We already sent the verification email to you.If you have any questions, please contact us.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[709.pdf](https://github.com/filecoin-project/notary-governance/files/10159454/709.pdf)

**Comment by Kevin-FF-USA** [comment]
@METAVERSEDATAMINING 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by METAVERSEDATAMINING** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedahzqjkunlmrujcky6ssdouzcg45oi45tug6cbogmv74u4dnlsci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedahzqjkunlmrujcky6ssdouzcg45oi45tug6cbogmv74u4dnlsci

**Comment by METAVERSEDATAMINING** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecr5ocxuekfg6hnqu2inkjnoluprvkw6tw7npist2doben4hmpwww
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecr5ocxuekfg6hnqu2inkjnoluprvkw6tw7npist2doben4hmpwww

**Comment by METAVERSEDATAMINING** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceb3vtgfkyd5agkhfshylv4gjnu4citxmbvzthjxf6ynfjkihuly3o
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3vtgfkyd5agkhfshylv4gjnu4citxmbvzthjxf6ynfjkihuly3o

**Comment by METAVERSEDATAMINING** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceawjjnif6isf6qx6ajovk2i4ouq6gsqhcpxlu4u3vbah2pxoifa4q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawjjnif6isf6qx6ajovk2i4ouq6gsqhcpxlu4u3vbah2pxoifa4q
