### ISSUE TITLE
Notary Application:6block

### ISSUE THREAD

**Issue by mingW1** [filecoin-project/notary-governance#71]
# Notary Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a notary, please fill out the following form. 

## Core Information
- Name: 6block
- (Optional) Affiliated Organization: 6block
- Website / Social Media: [6block.com](https://6block.com/en),[filfox.info](https://filfox.info)
- On-chain Address(es) to be Notarized:N/A
- Region of Operation: Greater China
- Use case(s) to be supported: Profession services(Long-term Backups,Long-term Log Storage),Web 3.0/DApps, Media&Entertainment
- DataCap Requested: 1 PiB  

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).

```
6block is one of the biggest Filecoin Miners and Mining solution providers, who operates more than 40 miner ids(the list is too long, so here we just put some of them: https://filfox.info/zh/address/t02623， https://filfox.info/zh/address/t07850， https://filfox.info/zh/address/t05315, https://filfox.info/zh/address/t010241, etc.)

We participated in Filecoin Mining from the testnet phase, and helped to report several bugs including the [inflation bug](https://medium.com/6block/6block-spotted-filecoin-inflation-bug-and-now-a-member-of-its-security-fellowship-b14496bcf5a4#:~:text=6Block%20found%20an%20inflation%20bug,over%20decades%2C%20similar%20to%20Bitcoin.). As a result, we are now a member of Filecoin Security Fellowship.

6block also played an important role in the Space Race and the Slingshot competition, and was the most efficient miner in the competition. We released our optimized version(community version) miner to the public. https://github.com/6block/6miner

Our team member White Lee and hayeah are active in Filecoin community, helped answering technical questions in Slack and [contribute to Filecoin project](https://github.com/filecoin-project/lotus/commits?author=hayeah) too.

Moreover, we built the most popular Filecoin explorer [filfox.info](https://filfox.info), which help Filecoin team, miners and common users to understand the latest status about the network.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.

```
More than 1,500,000 FIL token at stake. (the list is too long, so here we just put some of them: https://filfox.info/zh/address/t02623， https://filfox.info/zh/address/t07850， https://filfox.info/zh/address/t05315, https://filfox.info/zh/address/t010241, etc.)

```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

```
As a member of the Filecoin community:
- 6block made series videos to help miners and common user to understand how Filecoin works. https://www.youtube.com/channel/UCDPDdczcoVNNM-vWFxNT-9w
- 6block built the v28 params downloading service for Chinese community. https://6block-miner.filfox.info/
- 6block relese community version of our optimized miners. https://github.com/shannon-6block/lotus-miner/releases
- 6block helped to answer questions in Slack

- 6block build filfox.info, both the explorer and the web wallet.

6block team has become one of the most import technical leader in Filecoin ecosystem.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side). 

```
- Our team members are member of Filecoin Security Fellowship
- 6block spotted Filecoin inflation bug(critical). https://medium.com/6block/6block-spotted-filecoin-inflation-bug-and-now-a-member-of-its-security-fellowship-b14496bcf5a4
- 6block member hayeah fixed timing bug. https://github.com/filecoin-project/lotus/pull/1560

```

### External Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

```
- Nature of 6block: 6Block focuses on “Unicorn” projects in the blockchain area, providing solutions for cryptocurrency mining, including highly efficient mining programs, mining pools, hardware, cloud mining, and wallets. 6block is currently the most popular Filecoin mining solution provider. filfox.info made by 6block team is the most reputable explorer in the industry
- country of registration: China
- size of the organization: 40
- time since inception: 2019

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

```
- websiste: https://6block.com/en
- named officers: White Lee, Hayeah
- social media profiles:
	- https://medium.com/@6block
	- https://www.reddit.com/user/6block
	- https://twitter.com/6block2
	- http://t.me/sixblock
	- https://youtube.com/channel/UCDPDdczcoVNNM-vWFxNT-9w
	- https://space.bilibili.com/527190559
	- https://www.douyu.com/8380714

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

```
- social media profiles:
	- https://medium.com/@6block
	- https://www.reddit.com/user/6block
	- https://twitter.com/6block2
	- http://t.me/sixblock
	- https://youtube.com/channel/UCDPDdczcoVNNM-vWFxNT-9w
	- https://space.bilibili.com/527190559
	- https://www.douyu.com/8380714
	
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?

```
We plan to support multiple use cases; the percentage will be determined according to the real requirements from our customers and partners.
- 20% - Profession services(Long-term Backups,Long-term Log Storage)
- 30% - Web 3.0/DApps(DeFi,Layer2 data etc.) 
- 50% - media & entertainment (video & music streams)
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.

```
We will consider the following factors while allocation the DataCap:
* Reputation of the organization
* Use cases diversity
* Scale&Frequency of allocation
* Safety Precautions
* Transparency of customers
* The relationship between customer and miner
```

Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap? 

```
We will allocate the datacap according to our internal evaluation of the stored data. 
High-value data should be with higher priority of allocation and amount/rate.

The priority of different data types are as following:
1. Profession services(Long-term Backups,Long-term Log Storage), which is the most valueable data
2. Web3 and DApp data, which is important for the blockchain industry
3. Entertainment data, which is huge and used the most frequently data
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
We will do different level of KYC for different level of DataCap, depending on the DataCap size one requested.
As will do Due Diligence for as many details as possible about the client who applied for big DataCap.
```

### Client Due Diligence
How will you vet your Client to ensure they are spending that DataCap responsibly?

```
We will let clients provide their information and evidence of Client Reputation, Data, Diversity and Decentralization, Allocation Strategy and Track Record. And we will check the information。
Once we find that a client has improper behaviour, we will reject the Client's applicaiton during the next allocation.
```

What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them? 

```
We will ask clients some questions refer to the list of questions linked below:
https://github.com/filecoin-project/notary-governance/blob/main/notaries/templates/sample-client-application.md 
```

What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?

```
Firstly, we will ask clients to seperate Datacap to different entity.
Secondly, clients need to disclose their allocation records, and we will remind them if the allocation is not reasonable. If clients ignore it, their applicaitons will be rejected in the future.

```

### Bookkeeping Plan
Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?

```
Yes, we will keep records in details for audit requests. The records will be public in github.
```

Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 

```
Both, we will have the public github repo like this natory application, and also ask more detailed information(which might be private somehow) over email of telegram.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.

```
none
```

Cumulatively, how much DataCap have you previously successfully allocated? 

```
none
```

Have there been (or are there still) any disputes raised against you from your previous DataCap allocations? 

```
none
```

**Comment by ficherar** [comment]
> # Applicazione notarile
> ### SI PREGA DI NOTARE CHE QUALSIASI DOMANDA PRESENTATA PRIMA DELLA DEFINIZIONE DEL FIP DI GOVERNO O DEL PRESENTE REPO SARÀ ELIMINATA
> Per candidarsi come notaio, si prega di compilare il seguente modulo.
> 
> ## Informazioni di base
> * Nome: 6block
> * (Facoltativo) Organizzazione affiliata: 6block
> * Sito web/social media: [6block.com](https://6block.com/en) , [filfox.info](https://filfox.info)
> * Indirizzo(i) su catena da autenticare:N/A
> * Regione di operazione: Grande Cina
> * Casi d'uso da supportare: servizi professionali (backup a lungo termine, archiviazione dei registri a lungo termine), Web 3.0/DApps, media e intrattenimento
> * DataCap richiesto: 1 PiB
> 
> _Si prega di rispondere alle domande sotto forma di paragrafo, sostituendo il testo dicendo "Rispondi qui". Includi più dettagli che puoi nella tua risposta!_
> 
> ## Allineamento della rete a lungo termine
> ### Impegno di tempo
> Descrivi la natura e la durata della tua affiliazione con il progetto Filecoin. Si prega di includere handle di Github, ID miner, progetti o contributi significativi (con collegamenti).
> 
> ```
> 6block is one of the biggest Filecoin Miners and Mining solution providers, who operates more than 40 miner ids(the list is too long, so here we just put some of them: https://filfox.info/zh/address/t02623， https://filfox.info/zh/address/t07850， https://filfox.info/zh/address/t05315, https://filfox.info/zh/address/t010241, etc.)
> 
> We participated in Filecoin Mining from the testnet phase, and helped to report several bugs including the [inflation bug](https://medium.com/6block/6block-spotted-filecoin-inflation-bug-and-now-a-member-of-its-security-fellowship-b14496bcf5a4#:~:text=6Block%20found%20an%20inflation%20bug,over%20decades%2C%20similar%20to%20Bitcoin.). As a result, we are now a member of Filecoin Security Fellowship.
> 
> 6block also played an important role in the Space Race and the Slingshot competition, and was the most efficient miner in the competition. We released our optimized version(community version) miner to the public. https://github.com/6block/6miner
> 
> Our team member White Lee and hayeah are active in Filecoin community, helped answering technical questions in Slack and [contribute to Filecoin project](https://github.com/filecoin-project/lotus/commits?author=hayeah) too.
> 
> Moreover, we built the most popular Filecoin explorer [filfox.info](https://filfox.info), which help Filecoin team, miners and common users to understand the latest status about the network.
> ```
> 
> ### Esposizione della posta in gioco
> Si prega di citare il token totale in gioco (attualmente disponibile, bloccato come garanzia, maturato nel tempo) e qualsiasi prova comprovante.
> 
> ```
> More than 1,500,000 FIL token at stake. (the list is too long, so here we just put some of them: https://filfox.info/zh/address/t02623， https://filfox.info/zh/address/t07850， https://filfox.info/zh/address/t05315, https://filfox.info/zh/address/t010241, etc.)
> ```
> 
> ## Reputazione del settore
> ### Reputazione nel protocollo
> Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow.
> 
> ```
> As a member of the Filecoin community:
> - 6block made series videos to help miners and common user to understand how Filecoin works. https://www.youtube.com/channel/UCDPDdczcoVNNM-vWFxNT-9w
> - 6block built the v28 params downloading service for Chinese community. https://6block-miner.filfox.info/
> - 6block relese community version of our optimized miners. https://github.com/shannon-6block/lotus-miner/releases
> - 6block helped to answer questions in Slack
> 
> - 6block build filfox.info, both the explorer and the web wallet.
> 
> 6block team has become one of the most import technical leader in Filecoin ecosystem.
> ```
> 
> ### In-protocol Security
> Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references who might be able to substantiate your contributions (e.g. if you've filed several bugs, please cite who you've communicated with on the Filecoin side).
> 
> ```
> - Our team members are member of Filecoin Security Fellowship
> - 6block spotted Filecoin inflation bug(critical). https://medium.com/6block/6block-spotted-filecoin-inflation-bug-and-now-a-member-of-its-security-fellowship-b14496bcf5a4
> - 6block member hayeah fixed timing bug. https://github.com/filecoin-project/lotus/pull/1560
> ```
> 
> ### External Reputation
> Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
> 
> ```
> - Nature of 6block: 6Block focuses on “Unicorn” projects in the blockchain area, providing solutions for cryptocurrency mining, including highly efficient mining programs, mining pools, hardware, cloud mining, and wallets. 6block is currently the most popular Filecoin mining solution provider. filfox.info made by 6block team is the most reputable explorer in the industry
> - country of registration: China
> - size of the organization: 40
> - time since inception: 2019
> ```
> 
> Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
> 
> ```
> - websiste: https://6block.com/en
> - named officers: White Lee, Hayeah
> - social media profiles:
> 	- https://medium.com/@6block
> 	- https://www.reddit.com/user/6block
> 	- https://twitter.com/6block2
> 	- http://t.me/sixblock
> 	- https://youtube.com/channel/UCDPDdczcoVNNM-vWFxNT-9w
> 	- https://space.bilibili.com/527190559
> 	- https://www.douyu.com/8380714
> ```
> 
> Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
> 
> ```
> - social media profiles:
> 	- https://medium.com/@6block
> 	- https://www.reddit.com/user/6block
> 	- https://twitter.com/6block2
> 	- http://t.me/sixblock
> 	- https://youtube.com/channel/UCDPDdczcoVNNM-vWFxNT-9w
> 	- https://space.bilibili.com/527190559
> 	- https://www.douyu.com/8380714
> 	
> ```
> 
> ## Diversity and Decentralization
> ### Use Case Diversity
> (Optional) Any additional information you'd like to share about the use case(s) you plan to support?
> 
> ```
> We plan to support multiple use cases; the percentage will be determined according to the real requirements from our customers and partners.
> - 20% - Profession services(Long-term Backups,Long-term Log Storage)
> - 30% - Web 3.0/DApps(DeFi,Layer2 data etc.) 
> - 50% - media & entertainment (video & music streams)
> ```
> 
> # Allocation Plan
> ## Concreteness of Allocation Plan
> ### Allocation Strategy
> How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can.
> 
> ```
> We will consider the following factors while allocation the DataCap:
> * Reputation of the organization
> * Use cases diversity
> * Scale&Frequency of allocation
> * Safety Precautions
> * Transparency of customers
> * The relationship between customer and miner
> ```
> 
> Are there any internal processes you plan on impelementing regarding the target, amount, or rate at which you'll allocate DataCap?
> 
> ```
> We will allocate the datacap according to our internal evaluation of the stored data. 
> High-value data should be with higher priority of allocation and amount/rate.
> 
> The priority of different data types are as following:
> 1. Profession services(Long-term Backups,Long-term Log Storage), which is the most valueable data
> 2. Web3 and DApp data, which is important for the blockchain industry
> 3. Entertainment data, which is huge and used the most frequently data
> ```
> 
> How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
> 
> ```
> We will do different level of KYC for different level of DataCap, depending on the DataCap size one requested.
> As will do Due Diligence for as many details as possible about the client who applied for big DataCap.
> ```
> 
> ### Client Due Diligence
> How will you vet your Client to ensure they are spending that DataCap responsibly?
> 
> ```
> We will let clients provide their information and evidence of Client Reputation, Data, Diversity and Decentralization, Allocation Strategy and Track Record. And we will check the information。
> Once we find that a client has improper behaviour, we will reject the Client's applicaiton during the next allocation.
> ```
> 
> What questions will you ask to ensure the Client can properly handle the DataCap you intend to allocate to them?
> 
> ```
> We will ask clients some questions refer to the list of questions linked below:
> https://github.com/filecoin-project/notary-governance/blob/main/notaries/templates/sample-client-application.md 
> ```
> 
> What processes will you employ to confirm that a Client is not improperly over-allocating DataCap to a single entity?
> 
> ```
> Firstly, we will ask clients to seperate Datacap to different entity.
> Secondly, clients need to disclose their allocation records, and we will remind them if the allocation is not reasonable. If clients ignore it, their applicaitons will be rejected in the future.
> ```
> 
> ### Bookkeeping Plan
> Do you plan on keeping records of your allocation decisions? If so, with what level of specificity do you intend to respond to any audit requests?
> 
> ```
> Yes, we will keep records in details for audit requests. The records will be public in github.
> ```
> 
> Do you plan on conduct your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both?
> 
> ```
> Both, we will have the public github repo like this natory application, and also ask more detailed information(which might be private somehow) over email of telegram.
> ```
> 
> ## Track Record
> ### Past allocation
> Have you previously received DataCap to allocate before? If so, please link to any previous applications.
> 
> ```
> none
> ```
> 
> Cumulatively, how much DataCap have you previously successfully allocated?
> 
> ```
> none
> ```
> 
> Have there been (or are there still) any disputes raised against you from your previous DataCap allocations?
> 
> ```
> none
> ```

C'è una signora che mi dice che mi vuole dare 500.000 euro perché staorenfo
