### ISSUE TITLE
Notary Application: ORIGIN Storage

### ISSUE THREAD

**Issue by llifezou** [filecoin-project/notary-governance#710]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information

- Name:ORIGIN Storage
- Affiliated organization: ORIGIN Storage
- On-chain address to be notarized (recommend using a new address):f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
- Country of Operation: North America
- Region of Operation: North America,  Asia minus GCR
- Use case(s) to be supported: Web 3.0 applications, Web 2.0 applications, user data, scientific data, media, entertainment, and more
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment

Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).

```
As a distributed storage and blockchain practitioner, we started the research and application of IPFS in 2018 and caught up with Filecoin again in 2019. After closely studying the Filecoin white paper and related technologies, we believe it was the only business scenario that could be landed since the development of blockchain technology. ORIGIN storage was finally set up, and lots of human and material resources were invested into Filecoin during the continuous operation.

1. In 2018,  some of our codes were merged. For example: 
https://github.com/btfslib/go-libp2p-quic-transport/commit/944de2ea4fec3bbab65d9d36577b7128142b361a

2. We went through all the test networks of Filecoin (T02417 is still active in the main network: https://filfox.info/en/address/f02417):
Testnet1: T017267
Testnet2: T01030
Spacerace: T02417, T017273

3. Co-developed a decentralized netdisk with Blockcasting Cloud in slingshot. (Slingshot registration ID: 676715867) (https://github.com/litianc/slingshot/blob/master/participants/BlockcastingCloud.md) 

4. After continuous investment and efforts, the company has become an essential contributor to the Filecoin network, with a total of 600P+ computing power. We also have an integrated Filecoin storage solution covering IDC server room, hardware, and software. To improve data encapsulation and storage efficiency, we conduct deep optimization in the modules of encapsulation efficiency, scheduling, space-time proof, cluster architecture, etc.

5. We strive to promote the development of IPFS and Filecoin by establishing partnerships with several web 2.0 industry giants and facilitating the storage of valid data in Filecoin.
```

### Stake Exposure

Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).

```
The power of Origin Storage continues to increase, we now have more than 870P power, and the total pledge amount exceeds 500w FIL!

List of disclosed SPs(the rest are not disclosed)：https://docs.google.com/spreadsheets/d/1KHXyg4hVqRIiSYu5gIQ535gKFDYONi__D2EYoPLKmG0/edit?usp=sharing
```

How did you acquire the FIL cited above?

```
Early Space Race Earning & Mining Rewards & Purchases
```

### In-protocol Reputation

Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

```
1. Participated in the entire process of Filecoin's test net/space race/mainnet development(https://filfox.info/en/address/f02417)

2. Started in 2019, actively promoted IPFS and Filecoin technology. In October 2020, while many miners did not understand the protocol lab, we wrote many articles to explain the Filecoin economic model and spoke in public to support PL.

3. We developed the decentralized network disk in Slingshot (ID: 676715867) together with Blockcasting Cloud. 
(https://github.com/litianc/slingshot/blob/master/participants/BlockcastingCloud.md)

4. We continuously participate in the development of Filecoin, issue reporting, and code contribution.
(https://github.com/filecoin-project/lotus/issues/7833.
https://github.com/filecoin-project/lotus/pull/6635)

5. We became Venus Master to participate in the construction of the community and make contributions: slack: cryptostack-zou (https://filecoinproject.slack.com/archives/CEHHJNJS3/p1635833794026900)

6. Become the leading SP of Solana Lab to store blockchain snapshot data in Filecoin.

7. Become an early builder member of fvm.

8. Actively participate in the construction of the filecoin community and contribute to the command line HD wallet: https://github.com/llifezou/fil-wallet
```

### In-protocol Security

Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 

```
We keep working on Filecoin, and our colleague has proposed several issues and pr involved in the development of Filecoin.
https://github.com/filecoin-project/lotus/pull/6635
https://github.com/filecoin-project/lotus/pull/7844
https://github.com/filecoin-project/lotus/pull/7512
https://github.com/filecoin-project/lotus/pull/8208
https://github.com/filecoin-project/lotus/issues/7132
https://github.com/filecoin-project/lotus/issues/6669
```

### Organizational Reputation

Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.

```
We are now located worldwide (USA, Canada, Singapore, Hong Kong) with over 60 employees. We have been using IPFS since March 2018 and have been involved in Filecoin since the very beginning.

We have over 10 IDC server room resources worldwide, 500P+ computing power under management.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

```
Official website: https://www.originstorage.io/
Twitter：https://twitter.com/OriginStorage_
Named officer: 
Andy Guo CEO, ex Node Capital (one of the biggest crypto fund of China)  Director of Investment;
Hover Fang CMO, ex CEO assitant of 21 Vianet ( Nasdaq listed company);
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)

```
Youtube: Originstorage Introduction
https://www.youtube.com/watch?v=dJXJOvCdmP4&ab_channel=ORIGINStorage

(ORIGIN Storage focuses on IPFS distributed storage, helping to upgrade Web 3.0 comprehensively.)
https://www.sohu.com/a/460685605_381979

(Top 4 Open Source Distributed Storage_ORIGIN Storage Wins "2020 IPFS Most Influential Company" Award)
https://blog.csdn.net/weixin_39776787/article/details/111390399


ORIGIN Storage provides an efficient FIL mining solution to help achieve the multi-billion dollar distributed storage market
https://www.marketwatch.com/press-release/origin-storage-provides-an-efficient-fil-mining-solution-to-help-achieve-the-multi-billion-dollar-distributed-storage-market-2021-12-06?tesla=y

Thriving Filecoin Ecosystem, Promising Future | ORIGIN Storage
https://www.asiaone.com/business/thriving-filecoin-ecosystem-promising-future-origin-storage

IPFS & Filecoin – The Cornerstone of Building a Metaverse Ecosystem | ORIGIN Storage
http://wdpp.org/press-release/ipfs-filecoin-the-cornerstone-of-building-a-metaverse-ecosystem-origin-storage-33118/

ORIGIN Storage: Store NFTs with IPFS & Filecoin in Seconds
https://www.rfdtv.com/story/45780564/origin-storage-store-nfts-with-ipfs-filecoin-in-seconds

FVM: The Next Milestone for Filecoin, Welcome All Developers | ORIGIN Storage
https://www.marketwatch.com/press-release/fvm-the-next-milestone-for-filecoin-welcome-all-developers-origin-storage-2022-02-16

Decentralized Storage: A Further Integration of Web 3.0
https://www.originstorage.io/en_US/blog/DecentralizedStorageAFurtherIntegrationofWeb3

The Value Drivers of the Filecoin Network
https://www.originstorage.io/en_US/blog/TheValueDriversoftheFilecoinNetwork
```

### Individual Reputation

Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.

```
ORIGINStorage Twitter: https://twitter.com/OriginStorage_ 
ORIGINStorage channel: https://t.me/originstoragec
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)

```
Filecoin Foundation: Filecoin Storage Provider Spotlight — Origin Storage
https://filecoinfoundation.medium.com/filecoin-storage-provider-spotlight-origin-storage-58301b77c4f5

shares insights on Filecoin Virtual Machine at FIL Toronto Summit
https://finance.yahoo.com/news/chainup-mining-subsidiary-origin-storage-075702714.html

HS88 and Origin Storage signed an MOU on big data storage construction and technical support, and will start building Web 3.0 infrastructure
https://n.news.naver.com/article/123/0002279307?sid=101
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)

### Allocation Strategy

How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.

```
The allocation strategy is to make DataCap better used. We adopt different review strategies according to customer types and a phased allocation strategy for each allocation of DataCap, which can be outlined as follows.
(i) Different types of customers have different allocation and review rules.
(ii) Approved DataCap will be delivered to customers gradually to ensure that we are able to monitor the correct use of DataCap shares by our customers.

1. Allocation of shares by customer type
First, we divide the applicants into (i) general users and web3 developers (ii) corporate entities or organizations. It is expected that 30% of our DataCap quota will be allocated to general users and web3 developers, and the remaining 70% will be allocated to corporate entities or organizations.

Therefore, there are different rules that apply to these two types of applicants.
(i) For regular users, identity verification (the real name verification) will be performed. In order to promote the use of Filecoin among the general user community, the verification for general users will be minimized by allocating a maximum of 3 times per person, with a maximum of 1Tib per application, and the approval of the second application will be based on the applicant's rating.


(ii) For web 3.0 developers, who will be the ones strongly supported. Only the time of their GitHub registration and the site of their web3.0 application will be verified to ensure their authenticity. There is no limit to the number of applications, with a maximum of 10Tib per application. The approval of the second application will be based on the applicant rating and the impact of the applicant's application.

(iii) For entities, 70% of the DataCap quota is used on data storage for social enterprises, well-known Internet companies, research institutes, public welfare organizations, and other organizations. Since the early DataCap quota market is not mature enough, we will be proactive in acquiring valuable applicants. We have worked with several web2.0 companies who are potential applicants for our quota and are well known in China and the world. We are bringing this applicant data to Filecoin, which will help the ecological landing of Filecoin.

2. Phased allocation of shares
First, any applicant's DataCap will be allocated in stages, and the applicant will usually only receive 20% of the allocated share in the first stage. Only when it is determined that the current stage share is being used correctly will it be possible to receive the allocation of the next stage share. Applicants must meet the requirements: (i) storing only approved and compliant data (ii) not trading with a single SP.
Secondly, we will evaluate the applicant's score for each phase, which will affect their next application.

Applicant's scoring adjustment rules: Refer to the scoring rules form to rate applicants: https://docs.google.com/spreadsheets/d/1elUmUpJlQbsVoJlL3K8ibLQP88t0oLCL36TaTiq5KoU/edit?usp=sharing

The allocation process is basically as follows.
(i) Each applicant provides application information to initiate the review process.
(ii) Based on the information provided by the applicant, an initial review will be conducted, and the applicant must have a reasonable need for data storage. The requested share size must match the data storage requirements.
(iii) Applicants who fail the initial review will be asked to provide additional information, and applicants who fail the re-examination and refuse to provide additional information will be rejected.
(iv) For corporate entities or organizations, applicants that pass the initial screening will proceed to the due diligence phase; for individual users and web3 developers, they will proceed to the DataCap review phase.
(v) For entities or organizations that pass the due diligence and individual users and web3 developers that pass the preliminary review, the rating scoring process will begin. There may be cases where the allocated share is less than the share applied for by the applicant, which will be awarded based on their storage needs and the rating results.
(vi) Notify applicants in written form whether they have been awarded or denied.
(vii) Tracking and spot-checking the applicant's DataCap usage on an ongoing basis.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
The key allocated to the DataCap is protected on the multi-signature hardware wallet.
```

### Client Due Diligence

How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 

```
The following content will include a survey of applicant information prior to approval and a review of DataCap usage after approval.

1. Information survey of applicants
(i) Only their identity will be verified for individual users, and the basic verification will be ensured. In contrast, another verification is minimized to promote the use of Filecoin in the general user community.
(ii) For web 3.0 developers, we will verify their GitHub registration years and project websites to minimize other verifications and promote the use of Filecoin in decentralized applications.
(iii) For corporate entities or organizations, we will verify their entity information (including but not limited to registration number, registration date, registration certificate, board members, and beneficiaries), business type, data source, data samples, detailed usage plans, etc.

2. Review of usage
Post-allocation review will be conducted on an ongoing basis to avoid misuse of DataCap, guarantee the original purpose of Filecoin plus, and perform the duties of a notary. The review is based on the principle that it is the responsibility and obligation of the applicant to use the DataCap only for approved purposes. Since DataCap is allocated on the principle of phased distribution, subsequent quotas for applicants who do not pass the review will be delayed and even canceled. The specific review path is as follows (not excluding the continuation of additional review provisions).
(i) We require DataCap applicants to provide transaction Cid and minerID. For unencrypted data, we conduct random retrieval spot checks, and if the applicant has any violations of DataCap distribution, we will take measures to stop further distribution.
(ii) We verify that the user distributes the requested DataCap to at least three SPs to improve data storage security while reducing the possibility of misuse.
(iii) We establish a reputation scoring system to rate the applicant during the usage process, which will affect the applicant's next phase of quota distribution and the next DataCap application, further promoting the applicant's proper use of the quota he/she has received.

During the process of performing due diligence, we will ask the following basic questions to the applicant first:
(i) Self-introduction
(ii) Knowledge of Filecoin
(iii) Business requirements and data format
(iv) Data sources and data samples
(v) If the application is approved, the minerID that costs DataCap, and the detailed usage plan such as the quota between miners
(vi) Data security, any violation of local laws
(vii) Profitable or not

We will maintain the principle of conducting reasonable investigations without burdening the applicants with investigations and combine this with a phased distribution mechanism to ensure proper use of DataCap by our customers and do our best to promote Filecoin.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.

```
1. Conduct regular and continuous reviews with the help of various statistics from https://filplus.d.interplanetary.one/ and filfox.info to ensure that the assigned DataCap is not abused or misused according to the deal.

2. DataCap will be allocated in stages. If any improper use or misuse of the allocated DataCap is found, the unallocated DataCap may be reduced or even canceled. The score may be penalized to further ensure the proper use of the DataCap.

Applicants with abnormal usage will be contacted and dealt with promptly.
```

### Bookkeeping Plan

Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 

```
Github repo
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?

```
Saving more detailed information in own GitHub repo, while making it public in the public repository：
https://github.com/filecoin-project/filecoin-plus-client-onboarding
https://filplus.info/
```

### Engagement in Program

Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 

```
L4
```

### Past allocation 

Have you previously received DataCap to allocate before? If so, please link to any previous applications.

```
1. We are reviewing a client request: https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2502
2. We reviewed an applicant, allocated 100T of DataCap, and conducted a total of three reviews. The application IP is #2278, because its github account is flagged, this application is inaccessible.
```

## Disclosures

Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.

```
None
```

**Comment by Tom-OriginStorage** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedceochix426vgrmxizmcedqyk2hhyrt6glakjkb255fc6rqvf674
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedceochix426vgrmxizmcedqyk2hhyrt6glakjkb255fc6rqvf674

**Comment by Kevin-FF-USA** [comment]
Hi @llifezou,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by llifezou** [comment]
Hi @Kevin-FF-USA , I have sent, thank you

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[710.pdf](https://github.com/filecoin-project/notary-governance/files/10159455/710.pdf)

**Comment by llifezou** [comment]
@Kevin-FF-USA @galen-mcandrew Hi,  I updated our Service Level Agreement to L4, a total of three of us are involved in Fil+ related matters, and we will attend every meeting and remain active.
When my update is complete, our application status is abnormal, please help us, thank you

**Comment by Kevin-FF-USA** [comment]
@Tom-OriginStorage 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by Tom-OriginStorage** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedniiqtrz4vlq7jdwdq45yc75ihbna5ay3knewzhk2yhjo7vssvou
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedniiqtrz4vlq7jdwdq45yc75ihbna5ay3knewzhk2yhjo7vssvou

**Comment by Tom-OriginStorage** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebkxwrj6wtrts4uumfyg5k7nnarjaxxg6vy65a2avbwsb3bfb23xo
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkxwrj6wtrts4uumfyg5k7nnarjaxxg6vy65a2avbwsb3bfb23xo

**Comment by Tom-OriginStorage** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecwo7ev6ksxlcidmgtkd2i5lqp2oom3kvczad4s3wvqu2xp6yb5ca
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwo7ev6ksxlcidmgtkd2i5lqp2oom3kvczad4s3wvqu2xp6yb5ca
