### ISSUE TITLE
Notary Application: Straitdeer Pte. Ltd.

### ISSUE THREAD

**Issue by xlcbd** [filecoin-project/notary-governance#712]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Lingchao Xu
- Affiliated organization: Straitdeer Pte. Ltd.
- On-chain address to be notarized (recommend using a new address): f1ugvbxoxiihned23yjcy73k3cjp3weu5dl5hdpga
- Country of Operation: Singapore
- Region of Operation: Asia minus GCR
- Use case(s) to be supported: Professional Services, Decentralized Applications, Public or Open Data, Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB): 100TiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Bitdeer (Straitdeer) was founded in 2020, and we’ve been a part of the Filecoin community since then; Filecoin is one of our key exploration projects.
We are primarly a crypto miner, over 2 years in the industry, and we launched the Filecoin cloud business in October 2021 to support the long-term deveplopment of the Filecoin ecosystem; the website for our Filecoin cloud operations is https://hashrate.bitdeer.com. 
We have participated in the FVM Early Bird Program and are members of multiple Filecoin Storage Provider Working Groups. 
We have built the Web3 infrastructure platform Paralinker and the website is https://www.paralinker.com, which is developing the CDN, and will release Filecoin's API service and support for decentralized application development while also providing a decentralized storage gateway service for IPFS and Filecoin.
We are currently building a decentralized authorization CDN system and will release the first version in January 2023 through a secure software and hardware environment. It will enable users to encrypt and store data in the Filecoin storage network, and allow management of data permissions through smart contracts.

More information: 

- Github/Slack handle: @xlcbd
- Storage Provider ID: f01046069, f01101196
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
The total FIL at stake is over 200k, through the following miners f01046069, f01101196 since Jun 17, 2021.
```

How did you acquire the FIL cited above?
```
Through block rewards and growth through our company's business.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- We joined the Filecoin community in 2021 and focused on the deveplopment of the Filecoin ecosystem and decentralised storage services. 
- We have attended multiple events relating to the Filecoin protocol and recently joined the conference of FIL-Singapore.
- We supply the infrastucture and technology services to mining and storage customers that seek to use Filecoin and it's a popular coin amongst our customer base.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
We have not participated in filecoin protocol work up to this point. However, we are currently developing a decentralized authorization CDN system, and will gradually participate in the connection between CDN, IPFS and Filecoin, as well as the development of the Filecoin Virtual Machine (FVM).
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Bitdeer Group (Straitdeer) is the largest proprietary hashrate owner and the largest hash rate sharing service provider in the world. Headquartered in Singapore, Bitdeer Group operates in the United States, Norway, and other countries. To date, Bitdeer Group offers specialized mining infrastructure, high-quality hashrate sharing products, and reliable hosting services to global users. 
Paralinker is a Web3 business platform under Bitdeer, mainly providing Web3 infrastructure services, node maintenance, and IPFS, Filecoin & other decentralized gateway services.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://www.bitdeer.com
Twitter: https://twitter.com/BitdeerOfficial
Facebook: https://www.facebook.com/Bitdeerplatform
Telegram: https://t.me/Bitdeer_Official

Website: https://www.paralinker.com
Twitter: https://twitter.com/paralinker
Telegram: https://t.me/paralinker
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.bloomberg.com/press-releases/2021-10-26/bitdeer-offers-ipfs-mining-with-new-filecoin-package
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Telegram: @xlc19850110 (1000+ followers)
Twitter: https://twitter.com/louis_xu_bd
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
N/A
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The Paralinker team under Bitdeer is developing a decentralized authorization CDN system, which will effectively solve the problem of real data authorization and authentication. The CDN system will become an authorized bridge between users and Filecoin decentralized storage. User data will be encrypted through CDN and then stored in the Filecoin storage provider. We have established a security environment that combines software and hardware to maintain data encryption and the key of said encryption. No one can obtain the data encryption key, including the operator of the CDN. User data permissions will be managed through smart contracts, and we are also testing related contract implementations in the ongoing Filecoin Virtual Machine. 
We will build a DAO to conduct KYC audits for users who use DataCap. If user data is violated or users violated the law, the DAO will vote to close the access rights of the data through smart contracts. Because the data is encrypted and stored on Filecoin, no one can get the original data without access rights.

For all clients, they must go through a strict KYC process. In addition to collecting relevant information from the Filecoin community, we will also audit the identity of our clients from the following aspects:
 
 1. Entity information
 - Incorporation documents, including registration/company/information certifications.
 - Government issued entity identification number.
 - Company shareholding information and whether there are another related entities of interest.
 
 2. Authorized Representative Information
 - Direct relationship between the authorized representative and the company, and credible evidence.
 - Evidence that proves the representative's identification, such as passport/residence card/ID card.
 
 3. Company business and trade
 - Legal name of the company, main business direction, team scale.
 - official website/social media that can prove the company's business, and provide official email address
 - Website of Industrial and Commercial Bureau that can verify the company's information

Customer KYC information will be submitted through the decentralized authorization CDN system and stored in the Filecoin storage network. Data that needs to be kept secret will be encrypted, and the DAO will authenticate the user's KYC information.
After KYC, the DAO votes on customer usage senarios and allocates DataCap.
After customers apply for DataCap, they need to upload and download data through the decentralized authorization CDN system, and can assign data permissions through smart contracts. All upload and download records will be recorded on the blockchain.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will use hardware wallets for DataCap-related accounts, while also monitoring and auditing the DataCap usage.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
All the allocation of DataCap will be carried out through DAO. First, users need to undergo strict KYC audit. After the audit is passed, submit the data usage requirements.
Regarding the request for DataCap, we plan to ask the following questions:
1.Are you an individual or a business/organization? If an individual, please specify the name, date of birth, and nationality; if a company/organization, please specify the company name, registration time, and registration area. At the same time, please provide the corresponding supporting documents (individuals provide ID cards, enterprises/organizations provide licenses), and these documents will be submitted via the DAO website and stored in Filecoin storage via the decentralized authorization CDN.
2.What is your industry? What data will be stored? How much do you plan to store? Can the data be made public?
3.Where do you plan to use DataCap?
4.Please share information and relevant supporting documents or links that illustrate your industry status.
5.Is there any law risk? What percentage of questions are yours?
6.Please provide your social media account and indicate the number of followers.
7.Please specify the storage location, miner ID and storage proportion of your data to be stored. We require any data to be stored on the same node no more than 30% of the same batch of DataCap acquisitions.

The DAO will vote on the customer's application and allcate DataCap.
After customers apply for DataCap, they need to upload and download data through the decentralized authorized CDN system, and can assign data permissions through smart contracts. All upload and download records will be recorded in the blockchain.
We will analyze the upload and download of the data, confirm that the custome is really using the Filecoin storage and store meaningful data.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We are establishing a decentralized authorization system, and its back-end storage will be connected to Filecoin storage. All authorization information and storage information will be recorded through smart contracts and can be queried on the blockchain. At the same time, we will build a monitoring system, if the customer does not use DataCap correctly, we can impose penalties through mechanisms such as deduction, reduction of quota, blacklisting, etc.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes. We are open to any audit request from private and public channels.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We will use github repo to make allocation decisions and keep records.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
We will have one full-time employee(40 hours/week) responsible for communication and DataCap management and we chosen the L3 level of service commitment.
- Maintain a ranking in Leaderboard in the top 25% of Notaries.
- Attend 2 Governance calls a month
- Join 1 working group
- Respond to SLACK inquiries within 2 days
- Vote/Comment on 1 proposal a month
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
We have not allocated DataCap, but have applied for 64GiB from the website https://plus.fil.org/landing for testing. As SP, we are also looking for more DataCaps to seal.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No other associations.
```

**Comment by panges2** [comment]
Hello @xlcbd,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by xlcbd** [comment]
Hello, I have finished, please check
@panges2 
Thank you very much!

**Comment by xlcbd** [comment]
> Hello @xlcbd, Thanks for applying to become a Notary in the Fil+ program!
> 
> As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. *This cannot be from your personal account. You Must include the address of your Organization.
> 
> Subject Line: Notary Name, Application Number Email Body:
> 
> 1. Your First and Last name
> 2. Your Organization
> 3. Your Country of Operation
> 4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
> 5. Link to your GitHub application
> 
> This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.
> 
> Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2
> 
> Thank you!

Hello @Kevin-FF-USA  and @panges2,
I have replied your email with all information you requested above.  Please don’t hesitate to contact with me with any further questions.
Thank you very much!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[712.pdf](https://github.com/filecoin-project/notary-governance/files/10159461/712.pdf)
