### ISSUE TITLE
Notary Application: F3

### ISSUE THREAD

**Issue by goovo** [filecoin-project/notary-governance#715]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:Goovo
- Affiliated organization: F3
- On-chain address to be notarized (recommend using a new address): f1ou765ah6t5q2q46r5pgruhkvglk3fhcfq34weui
- Country of Operation: Singapore
- Region of Operation: [Asia minus GCN]
- Use case(s) to be supported: [ Professional Services 、Developer Tools、Media & Entertainment 、Decentralized Applications ]
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization---F3

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Headquartered in Singapore, F3 is the world's first hashrate NFT platform that combines FIL with NFT, an innovative Filecoin-based application where every NFT on the F3 platform is permanently anchored to FIL cloud hashrate. When users purchase NFTs from the F3 platform, they can enjoy the ongoing benefits of Filecoin hashrate.

As the first decentralized trading platform on the Filecoin network that truly combines NFT and hashrate, we bring a broader market to Filecoin, pry tens of millions of NFT players around the world, and allow NFT players to quickly access the Filecoin network as well. At the same time, we give our users 1080 days of continuous FIL output, which means that all of our hashrate mining has chosen the longest cycle of Filecoin, which shows our unlimited confidence in the Filecoin network

F3 has 25.9K followers on Twitter, many of our tweets have been liked and retweeted by official Filecoin account, and we have received support from a number of funds including Web3 USD Fund Nothing Research.

2021 was a booming year for Filecoin and we established F3HASH.
From 2021 to 2022, we have always been committed to the promotion and publicity of Filecoin, and we have held many salons and conferences for this purpose, as well as online AMAs.

We let tens of thousands of NFT users know about Filecoin, and we will continue to contribute to the development of IPFS and Filecoin.

Website：https://f3hash.com/
Twitter：https://twitter.com/f3_f3hash    25.5k followers
Telegram：https://t.me/f3hash_en          11.8k followers
Weibo：https://weibo.com/u/6973936880
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
So far, we hold tokens Close to 1 MM FILs (Details upon request).

Total：157,066 FIL
Currently Available：2,099 FIL
Initial Pledge: 146,598 FIL
Locked Rewards: 8,369 FIL
The above data are from the blockchain browser: FILFOX. The miner ID used for statistics is the ID published on the official websites of FILSCAN.
Miner ID: f01850726, f01900537, f01900722, f01900787, f01915309, f01914991 
Website:
FILFOX: https://filfox.info/en
FILSCAN: https://filscan.io/

The total disclosed is 157,066 FIL, the rest are not disclosed. 
```

How did you acquire the FIL cited above?
```
As the world's first Filecoin-based hashrate NFT trading platform, F3HASH maintains cooperation with the leading Filecoin SPs.
Therefore, the above FIL is our way to help our clients become Filecoin SPs by way of NFT according to their requirements.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As the first decentralized trading platform on the Filecoin network that combines NFT and computing power, F3HASH ((https://www.f3hash.com/) has brought a broader market to Filecoin, leveraging thousands of Ten thousand NFT players, so that NFT players can also quickly enter the Filecoin network. At the same time, we give users 1080 days of continuous output of FIL, which means that all of our computing power mining has chosen the longest period of Filecoin, which shows Our unlimited confidence in the Filecoin network.

F3's Twitter followers are as high as 25.9K Followers, and many of our Twitters have been liked and forwarded by Filecoin's official Twitter. At the same time, we have received support from Web3 USD Fund Nothing Research and many other funds：
https://docs.qq.com/doc/DSHJrem5hdlJJTndp


We also conducted a closed-door seminar with Tiger Fund：
https://mp.weixin.qq.com/s/nbWzZGzCyVvYnC2P8Ig7HQ

We have organized many conferences for Filecoin.

We co-organized the "Chinese web3 Tour - Shenzhen Station” : https://docs.qq.com/doc/DSERLU2pvWVdRcGJJ

We hosted the web3 x distributed storage, who will seize the next opportunity： https://docs.qq.com/doc/DSGlxcVpkbXJiV3ZX

We participated in the web 3.0 conference and delivered speeches and participated in roundtable discussions: https://docs.qq.com/doc/DSFR2TE1CdkNIZEhP

We held the "Filecoin x F3, Genesis Membership Event" : https://docs.qq.com/doc/DSFpsZWdOT29BRGpJ

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Our team focus on infrastructures of filecoin ecosystem. For example:
1. implement POREP_MINIMUM_CHALLENGES changes in pull request #1635(https://github.com/filecoin-project/rust-fil-proofs/pull/1635) to solve two “good first issue” #1632(https://github.com/filecoin-project/rust-fil-proofs/issues/1632) and #1631(https://github.com/filecoin-project/rust-fil-proofs/issues/1631)
2. We implement some tools for filecoin. The wallet related part is now open source.
https://github.com/hanbu97/flair-wallet
3. Besides, we are trying to talk with core developers and join the community. 
https://github.com/filecoin-project/lotus/discussions/9489
https://github.com/ChainSafe/forest/issues/1838#issuecomment-1220144246
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
We are an hashrate NFT trading platform, currently, we are open for trading and secondary market selling of Filecoin NFT, our NFT can also be placed on trading platforms such as opensea.

Next, we will open NFT trading for BTC and ETH, and our goal is to become the world's largest hashrate NFT trading platform.

Established: 2021
Number of employees: 45
Location: Singapore
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website：http://f3hash.com/
Twitter：https://twitter.com/f3_f3hash    25.5k followers
Telegram：https://t.me/f3hash_en          11.8k followers
Weibo：https://weibo.com/u/6973936880
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://mp.weixin.qq.com/s/LEdj_3_u3AXYUsBBo1HtOg
https://mp.weixin.qq.com/s/rKoZ6PJUnTzoHUHrFxfZ3A
https://mp.weixin.qq.com/s/Oq-7HwpHCZlwMk3MuaiEVQ
https://docs.qq.com/doc/DSFpsZWdOT29BRGpJ
https://docs.qq.com/doc/DSFR2TE1CdkNIZEhP
https://docs.qq.com/doc/DSGlxcVpkbXJiV3ZX
https://docs.qq.com/doc/DSERLU2pvWVdRcGJJ
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter：https://twitter.com/VasterDean
GitHub：https://github.com/DeanV-Huang

```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://mp.weixin.qq.com/s/LEdj_3_u3AXYUsBBo1HtOg
https://mp.weixin.qq.com/s/N_O0hqQEh48YFpVaef_hHw
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
For clients, we have a clear set of scoring criteria. We focus differently on applications from new and existing clients.
For an old customer, we prefer to determine whether he has complied with the FIL+ rules and whether the data quota per node is less than 25%.

In addition, we look at their previous applications and whether the data they encapsulated is consistent with their application. If it is consistent, it means that this is an honest client and we can choose to trust him while we continue to monitor him. If it is inconsistent, then we will be wary of that client and will not grant him datacap until he provides a reasonable response.

For new clients, we need to know.
1, name, official website, establishment date
2、Compnany main business.
3, the type of data generated by the company
4, whether the DC data requested by the customer matches the total amount of data of the company
5、SPs cooperated with, please indicate the miner id.
6、Allocation plan
7、Storage duration
8、Whether there is a retrieval plan and whether the SP it contacted can provide retrieval service
9、Please provide the domain email address to send an email to confirm the application
10、Please attach the business license to the email and send it together
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We purchase ledger wallets, which are mainly managed by the head of the company.
Our company has a safe deposit box, we will keep the ledger wallet in the safe deposit box and open it when we need to use it.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We explicitly ask our clients to provide the following information.
1, Company name, time of establishment
2, the company's official website, the official website domain name registration time
3, the company's business type, and the related data type.
4, the total amount of DC applied for by the company
5, the allocation plan: cooperated with which SPs, what is the distribution plan for SPs
6, Whether it can comply with the FIL+ rules, with no more than 25% of each SP's allocation
7, Whether retrieval is required, what is the frequency of retrieval, and whether the cooperating SPs provide retrieval services
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We review use the allocation records of our customers at https://filplus.d.interplanetary.one and http://www.filfox.info/
If an improper allocation is found, or if a single node has more than 35% of its allocation records, we will stop the allocation immediately.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we keep records of all communication with our clients.
First of all, clients apply on GitHub, and our communication with them is mainly on github.
Second, clients may contact us on slack or email or telegram. We prefer to communicate with customers via email, and we keep records of all our communication with customers on GitHub for the community to check.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub and email

GitHub can keep records permanently, and both the community and customers prefer to see all allocation records through github.
If the community has a problem with the allocation, first we will suspend the allocation, second we will hold a community meeting, ask the notary who signed it to give their reasons for signing it, and listen to the client's reasons, and finally we make a decision after listening to all parties.
At the same time, we communicate with our clients mainly through email, and all email communication records are kept and displayed on github.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
Our team has very good English skills, and the technical guy in charge of FIL+ has studied in the US for three years, and at the same time, he is also a Filecoin engineer. He follows filecoin's slack and GitHub every day, and at the same time, attends every conference, FIL+ as well as E-FIL+.
If we are elected notary, we can do it, spending more than 20 hours a week on slack, GitHub, and notary meetings, and we tend to be at L4 level.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes, https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/925
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
930TiB
```

**Comment by panges2** [comment]
Hello @goovo,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by goovo** [comment]
Hello @panges2 ,
The email has been sent, and the content is shown in the screenshot below.

**Comment by goovo** [comment]
![微信图片_20221125105654](https://user-images.githubusercontent.com/12687556/203891737-40d0af11-6cd2-4cdb-a1de-7d078ef6b8c9.png)

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by goovo** [comment]
We have proposed two optimizations again, please check: 

Pull request: https://github.com/filecoin-project/rust-fil-proofs/pull/1650 to fix to fix "good first issue" of project filecoin-project/ rust-fil-proofs #1645 Use workspace inheritance for dependencies 
(https://github.com/filecoin-project/rust-fil-proofs/issues/1645)

Pull request: https://github.com/filecoin-project/rust-fil-proofs/pull/1649 to fix "good first issue" of project filecoin-project/rust-fil-proofs #1637 Broken Links in README.md (https://github.com/filecoin-project/rust-fil-proofs/issues/1637)

**Comment by goovo** [comment]
In 2016， I was working in TCL as an system architect, and during that time I was inspired by IPFS protocol, and wanted to contribute on the filecoin eco-system. Same year, i setup Jiucun with some co-founders, which was one of the largest company in IPFS storage area, kindly refer to below link. https://www.ipfs.hk/

In 2017, we were always active in evangelizing IPFS and Filecoin, we had roadshows in China, North America and Singapore, and we also registered slack (slack: y50, ID: UNBPM9AKW) in 2018 so that we could be the first to know all the news about Filecoin.

In 2020, we invested in many Filecoin eco-projects, many of which participated in orbit and hackathon competitions, such as the Filecoin browser, and won places. We have also invested in a famous Chinese media "Chain DAO Business School", where we have studied the possibility of combining Filecoin and DAO.

In 2021, we founded F3, Headquartered in Singapore, F3 is the world's first hashrate NFT platform that combines FIL with NFT, an innovative Filecoin-based application where every NFT on the F3 platform is permanently anchored to FIL cloud hashrate. When users purchase NFTs from the F3 platform, they can enjoy the ongoing benefits of Filecoin hashrate.

As the first decentralized trading platform on the Filecoin network that truly combines NFT and hashrate, we bring a broader market to Filecoin, pry tens of millions of NFT players around the world, and allow NFT players to quickly access the Filecoin network as well. At the same time, we give our users 1080 days of continuous FIL output, which means that all of our hashrate mining has chosen the longest cycle of Filecoin, which shows our unlimited confidence in the Filecoin network

F3 has 25.9K followers on Twitter, many of our tweets have been liked and retweeted by official Filecoin account, and we have received support from a number of funds including Web3 USD Fund Nothing Research.

2021 was a booming year for Filecoin and we established F3HASH.
From 2021 to 2022, we have always been committed to the promotion and publicity of Filecoin, and we have held many salons and conferences for this purpose, as well as online AMAs.

We let tens of thousands of NFT users know about Filecoin, and we will continue to contribute to the development of IPFS and Filecoin.

Website：https://f3hash.com/
Twitter：https://twitter.com/f3_f3hash    25.5k followers
Telegram：https://t.me/f3hash_en          11.8k followers
Weibo：https://weibo.com/u/6973936880

**Comment by goovo** [comment]
@Kevin-FF-USA @panges2 @galen-mcandrew 

The above is some updated information, Please kindly take a look.
Thanks!

**Comment by Kevin-FF-USA** [comment]
@goovo 


Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
