### ISSUE TITLE
Notary Application: Bitrise capital

### ISSUE THREAD

**Issue by Bitrise0111** [filecoin-project/notary-governance#716]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Kivi
- Affiliated organization: Bitrise capital
- On-chain address to be notarized (recommend using a new address): f1dfkdmjhuvvol6okun57mix447wdpolwcd323ktq
- Country of Operation: Asia minus GCN
- Region of Operation: Asia minus GCN
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
1. In 2018, Bitrise Capital participated in Filecoin's early private equity financing and was fortunate to be an early investment institution of Filecoin;
2. in early February 2021, Bitrise Capital was cooperate with Coinlist. According to the latest statistics, Bitrse Capital and Coinlist have a total of over 1.5 million FIL loans to support storage service providers; [Cooperation certificates can be provided]
3. In May 2021, Bitrise Capital participated in the Fenbushi Capital Filecoin Ecological Special Fund, to jointly contribute to the development of the IPFS/Filecoin ecosystem;
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
None.
```

How did you acquire the FIL cited above?
```
None.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
None.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Bitrise capital is a venture capital institution focusing on blockchain and was Founded in Singapore. Its main investment direction is digital currency and mining. Bitrise Capital has invested in more than 60 projects.
Bitrise capital aims to provide safe and reliable decentralized + financial services and to provide asset management, digital asset payment, connection to defi ecology, NFT ecology, Polkadot ecology, and other hot track in the industry. It serves 50+ institutions, covers many countries, and manages over $200 million in mainstream encrypted digital assets. Bitrise capital can experience the various primary asset transaction strategies and high return strategies available for selection, deeply study multiple large defi projects, provide various asset value-added services such as liquidity mining, and protect the user experience one-stop decentralized financial project. In the years of deep cultivation industry, it has accumulated rich practical operation experience in the development of the blockchain industry and defi mining.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://www.bitrisevc.com/sy 
Twitter: https://twitter.com/Bitrisecapital_
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.bitrisevc.com/newsinfo/515145.html https://www.bitrisevc.com/newsinfo/517171.html 
https://twitter.com/Bitrisecapital_ 
https://twitter.com/ABGAasia/status/1484077817344061444?s=20&t=vtUXk7qZkXWit5h_6EMq7A 
https://twitter.com/Bitrisecapital_/status/1468882434364407811?s=20&t=vtUXk7qZkXWit5h_6EMq7 
https://twitter.com/Bitrisecapital_/status/1460137214172487688?s=20&t=vtUXk7qZkXWit5h_6EMq7
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter：@Bitrisecapital_ Follows：8060
Twitter: @kevinshao6 Follows:2642
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
None.
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
As a notary, our goal is to guarantee more organizations or individuals with data storage needs to join Filecoin on the basis of ensuring that the review is open and fair. We will keep our mechanism for continuous review.

Our allocation strategy is determined to divided in two mechanisms.
1.We have created a detailed proposal to evaluate and score the customer's industry, reputation, transaction frequency, personal information and storage content. 
Link: https://docs.google.com/spreadsheets/d/1bPdOHxeZlbuWe6qGpUL1OHJ41ddM4VSa/edit?usp=sharing&ouid=114559464152015480806&rtpof=true&sd=true

2.For the process of allocation, we will distribute the datacap that customers have applied for in three batches: 20% for the first time, 30% for the second time, and 50% for the third time. 
The interval between each allocation will not exceed two weeks if the client is storage efficiency. And after each issuance is completed, we will review the datacap usage of customers, and we will allocate the next datacap for customers with good reputation. 
See the allocation strategy table for details: https://docs.google.com/spreadsheets/d/1osogUMVafyb_vPJQkJSIiguMzT-Vkm9j/edit?usp=sharing&ouid=114559464152015480806&rtpof=true&sd=true
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Our review process:
1. We will check the submitted application in time every day. If there is any submitted information or the sample data is incomplete, we will ask the applicant to supplement it again.
2. Our staff will evaluate the applicant's detailed proposal and allocate the corresponding amount according to the final score. If the client disagrees with the score, we will conduct a second review.
3. The datacap is allocated after being reviewed and signed by two of our internal decision-makers.

We store the private key in a hardware wallet. Only people with operation rights can access.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will ask customers to submit a list of questions linked below.
https://github.com/filecoin-project/notary-governance/blob/main/notaries/templates/sample-client-application.md

We will ask customers to submit their personal information, corporate information, corporate milestones, reputation, transaction volume, social media accounts, official website, samples of data storage... in our sheet. 
My team will further review the customer's data. After the review, we adopt a continuous review mechanism to allocate the first 20% of the quota to the customer. Then, continue to track whether the customer's data storage meets the validity and authenticity requirements, and thus the credibility established by the customer. We will issue subsequent remaining datacap according to the customer's credit. If the customer's data storage is not compliant, we will make warning or penalize to customer.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
First, we use the above two links to check the customer's usage plan and distribution. Next, we will ask the customer to publish the transaction details in Github . We continue to track the customer's transactions and calculate whether the transaction distribution ratio is reasonable.
If a client improperly allocates Datacap to a single entity, we will give a warning. For client who continue to violate the rules after the warning, we will stop the next allocation. And will warn the public in the Filecoin community. Cooperation is no longer accepted. For customers with good reputation, we will make the next allocation.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We will save all customer usage, conversation content, customer information, etc. 
And use Github to save our allocation decisions in public
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
A google sheet for it.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
https://github.com/filecoin-project/notary-governance/issues/443
Haven't received any Datacap to allocate
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
Our previous business involved providing staking solutions for SPs,including f0673920, f0718311, f0103665, f0152799，f08257, f069448; 3. Bitrise’s steaking business client including 1475, NDlabs and IPFSunion
```

**Comment by panges2** [comment]
Hello @Bitrise0111,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[716.pdf](https://github.com/filecoin-project/notary-governance/files/10159469/716.pdf)

**Comment by Kevin-FF-USA** [comment]
@Bitrise0111 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @Bitrise0111, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by Bitrise0111** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecg3oinbyhqam6kwoxqiufrkmi2p2pmcvshgs3mxyf4ynd4u7xvsa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecg3oinbyhqam6kwoxqiufrkmi2p2pmcvshgs3mxyf4ynd4u7xvsa

**Comment by Bitrise0111** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebpnr6tdr53z2euvhj5gndx4m4ruxfh4tfhjpav6dpnm5xzo6wusa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpnr6tdr53z2euvhj5gndx4m4ruxfh4tfhjpav6dpnm5xzo6wusa

**Comment by Bitrise0111** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebebnu4tgsyow6mlxyiz5z2exulax4doh4d6kgviifyr4wlrxivo4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebebnu4tgsyow6mlxyiz5z2exulax4doh4d6kgviifyr4wlrxivo4
