### ISSUE TITLE
Notary Application: Direction Technology

### ISSUE THREAD

**Issue by DirectionTechnology** [filecoin-project/notary-governance#717]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:Direction Technology
- Affiliated organization: Direction Technology Co., LTD
- On-chain address to be notarized (recommend using a new address):f1hx7u4j5zzaupdx3ozk5mhnivz2hkzzrd7pf6oei
- Country of Operation: UK
- Region of Operation: Europe
- Use case(s) to be supported: Professional Services 、Web 3 Developer Tools、Decentralized Applications
- DataCap requested for allocation (10TiB - 1PiB): 100TiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
In 2020, Direction Technology  began focusing on the project from the Filecoin Slingshot.
In 2021, We joined the Filecoin project and we wanna to devote to Filecoin development for the long term.
In 2021, we sealed two nodes: f01188117 and f0218559, which contributed  more than 26PiB of storage to the network.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f01188117  ( 102,799.9720 FIL )
f0218559   ( 78,541.7451 FIL )
```

How did you acquire the FIL cited above?
```
Purchased by the company、Block rewards
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
N/A
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
DirectionTechnology is a blockchain technology service company, founded in 2022.9, registered in the UK, As a newly established team,the team consists of five developers and three operations,We plan to be involved in Filecoin and other Web3 projects for the long term.

We have focused on this project from the Filecoin Slingshot. In 2021, because of hardware cost constraints, we had to entrust other teams to seals two nodes for us, without participating on a larger scale. Now, the time to participation most appropriate has arrived.

Development status of Direction Technology:
-- Relevant technicians have been recruited to form a complete service team
-- Acquired a batch of redundant storage and computing equipment at low cost.
--We Contacted a group of clients in Europe and America for joint-sealing. They have a lot of idle Fil ，and and long-term bullish on the continued value of Fil.
--In the future, we plan to set up the IDC in the UK or the US.
--We are also very interested in active data storage and are willing to collaborate with many partners and organizations that have real data (they are also interested in this project). We can join them to store real data and help them submit  LDN application.
-- We would like to be more deeply involved in the Fil project, not only in the storage development, but also in the community construction and maintenance, so as to serve the Fil ecological construction.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Twitter：https://twitter.com/DT_Miner
Slack : D_tech
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
N/A
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
N/A
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
N/A
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
According to the Fil+operation guidelines, we fully agree with the responsibilities of notaries:
--Allocate DataCap to clients in order to subsidize reliable and useful storage on the network.
--Verify that clients receive a DataCap commensurate with the level of trust that is warranted based on information provided.
--Ensure that in the allocation of the DataCap no party is given excessive trust in any form that might jeopardize the network.
--Follow operational guidelines, keep record of decision flow, and respond to any requests for audits of their allocation decisions.

We totally understand that the core of notary assignment is to enable clients to correctly use DC allocation, and attract more enterprises or individuals to store real data in Filecoin network and improve the construction of Filecoin ecosystem. Therefore, based on the applicant's verification, data diversity and SPs' allocation, we have defined 6 trust thresholds at different levels, which can be reasonably allocated through evaluation.
https://docs.google.com/spreadsheets/d/1afKnLJfjkUz47ztjTWx-rxFOGTgYQ0y8JRpT3RwZyGc/edit?usp=sharing
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will use ledger for administration
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will conduct clients due diligence on individuals and organizations:
--For individuals, we will verify by account age and account activity to ensure they are valid users and provide a valid government-issued ID.
--For organizations, we will focus on their organizational documentation, industry reputation, portal sites; The applicant's relationship with the organization.

We get to know our clients through the following questions, mainly for first-time applicants:
1. Please introduce yourself and link your social media platform (Github, Twitter, Linkedin handle, Wechat, etc.)
2. If you represent an organization, Please note your organization's name, nature, country and data of incorporation, and proof of your relationship with the organization.
3. What are your data use for? How much data is the project expected to store?
4. Please prove your relationship with the stored data, especially the copyright?
5. Where is your data source? Describe the source and publicity of the data to be stored in Filecoin. If data can be made public, how can others retrieve it?)
6. Where do you plan to store your data? How many SPs are you looking for? Please list the SP ID. What is the ratio of storage per SP? What are the requirements for SPs?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will conduct ongoing reviews or spot checks after the distribution of DataCap to avoid abuse, keep up with the original intent of Fil+, and fulfill the duties of a notary. As DataCap is allocated in stages, subsequent quotas will be delayed or even be objected for applicants who do not pass the audit. Specific review principles (review terms will be adjusted according to community updates and actual conditions) :
--According to the volume of client project data allocated for the first time,
we will verify whether the application quantity is reasonable 
--We will ask the applicant to provide a CID for a random search and will take steps to stop further distribution if there is any violation of DataCap distribution by the applicant.
--We verify that a user distributes the requested DataCap to at least three SP to improve data storage security while reducing the possibility of misuse.

We collect information about clients who already have allocation records through the following questions：
1. How many DataCap did you get before this?
2. Can the data you have stored be retrieved normally? Please provide Cid?
3. How many SPs do you assign DataCap to? Where is their area?
4. Please keep the SP ID accessible to ensure that we can check the node information provided by you at any time.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, both on github and email, and update the following record sheet in real time:Bookkeeping Plan
https://docs.google.com/spreadsheets/d/1sGMGZhyYV4N2cAY-WnZRqBSLW2zVS8J-IIwHFGmIDf4/edit?usp=sharing
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub& some public sites: Filecoin-plus-client-onboarding, filplus.info
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4: <8 hours of engagement per week
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None
```

**Comment by panges2** [comment]
Hello @DirectionTechnology,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[717.pdf](https://github.com/filecoin-project/notary-governance/files/10159470/717.pdf)

**Comment by Yvette516** [comment]
@DirectionTechnology Hi, I noticed that 26PiB storage are all CC sectors. I am curious if Direction Technology has any real storage plans and how do you plan to contribute to this network. Also, can you share the official website of your organization? Thanks.

**Comment by DirectionTechnology** [comment]
Hi @Yvette516 , it was a pleasure to receive your reply and sorry for not replying in time.
 
Both of our nodes were sealed in 2021,the Filecoin plus program wasn't released at that time, so we didn't have much knowledge about Filecoin plus programand only played the role as SP in community.
 
Besides, on the issue of contributing to the network. As we mentioned in our notary application, the hardware cost issue and the coin price previously led to us not being strong enough to participate more deeply and we need to work with other teams for sealing, whereas the current hardware market and FIL price has led several of our partners to agree that the best time to participate in Fliecoin has come.
 
We have just recruited our technical team for Filecoin program, mainly targeted on sealing technicians, and we are recruiting other technicians who are expert in smart contract developers, web developers, application developers,so that we can start launching our application when FVM launch.
 
Because we a team with small scale, our company's website and application is preparing,when it done,we will make it public on github immediately.The contributions we are prepared to make in the future include:
1. Attracting more users to participate in sealing and pledging more FILs.
2. Developing applications on FVM to serve our node users and attract more other users.
 
If we are lucky enough to become a V4 notary, we are willing to accept monitoring from the project side to evaluate our contribution to the community.

**Comment by Kevin-FF-USA** [comment]
@DirectionTechnology 

Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by DirectionTechnology** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebhhxgplfsxcq2pn6u36otqqahqolb5jogzw7qj7ib57xacmlikkk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhhxgplfsxcq2pn6u36otqqahqolb5jogzw7qj7ib57xacmlikkk

**Comment by DirectionTechnology** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec2h6dq4nrlij27foz7je4t7r45hqezp3thusi2jszt4d7hhp37q6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2h6dq4nrlij27foz7je4t7r45hqezp3thusi2jszt4d7hhp37q6
