### ISSUE TITLE
Notary Application: Shanghai WangYu network technology Ltd.

### ISSUE THREAD

**Issue by Wang-Yu-Wang** [filecoin-project/notary-governance#718]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Wang Yu Wang
- Affiliated organization: Shanghai WangYu network technology Ltd.
- On-chain address to be notarized (recommend using a new address): f15g4izzyz523cqrmo5tqsx4nrhkuo2csfls3ibli
- Country of Operation: GCR
- Region of Operation: [North America, Europe, Greater China Region (GCR), Asia minus GCR]
- Use case(s) to be supported: [Developer Tools (Package Managers, Automatic Notaries, Web2 to Web3 integrations), Decentralized Applications, User Content (Personal Storage), Public or Open Data (Scientific datasets, research data, government or historic,  Media & Entertainment (Videos, photos, NFTs)]
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: [Organization]

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Since our company was established in 2003, we have cooperated more than 120 IDCs domestic and foreign telecom operators  , and we operate a total area of more than 50,000 square meters of server rooms that distribute in mainland China and Southeast Asia, and operate and maintain more than 50,000 servers. Our company, as a traditional IDC service provider, hasn't had the opportunity to contact decentralization projects in the early days, and has been serving traditional cloud storage and cloud computing clients.
But in the second half of 2020, a large number of clients suddenly appeared seeking to host a large number of servers, and they were all devoting the same project: FileCoin decentralized storage. During the communicated with them, we gradually understood the state and prospect of this project, and gradually became interested in this decentralized storage. With the recognition of this project, and the support of these miners, we started to adjust the direction of our business.
First,  because their lease term is generally up to 540 or even longer, they belong to our high-quality clients. Therefore, we strive to reduce their costs by optimizing cabinet combination, power distribution and other means.
Secondly, because this project has high requirements for storage stability, we have adjusted the duty policy of computer rooms outside Chinese Mainland to 7 x24 non-stop service. These two changes have brought our company a large number of FileCoin clients and considerable revenue.
In case of policy change in mainland China, we actively helped them to find other local cost-effective server rooms to survive their nodes.
These are our nodes:f01190147、f060072、f0745192 .
Since 2022, we have set up a business department to find more clients to participate in this project in our computer room. And provide these clients with more suitable network solutions and more cost-effective server configuration solutions that we have summarized.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f01190147, 72039.18 fil
f060072, 21227.21 fil
f0745192, 21252.88 fil
total: 114,519.27 fil
```

How did you acquire the FIL cited above?
```
Company Investment and block reward.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
N/A
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Shanghai WangYu network technology Ltd. is a well-known and one-stop Internet Data Center (IDC) and cloud-computing solution provider in China.We has been deeply involved in the industry for more than 20 years, and has mature and professional operation and maintenance service experience. We are committed to providing customers with diversified, specialized and customized IDC products and cloud computing integrated solutions to help customers achieve digital transformation

Founded in 2003,WangYu network is headquartered in Shanghai, China. At present, it has branches in Ningbo, China, and Suzhou, China, with more than 100 industry elites. The business covers the Internet, finance, education, games, blockchain, Internet of Things, logistics, entertainment, AI, intelligent manufacturing, government and enterprises and many other fields.

Our company cooperates with global operators to operate 100+Internet data centers, and we have a total bandwidth of more than 8TB, the core nodes are all over China. At present, there are two network management centers (NOCs) in China, both of them have an experienced customer service team and a professional team of technical engineers, they can provide "high-quality, efficient and safe" 7x24x365 professional operation and maintenance services for more than 2000 clients nationwide.

Awarded the annual innovation prize of China IDC industry in 2008.
In 2010, we received the China Industry Excellence Web Hosting Award.
In 2013, we received the China IDC Industry Annual Grand Award for Outstanding Cloud Product.
In 2018,we received the China IDC Industry Excellent Service Award.
In 2021,we received the China IDC Operation and Maintenance Service Provider Award.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
website：https://www.7x24.cn/about.php
WECHAT：上海网域网  
TikTok：上海网域网 
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://baijiahao.baidu.com/s?id=1704414542544497706&wfr=spider&for=pc
https://mp.weixin.qq.com/s/LILd8jtpfkdGi7czEj18kA
https://mp.weixin.qq.com/s/Mx6HcOfytdPOmH_Mg94tLg
https://mp.weixin.qq.com/s/JvCquKk6u0iA-3v1Vi7x2w
https://mp.weixin.qq.com/s/zHBvotamzfNlqoSJPghUbQ
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
WeChat：上海网域网 500+Followers
DouYin(tiktok):上海网域网 1.1k+Followers
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://baijiahao.baidu.com/s?id=1704414542544497706&wfr=spider&for=pc
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
First of all, our allocation plan is not limited by geography, organization, or industry,bringing in as many clients as possible into Filecoin is what we prefer to see, but only if the client first complies with filecoin and fil+ rules. In addition, we will conduct strict due diligence on our clients and rate them from L1-L5 based on the survey, with each level having a corresponding DataCap allocation quota, the higher the level, the higher the DataCap.The detailed scoring criteria is attached below: https://docs.google.com/spreadsheets/d/1TIcqvlYfWFvG-x4UIPzxmSYecAwFbCjYdDNsdWRWj4Q/edit#gid=0
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will exclusively use offline hardware wallets to verify accounts associated with Datacap allocations. Multi-signature wallets will be used in the future when we have more clients.
In addition, we will form a four-person working group which is dedicated to community governance and client communication.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
First, a flow chart was created to help the client understand the procedure of DataCap application, as detailed in the link:https://github.com/Wang-Yu-Wang/clients-due-diligence
Secondly, clients are required to fill out a form that includes information such as the client's entity name, jurisdiction of the entity, registration number, business location, contact person and title, email address, main business description, and the Datacap quota applied for, which will serve as the basis for our initial assessment of whether the client meets the requirements, as detailed in the link:https://github.com/Wang-Yu-Wang/clients-due-diligence/issues/new?template=Client-Due-Diligence-Form.yml
Third, for clients who pass the preliminary investigation, we will conduct a deeper due diligence, including information such as the main registration certificate, proof of main business address, etc. These inconvenient information we need the client to send to our email, we understand that clients have concerns about the leakage of the main information, so we will sign a confidentiality agreement with the client, see link for details,https://github.com/Wang-Yu-Wang/clients-due-diligence/blob/main/NON-DISCLOSURE%20AGREEMENT.docx
Fourth, after the client has passed all the verification, we will grant the client DataCap in stages, which will be consistent with the Fil+ rules, First allocation: lesser of 5% of total DataCap requested or 50% of weekly allocation rate; Second allocation: lesser of 10% of total DataCap requested or 100% of weekly allocation rate; Third allocation: lesser of 20% of total DataCap request or 200% of weekly allocation rate; Fourth allocation: lesser of 40% of total DataCap requested or 400% of weekly allocation rate; Fifth allocation onwards: lesser of 80% of total DataCap request or 800% of weekly allocation rate
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. Regular and continuous checks are performed using various statistical tools such as https://filplus.d.interplanetary.one/ and filfox.info to ensure that the allocated DataCap has not been abused or misused.
2. DataCap will be allocated in stages. If any improper use or misuse of the allocated DataCap is detected, we will immediately contact the clients and may reduce or even cancel the unallocated DataCap depending on the circumstances.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be made publicly in the Github repo, subject to oversight by the Filecoin Plus governance team, notaries and the community.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
In addition to retention in GitHub, we will also back up all distribution records and store them in Filecoin; due diligence data that clients are not comfortable disclosing we will create a dedicated database to store for data auditing and analysis, and we will be open to any audits.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4. Maintain a ranking in Leaderboard in the top 10% of Notaries. Attend 2 Governance calls a month. Join 2 working groups. Respond to SLACK inquiries within 2 days. Vote/Comment on >2 proposals a month
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
N/A
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
N/A
```

**Comment by panges2** [comment]
Hello @Wang-Yu-Wang,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Wang-Yu-Wang** [comment]
Hi @panges2 .We already sent the verification email to you.lf you have any questions, please contact us.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[718.pdf](https://github.com/filecoin-project/notary-governance/files/10159472/718.pdf)

**Comment by Kevin-FF-USA** [comment]
@Wang-Yu-Wang 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
