### ISSUE TITLE
Notary Application: MS Cloud

### ISSUE THREAD

**Issue by MatrixStorage** [filecoin-project/notary-governance#719]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Tracy
- Affiliated organization:  MS Cloud（formerly MatrixStorage）
- On-chain address to be notarized (recommend using a new address): f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
- Country of Operation: GCR
- Region of Operation: GCR
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?:  Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
MS Cloud officially started the project construction and technical pre-research in 2020.  At present, MS Cloud has been working in the IPFS/Filecoin for about 2 years. MS Cloud is a distributed encrypted storage service system based on blockchain technology and IPFS protocol. Relying on blockchain technology and IPFS protocol, MS Cloud integrates storage resources of the whole network to provides easy-to-use PaaS software, including OpenAPI and encrypted storage tool set. We are committed to efficiently linking Internet storage needs with decentralized storage networks.

Our team was founded in 2020. The project has been officially launched on April 22, 2021, and entered into the community's Ecosystem Map at the end of 2021.Recently, we experienced a brand upgrade and redefined the brand name as MS Cloud.
Github：MS Cloud（formerly MatrixStorage）
Project Milestones: https://github.com/Matrixstorage/Matrix-Storage/projects/1

We were elected in the third round of notary applications. During our tenure, we actively participated in community governance meetings and fulfilled the obligations of notary public. The attendance rate of the community governance meeting was 90%. In addition, we are also actively expressing our views on community and sharing experience with FiL-E as much as possible.

Activities
 IPFS Knowledge Raffle
 https://mp.weixin.qq.com/s/PJ5vCBI-F7A1KAp8TGltog
Overseas Online Discussion
We launched an online sharing session with Holobase technology community to share knowledge points and distributed storage advantages of Web3.0 with enterprise users from 16 countries.
https://mp.weixin.qq.com/s/Ro2m68luAD0G0iEClPy8KA
The First Anniversary Celebration
We united Computing Planet, hosted the celebration of the 1st anniversary of mainnet's launch, and accepted the invitation of the Force region to participate in the 1st anniversary event 
https://mp.weixin.qq.com/s/6ae6MSZmAFPj8uQk4TheKg
https://twitter.com/MatrixStorage/status/1448948410074103811
Outstanding works
In August 2021, Filecoin Plus Periodic Notary Report (In English and Chinese) was well received by the community for its detailed analysis of the Filecoin Plus project's information statistics, share allocation details, and global distribution of DataCap.
 In September 2021, Fil+ Phased Big Data Set Report (In English and Chinese) made a global survey and forecast of Filecoin Plus's initiatives to promote ecological implementation, including details of the Filecoin Plus project application, community approval preferences, and changes in application duration since the opening of the Filecoin Plus big data set application channel. By the community praise. Up to now, these two reports have been downloaded more than 1,000 times across multiple platforms.
 Related links:
 Twitter:
https://twitter.com/MatrixStorage
 Filecoin Plus Large Datasets Periodic Report: https://drive.google.com/file/d/1J__E67B6ym6tgXIv5tOYT8NP1n42HaK_/view?usp=sharing
 Filecoin Plus Periodic Report:https://drive.google.com/file/d/11T4SRoKBLnsHyEM2375xKNaj3U1G_lH2/view?usp=sharing
 Slack:
 Filecoin Plus Large Datasets Periodic Report:https://filecoinproject.slack.com/archives/C01KCAAURAN/p1630036161002600 Filecoin Plus Periodic Report:https://filecoinproject.slack.com/archives/C01KCAAURAN/p1629275531053000
 *Note: Due to policy influence, the above report was temporarily transferred to "private" in China and was not made public.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
None
```

How did you acquire the FIL cited above?
```
None
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Over the past 2 years, we have established data storage cooperation with many domestic enterprises. Our partners include 23Mofang, the largest consumer gene testing product in China, Zhongjing Tianping, the subordinate enterprises of State Information Center (China Economic Network), Digital Media Industry Base, one of the four national digital media technology industrialization bases, Huaqi Cloud and Qiniu Cloud, China's leading cloud media service provider.
At the same time, we set up WeChat groups.  These WeChat groups have linked storage users and storage resource providers.  Users can release their demands and storage resourceproviders can accept storage requirements.  We will also regularly publish updates of industry and product to the WeChat group, expanding the reach of the MS Cloud and IPFS/Filecoin.
Although the our project was officially launched in April 2021, early technology research based on IPFS and Filecoin networks began as early as July 2019.  Therefore, after the mainnet was launched, a special project team was quickly set up to do product research and development, complete products were presented in a short period of time, and market customers were accumulated in the early stage.  
We were elected in the third round of notary applications. During our tenure, we actively participated in community governance meetings and fulfilled the obligations of notary public. The attendance rate of the community governance meeting was 90%. In addition, we are also actively expressing our views on community and sharing experience with FiL-E as much as possible.

Activities
 IPFS Knowledge Raffle
 https://mp.weixin.qq.com/s/BRxZX3hH2_Xv2hqVliSoUg
 https://mp.weixin.qq.com/s/PJ5vCBI-F7A1KAp8TGltog
 Overseas Online Discussion
 We launched an online sharing session with Holobase technology community to share knowledge points and distributed storage advantages of Web3.0 with enterprise users from 16 countries.
 https://www.holobase.io/recap/6167f914d592574837604e5b
 https://mp.weixin.qq.com/s/Ro2m68luAD0G0iEClPy8KA
 The First Anniversary Celebration
 We united Computing Planet, hosted the celebration of the 1st anniversary of mainnet's launch, and accepted the invitation of the Force region to participate in the 1st anniversary event
 https://mp.weixin.qq.com/s/6ae6MSZmAFPj8uQk4TheKg
 https://twitter.com/MatrixStorage/status/1448948410074103811
Outstanding works
 In August 2021, Filecoin Plus Periodic Notary Report (In English and Chinese) was well received by the community for its detailed analysis of the Filecoin Plus project's information statistics, share allocation details, and global distribution of DataCap.
 In September 2021, Fil+ Phased Big Data Set Report (In English and Chinese) made a global survey and forecast of Filecoin Plus's initiatives to promote ecological implementation, including details of the Filecoin Plus project application, community approval preferences, and changes in application duration since the opening of the Filecoin Plus big data set application channel. By the community praise. Up to now, these two reports have been downloaded more than 1,000 times across multiple platforms.
 Related links:
 Twitter:
 https://twitter.com/matrixstorage
 Filecoin Plus Large Datasets Periodic Report: https://drive.google.com/file/d/1J__E67B6ym6tgXIv5tOYT8NP1n42HaK_/view?usp=sharing
 Filecoin Plus Periodic Report:https://drive.google.com/file/d/11T4SRoKBLnsHyEM2375xKNaj3U1G_lH2/view?usp=sharing
 Slack:
 Filecoin Plus Large Datasets Periodic Report:https://filecoinproject.slack.com/archives/C01KCAAURAN/p1630036161002600 Filecoin Plus Periodic Report:https://filecoinproject.slack.com/archives/C01KCAAURAN/p1629275531053000
 *Note: Due to policy influence, the above report was temporarily transferred to "private" in China and was not made public.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
[BUG] GenerateUnsealedCID,more than 32 GB file,return Piece is large then sector #6292https://github.com/filecoin-project/lotus/issues/6292
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
MS Cloud is a decentralized cloud computing infrastructure service provider, based on web3.0 infrastructure construction, providing individuals and enterprises with the world's leading cloud computing, big data, artificial intelligence and other technology products and services.  Team size of more than 10 people, the establishment of nearly 2 years of rapid development, the size of the team is still expanding.
MS Cloud provides an intermediate bridge between data storage requirements and data storage providers by providing easy-to-use PaaS services, OpenAPI services, and a storage toolset.  In order to connect the underlying technology with the real business needs, MS Cloud has established deep cooperation with key people in the upstream and downstream industries.
Storage Providers:
We have established a cooperative relationship with global storage providers, the top in the industry, and provided stable storage nodes for storage users, which ensure the stability and reliability of the storage cluster and achieve the effective balance between the performance and cost.  There will be more high-quality and stable nodes joining MS Cloud in the future, and provide users with more storage options and storage space.
https://www.donews.com/news/detail/4/3151551.html
http://www.itbear.com.cn/html/2021-05/405335.html
Clients:
MS Cloud is implemented in the fields of radio, television and video, big data of genes, big data of health, judicial storage and AI agents, as mentioned above.
At present, we are pushing forward to try more cooperation with traditional storage service providers.  We are also looking for more enterprise users who have real data storage needs to provide them with more secure, more reliablemore convenient , and less costly storage products.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
official website: https://www.a2pool.com
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
- https://www.donews.com/news/detail/4/3151551.html
- https://zhuanlan.zhihu.com/p/406002779
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter: https://mobile.twitter.com/MatrixStorage ( followers: 106 )
GitHub: https://github.com/MatrixStorage
Wechat official account: MatrixStorage (followers: 1843)
Wechat ID: MatrixStorage_ (followers: 100+)
Slack: https://filecoinproject.slack.com/archives/CR98WERRN/p1620384716043500
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
Reports:
https://www.donews.com/news/detail/4/3151551.html
http://www.itbear.com.cn/html/2021-05/405335.html
Project Award:
Won the second prize of Filecoin Grant Online Hackathon: https://www.ipfsnews.cn/24381.html
Wanxiang Blockchain：https://zhuanlan.zhihu.com/p/406002779
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We calculated the level of applicants through scoring, and set maximum amount for each level in first allocation, so that we could fully follow up the usage of applicants;  All individuals and businesses are encouraged to get involved in the IPFS business, but we prefer organizations in order to build the IPFS ecosystem more quickly.
We judge the qualification on a scale of 1 to 4 (round), and our scoring mechanism is as follows:
https://docs.google.com/spreadsheets/d/1SEIHx9ZdSBQlThI0I2CgfakdZBj78ioKZ21GODyK_tw/edit?usp=sharing
1. The entire application and allocation process will be transparent and open;
2. Strictly review the information provided by users, including but not limited to some written evidence;
3. Establish online communication audit mechanism and offline investigation audit as far as possible;
4. Score will be given after reviewing the information provided by clients;
5. We will confirm the previous DataCap usage when clients submit next application.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The private keys will be stored in the hard wallet and will be accessible only by the principal.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
According to the business & technology planning submitted by the applicant, we will conduct a sample survey on the applicant's business in effectiveness, continuity and usage after DataCap have been granted:
1. Communicate with organization, contact person online/offline from time to time;
2. Submit the information to prove the business is in operation;
3. Extract and view data samples;
4. Query the usage of DataCap.
If the applicant is found that they use DataCap irresponsibly or exchange benefits existing, the applicant shall immediately disclose this information to the authorities and cooperate in the verification.  If it is true, the applicant shall be disqualified from the allocation.  The processing result and the true situation shall be published to the community.
1. Why did your company choose IPFS industry and decentralized storage?
2. Can you give more details about duration, nature, scale of your company?
3. What industry does the company mainly serve/how many people are served?
4. Can you present future business or technology plans?
5. Can you explain in detail about data type, and copyright ownership?  And how much data will your company store?
6. Does your company need to call for stored data, and if so, how often it happens?
7. How many miners do you want to choose for storing the data?  How much DataCap will be allocated to each miner?
8. Will you publicly record allocation decisions? Which platform will you use?

In the application process, We will confirm with the client whether there are cooperative miners.  If there are, we will ask them to clarify the location of the miners, miners' ID, the proportion of distribution and the reason for selecting the miners;
If not, we will actively guide them on how to find miners (e.g. Slack, MS Cloud, Miner reputation system, etc.);
After allocation, we will require the customer to timely publish the trasaction information, including the location of the miners, miners' ID, the proportion of distribution, etc.
We will follow up every week.  If no abnormality is found, we will gradually expand the allocation;
If there is any abnormality, we will remind you in time.  If the client does not cooperate, we will terminate the subsequent allocation and confirm with the official whether the previous allocation can be recovered from the technical level.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
During the application phase, it is required to clarify the miner ID and other information.
After the application, it is required to publish transaction information, including miner ID, allocation proportion and the source of miners, etc. , and will be reviewed at a fixed time each week.
```
### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be public.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We will record in the form of table
(https://docs.google.com/spreadsheets/d/1FEBqBEiSb9GchyVmqqneddoiJ-RMOQu46bjR1Nn2cZ4/edit?usp=sharing), including Issue Number;  Applicants;  Current State;  DataCap Requirements;  Application Date;  Website/Social Media;  Nodes and Proportions;  Filecoin Address;  GitHub Account;  Result;  Result Time;  DataCap Allocation;  Remarks.
At the same time, We will store deal reputation information and basic client information in a distributed and irreversible manner, including but not limited to datacap allocation decisions;
The user handle the registration, login, edit the basic information, submits the datacap request and other actions.  All information are recorded by the matching system.
All allocations will be updated and published on the GitHub issue to follow up on DataCap allocations and related informations of allocation.
All allocation information is recorded on GitHub, table, and MS Cloud.  The information is open and transparent.  If there is any abnormality, we will update it on the GitHub issue simultaneously.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
https://github.com/filecoin-project/notary-governance/issues/436
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None
```

**Comment by panges2** [comment]
Hello @MatrixStorage,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by MatrixStorage** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecnosbmoydsxdov26hse4sqhku4fv7b6b4vxvsjqkfclaggdkfa3i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnosbmoydsxdov26hse4sqhku4fv7b6b4vxvsjqkfclaggdkfa3i

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[719.pdf](https://github.com/filecoin-project/notary-governance/files/10159475/719.pdf)

**Comment by MatrixStorage** [comment]
**Allocation strategy**
As for DataCap allocation strategy, I would like to add the following information. 
1. We ask clients to apply again after they have used up DataCap allocated.
2. We will check previous DataCap storage in SPs, and if there is anything do not conform to the community rules, we will ask the client to make explanation and adjustment before allocation.
3. We will also help those clients who want to apply and regulatory compliance in the enterprise so that they can successfully join Filecoin network. 

**Client due diligence**
**We will put more emphasis on the use of various tools.**
We review the credentials of clients through tools that we have shared with the FIL-e project team in public meetings, such as [https://www.qcc.com/.](https://www.qcc.com/) We have also provided the project team with a complete KYC verification process that helps us fully understand our clients. For non-Chinese enterprises, we will also ask them to provide inquiry tools simultaneously when providing the subject information, so as to ensure that we can know regulatory compliance; Of course, we will also require clients to provide some enterprise qualification documents with signature authorization or sealed documents, which can also ensure that we have a deep understanding of the enterprise and identify potential risks in advance.
In addition, after DataCap allocation, we will also communicate and track the clients' business continuation and storage distribution, including using Wechat, Slack and other instant tools, which will also help us to find problems in time. We will also use similar websites such as https://filplus.d.interplanetary.one/ and our own operating tools to supervise the client's past DataCap allocation. And we will remind them to reasonably make DataCap distribution. if it is before DataCap allocation, We will ask questions and make allocation decisions after the client has corrected them; If it is after the allocation, we will give a warning and terminate the allocation. Then we will also mark the client and inform other notary public their behaviors.

**BookingPlan**
All DataCap allocation will be publicly available to everyone on Github, and we'll record in our own public documentation. At the same time, all relevant data we collect from clients will be stored through Google cloud desk(https://drive.google.com/), so that other community members can easily retrieve or download according to the audit request at any time. For example, similar to what we did in the fil-e project, we would translate the related materials into English that everyone could understand so that it could be reviewed by the community.
<img width="1083" alt="pic" src="https://user-images.githubusercontent.com/82867405/206893305-44b8e78e-05a3-45c4-a895-0b3f6463fc2c.png">
<img width="385" alt="pic2" src="https://user-images.githubusercontent.com/82867405/206893307-871aa8e5-bdfd-4c7f-9ea9-b8c7c957b8cc.png">

**Comment by MatrixStorage** [comment]
@galen-mcandrew Thank you for your rating.  For part of the work, we have made detailed supplements and the use of tools, which will make our plan more comprehensive.

**Comment by MatrixStorage** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceakexf6tnrumk6h3qso5soxbv5s5utkuan675ndg7gkowgdpozksk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceakexf6tnrumk6h3qso5soxbv5s5utkuan675ndg7gkowgdpozksk
