### ISSUE TITLE
Notary Governance Call - Jan 5th 5pm UTC

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/notary-governance#72]
Per our standard schedule of bi-weekly calls, we have another call for Jan 5th at 5pm UTC (as also described before break in this issue: https://github.com/filecoin-project/notary-governance/issues/62) 

Below are proposed agenda topics, but please feel free to add any if you have more: 
- Discussion of any open issues
- Discussing timeline for the New Year
- Open questions and discussion

Please add more topics as comments below if you have more to discuss!

**Comment by jnthnvctr** [comment]
In advance, here is the details for the meeting: 
https://protocol.zoom.us/j/93414028246
Passcode: 554538

**Comment by IPFSUnion** [comment]
Dear All,

I would like to propose an agenda for today's meeting which is：  "adding 2-3 more Filecoin Plus Notaries for GCN region"

The motivation and rationale is explained in following document：

https://docs.google.com/document/d/1iaFcc6ijjgSYeIpHqSyFxvXrlMBO0IbGXHAZqnjUjz0/edit?usp=sharing
