### ISSUE TITLE
Notary Application: DeFIL

### ISSUE THREAD

**Issue by Edenwu777** [filecoin-project/notary-governance#720]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Eden
- Affiliated organization: DeFIL
- On-chain address to be notarized (recommend using a new address): f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
- Country of Operation: Greater China
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: Professional Services、Developer Tools、Decentralized Applications、Public or Open Data
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization--- DeFIL

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
DeFIL is a decentralized Filecoin lending and financial services platform designed to bridge the gap between FIL's primary and secondary markets. It provides miners with access to pledged currency or risk hedging through the issuance of standard computing power tokens. It also provides ordinary investors with access to FIL mining and benefits to existing FIL users.

The DeFIL platform is funded by IPFS Eco-Fund, Fenbushi Capital, FBG Capital, Gate Labs, ZB Capital, and others. The platform's TVL once reached a maximum of $250 million, pledging FIL amounted to 1.667 million, and lending FIL amounted to 1.186 million. As the Filecoin industry's first truly decentralized financial platform, we have solved the problem of insufficient liquidity in the industry, which is a significant milestone for the Filecoin circuit.

Evidence：
https://www.jinse.com/lives/267735.html
https://www.jinse.com/lives/247059.html

2021 is a year of rapid growth for the Filecoin industry. In this year, we have held several IPFS and Filecoin talks in Chengdu, Shenzhen, Hangzhou and other cities, enabling tens of thousands of people to learn about IPFS&Filecoin. In August of that year, DeFIL won a prize at the Filecoin Grant Hackathon.

Evidence：
https://www.jinse.com/news/blockchain/1130655.html
https://www.jinse.com/lives/262689.html

We've also formed the DeFIL community to make a better place for people to learn and interact Filecoin. In the future, we will continue to work on the IPFS&Filecoin track to create more value for the industry.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
We have 663.05PiB of power on our platform and mining partners, you may search in the official website (https://app.defil.org/miners)，the following are some of the cooperative miner nodes:

https://filfox.info/en/address/f0688165
https://filfox.info/en/address/f0127595
https://filfox.info/en/address/f0123261
https://filfox.info/en/address/f0128559
https://filfox.info/en/address/f01108594
https://filfox.info/en/address/f01173139
https://filfox.info/en/address/f01173170

At present, users have deposited 350,000 FIL tokens on the DeFIL platform. eFIL is the mapping of FIL tokens on the ETH and BSC chain. You can find it on the official website:

https://app.defil.org/pools/lend/efil

(Tips: To query the website data, you need to connect wallet)
```

How did you acquire the FIL cited above?
```
DeFIL is Filecoin SP, invested in Filecoin mining
At the same time, we also have cooperative mining partners
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
In 2020, we launched Filecoin lending and financial services platform DeFIL, which is expected to help dozens of miners solve the problem of pledging their coins. Miners get FIL by pledging their mining machines and computing power to the platform, and then continue to participate in Filecoin mining without having to pledge additional assets. This greatly saves the miners the cost of digging.

The platform also helps FIL owners make more money by lending FIL to miners on the DeFIL platform at a steady interest rate.

In May 2021, the maximum number of FIL tokens pledged by the DeFIL platform was 1.667 million, and the maximum number of FIL tokens lent was 1.186 million.

Evidence：
https://www.jinse.com/lives/247059.html

We have also established a community based on the concept of IPFS, serving nearly 10,000 users. Not only do we actively promote IPFS in the community, but we also talk to Filecoin officials on slack channels. The DeFIL platform has become one of the most important infrastructures in the Filecoin ecosystem.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
We made an even more important contribution to Filecoin, which is the cross-chain bridge. The DeFIL platform allows FIL holders to safely convert Filecoin from FIL to ETH or BSC in a cross-chain manner and carry out on-chain activities. This feature not only provides liquidity to the Filecoin industry, but also maximizes revenue for FIL holders.

Cross-chain bridge link:
  https://app.defil.org/bridge

Cross chain bridge use tutorial:
https://defilofficial.gitbook.io/support-center/v/english/jiao-cheng/kua-lian-qiao/how-to-convert-efil-to-fil
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
We are a mining pool alliance formed by more than 20 large mining nodes such as FILPool and LDPool, all decisions are made by public voting. Investment institutions include Fenbushi Capital, IPFS Eco-Fund, FBG Capital, ZB Capital, ZBG Capital, Gate Labs, etc. DeFIL is a decentralized Filecoin lending and financial services platform designed to bridge the gap between FIL's primary and secondary markets.

-Registration Country: China
-Organization size: More than 20 institutions
-Time since establishment: 2020
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website：https://defil.org/
TG-CN：http://t.me/defilorg
TG-EN：https://t.me/defilorgEN
Twitter：https://twitter.com/defilofficial
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://v.qq.com/x/page/f32580b0tus.html
https://xw.qq.com/cmsid/20210831A035O100
https://mp.weixin.qq.com/s/7Qp6E0gC7770L_cunckgWQ
https://mp.weixin.qq.com/s/lD82W14ZcebysYu89G69wA
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter
https://twitter.com/defilofficial
followers: 2.2K

Telegram
TG-CN：http://t.me/defilorg
TG-EN：https://t.me/defilorgEN
members: 5K
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://mp.weixin.qq.com/s/sNgeh15sv3Hv1_kE_c8mBg
https://mp.weixin.qq.com/s/dMluQ-jig0a9kKsqqcbAzQ
https://mp.weixin.qq.com/s/JPtcwMge15XAxFYNks-aZQ
https://mp.weixin.qq.com/s/7hxO7f6u_hZ2zWmwrEYH6g
https://mp.weixin.qq.com/s/VlyLJGfvtKsEpOdKN0Vqhg
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We will consider the following factors while allocation the DataCap:
1.Basic customer information and industry reputation
2.Binding relationship between customer and mining machine
3.Use cases diversity
4.Scale&Frequency of allocation
5.Safety Precautions

At the same time, we will verify the authenticity of customers and the validity of data through offline audit. Conduct spot check once a month and general survey every quarter to grasp the basic information and update progress of customers in time, and then change the allocation proportion according to the investigation.

We will strictly implement the allocation strategy and conduct a detailed investigation of the customer's information. For the clients who apply, we will make a file and score each client. We will distribute according to the score. It is worth noting that we will update the archives regularly. For clients who are progressing, they deserve more attention. We hope to build a healthy system in which people can make continuous progress and welcome more and more people to participate.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Our address is generated by ledger, and the private key of ledger is managed and backed up by the founder of DeFIL.
We created a three-person DeFIL notary team, and the three parties supervise each other, but only the founder of DeFIL has more authority because he is the only one who knows the mnemonic.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Customer Information and purpose of application is one of the important criteria for our audit. We conduct in-depth research on customer information and ask about the purpose of application, so that we can understand the real demand of customers and avoid the subsequent risk.

1.Research company entity information

Anyway Basic information: Company registration qualification/Business license/Information certificate, etc
Additional information: Certificate of Honor/Computer software copyright, etc

2.Investigate the company

Principal business/Product introduction/Other business
Fiscal Annual financial statement/Asset management statement

3.Signing cooperation agreements

The application form is signed and sealed by the legal person or responsible person
Submit a copy of the company's business license, etc.


We will ask the following questions:

What type of data do you want to store and for what purpose?

What are your plans for the number of miners to store the data, the area, and the assigned number of miners per miner?

What safety precautions do you have?

Do you comply with local laws and regulations and accept the miners'Terms of service?

We regularly spot check users to see if they are as well as they say.

Finally, we will clearly tell customers that we will track DC through the official website. For example, https://filplus.d.interplanetary.one/
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. We require customers to disclose their addresses, set up tracking records, and rigorously investigate the customer's stored data

2. We will have a special customer rating database, for low-scoring, poor performance of the customer will be a warning or punishment

3. For storage data diversity, high data authenticity of the customer we will improve the score, and make public praise

4.Finally, we will recruit community volunteers to participate in the monitoring，At the same time, we encourage the community to check and consider setting up a reward mechanism. It is best to mobilize everyone's power to supervise. If a client cheats, we will consider discussing it at a notary meeting.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
The final decision is made public on Github and notified to each customer in at least three ways. For customers' different opinions, we will set up a two-week publicity period, customers can submit personal suggestions, and we will hold an online meeting to make a final decision.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Github and official website
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
Our company invites a colleague who has a CET-8 score and a near perfect score in IELTS to attend every notary meeting. After the meeting, he will sort out the notes and give them to our team.
Every morning when we arrive at the company at 9:00, we will open slack to check the latest news.
In the past year, we also participated in some github FIP reviews.
We may be between L3-L4
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes.

https://github.com/filecoin-project/notary-governance/issues/446
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None.
```

**Comment by Defil2022** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebmn7zsnujylsqu4v7gi2hflua46zmqqwn6hzfshmgh3sqo5nz7rg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmn7zsnujylsqu4v7gi2hflua46zmqqwn6hzfshmgh3sqo5nz7rg

**Comment by panges2** [comment]
Hello @Edenwu777,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Edenwu777** [comment]
Hello,Email has been sent

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[720.pdf](https://github.com/filecoin-project/notary-governance/files/10159476/720.pdf)

**Comment by zizi-defil** [comment]
kevin ，we updated the form again with our full legal name thanks

**Comment by dkkapur** [comment]
@mikezli defil.org and app.defil.org are not loading for me. any idea what's going on?
