### ISSUE TITLE
 Notary Application: Stone moon Galaxy Ltd

### ISSUE THREAD

**Issue by StoneMoonGalaxy** [filecoin-project/notary-governance#724]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:StoneMoon
- Affiliated organization: Stone moon Galaxy Ltd
- On-chain address to be notarized (recommend using a new address):f1227koppjsmzpcmm2gxxfo753uv25qnywpqff4xq
- Country of Operation: Australia
- Region of Operation: [Oceania]
- Use case(s) to be supported: Professional Services/Public or Open Data
- DataCap requested for allocation (10TiB - 1PiB):100TiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
I have been following this filecoin project since 2020 and invested a node f0399346, it has 35.73 PiB power.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f0399346 
Initial Pledge: 283,955.4459 FIL
Total Reward: 482,854.46 FIL
```

How did you acquire the FIL cited above?
```
Personal input
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
None
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
As a Chinese Australian, I have been developing Filecoin in China since 2020. Due to policy reasons in Greater China, a large number of our computing servers have  confiscated, our whole business was interrupted for nearly half a year.

For the past two years, we have accumulated technical experience and client resources. At the same time, we have also deeply studied many projects in the Web 3.0 area. We believe that Fil is the leading project. 

I moved my business to Australia and set up StoneMoon on February 9, 2022. I am prepared to run Filecoin-related services in Australia on a long-term basis.

StoneMoon is a non-stop platform that provides storage solutions. We are currently a team of nine people, most of whom are technicians. We continue to be optimistic about the Filecoin project. With the accumulation from 2020 to 2022, we have been able to carry out fast seal and stable O&M, and are ready to follow up the development of smart contract application on FVM for a long time. Currently, the recruitment process is underway for developers and operators in the area of smart contracts.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Slack：StoneMoon
Twitter：https://twitter.com/StoneMoon
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Twitter：https://twitter.com/StoneMoon
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter：https://twitter.com/StoneMoon
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
Twitter：https://twitter.com/StoneMoon
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Based on Fil+ 's ideas and ground rules, we believe that the key of DataCap's allocation is:
· Review the real demands of clients and their reasonableness
· Filter data use cases that conform to the rules
· Standardize and establish an operational client application process
· Encourage storage and retrieval, and attract more individuals and organizations to participate in Filecoin ecological construction

Job Description:
· Processing client applications in time. We plan to spend 2 hours/day and 5 days/week on Fil+community affairs, including processing client applications, participating in community discussions, paying attention to community dynamics, and participating in Community Call.
·  Verify client information through our audit standards,
Including but not limited to account information, organization certificate, data rationality, samples, SP information, etc
· Guide clients to prepare certificates that meet requirements and guide how to find miners. For example, they need to respond to any audit requests for their allocation decisions through filplus.info and slip
·Completely record the decision-making process, client files, and synchronize github
·Track and spot check the datacap allocation of clients, SP allocation, and prevent abuse, counterfeiting, malicious hoarding, etc. Once we find violations, we will immediately stop the distribution, mark and make the announcement.
·Pay attention to the retrieval after client storage to ensure the integrity and continuity of the entire effective data storage

We will use the following tools when evaluating a client and determining its DataCap allocation. Each applicant will be scored based on the following factors and criteria.
https://docs.google.com/spreadsheets/d/1dAcpQKjDz2VAfiu3edvmfDr-qGTCRXOauG0CNFOREZg/edit?usp=sharing
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Hardware Wallet Management
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1. Can you introduce yourself and your company? Including social media/news references and other links.
2. Describe the nature of your organization, project, or use case. For the organization, include your relationship with the organization, the size of the organization, and how long it has been since its inception. For projects and other use cases, link to the relevant website or Github. Please include as much relevant detail as possible to provide contextual information (with external links).
3. How much do you know about the Filecoin network? What prompted you to choose it as your data store?
4. How much do you know about Filecoin DataCap? Once approved, what are your expectations for using DataCap?
5. Does your organization have the resources and budget for your Filecoin data storage project?
6. Why are you applying for DataCap and your type of data storage is worth the cost of DataCap?
7. Do you plan to store more data than DataCap allocates?
8. How many DataCap do you want to request?
9. What is the use case for the requested DataCap?
10. How long has your company been using cloud storage? How much data do you store in the cloud?
12. What percentage do you want to allocate from your current cloud storage to the Filecoin network?
13. What types and sources of data do you want to store in Filecoin, such as public vs. private data, and so on?
14. Once you get the datacap, will you make the deal record into public?
15. In which country/region do you plan to use DataCap? Please indicate if you plan to use DataCap in more than one country/region.
16. Do you plan to distribute the majority of DataCap to a single SP or to spread it among multiple SPs? If you have other SPs, please note.

We will continue to track the clients for the dc after use, and through the verify.glif.io、filrep.io、filplus.info、filplus.d.interplanetary.one. One such as data platform to verify the usage of the client, at the same time record in the  bookkeeping：Client dc tracking records/https://docs.google.com/spreadsheets/d/1EhUcmYzQ_Q7T47d-FiSGIzqokO6QSXwZEVck72GZYcM/edit?usp=sharing
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Since you have applied DataCap from me before, I have some problems with your previous DataCap distribution.
1. How many SPs do you assign DataCap to? What region does SP belong to?
3. How many DataCap will you require in the future?
4. Can data be retrieved normally?
Using the information collected will help me confirm that clients are not improperly using the DataCap they were previously granted. clients are encouraged to allocate DataCap to more than five different SPs, which not only increases storage redundancy, but also helps maintain dispersion and reduces the potential for misuse.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yeah, both ways
Information Registration/https://docs.google.com/spreadsheets/d/1EhUcmYzQ_Q7T47d-FiSGIzqokO6QSXwZEVck72GZYcM/edit?usp=sharing
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Make all records public on github.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
N/A
```

**Comment by panges2** [comment]
Hello @StoneMoonGalaxy,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[724.pdf](https://github.com/filecoin-project/notary-governance/files/10159482/724.pdf)

**Comment by StoneMoonGalaxy** [comment]
Hi,@galen-mcandrew, @Kevin-FF-USA 
Thanks for your review, I updated the Allocation Strategy, Due Diligence, and Bookkeeping plan in Notary Application.

### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Based on Fil+ 's ideas and ground rules, we believe that the key of DataCap's allocation is:
· Review the real demands of clients and their reasonableness
· Filter data use cases that conform to the rules
· Standardize and establish an operational client application process
· Encourage storage and retrieval, and attract more individuals and organizations to participate in Filecoin ecological construction
When evaluating clients and determining their DataCap allocation, we thought issue#413 would be a good use case to draw from, we will set up 7 different levels of trust that can be reasonably allocated according to the following allocation rules.
Link: https://docs.google.com/spreadsheets/d/1dAcpQKjDz2VAfiu3edvmfDr-qGTCRXOauG0CNFOREZg/edit#gid=1453211241
For different types of customers, , we will also use the third party verification tool such as Fakefollowers, twitteraudit to verify online.

```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Based on my observations and learning in the fil+ community, I have gained a deeper understanding of the difficulties and importance of customer due diligence, especially the issues of counterfeiting, hoarding and abuse that have emerged in the review of some recent appplications, so I have updated my review strategy.
Applicant Investigation—
Verification of the applicant's association with the organization (email verification, proof of employment, etc.)
Entity investigation—
Individual clients:
KYC information, submission of identity documents and valid proof of residence (the last three months)
Corporate clients:
--company information (full name, address, region, registration number, country) 
--KYC information of the company owner (or legal representative of client's company). This means clients need to pass the residency verification by submitting identification documents and a valid proof of residency for the last three months. The legal representative must disclose the legal documents he/she submits. If he/she is not marked on it, his/her KYC process cannot be verified. 
--Submit all legal documents of the company (Memorandum of Association, Bank Statements, Certificate of Incorporation, Register of Shareholders and Directors). If they do not have a bank statement, they can submit an additional document with a clear business address. 
-- UBOs holding more than 25% of the shares must submit all their KYC information (proof of identity and residence).
Data survey —
--Data volume
--Data copyright
--Data sample 
We get to know our clients through the following questions, mainly for first-time applicants:
1. Can you introduce yourself and your company? Including social media/news references and other links.
2. Describe the nature of your organization, project, or use case. For the organization, include your relationship with the organization, the size of the organization, and how long it has been since its inception. For projects and other use cases, link to the relevant website or Github. Please include as much relevant detail as possible to provide contextual information (with external links).
3. How much do you know about the Filecoin network? What prompted you to choose it as your data store?
4. How much do you know about Filecoin DataCap? Once approved, what are your expectations for using DataCap?
5. Does your organization have the resources and budget for your Filecoin data storage project?
6. Why are you applying for DataCap and your type of data storage is worth the cost of DataCap?
7. Do you plan to store more data than DataCap allocates?
8. How many DataCap do you want to request?
9. What is the use case for the requested DataCap?
10. How long has your company been using cloud storage? How much data do you store in the cloud?
12. What percentage do you want to allocate from your current cloud storage to the Filecoin network?
13. What types and sources of data do you want to store in Filecoin, such as public vs. private data, and so on?
14. Once you get the datacap, will you make the deal record into public?
15. In which country/region do you plan to use DataCap? Please indicate if you plan to use DataCap in more than one country/region.
16. Do you plan to distribute the majority of DataCap to a single SP or to spread it among multiple SPs? If you have other SPs, please note.

We will continue to track the client after the DC is used, and through verify,gllifi.io,filrep.io,filplus.info,filplus,d.minterplanetary.one.
Query customer usage and record in bookkeeping.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Allocation follow-up
To avoid misuse or abuse,we will review or spot-checking of data through the online platform
(filplus.d.interplanetary.oneor filplus.info) after DataCap allocation . Here is the specific review principles.
--verification of the SP: (for individual SP, they need provide identification documents, for organisations, they need provide company documentation and official documents, etc.)
--Too many applications are associated with the same SP (we can only verify this manually, and we expect official verification tools can assist with this in the future.)
--Check if SPs follow the allocation guidance "at least 4 SPs and no single SP ID should receive >30% of a client's allocated DataCap".
--Provide Cid for searching sample random and if there is any abuse of DataCap we will take steps to stop further distribution.
We will collect information of clients who already have a record of distribution through the following questions.
1. How much DataCap have you received before?
2. Please provide proof of SP's entity.
3. Is the any data that you have stored retrievable, please provide Cid?
4. How many SPs have you plan to choose? Where is the area they are located?
5. Please keep the SP ID accessible to ensure that we can readily view the node information that you have provided.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We will fully follow the FIL+guidelines and publish our allocation decisions on Github.
https://github.com/filecoin-project/filecoin-plus-client-onboarding
https://filplus.info/
We will make all information public and establish a detailed database for data audit and analysis. We will accept any audit without doubt.
Bookkeeping plan link: https://docs.google.com/spreadsheets/d/1EhUcmYzQ_Q7T47d-FiSGIzqokO6QSXwZEVck72GZYcM/edit#gid=0
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
On GitHub & and all other platforms such us: filecoin-plus-client-onboarding, filplus.info
Bookkeepingplanlink: https://docs.google.com/spreadsheets/d/1EhUcmYzQ_Q7T47d-FiSGIzqokO6QSXwZEVck72GZYcM/edit#gid=0
```

**Comment by Kevin-FF-USA** [comment]
@StoneMoonGalaxy 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
