### ISSUE TITLE
Notary Application: Fujian Endex Technology Co., Ltd.

### ISSUE THREAD

**Issue by filtakes** [filecoin-project/notary-governance#728]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Endex
- Affiliated organization: Fujian Endex Technology Co., Ltd.
- On-chain address to be notarized (recommend using a new address): f1a565iwd3cd36ffzzzt2lto3przyonk4g6q5waeq
- Country of Operation: China
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: Public or Open Data, Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB): 500TiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
The company was established in 2021, and our founder Hongji Wang has been focusing on the FILECOIN ecology since 2019. As an early evangelist, he is committed to promoting filecoin technology, and participated in the space race in 2020, and provided strong support for the subsequent hardware equipment supply chain.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
It is temporarily inconvenient to disclose the specific amount
```

How did you acquire the FIL cited above?
```
Part of it comes from our investors, and we also bought a part from the exchange.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As an early evangelist of filecoin, we continue to publish technical and media inquiries about filecoin on various media channels：
https://xueqiu.com/5129186038/216179373
https://xueqiu.com/5129186038/221961844
https://mp.weixin.qq.com/s/w3qPG_FAojXLb_fPurKkgg
https://mp.weixin.qq.com/s/S2WdRoLsZF823R0ilTGHbA
https://www.bilibili.com/video/BV1H34y1E7Kk/?spm_id_from=333.999.0.0&vd_source=451fdb5f2c9572a4455c5992c1fcb194
https://www.toutiao.com/c/user/token/MS4wLjABAAAAPvzC99G25lGDfpfHQJq145ASkth8HwlOlcLChVVDbs3OuGGXK9V0Z_P_EoNK_kU3
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Name: Endex
Country of registration: Fujian China
Employees: Over 10 employees 
Founded: Founded in 2021,
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: http://www.endex.vip
Named officers: Wang Hongji
Wechat: 恩德克斯endex
Bilibili: ENDEX恩德克斯
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.sohu.com/a/538225152_121374527
http://blog.eastmoney.com/o3582376493897852/blog_1166446165.html
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Toutiao: Filecoin爱好者社区 140followers

https://www.toutiao.com/c/user/token/MS4wLjABAAAAPvzC99G25lGDfpfHQJq145ASkth8HwlOlcLChVVDbs3OuGGXK9V0Z_P_EoNK_kU3

Weibo: IPFS村长 179followers
https://weibo.com/u/5736221879
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
N/A
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
First of all, we will try to balance the proportion of data types
Public or Open Data: 60%
Media & Entertainment: 30%
Other: 10%

Second, we will conduct a strict KYC review on the client and classify clients according to organizations and individuals, and divide them into several levels based on organizational reputation, business scale or personal reputation

https://docs.google.com/spreadsheets/d/1NZuLhBtlc9bPWidAuJQfRt6Rs97rE7vugUpYiUD6lKg/edit?usp=sharing

We will establish a credit mechanism for applicants, and encourage honest, active, and qualified applicants to use DataCap effectively and efficiently
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hard wallet that can only be accessible by me.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 

In the early stage, all clients are required for an onboarding process to be qualified.
We will collect and verify client information, including: personal or organizational identity information, this includes certificates of registration/incorporation/information. Related data authorization information, etc.

After approval, we will require clients to display transaction information, including miner number, allocation proportion and the source of miners, etc., and then follow up weekly on this basis.

Question List:
1. Please describe your organization, such as established time, the number of employees, users volumn, the number of social media followers.
2. In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.
3. Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.
4. What kind of method did you mainly use to deliver data? online, offline, and other methods
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Using filplus.info can easily reveal if a storage client is only sending deals with a single SP miner id. 
And I will use other questionnaires to gather more information:
1. In which region(s) did you use the DataCap?
2. What was your use case for the previous allocation?
3. In your previous allocation, did you violent any community principles like excessive/unfair self-dealing?

I will also conduct community inquiries to confirm whether the client has violated the rules.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, in public.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub repo
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4: <8 hours of engagement per week
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
N/A
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
N/A
```

**Comment by panges2** [comment]
Hello @filtakes,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[728.pdf](https://github.com/filecoin-project/notary-governance/files/10159484/728.pdf)

**Comment by Kevin-FF-USA** [comment]
Hi @filtakes,
I cant find a record of receiving your email verification. If you have not already done so, please email by 06DEC. If you have already sent, can you please re forward or paste the token code here that you received. Thank you

**Comment by filtakes** [comment]
Hi @Kevin-FF-USA , so far, I still haven't received a reply email, is there something wrong?

**Comment by Kevin-FF-USA** [comment]
@filtakes 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
