### ISSUE TITLE
Notary Application: Top Value Finance

### ISSUE THREAD

**Issue by luobin544** [filecoin-project/notary-governance#729]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Top Value Finance
- Affiliated organization: Top Value Limited
- On-chain address to be notarized (recommend using a new address): f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
- Country of Operation: USA
- Region of Operation: North America
- Use case(s) to be supported: [Please select from [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries)]General, Professional Services (Hosting Reseller, Long-term Backups, Data Warehousing), Developer Tools (Package Managers, Automatic Notaries, Web2 to Web3 integrations), Decentralized Applications, User Content (Personal Storage), Public or Open Data (Scientific datasets, research data, government or historic, Media & Entertainment (Videos, photos, NFTs)
- DataCap requested for allocation (10TiB - 1PiB):1 PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Top Value Finance has been actively participating in FIL mining and investment since its establishment in 2021. We believe in Filecoin as an indispensable part of the next-generation Internet in storage. We went in for mining and currently hold a scale of 170 PiB (Please find details via the following link: https://1drv.ms/x/s!AqjwJGQA5GYrhEgsxPxf0JyoBpRD?e=ufpPg1). Besides that we partnered with Huobi Asset Management (Hong Kong) successfully launched an IPFS infrastructure mining fund this year,ethusiastically to make our contribution in calling on more professional investors to join the Filcoin Network developing progress. We are presently in the progress of corporating with Protocol Labs to enhance our participation in Filecoin community.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
We have about 2,300,000+ Fil in Miner accounts (1,370,000+Fil, Please find details via the following link: (https://1drv.ms/x/s!AqjwJGQA5GYrhEgsxPxf0JyoBpRD?e=ufpPg1) and Binance account (300,000+Fil) and Topvalue wallet (700,000+Fil).
```
How did you acquire the FIL cited above?
```
We acquired the above cited FIL from mining rewards, purchasing and borrowing.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Top Value Finance has been actively participating in FIL mining and investment since its establishment in 2021. We believe in Filecoin as an indispensable part of the next-generation Internet in storage. We went in for mining and currently hold a scale of 170 PiB (Please find details via the following link: https://1drv.ms/x/s!AqjwJGQA5GYrhEgsxPxf0JyoBpRD?e=ufpPg1). Besides that we partnered with Huobi Asset Management (Hong Kong) successfully launched an IPFS infrastructure mining fund this year,ethusiastically to make our contribution in calling on more professional investors to join the Filcoin Network developing progress. We are presently in the progress of corporating with Protocol Labs to enhance our participation in Filecoin community.
``` 

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
TOP VALUE FINANCE   (Abbreviated as "TV FINANCE"）is a professional digital asset management agency registered in Cayman Islands and operated in Singapore. TV FINANCE is backed by more than 600 digital asset exchange customers, more than 150 wallet customers, more than 120 liquidity customers, more than 500 WaaS Alliance customers and thousands of mining customers. It has launched a professional wallet asset custody platform-Waas Alliance, and established the Defi Liquidity Mining Fund, Digital Asset Quantitative FOF (Fund Of Fund) and FIL Mining Fund. Since its establishment in year 2021, the TV FINANCE team has built a unique digital asset risk control system with a "computer + finance" approach. By ensuring the customer assets safety, it aims for "the highest value for its customers", while achieving considerable investment profit.At present, the return rate of FIL mining fund is at the leading level in the industry.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://topvalue.pro/
twitter handle：@topvaluefinance  （1 W+Followers)
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
None
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
twitter handle：@topvaluefinance  （1 W+Followers)
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
None. 
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The purpose of our allocation strategy is to ensure our clients storing real and valid data in right way. In order to achieve this goal, we will apply rigorous rubric to client evaluation and Client's DataCap allocation. Please refer to the following link for our Client rubric:https://1drv.ms/x/s!AqjwJGQA5GYrhD4Z0cGEdk80cfCY?e=BjM232
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The key allocated to the DataCap will be protected on the multi-signature hardware wallet.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will implement both on-boarding Client due diligence and post-allocation vetting. For the onboarding due diligence, we will collect KYC & onboarding documents to identify the client, including the Client’s name, contact details, registration number, registration date, registration certificate, scope of business, members of board and senior management and beneficial ownership structure. Meanwhile, we will perform post-allocation vetting by checking  statistics on  filfox on a regular basis and constantly monitor to ensure that no allocated DataCap being abused or misused, but being  spent exclusively for the approved uses.  In addition, as the DataCap will be allocated by stages, we may penalize the Client by delaying or even cancelling the outstanding DataCap if discovering any improper or fraudulent spending the allocated DataCap.

```
What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Firstly, we will review our clients' storage orders and relevant storage providers through but not limited to  checking statistics concerned from websites like https://filplus.d.interplanetary.one/ and filfox on daily basis to ensure the assigned DataCap has not been abused or misused. Secondly, we will allocate the granted DataCap to our clients gradually by stages, thus, on occurence of any improper use or misuse of the allocated DataCap being found, the unallocated DataCap will be reduced or even canceled.  Further on, in our Client rubric mechanism, bonus scores will be grant to clients will good previous  DataCap deploying performance, while past misbehaviour will lead to score deduction as penalty. For Client with malicious or material misconduct or misusing on previous DataCap assigned, we will take further punitive actions to cancel the client's remaining DataCap.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Github repo
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We will save detailed information in own GitHub repo, while making it public in the public repository：https://github.com/filecoin-project/filecoin-plus-client-onboarding  and  https://filplus.info/
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4 to L5. We will spend 10+ hours per week to perform our duty as a notary, reviewing every application carefully and actively participating in the Filecoin community.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No, we haven't.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
Yes, BingHe.
```

**Comment by panges2** [comment]
Hello @luobin544,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by luobin544** [comment]
We received the email regarding information verification. There is one requirement inside asking us to provide slack handle. As we have yet joined the filecoinproject.slack.com. , we submitted application to join it using the following email addresses: operation@topvalue.pro    k@topvalue.pro.
We would appreciate it if you could approve our application, letting us join the workspace as soon as possible.
Thank you.

**Comment by luobin544** [comment]
We've replied

> Hello @luobin544, Thanks for applying to become a Notary in the Fil+ program!
> 
> As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. *This cannot be from your personal account. You Must include the address of your Organization.
> 
> Subject Line: Notary Name, Application Number Email Body:
> 
> 1. Your First and Last name
> 2. Your Organization
> 3. Your Country of Operation
> 4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
> 5. Link to your GitHub application
> 
> This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.
> 
> Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2
> 
> Thank you!

We have replied the email with the following content.

1、Caira Wang
2、Top Value Finance
3、Singapore
4、No existing Slack handle, application (through comments on Github)to join pending for approval (Applicant' email addresses: [operation@topvalue.pro](mailto:operation@topvalue.pro)    k[@topvalue.pro)](http://topvalue.pro%29/)
5、https://github.com/filecoin-project/notary-governance/issues/729

We will update the slack handle information once our application of joining the slack workspace get approved.
Thank you.

**Comment by luobin544** [comment]
Dear Kevin and Panges,

In the previous Info Verification email, we explained our situation that we did not have existing Slack handle and we applied for using the following emails: operation@topvalue.pro and k@topvalue.pro to join the slack workspace. 
We would appreciate it if we could hear from you regarding the approval progress as soon as possible. 
Thank you for your understanding and support.

 @Kevin-FF-USA and @panges2

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[729.pdf](https://github.com/filecoin-project/notary-governance/files/10159485/729.pdf)

**Comment by luobin544** [comment]
Dear Kevin and Panges,

We have updated our stake exposure to the latest status as below.
Top Value Finance currently hold about 2,300,000+ Fil in Miner accounts (1,370,000+Fil, Please find details via the following link: (https://1drv.ms/x/s!AqjwJGQA5GYrhEgsxPxf0JyoBpRD?e=ufpPg1) and Binance account (300,000+Fil) and Topvalue wallet (700,000+Fil).

@Kevin-FF-USA and @panges2

**Comment by luobin544** [comment]
> **Thanks for your request!** ❗ We have found some problems in the information provided. We could not find your **Name** in the information provided We could not find your **Filecoin address** in the information provided We could not find the **Datacap** requested in the information provided We could not find any **Web site or social media info** in the information provided We could not find any **Expected weekly DataCap usage rate** in the information provided We could not find any **Region** in the information provided
> 
> ```
> Please, take a look at the request and edit the body of the issue providing all the required information.
> ```

# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Top Value Finance
- Affiliated organization: Top Value Limited
- On-chain address to be notarized (recommend using a new address): f14b22jglw2higaj7nzn6vio7nvskokx6f6sxqcii
- Country of Operation: USA
- Region of Operation: North America
- Use case(s) to be supported: [Please select from [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries)]General, Professional Services (Hosting Reseller, Long-term Backups, Data Warehousing), Developer Tools (Package Managers, Automatic Notaries, Web2 to Web3 integrations), Decentralized Applications, User Content (Personal Storage), Public or Open Data (Scientific datasets, research data, government or historic, Media & Entertainment (Videos, photos, NFTs)
- DataCap requested for allocation (10TiB - 1PiB):1 PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

## Long Term Network Alignment
### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Top Value Finance has been actively participating in FIL mining and investment since its establishment in 2021. We believe in Filecoin as an indispensable part of the next-generation Internet in storage. We went in for mining and currently hold a scale of 170 PiB (Please find details via the following link: https://1drv.ms/x/s!AqjwJGQA5GYrhEgsxPxf0JyoBpRD?e=ufpPg1). Besides that we partnered with Huobi Asset Management (Hong Kong) successfully launched an IPFS infrastructure mining fund this year,ethusiastically to make our contribution in calling on more professional investors to join the Filcoin Network developing progress. We are presently in the progress of corporating with Protocol Labs to enhance our participation in Filecoin community.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
We have about 2,300,000+ Fil in Miner accounts (1,370,000+Fil, Please find details via the following link: (https://1drv.ms/x/s!AqjwJGQA5GYrhEgsxPxf0JyoBpRD?e=ufpPg1) and Binance account (300,000+Fil) and Topvalue wallet (700,000+Fil).
```
How did you acquire the FIL cited above?
```
We acquired the above cited FIL from mining rewards, purchasing and borrowing.
```

## Industry Reputation
### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Top Value Finance has been actively participating in FIL mining and investment since its establishment in 2021. We believe in Filecoin as an indispensable part of the next-generation Internet in storage. We went in for mining and currently hold a scale of 170 PiB (Please find details via the following link: https://1drv.ms/x/s!AqjwJGQA5GYrhEgsxPxf0JyoBpRD?e=ufpPg1). Besides that we partnered with Huobi Asset Management (Hong Kong) successfully launched an IPFS infrastructure mining fund this year,ethusiastically to make our contribution in calling on more professional investors to join the Filcoin Network developing progress. We are presently in the progress of corporating with Protocol Labs to enhance our participation in Filecoin community.
``` 

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
TOP VALUE FINANCE   (Abbreviated as "TV FINANCE"）is a professional digital asset management agency registered in Cayman Islands and operated in Singapore. TV FINANCE is backed by more than 600 digital asset exchange customers, more than 150 wallet customers, more than 120 liquidity customers, more than 500 WaaS Alliance customers and thousands of mining customers. It has launched a professional wallet asset custody platform-Waas Alliance, and established the Defi Liquidity Mining Fund, Digital Asset Quantitative FOF (Fund Of Fund) and FIL Mining Fund. Since its establishment in year 2021, the TV FINANCE team has built a unique digital asset risk control system with a "computer + finance" approach. By ensuring the customer assets safety, it aims for "the highest value for its customers", while achieving considerable investment profit.At present, the return rate of FIL mining fund is at the leading level in the industry.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://topvalue.pro/
twitter handle：@topvaluefinance  （1 W+Followers)
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
None
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
twitter handle：@topvaluefinance  （1 W+Followers)
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
None. 
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
## Concreteness of Allocation Plan 
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The purpose of our allocation strategy is to ensure our clients storing real and valid data in right way. In order to achieve this goal, we will apply rigorous rubric to client evaluation and Client's DataCap allocation. Please refer to the following link for our Client rubric:https://1drv.ms/x/s!AqjwJGQA5GYrhD4Z0cGEdk80cfCY?e=BjM232
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The key allocated to the DataCap will be protected on the multi-signature hardware wallet.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will implement both on-boarding Client due diligence and post-allocation vetting. For the onboarding due diligence, we will collect KYC & onboarding documents to identify the client, including the Client’s name, contact details, registration number, registration date, registration certificate, scope of business, members of board and senior management and beneficial ownership structure. Meanwhile, we will perform post-allocation vetting by checking  statistics on  filfox on a regular basis and constantly monitor to ensure that no allocated DataCap being abused or misused, but being  spent exclusively for the approved uses.  In addition, as the DataCap will be allocated by stages, we may penalize the Client by delaying or even cancelling the outstanding DataCap if discovering any improper or fraudulent spending the allocated DataCap.

```
What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Firstly, we will review our clients' storage orders and relevant storage providers through but not limited to  checking statistics concerned from websites like https://filplus.d.interplanetary.one/ and filfox on daily basis to ensure the assigned DataCap has not been abused or misused. Secondly, we will allocate the granted DataCap to our clients gradually by stages, thus, on occurence of any improper use or misuse of the allocated DataCap being found, the unallocated DataCap will be reduced or even canceled.  Further on, in our Client rubric mechanism, bonus scores will be grant to clients will good previous  DataCap deploying performance, while past misbehaviour will lead to score deduction as penalty. For Client with malicious or material misconduct or misusing on previous DataCap assigned, we will take further punitive actions to cancel the client's remaining DataCap.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Github repo
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We will save detailed information in own GitHub repo, while making it public in the public repository：https://github.com/filecoin-project/filecoin-plus-client-onboarding  and  https://filplus.info/
```

## Service Level Agreement
### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4 to L5. We will spend 10+ hours per week to perform our duty as a notary, reviewing every application carefully and actively participating in the Filecoin community.
```


## Track Record
### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No, we haven't.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
Yes, BingHe.
```

**Comment by Kevin-FF-USA** [comment]
@luobin544 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by TopValueFinance** [comment]
@Kevin-FF-USA and @panges2

Dear Kevin and Panges,

Please note that we have updated the Notary address to:  f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q

Thank you.

**Comment by Kevin-FF-USA** [comment]
Updating address in CORE INFO based on comment

**Comment by panges2** [comment]
Hi @luobin544, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by luobin544** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecvk4k36x44xcgxndo7prnmdgne6prrwhwymu4tsifuvz7b3itxly
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvk4k36x44xcgxndo7prnmdgne6prrwhwymu4tsifuvz7b3itxly

**Comment by luobin544** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceavxmcxw6vgw3w6qb35bln7r4c7gusawrakboautbekr7m26t7r7a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavxmcxw6vgw3w6qb35bln7r4c7gusawrakboautbekr7m26t7r7a

**Comment by luobin544** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedrcuj3tsoczlvszr64cwdxkzr25p3daftudnobajr7br4zoe2cum
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrcuj3tsoczlvszr64cwdxkzr25p3daftudnobajr7br4zoe2cum
