### ISSUE TITLE
Proposal to allocate more notary and datacap quota to GCN region

### ISSUE THREAD

**Issue by IPFSUnion** [filecoin-project/notary-governance#73]
## Issue Description

Proposal to allocate more notary and datacap quota  to GCN region.

## Impact and Proposed Solution(s)

Simple Summary
To better serve the client, miner and community, it is necessary to increase the number of notaries and the datacap allocation for Filecoin Plus in certain regions, especially in GCN. The quota of notaries  and datacap volume can be related based on the miner power distribution in each specific region.as it is an indicator of local community size/influence or potential client numbers and other factors in certain regions.
 
Abstract
Allocating the quota of notaries and datacap volume based on the miner power distribution in each specific region will reinforce the Filecoin Plus as a whole. For example, more miner power means more miners, mining machines and Filecoin related activities in the region. It additionally indicates that there is more FIL is consumed or vested; more people are buying/selling mining machines or FIL; more Filecoin related activities are happening; more consensus and community size in the region. Therefore, it is rational to allocate notary quota according to the miner power distribution as it is an indicator of Filecoin consensus and community size/influence in each region.
 
Currently, there are 4 notaries in GCN. It stands for 28.57% compared with total 14 notaries nominated globally. However, the miner power distribution of the GCN region is around 800Pib. Compared with the total 1.728Eib power globally, the GCN power ration is around 45.3%. Thus, it is necessary to increase additional 2-3 notary quota in GCN. More notaries and datacap will not only better serve more Filecoin Plus clients but also improve the regional consensus. As a result, it improves the overall Filecoin ecosystem.
 
Motivation
The one of the most important motivations to add 2-3 new notaries in the GCN region and more datacap allocation is to better meet the needs of client, miner, and community, therefore to build a better Filecoin Plus ecosystem.
 
As discussed in the above abstract section, the miner power distribution is a objective indicator of many factors such as:

Mining-related: number of miners, mining machines;
Token-related: volume of FIL token trading, consuming and vesting;
Community/consensus-related: size of community members, Filecoin-related
Business-related: number of clients, understanding of Filecoin.

The higher the miner power indicates the better/higher the aforementioned factors in the region. The better/higher the aforementioned factors, the more and better services are required. Currently, the GCN region has contributed more than 800Pib miner power. However, it only occupied 4 notary quota (28.57%) compared with total 14 notaries globally. Meanwhile the power of GCN is around 800Pib by January 5, 2021. Compared with the total power 1.728Eib globally, the GCN’s power ration is around 45.3%. Therefore, the current notary quota cannot meet the needs in GCN whether it is now or future. Thus, it is reasonable to increase 2-3 notary quota for the GCN region.
 
In addition, the GCN region is one of the most digitized regions in the world. Chinese companies, organizations and other entities have enormous data storage needs. The movement of China even introduced the national strategy called “New Infrastructure Building” which focuses on building digital and internet infrastructure to support the future demands. Therefore, adding more notary and datacap allocation in GCN will strength Filecoin Plus and Filecoin because:

Meet huge storage need in GCN will help to implement Filecoin massively in real business and explore enormous business opportunities in the future;  
Build strong relationship with local government and great companies;
Expand local influence and communities will improve the FIL token liquidity and long-term value;
More miners and developers will lead to more hardware & software support and improve the overall performance of the Filecoin ecosystem.
More notaries will lead to a healthy competition in which different notaries will try to improve their services and performances. Afterall, to perfect the Filecoin Plus mechanism and explore more opportunities.

In addition, the first batch of notary nomination is more for testing purposes. Giving more quota and datacap allocation can let more parties join the test and explore more possibilities and help to perfect the mechanism. Meanwhile, it will also help to improve the Slingshot situation. Currently, most miners do not want to receive orders or set the price too high. As most Slingshot projects come from GCN, lots of them cannot afford such expensive prices to continue their project in Slingshot which is bad for the Filecoin ecosystem. More notaries and datacap will decrease the price and enable more projects and developers to join the Slingshot and Filecoin ecosystem. Therefore, the market and other features can be tested further. 

To wrap it up, it is reasonable to allocate regional notary quota based on the miner power distribution. To add 2-3 new notaries and more datacap allocation in the GCN region will not only meet the needs of client, miner and community, but also improve the overall Filecoin ecosystem.

Specification
Adding new notaries in GCN can follow the same evaluation process with the existing one. No new feature is required. Therefore, there is no new specification.
 
Rationale
The rationale of adding more notary quota for GCN is in the aforementioned “motivation section”. Adding new notaries in GCN can follow the same evaluation process with the existing one. No new feature is required.
 
Backwards Compatibility
Adding new notaries in GCN can follow the same evaluation process with the existing one. As there is no new features or technology change introduced, no backwards compatibility test is needed.
 
Test Cases
Adding new notaries in GCN can follow the same evaluation process with the existing one. No new test case is needed
 
Implementation
Adding a new notary in GCN can follow the same evaluation process with the existing one. It starts with submitting application issues on Github within a timeframe. The new applicant will be scored and further discussed in the next notary meeting. After the nominated notaries passed the audit resolution and there is no dispute against them, they will become the Filecoin Plus notaries as same as the existing ones.
 
Security Considerations
The risk of adding 2-3 notaries in GCN is very limited as there is already a standard notary evaluation procedure. Every new notary must follow the same protocol with the existing notaries. In addition, each new notary must establish a certain mechanism to disclose their intention, allocation decision process and execution etc. to all community members. If the new notary has not performed properly, they will be disqualified just as the existing one.
 
References
https://filfox.info/en/ranks/power

## Related Issues

Notary governance.

**Comment by jnthnvctr** [comment]
I think rather than treating this as a standalone issue - I think its worth connecting this with the other issue that asks how to determine how/when we increase DataCap by geography. 

I propose that if we define the criteria by which a region needs more DataCap (whether it be through more Notaries, refreshing DataCap, etc) - then we should be applying those rules equally to all geographies. 

https://github.com/filecoin-project/notary-governance/issues/76

**Comment by dkkapur** [comment]
Based on the above response and that: 
* clients are sometimes being served by notaries outside their regions if necessary
* Notaries in GCN region have been a lot more active in the last couple of months
* we have an upcoming Notary election process

I'm closing this issue for now. @IPFSUnion - let me know if you'd like to reopen to discuss any specific points. Thank you!
