### ISSUE TITLE
Notary Application: LendMi

### ISSUE THREAD

**Issue by Rongze92** [filecoin-project/notary-governance#730]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:LendMi
- Affiliated organization: LendMi team
- On-chain address to be notarized (recommend using a new address):f1frwhzjltdemtxqfsgn753qs2zbkkfc5o6rje4ii
- Country of Operation: United States
- Region of Operation: North America
- Use case(s) to be supported:  Professional Services (Hosting Reseller, Long-term Backups, Data Warehousing),Developer Tools (Package Managers, Automatic Notaries, Web2 to Web3 integrations),Decentralized Applications,User Content (Personal Storage),Public or Open Data (Scientific datasets, research data, government or historic,Media & Entertainment (Videos, photos, NFTs)
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
LendMi has been paying attention to the development of FIL since 2017. We believe that Filecoin is an indispensable part of the next-generation Internet in storage. In 2021, we established our own lending protocol and started Filecoin joint mining activities. We cooperate with many larger Filecoin nodes to help them reduce mining costs and help ordinary users earn mining income.
In April 2021, LendMi launched smart contracts on Heco chain, raised Fil, and issued revenue through smart contracts. There was over 1 million Fil raised in total, with over 110,000 transactions accessed by smart contracts and over 350 people involved. The data is traceable on the chain.
In June 2021, LendMi synchronized to BSC chain and launched smart contracts. More than 300k Fil raised with over 5600 transactions accessed by smart contracts and over 150 people involved in the process. The data is traceable on the chain.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
We hold more than 1100,000+ Fil, please refer to the document for specific assets (https://docs.google.com/spreadsheets/d/1S4ENnRFySfuvdyLTrpMGbDBOBbdzP1mUHZe7EVm4jgw)
```

How did you acquire the FIL cited above?
```
Sources of assets include self-purchase, user pledge, mining rewards, etc.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
LendMi's contribution to miners:
- Worked with over 10 Filecoin nodes and lent FIL to them since in 2021.
- Provided FIL pledges for 151 PiB computing power.

Contributions for FIL holders on Heco and BSC chains:
- Over 500 people use LendMi smart contracts to make deposits and earn income.
- High interest rate on deposits, varying from 10% to 45% APY depending on lock-up time.
- More than 2 million FIL in accumulated deposit flow.
- More than 100k FIL of accumulated earnings distributed to users.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
LendMi team has been working on Filecoin mining since the beginning of 2021, having experimented with Defi innovation on Ethereum chain previously, founded in 2020, Singapore.
LendMi currently has proven experience in Filecoin mining and smart contracts and is researching FVM and Near network.
LendMi team consists of DeFi researchers, smart contract engineers, Web3 front-end engineers, UI, UE, testing, etc., 11 members in total.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://lendmi.finance
Twitter：twitter.com/LendMi_Official.
Facebook：https://www.facebook.com/LendMiOfficial
Medium: LendMi_Official
Telegram：t.me/LendMi_Official
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.jinse.com/news/blockchain/1144872.html
https://medium.com/@LendMi_Official/lendmi-heco-exclusive-gold-mine-day-add-annualized-35-and-40-pledge-pool-a-total-of-10-000-fil-a0912488f2b1
https://twitter.com/FoxWallet/status/1463069812196741123
https://twitter.com/HECO_Chain/status/1438398773143629824
https://twitter.com/crypto_pikachu1/status/1454018402087886850
https://twitter.com/coinspeaker/status/1461357758737838080
Many articles and reports were taken down due to policy reasons.
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter：twitter.com/LendMi_Official, 10800 followers,
Telegram：t.me/LendMi_Official, 625 subscribers
Facebook：https://www.facebook.com/LendMiOfficial
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://medium.com/@LendMi_Official/lendmi-heco-exclusive-gold-mine-day-add-annualized-35-and-40-pledge-pool-a-total-of-10-000-fil-a0912488f2b1
https://twitter.com/FoxWallet/status/1463069812196741123
https://twitter.com/HECO_Chain/status/1438398773143629824
https://twitter.com/crypto_pikachu1/status/1454018402087886850
https://twitter.com/coinspeaker/status/1461357758737838080
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Preliminary assumptions about the distribution ratio are:
10% is allocated to ordinary users,
20% allocated to web3 developers,
50% is allocated to a corporate entity or organization,
20% is allocated to non-profit non-profit organizations,

Whether it is an ordinary user or an enterprise organization, it is necessary to provide application information to start the review process. We will verify the validity and veracity of the information submitted and reject applications with invalid or false information. For legal entities or organizations, applicants who pass the initial screening will enter the due diligence stage; for individual users and web3 developers, they will enter the DataCap review stage.

Different types of customers use different audit strategies. For specific reference documents:
https://docs.google.com/spreadsheets/d/1JhfnMbdkIUb_2nMCb0f7ikAij9z8sHi9_l1QqjKenN8/edit?usp=sharing

Additionally, to ensure that we can monitor the proper use of DataCap shares by clients, applicants will typically only receive 20% of the allotted share in the first stage, 30% in the second stage, and 50% in the third stage. Only when it is determined that the current phase shares are used correctly is it possible to receive the allocation of the next phase shares. Applicants must meet the following requirements: (i) store only approved and compliant data (ii) not transact with a single SP.
Second, we assess applicants' scores at each stage, which will affect their next application.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will employ a cutting-edge third-party authentication solution during this verification process to ensure a formally authorized distribution of DataCap, such as the use of multi-signature to control the distribution process.
All records will be entered on the relevant blockchain in order to be transparent and traceable to the community and demonstrate "verified transactions" between DataCap applicants and us.
At the same time, we formed a 3-person Filecoin working group dedicated to communicating with the community and managing accounts.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1. First of all, only verified customers are eligible to apply. The following criteria need to be met to become a verified customer.
The company
-has been established for more than six months.
-has an existing project website and ready-to-use products.
-has over 100T of storage capacity and a complete available storage solution.
-has proof of ability to ensure data integrity.
-has reasonable use cases and storage plans.

2.For verified customers, we will evaluate their applications and communicate remotely about the applied storage and evaluation criteria.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
First, we will regularly review our clients' usage plans and publish their transactions' details. We will calculate whether the percentage of transactions allocated is reasonable.
We will send a warning if a customer allocates Datacap to a single entity by mistake. We will cease the next allocation for clients who keep violating the rules after a warning. A warning will be issued to the public in the Filecoin community. Further cooperation will no longer be accepted.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Github repo.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
I will make a repo on github to record of all allocation decisions.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
Level4
Our team will spend at least 10 hours per week, including participating in governance calls, GitHub and Slack.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None.
```

**Comment by panges2** [comment]
Hello @Rongze92,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by SuperChaiChai** [comment]
@Kevin-FF-USA @panges2 We have sent the mail.
Subject: Notary: LendMi, Application Number: 730
E-mail: contact@lendmi.finance

Hope you can invite me to join the slack of filecoinproject.
Our Slack:  contact@lendmi.finance

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[730.pdf](https://github.com/filecoin-project/notary-governance/files/10159486/730.pdf)

**Comment by Kevin-FF-USA** [comment]
@Rongze92 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by Rongze92** [comment]
@Kevin-FF-USA @panges2 

Dear Kevin and Panges,

Please note that we have updated the Notary address to: f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da

Thank you.

**Comment by panges2** [comment]
Hi @Rongze92, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by SuperChaiChai** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebvrpjlciw5ke5ij5gd6ln2fkxdycfevlmfvaphilz7dc6zqbtxvm
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvrpjlciw5ke5ij5gd6ln2fkxdycfevlmfvaphilz7dc6zqbtxvm
