### ISSUE TITLE
Notary Application: YugaTech

### ISSUE THREAD

**Issue by EHume** [filecoin-project/notary-governance#731]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:Jimmy
- Affiliated organization: YugaTech
- On-chain address to be notarized (recommend using a new address):f122vzip64krqs5gdwioketfjsftnpq4vtzqgmyay
- Country of Operation: China
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: Web 3.0 / Decentralized Applications
- DataCap requested for allocation (10TiB - 1PiB):500TiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Our Github: Ehume
I used to research crypto and invest in blockchain. After researching, I found that what makes filecoin different from other cryptocurrencies is that filecoin is not just a cryptocurrency, it also has its own substantial use---its storage function brings more value. So I decided to invest some nodes of Filecoin and develope a website for retrieving nodes. f01933849, f01770524, f01610285, f01854758, f01653777, f01674967, f01832632, f01819592
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
We have totally more than 1MM tokens.
f01933849, f01770524, f01610285, f01854758, f01653777, f01674967, f01832632, f01819592
```

How did you acquire the FIL cited above?
```
From company's account and block reward
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We have been dedicated to building and optimizing industry-leading order encapsulation components for three years, enabling rapid processing and encapsulation of real data, and continuously empowering storage providers and data content providers.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
This is why Yuga launched Dashborad Products of FIL PLUS by EHume.com. The abuse of Datacap is becoming more and more serious. We hope to help filter higher quality compliant storage providers through Yuga's advanced tools to help filecoin network run more stably and securely in the future.
![1](https://user-images.githubusercontent.com/107671030/202396189-6019fffe-5b5e-4847-9ea5-c2f04d4e0540.png)
![2](https://user-images.githubusercontent.com/107671030/202396204-b59c529d-79f9-447e-8949-f9cfdaaaa89d.png)
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Yuga was founded in 2019 with core members mainly from Microsoft, AWS and other major leading organizations. Till now we have about 20 employees in Shanghai office. We've been dedicated to building and optimizing industry-leading order encapsulation components for three years, enabling rapid processing and encapsulation of real data, and continuously empowering storage providers and data content providers.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://ehume.com/
Twitter: @Ehume3 
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Website: https://ehume.com
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Douyin: Mr. Fan996 【3914 followers】 Wechat video account: Mr. Fan996
We will upload web3 related videos to introduce the world of web3.
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
Douyin: Mr. Fan996 【3914 followers】
Wechat video account: Mr. Fan996
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We will leverage some existing best practices to consider.
![3](https://user-images.githubusercontent.com/107671030/202395806-1c852c4e-5fd3-4191-80cc-2eacde2904f9.png)

The Rubric will be the primary guideline I use when evaluating a client and determining their DataCap allocation. These scoring guidelines can serve as a tool of assessment and further add a level of consistency across the board.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will purchase a ledger to save and sign the DataCap.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
I will prepare some questions to put on the client's application:

1. What's your name and your position in your company? Please introduce yourself and your team briefly.
2. Please show us some of your social media accounts such as Twitter, Facebook, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation. 
3. Please provide your company's business registration license. 
4. What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?
5. Where is your data stored now? Whether the data is stored on a server or a cloud service provider?
6. How many regions do you plan to store the data in? 
7. How many storage providers you intend to make dealing with?
8. Do you plan to record your allocation decisions and execution details in public? And how to realize it?
9. Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will use our product http://www.ehume.com  to check their record, and we also follow Audit the DC allocation statistics from https://filplus.d.interplanetary.one
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we will use both GitHub and email.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We plan on keeping the record on GitHub, and we will also keep a copy of our own records.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L3
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No, we haven't.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No. 
```

**Comment by EHume** [comment]
@Kevin-FF-USA Hello Kevin, can you please help my application add Round 4 Notary label? Thank you very much!

**Comment by panges2** [comment]
Hello @EHume,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[731.pdf](https://github.com/filecoin-project/notary-governance/files/10159488/731.pdf)

**Comment by EHume** [comment]
I would like to add some details to my notary application:

**a.** In order to promote our product-----Ehume.com and make it influential in filecoin community in the future. We have organized a team to do this. So we want to change our application to become an L4 notary and we want to do more for the community to make filecoin better.

**b.** We are inexperienced in how to allocate datacap, so we will gradually build a good data cap allocation mechanism through continuous summarization, improvement and iteration.
We believe that the main responsibility of a notary is to verify the validity of the client. Therefore, we will focus on the authenticity and impact of our clients. When making allocation decisions, the following factors will be considered:
1. Basic information and reputation of the client organization.
2. Development planning and completion of the project.
3. Distribution size of DataCap
4. Customer's DataCap usage.
5. Safety Precautions
We have presented our distribution principles in this table.
![3](https://user-images.githubusercontent.com/107671030/206670401-95a290ce-d92f-41e8-a853-e527bef65333.png)

I hope @Kevin-FF-USA, @panges2, and @galen-mcandrew can review what I added and be willing to re-examine the scores of my application, thanks!

**Comment by Kevin-FF-USA** [comment]
@EHume 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
