### ISSUE TITLE
Notary Application: Genesis

### ISSUE THREAD

**Issue by Chuangshi1** [filecoin-project/notary-governance#732]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:Anne
- Affiliated organization: Genesis
- On-chain address to be notarized (recommend using a new address):f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
- Country of Operation: China
- Region of Operation:Greater China Region (GCR)
- Use case(s) to be supported: Professional Services, Decentralized Applications, Public or Open Data, Media & Entertainment Developer Tools
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: [Organization]

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
In March 2019, the founders of Genesis and his team noticed the development of IPFS in the field of distributed storage, planned the layout of IPFS&Filecoin, then participated in and held IPFS-related conferences for many times. 
In April 2020, the Genesis team made code contributions to the filecoin project and actively participated in the network test project. （https://github.com/filecoin-project/sector-storage/pull/16）In September 2020, IPFS started a global competition-Slingshot, and the core team of Genesis defeated the crowd and achieved the top five achievements in the world. 
In 2020, The Filecoin main network was successfully launched at 22:45 on the evening of October 15. At the same time, the data storage space of Genesis power reached the top six in the entire network, and the storage efficiency of data storage packaging continued to be higher than the industry average. 
Genesis team focus on the field of distributed storage, with blockchain and filecoin data storage track as the major development business sectors.It currently has more than 80 members, invested about 300 million yuan, and deployed more than 4,000 storage server equipment in four cities across the country. The current daily growth rate is 500TB to 1.5PiB.
About filecoin products developed by Genesis team :
 Firstly, The Genesis Browser is a Filecoin blockchain browser and data service platform. It provides users with various data, information and visible charts related to Filecoin steadily. It can also enable users to understand the entire network information and node data changes more comprehensively and timely, at the same time ,it can monitor node-related risks, avoid losses, ensure node output, and master market conditions and node power anytime, anywhere.
Secondly,"SD Cloud" filecoin storage cloud service platform, which solves the problems of data storage, data security and data transmission. It adopts transmission protocol, git modular technology, SFS self-certified naming technology, and is based on a blockchain integrated architecture design. It can support PiB-level mass storage. It helps enterprises to solve the problems of high cost of data storage, slow transmission, security risks, low availability, and expansion difficulties in one stop. Let data returns to its original source and realize data right confirmation and data distribution. Let the whole people share knowledge, all people search knowledge, and build a data center with high efficiency, strong privacy, and low cost.
Thirdly, Integrated cabinet:We are deeply involved in the field of edge computing and distributed storage. Relying on the self-developed integrated data storage micro-cabinet, we integrate multiple systems such as refrigeration, monitoring, fire protection, and edge computing. Through the monitoring system, we implement overall management of subsystems and realize one-stop data. Deployment and operations management. Enterprises can customize the nodes, resources and service methods used in the entire edge computing network, and build a highly secure global private network suitable for their own business applications..More details view photos：https://docs.google.com/document/d/1uBaPHk_bpJ1wVTQjvkj7YDqbrBtrgQAg_6jRxBFrDgc/edit
Regarding the event, we participated in the Wanxiang Blockchain IPFS Developer Competition and entered the finals. We also participated in Tianchi Aliyun Hackathon, minerX project, Slingshot and other activities. Actively participated in Near ecological construction, submitted relevant proposals and received official recognition and approval,（https://github.com/filecoin-project/devgrants/issues/375） and won awards in the space race. We are currently participating in the Slingshot 2 project and Near Meta build Hackathon competition.
In addition, we actively participated in cooperation and signed contracts with the local Guancheng government. Genesis adopts the distributed storage technology of Zhongchuang Computing Co., Ltd..and Baidu Smart Cloud signed a strategic cooperation agreement, reached a cooperation agreement with the Chinese Academy of Sciences cloud computing, reached a cooperation with the National Big Data Disaster Recovery Center. At the same time, we cooperated with People's Data Management (Beijing) Co., LTD to hold the cooperation signing ceremony of "Computing power Data Center" project. In-depth cooperation will be conducted on big data storage, resource sharing and application, privacy protection, "Internet plus Data product processing" and data computing standardization.We obtained 12 national software patents in the field of blockchain distributed storage, including value-added telecommunications services Business license, intellectual property management system certification, etc. For more information , please visit: [https://photos.app.goo.gl/wZH3XCEqoA3xBi266](https://docs.google.com/document/d/16EhnDQ_TjhlOKUitcMWzxXh046ImouTeO0Zc_-FlqSE/edit)
We are also constantly updating the filecoin industry dynamics on social media platforms. Including Weibo 
https://weibo.com/u/7583724940?is_hot=1&sudaref=s.weibo.com with12000 fans 
TIKTOK（in China）Official Account:https://www.douyin.com/search/%E4%B8%AD%E5%88%9B%E7%AE%97%E5%8A%9B?source=normal_search&aid=02791d7a-cc95-44ae-ada6-6e2b517e38a6&enter_from=recommend  
ID：zhongchuangsl  with8171 fans  
Finally, we have 5 miners running on the filecoin network, and the total amount of fil is 1.27Million
f020330  f025002  f024483  f0101020  f0101021 with 143.22PiB
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f020330  f025002  f024483  f0101020  f0101021 with 143.22PiB 
and the total amount of fil is 1.27Million
```

How did you acquire the FIL cited above?
```
Block rewards & storage provide service&Grants from Hackathon
```
### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As the world's leading provider of decentralized storage solutions, Genesis has been actively participating in and organizing various activities to promote the Filecoin ecosystem and has achieved remarkable results.
1.In October 2021, we participated in the Wanxiang Blockchain IPFS Developer Competition and entered the finals, as well as the Aliyun Tianchi Hackathon. We actively participated in the Near ecological construction, submitted relevant proposals and got official approval , participated in the Slingshot race, and organized exchange meetings with Alibaba Cloud, and some Salon activities are held from time to time.In 2022, we participated in slingshot2 and Near Metabuild Hackathon competition.
2.Actively discuss filecoin issues on Github and participate in the filecoin ecological construction.
https://github.com/filecoin-project/bellperson/issues/175
https://github.com/filecoin-project/devgrants/issues/375
https://github.com/filecoin-project/sector-storage/pull/16
https://github.com/filecoin-project/lotus/issues/5130
https://github.com/filecoin-project/lotus/issues/6669
https://github.com/filecoin-project/lotus/issues/6077
https://github.com/filecoin-project/lotus/issues/3826
3.The Genesis Browser is a filecoin browser , which provides users with  various data, information and visual charts related to Filecoin stably. Please check  http://www.ipfs6.com/
4.SD Cloud is the first cloud service platform based on the IPFS and filecoin storage network, which solves the problem of data transmission. Pls check:  https://morning-fire-9060.on.fleek.co/#/menu/home
5.We build Integrated cabinet. Check pictures here：https://photos.app.goo.gl/wZH3XCEqoA3xBi266
6.We are the the V3 notary for filecoin.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Genesis Browser actively participated in the early network testing and presented some codes bug to the authorities in slack. During the launch of the main network, our f020330 nodes contributed 148888 of the first block of the main network. 
Also actively participate in the discussion on github, the link is as follows:
https://github.com/filecoin-project/bellperson/issues/175
https://github.com/filecoin-project/devgrants/issues/375
https://github.com/filecoin-project/sector-storage/pull/16
https://github.com/filecoin-project/lotus/issues/5130
https://github.com/filecoin-project/lotus/issues/6669
https://github.com/filecoin-project/lotus/issues/6077
https://github.com/filecoin-project/lotus/issues/3826
```
### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Company Nature: Co. Ltd
Country of registration: Henan, China
Organization scale: nearly 80 employees
Date of establishment: January 26, 2021
Organization reputation:
The Genesis team is a leading domestic platform solution provider based on IPFS and blockchain storage. The representative products of our company are the self-developed Genesis browser and SD Cloud storage platform.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Wechat Official Account: https://mp.weixin.qq.com/s/X_soXjNUsU5OkeGNb1uwGg
Weibo: https://weibo.com/u/7583724940?is_hot=1&sudaref=s.weibo.com
SDCloud: https://sdcloud.on.fleek.co/
Genesis Browser: http://www.ipfs6.com/
Tiktok in China https://www.douyin.com/search/%E4%B8%AD%E5%88%9B%E7%AE%97%E5%8A%9B?source=normal_search&aid=02791d7a-cc95-44ae-ada6-6e2b517e38a6&enter_from=recommend
Twitter：https://twitter.com/IPFSZC
https://medium.com/me/stories/public
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
[Please answer here.](https://weibo.com/u/7583724940?is_hot=1&sudaref=s.weibo.com
https://www.zhihu.com/people/ipfszhong-chuang-suan-li/posts
https://blog.csdn.net/weixin_57995426
https://www.shilian.com/shilianhao/448732.html
https://www.douban.com/note/819866424/
https://tieba.baidu.com/f?ie=utf-8&kw=%E4%B8%AD%E5%88%9B%E7%AE%97%E5%8A%9B&fr=search
https://xueqiu.com/u/3878285823
https://www.sohu.com/a/500896771_121114728
https://beepcrypto.com/home?userId=20168
https://www.odaily.com/
https://beepcrypto.com/home?userId=20168
https://v.douyin.com/RQgBJqW/)
https://medium.com/me/stories/public
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
(https://weibo.com/u/7583724940?is_hot=1&sudaref=s.weibo.com with12000 fans 
TIKTOK（in China）Official Account:https://www.douyin.com/search/%E4%B8%AD%E5%88%9B%E7%AE%97%E5%8A%9B?source=normal_search&aid=02791d7a-cc95-44ae-ada6-6e2b517e38a6&enter_from=recommend  
ID：CS_Genesi  with 6100 fans  
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
Regarding the event, we participated in the Wanxiang Blockchain IPFS Developer Competition and entered the finals. We also participated in Tianchi Aliyun Hackathon, minerX project, Slingshot and other activities. Actively participated in Near ecological construction, submitted relevant proposals and received official recognition and approval,（https://github.com/filecoin-project/devgrants/issues/375） and won awards in the space race. We are currently participating in the Slingshot 2 project and Near Meta build Hackathon competition.
```
# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
In order to prevent customers from malicious use or abuse of DataCap, we will carefully review customers, examining their needs, and allocate them on demand. So I first specify some rules to figure out the true identity of the applicant.Browse its official website to get a general understanding of the company or individual.
* Browse its official website to get a general understanding of the company or individual. If necessary, go to the company for on-site inspections and review whether the data is valid.
* Check the company's registration information on relevant government websites to ensure that the information submitted is true.
* Ask some questions to understand the applicant's position/organization/plan/use case, etc.
* Then we will classify the applicants according to their industry reputation and scale.
https://docs.google.com/spreadsheets/d/1ZZVv7ubFyXG8jdx6lXQi48yJ2U1MdjVzpMFwhIF9rXE/edit?usp=sharing
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The hardware wallet will be used to securely store the key associated with the address assigned by DataCap.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In order to ensure the fairness and justice of DataCap distribution, we have formulated separate online and offline application procedures based on the number of DataCap applications and individual and corporate users.
For individual users:
We will review their Github registration years (180 days at least) to prevent malicious application bots. The amount of approval will also be controlled below 0.5 TiB.
For business users:
We have developed different review methods and requirements based on the number of their DataCap applications.
If it is less than or equal to 5TiB, we will use online review. The following points will be reviewed.
• Business license
• Enterprise authorization letter (CEO's signature + seal)
• All shareholders who account for more than 25% of the total number of shareholders must provide ID cards or passport photos.
• Sample data submission (accounting for 0.2% of its total DataCap requests)
If the application is larger than 5TiB, we will add offline comments based on online surveys (visit customers on business trips or invite them to our company).
Enterprise business type
• data source
• Data volume (monthly)
• What companies think about Filecoin
• Data storage plan
Question:
Please introduce yourself and your personal information on social media (official website, WeChat, LinkedIn,, GitHub).
• What is the purpose of your application for DataCap?
• Please provide the wallet address you want to apply for DataCap
• Please provide the quota of Datacap you want to apply for.
• Please provide the name of the organization, nationality, country of registration, time of registration, name of the executive, and relevant website (if you are an institutional user).
• Please provide the region where you want to use DataCap, if it is more than one region, please pay attention.
• How many miners do you plan to distribute DataCap to, if there are specially designated miners, please pay attention.
• Have you assigned DataCap before? If so, please provide details.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Applicants need to distribute Datacap to at least 3 or more miners, which will increase storage redundancy and help maintain decentralization and reduce the possibility of abuse. The more miner clients allocate, the more Datacap clients may get.
We will regularly monitor and record the usage of all distributed Datacaps every month.
For applicants who abnormal usage, we will contact them to understand the situation and record it.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, all allocation decisions will follow the guidelines published on Github. The same is true for all communications.
Since all interactions are intended to be done publicly, most allocation decisions should be self-explanatory.
Any challenges related to allocation decisions should first be discussed publicly in the Github repository.
If the notary public can’t provide a convincing reason, it can submit a dispute resolution application to the Notary Public Administration 14 business days from the date of the initial challenge. After submitting the dispute resolution application, the notary public can appoint an arbitrator among the root key holders to resolve the dispute. According to the decision of the arbitrator, a hearing may be held within 30 business days after the dispute resolution application is made. 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
All allocation decisions will be made publicly on GitHub-all communication will also be made through the repository and issue tracking, and we will send two email notifications to customers to ensure effectiveness
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
- Maintain a ranking in Leaderboard in the top 10% of Notaries.
- Attend 2 Governance calls a month.
- Join 2 working groups
- Respond to SLACK inquiries within 2 days
- Vote/Comment on >2 proposals a month
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
(https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1009
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/720
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1374)
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/260
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No
```

**Comment by panges2** [comment]
Hello @Chuangshi1,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by 1ane-1** [comment]
> Hello @Chuangshi1, Thanks for applying to become a Notary in the Fil+ program!
> 
> As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account. *This cannot be from your personal account. You Must include the address of your Organization.
> 
> Subject Line: Notary Name, Application Number Email Body:
> 
> 1. Your First and Last name
> 2. Your Organization
> 3. Your Country of Operation
> 4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
> 5. Link to your GitHub application
> 
> This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.
> 
> Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2
> 
> Thank you!

The email had been sent to you,pls check it.

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by Chuangshi1** [comment]
> Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

We will cooperate with the investigation and provide relevant information at any time. Have a nice day~

**Comment by Chuangshi1** [comment]
Hello, in order to support the audit, i want to make a explaination:

- Here is the V3 notary link,https://github.com/filecoin-project/notary-governance/issues/411

V4 we changed another Github address with a new account.

- About official email; The Genesis filecoin browser address is https://www.ipfs6.com/, here is our email

![image](https://user-images.githubusercontent.com/112937825/205418352-86072e64-1a40-406f-9b6c-5481e41b0594.png)

- About active notary, we  take part in some channel in slack and try to give answers
![image](https://user-images.githubusercontent.com/112937825/205418617-bb605f7a-4227-4363-826f-6d6191193ca2.png)
![image](https://user-images.githubusercontent.com/112937825/205418644-ccd555f1-48e8-41ef-9b09-2bc4995debbb.png)

- We join every notary meeting as Anne, and voted for fips. You can check the sign-in sheet. Besides，we actively join the filecoin hackathon to develop the ecosystem.
- About signing, we did the due diligence before signing, but with few signs because these days something wrong with our ledger, 
![image](https://user-images.githubusercontent.com/112937825/205419117-53ca6502-8865-4e63-8ad6-2bf511e414bf.png)
![image](https://user-images.githubusercontent.com/112937825/205419166-14074d1b-7fdc-41ab-897b-4245a2c8e363.png)
![image](https://user-images.githubusercontent.com/112937825/205419230-530fcaeb-aa0a-4b0d-afd2-aede1b5b303a.png)
Finally, yesterday we dealed with it. The ledger works again.And we will obey notary rules and do our best to bulid a better filecoin community.

**Comment by Chuangshi1** [comment]
![image](https://user-images.githubusercontent.com/112937825/205431485-37e66213-56ad-41e8-aad3-375d854d9d33.png)

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[732.pdf](https://github.com/filecoin-project/notary-governance/files/10159489/732.pdf)

**Comment by Chuangshi1** [comment]
In order to imporve our scores, we update some information here, hope it can help us.
In-protocol Reputation: 
Participate in the first phase of the testnet that started in December 2019,  and the final storage capacity exceeds 1PiB,Participated in Trusted Setup Ceremony Phase 2 https://filecoin.io/blog/trusted-setup-complete/ Join the Filecoin Hackathons in China with the project named Genesis NFT, and Near Metabulid hackathon with SDcloud storage,Singshot repair project, Filecoin NFT hackathon,wanxiang bolckchain hackathon,https://www.bilibili.com/video/BV1CW4y1k7uv/?share_medium=iphone&share_plat=ios&share_source=WEIXIN&share_tag=s_i&timestamp=1655466284&unique_k=silN2vT
Share some bugs in Slack 
Individual Reputation:
We join the wanxiang blockchain hackathon with Genesis cloud storage. Time starts from 1:29:00 https://www.bilibili.com/video/BV1CW4y1k7uv/?share_medium=iphone&share_plat=ios&share_source=WEIXIN&share_tag=s_i&timestamp=1655466284&unique_k=silN2vT
Genesis NFT https://www.youtube.com/watch?v=YN-wAMexs3U&t=13s
Filecoin Genesis browser introduction:https://www.youtube.com/channel/UCyJkdpgvKvcAU_z8xpf6s3Q
30+ articles about filecoin: https://medium.com/me/stories/public

**Comment by Chuangshi1** [comment]
<img width="290" alt="image" src="https://user-images.githubusercontent.com/112937825/205854759-a4c4b83a-0d89-472f-8aef-434dd1a8d961.png">
<img width="365" alt="image" src="https://user-images.githubusercontent.com/112937825/205854785-de447ce0-7407-4623-b50b-badac4860d9c.png">

**Comment by 1ane-1** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecj4knrurhxpqk5r62omfmublbrwrbzyuiounnlplp3mzzjocnbly
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecj4knrurhxpqk5r62omfmublbrwrbzyuiounnlplp3mzzjocnbly

**Comment by Chuangshi1** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebl2r62kta2u6syz7dty3shzhtsezl4jcpvdxfxs77edlltuytfek
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebl2r62kta2u6syz7dty3shzhtsezl4jcpvdxfxs77edlltuytfek

**Comment by 1ane-1** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecvjhn3ot2oxxlvbkwyp6i5sfvzjeixezef4dmo4zgswql5gdk5ni
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvjhn3ot2oxxlvbkwyp6i5sfvzjeixezef4dmo4zgswql5gdk5ni
