### ISSUE TITLE
Notary Application: Maple - Techpie

### ISSUE THREAD

**Issue by Techpie-Maple** [filecoin-project/notary-governance#733]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information 
- Name:TechPie
- Affiliated organization: TechPie
- On-chain address to be notarized (recommend using a new address): f1rdcogwltcj6663ytyconrs5av57nnc5hkvtpfva
- Country of Operation: People's Republic of China
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: Professional Services, Developer Tools, Decentralized Applications, User Content, Public or Open Data
- DataCap requested for allocation (10TiB - 1PiB):500TiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Engaged in Filecoin ecosystem since the mainnet as
1. Storage providers
2. FIL Investor
More information:
● Miner ID: f0152337 f01262966 f01933849 f0161542
● Slack: Techpie-Maple
● GitHub account:Techpie-Maple
● https://techpie.org 
● Twitter:@TechPieinfo
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
● Total 50000+ FIL f0152337 f01262966 f01933849 f0161542
```

How did you acquire the FIL cited above?
```
We bought it from Binance and block rewards from Filecoin network.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As a traditional IT company, we believe that the charm of blockchain is not only in its financial attributes, but the Filecoin network makes it possible to store data at very low cost. 

This is also an important reason for our company to transform into WEB3. We invested FIL on 4 nodes. 
Feb 2021 f0152337 & f0161542  and Sep. 2021 f01262966  all are storage space provider 
Oct. 2022 f01933849  storage provide help people or enterprise keep their data
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
We are a Chinese IT outsourcing company for Canadian clients; focusing on optimizing AI translation engines and information aggregation algorithms for AI, Health, Fintech, Enterprise, etc.

We have built strong internal databases and research insights in various industries to provide data support for researching and comparing technology supply and demand companies; as well as creating target company tracking lists and getting automatic email alerts, among other services.

WEB3 quantitative trading tools, data mining and analysis, personalized and precise matching; bilingual platform, two-way communication, processing a large amount of unstructured data; providing companies with data on technology, investment and financing requirements. (BTC, ETH, BSC, etc.) 
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
GitHub account:Techpie-Maple
https://techpie.org 
https://canadapie.com/
Twitter:@TechPieinfo
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
GitHub account:Techpie-Maple
https://techpie.org 
https://canadapie.com/
Twitter:@TechPieinfo
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
GitHub account Techpie-Maple
https://techpie.org 
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://techpie.org 
```
# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
To prevent customers from maliciously using or abusing DataCap, we carefully vet customers, examine their needs, and assign them as needed. Therefore, I first developed some rules to find out the true identity of the applicant. 

We plan on allocating the DataCap based on the community governance principles of Trust, Transparency, and Accountability. 

We will support use cases that validate and encourage decentralisation and diversity, building towards a useful storage network. 

To successfully implement the target amount of DataCap, we’ll look into the following:
- Client’s website, social media, and/or any external media information;
- Client’s legal and business entity information (if available publicly);
- The relationships between the data sample, use cases, and client industries to make sure that the applicant(s) are rightful owners of the data.

For more effective verification, we will preferentially accept applications from customers in Greater China or customers outside Greater China who choose Chinese SP.
In order to better improve the review quality, we also made the customer feedback form:
https://docs.qq.com/form/page/DUnZCc09NQmFaRnFO
```
How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Hardware wallet and GitHub account will be handled by two employee.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We divide the individual client and enterprise client

We have developed separate online and offline application processes. If the application is larger than 50TiB, we will add an video call to review based on the online survey method (traveling to visit client in China or inviting customers to Techpie, Shanghai, China).

In addition, we may ask further questions to give the applicant an accurate score.
In order to get more clients involved in the Filecoin network, we're not going to ask too many complicated questions, but focus on questions about the validity of clients.
 
Question List:
● Please provide the name of the organization, business scale, social media accounts and followers, business license (can be sent by email); If you are an individual, please provide your name, date of birth, employer and size, employment permit, social media accounts and followers, ID card (which can be sent by email);
● When did you first learn about Filecoin? Please describe the projects you have participated in. What do you want from Filecoin? Any suggestions or expectations for the Filecoin network?
● Are there legal risks? What percentage of your questions are?
● Please describe your organization, such as founding, number of employees, number of users, number of social media followers.
● What about your data volume, sources and future planning? Please describe the type, format, origin, storage capacity, publicity of the data that will be stored in Filecoin (and if the data can be made public, how can others retrieve it?)
● What region do you plan to store your data in? How many miners are you looking for? Please list the SP ID. What is the storage ratio of each miner? What are the requirements for miners? Finally, please describe your layoff plans.
● Do you agree to disclose transaction information? If you have acquired a DataCap, please make the transaction information public in a timely manner.

Enterprise client and application purposes are one of the important criteria we review.
● Research company entity information
● Investigate the company
● Sign a cooperation agreement

Question List:
● What type of data do you want to store and for what purpose?
● What are your plans for the number of SPs where data is stored, the zones, and the number of miners allocated per SP?
● What security measures do you have?
● Do you comply with local laws and regulations and accept SP's Terms of Service?
● We will spot check and retrieval their data from the SP .
● We may add additional questions and requests based on responses and client due diligence. 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
A Ledger will be used for datacap allocation and the GitHub account will be keep under a supervisor.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, Both GitHub and email.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub Repo.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
We'd like choose L3
```
### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No.
```

**Comment by panges2** [comment]
Hello @Techpie-Maple,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Techpie-Maple** [comment]
Hello @panges2 @Kevin-FF-USA,
I would like to further clarify my answer to this question---'_What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity._'

We will use the address in which clients are requesting DataCap and check all of the deals that a client is sending out to other SPs. Also, we will use the https://filplus.d.interplanetary.one/ to check that the total amount of DataCap is even distributed amongst the SP nodes participating in storing the dataset.
We'll retrieve the data to make sure the data that is receiving datacap is consistent with the dataset description states in the LDN to maintain honest datacap use.

If possible, we would like to apply for L4 notary. We are willing to devote more time to the work of the filecoin community in the future. We'd like to help community ensure clients are operating in good faith and in accordance with the program guidelines and their own stated goals. 

Hope my notary application can be approved by community, thank you!

**Comment by Kevin-FF-USA** [comment]
@Techpie-Maple 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
