### ISSUE TITLE
Notary Application:  IPFS.CN

### ISSUE THREAD

**Issue by ipfscn** [filecoin-project/notary-governance#734]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Nic
- Affiliated organization: IPFS.CN
- On-chain address to be notarized (recommend using a new address): f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
- Country of Operation:  Greater China
- Region of Operation：Greater China Region (GCR)
- Use case(s) to be supported:  Professional Services 、Developer Tools 、Decentralized Applications、User Content 、Public or Open Data、Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?: Organization--IPFS.CN

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
IPFS.CN (IPFS China Community), officially established in October 2017, is the most influential and well-known IPFS Chinese community media in the world, with a community of over 100,000 people, and is one of the first groups of communities dedicated to IPFS evangelism in China.

In December 2021,  Response to the trend and national call, IPFS.CN officially changed its name to IPFS Metaverse Community.We will deeply analyze the core values of IPFS & Filecoin, Web3.0, Metaverse and other related fields, and build a complete ecology from IPFS to Metaverse.

IPFS Metaverse Community is committed to building a global IPFS ecological community, providing IPFS and Filecoin industry information, trend insights, in-depth reports, project incubation, mining pool development and other services for IPFS enthusiasts. In May 2021, IPFS Metaverse Community (formerly IPFS.CN) As a community partner of the Filecoin Grant online hackathon, assisted the developer platform Dorahacks with an online hackathon that lasted nearly two and a half months.

In addition, on May 31, 2021, IPFS Metaverse Community (formerly IPFS.CN) & Rhythm BlockBeats jointly launched the first podcast in the field of distributed storage - IPFS Enthusiasts Speak. It is the first podcast in the field of distributed storage in China.

In July 2021, 『IPFS.CN AMA』 was officially launched, dedicated to the content around IPFS & Filecoin ecology, and regularly invites value projects in the blockchain field to discuss the industry focus and future pattern together. After the launch of this column, many famous partners including ：Seedao, celer, polygon, Near, Dapper, Chainlink, DoraHacks, FILSWAN...


The IPFS Metaverse Community is also one of the builders of Filecoin, and we have led a number of developers in the community, giving them technical support assistance. One of these developers has participated in many Filecoin hackathon competitions and has achieved excellent results.

Links：
-https://mp.weixin.qq.com/s/dvG2cgwAKSbWk9A6zFaZdw
-https://twitter.com/Filecoin/status/1394015047886725121
-https://www.theblockbeats.info/radioinfo/66
-https://mp.weixin.qq.com/s/AltvVwI4dPUvV6DvqimHTg
-https://mp.weixin.qq.com/s/rMkbHn-IeMSxWdw9xa8n3Q
-https://mp.weixin.qq.com/s/c1NRp0j9NrTYi3PJTXyR6g
-https://mp.weixin.qq.com/s/UXACwDREC9j7bmmSspGNJw
-https://twitter.com/cn_ipfs/status/1448596977709555719

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
As a neutral media organization, IPFS Metaverse Community is not directly or indirectly involved in mining, so we do not hold tokens. However, we plan to launch a developer hackathon for soliciting Filecoin in May this year. After that we apply for a wallet and get tokens.

Total：365,595.4 FIL
Currently Available：34,617.8720 FIL 
Initial Pledge: 296,890.008 FIL 
Locked Rewards: 34,087.5327 FIL
ID: f0441372、f087999、f01617056
Website: FILFOX: https://filfox.info/en 
 
```

How did you acquire the FIL cited above?
```
 invest myself
customer investment
Participate in the filecoin hackathon and other rewards
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
1.We started the IPFS Metaverse Community (formerly IPFS.CN) to research and evangelize about IPFS & Filecoin, and on the first anniversary of the IPFS mainnet, we launched the "Filecoin First Anniversary Poster" which documents Filecoin has made great progress since the launch of the mainnet.

Links：
-https://twitter.com/cn_ipfs/status/1448892719921647618
-https://twitter.com/cn_ipfs/status/1448892689156493316

2.On December 8, 2019, the "China Distributed Storage Industry Alliance" was officially launched by IPFS Metaverse Community, together with LINGDAI Community, FANDER Community and CCTF.

3.June 22, 2020, IPFS Metaverse Community (formerly IPFS.CN) received the "Most Cohesive Community Award.

4. ICAA Global NFT Festival South America's first NFT exhibition partner.

Link：https://twitter.com/theTingDAO/status/1457556403917369344


```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
IPFS Metaverse Community (formerly IPFS.CN) was officially established in October 2017, and is the most influential and well-known IPFS Chinese community media in the world, with a community of over 100,000 people, and is one of the first communities in China dedicated to IPFS evangelism.

-Foundation：IPFS Ecological Fund
-Distributed Storage Service Providers：STCloud
-Media Cooperation：BlockBetas
-Project Partners：Seedao、celer、polygon、Near、Dapper、Chainlink、DoraHacks、FILSWAN.
-Registration Country: China
-Organization size: 100
-Time since establishment: 2017

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
-Twitter：@cn_ipfs
-Telegram：https://t.me/ipfscn2018
-Medium：[@cn_ipfs ](https://medium.com/@cn_ipfs)
-Discord：https://discord.gg/Sr9BE3V5
-jinse：https://m.jinse.com/homepage/419853
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://m.jinse.com/homepage/419853
https://twitter.com/theTingDAO/status/1457556403917369344
https://mp.weixin.qq.com/s/hp1-a4a5AHP6Wo0gJwZMhA
https://mp.weixin.qq.com/s/CNFImDj0JkN1Zl87fwNENQ
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter: https://twitter.com/buboo_m
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
 
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
In order to better serve community participants, IPFS Metaverse Community will not impose strict restrictions on use cases, but as a technology research institution, we prefer to support developer tools, Web 3.0, Web3 DApp, Web 2.0 applications and other technology-related applications.

We will focus on the authenticity, influence, allocation decisions, etc. of our customers.
In addition, we will conduct offline surveys to find out who they really are, what they do, their reputation, etc., and how they use Filecoin for storage. We even plan to conduct a full review and assessment of our clients' reputation every three months and reserve the right to adjust client quotas to ensure that shares are allocated to the fullest extent possible.

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will use a wallet with multiple signatures launched by our partner FIL WALLET to distribute to more customers and use a wallet that supports file coins to verify accounts associated with Datacap distributions.

The private keys will be stored in the hard wallet and will be accessible only by the principal.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
First, we will collect relevant information about customers.

1.Entity Information
- Formation documents , this includes certificates of registration/incorporation/information; 
- government-issued identification number for the entity；

2. Authorized Signatory Information
- evidence of the authorized signatory’s authority to act on behalf of the application entity ；
- Sign and press fingerprints (official seal and corporate seal are required)；
- ID card and a photo of the individual and ID card to prove it is the person;

3.Company operation direction and turnover
- Company goals, company's main business；
- Annual turnover in the last two years；

Question List:
1.Please provide information about the project, including the name of the organization, scale of operation, social media accounts & follwers, business license (can be sent by email); if you are an individual, please provide your name, date of birth, workplace and scale, proof of employment, social media accounts & follwers, ID card (can be sent by email).

2.When did you first learn about Filecoin? Please tell us about the projects you have participated in ? What do you want to get from Filecoin? What are your suggestions or expectations for the Filecoin network?

3.What is your data volume, source and post planning? Please describe the type, format, source, storage capacity, and public nature of the data that will be stored in Filecoin (if the data is publicly available, how will others retrieve it?

4.For application developers, will you act as a client on behalf of the user or will you apply for a notary on behalf of the user? If so, how much DataCap approval do you expect each user to receive?

After verifying this provided information, an interview and data source checking process is required. After that, an agreement should be signed for the next step: progressive assignment of DataCap, allowing the client to collect more credits

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Check and inspections regualrly (weekly or bi-weekly;We will use the filfox and filplus websites to check the allocation ratio of customers to SP.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we will record the review request in detail, the record will be published on github, and there will be a 10 working day publicity period for DataCap customer assignments for the community to check.

Of course, we may communicate with customers on slack, tg or email, and we will also keep the communication records on these channels. 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub will be the place to implement all requests, changes and fixes related to distribution. All records should be synchronized on GitHub, so that everyone in the community can clearly see the customer's situation, and track and supervise in a timely manner. Therefore, we will All records are kept on github.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L3
We will regularly participate in meetings, follow up news on slack in a timely manner, pay attention to FIP on github, and actively handle customer DC requests. Participate more than 15 hours per week

```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes
https://github.com/filecoin-project/notary-governance/issues/434

```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None
```

**Comment by ipfscn** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedxfsbmuzrb3iwjduzsggpu2uisw7otjk5unl3wo32wqp45gudzhs
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxfsbmuzrb3iwjduzsggpu2uisw7otjk5unl3wo32wqp45gudzhs

**Comment by ipfscn** [comment]
@panges2 we have send the email，thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[734.pdf](https://github.com/filecoin-project/notary-governance/files/10159493/734.pdf)

**Comment by Kevin-FF-USA** [comment]
@ipfscn 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by ipfscn** [comment]
Thanks, I filled out the form,

**Comment by Kevin-FF-USA** [comment]
Hi @ipfscn,

Doing a review of all the applications Disclosure forms, in your disclosure form only a FIRST name was provided for the HUMAN who has physical control of the ledger.  Can you please send the fill FIRST/LAST name of the person living who has control to our private SLACK DM.

**Comment by Kevin-FF-USA** [comment]
Hi @ipfscn 
Sending a final check in on the name question for your application.  In the disclosure form you submitted, the name was entered as only = NIC.  Need a full human FIRST and LAST for the completion of the sanctions checks. Without this, we not be able to move forward with your Notary onboarding.
