### ISSUE TITLE
Notary Application: TAKI Chain

### ISSUE THREAD

**Issue by TakiChain** [filecoin-project/notary-governance#736]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Smart Dong
- Affiliated organization: TAKI Chain
- On-chain address to be notarized (recommend using a new address):f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
- Country of Operation: GCR
- Region of Operation: [Greater China Region (GCR)]
- Use case(s) to be supported: [Professional Services, Developer Tools, Decentralized Applications, Public or Open Data]
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: [Organization]

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```

I am Smart Dong, Co-founder of TAKI Chain of Shanghai, as a Web 3.0 enthusiast and advocate of decentralized storage, I have been focusing on IPFS/Filecoin research and development since 2020.

Since November 2020, Filecoin Plus launched its Beta version, I have been following this program and doing some research on this project.
I like this project very much, and I also let our employees know and learn about the filecoin project. I have had my own SP node since 2021. At the same time, we also tried to apply the company's own data to the community for datacap to help further understand the filplus project.

More info about myself:
- GitHub: @TakiChain
- Slack: @TakiChain
- Involved in: FIL+/SP/Retrieval Market
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f021479 ,f023530 ,f0508328, f01843749
The amount of FIL has exceeded 1MM.
```

How did you acquire the FIL cited above?
```
Act as Storage Provider
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As the Co-founder of our company, I have repeatedly appealed to employees to embrace web3 and accept the idea of innovative ideas. Filecoin is one of my favorite projects. At least 10 employees around me have started to contact and participate in the filecoin project.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Shanghai Jilian Technology Development Group Co., Ltd. (hereinafter referred to as "Taki Chain") was founded in Shanghai, China, in October 2014. The two carriages of technology and consumption work together. At present, there are more than 500 employees on the job. It has many brands such as Jilian Intelligence, Jilian AI Scientific Research Cloud, TAKIPLAY Script Art, TAKILUCKY Lucky Collection, TAKITOYS Original Fashion Play, TAKIMART IP Business, Weilian Brand E-commerce Service, etc.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
www.videojj.com
https://baijiahao.baidu.com/s?id=1739061137799990097&wfr=spider&for=pc
https://www.chinaz.com/tags/jiliankeji.shtml
https://blog.csdn.net/qq_36654626/article/details/116129762
http://capital.people.com.cn/n1/2020/0105/c405954-31535002.html
https://www.chinaz.com/news/mt/2019/0515/1016456.shtml
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://baijiahao.baidu.com/s?id=1739061137799990097&wfr=spider&for=pc
https://www.chinaz.com/tags/jiliankeji.shtml
https://blog.csdn.net/qq_36654626/article/details/116129762
http://capital.people.com.cn/n1/2020/0105/c405954-31535002.html
https://www.chinaz.com/news/mt/2019/0515/1016456.shtml
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
WeChat Official Account: Jilian Group        Followers: 26000+;
WeChat Official Account: Jilian AI Cloud     Followers: 8000+;
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://www.bilibili.com/video/av845041006/
https://baijiahao.baidu.com/s?id=1726086730671833953&wfr=spider&for=pc
https://baijiahao.baidu.com/s?id=1708913112619649670&wfr=spider&for=pc
https://baijiahao.baidu.com/s?id=1648808206168273468&wfr=spider&for=pc
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We supports all types of industries and entities, especially start-ups willing to use Filecoin to store real and useful data created from their business. 
For detailed info about allocation strategy, please check 
![6](https://user-images.githubusercontent.com/116626712/201945019-328e40ae-5fdf-461b-86d3-9776e881c47d.png)
![8](https://user-images.githubusercontent.com/116626712/201945505-d729bfb2-9b36-4b7c-907a-9aaa214c3e72.png)


For due diligence, it is necessary to collect basic information from applicants, including:
- Detailed information about their teams/companies/entities
- In-protocol or social reputation
- Data/use-case details
- DataCap allocation plan
- History of previous DataCap allocation

With the required info, we could know better about applicants and their businesses, verify their qualifications and authenticity, review data samples, and decide to allocate certain DataCap according to our allocation strategy rating form.

Clients with great credit and reputation in Filecoin Plus could gradually increase their limitations for their one-kick DataCap allocation application.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
An offline wallet will be used for DataCap allocation only.
And multi-sig wallet will be used when more team members join the Notary work.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
All clients have to go through a strict process to be qualified in the early stage.

Questions about the Client's qualifications:
1. Entity Information
 - Formation documents: includes certificates of registration/incorporation/information
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory's authority to act on behalf of the application entity (evidence include written consent of the company board of directors, a secretary's certificate, a signed letter from the applicant's CFO, or may be included in the company operating agreement); 
 - close-up photo of the signatory's face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners
If there are any 25%+ shareholders, we need a document, including a capitalization table, operating agreement, or similar, to verify the ownership, and also the following information for each of them: 
	 - legal name;
	 - date of birth; 
	 - address; 
	 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 	- a copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence, which bears a photograph of the individual. 


Question about the DataCap allocation plan:

1. Introduction of yourself/ your organization(with links)
2. Use case
3. Location
4. Max DataCap Allocation
5. Filecoin address
6. SPs you intend to allocate DataCap with allocation proportion
7. Specific requirements of SPs and storage service
8. For-profit or not
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Audit of DataCap usage
- using filplus.info to check the usage of DataCap and the flow of verified deals to ensure these DataCaps were not improperly used.

Retrieval usability test
- randomly do retrieval usability tests and detect whether its content is consistent with its DataCap application.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All my allocation decisions will be accessible and in public(e.g. Github)
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Yes.
All allocation decisions and records will be public on GitHub, and support to be checked on PL's dashboard.
Any challenges and discussions about my allocation decisions must also be raised, discussed, and solved publicly.
The response time should be limited to a maximum of 7 work days.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
- Maintain a ranking in Leaderboard in the top 10% of Notaries.
- Attend 2 Governance calls a month.
- Join 2 working groups
- Respond to SLACK inquiries within 2 days
- Vote/Comment on >2 proposals a month
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No. thanks!
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No, thanks!
```

**Comment by panges2** [comment]
Hello @TakiChain,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by TakiChain** [comment]
Our official email domain name is **@videopls.com**, you can see and verify it on our official website **www.videojj.com**.  Thank you!
![Mailbox](https://user-images.githubusercontent.com/116626712/205206407-dbfb389f-d698-4ba3-8ac0-9332416afdf8.png)

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[736.pdf](https://github.com/filecoin-project/notary-governance/files/10159494/736.pdf)

**Comment by panges2** [comment]
Hi @TakiChain, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by TakiChain** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedmoqfc2bvtkxwfosqcq7bkqr5vjfmcj7olktap4taydxs3abjd7y
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmoqfc2bvtkxwfosqcq7bkqr5vjfmcj7olktap4taydxs3abjd7y

**Comment by TakiChain** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec6nzt7d7wcb22isk2ww5zfsj4vksdjfjmuxys3xyb6obdzuoq7s4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6nzt7d7wcb22isk2ww5zfsj4vksdjfjmuxys3xyb6obdzuoq7s4

**Comment by TakiChain** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebpdjxzhfevx3g3komminl3jayccuhl2bj36iwfjmydc3eajmzmwm
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpdjxzhfevx3g3komminl3jayccuhl2bj36iwfjmydc3eajmzmwm
