### ISSUE TITLE
Notary Application: 58pic

### ISSUE THREAD

**Issue by HarveryL** [filecoin-project/notary-governance#737]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: 58pic
- Affiliated organization: https://www.58pic.com/
- On-chain address to be notarized (recommend using a new address): f1qlhthcgv5riw4gwyppogte5e7ktmj3fb2v47hsy
- Country of Operation:  Greater China
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: User Content 、Public or Open Data、Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB): 4.5PiB
- Are you applying on behalf of yourself or an organization?: myself

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
We have a large number of images to store, and these images may need to be accessed frequently; Therefore, these pictures cannot be stored in cold storage, so we need a highly available, high-speed, low-cost storage scheme; We want to be able to use Fil for storage.

Our miner ID is: f01319164, the hashrate is 1.01 PiB
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Sorry, It is will not to disclose at this time depending on the customer's requirements.
```

How did you acquire the FIL cited above?
```
Mainly by mining, a little of this is buy from Binance.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We knew about Filecoin in 2021, and started learning Filecoin at same time. 
We mainly try to use fil in the company. We haven't published too many comments in the community. Sorry
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
We focus on the use of Fil. We still hope to support our business with Fil. 
Sorry that we haven't made more contributions to the fil community.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
58pic founded in 2013 and affiliated to Shanghai Pintu Network Technology Co., Ltd., is an excellent "design&office" creative service platform in China. Adhering to the development mission of "being an affordable creative copyright service", after eight years of development, the total number of users has exceeded 85 million, including print Ads, video sound effects, background elements, illustration and painting, e-commerce design, office documents, fonts, new media pictures, etc.
As an excellent "design office" creative service platform in China, 58pic adhering to the development mission of "being an affordable creative copyright service", has accumulated a large number of users after eight years of development.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
website: https://www.58pic.com/
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
WeChat official account: 千图网
weibo: https://weibo.com/58pic
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
WeChat official account: 千图网: 500 thousand
weibo: https://weibo.com/58pic：follower: 83 thousand
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://weibo.com/ttarticle/p/show?id=2309404833533876371576
https://i.ifeng.com/c/86hOiY54CZj
https://news.sina.com.cn/o/2018-09-18/doc-ifxeuwwr5429594.shtml
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
As one of the largest photo communities in China, in order to better serve community participants, Qiantu hopes to provide a more free creative environment, provide more resources, better tools, and a more free environment for the community, and hope that the community can use Web 3.0, Web3 DApp, Web 2.0 applications, and other technology related applications to promote Qiantu to become the first photo community in China.
We pay attention to the readability, appreciation, uniqueness and other dimensions of all works to evaluate our community externally.
In addition, we will conduct an offline survey to understand their real identity, work, reputation, etc., and how they use Filecoin for storage. We even plan to conduct a comprehensive review and evaluation of the customer's reputation every three months, and reserve the right to adjust the customer quota to ensure that the shares are allocated as fully as possible.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will use a wallet with multiple signatures launched  to distribute to more customers and use a wallet that supports file coins to verify accounts associated with Datacap distributions.

The private keys will be stored in the hard wallet and will be accessible only by the principal.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will collect relevant information about customers.

1.Entity Information
- Formation documents , this includes certificates of registration/incorporation/information; 
- government-issued identification number for the entity；

2. Authorized Signatory Information
- evidence of the authorized signatory’s authority to act on behalf of the application entity ；
- Sign and press fingerprints (official seal and corporate seal are required)；
- ID card and a photo of the individual and ID card to prove it is the person;

3.Company operation direction and turnover
- Company goals, company's main business；
- Annual turnover in the last two years；

Question List:
1.Please provide information about the project, including the name of the organization, scale of operation, social media accounts & follwers, business license (can be sent by email); if you are an individual, please provide your name, date of birth, workplace and scale, proof of employment, social media accounts & follwers, ID card (can be sent by email).

2.When did you first learn about Filecoin? Please tell us about the projects you have participated in ? What do you want to get from Filecoin? What are your suggestions or expectations for the Filecoin network?

3.What is your data volume, source and post planning? Please describe the type, format, source, storage capacity, and public nature of the data that will be stored in Filecoin (if the data is publicly available, how will others retrieve it?

4.For application developers, will you act as a client on behalf of the user or will you apply for a notary on behalf of the user? If so, how much DataCap approval do you expect each user to receive?

After verifying this provided information, an interview and data source checking process is required. After that, an agreement should be signed for the next step: progressive assignment of DataCap, allowing the client to collect more credits
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Regular (weekly or fortnightly) inspection and inspection; We will use the filfox  websites to check the proportion of SP allocated by customers.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we will record the review request in detail, and the record will be published on github. DataCap customers will be assigned a publicity period of 10 working days for community inspection.
Of course, we may communicate with customers through slip, tg or email, and we will also keep communication records on these channels.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub will be the place to implement all requests, changes and fixes related to distribution. All records should be synchronized on GitHub, so that everyone in the community can clearly see the customer's situation, and timely track and supervise. Therefore, we keep all records on github.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L2
We will attend meetings regularly, follow up the news in a timely manner, pay attention to FIP on github, and actively handle customer DC requests. More than 5 hours per week
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No, We have any relationship with any other existing notaries or their organizations.
```

**Comment by panges2** [comment]
Hello @HarveryL,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[737.pdf](https://github.com/filecoin-project/notary-governance/files/10159495/737.pdf)

**Comment by Kevin-FF-USA** [comment]
@HarveryL 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
