### ISSUE TITLE
Notary Application: Julien NOEL - Twinquasar

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/notary-governance#739]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Julien NOEL
- Affiliated organization: Twinquasar
- On-chain address to be notarized (recommend using a new address): f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
- Country of Operation: I operate and I’m physically based in France
- Region of Operation: Europe
- Use case(s) to be supported: Any
- DataCap requested for allocation (10TiB - 1PiB): 100 TiB or any higher allocation that can be granted to my profile.
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
I’m the founder of Twin Quasar a Filecoin ecosystem mining and CID gravity a software development fully engaged with  Filecoin for many years. We invest money and all our time to support and help the Filecoin ecosystem.  We will do as much as we can for Filecoin to succeed.
Personally, I've been using  IPFS for years, I joined filecoin community 15months ago.
- Running miner : f010479
- Granted 3 times for Lotus-farcaster
- CID gravity is funded by Filecoin main player and ecosystem. 
- Presenting for miner show and tell : https://www.youtube.com/watch?v=1JtQnhvxlVg
- Presenting for Celebration week : https://www.youtube.com/watch?v=cyer6_gSv78
- Participating to SR1 / SR2 Orbital burn / Slingshot 1/2.2/2.3 (project dCompute) / Apollo program
- Participating to Dorahack Hackathon
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
~15 000Fil
```

How did you acquire the FIL cited above?
```
Participating to PL initiative (MinerX/Slingshot/SpaceRace + Mining)
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
- Developing Farcaster an opensource software for the miner community
- Current Notary for EU. Participating to weekly calls and actively helping to scructure the Fil+ program.
- Leading the EMEA storage provider group
- Funder of CID gravity. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
- CID gravity help storage-providers to protect their platform. 
- CID gravity will support new  features to protect the network against illegal content. 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Twinquasar is a storage providers managing internal and client miners
CID gravity is a platform aiming to participate to Filecoin enablement for B2B market)
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Linkedin : https://twitter.com/cidgravity (1000+ followers)
Slack : cidgravity-x.slack.com (500+ members)
Website : http://twinquasar.io
Website: http://cidgravity.com
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.youtube.com/watch?v=VODTRCMEPe4
https://www.youtube.com/watch?v=s6A6v7qeK-c&t=290s
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
I spent 17 years working for Tech companies with an expertise in Datacenters, Operating Systems, network and secuirty. My last position was Head of a Business Unit for a fortune 100 company.

Linkedin : https://www.linkedin.com/in/julien42/ (900+)

I’m looking to help and support filecoin growth. After working closely with the Notary during the first wave of notaries to define process to on-board large client, I would like to work on onboarding such client. 
In // I'm interesting to small project of the ecosystem like Lighthouse or MooseDar 
I'm also interested in supporting the Fil+ LDN objectives and initiative like Filecoin Restore, etc... 
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
PRINCIPLES : 
My approach is similar to What I did until now  : 

Defining thresholds with varying degrees of trust.
Higher the request, Higher the scrutiny

Several factors will be considered when making allocation decisions: 
- Reputation of organisation
- Scale of allocation over a certain period of time
- Security considerations
- Transparency of Client
- Client engagement to respect guidelines :
	- Process
	- Delegation
	- Contractual terms. 
	- etc…
- Sucess of a Probation period for new client (described below)
- Public or Private Data

Allocation plan : 
1. All new client start with 1-2TiB max
2. After successfully consuming the first allocation and only if it's in line with it's commitments,  client can request and get allocation for more datacap (max 5TiB)
3. Continue 5TiB iterations
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Ledger
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
 - Type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. 
 - public data vs private data etc
 - Your relationship with the data, especially with regard to copyright
 - How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
 - Have you already ask datacap to another notary that have been accepted or rejected.
 - Do you run a storage miner ?
 - How much data are you considering storing to your own miner ?
 - Please describe the nature of the relationship with this miner especially if you've got any interests in storing these miners ?
 - Will you agree to share here all the CIDs related to the datacap ?
 - Did you already have datacap from another notary ?
 - Adress confirmation
 - Entity proof : 
     - certificate of incorporation, business evidence and reputation
     - business address and location, etc..
 - Requester personal information : 
     - Bylaws / authorization from the company / title
     - Identity card / passport delivered by government and valid. 

 
If the data is private, I ask much more information and authorization from the client to audit the data unencrypted.

- Asking for commitment and transparency from the client 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. Commit the client on how the datacap will be consumed : 
2. Verify once the datacap is consumed : 
- Check on https://filplus.d.interplanetary.one how the data is spread across miners
- Audit a few deals (as soon its achievable),  
3. Iterate
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
For transparency purpose, I plan to provide all the allocation decisions in public via a GitHub repo. I will also agree to align the process the other notaries and the community; keeping in mind the processes we put in place have to be efficient. 
I will answer to any audits requests. 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
For transparency purpose, I provide all the allocation decisions in public via a GitHub repo. I will also agree to align the process the other notaries and the community. 
Private allocation will need more tooling and tracking that are not here yet. Depending on the volume of such requests I may consider accepting private requests.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
https://github.com/filecoin-project/notary-governance/issues/5
https://github.com/filecoin-project/notary-governance/issues/136 
https://github.com/filecoin-project/notary-governance/issues/468
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
I did receive a few month ago deals from clients that are notaries : Decent / PikNik
```

**Comment by panges2** [comment]
Hello @s0nik42,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[739.pdf](https://github.com/filecoin-project/notary-governance/files/10159500/739.pdf)

**Comment by Kevin-FF-USA** [comment]
@s0nik42 

Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by s0nik42** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedtzc7emjd4s5tlmuel5hn4n6l4qibrmmk5hwveukb3ep52oihtlw
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtzc7emjd4s5tlmuel5hn4n6l4qibrmmk5hwveukb3ep52oihtlw

**Comment by s0nik42** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecglpqw4ly2n2iezzb23ejx4bhip3fucfs3cmsdgcdwxcjtad3rqw
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecglpqw4ly2n2iezzb23ejx4bhip3fucfs3cmsdgcdwxcjtad3rqw

**Comment by s0nik42** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacechuschijkilf6mry673tkqm5uaqqdtt5lxxe5uhhje4ywibu5t5c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechuschijkilf6mry673tkqm5uaqqdtt5lxxe5uhhje4ywibu5t5c

**Comment by s0nik42** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedg6i2pzdt4k46kywbglggvl2u4nkzwdjjyp3oxow5qcx66dkh4hi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedg6i2pzdt4k46kywbglggvl2u4nkzwdjjyp3oxow5qcx66dkh4hi
