### ISSUE TITLE
Notary Application: Ewesion

### ISSUE THREAD

**Issue by Ewesion** [filecoin-project/notary-governance#740]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Ewesion
- Affiliated organization: http://www.ewesion.com/
- On-chain address to be notarized (recommend using a new address):f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
- Country of Operation: China
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: User Content (Personal Storage), Public or Open Data (Scientific datasets, research data, government or historic, Media & Entertainment (Videos, photos, NFTs)
- DataCap requested for allocation (10TiB - 1PiB):500TiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Our company is mainly engaged in image related Internet information services and our business covers a large number of aspects. That said, we have a large amount of data to store. Our department is always trying to figure other options to meer our storage need and that's how we found Filecoin.
Our GitHub handles: Ewesion https://github.com/Ewesion
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Now we have more than 60k Fil. f01830428, f01861781, f01866438
```

How did you acquire the FIL cited above?
```
Our company invest it.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Our first application for datacap was in September 2021. After our first successful datacap request and use, we made several more requests for datacap to store our company's data. Due to our active use of datacap, Filecoin Foundation has written a special article to document our participation in filecoin. https://filecoinfoundation.medium.com/storage-company-ewesion-leverages-filecoin-network-for-data-preservation-e36cecc84e0e
Also we have made deals on BDE platform. https://www.bigd.exchange/detail/20220902165012
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Founded in 2019 by Benny Li, Ewesion is a platform for creative artists that serves everyone from large and medium-sized enterprises to media and individual users. Ewesion is the largest picture provider for the Tencent public cloud today. We provide functional design and editing tools to its users as well as secure storage of their final creations. It is quickly becoming the image repository of choice, aiming to power and preserve content to elevate visual communications. Our company is located in China, and we have office in both Shanghai and Beijing. Now we have over 100 employees. We specialize in providing a full range of Internet information services that meet the creative and editorial graphic needs of all types of businesses, channels, media and individual users.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Official website:http://www.ewesion.com/
Wechat account: ShanghaiYiweishi
Weibo: ShanghaiYiweishi
Douyin: evistek
Twitter: ewesion
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Here's the link about an article posted by Filecoin Foundation.
https://filecoinfoundation.medium.com/storage-company-ewesion-leverages-filecoin-network-for-data-preservation-e36cecc84e0e
Here's the link posted by Sina.
http://sh.sina.com.cn/zw/q/2021-05-19/detaili-ikmyaawc6262511.shtml
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Weibo: ShanghaiYiweishi (1k+ followers)
Douyin:evistek (78 followers)
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://www.sohu.com/a/605615072_120765287
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The purpose of allocating the DataCap is to make sure clients use these DataCap in a manner fit the ecosystem needs. For new applied clients, we need background check about his/her information, like we once did.
We define 6 varying degrees of trust. The rules in this table will be the primary guideline we use when evaluating a client and determining their DataCap allocation.
![Ewesion](https://user-images.githubusercontent.com/107249346/201995761-64f71bca-0a2a-4ce8-8b99-56da86bcbf2e.png)
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We have prepared a ledger for it.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. We will consider the customer's answers and ask further questions to address the points of doubt.
We have created a questionnaire to help us get to know our clients.
1. What's your name and your position in your company?
2. Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team?
3. Are you applying on behalf of an individual or a company? For your organization, Please describe the details of your company.
4. Please describe the process by which you or your organization learned about filecoin.
5. Please show us some of your Social Media Accounts
6. Please provide your company's business registration license.
7. What types of data do you plan to store with the DataCap and how many do you need? Could you please provide us some of your sample data?
8. Where is your data stored now? Whether the data is stored on a server or a cloud service provider?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
The webpage of filplus.info easily displays if a client has only made deals with a single SP. 
To make sure deals are not distributed within a single SP entity, I plan to sync with other notaries and cross check with them on a regular basis to eliminate the concerns.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We will use GitHub.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We also use GitHub for recording.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L3.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No.
```

**Comment by panges2** [comment]
Hello @Ewesion,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[740.pdf](https://github.com/filecoin-project/notary-governance/files/10159501/740.pdf)

**Comment by Ewesion** [comment]
Please let me describe some more content in my application and I hope filplus can improve my score for notary application.

Founded in 2019, Ewesion is a platform for creative artists that serves everyone from large and medium-sized enterprises to media and individual users. Ewesion is the largest picture provider for the Tencent public cloud today. It is quickly becoming the image repository of choice, aiming to power and preserve content to elevate visual communications. With the storage request, Ewesion has joined into filecoin in May 2021. 

Due to the active participation of Ewesion, we were officially reported by filecoin and published in the official media of filecoin.https://filecoinfoundation.medium.com/storage-company-ewesion-leverages-filecoin-network-for-data-preservation-e36cecc84e0e

I'd like to show our scoring criteria again. 
We will strictly follow the criteria we have set to review the clients who apply for us.
https://user-images.githubusercontent.com/107249346/201995761-64f71bca-0a2a-4ce8-8b99-56da86bcbf2e.png

As it mentioned above, all our allocation records are public and transparent. If there is any dispute, we will respond in Slack and Github immediately; And we will form an audit team with community members under specific conditions to provide information to the notaries, respond to disputes and audit again.

**Comment by Kevin-FF-USA** [comment]
@Ewesion 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @Ewesion, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by Ewesion** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebzgbehm5dv3dtbddaviwt74z3miwetipknra3o6s65of7hehvtii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzgbehm5dv3dtbddaviwt74z3miwetipknra3o6s65of7hehvtii
