### ISSUE TITLE
Notary Application: Banyan

### ISSUE THREAD

**Issue by laudiacay** [filecoin-project/notary-governance#742]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Claudia Richoux
- Affiliated organization: Banyan
- On-chain address to be notarized (recommend using a new address): f1oc6qvenzp7wsriu7edyebb325gnaovktmujl7jq
- Country of Operation: United States
- Region of Operation: North America
- Use case(s) to be supported: [Please select from [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries)] Professional Services/Web 3.0/Other
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: [Individual, Organization] Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
My github is @laudiacay, and I am a former Protocol Labs developer working mainly on the Filecoin runtime. I have made contributions to Lotus, specs-actors, FVM, several dependency libraries of those, and contributed to internal tokenomics discussions daily during the term of my employment. 

I'm very active in Slack, attended the past two lab weeks, and send a member of my team to each governance call.

I nucleated a venture-backed startup (Banyan) in the PLN funded by Protocol Labs' Venture arm, and I'm reapplying as a DataCap Notary on behalf of Banyan. We're trying to bring on massive quantities of healthcare and other regulated data from enterprise clients.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
I have my own personal limited amount of Filecoin that I got as part of my employment package. It's not a lot. However, my entire startup is building on filecoin, so there's a substantial amount of reputational stake. We'll probably buy Filecoin to do deals as we grow our business.
```

How did you acquire the FIL cited above?
```
Employment at PL.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
My contributions are in my GitHub history, between September 2021 and February 2022, to various filecoin-affiliated repositories- FVM/ref-fvm, forest, specs-actors, lotus, and a few private security-patch repositories. You can also find my contributions in the PL slack by searching my handle, probably the ones I'm most proud of have to do with tokenomics in various crypto-econ threads.

My team and I have also been in the foundry f1 program building DeFi rails on the FVM, and we're coming out with a spec for how to do enterprise compliance auditing on chain and applying it to other services.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
I patched several security bugs during my tenure as a Protocol Labs employee with zenground as my work manager.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Delaware C-corp with 6 American FT employees, several contractors, and one Russian full-time designer. We incorporated in February 2022.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://banyan.computer
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
@banyancomputer on instagram and twitter- banyancomputer on github as well
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Almost 800 on Twitter @0xcccrrr
Like 50 or something on Github @laudiacay
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
I'm giving an interview with Chainlink as part of their Startup with Chainlink thing.
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We are going to give away as much as hospitals, telehealth clients, and others who need to store sensitive data to the clients, and give it to miners who have the correct compliance certifications. We'll scale with our BD pipeline.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We have a ledger that we already secure well.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We'll help them with it, but we'll have prior relationships with them because we'll have brought them in through our sales pipeline.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We'll be introducing them to the SPs who are appropriately vetted.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Probably private because we'll be working with sensitive clients with strict regulation on them.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We can keep an anonymized public record on GitHub if needed.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
We've been doing an L3-L4 for the past several months and can continue this level of engagement.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes: https://github.com/filecoin-project/notary-governance/issues/459
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No.
```

**Comment by panges2** [comment]
Hello @laudiacay,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[742.pdf](https://github.com/filecoin-project/notary-governance/files/10159508/742.pdf)

**Comment by Kevin-FF-USA** [comment]
@laudiacay 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to continue as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @laudiacay, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by laudiacay** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacea4mgjxerqeybtzre3ggiiqe3uid775wu5x5mb4hm7gqu33fdzpkg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4mgjxerqeybtzre3ggiiqe3uid775wu5x5mb4hm7gqu33fdzpkg
