### ISSUE TITLE
Notary Application: Saukibit, Inc. (DBA Canza Finance)

### ISSUE THREAD

**Issue by NatoSilue** [filecoin-project/notary-governance#744]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](w) and then fill out the following form. 

## Core Information
- Name: Canza Finance
- Affiliated organization: Saukibit, Inc. (DBA Canza Finance)
- On-chain address to be notarized (recommend using a new address): f1u46kil2f4kmo3pkaowqrohfueaijslm7limqxyq
- Country of Operation: Primary: United State | Secondary: Nigeria and Kenya
- Region of Operation: [North America, South America, Europe, Africa, Greater China Region (GCR), Asia minus GCR, Oceania]: Primary: North America | Secondary: Africa
- Use case(s) to be supported: [Please select from [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries)] : Public or Open Data (Scientific datasets, research data, government or historic)
- DataCap requested for allocation (10TiB - 1PiB): 200TiB
- Are you applying on behalf of yourself or an organization?: [Individual, Organization]: Organization, specifically, Canza Finance.

Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```

Canza Finance’s affiliation with Protocol Labs started a little over 2 years ago. Our involvement can be described in two aspects. The first one being learning and exploration and the second one being as service provider. The very first activity we participated in was the Tachyon Blockchain Accelerator 2020 Second Cohort where we learned from the other companies on how they were implementing IPFS/Filecoin in their respective organization. Following the accelerator, we attended Protocol Labs 2021 Lab week in Madeira, Portugal in October 2021. This event allowed us to build relationships with other organizations in the ecosystem. In March 2022, two of our employees completed the Protocol Labs Network Launchpad Training Program (V1). In June 2022, we attended Consensus by Coindesk. We used this opportunity to attend the Fil Plus Day Storage Provider Meetup and the Launchpad Community Party. During this event, we strengthened our relationship with Filecoin community members. 
Our desire to become storage providers started in April after our first 2 employees completed the Launchpad Program. In order to become a storage provider, we found it necessary to teach the african community about Filecoin and IPFS. So, we started by applying and getting accepted as Filecoin Orbit Enterprise participants to assist education and outreach for African Americans and Sub-Saharan Africans. We have participated in Outreach Programs in Nigeria and Kenya. 
In May 2022 we got accepted into the Enterprise Storage Providers Accelerator (ESPA) Program. So far, we have completed the bootcamp and learning materials. In addition, we have set up owner and worker addresses and are in the process of signing agreements with two Filecoin Leasing companies to borrow Filecoin to meet our collaterals in order to start storing data. By the end of this program, our goal is to have an infrastructure set up in Africa specifically in Kenya. Our team traveled to Kenya in August, and we were able to collaborate with existing data centers in the country. We have selected one of those data centers to collocate with. 
Protocol Labs has assisted us through this process by giving us a marketing Grant from Protocol Labs to assist with the creation of our Storage Provider website as well as marketing videos.

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
(We received an FIL allocation for investment and added more FIL to our wallet to assist our innovation and participation within the FIL ecosystem.)

```

How did you acquire the FIL cited above?
```
The FIL cited above was acquired via a seed investment round for Canza Finance. Additional FIL will be acquired leveraging lending Institutions such as Anchorage Digital and Darma Capital where relationships are already established.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Canza Finance’s past activities as members of the Filecoin community include the Tachyon Blockchain Accelerator 2020 Second Cohort where we learned from the other companies on how they were implementing IPFS/Filecoin in their respective organization. In addition, we attended Protocol Labs 2021 Lab week in Madeira, Portugal in October 2021. This event allowed us to build relationships with other organizations in the ecosystem. In March 2022, two of our employees completed the Protocol Labs Network Launchpad Training Program (V1). In June 2022, we attended Consensus by Coindesk. We used this opportunity to attend Fil Plus day, Storage Provider Meetup and well and the Launchpad Community Party. During this event, we strengthened our relationship with Filecoin community members. Additionally, Nato Silue, one of our team members mentored for the PL Launchpad V5 program in August 2022. She mentored a new Filecoin Foundation employee. She met with her mentee weekly to connect, guide and answer questions throughout the program. Finally, in October 2022, we participated in the LabWeek in Lisbon, Portugal.
Our current activities include the ESPA Cohort 3 program which will get us ready to start our initiative as Filecoin Storage Provider in Africa. We have also received a marketing Grant from Protocol Labs to assist with the creation of our Storage Provider website as well as marketing videos. We are also Filecoin Orbit Enterprise participants to assist education and outreach for African Americans and Sub-Saharan Africans. 
Fil Plus gives us access to participate in the social trust layer of the filecoin network. Encouraged to be a part of the Notary program from the ESPA program, we understand that this level of participation will increase our onchain and transparency activities within the ecosystem while also contributing to the activities of Storage providers in Filecoin Plus. Participating as a core stakeholder in the ecosystem while also gaining experience to clients and deal making/activity will also in turn increase our knowledge which add value to our storage provider capabilities. 

Relevant articles include:
The medium article regarding the Filecoin Orbit Program integration https://saukibit.medium.com/canza-finance-filecoin-orbit-2021-51773b4154cd
Canza <> Filecoin Youtube Demo : https://www.youtube.com/watch?v=95kGjmUYEhY
Filecoin Launchpad Accelerator article https://filecoin.io/blog/posts/filecoin-for-treasuries-wills-financial-access-and-more/
Filecoin twitter post about Canza Finance Seed round https://twitter.com/Filecoin/status/1518619358091743233?cxt=HHwWgsC4wdOQnJMqAAAA
Protocol Labs twitter post about Canza Finance seed round https://twitter.com/protocollabs/status/1517597585367830528?s=20&t=Y5X4a5sb5vF1bSKqNN8JLw

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Countries : Kenya , Nigeria and USA
Size : 20+ employees 
Time since inception : 2020 
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Websites :  
Canza Finance Main Website  https://canza.io/
Storage Provider Website https://www.gidabit.io/ 
Names officers : Nato Silue, Pascal Ntsama, Oyedeji Oluwoye and Victor Teixeira.
Twitter : [Canza Finance (@Canza_Finance) / Twitter](https://twitter.com/Canza_Finance)
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Relevant articles include:
The medium article regarding the Filecoin Orbit Program integration https://saukibit.medium.com/canza-finance-filecoin-orbit-2021-51773b4154cd
Canza <> Filecoin Youtube Demo : https://www.youtube.com/watch?v=95kGjmUYEhY
Filecoin Launchpad Accelerator article https://filecoin.io/blog/posts/filecoin-for-treasuries-wills-financial-access-and-more/
Filecoin twitter post about Canza Finance Seed round https://twitter.com/Filecoin/status/1518619358091743233?cxt=HHwWgsC4wdOQnJMqAAAA
Protocol Labs twitter post about Canza Finance seed round https://twitter.com/protocollabs/status/1517597585367830528?s=20&t=Y5X4a5sb5vF1bSKqNN8JLw

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```

Linkedin

Pascal Ntsama 
[Pascal Ntsama IV | LinkedIn](https://www.linkedin.com/in/pascal-ntsama-iv-92297728/)
Followers: 2,189

Oyedeji Oluwoye
[Oyedeji Oluwoye | LinkedIn](https://www.linkedin.com/in/oyedeji-oluwoye-2b9562110/)
Followers: 1,456

Victor Teixeira
[Victor M. Teixeira | LinkedIn](https://www.linkedin.com/in/victor-m-teixeira-0a0101a0/) 
Followers: 576

Nato Silue 
[Tchetahan 'Nato' Silué | LinkedIn](https://www.linkedin.com/in/natotchetahansilue/) 
Followers: 1,002

```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
Relevant articles include:
The medium article regarding the Filecoin Orbit Program integration https://saukibit.medium.com/canza-finance-filecoin-orbit-2021-51773b4154cd
Canza <> Filecoin Youtube Demo : https://www.youtube.com/watch?v=95kGjmUYEhY
Filecoin Launchpad Accelerator article https://filecoin.io/blog/posts/filecoin-for-treasuries-wills-financial-access-and-more/
Filecoin twitter post about Canza Finance Seed round https://twitter.com/Filecoin/status/1518619358091743233?cxt=HHwWgsC4wdOQnJMqAAAA
Protocol Labs twitter post about Canza Finance seed round https://twitter.com/protocollabs/status/1517597585367830528?s=20&t=Y5X4a5sb5vF1bSKqNN8JLw
```
# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We plan to allocate the DataCap requested based on the community governance principles of Trust, Transparency, and Accountability. 
The target allocation amount rubric/metrics can be found in this spreadsheet [Allocation Rubric - Canza Finance - Google Sheets](https://docs.google.com/spreadsheets/d/12F3qSsd1XvaszNha89nyJSvYBR23uxvsi2jdvA6bPgQ/edit#gid=0).
We will check the eligibility of the companies we will be working with and make sure they are legit. We will do this by following these steps:
-Browse their official website to get a general understanding of the company or the individual. 
-Query the company's registration information from government related websites to make sure the information submitted is true.
-Ask some questions to know about the applicant's position/organization/plan/use case etc. 
-Set up a call if possible with the company to have an interaction with them and learn more about them.
-Then we will classify applicants based on their industry reputation and scale etc. All applicants will be divided into four categories to determine the amount of datacap they will get. (See rubric) 
-The whole application process should be open and transparent. 
-Some brief communications via e-mail to make sure the e-mail address is authentic and valid.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hardware wallet will be used to store the keys associated with the DataCap allocation address securely. We could also use a multisig address.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will vet clients by thoroughly reviewing their background information. We will also refer to the proposed allocation due diligence solution on issue 611 [Modification: Review of E-Fil+ Project Guidelines and Details - (Pilot Kickoff October 2022) · Issue #611 · filecoin-project/notary-governance (github.com)](https://github.com/filecoin-project/notary-governance/issues/611)

Below are some questions we will ask:
1) Organization Name 
2) Legal documents such as when the organization was funded and their KYC/KYB status. This will allow us to know if we are working with a legit company or individual.
3) How reputable is the organization? This will include how long they have been operating, how many followers they have, or how well are they known?
4) Geographical location in case the client operates in multiple locations.
5) Details regarding the Use Case such as the type of data.
6) Team/personal introduction. This will help us know more about the client.
7) Filecoin Onchain Address, this will allow us to check if they had past allocations.
8) How much DataCap do you want, and why? This will help us avoid over and underallocation. 
9) Have you ever allocated any datacap  before? If yes, could you give us more details? This will allow us to have an idea of their previous experience and understand or disclose any issues they encountered in the past.
10) How will you allocate your DataCap and what will you do to avoid the datacap waste? This will allow us to check if the client has a solid strategy in place to avoid DataCap waste.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Before and after any allocation, we will track our client’s previous record. We will follow up with them to make sure that they are not violating any rules. In case, a light mistake occurs, we will warn them. However, if it’s a violation, we will notify the community and blacklist them and will no longer give them DataCap. 

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We will have a hybrid approach. This will depend on our clients. If the client does not mind, we will make all decisions publicly on github. However, if the client information can’t be exposed on github, we will make all decisions through email.

```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We will use the public filecoin github for all our allocation decisions

```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
We are willing to dedicate ourselves to L2 or higher. We have already been joining the governance calls and now we want to explore more.We will love to join a working group as well.

```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No

```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
Fenbushi Capital
PiKNiK
```

**Comment by panges2** [comment]
Hello @NatoSilue,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[744.pdf](https://github.com/filecoin-project/notary-governance/files/10159515/744.pdf)

**Comment by Kevin-FF-USA** [comment]
@NatoSilue 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by NatoSilue** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceb2o5z47ocg2v62xyzcvy5q5vo7342dfptkzkqgndhxscvz4pv5zs
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2o5z47ocg2v62xyzcvy5q5vo7342dfptkzkqgndhxscvz4pv5zs
