### ISSUE TITLE
Notary Application: Starboard

### ISSUE THREAD

**Issue by sylvanzhang** [filecoin-project/notary-governance#745]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Sylvan Zhang
- Affiliated organization: Starboard
- On-chain address to be notarized (recommend using a new address): f1x5gaseatlcp7heucu7xms5sslcwerttexgigeoq
- Country of Operation: Singapore
- Region of Operation: Asia minus GCR
- Use case(s) to be supported: Public or Open Data (Scientific datasets, research data, government or historic
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment

Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
Starboard (http://starboard.ventures/) is a dedicated contributor to the Filecoin ecosystem, primarily focused on network analytics and the provision of analytics tools to the community at large. 

Our most visible and widely used contribution to the Filecoin project is in the form of our flagship Network Health Dashboard (https://dashboard.starboard.ventures/dashboard) which is widely used across the Filecoin ecosystem to track network health on a daily basis. We produced analytics, projections, simulations, and data charts on the most important Filecoin network analytics topics through our open source research notebooks (https://observablehq.com/@starboard). We are also making the data displayed on our dashboards and notebooks available through API calls with our Spacescope product (spacescope.io). 

We disseminate important recent and historical trends about the Filecoin network through our Twitter account (https://twitter.com/Starboard_V) which at almost 170,000 followers is among the largest in the ecosystem. 

Finally, Starboard has contributed actively to events in the Filecoin ecosystem, most recently hosting or co-hosting well-received events related to network analytics and crypto-economics at FIL Austin, FIL Singapore and FIL Lisbon, with 100+ attendees on average. Link to our most recent event: https://www.filecoinanalytics.xyz/home
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
We hold about 50k Filecoin in our company account. 
```

How did you acquire the FIL cited above?
```
We bought them on the market throughout the past two years as treasury management and interest alignment measures with the Filecoin ecosystem.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Starboard’s primary activity in the Filecoin community is in the provision of contextualised network analytics to all other stakeholders in the ecosystem. Our flagship product, the Network Health Dashboard (https://dashboard.starboard.ventures/dashboard), is widely used by teams across the Filecoin ecosystem as a means to track network health and performance, and circulating supply. We also provide API endpoints to serve the aforementioned data on a headless and à la carte basis through our Spacescope (https://spacescope.io/) product. 

Additionally, Starboard has a public relations arm that regularly disseminates important updates and insights about the state of the network through blog posts and social media. Our social media presence is very well followed, with ~170,000 followers on our Twitter account (https://twitter.com/Starboard_V). 

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
We have joined the Filecoin ecosystem shortly after the mainnet launch. We helped addressed many ecosystem and protocol wide research questions, and developed analytics and tools to improve community understanding and governance. Our dashboards, research notebooks, and simulations were repeatedly used in FIP discussions. 

One example is the recent discussion of FIP 36, where our data dashboard and economic simulation were included in extensive community governance discussions. The simulator that we built to help the community better understand the implication of the FIP: https://observablehq.com/@starboard/sproi-fip-duration-v2.

```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Nature of the organization: network analytics, research, and product development
Country of registration: Singapore
Size of the organization: <50 ppl
Time since inception: around 2 years

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: https://www.starboard.ventures/
Twitter: https://twitter.com/Starboard_V 

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://messari.io/report/filecoin-has-it-an-ecosystem-overview
![image](https://user-images.githubusercontent.com/79552241/202054029-7d334f99-4607-48ca-98c8-6db7bb6d0ad9.png)

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
We run the Starboard Twitter account (https://twitter.com/Starboard_V), which has approximately 170,000 followers. 
My personal Twitter account (https://twitter.com/sylvanzsr)
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
Talks and interviews:
https://www.youtube.com/watch?v=72UadM5u0qs
https://www.youtube.com/watch?v=soCNjduv5Aw
https://www.youtube.com/watch?v=9Ol9PoYHsqs
https://www.youtube.com/watch?v=b1iX24s9CW4
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
A notable advantage of Starboard taking on datacap allocation responsibilities is our deep familiarity and intuition with network data. We intend to use an analytical and data-driven approach to datacap allocation, using our estimate of client quality to assign the datacap. 
Our allocation strategy is based on a thorough and holistic assessment of the client’s needs, reputation and quality. 
We assess client quality by leveraging on our pre-existing analytics tools:
- Our in-house SP reputation system (https://sprd.starboard.ventures/) assigns a reputation score to an SP based on metrics such as capital/size, storage reliability, gas efficiency, deal sizes and growth rate. 
- Our Filecoin Canvas (https://observablehq.com/@starboard/fpa-canvas) and Filecoin Plus dashboards (https://observablehq.com/@starboard/filecoin-plus-analytics-dashboard) track previous and current client behaviour on Filecoin Plus, checking a range of Filecoin Plus metrics including deal duration, datacap usage and utilisation, and others.

These tools will be used to answer several questions:
1. Does the client have a good track record for expending the datacap expeditiously and efficiently?
2. Has the client assigned datacap to the best and/or most reputable SPs?
3. How does the prospective client compare to the average client on Filecoin Plus?
4. Is the data onboarded by the client high quality? 

From these questions we will assign to the client a quality score, and allocate datacap at a quantum proportional to client’s size/financial means and reputation (for example, with priority or enhanced allocation for clients in the top quartile). We use historical data to guide the minimum and maximum allowable levels. Our allocation strategy is intended to fulfill our notary’s role in leveraging analytics tools to oversee client spending behaviour, and to ensure that the datacap we allocate will not be used irresponsibly by the client. 

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will develop internal tools to make sure that the DataCap allocation process is within our full control and our address is secured.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will make it compulsory for clients to provide the address for which the datacap is requested, as well as addresses the client has used historically, to facilitate our due diligence processes. 
Our vetting process is split into three major categories. We obtain answers to many of these questions from our existing analytics tools, the Filecoin Plus Analytics dashboard (https://observablehq.com/@starboard/filecoin-plus-analytics-dashboard) and the Filecoin Plus Canvas (https://observablehq.com/@starboard/fpa-canvas). 

Client profile
1. Client’s website, social media and other public information
2. Public business entity information
3. Relationships between clients, data and downstream clients
4. Client’s previous addresses

Client’s on-chain track record 
1. Does the client have any track record?
2. Has the client previously onboarded data? 
3. How efficiently did the client provide data? 
4. How reliable was the storage service provided? 
5. How much storage capacity did the client provide?
6. Were there any inconsistencies and reasons to be suspicious of their behaviour (i.e. deals with a single entity)? 

Consistency checks
Does our internal inspection conflict with any client declaration (i.e. there is substantially more or less activity than declared)? 

Additionally, we will ask clients to make a series of declarations
1. If there are open disputes over previous allocations
2. That the client will abide by the local laws and regulations
3. How the client plans to expend the allocated datacap
4. Whether the client has ever violated the terms of Filecoin Plus


```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will use our existing data infrastructure to check how the datacap was used once disbursed by us in previous application rounds. Since we make it mandatory to specify an address during the application, we are able to track the flow of deals and datacap between the client, SP and other recipient nodes. 

Apart from checking that deals are not made with a single entity, we will also check that deals are not made with recurring groups of actors or network of actors, since this can be a way of masking overallocation. If we observe inconsistencies or during the due diligence process we will ask the client to declare reasoning in writing. 

We will also check for changes to the client’s use of the allocation – if there is a major change to the way that the client will use the datacap going forward, the client is asked to declare in writing why. 

Finally, we have the capacity to check for discrepancies between what the client has declared to us and what appears on-chain, and reserve the right to decline further allocation if we assess that the client has not been up front about certain matters. 

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We plan to make allocation decisions public on Github.

```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We will open a new repo under Starboard GitHub page to record allocation decisions. 
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
We will try out best to allocate more time towards the Fil+ program and commit at least 10 hours per week on related issues.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes.
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1581
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1692
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None
```

**Comment by panges2** [comment]
Hello @sylvanzhang,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[745.pdf](https://github.com/filecoin-project/notary-governance/files/10159517/745.pdf)

**Comment by Kevin-FF-USA** [comment]
Hello @sylvanzhang,

I have not received your email verification. If you haven't sent it already, please do so by 06DEC. If you have already sent your confirmation to NotaryElection@fil.org can you please resend to ensure it was received as well as post a screenshot here as a comment.

**Comment by sylvanzhang** [comment]
> Hello @sylvanzhang,
> 
> I have not received your email verification. If you haven't sent it already, please do so by 06DEC. If you have already sent your confirmation to [NotaryElection@fil.org](mailto:NotaryElection@fil.org) can you please resend to ensure it was received as well as post a screenshot here as a comment.

Hi @Kevin-FF-USA ,

I have already submitted the email verification to NOTARYELECTION@fil.org. I just forwarded it again. Thanks!

**Comment by Kevin-FF-USA** [comment]
@sylvanzhang 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by galen-mcandrew** [comment]
@sylvanzhang Please update this parent comment with your Ledger address by Wednesday Feb 8th or we will not be able to ratify you as a notary in the fourth round.

**Comment by beng-starboard** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceccvr2yurogjsjgywgq7wjdy6zxt2kgovv7sl5osh2jjr2zxhe2tk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceccvr2yurogjsjgywgq7wjdy6zxt2kgovv7sl5osh2jjr2zxhe2tk

**Comment by Kevin-FF-USA** [comment]
Hi @beng-starboard 
Closing this application out. Fully onboarded in 4th Rd
