### ISSUE TITLE
Notary Application: Tokencan

### ISSUE THREAD

**Issue by Joyologist** [filecoin-project/notary-governance#746]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Tokencan
- Affiliated organization: Tokencan
- On-chain address to be notarized (recommend using a new address): f1pwc4w756u5gmp6gmqrxdphj7fu7kj6xjuoio54q
- Country of Operation: China
- Region of Operation: Greater China Region (GCR)
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
GitHub handle: Joyologist
Slack: Joyologist

Talis as the platform coin of Tokencan is committed to building a truly decentralized, blockchain-based operating system as the cornerstone of Web3.0, providing high throughput, scalability and availability support for all decentralized applications in the Talis ecosystem.
Talis has designed a unique distributed storage protocol based on Filecoin decentralized storage technology to better meet the diverse data storage needs of the real world, making it more stable, data persistent, and does not terminate abnormally in an intermediate state.
The Talis protocol will provide a RESTful HTTP API that can be easily used in Javascript clients, allowing Web2.0 users to transition naturally to the Web3.0 ecosystem.

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
We prefer not to disclose at this time as required by our clients.
```

How did you acquire the FIL cited above?
```
We acquired some from our investors and others are block rewards from Filecoin network.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
https://twitter.com/Tokencan/status/1405469405631303682 
https://twitter.com/Tokencan/status/1402569771321753600
https://twitter.com/Tokencan/status/1394557446190821377
https://twitter.com/Tokencan/status/1382352659227705356
https://twitter.com/Tokencan/status/1374929025240498176
https://twitter.com/Tokencan/status/1374912216592343043

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
As the world's largest decentralized storage file system, Filecoin already has more than 16EiB of storage capacity, and most miners also have a large number of machines with high computing power, and plenty of resources are currently involved in the mining and consensus maintenance stages. Lots of traditional customers, especially customers with huge data needs, have not migrated their data to the Filecoin network. This has led to a significant waste of resources, and the end-to-end distributed storage system we developed is designed to solve this problem. The storage resources provided by the Filecoin ecosystem are more preferential, more flexible, and have higher security and reliability.
As the governance currency of the distributed storage end-to-end operation system, Talis realizes the functions of profit distribution, trading, and pledge.

```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Launched in 2017, Tokencan Exchange (T Net) is an international platform for crypto digital assets that is obligated to provide issue and circulation service for Token. T Net has a wealth of business sectors, including but not limited to MIsscoin project incubator, merit wall, Mr.game platform, mining pool mall, etc., to provide comprehensive all-round one-stop services for project parties, while providing multiple profit opportunities for intermediaries. 

In recent years, T Net has developed rapidly. The number of employees distributed around the world has grown to more than 100, and the group's total sales will reach 300 billion won. In addition, 'Token Can' has built up its reputation in the global market by launching numerous investment and deposit products and achieving more than 200,000 users within two years of its establishment.

As a the platform coin of Tokencan, YLB led the original dividend contract mining model, sharing the dividends of the exchange development to every user who locked YLB through smart contracts. To achieve a mutually beneficial and win-win development model, T Net Management Committee decided to update the name of the platform coin: TALIS on April 18, 2022, laying a solid foundation for the development of T Net.

T Net will collaborate with all members to create a credible exchange, abides by the principle of self-discipline, to lead a rational communication, positive cooperation and stable development with both partners and worldwide regulators.

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://t.me/tokencanEN 
https://twitter.com/tokencan
https://www.instagram.com/tokencanglobal/
https://www.facebook.com/tokencan.net/
https://www.reddit.com/r/Tokencan/
https://tokencanglobal.blogspot.com/?zx=f9e5551466bb5e8

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.cryptowisser.com/exchange/tokencan/ 
https://cryptochooser.com/trading/tokencan-review/
https://tokenhell.com/tokencan/        
https://revain.org/exchanges/tokencan                   

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter: @Tokencan Exchange 3275 followers
Facebook: @TokencanExchange 11k followers

```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://www.uai.com.br/cupons/cupom-de-desconto-tokencan 
https://m.apkpure.com/tokencan-the-safest-and-fastest-crypto-exchange/com.Tnet.Tokencan
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The following Rubric will be the primary guideline we use when evaluating a client and determining their DataCap allocation:
https://docs.google.com/spreadsheets/d/1mDcktVl5OxZjqZ8Dt_uT9xbYS3XyBoKoj9sqrpzETks/ 

DataCap will be assigned to clients who can provide authentic information of their organization and ensure that the data is publicly available. We specify rules to figure out the true identity of the applicant as follows: 

1. Look up the client's official website to acquire the basic information of their company, and verify the validity and authenticity of the information submitted and the data source.

2. Require the clients to provide verifiable information such as the organization's business registration license, establishment documents, and to send a confirmation email with their official domain.

3. Conduct a review of the clients company's data storage content.

We will use the assessment model to score clients and assign their DataCap needs and regularly audit their allocations. 

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will use a hard wallet to store the private keys associated with the DataCap allocation address securely and we would like to use ledger to protect our datacap.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In order to ensure the authenticity of the information and reputation of clients and fairness of DaraCap allocation, we will verify the online and physical identity and reputation of clients according to the following:

Basic Info
Your name and your position in your company?

Please describe your history working on IPFS/Filecoin (significant projects or contributions with links to the community, type of engagement shown over time etc)

For your organization, Please describe its business, its history since inception, registration country, scale, employee counts, operation regions, relevant projects, industry reputation, etc.

Please show us your social media pages such as Twitter, Facebook, Instagram, LinkedIn, Reddit, Medium, YouTube, Weibo, WeChat official account, etc. Please include as many relevant details (with external links) to show your Web3 reputation or external reputation.

Can you explain your data composition and provide sufficient data samples (0.2% of your total DataCap request) separately?

Where was the data in this dataset sourced from? Do you have any proof of the ownership or authorization?

Please send a confirmation email with your official domain to our email address and attach the screenshot here. Email name should includes the issue id #.

Please send your company's business registration license to our email address for privacy concerns. If you have any presentation documents about your business, please provide them to us too.

Where is your data stored now? Whether the data is stored on a server or a cloud service provider?

Track Record
Has your organization acquired DataCap before? If so, please answer the following sub-questions.
1.1 Please share all the links and recordings of your applications before.
1.2 Please provide your DataCap allocation status and the information of Storage Providers you worked with. Is there any DataCap remaining?
1.3 What was your allocation strategy plan then and how did you execute it?

Are there any disputes open against you from your previous DataCap allocations? If any, please describe any of your honors or disputes in the field of Filecoin.

Allocation Plan
Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc.

In which geographies (countries, regions) do you plan on making storage deals?

How will you be distributing your data to storage providers?

Do you plan to make your allocation decisions and execution details public? And how to realize it?

Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?

We may further ask some questions and then give an accurate score to the application. Thank you for your cooperation!

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. We will audit the DC allocation status via statistics from https://filplus.d.interplanetary.one or [www.filfox.info](http://www.filfox.info/) (records are monitored and reviewed regularly to determine disqualification or demotion of misbehaving clients).
2. Clients are required to allocate DataCap to at least 3 or more SPs and no single SP ID should receive >30% of a client's allocated DataCap, to increase storage redundancy, maintain decentralization and reduce data abuse.
3. If the violation circumstances are serious, we will reveal this client's infringing operations to the public and add them to a blacklist and their future applications will be rejected.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We plan on making all our allocation decisions public through GitHub repo.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We will make all our allocation decisions publicly accessible on GitHub.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None.
```

**Comment by panges2** [comment]
Hello @Joyologist,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Joyologist** [comment]
@panges2 Hi just sent the required information by email. Thanks for your support!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[746.pdf](https://github.com/filecoin-project/notary-governance/files/10159520/746.pdf)

**Comment by Kevin-FF-USA** [comment]
@Joyologist 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by Joyologist** [comment]
Many thanks for your great work and support. We'll keep it up!!!

**Comment by Joyologist** [comment]
@Kevin-FF-USA @panges2 @galen-mcandrew Hi we need to change the address into our ledger address: f1txboxiscdm4f3okffyjmbilmwjtbisrbee72j6q. Thanks for your help!

**Comment by Joyologist** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec2xy3sdowqqhqjh5k56sa4qxjhma3hjdijrtexfawyl4e57f6mji
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2xy3sdowqqhqjh5k56sa4qxjhma3hjdijrtexfawyl4e57f6mji
