### ISSUE TITLE
Notary Application: XnMatrix

### ISSUE THREAD

**Issue by XnMatrixSV** [filecoin-project/notary-governance#747]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: XnMatrix
- Affiliated organization: XnMatrix
- On-chain address to be notarized (recommend using a new address): f1bcvvwv3w6az7ivhdzory7anha54ocrlkxazm3yq
- Country of Operation: USA
- Region of Operation: North America
- Use case(s) to be supported: Professional Services, Public or Open Data
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
As an organization, XnMatrix Group built quite an extensive relationship with the Filecoin community since 2019. We have sustained some contributions to the overall network. 
As a miner and researcher，we joined the testnet, space race, slingshot, mainnet. 
Here is some GitHub issue we discussed about:
https://github.com/filecoin-project/lotus/issues/3928
https://github.com/filecoin-project/lotus/issues/4861
https://github.com/filecoin-project/lotus/issues/1824
In addition, we are deeply involved in the mining of filecoin. Our miner IDs are f02614, f09652, f010424, f03362, f020928, f039992 and more,  with a total computing power of about 600 PiB.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
So far, we hold total tokens more than 1MM FIL, of which 742 FIL is currently available, 759193 FIL is locked as collateral, and 553035FIL is vesting.
```

How did you acquire the FIL cited above?
```
mining
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Now XnMatrix is the world's leading IPFS supplier with the leading IPFS mine pool.
XnMatrix can provide customers with one-stop storage services, including storage resource management, storage resource trading, and storage token trading across different block chains.
At the same time, XnMatrix provides decentralized cloud computing services based on the Web 3.0 infrastructure backboned by blockchain technology.
We participated in the AMA online meeting actively.
At the same time, we successfully held the 2020 Distributed Storage Summit in Chengdu. 
We are honored to invite @Keren from the Protocol Lab to give a keynote speech. Please check with @Keren who will be able to substantiate our contributions. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
We participated in the early testing before reset and gave the official feedback.
Leng Bo @coder-lb joined our IPFS business union as technical consultant early. 
We found some serious/critical bugs, such as
https://github.com/filecoin-project/specs-actors/issues/448 : The mining power is permanently dropped but there are no expired faulty sectors
https://github.com/filecoin-project/lotus/issues/1824 : We need to add Deadline for SubmitWindowedPoStParams
https://github.com/filecoin-project/lotus/issues/2204 : Index out of range issue of lotus-storage-miner proving info
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Organization: XnMatrix Silicon Valley Office
Nature:  private company
Registration Country: California,US
Established: Jan, 2021
Size: over 500 employees
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Homepage: https://www.xnmatrixs.com
Twitter: https://twitter.com/superxnmatrix?lang=en
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
XnMatrix is the world’s leading decentralized cloud computing platform, offers fully featured decentralized cloud/network resource services and computing power products to individuals and enterprises, to complement and leapfrog the centralized cloud computing in terms of lower cost, data privacy and security and digital asset liquidity.
We also optimize distributed storage efficiency in terms of hardware, software, algorithms, operation and maintenance, applications, etc. 
We provide integrated storage products and industry solutions for enterprises and industries.
It mainly includes ultra-low-cost computing power covering IPFS, cryptocurrency, AI, edge computing and other fields, as well as services derived from computing power requirements, including cloud computing account management, cloud computing APP SaaS service, cloud computing e-commerce platform PaaS service, cloud computing trading service, etc.
https://finance.yahoo.com/news/2020-distributed-storage-summit-ended-124500305.html
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
NA
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
NA
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Here is our allocation process.
```
![1621834931(1)](https://user-images.githubusercontent.com/74889675/119301991-ee5aa900-bc95-11eb-82de-1dcdcf94b441.jpg)
```
1. The DataCap will be mainly allocated to North American customers.
   Other regions Applications will enter the waiting queue.

2. We will classify customers based on their industry reputation and scale. 
   All customers will be divided into four categories:  top team customers, medium team customers, small team customers, and individual. 
   The four categories of customers are allocated 40%, 30%, 20%, and 10% respectively.

3. The client classification rules are as follows:
https://docs.google.com/spreadsheets/d/1LjVLLmV0GxEDZf4eH5hv3m2v00qDzbKlez9g0-t95RY/edit?usp=sharing

4. In the initial stage of specific allocation, we will take out a small part (<10%) of each category for testing, and gradually establish a reputation mechanism (including incentive, punishment, supervision)

5. Each assignment will be used to evaluate the customer's reputation.
   For example, if a customer applies the DataCap which is valid and efficient, its reputation credit will increase.
   With higher credit, the customer can apply more DataCap (maximum increase 200%).

6. Throughout the allocation and use the DataCap, we will establish a corresponding review mechanism.   
   Good customer will benefit, bad customer will be punished. The quality of the customer will be optimized gradually.

Our internal processes rarely involve allocating DataCap target, amount or rate.
Most of the processes are external, which are open to the public.
The few internal processes, such as the collection of confidential information or the execution of due diligence, will be in private. 
Only when we are unable to verify the truth and legality of the information provided by the customer, the internal processes will be triggered.
In addition, some third-party tools may also be used to collect the information of clients from web.

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A hardware wallet will be used to store the keys for DataCap address.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Generally, the higher DataCap is needs, the stricter the customer review. In the early stages, all customers must go through a rigorous process.
For individual customers, the verification of their identity will be verified through two parts, the account age and the account activity, which will prove that customers are valid users and not machines. 
In addition, some open third-party data, such as Linkedin and Twitter official accounts, can also be used to verify online identities.
For organizational customers, we will set up a due diligence team and establish a complete review mechanism to ensure the reasonable allocation and effective use of the DataCap.
The following is the proposed due diligence procedure.
According to the customer level that requires due diligence, we need the following types of information. 
The review requirements for small-scale storage users are relatively simple, and users for large-scale storage will be strictly reviewed.

A. Basic information / Initial verification
Verify content:
1.Whether the customer have used up allocated DataCap
2.Valid client
(1)Active time is more than 6 months of github account or other authoried social platform account, like Twitter, linkedin, Weixin,etc.
(2)Whether to meet the basic requirements?
3.Application Requirements
XnMatrix accepts applicants for DataCap from all entities legally existing within the territory , including but not limited to enterprises, institutions, non-profit organizations, individuals, etc. Application requirements mainly includes three parts,  basic requirements, ban instructions, and annoucements.
Basic Requirements
（1）Abide by the laws and regulations of applicants' area with no bad record due to any violation of laws and regulations.
（2）All actions comply with the Filecoin community specifications and do not directly or indirectly harm the Filecoin network.
（3）The location of the applicant allows/does not restrict the development of distributed storage and related businesses. If there is any requirement about distributed storage and related businesses, the applicant should achieve corresponding required standards. 
（4）The data to be stored should meet the following requirements:
① Clients have the irrefutable proprietary right of the data, such as usage, storage, etc. Data can be from daily business, production, and data obtained and authorized from a third platform.
② The content should be legal, true, valid, and not sensitive.
（5）We discourage that miners or entities associated with miners apply for DataCap, and shall not conduct offline transactions with miners for benefits.
Ban Instructions
（1）It is prohibited for related applicants to apply at the same time.
（2）It is forbidden to upload false or unauthorized data.
（3）DataCap applications and data storage are prohibited for illegal, unethical or malicious purposes, including but not limited to give away, transfer or sell to third parties.
Annoucements
（1）The principle of exhausted Datacap: Before applying, please confirm that you have no available DataCap. The application will not be granted if the Datacap is not exhausted.
（2）The principle of waiting: XnMatrix will give priority to applications from North American clients. Applications from other regions should wait for 7 days. XnMatrix will confirm whether or not to process the application based on the remaining DataCap. If there is still a surplus after 7 days, XnMatrix will initiate the application vetting procedure for these applications.
（3）The principle of updated specifications: XnMatrix will process all applications in accordance with the above specifications. If it is necessary to add or modify the relevant specifications, XnMatrix reserves rights to decide whether to approve the requirements of clients in the process of application with the new regulations.
（4）The principle of response: During the vetting process, XnMatrix can put forward more requirements to clients, and all applicants shall respond within 7 days, otherwise it will be deemed to be automatically withdrawn and XnMatrix will close the issue.
（5）The principle of allocation: For individuals/organizations that meet the above basic requirements, XnMatrix will score and classify according to clients’profile. The detailed allocation plan is in the following part. XnMatrix will allocate 0-10 TiB for the first time, 0-20TiB for the increased application, 0-100TiB for the accumulated application. If there is no sufficient reason, it is recommended to apply for DataCap within the above amount.
（6）All interpretation rights belong to XnMatrix within the law.

B. Basic requirements of DataCap allocation / Second verification
Verify content:
1.Whether the region is same as the notary's region?
2.Information integrity, whether there are the following required items not filled in / selected:
(1)Name, website / social media, filecoin address, DataCap request
(2)Region (where you / company, the client,  based)
(3)An individual or a company
    For an individual: number of social media audiences, past project level, filecoin activities,data type, storage requirements，links to social media/news mentions, etc.
    For company:date of establishment, number of employees, business area, number of registered users, number of social media audiences, storage requirements, the best products or projects, links to social media/news mentions etc.
(4)Whether they are willing to publish the transaction flow on GitHub;
(5)Data source, your relationship with data.
3. Information accuracy
(1) Whether the website / social media is a valid link;
(2) Whether the filecoin address is a valid filecoin address;

C. More information/Final verification
Confirm the DataCap allocation plan with the qualified client. Reclssify if the client add extra questions to verify the client's qualification, and decide allocation scale.
Content:
1. The client's application records from other notaries, whether it is finally passed or rejected. whether it is properly used after allocation, and the reasons for rejection, etc
2. For qualified clients, grant DataCap according to the level. For the allocation plan, whether the client accepts it

After collecting and reviewing the above information, they will learn spend the DataCap reasonably and effectively.
We will make a training plan and release an online test for DataCap and Filecoin. Only clients who pass the test can apply the dataCap.
We will help customers match and recommend more suitable miners. We will provide clients more useful information about miners, such as failure rate, storage cost, safety, reliability, capacity, etc.
We mark the results of using DataCap as the feedback to influence the allocation in future , thereby affecting customer behavior.
The incentive mechanism, punishment mechanism and supervision mechanism will make spending the DataCap responsibly and effectively.

1. incentive mechanism
If a customer applies the DataCap which is valid and efficient, its reputation credit will increase. With higher credit, the customer can apply more DataCap (maximum increase 200%).
We encourage customers to allocate DataCap to more new miners, and each new miner allocation will have additional incentives.

2. punishment mechanism
If a customer is found to be abusing data, it will be punished.The next apply will reduce 50%.
In particular, if the client and the miner cheat together, both of them will be added to the banlist.
Other clients can report unfair allocation.

3.supervision mechanism
As a Notary, we will develop a tool to randomly check verified transactions of all customers to ensure they comply with the agreement.
Also,we will use a series of incentive mechanisms to encourage other clients to report unfair allocation and allow them to monitor and  supervise each other.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will monitor and track the use of DataCap strictly.
Each assignment will be used to evaluate the clients' reputation. 
We encourage customers to allocate DataCap to more new miners, and each new miner allocation will have some incentives.
Also, we will develop a tool to randomly check verified transactions of all customers to ensure they comply with the agreement.
If some problems are found, we will communicate and coordinate promptly. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We will keep every detail record for all allocation decisions on Github, including time, amount, allocated customers, reason for judgment, etc.
Since all interactions are intended to occur publically, most of the allocation decisions should be self-explanatory.
Any challenges raised regarding allocation decisions should be discussed publicly, e.g. the Github repo.
If convincing justifications can’t be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date.
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders to resolve the dispute.
A hearing may be given within 30 calendar days of the dispute resolution application depending on the arbitrator's decisions.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
All allocation decisions will happen in the Github repository publicly.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L5
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
https://github.com/filecoin-project/notary-governance/issues/150
https://github.com/filecoin-project/notary-governance/issues/27
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
MatrixStorage & BingHe
```

**Comment by panges2** [comment]
Hello @XnMatrixSV,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by Kevin-FF-USA** [comment]
@XnMatrixSV 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by Kevin-FF-USA** [comment]
Hello @XnMatrixSV 

As of this writing you have not yet confirmed your TOKEN code in SLACK to verify your comms. Please send a DM to Kevin-FF in SLACK ASAP to link your GITHUB comms with SLACK.

In your completed CONTACT and DISCLOSURE form you did not provide a FUL LEGAL NAME for the owner/controler of the wallet address. Please resubmit with that needed information by EOD 17Jan or you will not be verified to receive FIL or DataCap in this 4th round.

**Comment by XnMatrixSV** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecahc2l7i5bvsq6nplcuexlxl5yup52lw233hxxip6l7f5yp6zdpw
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecahc2l7i5bvsq6nplcuexlxl5yup52lw233hxxip6l7f5yp6zdpw

**Comment by Kevin-FF-USA** [comment]
Hello @XnMatrixSV ,
The disclosure form submitted did not include a name (need FIRST/LAST) for the owner/controller of your physical ledger. Via email) [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) please send FIRST/LAST name to avoid significant delays in receiving R4 DataCap

**Comment by XnMatrixSV** [comment]
@Kevin-FF-USA noted, will send the name through email now. Thanks!

**Comment by XnMatrixSV** [comment]
@Kevin-FF-USA name has been sent to the email, please check. Thanks!
