### ISSUE TITLE
Notary Application: Holon Innovations

### ISSUE THREAD

**Issue by mjroddy** [filecoin-project/notary-governance#748]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Holon Innovations
- Affiliated organization: Holon Global Investments PTY Ltd
- On-chain address to be notarized (recommend using a new address): f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
- Country of Operation: Australia
- Region of Operation: [North America, South America, Europe, Africa, Greater China Region (GCR), Asia minus GCR, Oceania] Oceania
- Use case(s) to be supported: [Please select from [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries)]
Support (1) or more the following, which can be linked to in a separate doc:

Professional Services (Hosting Reseller, Long-term Backups, Data Warehousing)
Public or Open Data (Scientific datasets, research data, government or historic
Media & Entertainment (Videos, photos, NFTs)
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: [Organization]

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```

- In 2017 Heath Behncke Holon co-founder participated in the Filecoin SAFT

- Holon Global is among a small number of funds that have an investment philosophy open to digital assets in Oceania and is working to make access to Web3.0 opportunities open to everyone.

- In true web3 collaborative fashion, [Holon](https://holon.investments/) and [Filecoin Green](https://green.filecoin.io/), a Protocol Labs initiative to decarbonize the Filecoin Network, have released their first comprehensive Web 3.0 Environmental, Social and Governance (ESG) report.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Significant Exposure and collateral at stake - prefer not to give details currently.
```

How did you acquire the FIL cited above?
```
Own capital, Founders capital, Holon has also set up a fund in the Australia market in which it utilises for its own storage operation.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
Holons' founder Heath Behncke was an early advocate and investor in FIL, having analysed the problems of web2.0 and discovering the potential of decentralised storage models and the Filecoin proposition. Filecoin is now an investment focus for Holon with the following underway:

1. Growing at 500TiB capacity per month, 37 PiB of Adjusted Storage currently online.

2. Holon Innovations set up the Holon FIL Wholesale Fund with custody partner Gemini. The fund is dedicated to investing in growing Holon's FIL mining operation.

3. Commenced a thought leadership campaign working with ProtoSchool (https://proto.school/) targeting the tertiary education sector in Oceania to build awareness and the Filecoin community with the student and academia community - a 'grass-roots' tactic to excite Grads and inform educators of disruptive technologies. This involves sponsoring education/ masterclasses, presentations/ webinars and sharing resources. (https://holon.investments/wp-content/uploads/2021/04/IPFS_masterclass-flyer.pdf)

4. Commenced awareness and marketing campaigns including a hackathon (https://taikai.network/en/holon/hackathons/holon-innovate/overview) to build both knowledge of IPFS and Filecoin and the community in Oceania
Fundamentally, the Holon team see the potential and believe in the value Filecoins decentralised storage can offer the world and are working to help make it a success. Our own mission is to look after the wealth of our clients, to ensure they benefit from disruption, not suffer.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Holon has made contributions to the development of an enterprise grade Filecoin Storage Solution, working with other SPs and PL globally on technical issues, ingress efforts and automation of operations. This includes forming partnership with PikNik, DSM & Dcent. We will face constraints in our ability to scale if the scope of the system continues to remain public data only.

PROPOSAL: Something that is growing in demand, and the reason it is mentioned in this application is, this will influence our future investment in the network is - “FIL+ for private data” – we are seeking to understand if the program be expanded to include private data where the applicant/ company is KYC, and the KYC system is a global standard. 80% of the worlds data is private, could there be sub "FIL-Priv" program for private data?
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Holon Global Investments was founded in 2018 at a time when it was clear digital assets will become an investment class and that everyone should have access to investing in them.
Our mission is to be the 'next generation Fund Manager' with an evolutionary philosophy. Having worked in wealth management for decades, this experienced team came together over a desire to solve the issues investors face around declining returns and access to investing in digital assets which offer yield potential. Holon Global Investments (HGI) has 3 entities:

1. Holon Global Investments - delivering a range of investment funds, diversified across digital assets

2. Holon Innovations - builds tacit know-how through getting involved in Web3.0 and decentralised projects, the first is a Filecoin mining operation across Sydney AUS and Oceania

3. Holon Principal Investments & VC - The first strategic investment in Avanti bank (https://holon.investments/why-we-invested-in-avanti-the-future-of-banking/) is part of creating a safe legal structure for digital assets and in the future the VC arm with fund accelerators and other Web 3.0 ventures.

With Wealth creation now taking place through innovation and disruptive new business models and we are working to make these opportunities available to everyone.
Ref here for all media & press https://holon.investments/insights/

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).

Holon Global Founders: Heath Behncke [www.linkedin.com/in/heath-behncke-a164971a/](https://auc-word-edit.officeapps.live.com/we/www.linkedin.com/in/heath-behncke-a164971a/)
Luke Behncke [www.linkedin.com/in/luke-behncke-3a945723/](https://auc-word-edit.officeapps.live.com/we/www.linkedin.com/in/luke-behncke-3a945723/)
MD of Holon Innovations: Jonathan Hooker [www.linkedin.com/in/jonathan-hooker-syd/](https://auc-word-edit.officeapps.live.com/we/www.linkedin.com/in/jonathan-hooker-syd/)

```
Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Website: [www.holon.investments](https://auc-word-edit.officeapps.live.com/we/www.holon.investments) 2000 subscribers
Linkedin: Holon Global Investments 1200 followers
Livewire: Holon Global Investments 2000-3000 views per story
Twitter: @GlobalHolon
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Head of Ops & ecosystem & current notary: Mark Roddy https://www.linkedin.com/in/mark-roddy-40b2ba36/
https://twitter.com/markroddy9 (180 followers)
https://medium.com/@mark.roddy
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
(https://www.livewiremarkets.com/contributors/mark-roddy) 31k views on stories
(https://medium.com/@mark.roddy)
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The mission of our DataCap strategy is to build network effect. Our role as a Notary and how we will generate the market are strategically aligned. Oceania is lagging the Northern Hemisphere's awareness and adoption of decentralized protocols and solutions, our use case diversity will target the most ideal clients/ data who will become advocates. The end to end customer journey from ‘acquire to ‘retire’ and all service in between will be managed in the following way
(1) Application DD. As a Notary we triage for completeness before processing using this question set
(2) Following client response, these are evaluated:
Reputation of business
Storage request and growth rate
Low retrieval rates
Security considerations/ sensitivity of data
Ability to become a Filecoin ambassador/ advocate
(3) Should the application be approved, we monitor usage or where this is an LDN, ref to the bot stats in GitHub
There are many issues with the current LDN process which is one of the two key reasons we considered not renewing the Notary role. The LDN process is calibrated to manage bad actors. It's almost at odds with a Web3 trustless world. Its introduced a lot of friction for notaries and is a poor customer experience.


PROPOSAL:
(1) Many issues could be solved up front with KYC and a client application not in GitHub but with a decent UX and CRM
(2) LDNs need audit automation and automatic allocation rather than the friction occurring in Github over subsequent tranches
(3) The entire process is not a positive CX experience which is not aligned with Holons values and how we work, causing friction for us. Filecoins commercialisation stage needs a focus on the customer and a service design blueprint & customer journey is very necessary
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The address that will be allocated DataCap will have its keys be secured with custody partner Gemini
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Following onboarding of the client and allocation of their first tranche, clients will be monitored and vetted regularly against their decentralised data storage strategy and execution plan to ensure the allocated DataCap is being spent exclusively as approved. Additionally during this ‘probation’ term Holon Notary Ops will ask the Client to provide some or all of the following:
(1) A consolidated Content Identifier (“CID”) list for verified deals that includes deal CID and miner ID (showing how the allocated DataCap has been used);
(2) A description of the data being stored and how the data has been processed;
(3) Instructions on data retrieval.
(4) Random-sample inspections by Holon Notary Ops on the verified deals sent out by the Client on chain will be checked against the deal CID and retrieval from miners to verify the data authenticity. Filecoin public monitoring and auditing will be in play also
(5) “In-life” client questionnaire
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
As above.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will conform to standards using the repo https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues . We will store all the work records of clients, their artefacts and allocation decisions.
1.The allocation guidelines and other supporting rules will be publicly available following approval.
2. The client record/ data, application, correspondence and decision reports will be kept for at least 3 years.
3. Audits to be conducted by professional lawyers or accountants appointed through Filecoin community governance procedure. Auditors will have access to all relevant files ensuring confidentiality and that certain data may be withheld without permission of the Client authority.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
All allocation decisions will conform to standards using the repo https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues, made public for transparency in this phase. In future some clients and their storage needs may be complex or sensitive and records may be then maintained on Holon Database
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
Approximately 1 day per week
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
YES 100 TiB
https://github.com/filecoin-project/notary-governance/issues/460
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No
```

**Comment by mjroddy** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecd6h52knz63y2yl2lcfqauhk2xknygwms5slmvyoi63c42ccyi4g
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecd6h52knz63y2yl2lcfqauhk2xknygwms5slmvyoi63c42ccyi4g

**Comment by Kevin-FF-USA** [comment]
Hi @mjroddy,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Kevin-FF-USA** [comment]
@mjroddy 

Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to continue as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by mjroddy** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacea3okwr43r6w5adnqa4ywihylyurxnahqi7ea62su4t3a6h346ngy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3okwr43r6w5adnqa4ywihylyurxnahqi7ea62su4t3a6h346ngy

**Comment by mjroddy** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedza2fknhackir6ptsw6a65z2i45poplv3kqeowrrfgwrkqb36kem
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedza2fknhackir6ptsw6a65z2i45poplv3kqeowrrfgwrkqb36kem
