### ISSUE TITLE
Discussion: Notaries should be expected to attend Bi-Weekly Community Call

### ISSUE THREAD

**Issue by zixuanzh** [filecoin-project/notary-governance#75]
Being a notary itself is a tedious job that serves the community. Having notaries attend bi-weekly community call allows more face time with the community like an office hour to build trust and transparency, foster collaboration, hear community feedback. Phillip has done a great job of attending almost every community call to date and there are other community members who have done so as well.

Timezone could get in the way but we can potentially work something out. For example, changing the community call to 30 min a day at two different time slots or alternate different time slots every other community call.

**Comment by jnthnvctr** [comment]
+1 to the idea of altering time slots to making it easy for folks to participate.

**Comment by jnthnvctr** [comment]
I've started a poll in the slack for people to add options and vote!
