### ISSUE TITLE
Notary Application: Filecoin Foundation

### ISSUE THREAD

**Issue by dannyob** [filecoin-project/notary-governance#750]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Danny O'Brien
- Affiliated organization: Filecoin Foundation
- On-chain address to be notarized (recommend using a new address): f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
- Country of Operation:  United States
- Region of Operation: North America, Europe
- Use case(s) to be supported:
Professional Services (Hosting Reseller, Long-term Backups, Data Warehousing)
Developer Tools (Package Managers, Automatic Notaries, Web2 to Web3 integrations)
Decentralized Applications
User Content (Personal Storage)
Public or Open Data (Scientific datasets, research data, government or historic
Media & Entertainment (Videos, photos, NFTs)

- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
The [Filecoin Foundation](https://fil.org/about) is an independent organization dedicated to supporting the growth and long term success of Filecoin.  The Foundation was also the first beta notary for Filecoin Plus, as well as a notary for Europe in the first round of notary selections where @philippbanhardt represented the Filecoin Foundation and distributed 100TiB of Data Cap.  Subsequently, @dannyob has been Filecoin Foundation Notary since [July 2021](https://github.com/filecoin-project/notary-governance/issues/187#issuecomment-883627535), as part of his duties at the Filecoin Foundation to monitor and steward the long-term health of the Filecoin ecosystem.

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
100 million tokens, per the vesting [schedule](https://coinlist.co/filecoin). 
```

How did you acquire the FIL cited above?
```
The Filecoin Foundation reservation of FIL was established in the original paper, specifying the Filecoin network.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
The Filecoin Foundation is an independent organization dedicated to supporting Filecoin, an open source, decentralized storage network designed to preserve humanity’s most important information.The Filecoin Foundation facilitates governance of the Filecoin network, funds critical development projects, supports the growth of the Filecoin ecosystem (including managing the security reporting for the network's primary tooling, and supporting alternative implementations of the client), and advocates for Filecoin and the Decentralized Web.

(Note that while Foundation is the host for the Fil+ governance team, the role of notary is independent and falls to someone outside the reporting structure for governance.)
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
The Foundation employs a [full-time computer security team](http://fil.org/governance/#panel-2-title), who maintain our bounty program, and organizes audits of key components of the Filecoin stack.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
The Filecoin Foundation is an independent organization dedicated to supporting Filecoin, an open source, decentralized storage network designed to preserve humanity’s most important information.The Filecoin Foundation facilitates governance of the Filecoin network, funds critical development projects, supports the growth of the Filecoin ecosystem, and advocates for Filecoin and the Decentralized Web.

The Filecoin Foundation was founded in 2018 is registered in the US.  It has fifty staff. ```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://fil.org/ 
https://twitter.com/FilFoundation
https://filecoinfoundation.medium.com/
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
http://filecoin.io/blog/posts/meet-the-filecoin-foundation/
https://news.google.com/search?q=%22Filecoin%20Foundation%22
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://www.twitter.com/mala (8341)
https://www.linkedin.com/in/dannyo2/ (500+)
https://keybase.io/malaclyps (152)
https://github.com/dannyob (280)
https://mastodon.social/@mala (3200+)

```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
[Wikipedia entry](https://en.wikipedia.org/wiki/Danny_O%27Brien_(journalist))
[Introduction](https://filecoinfoundation.medium.com/meet-filecoin-foundation-senior-fellow-danny-obrien-8350302f7d0)
[Interview](https://fission.codes/blog/danny-obrien-filecoin-foundation-redecentralize/)
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
## Concreteness of Allocation Plan 
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We use application judgement modeled after the one used by https://github.com/filecoin-project/notary-governance/issues/29# 

We also use our knowledge of teams needing data cap through our work with them in programs such as our developer grant program, and our ecosystem development programs, and real-world partners supported by our sibling non-profit organization, the Filecoin Foundation for the Decentralized Web, to help promote the public interest goals of verified clients and help facilitate their onboarding of useful data to the filecoin network. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
The address that allocates DataCap has its keys secured on a hardware wallet. Foundation employees acting in the role of notary have and will be vetted by the foundation. 

```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Clients who apply for DataCap for a project associated with other Foundation services will have the allocated data evaluated in conjunction with their other milestone check ins. 

Clients who apply for DataCap from the general public will have submitted a detailed proposal and have been vetted according to the criteria laid out by the Fil+ criteria.

Clients behavior will be compared to the plan they had submitted and if there are significant deviations, especially with publicly available data, the foundation will investigate.  We continue to utilize tooling that will automate verification of on chain data vs what was proposed in the clients initial application. We also expect the community to flag any broad cases of wrong doing and to work with our dispute management system. Additionally those found to have misallocated data will be strongly discouraged from engaging in other forms of Filecoin Foundation support. 

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We monitor the outlay of previous datacap, and ensure that it is being widely allocated (barring mitigating explanations of a temporary nature). This is primarily conducted via Fil+'s existing public  bot analysis, though we reserve the right to compare and prioritise our own internal tooling if necessary.

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We err on the side of public disclosure, though when necessary, we are willing to communicate privately when confidential information can assist in our decisions. For instance, in a number of cases, the Foundation has agreed to sign an NDA in order to investigate a Fil+ client, when for publicity reasons they wished to delay the disclosure of their identity until after the data had been stored. These agreements are exceptional, however, and we will publicly note when they are taking place, provide a justification, and state the time-limits or any conditions that apply to them.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
On Github.
```

## Service Level Agreement
### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
We anticipate an L4 level of service.
```


## Track Record
### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```

@philippbanhardt acted as a representative of the Filecoin Foundation in our first application:
https://github.com/filecoin-project/notary-governance/issues/54

@meganklimen acted as representative of the Filecoin Foundation in our second application:
https://github.com/filecoin-project/notary-governance/issues/187

@dannyob acted as representative of the Filecoin Foundation in our third application https://github.com/filecoin-project/notary-governance/issues/469
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No relationships, beyond  interactions as part of working with all of the stakeholders in our community.

```

**Comment by dannyob** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceca65iucggrllz37o7nyhsjyb6trw4fgerik5yfqvykak7ykwm4kg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceca65iucggrllz37o7nyhsjyb6trw4fgerik5yfqvykak7ykwm4kg

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[750.pdf](https://github.com/filecoin-project/notary-governance/files/10159533/750.pdf)

**Comment by Kevin-FF-USA** [comment]
@dannyob 

Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to continue as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.
