### ISSUE TITLE
Notary Application: CodoonHealth

### ISSUE THREAD

**Issue by Holiday507** [filecoin-project/notary-governance#752]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:CodoonHealth
- Affiliated organization: Chengdu Codoon Health Technology Co., LTD
- On-chain address to be notarized (recommend using a new address): f13fb55frdtfjfyaj75v4lp3elchrlxm2lgle43bq
- Country of Operation: GCR
- Region of Operation: GCR
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
It has been more than two years since CodoonHealth joined Filecoin in 2020. We started out as a community participant by using distributed storage. Since 2021, we have become the communicator of distributed storage. We began to attend distributed storage related summits and give presentations and speeches on the changes brought by our participation in ecology to the sustainable development of enterprises.
Github：@Holiday507
Important project in 2020: https://www.163.com/dy/article/FRT91AB50519SM7A.html 
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
none
```

How did you acquire the FIL cited above?
```
none
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We participated in the Summit as eco-partners in 2020: https://www.163.com/dy/article/FRT91AB50519SM7A.html 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
none
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Chengdu Codoon Health Technology Co., LTD is an enterprise focusing on AI big data and diet health. We are a subsidiary of China's top sports APP Codoon and invested by Codoon and SoftBank China. Our products CodoonHealth (https://www.codoonhealth.com/) is based on AI exercise with the diet health services for big data platform. 
We were founded in 2016 in China, with more than 10 members.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website：https://www.codoonhealth.com/ 
Weibo：https://weibo.com/u/6345569585 
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.cqcb.com/dyh/live/dyh2737/2018-10-15/1154197_pc.html
https://36kr.com/project/1678347005228033
https://mp.weixin.qq.com/s/VpkmazfmvJmNQaKNHGHd1w
https://baike.baidu.com/item/%E5%92%95%E5%92%9A%E5%81%A5%E5%BA%B7/22398274?fr=aladdin
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Wechat Official Account：codoonhealth （follower：30849）
Weibo：咕咚健康（follower：31000）https://weibo.com/u/6345569585 
```
![image](https://user-images.githubusercontent.com/118235124/201898043-8b5b6ee2-8a83-4b9e-9880-5e6dbc7bf5ea.png)
![image](https://user-images.githubusercontent.com/118235124/201898089-44ad42e8-2e87-4e6a-953d-1dd381232a23.png)

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://baike.baidu.com/item/%E5%92%95%E5%92%9A%E5%81%A5%E5%BA%B7/22398274?fr=aladdin
```

# Allocation Plan 
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
General Principles:
We will do our best to ensure that our distribution will be fair, justified and open. Our goal is to enable compliant clients to access the Filecoin ecosystem through DataCap acquisition. Based on a survey of past DataCap grants, we found that applicant authenticity and SPs storage allocation are the most important parts of DataCap grants that should be focused on.
For DC applicants
1.Authenticity and compliance
The applicant shall highly reflect the authenticity, effectiveness and sustainability of the project and data in the application materials.
a.We'll try to know the basic information of the applicant through the questions and procedures involved in due diligence, including the place of registration of the business, time, business license, business scale, industry reputation, etc.
b.Vet in multiple ways, icluding basic data sample, the amount of data requested, the type of data, previous storage methods and openness of data. 
2.SPs distribution
The applicant shall guarantee that prior or future storage shall comply with community rules.
a.Find out if the user has a list of SPs to store, or a storage plan;
b.If it is not the client's first allocation, we will refer to the client's previous usage of DataCap and determine whether to grant it.

For ourselves
Oriented by the allocation objectives within the term of office, the allocation process shall be non-discriminatory and transparent.
1.Transparency and justice
a.We are open to applications from all regions, data categories and nature of subject.
b.We won't allocate more than 30% of our DataCap to the same client.
c.All allocations will be fully disclosed and recorded.
2.Efficiency of allocation
a.We will give feedback to inquiry of the Issue within 2 working days.
b.Actively cooperate with the allocation and participation of LDN or other ecological projects.
c.We will try to complete 80% of the DataCap allocation before the next Notary Election Cycle.

https://docs.google.com/spreadsheets/d/1rUqE6Dp4NzHrIKrq9WLzDcCmfwMzmJLnRrqBRlmmoxk/edit?usp=sharing
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will treat the allocation of DataCap as a separate project and use project management tools for phase management, process oversight, and goal achievement.
Inner our organization
a.First of all, we will organize the related work of the Notary internally and form a work manual. It should include who should be involved in the project and what links they are responsible for respectively.
b.Secondly, we will authorize a trusted colleague within the project to manage the overall project. For this project, we will also issue a letter of authorization, and the colleague who undertakes this work will also sign and confirm the letter of authorization with clear responsibilities and powers, and then he/she will manage the key and complete the final authorization.
c.Finally, we will record the problems we encounter and the solutions in the whole process of the project. If we find good projects, we will recommend them to PL. We will share the above information with our community partners from time to time.
For applicants
a.We will have a tight allocation strategy. However, there will also be a small amount of agility when allocation because it will be good for marketing.
b.Implement a strict KYC process to help us properly identify stakeholders. We may use the following tools;
To query GCR enterprises: https://www.qcc.com/
To query NA enterprise: https://opencorporates.com/
c.Establish communication channels so that we can reconfirm before allocation and conduct supervise.
We believe that we have the ability to protect DataCap and fully ensure that our authorization and delegation to DataCap is compliant and enforceable.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In the early stage, we will focus on the following aspects fof questions. All questions are variable, but the final purpose of communication remains the same. However, as the focus of community governance changes, the purpose of communication and related issues can be changed.
https://docs.google.com/spreadsheets/d/1lYSnBSbtqTokikss_vb8l0_-MtIhCwEx700-DO4gZ6w/edit?usp=sharing
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will confirm whether the client has any illegal ussage of DataCap in following three steps:
1.Ask
Through the question set above, we can know whether the client has any remaining DataCap. If the client answers no, we can continue with other questions or query for confirmation. If the client answers yes, then in principle we will suspend or close the application until their DataCap has been used up.
2.Query
If the client answers no, we will query the previous usage, which should include the following directions:
Whether there are any remaining DataCap (send us the link)
Previous DataCap storage record with link
3.Agree or Refuse
If it is not used properly, it will enter the allocation strategy scoring;
In case of improper use, we will timely take corrective actions, notify relevant Notaries and community personnel about this thing.
```
![image](https://user-images.githubusercontent.com/118235124/201901144-2d5ddf8e-bdff-4ca6-9a3d-c8b75a56da6b.png)

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
We strongly support public disclosure of all allocation decisions and will choose to display online.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
1.All user information and final allocation decisions are publicly available on github. In addition, there are many ecological tools that can directly query allocation records.
2.We will also establish a project management form, which will disclose all the projects we have participated in for the convenience of centralized review, and viewers can mark the issues or subjects they think are risky, which can also help us timely control the allocated risks.
Google document link:https://docs.google.com/spreadsheets/d/1ILgo0hsDJ4qLKHLCJxQtj8sNtiFZAPRuph_6T1Grrs4/edit?usp=sharing
3.We will open our email as a communication channel, and if somebody has questions about our allocation or client, we will immediately start self-examination, invite the community management team to intervene in the investigation/audit process, and finally give the results to prevent the occurrence of mistakes or put an end to some mistakes.
4.The following is our process for the overall audit. As shown in the flow chart, for each audit request, we will go into a process to ensure that the problem is fully disclosed. If the problem is serious, we will terminate the project.
```
![image](https://user-images.githubusercontent.com/118235124/201901219-5c48eaef-c43e-42d4-8d9e-1facb381c51e.png)

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
We are guaranteed to work at the L4 level.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None
```

**Comment by Kevin-FF-USA** [comment]
Hi @Holiday507,
Thanks for applying to become a Notary in the Fil+ program!

As we score your application, you will need to verify your contact information and affiliated organization. Since you are applying on behalf of an organization, please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from your Organizations email account.
*This cannot be from your personal account. You Must include the address of your Organization.

Subject Line: Notary Name, Application Number
Email Body:

Your First and Last name
Your Organization
Your Country of Operation
Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
Link to this GitHub application

This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[752.pdf](https://github.com/filecoin-project/notary-governance/files/10159535/752.pdf)

**Comment by Holiday507** [comment]
### **Allocation Strategy**

We want to further refine the key points of our allocation strategy, which help us to conduct authenticity checks on our clients and allow them to obtain DC under fair rules.

**1. We have a scoring mechanism for how we allocate;**
<img width="1539" alt="png" src="https://user-images.githubusercontent.com/82493512/206909174-990c8056-641c-4be5-89d1-f3af97ef185d.png">

**2. We've made a strict KYC process to help us to correctly identify stakeholders.**
- Inquire GCR enterprise: https://www.qcc.com/; Query NA enterprise: https://opencorporates.com/
- Verification of the clients' official email address is used to ensure the actual control of the applicant and the subject of the application;
- We will advise clients to inform us of common local channels (such as wechat and slack) for later follow-up;
- If the client has obtained DC before, we will inquire storage records to ensure compliance;

**3. We'll be self-disciplined.**
**3.1 Transparency and Justice**
- We are open to applications from all regions, data categories and indentites.
- We don't allocate DC when clients still have.
- No more than 30% of DC will be allocated to the same client.
- All allocations are fully disclosed and recorded.
**3.2 Allocation efficiency**
- We'll complete the reply and inquiry of the Issue within 2 working days.
- We'll actively cooperate with the allocation and participation of LDN or other ecological projects.
- We expect to complete 80% of the DC allocation before the next round of notary election.

**Comment by Holiday507** [comment]
### **Client Due Diligence**
1. We have different query tools according to different countries, such as https://www.qcc.com/ for GCR enterprises [https://opencorporates.com/](https://opencorporates.com/,) for NA enterprise. All of these can help us understand whether there is a risk.
2. We'll also ask clients to provide the qualification materials issued by the relevant government or business section for their subject to confirm the nature of the subject. At the same time, we may require the applicant to provide authorization documents to ensure that the applicant has obtained the subject authorization;
3. For those who have obtained DC before, we'll verify their storage status through the dashboard tool such as https://filplus.d.interplanetary.one/. If there is no compliance, we would point it out and delay allocation, until they put forward the improvement plan.

**Comment by Holiday507** [comment]
### **Bookkeeping Plan**
We plan to open other google files in addition to google forms, so that auditors can retrieve all the information of relevant subjects and data samples at any time. In this way, we can complete records internally and provide search or query externally, which also helps our work to be completely transparent and public so as to respond to audit at any time. If community member have questions about our allocation, we will respond to it on github or slack within 3 working days.

**Comment by Holiday507** [comment]
This is the explanation and supplement to the information provided before. Please have a look,thanks. @galen-mcandrew

**Comment by Kevin-FF-USA** [comment]
@Holiday507 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by Holiday507** [comment]
@Kevin-FF-USA Hi Kevin, I have finished the form, and we have changed the address to: f1sa3dp3a7fwirrsxjdthvzneo7rnjcrrfllsnjpq ，Please check, thank you.

**Comment by panges2** [comment]
Hi @Holiday507, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by panges2** [comment]
Hi @Holiday507,  this is another reminder to get your ledger verified as soon as possible. Thank you!

**Comment by Holiday507** [comment]
@panges2 Thank you for reminding me. I tried but failed. I don't know the reasons.

**Comment by Holiday507** [comment]
![image](https://user-images.githubusercontent.com/82493512/219936528-7d712b32-932f-48da-b2b7-0134069a4c64.png)
![image](https://user-images.githubusercontent.com/82493512/219936535-97ba1846-3c7d-4411-a3f9-36c914c3da19.png)
The process loops through these two pages @panges2

**Comment by Holiday507** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec6wuzku2wdmona2icrbrupdt54jy2urrobmqfyrvhcwo2qcvrhpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6wuzku2wdmona2icrbrupdt54jy2urrobmqfyrvhcwo2qcvrhpy
