### ISSUE TITLE
Notary Application:  ZTLC PTE LTD

### ISSUE THREAD

**Issue by Arockpoolztlc** [filecoin-project/notary-governance#753]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:Arockpool
- Affiliated organization: ZTLC PTE LTD
- On-chain address to be notarized (recommend using a new address):f1cvytxoywr4bfixwknqhd2sfdfhxdynox63hyyja
- Country of Operation: SINGAPORE
- Region of Operation: Asia minus GCR
- Use case(s) to be supported: Professional Services
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?:  Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
We are a tech company mainly focusing on providing web3.0 infra, including filecoin explorer, wallet, data api and other toolkits. https://github.com/filecoin-project/devgrants/issues/817
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
None
```

How did you acquire the FIL cited above?
```
None
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
The existing block explorer, arockpool.com, was created by our team, and it has been operational ever since it went up one year ago. It makes use of Python 3 and the microservice architecture, using flask and mongo to offer on-chain data services, and redis and kafka as message and cache middleware. For its data service and profit/trend calculator, the mining industry attracted the majority of users. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
We have re-evaluated the existing platform structure in light of the impending Filecoin Virtual Machine (FVM) upgrade, which will significantly increase filecoin agility and usability. We intend to add modern explorer features like testnet support, graphQL data API, RPC endpoint service, data dashboard refactoring, and smart contract verification & decompiler integration to make the platform more developer and community friendly.
https://github.com/filecoin-project/devgrants/issues/817
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Organization: ZTLC PTE. LTD. 
Nature: Private company
Registration Country: SINGAPORE 
Established: 21 Mar 2013
Size: 20-30 staffs
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://www.arockpool.com/en
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://medium.com/@Arockpool/about
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
None
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
None
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We will consider the following factors while allocation the DataCap:
1.Basic customer information and industry reputation
2.Binding relationship between customer and mining machine
3.Use cases diversity
4.Scale&Frequency of allocation
5.Safety Precautions

At the same time, we will verify the authenticity of customers and the data validity through the offline audit. Conduct spot check once a month and general survey every quarter to grasp the basic information and update customers' progress in time, and then change the allocation proportion according to the investigation.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will strictly implement the allocation strategy and conduct a detailed investigation of the customer's information. For the clients who apply, we will make a file and score each client. We will distribute according to the score. It is worth noting that we will update the archives regularly. For clients who are progressing, they deserve more attention. We hope to build a healthy system in which people can make continuous progress and welcome more and more people to participate.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Customer Information and purpose of application is one of the important criteria for our audit. We conduct in-depth research on customer information and ask about the purpose of application, so that we can understand the real demand of customers and avoid the subsequent risk.

1.Research company entity information

Anyway Basic information: Company registration qualification/Business license/Information certificate, etc
Additional information: Certificate of Honor/Computer software copyright, etc

2.Investigate the company

Principal business/Product introduction/Other business
Fiscal Annual financial statement/Asset management statement

3.Signing cooperation agreements

The application form is signed and sealed by the legal person or responsible person
Submit a copy of the company's business license, etc.


We will ask the following questions:

What type of data do you want to store and for what purpose?

What are your plans for the number of miners to store the data, the area, and the assigned number of miners per miner?

What safety precautions do you have?

Do you comply with local laws and regulations and accept the miners term of service?

We regularly spot-check users to see if they are as well as they say.

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. We require customers to disclose their addresses, set up tracking records, and rigorously investigate the customer's stored data

2. We will have a special customer rating database, for low-scoring, poor performance of the customer will be a warning or punishment

3. For storage data diversity, high data authenticity of the customer we will improve the score, and make public praise

4. Finally, we will recruit community volunteers to participate in the monitoring
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
The final decision is made public on Github and notified to each customer in at least three ways. For customers' different opinions, we will set up a two-week publicity period, customers can submit personal suggestions, and we will hold an online meeting to make a final decision.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Github and official website.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None
```

**Comment by panges2** [comment]
Hello @Arockpoolztlc ,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by Kevin-FF-USA** [comment]
Hi @Arockpoolztlc 
We never received an email. Wanted to send a friendly follow up that this step is needed in order to verify your connection to the organization. Failure to reply will result in a decrease in your score and possible non-selection as a Notary.  If you have already replied (and we are overlooking), please paste the time stamp from sent message in this thread.

**Comment by Arockpoolztlc** [comment]
Hi Kevin，

Thanks for your email，
I have send the email on 28th Nov as attached in the screen shot.

Regards，
Pearl

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Kevin-FF-USA** [comment]
@Arockpoolztlc 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
