### ISSUE TITLE
Discussion: Determining how / when more Notaries should be added

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/notary-governance#76]
Several discussions have arisen around how and when we should determine when new Notaries should be added. Given our last elected Notaries have not received DataCap yet, it seems sensible to try and define at what point or triggers would we envision needing to start the process for recruiting more Notaries or enabling existing Notaries to apply for more DataCap.

Specifically, I think it's worth clarifying a few cases: 
1) Should new Notaries be elected per region as a specific region runs low on DataCap?  
2) Under what conditions should we consider expanding the number of notaries per geography? 

Separately, it's might be worth considering what metrics and feedback mechanisms we need to have to foresee a potential need for additional Notaries / DataCap in order to ensure Clients are able to appropriately source and spend DataCap.

**Comment by KaptinLin** [comment]
1) Yes, new notaries be elected per region will make the work more efficiency 
2) more notaries can contribute more. And there should have a elimination mechanism to eliminate the notary who are not participate actively and break the rule.

**Comment by jnthnvctr** [comment]
re (2) maybe its worth re-evaluating the total cap of what Notaries can allocate? Maybe one idea is to max out the allocation amounts at a lower threshold (1PiB? 5PiB?) - and to add more DataCap to a region we add more Notaries.

**Comment by jnthnvctr** [comment]
So speaking with Hidde - I think another potentially important consideration might be to try and define demand forecasting (i.e. solving the problem of running out of DataCap, or not having enough in the system). 

One idea here might be to figure out a way for folks who have a massive amount of data they know they will want to onboard (e.g. Discover, Speedium, I'm sure there are many others) - to get "pre-vetted" by existing Notaries ahead of time - and use that to dictate where additional DataCap should be added. 

I think there might be a few approaches on how this could be solved: 
1) Single purpose projects where a Client states a project they'd like to acquire a large amount of DataCap for (and have Notaries from several geographies independently validate the request etc) - and use that to do a "special" approval for speciifc projects. We'd have to define the process of approval here, as well as how (assuming that request is approved) the DataCap is actually allocated to ensure its done in compliance with the proposal. 

2) Another idea might be to instead use that validation to increase the amount of DataCap available in a region / in total.

**Comment by bary321** [comment]
The main goal of Fil-plus is to promote the Filecoin network to store precious data and promote the Filecoin network to move forward.
 First of all, I think it is correct that each notary has a quota of 100TB, because this can make the network more decentralized rather than monopolistic. 
Secondly, I think the number of notaries can be increased to demonstrate fairness. I believe that every miner working on the Filecoin network has certain real data storage resources. These resources are expensive and should be given more opportunities for miners. 
Finally, Asia is the region with the most miners. In order to better promote the development of the Filecoin network, can the number of notaries be allocated according to the number of miners, rather than just simply by region.

**Comment by jnthnvctr** [comment]
I think it's worth resurfacing this discussion again in the governance call tomorrow. 

1) I think we're seeing a large volume of requests that haven't been responded to - this makes me think we should root cause what is the delay in actioning. If this is a training issue, that's a separate issue (and hopefully we'll see higher throughput shortly). However, if the process of allocating DataCap is quite slow (or its difficult to process applications) - we should revisit what a "reasonable" number of Notaries is. (e.g. if each Notary can only service N number of applications a day, and our rate of inbound requests is M, and M >> N, we're clearly going to need more Notaries). 

2) I think it's worth considering how we can incorporate some sort of demand forecasting. I've heard of a few projects that are going to have known high demand for DataCap for a sustained period of time. Should there be a way of a project just directly proposing to the community that it requires some allocation of DataCap? 

One rough idea I have here: 
1) A Client should be able to file a "special purpose" DataCap allocation request not to a Notary - but in this repo to the Governance process. 
2) In the Governance process, we deliberate collectively on the merits of the use case
3) That DataCap allocation can be granted, and administered by a Notary (to ensure the Client does what they claimed to do). 

By creating this alternative structure, the community could be more involved for large allocations without reducing the available DataCap of the Notaries. From a "limited trust" perspective - it would mean the bar for getting approved is significantly higher.

**Comment by KaptinLin** [comment]
I think that for notaries public should be lenient in entry and strict exit (宽进严出), and the threshold for becoming a notary public should be relaxed, but their behavior should be evaluated. If they do not meet everyone's expectations, then their role as a notary should be withdrawn.

**Comment by NSC-FIL** [comment]
I think all participants concerned about Filecoin+ should review this related issue regarding governance of datacap trading.
https://github.com/filecoin-project/notary-governance/issues/66

**Comment by zixuanzh** [comment]
Some thoughts ahead of our call later today, there might be a few factors that can impact the timing in my opinion.

**1. Community Perception:** There is still a misperception that people become notaries to benefit themselves and false claims about Filecoin Plus that undermine the trust in the community. That’s just not how it works and we should collectively work towards keeping the community well-informed of the program.
**2. Ecosystem Tooling:** Analytics will be key in notary governance. It may take time for tooling to be built. There are folks working on it and maybe we need more building and less bickering.
**3. Operational Guidelines:** There are still some uncertainty and questions in what falls within the norm and what does not. We should perhaps align on these guidelines first.

Before we talk about adding more notaries, maybe we should first diagnose the current DataCap application and allocation pipeline? Are Notaries being too conscious of their actions? Is the community giving them too much pressure? Are clients having a difficult time navigating the DataCap application process? Do we need more office hours with Notaries?

I feel like folks who help make progress on the process or improve on the factors above are natural to become the next set of Notaries (given that they also score well based on the rubric). In addition, I do like the proposal of having more notaries with small amounts of DataCap to start. Those who do a good job get a second term. After all, being a Notary can be tedious and time consuming, especially in the early phase of the network.

**Comment by virgil-file** [comment]
Notaries are similar to the reviewers for academic papers. I think we can refer to the blind review mechanism of papers in academic circles.
1) Develop a certain number of notaries in each field (not less than 10 in each geography), and each field has notaries with different levels of familiarity (for example, L1-expert, L2-knowledgeble, etc).
2) The clients need to specify the field when submitting the certification application, the platform (https://plus.fil.org/) randomly assigns 3-5 notaries in this field according to a certain weight (such as 2 L1 notaries, 3 L2 notaries, etc.). Before all the reviews are completed, the clients will not Know who is the notary in charge of the review.
3) The review is time-limited (such as 72 hours). After all reviews are completed, the review comments can be publicly discussed.
4) The time paid by the notary should not be free, and a certain salary should be paid by the foundation.

**Comment by NSC-FIL** [comment]
I agree with @zixuanzh and particularly point 3.  Guidelines for Notaries and other participants in this program should be clear and well publicized so that our Filecoin community can accept and abide by them for the betterment of network governance, decentralization,and fairness IMO.  Hope we can get to a consensus on the Operational Guidelines soon.

**Comment by Leozhang404** [comment]
Filecoin plus aims to bring more and more real and useful data to the Filecoin network, and notaries are the regulators of useful data. I think the most important is to decide how many datacap should be allocated to the notaries. And the datacap 
 allocated to one notary should be decided by the [Notary Allocation Plan Rubric](https://github.com/filecoin-project/notary-governance/tree/main/notaries/templates).

As @jnthnvctr  said, we should design a feedback mechanisms to calculate the total datacap in current round, and then we rank every applicant according to their score. Finally, RKHs assign each application to the corresponding datacap until the total datacap is coimplete.

So we should convert to foresee the datacap the demand. And when the datacap has been used 90%, we can start a new round allocation(a round of notary application)

**Comment by dkkapur** [comment]
Closing this one out for now. We've gone from elections "as needed" to roughly 2 per year at this moment. I expect that will be the status quo for the time being. Personally - my hope is that with significant improvements to notary tracking and evolution of the notary role itself, we can move away from election events and instead enable people to become notaries on a rolling basis. Those interested in engaging in this - let's do it in a Discussion topic instead. Thank you!
