### ISSUE TITLE
Notary Application: Ghost Byte Inc

### ISSUE THREAD

**Issue by GhostByteInc** [filecoin-project/notary-governance#760]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information

![image](https://user-images.githubusercontent.com/112573663/205354819-805ffff1-e940-4f8d-b3f5-12d9c58a49eb.png)

- Name: Trevor K Smith
- Affiliated organization: Ghost Byte Inc 
- On-chain address to be notarized (recommend using a new address): f1gjuwa45ujqjryxnmhcdjxb4a6ywb3s3c74eunti
- Country of Operation: United States of America
- Region of Operation: North America
- Use case(s) to be supported: Professional Services
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).

```
f01826669
f01883179
f01910202
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).

```
75k
```

How did you acquire the FIL cited above?

```
Purchase and Loans

```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 

```
I have been part of the filecoin community since late october last year, a little over a year. I attended the second and fourth ESPA events, as well as FIL Austin. I have worked with seagate to help kickstart a filecoin hardware leasing program - https://www.seagate.com/products/storage/data-storage-systems/leasing/ - with a related video shared on the page - https://www.youtube.com/watch?v=6PejYUlN0AM&t=1s - helping to reach new audiences. I am active in the filecoin slack channel, assisting people free of charge in deploying and troubleshooting issues. My slack, `Trevor K Smith - Ghost Byte` can be searched in the channels. I was among the first to deploy and test boostd even before the first stable release. I was among the first to run saturn nodes, currently coming in with the top weighed score.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 

```
NA
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
1 Employee, me. Ghost Byte Inc. United States of America, Maryland.  October 2021.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://ghostbyte.io
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
(https://www.youtube.com/watch?v=6PejYUlN0AM&t=1s)
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://www.linkedin.com/in/trevorksmith/

I otherwise do not have social media profiles. I do not aspire to be a content creator.
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://www.youtube.com/watch?v=6PejYUlN0AM&t=1s
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The amount and rate per client will be dependent upon the application, its requirements, and level of legitimacy or track record. Regardless, all communication and transactions will be recorded and available publicly. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Ledge, offline transactions.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
I will conduct full audit on the application. I will confirm website, date the domain was registered, scan the internet for similar code of the applicants website to make sure its has not been cloned via htrack and set up as a front for datacap. I will ensure the samples of applications are true and legitimate, not web scraped data to form a dataset. I will confirm DNS entries of the application website to make sure proper email entires are in place to prevent spoofing of email addresses to bypass email verification of root domains. I will request email verification of the client.

I will confirm the applicant has the knowledge to use the datacap and issue it responsibly. I can assist as needed and help guide the applicant to success. 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
I will do research on their past datacap tranches and ensure they have been splitting allocations up upon a wide amount of SP's. I will ensure that all data is retrievable from all applicants.I will ensure the the SPs they have been allocating to is not affiliated with themselves, or other past notaries that approved their previous applications on trenches.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
I plan to keep all decisions in a public accessible place, such as github. I will only communicate privately if required by the applicant for security reasons, in which all communication will be documented for future reference upon request or investigation.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
 I can host on a publicly available google sheet, unless more specific requirements are needed.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L5. I can be as active as possible. I work in filecoin full time, and i can this as a additional role to my daily tasks.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No, first time applying.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No, no relationship to this extent. 
```

**Comment by panges2** [comment]
Hello @GhostByteInc,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Trevor-K-Smith** [comment]
> 

Sent

**Comment by Trevor-K-Smith** [comment]
@Kevin-FF-USA @panges2 

FYI: I had updated my issue and looks like some of the tags had changed. Unsure if this effects things. Thanks

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[760.pdf](https://github.com/filecoin-project/notary-governance/files/10159547/760.pdf)

**Comment by Kevin-FF-USA** [comment]
@GhostByteInc 

Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @Trevor-K-Smith, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by GhostByteInc** [comment]
Hello, Please let me know if there are any missing steps or actions needed taken on my side, thanks!

**Comment by panges2** [comment]
Hey @GhostByteInc, I wanted to follow up with my previous message about ledger verification

**Comment by GhostByteInc** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceb6vb7q75rd733kweezwvcxkj4uhsptctz24gcyrgqdxugzftovmw
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6vb7q75rd733kweezwvcxkj4uhsptctz24gcyrgqdxugzftovmw

**Comment by Kevin-FF-USA** [comment]
Hi Trevor,

As of this writing the Governance team has still not received
1. A slack message from the accounts you wish to communicate with in the Fil+ channel.  Need you to DM Phil and I in SLACK the Token code for EACH member of your organization in SLACK who can speak on behalf of Ghost Byte.

2. Verify your Ledger in the Registry.  This was covered on the past two Notary class. **Need you to follow the directions in these docs and verify your ledger by 19Feb** or your DataCap will be significantly delayed.

Here if you have any questions,
-Kevin

**Comment by Trevor-K-Smith** [comment]
@Kevin-FF-USA 

Hi Kevin,

On December 2nd 2022, you and Phil received a slack message from me in a group chat with my token code for the slack account to be used on behalf of Ghost Byte. Phil had confirmed receipt with a green check mark. Let me know if any issues, and i can send again. This will be the only account.

Regarding the ledger verification, i had performed once but failed to see a comment land on this issue. Hence why i asked if any additional actions was needed [here](https://github.com/filecoin-project/notary-governance/issues/760#issuecomment-1425333586) (i thought it went through). After seeing paneges2 comment, i repeated the process and this time see a successful comment on this issue [here](https://github.com/filecoin-project/notary-governance/issues/760#issuecomment-1432313894).

At the time of your comment, i believe both requested actions should be complete best to my knowledge. 

Let me know if this is not the case.

Thanks!

--Trevor K Smith
