### ISSUE TITLE
Notary Application: Cabrina Huang

### ISSUE THREAD

**Issue by xingjitansuo** [filecoin-project/notary-governance#763]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Cabrina Huang
- Affiliated organization: self-employed
- On-chain address to be notarized (recommend using a new address): f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
- Country of Operation: Greater China
- Region of Operation:  Greater China Region (GCR)
- Use case(s) to be supported:  web2/ web3  Public Data, Enterprise Data
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Individual

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
1. Participated in Filecoin as Storage Provider since Mainnet 
2. Engaged in Space Race, Slingshot, Slingshot Restore, E-Fil+, V3 Notary
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Mining Reward from f022289, f039940   > 40K 
Slingshot Reward and personal purchase  > 5K 
```

How did you acquire the FIL cited above?
```
Mining Reward, Competition Reward, Personal Purchase from exchange 
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
1. Engaged in Space Race, Slingshot, and SlingshotRestore. 
2. Onboarded over 10PiB FIl+ deals to network and worked with over 60 SPs from NA, Europe, Australia, and Asia. See more information at http://www.dstorage.cabrina.xyz/
3. V3 Notary and helped multiple clients with Fil+ applications. 
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
1. Due Diligence on FIL+ clients. 
2. Discussions on community proposals 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Does not apply. My interaction with Filecoin so far is personal behavior.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Linkedin: https://www.linkedin.com/in/cabrina-h-b392bb109/
Personal Deal-onboarding and tracking website [WIP]:   http://www.dstorage.cabrina.xyz/
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
N/A
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://www.linkedin.com/in/cabrina-h-b392bb109/
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
N/A

```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
My allocation goal is to ensure I grant eligible clients the appropriate amount of DataCap and with smooth onboard into Filecoin. Authenticity,  allocation fairness, client's correct usage of DataCap are the key. 

Authenticity :
1. Verify the client's basic information, including operation's registration of place and time, Business license, operation size, and industry reputation. 
2. Investigate the total amount of requested data, data type, the previous storage method, and whether it is open public or encrypted. 

Allocation fairness:
1. I am open to reviewing the application from all the regions and various data types. 
2. I will not allocate more than 30% of DatCap to the same client. 

Client usage of DataCap: 
Make sure the client has a clear, feasible plan on data generation, ways of deal-making, and SP selection from a big pool. 
If it is not the client's first-time allocation, I will refer to the client's previous DataCap consumption and ensure the deal-making is not heavily made to few SP. I will also randomly retrieve the deal to confirm the requested data is stored into Filecoin. 

Allocation Speed:
I plan to allocate 50% of DataCap within half a year. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A ledger that can only be accessible by me.

```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1. Ask the client to provide the fundamental introduction to the business entity, including but not limited to the operation size, operation year, registration country, operation regions, reputation in its industry, Business License, and any social media page. 
2. Explain the relationship between the Datacap Requester and the Business.   
3. Describe the type of the data, and provide a sample. 
4. Elaborate on the plan to onboard into Filecoin. Familiarity with deal sending?  Do you send online deal or offline deal?  Any tools you plan to use to prepare the data?  How do you find the SPs? How do you allocate your DataCap among SPs? How many copies do you intend to store?  Which geo-location will you onboard the data? 
5. Do you run an SP on your own?  If so, what percentage you plan to store yourself. 
6. Plan to avoid the DataCap waste. 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Check client address on https://filplus.d.interplanetary.one/ to make sure the usage of DataCap is not heavily used in one SP. 

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, I will document the supporting details on the decisions I make with each client in public through Github. 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
A public Google Sheet that can be easily viewed by others. 
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
yes, please refer to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=xingjitansuo
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
Not for now, but will update the list if I establish the business with others. 
```

**Comment by xingjitansuo** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaced52hec5zqikyid5mhoybeabj4rd65jslf3dqux6lt23q32xjs3mg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced52hec5zqikyid5mhoybeabj4rd65jslf3dqux6lt23q32xjs3mg

**Comment by panges2** [comment]
Hello @xingjitansuo,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Please email NOTARYELECTION@FIL.ORG from the email account linked to this GitHub account. *The email MUST COME from the same GitHub account you used in this application.

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[763.pdf](https://github.com/filecoin-project/notary-governance/files/10159549/763.pdf)

**Comment by Kevin-FF-USA** [comment]
@xingjitansuo 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by xingjitansuo** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceasmwhpbggwgjp7kxxvgloc6yqv6ntwfb4ubg37pistcxymazbfi6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasmwhpbggwgjp7kxxvgloc6yqv6ntwfb4ubg37pistcxymazbfi6

**Comment by xingjitansuo** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedswmoaex3desopjae6xy7x75qtgeb6m4d4oscbvbthqeqoolp2ns
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedswmoaex3desopjae6xy7x75qtgeb6m4d4oscbvbthqeqoolp2ns

**Comment by xingjitansuo** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceck5z5tlcogegusggjdmdplnlbfotcd44butp4phiu3vxaomtqqnk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceck5z5tlcogegusggjdmdplnlbfotcd44butp4phiu3vxaomtqqnk

**Comment by xingjitansuo** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceb44l2a423frq7hkpzsv7gktxfysfvwlqai63gpp5owlneequ3pnk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb44l2a423frq7hkpzsv7gktxfysfvwlqai63gpp5owlneequ3pnk

**Comment by xingjitansuo** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceb2bt63sgahm5sl73boa4qkrqwqt4n63ffzxfdojjc3fyjjivupx6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2bt63sgahm5sl73boa4qkrqwqt4n63ffzxfdojjc3fyjjivupx6
