### ISSUE TITLE
Notary Application: STCould

### ISSUE THREAD

**Issue by stcouldlisa** [filecoin-project/notary-governance#764]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: LISA
- Affiliated organization: STCould
- On-chain address to be notarized (recommend using a new address):f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
- Country of Operation: Greater China
- Region of Operation: Greater China Region (GCR) 
- Use case(s) to be supported: Professional Services 、Developer Tools、Decentralized Applications、User Content、Public or Open Data、Media & Entertainment 
- DataCap requested for allocation (10TiB - 1PiB):1PiB
- Are you applying on behalf of yourself or an organization?:  Organization：STCould

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
It has been 7 years since we have been deeply involved with IPFS and Filecoin. 
Since 2015, our team has been following and propagating IPFS.
In October 2017, in order to better promote IPFS and Filecoin in China, we established the IPFS China Community (ipfs.cn). So far, it has more than 100,000 fans.
From 2017 to 2021 based on the original intention of "Propagating for IPFS and Voice for Filecoin", our team successively conducted IPFS and Filecoin themed promoted sermons in Shenzhen, Guangzhou, Beijing, Hangzhou, Hefei, Changsha, Wuhan and so on. 
In 2020, our team actively participated in Filecoin testnet and achieved superior results in Space Race 1 and Space Race 2.
On October 15, 2020, Filecoin mainnet was officially launched. Our node have been operated and maintained smoothly so far, and miner ID: f0688165 has been ranked No. 1 in the Adjusted Power rankings. Also, we provide mining technical support for the mining pools FILPool.me and BPool.io, which is serving Filecoin investors.
Our team has been deeply involved in the storage industry for more than 12 years. We have rich experience in data storage, cluster architecture construction and emergency handling. The storage products we have developed have now cooperated with the multinational giant-China Unicom and served nearly one million people.
We not only have advantages in storage technology, but also are committed to developing the ecological construction of IPFS and Filecoin. To help fans understand IPFS & Filecoin faster, we have created the IPFS China Community (ipfs.cn). In order to help teams with ideas to develop the ecology, we have established the IPFS Ecological Fund for investing in applications that are beneficial to the ecology. According to the economic model of filecoin, in order to increase the liquidity of filecoin, we participated in the investment and incubation of the Defil platform.
Links：
Telegram: https://t.me/ipfscn2018
Miner ID: f0688165/f0127595
website:https://yunos.io/
BPool: https://bpool.io/
Promotional activities: 
https://drive.google.com/file/d/1xQDkNcckyinYfkLuOCWF2med4dTfAHzR/view?usp=sharing
https://v.qq.com/x/page/s3219a9ooi1.html
Interview: 
https://v.qq.com/x/page/j3017ziwzri.html
https://v.qq.com/x/page/t3219mnjjvt.html
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Total：5,321,670.52 FIL
Currently Available：61,608.25 FIL
Initial Pledge: 4,430,938.85 FIL
Locked Rewards: 828,214.21 FIL
The above data are from the blockchain browser: FILFOX. The miner ID used for statistics is the ID published on the official websites of FILPool and BPool.
Miner ID:  f0123261; f01110844; f0441372; f01260384;f0688165; f0128559; f0724216; f0690736; f02770;  f0127595; f0724216; 
Website:
FILFOX: https://filfox.info/en
website:https://yunos.io/
BPool: https://bpool.io/
```

How did you acquire the FIL cited above?
```
Own and customer invested
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
1. For enthusiasts to understand IPFS & Filecoin faster and better, create an IPFS Chinese community
2. Many community ama has been held in the community to help users better understand its ecology, such as FLow, Polygon, Chainlink, Near, Mask Network, FILSwan, etc.
https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzkyMDIyMTY3Ng==&scene=124&uin=&key=&devicetype=Windows+10+x64&version=6302019c&lang=zh_CN&a8scene=7&fontgear=2
3. Increase liquidity for Filecoin, invest and incubate DEFIL platform: https://defil.org/#/home
4. In order to incubate its ecological development and provide financial support, the IPFS&Filecoin ecological fund was established:  http://dongxicaijing.com/portal.php?mod=view&aid=928
4. Investment incubation filecoin wallet: Filwallet.io
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Our team have discovered some errors in the past two years and actively submitted feedback.
Such as:
WindowPost not submitted, but the power was not drop:
https://github.com/filecoin-project/lotus/issues/1812
Synchronous abnormal:
https://github.com/filecoin-project/lotus/issues/1833
The expiration of a user order can cause a contract error:
https://github.com/filecoin-project/lotus/issues/1929
Uneven distribution of sectors in the deadline in windowPost:
https://github.com/filecoin-project/lotus/issues/1813
In addition, our team participated in two chain maintenance and assisted the PL to perform multiple upgrades, and we assist the official to solve the following problems in the slack private channel:
1. User order blocking problem
2. Gas fees in the test network skyrocket 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
STCloud is headquartered in Shenzhen, China. STCloud is a high-tech company focusing on the research and development of distributed storage, distributed computing, and distributed database technology. It invests in and incubates sub-brands such as "IPFS China Community", "FILPool Mining Pool", and "Spider Mining Machine". Filecoin mining machine research and development, mine construction, mining pool development, IPFS ecological investment incubation, distributed network technology research and development, etc., ST cloud committed to becoming the next generation of distributed network operators.
-Registration Country: China
-Organization size: 150+
-website:https://yunos.io/
-Time since establishment: 2018
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Social Media
Slack: LISA
Github：stcouldlisa
website:https://yunos.io/
jinse:https://m.jinse.com/homepage/150033

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://v.qq.com/x/page/j3017ziwzri.html
https://v.qq.com/x/page/t3219mnjjvt.html
https://www.zhihu.com/zvideo/1372140005117251584
https://zhuanlan.zhihu.com/p/366661395
https://mp.weixin.qq.com/s/JRNPbmgmJFXUHnt1g7tlMw 

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
slack: LISA
github：stcouldlisa

```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
My English name is lisa, and my Chinese pen name is Fat Xiaozeng. I graduated from Tsinghua University. My specialty is writing articles. I have written a lot of articles for Filecoin, including in 2021, when FVM was still just an Juan proposed FIP, and I wrote the content of FVM. At the same time, we are also the first author in China to write about the storage relationship between IPFS and NFT, and promote popular NFTs such as KAKANFT to store data on the IPFS network. In China, I am A KOL of IPFS & Filecoin.

https://mp.weixin.qq.com/s/dZJVUaHi-w5hm_v3nuqliA
https://mp.weixin.qq.com/s/EHe09lbe9UkoZtCWHlt9gQ
https://mp.weixin.qq.com/s/iUI8Sp09MKdzjNB3yCBL-Q
https://mp.weixin.qq.com/s/7MV4942K1Ltbbin32QNDIQ


```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
To be more specific, I will set a specific ratio based on the actual situation and the development of the network, and I will also refer to Filecoin Discover, such as:
1. User content (individual user storage)
2. Scientific data (artificial intelligence training, geological data, autonomous driving)
3. Media and Entertainment (Video and Music)
4. Historical data (weather, books)unts

First of all, the allocation requirement is planned to be divided into 5 categories from L1-L5 by the data volume. The larger data volume clients request, the more strict requirements will be. We want to inspect these clients by reputation, data, diversity and decentralization, allocation strategies, track record, etc.
We will consider the following factors while allocation the DataCap:
1. Reputation of the organization
2. Use cases diversity
3. Scale&Frequency of allocation
4. Safety Precautions
5. Transparency of customers
6. The relationship between customer and miner
In addition, we will also conduct offline investigations to understand their true identity, work content, reputation, etc., and how they use Filecoin for storage. We even plan to conduct a comprehensive review and evaluation of customers reputation every three months, and Reserve the right to adjust the customer's quota to ensure that the share can be fully allocated to the greatest extent.
Customers are rated through the above methods and the quota is allocated as follows:
L1-50 GiB
L2-500 GiB
L3-1 TiB
L4-10TiB
L5-100TiB
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
As a v3 notary, we purchased a ledger wallet whose private key is known only to me and the CTO, so we can be sure that our rights will not be abused
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Generally, the higher the DataCap threshold, the greater the limit for client review. In the early stages, all customers must go through a rigorous process to qualify. First, we will collect relevant information about customers.
1. Entity Information
1.1 Formation documents , this includes certificates of registration/incorporation/information; 
1.2 government-issued identification number for the entity
2. Authorized Signatory Information
2.1 evidence of the authorized signatory’s authority to act on behalf of the application entity 
2.2 Sign and press fingerprints (official seal and corporate seal are required)
2.3 ID card and a photo of the individual and ID card to prove it is the person;
3. Company operation direction and turnover
3.1 Company goals, company's main business
3.2 Annual turnover in the last two years
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. The number of miners allocated to the datacap of each level of customer from L1 to L5 is required.
2. Set up customer tracking records to prevent customers from making wrong assignments.
3. Regularly check and audit the usage of DataCap.
4. Use incentives: encourage customers to report unfair distribution and listen to the voices from the community.
According to the amount obtained by the customer, we require the customer to decentralize the allocation of DataCap. For example, the L1 level can be allocated to only one miner, but the L5 level must be allocated to at least 5 miners, because the more dispersed the DataCap, the more beneficial it is to reduce the potential The possibility of misuse is also conducive to a more decentralized network and reduce the possibility of centralized power.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we will keep detailed records for review requests, and the records will be published on Github.
In addition, we allow the community to provide different opinions and report, and there will be a 14 working day publicity period for DataCap customer allocation. If there is a dispute, we will consider holding a hearing to make another decision.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Github、slack、email. Regardless of the channel, we will keep the content of communication with customers permanently, and we even consider developing a system to better integrate all communication records with customers
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L5
We participate in every FIL+ and E-FIL+ meeting, actively follow the news on slack, we also pay attention to FIP, and express our views on some FIPs.
After conducting background checks, we signed many LDNs in the community, helping customers store DCs on the Filecoin network.
In total, we spend over 15 hours per week on the Filecoin network. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes,   https://github.com/filecoin-project/notary-governance/issues/429
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
We invested in IPFSCN, but IPFSCN is currently operating as a completely independent entity.
```

**Comment by stcouldlisa** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceawwapdzmaq44xodgwodybczff72h2jaddjbmqveztdwujot3go7g
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawwapdzmaq44xodgwodybczff72h2jaddjbmqveztdwujot3go7g

**Comment by stcouldlisa** [comment]
Hi，@panges2 @Kevin-FF-USA ,the eamil has been send，thanks for viewing

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by stcouldlisa** [comment]
@raghavrmadya  Hello, what information  need to provide? We can cooperate. We have sent the email, please check it

**Comment by stcouldlisa** [comment]
<img width="480" alt="WX20221202-143735@2x" src="https://user-images.githubusercontent.com/112812896/205230949-bbae88fe-791b-431b-978e-0feff4a1e2af.png">

**Comment by stcouldlisa** [comment]
We sent an email on November 25th, but we did not receive your email, is there something I missed

**Comment by stcouldlisa** [comment]
https://docs.qq.com/sheet/DWEtLeGlmTXJ6QVhs?tab=9foxcn

**Comment by stcouldlisa** [comment]
We provide more audit criteria for customers, please check

**Comment by stcouldlisa** [comment]
<img width="1138" alt="WX20221203-235510@2x" src="https://user-images.githubusercontent.com/112812896/205449994-a7412d23-7591-4ac8-90c7-d19efc5b0f57.png">

**Comment by stcouldlisa** [comment]
We invested in Fenbushi Capital，We invested in Fenbushi Capital，

**Comment by stcouldlisa** [comment]
We invested in Fenbushi Capital，We hosted the Boao Forum blockchain sub-forum

**Comment by stcouldlisa** [comment]
![WechatIMG553](https://user-images.githubusercontent.com/112812896/205559090-32979011-e197-4f37-bfdc-e32fc9bec343.jpeg)

**Comment by stcouldlisa** [comment]
<img width="286" alt="WX20221205-135820@2x" src="https://user-images.githubusercontent.com/112812896/205560909-4ae6ad2b-927b-47bb-9a56-6c7782150a07.png">

**Comment by stcouldlisa** [comment]
<img width="286" alt="WX20221205-135820@2x" src="https://user-images.githubusercontent.com/112812896/205561816-e8563436-95bb-4a3d-a5ae-34e82f954ef9.png">

**Comment by stcouldlisa** [comment]
<img width="437" alt="WX20221205-140907@2x" src="https://user-images.githubusercontent.com/112812896/205561863-283ec17a-9412-4ab9-8d88-95104080eb24.png">

**Comment by stcouldlisa** [comment]
<img width="351" alt="WX20221205-141007@2x" src="https://user-images.githubusercontent.com/112812896/205561986-38dc0d3a-5cf0-43e5-a2d3-e57c127fdbe1.png">

**Comment by stcouldlisa** [comment]
<img width="443" alt="WX20221205-141317@2x" src="https://user-images.githubusercontent.com/112812896/205562254-226e01cc-ae77-402a-86c1-c76d04535885.png">

**Comment by stcouldlisa** [comment]
The Boao Forum was initiated by 25 Asian countries and Australia (increased to 28 in 2006). It was announced on February 27, 2001 in Boao Town, at the mouth of the Wanquan River in Qionghai City, Hainan Province, China. At that time, programmatic documents such as the Declaration and the Guiding Principles of the Charter were adopted. The Forum is a non-official, non-profit, regular, fixed-site international organization that provides a high-level dialogue platform for governments, enterprises, experts and scholars to discuss economic, social, environmental and other related issues.

In 2020, through our efforts, the Boao Forum opened the first blockchain sub-forum, and stcould is the exclusive organizer.

We listed Filecoin as a roundtable dialogue in the blockchain sub-forum, and we introduced the significance of filecoin as the storage infrastructure of web3 to people from all walks of life such as politics and business.

**Comment by stcouldlisa** [comment]
We have invested in Luckyhash (https://luckyhash.com/). Luckyhash has been established for 2 years. It is committed to promoting and popularizing Filecoin on a global scale. Its customers cover 5 continents. Luckyhash has served nearly 35,000 customers. Among them, https://t.me/luckyhashgroup has 9046 members.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[764.pdf](https://github.com/filecoin-project/notary-governance/files/10159550/764.pdf)

**Comment by stcouldlisa** [comment]
Since 2015, we have been paying attention to the distributed storage technology brought by IPFS. In 2017, we came into contact with Filecoin. Our team was excited by Filecoin. Therefore, in October 2017, in order to let more people know about IPFS And Filecoin, we established the IPFS China community, and held IPFS&Filecoin conferences in 30 cities in China, as well as Vietnam, Singapore, etc. So far, the IPFS China community has more than 100,000 fans.
In 2018, we registered and established stcould (official website: https://yunos.io/) in China, and began to study Filecoin technology in depth. Since our technical director Vinenten has been engaged in the storage industry for more than 12 years (the storage products we have developed are now Cooperate with the multinational giant China Unicom, serving nearly one million people). Therefore, since the launch of the Filecoin testnet in 2019, we have actively participated in every round of the testnet, and basically ranked among the top three in the entire network.
In 2020, our team actively participated in the Filecoin test network and achieved excellent results in Space Race 1 and Space Race 2. On October 15, 2020, the Filecoin mainnet was officially launched. Our SP (f0688165) is #1 in the adjusted hashrate ranking. For a long time, stcould's computing power has been ranked among the top three in the entire network. Here are some of our nodes: f01173170, f0688165, f01108594, f0123261
In 2021, we established the IPFS Ecological Fund and invested in many Filecoin ecological projects, such as Fenbushi Capital (notary), IPFS Chinese Information Network (video media, explaining 3-5 videos for IPFS and Filecoin in the form of videos every day) , with more than 6,000 readings per article), Wanganxin, luckyhash (a filecoin company established in North America, we invested 5.5 million US dollars).
We have won many honors, among which we are the vice president of the Distributed Storage Branch of the China Association for the Promotion of Private Science and Technology.

**Comment by stcouldlisa** [comment]
Since 2015, we have been paying attention to the distributed storage technology brought by IPFS. In 2017, we came into contact with Filecoin. Our team was excited by Filecoin. Therefore, in October 2017, in order to let more people know about IPFS And Filecoin, we established the IPFS China community, and held IPFS&Filecoin conferences in 30 cities in China, as well as Vietnam, Singapore, etc. So far, the IPFS China community has more than 100,000 fans.

In 2018, we registered and established stcould (official website: https://yunos.io/) in China, and began to study Filecoin technology in depth. Since our technical director Vinenten has been engaged in the storage industry for more than 12 years (the storage products we have developed are now Cooperate with the multinational giant China Unicom, serving nearly one million people). Therefore, since the launch of the Filecoin testnet in 2019, we have actively participated in every round of the testnet, and basically ranked among the top three in the entire network.

In 2020, our team actively participated in the Filecoin test network and achieved excellent results in Space Race 1 and Space Race 2. On October 15, 2020, the Filecoin mainnet was officially launched. Our SP (f0688165) is #1 in the adjusted hashrate ranking. For a long time, stcould's computing power has been ranked among the top three in the entire network. Here are some of our nodes: f01173170, f0688165, f01108594, f0123261.At the same time, we are the first SP in the world to use 64GB sectors.

In 2021, we established the IPFS Ecological Fund and invested in many Filecoin ecological projects, such as Fenbushi Capital (notary), IPFS Chinese Information Network (video media, explaining 3-5 videos for IPFS and Filecoin in the form of videos every day) , with more than 6,000 readings per article), Wanganxin, luckyhash (a filecoin company established in North America, we invested 5.5 million US dollars).

We are deeply involved in Filecoin, and at the same time, we have also won many honors. For example, we are the vice president unit of the Distributed Storage Branch of the China Private Technology Promotion Association. Moreover, we are the only company in the world that has won the sponsorship of the Boao Forum's blockchain sub-forum. We listed Filecoin as a roundtable dialogue, and introduced the significance of Filecoin as a web3 storage infrastructure to people from all walks of life including politics and business.

**Comment by stcouldlisa** [comment]
<img width="745" alt="WX20221207-181118@2x" src="https://user-images.githubusercontent.com/112812896/206151181-32bd7679-0146-4e11-8877-bddcbe30cb03.png">

**Comment by stcouldlisa** [comment]
![图片4](https://user-images.githubusercontent.com/112812896/206152087-b854e08f-7ab8-4820-9a80-af76fc98d876.png)
![图片1](https://user-images.githubusercontent.com/112812896/206152141-f03766bf-aed5-4ce2-aeb2-5fe072982850.png)
![图片5](https://user-images.githubusercontent.com/112812896/206152229-549b25cd-853a-4795-ad71-77403c61051f.png)

**Comment by stcouldlisa** [comment]
![图片1](https://user-images.githubusercontent.com/112812896/206152371-19cdc181-5efc-4bea-a575-3663a43ca46c.png)

**Comment by stcouldlisa** [comment]
![图片5](https://user-images.githubusercontent.com/112812896/206155542-64871c98-1731-4943-9dd7-f75ebc23ed8f.png)

**Comment by stcouldlisa** [comment]
This is luckyhash (https://luckyhash.com/) located in North America. We have invested 5.5 million US dollars, and Luckyhash customers are located on five continents. Luckyhash has served almost 35,000 customers. Among them, https://t.me/luckyhashgroup has 9046 members.

**Comment by stcouldlisa** [comment]
<img width="1022" alt="WX20221207-183554@2x" src="https://user-images.githubusercontent.com/112812896/206156836-43faa7eb-42f1-4e87-b67b-556c938bd027.png">

**Comment by Kevin-FF-USA** [comment]
@stcouldlisa 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by stcouldlisa** [comment]
@Kevin-FF-USA We have filled out the form, please check

**Comment by galen-mcandrew** [comment]
Did the organization change names from STCloud to STCould? or is this a series of typos?

**Comment by galen-mcandrew** [comment]
https://github.com/filecoin-project/notary-governance/issues/429

**Comment by stcouldlisa** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebpco7sxqawm4ulunq2efqt6ppi2cojtrrzdp5x2ta34rlieusj3m
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpco7sxqawm4ulunq2efqt6ppi2cojtrrzdp5x2ta34rlieusj3m

**Comment by stcouldlisa** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec5u5flr65g75kle3zeps3lwntq7qbbco3qio6to3jrw4atcw5n22
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5u5flr65g75kle3zeps3lwntq7qbbco3qio6to3jrw4atcw5n22

**Comment by stcouldlisa** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacea6vba3ibv2gxz5xpgabo3s4b6qsgjzddfq5l64rrj7o3lnxphmf2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea6vba3ibv2gxz5xpgabo3s4b6qsgjzddfq5l64rrj7o3lnxphmf2

**Comment by stcouldlisa** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebgfummgecxlhaynpdxysqmltgh6i2tz2fvmyizjy2ue26hbtocsi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgfummgecxlhaynpdxysqmltgh6i2tz2fvmyizjy2ue26hbtocsi

**Comment by stcouldlisa** [comment]
> 该组织是否已将名称从 STCloud 更改为 STCould ？或者这是一系列错别字？

It's just a typo. Sorry, cloud and could look too similar. Sometimes I type too fast, resulting in the wrong order. @galen-mcandrew
