### ISSUE TITLE
Notary Application：POW POWER

### ISSUE THREAD

**Issue by powpower2022** [filecoin-project/notary-governance#765]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Jackson
- Affiliated organization: POW POWER
- On-chain address to be notarized (recommend using a new address): f1u2c7dpdqmlfk5zknafigcycrpzltcjd6nmjnuia
- Country of Operation: GCR
- Region of Operation: GCR
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 1PiB): 1P
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
POW POWER has been promoting the Filecoin to users in the blockchain industry in the form of evangelists and media.
On July 3, 2020, POW POWER hosted the world's first 1,000-person IPFS ecological theme summit - "2020 IPFS Ecology and Decentralized Storage Industry Summit" in Hangzhou, China, with over 200,000 offline participants and online participation. At the same time, the summit invited institutions such as Protocol Labs, Amazon Cloud, Alibaba Cloud, and JD Cloud to participate. This summit further expanded the popularity of Filecoin in the blockchain industry and attracted a large number of industry practitioners Learn about the Filecoin network.
https://play.yunxi.tv/livestream/flash?id=e1eecab932304450b9e332502dbbf490#/
https://www.huodongxing.com/go/2548714732600
In April 2021, POW POWER held 1,000-person summit in Chengdu, China - "Data Royal Future - 2021 Data and Storage Industry Summit". The number of offline participants of the summit exceeded 3,000, and the number of online participants exceeded 100,000. At the same time, the summit invited Dozens of institutions such as distributed storage track institutions and data service providers participated. The publicity of the Filecoin network at this summit was further expanded.
https://www.huodongxing.com/event/5592487124100
POW POWER has held more than 10 online summits, AMAs, offline salons and other activities for Filecoin.
https://www.huodongxing.com/go/8556390175400
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
N/A
```

How did you acquire the FIL cited above?
```
N/A
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
POW POWER, a well-known media in the blockchain industry, reports real-time industry news and regularly holds industry summits, etc. Regularly update Filecoin's official news and project progress.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
Publicity for Filecoin&IPFS
https://mp.weixin.qq.com/s/C8sVvUX9mjUHyYaQQ31phw
https://mp.weixin.qq.com/s/CKQBC0C73JfLU-Fp7lzN6A
https://mp.weixin.qq.com/s/DdRRRvtlsJtCezxJbjEz5w
https://weibo.com/ttarticle/x/m/show/id/2309404618332409299098?_wb_client_=1
https://weibo.com/ttarticle/x/m/show/id/2309404616453893783653?_wb_client_=1
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
POW POWER, located in CBD center of Hangzhou, China, is a global service platform across project incubation, Blockchain news report, Blockchain product R&D, industry sharings (exhibition/ conference/ live broadcasting/ forum...) , ecosystem construction, etc..

Attracted by Web 3.0 style of storage, POW POWER get involved in IPFS & Filecoin since 2018 for promotion, ecosystem construction and R&D of distributed storage related product. Over 100 online & offline sharings on IPFS & Filecoin are held till now.

Following are some relative instances:
1.We have held several IPFS, Filecoin, distributed storage related summits such as the first “IPFS Ecology and Distributed Storage Industry Summit” in July,2020， “Data & Future: 2021 Data and Storage Industry Summit” in April, 2021 and there are over 5,000 visitors for single summit. 
2.During 2019-2020, We have held over 10 nationwide blockchain related POW POWER sharings in many cities such as Beijing, Shanghai, Shenzhen, Chengdu, Hangzhou, etc.. Over 10,000 people have joined the sharings and over 1,000,000 people have viewed related news.
3.In 2020, POW POWER has held over 50 online AMA related to IPFS, Filecoin, distributed storage, in which we invite company leaders, industry KOL,etc. And more than 1,000,000 people have viewed related live streaming.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Twitter: @POWPOWER2020
Facebook: @Pow Power
WeChat: @POW POWER  @POW POWER Official
Weibo:https://weibo.com/u/7444675513
Instagram: @powpower_official
Discord: POW POWER
Email: powpower2020@gmail.com
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://mp.weixin.qq.com/s/C8sVvUX9mjUHyYaQQ31phw
https://mp.weixin.qq.com/s/CKQBC0C73JfLU-Fp7lzN6A
https://mp.weixin.qq.com/s/DdRRRvtlsJtCezxJbjEz5w
https://weibo.com/ttarticle/x/m/show/id/2309404618332409299098?_wb_client_=1
https://weibo.com/ttarticle/x/m/show/id/2309404616453893783653?_wb_client_=1
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
WeChat public account：:POW POWER(Following：5000+)
Telegram:https://t.me/POWPOWERGlobal(Following：5000+)
Twitter: @POWPOWER2020 (Following：1827)
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
None
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We set detailed rules for the allocation strategy of DataCap, as shown in the following table:
https://docs.google.com/spreadsheets/d/1T8eEzBz-LCJMSpTIdM-OVRt3r-7TTlyw/edit?usp=sharing&ouid=109592846968506244474&rtpof=true&sd=true
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We have our own DataCap allocation protection process. The detailed rules are as follows:
1. The assignment of DataCap will mainly involve three departments: the business department, the risk control department, and the finance department
2. When the business department accepts the user's DataCap application, it will conduct the first round of review of the application record
3. After the business department has passed the review, it will submit the application form in the OA system to the risk control department
4. The risk control department will verify the applicants submitted by the business department by phone call, and transfer the OA to the finance department after the verification is passed.
5. The Finance Department keeps the assigned private key account numbers in a unified manner, and the Finance Department finally conducts a unified distribution operation
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
The post-allocation vetting of Clients will be performed regularly and constantly to avoid the allocated DataCap being abused or misused. The fundamental principle is that the Client is obliged to spend the DataCap exclusively for the approved uses (which will be specified in our allocation decision). 
To this end, at any time of the Client’s spending the DataCap, we may ask the Client to provide:
(1) a consolidated Content Identifier (“CID”) list for verified deals that includes deal CID and miner ID (showing how the allocated DataCap has been used);
(2) description of the data being stored and how the data has been processed; and
(3) instructions on data retrieval. 
(4) Pow power will randomly sample the verified transactions sent by the client on the chain, and will verify the authenticity of the data based on the transaction CID and miner retrieval. Filecoin public monitoring and auditing will also play a role
(5) Collect and score questionnaires for customers

Do you store data in one or more geographic areas?
What key features (such as fast retrieval) do you use in your storage transactions?
How do you secure DataCaps to ensure that your organization (and its delegates) are the ones who assign DataCaps?
Describe how you allocate data between miners
Does the data you store comply with local regulations and the recipient miner's terms of service?
Are there any disputes with you about your previous DataCap assignments? or any violation?
Additionally, we may use automated tools such as https://www.fil.deals/
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We mainly confirm through the application user points table established internally by POW Power. The following is our implementation process:

1. We will ask questions about the usage plan of DataCap allocation for the applied client. The more entities allocated by the user, the higher the points. (Scores from 1 to 10)
2. We will allocate a certain proportion (20%) of DataCap to the applying users, and track the usage of the customer for a period of time after the allocation, and score points according to the usage of the customer (from 1 to 10 points)
3. According to the user's condition, the second round of DataCap allocation will be made to the customer, and the ratio is the percentage of the points score (if the points are 2 points, 2% will be allocated, and the highest in this round is 20%)
4. Track the customer usage in the second round, and also score the customer usage. However, if the total points of the customer this time are less than 5 points, they will not be allocated. (up to 30% this round)
5. In this process, if the score of each round is lower than the average of the total points, the customers in this round will not pass the DataCap allocation until the user's total datacap allocation is completed.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we will announce each round of allocation on github, and will also notify applicants by email. 
In addition, we will also publish allocation information on TG and twitter
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
A google sheet for it.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
There is a business cooperation and sales relationship between PowPower and ipollo. PowPower does not control any other address or miner except our own address.
```

**Comment by panges2** [comment]
Hello @powpower2022,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by powpower2022** [comment]
@raghavrmadya The verification email has been sent through 'kehanwang@powpower.net', Please take a look. 
Would you mind explaining the details of "further audit" ?

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[765.pdf](https://github.com/filecoin-project/notary-governance/files/10159553/765.pdf)

**Comment by Kevin-FF-USA** [comment]
@powpower2022 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @powpower2022, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by powpower2022** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecbipal3ucardpo7jumblmobschyfyw5gi4zf7zetelbwxkwjtvie
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbipal3ucardpo7jumblmobschyfyw5gi4zf7zetelbwxkwjtvie

**Comment by powpower2022** [comment]
Thanks for reminding and all the welcome and we are really sorry for the late reply. The POWPOWER account will continue to be used. Due to internal reasons within the company, we missed a lot and caused the lack of signature before. During this period, we have been tightly following up the situation of the community in a timely manner, and we have seen the latest rules. In the future, we will have positive activity against the rules with our SLA. Please don't remove us, thanks! @raghavrmadya
