### ISSUE TITLE
Notary Application: NFTERA

### ISSUE THREAD

**Issue by NFTERA2121** [filecoin-project/notary-governance#766]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Rena
- Affiliated organization: NFTERA
- On-chain address to be notarized (recommend using a new address): f1yufwz7x3fguqa4v5ran45k7xmwyqtxm4tlrbhcq
- Country of Operation: Asia minus GCR
- Region of Operation: GCR&Asia minus GCR
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
None.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
None.
```

How did you acquire the FIL cited above?
```
None.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
None.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
None.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
NFT ERA focuses on the exploration of NFT and meta-universe field, pursuing professional, comprehensive and accurate information and data. We have established cooperation with nearly 100 capitalists, project parties and community media. We strive to be the world's leading blockchain information service platform.

Advantages of NFT ERA
1. Blockchain field vertical
NFT ERA is a vertical information platform in the blockchain field and has accumulated more resources related to the field by deeply cultivating in the segmentation track such as NFT and meta-universe - NFT ERA has reached long-term strategic cooperation with more than one hundred community opinion leaders and many famous blockchain media at home and abroad, and established a blockchain information community of tens of thousands of people. It has established a blockchain information community of tens of thousands of people and realized accurate information delivery.
2. Global Coverage
NFT ERA was founded in the "Web3 hub" of Singapore, with team members from the Middle East, North America, Southeast Asia and other regions. NFT ERA has provided services for nearly 100 capitalists, project parties and community media around the world. By choosing NFT ERA, you can not only reduce the cost of communication and get guidance on local policies and regulations, but also achieve global information placement.
3. Rich experience in organizing events
NFT ERA has a wealth of experience in hosting online and offline events, and has held a number of global large-scale summits, and has won the praise of the industry.

On May 15, the Metaverse Artwork: NFT Global Summit, co-hosted by NFT ERA and Mars Finance, kicked off! Around the current hot Metaverse, NFT topic, show and explore the new form of art within the future metaverse. 4 major mainstream public chains, 5 major head platforms, 17 award-winning institutions, 20 top investment institutions, 20 global NFT project parties gathered at this summit.
https://www.youtube.com/watch?v=dzGvwkXeqLA

On October 31, the Twitter Space of "The Great Tide Rises in Hong Kong: Explaining the New Heavyweight Crypto Policy in Hong Kong", initiated by Hong Kong Legislative Council member Wu Jiezhuang and Nano Labs founder Jack Kong, experienced five times of overflowing numbers triggering a fried room, and eventually the whole network was broadcasted nearly 500,000 times, which was the first record of a single Space worldwide.
It is reported that this Space was hosted by NFT ERA, with special guest Ione Y, and the keynote speakers included Hong Kong Cyberport executives, Xiao Feng, Jack Kong, Sun Yuchen, Du Jun, Wang Feng and other top industry leaders, and other investment community bigwigs, executives from various exchanges, and major community Kol took turns to participate online.
https://twitter.com/i/spaces/1YqJDomAYbzGV
https://twitter.com/i/spaces/1mrGmkONXBqxy
https://twitter.com/i/spaces/1OyJAVzAPEzxb
https://twitter.com/i/spaces/1RDxlaDogmOKL
https://twitter.com/i/spaces/1lDxLnbmMbbGm
https://twitter.com/i/spaces/1vAxRAjRAAXJl?s=20
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
https://news.marsbit.co/20220518144642044744.html
https://news.marsbit.co/20220518144545760287.html
https://twitter.com/i/spaces/1kvKpmwOwybGE
https://twitter.com/i/spaces/1PlKQpgdNwXxE
https://twitter.com/i/spaces/1lDxLnbmMbbGm
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Twitter：@NFTERA_Media  
WeChat video：NFT.ERA  
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Twitter：@NFTERA_Media  Followers：49.9k
WeChat video：NFT.ERA   Followers：2548
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://www.youtube.com/watch?v=dzGvwkXeqLA
https://twitter.com/i/spaces/1YqJDomAYbzGV
https://twitter.com/i/spaces/1mrGmkONXBqxy
https://twitter.com/i/spaces/1OyJAVzAPEzxb
https://twitter.com/i/spaces/1RDxlaDogmOKL
https://twitter.com/i/spaces/1lDxLnbmMbbGm
https://twitter.com/i/spaces/1vAxRAjRAAXJl?s=20
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We consider the authenticity and validity of data and the level of trust of a client to be particularly important. To prevent any damage to the network ecosystem, we have an audit program, regularly monitor the use of DataCap, and ensure that DataCap is granted to clients in a fair and equitable way.

When assigning DataCap, we perform the following four areas of assessment and assignment.
1. Basic information about individuals and organizations.
Social media account followers, account activity, official website, company size, time of establishment, number of employees, and other information.
2. DataCap usage strategy.
Which geographical locations will be located, how many SPs are selected, sealing speed, retrieval service, etc.
3. Data Information.
The type of data you intend to store. Can you provide 10% of the total application data as sample data
4. History.
Have you received DataCap before? Please share the link to your previous request. Have you previously used data local backup or cloud-based data backup?
Link to detailed scoring criteria.
https://docs.google.com/spreadsheets/d/14SHq9z5RvStDXxhXObEC5HeRUUnLHyVL/edit?usp=share_link&ouid=104835694739147544631&rtpof=true&sd=true
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
I will be solely responsible for the approval and delegation of the dc. The ledger will only be in my own hands.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We perform due diligence on our clients to gain a deeper understanding of their information, true needs, and follow up on DataCap usage after approval is obtained to determine if they are using DataCap correctly.
We review the client in the following main areas.
1. The description of your primary business and the type and size of data being stored.
2. Whether the source of the data you plan to store on Filecoin is authorized.
3. Whether the data stored on Filecoin complies with local laws and regulations and accepts the miner's terms of service.
4. Describe your reasons for choosing Filecoin as your data storage.
5. Plz disclose the storage provider you plan to cooperate and the percentage of allocation.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Usage review after allocation of Datacap.
1. we periodically spot-check the data stored on Filecoin by our clients to verify that it is publicly retrievable.
2. if allocated Datacap are found to be used fraudulently, we will blacklist them and make them public in the community.
3. we check if the data is allocated to storage providers in at least three different cities or regions to improve the security of the data storage.

We will track usage through our website: https://filplus.d.interplanetary.one/ and use other flexible methods to review and manage.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Github
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Github
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None.
```

**Comment by panges2** [comment]
Hello @NFTERA2121,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[766.pdf](https://github.com/filecoin-project/notary-governance/files/10159557/766.pdf)

**Comment by NFTERA2121** [comment]
Hi @Kevin 
Here's the update for some inforamtion, Please kindly take a look.
In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow.
**According to the industry reputation, we have recently successfully held some successful space sharing sessions. Aim to share web3 market experience and project analysis.
Among them is the promotion of Filecoin. We have used Filecoin as part of the presentation at different space in the past. One of them reached up to 300,000 listeners. The average number of listeners per show is 100,000. Our space was the hottest space in first week of Dec.
As a media platform, we hope to contribute more attention to Filecoin through our own media power.**

Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
**Based on the previous answers, we differentiate between individual clients and organizational clients.
Individual clients can easily check relevant applications and evidence. After verifying the personal information they submitted, 50% of their application dc will be allocated first. They are tracked according to their packaging speed and whether the SP is retrievable. At least 4 SPs can be found if their sealed, and each sp can be retrieved. And the data upload speed is very impressive, then I will continue to agree to the next allocation.
In addition, we will continue to use the allocation table above to see if they really understand the workflow of Filecoin Plus.**

Allocation Strategy
What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
**Usage review after allocation of Datacap.
1. we periodically spot-check the data stored on Filecoin by our clients to verify that it is publicly retrievable.
2. if allocated Datacap are found to be used fraudulently, we will blacklist them and make them public in the community.
3. we check if the data is allocated to storage providers in at least three different cities or regions to improve the security of the data storage. And there will be no less than 5 SPs for one client. 
4. Ask them following questions: 
1. Which method did you use to transfer your data to SPs?
2. How did you communicate with your SPs?
3. Was there any difficulty in dealing with your SPs?
4. Do you have any other options for your allocation strategy?
5. Have you searched the data stored after dealing with your SPs?
6. Is there any feedback from your experience to improve?

We will track usage through following website: 
https://filplus.d.interplanetary.one/ 
https://pluskit.io/home
https://www.atpool.com/en/dataCap/myIndex/customer
https://metawave.info/#/
https://filecoin.tools/
and use other flexible methods to review and manage.**

Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both?
**Yes, the assignment will public in GitHub repo.
What’s more, Slack@NFTERA, TG@NFTERA, Twitter@NFTERA_Media all of those can be open to our clients. 
We also will use a google docs to follow up on our assignment.** 

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
Publicly accessible record management plan
Github : https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues
Website: https://filplus.info/

**Comment by Kevin-FF-USA** [comment]
@NFTERA2121 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
