### ISSUE TITLE
Notary Application: Interstellar Storage (ShenZhen)

### ISSUE THREAD

**Issue by kyokaki** [filecoin-project/notary-governance#768]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Interstellar Storage（ShenZhen）
- Affiliated organization:  Interstellar Storage（ShenZhen）
- On-chain address to be notarized (recommend using a new address): f1fkfds7io5dqcxha25mclrnaop4ngstpjgjzjt5y
- Country of Operation: GCR
- Region of Operation: GCR
- Use case(s) to be supported: Professional Services (Hosting Reseller, Long-term Backups, Data Warehousing)
Developer Tools (Package Managers, Automatic Notaries, Web2 to Web3 integrations)
User Content (Personal Storage)
Public or Open Data (Scientific datasets, research data, government or historic
Media & Entertainment (Videos, photos, NFTs)
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?:  Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
We have been aware of Filecoin since May 2018, when we followed social media postings about ipfs and took note of this aspect and began to focus on it.

Interstellar Storage（ShenZhen）was founded on October 30, 2019 and has been active in the filecoin China community, actively participating in various online and offline shows, including every WEB 3.0 Summit from 2020 to 2022, and delivering speeches on stage and interacting enthusiastically with fellow attendees.

Interstellar Storage（ShenZhen）is one of the builders of Filecoin, and we are actively involved in various competitions in the community and have achieved excellent results in them.

About the projects we participated in:
Space Race 1.
Space Race 2.

As a service provider, we provide professional and integrated operation and maintenance services in the community, which guarantee the stable operation of our partners' nodes.
In terms of technology, we have developed a sector expiration query platform. We have developed a sector expiration query platform to protect the expiration of nodes.
We have also developed a coin distribution system and hardware management system to ensure the distribution of DCs.

As a senior evangelist of the Chinese filecoin community, we actively publish filecoin-related news and articles on our own social media platform.
Among the articles published are
Filecoin zk-SNARKs: Filecoin network has become the largest zero-knowledge proof network
 https://mp.weixin.qq.com/s?__biz=MzIwNTQ0NzkyOA==&mid=2247490163&idx=1&sn=008094ba53725685fc99208450daaa59&chksm= 9731ede4a04664f231aa5cb4fbbdde70a4da802a98d7543e7e1274ee7e134bb1201373cc1e55&token=308620900&lang=zh_CN#rd
Filecoin's Autumn: Value Upstream
https://mp.weixin.qq.com/s?__biz=MzIwNTQ0NzkyOA==&mid=2247490422&idx=2&sn=15730ea89f0eede2b7ec25fa3b6c5227&chksm= 9731ece1a04665f79bb52631416a7292cc1a8986b950c8e938291e42b13b418d21686d6cc9ae&token=308620900&lang=zh_CN#rd

Protocol Labs and Energy Web Complete First Demonstration of Filecoin's Open Source Solution for Carbon Reduction
https://mp.weixin.qq.com/s?__biz=MzIwNTQ0NzkyOA==&mid=2247490741&idx=5&sn=e9dff259edfdf63a1692d8dbb23a6ddb&chksm= 9731eb22a0466234ff5c472491e18f90356adb6f16a45a55db410ee1979f7dd70e0f2082aae3&token=308620900&lang=zh_CN#rd
How the combination of Filecoin and IPFS enables decentralized storage
https://mp.weixin.qq.com/s?__biz=MzIwNTQ0NzkyOA==&mid=2247490972&idx=2&sn=de327eabfb3547b7d69dd4cc69e15904&chksm= 9731ea0ba046631dde1ba185429a1d2f3045006a1370fe1014acdc0e93acc554f5f2f029d9a9&token=308620900&lang=zh_CN#rd
```
### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f01022733: 71942 Fil
```
How did you acquire the FIL cited above?
```
The first part of our participation in the competition to get some of the rewards, most of the later is mining, and part of the investment and market purchase to get.
```
### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We have actively participated in several important exhibitions of filecoin and distributed data storage in China, and have given presentations on.
2020 Global Internet Data Conference
2020 The 3rd Shenzhen Distributed Storage Industry Conference & Exhibition
2021 World Blockchain Ecology Conference
2021 Web3.0 China Summit - Chengdu
2022 Shenzhen International Big Data & Storage Summit, Web3.0 China Summit


https://www.ipfsnews.cn/6281.html
https://mp.weixin.qq.com/s?__biz=MzIwNTQ0NzkyOA==&mid=2247485490&idx=1&sn=6abe28d81e8ef7a61f3b49d464f6ab9a&chksm= 9731ffa5a04676b3965e2c8f9594d7e576339d6af44e665cd4b78b7b6bee765e4f80893ac4f4&token=1893421355&lang=zh_CN#rd
https://mp.weixin.qq.com/s?__biz=MzIwNTQ0NzkyOA==&mid=2247487341&idx=1&sn=3b3fdfee1ec234cf2b19a5b65f26202c&chksm= 9731f8faa04671ec6ec8e7b4a13debe9da514a2622da9a59104a7651a6c962536c1d6ff4a90b&token=1893421355&lang=zh_CN#rd
https://mp.weixin.qq.com/s?__biz=MzIwNTQ0NzkyOA==&mid=2247486693&idx=1&sn=d6cb039acbaa4055793136621beb937c&chksm= 9731fb72a046726410b24f8f67c425e07df1243593d7c4bfb0951fcffbfae626bfae1e963a8c&token=1893421355&lang=zh_CN#rd

As a senior evangelist of the filecoin community in China, we actively publish filecoin-related news and articles on our own social media platforms.
Among the articles published are

Filecoin zk-SNARKs: Filecoin network has become the largest zero-knowledge proof network
 https://mp.weixin.qq.com/s?__biz=MzIwNTQ0NzkyOA==&mid=2247490163&idx=1&sn=008094ba53725685fc99208450daaa59&chksm= 9731ede4a04664f231aa5cb4fbbdde70a4da802a98d7543e7e1274ee7e134bb1201373cc1e55&token=308620900&lang=zh_CN#rd
Filecoin's Autumn: Value Upstream
https://mp.weixin.qq.com/s?__biz=MzIwNTQ0NzkyOA==&mid=2247490422&idx=2&sn=15730ea89f0eede2b7ec25fa3b6c5227&chksm= 9731ece1a04665f79bb52631416a7292cc1a8986b950c8e938291e42b13b418d21686d6cc9ae&token=308620900&lang=zh_CN#rd

Protocol Labs and Energy Web Complete First Demonstration of Filecoin's Open Source Solution for Carbon Reduction
https://mp.weixin.qq.com/s?__biz=MzIwNTQ0NzkyOA==&mid=2247490741&idx=5&sn=e9dff259edfdf63a1692d8dbb23a6ddb&chksm= 9731eb22a0466234ff5c472491e18f90356adb6f16a45a55db410ee1979f7dd70e0f2082aae3&token=308620900&lang=zh_CN#rd

How the combination of Filecoin and IPFS enables decentralized storage
https://mp.weixin.qq.com/s?__biz=MzIwNTQ0NzkyOA==&mid=2247490972&idx=2&sn=de327eabfb3547b7d69dd4cc69e15904&chksm= 9731ea0ba046631dde1ba185429a1d2f3045006a1370fe1014acdc0e93acc554f5f2f029d9a9&token=308620900&lang=zh_CN#rd

There were some other links, but most of them were blocked due to the policy situation at the time.
```
### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
1. we participate in the main network of the preliminary rounds of testing, to assist hardware vendors, storage vendors testing, perfect hardware and storage performance optimization.
2. we provide professional integrated operation and maintenance services to ensure the stable operation of our partners' nodes.
3,. Developed a sector expiration query platform to escort the expiration of nodes.
4.. We developed a coin distribution system and hardware management system to ensure DC distribution.
```
### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Our company was incorporated in Shenzhen, China on October 30, 2019, and in the 3 years of our development and growth, we have always provided our customers with good products and technical support, sound after-sales service.
Mainly engaged in computer network technology, computer technology in the field of technology development, technology consulting, technology transfer, technology services, computer software development; electronic products, office equipment, computers, software and auxiliary equipment sales; cloud server sales; blockchain technology research and development applications; server storage equipment development and sales; trade brokerage and agency; business information consulting; business management consulting; in Online business activities; import and export business.
```
Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
WeChat official account: 星际存储深圳
website: http://www.xjccsz.com/
```
Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.citexpo.org/activities/120
https://baike.baidu.com/item/%E6%98%9F%E9%99%85%E5%AD%98%E5%82%A8%EF%BC%88%E6%B7%B1%E5%9C%B3%EF%BC%89%E7%BD%91%E7%BB%9C%E7%A7%91%E6%8A%80%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/51318754?fr=aladdin
https://www.ipfsnews.cn/9078.html
https://as.alltuu.com/album/1137662004/?from=qrCode
https://as.alltuu.com/album/1137662004/1143037213/
```
### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Slack: Interstellar Storage（ShenZhen）
WeChat official account: 星际存储深圳
The above social media accounts are all run by me.
```
Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
Exhibited Interviews and Presentations：
2020 Global Internet Data Conference
2020 The 3rd Shenzhen Distributed Storage Industry Conference & Exhibition
2021 World Blockchain Ecology Conference
2021 Web3.0 China Summit - Chengdu
2022 Shenzhen International Big Data & Storage Summit, Web3.0 China Summit

Below are photos and coverage of the presentation.
https://as.alltuu.com/album/1137662004/?from=qrCode
https://as.alltuu.com/album/1137662004/1143037213/
https://www.ipfsnews.cn/9078.html
```
# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
When evaluating customers and determining their DataCap allocation, we will focus on the authenticity of the customer. influence, allocation decisions, etc.
We do not intentionally set overly harsh conditions to limit community participants in order to facilitate community development and member participation. As a technology service provider, we will focus more on developer tools, hardware direction and Web3.0 and other hardware and technology related applications.

We will focus on the following points in checking customers.
1. checking the client's official social media to obtain basic information about their company and verifying the validity and authenticity of the information submitted and the source of the data.

2. requesting verifiable information from the client, such as the organization's business registration license, incorporation documents, and sending a confirmation email with its official domain name

3. Review the content of the client company's data storage.

In the distribution of Datacap, we will take a gradual growth approach.
We will allocate DCs up to 25Tib to clients who pass the evaluation for the first time, and if no unusual circumstances occur, the allocation amount will gradually increase. We plan to limit the single allocation to 50 TiB. 

And we will re-evaluate our customers again within six months in a comprehensive manner and reserve the right to adjust the customer's quota to ensure the full utilization of the share.

In addition, we will monitor submitted applications on a daily basis and respond to them within 2 business days.
```
How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We would like to choose Hardware wallet and GitHub account.
The private keys will be stored in the hard wallet and will be accessible only by the principal.
```
### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In the audit, firstly, we will ask the client to provide basic information to ensure the client's industry reputation

1. Client's profile
2. the client's various social media platforms
3. information on public business entities, such as business licenses, etc.
4. the client's previous address

The next step is to verify the authenticity and publicness of.

1. the composition of the client's data, and provide sufficient data samples respectively

2. The source and storage capacity of the customer's data set and its public nature (the customer is required to show proof of ownership or authorization according to local law)

3. The client is required to send a confirmation email with its own official domain name to our email address. The email name should include the issue ID #.

Finally about the allocation

1. how the customer plans to use the allocated data space

2. Does the client plan to make the allocation decision and implementation details public? and how to achieve it?
```
What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Regular (weekly or fortnightly) inspection and inspection; We will use the filfox  websites to check the proportion of SP allocated by customers.
```
### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we will choose Github, Slack and email to make allocation decisions and keep detailed records. Of course Github will be our best choice, and secondly we will also communicate and keep in touch with our clients on email and slack.
```
Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We will keep all records of all public access on the Github repo.
```
### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4 would be a better fit for us.
We are able to attend meetings on time, respond in a timely manner, follow up on FIPs on github, and actively handle client DC requests.
The amount of time we can spend here is around 20 hours per week.
```
### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
None
```
## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None
```

**Comment by panges2** [comment]
Hello @kyokaki,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by kyokaki** [comment]
Hi, @Kevin-FF-USA @panges2
Just sent the email! Also, I have a question about that do we need to prapare power point and attend the Next Governance Call to present our notary application? Cause I only saw the LDN application needs to do this, and can't find other informations of  notary application arrangement.
Thank you!

**Comment by Kevin-FF-USA** [comment]
@kyokaki 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @kyokaki, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by kyokaki** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaced34xwwn4hpeh4fpbqwfamjs3rrnq26eexuay7m72gmiulim5tpn6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced34xwwn4hpeh4fpbqwfamjs3rrnq26eexuay7m72gmiulim5tpn6
