### ISSUE TITLE
Notary Application: Bobby Choi

### ISSUE THREAD

**Issue by BobbyChoii** [filecoin-project/notary-governance#769]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Bobby Choi
- Affiliated organization: None
- On-chain address to be notarized (recommend using a new address): f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
- Country of Operation: Switzerland
- Region of Operation: [North America, South America, Europe, Africa, Greater China Region (GCR), Asia minus GCR, Oceania] Europe
- Use case(s) to be supported: [Please select from [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries)]
Professional Services (Hosting Reseller, Long-term Backups, Data Warehousing)
Developer Tools (Package Managers, Automatic Notaries, Web2 to Web3 integrations)
Decentralized Applications
Public or Open Data (Scientific datasets, research data, government or historic
Media & Entertainment (Videos, photos, NFTs)
- DataCap requested for allocation (10TiB - 1PiB): 50TiB
- Are you applying on behalf of yourself or an organization?: [Individual, Organization] Individual

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
I am Alex, the chief technical engineer of Bobby Choi, and the actual operator of this account. Our CEO bobby is a successful businessman who owns his own construction companies and has been an investor in a number of companies, such as SFS.The rise of web3 in recent years has caught his attention and we have always had a great interest in cryptocurrencies as long time holders of BTC. I proposed using Filecoin for backup of company data this year, but the board didn't approve it. However, from an investment point of view, my boss is very optimistic about the future of Filecoin. 

I've also been talking to members of my technical team and received general support for the idea and tech of distributed storage. Besides, I've had a lot of communication with the community from a technical level, and I'm fully aware of the storage methods and tools.

```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
N/A

```

How did you acquire the FIL cited above?
```
N/A

```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
N/A

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
No contribution at this point, but will suggest some parts that I think could be optimized after we assess the whole network.

```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
N/A

```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
N/A

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
N/A

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
I had several conversations with the Filecoin governance team in slack and in GitHubhttps://filecoinproject.slack.com/archives/C01DLAPKDGX/p1661847948903959
https://filecoinproject.slack.com/archives/CEHTVSEG6/p1659684360291179
https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1659943079842559
https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1659945761522969?thread_ts=1659712006.989649&cid=C01DLAPKDGX
https://www.instagram.com/bobbychoi1/

```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
N/A

```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
The focus of allocating DataCap is to know the applicant and the legitimacy of their allocation plan.
The authenticity of the client/application will be verified through the following steps.
1. Browse their official website to get a general understanding of the company or the individual. 
2. Confirm their status of compliance through the official inquiry authorities of each country.
3. KYC via email to verify that the applicant can truly represent the organization as claimed.
The validity of the allocation plan will be verified by data and by service provider details.
1. Whether the data samples and data set descriptions match its requested volume.
2. The SP allocation and how to perform the regular check on SP.
3. Whether the applicant is involved in self-dealing will be double-verified through dashboard after inquiry.

```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
By the ledger.

```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
The questions will correspond to the allocation plan mentioned above.
1. Please introduce yourself and your organization, what is its name, nature, country of registration, scale, time of establishment and business scope?
2.  In which region(s) did you use the DataCap?
3. What was your use case for the allocation?
4. Do you have a basic understanding of web3 and storing data in Filecoin?
5. Have you communicated with SP and if not, how do you plan to find any?
6. How many miners do you plan to use to distribute the data? 
7. What method/tool will you use to check the miners? (e.g. filfox, dashboard and miner Rep)
8. Are any of these miners controlled by yourself/your organization, and if yes, what percentage is expected to be?

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. I will check through slack and https://filplus.d.interplanetary.one/ to see if there are any violations in the previous application.
2. For clients with violations, I will check to see if they have explained and corrected their violations. I will also look for whether the applicant has been involved in other applications with similar behavior.
3. I will not allocate DataCap to a client who has not provided an explanation and has been involved in multiple violations. But if clarification is provided and there is community consensus, I will ask for more details about the allocation and distribution plan for this application that was submitted to me.

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
With both Github repo and email. 

```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
In github issues.

```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L3 with one hour per day during the week.

```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No, I have never made an application.

```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
None

```

**Comment by panges2** [comment]
Hello @BobbyChoii,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Please email NOTARYELECTION@FIL.ORG from the email account linked to this GitHub account. *The email MUST COME from the same GitHub account you used in this application.

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Carohere** [comment]
Hi @Kevin-FF-USA @panges2, I didn't receive the token code after the email was sent. Could you guys check it out for me? Thanks!

**Comment by BobbyChoii** [comment]
Hi Carolina,

I think you replied to the wrong application.

Best,

Bobby Choi
________________________________
发件人: Carolina ***@***.***>
发送时间: 2022年11月27日 22:32
收件人: filecoin-project/notary-governance ***@***.***>
抄送: Bobby ***@***.***>; Mention ***@***.***>
主题: Re: [filecoin-project/notary-governance] Notary Application: Bobby Choi (Issue #769)


Hi @Kevin-FF-USA<https://github.com/Kevin-FF-USA> @panges2<https://github.com/panges2>, I didn't receive the token code after the email was sent. Could you guys check it out for me? Thanks!

―

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[769.pdf](https://github.com/filecoin-project/notary-governance/files/10159563/769.pdf)

**Comment by BobbyChoii** [comment]
Time Commitment 
I participated in three working groups which are fil-plus-trust-wg, enterprise-wg and global-storage-provider-community.
I have contributed in proposal #594.


Client Due Diligence
To be consistent with the trust and transparency guidelines, I will cross-check the wallet addresses. First, for multiple applications from the same applicant for the same dataset, if the same address is not used. I will first check the address on https://filplus.d.interplanetary.one/ to see if there is any connection between the addresses or if there has been any improper behavior involved.  If there is, I will synchronize with the TRUST WG to flag the irregularities. If it's normal, I will notify under the issue itself and suggest the applicant to change the address. In addition, I will verify that the applicant's allocation does not contain any irregularities through the https://filrep.io/ SP reputation system.

Bookkeeping Plan
All of our records are publicly available and transparent on github and at https://filplus.d.interplanetary.one/. In addition, we will add secondary records in cases where there are special requests or exceptions to the data.For example, for encrypted enterprise type clients, we will update the private form with basic information that does not involve privacy. If in the future there are issues related to copyright infringement etc., I will work privately with the fil plus team to address the confusion.

Service Level Agreement
Changing from L3 to L4. 

Hi @Kevin-FF-USA @panges2, I just added more additional information. Please let me know if you need anything else.

**Comment by Kevin-FF-USA** [comment]
@BobbyChoii 

Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @BobbyChoii, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by BobbyChoii** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacec3n6beqlm4kq3piiffsd3e2g6ss6avsej2o2pqqk6ght5wbzkvw4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3n6beqlm4kq3piiffsd3e2g6ss6avsej2o2pqqk6ght5wbzkvw4
