### ISSUE TITLE
Notary Application: FogMeta

### ISSUE THREAD

**Issue by Normalnoise** [filecoin-project/notary-governance#772]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: FogMeta
- Affiliated organization: https://fogmeta.com  
- On-chain address to be notarized (recommend using a new address): f1o2yjnzchhp22daqwxe3mszl2uz6asi4iqmow7yy
- Country of Operation: China
- Region of Operation: GCR
- Use case(s) to be supported: Professional Services, Decentralized Applications, Public or Open Data, Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
FogMeta Technology Co., Ltd. is a high-tech company specializing in distributed storage, edge computing and fog computing. We have been filecoin community member for a long time, we have developed and been mataining some projects and tools to help more people join the filecoin ecosystem easily. The projects and tools are as follows:

 - Filecoin-IPFS Data Rebuilder: https://github.com/FogMeta/Rebuilder
 - Filecoin-IPFS Data Rebuilder website: http://rebuilder.fogmeta.com
 - Swan Client: https://github.com/FogMeta/go-swan-client
 - Swan Provider: https://github.com/FogMeta/go-swan-provider
 - Chainsnap: https://github.com/FogMeta/chainsnap

Our github accounts are: Fogmeta, FogmetaLab
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f1o2yjnzchhp22daqwxe3mszl2uz6asi4iqmow7yy  168.922 FIL
```

How did you acquire the FIL cited above?
```
Those FILs are our competition reward from Protocal Labs. Three months ago, we have taken part in the DATA DAO Hackathon hosted by filecoin foundation, filswan and chainsafe. Finally, our project, IPFS-filecoin data rebuilder, won the rewards.

 - DATA DAO Hackathon: https://dorahacks.io/zh/hackathon/27/
 - IPFS-filecoin data rebuilder: https://dorahacks.io/zh/buidl/3394
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As a member of the Filecoin community, Fogmeta has developed and maintained four tools for clients and storage providers. They are "Filecoin-IPFS Data Rebuilder", "Swan Provider", "Swan Client" and "Chainsnap".

(1) Filecoin-IPFS Data Rebuilder is a data build-and-rebuild tool between the IPFS network and the Filecoin network. 


(2) Swan Client is an important Web3 toolkit. It provides different tools to help users connect to the web3 world. It includes the following features:
 - Filecoin Deal Sender
 - Blockchain RPC Service


(3) Swan Provider listens to offline deals that come from Swan platform. It provides the following functions:
 - Download offline deals automatically using aria2 for downloading service.
 - Import deals using lotus once download completed.
 - Synchronize deal status to Swan Platform, so that both clients and miners will know the status changes in realtime.
 - Auto bid task from FilSwan bidding market

(4) Chainsnap is a project for maintaining blockchain snapshots. This project enables the storing and retrieval of snapshots for blockchain projects including Filecoin, Polygon, Ethereum, Binance Smart Chain, and Near.

Related Links(github and docs)
 - Filecoin-IPFS Data Rebuilder: https://github.com/FogMeta/Rebuilder
 - Filecoin-IPFS Data Rebuilder website: http://rebuilder.fogmeta.com
 - Swan Client: https://github.com/FogMeta/go-swan-client
 - Swan Provider: https://github.com/FogMeta/go-swan-provider
 - Chainsnap: https://github.com/FogMeta/chainsnap
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
In the 2020, I have been a member of Filecoin Security Research Fellowship, And I submitted several bug reports to help filecoin fix the protocal bug. Whyrusleeping can prove it.  
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Fogmeta is headquartered in Shanghai, FogMeta Technology Co., Ltd. is a high-tech company specializing in distributed storage, edge computing and fog computing. 

- Registration Country: China
- Organization size: 20+
- Time since establishment: 2021
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Official Website：https://fogmeta.com
Slack: Leo Zhang
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Github Organization: Fogmeta, FogmetaLab

```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Github Organization: Fogmeta, FogmetaLab
Personal Github: Normalnoise
Slack: Leo Zhang
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://mp.weixin.qq.com/s/c69k7nsNF_VHS_VUHGK2Lw
https://mp.weixin.qq.com/s/JWipqq11vUnRA8ygT7rIkQ
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Clients who apply for DataCap will be required to submit a detailed proposal

(1) The basic information to ensure the client's industry reputation:

 - Client's social media account
 - The information of company or organization
 - Previous application and address

(2) Data Description:
 - the composition of the data, and provide enough samples.
 - data is public or private? if it is private data, please provide the proof of ownership or authorization
 - send an email with official domain name fo validating the owner.

(3) how to distribute you datacap?
 - Do you have a storage provider or related storage providers?
 - How to choose the storage providers for you datacap?
 - What is your plan to send your dat to the storage providers, online or offline?
 - How to assign the Datacap to different Storage Providers?
 
Finally, I will allocate the datacap to 10 client at least. Every client can not get more than 100TiB datacap.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
we will use a ledger wallet to store our private key
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
The basic rules is that the higher the DataCap application, more infomation will be required for client. First, we will ask relevant information about customers and organization.

(1) Personal Infomation: 
 - Location
 - Social media account

(2) Company or organization infomation:
 - The Country of registration
 - Company's social media, news, etc.
 - Size of the organization
 - Time since inception

(3) dataset infomation
 - please describe your dataset
 - What is the size of your data?
 - Is it public or private?
 - how to process your data to CAR file?
 - How to distribute your data to Storage providers?

(4) how to distribute DataCap:
 - Do you have some storage Providers?
 - How to select the Storage Providers?
 - How to assign the Datacap to different Storage Providers? 
 - Please submit yourdeal metadata

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Before I grant the new datacap to client, I will check that client how to distribute their datacap in the last round datacap. The check list will be as fillows:
 - The numbers of storage providers
 - Number of deals
 - Most datacap used on a single miner
 - Numbers of dataCID
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, all allocation decisions will be conducted in the github, and the records will be published on the Github. and I am gong to have a DD with some clients by slack, email and Telegram. 

```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
we will list all the allocation decisions to fogmeta github repo.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L5, we hope to deeply participant in the Fil+ program, we will try to accomplish the followling requirements:

 - Maintain a ranking in Leaderboard in the top 5% of Notaries.
 - Attend 2 Governance calls a month - with webcam turned on
 - Join 2 working groups
 - Respond to SLACK inquiries within 24 hours
 - Vote/Comment on all proposals submitted
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Yes, we have applied the datacap before.
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/954
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/984
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1135
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1136
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1137
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1138

```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
Yes, we are helping filswan develop and maintain the swan-provider and swan-client project. 
```

**Comment by panges2** [comment]
Hello @Normalnoise,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by raghavrmadya** [comment]
Thank you for your verification information. At this stage, the Trust & transparency Working Group has flagged your application for further audit. The governance team will wait for guidance from the WG before we can proceed further with your application.

**Comment by Normalnoise** [comment]
@raghavrmadya @Kevin-FF-USA I have seen the [message](https://filecoinproject.slack.com/archives/C0405HANNBT/p1670031496440939?thread_ts=1669940760.027469&cid=C0405HANNBT) in slack.

I want to provide more information about Fogmeta.
Official Github: https://github.com/FogMeta
Company Email: jianzhang@fogmeta.com

Besides, I have received verify code from phil.pangestu@protocol.ai and the token code has been sent to [Kevin-FF](https://filecoinproject.slack.com/team/U02KQGP29S9) and [Philippe Pangestu](https://filecoinproject.slack.com/archives/D04D55LN96F)

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[772.pdf](https://github.com/filecoin-project/notary-governance/files/10159565/772.pdf)

**Comment by Kevin-FF-USA** [comment]
@Normalnoise 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @Normalnoise, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by Normalnoise** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedaztrdn2e4cttkzqwzkj6iw7ot5gmdaq74bbw5rd6aohsai5k7oc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedaztrdn2e4cttkzqwzkj6iw7ot5gmdaq74bbw5rd6aohsai5k7oc
