### ISSUE TITLE
Notary Application: Drust

### ISSUE THREAD

**Issue by Agee-Drust** [filecoin-project/notary-governance#773]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:Agee
- Affiliated organization: Drust
- On-chain address to be notarized (recommend using a new address):f1sng4f4ws4dmg4itg45bt5to37ev5wc5wpx67pzq
- Country of Operation: Singapore
- Region of Operation: Asia minus GCR
- Use case(s) to be supported: User Content (Personal Storage), Public or Open Data (Scientific datasets, research data, government or historic
- DataCap requested for allocation (10TiB - 1PiB):500TiB
- Are you applying on behalf of yourself or an organization?: Individual

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
GitHub: Agee-Drust https://github.com/Agee-Drust
I had heard about distributed storage IPFS and participated in hackathon, and after learning about it I discovered filecoin and interested in it. As Filecoin vision say, Filecoin is a decentralized storage network designed to store humanity's most important information. I have ambitious with Filecoin and Filecoin Slingshot about ensuring meaningful data is stored and retrieved from the Filecoin Network. Thus, I took part in Slingshot in June and keep an eye on the community.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
The total amount of tokens I have exceeds 500K Fil. 
Address: f01887652, f01915041, f01895928, f01035021
```

How did you acquire the FIL cited above?
```
From indivial account.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
I have attended Governance Meetings every two weeks and participated in discussions to follow the development and movement of the filecoin community. I think filecoin has a great future so that I actively take part in Slingshot and  apply for Slingshot evergreen. 
![Agee](https://user-images.githubusercontent.com/106581965/202263356-8c7cc1bc-025f-4849-a426-a47367791bf2.png)
Also, I have submitted several applications on GitHub and used datacap in a reasonably way under community's rules.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Joining to filecoin is based on my personal interest and it is a personal act.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
N/A
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
N/A
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
GitHub: Agee-Drust https://github.com/Agee-Drust
slack: @Agee
Twitter: @AgeeWeb3
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
N/A
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
I plan to allocate 80% DataCap within 10 months.
I will judge and approve applicants through questions and surveys. And I'd like to ensure I grant eligible clients the appropriate amount of DataCap and with smooth onboard into Filecoin. Authenticity,  allocation fairness, client's correct usage of DataCap are the key. 
First, I will verify the identity of the client, including the qualifications of the organization the client represents.
Then I will investigate the amount of data requested by the client, the type of data, storage method they used to choose, and whether it is public data.
I hope that the client has a clear plan on data generation, ways of deal-making, and SP selection. 
If it is not the client's first-time allocation, I will refer to the client's previous DataCap consumption and ensure the deal-making is not heavily made to few SP. I will also randomly retrieve the deal to confirm the requested data is stored into Filecoin. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
I've got a ledger and I will use it to secure the DataCap.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
1. What's your name and your position in your company?
Please introduce yourself and your team briefly.
2. Please show web pages, Github, social media accounts. 
3. Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to me. And also could send me via email for privacy concerns.
4. What types of data do you plan to store with the DataCap and how many do you need? Could you please send me some of sample data?
5. Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?
6. Where is your data stored now? Whether the data is stored on a server or a cloud service provider?
7. Has your organization obtained DataCap before? if so, please answer the following sub-questions.
a. Please share all the links and recordings of your applications before.
b. How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
c. What was your allocation strategy plan then and how did you execute it?
8. Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc. 
9. How many regions do you plan to store the data in? 
10. How many storage providers you intend to make dealing with?
11. Do you plan to record your allocation decisions and execution details in public? And how to realize it?
12. Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
I will use https://filplus.d.interplanetary.one/ for checking their usage of DataCap.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, I will document the supporting details on the decisions I make with each client in public through Github.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
I will record it on GitHub and back it up myself.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
I'm willing to be L2 notary.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No, I'm not a notary in the past.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No, but I hope  to get to know more notaries so that I can understand more about filecoin.
```

**Comment by panges2** [comment]
Hello @Agee-Drust,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[773.pdf](https://github.com/filecoin-project/notary-governance/files/10159567/773.pdf)

**Comment by Agee-Drust** [comment]
@Kevin-FF-USA @panges2 @galen-mcandrew Hi, sir. I'm Agee, I have a few points to add to my application. 
First of all, I have been trying to apply for a notary as an individual, but it was modified by @panges2  to apply as an organization --- Drust, please help me to modify my application to an individual notary application if it is allowed.
I started focusing on filecoin in 2020, and then I followed filecoin mainnet and paid a lot attention to the development of distributed storage. I am really interested in filplus project that encourages real data storage, and I hope to join the filplus to become a notary and contribute to community governance. So I want to apply to become an L4 notary and I am well prepared for this.
Then, for my allocation strategy, I've made a criteria and I'll use the criteria to judge the client.
https://1drv.ms/x/s!AvvsgTi08U9XcYLhnZY1ocGuSlM?e=bgSD9z
![1 (2)(1)](https://user-images.githubusercontent.com/106581965/206524076-46abe4ff-1853-40d3-ba52-9a2a20c4e9ef.png)
For Client Due Diligence, I don't just ask the 12 questions in clients' applications that I prepared in my notary application. The questions I am going to ask may vary due to different information provided by clients, I will ask further questions to clear the doubts as I see fit. If all the responses make sense, then the application will  be approved. I will check if or not the SP number is the same as planned and ask them to make adjustment if required. I will pay attention to the  github/slack messages, and any misconduct about DataCap using is not allowed.
Thank you for this opportunity to further explain my application!

**Comment by Kevin-FF-USA** [comment]
@Agee-Drust 

Thank you for applying to serve as a Notary in this 4th round of elections for the Filecoin Plus program. This round’s pool of applicants was the largest and most accomplished in the programs history; and in light of this, we were unable to offer positions to every worthy applicant.  After carefully reviewing the application, I’m sorry to inform that it was not selected as a Notary in this 4th round. 

Please know that this decision in no way diminishes your application. We are impressed by the contributions you’ve demonstrated and hope you continue to drive the success of the Filecoin storage system. The 5th round of new Notary Elections is scheduled to open in Q2 of 2023, and we encourage you to maintain a presence in the community and return during the next round.   Please reach out to Galen, Kevin-FF, or Philip on Slack if you have any questions.

Thank you for the hard work your application represents.
