### ISSUE TITLE
Notary Application: Olivier Molenkamp

### ISSUE THREAD

**Issue by OlivierMolenkamp** [filecoin-project/notary-governance#774]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Olivier Molenkamp
- Affiliated organization: N/A
- On-chain address to be notarized (recommend using a new address):f1fl5gjqv3xknuhka273jrsrkzqcumrp6idrnvgyi
- Country of Operation: Netherlands
- Region of Operation: Europe
- Use case(s) to be supported: Gernal 
- DataCap requested for allocation (10TiB - 1PiB): 300TiB
- Are you applying on behalf of yourself or an organization?: Individual

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
In 2017, I learned about cryptocurrency for the first time and became a Bitcoin holder.
In 2019, invested in Bitcoin mining machines in Amsterdam, Indonesia, Sichuan, China, Xinjiang, China
In 2019, more cryptocurrencies were invested like DOT, ETH, LTC, XMR, etc.
In 2020, learn about Filecoin and pay attention until mainnet launch, and buy it on the exchange
In January 2021, I invested and joined the Filecoin network with my friends in China under Renren mine.
In 2022, pay attention to the project Fil+ project Saturn, smart contract.SP ID f0130791
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f0130791 more than 120000+FIL
```

How did you acquire the FIL cited above?
```
Bought from Binance and crypto.com
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
N/A
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
N/A
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
N/A
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
N/A
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```In 2017, I learned about cryptocurrency for the first time and became a Bitcoin holder.
In 2019, invested in Bitcoin mining machines in Amsterdam, Indonesia, Sichuan, China, Xinjiang, China
In 2019, more cryptocurrencies were invested like DOT, ETH, LTC, XMR, etc.
In 2020, learn about Filecoin and pay attention until mainnet launch, and buy it on the exchange
In January 2021, I invested and joined the Filecoin network with my friends in China under Renren mine.
In 2022, pay attention to the project Fil+ project Saturn, smart contract.
Facebook https://www.facebook.com/olivier.molenkamp 532 follower
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
Facebook https://www.facebook.com/olivier.molenkamp 532 follower  
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.

```
Define thresholds with different levels of trust.The higher the requirements, the stricter the review：
Several important factors:
- Reputation of the applicant organization
- Is there any contribution to the Filecoin ecosystem (not necessarily a factor, but it will be a bonus item)
- Scale of allocation
- Assigned rating
- Safety Precautions
- Customer transparency
The type of data applied for (the public data set will be given priority)
The specific distribution plan can be viewed in the Google shared table：https://docs.google.com/spreadsheets/d/1AsAyaW1mV-eKyaqLWWTIAsaWHf24YNCriinHc-naJrs/edit?usp=sharing
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
A cold wallet - Ledger will be used for datacap allocation by myself. 
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 

```
All the allocation of DataCap will be carried out through Filecoin community and FIL+ team. 
Client need KYC audit. After the audit is passed, submit the data usage requirements.
Regarding the request for DataCap, we plan to ask the following questions as the KYC audit:
1. Are you an individual or a business/organization? 
2. If an individual, please specify the name, date of birth, and nationality (by providing passport insurerance ID)
3. If a company/organization, please specify the company name, registration time, and registration area. 
4. Please provide the corresponding supporting documents (,enterprises/organizations provide business licenses)
5. What is your industry? 
6. What type of data will be stored? 
7. How many TiB do you plan to store? 
8. Can the data be public and retrieval by anyone from the network?
9. Please share information and relevant supporting documents or links that illustrate your industry status.
11. Is there any law risk by storing these data to our network?
12. Please provide your social media account for referance.
13. Please specify the storage location, SP ID and storage proportion of your data to be stored. We require less than 30% of DataCap spend on one SP.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.

```
1. Check their previously allocation on Fil+ dashboard,Less than 30% of single datacap used on single SP is acceptable. 
https://filplus.d.interplanetary.one
2. Check with the notaries who allocated the datacap for this client, any suspicious behavior during the data onboarding?
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 

```
Yes,  all records will be public.If any information from email, I will keep the screenshots.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?

```
Github Repo
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 

```
L1 is fine
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No, I don't have any
```

**Comment by panges2** [comment]
Hello @OlivierMolenkamp,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Please email NOTARYELECTION@FIL.ORG from the email account linked to this GitHub account. *The email MUST COME from the same GitHub account you used in this application.

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by OlivierMolenkamp** [comment]
> Hello @OlivierMolenkamp, Thanks for applying to become a Notary in the Fil+ program!
> 
> As we score your application, you will need to verify your contact information and affiliated organization. Please email [NOTARYELECTION@FIL.ORG](mailto:NOTARYELECTION@FIL.ORG) from the email account linked to this GitHub account. *The email MUST COME from the same GitHub account you used in this application.
> 
> Subject Line: Notary Name, Application Number Email Body:
> 
> 1. Your First and Last name
> 2. Your Organization
> 3. Your Country of Operation
> 4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
> 5. Link to your GitHub application
> 
> This step needs to be completed by 28NOV. Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed. Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.
> 
> Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2
> 
> Thank you!

Hi Phil, email replied.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[774.pdf](https://github.com/filecoin-project/notary-governance/files/10159570/774.pdf)

**Comment by OlivierMolenkamp** [comment]
Thanks for your reply, Galen!  I think the score of my evaluation is too low. 

Since January 2021, I have been actively contributing to this community to understand and promote Filecoin. My friends and I created a TG group last year to promote the Filecoin information. YTD, we have 6399 members.
![TG Screenshot1](https://user-images.githubusercontent.com/107348556/206527519-9f135f9b-7088-44d7-a8e4-74d3b116a028.png)

![TG Screenshot0](https://user-images.githubusercontent.com/107348556/206527537-8e63dbdb-edc2-4085-829b-95f310b88427.png)

In addition, I also want to spend more time in the community, and I am willing to modify my SLA to L4. 

Hope you can re-evaluate for me.
Thank You

**Comment by OlivierMolenkamp** [comment]
Thanks for your reply, Galen!  I think the score of my evaluation is too low.

Since January 2021, I have been actively contributing to this community to understand and promote Filecoin. My friends and I created a TG group last year to promote the Filecoin information. YTD, we have 6399 members.

In addition, I also want to spend more time in the community, and I am willing to modify my SLA to L4.

Hope you can re-evaluate for me.
Thank You
________________________________
发件人: Galen ***@***.***>
发送时间: 2022年12月6日 9:04
收件人: filecoin-project/notary-governance ***@***.***>
抄送: Olivier Molenkamp ***@***.***>; Mention ***@***.***>
主题: Re: [filecoin-project/notary-governance] Notary Application: Olivier Molenkamp (Issue #774)


Please see attached for initial notary scoring by governance team. Thank you for applying!
774.pdf<https://github.com/filecoin-project/notary-governance/files/10159570/774.pdf>

―

**Comment by OlivierMolenkamp** [comment]
Thanks for your reply, Galen!  I think the score of my evaluation is too low. 

Since January 2021, I have been actively contributing to this community to understand and promote Filecoin. My friends and I created a TG group last year to promote the Filecoin information. YTD, we have 6399 members.
![TG Screenshot0](https://user-images.githubusercontent.com/107348556/206528580-33241633-2d69-49da-af49-bd309c2688bb.png)

![TG Screenshot1](https://user-images.githubusercontent.com/107348556/206528639-7b6403d5-a3a2-436d-99f9-c6cf8158b28f.png)


In addition, I also want to spend more time in the community, and I am willing to modify my SLA to L4. 

Hope you can re-evaluate for me.
Thank You

**Comment by OlivierMolenkamp** [comment]
HI Kevin,

Thank you so much for your support, I am very happy to be one of the notaries of the community. I will try my best to help and serve the community

Oliv
________________________________
发件人: Kevin ***@***.***>
发送时间: 2022年12月13日 10:34
收件人: filecoin-project/notary-governance ***@***.***>
抄送: Olivier Molenkamp ***@***.***>; Mention ***@***.***>
主题: Re: [filecoin-project/notary-governance] Notary Application: Olivier Molenkamp (Issue #774)


@OlivierMolenkamp<https://github.com/OlivierMolenkamp>

Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections.

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in https://plus.fil.org/ as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

  1.  By 20 December - Complete the CONTACT AND DISCLOSURES form
     *   https://airtable.com/shrjx52lvefitwdq6
  2.  By 30 December - Ensure that the Governance meeting time is on your calendar and make scheduling plans which allow you to commit to attending per your SLA level expectations. (L1-L5)

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

―

**Comment by panges2** [comment]
HI @OlivierMolenkamp, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by OlivierMolenkamp** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebrl7eq24twl7hcuzkle2t272vqpkolgqkxwyw5n5tyiusgmmbvew
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebrl7eq24twl7hcuzkle2t272vqpkolgqkxwyw5n5tyiusgmmbvew

**Comment by OlivierMolenkamp** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacea7p7pr4plqerdbrik5bp2p4fbwpdjekdomhbzjcrsns6mjrmcyhk
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7p7pr4plqerdbrik5bp2p4fbwpdjekdomhbzjcrsns6mjrmcyhk

**Comment by OlivierMolenkamp** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceajx7gm44s3znokutpusouwnesywz5s2ofo7grzevrk3nt6imxez4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajx7gm44s3znokutpusouwnesywz5s2ofo7grzevrk3nt6imxez4
