### ISSUE TITLE
Notary Application: Pangod 

### ISSUE THREAD

**Issue by PangodGroup** [filecoin-project/notary-governance#775]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Casey
- Affiliated organization: Pangod
- On-chain address to be notarized (recommend using a new address):f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
- Country of Operation: China
- Region of Operation: [Greater China Region (GCR)]
- Use case(s) to be supported: [Web2/ Web3 Public Data, Enterprise Data]
- DataCap requested for allocation (10TiB - 1PiB): 500TiB
- Are you applying on behalf of yourself or an organization?: [Organization]

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
I'm Casey, Co-founder and VP of China Pangod Group. We know Filecoin and IPFS via IPFSUnion in January 2021- one of the biggest Lotus operator in China. At the beginning, I started to participate as an mining investor.

We had a good experience on Filecoin Plus Project since March 2022. For this case, it's bring me a lot of imagination on the new way of cost control. Additionally I attended the filecoin governance call in March this year. So I gradually have a deeper understanding of filecoin.

Pangod is a technology media enterprise that uses leading Internet technology to change the traditional advertising industry.We are trying to find more innovation opportunities to embrace the future world, including, of course, connectivity with the web3 world. Filecoin is our first great attempt, and we hope to have more opportunities to participate in it.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
f0130791/f095334/f0133957/f01828096
Now totally we have more than 1MM FIL.
```

How did you acquire the FIL cited above?
```
Trading by Binance
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
To be a LDN client and on boarding data successfully.
Please refer to : https://filplus.d.interplanetary.one/clients?filter=f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
cChengdu Pangod Group is committed to providing professional Internet advertising services for enterprises and various institutions. At present, it has about 800 employees. Since its establishment in August 2003, the company has been following the business philosophy of "honesty based", aiming at "serving the traditional industry, promoting the innovative development of the industry, integrating network marketing, and providing professional services", adhering to the service concept of "customer first, serving with heart, and winning customers by relying on service", constantly improving and improving professional level and service quality, embracing the Internet and innovative technology, and shaping a good service brand and corporate image, It has established a good reputation and popularity in the industry and customers.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
http://www.pangod.com
Wechat official account: Pangod AD
Wechat official account: Pangod Digital
Wechat official account: Pangod Network

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://www.xinpianchang.com/a10798982
https://www.zhipin.com/gongsi/d2ccdc64326df0c20nVz2tu1EA~~.html
http://chengdu0271751.11467.com/
https://baike.baidu.com/item/%E6%88%90%E9%83%BD%E7%9B%98%E5%8F%A4%E4%BA%92%E5%8A%A8%E5%B9%BF%E5%91%8A%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/15089989?fr=aladdin
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
Wechat official account: Pangod AD （followers：3500+）
Wechat official account: Pangod Digital（followers：200+）
Wechat official account: Pangod Network（followers：180+）
https://weibo.com/ttarticle/p/show?id=2313501000014157241560332189
https://baijiahao.baidu.com/s?id=1702820807287672659&wfr=spider&for=pc
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://weibo.com/ttarticle/p/show?id=2313501000014157241560332189
https://baijiahao.baidu.com/s?id=1702820807287672659&wfr=spider&for=pc
http://www.pangodbj.com/m/newsdetail.aspx?listid=11&infoid=376
https://www.mbachina.com/html/mbachina/201806/86627.html
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
#Allocation Plan:
1.We will verify customers into two categories: Existing customers and New Customers
2.For existing customers, we need to check if there is any violation of international and local laws, filecoin’s standards and ethics. For new customers, we will go through a specific KYC for individual clients or corporate clients.
3. After the KYC and client identify verification, the client who apply for the DataCap will go through a scoring process based on their applications and evidence as below: https://docs.google.com/spreadsheets/d/1MkVkIgVduJDq3ic02X-r60epc3Fa62APM9kD88q4DBo/edit?usp=sharing
4. The final sore will be given based on the Client Identity, Diversity, Decentralization, Allocation Strategy. For each sector we give a score of 0-7, eventually, the total score will be fit into a DataCap table to give the final granted amount of DataCap.
5. The granted amount of DataCap will be confirmed and verified with remaining DataCap, then the granted amount will be allocated to client.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Hardware wallet and GitHub account will keep in two different staff when allocating.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 
For individual clients, online identity will be verified by both account age and account activity perspectives, 
and this will serve to prove that they are valid users and not bots or sybils. 
Third-party tools like twitteraudit may also be used to verify online identities. 

For organizational clients, application organizations should be easy to verify through the appearance of their application. 
The developing applications may require further stringent investigation; 
this is to ensure that the application is valid and enclosed with meaningful content, rather than the shell of a malicious client. 
Large public datasets hosted by organizational clients are easy to verify because the data should be unencrypted and accessible to anyone. 
However, in the event that the organizational client has large private encrypted datasets(i.e., law firms), the Due Diligence procedure will be executed.

Below is the proposed procedure of Due Diligence. We need 3 types of information for review by myself or our compliance team depending on the volume of clients required Due Diligence:
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information; 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name;
 - date of birth; 
 - street address (P.O. box number is not acceptable); 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

There are two questionnaires to help me get to know our clients. The first one is about the basic information collection of new clients. 

#Questions #1
Please describe answers as much specificity as you can.

1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.)
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
6. How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify.
7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing? 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will use the second questionnaire to collect follow-up answers about previous allocations for returning clients. 

#Questions #2
Since you have requested DataCap from me or other notaries before, we have some questions regarding your previous DataCap allocation.

1. How much cumulative DataCap was allocated to you from me or other notaries?
2. In which region(s) did you use the DataCap?
3. What was your use case for the previous allocation?
4. Did you specify any advanced features for the previous allocation?
5. How many miners did you allocate the DataCap to? Please specify transaction links to the storage deals.
6. In your previous allocation, did you violent any community principles like excessive/unfair self-dealing?
7. Did you ask SP to provide the fast retrival to the network?
8. Is there anything I could improve to serve you better in future allocations?

Utilizing the information collected will help me confirm that the client is not improperly using the DataCap they were previously granted. 
Clients are encouraged to allocate the DataCap to more than 3 different miners, 
which not only increases storage redundancy but also helps maintain decentralization and reduce the possibility of potential misuse.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Both GitHub and Email are ok.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub Repo.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L3 will be ok for us.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No, thanks.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No, I don't have any notaris or organizations related.
```

**Comment by panges2** [comment]
Hello @PangodGroup,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[775.pdf](https://github.com/filecoin-project/notary-governance/files/10159573/775.pdf)

**Comment by Kevin-FF-USA** [comment]
@PangodGroup 
Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsbilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @PangodGroup, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by PangodGroup** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecug3srw6pyzxfjgfuby6tyws2bhn7qqh6habygryixqgbmd4xxe6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecug3srw6pyzxfjgfuby6tyws2bhn7qqh6habygryixqgbmd4xxe6
