### ISSUE TITLE
Notary Application: PiKNiK

### ISSUE THREAD

**Issue by jamerduhgamer** [filecoin-project/notary-governance#776]
# Notary Application

## Core Information
- Name: James Hoang
- Affiliated organization: PiKNiK
- On-chain address to be notarized (recommend using a new address): f1kqdiokoeubyse4qpihf7yrpl7czx4qgupx3eyzi
- Country of Operation: United States of America
- Region of Operation: North America
- Use case(s) to be supported: Professional Services, Developer Tools, Public or Open Data, Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB): 1 PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
We have been in the Filecoin ecosystem even before mainnet launch. Our miner IDs are f066596 and f0678914. Having contributed to Bleeding Edge, MinerX, MinerX2, MinerX3 and now SPX, we are very deeply involved with improving the network and the ecosystem.
Starting on December 16th, 2021, we have participated in the Slingshot restore program as a SP to numerous Slingshot clients.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```

Currently Available - 200,000
Initial Pledge - 220,000
Locked Rewards - 30,000

https://filfox.info/en/address/f066596
https://filfox.info/en/address/f0678914
https://filfox.info/en/address/f01880776
https://filfox.info/en/address/f01833311
https://filfox.info/en/address/f01903261
https://filfox.info/en/address/f01662356
https://filfox.info/en/address/f01851060
https://filfox.info/en/address/f01652333
```

How did you acquire the FIL cited above?
```
Sourcing our own FIL from exchanges and then utilizing FIL lenders such as DARMA, Anchorage and CoinList.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
PiKNiK's CEO has contributed universally to the docs.filecoin.io GitBook including changes to the "Miner" nomenclature to "Storage Provider" as well as the reference architecture that included Intel. This FIP was inspired by the above - https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0018.md

 As a title sponsor, PiKNiK has also written significant documentation for ESPA (Enterprise Storage Provider Accelerator) about the different implementations and many other aspects of Filecoin in their learning management system.

ESPA Bootcamp Content 
https://www.youtube.com/playlist?list=PL_0VrY55uV1-rriLu3aH-8Q1b9Xqf0_Zs

We have also supported the ecosystem's very first enterprise-tier storage customer, USC Shoah Foundation, to store across multiple independent SPs.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
PiKNiK's architects and senior technical leadership have contributed to the Filecoin protocol through numerous Github issue request listed below:

Alex Fox - https://github.com/filecoin-project/lotus/issues/created_by/neondragon
Has been contributing since Nov 26, 2021 in numerous ways to the security of Filecoin through detecting Lotus issues and suggesting improvements such as: 
- Storage deals getting stuck or failing add piece
- PreCommit logic improvement
- New query-ask format suggestion
- Lotus-bench quick PC2 or C2 improvements
- Reported bug with sectors in shared storage being deleted
- Disconnected worker improvements
- Market node write permission for retrieval enhancement

Also submitted: FIP Proposal - https://github.com/filecoin-project/FIPs/issues/93
Which addresses upgrading sectors and how its power should be consistent with a newly sealed sector.

Benjamin Højsbo - https://github.com/filecoin-project/lotus/issues/created_by/benjaminh83
Has been contributing since Aug 10, 2020 in numerous ways to the security of Filecoin through detecting Lotus issue such as
- Bug with dedicated PreCommit2 worker
- CommittingFailed with sector containing deals
- Sectors stuck in WaitDeals failing ProviderEventDealHandoff
- Sectors stuck in StorageDealStaged
- Bug with sectors extend
- Bug with lotus-miner / markets subsystem crash
- Suggested that the dagstore destroy shard if sector is lost
- Suggested a command to remove expired sectors
- Bug with offline deal imports crashing the market node
- Bug with unsealing job being scheduled even though unsealed copy exist
- Issue with AddPiece on multicore CPUs
- Lotus market bug with too many active transfers
- Bug with hwloc calculation on Multicore Milan EPYCs
- Bug with snap-up sector stalled in FinalizeReplicaUpdate
which caused the creation of https://github.com/filecoin-project/lotus/pull/8177

James Hoang - https://github.com/filecoin-project/lotus/issues/created_by/jamerduhgamer
- Assisted in some Lotus feature testing since Apr 22, 2021. Found an issue where unsealed copy of a sector containing a deal would stay on the remote worker during an offline deal.
- Bug with snap deals creating unsealed copy even though the config is set to false
- Improvement with allowing control addresses to be added using a worker address
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Aiming to be a leader in Web3 Storage as well as an ecosystem multiplier (for the Filecoin ecosystem).
Country of Registration - United States of America
Size of the Organization - 35+ employees
Time since inception - 1.5 years (November 2020)
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Company Website - https://www.piknik.com/

Co-founder - Kevin Huynh
Co-founder - Patrick Yu
VP of Research and Development - Benjamin Højsbo
LinkedIn Links and Profiles for the above - https://www.piknik.com/about
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
New Articles
Filecoin Foundation - Storage Provider Spotlight - https://filecoinfoundation.medium.com/filecoin-storage-provider-spotlight-piknik-daf8bad5645d

Bloomberg - What you Need to know about Web3 Crypto’s Attempt to Reinvent the Internet - https://www.bloomberg.com/news/articles/2021-12-10/web3-is-crypto-s-attempt-to-reinvent-the-internet-here-s-what-you-should-know

Energy Web - https://medium.com/energy-web-insights/protocol-labs-and-energy-web-complete-first-showcase-of-an-open-source-solution-to-decarbonize-1a8c22ac02f5

Filecoin Foundation - PiKNiK’s ESPA Makes Way for Web3 Enterprise Storage on Filecoin - https://filecoin.io/blog/posts/piknik-s-espa-makes-way-for-web3-enterprise-storage-on-filecoin/

Filecoin Foundation - PiKNiK—The Rising Tide That Lifts All Boats - https://hub.filecoin.io/case-study-piknik

Social Media Profiles
PiKNiK LinkedIn - https://www.linkedin.com/company/piknikus/ - 538 Followers
PiKNiK Twitter - https://twitter.com/piknik_us - 260 Followers
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
James Hoang LinkedIn - 226 connections
https://www.linkedin.com/in/james-hoang-542257138/

Kevin Huynh LinkedIn - 500+ Connections
https://www.linkedin.com/in/kevinforthehuynh/
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
Kevin Huynh and Benjamin Højsbo featured Panelist in Filecoin Orbit Green - https://youtube.com/clip/UgkxXJ5YnMr5i8QY23PMlJOyMt-iFtxAWo6h

HackFS Summit Panel with Kevin Huynh and Stuart Berman - https://filswan.medium.com/hackfs-storage-providers-summit-panel-for-storage-business-opportunities-5bc8b59fc09

Stuart Berman in Consensus 2022 - https://www.coindesk.com/video/consensus-2022-foundations-filecoin/

Stuart Berman in Lagos Filecoin Orbit Meetup - https://blockbuild.africa/filecoin-orbit-lagos-hosts-fil-storage-provider/

Michael Fair, CRO of PiKNiK in Channel Future Interview - https://www.channelfutures.com/people-on-the-move/storage-provider-piknik-nabs-channel-vet-michael-fair-as-cro/?ppage=2


```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
PiKNiK will allocate different amounts of DataCap depending on several factors for the Storage Providers that the client plans on working with.
1. Trust and reputation - It is important that the Client we are allocating DataCap towards is reputable and can be trusted to correctly use the DataCap.
- Check SP's miner actors through the use of blockchain explorers like filfox.info and the Starboard reputation system - https://sprd.starboard.ventures/home
- Check SP team's social media, LinkedIn, and Filecoin Slack involvement for their reputability.
- Check SP's miner actor's data center colocation to see if they are able to store data using best practices.

2. Previous usage of DataCap - PiKNiK will do spot checks on the Clients to see if they are allocating the DataCap properly (i.e. 5 copies of the Dataset on 5 different SPs and not 1).
- Check the following datacap and how much is going to each of the SPs that the client said they would work with. This will be tracked in: https://docs.google.com/spreadsheets/d/1ZgzkpAx5uQsdcVEk11W2NvDkyKKwo4YGEnyzKzaeMWE/edit?usp=sharing

3. Size and scalability - Increasingly large DataCap requests should only be given to clients that are willing to further the Filecoin ecosystem and are working with SPs that have the same vision and can also support the datacap being allocated to the client.
- Check that the client’s SPs have enough capacity to store the data and how much more capacity they plan on allocating.
- Check that the client’s SPs are following best practices when it comes to their data redundancy plans.
- Check that the client’s SPs can support and seal the deals in a reasonable amount of time. (TiBs per day).
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
PiKNiK will use a secure hardware wallet where only organization executives will have access.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
PiKNiK will do its due diligence in checking which SPs that the client plans on sending the DataCap. Ideally they are a notable contributing member in the Filecoin ecosystem or have some other reputational sound background.

Client Diligence Process
1. Check if the client has any miner actors and if they do, use blockchain explorers like filfox.info and the Starboard reputation system to see if they are knowledgeable about Lotus deal making and sealing.
2. Check the client's social media, LinkedIn, and Filecoin Slack involvement for their reputability.
3. Check if the client has participated in any community events.

Other methods to evaluate legitimacy includes the domain of the email the Github user communicates from, the website domain age, searching the originality of texts, and reviewing the dataset sample with respect to the claimed size and dataset description. 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will use the address in which they are requesting DataCap and check all of the deals that a client is sending out to other SPs. We will also use the Slackbot to check that the total amount of DataCap is even distributed amongst the SP nodes participating in storing the dataset.

We will retrieve the data to make sure the that data that is receiving datacap is consistent with the dataset description states in the LDN to maintain honest datacap use.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
In public on the GitHub repo in the governance and filecoin-plus-large-datasets repositories.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Publicly Shared Spreadsheet - https://docs.google.com/spreadsheets/d/1ZgzkpAx5uQsdcVEk11W2NvDkyKKwo4YGEnyzKzaeMWE/edit?usp=sharing
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
4
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
100 TiBs allocated in previous round
https://github.com/filecoin-project/notary-governance/issues/438
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
We currently work with Fenbushi Capital, Kernelogic, Dcent and Greaterheat on some of the LDNs.
```

**Comment by panges2** [comment]
Hello @jamerduhgamer,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by jamerduhgamer** [comment]
Hello @panges2, the email has been sent to NOTARYELECTION@FIL.ORG. Let me know if you need anything else 🙂

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[776.pdf](https://github.com/filecoin-project/notary-governance/files/10159575/776.pdf)

**Comment by Kevin-FF-USA** [comment]
@jamerduhgamer 

Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to continue as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @jamerduhgamer, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by jamerduhgamer** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacea674cr3vlol3hzacegdcopkurcsoz3m7n4uk6xjf32gsuhi7uewu
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea674cr3vlol3hzacegdcopkurcsoz3m7n4uk6xjf32gsuhi7uewu
