### ISSUE TITLE
Notary Application: Nebula Block Data 

### ISSUE THREAD

**Issue by bq1024** [filecoin-project/notary-governance#777]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:  Boqian Wang
- Affiliated organization: Nebula Block Data
- On-chain address to be notarized (recommend using a new address): TBD
- Country of Operation: Canada
- Region of Operation: North America
- Use case(s) to be supported: Developer Tools, Public or Open Data, Media & Entertainment 
- DataCap requested for allocation (10TiB - 1PiB): 100TiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
As a data center services provider and blockchain practitioner, we are one of the earliest participants in the Filecoin ecosystem in North America. Nebula Block has been contributing to the Filecoin network and ecosystem since 2020. Currently, Nebula block is one of the biggest web3 hosting providers in North America, which works with 4 data centers across the world, and hosts more than 3000 servers with 700 PiB storage. 
Nebula Block provides one-stop-shop data center services and customized IDC hosting solutions for long-term R&D on the Filecoin network. 
With years of ample development and operational experience in web3, Nebula Block team also provides “one-stop shops data center” solutions for storage providers participating in the Filecoin network. 

- Participated in the Filecoin Space Race program and ranked 5th place North America Region: https://spacerace.filecoin.io/?region=021 (NBFS Canada). 
- Participated in Slingshot phase 1 and phase 2. 
- Participated in the Slingshot Restore Program as SP. 
- We were selected as minerX fellow, participated in early-stage testing, and helped improve louts and other ecosystem projects.  
- Participated in various events organized by Protocol lab, such as Fil-Toronto and Fil-Singapore in 2022. 
- Participated in the Dato Dao Hackathon hosted by Filecoin Foundation, Filswan, and ChainSafe, and ranked 1st place in Computing Over Data track. Our project name is IPFS Computing Router. 
    - Data Dao Hackathon: https://dorahacks.io/zh/hackathon/27/ 
    - IPFS Computing Router: https://dorahacks.io/buidl/3442 

GitHub handle: https://github.com/Nebula-Block-Data 

Storage Provider IDs: f019104, f02401, f01276, f0165400, f0145874, f0157535, f0447183, f01091840, f01938223, f01786736 
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
We have over 170,000 FIL at stake, and over 125,000 FIL locked as Initial Pledge. (Storage Provider IDs: f019104, f02401, f01276, f0165400, f0145874, f0157535, f0447183, f01091840, f01938223, f01786736) 
```

How did you acquire the FIL cited above?
```
Owned by Nebula Block Data. 
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
As a member of the Filecoin community, Nebula Block Data has developed tools and platform to help the Filecoin ecosystem grow 
- NBFS POOL(https://nbfspool.com/#/) provides professional and security Filecoin hosting solutions. 
- IPFS Computing Router(https://github.com/Nebula-Block-Data/ipfs-computing-router) enables users to store and fetch datasets from the closest IPFS node and upload the training result to the same node available.

```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
We were selected as minerX fellow, participated in early-stage testing, and helped improve Louts and other ecosystem projects 
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
In 2020, Nebula Blockchain Frontier Solutions Inc. (NBFS) was founded in Canada and headquartered in Montreal, the AI capital of the world. Over the years, our continuous efforts have led us to lead data center services and play as Filecoin’s top eco-developer and storage operator in North America. Our areas of expertise include customized IDC hosting, whole cabinet rental, overseas purchasing, overseas server hosting, and outdated hardware recycling services.  
For now, Nebula block has a team of 20 people, of which eight work in the operation team. Over 70% of our employees hold a master's degree or above, and most of our staff have at least ten years of experience in operation or management. 
Currently, Nebula block is the biggest web3 hosting provider in North America, which works with 4 data centers across the world, and hosts more than 3000 servers with 700 PiB storage. 
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Nebula block Website: https://www.nebulablock.com/ 
Nebula block Twitter: https://twitter.com/nbfsdata 
Nebula block LinkedIn: https://www.linkedin.com/company/nebula-block/ 
Nebula block Medium: https://medium.com/@nbdata 
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
Fil-Toronto: https://beincrypto.com/filswan-fil-toronto-summit-successfully-concluded/ 
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
GitHub: https://github.com/bq1024
Slack: Boqian – NBFS 
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://fil-toronto.com/speaker/boqian/
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and the rate at which you'll allocate DataCap.

The allocation strategy is to ensure the Datacap meets the needs of the ecosystem and will be better used. We will measure the applicant's qualifications along two dimensions：
1. Applicant qualification requirements,
2. Categories of applicant

> **1. Applicant qualification requirements, please see the table below:**

For the new applicants, we identify the applicant’s status and reputation, for example, we will visit the applicant’s official website, social media, LinkedIn, and filecoin slack to get a general idea about the organization or individual. And we try to check the company's registration information with the government to confirm the information they submit is true as well. Usually, individual applicants will receive fewer DataCap than organizations.
We are building an internal tool on a reputation system where customers are graded from 1-10. The factors calculated include, but are not limited to: contributions to the community, terms of work within the ecosystem, community reputation, GitHub activity, allocation of credit history， deal success rate, miner behavior (if they have miners), decentralization of the storage, duplicate copies, compliance with local regulations, data quality and data cited by users.
We tried to build a system that shows the clients' task sending history and the miner's deal reputation history.
                                    
 **Applicant qualification requirements**

<img width="551" alt="image" src="https://user-images.githubusercontent.com/78975968/202351355-1e02dc26-68f5-495f-9c95-37c55541f6f8.png">

> **2. Categories of the applicant.**

We use the “Applicant qualification requirements “for examination.  According to applicant categories and adopt a phased allocation strategy for each allocation of DataCap, which can be summarized as follows.
(a) There are different allocations and rules for different categories of clients.
(b) The approved DataCap will be delivered to the applicants gradually. The usage of datacap will be monitored to ensure that applicants are using datacap correctly.

**- Allocation of shares by applicant categories**

First, we classified applicants into 
(a) general users 
(b) web3 developers 
(c) corporate entities or organizations. 
It is predicted that 20% of our DataCap quota will be allocated to general users, 30% will be allocated to web3 developers, and the remaining 50% will be allocated to corporate entities or organizations.

Therefore, there are different rules that apply to these three types of applicants.
(a) For general users, background verification will be performed. To promote the use of Filecoin among the general user community, the verification for general users will be minimized by allocating a maximum of 2 times per person, with a maximum of 1Tib per application, and the approval of the second application will be based on the applicant's rating.

(b) For web 3.0 developers, will be the ones who are highly supported. To ensure their authenticity, they are verified based on the GitHub registration time and the website content of their web3.0 application. The verification for web 3.0 developers will be minimized by allocating a maximum of 5 times per user, with a maximum of 1Tib per application there is a maximum of 10Tib per application. The second approval will be based on the qualification of the applicant and the applicant's first datacap usage.

(c) For entities, 50% of the DataCap quota will be used for this category. The DataCap quota market is now relatively mature. On the one hand, we are working to deepen our cooperation with existing applicants. On the other hand, we have already worked with the community to identify some potential quota applicants. We encourage these applicants to bring data to Filecoin, which will help the Filecoin ecosystem to develop further.

- **Phased allocation of shares**

First, the applicant's DataCap will be allocated in stages, and the applicant will normally only receive 20% of the allocated share in the first stage. Only if it is determined that the current phase share is being used correctly will it be possible to receive the next phase share allocation. First, Applicants must meet the” Applicant qualification requirements “. Second, we will evaluate the applicant's score at each stage, which will influence their next application.

> The allocation process is as follows:

(a) The review process is initiated with each applicant providing an application within 24 hours of its launch.
(b)Based on the information provided by the applicant, an initial review will be performed. we will use "Applicant qualification requirements” to review their application. The applicant must have a reasonable need for data storage. The requested share size must match the data storage requirements.
(c) If we have questions about the initial review applicants will be asked to provide additional information and if the applicant refuses to provide additional information without reasonable cause then the application will be denied. The applicant will be notified in writing to confirm whether the application has been granted or denied.
(d) For individual users and web3 developers, they will proceed to the DataCap review where we simply check their background; for organizations, applicants who pass the initial review will proceed to the due diligence phase.
(e) For organizations that pass the due diligence, and for individual users and web3 developers that pass the initial review, the rating scoring process will begin. Shares will be awarded based on their storage needs and rating results. But there must be a 7-day cooling off period between requests for allocation.
(f) Applicants' DataCap usage will be tracked and spot-checked on an ongoing basis.

For all applications, we require a track record from submission-review-approval-transaction tracking. Approval requires the signatures of two officers and a tracking system. An applicant's allocation may be reduced or canceled if the applicant violates the terms, policies, or conduct of the Filecoin community.
If an applicant believes that any process or conclusion is incorrect, they may file a complaint.

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
A Ledger wallet will be used to securely store the keys associated with the DataCap distribution address. 
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
- To review the applicants who are applying for DataCap, we will visit the official website, social media, LinkedIn and filecoin slack engagement of applicants to get a general idea about the organization or individual. The information we check on applicants depends on their category, as follows:
(a) For individual users, we verify their identity and ensure basic information only.
(b) For web 3.0 developers, we verify their GitHub registration year, activity level, project content, and project website, and confirm their role in promoting Filecoin in decentralized applications.
(c) For organizations, we verify the company's registration information with the government to check the information they submit is true. And we need to confirm their data sources, data samples, detailed usage plans, etc.

- The purpose of auditing DataCap users is to ensure that applicants are using them in the correct way to store real and valid data. The following includes a review of the surveys of applicant information prior to approval and a review of DataCap usage after approval. The review is based on the principle that it is the responsibility and obligation of the applicant to use the DataCap only for approved purposes. Since the DataCap is allocated according to the principle of phased allocation, the subsequent quotas of applicants who do not pass the review will be postponed or even canceled. The review paths are as follows:
(a) We will check the number of deals sent, the number of dataCID, and the deals distribution among all the storage providers. For unencrypted data, we will conduct random search sampling, and if the applicant has irregularities in issuing DataCap, we will take measures to stop further issuance.
(b) We establish a reputation scoring system to score the applicant during the usage process, which will affect the next phase of the applicant's quota allocation and the next DataCap application, further promoting the applicant's proper use of the quota he/she receives.
Following the above audit process, we will classify the applicants according to their results.

- We accept requests from applicants who share the same vision and are willing to grow the Filecoin ecosystem. 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We will check the historical usage of DataCap as follows. 
- Check the applicant's historical DataCap usage to see if they have allocated the correct volume of DataCap. 
- Verify if the data are assigned the exact DataCaps per SP as described by the applicants. 
Firstly, we will start by checking all the deals that a client is sending out to other SPs. 
Secondly, we will confirm that our clients have not used their previously acquired DataCap improperly. To verify all the above information, we will use an automated script that will check the volume of DataCaps coming into each SP node, where they are sending the verified deals. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be noted in the GitHub repository.  
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L4
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
Filswan. Nebula Block Data nodes are getting deals from multichain storage.
```

**Comment by panges2** [comment]
Hello @bq1024,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Kevin-FF-USA** [comment]
@bq1024,
Do you currently have a ledger/address?

**Comment by bq1024** [comment]
> @bq1024, Do you currently have a ledger/address?

I do not have a ledger for now, but I ordered one and it is on the way, I will get it very soon.

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[777.pdf](https://github.com/filecoin-project/notary-governance/files/10159576/777.pdf)

**Comment by Kevin-FF-USA** [comment]
@bq1024 

Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @bq1024, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by bq1024** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebfjdimkmaigamylouupxjv3u4pkgpoqwms5zsx4pe7rf2innlhb2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfjdimkmaigamylouupxjv3u4pkgpoqwms5zsx4pe7rf2innlhb2
