### ISSUE TITLE
Notary Application: FilSwan

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/notary-governance#778]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary
Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the
following form.

## Core Information

- Name: FilSwan
- Affiliated organization:  FilSwan
- On-chain address to be notarized (recommend using a new address):
- Country of Operation: Canada
- Region of Operation: North America
- Use case(s) to be supported:
  Professional Services,Developer Tools,Decentralized Applications,User Content,Public or Open Data,Media &
  Entertainment
- DataCap requested for allocation (10TiB - 1PiB): 100TB
- Are you applying on behalf of yourself or an organization?: [Individual, Organization] Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as
much detail as you can in your answer!_

### Time Commitment

Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles,
Storage Provider IDs, significant projects or contributions (with links).

```
Start from 2021, FilSwan has been working on Filecoin Ecosystem. FilSwan as a community project starts from 2020, it is the first project starts processiong deals. It also paticipated in lots of projects like slignshot.

FilSwan paticiated the Filecoin major community acvities like:
- Filecoin Space Race     2020
- Filecoin Mainnet Launch 2020
- Filecoin Labweek        2021
- Slingshot 2             2021
- North America Storage Working Group Member  2022
- Filecoin Austin         2022
- Filecoin Toronto(host) 2022
- DataDao Hackathon(host) 2022 
- Filecoin Singapore      2022
- Fil+ notary round 2     2021
- Fil+ notary round 3     2022
...


GitHub: https://github.com/filswan 

FS3: https://github.com/filswan/fs3
multichain storage: https://github.com/filswan/multi-chain-storage


```

### Stake Exposure

Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating
evidence (i.e., addresses on chain with their corresponding FIL amounts).

```
FilSwan is an ecosystem project, has about 3000 for development purposes.
```

How did you acquire the FIL cited above?

```
N/A
```

### In-protocol Reputation

Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links
where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help
the Filecoin ecosystem grow.

```
We are working with Chainlink with data provider project.
Actively participating and helping the Filecoin miner community (more than 13k messages on slack)
- Participating to HackFS
- Filecoin Obit project
- report bugs and other issues: https://github.com/filecoin-project/lotus/issues/created_by/flyworker
- Discussion in devgrants https://github.com/filecoin-project/devgrants/blob/6e12c1659cb588235010d27618623295db2a0249/rfps/new-mining-tools-rfps.md
- fil-starling-collab, providing miners and collaboration with storage deal testing
Filecoin space race community lead reward.
Filecoin Onboarding client granted https://github.com/keyko-io/filecoin-clients-onboarding/issues/38, setup miners list for sending deals

Recently Filecoin Community activities:
- Space Race Miner Show & Tell, Spe. 4th 2020,https://www.youtube.com/watch?v=jqbfETY3v6Q&t=1136s
- Slingshot - Phase 1 Closing Ceremony, 28 Oct 2020 https://www.youtube.com/watch?v=qheNJZ1DClM&t=4089s
- Filecoin as a Decentralized Substrate for Computing, 28 Oct 2020 https://www.youtube.com/watch?v=pvJaOhbGhGw
- Fil Toronto 
- Data Dao hackathon
```

### In-protocol Security

Please describe your contributions to the security of Filecoin and the duration over which you've made contributions.
Please also include any links or references that can substantiate your contributions.

```
Please answer here. 
```

### Organizational Reputation

Please describe the nature of your organization, including the country of registration, size of the organization, and
time since inception.

```
Founded in 2021, FilSwan is the leading Filecoin application development company based in Montreal Canada. It has more than 30 employees and running more than 10 nodes to support the filecoin ecosystem.

FilSwan is invested by FBG Capital, SNZ Capital and Binance Labs.
```

Please share any relevant details to help substantiate information about your organization (website, named officers,
links to social media profiles).

```
💻Website：https://filswan.com
📱Telegram：https://t.me/filswan
📱Twitter: https://twitter.com/0xfilswan
💻Facebook： https://www.facebook.com/filswan.technology
💻Medium：https://filswan.medium.com
💻Discord: https://discord.com/invite/KKGhy8ZqzK
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles,
etc.)

```
Please answer here.
```

### Individual Reputation

Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the
approximate size of your audience (i.e., followers, subscribers) for each one.

```
https://twitter.com/0xfilswan 11K fillower
https://discord.com/invite/KKGhy8ZqzK 3500 User
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts,
videos, awards, etc.)

```
https://blog.chain.link/filswan-chainlink-filecoin-joint-grant
https://www.binance.com/en/blog/ecosystem/%E2%80%8Bbinance-labs-launches-season-4-of-its-incubation-program-with-14-earlystage-startups-421499824684903808

```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)

### Allocation Strategy

How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much
specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.

| Factors  | Details | Rating Weight |
| :---         |     :---      |          :--- |
| Ecosystem Value | The data should be meaningful for the Filecoin ecosystem. e.g. some data record random or meaningless data will be rejected.| 40% |
| Technology | Client should show they have enough technology to manage the deal transfer and result tracking. Data used in slingshot is not qualified since participants already get the reward from competition.  | 20% |
| Past History | Client past successfully complete the data quota will be a plus, other wise it will be decrease the allocation | 20% |
| Legal | The content upload should have no copywrite issue and qualified the local law and governance. | 20% |
```
The purpose of allocating the DataCap is to make sure clients use these DataCap in a manner fit the ecosystem needs.
For new applied clients, we need background check about his/her information, usually individual will be granted less Datacap than organizations.
We are building an internal tool about the reputation system, clients have a score from 1 to 10, factors be calculated will include but not limited to: contribution to the community, working terms inside the system, community reputation, GitHub activity, past allocation credit history, deal success rate, miner behavior (if they have miners), decentralization of the storage, duplications of the copies, compliance with local regulations, data quality, data cited by users.

With Filswan.com we have built a system shows the clients task sending history, the miners past deal reputation history, you can check a sample here: https://www.filswan.com/#/miner/f010479
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating
the DataCap?

```
With all the applications we asked a tracking record from submission – review-approval -deal tracking. The approval needs two sign officers’ approval, and the system tracking record need to be in place.

Individual DataCap start from 1GB up to maximum 5TB, organizations start from 10GB to maximum 10TB. They can ask for a 10% incremental of next application after used current Datacap, but a cool time of 7 days is mandatory between two allocation requests.

Client allocation can also be decreased or cancelled if they violated the terms , policy can conduct of Filecoin community.

Client can apply for arbitrage if they believe any process or conclusion in incorrect.
```

### Client Due Diligence

How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed
well and that clients can properly handle the DataCap you intend to allocate to them?

```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 

In the early stage, all clients are required for an onboarding process to be qualified. Firstly, I need to collect information including:  
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information. 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name.
 - street address (P.O. box number is not acceptable). 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence. 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

 With these provide, an interview and data source checking process need to go through. After that, an agreement should be signed for the next step - gradually allocate datacap and let the client gather more credit. 

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This
includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals
with a single SP entity.

```
Periodical inspection and audit of DataCap usage

Scan tools for monitoring verified deals with miners, content scanning tools for violation of local law and policies, usage of the data, verified data distribution.
https://filplus.d.interplanetary.one/clients

```

### Bookkeeping Plan

Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email,
Telegram, etc), or both?

```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 

In the early stage, all clients are required for an onboarding process to be qualified. Firstly, I need to collect information including:  
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information. 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name.
 - street address (P.O. box number is not acceptable). 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence. 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

 With these provide, an interview and data source checking process need to go through. After that, an agreement should be signed for the next step - gradually allocate datacap and let the client gather more credit. 
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?

```
Yes, I plan on keeping records of our allocation decisions via a GitHub repo. We will also build a open source project for auditing purpose.
- The allocation plan and criteria is public accessible  
- Each approval and allocation is on GitHub
- All the conversation of datacap interview with client is recorded under the awareness with the client and saved in secure place.
- Client submission related documents are securely saved for future auditing.
- Client data quatation usage is online traceable.  All the datacap alocated will be saved in database for future analysis and auditing. 
We are open to any audit requests.
```

### Engagement in Program

Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes
making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues,
attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments
please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630)

```
5
```

### Past allocation

Have you previously received DataCap to allocate before? If so, please link to any previous applications.

```
https://github.com/filecoin-project/notary-governance/issues/433
```

## Disclosures

Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please
list the names of the Notary individuals or organizations you may be related to.

```
No
```

**Comment by panges2** [comment]
Hello @flyworker ,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Since you are applying on behalf of an organization, please email NOTARYELECTION@FIL.ORG from your Organizations email account. 
*This cannot be from your personal account. You Must include the address of your Organization.  

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Kevin-FF-USA** [comment]
@flyworker ,
Do you have a wallet address?

**Comment by flyworker** [comment]
yes, I have, should I use the old one or has to be a new one?
thanks

**Comment by flyworker** [comment]
> @flyworker , Do you have a wallet address?

yes, I have, should I use the old one or has to be a new one?
thanks

**Comment by Kevin-FF-USA** [comment]
@flyworker 

Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to continue as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by flyworker** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceco63gadd2dg2lk3xjfiz2sn5spgq6owourrdkt6ze2k2uyzateq2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceco63gadd2dg2lk3xjfiz2sn5spgq6owourrdkt6ze2k2uyzateq2

**Comment by flyworker** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecpq32q6z7zobfzab3cmbmx32rx6oel464xcte5ql5yrk3d7fzqco
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecpq32q6z7zobfzab3cmbmx32rx6oel464xcte5ql5yrk3d7fzqco

**Comment by flyworker** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedapsqhrggsxwjewy232gih6brfksek47aoh43rimopecvsiys45y
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedapsqhrggsxwjewy232gih6brfksek47aoh43rimopecvsiys45y

**Comment by flyworker** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacednhpaocq42j63jvy2ve37e5worwm6gb2zlasaoenuazbq5hh77uq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednhpaocq42j63jvy2ve37e5worwm6gb2zlasaoenuazbq5hh77uq

**Comment by flyworker** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebimybqa7pstysbd7y4jir5v627mfgzoj6lnc5au7o5m46znc45u2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebimybqa7pstysbd7y4jir5v627mfgzoj6lnc5au7o5m46znc45u2

**Comment by flyworker** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebr3yj4kb6sku3ykmq4htdtrvkc2aw4aaay4mmdlizgfrvuhpmku4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebr3yj4kb6sku3ykmq4htdtrvkc2aw4aaay4mmdlizgfrvuhpmku4

**Comment by flyworker** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedbefglich2du4csyetfjfgljd4rvsfqvauv7o5bpaom2p4dv3odg
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbefglich2du4csyetfjfgljd4rvsfqvauv7o5bpaom2p4dv3odg

**Comment by flyworker** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacedddlg5zflh4jg5reukg52xfhzmyu5uqbsqjh5mfewwjfz3vyfhc6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedddlg5zflh4jg5reukg52xfhzmyu5uqbsqjh5mfewwjfz3vyfhc6

**Comment by flyworker** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacebgywxbalezaee6yckjl25n7mpa6iiedpc54fmh45bortj5hmylr4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgywxbalezaee6yckjl25n7mpa6iiedpc54fmh45bortj5hmylr4

**Comment by flyworker** [comment]
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzacecsvtr7zx2w44c2naubumi6cp2az4liv7hdgub75vs2bplnba4ibc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsvtr7zx2w44c2naubumi6cp2az4liv7hdgub75vs2bplnba4ibc
