### ISSUE TITLE
Notary Application: Nick Merrick

### ISSUE THREAD

**Issue by NMerrick** [filecoin-project/notary-governance#779]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: Nick Merrick
- Affiliated organization: 
- On-chain address to be notarized (recommend using a new address): f1e2phy4fzi2dzx75dqwpvzg25iu7dqjdoquyt4fy
- Country of Operation: United States of America
- Region of Operation: North America
- Use case(s) to be supported: Professional Services, Developer Tools, Decentralized Applications, User Content, Public or Open Data, Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB): 1PiB
- Are you applying on behalf of yourself or an organization?: Individual

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
I am new to the FileCoin ecosystem but a firm believer in the use case and potential for this project. 

Github: NMerrick
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Prefer not to disclose. 
```

How did you acquire the FIL cited above?
```
N/A
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
N/A
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
N/A
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
N/A
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
N/A
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
https://www.facebook.com/nick.merrick.5/
528 friends

https://www.instagram.com/merrick_nick/
311 followers
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
N/A
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Candidates for datacap allocation should be thoroughly vetted to ensure best standards and practices with respect to the principles of this project. That being said, clients will be checked along the following criteria prior to allocation of datacap:
Taking a look at the company's website and making sure the information listed is legitimate.
Querying government websites where the organization resides and authenticating claims made.
Analyzing sample use and data sent by the organization upon application to ensure proper utilization of the Filecoin network.
Tracking miners used by potential clients to ensure no self dealing, etc. 
Check Slack and Github for previous logs of organization's activity. 
Analyzing previous datacap usage by organization.
Communicating with other notaries to verify organizational integrity. 

Depending on the solidity of the organization and the use case(s) requested, I will allocate datacap according to Filecoin best standards and practices. 

Clients that submit only partial records requested, whether that be records held by respective government organizations, proof of use case, or website and verification identification, will receive only limited datacap until details can be further solidified. 
If clients comply with all requests and submit all requested documentation to verify identity and validity of use, they will be granted their full request. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Datacap will protected on a secure, personal hardware wallet. 
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
Candidates for datacap allocation should be thoroughly vetted to ensure best standards and practices with respect to the principles of this project. That being said, clients will be checked along the following criteria prior to allocation of datacap:
Taking a look at the company's website and making sure the information listed is legitimate.
Querying government websites where the organization resides and authenticating claims made.
Analyzing sample use and data sent by the organization upon application to ensure proper utilization of the Filecoin network.
Tracking miners used by potential clients to ensure no self dealing, etc. 
Check Slack and Github for previous logs of organization's activity. 
Analyzing previous datacap usage by organization.
Communicating with other notaries to verify organizational integrity. 

"Have you ever worked with the Filecoin ecosystem before?"
"What is your use case for this datacap?"
"Can you provide sample data for your use case?"
"Can you provide documentation verifying the identity and/or licensure of your organization?"
"Can you contact me via Slack within the Filecoin community so I can further verify your identity?"
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1. Investigate client and ensure integrity of their organization.
2. Check miners and addresses to exclude any doubt with respect to self dealing, fraud, etc.
3. Comb through Filecoin organizational logs (including Slack/GitHub) to ensure no previous misdealing occurred.
4. Ensure previous datacap usage is in alignment with previous dataset descriptions to safeguard against violations of standards and best practices.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
All allocation decisions will be conducted publicly in Github, using proper public Github repos (https://github.com/filecoin-project/filecoin-plus-client-onboarding)
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
I will have a public Google Sheet where I record all allocation decisions.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L2
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
No. 
```

**Comment by panges2** [comment]
Hello @NMerrick,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Please email NOTARYELECTION@FIL.ORG from the email account linked to this GitHub account. *The email MUST COME from the same account you used 

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Your Organization
3. Your Country of Operation
4. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
5. Link to your GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by galen-mcandrew** [comment]
Please see attached for initial notary scoring by governance team. Thank you for applying!
[779.pdf](https://github.com/filecoin-project/notary-governance/files/10159582/779.pdf)

**Comment by Kevin-FF-USA** [comment]
@NMerrick 

Thank you for applying to serve as a Notary in support of the Filecoin Plus program. After review of your application and a diligent scoring of your past and potential future contributions to the program, you have been selected to onboard as a Notary in this 4th round of elections. 

In the coming days you will receive an onboarding training checklist. It will walk you through the steps to verify your ledger verification in [https://plus.fil.org/](https://plus.fil.org/) as well as outline the best practices and responsibilities for a Notary in the Program.

Next steps

1. **By 20 December** - Complete the CONTACT AND DISCLOSURES form
    1. [https://airtable.com/shrjx52lvefitwdq6](https://airtable.com/shrjx52lvefitwdq6)
2. **By 30 December** - Ensure that the [Governance meeting time is on your calendar]( [https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles) ) and make scheduling plans which allow you to commit to attending per your SLA level expectations. ([L1-L5]( [https://github.com/filecoin-project/notary-governance/issues/630](https://github.com/filecoin-project/notary-governance/issues/630))) 

Please reach out to Galen, Kevin-FF, or Philop on Slack if you have any questions.

**Comment by panges2** [comment]
Hi @NMerrick, this is a kind reminder to get your ledger verified by Wednesday, Feb 8. To connect and set up your account in the Registry, please follow this short guide.
https://docs.google.com/document/d/1VCksV4_roLSTmaPqZJ8u643rykC0A7Z53YBDUoIY1xc/edit?usp=sharing
For a longer video walkthrough - see here: https://drive.google.com/file/d/1HFvRjjplt4NpRz4P67320D2g3Z42ePzj/view

**Comment by panges2** [comment]
Hi @NMerrick,  this is another reminder to get your ledger verified as soon as possible. Thank you!

**Comment by NMerrick** [comment]
Hello @panges2, @Kevin-FF-USA, and @simonkim0515! I am having issues with the verification process. 

I have my ledger connected with the Filecoin app opened with expert mode enabled. I sign into the registry as a notary with ledger connected, and click the button to approve the request, but I am not receiving a message on my ledger device to approve. 

I got on a Zoom meeting with Kevin, it looks like everything is verified from the transaction history, but I just thought I should check in.

**Comment by Kevin-FF-USA** [comment]
Hi @NMerrick 

Thanks for flagging.  Can you try this one more time, but this time - capture the console logs so we can troubleshoot on backend.   (right click after you select VERIFY)
![image](https://user-images.githubusercontent.com/94004586/221665717-ebb74840-0eac-4094-9fc8-0f693f4932d9.png)

**Comment by NMerrick** [comment]
Of course, let me know if there is anything else I can help with. 

![error2](https://user-images.githubusercontent.com/62187230/221765028-e3a92fc7-e1a4-488f-8ed9-76b2d3e18306.png)
![error3](https://user-images.githubusercontent.com/62187230/221765030-6b64ec6a-d7a2-4484-8ea8-34d529b2bf19.png)
![error4](https://user-images.githubusercontent.com/62187230/221765031-305ffedd-aa26-482f-9c77-236b2d62e70f.png)
![error1](https://user-images.githubusercontent.com/62187230/221765033-8ea29aa9-aad1-4bc0-a88a-635003df016a.png)
