### ISSUE TITLE
Discussion: Notaries' entity should be in the same region of they applied

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/notary-governance#78]
## Issue Description
We noticed a HONG KONG hold company get the notary of North America, but their Registration Country is HongKong, China

Nature:  private company
Registration Country: HongKong, China

from their twitter and other social media reports you can see their major activities are in China.
https://finance.yahoo.com/news/2020-distributed-storage-summit-ended-124500305.html
https://36kr.com/topics/836219830696069
http://www.cnr.cn/rdzx/cxxhl/zxxx/20201127/t20201127_525344968.shtml
http://www.chinanews.com/business/2020/11-20/9343298.shtml
https://www.businesswire.com/news/home/20200916005395/en/
http://prnews.techweb.com.cn/qiyenews/archives/188809.html
https://www.myzaker.com/article/5f73ee418e9f096d9936e298/
https://apnews.com/press-release/newswire/4190dd75a9d3a4cc6719ba648929b7bc
https://finance.yahoo.com/news/mr-wu-wenjie-chairman-xnmatrix-150000958.html
https://tech.sina.com.cn/roll/2020-09-04/doc-iivhuipp2523374.shtml
https://www.8btc.com/article/624455
https://mp.weixin.qq.com/s/i59KYMuh4nZIzsHslRoYGQ
https://mp.weixin.qq.com/s/n5zhW3DKzKAFxf5wV7ONgg
https://mp.weixin.qq.com/s/oTts2731hZoffHACe4TIOg

## Impact

In the Client Due Diligence part , they need the client provide the following information
1. Basic information (small teams, start-up teams)
-Business license;
-Legal person related information, including: ID card, mobile phone number;
-Application with Legal person or agent’s signatures
-Use schedule for DataCap
-Materials or certificates that demonstrate ability and influence

According to the data privacy protection law, and EU GDPR, those are sensitive information, how can we protect the privacy of client data?
US government currently actively  investigating  China organizations like Tiktok,Tencent, Alibaba. It is a potential risk for Filecoin organization involved in the legal issue ask NA clients submit critical information to China owned Entities.  

## Proposed Solution(s)

Only approve the entity in the same region.

**Comment by jnthnvctr** [comment]
This is a fair flag - one of the challenges here is figuring out the right way to define being "based" in North America. 

One challenge we have is that companies can be multinational and have subsidiaries that operate in several geographies (and employees based all over). In the current construction, the definition is: 
1) The company must operate in the region
2) The notary must be in the region

This is perhaps not sufficient - and so we should discuss how to refactor this for the rubric.

As such, it is worth discussing: 
1) How do we want to handle companies that have subsidiaries (i.e. can a NA subsidiary apply to be a Notary for a geography)? 
2) How do we want to handle relationships and ties to other countries (controlling shareholders? parent organizations? global employee base? general perception? revenue proportion?)

The legal concerns are real and valid - and perhaps another requirement that should be added in the rubric and the allocation plan is a strategy for how collected information is stored or shared. Of course even in the short term, Clients should be able to work with a diversity of Notaries - so hopefully if there is mistrust against one, the Clients can work with others (e.g. Filecoin Foundation).

In the case of XnMatrix that was brought up, XnMatrix is [applying](https://github.com/filecoin-project/notary-governance/issues/27#issuecomment-742510047) with a US subsidiary from a US person with an explicit priority given to North American use cases. North American clients and applications are encouraged to apply for DataCap from Dr Shin to the extent that it is compliant and monitor how DataCap is allocated.

In the event an organization falsified information in the application, the appropriate fix would be to file an issue / dispute and to use that process to either remove power or bar from future actions.

**Comment by jnthnvctr** [comment]
Some ideas @zixuanzh  and I were kicking around that might be interesting jumping off points - perhaps there one approach is to treat subsidiaries as standalone companies (still may be tricky for things like "controlled FIL" if it's owned by the parent subsidiary). Another might be to try and determine some metric to "proportion" the representation one has in a geography (i.e. what % of revenue or headcount is employed in that geography)?

**Comment by ann-shin** [comment]
Hi, @jnthnvctr @flyworker , I want to point out some explanations：

1. I got my PhD from Columbia University and my bachelor degree from Berkeley. I always live in the United States. In recent years, I have been active in the field of blockchain and distributed storage for a long time.
2. XnMatrix is ​​a global company with business covering Asia, North America and other regions.We focus on developing the North American market.
3. As we have discussed in our  notary application, we will use the same tooling as the Filecoin foundation. All dataCap allocations will be public. We will give priority to serving customers and miners in North America.

Thank you for your attentions. I believe XnMatrix can do well as a NA notary.

**Comment by flyworker** [comment]
Thanks @ann-shin  for your reply
1. We did not questioning about your professional or living address. we are talk about XnMatrix as a China Entity. I assume you are not the sign officer of that company,but maybe I am wrong.

2. Operational globally does not change the fact your application claimed you are China entity and I believed the 300 employees you claimed are in China not with you in NA. We are talking about the enterprise information and Government ID  privacy issue when you do KYC . If we only consider your NA entity if you have, you might need to be re-scored, e.g , are your parent company in full  liability for the lawsuit potentially happen in the future? Is the collateral you claimed on those node belong to your US entity or China entity?  You need to show the proof of those documents for you to claim you are applying as US entity and still qualified.  
3.  This is something not need to talk about, this is mandatory for any notary's who suppose to serve the region.

**Comment by flyworker** [comment]
> Some ideas @zixuanzh and I were kicking around that might be interesting jumping off points - perhaps there one approach is to treat subsidiaries as standalone companies (still may be tricky for things like "controlled FIL" if it's owned by the parent subsidiary). Another might be to try and determine some metric to "proportion" the representation one has in a geography (i.e. what % of revenue or headcount is employed in that geography)?

Yes, if that can be considered  as qualified US entity , any China miner can find some one setup a company and pay several hundreds dollar for the registration fee fee  then he became a US entity with all the collateral still belongs to China entity.

**Comment by PatrickDeuse** [comment]
@jnthnvctr a entity should have to fully "own" the FIL they put up for this. not a parent company, not a shell somewhere on some island. 

notaries should should be forced to use a set of  "standard terms of use" agreements that are in full compliance with the locality they are operating in. this should include that data is not transferred to any other jurisdictions than the ones the notary applied for. ownership structure of the entity should be made public, including parent entities etc. - if it is not clear who owns/controls the entity they shouldn't be considered.

**Comment by jnthnvctr** [comment]
@PatrickDeuse - how do we prove who owns what address? Couldn't someone just claim that the address is owned by the US entity? Maybe its worth refactoring the definition of the "at stake" portion - perhaps it needs to be something along the lines of "wholly owned (i.e. not received on loan) and [somethign about maintaining control] over the duration of the Notary period"

Re "standard terms" - there was another [thread](https://github.com/filecoin-project/notary-governance/issues/30) about this, but I think it totally makes sense as an addition. I think a reasonable operational guideline is that all Notaries should be acting in compliance with their local regulations (and any collected Data should not leave the geographic region). 

Re disclosure of ownership structure - I think that also seems pretty reasonable, but maybe more tactically what sort of evidence or proof do we want folks to submit?

**Comment by jnthnvctr** [comment]
@PatrickDeuse  - it also occurs to me that perhaps this is actually a really good dID problem that we should be thinking about (perhaps this is a dev grantable thing?). Rather than trusting a notary to handle sensitive data correctly, a better option might be to use something like Civic (or some other dID platform) such that you as the applicant retain control of your data, and you can grant access to the documents (and the Notary can verify that the documents are what you claim).

**Comment by PatrickDeuse** [comment]
@jnthnvctr do you have any idea where the Civic project stands right now? It would only make sense if they have the necessary validators on board already or accept everyone (not everyone, but you, me, us,the fc project, whoever might want to do that work) to do validation of identities to a degree that it is acceptable for fil+ notaries

i see a possible problem with the costs being put on the notary and not the applicant with civic. on the other hand it's outsourcing work the notary doesn't need to do anymore when using civic (or else)

this might actually be a good optional thing to give notaries at hand. a kind of "separation of knowledge" factor you can score right away with the application and later show in a "ranking",list, whatevs

**Comment by jnthnvctr** [comment]
I don't have a good view on the latest with Civic - but I think there's a general shape of a problem here, which I think potentially might be interesting. I've shared this with some folks at identity.org, to see if they have thoughts. 

Generally there is an issue where some Notaries (who are attempting to allocate large amounts of DataCap) may justifiably want to be able to do real due diligence - and that will require some trust. I think having Notaries agree to follow the local regulations / restrictions should be a part of their initial application - and I think it makes sense to add that as a part of the "operational guidelines" that Notaries attest to when receiving their initial allocation. 

Also bumping to the Notaries - to see if they have thoughts on how we can address!

**Comment by askender** [comment]
> HONG KONG hold company get the notary of North America, but their Registration Country is HongKong, China
What is the progress of this issue?

**Comment by dkkapur** [comment]
Closing this out for now. 

Guidance at this moment stands as:

- you can apply from a region where you have a legal entity / establishment
- you can only apply from the region in which you physically are based / will be carrying out the notary duties from
