### ISSUE TITLE
LDN Application Exception Proposal - <Godap>

### ISSUE THREAD

**Issue by jenniferAzhou** [filecoin-project/notary-governance#781]
## Application information 

Link to existing LDN application(s)
- [_link to applocation(s) in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues_](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1248)
  
Are you the data owner?
- [x] Yes
- [ ] No

Is the data private i.e., encrypted or not meant to be retrieved by anyone else on the network?
- [ ] Yes
- [x] No
We will encrypt the private data.

## Data owner information
- Data owner:  CoverMe Communications, Inc
- Data owner's website: [www.godap.com](http://www.godap.com/)
- Data owner's social media account(s):

### Data owner description 
please refer to LDN application #1248
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1248

### What is the motivation behind onboarding this data to Filecoin? 
In Godap's business scenario, customers will create a large amount of content information in pdf/word, xmind/visio, videos, recording, whiteboard pictures, work and life photos, etc. 
Godap should help customers store these original content. We expect a huge amount of storage demand in the future, so we have been looking for safe, reliable and affordable storage service providers. 
IPFS & Filecoin is our best choice now.

### What organizations are involved in this project? Sources of funding, SPs partnering in onboarding, other service providers, etc.?
CoverMe Communications, Inc
TopBlocks (SP)
Dcent @ Hidde Hoogland (SP)
Cabrina (SP)
Feiyan (SP)

## Transparency in KYC
_If you are not the data owner, please email filplus@fil.org with you and the data owner on a thread so at least the Fil+ governance team can act as a lightweight KYC check._

Are you going to offer NDAs to notaries?
- [ ] Yes
- [x] No

## Dataset description 
The files stored in Filecoin are a collection of files uploaded to the Godap platform by users in the past. The files include videos, photos, screenshots, and recordings uploaded by users, which may be an encrypted compressed file. 

### Why is it useful to the Filecoin network?
At present, the main purpose of our storage in Filecoin is for data disaster recovery. In the future, if Filecoin can support small file retrieval, we will upload user original files without packaging and we will also try to directly connect our services to the retrieval market of Filecoin, such as Saturn.
  
## Storage needs

Is the data to be stored in a single region, either due to geopolitical constraints or data owner policy?
- [ ] Yes
- [x] No

### Which SPs will you/the data owner be working with to store the data? 
We have contacted the following SPs:
 
| SP ID | SP org | SP region |
| --- | --- | --- |
| f0143858 | TopBlocks  | San Jose (USA ) |
| f02301 | TopBlocks  | Santa Clara (USA ) |
| f039940 f022289 | Cabrina | chengdu (China) |
| f01046069 | xlcbd | Singapore(SG) |
| f01502887 | oneil8765| Shanghai(China) |
| f01969779 | Nick | Santa Clara(US) |

### How were these SPs identified?
TopBlocks help us to find these SPs.

## Notaries that support the project 
 _Notaries perform KYC/KYB to validate the legitimacy of data and organizations. To find supporting notaries please view the list of [round 3 notaries](https://github.com/filecoin-project/notary-governance/tree/main/notaries) and post your LDN application in the Filecoin slack channel #fil-plus-application-review. Feel free to update the form as you gain support over time and more notaries are willing to support your application._

| Notary name | Notary org | Notary region |
| --- | --- | --- |
| _name_ | _org_ | _region_ |

**Comment by kevzak** [comment]
@jenniferAzhou how can someone become a godap user? The website has no links. Where is user platform? Where is user data?

**Comment by kevzak** [comment]
Can you please include SP IDs? Have Decent, Fei Yan, Cabrina done any KYB on their own?

**Comment by jenniferAzhou** [comment]
@kevzak  please allow me to explain that godap is an ongoing project, and the app is nearing completion. Godap is a sub business of CoverMe. It has not been put on the app store yet, so there is no link on the website. The products under CoverMe have been operated for many years and have accumulated tens of millions of users. Please refer to CoverMe Ws website http://coverme.ws/. These accumulated users will seamlessly transfer to Godap platvorm in the near future, which is part of our product upgrading strategy.

**Comment by jenniferAzhou** [comment]
> 

@kevzak I know that the SP ID of TopBlocks is f0143858, and several other SPs were introduced to me by TopBlocks. So far, I do not know their SP IDs. I may also find more SPs to investigate.

**Comment by jenniferAzhou** [comment]
> 

In addition, when we can confirm that Filecoin provides sufficient data encryption security, we will also store the insensitive data accumulated in the past to Filecoin, which is about hundreds of TiB data, and will continue to increase.

**Comment by jenniferAzhou** [comment]
@kevzak  We have nearly 200TiB of data that can be uploaded to Filecoin online, with an increase of about 5TiB every day. In our cold storage system, more data can be transferred offline. We are sure that there will be more data after Godap goes online, and the daily data increment will exceed 10TiB.

We plan to require at least five copies, two for TopBlocks and one for each of the other three SPs. We hope that the SP in North America will be the Lead SP and TopBlocks will be our first choice.

I have asked TopBlocks to inquire about the SPIDs of several other SPs. Their SPs ID will be completed later. It should be noted that we will also look for other SPs for investigation.

Here the latest screenshot of our online database:

![lQLPJxbiPF6bsHfMwM0CbbCxEuiz3IhPTQNzuycswPsA_621_192](https://user-images.githubusercontent.com/118191915/202599782-7d9ecc87-079b-4e8f-8b3f-22647f387b71.png)

**Comment by kevzak** [comment]
OK, great. One other piece of feedback: I would ask TopBlocks to list both locations (Cities) they will be storing data in North America on this application. One copy in X and one copy in Y.

**Comment by jenniferAzhou** [comment]
@kevzak First of all, I'll explain why I applied for 5P. Currently, there are 200T data, and 5T new data every day (before compression). Previously, we cleaned up or migrated the data over 180 days to the cold storage system due to the consideration of local storage costs. If the data can be accessed to Filecoin, we do not need to clean up, and our data volume will grow to 1P in the next 180 days. We are going to put 5 replicas, so we need 5P Datacap.

If the future data is not in your review, I think your suggestions are very pertinent，and I also agree with this investigation method. I am willing to apply for a small amount of Datacap to meet the current data volume. I wonder if I can apply for a 2P Datacap based on 400T and 5 copies?

**Comment by kevzak** [comment]
Yes, I recommend applying for a smaller size:
- For your company to pilot using the Filecoin system
- To test encryption
- Requesting a smaller amount of DataCap for a new client's first application with private data is more likely for notary support. 
- Future ongoing requests will be easier to attain if you prove that you followed the data storage plan from your application.

**Comment by jenniferAzhou** [comment]
@kevzak The data request amount on the application has been modified. The SP information of TopBlocks and FeiYan has been updated, and the other two information TopBlocks have not been submitted to me. I'll update again once updated, thanks.

**Comment by jenniferAzhou** [comment]
@kevzak updated. Pleases review it again.

**Comment by newwebgroup** [comment]
I will confirm with Cabrina and feiyan

**Comment by flyworker** [comment]
> @kevzak please allow me to explain that godap is an ongoing project, and the app is nearing completion. Godap is a sub business of CoverMe. It has not been put on the app store yet, so there is no link on the website. The products under CoverMe have been operated for many years and have accumulated tens of millions of users. Please refer to CoverMe Ws website http://coverme.ws/. These accumulated users will seamlessly transfer to Godap platvorm in the near future, which is part of our product upgrading strategy.

if coverme.ws is the big user case, why not using coverme.ws as the major application entity?

**Comment by jenniferAzhou** [comment]
Hello @flyworker coverme.ws is a private chat App, and our customers are very concerned about privacy. Although our background data does not save any customer privacy data, and we will not upload customer sensitive data to any third-party platform such as Filecoin, we are still worried that using coverme.ws to apply for LDN will cause customer concern. That is all,
thank you.

**Comment by kernelogic** [comment]
Can confirm I agreed to be an SP for this entity.
