### ISSUE TITLE
Next Governance Call: Tues November 29 8am PT / 1500 UTC -and- 6pm PT / 0200 UTC

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#784]
The twenty second Notary Governance Call of 2022 will take place on November 29 8am PT / 3pm UTC -and- 6pm PT / 0200 UTC

Tentative Agenda topics will include:
-Election Scoring
-Election FAQs and Discussions
-Recent Proposals
Issues brought up from the Community for Discussion

If you would like to add an item to the agenda, please request time by adding a brief description of the issue/proposal/topic in the comments of this issue.

If you would like to share your project/application 
- Please have your request submitted in this issue at least 48hrs before the Governance meeting. 
- Application presentation videos should be lo longer than 5minutes. 
- Video recordings with the Notaries both prior and after the Governance Call. 
- During the call you will be allocated time to answer any questions Notaries may have. 
- Requests to showcase an Application or LDN should be submitted via a recorded video following the guidance in (https://github.com/filecoin-project/notary-governance/issues/537)
- If unable to upload your video to folder, please contact Kevin-FF in SLACK for troubleshooting support.

If you would like to follow these meetings, the Fil+ Notary Governance calendar is available at
(https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D

You are welcome to attend both! These will be recorded, and video links will be posted in this issue.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

**Comment by heroapn** [comment]
@Kevin-FF-USA Hi，Kevin，I want to join this governance call.
Link to the application:(https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1213） (Eystorage Large Dataset Notary Application）
Organization represented: WenChu Blockchain Technology Co., Ltd
Wenchu Blockchain was established in 2018 and is headquartered in GuangDong China. There is a blockchain research and development center in Shenzhen, and a blockchain joint laboratory in Stockholm, Sweden. Wenchu has established a global technical research and development team of nearly 100 people, with members from Tencent and Alibaba. It has achieved multiple breakthroughs in the field of blockchain technology and has been recognized as a "National High-Tech Enterprise". It is a blockchain technology research and development, government and enterprise solutions, professional talent training and certification, and industrial investment.
Location: China
Length of time application has been open: 18 days.
Link to your recorded video: https://drive.google.com/file/d/1AwMAkGFXlocVIT7Y99BgqzagIGUqzc1a/view?usp=drivesdk
PPT Link:https://docs.google.com/file/d/1ICxQkIhaYdSYDSThcK9FuJnwAcGyrGOq/edit?usp=docslist_api&filetype=mspresentation

**Comment by beegoathz** [comment]
hi @Kevin-FF-USA,  thanks for your time
our company was not selected at the previous Governance Call,
applied to join this  governance call  again,
here is our team to application the LDN : https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1230
the video https://drive.google.com/file/d/12zpia2ftYThDorNCkf_csJyO2wK020CP/view?usp=share_link  have uploaded to google driver

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/790

**Comment by heroapn** [comment]
> @heroapn , The link to your LDN application is showing removed in GITHUB. Just wanted to send a friendly check in on status.

link: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1213
please check this.

**Comment by heroapn** [comment]
@Kevin-FF-USA 
Link: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1213
please check this.

**Comment by beegoathz** [comment]
@Kevin-FF-USA
I just saw at the meeting ，There is a problem with the link in the PPT
The page shows LDN#1230, but actually points to LDN#1250，May cause viewing problems，
The correct one should display 1230 at the same time.

---------------
The following screenshot：

![image](https://user-images.githubusercontent.com/16235303/204699920-77fee2f5-e0ce-4804-a8ff-4a0c97d83eb6.png)

**Comment by Kevin-FF-USA** [comment]
https://youtu.be/8Yix96R2bCg
