### ISSUE TITLE
Baikal Seal Storage Technology

### ISSUE THREAD

**Issue by salstorage** [filecoin-project/notary-governance#785]
## Application information 

Link to existing LDN application(s)
- _link to applocation(s) in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1212
  
Are you the data owner?
- [ ] Yes
- [ x] No

Is the data private i.e., encrypted or not meant to be retrieved by anyone else on the network?
- [ x] Yes
- [ ] No

## Data owner information
- Data owner:  Dark Matter Group within UC Berkeley
- Data owner's website: https://physics.berkeley.edu/research-faculty/nuclear-physics
- Data owner's social media account(s): https://vcresearch.berkeley.edu/faculty/gabriel-orebi-gann

### Data owner description 
https://vcresearch.berkeley.edu/faculty/gabriel-orebi-gann

### What is the motivation behind onboarding this data to Filecoin? 
Our customer is a Dark Matter Group within UC Berkeley and Seal is involved in a project with them to store the outputs of their scientific experiments. They would like to upload data to a distributed platform for other globally based researchers to be able to access this data

### What organizations are involved in this project? Sources of funding, SPs partnering in onboarding, other service providers, etc.?
Storage Providers Identified for project Baikal
Holon, 400 TiB
ElioVP, 400 TiB
PikNik, 400 TiB
Seal, 800 TiB

SP ID's
Holon
f01156901
f01156975
f01157018
f01157027

ElioVP
f01345523
f01392893

Piknik
f01873432

Seal
f01886710
f01558688

Seal will also be keeping a hot copy (400 TB) for the Customer available for access.

The data ingestion will follow this approximate schedule:

55 TB right away
by the end of year 1: 5 TB
by end of year 2: 50 TB
by end of year 3: 290 TB

## Transparency in KYC
KYC completed as per original application that was deprecated due to non activity
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/325

Are you going to offer NDAs to notaries?
- [ x] Yes
- [ ] No
  
## Dataset description 
The data sets are the original outputs of scientific experiments.
Total amount of DataCap being requested is 2 PiB

### Why is it useful to the Filecoin network?
The current data set requires permission based access.
A goal of the pilot project is for Seal to work with our customer to provide a permission based model to access data. Staged data for access will be supported on IPFS, Seaweed FS Open Source tools.
  
## Storage needs

Is the data to be stored in a single region, either due to geopolitical constraints or data owner policy?
- [ ] Yes
- [ x] No

### Which SPs will you/the data owner be working with to store the data? 
Storage Providers Identified for project Baikal
Holon, Australia 400 TiB
ElioVP, Europe 400 TiB
PikNik, USA 400 TiB
Seal, USA & Canada 800 TiB

Seal will also be keeping a hot copy (400 TB) for the Customer available for access.

### How were these SPs identified?
We are currently discussing capabilities and performing due diligence with several SPs and have chosen three SPs for this project. We chose these based on their current storage capacity, compute capabilities, enterprise-grade DCs and bandwidth.

## Notaries that support the project 

Danny O'Brien / Filecoin Foundation / USA
Kobby Chen / Fenbushi / Asia
Neo Ge / IPFS Main / Asia
Mark Roddy / Holon / Australia
Eric / ByteBase / Asia

**Comment by dkkapur** [comment]
Danny O'Brien / Filecoin Foundation / @dannyob / f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
Kobby Chen / Fenbushi / @Fenbushi-Filecoin / f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
Neo Ge / IPFS Main / @neogeweb3 / f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
Mark Roddy / Holon / @mjroddy / f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
Eric / ByteBase / @swatchliu / f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi

^ Notaries, can you confirm that you're good with this and we can get the msig set up and start moving to unblock this client? 

Other notaries/community members, feel free to ask any questions about the project here. Thanks.

**Comment by mjroddy** [comment]
Yes, I am happy with this. The more tooling we can get for clients the better.

**Comment by salstorage** [comment]
As per @dkkapur comment above, Paging Notaries for approval comment.
Note original LDN approved was #325 which was deprecated due to non activity, and new LDN application #1212 created for this Project.

Danny O'Brien / Filecoin Foundation / @dannyob / f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
Kobby Chen / Fenbushi / @Fenbushi-Filecoin / f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
Neo Ge / IPFS Main / @neogeweb3 / f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
Eric / ByteBase / @swatchliu / f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi

**Comment by raghavrmadya** [comment]
Multisig to be created by gov team

**Comment by kevzak** [comment]
Hello per discussion from slack https://filecoinproject.slack.com/archives/C0405HANNBT/p1670015428087609 we will add this application via E-Fil+ pilot.

As precedent for all other E-Fil pilot applicants: please add all SP IDs to the exception proposal 

cc @salstorage @raghavrmadya

**Comment by salstorage** [comment]
SP ID's
Holon
f01156901
f01156975
f01157018
f01157027

ElioVP
f01345523
f01392893

Piknik
f01873432

Seal
f01886710
f01558688
