### ISSUE TITLE
Notary Application: yiche

### ISSUE THREAD

**Issue by FrankSmis** [filecoin-project/notary-governance#786]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: yiche.com
- Affiliated organization: yiche
- On-chain address to be notarized (recommend using a new address): f1ujjgrutdlp7inzaomwsps4lvkvbkzdwaytrktji
- Country of Operation: GCR 
- Region of Operation: GCR
- Use case(s) to be supported:  User Content 、Media & Entertainment
- DataCap requested for allocation (10TiB - 1PiB): 3.8PiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
We began to learn about Fil in 2021. At that time, we thought Fil might solve the huge storage problem we have been facing since then; after that, we began to do some work to study how Fil use and work; the following are some articles we published at that time and later。
https://blog.csdn.net/m0_58340903/article/details/117672705
https://blog.csdn.net/m0_58340903/article/details/118093816
https://blog.csdn.net/m0_58340903/article/details/118341828
https://blog.csdn.net/m0_58340903/article/details/118580139
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Sorry for legal reasons we cannot disclose.
```

How did you acquire the FIL cited above?
```
We buy from Binance.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We knew about Filecoin in 2021 and started to study Filecoin at the same time.
We mainly experiment with Fil in the company. We haven't posted many comments in the community yet.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
We're more of a user of Fil, We haven't made any security contributions to Fil yet, and we hope to make contributions when we encounter them in the future.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Bitauto was established in 2000 and listed on the New York Stock Exchange in 2010; it was privatized in November 2020 and became a member of the Tencent family. As a Chinese car Internet platform company, Bitauto provides professional and rich Internet information services for Chinese car users, and provides effective Internet marketing solutions for car manufacturers and car dealers.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
wesite: https://www.yiche.com/
weibo: https://weibo.com/yiche/
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
WeChat official account: 易车
weibo: https://weibo.com/yiche
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
WeChat official account: yiche:  follower: 3.2 million
weibo: https://weibo.com/yiche：follower: 8.646 million
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
https://baijiahao.baidu.com/s?id=1669302749881296842&wfr=spider&for=pc
https://baijiahao.baidu.com/s?id=1748525911829291625&wfr=spider&for=pc
https://baijiahao.baidu.com/s?id=1748911670514313973&wfr=spider&for=pc
```

# Allocation Plan 
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Bitauto is one of the largest online communities in China. In order to better serve community participants, Bitauto hopes to provide a more free creative environment, larger network capacity, and provide the community with more resources, better tools, and more Free environment, hope that the community can use Web 3.0, DApp, Web 2.0 applications and other technology-related applications.
Additionally, we will only store for daily open Filecoins that we have vetted and certified. We plan to conduct a comprehensive review and assessment of our client's reputation on a quarterly basis and reserve the right to adjust client quotas to ensure the fullest possible allocation of shares.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will use a wallet with multiple signatures launched  to distribute to more customers and use a wallet that supports file coins to verify accounts associated with Datacap distributions.

The private keys will be stored in the hard wallet and will be accessible only by the principal.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
We will collect relevant information about customers.

1.Entity Information
- Formation documents , this includes certificates of registration/incorporation/information; 
- government-issued identification number for the entity；

2. Authorized Signatory Information
- evidence of the authorized signatory’s authority to act on behalf of the application entity ；
- Sign and press fingerprints (official seal and corporate seal are required)；
- ID card and a photo of the individual and ID card to prove it is the person;

3.Company operation direction and turnover
- Company goals, company's main business；
- Annual turnover in the last two years；

Question List:
1.Please provide information about the project, including the name of the organization, scale of operation, social media accounts & follwers, business license (can be sent by email); if you are an individual, please provide your name, date of birth, workplace and scale, proof of employment, social media accounts & follwers, ID card (can be sent by email).

2.When did you first learn about Filecoin? Please tell us about the projects you have participated in ? What do you want to get from Filecoin? What are your suggestions or expectations for the Filecoin network?

3.What is your data volume, source and post planning? Please describe the type, format, source, storage capacity, and public nature of the data that will be stored in Filecoin (if the data is publicly available, how will others retrieve it?

4.For application developers, will you act as a client on behalf of the user or will you apply for a notary on behalf of the user? If so, how much DataCap approval do you expect each user to receive?

After verifying this provided information, an interview and data source checking process is required. After that, an agreement should be signed for the next step: progressive assignment of DataCap, allowing the client to collect more credits
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
Regular (weekly or fortnightly) inspection and inspection; We will use the filfox  websites to check the proportion of SP allocated by customers.

```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes, we log review requests and the logs are posted on github. DataCap customers will be allocated a publicity period of 15 working days for community checks.
Of course, we may communicate with customers through slip, tg or email, and we will also keep communication records of these channels.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
GitHub will be the place to implement all requests, changes and fixes related to distribution. All records should be synchronized on GitHub, so that everyone in the community can clearly see the customer's situation, and timely track and supervise. Therefore, we keep all records on github.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L2
We will participate in meetings regularly, follow up the development in time, pay attention to FIP on github, and actively handle customer DC requests. more than 5 hours per week
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
No
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
We have any relationship with  existing notaries.
```

**Comment by Kevin-FF-USA** [comment]
Hi @FrankSmis,

Wanted to send a comment letting you know we received this application, but its come in after the deadline. I'm tagging this with a 5th round application label and will save it for the next round of elections - tbd in 2023.

**Comment by Kevin-FF-USA** [comment]
Hi @FrankSmis ,

Would you like to reopen and resubmit for the updated 5th round applicaiton?

**Comment by Filplus-govteam** [comment]
Removing 5th Round Label and closing.  If you're keen to reapply in the open enrollment, please check back in the Governance Issues for updates.  Thanks!
