### ISSUE TITLE
Notary Application: West Labs Venture

### ISSUE THREAD

**Issue by westlabsventure** [filecoin-project/notary-governance#787]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: West Labs Venture
- Affiliated organization: West Capital Group Limited
- On-chain address to be notarized (recommend using a new address): f1b5wse72uiusm4n2waqx4vuvsnvadz4ltcfruksa
- Country of Operation: APEC
- Region of Operation: Oceania
- DataCap requested for allocation (10TiB - 1PiB): 100TiB
- Are you applying on behalf of yourself or an organization?: Organization

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
WestLabs is a venture capital company that focusing on blockchain technology and infrastructure incubation since 2021. We are one of the leading crypto funds that invest in Web 3.0 projects that in the area of NFTs, Gamefi, DeFi and Metaverse. Our Filecoin Infrastructure Fund started with $25 million in funding to incentivize storage providers (or miners) to build on the network. We have operations in APEC region(Australia, Hong Kong and Singapore)
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
Prefer not to disclose.
```

How did you acquire the FIL cited above?
```
Prefer not to disclose.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
N.a.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N.a.
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Organization: West Capital Group Limited
Nature:  private company
Registration Country: Cayman Islands
Established: 02 November, 2021
Size: over 20 employees
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
WestLabsVenture
Homepage: https://westlabs.io/
Twitter: @WestLabsVenture

Investor Relation Director:
Mia 	
Linkedin : https://www.linkedin.com/injobs/in/mia-deng-3052b4233
Twitter：@dengmiamia
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
WestLabs is a Venture Capital focusing on blockchain technology and infrastructure incubation.
Westlabs believes that Filecoin is the future of cloud storage, and therefore, proposed the Filecoin Fund. The Filecoin Fund has invested over $10 million in funding to incentivize storage providers (or miners) to build the infrastructure layer of Web 3.0. 
Details in our Web 3.0 investment portfolio can be seen at link below: https://mobile.twitter.com/WestLabsVenture/status/1494128416924127235
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
N.a.
```

Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
N.a.
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Here is our allocation process:
1.We will verify customers into two categories: Existing customers and New Customers
2.For existing customers, we need to check if there is any violation of international and local laws, filecoin’s standards and ethics. For new customers, we will go through a specific KYC for individual clients or corporate clients.
3. After the KYC and client identify verification, the client who apply for the DataCap will go through a scoring process based on their applications and evidence as below: https://docs.google.com/spreadsheets/d/1DBRygcUpdGMnhRq3mSgOkyKjyd9MyuTPnJj86WvMUwg/edit?usp=sharing
4. The final sore will be given based on the Client Identity, Diversity, Decentralization, Allocation Strategy. For each sector we give a score, eventually, the total score will be fit into a DataCap table to give the final granted amount of DataCap.
5. The granted amount of DataCap will be confirmed and verified with remaining DataCap, then the granted amount will be allocated to client.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We will use hardware wallet to store the keys for DataCap address.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. 
In the early stage, all clients are required for an onboarding process to be qualified. 
Firstly, I need to collect information including:  
1. Entity Information
 - Formation documents - this includes certificates of registration/incorporation/information. 
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory’s authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary’s certificate, a signed letter from the applicant’s CFO, or may be included in the company operation agreement); 
 - close-up photo of the signatory’s face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
 - legal name.
 - street address (P.O. box number is not acceptable). 
 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence. 
 - copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 
 With these provide, an interview and data source checking process need to go through. After that, an agreement should be signed for the next step - gradually allocate datacap and let the client gather more credit. 

The questions will cover the following areas that to ensure the DataCaps are properly allocated:

1.Introduction of yourself/ your organization (with links);
2.Use case examples and scope;
3.Geographic location of the client;
4.DataCap Allocation Requests Amount;
5.Filecoin On-Chain Address;
6.Declaration of Copy rights and Legal Compliance Requirements;
7.Specific requirement of miners and storage service
Nature Of Business (Government, Public, Private, NGO)

```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
1.DataCap usage monitoring and auditing;
2.Trade Deal monitoring;
3.Content Monitoring. 
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Yes. We are open to any audit request from private and public channels.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
Yes. We will use github repo to make allocation decisions and keep records.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
We will have one full-time employee(40 hours/ Week) responsible for communication and DataCap management. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
[Please answer here.]None
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
N.a.
```

**Comment by Kevin-FF-USA** [comment]
Hi @westlabsventure,

Thank you for your interest in becoming a Notary with the Filecoin Plus program. Leaving this comment to let you know  you application has been received, but after the deadline for scoring in the 4th (current) election.  I'll add a tag for the upcoming 5th round of elections which is tentative for Q2 in 2023. I'll keep this application on file for that date, and when the date draws closer, I'll re comment on this issue to let you know what updated fields are needed to resubmit.

**Comment by Kevin-FF-USA** [comment]
Hi @westlabsventure 
Would you like to resubmit with the updated application for the 5th round?
