### ISSUE TITLE
Notary Application: Vault 32 

### ISSUE THREAD

**Issue by staaaang** [filecoin-project/notary-governance#791]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name: **Sarah Tang**
- Affiliated organization: **Vault 32 Inc**
- On-chain address to be notarized (recommend using a new address): **f3uaaphrmedsw75et5gblhnghpjy2vcwpzivhwjmix77p2pqdbyucmu2vvajftvmdy42tiynxhduangl26zpaq**
- Country of Operation: **Canada**
- Region of Operation: **North America**
- Use case(s) to be supported: 
**1. Professional Services (Hosting Reseller, Long-term Backups, Data Warehousing)
2. Developer Tools (Package Managers, Automatic Notaries, Web2 to Web3 integrations)
3. Decentralized Applications
4. User Content (Personal Storage)
5. Public or Open Data (Scientific datasets, research data, government or historic
6. Media & Entertainment (Videos, photos, NFTs)**
- DataCap requested for allocation (10TiB - 1PiB): **1PiB**
- Are you applying on behalf of yourself or an organization?: **Organization**

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin network. Please include relevant GitHub handles, Storage Provider IDs, significant projects or contributions (with links).
```
We started participating in the Filecoin community in January 2022 and attended the ESPA program in April 2022 for the second cohort they hosted. Decided to start our own Filecoin storage provider business in June 2022.
Miner IDs:
 https://filfox.info/en/address/f01886797
https://filfox.info/en/address/f01963614
Github: github.com/jcace
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence (i.e., addresses on chain with their corresponding FIL amounts).
```
https://filfox.info/en/address/f01963614 - 10k fil available / 300 fil pledged (darma loan)
https://filfox.info/en/address/f01886797 - 13k fil pledged, 1k fil locked/vesting
https://filfox.info/en/address/f13kaavc7g6swkbqmmc4ni6ue6jzf2cp7hyyffnuy - 2.5k fil wallet
```

How did you acquire the FIL cited above?
```
**FIL acquired from DARMA + buying it ourselves**
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
We've ingested 100TiB+ of data from programs (evergreen/slingshot, estuary) and are onboarding a 500TiB dataset from another SP. Participated in Saturn Sunrise program. We've attended the ESPA program for cohort 2 this past April including multiple Filecoin meetup/conferences throughout the year. Our team has also helped Hut 8 Mining get into the Filecoin ecosystem, by helping them with their hardware setup and taught them everything we've learned after ESPA.
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/a
```

### Organizational Reputation

Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
We have a 2PB node located in a datacentre called The Vault, located in Vancouver BC, Canada. There are currently 6 members working for our company. We registered Vault 32 in June 2022, our node was running by Mid July 2022.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Website: currently in the works.
Instagram: v32_io

```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
N/A
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.

```
Instagram:
Sarahmtng: 706 followers
Jso.n: 274 followers

```
Please share any additional relevant information regarding your presence (e.g. news articles, interviews, podcasts, videos, awards, etc.)
```
N/a
```

# Allocation Plan [refer to the Rubric to see how this impacts your Notary score](https://docs.google.com/spreadsheets/d/172-sbd5qzdbSofvL_C5FHRyXEsTUpMiKspItygAVJA4/edit?usp=sharings)
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
Depending on the application, the requirements, and the level of legitimacy or track record, the amount and rate per client will vary. The public will have access to all communication and transactions regardless. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
Ledge, offline transactions.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
I will audit the application in its entirety. In addition to verifying the website, date the domain was registered, and scanning the internet for similar code, I will ensure that the website has not been cloned via htrack and posed as a front for datacap. My goal is to ensure the samples are genuine, not web scraped information. In order to prevent email spoofing of root domains, I will confirm DNS entries of the application website. In order to verify the client's email address, I will request an email confirmation.
The applicant must demonstrate knowledge and understanding of how the datacap should be used and issued responsibly. In order to help the applicant succeed, I can provide assistance as needed. 
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
In order to make sure allocations have been distributed across a wide variety of SP's, I will do research on their past datacap tranches. All data from all applicants will be retrievable and I will ensure that the SPs they have been allocating to are not affiliated with themselves or past notaries who approved their previous trench applications.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
I intend to keep all decisions on github, which is publicly accessible. If a candidate requests private communication for security reasons, I will document all correspondence for future reference.
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
 I can host on a publicly available google sheet, unless more specific requirements are needed.
```

### Engagement in Program
Which level (1-5) of service commitment are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), joining working groups, adding comments on discussion/issues, attendance in governance calls, messages in Slack, etc. For a full list of the service levels and time commitments please review the [rubric](https://github.com/filecoin-project/notary-governance/issues/630) 
```
L5. The more active I am, the better. As part of my day-to-day job, we work in filecoin full-time.
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Our first time applying.
```

## Disclosures
Do you/your organization have any relationship(s) with other existing notaries or their organizations? If yes, please list the names of the Notary individuals or organizations you may be related to.
```
We have no relationships with other existing notaries.
```

**Comment by Kevin-FF-USA** [comment]
Hi @staaaang,
Thanks for your interest in becoming a Notary with the Filecoin Plus program. Adding this comment to let you know we have received your application, but it was received after the deadline and will not be processed or scored until the next (5th) round of elections TBD in Q2 of 2023.  
Once the next election cycle begins, I'll reping this application so you are aware of any updates needed.

**Comment by Kevin-FF-USA** [comment]
Hi @staaaang,

Would you like to update and resubmit for the 5th round of applications?

**Comment by Kevin-FF-USA** [comment]
Hello!
Going to close this issue out and remove the 5th Round tag.  There will be another application round scheduled for Q2/Q3 which will be rolling - should you wish to apply
