### ISSUE TITLE
Proposal: Add `KYBed` tag to Efil+ LDN if it passes KYB

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/notary-governance#796]
## Background 

When assigned this LDN [application](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1248#issuecomment-1326291704) for review, information that it has passed KYB was buried.

## Proposal

Add a `KYBed` tag to Efil+ LDN if it has already passed KYB.

**Comment by kevzak** [comment]
This is a good idea @Fatman13 thank you for the comment! We will look to add a tag that represents KYB complete
