### ISSUE TITLE
EhostICT Dataset

### ISSUE THREAD

**Issue by gustjr154** [filecoin-project/notary-governance#797]
## Application information 

Link to existing LDN application(s)
- _link to applocation(s) in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1274
  
Are you the data owner?
- [O] Yes
- [ ] No

Is the data private i.e., encrypted or not meant to be retrieved by anyone else on the network?
- [O] Yes
- [ ] No

## Data owner information
- Data owner: EhostICT
- Data owner's website: https://www.ehostidc.com/
- Data owner's social media account(s): https://www.linkedin.com/company/ehostidc/

### Data owner description 
_EhostICT is running a tier-3 data center which is located in Seoul, South Korea. We have been offering IT total services such as GPU server hosting, Network, Security controller based on almost two decades’ experiences of IDC operation. We operate various scales of data centers & POPs over the world to offer global IDC services.
Confirmed
Our main data center’s infrastructure is tier 3 levels of high availability with 176 racks mounted 1,630 servers and equipped with three major ISP lines and China direct line with 50G port speed. Also, the operation & management team offers 24/7 monitoring service which handles the network changes, system network infra resource, security issues and backup schedule._

### What is the motivation behind onboarding this data to Filecoin? 
_About 100~150TB of backup data occurs everyday operating our IDC infrastructure and services. It has been stored only in the physical hard disk in our DC for years. However, we need a different level of storing method that anyone can retrieve and share under the Web 3.0 era and found out the IPFS technology would fit our needs._

### What organizations are involved in this project? Sources of funding, SPs partnering in onboarding, other service providers, etc.?
_No other organizations are involved. It's our own funds and data. 
Looking for 2 SPs for vaulting backup. f01873489 and f01956198 have fixed, met them in SP community._

## Transparency in KYC
_If you are not the data owner, please email filplus@fil.org with you and the data owner on a thread so at least the Fil+ governance team can act as a lightweight KYC check._
: FYI, KYB has been completed. confirmed by @kevzak 

Are you going to offer NDAs to notaries?
- [O] Yes
- [ ] No
  
## Dataset description 
_It's backup data from operating IDC infrastructure and services. It includes clinet's private&public data such as confidential docs and DB(deep learning, autonomous driving, and education). And private&public data from us like company introduction and backup data from our R&D dept. 
total amount of datacap being requested is 2pib. 4copies of 500tb._

### Why is it useful to the Filecoin network?
_Our first goal is decentralizing these petabyte levels of datasets into a filecoin system and making it contactable to anyone could retrieve. When the retrieval market is released, our customers can find the os container whenever they want, wherever they are. _
  
## Storage needs

Is the data to be stored in a single region, either due to geopolitical constraints or data owner policy?
- [ ] Yes
- [O] No

### Which SPs will you/the data owner be working with to store the data? 
_If all the SPs have not been chosen at the time of issue submission, feel free to edit and update the form as they are chosen. If you need support on finding reputable SPs, please check out filgram.io, filrep.io, plus.fil.org/miners, or Filecoin Slack channels: #fil-plus, #fil-deal-market_
  
| SP ID | SP org | SP region |
| --- | --- | --- |
| _minerID_ | _org_ | _region_ |

f01873489 and f01956198 are fixed and looking for two more SPs in community and Slack now. I will update it later. 

### How were these SPs identified?
_Who can meet our requirements like having 10 port speed, storage capacity, and geo-location_

## Notaries that support the project 
 _Notaries perform KYC/KYB to validate the legitimacy of data and organizations. To find supporting notaries please view the list of [round 3 notaries](https://github.com/filecoin-project/notary-governance/tree/main/notaries) and post your LDN application in the Filecoin slack channel #fil-plus-application-review. Feel free to update the form as you gain support over time and more notaries are willing to support your application._

| Notary name | Notary org | Notary region |
| --- | --- | --- |
| _name_ | _org_ | _region_ |

I need to find the notaries who can support Efil+ project.

**Comment by kevzak** [comment]
@gustjr154 where are f01873489 and f01956198 located?

**Comment by kevzak** [comment]
@gustjr154 can you connect me to SP ID f01873489? They have top scores for retrievals and I'd like to help promote their storage for open datasets. Thanks
