### ISSUE TITLE
2023 Notary Goverance Meeting Dates & Times

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#799]
## Issue Description
2023 Notary Governance meeting dates and times

## Impact
In 2022 the call times for the Bi-Weekly Notary Governance Meetings took place at 0800pt/1600utc & 1600pt/0000utc for the first part of the year, then were updated based on feedback in the [time change proposal.](https://github.com/filecoin-project/notary-governance/issues/538.) to 1800pt/02000utc(next day)

Once the 2nd call was shifted back two hours to begin at 1800pt/0200utc(next day) the attendance more than doubled. 

## Proposed Solution(s)
Proposing the call times for the 2023 Governance keep this established time as shared in the [Filecoin Plus shared calendar](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles). 

### Timeline
2023 Governance Dates  (all dates PT timezone)
Call 1: 0800pt/1600utc   Call 2: 1800pt/0200utc(next day)
1. 17 January 
2. 31 January
3. 14 February
4. 28 February
5. 14 March
6. 28 March
7. 11 April
8. 25 April
9. 09 May
10. 23 May
11. 06 June
12. 20 June
13. 11 July  
14. 25 July
15. 15 August
16. 29 August
17. 12 September
18. 26 September
19. 10 October
20. 24 October
21. 07 November
22. 21 November
23. 05 December
24. 19 December

In the event a Governance Meeting date overlaps with a future conference, the conference will take the place of the Governance Meeting. 

### Technical dependencies 
None, but seeking confirmation from SLA4+SLA5 they are available and able to commit to this schedule. 

## Risks and mitigations 
Major Holidays outside of Lunar New Year, 4th of July, and Christmas that aren't taken into account. If so, please comment below with potential date conflicts.

## Related Issues
https://github.com/filecoin-project/notary-governance/issues/538

**Comment by liyunzhi-666** [comment]
For a Notary living in China, the dates look good~

**Comment by IreneYoung** [comment]
It works for me, too.

**Comment by caoyoungyoung** [comment]
Timing is perfect for those  in China

**Comment by kernelogic** [comment]
Looks like this is in conflict of the T&T meeting, at least according to the google calendar.

**Comment by cryptowhizzard** [comment]
Looks good.

**Comment by Kevin-FF-USA** [comment]
Thank you to all who shared feedback.  Going to close this issue with the dates listed.
Link to the calendar invite is now live in the shared Google Cal: https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles
