### ISSUE TITLE
Proposal: motion for relocating f+ program to L2

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/notary-governance#803]
## Simple Summary

Add "explore potentials of moving f+ to L2" to f+ program's OKR.

## Abstract

With FEVM just around the corner, f+ program could finally play around the idea of moving the program to L2. By doing so, it should provide more tools for the team to govern the program in a more transparent and decentralized ways and at the same time lower the complexity of L1 leaving it in a much more cleaner state. Some of the key milestone of this expedition could be the following...

- A whitepaper of f+ program on L2 including mechanics on governance, tokennomics, how program functions on L2 and etc
- Prototyping on FEVM and possibly hold incentivized tests on Calibration
- FIP to remove Datacap entirely on L1

## Motivation

As pointed out by [ZX](https://github.com/filecoin-project/FIPs/discussions/453#discussioncomment-3541311) in Sep last year, the network has succumbed to the macro economic winter. [Network growth](https://github.com/filecoin-project/community/discussions/572) has fallen dramatically with no significant number of new SP joining and existing SP leaving the network. 

By looking at Web2 companies like Meta, it is apparent that **data** is the key to a successful venture. One of the ways to address the aforementioned issue is to onboard more valuable data which in turn increase the value of the whole network. However, f+ program sitting at the core of on-boarding valuable data (as opposed to verified data) as it is structured right now on L1 falls short in accomplishing so from the following aspects...(many of the [issues](https://github.com/filecoin-project/FIPs/issues/203) in Nov, 2021 are still not really addressed)

### 1

From original[ FIP0003](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0003.md)...(Oct, 2020)

> This proposal rebrands the Verified Clients program as Filecoin Plus - to represent the addition of a layer of social trust and all the use cases that will be enabled on the existing Filecoin protocol.

A social layer doesn't scale well and we see how it is played out for **2 years** now. The program tries to adapt over the span of **2 years** but still fails at the goal of distributing **5PiB** valuable data to the network per day. It is clear that the current paradigm does not work in a global scale and need drastic changes like what is proposed here.

### 2 

Current f+ program implicitly incentivize division of the community. Instead of uniting the community to work toward a common goal, program as it is right now creates a strong "us VS. them" atmosphere crippling data on-boarding efforts. A new governance model based on L2 smart contracts with proper incentive/punitive structure is needed to guide the community to work together.   

### 3

**Valuable data** as opposed to *verified data*. There is very little inherent value of verified data as it does very little to increase the actual value of the network. What the network need is more valuable data determined by free market. To iterate on such model of value evaluation, having f+ on L1 and needing a FIP to adapt is near to impossible. Moving to L2 so that proper incentive could be given to more valuable data will boost the value of the network in orders of magnitudes. 

## Community Highlights

> [sunset of Fil+](https://github.com/filecoin-project/FIPs/discussions/554#discussioncomment-4467725) in favor of L2 mechanisms

> [A better solution](https://github.com/filecoin-project/FIPs/discussions/554#discussioncomment-4376052) is to move Fil+ totally to Layer 2 after FVM is ready.

> [Move f+ off-chain](https://github.com/filecoin-project/community/discussions/572#discussioncomment-4288563)

**Comment by stcouldlisa** [comment]
I am very interested. You mentioned Valuable data. How to  defined Valuable data ? Generally speaking, people are willing to pay for the data of Valuable data.

This is also the vision of the Filecoin network: to store precious data, store data that people are willing to pay for, and grow into a cloud storage service provider like Amazon Cloud.

**Comment by Fatman13** [comment]
Hey @stcouldlisa, appreciate your thoughts! The discussion has been moved to https://github.com/filecoin-project/notary-governance/discussions/804. Will close this one to clear confusion.
