### ISSUE TITLE
Upcoming Governance Call: Tues January 31 8am PT / 1600 UTC -and- 1800 PT / 0200 UTC (next day)

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#806]
The second Notary Governance Call of 2023 will take place on January 31st at 8am PT / 1600 UTC -and- 1800pm PT / 0200 UTC (next day). To join the call or add the meeting to your calendar, please add the [Fil+ Shared Calendar](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D)

Agenda

    SLA attendance and reporting
    Governance Team Intros
    Metrics Review
    Working Group Updates
        Trust and Transparency
        Enterprise Fil+
    New Notary Onboarding
    Proposals
    Community for Discussion

If you would like to add an item to the agenda, please request time by adding a brief description of the issue/proposal/topic in the comments of this issue. Please have your request submitted in this issue at least 48hrs before the Governance meeting to ensure it is included in agenda.

If you would like to share your project/application please prepare a short (less than 5min video) that covers your application. Recommended topics include

    A brief summary/intro of the organization requesting the data.
    What the data is and how it benefits the Fil+ mission.
    What specific actions are you seeking from the Notaries.

Video recordings with the Notaries both prior and after the Governance Call. During the call, if time permits you will be allocated time to answer any questions Notaries may have. Requests to showcase an Application or LDN should be submitted via a recorded video following the guidance in (Modification: Record presentations - Share projects async rather than live on Notary Governance Calls https://github.com/filecoin-project/notary-governance/issues/537)
If unable to upload your video to folder, please contact Kevin-FF in SLACK for troubleshooting support.

Notary Governance Meetings are recorded and posted to Youtube.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

**Comment by Kevin-FF-USA** [comment]
Proposal for Discussion: https://github.com/filecoin-project/notary-governance/issues/813

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/811

**Comment by cryptowhizzard** [comment]
Can you please include #815  ( in case of no response there ) and #816

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/819

**Comment by Kevin-FF-USA** [comment]
Video: https://www.youtube.com/watch?v=jXQdslc5DLA
Slides: https://docs.google.com/presentation/d/1HWFZusN8OMouNSxfj860g_zdOgwPPoZct1tizxwdrJM/edit?usp=sharing
