### ISSUE TITLE
Modification: [Remove Fogmeta & FilSwan from R4 notary]

### ISSUE THREAD

**Issue by Carohere** [filecoin-project/notary-governance#824]
## Issue Description
Fogmeta and Filswan are both owned by Charles Cao. In notary disclosure, Fogmeta stated itself as "helping filswan develop and maintain the swan-provider and swan-client project“ and FilSwan stated "no". As the ultimate beneficial owner Charles didn't reveal the connection between the two organizations. 

![Snipaste_2023-02-09_09-32-23](https://user-images.githubusercontent.com/106579285/217777598-4b48b708-2a52-4528-891a-b0fb6fdbf4a4.png)
![Snipaste_2023-02-09_09-33-17](https://user-images.githubusercontent.com/106579285/217777601-f60af053-1d79-4f78-b405-ff14bde7c9e5.png)
![Snipaste_2023-02-09_10-20-43](https://user-images.githubusercontent.com/106579285/217777612-33e4a76d-e26c-4653-b4ec-e524967a9b67.png)

![Snipaste_2023-02-09_09-38-50](https://user-images.githubusercontent.com/106579285/217790857-7e3e843e-8b5c-47cb-ab57-e9cc3d46a6c3.png)

![Snipaste_2023-02-09_11-34-44](https://user-images.githubusercontent.com/106579285/217790892-4dc7c7cc-0df7-4ae9-9f86-fefac8386a8f.png)
![Snipaste_2023-02-09_09-34-13](https://user-images.githubusercontent.com/106579285/217790918-7d3453d0-9737-4c0a-8040-30df2a6ff15e.png)

![Snipaste_2023-02-09_10-10-52](https://user-images.githubusercontent.com/106579285/217791224-7e9ae9d3-78a9-4fcd-87a3-89707071691a.png)

![Snipaste_2023-02-09_09-30-04](https://user-images.githubusercontent.com/106579285/217791243-bdc1654e-bb33-4998-906b-b479f4012eb8.png)

For privacy reasons, I covered the specific information about Charles, details will be available to the governance team only.

-----------------------------------------
In #924, Filswan staff guided a client with only 10GiB data to apply for 3PiB Datacap, and later faked 40TiB with 4 images. 
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/924#issuecomment-1413545571
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/924#issuecomment-1420840438
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/924#issuecomment-1421182238
## Impact
- As a long-time participant in the community, Filswan has been receiving a large amount of Datacap based on its reputation. Whether all Datacap allocation/usage acquired adheres to the rules of FIL+ is yet to be verified.

- Being the UBO of two organizations and refusing to disclose is contrary to transparency.

## Proposed Solution(s)
Remove Fogmeta & Filswan from the R4 Notary 

### Timeline
- Community inputs until February 13th
- Discussion on February 14th governance call

### Technical dependencies 
- RKH signing to remove Filswan from the current multisig 
- Stop onbording Fogmeta into R4 multisig 

### Recommendations
Recommend community members to check all storage performed by Filswan and share inputs.

## Related Issues
#772  
#778 
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/924

## Related Discussions 
https://filecoinproject.slack.com/archives/C0405HANNBT/p1675841043786789?thread_ts=1675836958.628709&cid=C0405HANNBT

**Comment by Carohere** [comment]
Appreciate your input @cryptowhizzard, let's walk through it together. 

@flyworker, founder of Filswan
@nancy668, founder of Ipfsnews
@cwisoft aka Leo Zhang, the mysterious man 

- Filswan is long term business partner with Ipfsnews and proposed them for filecoin storage
- Leo (filswan emplyee, according to Nancy) guided ipfsnews through KYC, shared the email screenshot
- After you pointed out the data is fake, both parties claim that Leo is not their employee, that's the controversy we're facing here and i would like to find out who is lying.

**Comment by flyworker** [comment]
You are making facts now.
Leo is not FilSwan 's employee. Why you are trying to make false information as truth?
You are trying to scam the community.
Our information is transparent on the internet and community, so you can find so called proof.
That's it

**Comment by flyworker** [comment]
If you have no more proof Leo is FilSwan's employee, I suggest you stop this topic, it does not bring anything to continue.

**Comment by Carohere** [comment]
First thing first, calling me play dirty doesn't make you come out clean... 

> Leo is not FilSwan 's employee. Why you are trying to make false information as truth?

that's your words... stay rational... what u say, what i say, doesnt matter. i see conflicts and i pointed it out, that's it period.

>Mealwhile FilSwan will continue his work serve the community, we don't have time to work with your dirty play.

Btw im also R4 notary, i'm serving the community in my way as well... dont jumo into the connclusion, that only will make you sound stupid...

**Comment by flyworker** [comment]
Ahhh, you are  R4 notary, and you call me stupid?
Why you are doing personal attack ?

**Comment by flyworker** [comment]
by the way, I am start questioning if you are qualified as R4 notary.

**Comment by Carohere** [comment]
> > Mealwhile FilSwan will continue his work serve the community, we don't have time to work with your dirty play.
> 
> Btw im also R4 notary, i'm serving the community in my way as well... dont jumo into the connclusion, that only will make you sound stupid...

u started first... go check what dirty play means in the dictionary. and sure, do wahtever u should do. i accept all concerns against me, won't be a problem since i know how to handle talks in a rational way and has no anger issues :)

**Comment by fillove** [comment]
@flyworker 

you just need to answer one thing：

Who should be responsible for the evil deeds in 924?

**Comment by manojkumardevisetty** [comment]
I don't see any problem with FilSwan I was using this for the past months it's completely free to us FilSwan products and it is very good for us since as an sp. that we are getting good

**Comment by Neal-fil** [comment]
It is clear the purpose of an organization controlling multiple notaries is to sign through more applications affiliated with themselves, one of them should be removed.

**Comment by jimcray** [comment]
funny to see a lot of accounts do not do anything to the SP growth but are good at attack. If you guys can do anything to help the community growth, Filecoin would not be at this position.

**Comment by jimcray** [comment]
FilSwan deserved to go to a better community, maybe BNB chain or ARWeave,

Join here ARWeave https://discord.gg/AhsZfBm

**Comment by jimcray** [comment]
who are those guys? @Sunnylscoming  @Neal-fil @fillove

**Comment by coldjoke1** [comment]
#815

**Comment by coldjoke1** [comment]
#816

**Comment by jimcray** [comment]
here comes another recently created account @coldjoke1  is filecoin a spammer-only community now?

**Comment by coldjoke1** [comment]
I read all the information.

No matter who raises the question, as long as his question is reasonable, it needs to be taken seriously.

It is shameful to achieve 40T of data with only 4 pictures and get 400T of income.

Just tell the community who is responsible for 924.

**Comment by coldjoke1** [comment]
I didn't attack anyone, please don't attack me

**Comment by jimcray** [comment]
yeah, I like those newly created account pretending to be good citizens, and they did not feel shame as a spammer.

**Comment by coldjoke1** [comment]
When everyone is talking about a problem, you divert everyone's attention, you want to attract other people's attention, and thus weaken the problem.

Don't take us for idiots, don't think that RG would be so stupid to get eyeballed by your question.

To answer the question directly, who is responsible for 924?

**Comment by jimcray** [comment]
I am just watching you play @coldjoke1  why did you ask me about 924? so funny

**Comment by coldjoke1** [comment]
> by the way, I am start questioning if you are qualified as R4 notary.

@flyworker There is no need to rise to personal attacks, Carohere did nothing wrong, she just revealed your problem, she just let more people discuss the problems of 924.

You attack her as not qualified to be a V4 notary.

If 924 didn't have any problems, why did 924's GitHub "die" so quickly.

**Comment by jimcray** [comment]
Why do you think questioning if qualified as R4 notary is a personal attack?

**Comment by coldjoke1** [comment]
Don't @ me, I don't want to debate with you, let everyone return to the topic:  Remove Fogmeta & FilSwan from R4 notary

**Comment by Neal-fil** [comment]
@jimcray 
spammer=opinions that you don't want to hear 
What's your role in the ecosystem?  I‘m ready to learn your way of contributing to the network.

**Comment by Carohere** [comment]
Let's don't get too far away... A few things i would like to get focus on in this proposal
1. Does Charles own these two organizations i mentioned? 
2. If so, does it violate transparency, self-disclosure in notary application？
3. 40TiB is nothing huge but still matters. I would like to figure out who's playing dirty in #924.

**Comment by cryptowhizzard** [comment]
Hi,

Some things i want to add here.

Charles is a long respected member of the community. He has done a lot for the benefit of Filecoin( Filswan platform and other tools ) and invested lot's of time and efforts. This morning i had a PDF in my e-mail about this whole situation. Reading it I conclude that the people who wrote it seem to have joy in destroying people's reputation and literally all intellect of what these kind of things do to people seems to have vanished. The level went down to elementary school levels -> "If i can't have it, you can't have it either" :(

Again i will stand up to this. Yes, if there is something that went wrong with ( the people around ) Charles then we should know that and yes, as a human being we all make mistakes sometimes. I however did not lose trust in Charles and i am -by far- not in support of this proposal.

**Comment by StFileCloud** [comment]
> Again i will stand up to this. Yes, if there is something that went wrong with ( the people around ) Charles then we should know that and yes, as a human being we all make mistakes sometimes. I however did not lose trust in Charles and i am -by far- not in support of this proposal.

As you say that ’as a human being we all make mistakes sometimes‘. So you admit that Charles has made mistakes, right?  But unfortunately Charles doesn't think so.

**Comment by cryptowhizzard** [comment]
> > Again i will stand up to this. Yes, if there is something that went wrong with ( the people around ) Charles then we should know that and yes, as a human being we all make mistakes sometimes. I however did not lose trust in Charles and i am -by far- not in support of this proposal.
> 
> As you say that ’as a human being we all make mistakes sometimes‘. So you admit that Charles has made mistakes, right? But unfortunately Charles doesn't think so.

Don't quote me out of context. I explicitly used ( the people around ) to make clear that Charles is entrepeneur and has a lot of people around him.

**Comment by xixiott** [comment]
@cryptowhizzard你是真的搞笑，自己把盟友的假数据挖出来，现在又来给铺台阶了。speedium自己是客户，矿工和公证人，申请里那么多共享cid，存的也不是宣称的数据。filswan平台里大堆大堆的自家矿工，一个人控制着好几个账号还道貌岸然的，看看兜里几个ledger再说吧。行业里大家都清楚，不要装。劝你们做人谦虚一点。

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard你是真的搞笑，自己把盟友的假数据挖出来，现在又来给铺台阶了。speedium自己是客户，矿工和公证人，申请里那么多共享cid，存的也不是宣称的数据。filswan平台里大堆大堆的自家矿工，一个人控制着好几个账号还道貌岸然的，看看兜里几个ledger再说吧。行业里大家都清楚，不要装。劝你们做人谦虚一点。

?

**Comment by cryptowhizzard** [comment]
> 

That's the difference between us. You think in allies like in elementary school. I think in people and the damage the network you belong to is doing to them.

**Comment by raghavrmadya** [comment]
Thanks everyone for your contribution to this discussion. Based on the evidence and explanation provided by @flyworker about how the entities are organized, I would like to see if anyone still has questions/concerns about this issue. If there is no significant pushback or further evidence that proves otherwise, I suggest we close this issue.

**Comment by flyworker** [comment]
As we mentioned in the governance meeting last morning. We have the statement below.

![image](https://user-images.githubusercontent.com/8363795/219051524-339c519c-651e-4024-9a37-f0ac5c46e2c4.png)

**Comment by Carohere** [comment]
I would still suggest all community members to consider if it's really necessary to have multiple related/ co-owned organizations joining the same round notary. Especially since the number has been doubled in r4. Do we really need to add more potential collusion to the already fragile system? Even now it's hard enough to distinguish the relation between client and sp, sp and notary, I don't see anything good by adding the notary and notary layer on top of it...

**Comment by dkkapur** [comment]
+1 to @raghavrmadya's comment above. would love to hear from @Carohere if there's any pending open concerns after the gov call today.

**Comment by Kevin-FF-USA** [comment]
@Carohere  Thank you for raising this proposal and helping to facilitate the discussion in a professional and courteous way.  Also appreciate you raising additional topics around how this program scales to address multiple/related organizations. Since some of these co-owned organizations disclose their connection in their application disclosure forms (which is private), there isnt _currently_ a way for the public to see the transparency provided. Good flag. I'll take action to scope out a solution to this in the 5th election process. 

All,
During the last Governance call, @flyworker provided a public transparency update around the organizations connections.  Outlining how the organizations are modeled, lead, and maintain separate work streams in the Fil+ ecosystem.  Also, publicly declared that their organizations will not be colluding to sign applications.

Given Fogmeta, FilSwan's, and Nebula Blocks public transparency in this issue and on the call, as well as no past T&T review proposals- **will hold their organizations to their commitment to not sign applications from each other in same round in order to maintain status as a Notary in high standing in the R4.** 

Before closing this issue on Feb 20, if there were any additional data points or comments - the forum is still open.

**Comment by Chris00618** [comment]
Obviously, @Carohere was not satisfied with this result. We believe there are more people who have the same view with us. Such a well-known notary does evil,  which has a great negative exemplary effect on the community. A large number of people have begun to prepare multiple sets of identities of  R5 notaries which is not going to get us very far in such a community.

![image](https://user-images.githubusercontent.com/105741726/219546046-0371f57a-67d6-4928-88be-d934d7904400.png)

Why can't we decide the result of the proposal by voting? This will make it more open and transparent, otherwise such a small-scale debate can't reach the most fair decision.

It is suggested that anyone can propose to remove the "bad" notaries. If more than 30% (or 20%) of the notaries or clients vote and pass in the specified time (such as two weeks), we should remove them. if not pass, we can close it.  This is the most efficient way to solve friction.

It's time to return the jurisdiction to the community @Kevin-FF-USA

**Comment by licornduan** [comment]
The low price of filcoin has made it impossible for many SP to operate normally and expand the market. We are looking for truly valuable customers, rather than opportunistic in order to obtain fil

**Comment by raghavrmadya** [comment]
Based on the evidence provided on the relationship b/w the entities in question on the governance call by @flyworker and seeing no major concerns other than a very valid point made by @Carohere above, we are closing this issue. Not having multiple related/ co-owned organizations joining the same round notary was not a requirement in the most recent round of elections as long as the notary applicant was upfront about the potential/existing relationship b/w entities. 

If the community feels strongly about changing this moving forward, kindly open an issue for discussion
