### ISSUE TITLE
Upcoming Governance Call: Tues February 28 8am PT / 1600 UTC -and- 1800 PT / 0200 UTC

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#828]
The fourth Notary Governance Call of 2023 will take place on February 28 at 8am PT / 1600 UTC -and- 1800pm PT / 0200 UTC (next day). To join the call or add the meeting to your calendar, please add the [Fil+ Shared Calendar](https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles%5B%5D)

Projected Agenda
Disclosure Updates
Registry Verification Updates
Notary Onboarding Questions
Working Group Updates
Trust and Transparency
Enterprise Fil+
New Proposal Discussions
Community for Discussion

If you would like to add an item to the agenda, please request time by adding a brief description of the issue/proposal/topic in the comments of this issue. Please have your request submitted in this issue at least 48hrs before the Governance meeting to ensure it is included in agenda.

If you would like to share your project/application please prepare a short (less than 5min video) that covers your application. Recommended topics include

A brief summary/intro of the organization requesting the data.
What the data is and how it benefits the Fil+ mission.
What specific actions are you seeking from the Notaries.

Video recordings with the Notaries both prior and after the Governance Call. During the call, if time permits you will be allocated time to answer any questions Notaries may have. Requests to showcase an Application or LDN should be submitted via a recorded video following the guidance in (Modification: Record presentations - Share projects async rather than live on Notary Governance Calls https://github.com/filecoin-project/notary-governance/issues/537)
If unable to upload your video to folder, please contact Kevin-FF in SLACK for troubleshooting support.

Notary Governance Meetings are recorded and posted to Youtube.
[https://www.youtube.com/playlist?list=PL_0VrY55uV1-cwaAU8lcChONxYQ_Bj9hx](https://github.com/filecoin-project/notary-governance/issues/url)

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/832

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/839

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/835

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/836

**Comment by Kevin-FF-USA** [comment]
5minutes - KYC review

**Comment by Kevin-FF-USA** [comment]
Trust and Transparency WG updates

**Comment by zcfil** [comment]
Hi, @Kevin-FF-USA,@galen-mcandrew   
I'm Fsector-ZC, from ZC LABS. We will introduce the Filecion graphical operation and maintenance platform developed by our team, which is mainly committed to solving the operation and maintenance threshold of Filecion and allowing more people to participate in the ipfs ecosystem

**Comment by Kevin-FF-USA** [comment]
Hi @zcfil 
Sounds like an interesting proposal.  Since this is coming through just before the call is going to begin I wont be able to add into the Agenda, but will give you first opportunity in the remaining COMMUNITY DISCUSSION section at end.  (2-3minutes)

**Comment by Kevin-FF-USA** [comment]
Link to the meeting recordings: https://youtu.be/KmD4kN0Z6qU

**Comment by Kevin-FF-USA** [comment]
[Project introduction of ZC automatic operation and maintenance management platform (for speech) - English.pptx](https://github.com/filecoin-project/notary-governance/files/10894275/Project.introduction.of.ZC.automatic.operation.and.maintenance.management.platform.for.speech.-.English.pptx)
Project Summary Slides shared by @zcfil  in this call. (not shown in recordings)
