### ISSUE TITLE
List of T&T WG members who have expressed interest in joining the T&T board

### ISSUE THREAD

**Issue by raghavrmadya** [filecoin-project/notary-governance#831]
Slack Name(s) | GitHub ID(s) | Official name/entity |   |   | What's your role in the Filecoin Network?
-- | -- | -- | -- | -- | --
Nelson | NSC-FIL | Nelson Chen |   |   | Storage Provider, Community Member
Hiddehoogland | Herrehesse | Hidde Hoogland - DCENT |   |   | Storage Provider, Client, Community Member, Large Investor / Early Adapter
Xinan Xu | xinaxu | Tech Greedy |   |   | Notary
PiotrS | PiotrStyla | Piotr Styła |   |   | Community Member, Saturn - storage provider
JonathanHooker | jhookersyd | Holon |   |   | Storage Provider
@Patrick-li | @liyunzhi-666 | Tianji Studio |   |   | Notary
Zhao KK | kikakkz | web3eye.io |   |   | Storage Provider, Community Member
LISA | stcouldlisa | STCould |   |   | Notary
ND LABS - OFFICE | ND LABS - OFFICE | ND LABS |   |   | Notary
Charles Cao - FilSwan | flyworker | FilSwan |   |   | Client, Community Member, Notary
wenxin | wenxinnnnn | FrogHub |   |   | Community Member
Laura Panda | aurarenpanda | FileDrive Labs |   |   | Client, Notary
Joss-Venus | Joss Hua | Venus team |   |   | Community Member, Notary, Project&Community Builder
jomozz-NewToken | jomozz | Hangzhou Niutong Information Technology Co., Ltd. |   |   | Notary
Carohere/Carolina | carohere | Carolina Lin |   |   | Notary
f8-ptrk | f8-ptrk | Factor8 Solutions |   |   | Storage Provider, Client, Community Member
CB Tan | cbtan21 | BigData Exchange |   |   | Community Member, Notary
Tim Yong | Tim-Yong | Isotechnics |   |   | Storage Provider, SP Management Consultant
James - PiKNiK | jamerduhgamer | PiKNiK |   |   | Storage Provider, Community Member, Notary
Jessie8o8 - PiKNiK | jessie8o8 | PiKNiK & Company |   |   | Storage Provider, Community Member, Notary
Wijnand schouten | Cryptowhizzard | Wijnand schouten / dcent |   |   | Storage Provider, Client, Community Member, Notary
Young | caoyoungyoung | StorSwift |   |   | Notary
Lucas (Lucas van Schouwen) | lvschouwen | Lucas van Schouwen |   |   | Storage Provider, Community Member
Eric-Bytebase | swatchliu | ByteBase |   |   | Notary
Fei Yan | kernelogic | Fei Yan - Kernelogic |   |   | Storage Provider, Client, Community Member, Notary
PluskitOfficial | PluskitOfficial | Pluskit |   |   | Notary
MS Cloud | MatrixStorage | MS Cloud |   |   | Notary
Pangod | Pangod | Pangod |   |   | Notary
Ewesion | Ewesion | Peter Shao |   |   | Notary
Benny -Aifabot | Aifabot-Cloud | Benny Wang |   |   | Notary
RawTech Ventures | RawTech Ventures | RawTech Ventures |   |   | Notary
Bobby Choi | BobbyChoii | Individual |   |   | Notary, Maybe DP one day
NDLABS-OFFICE | NDLABS-OFFICE | NDLABS |   |   | Storage Provider, Community Member, Notary
TAKI Chain |TakiChain | | | | Notary
BlockMaker | BlockMakeronline
Coulson | heroapn | | | | Client
cryptochen | crypochen	| | | | Storage Provider
CabrinaHuang |  xingjitansuo  |  |  |  |  Storage Provider, Client,, Notary

**Comment by raghavrmadya** [comment]
On February 1st 2023 - The T&T WG Lead shared a form in the T&T WG for members to share information in exchange for membership within the T&T DAO. A total of 38 responses were received but 1 applicant did not share their Github ID.

**Comment by raghavrmadya** [comment]
<img width="515" alt="Screenshot 2023-02-21 at 7 40 04 AM" src="https://user-images.githubusercontent.com/91579519/220393350-e5dfd3b3-34e9-493e-8fda-f774b5c59874.png">

**Comment by raghavrmadya** [comment]
Majority of the applicants were in support of staking to join the T&T DAO

**Comment by Tom-OriginStorage** [comment]
Hi @raghavrmadya 

may I inquire about the availability of joining the T&T Working Group Member.

If so, could you provide me with more information about the process and any requirements that need to be met?

**Comment by raghavrmadya** [comment]
Hi @Tom-OriginStorage, you are welcome to join the T&T WG by joining the slack channel. For this list, unfortunately the form is now closed but we hope to open it again in the coming months.

**Comment by raghavrmadya** [comment]
Current status on this: We are working with FF Legal team to understand legal implications of staking. Phil and myself have brainstormed a few ideas here - https://hackmd.io/0LjboMYvQ76emDXUjQy2Vg?view

**Comment by lvschouwen** [comment]
@raghavrmadya 
I would like to remove my name from the list.

**Comment by Carohere** [comment]
Not sure how the staking model will be atm. If it comes down to vote, I suggest limiting the valid votes to one per organization. i.e. avoid the same commonality of interests to ensure fairness, each organization can only pledge once.
