### ISSUE TITLE
Modification: 4th round Large Dataset Notary Multisig Signers v3.1

### ISSUE THREAD

**Issue by galen-mcandrew** [filecoin-project/notary-governance#835]
## Issue Description
To modify an existing multisig (such as adding and removing signers) requires each change to come with a proposal message and an approval. Since we are adding many new notaries to the signer pool with the 4th round of elections, this would require a massive lift. It is significantly easier to just create a new multisig address on chain, with the new set of signers, and award that multisig with DataCap, then point all the tooling and dashboards to the new address.

## Impact
This will not impact other programs, like E-Fil+ or the direct allocation pathway. Those will require other changes, out of scope of this specific modification.

## Proposed Solution(s)

We will refer to this as the LDN v3.1 address, since it is still functionally the same process: approved notaries, admins for maintenance, threshold of 2, and ongoing top-up from RKH based on 4 week DataCap outflow to LDNs.

Address: f02049625
Robust Address: f2yk6skf7mpk5mkp3bk5qyy5pmxgic6hfp55z2wcq
https://filfox.info/en/address/f2yk6skf7mpk5mkp3bk5qyy5pmxgic6hfp55z2wcq

### Signers
**Admins:**
_These are not intended to award DataCap to clients. These addresses are intended for governance team to make changes to signers as necessary, such as removal or updating with new address._

- G: f1a5b5cn5xgsmui2kivzj2eryzrqmhmew4tytj3by
- D: f14l6ugtjaqp72yfrum6mwpbmw6v6rncbqp64526y
- R: f1zndwxgee6xr7zlg2k2zos6aqu64uxlgajbprdmi

**Notary Signers:**
_Please note: these notaries should not add/remove/edit the signers on this multisig. Changes (such as a new Ledger address) should be processed through the Governance Team to check for disclosures and diligence._
* IPFS Force: f1ozt3gaqbnzfic6f2zsj4vppncws36ik5nqofhka
* Meibuy Cloud: f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
* Fungi Project: f1m6pqvscf7o5n3pzyxxb4w2soqgma7cfqh2z6fra
* Bobby Choii: f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
* FBG Capital: f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
* Protocan: f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
* Speedium / DCENT BV.: f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
* ZhongYiGuoLian: f1ho2liobpznr7llma6xcl7jtififsfvhdnudn4yy
* Ewesion: f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
* RawTech Ventures: f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
* Olivier Molenkamp: f1fl5gjqv3xknuhka273jrsrkzqcumrp6idrnvgyi (Removing for investigation)
* Blockmaker: f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
* Acrontech Inc.: f1kjyqtjjtco4dudknq6iszoevicebo6kz3crecpy
* Aifabot: f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
* Saukibit, Inc. (DBA Canza Finance): f1u46kil2f4kmo3pkaowqrohfueaijslm7limqxyq
* Bit Engine Pte Ltd: f1jyvhxp4kmwreo22ke4itspraznpudw3uqaink5i
* OPENGATE TECHNOLOGY INVESTMENT GROUP PTY LTD: f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
* Starboard: f1x5gaseatlcp7heucu7xms5sslcwerttexgigeoq
* BigData Exchange: f1dvvrjur7tstos2paxdsvdpljqx53c74wsp5cl4q
* Bitrise capital: f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
* 12Ships Foundation: f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
* Carolna Lin: f1pynuve3pi2fwvhlkco6dl3ipspkgzmb25syv5ca
* FogMeta: f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
* Holon Global Investments PTY Ltd: f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
* Top Value Limited: f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
* TopBlocks: f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
* Fenbushi Capital: f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
* Pangod: f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
* Banyan: f1oc6qvenzp7wsriu7edyebb325gnaovktmujl7jq
* Pluskit: f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
* Bewell Technology Limited: f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
* FILWallet: f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
* STCould: f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
* Ipollo: f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
* MS Cloud（formerly MatrixStorage）: f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
* Tokencan: f1txboxiscdm4f3okffyjmbilmwjtbisrbee72j6q
* Nebula Block Data: f1pkjtavqx4r2q2w3he3jknfc5mo2vgfimccmpnaa
* NewToken - Hangzhou Niutong Information Technology Co., Ltd.: f1qpdwt2f2fse74nl5wi27uk5jcyqqqyil47yqt7i
* Define Platform: f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
* New Huo Pool: f16karfxq7lxdy7izqrzrk75jf3not34k6sg6zvcy
* Twinquasar: f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
* mkccstorage: f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
* ByteBase: f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
* CoinSummer Labs: f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
* TAKI Chain: f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
* Guazi Dynamic: f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
* ND LABS: f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
* BigFrog Technology: f1nwjsd2mc6hu4qrwnmd6ukrfkuu4h5fhs7u3exii
* DeFIL: f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
* Direction Technology Co., LTD: f1inkdoatsbfumdvpctxbgcatscewr3rus5pxmsgi
* Kernelogic (sole corporation / self-employed): f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
* Tech Greedy: f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
* NonEntropy Tech.: f1xzff5xup63o5sygr2swp4zvcajg54lotliimdty
* Antalpha Digital Pte. Ltd.: f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
* LendMi team: f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
* ZC LABS: f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
* POW POWER: f1u2c7dpdqmlfk5zknafigcycrpzltcjd6nmjnuia
* METAVERSE DATA MINING PTE.LTD.: f17idrnfnxl2mbgcgr57a6z2c6lj2qx56gvm3336i
* Cabrina Huang: f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
* Force Community: f1yslbnnqzrjlyuxsmyxfbqcc7xthcavgpripjevi
* FileDrive Labs: f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
* Genesis: f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
* ORIGIN Storage: f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
* New Web Group: f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
* Tianji Studio: f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
* FilSwan: f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
* BlockchainWorld: f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
* IPFSMain: f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
* XnMatrix: f1bcvvwv3w6az7ivhdzory7anha54ocrlkxazm3yq
* StorSwift: f1dktm3abgn7wkpepxab4q3eaw24qktizk4esfzyy
* Greaterheat Pte.Ltd.: f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
* PiKNiK: f1kqdiokoeubyse4qpihf7yrpl7czx4qgupx3eyzi
* YuanHe Tech ( Firefly ): f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
* 1475: f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
* SXX Future Data: f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
* IPFS.CN: f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
* Venus Team: f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
* Filecoin Foundation: f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
* Interstellar Storage: f1ktp3fmcfnt3tjeansazq4ed5qkrs6pbn4lvwgvq
* CodoonHealth: f1sa3dp3a7fwirrsxjdthvzneo7rnjcrrfllsnjpq
* Ghost Byte: f1437jngablusaizqizc6sxp4r5llioq7mp2eqlii

### Timeline
New address created and awarded DataCap from RKH by Feb 24.
Dashboards and Registry tooling notified of new v3.1 address Feb 24.
All NEW LDN allocation requests (first and subsequent) initiated from Feb 24 will be requested from v3.1 address.
All open allocation requests that have one proposal (labeled "startSign") prior to Feb 24 will still pull from v3.0 address. This is necessary to not abandon the first notary proposal transaction. This affects ~44 issues.
All open allocation requests WITHOUT a proposal prior to Feb 24 will be updated to point to new notary v3.1 address. This affects ~364 issues.

### Technical dependencies 
Dashboards and registry tooling should update to track new address.

## Related Issues
This is similar to the LDN v3 issue, with the new set of notaries: https://github.com/filecoin-project/notary-governance/issues/509

**Comment by Joyologist** [comment]
@galen-mcandrew Hi Galen, I'm Joyologist from Tokencan. I'm afraid our address posted in the Notary Signers might be wrong. Please check our issue #746. Please let me know if there's anything you need. Thanks a lot!

**Comment by galen-mcandrew** [comment]
> @galen-mcandrew Hi Galen, I'm Joyologist from Tokencan. I'm afraid our address posted in the Notary Signers might be wrong. Please check our issue #746. Please let me know if there's anything you need. Thanks a lot!

Thanks! Edited parent comment, updated our tracking spreadsheet, and added to v3.1 msig [f02049625](https://filfox.info/en/address/f2yk6skf7mpk5mkp3bk5qyy5pmxgic6hfp55z2wcq)

**Comment by zcfil** [comment]
Hi Galen, I'm from ZC LABS. The wallet address we announced here needs to be modified. This is not the hardware wallet we use now. We have previously submitted the change record in the disclosure form and modified it in the [#643](https://github.com/filecoin-project/notary-governance/issues/643) application header, but it seems that there is no change here. Please update it for me, thank you!

**Comment by kyokaki** [comment]
@galen-mcandrew Hi Galen, this is from Interstellar Storage（ShenZhen). I checked that we didn't on the list, and we already received the ledger verified message at [768](https://github.com/filecoin-project/notary-governance/issues/768). Please let me know if there are any problems here, thank you so much!

**Comment by Trevor-K-Smith** [comment]
@Kevin-FF-USA Hey Kevin, i do not seem my name above. Thanks

**Comment by xingjitansuo** [comment]
I signed a LDN created later than Feb 24, but it still pull from LDN V3.0 address. Check my msg on LDN #[1696 ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1696#issuecomment-1448509579) https://filfox.info/en/message/bafy2bzacebyc4j6gmwtuucw2evbe2eqkoziilzbhz6kbcosty4j2bq4wqrxbi

**Comment by fillove** [comment]
hope that v4 will enter the job soon.
The quota of v3 410 was used up by the big SP within a week.
Those small SPs, slow SPs, and real customers want to move forward, but because 410 has no DC, and the new pool of V4 cannot sign, they are struggling and cannot survive.

**Comment by galen-mcandrew** [comment]
@zcfil & @kyokaki , will work on adding and updating.

@Trevor-K-Smith It appears we are missing comms between you and kwray, you will need to complete some additional steps. Check with kwray in Slack.

@xingjitansuo LDN's may still be pulling from the v3 notary. We are still making the switch, and there will be a rollover period.

**Comment by zcfil** [comment]
@galen-mcandrew Hi，I want to know when I can change my wallet address

**Comment by Trevor-K-Smith** [comment]
Please know if additional action needed by me, reached out via slack again on march 8th.

**Comment by zcfil** [comment]
@galen-mcandrew Hi,My wallet address: f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
"Modified here, but not modified here:"
[https://filfox.info/en/address/f2yk6skf7mpk5mkp3bk5qyy5pmxgic6hfp55z2wcq](https://filfox.info/en/address/f2yk6skf7mpk5mkp3bk5qyy5pmxgic6hfp55z2wcq)
Old wallet address: f17xummecmkqgjhm4fesktesaieumn7ugarwucwty
New wallet address: f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
Please help me adjust, thank you

**Comment by Kevin-FF-USA** [comment]
@zcfil 
Confirming this new updated address in your application, will be manually adding you on to the multisig in the coming sprint

**Comment by Kevin-FF-USA** [comment]
@Trevor-K-Smith 
Confirming receipt of your updated address: f1437jngablusaizqizc6sxp4r5llioq7mp2eqlii.  Will be adding to the multisig in coming sprint

**Comment by GhostByteInc** [comment]
> @Trevor-K-Smith Confirming receipt of your updated address: f1437jngablusaizqizc6sxp4r5llioq7mp2eqlii. Will be adding to the multisig in coming sprint

Thank you Kevin!

**Comment by zcfil** [comment]
> Will be adding to the multisig in coming sprint
Thank you Kevin!
We have confirmed, please help me add the new address to MSIG

**Comment by zcfil** [comment]
> @zcfil Confirming this new updated address in your application, will be manually adding you on to the multisig in the coming sprint

Thank you Kevin!
We have confirmed, please help me add the new address to MSIG

**Comment by GhostByteInc** [comment]
Hello, When time persists, i am awaiting `f1437jngablusaizqizc6sxp4r5llioq7mp2eqlii` to be added to the MSIG.

Ref: https://github.com/filecoin-project/notary-governance/issues/760

Thanks Team.

**Comment by GhostByteInc** [comment]
> Hello, When time persists, i am awaiting `f1437jngablusaizqizc6sxp4r5llioq7mp2eqlii` to be added to the MSIG.
> 
> Ref: #760

Hello, is there any update on adding this address into the multisig? I still do not see my address in there and respectfully still cannot perform any notary actions.

Waiting patiently for an update on this.
