### ISSUE TITLE
Large dataset multisig request: LDN v3.1 multisig

### ISSUE THREAD

**Issue by galen-mcandrew** [filecoin-project/notary-governance#836]
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 
    
## Core Information
- Name: LDN v3.1 multisig
- Affiliated Organization: Filecoin Plus Program
- Website / Social Media: https://filplus.storage/apply
- On-chain Address(es) to be Notarized: f02049625
- Country of Operation: n/a
- Region of Operation: [North America, South America, Europe, Africa, Greater China Region (GCR), Asia minus GCR, Oceania]
- Use case(s) to be supported: https://github.com/filecoin-project/notary-governance/issues/835
- DataCap requested for allocation (10TiB - 1PiB): 50PiB
- Are you applying on behalf of yourself or an organization?: Organization

**Comment by galen-mcandrew** [comment]
## Request Approved
#### Address 
> f02049625
#### Datacap Allocated
> 50PiB

**Comment by galen-mcandrew** [comment]
@fabriziogianni7 Trying to get this new LDN v3.1 msig to show up in the verifier front-end for RKH. Looks like I'm missing something in the parent comment. Is it requiring all the notary application questions before it will display?

**Comment by fabriziogianni7** [comment]
![Schermata 2023-02-27 alle 12 16 48](https://user-images.githubusercontent.com/46995085/221549996-b3dda61d-75ea-4258-a75b-6988ba1b6042.png)

hey @galen-mcandrew maybe you need to login with github?

**Comment by galen-mcandrew** [comment]
Interesting, I didn't think GitHub was required for RKH view.

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacedbmqprqj5r4n6oxou3fxbndkrg5t6sbpabzhpb75li2g3zb5k56g

**Comment by galen-mcandrew** [comment]
Thanks Fabri, looks like the root key holders were able to sign once I passed that on to them. Checking on chain, f02049625 now has 50PiB. Updating labels.

**Comment by Fatman13** [comment]
what is the action items for notaries here? The form linked is just a markdown file?

**Comment by galen-mcandrew** [comment]
@Fatman13 There is no action here for notaries, this is the 'application' for the large dataset multisig notary to the root key holders. This is where the root key holders can send DataCap to the multisig.

**Comment by galen-mcandrew** [comment]
Checking messages and chain, looks like RKH completed this top-up yesterday.

https://filfox.info/en/message/bafy2bzaceb2hvz6cesymir546muugh5qsto24kzk2z5xtk7olnsnj7tv6yoko

`lotus filplus check-notary-datacap f02049625
104011513003423824
`

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzaced52pkfxvoefchtzn3w47634ocm2jk44wmdtfss7gfwiari44ntgw

RKH let me know this cleared, confirmed on chain.

**Comment by galen-mcandrew** [comment]
This received second signature: https://filfox.info/en/message/bafy2bzacebdgjc7r5voweqsqxjvqve24jzc4x627z2dkx7jntwe4qyeddecak

**Comment by galen-mcandrew** [comment]
SSA bot did not trigger, and looks like this msig has ~370TiB remaining (maybe my calculations are off, and it wouldn't trigger until lower bound, can you fact check me @panges2 ?)

Kicking off manual allocation request to RKH for now.

**Comment by galen-mcandrew** [comment]
## Datacap Request For MultiSig
#### Address
> f02049625
#### Datacap Allocated
> 100PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacea4ifrcbidzwymdathozekmqrolgz6bgefme7aare2egifpla54ma?t=1

Second RKH

**Comment by galen-mcandrew** [comment]
## Datacap Request For MultiSig
#### Address
> f02049625
#### Datacap Allocated
> 100PiB

**Comment by galen-mcandrew** [comment]
RKH approval: https://filfox.info/en/message/bafy2bzaceaqaz66awjn4zry5u2u4ggpct4rdtqtsmoaheryyjn2vtfoeblidi?t=1

**Comment by galen-mcandrew** [comment]
## Datacap Request For MultiSig
#### Address
> f02049625
#### Datacap Allocated
> 100PiB

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacec6q2s4ztntsyyr7uqcw5g7fxjvtw7ayhzc3ivg67ytpa2mnvkxys?t=1

Approval from second RKH

**Comment by galen-mcandrew** [comment]
## Datacap Request For MultiSig
#### Address
> f02049625
#### Datacap Allocated
> 100PiB

**Comment by galen-mcandrew** [comment]
Approval here: https://filfox.info/en/message/bafy2bzacecutahkmega5654ic2fd2yo55ul5qakxxwvfal4ejjh6fsniqrbng?t=1

**Comment by nicelove666** [comment]
hope to speed up

**Comment by galen-mcandrew** [comment]
## Datacap Request For MultiSig
#### Address
> f02049625
#### Datacap Allocated
> 100PiB

**Comment by galen-mcandrew** [comment]
## Datacap Request For MultiSig
#### Address
> f02049625
#### Datacap Allocated
> 100PiB

**Comment by galen-mcandrew** [comment]
## Datacap Request For MultiSig
#### Address
> f02049625
#### Datacap Allocated
> 0PiB

**Comment by galen-mcandrew** [comment]
https://filscan.io/en/message/bafy2bzacebohqvxbf4cz4tkclom5ieqjwxqjn7ilijnjdchj6vnmysbclrdj2/
