### ISSUE TITLE
Issue: Asian Filecoin Storage Provider Convertor BootCamp - Large Amount Datacap application is on the way

### ISSUE THREAD

**Issue by AlanGreaterheat** [filecoin-project/notary-governance#845]
For community transparency purposes, GreaterHeat & Protocol Labs plan to start Asian Filecoin Storage Provider Convertor BootCamp. We would like to present the project details and plan to participate in a governance call on Tuesday, March 28, 2023 (as there are many notaries present to promote it live and contact them to work together) to discuss it with the community. 

The introduction of Asian Filecoin Storage Provider Convertor BootCamp
BootCamp Vision: Help Asian Storage Providers' FIL+ business transformation, as well as continuously widen the effective data storage capacity in Filecoin ecosystem. 
BootCamp Mission: Asian Filecoin Storage Provider Convertor BootCamp is expected to be officially launched before the middle of 2023. The main goal is to help 30 Filecoin CC Storage Providers within 6 months, creating an estimated adequate QAP of 1EiB for Filecoin network. 
BootCamp Resources: The vision and mission of the BootCamp will be adjusted according to the instant issues of Filecoin ecosystem. Before officially entering this project, the team gathered various resources demanded to implement the solution. As long as our current planning, these resources will come from GreatHeat and Protocol Labs respectively. 

Background: 
•Conventional LDN applications have a maximum quota of 5PiB, which is kind of difficult to meet the Bootcamp's requirement of 100PiB Datacap quota. In this case, LDN has to collect at least 20 different Applications. However, high-qualified datasets may only need 2-3 to meet the Bootcamp goal. 
•Develop high-quality data and make a data-storage history. Develop qualified data such as scientific associations, university archives, film art, etc., and establish cooperation between the storage client and Filecoin Ecosystem. In order to promote the development of real data storage in Filecoin eco. 

Usage:
The applied Datacap will serve the Storage Providers participants in the Bootcamp, in order to create 1EiB QAP of Fil+ storage growth. 

Type of the dataset: 
•Large-scale qualified enterprise datasets (Fil-E), in the form of filecoin-project/notary-governance/issue, which means the client will have the need for large dataset storage and the interest in utilizing Filecoin network to solve data storage problems. 
•High-quality public dataset (LDN), which can be researched with transparency, is meaningful to human development, such as meteorological data, geographic data, genetic data, etc. 

Commitment Statement of the Issues
•The Bootcamp team will go through the KYB process to verify clients by strictly following FIL+ rules, which include meetings with client teams, technical exchanges, data transmission tests, sample data verification, as well as limitedly disclosing client names and project basis, such as email correspondence, working document instructions, data transfer details & sample data, etc.
•We accept KYB from Filecoin community volunteer notaries about issues.
•As one of the organizers of Asian Filecoin Storage Provider Convertor BootCamp, GreaterHeat is willing to disclose some Storage Provider Node IDs for community review. 

The Transparency of FIL+ Guideline
•Submit proposal issues for the entire Bootcamp project in Notary Governance Repo;
•Submit 2-3 applications（each 30-50PiB / application ), each one will utilize the same client data;
•Each Datacap application will be assigned to Storage Provider Participants according to the Bootcamp arrangement;
•Each LDN needs at least 4 volunteer notaries to support this application.

Data Storage Plan
•The client will apply the DataCap quota according to his/her actual situation. Each client will have 5-10 complete copies. The Bootcamp will do its best to collect 2-3 applications(30-50PiB each) to reach the goal of 100PiB. 
•If a large scientific research association is with 5PiB, we can directly apply for 50PiB Datacap with 10 copies. 

Storage Provider Partnership
To prove the value proposition of Decentralized Data Storage, storage providers in Asia are welcome to cooperate together to store 100PiB DataCap.

Notary Partnership
More volunteer notaries are welcome to participate in the review of large Datacap.

Thank you Fil+ community for supporting us, we really appreciate it. Our Bootcamp team will actively persuade new storage providers to participate in this prosperous community. It would be great if we could receive some valuable feedback from you. Please don't hesitate to join us to co-contribute to Filecoin ecosystem!

**Comment by kernelogic** [comment]
Increasing the maximum DC has been brought up by me before, but I guess this time is for FIL-E which is different circumstances.

https://github.com/filecoin-project/notary-governance/issues/594

**Comment by liyunzhi-666** [comment]
Nice proposal, it's nice to see large and reliable data onboarding the Filecoin network. I have some questions and suggestions.

- Am I to understand that this project is a community-based Slingshot?
- There will be a Notary working group dedicated to reviewing the project?

I see that the dataset types are E-Fil+ and LDN, but as far as the workflow is concerned, the KYB review and subsequent DD for these two dataset types are not quite the same. So I think the dataset types should be unified.

**Comment by AlanGreaterheat** [comment]
> Increasing the maximum DC has been brought up before, but I guess this time is for FIL-E which is different circumstances.
> 
> #594

This #594 proposal is great！This provides a good idea to apply DCs for large amounts, which effectively circumvents wallet address discrepancies, questions and replies carried out in the same process, and LDN number splitting, compared to applying DCs by sequence.

**Comment by AlanGreaterheat** [comment]
> wow, would love to see any projects that promote the development of the network.
> 
> A few minor questions about this project:
> 
> 1. Is this project only for encrypted data (E-FIL)?
> 2. Is data transmission offline or online, or both, but with a certain proportion?
> 3. Can this project be understood as: the project party provides the dataset, the SP in the Asian community provides storage, and the community notary provides review? In addition, who are the clients?
> 4. Can other organizations in the ecosystem participate deeply, such as the Venus team?

Thanks to Joss for the questions～

1. this project is equally welcoming to E-fil and public datasets.
2. the data transfer depends on the SPs actual situation, online transfer would be much easier, but offline transfer is not out of consideration.
3. the main goal of this project is to help 30 Filecoin CC SPs successfully transition to DC SPs within 6 months, creating an estimated 1 EiB of effective computing power for the Filecoin network. The dataset will be jointly developed and found by PL and GH. In order to improve the efficiency of DC approval, we hope more notary volunteers will join this project, those who are interested can leave a direct message and we will communicate in detail.
4. We welcome more ecological partners to join this project and grow the filecoin network together.

**Comment by AlanGreaterheat** [comment]
> Nice proposal, it's nice to see large and reliable data onboarding the Filecoin network. I have some questions and suggestions.
> 
> * Am I to understand that this project is a community-based Slingshot?
> * There will be a Notary working group dedicated to reviewing the project?
> 
> I see that the dataset types are E-Fil+ and LDN, but as far as the workflow is concerned, the KYB review and subsequent DD for these two dataset types are not quite the same. So I think the dataset types should be unified.

Hi @liyunzhi-666 , thank you for adding your thoughts on this proposal.
1. This project is a PL and GH co-build project, plan to apply for 100PiB DC to serve 30 Asian SPs in BootCamp.
2. We welcome messages from interested notaries, and we plan to form a special Notary working group dedicated to this project.
3. For the type of 100PiB DC dataset applied for, both E-fil and LDN are welcome. Because it is a large DC application, a dedicated Notary working group is necessary.

**Comment by Carohere** [comment]
Resharing a few concerns I raised at T&T WG call:
- Which party will perform KYC on these miners and will the node ownership and the miner's identity/organization be made public to the community/notaries? 
- Will it be possible for notaries to kyc these node operators individually?
- Given that the project is focused on CC storage miners. How do you plan to verify that these participants are technically & financially pledgeable to complete this project? Previously I have seen organizations that have received DataCap but never sealed at all. It would be nice to avoid such occasions.

**Comment by AlanGreaterheat** [comment]
> Resharing a few concerns I raised at T&T WG call:
> 
> * Which party will perform KYC on these miners and will the node ownership and the miner's identity/organization be made public to the community/notaries?
> * Will it be possible for notaries to kyc these node operators individually?
> * Given that the project is focused on CC storage miners. How do you plan to verify that these participants are technically & financially pledgeable to complete this project? Previously I have seen organizations that have received DataCap but never sealed at all. It would be nice to avoid such occasions.

@Carohere Thanks for your patience in listening.
1. bootcamp itself has four phases of the journey, such as customer KYC, interviews, training and guidance, business implementation, etc., pending bootcamp official announcement.
2. We welcome valuable input from notaries and the community. SPs joining bootcamp will first go through KYC and one-on-one interviews with the bootcamp team, and we will also develop a login interface to collect information from SPs.
3. Yes, bootcamp is all about service and support, and that's not just in terms of business training, but also in terms of O&M systems and filcoin financials. This will all be announced after the official announcement.

**Comment by TrueBlood1** [comment]
>•High-quality public dataset (LDN), which can be researched with transparency, is meaningful to human development, such as meteorological data, geographic data, genetic data, etc.

Not sure where these datasets come from. Who will be collecting the public datasets? What is the difference between this and Slingshot, Evergreen, etc.? 

>For the type of 100PiB DC dataset applied for, both E-fil and LDN are welcome. Because it is a large DC application, a dedicated Notary working group is necessary.

E-fil has its own process and notary team. What's the workflow in between? 

>SPs joining bootcamp will first go through KYC and one-on-one interviews with the bootcamp team, and we will also develop a login interface to collect information from SPs.

What is the structure of Bootcamp team? Will  SPs' information be publicly available? 

>This project is a PL and GH co-build project, plan to apply for 100PiB DC to serve 30 Asian SPs in BootCamp.

Can anyone from PL provide more information about this project? When is the official announcement?

**Comment by caoyoungyoung** [comment]
Greaterheat brings the dataset?

**Comment by AlanGreaterheat** [comment]
> > •High-quality public dataset (LDN), which can be researched with transparency, is meaningful to human development, such as meteorological data, geographic data, genetic data, etc.
> 
> Not sure where these datasets come from. Who will be collecting the public datasets? What is the difference between this and Slingshot, Evergreen, etc.?
> 
> > For the type of 100PiB DC dataset applied for, both E-fil and LDN are welcome. Because it is a large DC application, a dedicated Notary working group is necessary.
> 
> E-fil has its own process and notary team. What's the workflow in between?
> 
> > SPs joining bootcamp will first go through KYC and one-on-one interviews with the bootcamp team, and we will also develop a login interface to collect information from SPs.
> 
> What is the structure of Bootcamp team? Will SPs' information be publicly available?
> 
> > This project is a PL and GH co-build project, plan to apply for 100PiB DC to serve 30 Asian SPs in BootCamp.
> 
> Can anyone from PL provide more information about this project? When is the official announcement?


Sorry for the late reply, We have been busy with the Hong Kong conference preparation some time ago.

1. public datasets mainly come from AWS, libraries, archives and other channels, DSPA project team will carry out public dataset docking, of course, we do not exclude cooperation with well-known DPs in the community.

2. Yes, E-fil we will follow the official rules, we need special volunteer notaries, the main purpose is to speed up the efficiency of LDN approval.

3. Bootcamp team has PL and GH together, mainly project manager, community manager, brand manager, customer service manager, pre-sales engineer, etc. The information of SP will be made public inside Bootcamp.

4. PL-related personnel involved in Bootcamp know more about the project, which has been officially announced in Hong Kong on April 15. https://blockchainwire.io/press-release/greaterheats-accelerator-asia-paves-the-way-for-decentralized-enterprise-storage-on-filecoin-at-hong-kong-web3-festival-2023

**Comment by AlanGreaterheat** [comment]
> Greaterheat带来了数据集？项目是否启动？什么时候dealine？

Thanks for your attention. The dataset will be docked by GH owner and PL will provide data resources. bootcamp project has been officially announced in Hong Kong on April 15. https://cryptounfold.org/greaterheats-accelerator-asia-paves-the-way-for-decentralized-enterprise-storage-on-filecoin-at-hong-kong-web3-festival-2023/

**Comment by stcouldlisa** [comment]
I have a question: how much about  retrieval rate ?
