### ISSUE TITLE
Deciding the appropriate staking method 

### ISSUE THREAD

**Issue by raghavrmadya** [filecoin-project/notary-governance#846]
## Issue Description
To enable the T&T Board and eventually the T&T DAO, we are introducing staking to ensure there is weight and accountability to the actions and decisions within the T&T WG. A few proposals were put forward, and their pros and cons are outlined in #847. After feedback from the legal and engineering teams, we seek community feedback on the following two staking options. 

## Proposed Solution(s)
- Tracked Wallet: Participants transfer a specified amount of FIL to a wallet designated as their "tracked wallet" by the Fil+ governance team. Fil+ monitors the wallet to ensure it always contains at least the specified amount of FIL, and penalizes participants who deviate from this requirement.

- Burner Wallet: Participants transfer a specified amount of FIL to a burner wallet to join the T&T Board, with no expectation of reclaiming their FIL.

## next steps
The next steps involve discussing these options in the upcoming T&T working group and notary governance calls, to finalize a plan within two weeks. Other proposed implementations, such as the Fil+ treasury and optimistic governance, pose legal and technical difficulties that would significantly increase the development timeline. Therefore, the Fil+ governance team has decided to refrain from pursuing these options for the initial version.

### Timeline
2 weeks

**Comment by panges2** [comment]
The Trust and Transparency working group proposes implementing a staking solution for potential participants to gain decision-making privileges as part of the T&T Board. After evaluating several proposed implementations, two potential options remain:

Tracked Wallet: Participants transfer a specified amount of FIL to a wallet designated as their "tracked wallet" by the Fil+ governance team. Fil+ monitors the wallet to ensure it always contains at least the specified amount of FIL, and penalizes participants who deviate from this requirement.

Burner Wallet: Participants transfer a specified amount of FIL to a burner wallet to join the T&T Board, with no expectation of reclaiming their FIL.

The next steps involve discussing these options in the upcoming T&T working group and notary governance calls, with the goal of finalizing a plan within two weeks. Other proposed implementations, such as the Fil+ treasury and optimistic governance, pose legal and technical difficulties that would significantly increase the development timeline. Therefore, the Fil+ governance team has decided not to pursue these options for the initial version.

**Comment by caoyoungyoung** [comment]
A little confused, what's the difference between tracked wallet and burner wallet? Fils are staked for pulishment. @raghavrmadya
