### ISSUE TITLE
Modification: Notary due-diligence flow and template comments

### ISSUE THREAD

**Issue by panges2** [filecoin-project/notary-governance#850]
## Context
We propose the introduction of new labels for LDN applications, as well as template comments that notaries and clients can post to prompt the SA bot to apply these labels. Notaries will use these template comments as a lightweight mechanism to show their engagement with a given DataCap application.

This will make it easier for notaries to share their takeaways for each application, help bring others in the community up to context in the future, and enable improved tracking for each DataCap application so clients understand how their application is being interpreted by notaries.

These are explicitly not required to be used, and the saved reply comments themselves without justification will not be considered sufficient diligence. Our goal is to provide some additional structure to help make the notary process more streamlined and consistent and increase the client experience by providing more at-a-glance insight into the status of their application. As we test this, we can build additional tooling that makes this process even easier and more reliable, so we welcome the collaboration and feedback.

## Proposed labels

1. `needsNotaryReview`: This label indicates that the application requires a notary review.
2. `waitingForClientReply`: If a notary requires additional evidence, they can apply this label, signifying that they are awaiting the client's response.
3. `oneNotaryReviewed`: This label indicates that at least one notary has reviewed the application but requires more information. 
4. `oneNotaryDeclined`: This label indicates that at least one notary has declined the application.
5. `oneNotaryApproved`: This label indicates that at least one notary has approved the application.

Note that during the due diligence phase, one of the first two labels must always be applied. These labels are separate from those currently applied when a notary signs (e.g., `readyToSign` and `startSignDatacap`). As an LDN application currently requires two different notary signatures (proposal and approval), the state must return to `needsNotaryReview` after the first notary signs, as another notary's review is required.

Additionally, the `oneNotaryReviewed`, `oneNotaryDeclined` and `oneNotaryApproved` labels can coexist with any of the other labels. A notary can still review an application even if it has been previously reviewed, declined, or approved.

## Proposed templates and flow

![](https://i.imgur.com/WhzWjfn.png)

When a notary has completed due diligence and believes that the application can be allocated DataCap, they can add the `oneNotaryApproved` label by posting the following template comment. If it is the first notary to approve, the `needsNotaryReview` label will not be removed.
> I have reviewed the application, it meets my stated diligence process, and I will support for the following reasons: <reasons>

When a notary disapproves of an application, they can apply the 'oneNotaryDeclines' label by posting the following template:
> I have reviewed and I will not support due to:
    - Conflict of interest
    - Not in my expertise or domain
    - Outside my regional jurisdiction
    - Requested amount does not match dataset
    - Client deal-making behavior does not match stated allocation strategy
    - Client did not provide information about the Storage Providers they are working with 
    - Fil+ data distribution noncompliance (Incorrect SPs that client stated that they would work with in their application)
    - False information that was provided from application
    - Other reason: <please put your reason here>

If a notary requires more evidence to conduct due diligence, they can apply the `waitingForClientReply` label by posting the following template. This would also add the `oneNotaryReviewed` label to issue to indicate that a notary has reviewed the application but required more information:
> I have reviewed but am not ready to support yet. There is insufficient information about: 
    - Data Samples 
    - Why the client requires the requested amount of DataCap
    - The legitimacy of the client or the associated business
    - The legitimacy of the data that the client is storing
    - Who the client plans to store their data with and where they are located
    - Other reason: <please put your reason here> 

To inform notaries that they have provided the requested evidence, clients can use the following template. By doing so, the `waitingForClientReply` label will be removed and the `needsNotaryReview` label will be added. It's important to note that the bot will only update the labels if the GitHub user who opened the issue is the user posting this template.:
> I have provided the additional required information: <the additional information>
    
Note that all the above templates encourage notaries to provide reasons for their actions. This aims to reduce spam approvals and generate data for the client growth team to analyze.

## Impact
This proposal significantly enhances transparency in the LDN application due diligence phase between notaries and clients, fostering collaboration among notaries and streamlining the review process. Notaries in the Filecoin Plus ecosystem can openly indicate their approval or disapproval of an application, allowing other notaries to form a preliminary assessment of applications before examining them in detail. The proposed templates also encourage notaries to provide clear reasons for their decisions, reducing spam approvals and maintaining the ecosystem's integrity.

Moreover, the generation of more data for analysis through these labels and templates can be utilized by the client growth team to gain valuable insights into the application process and identify areas for improvement. Depending on the adoption and success of these labels, they could serve as a foundation for future tooling decisions, such as the development of automated systems or dashboards that provide real-time status updates and trend analysis to enhance the Filecoin Plus ecosystem further.

## How to post template comments

1. On the top right of the "Leave a comment" section, click on the "select a reply" button. Then click on "Create a new saved reply..."
![](https://i.imgur.com/VjnFiOU.png)

    
2. Add the templates as written here as new saved replies. Then Click on "Add saved replly" on the bottom right.
![](https://i.imgur.com/AcWLzPn.png)

3. Now in any issue, you can click the "select reply" button again. The new saved reply should be an option for you.   
![](https://i.imgur.com/H3BpJMd.png)

4. It should automatically paste the whole template as needed.   
![](https://i.imgur.com/jbRehDb.png)

5. Remember that these templates offer multiple options for justification. Before clicking on the "comment" button, select an option by deleting the rest. In the case of selecting "Other reason", write your reason where it says "< please put your reason here >". We will not accept the reply if you do not select one of the options. 
![](https://i.imgur.com/o1zUhIf.png)

**Comment by dannyob** [comment]
This looks _great_, thanks for considering this. How quickly could we get this up and working?

**Comment by panges2** [comment]
@dannyob, thanks for the interest! We're trying to have an early version up by the end of the week, but latest should be by next week

**Comment by METAVERSEDATAMINING** [comment]
Great, leave reasons to review, provide real-time status updates.
Will it also be used in the E-FIL?

**Comment by kyokaki** [comment]
Really nice! It would help us save more time to reviewing applications. Also the problem that we go though the all requests status at these days is need speend more time to check, it also solved. Hope this would working soon.

**Comment by panges2** [comment]
@METAVERSEDATAMINING Yes this will be implemented for E-Fil applications too

@kyokaki There are other features coming soon to summarize LDN applications, too this will not be the only one. We want to make your lives as notaries as painless as possible!

**Comment by cryptowhizzard** [comment]
Looking great. You have our full support for this.
