### ISSUE TITLE
Modification: Full Upfront Check toward efficient initial allocation approval (via E-Fil+ pilot)

### ISSUE THREAD

**Issue by kevzak** [filecoin-project/notary-governance#853]
## Issue Description
Over the past few months we've been testing the random assignment of notaries as part of the E-Fil+ pilot. 

See background of the initiative: https://github.com/filecoin-project/notary-governance/discussions/810#discussion-4762993 and https://github.com/filecoin-project/notary-governance/discussions/807

See notary engagement analysis: https://github.com/filecoin-project/notary-governance/discussions/807#discussioncomment-5445629

**Key Observations**
1) The test on E-Fil notary WG engagement (defined as: required commenting on an allocation request within 48-72 hours) has seen 60% of assigned notaries meet the SLA over a sample size of 106 assignments across 14 applications.                       
- Learnings about engagement:
  - In general, expecting any random notary to be available for immediate review as allocation requests come in any time, any day is not realistic. Reasons for missed assignment were either they did not acknowledge a GitHub notification in time, or were on holiday/on vacation or unavailable for personal/business reasons.
  - Unreviewed assignments required multiple re-assignments to eventually find two notaries who were fully engaged and completed an allocation request. However, even once engaged, the back and forth async communication with clients would take days for each side to see a question/message in GitHub and reply. This entire cycle toward engagement and approval was taking anywhere from 5-14 days to complete.
  - Likewise, the randomized assignment of notaries created review situations that required a lot of time and energy to review previous comments and understand what has already been asked and what needs to happen next. Ideally, we can look to find notaries who are involved from start to finish of an application.
 
2) Even with KYC/KYB checks being completed upfront as a requirement by the client, notaries still asked for more info about datasets and SPs involved, causing delays in approvals because of the back and forth communication required with applicants until more information was disclosed. 

3) Within the set of E-Fil+ applications, there were only 5% of assigned notaries that declined to sign, and no applications were closed. 
  - Some preliminary inferences here include:
    - The upfront vetting of clients and data required before notary review may have minimized potential spam, illegitimate, incomplete, or abusive applications submitted via this pathway.
    - If an E-Fil+ client and SPs are willing to share all details, and then complete storage as planned to meet Fil+ guidelines and requirements, they should continue to be awarded DataCap allocations until completion.

4) Feedback from participants:
- We've learned based on direct feedback from SPs, that continuously waiting more than 24-48 hours for each allocation approval is directly impacting E-Fil+ clients and SPs experience and impressions of Filecoin Data Onboarding. 
  - Specifically for E-Fil+ clients who are willing to meet upfront verification expectations, they are expecting better service SLAs as a result.
  - Likewise for the SPs involved, by waiting for notary approvals to store verified data, they are losing significant potential revenue ($1000s/Day).

**Iteration recommendations of the E-Fil+ notary review process**
- Within the E-Fil+ pilot, we'll look to iterate toward a more efficient review process for verified clients:
  - First, by leveraging more upfront information requirements to build required client/application trust
  - Second, by removing assignments and enabling all E-Fil+ notaries to be eligible to review applications as requests comes in.

## Proposed Solution(s)
1) We'll implement a **_[full upfront check](https://form.jotform.com/231003748181651)_** for any new or current E-Fil+ client applicants to build a required trust level toward initial approval

Based on notary feedback, we've learned that a **_full upfront check_** includes:
- E-Fil+ KYC check of the Data Owner
- E-Fil+ KYB third party Business check
- A complete list of SPs participating in the project
  - Including Business Name, Miner ID, Locations
  - And signoff from SPs confirming their datacenter location and their participation with the applicant
- Dataset size and # of copies (Total DataCap requirements explained)
- Dataset proof of size (Ex: screenshot such as cloud drives, local disks, etc.)
- Dataset sample review (under NDA if required)

Applicants will complete [this form](https://form.jotform.com/231003748181651) and all information will be reviewed for completeness by the E-Fil lead prior to notary review.

2) We'll move away from notary assignment and instead leverage the E-Fil WG multisig to allow any of the available notaries to be able to respond to more immediately to allocation requests. 
- General Fil+ notary guidelines remain the same as listed here: https://github.com/filecoin-project/notary-governance/tree/main/notaries#operational-guidelines
- We'll look to identify time to engagement for notaries to see if there is any difference versus assignment

**Tests on the impact of Full Upfront checks toward efficient allocations**
Over the next 2-3 months, we'll test the next 10-15 dataset applications in the following areas:
- The number of Full Upfront Check applications that met notary approval expectations without additional questions/comments
  - We want to confirm if the full upfront check is providing the needed requirements toward trust expectations for approval 
- The number of notaries that were active and engaged toward a 24-48 hr SLA for allocation review
- The time to allocation completion (Time from allocation review notification to comment by notary)

**Comment by FILDCKabat** [comment]
I think it’s a good idea, it should really speed up the process

**Comment by salstorage** [comment]
Seal Storage Technology supports this proposal
- Current tranches and delay in notary signing allocations slow down ability to seal as we have to shut down sealing services while waiting for next allocation tranche. This delay means lost revenue
- Backend Operational resources are impacted due to reissue of dealing making with other SP's
- Current allocation limitations do not scale for Enterprise level onboarding.

**Comment by caoyoungyoung** [comment]
Great idea ! Maybe it needs to select more notaries to engage in the E-fil+ project

**Comment by kevzak** [comment]
This project is underway. We will report back in Q3 of any initial findings
