### ISSUE TITLE
Removal of Notary from v3.1 multisig

### ISSUE THREAD

**Issue by raghavrmadya** [filecoin-project/notary-governance#855]
## Issue Description
We have received reports of potential identity theft by a current v3.1 notary. The claim states that the notary has stolen the identity of a prominent individual outside the Filecoin ecosystem or Protocol Labs Network. The governance team has made attempts to contact the accused notary but has not received any response. The identity of the individual who was the claimed victim of the identity theft is being kept confidential to protect public defamation. 
  
## Impact
Identity theft is a serious violation of Fil+ rules and guidelines and has strong grounds for the removal of the accused stakeholder from the Fil+ program

## Proposed Solution(s)
As a result of no response from the accused notary, the governance team, on the recommendation of the T&T WG Lead, has requested the multisig admins to remove the notary from the v3.1 multisig.

### Timeline
multisig admins informed of notary removal - April 17th 2023
multisig admins act to remove notary from v3/1 multisig.- by EOD April 19th 2023

### Technical dependencies 
Signatures from multisig admins

**Comment by dkkapur** [comment]
ACK I think v3.1 has a handful of admins from FF / Governance team that can step up to support this. 

Looks like proposal was already made to the multisig based on your notification of this issue: https://filfox.info/en/message/bafy2bzacednnmshs6whtp5vwby54aqsihz6qbi4a7nvdi2muvw4jeilkgedwk

I can audit and follow-up with an approval.

**Comment by dkkapur** [comment]
For audit trail purposes - connected with RG / T&T WG and am OK with proceeding with this action. FWIW, this is easily reversible in case we do get it wrong, but the confidence level is high enough to push through here. Thanks to those that came forward with this and provided the necessary information.

**Comment by dkkapur** [comment]
Approval message: https://filfox.info/en/message/bafy2bzaceclrpqf6n6d5tf4gqs6obt7cn2fzmpzfte5c643yiorc2blmw7jgo
