### ISSUE TITLE
Green Scores to earn notary trust in due diligence process

### ISSUE THREAD

**Issue by raghavrmadya** [filecoin-project/notary-governance#860]
## Issue Description
As Filecoin plus moves into the [quality phase](https://medium.com/filecoin-plus/announcing-the-quality-phase-for-filecoin-plus-2890a9797456?source=collection_home---6------4-----------------------), the community has an opportunity to explore new ways for clients to earn notary trust.

One of the major concerns we hear from Notaries today is that is challenging for them to assess the legitimacy of the SP IDs that a client provides during the due diligence process. Doing SP KYC is beyond the direct scope of the Filecoin Plus program as it focuses on client-driven deal-making; hence, client KYC and trust mechanisms are the current top priority. But we can leverage other teams and mechanisms in the Filecoin Network to provide a higher level and quality of SP KYC than what exists today.

One such mechanism can be the Green Scores developed by the Filecoin Green team to identify SPs using sustainable energy sources in their operations. 

## Impact
By allowing notaries to leverage the green scores in the due diligence process, notaries can gain a higher level of trust in handing out DataCap if the clients signal that they will be storing their copies with SPs on the Greenscore list

## Proposed Solution(s)
The current solution proposed is allowing Notaries to use the greenscores as a valid argument to support signing on an incoming application as part of their due diligence process. This will also require a collaboration between the T&T WG and the Filecoin Green team to ensure that the WG and Filecoin Plus community understands the robust scoring methodology that the Filecoin Green team is using to come up with the green scores for transparency reasons.

### Timeline
April 23rd 2023 - Proposal
April 23rd - May 2nd - Discussion
May 2nd - Consensus shared on T&T WG call

### Technical dependencies 
Greenscores.xyz

**Comment by raghavrmadya** [comment]
To add to the proposal, I had an opportunity to connect with @mjohnson518 on their methodology for the sustainability audit as well as the SP KYC they are doing for attesting the different tiers for sustainability. As the T&T WG Lead, I believe the Filecoin Plus community can immensely benefit from the work that the Filecoin Green team is enabling.

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/notary-governance/issues/854

**Comment by raghavrmadya** [comment]
This proposal is considered to be accepted following the principles of optimistic governance seeing no active pushback from the community
