### ISSUE TITLE
Modification: Specialized Pathways to DataCap by Data and Applicant Type

### ISSUE THREAD

**Issue by kevzak** [filecoin-project/notary-governance#872]
## Issue Description
Currently all Large Dataset applications (LDN) are collected and organized in the same GitHub repo 

## Impact
There is currently no easy way to:
- Distinguish by Dataset type or applicant type
- Differentiate or standardize as needed by more specific application requirements 

## Proposed Solution(s)
Organize the application process into different application pathways by:

- Data Type
    - OPEN PUBLIC
    - COMMERCIAL PUBLIC
    - PRIVATE
- Applicant Type
    - Data Owner
    - Data Preparer
    - Lead SP / Onboarding SP
    - Aggregator / ISV (Proxy to many clients)

### Timeline
Light weight iteration (limited tech change requirements)
- [X]  Develop Categories to be turned into labels in GitHub - May 1
- [x]  Review application question flow for each pathway and recommend iterations - May 7
- [x]  Confirm needed changes to dashboards, tools, documentation - June 1
- [x]  Create clear applicant instructions per pathway - June 15

### Technical dependencies 
None expected for light weight iteration change - need to discuss with Keyko, AU, Dmob

**Comment by kevzak** [comment]
posting a comment from the original discussion here: https://github.com/filecoin-project/notary-governance/discussions/848#discussioncomment-5795447

This makes a lot of sense to me and is a much better user segmentation than just doing things blindly by size.

It has the potential to unify all DataCap applications into a single repo instead of splitting across the [filecoin-project/filecoin-plus-client-onboarding](https://github.com/filecoin-project/filecoin-plus-client-onboarding) and [filecoin-project/filecoin-plus-large-datasets](https://github.com/filecoin-project/filecoin-plus-large-datasets) repos, if that's something we want (it does feel cleaner).

Segmentation can be done via Github labels as we do now

**Comment by liyunzhi-666** [comment]
I support this proposal, it makes easier for clients to understand the type of data they want to store. And also convenient for the initial review by the notary.
