### ISSUE TITLE
Modification: Notary due-diligence flow v0.1

### ISSUE THREAD

**Issue by panges2** [filecoin-project/notary-governance#884]
## Issue Description

**This is a continuation of this issue here: https://github.com/filecoin-project/notary-governance/issues/850**

To summarize the above issue, we have implemented changes to the Fil+ registry app to enable notaries to take actions other than signing it. One such action is the ability to "decline" an application, indicating to other notaries that the application has been declined by at least one notary. These changes aim to help notaries filter through applications and provide additional data on notary behavior in the Fil+ system.

In this continuation post we will be discussing the differences between what was actually implemented vs what was proposed in the previous issue. The following design changes were decided as they simplified the proposed process in terms of technical implementation and UX. 

## Implementation changes

Instead of adding the previously proposed five labels (`needsNotaryReview`, `waitingForClientReply`, `oneNotaryReviewed`, `oneNotaryDeclined`, `oneNotaryApproved`). We are just adding three different labels:
- `one notary declined`: This label indicates that at least one notary has declined the application. 
- `waiting for client reply`: If a notary requires additional evidence, they can apply this label, signifying that they are awaiting the client's response. This label is rmeoved once the notary receives the next allocation (if two notaries sign the application)
- `verified client`: This means that this client application has received at least 1 allocation, which in turn means that there were at least two notaries that sign the application.

We removed `needsNotaryReview` because we think that it is the default state and applications should always be needing notary review. We also removed `oneNotaryReviewed` because `waitingForClientReply` implicitly means that a notary has reviewed it. If it is after the first allocation, then there will always be the `verified client` label which again implicitely means that there was at least one notary that has reviewed it. 

The flow is changed to be like the following with the new labels:

<img width="1415" alt="Screen Shot 2023-05-23 at 12 06 31 AM" src="https://github.com/filecoin-project/notary-governance/assets/96081835/d8bf5a70-3e8e-4bf2-a6c4-edce700628de">

## How to use

1. When opening the usual fil+ registry on [filplus.fil.org](https://filplus.fil.org) you will notice a new column below titled "Actions"

<img width="1306" alt="dd1" src="https://github.com/filecoin-project/notary-governance/assets/96081835/700cf761-f8f2-46a1-ae19-5f8897eb14c8">

2. A notary can "act" on an LDN application by clicking on the pencil icon on the right. Once the pencil icon is selected, the following menu will appear. In this menu the notary may select "Request More Information" or "Decline"

<img width="1318" alt="dd2" src="https://github.com/filecoin-project/notary-governance/assets/96081835/722ac41e-6210-4eb7-b6cb-4f0b634b414d">

3. If "Request for more evidence" is selected, the notary may select a type of evidence to request more information for. Additionally they may also enter other types of evidence to request. When they click on send, a comment from that notary is posted on the application asking for more evidence from the notary. the label `waiting for client reply` is added to the application to notify to the client that they are waiting for more evidence. This label will only be removed when the current allocation is granted.

<img width="1378" alt="dd3" src="https://github.com/filecoin-project/notary-governance/assets/96081835/67d55fbb-67c3-4e71-9af2-2ac77ad637dd">

<img width="1236" alt="dd4" src="https://github.com/filecoin-project/notary-governance/assets/96081835/d952ac03-782c-4159-ac2e-86acfd0fe3fe">

3a. When the client (the github user who created the application) posts a comment providing more evidence, a notification counter is incrimented on the registry front end to notify the notary that the client has replied. Additioinally the clients comments are tracked for the notary to be able to inspect. 

<img width="1179" alt="Screen Shot 2023-05-23 at 12 13 06 AM" src="https://github.com/filecoin-project/notary-governance/assets/96081835/cb9683b0-1255-4838-8c2d-668b29e0d43e">

<img width="1340" alt="dd6" src="https://github.com/filecoin-project/notary-governance/assets/96081835/657d8833-03fa-429c-9c94-573c26193489">

<img width="462" alt="dd7" src="https://github.com/filecoin-project/notary-governance/assets/96081835/792426a4-d144-47d1-b873-f611853d4216">

4. If "Decline" is selected, the notary may select a reason for why they declined. Additionally they may also enter a reason for declining in the text box. After they click on send a comment from that notary is posted on the application claiming that they decline for the above reason. the label `one notary declined` is added to the application and never removed. This does not effect the application in any other way, other notaries can still approve it.

<img width="1370" alt="Screen Shot 2023-05-22 at 5 53 43 PM" src="https://github.com/filecoin-project/notary-governance/assets/96081835/8d02f47b-01f1-494d-8cab-36fe3b40699e">

<img width="1329" alt="Screen Shot 2023-05-22 at 5 54 39 PM" src="https://github.com/filecoin-project/notary-governance/assets/96081835/b0d9938d-a493-409f-be2f-7d54464bd61b">

## Possible future changes

Like other features on the Fil+ tooling, this particular feature is subject to ongoing iterations. In the future, we might refine the interface to reduce the number of clicks required for notaries to utilize it. Our aim is to encourage a larger number of notaries to make use of this feature, as it contributes to transparency within the Fil+ system. However, we also want to avoid adding any unnecessary complexity to the already intricate process of datacap issuance.

If you have any ideas or suggestions for modifying this implementation, please feel free to share them in the comments section or reach out to @philippe-pangestu on Slack. We value your feedback and are open to making further improvements.

**Comment by destor2023** [comment]
Hi Phillippe, it looks like the function is not working yet. When will it be online?

**Comment by psh0691** [comment]
Thank you for making a good tool. 
I saw it, but I didn't use it. I'll use it a lot.

**Comment by MatrixStorage** [comment]
This is a nice feature that makes the operation of the notary much easier.

**Comment by PluskitOfficial** [comment]
It's a great tool and I'll try it soon.
But at the moment it seems to be one-way, I mean, when comments are posted directly on Github, they cannot be synced to the fil+ registry.

**Comment by 1ane-1** [comment]
if i support the LDN, should i have to leave the reason?

**Comment by a1991car** [comment]
Thank you for your hard work. When we sign, do we need to leave support on GitHub and the signing website at the same time?

**Comment by NDLABS-OFFICE** [comment]
This is a very useful tool, thank you for your work

**Comment by spaceT9** [comment]
Great work

**Comment by Aaron01230** [comment]
nice
