### ISSUE TITLE
Pause signing on applications under dispute

### ISSUE THREAD

**Issue by raghavrmadya** [filecoin-project/notary-governance#895]
## Issue Description
We have seen instances where notaries have continued to sign applications under dispute on the [dispute tracker](https://www.notion.so/filecoin/T-T-Dispute-Tracker-d28b93677cb544b48e77b585856601cf) often hindering enough time for a dispute to be resolved. 

## Impact
This can lead to a slowdown of allocations 
It can lead to an increase in quality of DC flow

## Proposed Solution(s)
This issue proposes pausing signing on applications that are under dispute. The dispute may be against the client, an SP working with the client, or a notary. 

### Proposed Timeline
Discussion on June 27th T&T WG call
Community input until June 30th 2023 5 PM EST
Decision released async in the Fil-plus channel as well as T&T WG channel at 5:01 pm EST

### Technical dependencies 
N/A

**Comment by herrehesse** [comment]
I agree with the suggestion, perhaps adding a bot message below applications marked with "ACTIVE DISPUTE" could help. This would serve as a useful indicator to draw attention to notaries checking the application. Additionally, if notaries proceed to sign such applications, they should be put on hold and requested to provide clarifications.

**Comment by Chris00618** [comment]
This label seems to be quite obscure at the moment, should we fill it as soon as possible?

**Comment by raghavrmadya** [comment]
@Chris00618, what do you mean?

**Comment by raghavrmadya** [comment]
Seeing no major pushback, this issue is considered passed. All future applications under dispute should not be signed.
