### ISSUE TITLE
Auduting DC FogMeta Labs LDNs

### ISSUE THREAD

**Issue by raghavrmadya** [filecoin-project/notary-governance#897]
## Issue Description
I have observed some inconsistent behavior with FogMeta Labs and I would like to open a community audit on all of FogMeta Labs' applications
## Impact
Removal of DC if found abusing DC

## Proposed Solution(s)
Manual audit of all applications till date.

### Timeline
Week of June 26th 2023

**Comment by raghavrmadya** [comment]
While the application is in audit, notaries are requested to not sign further allocations.

**Comment by Carohere** [comment]
For anyone willing to share input, please see the relevant applications [here](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+is%3Aopen+fogmeta).

**Comment by Normalnoise** [comment]
We accept the questioning from the community, but we want to know why only us?

**Comment by raghavrmadya** [comment]
Zcfil has an usually high signatures on your application. Also no reply after getting the allocation.

**Comment by raghavrmadya** [comment]
@hengdingy, don't worry, others are coming but that shouldn't prevent you to share more information about your deal-making behavior

**Comment by hengdingy** [comment]
Fogmeta Labs applications can be found [here](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+is%3Aopen+fogmeta),  

We are trying to distribute the data to the storage providers in different regions following the Fil+ rule.  Every application's cid report can be found in the issue comment. I paste some reports here. All deals are sent to storage providers by filswan's bidding engine as it says in the application.

<img width="849" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/9c9d0981-9028-415f-9722-ee34d6645113">
<img width="939" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/9712a8ae-ff5d-433d-834d-b4b49104f5f6">
<img width="926" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/cc7501ad-c460-4d98-878b-b2575f53211b">
<img width="773" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/5c5c373f-a93f-4c08-b214-91dbc276a938">
<img width="998" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/2af7d877-6deb-407e-9299-6820d81c2f08">
<img width="907" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/38dfebac-93d8-4cfd-8c97-8aee0dfc61f1">

**Comment by hengdingy** [comment]
Some of the notaries who due diligence our applications can be found [here](https://datacapstats.io/large-datasets?filter=fogmeta)

<img width="784" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/071ca7d7-38ce-4a71-bc1b-485663f22a81">
<img width="768" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/13262fe3-2442-4225-aa35-e20f070e7010">
<img width="759" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/23aedd0e-3913-4620-93bc-9de27a087641">
<img width="765" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/57e5c78a-4dfe-4f8e-a141-3ae5024a826a">
there are many notaries' due diligence on our applications, Full due diligence will be done every time, let me list some screenshot

<img width="643" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/a002c85f-89b9-44fb-8945-2290adcc73c6">
<img width="584" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/f8d86b44-9ffd-40c9-9882-24b78f8f4a0d">
<img width="639" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/f191f7d6-298e-451d-aa86-96705bdf8f56">
<img width="655" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/4b0e6d2e-0913-4745-8f77-f336dc0dc5de">
<img width="522" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/1d097999-b81d-408c-ba2f-fb0a1f9fe4f2">
<img width="589" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/6d314740-d010-4b26-85d9-6025ade5a092">
<img width="822" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107467232/084ccbd0-7d0a-4ff3-92ad-a98c5bdd640d">

**Comment by raghavrmadya** [comment]
Thanks. Still open questions on applications # 1733-1742. They all have been granted datacap once and have not used any yet since May timeframe. Zcfil signed many of these

**Comment by kernelogic** [comment]
From one client to another, I would guess FogMeta Lab might got a bit too optimistic about how much DC they can onboard and the gas fee has slowed down the onboarding for many SPs in the past few months.

**Comment by hengdingy** [comment]
@kernelogic Thanks for your understanding. 
@raghavrmadya We are preparing the dataset and have sent the deals to the some storage providers. In addition, many thanks to @zcfil for supporting our application for this series(one big dataset)
