### ISSUE TITLE
Discussion: Orienting Clients to Filecoin Plus

### ISSUE THREAD

**Issue by zixuanzh** [filecoin-project/notary-governance#9]
## Goals
- Provide recommendations/suggestions to prospective storage clients on how to think about and approach Filecoin Plus
- Start community discussion on how a Filecoin Plus Client should think about selecting a miner and requesting features

## Background
- Filecoin is a global platform economy enabled by blockchain technologies. This is something new and it is what many of us in this industry have envisioned for years. It is now time to make it happen.
- The Filecoin protocol innovatively puts power in the hands of storage clients to make the Filecoin Economy work for them. Clients, especially early Filecoin Plus clients are active participants in shaping the products and services on Filecoin.
- As the community collectively develops Filecoin Plus, what should a Filecoin Plus client consider when selecting a miner to store data with?

## Recommendations

- Filecoin Plus is all about storage clients. Filecoin is an evolving protocol with a thriving ecosystem but the economy is as strong as the community make it to be.
- Filecoin is an underlying protocol that enables participants like storage miners to offer competitive storage services to existing cloud providers. Filecoin Plus clients are helping themselves, miners, and the network to make that a reality.
- To start, what would a client want? Latency, redundancy, privacy, locations, different clients may have different combinations of needs but feel free to request them from miners. The Filecoin protocol provides the baseline guarantee that the storage is reliable and all those additional features are supported by the protocol. Filecoin Plus gives miners ten times the revenue to serve specific needs of clients.
- Given that Filecoin is a decentralized protocol, there is an extra responsibility of decentralization that storage clients may want to consider. However, if a storage client really cares about their storage, this problem will take care of itself. For example, it is better for a client to store multiple copies of their data in different data centers, with different miners to reduce correlation risks. In addition, if a client wants to store data in a specific region that miners do not provide at the moment, request for it. These rational actions by storage clients will make the network more useful and decentralized.
- Last but not least, when making deals it is the clients' responsibility to ensure they are staying in compliance with the miner’s stated Terms of Service and Content Policy. Clients who are found to violate miner’s policies may be ineligible for future DataCap allocations and other repercussions.

**Comment by flyworker** [comment]
Filecoin clients is more like an agent, since the real client who use the service is always through  software applications. As an agent, he has the right to choose different miners as his vendors,however, since he has 10X power, bribe can be an issue. On the other hand , a client has so much power but what he can benefit from it by allocation datacap to other miners?

**Comment by MegTei** [comment]
HI @zixuanzh I am leading a Foundation funded project with IDC starting in Jan that will research and interview a global community to represent the client problems to be solved and the Filecoin value propositions we may offer. Let me know if you would like to be kept in the loop about this

**Comment by dkkapur** [comment]
Closing this issue out. For folks interested in spinning up discussion threads on topics related to this, please do here: https://github.com/filecoin-project/notary-governance/discussions.
