### ISSUE TITLE
Unreachable Miners

### ISSUE THREAD

**Issue by SPWG1234** [filecoin-project/notary-governance#906]
## Issue Description
I'm a member of the SP WG and I would like to flag that the following miners are unreachable 

f0466405
f03624
f01619524
f01920091
f01228089
f01443744
f01861488
f020522
f02169409
f02528

## Impact
They are likely abusing the Fil+ system
## Proposed Solution(s)
While I understand that Fil+ team does not have much power over SPs, clients should not deal with them.

The owners of these SPs should declare themselves are share with the community why they are unreachable. Retrievability is also an issue on these nodes.

**Comment by herrehesse** [comment]
@SPWG1234 Lets try and connect with the entities behind these SP's and show them this thread: https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1688029823430619

With a few updated and adaptations all storage providers storing verified data can reach 100% retrievability success. If they do not respond, want to work together or simply disable retrievability, then move on with your solutions.

**Comment by Chris00618** [comment]
Let's dig out the notaries hiding behind these SPs and remove these rule breakers immediately. @raghavrmadya

**Comment by raghavrmadya** [comment]
Hi @Chris00618, While the Fil+ program does not have the ability to remove miners, lack of engagement and response can be seen as a sign of a bad reputation and it's upon the clients to pause deal-making with any SP IDs. I'm actively working to improve the retrievability.

**Comment by sgclouder** [comment]
Declare？So do I need to register to mine?  What is the meaning of distributed. @SPWG1234 Love to hear your opinion.

**Comment by sunjiebin** [comment]
Hello, my miner ID is 20522. I would like to request your assistance in providing a list of unsuccessful retrievals for the following CID. My program has encountered both successful and unsuccessful retrievals, and I would appreciate it if you could provide me with a specific inventory. Here are some screenshots of my search。
<img width="1435" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/33552080/0abfdfe1-037a-4c1f-84a2-1e427e9f14d7">

**Comment by sunjiebin** [comment]
Hello, my miner ID is 20522. I would like to request your assistance in providing a list of unsuccessful retrievals for the following CID. My program has encountered both successful and unsuccessful retrievals, and I would appreciate it if you could provide me with a specific inventory.

Below is a screenshot of my retrieval deal.
<img width="1337" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/33552080/01ef33bd-c3ff-443b-8929-3a30723329ce">

**Comment by herrehesse** [comment]
@sgclouder, registering to mine Filecoin is not a requirement. In fact, it is possible to mine anonymously using a VPN, ensuring zero traceability and complete confidentiality. However, if you wish to leverage the multiplier known as "datacap," it is essential to comply with the guidelines of the Filecoin+ program and ensure that the files you store are easily retrievable.

It appears contradictory to desire the benefits of datacap without being willing to fulfill the necessary requirements. Such an approach seems peculiar to me.
