### ISSUE TITLE
Notary block always signing together

### ISSUE THREAD

**Issue by raghavrmadya** [filecoin-project/notary-governance#907]
## Issue Description
The following notaries consistently sign in pairs 

[BobbyChoii](https://github.com/BobbyChoii)
[Casey-PG](https://github.com/Casey-PG)
[Aifabot-Cloud](https://github.com/Aifabot-Cloud)
[TakiChain](https://github.com/TakiChain)

Here's more evidence - https://github.com/filecoin-project/notary-governance/issues/892#issuecomment-1611178238

## Proposed Solution(s)
Removal of aforementioned notaries from the main multisig 

### Proposed Timeline
Community Discussion - June 29th 2023 - July 6th 2023
Decision announced - July 11th 2023 Gov call

**Comment by lilisy90** [comment]
This is common and widespread in the community now! We should look into phenomenon and make great efforts to rectify the egregious case!

**Comment by lilisy90** [comment]
I knew that many notaries have formed private unions and have even built some groups for cooperation. The phenomenon of signing for each other's applications is serious. It is time to strongly rectify it. 

I will help to expose these phenomenons together!

**Comment by herrehesse** [comment]
Supportive of removing the above notaries from the Multisig. We have opened multiple disputes against these notaries previous to the above allegations. 

Disputes: https://filecoin.notion.site/T-T-Dispute-Tracker-d28b93677cb544b48e77b585856601cf

**Comment by igoovo** [comment]
There are already few active notaries, and this situation is inevitable. Notary authority can be warned but should not be removed.

**Comment by herrehesse** [comment]
@igoovo what is the result if an abusive notary gets a warning? They will just continue with the abusive behavior.

**Comment by BobbyChoii** [comment]
I get a lot of messages on slack from clients asking for signatures. Clients may send information to notaries on a large scale hence the pair of notary sign-offs may overlap. It is difficult for a limited number of active notaries to avoid similar combinations.

**Comment by Aifabot-Cloud** [comment]
I really don't see a causal relationship between the evidence you provide and to the conclusion you are trying to prove. There are not many active notaries. It is quite normal to provide signatures for some applications under LDN scope.

**Comment by TakiChain** [comment]
A group of notaries vs. a group of application vs. a group of nodes
I'd like to know what the definition of "signing together" is, is it 2 notaries, or 4, or 8, or 16?

**Comment by TakiChain** [comment]
Without a clear definition, all notaries could be defined as suspected. This will only create more community conflict and disagreement. I think the primary concern is whether these applications in question are slef-dealing? If quotas are distributed to a large number of decentralized nodes, I don't see a problem with this.

**Comment by herrehesse** [comment]
@BobbyChoii @Aifabot-Cloud @TakiChain

Not only are you visible and constantly signing in pairs to quickly push datacap, but you have also neglected the majority of your notary responsibilities. Your actions have resulted in a significant allocation of datacap being allocated to dubious clients without conducting proper due diligence. Evidence suggests that you have collaborated together, as indicated by previous unresolved disputes that were raised several months ago. Unfortunately, your behaviour has persisted unchanged since then, and none of you have been able to convincingly refute any of the allegations. What's even more concerning is your complete lack of response to any of the previous disputes visible on the dispute tracker since May 6th ([link](https://filecoin.notion.site/T-T-Dispute-Tracker-d28b93677cb544b48e77b585856601cf)).

I am no longer interested in playing this cat and mouse game. It is evident that you have failed in your duties as notaries and have contributed no value to the Filecoin network with the reckless distribution of datacap. Therefore, removal is the appropriate course of action.

**Comment by Casey-PG** [comment]
The consensus on signature we acknowledge is that the same notary can't sign off on immediately subsequent allocations. Four notaries(A, B, C, & D) AB+CD+AB is allowed in the FIL+ rules. @raghavrmadya are you familiar with this? If not, we would like to suggest you sync with @dkkapur. Long term members of the community are all aware of it.

**Comment by herrehesse** [comment]
@Casey-PG, you have been involved in several disputes since May 6th ([link](https://filecoin.notion.site/T-T-Dispute-Tracker-d28b93677cb544b48e77b585856601cf)) across various platforms. It is disappointing to witness your arrogant behavior towards RG. It is evident that you are aware of your abusive practices, and the network would benefit from your absence.

**Comment by Casey-PG** [comment]
@herrehesse We have offered our point of view over and over to your arrogant charges with no evidence. You chose to ignore the fact and keep slandering us with your interpretation on LDN rules. That's your choice and it's ok, we are over the phase to explain thousands times to you. If you have any disagreements on clients, LDN rules, notary election rules and so on, if it is not specific to the topic of this proposal, please carry your discussion somewhere else. Thank you.

**Comment by Casey-PG** [comment]
> The consensus on signature we acknowledge is that the same notary can't sign off on immediately subsequent allocations. Four notaries(A, B, C, & D) AB+CD+AB is allowed in the FIL+ rules. @raghavrmadya are you familiar with this? If not, we would like to suggest you sync with @dkkapur. Long term members of the community are all aware of it.

@raghavrmadya We have no intention offending you. With all due respect, I'm just laying out the fact from https://github.com/filecoin-project/filecoin-plus-large-datasets regarding sign requirement. We have responded to charges with no evidence or written rules many times over the past two months. It's wearing us down. It's very important for us to know the exact process and get to further discussion. We sincerely ask for your understandings.

**Comment by Carohere** [comment]
> A group of notaries vs. a group of application vs. a group of nodes I'd like to know what the definition of "signing together" is, is it 2 notaries, or 4, or 8, or 16?

> > The consensus on signature we acknowledge is that the same notary can't sign off on immediately subsequent allocations. Four notaries(A, B, C, & D) AB+CD+AB is allowed in the FIL+ rules. @raghavrmadya are you familiar with this? If not, we would like to suggest you sync with @dkkapur. Long term members of the community are all aware of it.
> 
> @raghavrmadya We have no intention offending you. With all due respect, I'm just laying out the fact from https://github.com/filecoin-project/filecoin-plus-large-datasets regarding sign requirement. We have responded to charges with no evidence or written rules many times over the past two months. It's wearing us down. It's very important for us to know the exact process and get to further discussion. We sincerely ask for your understandings.

@TakiChain @Casey-PG to answer your questions specifically, I have talked with several long-term recognized members of the community. So in the LDN framework the same two notaries signing back-to-back allocations is not allowed. You could, for example have four notaries (A, B, C, & D). A & B could sign the first allocation, C & D the second, and then A & B could sign the third allocation and so on. That said, one LDN application needs to be signed by at least four notaries. The discussion can be found [here](https://github.com/filecoin-project/notary-governance/issues/217#issuecomment-908504325). 

As a community-driven program, everyone has their own understandings. It is this difference that allows us to hear more opinions and lead us toward a greater consensus. TT Working group is designed to address the various concerns that may arise during client onboarding. It aims to help notaries better evaluate the compliance of applications and definately not to add frictions. Appreciate everyone‘s engagement for community transparency. Please feel free to share if there's anything else you would like to add 🙏

**Comment by raghavrmadya** [comment]
No conclusive outcome achieved through this discussion
