### ISSUE TITLE
Removal of notary from the FIL+ program

### ISSUE THREAD

**Issue by herrehesse** [filecoin-project/notary-governance#908]
## Issue Description

Notary [XnMatrixSV](https://github.com/XnMatrixSV) signs off datacap allocation with statement "Everything looks healthy. I would like to support this. Good work!" while the application has zero retrievability, 100% VPN use and no distribution as promised in client application.

Also visible on issue: https://github.com/filecoin-project/notary-governance/issues/903

## Proposed Solution(s)
Withholding from doing due diligence and blindly signing an application with visible problems is not something we can longer accept from notaries and therefore I would suggest to remove [XnMatrixSV](https://github.com/XnMatrixSV) from the pool of notaries.

## Timeline
Discussion at the next 2023 WG Call
Decision announced by the T&T WG Lead after

## Technical dependencies
Removal from main multisig

## Related Issues
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1264

**Comment by HiFil** [comment]
@herrehesse  There are so many notaries involved in validating this application as you mentioned, why did you only add XnMatrixSV to the removal list and purposely ignore the other notaries involved?

**Comment by herrehesse** [comment]
@HiFil Thank you for bringing up this important point. It is indeed true that there are numerous notaries involved in the validation process for this application. The reason why XnMatrixSV was specifically added to the removal list is because their improper signing was clearly evident and the most recent. Once we have obtained a resolution regarding the matter raised in this issue, we will list and address the other notaries as well.

**Comment by herrehesse** [comment]
@HiFil You have the ability to copy/paste the list of involved notaries yourself, and others can also access the [application](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1264) to see everyone involved. It is important to note that not every signing notary is automatically considered abusive. As I mentioned earlier, I focused on the removal of XnMatrixSV for specific reasons.

**Comment by raghavrmadya** [comment]
Yes I'll add it to the agenda
