### ISSUE TITLE
Notary block always signing together

### ISSUE THREAD

**Issue by lilisy90** [filecoin-project/notary-governance#909]
## Issue Description
The following notaries consistently sign in pairs

[1ane-1](https://github.com/1ane-1)
[psh0691](https://github.com/psh0691)
[Rongze92](https://github.com/Rongze92)/[SuperChaiChai](https://github.com/SuperChaiChai)
[ipollo00](https://github.com/ipollo00)
[Normalnoise](https://github.com/Normalnoise)
[YuanHeHK](https://github.com/YuanHeHK)
[igoovo](https://github.com/igoovo)
[woshidama323](https://github.com/woshidama323)
[zcfil](https://github.com/zcfil)
[liyunzhi-666](https://github.com/liyunzhi-666)

**Here's more evidence**

![a](https://github.com/filecoin-project/notary-governance/assets/117716675/9c4d8371-dfe8-4e34-ad05-3a6f32b8034f)
![b](https://github.com/filecoin-project/notary-governance/assets/117716675/fc6645e7-55c4-46a0-b044-2a51409e5beb)
![c](https://github.com/filecoin-project/notary-governance/assets/117716675/abc41f3f-3402-4f0e-8937-3f229c6a47e9)
![d](https://github.com/filecoin-project/notary-governance/assets/117716675/b2484010-9ff4-41c2-b59c-1940d4cf8543)
![e](https://github.com/filecoin-project/notary-governance/assets/117716675/fd104f2f-70e4-4f64-8f28-4cc4ccf8f8eb)
![f](https://github.com/filecoin-project/notary-governance/assets/117716675/c0617fad-e371-4906-8bb2-bcb80b75ffd4)
![g](https://github.com/filecoin-project/notary-governance/assets/117716675/a66037d0-d1e5-48c4-977d-94883fdba540)

## Proposed Solution(s)
Removal of aforementioned notaries from the main multisig

## Proposed Timeline
Hope more discussions about it from now!

**Comment by herrehesse** [comment]
@lilisy90 Can you give me a list of LDNs to conduct my own research. It is crucial to gather sufficient evidence before forming a definitive opinion on the involvement of numerous notaries in abusive practices. While I firmly believe that there is a **significant number** of notaries engaged in abuse or displaying abusive behaviour, I personally need more information to support the proposed solution.

Regarding signing in pairs, it is important to note that it is not inherently abusive. Although patterns can appear who show the evidence leading to abusive notary behaviours, as we shown and disputed here already: https://github.com/filecoin-project/notary-governance/issues/907

**Comment by raghavrmadya** [comment]
I have spent my morning looking at collusion patterns on the aforementioned notaries and I personally did not find a high level of confidence in the patterns. Please note that I look at total number of signatures ever made and then find signing blocks. The block to signing ratio is very low for the aforementioned notaries. Still, if your analysis is different or if you have further evidence, please post it here

**Comment by liyunzhi-666** [comment]
Since onboarding the Notary I have signed over 150 applications (including E-Fil+). I took the time to check your corrections in the morning and found that both of them were E-Fil+ applications. I should be one of the most active E-Fil+ notaries (KZ should be able to give me proof). So continuous review, continuous signatures, that can't be avoided.
So I don't think there is a case for "working together" as you say.

**Comment by kernelogic** [comment]
Even by looking at the screenshot I immediately recognized these notaries sign on the same series of a dataset. I would say it is completely normal when a pair of notary happen to sign on multiple LDNs of the same series.

**Comment by Normalnoise** [comment]
The client will DM in the slack or channel for a series of a application(same dataset). after the DD, I am willing to support all  or part of the applications. I believe other notaries are the same action. So it is normal a pair of notary sign on multiple LDNs(same dataset)

**Comment by igoovo** [comment]
Notaries who do nothing should be removed.
Instead of notaries who actively provide services to the community.

**Comment by zcfil** [comment]
During our tenure, we reviewed a total of 50+cases, and it is normal for notaries to happen to sign multiple LDNs in the same series.

**Comment by psh0691** [comment]
Notaries who know each other can sign enough. I don't think this is a problem.  
1. If it's signed by a trusted notary I know, I'm willing to sign it because it saves me the trouble of due diligence.

2. An application signed after one validation is likely to be signed in the next round, so the signature may be duplicated.


3. Notaries who are actively engaged in activities are bound to overlap with each other. You need to resolve the issue of inactive notaries.

4. If the problem is a notary who always signs together, I think it is also a good idea to automatically designate a specific notary for each application to conduct due diligence, and to increase responsibility by signing it. We need to discuss more ways and procedures for this...

**Comment by YuanHeHK** [comment]
Since several LDNs happen to be signed by two identical notaries, it is considered a violation, which is very absurd and irresponsible.

**Comment by herrehesse** [comment]
@YuanHeHK you “find” it absurd and irresponsible. That is something different.

The truth is, some notaties work together to push abusive applications and by dual signing they can immediate grant datacap and help the client / SPs receive datacap.

Notaries should never ever work in pairs, the only sightings might be random, which is acceptable, but patterns are most likely a form of abuse.

Patterns everywhere.

**Comment by NDLABS-OFFICE** [comment]
On one hand, the community demands active participation from notary publics, while on the other hand, it requires that notary publics should not have too high a probability of overlapping cases. These two requirements clearly conflict with each other. Each notary public has disclosed their own examination standards during the application process. As long as they conduct examinations in accordance with these standards, I believe they are qualified notary publics. Let's not make those active notary publics who are certified examiners feel that their efforts are in vain.

**Comment by YuanHeHK** [comment]
@herrehesse Perhaps you didn't understand me correctly, but I mean that it is arbitrary to assume that a notary colludes by the fact that some LDNs happen to be signed by two identical notaries.

I'm not saying it's reasonable for notaries to sign in pairs, I think there's a greater chance of a coincidence here.

In fact, we now have more than 400 LDNs waiting to be signed, including at least 800 LDNs that have been completed and approved. There are only more than 20 examples above, and we have no more than 30 notaries who are active and willing to sign. With so much signing workload for a relatively small number of notaries to sign, there is a reasonable probability that the situation before the problem description appears.

**Comment by YuanHeHK** [comment]
Yes, there will inevitably be some fraud in more than 400 LDNs. But it must be admitted that regardless of whether these 400 are fraudulent or not, and whether these LDN applicants have created more than 10 LDNs in a matter of minutes, the number of these examinations and the workload of the examinations are constant.

**Comment by herrehesse** [comment]
An increase in abuse does not automatically equate to an increase in the number of signatures required. While narrowing down the influx of abusive entities could be considered as a potential solution, I firmly hold the belief that eliminating abuse from the network would prevent many of these entities from re-entering the LDN application phase in the future.

**Comment by raghavrmadya** [comment]
No conclusive evidence that the block is intentionally abusing. Closing issue as it's become stale with no comments for over a month
