### ISSUE TITLE
Notary block always signing together

### ISSUE THREAD

**Issue by TrueBlood1** [filecoin-project/notary-governance#910]
## Issue Description
**The following notaries consistently sign in pairs**

[kernelogic](https://github.com/kernelogic)
[NiwanDao](https://github.com/NiwanDao)
[laurarenpanda](https://github.com/laurarenpanda)
[newwebgroup](https://github.com/newwebgroup)
[Joss-Hua](https://github.com/Joss-Hua)
[xinaxu](https://github.com/xinaxu)

Evidence
![E11](https://github.com/filecoin-project/notary-governance/assets/126061227/b6991115-eb9f-498a-afca-b88975e35888)
![E112](https://github.com/filecoin-project/notary-governance/assets/126061227/0335969e-fe73-4ebb-919f-8eee8861705e)
![E21](https://github.com/filecoin-project/notary-governance/assets/126061227/cded3031-beb1-4ed4-a2d2-89f24daca27a)
![E212](https://github.com/filecoin-project/notary-governance/assets/126061227/51a6a85c-33bc-4c6a-8831-4880426c39bd)
![E1213](https://github.com/filecoin-project/notary-governance/assets/126061227/229deb44-6cbf-468a-ae45-4df2489fedc2)

## Proposed Solution(s)
Removal of aforementioned notaries from the main multisig
### Timeline
Discussion at the next 2023 WG Call
Decision announced by the T&T WG Lead after
### Technical dependencies 
Removal from main multisig

## Related Issues
#907 #909

**Comment by kernelogic** [comment]
I sign more than 200 of LDNs so far. These kind of things bound to collide and by no means we are working together like you are insinuating here.

**Comment by raghavrmadya** [comment]
Thanks for posting and thanks for clarifying @kernelogic. If the OP has additional comments/evidence, please add

**Comment by NDLABS-OFFICE** [comment]
On one hand, the community demands active participation from notary publics, while on the other hand, it requires that notary publics should not have too high a probability of overlapping cases. These two requirements clearly conflict with each other. Each notary public has disclosed their own examination standards during the application process. As long as they conduct examinations in accordance with these standards, I believe they are qualified notary publics. Let's not make those active notary publics who are certified examiners feel that their efforts are in vain.

**Comment by TrueBlood1** [comment]
Here's more evidence about signing together as below

**Comment by TrueBlood1** [comment]
[kernelogic](https://github.com/kernelogic)

![E33](https://github.com/filecoin-project/notary-governance/assets/126061227/17351231-d112-467a-a4d4-c3dfe003995a)
![E255](https://github.com/filecoin-project/notary-governance/assets/126061227/b54a3265-9291-4af9-858a-dac119dc6dae)
![E322](https://github.com/filecoin-project/notary-governance/assets/126061227/0d600430-bf3e-4b38-bb6c-76f657778a66)
![E343](https://github.com/filecoin-project/notary-governance/assets/126061227/cb677074-4eb7-42dd-9ee1-cc0f94ff0a61)
![E358](https://github.com/filecoin-project/notary-governance/assets/126061227/a2da2e57-aa7a-44d0-9162-16f714b94f04)
![E359](https://github.com/filecoin-project/notary-governance/assets/126061227/e0c56749-ea36-4ef4-9303-43a8d7c92d2a)

**Comment by TrueBlood1** [comment]
[NiwanDao](https://github.com/NiwanDao)

![E401](https://github.com/filecoin-project/notary-governance/assets/126061227/277ff5e0-5561-4471-b24a-eb4723541d24)
![E429](https://github.com/filecoin-project/notary-governance/assets/126061227/3d73f965-3aee-4451-8005-ae86a61a4fcc)
![E418](https://github.com/filecoin-project/notary-governance/assets/126061227/ba4d5f94-06c5-4566-95e5-c0bbbf245753)
![E420](https://github.com/filecoin-project/notary-governance/assets/126061227/2563b322-41c7-435f-9cb9-e4168cb78cf2)
![E421](https://github.com/filecoin-project/notary-governance/assets/126061227/1b457674-911c-4b9a-9286-40fc2dc7be1a)
![E422](https://github.com/filecoin-project/notary-governance/assets/126061227/2cdbc057-dd63-4fa4-84ec-636942678ec6)

**Comment by TrueBlood1** [comment]
[laurarenpanda](https://github.com/laurarenpanda)

![E423](https://github.com/filecoin-project/notary-governance/assets/126061227/4680c302-3b98-4d8d-8ca9-85be6b0e7e46)

**Comment by TrueBlood1** [comment]
[newwebgroup](https://github.com/newwebgroup)

![E424](https://github.com/filecoin-project/notary-governance/assets/126061227/b228169f-030d-4b2f-aa64-977b4374afea)
![E425](https://github.com/filecoin-project/notary-governance/assets/126061227/f3beb345-755d-48d6-9de7-743a3c99c262)

**Comment by TrueBlood1** [comment]
[Joss-Hua](https://github.com/Joss-Hua)

![E426](https://github.com/filecoin-project/notary-governance/assets/126061227/06b95a7f-f348-49a7-abd3-c9db3af8c096)

**Comment by TrueBlood1** [comment]
[xinaxu](https://github.com/xinaxu)

![E428](https://github.com/filecoin-project/notary-governance/assets/126061227/5b8d1231-e42c-4d4f-8b00-2ec85ce7b00b)

**Comment by kernelogic** [comment]
I sign hundreds of LDNs this year and you are listing all the notaries that happen to sign with me as my "co-conspirator". Your accusation means absolutely nothing.

**Comment by destor2023** [comment]
These frictions due to unclear rules could have been avoided. I think more notaries would be confused if the definition and rules of "always signing together" were not clear.

The community of FIL+ has never issued a specific constraint that several notaries can't sign together, nor has it issued a bylaw that notaries can't appear in pairs. There is only a basic requirement that the same notary can't sign the same issue two rounds in a row, but can sign a proposal multiple times.

For a rough rule that has no consensus and is ambiguous, why not have a full discussion on the discussion channel before submitting a formal proposal?

Also, we support the idea that 4 and more notaries can sign the same proposal multiple times together. If someone thinks it would be more scientific to raise the 4 to 6 or 8+, we can use the voting tool to decide. Thanks.
