### ISSUE TITLE
Remove inactive notaries

### ISSUE THREAD

**Issue by SPWG1234** [filecoin-project/notary-governance#911]
Why don't we remove the inactive notaries? They are like virus to the program. I think half the problem will be solved if removed

<img width="1440" alt="Screenshot 2023-06-30 at 1 19 27 PM" src="https://github.com/filecoin-project/notary-governance/assets/138135549/e191fd7f-6b6a-453f-b920-d77583aed2b8">

**Comment by i0k24** [comment]
I support this proposal.

**Comment by igoovo** [comment]
Notaries who do not work and do nothing should be severely criticized.
I am fully in favor of disqualifying them as notaries.

**Comment by herrehesse** [comment]
Non signing activities like due diligence should also be considered.

**Comment by spaceT9** [comment]
Signing activities can not be considered the only factor  to remove a notary.  
Some just choose to sign more cautiously, and some are seeking the number of signing applications. They don't have the same metrics.

**Comment by herrehesse** [comment]
Exercising caution does not imply refraining from singing altogether. There exists a distinction between the two approaches. Notaries should never prioritize quantity over quality when it comes to signing. Instead, they should diligently perform their duties and prioritize the safety and well-being of the community.

**Comment by raghavrmadya** [comment]
Appreciate the discussion here. Still think no signing for more than 3 months is not acceptable. The metric flagged above of course only captures two weeks.

**Comment by NDLABS-OFFICE** [comment]
> Appreciate the discussion here. Still think no signing for more than 3 months is not acceptable. The metric flagged above of course only captures two weeks.

@raghavrmadya  Thank you for your prompt follow-up. 

Similar to these regulatory clauses, I hope we can synchronize them in the form of a document within the notary public group. This will enable better adherence to the guidelines by the notary publics. Once again, I want to express my appreciation for your work.

**Comment by herrehesse** [comment]
@raghavrmadya, could you provide metrics on durations longer than two weeks? I propose the following actions:

1. Inquire publicly on the Fil+ slack channel, asking the idle notaries why they have been inactive.
2. Transparently announce the removal of notaries who have been idle for four or more weeks, granting them an additional week to respond.

Remaining with a smaller, dedicated and trustworthy team of notaries would highly benefit this program in my opinion.

**Comment by YuanHeHK** [comment]
> Non signing activities like due diligence should also be considered.

I agree with that statement. The main responsibility of a notary is to audit LDNs, and if the notary is more involved in due diligence and community discussions, the notary can be considered active even if there are fewer signatures.

The core purpose is to do good things for the community, and of course, it would be better to have clearer quantitative indicators and rules to avoid confusion.

**Comment by herrehesse** [comment]
It is more reasonable to have a small amount of active, trusted and experienced notaries. Most idle/new notaries are involved in huge amounts of abuse. This is clearly visible if you take some time to run though the open applications.

Reduce the notary amount, reduce the open applications and focus on signing behaviour. This should be a fruitful combination of getting into the quality phase.

**Comment by liyunzhi-666** [comment]
I propose to add this rule to the notary guidebook. @Kevin-FF-USA 

> Feedback on the timeline that should be used to measure 'Activity' was MONTHLY based on the [11July Governanc](https://youtu.be/hjiu7vHZVZk?t=677)e call.
> 
> Notaries who had **NO DILIGENCE activity within a 30 period** would be flagged for review/possible removal.

**Comment by Kevin-FF-USA** [comment]
Agreed @liyunzhi-666 ,

Great input. We will let @raghavrmadya  and the community within Trust and Transparency review. On next Governance call will discuss the timeline and implementation - after approved - will add to the guidebook.
