### ISSUE TITLE
[DataCap Removal Proposal]

### ISSUE THREAD

**Issue by fabriziogianni7** [filecoin-project/notary-governance#912]
### Client Application URL or Application Number

test

### Client Name

test

### Client Address

f16fibkxu77c4ymtzzsws3kwdcj7ztd7qdn5szpoy

### Amount of DataCap to be removed

200tiB

**Comment by fabriziogianni7** [comment]
test

**Comment by fabriziogianni7** [comment]
test

**Comment by fabriziogianni7** [comment]
# notary approved for datacap removal: 
            
 > **Client Address**: f16fibkxu77c4ymtzzsws3kwdcj7ztd7qdn5szpoy
            
 > **Client Id Address**: f01484077
            
 > **Notary Id Address**: f02058157
            
 > **Signature**: 84c521dbe12a33aac41aa083e0f5c4a422a7ece07b104312c68f0a8b525e04865856146d685f7376c81e5f88c430675056f5a1aefdcbae12b8533cad3e49ce1f01

**Comment by fabriziogianni7** [comment]
# notary approved for datacap removal: 
            
 > **Client Address**: f16fibkxu77c4ymtzzsws3kwdcj7ztd7qdn5szpoy
            
 > **Client Id Address**: f01484077
            
 > **Notary Id Address**: f02058157
            
 > **Signature**: 84c521dbe12a33aac41aa083e0f5c4a422a7ece07b104312c68f0a8b525e04865856146d685f7376c81e5f88c430675056f5a1aefdcbae12b8533cad3e49ce1f01

**Comment by fabriziogianni7** [comment]
# notary approved for datacap removal: 
            
 > **Client Address**: f16fibkxu77c4ymtzzsws3kwdcj7ztd7qdn5szpoy
            
 > **Client Id Address**: f01484077
            
 > **Notary Id Address**: f02058157
            
 > **Signature**: 84c521dbe12a33aac41aa083e0f5c4a422a7ece07b104312c68f0a8b525e04865856146d685f7376c81e5f88c430675056f5a1aefdcbae12b8533cad3e49ce1f01

**Comment by fabriziogianni7** [comment]
# notary approved for datacap removal: 
            
 > **Client Address**: f16fibkxu77c4ymtzzsws3kwdcj7ztd7qdn5szpoy
            
 > **Client Id Address**: f01484077
            
 > **Notary Id Address**: f02058157
            
 > **Signature**: 84c521dbe12a33aac41aa083e0f5c4a422a7ece07b104312c68f0a8b525e04865856146d685f7376c81e5f88c430675056f5a1aefdcbae12b8533cad3e49ce1f01

**Comment by xiangloong** [comment]
# notary approved for datacap removal: 
            
 > **Client Address**: f16fibkxu77c4ymtzzsws3kwdcj7ztd7qdn5szpoy
            
 > **Client Id Address**: f01484077
            
 > **Notary Id Address**: f01845670
            
 > **Signature**: undefined

**Comment by xiangloong** [comment]
# notary approved for datacap removal: 
            
 > **Client Address**: f16fibkxu77c4ymtzzsws3kwdcj7ztd7qdn5szpoy
            
 > **Client Id Address**: f01484077
            
 > **Notary Id Address**: f01845670
            
 > **Signature**: undefined

**Comment by fabriziogianni7** [comment]
@xiangloong which which ledger model and version of ledger are you using ?

**Comment by Chuangshi1** [comment]
# notary approved for datacap removal: 
            
 > **Client Address**: f16fibkxu77c4ymtzzsws3kwdcj7ztd7qdn5szpoy
            
 > **Client Id Address**: f01484077
            
 > **Notary Id Address**: f01813363
            
 > **Signature**: undefined

**Comment by xiangloong** [comment]
# notary approved for datacap removal: 
            
 > **Client Address**: f16fibkxu77c4ymtzzsws3kwdcj7ztd7qdn5szpoy
            
 > **Client Id Address**: f01484077
            
 > **Notary Id Address**: f01845670
            
 > **Signature**: undefined

**Comment by simonkim0515** [comment]
# notary approved for datacap removal: 
            
 > **Client Address**: f16fibkxu77c4ymtzzsws3kwdcj7ztd7qdn5szpoy
            
 > **Client Id Address**: f01484077
            
 > **Notary Id Address**: f01993949
            
 > **Signature**: undefined
