### ISSUE TITLE
[DataCap Removal Proposal] Abusive Behaviour Detected on 1930, 1994, 2005, 1975, 1990, 2035, 1976 and 1989

### ISSUE THREAD

**Issue by herrehesse** [filecoin-project/notary-governance#914]
## Issue Description

Eight instances of abusive and connected clients have been identified involving the following activities:
- Almost fully self-dealing their own applications
- Utilising VPNs to conceal their true location, indicating that miners are not operating from the claimed location. 
- These four separate clients belong to the same entity with funding wallet: f1oamg2yffhxeaoc4gqm4tq6c4qowt3yn666loowa

This situation serves as a prime illustration where the client is also the storage provider, receiving support from negligent notaries who fail to fulfil their responsibilities.

## Impact

This organisation has the capability to accumulate datacap exclusively for its own miners, disregarding regional distribution and engaging in significant self-dealing. Such actions contradict the rules and guidelines of the Filecoin+ program, granting them undue financial advantages over entities striving to operate fair and decentralised storage provider businesses.

## Details

**Clients**
ID | Link | Title | Client | Funding Wallet
-- | -- | -- | -- | --
2035 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2035 | [DataCap Application] <Zhejiang Dahua Technology Co., Ltd> - <Environmental monitoring> | dahuajishu | f1oamg2yffhxeaoc4gqm4tq6c4qowt3yn666loowa
2005 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2005 | [DataCap Application] <Shenzhen Fingertip Culture Media Co., Ltd> - <The art of painting> | zhijianwenhua | f1oamg2yffhxeaoc4gqm4tq6c4qowt3yn666loowa
1994 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1994 | [DataCap Application] <Shenzhen Fingertip Culture Media Co., Ltd> | zhijianwenhua | f1oamg2yffhxeaoc4gqm4tq6c4qowt3yn666loowa
1990 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1990 | [DataCap Application] <Zhejiang Dahua Technology Co., Ltd> - <Architectural design> | dahuajishu | f1oamg2yffhxeaoc4gqm4tq6c4qowt3yn666loowa
1989 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1989 | [DataCap Application] <Shenzhen Xinghongweiye Technology Co., LTD> - <Technological Agriculture> | c12xf | f1oamg2yffhxeaoc4gqm4tq6c4qowt3yn666loowa
1976 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1976 | [DataCap Application] <Shenzhen Xinghongweiye Technology Co., LTD> - <Medical> | c12xf | f1oamg2yffhxeaoc4gqm4tq6c4qowt3yn666loowa
1975 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1975 | [DataCap Application] <Zhejiang Dahua Technology Co., Ltd> - <Smart agriculture> | dahuajishu | f1oamg2yffhxeaoc4gqm4tq6c4qowt3yn666loowa
1930 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1930 | [DataCap Application] <Beijing Bazuo Architectural Design Firm> - <Architectural Design（2/2）> | zhogntao | f1oamg2yffhxeaoc4gqm4tq6c4qowt3yn666loowa

**Storage Providers**

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01927554 | f02129071 | 103.201.24.45 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 12
f01923787 | f02129071 | 14.215.165.42 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 19
f01923786 | f02129071 | 103.201.24.43 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 16
f01938674 | f02129071 | 183.60.90.194 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 19
f01938671 | f02129071 | 103.201.24.42 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 20
f01859603 | f02129071 | 14.18.234.122 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 14

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01836766 | f02191439 | 14.215.165.41 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 8
f01859603 | f02191439 | 14.18.234.122 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 10
f01877184 | f02191439 | 8.219.103.232 | mike | SG , Singapore , Singapore | TRUE with fraudscore 75 | 9
f01923787 | f02191439 | 14.215.165.42 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 13
f01927554 | f02191439 | 103.201.24.45 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 12
f01938674 | f02191439 | 183.60.90.194 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 15
f01923786 | f02191439 | 103.201.24.43 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 14
f01938671 | f02191439 | 103.201.24.42 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 16
f02215422 | f02191439 | 103.201.24.46 | mike-f01938671 | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 3

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01859603 | f02199133 | 14.18.234.122 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 15
f01923786 | f02199133 | 103.201.24.43 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 16
f01923787 | f02199133 | 14.215.165.42 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 16
f01927554 | f02199133 | 103.201.24.45 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 15
f01938671 | f02199133 | 103.201.24.42 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 19
f01938674 | f02199133 | 183.60.90.194 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 18
f0240185 | f02199133 | 159.203.96.29 | topblocks | US , New Jersey , Clifton | TRUE with fraudscore 75 | 0
f02301 | f02199133 | 159.65.189.52 | topblocks | US , New Jersey , Clifton | TRUE with fraudscore 75 | 0
f0143858 | f02199133 | 159.203.96.29 | topblocks | US , New Jersey , Clifton | TRUE with fraudscore 75 | 0
f03223 | f02199133 | 159.65.189.52 | topblocks | US , New Jersey , Clifton | TRUE with fraudscore 75 | 0
f01969779 | f02199133 | 159.89.177.42 |   | US , New Jersey , Clifton | TRUE with fraudscore 87 | 0

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01859603 | f02185204 | 14.18.234.122 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 17
f01923787 | f02185204 | 14.215.165.42 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 23
f01923786 | f02185204 | 103.201.24.43 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 14
f01927554 | f02185204 | 103.201.24.45 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 16
f01938671 | f02185204 | 103.201.24.42 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 13
f01938674 | f02185204 | 183.60.90.194 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 17

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01859603 | f02190848 | 14.18.234.122 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 14
f01923787 | f02190848 | 14.215.165.42 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 15
f01938671 | f02190848 | 103.201.24.42 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 19
f01923786 | f02190848 | 103.201.24.43 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 17
f01927554 | f02190848 | 103.201.24.45 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 16
f01938674 | f02190848 | 183.60.90.194 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 19

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01927554 | f02208908 | 103.201.24.45 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 13
f01923787 | f02208908 | 14.215.165.42 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 16
f01923786 | f02208908 | 103.201.24.43 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 15
f01938674 | f02208908 | 183.60.90.194 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 18
f01859603 | f02208908 | 14.18.234.122 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 19
f01938671 | f02208908 | 103.201.24.42 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 19

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01923787 | f02185203 | 14.215.165.42 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 17
f01859603 | f02185203 | 14.18.234.122 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 15
f01923786 | f02185203 | 103.201.24.43 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 18
f01927554 | f02185203 | 103.201.24.45 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 14
f01938671 | f02185203 | 103.201.24.42 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 17
f01938674 | f02185203 | 183.60.90.194 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 20

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01923787 | f02190348 | 14.215.165.42 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 14
f02062851 | f02190348 | 154.40.35.51 | mike-f01836766 | US , California , Los Angeles | FALSE with fraudscore 0 | 3
f01836766 | f02190348 | 14.215.165.41 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 4
f01859603 | f02190348 | 14.18.234.122 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 14
f01877184 | f02190348 | 8.219.103.232 | mike | SG , Singapore , Singapore | TRUE with fraudscore 75 | 4
f01923786 | f02190348 | 103.201.24.43 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 15
f01927554 | f02190348 | 103.201.24.45 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 14
f01938671 | f02190348 | 103.201.24.42 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 17
f01938674 | f02190348 | 183.60.90.194 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 16
f02215209 | f02190348 | 183.60.90.197 | SWK-f01953985 | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 0

**Notaries**

1bq1024
1DaYouGroup

11ane-1
1maxvint
1psh0691
1SuperChaiChai
1woshidama323
1zcfil

11ane-1
1DaYouGroup
1woshidama323
1zcfil

11ane-1
1ipollo00
1woshidama323
1zcfil

11ane-1
1ipollo00
2Normalnoise
1stcouldlisa
1zcfil

1DaYouGroup
1ipollo00
2Normalnoise
1psh0691
1zcfil

1Aaron01230
1Chuangshi1
1mikezli
1Normalnoise

1igoovo
1Normalnoise

## Proposed Solution(s)

We propose the following actions to address the situation:
- Immediately eliminate the remaining datacap granted on clients.
- Initiate disputes against notaries who have signed inappropriately.
- Immediate removal of repeated offending notaries from the multisig.
- Blacklist the storage providers implicated in the incident.

### Timeline

Discussion at July 11th 2023 WG Call
Community open audit until July 14th 2023 at 5 pm ET
Decision announced async at 5:01 pm ET

**Comment by ipollo00** [comment]
#1976&#1989 They passed KYB. They provided a trustable data sample after I asked more questions.  

#1990 Zhejiangdahua is an extremely famous and huge company in Zhejiang, China. They passed the KYB process by RKH. They have a healthy checker report. No reason that I don't sign for them.

**Comment by Mike-QC6688** [comment]
@herrehesse  I used to only purchase DC quotas from you as an intermediary, which doesn't mean these miners are all mine. Have I not purchased DC quotas from you now and haven't made you any money? Are you talking nonsense here? You're so interesting. If these SPs were all mine, I would laugh in my dreams at night.

**Comment by herrehesse** [comment]
@Mike-QC6688 Thanks for your clarification. Can you share the entities names with us so we can update the names on this issue? Thank you.

**Comment by hsxiaotianquan** [comment]
This is a decentralized network, so why disclose the SP names? What a joke.
Selling DC data is forbidden, hope you can clarify.
@herrehesse

**Comment by herrehesse** [comment]
<img width="184" alt="Screenshot 2023-07-06 at 09 16 50" src="https://github.com/filecoin-project/notary-governance/assets/70132857/6ab5be87-4b64-439b-b9c2-d50e91ccbbd7">

Are you referring to the website supported by Protocol Labs where we previously conducted auctions for our valuable, well-distributed, and properly packaged data? https://www.bigdataexchange.io/

**Comment by sgclouder** [comment]
Agree with @herrehesse they are selling DC 2 FIL/TiB, with  valuable, well-distributed, and properly packaged data.1000TiB DC is on sell,have a look if anyone need it. https://www.bigdataexchange.io/detail/20230627090859

**Comment by herrehesse** [comment]
<img width="723" alt="Screenshot 2023-07-06 at 10 01 24" src="https://github.com/filecoin-project/notary-governance/assets/70132857/ed510d0c-fd53-487d-a40d-e82dab802896">

CB Tan the director or BDE asked me personally last week to add one of our sets to BDE. We haven't posted there in months.

Our sets are also visible on the new Protocol Labs supported website https://openpanda.io/dataset/nih-ncbi-sequence-read-archive-sra-on-aws

Please take a look if you want to see datasets that add value to our whole ecosystem.

**Comment by sgclouder** [comment]
Ok.Thanks for you reply.I know what happen.

**Comment by dahuajishu** [comment]
@herrehesse May I ask if there is any problem? I am completely unfamiliar with other related LDNs.The amount of my wallets was extracted from a domestic exchange.

**Comment by dahuajishu** [comment]
Are there any issues with different LDNs contacting the same storage provider?

**Comment by herrehesse** [comment]
@dahuajishu After examining most exchanges, we have found no evidence to support your statement. Additionally, even if it were a generic exchange wallet, it would still trace back to the same owner.

There is no problem with multiple LDNs utilising the same storage provider unless suspicious patterns emerge, indicating collusion, self-dealing, or improper distribution, and unretrievable deals.

**Comment by dahuajishu** [comment]
May I ask if you have any knowledge of our company?

**Comment by herrehesse** [comment]
May I ask your proper and in-depth response to the various points we have made against the LDN's so far? I do not see knowledge of your company changing any blockchain based facts.

**Comment by dahuajishu** [comment]
Some of the bad behaviors you mentioned have no benefits for our company, and we do not engage in abusive behavior. Currently, our company is still in contact with SPs in other regions, and we have just started.

**Comment by herrehesse** [comment]
I kindly request the removal of this client and the remaining datacap. Despite several accusations, no evidence has been provided against it. There has been no progress, so I urge you to take appropriate action.

I also recommend initiating a dispute or removal process for the notaries involved, as it appears that a significant portion of them are recurring abusers (see open issues).

**Comment by raghavrmadya** [comment]
Seeing no critical evidence provided by the client in response to the abuse allegations, the T&T WG lead recommends the removal of DC for the above LDNs based on the evolving discussion. Requesting @simonkim0515 to alert RKH to take action. 

Clients are welcome to apply for LDN again and regain community trust
