### ISSUE TITLE
[DataCap Removal Proposal] Abusive Behaviour Detected on 1914, 1913, 1912, 1413, 1412, 1408 and 1404

### ISSUE THREAD

**Issue by herrehesse** [filecoin-project/notary-governance#915]
## Issue Description

Seven instances of abusive and connected clients have been identified involving the following activities:
- Almost fully self-dealing their own applications
- Utilising VPNs to conceal their true location, indicating that miners are not operating from the claimed location. 
- These four separate clients belong to the same entity with funding wallet: f1bxji6gvmvnzvoznvmojasufrrkg4gyyzzfyud4q

This situation serves as a prime illustration where the client is also the storage provider, receiving support from negligent notaries who fail to fulfil their responsibilities.

## Impact

This organisation has the capability to accumulate datacap exclusively for its own miners, disregarding regional distribution and engaging in significant self-dealing. Such actions contradict the rules and guidelines of the Filecoin+ program, granting them undue financial advantages over entities striving to operate fair and decentralised storage provider businesses.

## Details

**Clients**

ID | Link | Title | Client | Funding Wallet
-- | -- | -- | -- | --
1914 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1914 | [DataCap Application] <Little Angel Dance Education> - <Little Angel Dance Education(3/3) | fildance | f1bxji6gvmvnzvoznvmojasufrrkg4gyyzzfyud4q
1913 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1913 | [DataCap Application] <Little Angel Dance Education> - <Little Angel Dance Education(2/3) | fildance | f1bxji6gvmvnzvoznvmojasufrrkg4gyyzzfyud4q
1912 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1912 | [DataCap Application] <Little Angel Dance Education> - <Little Angel Dance Education(1/3)> | fildance | f1bxji6gvmvnzvoznvmojasufrrkg4gyyzzfyud4q
1413 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1413 | [DataCap Application] <Red bayberry> - <Painting/video teaching(3/3)> | Fil-ZC | f1bxji6gvmvnzvoznvmojasufrrkg4gyyzzfyud4q
1412 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1412 | [DataCap Application] <Red bayberry> - <Painting/video teaching(2/3)> | Fil-ZC | f1bxji6gvmvnzvoznvmojasufrrkg4gyyzzfyud4q
1408 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1408 | [DataCap Application] Shenzhen Star Dance Zhuo Meng Art Education - Star Dance Zhuo Meng Art Education  - [1/3] | arsbuli | f1bxji6gvmvnzvoznvmojasufrrkg4gyyzzfyud4q
1404 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1404 | Hangzhou Seoul Education Training Co., Ltd - Du immortality[1/3] | ZC-FILSZ | f1bxji6gvmvnzvoznvmojasufrrkg4gyyzzfyud4q

**Storage Providers**

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01923787 | f02126811 | 14.215.165.42 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 14
f01938674 | f02126811 | 183.60.90.194 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 18
f01859603 | f02126811 | 14.18.234.122 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 13
f01927554 | f02126811 | 103.201.24.45 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 15
f01923786 | f02126811 | 103.201.24.43 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 16
f02215422 | f02126811 | 103.201.24.46 | mike-f01938671 | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 5
f01836766 | f02126811 | 14.215.165.41 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 2
f01938671 | f02126811 | 103.201.24.42 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 8
f01877184 | f02126811 | 8.219.103.232 | mike | SG , Singapore , Singapore | TRUE with fraudscore 75 | 8

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01927554 | f02126809 | 103.201.24.45 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 15
f01923787 | f02126809 | 14.215.165.42 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 15
f01923786 | f02126809 | 103.201.24.43 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 16
f01938671 | f02126809 | 103.201.24.42 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 18
f01938674 | f02126809 | 183.60.90.194 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 17
f01859603 | f02126809 | 14.18.234.122 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 7
f02215209 | f02126809 | 183.60.90.197 | SWK-f01953985 | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 0
f02215422 | f02126809 | 103.201.24.46 | mike-f01938671 | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 11

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01859603 | f02126804 | 14.18.234.122 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 16
f01923786 | f02126804 | 103.201.24.43 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 15
f01923787 | f02126804 | 14.215.165.42 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 13
f01927554 | f02126804 | 103.201.24.45 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 13
f01938671 | f02126804 | 103.201.24.42 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 17
f01938674 | f02126804 | 183.60.90.194 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 16
f01836766 | f02126804 | 14.215.165.41 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 6
f01877184 | f02126804 | 8.219.103.232 | mike | SG , Singapore , Singapore | TRUE with fraudscore 75 | 3
f02215422 | f02126804 | 103.201.24.46 | mike-f01938671 | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 1

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01128206 | f01984875 | 103.201.24.44 | mike-f01938671 | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 2
f01836766 | f01984875 | 14.215.165.41 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 2
f01859603 | f01984875 | 14.18.234.122 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 14
f01923786 | f01984875 | 103.201.24.43 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 15
f01923787 | f01984875 | 14.215.165.42 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 14
f01927554 | f01984875 | 103.201.24.45 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 15
f01938671 | f01984875 | 103.201.24.42 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 15
f01938674 | f01984875 | 183.60.90.194 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 15
f02062851 | f01984875 | 154.40.35.51 | mike-f01836766 | US , California , Los Angeles | FALSE with fraudscore 0 | 6
f01877184 | f01984875 | 8.219.103.232 | mike | SG , Singapore , Singapore | TRUE with fraudscore 75 | 1
f0872282 | f01984875 | 103.201.24.105 | mike-f01938671 | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 0
f02215422 | f01984875 | 103.201.24.46 | mike-f01938671 | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 2

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01836766 | f01984874 | 14.215.165.41 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 1
f01128206 | f01984874 | 103.201.24.44 | mike-f01938671 | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 4
f01859603 | f01984874 | 14.18.234.122 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 15
f01877184 | f01984874 | 8.219.103.232 | mike | SG , Singapore , Singapore | TRUE with fraudscore 75 | 1
f01923786 | f01984874 | 103.201.24.43 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 15
f01923787 | f01984874 | 14.215.165.42 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 16
f01927554 | f01984874 | 103.201.24.45 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 14
f01938671 | f01984874 | 103.201.24.42 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 15
f01938674 | f01984874 | 183.60.90.194 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 16
f02062851 | f01984874 | 154.40.35.51 | mike-f01836766 | US , California , Los Angeles | FALSE with fraudscore 0 | 4
f0872282 | f01984874 | 103.201.24.105 | mike-f01938671 | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 0

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01128206 | f01984836 | 103.201.24.44 | mike-f01938671 | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 3
f01859603 | f01984836 | 14.18.234.122 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 13
f01877184 | f01984836 | 8.219.103.232 | mike | SG , Singapore , Singapore | TRUE with fraudscore 75 | 2
f01923786 | f01984836 | 103.201.24.43 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 15
f01923787 | f01984836 | 14.215.165.42 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 14
f01927554 | f01984836 | 103.201.24.45 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 15
f01938671 | f01984836 | 103.201.24.42 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 14
f01938674 | f01984836 | 183.60.90.194 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 16
f02062851 | f01984836 | 154.40.35.51 | mike-f01836766 | US , California , Los Angeles | FALSE with fraudscore 0 | 5
f01836766 | f01984836 | 14.215.165.41 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 2

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01859603 | f01984832 | 14.18.234.122 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 16
f01923786 | f01984832 | 103.201.24.43 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 17
f01923787 | f01984832 | 14.215.165.42 | mike | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 15
f01927554 | f01984832 | 103.201.24.45 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 16
f01938671 | f01984832 | 103.201.24.42 | mike | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 17
f01938674 | f01984832 | 183.60.90.194 | mike | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 19

**Notaries**

Chuangshi1
Normalnoise

Chuangshi1
DaYouGroup
Normalnoise

Aaron01230
DaYouGroup
igoovo
Normalnoise
psh0691
zcfil

Bitrise0111
DaYouGroup
ipollo00
Normalnoise
stcouldlisa
sxxfuture-official
woshidama323
zcfil

bq1024
DaYouGroup
newwebgroup
nj-steve
Normalnoise
stcouldlisa
zcfil

Aaron01230
Bitrise0111
bq1024
cryptowhizzard
DaYouGroup
igoovo
mikezli
newwebgroup
Normalnoise
zcfil

1ane-1
DaYouGroup
igoovo
newwebgroup
Normalnoise
SuperChaiChai
zcfil

## Proposed Solution(s)

We propose the following actions to address the situation:
- Immediately eliminate the remaining datacap granted on clients.
- Initiate disputes against notaries who have signed inappropriately.
- Immediate removal of repeated offending notaries from the multisig.
- Blacklist the storage providers implicated in the incident.

### Timeline

Discussion at July 11th 2023 WG Call
Community open audit until July 14th 2023 at 5 pm ET
Decision announced async at 5:01 pm ET

**Comment by Mike-QC6688** [comment]
I have left this circle. Stop talking nonsense. You have caused me a lot of trouble, and it seems that no one has purchased DC from you,You are now biting people indiscriminately.

**Comment by herrehesse** [comment]
@Mike-QC6688, You have the freedom to think and express your opinions. However, the information presented above is based on factual data, which speaks for itself.

**Comment by herrehesse** [comment]
I kindly request the removal of this client and the remaining datacap. Despite several accusations, no evidence has been provided against it. There has been no progress, so I urge you to take appropriate action.

I also recommend initiating a dispute or removal process for the notaries involved, as it appears that a significant portion of them are recurring abusers (see open issues).

**Comment by raghavrmadya** [comment]
Seeing no critical evidence provided by the client in response to the abuse allegations, the T&T WG lead recommends the removal of DC for the above LDNs based on the evolving discussion. Requesting @simonkim0515 to alert RKH to take action.

Clients are welcome to apply for LDN again and regain community trust
