### ISSUE TITLE
[DataCap Removal Proposal] Abusive Behaviour Detected on 1910 and 1251 NFT Printer Dataset

### ISSUE THREAD

**Issue by herrehesse** [filecoin-project/notary-governance#916]
## Issue Description

One instance of connected SP's have been identified involving funding relationships between all SP's.

## Impact

This organisation has accumulated datacap exclusively for its own miners, disregarding regional distribution and engaging in significant self-dealing. Such actions contradict the rules and guidelines of the Filecoin+ program, granting them undue financial advantages over entities striving to operate fair and decentralised storage provider businesses.

## Details

Based on the provided data, let's analyze the wallets and their funding relationships to identify the correlation:

- f01915133 is funded from f15kiswlfelqkl6ri4aiyf7ke5nebckdn5iaw4nzi.
- f020522 is funded from f16syz46negcfljuysbonexvms762iyxkn6po65di.
- f03325 is funded from f15kiswlfelqkl6ri4aiyf7ke5nebckdn5iaw4nzi.
- f07786 is funded from f15kiswlfelqkl6ri4aiyf7ke5nebckdn5iaw4nzi.
- f07830 is funded from f16syz46negcfljuysbonexvms762iyxkn6po65di.

From the given information, we can see that f01915133 and f03325 are both funded from f15kiswlfelqkl6ri4aiyf7ke5nebckdn5iaw4nzi. Similarly, f07786, f07830, and f020522 are funded from f15kiswlfelqkl6ri4aiyf7ke5nebckdn5iaw4nzi and f16syz46negcfljuysbonexvms762iyxkn6po65di.

Further investigation reveals that f15kiswlfelqkl6ri4aiyf7ke5nebckdn5iaw4nzi is funded from f1fwmhkm72chblzx27t3n4uqxjqdmsl6deri3mqri, and f1fwmhkm72chblzx27t3n4uqxjqdmsl6deri3mqri is funded by f1en4uflr25qkv76bnjhtf2hhxjb5dmwncc65gn5y.

Lastly, there are transactions between f1en4uflr25qkv76bnjhtf2hhxjb5dmwncc65gn5y and f16syz46negcfljuysbonexvms762iyxkn6po65di, which can be verified at the provided [link](https://filfox.info/en/message/bafy2bzaceapfapfopafjczmwpud2yjzermrop5oimessanrcencehfrwrtli4). 

Based on this information, we can conclude that there is a funding correlation between the wallets, suggesting they are most likely associated with the same entity or involved in self-dealing activities.

**Clients**
ID | Link | Title | Client | Funding Wallet
-- | -- | -- | -- | --
1251 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1251 | [NFT Printer Dataset  | CourteousBin | f1qwhdzl4c5mredljdi22npsqd4aoh4b5ehqacdfa
1910 |https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1910 | [NFT Printer Dataset  | CourteousBin | f1c2unlsfmqzgff3q25xep73nrfxygtujzeubbqqq

**Storage Providers**

Storage Provider | Client | IP Address | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | --
f01915133 | f02168993 | 122.10.123.251 | HK , Hong Kong , Hong Kong | TRUE with fraudscore 75 | 19
f020522 | f02168993 | 43.131.60.52 | DE , Hesse , Frankfurt am Main | TRUE with fraudscore 75 | 21
f03325 | f02168993 | 108.61.161.23 | JP , Tokyo , Tokyo | TRUE with fraudscore 75 | 19
f07786 | f02168993 | 139.162.52.239 | SG , Singapore , Singapore | TRUE with fraudscore 75 | 20
f07830 | f02168993 | 43.135.156.183 | US , California , Santa Clara | TRUE with fraudscore 95 | 21

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f01915133 | f01986859 | 122.10.123.251 |   | HK , Hong Kong , Hong Kong | TRUE with fraudscore 75 | 19
f01915135 | f01986859 | 152.104.9.169 |   | HK , Hong Kong , Hong Kong | TRUE with fraudscore 75 | 2
f01915188 | f01986859 | 14.29.108.235 |   | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 3
f020522 | f01986859 | 43.131.60.52 |   | DE , Hesse , Frankfurt am Main | TRUE with fraudscore 75 | 19
f03325 | f01986859 | 108.61.161.23 |   | JP , Tokyo , Tokyo | TRUE with fraudscore 75 | 18
f07786 | f01986859 | 139.162.52.239 |   | SG , Singapore , Singapore | TRUE with fraudscore 75 | 18
f07830 | f01986859 | 43.135.156.183 |   | US , California , Santa Clara | TRUE with fraudscore 95 | 20
f0240185 | f01986859 | 159.203.96.29 | topblocks | US , New Jersey , Clifton | TRUE with fraudscore 75 | 0
f03223 | f01986859 | 159.65.189.52 | topblocks | US , New Jersey , Clifton | TRUE with fraudscore 75 | 0

**Notaries**

1Bitrise0111
1destor2023
1Fatman13
1jomozz
1Joss-Hua
1kernelogic
3laurarenpanda
1maxvint
1YuanHeHK
1zcfil

11ane-1
1cryptowhizzard
1kernelogic
2NDLABS-OFFICE
1newwebgroup
1psh0691
1Tom-OriginStorage
1xinaxu

## Proposed Solution(s)

We propose the following actions to address the situation:
- Immediately eliminate the remaining datacap granted on clients.
- Initiate disputes against notaries who have signed inappropriately.
- Immediate removal of repeated offending notaries from the multisig.
- Blacklist the storage providers implicated in the incident.

### Timeline

Discussion at July 11th 2023 WG Call
Community open audit until July 14th 2023 at 5 pm ET
Decision announced async at 5:01 pm ET

## Additional

Same behaviour and SP's: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1907

**Comment by cryptowhizzard** [comment]
Adding [Issue 1907 to this list](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1907)

**Comment by herrehesse** [comment]
I kindly request the removal of this client and the remaining datacap. Despite several accusations, no evidence has been provided against it. There has been no progress, so I urge you to take appropriate action.

I also recommend initiating a dispute or removal process for the notaries involved, as it appears that some of them are recurring abusers (see open issues).

**Comment by raghavrmadya** [comment]
Seeing no response to the abuse allegations, the T&T WG lead recommends the removal of DC for the above LDNs based on the evolving discussion. Requesting @simonkim0515 to alert RKH to take action.

Clients are welcome to apply for LDN again and regain community trust

**Comment by heroapn** [comment]
What are you doing?Do not remove my DC! @raghavrmadya  I have sufficient reasons and evidence to oppose the false accusations against me!
