### ISSUE TITLE
[DataCap Removal Proposal]  #2050 - Merged Set of "Open data"  - Improper Due Diligence by Notaries

### ISSUE THREAD

**Issue by herrehesse** [filecoin-project/notary-governance#921]
### Client Application URL or Application Number

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2050

### Client Name

datalove2 

### Client Address

f1tp3kxwlvxd3ggjsfcbivr25fzz2edrrrqe5vapy

### Amount of DataCap to be removed

1PiB

**Comment by herrehesse** [comment]
@luobin544 and @newwebgroup have been recommended for the removal of their notary status. Notary @luobin544 showed a lack of due diligence by signing the application without any due diligence, simply relying on the statement "Check project status is good, supported." Notary @newwebgroup attempted to perform due diligence but still promptly signed the application, which is not proper due diligence at all. It's important to note that signing off on a 1PiB trench is a significant decision.

Furthermore, there are concerns regarding the distribution process, as it appears that all distribution is occurring in a single region, or it could potentially be fake distribution using a VPN.

Additionally, this application involves a merged dataset request, which the community has decided is no longer allowed. Despite being aware of this decision, the notaries still proceeded to sign the application. For reference, please see the following link: https://github.com/filecoin-project/notary-governance/issues/832

[@raghavrmadya and @dkkapur](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2050#issuecomment-1625179114)

**Comment by herrehesse** [comment]
sp | client | ipadres | port | subnet | location | vpnresults | percent
-- | -- | -- | -- | -- | -- | -- | --
f02148382 | f02227756 | 223.111.148.197 | 23450 | 223.111.148 | CN , Jiangsu , Yancheng | TRUE with fraudscore 70 | 11
f02226892 | f02227756 | 183.60.189.225 | 24001 | 183.60.189 | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 2
f02194766 | f02227756 | 101.206.185.216 | 41001 | 101.206.185 | CN , Sichuan , Chengdu | FALSE with fraudscore 0 | 22
f02212669 | f02227756 | 115.231.235.242 | 23459 | 115.231.235 | CN , Zhejiang , Jiaxing | TRUE with fraudscore 70 | 11
f01740934 | f02227756 | 128.14.72.189 | 23456 | 128.14.72 | US , California , Los Angeles | TRUE with fraudscore 75 | 13
f01854772 | f02227756 | 128.1.112.6 | 23450 | 128.1.112 | US , New Jersey , Red Bank | TRUE with fraudscore 75 | 3
f01834291 | f02227756 | 65.255.36.78 | 23450 | 65.255.36 | US , California , Los Angeles | TRUE with fraudscore 75 | 10
f01834253 | f02227756 | 23.236.115.78 | 23450 | 23.236.115 | US , California , Los Angeles | TRUE with fraudscore 75 | 10
f01853077 | f02227756 |   |   |   |   |   | 2
f02201020 | f02227756 |   |   |   |   |   | 3
f02192496 | f02227756 |   |   |   |   |   | 5
f02185816 | f02227756 |   |   |   |   |   | 1
f02224274 | f02227756 |   |   |   |   |   | 6

**Comment by datalove2** [comment]
1. Those sp I am cooperating with are NOT using VPN, and the whole process follows the rules. In the case of fully complying with the rules, is it necessary for the notary to ask some unnecessary questions? Just to bother clients? 
2. There are no restrictions on clients applying dc using aws data. In the proposal you mentioned, there are no consensus has been reached. An unresolved proposal CANNOT be the reason to remove everyone's effort. 
3. Your allegations against these notaries make me uncomfortable even though I am not a notary. They reviewed it for us and made suggestions for our application form. What they're doing is making things go more smoothly, How about you? If you feel that the data I applied for does not meet the "requirements", then I should be rejected at the "Datacap Request" stage. Instead of accusing the notary who works for us here. I actually asked a lot of people through Slack, but very few people were willing to help. What do you think about it?

**Comment by herrehesse** [comment]
1. That could be accurate since the VPN bot is merely suggesting based on an IP database that assesses past behaviours and rates IPs accordingly. However, it's important to note that even if the suggestions may never be 100% accurate it is an valuable metric to add into account when researching Notary>Client>SP behaviour.
2. Yes, there are restrictions on merging open datasets, as mentioned in this link: https://github.com/filecoin-project/notary-governance/issues/832. The purpose of merging datasets is primarily to increase datacap for the client and does not offer any significant value to Filecoin since there is no client requesting such a merge. It also increases the inability to track public open datasets properly.
3. Your personal feelings are valid, and you are entitled to feel however you wish. However, I am primarily highlighting behaviours and rules within the Filecoin+ community and pointing out instances where things deviate from those rules.

When you state "the notary works for us here," what exactly do you mean? Notaries are not permitted to work for any specific entity or individual; rather, they serve as the exclusive guardians of the Filecoin Plus program and the value it brings to the Filecoin network through real customers and data.

If there is a lack of willingness from notaries to assist, it could be due to unfortunate circumstances or because your application fails to meet the requirements for notaries to sign, lacks additional value, or any other reasons that notaries may consider.

I have made my points clear, and I am awaiting the community call to discuss them further.

**Comment by herrehesse** [comment]
Try it: https://www.ipqualityscore.com/vpn-ip-address-check

**Comment by herrehesse** [comment]
@0xXPunkX Thank you for showing me again that all SP's are in china, committing abuse for storing all in the same region/dc.

**Comment by raghavrmadya** [comment]
This issue is being closed as the client has responded to the allegations. VPN use alone is not a sign of abuse.
