### ISSUE TITLE
Initiation of FIL+ Application Low-Permission Process

### ISSUE THREAD

**Issue by Chris00618** [filecoin-project/notary-governance#928]
## Issue Description
All centralized platforms or projects have monopoly possibilities, and Fil+ is no exception. Growing abusive behavior is at the root of the current controversy in the community. Most of LDN applications are relocating aws public data to filecoin, no users would make downloads of AWS datasets on Filecoin. It doesn't create a demand for retrieval but only causes so much controversy in the community, which keeps piling up and remains unresolved.
1. In Q1 this year, triggers were released almost unconditionally for all applications. As of today, a total of 4,600+ PiB of datacap were handed out trigger, which would bring an incremental QAP of 46EiB if all of them were used.    
2. For historical reasons, communities have not been able to restrict SPs from serving as notaries public, which is the second major reason why abuses are bound to occur.        
3. FIL+ helps SPs gradually start storing real deal data by incentivizing layer, even though the value of the data cannot be defined whatsoever. It was just an experiment, yet it was scaled up to become mainstream across the network. Constantly raising the application limit for single LDNs is the third reason why abusive behavior has gotten out of hand.

## Impact
1. Encourage more new members, new SPs to join the datacap experience program. 
2. Discourage older community accounts and notaries to repeatedly serve as DPs crowding out opportunities for new members. 
3. Let FIL+ gradually begin to enter the era of decentralization with a low trust threshold, low manual intervention, and low community friction.

## Proposed Solution(s)
1. Change the rules for giving out triggers to a maximum of 5 applications per day.
2. Adjust all application limits to 1.5PiB ( by three allocations of 500TiB each time).
4. Freeze period on Github account to reduce the possibility of fraud. Only accounts that have been registered for more than 2 months and have more than 10 records of interactions are allowed to apply for LDN, with each account applying for a maximum of 5 times.
5. No KYC for applicants, no review of SP, no requirement for retrieval, no inquiry into historical records, only the number of allocated nodes shall not be less than 8.
6. Notaries are still allowed to act as SPs. They only need to sign off on the report after doing a simple check of the number of nodes assigned.
7. Consolidate the E-fil program into LDN without special quota authority. 
8. Close Trust&Transparency channel.

### Timeline
Proposal to be reviewed on upcoming Governance Call
Updated proposal process flow to be implemented after review and approval for all new applicants

### Technical dependencies 
Changes to LDN application template
Authorization from Filecoin Slack team

**Comment by Aaronn85** [comment]
Now getting 32GiB  per git-account per time automatically is indeed not quite enough. Also no one can guarantee the compliance of  triggers over 20~50 PiB everyday. We support the amount of trigger max to 1.5P*5/day with no KYC and simplest review. 

FIL+ is merely a promotional program and should never be used as a universal model for constant scaling, and it must be full of sticky to keep catching bugs with an incredibly complex review mechanism. All of us here wouldn't stand this trend.

Without reform, fil+ must end up a mess.

**Comment by Jaida0** [comment]
Curious that if DPs/Clients applied for more DataCap than the limit, what should they do then?

**Comment by Chris00618** [comment]
> Curious that if DPs/Clients applied for more DataCap than the limit, what should they do then?

Good question. FIL+ has always emphasized the distributivity of the nodes, but has never focused on the distributivity of the applicants. This is the source of the gradual loss of community governance.

If we take a closer look at the statistics, the current application quota is very centrally monopolized by some so-called highly trusted and star members, how can we expect these highly concentrated applications to be actually used for a wide range of SP nodes?

So, before T&T team still struggles to guess whether different accounts are controlled by the same entity behind them, shouldn't we first manage the problem of excessive datacap applications for the same accounts, because the same accounts must be controlled by the same entity.

Finally to answer your question, I'd encourage entities that wish to overdose on datacap to be able to PURCHASE datacap quotas from dedicated way. Yes, just like carbon credits.

If a wider range of accounts had access to datacap within a certain quota, we'd be completely 90% decentralized and all of the kyc and reviews would be unnecessary. And clients who are willing to pay for DC quotas are the real seed users for the future commercialization of filecoin.

Thanks for more input!

**Comment by marksunyaoyao** [comment]
Permissionless is the right way forward.  FIL+ is just an experiment.
There's a program called fil- on slack. Have you guys heard of it?

**Comment by kenzz45** [comment]
It could be tried and possibly an innovative approach. There's been so much controversy in the community lately that too much people in the community propose to kill fil+.

**Comment by The-Wayvy** [comment]
Juan keeps saying that storage would be too expensive without this tax on the permissionless part of the network. 

No one knows what kind of storage services will be built on top of Filecoin in the next 5 years and how much clients will be willing to pay for these.

It is just another excuse to keep FIL+ alive and save face.
