### ISSUE TITLE
REMOVAL: mikezli signed 2PiB while application 2050 is under dispute

### ISSUE THREAD

**Issue by herrehesse** [filecoin-project/notary-governance#929]
## Issue Description
Notary [mikezli](https://github.com/mikezli) has signed application https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2050 while being under dispute.

## Proposed Solution(s)
Removal of notary from the multisig immediately.

**Comment by Yvette516** [comment]
Kernelogic signed the same round, any reason why he is not on the list?
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2050#issuecomment-1637532090

**Comment by herrehesse** [comment]
Good question, same for @Kernelogic

**Comment by kernelogic** [comment]
See my comment https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2050#issuecomment-1637190299

It is NOT on the tracker when I signed. I believe it does not count as a violation. @raghavrmadya

**Comment by herrehesse** [comment]
@kernelogic Valid point, I will make sure all disputes are clearly visible on the tracker next time.

**Comment by datalove2** [comment]
The allegations against our LDN are related to dataset merging and the use of VPN. Prior to this, RG has publicly stated that signing for applied and completed public datasets is permitted, and the VPN accusation has been explained as well. Moreover, our reports are all compliant, and notary nodes sign in a reasonable and compliant manner. Can such an accusation to remove notary nodes be made so casually?
