### ISSUE TITLE
Notary Governance Meeting - Feb 16th 11pm UTC

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/notary-governance#93]
Hi all, 

Per our calendar change a few weeks back - we have another Governance call slated for Feb 16th at 11pm UTC. 

Per usual, we'll be discussing open issues / PRs and any other agenda items flagged below. Please add items to the Github comments to add to the agenda. 

Zoom details: 
https://protocol.zoom.us/j/93414028246
Passcode: 554538

**Comment by jnthnvctr** [comment]
Per the slack thread(s) it seems we should discuss: 

1) What rules do clients have for allocating DataCap / making deals with Miners? 
2) Identifying slowness in DataCap allocations
3) Notary operational rules (i.e. what are appropriate punishments for various scales of bad actions, and defining some of those bad actions)

**Comment by NSC-FIL** [comment]
For anyone interested, relevant discussions can be found here:
https://github.com/filecoin-project/notary-governance/issues/76
https://github.com/filecoin-project/notary-governance/issues/66

**Comment by NSC-FIL** [comment]
Before the meeting, could someone send a query out to Notaries or Clients that have not distributed their DataCap and find out why they are not using it?

**Comment by NSC-FIL** [comment]
And does PL have the tools to do a simulation on how the Filecoin network would evolve if say the top 20 miners were to pay (start offering negative --verified prices)  an incrementally increasing amount to get verified deals (10x power growth)?  How would the power consolidate or distribute including potential block wins?  How would this affect the smaller (> 10TiB raw power) miners if they do or don't do offer the same deals?  Very curious how this scenario would play out.
