### ISSUE TITLE
[NOTARY REMOVAL] Abusive Behaviour Detected on 1068 from cryptowhizzard's signature

### ISSUE THREAD

**Issue by CorruptedPixels** [filecoin-project/notary-governance#930]
## Issue Description
**All of the distributed data is concentrated in the same region, the same SP.** Notary related to interests has knowingly signed off on the application, allowing the storage provider to utilise this data cap in violation of the Filecoin+ program rules. 
## Impact
More notaries improperly follow cryptowhizzard's behavior, leading to increasing abuse in the community
## Proposed Solution(s)
Immediate removal of repeated offending notary---cryptowhizzard
### Timeline
To be reviewed on upcoming T&T Call
## Related Issues
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1068

**Comment by herrehesse** [comment]
The individual responsible for this account is Patrick Deuse (Factor8). It is highly probable that he will attempt to make a statement here, but his efforts are unlikely to succeed. The application in question originates from Greater Heat and has faced numerous disputes, including ones raised by our own team. If you take the time to thoroughly examine the actual application, you would have already come across this information.

In the interest of the community, we kindly request @beck and @cryptowhizzard to provide a clarification on the matter at hand.

**Comment by cryptowhizzard** [comment]
Personal note:
🇨🇳-> it is *very* uncool to impersonate someone else. I am not entirely familiar with the way things work over there but taking over someone’s account without his permission is a violation of human rights on the part of the globe where i live. 

Professional note:
GreaterHeat did KYC with us, we have done dinner with them, we have made agreements with them. See my personal note: -> sometimes things don’t work out the way they are supposed to on your side of the globe. That’s what happens when people with no clue and state controlled start meddling in someone’s business. 

Ps… Patrick is still welcome to join the T&T 📞 to talk about community and outstanding issues.

**Comment by CorruptedPixels** [comment]
@cryptowhizzard @herrehesse 

I don't know the person you mentioned above. There's no similar github account in the community either. No one else will mistake me as that friend of yours.

Also, it's my right to name any ID, which obviously doesn't break any rules of community. There's no need to pretend to be anyone else. 

I have not found any valid Due Diligence or any penitential explanation from you before you signed this application which had obvious abuse. So I propose removing you from the multisig of notaries.

Do not think that you can avoid charges by attacking any identity.

**Comment by woshidama323** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1551

![image](https://github.com/filecoin-project/notary-governance/assets/11014169/92bdf584-16d5-4463-8637-4a3194848c88)


@cryptowhizzard why does your application has so large duplicate issue

**Comment by cryptowhizzard** [comment]
> [filecoin-project/filecoin-plus-large-datasets#1551](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1551)
> 
> ![image](https://user-images.githubusercontent.com/11014169/253878971-92bdf584-16d5-4463-8637-4a3194848c88.png)
> 
> @cryptowhizzard why does your application has so large duplicate issue and sharing with **4 PiB** ?

https://github.com/tech-greedy/singularity/issues/172

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard @herrehesse
> 
> I don't know the person you mentioned above. There's no similar github account in the community either. No one else will mistake me as that friend of yours.
> 
> Also, it's my right to name any ID, which obviously doesn't break any rules of community. There's no need to pretend to be anyone else.
> 
> I have not found any valid Due Diligence or any penitential explanation from you before you signed this application which had obvious abuse. So I propose removing you from the multisig of notaries.
> 
> Do not think that you can avoid charges by attacking any identity.

If you think that I will bring someone in trouble snitching to build your case against him over there then you are wrong. 

Give my regards to Patrick.

**Comment by cryptowhizzard** [comment]
> > Professional note: GreaterHeat did KYC with us, we have done dinner with them, we have made agreements with them. See my personal note: -> sometimes things don’t work out the way they are supposed to on your side of the globe. That’s what happens when people with no clue and state controlled start meddling in someone’s business.
> 
> From Dcent's history of statements, they believe that almost all Chinese notaries have failed in their kyc and due diligence responsibilities with no proof, no rule explained. We had dinner with them and we reached an agreement with them should not be the reason for a notary to give signatures. Plus, this application relates to multiple disputes, it's hard to be convinced that their kyc was reasonable. The governance team should look into this and keep the community updated.

What do you mean with “it is hard to understand their kyc was reasonable” . KYC stands for know your customer. We know them? The disputes were after my signature.

**Comment by Yvette516** [comment]
I mean kyc and due diligence. You had no idea if beck was applying #1068 on behalf of GreaterHeat or on his own, didn't you?

**Comment by HiFil** [comment]
@cryptowhizzard  Stop lying immediately, your signing took place in round 5, before that the report had already manifested a great deal of abusive behavior. I don't know the details of your cooperative agreement with the applicants, but in any case, that doesn't excuse your involvement in abusive behavior.

Support the removal of @cryptowhizzard  from the multisig!

**Comment by herrehesse** [comment]
@HiFil Stop gaslighting.

**Comment by cryptowhizzard** [comment]
> I mean kyc and due diligence. You had no idea if beck was applying #1068 on behalf of GreaterHeat or on his own, didn't you?

Does that matter? To my understanding he was / is working for GreaterHeat.

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard Stop lying immediately, your signing took place in round 5, before that the report had already manifested a great deal of abusive behavior. I don't know the details of your cooperative agreement with the applicants, but in any case, that doesn't excuse your involvement in abusive behavior.
> 
> Support the removal of @cryptowhizzard from the multisig!

To what ends? It won't get your LDN going with your inflated mp4's, secondly it won't stop me of doing due diligence on LDN's. It would only save me time........... much of it. Thirdly i did nothing wrong.

**Comment by beck** [comment]
@herrehesse can you please update your comment to mention @beck-8 (not me)

**Comment by herrehesse** [comment]
Done!

**Comment by HiFil** [comment]
> > Professional note: GreaterHeat did KYC with us, we have done dinner with them, we have made agreements with them. See my personal note: -> sometimes things don’t work out the way they are supposed to on your side of the globe. That’s what happens when people with no clue and state controlled start meddling in someone’s business.
> 
> From Dcent's history of statements, they believe that almost all Chinese notaries have failed in their kyc and due diligence responsibilities with no proof, no rule explained. We had dinner with them and we reached an agreement with them should not be the reason for a notary to give signatures. Plus, this application relates to multiple disputes, it's hard to be convinced that their kyc was reasonable. The governance team should look into this and keep the community updated.

Dcent's ridiculous reason for signing, knew them, had dinner with them? If such notaries are not removed, it would be ironic to the developers of CID reports that applicants can get signatures just by buying a notary dinner?

**Comment by dikemm** [comment]
#2008, a total of 5 rounds were triggered, 5x2=10 signatures, and someone signed 2 or 3 consecutive times. This is very unreasonable, and there is a possibility of collusion. It is recommended to investigate thoroughly. I found the report of Fildrive and Force LDN was also very unreasonable, and Herrehesse chose to turn a blind eye!
<img width="1175" alt="WX20230719-152306@2x" src="https://github.com/filecoin-project/notary-governance/assets/138772951/c3aa2b40-c51b-4fbe-a9c6-5a5e28272268">
Immediately check out notaries who sign multiple times and see which LDN they belong to!
Get rid of the 2008 data cap now!

**Comment by dikemm** [comment]
> > [filecoin-项目/filecoin-plus-large-datasets#1551](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1551)
> > ![图像](https://user-images.githubusercontent.com/11014169/253878971-92bdf584-16d5-4463-8637-4a3194848c88.png)
> > @cryptowhizzard为什么你的应用程序有如此大的重复问题并与**4 PiB**共享？
> 
> [技术贪婪/奇点#172](https://github.com/tech-greedy/singularity/issues/172)

This explanation is too fake!
There are so many people using Singularity at the same time, why is there so much duplication of your LDN?
Can you not take any responsibility if you push all the problems to the singularity?
Even if it is a problem of singularity, then you have seen this problem, why don't you stop it?

**Comment by cryptowhizzard** [comment]
> > > [filecoin-项目/filecoin-plus-large-datasets#1551](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1551)
> > > ![图像](https://user-images.githubusercontent.com/11014169/253878971-92bdf584-16d5-4463-8637-4a3194848c88.png)
> > > @cryptowhizzard为什么你的应用程序有如此大的重复问题并与**4 PiB**共享？
> > 
> > 
> > [技术贪婪/奇点#172](https://github.com/tech-greedy/singularity/issues/172)
> 
> This explanation is too fake! There are so many people using Singularity at the same time, why is there so much duplication of your LDN? Can you not take any responsibility if you push all the problems to the singularity? Even if it is a problem of singularity, then you have seen this problem, why don't you stop it?

It is already stopped. You are looking in the past ( months ago ) and should look in the present.

**Comment by lyjmry** [comment]
I want to be taken seriously
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2008#issuecomment-1643645187

**Comment by defiking0108** [comment]
I have some doubts about Hidde's [response](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2100#issuecomment-1637055285), as far as I know, it is not according to the FILPlus rules.

![image](https://github.com/filecoin-project/notary-governance/assets/109508514/98ea2a22-7d34-4273-ac27-54c9bd5a8a77)


Why can Hidde widely comment on new LDNs with rules not approved by the community and influence PL's judgment, seriously affecting the review progress? If you are willing to spend time, you can find Hidde's replies on many new LDN applications, and only those that meet his rules can pass the review. Is this dictatorship?
https://github.com/filecoin-project/notary-governance/issues/934#issuecomment-1643384873
![image](https://github.com/filecoin-project/notary-governance/assets/109508514/a94e39f6-7921-45e2-83f6-ba39dd2a0cf8)



Why discriminate against Asia? Can't Asian SPs participate in FILPlus? Isn't Filecoin global? VPNs aren't banned by the community, are you targeting certain SPs with American VPNs?
![image](https://github.com/filecoin-project/notary-governance/assets/109508514/841878a1-d4e6-4fe1-a001-39c5036ff2ba)


We strongly suggest removing Hidde from notaries pool.

**Comment by herrehesse** [comment]
Yes let’s remove me from the notary pool!

**Comment by herrehesse** [comment]
Could you please stop with the “discrimination/racist” argument?

**Comment by defiking0108** [comment]
> Could you please stop with the “discrimination/racist” argument?
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1937#issuecomment-1633927361
![image](https://github.com/filecoin-project/notary-governance/assets/109508514/56faf1bf-d1d6-4af6-9c0e-391636a72bce)

**Comment by herrehesse** [comment]
If it’s true then it’s by default no racism / discrimination 🫡

**Comment by herrehesse** [comment]
@defiking0108, are you genuinely asking me to provide evidence that the majority of abuse cases originate from the same region in Asia/China? It is an established fact and not a matter of discussion or argument. I would also like to emphasize that the argument of racism or discrimination does not hold ground at all in this context. 

The identification of a specific region is based solely on observed patterns and statistics, without any discriminatory intent or implications.

**Comment by herrehesse** [comment]
It is important to emphasize that recognizing the prevalence of fraud originating from a particular region is not an act of discrimination. Identifying patterns and trends based on data and observations is a standard practice in addressing and mitigating fraudulent activities. 

Our intention is to safeguard the ecosystem and protect its users, without targeting or discriminating against any specific group of people. Our focus remains on combating fraud and ensuring a safe environment for all participants.

**Comment by emilytklee** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2040#issuecomment-1636055281

![image](https://github.com/filecoin-project/notary-governance/assets/140073209/416d0494-9b1e-4097-a1ce-1ce7c313f1d7)

![image](https://github.com/filecoin-project/notary-governance/assets/140073209/c4e3f67a-14f4-46d0-b5b7-db28b144ea0b)

![image](https://github.com/filecoin-project/notary-governance/assets/140073209/74fec562-766c-4b39-a0eb-e48535e442f2)

Look, in the CIDreporter, there is only one miner located in Cleveland, Ohio, US - OneCleveland. The new SP is also located in the US, and the list of SPs in the client's current sealing plan does not comply with FILPlus rules at all. Yet, you signed it knowingly violating the rules.

**Comment by emilytklee** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2008#issuecomment-1643645187

Help to attach 2008 here

**Comment by herrehesse** [comment]
![Screenshot 2023-07-20 at 14 59 24](https://github.com/filecoin-project/notary-governance/assets/70132857/fba38f19-18a6-4654-ac1d-4985ee37f198)

Yes we need more throwaway accounts to do due diligence on active and respected community members. Thank you so much. @emilytklee

**Comment by amughal** [comment]
@emilytklee This is Azher from mongostorage. Please take sometime and read through the LDN notes. Per my commitment, next SP coming up is in LasVegas and more SPs to follow for broader GEO redundancy. Let me know if you have further questions.

**Comment by herrehesse** [comment]
Thanks for your quick response @amughal

**Comment by emilytklee** [comment]
> @emilytklee This is Azher from mongostorage. Please take sometime and read through the LDN notes. Per my commitment, next SP coming up is in LasVegas and more SPs to follow for broader GEO redundancy. Let me know if you have further questions.
> 
> Adding further; Another SP I am working with is in South Korea.

also 
But @cryptowhizzard  did not carry out due diligence, he did not disclosure any info at that time

**Comment by herrehesse** [comment]
I can give you about a thousand, but lets start here: https://github.com/filecoin-project/notary-governance/issues/937

**Comment by emilytklee** [comment]
Attach another useful link here #933

**Comment by defiking0108** [comment]
> I can give you about a thousand, but lets start here: #937

Come on, a single case like #937 does not substantiate the broad claim you're making. Can you provide concrete evidence that verifies the general applicability of your statement?

**Comment by herrehesse** [comment]
One case?

Issue 914: https://github.com/filecoin-project/notary-governance/issues/914
Issue 915: https://github.com/filecoin-project/notary-governance/issues/915
Issue 916: https://github.com/filecoin-project/notary-governance/issues/916
Issue 917: https://github.com/filecoin-project/notary-governance/issues/917
Issue 918: https://github.com/filecoin-project/notary-governance/issues/918

Based on the information provided, it appears that the origin of the activity can be attributed to either China or "VPN" connections from the USA or Europe (CN). If you would like, I can continue showing you more, as we have been conducting extensive research on abuse cases since December of last year. We have gathered substantial evidence on numerous abusive applications, many of which have been traced back to China.

As I present more evidence to counter your "discrimination" accusation, its strength seems to diminish. Therefore, I would like to understand the main point you are trying to convey here.

Can you provide examples of fraud from Australia, Belgium, New York, or Amsterdam? Thus far, I have not come across any instances from these locations. While >90% is from the CN region.

**Comment by herrehesse** [comment]
More gaslighting!

**Comment by cryptowhizzard** [comment]
> I want to be taken seriously
> [filecoin-project/filecoin-plus-large-datasets#2008 (comment)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2008#issuecomment-1643645187)

If you want to be taken seriously i suggest that you start with yourself.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2068

**Comment by cryptowhizzard** [comment]
> [filecoin-project/filecoin-plus-large-datasets#2040 (comment)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2040#issuecomment-1636055281)
> 
> ![image](https://user-images.githubusercontent.com/140073209/254885589-416d0494-9b1e-4097-a1ce-1ce7c313f1d7.png)
> 
> ![image](https://user-images.githubusercontent.com/140073209/254885754-c4e3f67a-14f4-46d0-b5b7-db28b144ea0b.png)
> 
> ![image](https://user-images.githubusercontent.com/140073209/254885898-74fec562-766c-4b39-a0eb-e48535e442f2.png)
> 
> Look, in the CIDreporter, there is only one miner located in Cleveland, Ohio, US - OneCleveland. The new SP is also located in the US, and the list of SPs in the client's current sealing plan does not comply with FILPlus rules at all. Yet, you signed it knowingly violating the rules.

Have you even read this?

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2040#issuecomment-1581369542

This client is an ESPA participant. There is little use in proving extra KYC as PikNik already arranged that and Dcent has close contact with them.

Please educate yourself about the ESPA program and it’s use. Perhaps you should participate, there is a world to learn for you.

**Comment by dikemm** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1623
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1624
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1625
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1626
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1627

**Comment by dikemm** [comment]
https://github.com/filecoin-project/notary-governance/issues/935#issuecomment-1646456333

**Comment by Filplus-govteam** [comment]
This post was supposed to be about 1068 from cryptowhizzard's signature but has severely diverged calling out other applications and members of the community. 

The accused notary has provided evidence for their signature on 1068 and seeing no objective response to their evidence, this dispute is being closed with no consequences on the said notary
