### ISSUE TITLE
FilSwan Resignation as a notary from the Filecoin plus program

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/notary-governance#936]
Hi everyone,

Time flies fast, it has been 2 years since I elected as a notary (https://github.com/filecoin-project/notary-governance/issues/157)

**What I have done**
•	SLA Level 5 https://github.com/filecoin-project/notary-governance/issues/778
•	Applications Signed: 47
•	Comments on Proposals: 4
•	Active member of T&T Working Group: No
•	Active member of E-Fil+ Working Group: Yes
•	Completed Sentiment Survey: No
•	Notary Governance Calls Attended: 10
•	Metrics confirmed by Notary: Yes
Reference: https://github.com/filecoin-project/notary-governance/discussions/904

It was a wonderful time to work with Deep, Kevin from day one when the program was set up, and help test the fil+, verified deals, etc.

Today, Fil+ is a group has over 100 notaries, and 50% of the Filecoin QAP with 100% new QAP increase is bought by Fil+. It becomes more important to the Filecoin economic model.

Meanwhile, me, Charels Cao as the notary of FilSwan, become increasingly busy with ecosystem project building and feels that it is becoming harder for me to continue work in the group.

**Reason to Resign**

•	Notary has no compensation for the work spent in the group
•	If you sign a datacap, you need to perform lots of work like data distribution,  data verification, and now data retrieval, those requirements are continues increasing to take more time
•	Notaries attack each other using some policy set by the governance team, which takes lots of time and delays the progress of actual work
•	Some notaries need to prove your innocence even when accuse without evidence https://github.com/filecoin-project/notary-governance/issues/898
•	Personally want to spend more time building projects to serve the client who wants to pay for storage. 

**Final Words**
Based on the above thoughts, I decided to resign as a notary, but I will still stay in the ecosystem as a builder and community member. 

Good luck everyone.

**Comment by The-Wayvy** [comment]
Make Filecoin Permissionless Again!

**Comment by Normalnoise** [comment]
Thank filswan for your contributions to Fil+ and Filecoin

**Comment by raghavrmadya** [comment]
Thanks for your contributions Charles.

**Comment by sgclouder** [comment]
"No FIL Plus, No Abuse".The beautiful melody and its echo remained whirling around the house rafters.

**Comment by 1ane-1** [comment]
Thanks

**Comment by hsxiaotianquan** [comment]
Should fil+ do something to keep Charles here?  I am afraid more notaries will leave filecoin Notary Group.

**Comment by The-Wayvy** [comment]
@hsxiaotianquan 

No!

We need to do kill FIL+

**Comment by ars-bubu** [comment]
We express our regret that such an excellent organization and individual have left. Is there still a voice of justice.
@flyworker 
Although you have removed your equipment, I hope you will still maintain peace in a different capacity

**Comment by marksunyaoyao** [comment]
> @hsxiaotianquan
> 
> No!
> 
> We need to do kill FIL+

Please give current gov-team some time to change.
If things aren't going in the right way, we support to kill fil+.

**Comment by marksunyaoyao** [comment]
> Should fil+ do something to keep Charles here? I am afraid more notaries will leave filecoin Notary Group.

It doesn't matter , RG is enough!

**Comment by flyworker** [comment]
> 

Thanks @ars-bubu 

We did not remove the equipment, FilSwan provides services that integrate data, computing, bandwidth, and payment into one suite for Web3 projects.
So the major focus is the ecosystem build.

**Comment by baseonejj** [comment]
> Personally want to spend more time building projects to serve the client who wants to pay for storage.

现在有这样的客户吗？

**Comment by Kevin-FF-USA** [comment]
Thank you for your years of selfless service Charles. Looking forward to seeing you within the ecosystem
