### ISSUE TITLE
Pause closing of open issues/decisions until a consensus is reached on T&T Committee

### ISSUE THREAD

**Issue by Filplus-govteam** [filecoin-project/notary-governance#942]
## Issue Description
Over the last several weeks, the Fil plus gov team has received pleas pleading not guilty as well as evidence in DMs from various active community members requesting action on certain open issues related to DC removal or notary removal.

## Proposed Solution(s)
The governance team will refrain from closing or providing a decision on open disputes and issues until we reach a consensus on the proposal for the T&T Committee

### Timeline
Effective immediately

**Comment by The-Wayvy** [comment]
"pleading not guilty"

is this a blockchain or a court?
