### ISSUE TITLE
[DataCap Removal Proposal] Abusive Behaviour Detected on 1906 - TakiChain, BobbyChoii, Aifabot-Cloud and Casey-PG

### ISSUE THREAD

**Issue by herrehesse** [filecoin-project/notary-governance#943]
## Issue Description

The submitted data is not retrievable. Data is fully centralised in the same region. Notaries failed to conduct any due diligence. 

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1906

Notaries Involved:
- Aifabot-Cloud
- BobbyChoii
- Casey-PG
- TakiChain

## Proposed Solution(s)

Requesting immediate removal of the application, client datacap, and the removal of the involved notaries who are recurrently involved in abuse cases.

**Comment by Parker35sun** [comment]
Have replied in the application. Thanks!

**Comment by raghavrmadya** [comment]
Closing this issue and following up in the application
