### ISSUE TITLE
[DataCap Removal Proposal LDN 1997]

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/notary-governance#944]
### Client Application URL or Application Number

1997

### Client Name

Inayatullah199 

### Client Address

f1whhxwushklk2lklqj7yv3lulqphdgnamei4fdfy

### Amount of DataCap to be removed

2PB

**Comment by cryptowhizzard** [comment]
Reason:

This data is not retrievable and not in line with FIL+ rules and guidelines

**Comment by raghavrmadya** [comment]
Seeing no comments, reply or pushback from the aforementioned client, this proposal is considered passed and DC must be removed from this LDN. cc @simonkim0515

**Comment by Inayatullah199** [comment]
Hi @raghavrmadya Can you share why you were comfortable passing this obvious gaslighting proposal without any your own confirmation? 

![image](https://github.com/filecoin-project/notary-governance/assets/130740851/0a89f513-bb97-4319-b010-eebb90a7b1b2)
