### ISSUE TITLE
DataCap Removal Proposal #1977

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/notary-governance#945]
### Client Application URL or Application Number

1977

### Client Name

leviYao25

### Client Address

f1bvwe3ohazst2t64sfhjdfb4mcdxmy2yb6eho3rq

### Amount of DataCap to be removed

238TB

**Comment by cryptowhizzard** [comment]
This LDN has 0% retrievability. Instead of waiting that things get sealed against rules and guidelines we might as well remove the datacap.
Secondly:

⚠️ 1 storage providers sealed more than 90% of total datacap - [f02244750](https://filfox.info/en/address/f02244750): 100.00%

⚠️ All storage providers are located in the same region.

**Comment by leviYao25** [comment]
@cryptowhizzard 

The SPs we worked with support retrieval.
![0706](https://github.com/filecoin-project/notary-governance/assets/129844561/499478c8-2b25-4df7-8c6c-5e7d241ebf00)
But I don't know why the data is not shown in the retrieval report.

Our application was granted 256TiB in the first round and we've only sent 18TiB datacap to a SP. Since the community rules require sp to support http retrieval, we are in touch with more suitable SPs for future cooperation. Everything will get updated soon, thanks for your following.

**Comment by leviYao25** [comment]
@herrehesse 
>Our application was granted 256TiB in the first round and we've only sent 18TiB datacap to **a SP**.

**Can you please read my reply carefully?**


> This LDN has 0% retrievability. Instead of waiting that things get sealed against rules and guidelines we might as well remove the datacap. Secondly:
> 
> warning 1 storage providers sealed more than 90% of total datacap - [f02244750](https://filfox.info/en/address/f02244750): 100.00%
> 
> warning All storage providers are located in the same region.


Where did he mentioned that the location is VPN? I don't find anything from your picture. **No gaslighting**

**Comment by herrehesse** [comment]
@leviYao25 

![Screenshot 2023-07-24 at 11 46 30](https://github.com/filecoin-project/notary-governance/assets/70132857/b4c7efe8-6fe6-4cec-b14d-b45002b978cc)

Your set has already been onboarded multiple times, why does your copy add value?
If you made a "mistake" which i think you did not, I am happy to give you a second change looking at the size of the abuse, my follow up questions will be:

What miners have you selected to store with?
What are their real (no VPN) regions, so distribution can be done properly.
What is their name/business?
How did you contact/find them?

Lastly, your IP provider https://speedypage.com/ hosts VPN/VPS servers. Do you really want to argue your real location us UK?

**Comment by leviYao25** [comment]
Gaslighting is a form of psychological manipulation and emotional abuse in which one person seeks to make another doubt their own perceptions, memory, judgment, or sanity. The term "gaslighting" originated from a play called "Gas Light" and later adapted into movies, where a husband manipulates his wife into believing she is going insane by dimming the gas lights in their home and then denying that the lights have changed when she mentions it.

In interpersonal relationships, gaslighting typically involves a pattern of behavior by the gaslighter that aims to undermine the victim's confidence and sense of reality. Some common tactics used in gaslighting include:

Denial: The gaslighter denies that certain events happened or refuses to acknowledge their actions, even if there is evidence to the contrary.

Minimization: They downplay the significance of the victim's feelings or experiences, making them feel like their emotions are unwarranted or exaggerated.

Projection: The gaslighter attributes their own negative traits, behaviors, or actions to the victim, making the victim question their own behavior and character.

Blatant lies: They tell outright lies to confuse the victim and make them doubt their memory and understanding of events.

Withholding information: The gaslighter may withhold information to keep the victim in the dark and make them doubt their understanding of a situation.

Shifting blame: They blame the victim for any problems or issues in the relationship, making the victim feel responsible for the gaslighter's behavior.

Creating doubt: The gaslighter questions the victim's perception of reality, making them doubt their memory, judgment, or sanity.

**Comment by leviYao25** [comment]
@herrehesse 

Gaslighting is a form of psychological manipulation and emotional abuse in which one person seeks to make another doubt their own perceptions, memory, judgment, or sanity. The term "gaslighting" originated from a play called "Gas Light" and later adapted into movies, where a husband manipulates his wife into believing she is going insane by dimming the gas lights in their home and then denying that the lights have changed when she mentions it.

In interpersonal relationships, gaslighting typically involves a pattern of behavior by the gaslighter that aims to undermine the victim's confidence and sense of reality. Some common tactics used in gaslighting include:

Denial: The gaslighter denies that certain events happened or refuses to acknowledge their actions, even if there is evidence to the contrary.

Minimization: They downplay the significance of the victim's feelings or experiences, making them feel like their emotions are unwarranted or exaggerated.

Projection: The gaslighter attributes their own negative traits, behaviors, or actions to the victim, making the victim question their own behavior and character.

Blatant lies: They tell outright lies to confuse the victim and make them doubt their memory and understanding of events.

Withholding information: The gaslighter may withhold information to keep the victim in the dark and make them doubt their understanding of a situation.

Shifting blame: They blame the victim for any problems or issues in the relationship, making the victim feel responsible for the gaslighter's behavior.

Creating doubt: The gaslighter questions the victim's perception of reality, making them doubt their memory, judgment, or sanity.

**Comment by herrehesse** [comment]
Copy pasting my own responses won't help you here, answering questions will.

**Comment by raghavrmadya** [comment]
It seems that the issue here is with the retrieval bot and not an honest mistake of the client. Since the discussion has not evolved on this issue, it is reasonable to close the proposal without any removal. If there has been any updates to removal proposal, kindly open a new proposal
