### ISSUE TITLE
[Removal of notaries from the FIL+ Program]Abusive Behaviour Detected on 2008 - PikNik

### ISSUE THREAD

**Issue by kenzz45** [filecoin-project/notary-governance#946]
## Issue Description
@jamerduhgamer from PikNik signed this abusive application, Ignoring warnings from community members!

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2008
1、too much duplicate data
2、CID sharing within totally different datasets.

## Proposed Solution(s)
Requesting immediate removal of abusive notaries who are involved in this application---PikNik (may be more)

**Comment by cryptowhizzard** [comment]
![image](https://github.com/filecoin-project/notary-governance/assets/36404435/2081f450-02c9-40b6-9e0a-130644ada922)

**Comment by igoovo** [comment]
> ![image](https://user-images.githubusercontent.com/36404435/255330820-2081f450-02c9-40b6-9e0a-130644ada922.png)

Oriental culture has implicit characteristics, and your friends can't lose face to accuse you.
Change nickname to remind you that you have done a lot of violations of the rules and go around blaming others.

In addition, even if they are new to the fil network, don't they have the right to speak?

**Comment by cryptowhizzard** [comment]
> > ![image](https://user-images.githubusercontent.com/36404435/255330820-2081f450-02c9-40b6-9e0a-130644ada922.png)
> 
> Oriental culture has implicit characteristics, and your friends can't lose face to accuse you. Change nickname to remind you that you have done a lot of violations of the rules and go around blaming others.
> 
> In addition, even if they are new to the fil network, don't they have the right to speak?

I really can’t wait to get my holiday invitations to come spend time with you guys but shall we get back on topic?

No need to worry, in my place of the world everyone has a right to speak. The people even use real names, makes it much more comfortable…..

Regarding the complaint itself it is already answer by the filcoinplus governance team

**Comment by kenzz45** [comment]
This is a classic case of a notary IGNORING the opinions of community members to force signatures. This type of behavior is exactly what the community is cracking down on these days.

@cryptowhizzard you haven't signed yet, don't come interfering.

**Comment by kenzz45** [comment]
This is a typical case of a notary IGNORING the opinions of community members to force signatures. This type of behavior is exactly what the community is cracking down on these days.

@cryptowhizzard you haven't signed it, don't come interfering.

**Comment by cryptowhizzard** [comment]
> This is a typical case of a notary IGNORING the opinions of community members to force signatures. This type of behavior is exactly what the community is cracking down on these days.
> 
> @cryptowhizzard you haven't signed it, don't come interfering.

2008 is my own application, notary rules state that you can’t sign your own applications.

Again, the governance team already responded to the claim and decided that it was ok to move on.

See here: https://github.com/filecoin-project/notary-governance/issues/935#issuecomment-1645456935

**Comment by kenzz45** [comment]
@cryptowhizzard  
Don't you see the new flag raised by community members after the link comment you gave?  And it may involve a serious notary collusion, which is a very sensitive matter.

Before this flag is reasonably explained, PikNik's forced signing is clearly an abuse. This is the common rule of the community. 

![image](https://github.com/filecoin-project/notary-governance/assets/140135738/c5e65aab-45eb-4be9-b25e-e3eb674804cd)

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard Don't you see the new flag raised by community members after the link comment you gave? 

No

> And it may involve a serious notary collusion, which is a very sensitive matter.

No, there is nothing like this.

> 
> Before this flag is reasonably explained, PikNik's forced signing is clearly an abuse. This is the common rule of the community.

It was already explained.

> 
> ![image](https://user-images.githubusercontent.com/140135738/255340234-c5e65aab-45eb-4be9-b25e-e3eb674804cd.png)

**Comment by c12xf** [comment]
As you mentioned earlier, having lunch or dinner together can earn your recognition; Did the notary also accept your bribe, so he took the risk of signing for you.

**Comment by kenzz45** [comment]
Exposing a suspicious interaction between them: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/388

**Comment by herrehesse** [comment]
Gaslighting is a form of psychological manipulation and emotional abuse in which one person seeks to make another doubt their own perceptions, memory, judgment, or sanity. The term "gaslighting" originated from a play called "Gas Light" and later adapted into movies, where a husband manipulates his wife into believing she is going insane by dimming the gas lights in their home and then denying that the lights have changed when she mentions it.

In interpersonal relationships, gaslighting typically involves a pattern of behavior by the gaslighter that aims to undermine the victim's confidence and sense of reality. Some common tactics used in gaslighting include:

1. Denial: The gaslighter denies that certain events happened or refuses to acknowledge their actions, even if there is evidence to the contrary.

2. Minimization: They downplay the significance of the victim's feelings or experiences, making them feel like their emotions are unwarranted or exaggerated.

3. Projection: The gaslighter attributes their own negative traits, behaviors, or actions to the victim, making the victim question their own behavior and character.

4. Blatant lies: They tell outright lies to confuse the victim and make them doubt their memory and understanding of events.

5. Withholding information: The gaslighter may withhold information to keep the victim in the dark and make them doubt their understanding of a situation.

6. Shifting blame: They blame the victim for any problems or issues in the relationship, making the victim feel responsible for the gaslighter's behavior.

7. Creating doubt: The gaslighter questions the victim's perception of reality, making them doubt their memory, judgment, or sanity.

**Comment by raghavrmadya** [comment]
Closed for spamming and gaslighting bas on aforementioned evidence and lack of objective or useful arguments

**Comment by kernelogic** [comment]
Who is gaslighting whom here?

**Comment by kernelogic** [comment]
KYCing new github account for LDN applications is one thing, I get that. 

OP posted a valid technical governance question and immediately get blamed on because the account is new? Not cool.
