### ISSUE TITLE
Modification: Removal of inactive E-Fil+ Notaries and invitation for active notaries from v4 multisig to join the E-Fil+ multisig

### ISSUE THREAD

**Issue by kevzak** [filecoin-project/notary-governance#948]
## Issue Description
First, we've found over the past 4+ months that the following notaries have been completely inactive in due diligence and/or signing activities for E-FIl+ applications. 
@Joss-Hua
@suyanj
@Holiday507
@Aifabot-Cloud
@Wengeding
@TakiChain
@Meibuy
@athsmith
@OlivierMolenkamp
@BobbyChoii
@Casey-PG
@1475Notary
@IPFSUnion
@bmcnabb25
@flyworker
@neogeweb3
@davidthoms
@swatchliu
@BlockMakeronline
@PluskitOfficial

This goes against the [SLA that was designed to support the E-Fil+ pilot](https://github.com/filecoin-project/notary-governance/discussions/579#discussioncomment-3198331) and in an effort to primarily reduce the admin overhead required to support 35+ notaries by one resource but also to open up space for more active notaries we are proposing to remove the list above.

Second, we have 13 notaries active at varying levels in past few months, but we have a demand for more consistent, active notaries in this multisig and are looking for new notary applicants so that we have 10-20 active from all regions available. Therefore, we are opening an invitation to join.

**Requirements to join the multisig:**
- Newly interested candidates and active notaries, we will require a free, third party KYC check associated with your GitHub account via filplus.storage
- If an active notary, we will also review your activity via leadership dashboard and review any active disputes/associations with applications proposed for DataCap removal.
- If a new notary applicant, there are the requirements to confirm you can meet responsibilities and operational guidelines as set here: https://github.com/filecoin-project/notary-governance/tree/main/notaries#operational-guidelines

FYI:
@jamerduhgamer
@cryptowizzard
@MatrixStorage
@Fenbushi-Filecoin
@newwebgroup
@derricktan23
@liyunzhi-666
@Fatman13
@stcouldlisa
@MRJAVAZHAO
@Carohere
@XnMatrixSV
@niwandao
@laurapanda
@Destore2023 

### Timeline
- Inactive notaries have been warned twice previously via slack about participation SLA and without any further notification to me, they will be removed by Aug 7th.

- For new applicants and active notaries, the timeline for proposed changes will be two weeks, by Aug 7th.
- For active notaries, KYC will need to be completed prior and activity will be reviewed and decided by Aug 11th.
- For new notaries, KYC will need to be completed and applications are due by this date and will be reviewed and decided by Aug 11th.

### Technical dependencies 
RKH is required to add/remove notaries

**Comment by Chris00618** [comment]
Don't think it's a good idea to set up a separate E-fil notaries group which would waste lots of governance cost and suggest sharing current notaries. 

For the full proposal, please refer to https://github.com/filecoin-project/notary-governance/issues/928

**Comment by flyworker** [comment]
agree

**Comment by Fatman13** [comment]
If this is to be accepted, for notaries in China, I propose use SMS text as the verification for KYC as every mobile phone number is already mandated by the government to be linked to citizen id (equivalent to SNS# in States) and would be much more reliable than third-party vendor the f+ governance body could get hold of.

**Comment by igoovo** [comment]
I support the proposal.

**Comment by spaceT9** [comment]
interested to join

**Comment by Destore2023** [comment]
> Don't think it's a good idea to set up a separate E-fil notaries group which would waste lots of governance cost and suggest sharing current notaries.
> 
> For the full proposal, please refer to #928

Hi Kevin, #934 may be the reason you can't find a notary to sign, those notaries are under dispute. 

Argee with@Chris00618 sharing current notaries plus your KYC (Toggle) will be the most efficient way to move forward on FIL+E.

What I know is that the Toggle will cost USD100 for each validation. Can you help them get a grant from PL for their KYC based on the notary's contribution to the community without any pay?

Once they pass the KYC, all disputes will be removed and the notary will be responsible for their approval for each LDN they are involved in.

**Comment by kevzak** [comment]
Hi @Destore2023 thank you for the feedback. Any notary that's a part of 934 was not active in E-Fil WG anyway, so I'm not so concerned there. 

Just for awareness about why E-Fil is a separate WG, see details [here ](https://github.com/filecoin-project/notary-governance/discussions/579#discussioncomment-3198331). We needed to find a sub group of notaries who were supportive of private dataset and also could meet a certain SLA. That is still the expectation. Clients in this WG are going through additional KYC and KYB and sharing information about their project and SPs involved. And as a result of this level of transparency they expect a certain level of support from notaries. This is a different environment that the v4 multisig. 

I am looking for notaries to be active and conduct due diligence and ask questions. They do not have to sign. That's not the point. But remaining silent on the side line for months, not responding to slack, not adding any ideas or value toward building a better product is not the goal of this WG. Those listed above that did not meet the SLA are being removed for this reason.

Regarding cost: I think you are thinking of the [Synaps KYB tool](https://efilplus.synaps.me/) that we offer for private data clients. That costs $100 to complete a business check. 

For notaries and anyone else, KYC is free. We have integrated a solution in filplus.storage that anyone can complete. 

Adding layers of trust for all actors involved is part of the goal of E-Fil+ and KYC requirements for notaries who want to be involved is the next layer.

**Comment by kevzak** [comment]
> Don't think it's a good idea to set up a separate E-fil notaries group which would waste lots of governance cost and suggest sharing current notaries.
> 
> For the full proposal, please refer to #928

@Chris00618 see my comment above about why E-Fil+ WG is a separate multisig today. I don't disagree with you that eventually it could be combined into v4. However, the majority of the 85 active notaries there do not meet the SLA requirements toward support of private dataset onboarding. And the datatype pathways are different enough to keep separate for now. If we continue to move toward more trust requirements for all clients, then I can see it being the same.

**Comment by Chris00618** [comment]
Understand your position, but disagree with your point. Precisely because of the early stage of development, deliberately emphasizing e-fil's special SLA will only have a negative effect on its growth. @kevzak 

Suggest a public vote to decide whether this proposal passes or not.

**Comment by Fatman13** [comment]
Thank you, Kevin! @kevzak 

> Thank you for the feedback @Fatman13 . If you have another third party product that can confirm identification we're open to using it.

I see three ways that KYC could be easily done in China region.

1. Send random token to notaries' mobile phone and have notaries report back the token. 
2. Send random amount of money, 0.3 rmb for example, to notaries' alipay account and have notaries to report back the number.
3. Use wechat [identification API](https://pay.weixin.qq.com/wiki/doc/api_external/en/apis/chapter4_3_2.shtml). 
4. Use Alipay [identification API](https://global.alipay.com/docs/ac/dws2/verifyauthentication).

Again, all accounts mentioned above is linked to a unique citizen id (equivalent to SNS# in States) already.

**Comment by kevzak** [comment]
> 

@Chris00618 I don't understand how the SLA has a negative effect on growth. Can you explain?

Perhaps I should separate the two topics:
- Removing inactive notaries - just to reiterate - these are individuals or entities that have not engaged over a substantive time horizon, defined as not responding, not engaging, not discussing, let alone not reviewing DataCap applications. removing them is reducing a threat vector in the allocation of a valuable resources.

- Adding notaries who support enterprise use cases and agree to meet the SLA. We need more active notaries here to support growth actually.

**Comment by Chris00618** [comment]
@kevzak  Thanks for your feedback. As a decentralized storage type project, censoring storage content and setting up different SLAs sounds anti-web3, so it can't be something sustainable in the long term.

Consolidation and simplification is the right direction.

**Comment by Fenbushi-Filecoin** [comment]
Support the proposal

**Comment by newwebgroup** [comment]
Support the proposal

**Comment by kevzak** [comment]
> @kevzak Thanks for your feedback. As a decentralized storage type project, censoring storage content and setting up different SLAs sounds anti-web3, so it can't be something sustainable in the long term.
> 
> Consolidation and simplification is the right direction.

I actually think the opposite. Consilidation = centralization. Having different pathways is in fact more decentralized.

**Comment by kevzak** [comment]
Seems like comments from the active notary community are in support of this proposal. 

We'll make one change to the details above. This invitation to join the multisig should only be available to currently active notaries, which experience using the tools and processes. This follows similar onboarding of addtional E-Fil members in the past. If you are interested and not an active notary, you can look to join this particular multisig in conjunction with a future general notary election.

**Comment by 1ane-1** [comment]
> 活跃的公证人社区的评论似乎支持该提案。
> 
> 我们将对上述细节进行一处更改。加入多重签名的邀请仅适用于当前活跃的公证人，他们具有使用工具和流程的经验以及管理应用程序的视角。此前，其他 E-Fil 成员也曾进行过类似的入职培训。
> 
> 如果您有兴趣但不是活跃的公证人，您可以考虑加入这个特定的多重签名，同时完成未来的公证人选举。
> 
> 到目前为止，我从不活跃的 E-Fil 公证人那里得知，他们已经重新聘用了： @NDLABS-Leo @BlockMakeronline @AthSmith @Joss-Hua
> 
> 以及来自 v4 多重签名的公证人： @NewHuoPool @sxxfuture-official

we

> Seems like comments from the active notary community are in support of this proposal.
> 
> We'll make one change to the details above. This invitation to join the multisig should only be available to currently active notaries, that have experience using the tools and processes and perspective on managing applications. This follows similar previous onboarding of additional E-Fil members in the past.
> 
> If you are interested and not an active notary, you can look to join this particular multisig in conjunction with completion of a future general notary election.
> 
> so far I've heard from inactive E-Fil notaries that have reengaged: @NDLABS-Leo @BlockMakeronline @AthSmith @Joss-Hua
> 
> And notaries from the v4 multisig: @NewHuoPool @sxxfuture-official

Hey, dear kevzak,we are V3 and V4 active notary, we want to be the E-FIL notary too.

**Comment by 1ane-1** [comment]
> Seems like comments from the active notary community are in support of this proposal.
> 
> We'll make one change to the details above. This invitation to join the multisig should only be available to currently active notaries, that have experience using the tools and processes and perspective on managing applications. This follows similar previous onboarding of additional E-Fil members in the past.
> 
> If you are interested and not an active notary, you can look to join this particular multisig in conjunction with completion of a future general notary election.
> 
> so far I've heard from inactive E-Fil notaries that have reengaged: @NDLABS-Leo @BlockMakeronline @AthSmith @Joss-Hua
> 
> And notaries from the v4 multisig: @NewHuoPool @sxxfuture-official

@kevzak Hey, dear kevzak,we are V3 and V4 active notary, we want to be the E-FIL notary too. What should i do for that?

**Comment by PluskitOfficial** [comment]
@kevzak We are willing to continue to participate in the E-Fil project and will further increase our activity in the future.

**Comment by kevzak** [comment]
Additional notaries from v4 multisig requesting to join:
@dayougroup 
@1ane-1 
@METAVERSEDATAMINING
@Wengeding
@nj-steve

Notaries who messaged saying they are willing to re-engage:
@PluskitOfficial 
@Bennyyangpu
@bobbychoii
@takichain
@casey-pg
@Suyanj

Note: any notaries under dispute will not be impacted by this change. If something transpires from other proposals/disputes, that will supersede any changes here.

**Comment by kevzak** [comment]
For E-Fil+ multisig notaries, please review the SLA for expectations: https://github.com/filecoin-project/notary-governance/discussions/579#discussioncomment-3198331

Once reviewed and in agreement, the next step to remain an active member of the multisig, all notaries should complete the KYC (know your customer) ID check on Filplus.storage.

Steps:
- Login to Filplus.storage with your notary github handle. 
- Click on KYC verification link
- Complete steps on third party site, Togggle (ID check and liveliness)
- Once confirmed your github ID will show as KYC verified. Message @kevzak to confirm.
- See article here for more details: [LINK](https://medium.com/filecoin-plus/implementation-of-a-third-party-kyc-id-check-for-fil-applicants-e5e825b1484e)
- Please complete the check by Sunday, August 13th.

@PluskitOfficial
@Bennyyangpu
@BobbyChoii
@TakiChain
@Casey-PG
@Suyanj
@DaYouGroup
@1ane-1
@METAVERSEDATAMINING
@Wengeding
@nj-steve
@NDLABS-Leo
@BlockMakeronline
@AthSmith
@Joss-Hua
@NewHuoPool
@sxxfuture-official
@jamerduhgamer
@cryptowizzard
@MatrixStorage
@Fenbushi-Filecoin
@newwebgroup
@derricktan23
@liyunzhi-666
@Fatman13
@stcouldlisa
@MRJAVAZHAO
@Carohere
@XnMatrixSV
@NiwanDao
@laurapanda
@Destore2023

**Comment by Joss-Hua** [comment]
done @kevzak

**Comment by 1ane-1** [comment]
Done @kevzak

**Comment by sxxfuture-official** [comment]
Done @kevzak 
![img_v2_35034dc8-a282-4f25-aa9d-7bb84101e00g](https://github.com/filecoin-project/notary-governance/assets/113963951/2ee44e86-2a8c-44ac-a4c7-36ec3969d2fa)

**Comment by 1ane-1** [comment]
![image](https://github.com/filecoin-project/notary-governance/assets/91301211/277f0bd2-f153-4ffe-beaf-f48ff2bc4857)
Done @kevzak

**Comment by nj-steve** [comment]
have done kyc @kevzak

**Comment by jamerduhgamer** [comment]
Also done
![image](https://github.com/filecoin-project/notary-governance/assets/16791309/dadecc44-528e-4ebe-a476-42626d53b90e)

**Comment by newwebgroup** [comment]
Done
<img width="469" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/100118145/977fcbc8-117a-4b47-957d-df8e729cf744">

**Comment by NewHuoPool** [comment]
Done![image](https://github.com/filecoin-project/notary-governance/assets/117884185/fd33d155-5984-4e3d-9591-1a7325cae86a)

**Comment by Fatman13** [comment]
Hello, @kevzak, I would like to bing up the issue :alert: that it is breaking [Chinese law](http://www.npc.gov.cn/npc/c30834/202108/a8c4e3672c74491a80b53a172bb753fe.shtml) to process Chinese citizen KYC information without establishing a legal entity in China. efil+ needs other ways to KYC CN notary.

![image](https://github.com/filecoin-project/notary-governance/assets/1591330/728521be-accf-4bc9-b192-cdb8a8fb678f)

**Comment by kevzak** [comment]
@Fatman13 - So then it must be illegal to complete business checks on Chinese companies as well? Should we exclude China from Enterprise opportunities?

Are any of the ways [you mentioned above ](https://github.com/filecoin-project/notary-governance/issues/948#issuecomment-1650831770) considered more legal for Chinese citizens then? What is the difference between checking a legal ID and checking another way to identify someone? 

As I mentioned to you before, you are welcome to find another way that meets requirements to identify someone. I'm happy to work with you to get it setup. For now, we have one third party process in place that checks identity for any country. Seems to work well.

**Comment by raghavrmadya** [comment]
Hi @Fatman13, this is interesting. E-fil+ is merely listing the requirements to be eligible. If a chinese citizen chooses to participate in E-Fil+, it is their liability. 

Until this is resolved and we find a way to properly do KYC on Chinese clients, I think we should propose that all Chinese clients to participate in E-Fil+. I'll draft a proposal later today

**Comment by Fatman13** [comment]
> How do Chinese citizens travel abroad? Do they not have to show legal ID and liveliness?

Because countries has embassies in China which will be liable if breach of information is found out. 

> Are any of the ways https://github.com/filecoin-project/notary-governance/issues/948#issuecomment-1650831770considered legal for Chinese citizens then?

yes KYC through Alipay and WeChat are legal. They follow Chinese regulations and will do DDs on whoever is using their APIs.

> For now, we have one third party process in place that checks identity for any country. Seems to work well even for Chinese participants.

If they are not have entity setup within China, it is considered illegal.

**Comment by Aaron01230** [comment]
<img width="323" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/107668727/5b99d498-268a-4b33-801f-973bd59ce6b6">
done

**Comment by derricktan23** [comment]
just happened to see this thread, I will do the verification by tommorrow. 

> For E-Fil+ multisig notaries, please review the SLA for expectations: [#579 (comment)](https://github.com/filecoin-project/notary-governance/discussions/579#discussioncomment-3198331)
> 
> Once reviewed and in agreement, the next step to remain an active member of the multisig, all notaries should complete the KYC (know your customer) ID check on Filplus.storage.
> 
> Steps:
> 
> * Login to Filplus.storage with your notary github handle.
> * Click on KYC verification link
> * Complete steps on third party site, Togggle (ID check and liveliness)
> * Once confirmed your github ID will show as KYC verified. Message @kevzak to confirm.
> * See article here for more details: [LINK](https://medium.com/filecoin-plus/implementation-of-a-third-party-kyc-id-check-for-fil-applicants-e5e825b1484e)
> * Please complete the check by Sunday, August 13th.

**Comment by kevzak** [comment]
Currently providing any additional time needed time for notaries to complete KYC this week. I will finalize the list and next steps by Friday

**Comment by kevzak** [comment]
> > > How do Chinese citizens travel abroad? Do they not have to show legal ID and liveliness?
> > 
> > 
> > Because countries has embassies in China which will be liable if breach of information is found out. These are agencies of states, which KYC providers are obviously not.
> > > Are any of the ways [#948 (comment)](https://github.com/filecoin-project/notary-governance/issues/948#issuecomment-1650831770considered) legal for Chinese citizens then?
> > 
> > 
> > yes KYC through Alipay and WeChat are legal. They follow Chinese regulations and will do DDs on whoever is using their APIs.
> > > For now, we have one third party process in place that checks identity for any country. Seems to work well even for Chinese participants.
> > 
> > 
> > If they do not have entity setup within China, it is considered illegal.
> > > I'm happy to work with you to get it setup.
> > 
> > 
> > Would love to, unfortunately, I don’t have enough time for this.
> 
> The problems @Fatman13 mentioned are real.

Anyone who want to pilot KYC through another third party option, please let me know this week.

**Comment by derricktan23** [comment]
> just happened to see this thread, I will do the verification by tommorrow.
> 
> >

<img width="245" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/108317502/f1e2a54c-ad71-44a7-b478-aeeaf3d93356">
verified, thanks kevin for the time extension.

**Comment by kevzak** [comment]
Update here:
the following notaries have successfully completed a KYC check:
@derricktan23 
@Aaron01230 
@NewHuoPool 
@jamerduhgamer 
@Destore2023 
@nj-steve 
@1ane-1 
@sxxfuture-official 
@newwebgroup 
@Joss-Hua 
@opengateNFT
@liyunzhi-666
@metaversedatamining
@cryptowizzard

For any others who signaled they wanted to remain as an active E-Fil+ notary, please confirm your intentions to complete KYC or not as soon as possible. Includes: https://github.com/filecoin-project/notary-governance/issues/948#issuecomment-1668721301

**Comment by psh0691** [comment]
@kevzak 
3,4 Active Notary, KYC completed.
I want to be a notary of E-Fil+.

**Comment by cryptowhizzard** [comment]
Done @kevzak

**Comment by kevzak** [comment]
> @kevzak 3,4 Active Notary, KYC completed. I want to be a notary of E-Fil+.

updated

**Comment by PluskitOfficial** [comment]
@kevzak KYC completed. Please check and confirm.
![6c6ed569bf770154c02c71f5c7ede6f](https://github.com/filecoin-project/notary-governance/assets/94815279/4e29625b-f7ed-47f5-9b91-0f27c79894a8)

**Comment by dannyob** [comment]
Hi @kevzak, I'd be happy to join the program.

**Comment by MatrixStorage** [comment]
<img width="459" alt="image" src="https://github.com/filecoin-project/notary-governance/assets/82867405/0e4c61e7-bdad-49cd-b523-84fd3ceef607">
please confirm

**Comment by Suyanj** [comment]
![image](https://github.com/filecoin-project/notary-governance/assets/107249346/8ac88bc0-888c-4759-8752-c2f3c875752f)

**Comment by MRJAVAZHAO** [comment]
![image](https://github.com/filecoin-project/notary-governance/assets/47096545/c9e1273c-ce5e-4c40-bed4-f3ec1f48888c)
Completed.

**Comment by kevzak** [comment]
> Hi @kevzak, I'd be happy to join the program.

Great @dannyob - please complete the KYC check and we'll add you to the list.

**Comment by zcfil** [comment]
![企业微信截图_16919846616275](https://github.com/filecoin-project/notary-governance/assets/45065975/a76b5d92-d030-438a-94b1-1fd8598a9c78)
Completed.

**Comment by Casey-PG** [comment]
![image](https://github.com/filecoin-project/notary-governance/assets/107392596/e3acfc8e-2eb9-4938-aed4-00bede248aaa)
Finish KYC.

**Comment by 1475Notary** [comment]
done.
![image](https://github.com/filecoin-project/notary-governance/assets/103022086/94b99c33-de6c-4155-b53a-15feba31ce1a)

**Comment by laurarenpanda** [comment]
Done!

<img width="402" alt="截屏2023-08-24 16 50 54" src="https://github.com/filecoin-project/notary-governance/assets/74699939/6af076d6-8745-45c8-9698-b9f934a5491a">

**Comment by herony-fil** [comment]
Done!
![image](https://github.com/filecoin-project/notary-governance/assets/112673155/2551670d-9912-4782-b950-aa35733843ad)

**Comment by AthSmith** [comment]
![image](https://github.com/filecoin-project/notary-governance/assets/94275737/009bf74a-9c33-4ac4-b979-5728310511d8)
Done!

**Comment by Meibuy** [comment]
![image](https://github.com/filecoin-project/notary-governance/assets/108273047/fe6a7e88-c590-401b-9b25-ba4196cdd58d)
Completed.

**Comment by NDLABS-Leo** [comment]
Done！
![image](https://github.com/filecoin-project/notary-governance/assets/104019147/0cbc6175-6902-4d66-ba8b-9feb9e9ce7a9)

**Comment by Wengeding** [comment]
![image](https://github.com/filecoin-project/notary-governance/assets/117442528/498509e1-55c5-4b55-8561-fd9c4c60c4cb)
done

**Comment by Bennyyangpu** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/107031628/d49ac95a-9696-47c5-9cd4-1ad1e5285223)
done

**Comment by TakiChain** [comment]
Done

![image](https://github.com/filecoin-project/notary-governance/assets/116626712/0e74f474-5ac8-45b0-91d7-18611bbdceb1)

**Comment by Filplus-govteam** [comment]
Here is the final list of E-Fil Notaries to be added/updated on the WG multisig: 
@derricktan23
@Aaron01230
@NewHuoPool
@jamerduhgamer
@Destore2023
@nj-steve
@1ane-1
@sxxfuture-official
@newwebgroup
@Joss-Hua
@OpenGateNFT
@liyunzhi-666
@METAVERSEDATAMINING
@cryptowizzard
@psh0691
@TakiChain 
@Bennyyangpu 
@Wengeding 
@NDLABS-Leo 
@MRJAVAZHAO 
@zcfil 
@Casey-PG 
@spaceT9 
@MatrixStorage 
@Suyanj 
@1475Notary 
@Meibuy 
@AthSmith

**Comment by Filplus-govteam** [comment]
> Done! ![image](https://user-images.githubusercontent.com/112673155/262924406-2551670d-9912-4782-b950-aa35733843ad.png)

which notary are you? @herony-fil

**Comment by kevzak** [comment]
Here is the final list of E-Fil Notaries that have compelted KYC to be added/updated on the WG multisig:
@laurarenpanda
@derricktan23
@Aaron01230
@NewHuoPool
@jamerduhgamer
@Destore2023
@nj-steve
@1ane-1
@sxxfuture-official
@newwebgroup
@Joss-Hua
@OpenGateNFT
@liyunzhi-666
@METAVERSEDATAMINING
@cryptowizzard
@psh0691
@TakiChain
@Bennyyangpu
@Wengeding
@NDLABS-Leo
@MRJAVAZHAO
@zcfil
@Casey-PG
@spaceT9
@MatrixStorage
@Suyanj
@1475Notary
@Meibuy
@AthSmith
@PluskitOfficial
@Fenbushi-Filecoin
@DaYouGroup
@s0nik42
@maxvint

Next Steps: Please allow 1-2 weeks to have notary address added to mutilsig (if not an active E-Fil+ Notary)

**Comment by kevzak** [comment]
Also, please let this serve as a reminder of the E-Fil+ WG [SLA](https://github.com/filecoin-project/notary-governance/discussions/807#discussion-4762523). The original list of inactive notaries were allowed to remain if they requested, but we will continue to monitor activity over the next 3-6 months. Thank you.

**Comment by kevzak** [comment]
Please confirm notary names:
@1ane-1
@nj-steve
@OpenGateNFT
@spaceT9
@suyanj
@Wengeding

**Comment by nj-steve** [comment]
Hello @kevzak I am steve from antalpha. nj-steve is my github handle. Our notary name is Xin Jin. My slack name is Steve-Antalpha.

**Comment by AlanGreaterheat** [comment]
> 以下是已完成 KYC 并在 WG 多重签名上添加/更新的 E-Fil 公证人的最终列表： @laurarenpanda @derricktan23 @Aaron01230 @NewHuoPool @jamerduhgamer @Destore2023 @nj-steve @1ane-1 @sxxfuture-official @newwebgroup @Joss-Hua @OpenGateNFT @liyunzhi-666 @METAVERSEDATAMINING @cryptowizzard @psh0691 @TakiChain @Bennyyangpu @Wengeding @NDLABS-Leo @MRJAVAZHAO @zcfil @Casey-PG @spaceT9 @MatrixStorage @Suyanj @1475Notary @Meibuy @AthSmith @PluskitOfficial @Fenbushi-Filecoin @DaYouGroup @s0nik42 @maxvint @AlanGreaterheat 后续步骤：请等待 1-2 周时间将公证地址添加到 mutilsig（如果不是活跃的 E-Fil+ 公证人）

cool！really thanks！

**Comment by 1ane-1** [comment]
Hello@kevzak, I am Anne from Genesis group. Our notary name is Genesis, and my github handle is 1ane-1 and slcak name is Genesis
