### ISSUE TITLE
[Appeal] Request to remain active Notary

### ISSUE THREAD

**Issue by MasaakiNawatani** [filecoin-project/notary-governance#952]
Hi, this is Masaaki Nawatani. 

I have been a Notary since the beginning of this program. I have been an active Notary and have distributed datacap in the ASIA minus GCN region for almost 2 years now. Until Round 4, where we encounter a technical issue with the ledger and Registry app taking our ability to sign away from us. 

While we wait for this technical solution to get implemented, we would like to stress our commitment to remain in the program.  We have filed active bug report to address and will regain access to Diligence. Will review open proposals and discuss and comment.

**Comment by raghavrmadya** [comment]
If you are able to provide evidence and it would be more reasonable to consider this appeal. Stressing commitment without showing any trace or evidence of engaging in due diligence, even if you could not sign, makes for a very weak appeal the appeal IMO. 

If RKH are seeing this, this notary does not have my support for remaining as an active notary. Other community members are welcome to chime in

**Comment by joshua75235** [comment]
> If RKH are seeing this, this notary does not have my support for remaining as an active notary. Other community members are welcome to chime in

It is funny you are calling RKH's attention for this issue. As a management personnel, how can you do not know that "The role of the Root Key Holder is not to make subjective decisions" and that they only "act as an executor for decisions made by the community"?

**Comment by MasaakiNawatani** [comment]
@raghavrmadya Thank you for sharing your thoughts. However, we are saddened by your opinion of me and my commitment to the program. Moreso, how my ongoing technical issue is handled by your team. I have evidence of my participation in all Notary rounds. I also have evidence of my perpetual request for someone on your team to assist me with our technical issue with datacap allocation and @Kevin-FF-USA and Philippe can attest to the situation as well.
