### ISSUE TITLE
[Appeal] Request to Retain Notary Identity of NFTSTAR

### ISSUE THREAD

**Issue by NFTSTAR2023** [filecoin-project/notary-governance#953]
Hi all, 
I am writing with a heartfelt plea to reconsider the decision to remove my notary identity from the Fil+ community due to inactivity. 
I was elected as a notary last year, and I am truly passionate about contributing to this esteemed role. Unfortunately, due to technical difficulties at that time, my hardware wallet was not integrated into the multi-signature address.

Despite this setback, I proactively reached out to the official team through Slack, seeking assistance to resolve the technical issues. Regrettably, my attempts to elicit a response went unanswered, leaving me unable to participate actively. Nevertheless, I remained enthusiastic about engaging in the community, as evident from my verification of the wallet address back in February.

I was deeply honored to have been selected as a notary in the third round and have wholeheartedly participated in every meeting and activity since then. The same holds true for the fourth round, where I continued to demonstrate my dedication and commitment. I genuinely believe in the mission of our community and am determined to contribute meaningfully.

I sincerely request everyone's understanding and compassion in considering my circumstances. Technical challenges are bound to arise in any endeavor, and my unwavering efforts to overcome them speak to my genuine intentions to serve as an active notary. I am incredibly grateful for the trust placed in me thus far, and I humbly ask for the opportunity to continue serving in this vital role.

Gov team's  decision means a great deal to me, as it represents not only the chance to remain a notary but also the chance to keep supporting the community I deeply care about. Please know that I am ready and willing to put forth my best efforts to fulfill my responsibilities as a notary and contribute positively to the growth and success of our community.

Thank you for taking the time to read my appeal. Your consideration and support are immensely appreciated.

With utmost sincerity and gratitude,
NFTSTAR

**Comment by raghavrmadya** [comment]
If you are able to provide evidence and objectivity to support what you said above, it would be more reasonable to consider this appeal. Here is an https://github.com/filecoin-project/notary-governance/issues/959 from another notary that was flagged for inactivity.

Your appeal is merely claims and words without any substantial proof.
Without evidence of engaging in due diligence, even if you could not sign due to technical challenges, the appeal is very weak IMO
