### ISSUE TITLE
[Appeal] KodaRobotDog Remain Notary

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/notary-governance#957]
On behalf of @KodaRobotDog -  Migrating this issue FROM: [Keyko](https://github.com/keyko-io/filecoin-verifier-frontend/issues/827) TO: This repo

"
I was not able to authenticate in Registry despite having been elected in v4 to be a notary.

I have continuously raised the tech issues to the team in various chats and threads in Slack to Kevin and the engineers since March. However, my notary account remains unverified despite multiple trials.

I have every intention to remain as a Notary because I am highly motivated to help the Filecoin community grow stronger in a healthy environment.

I have raised 2 bug reports and would like an opportunity to actually serve the community as a Notary once they are fixed.
"

![image](https://github.com/filecoin-project/notary-governance/assets/94004586/841a31b5-c514-41d9-a682-d378306e768c)

**Comment by raghavrmadya** [comment]
If you are able to provide evidence that your still participated in due diligence, even if you couldn't sign, this appeal seems reasonable.
