### ISSUE TITLE
[Appeal] CoffeeCloud Request to remain active Notary

### ISSUE THREAD

**Issue by xiangloong** [filecoin-project/notary-governance#958]
Hello, RG, kevin, and Fil-plus teams. I am Ti Wong of Coffee Cloud, and I am participating in the meeting to request to retain the notary status of Coffee Cloud.

To be honest, we attach great importance to the identity of the notary. Because we think the identity of the notary is very important, we treat signatures very cautiously. We don't want to sign any non-compliant signatures, so our activity may be relatively low. 

However, the number of signatures and attention to filecoin are different concepts. For a long time, we have been paying close attention to the dynamics of slack, issus, Filecoin version updates and technology upgrades. We actively participate in major notary conferences, and we are also Develop Dapps based on FVM.

As a technology-driven company, our silence and low profile may not be the best option in the eyes of the community. Therefore, we will also actively participate in meetings, publish our views, and sign actively from now on.

Sincerely, I hope you will consider retaining our position as a notary, thank you!

**Comment by raghavrmadya** [comment]
If you are able to provide evidence and objectivity to support what you said above, it would be more reasonable to consider this appeal. Here is an [example ](https://github.com/filecoin-project/notary-governance/issues/959)from another notary that was flagged for inactivity. 

Your appeal is merely claims and words without any substantial proof for comments like " we have been paying close attention to the dynamics of slack, issues, Filecoin version updates, and technology upgrades"

If you think that is a risk for your org to engage as a notary publicly, I do not think the notary role is a fit for your organization
