### ISSUE TITLE
[Appeal] Big Data Exchange (BDX) Request To Remain As A Notary

### ISSUE THREAD

**Issue by BDE-io** [filecoin-project/notary-governance#959]
Hi Notaries and Governance Team, 

BDX likes to request to remain as a notary. 

Our SLA is L2 and we chose this level in our application because we were confident we can meet this level of commitment and we believe we have as illustrated below:

1. We actively participate in Notary Governance meeting. Up till now, we missed at most five meetings due to schedule conflicts. 
2. While we may not have actively provided comments and opinions in public discourse regarding LDN applications, we have provided advice regarding LDN's rules and guidance to a lot of the participants privately or on BDX slack workspace. Happy to provide names if necessary.
3. We actively help data clients, including LDN applicants, source for SPs to store replicas of the datasets, thus helping them with distribution of replicas across multiple regions. This also helps LDN applicants get to the next tranche of DataCap allocation promptly so that the community can continue to onboard more useful data. Happy to provide names if necessary. 
4. Recently, we have also started signing LDN application to signal more activity in a more visible manner. And we are happy to do so to continue to show our interest and involvement within the community
5. On BDX, if the data auction carries a LDN application, anyone anywhere can track how the data is being stored and where it is being stored to a certain extent. In this respect, this is another governance tool for notaries. 
6. There were also non-native data clients that we have actively helped to onboard into the Filecoin ecosystem when they experienced difficulty sourcing for SPs. Solana is one example and we facilitated the matching within 24 hours for two of their datasets (https://www.bigdataexchange.io/detail/20230510459289 and https://www.bigdataexchange.io/detail/20230718051309)
7. We have built external API tools for data clients, including LDN applicatns, to programmatically publish data auctions. The aim is to be able to match data clients and SPs efficiently and thus onboard data at scale.  
8. We assisted with translation services for notary and governance related matters.

We love to remain as a notary and continue contribute to onboarding more data onto Filecoin. Please kindly consider our request.

**Comment by raghavrmadya** [comment]
Thanks for the comments @BDE-io. Your points make sense to me and as you were an L2 notary, I would be willing to support your appeal. Are you able to provide evidence for point 2.?

**Comment by BDE-io** [comment]
@raghavrmadya Will respond to you privately with the names.

**Comment by raghavrmadya** [comment]
Thanks for the names @BDE-io. I'm willing to support your appeal.

**Comment by BDE-io** [comment]
@raghavrmadya thank you!
