### ISSUE TITLE
Proposal: Reform urgently needed on FIL+ program

### ISSUE THREAD

**Issue by brian75235** [filecoin-project/notary-governance#965]
It's evident that the current governance of the FIL+ program is one of the most dysfunctional governance systems we've witnessed in the blockchain space. It's marred by corruption, rife with unsolvable disputes, and at its core, plagued by inept management. The manifestations of this incompetence are as follows:

1. When disputes arise among notaries in the community, there exist good and bad notaries (some of the bad notaries are intentionally bad, while others are inadvertently so), as well as inactive notaries (these notaries might not have fulfilled their responsibilities due to various reasons over a certain period). Even a three-year-old child knows that the hierarchy of harm to the community should be ranked from greatest to least as follows: intentionally bad notaries > unintentionally bad notaries > inactive notaries. However, including individuals like RG among the governance personnel, the first step they take is to remove the least harmful inactive notaries, a significant portion of which are already active and engaged notaries, merely because they are the easiest to identify and deal with (RG claims that inactivity is unfair to diligent notaries – where does this notion of fairness come from? Notaries are volunteers; would any other notary consider inactive notaries unfair to themselves?!). Meanwhile, there's a delay in addressing intentionally or unintentionally malicious notaries, showcasing their utmost incompetence.

2. There's a complete lack of systematic approach to tasks. Be it in the process of removing inactive notaries or in dealing with existing LDN disputes, the employed procedures are haphazard and unplanned, exhibiting incompetence. For instance, RG has stated on multiple occasions that voting is an inefficient approach, which stems from his failure to meticulously devise a rational plan. Various proposals put forth in the community are not subjected to appropriate methods (such as sufficiently notifying everyone through the notary mail list); instead, they are hastily declared as "there is no major pushback, so we will..."

3. For a blockchain community, one needs really know about blockchain if he or she want to properly manage it. The proposals I have seen so far are almost disasters, for example, https://github.com/filecoin-project/notary-governance/issues/940 (which was already closed) and https://github.com/filecoin-project/notary-governance/issues/963 (currently open). These proposals are so badly drafted that they lack very basic thinking on what would happen once they are enforced. What's worse is that the authors of these proposals are self-satisfied and are not really listening to the communities' suggestions. One can see little hope to solve the challenges with this kind of management. 

Examples like these illustrate that this community's governance requires a substantial overhaul. We hope that the Filecoin Foundation and Protocol Labs can step forward and establish a legitimate, effective process to thoroughly rectify the current situation (which is currently chaotic and semi-paralyzed). My intention isn't to target any individual; rather, it's to elucidate the existing issues and we need to know where to make complaints. All discussions are welcome.

**Comment by joshua75235** [comment]
I have someone translate a Chinese version for me, since I know there are a lot of people in the community here do not read English so well. 

很明显，FIL+计划的当前治理是我们在区块链领域所见过的最不正常的治理系统之一。它被腐败所玷污，充斥着无法解决的争端，其核心是被无能的管理所困扰。这种无能表现为：
1. 当社区公证人之间发生纠纷时，公证人有好有坏（有些公证人是故意为之，有些则是无意为之），也有不积极的公证人（这些公证人可能由于各种原因在一定时期内没有履行自己的责任）。即使是一个三岁的孩子也知道，对社区造成伤害的等级应该从大到小排列如下：故意的坏公证人>无意的坏公证人>不活跃的公证人。然而，在治理人员中包括像RG这样的个人，他们采取的第一步是清除危害最小的不活跃公证人，其中很大一部分是已经活跃和参与的公证人，仅仅因为他们是最容易识别和处理的（RG声称不活跃对勤勉的公证人是不公平的——这一公平概念从何而来？公证人是自愿的，任何其他公证人会认为不活跃的公证人对自己不公平吗？与此同时，在处理有意或无意的恶意公证人时出现了延迟，这显示了他们的极度无能。
2. 对任务完全缺乏系统的方法。无论是在撤换不活跃的公证人的过程中，还是在处理现有的土地退化零增长争议时，所采用的程序都是随意和无计划的，表现出不称职。例如，RG曾在多个场合表示，投票是一种低效的方法，这源于他未能精心设计一个合理的计划。在社区中提出的各种建议没有经过适当的方法（例如通过公证人邮件名单充分通知每个人），而是匆忙宣布“没有重大阻力，所以我们将……”。
3. 对于区块链社区来说，如果他或她想要正确地管理它，他或她需要真正了解区块链。到目前为止，我看到的提案几乎都是灾难，例如，TT委员会提案#940（已经关闭）和提案：立即撤销公证人资格#963（目前开放）。这些提案起草得如此糟糕，以至于它们缺乏对一旦实施会发生什么的非常基本的思考。更糟糕的是，这些提案的作者自鸣得意，并没有真正听取社区的建议。人们几乎看不到用这种管理来解决挑战的希望。
像这样的例子表明，这个社区的治理需要进行重大的改革。我们希望Filecoin基金会和Protocol Labs能够站出来，建立一个合法、有效的流程来彻底纠正目前的情况（目前处于混乱和半瘫痪状态）。我的意图不是针对任何个人，而是阐明现有的问题，我们需要知道去哪里投诉。欢迎所有讨论。

**Comment by herrehesse** [comment]
I'm of the opinion that a significant overhaul of the FIL+ governance structure is necessary to effectively address and manage abuse. I wholeheartedly share your viewpoint on this matter.

However, where my perspective diverges is in your dismissal of the efforts put forth by the governance team, which includes @raghavrmadya , during this recent timeframe. While you're entitled to disagree, labeling their work as inept, perilous, and catastrophic isn't entirely just. It's essential to acknowledge that the group of active abusers involved in this program is remarkably toxic. I can personally attest to this, given that they've made repeated attempts to target us as well.

If you're going to criticize those who are genuinely striving to enhance this program, it would be more constructive to propose an alternative approach or set of guidelines for the FIL+ community. Without such a framework, your critique lacks the foundation required to be a substantial proposal in itself.

**Comment by brian75235** [comment]
If a city is filled with drug dealers, thief, and even murders, and the polices are still arresting people who are sleeping at home or who are late for their work, who will you blame? The bad guys, or the police?

If a government is filled with corrupted officers and citizens' daily life is badly affected, who will you blame? The corrupted officers, or the government or mayor who runs the city?

I am not on the payroll of Protocol Labs or Filecoin Foundation, I'm not even a notary, why it is MY responsibility to propose alternative approaches for a valid criticize? If they are working really hard to solve this, well, I appreciate their input. But they should work more smartly or have someone who really understand blockchain community to take over the work.

**Comment by herrehesse** [comment]
Agreeing with:

> Bad people are bad as they are, we need proper leadership, we need wise laws, we need carefully constructed standards to guide, to incentive, and to punish.

**Comment by raghavrmadya** [comment]
@brian75235 , thanks for creating a brand new github account to personally attack me. 

I would like to invite you to contribute to following discussions - https://github.com/filecoin-project/notary-governance/discussions/961

https://github.com/filecoin-project/notary-governance/discussions/841

Thank you

**Comment by brian75235** [comment]
Well, maybe thinking that I was attacking you personally is the key problem to begin with. I am simply stating the problems and the logic above, and it has nothing to do with whether this Github account is new or not. 

I have no intention to attack you, I am really sorry if I made you believe so. 

Do I hate you? Noooo, what you are doing has nothing to do with me personally and I have the least reason to hate you. 

Am I disappointed by the way you(the Fil+ team) work? Yes. The work flow and the proposals you put forward are so far not as satisfying or efficient as I would expect from a community manager for a big project like Filecoin. 

We deserve better, either from you or anyone who may replace you (to clarify, you here is not referring to anyone individual, but the Fil+ team)

**Comment by herrehesse** [comment]
Extremely valid point made:

> It seems anything related to the gov team has become a lose-lose situation these days. If the governance team proposes change, it's seen as coming from PL/FF or seen as too centralized. But if the governance team doesn't do anything, we're criticized for not addressing the issues.

**Comment by Chris00618** [comment]
Agree with @brian75235，it's well known that recent governance is very poor.
Highly recommended that this proposal as below should be urgently suspended as the result is a serious lack of the consent of most of the 88 notaries.
https://github.com/filecoin-project/notary-governance/issues/922

![image](https://github.com/filecoin-project/notary-governance/assets/105741726/bdeb9511-0738-4393-a1f0-451d260f7eb7)

**Comment by raghavrmadya** [comment]
@brian75235 , you are in conflict here - "When a city is falling down, most people (who are citizens) can only make complaints, because they do not have the capability or they are not at the position to propose/push forward anything specific."

EVERYONE has the ability to propose. You can propose suggestions. This very proposal is merely a rant and complaint

**Comment by raghavrmadya** [comment]
> Agree with @brian75235，it's well known that recent governance is very poor. Highly recommended that this proposal as below should be urgently suspended as the result is a serious lack of the consent of most of the 88 notaries. #922
> 
> ![image](https://user-images.githubusercontent.com/105741726/260992268-bdeb9511-0738-4393-a1f0-451d260f7eb7.png)

Stop gaslighting. I don't see pushback in the issue. No one is asking for consent here, either yours or that of notaries. This is not consent based governance. This is consensus based governance. 

Lack of dissent on a given proposal is consensus. You are welcome to propose alternatives

**Comment by raghavrmadya** [comment]
> It's evident that the current governance of the FIL+ program is one of the most dysfunctional governance systems we've witnessed in the blockchain space. It's marred by corruption, rife with unsolvable disputes, and at its core, plagued by inept management. The manifestations of this incompetence are as follows:
> 
> 1. When disputes arise among notaries in the community, there exist good and bad notaries (some of the bad notaries are intentionally bad, while others are inadvertently so), as well as inactive notaries (these notaries might not have fulfilled their responsibilities due to various reasons over a certain period). Even a three-year-old child knows that the hierarchy of harm to the community should be ranked from greatest to least as follows: intentionally bad notaries > unintentionally bad notaries > inactive notaries. However, including individuals like RG among the governance personnel, the first step they take is to remove the least harmful inactive notaries, a significant portion of which are already active and engaged notaries, merely because they are the easiest to identify and deal with (RG claims that inactivity is unfair to diligent notaries – where does this notion of fairness come from? Notaries are volunteers; would any other notary consider inactive notaries unfair to themselves?!). Meanwhile, there's a delay in addressing intentionally or unintentionally malicious notaries, showcasing their utmost incompetence.
> 2. There's a complete lack of systematic approach to tasks. Be it in the process of removing inactive notaries or in dealing with existing LDN disputes, the employed procedures are haphazard and unplanned, exhibiting incompetence. For instance, RG has stated on multiple occasions that voting is an inefficient approach, which stems from his failure to meticulously devise a rational plan. Various proposals put forth in the community are not subjected to appropriate methods (such as sufficiently notifying everyone through the notary mail list); instead, they are hastily declared as "there is no major pushback, so we will..."
> 3. For a blockchain community, one needs really know about blockchain if he or she want to properly manage it. The proposals I have seen so far are almost disasters, for example, [Proposal for T&T Committee #940](https://github.com/filecoin-project/notary-governance/issues/940) (which was already closed) and [Proposal: Qualifiers for immediate notary removal  #963](https://github.com/filecoin-project/notary-governance/issues/963) (currently open). These proposals are so badly drafted that they lack very basic thinking on what would happen once they are enforced. What's worse is that the authors of these proposals are self-satisfied and are not really listening to the communities' suggestions. One can see little hope to solve the challenges with this kind of management.
> 
> Examples like these illustrate that this community's governance requires a substantial overhaul. We hope that the Filecoin Foundation and Protocol Labs can step forward and establish a legitimate, effective process to thoroughly rectify the current situation (which is currently chaotic and semi-paralyzed). My intention isn't to target any individual; rather, it's to elucidate the existing issues and we need to know where to make complaints. All discussions are welcome.

@brian75235, I appreciate your comments here. FIP 003 intentionally gives notaries room for interpretation in due diligence. What you are suggesting from us is "detailed guidelines and rules to follow". I'm happy to provide you this and invest my time on this instead of [this](https://dataprograms.org/#section-projects) (which I believe is what we need to double down on, different topic tho). 


Instead of creating a proposal to rant and complain, i would suggest to drive a proposal to effectively delegate the notary duty to the governance team and I will have the detailed guidelines and rules to you within 2 weeks if such a proposal passes. 

You see, if any of us proposes this proposal, we will get gaslighted for plutocracy and if we take action against notaries, we get called out as well. 

So next step to reform Fil+ as you propose is to make a proposal, maybe by you, to give the ability to make rules to the governance team as you seem to be pushing for this. We can then encode these rules in a smart contract and get rid of all the problems.

**Comment by Chris00618** [comment]
1、You don't see pushback in the issue #922 . Why does kevinZ feedback that everyone's follow-up execution results are poor?
2、Whenever someone makes a suggestion you don't like,  why would your first reaction be to think they are attacking you or gaslighting you? it's not cool.

**Comment by brian75235** [comment]
> Instead of creating a proposal to rant and complain, i would suggest to drive a proposal to effectively delegate the notary duty to the governance team and I will have the detailed guidelines and rules to you within 2 weeks if such a proposal passes.

@raghavrmadya I agree with you that a valid proposal would be much better than this complaint (which I admit is what this proposal all about). Well, the problem is that I do not think I have the capability to propose a good one. Knowing something is not alright does not give me the ability to find ways to correct it, which is a pity though. 

In terms of "rules and guidelines", I would like to take one issue as example, the process of removing inactive notaries. Here is what I think could be a better way (I have limited time to figure this out, so there could be missing or mistaken parts) :
1. notify every notary through a mail list, warning that the inactive notaries are being noticed and subsequent measure may be taken. 
2. set and publish a standard to judge who will be identified as inactive notaries and in what procedure will this notary be removed
3. The chance of appeal should be taken into consideration. Warned notaries and file appeals, then what? How and who shall decide whether an appeal shall be accepted or rejected? By you, by other notaries, or by RKH? When will the appeal be solved? These should all be taken into consideration ahead of time so everyone can be convinced and follow the rules. 


I have to admit that community governing is a difficult job and sometimes even annoying. I do, at the same time, appreciate your hard working, as you are trying to do something that I do not dare to try and that I know I will not be good at. It's just I think the community may benefit more if you guys, as FIL+ governing team, could maybe change on how issues are taken care of.

**Comment by kevzak** [comment]
> 1、You don't see pushback in the issue #922 . Why does kevinZ feedback that everyone's follow-up execution results are poor? 2、Whenever someone makes a suggestion you don't like, why would your first reaction be to think they are attacking you or gaslighting you? it's not cool.

@Chris00618 can you clarify what you are saying here? I don't understand the statement. _Why does kevinZ feedback that everyone's follow-up execution results are poor?_

**Comment by Chris00618** [comment]
@kevzak   https://github.com/filecoin-project/notary-governance/discussions/966

![image](https://github.com/filecoin-project/notary-governance/assets/105741726/17597c66-966a-439f-82e2-d5222a69d153)

![image](https://github.com/filecoin-project/notary-governance/assets/105741726/b851bd34-009d-49d7-a3fe-c35cfb750560)

**Comment by kevzak** [comment]
@Chris00618 I'm seeing what I wrote and what RG wrote, but I'm still not sure I understand the point you are trying to make [here](https://github.com/filecoin-project/notary-governance/issues/965#issuecomment-1683140014)

**Comment by kevzak** [comment]
I'm going to close this proposal out. If someone has a proposal please open new a specific issue. Or if you'd like to continue a discussion, please open an issue under the discussion tab.
