### ISSUE TITLE
Discussion Mar 2 3pm UTC

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/notary-governance#97]
Hi all,

Per our calendar change a few weeks back - we have another Governance call slated for tomorrow at 3pm UTC.

Per usual, we'll be discussing open issues / PRs and any other agenda items flagged below. Please add items to the Github comments to add to the agenda.

Zoom details:
https://protocol.zoom.us/j/93414028246
Passcode: 554538

**Comment by dkkapur** [comment]
#94 - @jnthnvctr or @s0nik42 to discuss on call
#96 - @Fatman13 if you'd like to join the call to discuss, would be great to have you there!

**Comment by dkkapur** [comment]
#98

**Comment by Fatman13** [comment]
Will be there. Thank you for the invite!

**Comment by dkkapur** [comment]
call recording is available here: https://www.youtube.com/watch?v=OgkUhAF-O7U
