### ISSUE TITLE
[DataCap Removal Proposal for #1631]

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/notary-governance#971]
### Client Application URL or Application Number

1631

### Client Name

carelscholtens

### Client Address

f1mifv4bn6tsg6js7l4742nccbo5pdtdpgm2p6d5a

### Amount of DataCap to be removed

238TB

**Comment by CarelScholtens** [comment]
The specific reasons have been stated in the original application.

As we all know, the discussion that DC from the closed applications with low onboarding rate may be removed is still ongoing:
https://github.com/filecoin-project/notary-governance/issues/967
   
We all know this proposal is currently highly controversial and a lot of people are against it. Not sure if we're gonna agree on some points.

So why would you feel comfortable being impatient to submit such a proposal at the present time? Do you want to use controversy to raise awareness of your #967?

If you do have other motives, feel free to DM me and I'll do my best to come to your aid @cryptowhizzard

**Comment by Carohere** [comment]
According to T&T Dispute Tracker https://filecoin.notion.site/T-T-Dispute-Tracker-d28b93677cb544b48e77b585856601cf, these disputes are inconclusive till now, rushing to propose the removal of DC will only create more confusion and distress.

**Comment by herrehesse** [comment]
@Carohere This application is fully self-dealed and non retrievable? How you mean "inconclusive" ?
