### ISSUE TITLE
[DataCap Removal Proposal for 1689]

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/notary-governance#972]
### Client Application URL or Application Number

1689

### Client Name

WisseHeyne

### Client Address

f1anpyrkoyzqxsv3glkjsvdnyiols7p4cajtwax7a

### Amount of DataCap to be removed

202TB

**Comment by Carohere** [comment]
According to T&T Dispute Tracker https://filecoin.notion.site/T-T-Dispute-Tracker-d28b93677cb544b48e77b585856601cf, these disputes are inconclusive till now, rushing to propose the removal of DC will only create more confusion and distress.

**Comment by WisseHeyne** [comment]
have replied on the application. Thanks all.

**Comment by herrehesse** [comment]
@Carohere Are you going to copy-paste this response on all removal requests? I'd suggest you read the LDN and act properly.

**Comment by CorruptedPixels** [comment]
@herrehesse lol Isn't it the same with you and your friend? Copy-paste the same comment everywhere.

**Comment by herrehesse** [comment]
@CorruptedPixels, just to clarify, I'm not affiliated with PL. It's @Carohere who is. She should offer a more in depth response with details on LDNs.

**Comment by herrehesse** [comment]
Second to that, @Carohere has signed multiple "under dispute" LDN's and never properly responded to that misconduct.
