### ISSUE TITLE
[DataCap Removal Proposal #1608]

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/notary-governance#973]
### Client Application URL or Application Number

#1608

### Client Name

MiaAus

### Client Address

f1epywjw5mm4bihvttndrb35dymznxqpkevbnv36q

### Amount of DataCap to be removed

1908TB

**Comment by Carohere** [comment]
According to T&T Dispute Tracker https://filecoin.notion.site/T-T-Dispute-Tracker-d28b93677cb544b48e77b585856601cf, these disputes are inconclusive till now, rushing to propose the removal of DC will only create more confusion and distress.

**Comment by herrehesse** [comment]
@Carohere Again?
