### ISSUE TITLE
Modification: AC Bot v1.0 Launch Timeline & Process

### ISSUE THREAD

**Issue by ghost** [filecoin-project/notary-governance#989]
We are excited to launch the first verison of the Aggregation and Compliance (AC) Bot. The AC Bot is designed to automatically collect data from various sources within the Filecoin network and utilize this information to maintain adherence to the rules for DataCap distribution within the LDN and E-Fil+ pathways. For more information on the AC bot read these proposals:
- [issue 976](https://github.com/filecoin-project/notary-governance/issues/976)
- [issue 986](https://github.com/filecoin-project/notary-governance/issues/986)

The following issue highlights details of the AC bot launch in the upcoming weeks:
- Timeline: Schedule for the launch of AC Bot v1.0 as well as features being developed for future releases
- Process: How clients can ensure compliance to the AC Bot. If you are an existing client this section is important as there are items to be acted upon.

Note for notaries: Complying with the AC bot does not necessarily mean that they should qualify for another tranche of datacap. However, non-compliance is indicative of a breach of the Fil+ program standards.

### Initial launch of AC Bot v1.0

By **Friday Nov 24**, the initial version 1.0 of the AC bot will launch. This initial version of the AC bot will have the following functionality:
- Monitor criteria specified in [issue 986](https://github.com/filecoin-project/notary-governance/issues/986) and make informed decisions based on the thresholds form the 1-2 week period. 
- Every 3 days the AC Bot will be triggered to place warning comments on client issues that are past the third allocation and that do not comply with AC Bot v1.0. An example of such comment is as follows:
```
AC Bot: This is a warning that this client address has not complied with the following thresholds for the past X days:
  - The top storage provider for this client address is storing X% of the data. This is more than 75%, please store DataCap with other SPs to lower this percentage. 
  - X% of the CIDs stored by this client address are stored by another client address. This is more than 20%, please do not store CIDs that are already stored by other client addresses.
  - ...
Please do the above actions or this client address could be subjected to DataCap intervention
```
- Create snapshots of client behaviour after the warning. These snapshots will be analyzed and could be used for DataCap intervention in the future. Issue may be manually closed and DataCap may be removed depending on the analyzed behavior. 

### Features and integrations to be added to the AC bot after launch
- Automated issue closure
- Automated creation of proposals for DataCap removal 
- Integration with [JSON backend migration](https://github.com/filecoin-project/notary-governance/issues/839#issuecomment-1601951783)
- Open AC bot endpoint to integrate with other allocator pathways 

## Process

The following highlights requirements for clients to fulfill in order to comply with AC Bot.

### Compliance required at launch

Clients must meet the following criteria to comply with the AC Bot v1.0 at launch:

| metric | Threshold |
| -------- | -------- | 
| CID-checker score| >25% |
| Actual SP count after fourth allocation | >5 |
| Max percent data stored by top provider | <75% |
| Shared data percent | <20% |

In addition to the above thresholds, existing clients must also list all SPs associated with their application's client address. This list should be formatted as below and posted as a comment in the relevant issue:
```
[
{"providerID": "XYZ", "location": "XYZ",  "SPOrg","XYZ"}, 
{"providerID": "XYZ", "location": "XYZ",  "SPOrg","XYZ"}
]
```
### Required after the 8th week post launch 

After the 8th week from the launch, clients should adhere to the following standards:

| metric | Threshold | 
| -------- | -------- |
| CID-checker score | >95% |
| Retrieval Bot score | >75% |
| Claimed SP count | >5 |
| Actual SP count after fourth allocation | >5 |
| percent of actual SPs in claimed list | >100% | 
| KYC Check | 1 | 
| SP unique locations | 4 |
| Percent of properly replicated data | >75% |
| Max percent data stored by top provider | <35% |

Clients have to confirm their identity [here](https://filplus.storage/kyc) to fulfill the KYC requirement

**Comment by cryptoAmandaL** [comment]
Shared data percent | <20%
-- | --

can you please clarify this? thanks

**Comment by nicelove666** [comment]
I'm very happy, the AC robot is finally going online, I'm looking forward to it.

**Comment by nicelove666** [comment]
November 24th has arrived, has the robot started?

**Comment by psh0691** [comment]
Welcome to the launch of AC Bot.
I think automation will play a big role in pre-blocking and stabilizing the conflict elements of Fil+. 
Furthermore, we hope that the fundamental rules of Fil+, which have been continuously controversial, will be improved one by one.

**Comment by Filplus-govteam** [comment]
> Shared data percent	<20%
> can you please clarify this? thanks

@cryptoAmandaL Here is a link to a CID report example showing the section that measures shared data. https://github.com/data-preservation-programs/filplus-checker-assets/blob/main/filecoin-project/filecoin-plus-large-datasets/issues/1759/1694681102847.md#deal-data-shared-with-other-clients2

**Comment by Filplus-govteam** [comment]
> November 24th has arrived, has the robot started?

the bot initially gives a client a seven day grace period, so any notifications should be showing up later this week
