### ISSUE TITLE
v5 Notary Allocator Application: Tech Greedy Datacap Allocator

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/notary-governance#999]
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): Tech Greedy Datacap Allocator
3. Organization Name: Tech Greedy
4. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f1lubkhti5swayk6v25e47f3dtgwbudewrgncfr5y
5. Country of Operation (Where your organization is legally based): USA
6. Region of Operation (What region will you serve?): All regions
7. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Primarily automated, manual if necessary
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 200 PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment]
Hi @xinaxu 

Wanted to let you know this application has been received. Also verifying you have completed and submitted the Airtable form with your detailed Allocator plan - the public answers will be posted in a thread below soon. 

If you have any questions - please let me know.

**Comment by xinaxu** [comment]
Closing this one and will open a new one soon.

**Comment by Kevin-FF-USA** [comment]
Hi @xinaxu 
Was there a new Application filed in Github?   asking because I see the AIRTABLE form completed, but not a new GITHUB issue.  Reopening so this application doest get left behind

**Comment by xinaxu** [comment]
@Kevin-FF-USA Yes, it is #1024. There should be another airtable submission for that issue.

**Comment by Kevin-FF-USA** [comment]
Closing - Please see 24.
Thanks @xinaxu

**Comment by LucasLucas1987** [comment]
Hi Galen, @Kevin-FF-USA , @xinaxu and the official governance team and Filecoin community partners,

Thank you for your review. I am Lucas, a member of Xinaxu's TechGreedy team. Moving forward, the operation of the EasyOnboard Allocator will primarily be my responsibility, and I will also be the main point of contact for communication with the official governance team and the broader community. Xinaxu will continue to provide necessary technical support and guidance on Filecoin compliance operational rules.

For more details, please refer to the linked content (in October 2024, Xinaxu provided a comment explanation): [https://github.com/filecoin-project/notary-governance/issues/1024#issuecomment-2405737237](https://github.com/filecoin-project/notary-governance/issues/1024#issuecomment-2405737237)

Our allocator name is: **EasyOnboard Allocator**, and its operation mode is **manual**. My contact email is: lucas19870912@163.com.

We hope to receive official support, and we greatly appreciate it!

If you have any questions or need further information, please feel free to let us know. We look forward to continuing to contribute and support the growth and development of the community.

Best regards,  
Lucas

**Comment by LucasLucas1987** [comment]
**Please note that the application link for #1024 is the final version for the allocator application, and a comment has already been added.**

**Comment by xinaxu** [comment]
Cheer！ Lucas is new member of TechGreedy. He'll be responsible for operations and communications of EasyOnboard Allocator. Thank you for your support!
Relevant change request
https://github.com/filecoin-project/Allocator-Registry/issues/512

**Comment by LucasLucas1987** [comment]
Updation：

https://github.com/filecoin-project/Allocator-Registry/issues/513
https://github.com/filecoin-project/Allocator-Registry/issues/512
